Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#28ac83b4-5d97-4ae8-aa99-fcc9a7b2575e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Syvris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Al-Nasrl> <http://telicent.io/ontology/primaryName> "Al-Nasrl" .
<https://starwars.com#planet_Syvris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Al-Nasrl> .
<https://starwars.com#sector_Al-Nasrl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Syvris> <http://www.w3.org/2000/01/rdf-schema#comment> "Syvris was a small moon in the Outer Rim Territories region of the galaxy located at galactic coordinates T-13. It was part of the Triellus Trade Route, which connected it to the worlds Dubrava and Arami. Another hyperspace route connected it to the Hutt Space world of Hollastin. " .
<https://starwars.com#28ac83b4-5d97-4ae8-aa99-fcc9a7b2575e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Syvris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Syvris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#28ac83b4-5d97-4ae8-aa99-fcc9a7b2575e> .
<https://starwars.com#planet_Syvris> <http://telicent.io/ontology/primaryName> "Syvris" .
<https://starwars.com#sector_Al-Nasrl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Syvris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T13> .

