Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3646895b-08d2-42f7-8e2e-6064d880f5d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mrlsst"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mrlsst> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3646895b-08d2-42f7-8e2e-6064d880f5d9> .
<https://starwars.com#planet_Mrlsst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Mrlsst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Mrlsst> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mrlsst> <http://www.w3.org/2000/01/rdf-schema#comment> "Mrlsst was a location from which an artist hailed. The pirate captain Sidon Ithano, also known as the Crimson Corsair, owned a custom speeder with a custom chassis designed after his mask that was crafted by hand by the Mrlsst artist. " .
<https://starwars.com#3646895b-08d2-42f7-8e2e-6064d880f5d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mrlsst> <http://telicent.io/ontology/primaryName> "Mrlsst" .

