Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a3e7bdcb-e98d-4077-a6f6-7bc3f868c65f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_I20> <http://telicent.io/ontology/primaryName> "I20" .
<https://starwars.com#planet_Needan> <http://telicent.io/ontology/primaryName> "Needan" .
<https://starwars.com#planet_Needan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I20> .
<https://starwars.com#grid_I20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9a577934-1a6c-44bb-be7e-61c91bffb3ae> .
<https://starwars.com#a3e7bdcb-e98d-4077-a6f6-7bc3f868c65f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Needan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9a577934-1a6c-44bb-be7e-61c91bffb3ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Needan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#9a577934-1a6c-44bb-be7e-61c91bffb3ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_I20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Needan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a3e7bdcb-e98d-4077-a6f6-7bc3f868c65f> .
<https://starwars.com#planet_Needan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Needan> <http://www.w3.org/2000/01/rdf-schema#comment> "The Geelan survived the ensuing mass extinction of Needan's species by sheltering themselves inside dome-like habitats they constructed. Eventually, an Arcona-crewed medical starship picked up the Geelan distress signals, leading to a contact between the two species and a mass emigration of the Geelan from their doomed homeworld. " .

