Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Svolten> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Svolten> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#planet_Svolten> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Svolten> <http://telicent.io/ontology/primaryName> "Svolten" .
<https://starwars.com#8c630c50-9478-42e2-bbae-c08fd66af695> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Svolten"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8c630c50-9478-42e2-bbae-c08fd66af695> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Svolten> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Svolten> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8c630c50-9478-42e2-bbae-c08fd66af695> .

