Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ithor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .
<https://starwars.com#planet_Ithor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ithor> <http://www.w3.org/2000/01/rdf-schema#comment> "The Ithorian Jho left Ithor to settle on the planet Lothal, where he operated a cantina known as Old Jho's Pit Stop. At some point, an Ithorian rebel sympathizer named Momaw Nadon was forced to reveal the secrets of Ithorian agricultural technology to the Galactic Empire to save his homeworld from destruction. " .
<https://starwars.com#planet_Ithor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1ea2ebee-650b-4c22-9fb6-3538c7aba556> .
<https://starwars.com#sector_Ottega> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1ea2ebee-650b-4c22-9fb6-3538c7aba556> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ithor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ottega> .
<https://starwars.com#1ea2ebee-650b-4c22-9fb6-3538c7aba556> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ithor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ottega> <http://telicent.io/ontology/primaryName> "Ottega" .
<https://starwars.com#sector_Ottega> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Ithor> <http://telicent.io/ontology/primaryName> "Ithor" .

