Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ThonBoka> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#551b51b7-e0ad-4ced-abb1-a5c7fdb87c52> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_ThonBoka> <http://www.w3.org/2000/01/rdf-schema#comment> "The ThonBoka, also known as the ThonBoka Nebula, was a sack-shaped nebula in the Centrality full of gases, organic molecules, carapace creatures and interstellar plankton. Its name translated into Basic as 'StarCave Nebula.' It was home to the sentient Oswaft species, manta ray-like creatures that fed on the nutrients inside the ThonBoka. " .
<https://starwars.com#planet_ThonBoka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#551b51b7-e0ad-4ced-abb1-a5c7fdb87c52> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ThonBoka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#planet_ThonBoka> <http://telicent.io/ontology/primaryName> "ThonBoka" .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#551b51b7-e0ad-4ced-abb1-a5c7fdb87c52> <http://ies.data.gov.uk/ontology/ies4#representationValue> "ThonBoka"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ThonBoka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

