Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mustafar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L19> .
<https://starwars.com#sector_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#eb5cbbe3-32d4-434e-822c-89e5d3a5e7aa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mustafar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atravis> .
<https://starwars.com#planet_Mustafar> <http://telicent.io/ontology/primaryName> "Mustafar" .
<https://starwars.com#planet_Mustafar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mustafar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eb5cbbe3-32d4-434e-822c-89e5d3a5e7aa> .
<https://starwars.com#sector_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mustafar> <http://www.w3.org/2000/01/rdf-schema#comment> "Volcanic planet used by the Techno Union to mine for valuable materials. Hiding place of the Separatist Council during the final days of the Clone Wars, and the location of the duel between Anakin Skywalker and Obi-Wan Kenobi that results in the former's disfigurement. During the Imperial Era, it is the location of Darth Vader's personal stronghold. In the VR game Vader Immortal, it is revealed that Mustafar was once forested and very populous, but was left devastated by an ancient battle. It later begins to slowly heal itself, and, by the time of The Rise of Skywalker, trees appear to have regrown on Mustafar's surface." .
<https://starwars.com#eb5cbbe3-32d4-434e-822c-89e5d3a5e7aa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mustafar"^^<http://www.w3.org/2001/XMLSchema#string> .

