Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AlliedTion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Voss> <http://telicent.io/ontology/primaryName> "Voss" .
<https://starwars.com#planet_Voss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4b8b75ef-ecec-43d1-a0fc-06043086f27f> .
<https://starwars.com#planet_Voss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#4b8b75ef-ecec-43d1-a0fc-06043086f27f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_AlliedTion> <http://telicent.io/ontology/primaryName> "Allied Tion" .
<https://starwars.com#planet_Voss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4b8b75ef-ecec-43d1-a0fc-06043086f27f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Voss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Voss> <http://www.w3.org/2000/01/rdf-schema#comment> "When the galaxy was conquered by the Eternal Empire of Zakuul, the Voss and the Gormak ended their centuries long conflict and united in face of a larger threat. Voss Mystic Sana-Rae and Gormak warrior Rokuss traveled off-world to join the Alliance that opposed Zakuul and helped destroy the Star Fortress that dominated over Voss. Voss was later directly attacked by the Eternal Fleet, which destroyed the Shrine of Healing and dealt significant damage to Voss-Ka until the attack was repelled by the combined efforts of the Alliance, the Mandalorian warriors, and the Imperial fleet, though casualties still numbered in thousands. By the time of the Galactic Empire thousands of years later, Voss was controlled by the Tionese clans. " .
<https://starwars.com#planet_Voss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AlliedTion> .
<https://starwars.com#sector_AlliedTion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

