Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sharb> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#05adcdca-ef98-4904-a5b8-7603fef7b48e> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sharb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sharb> <http://telicent.io/ontology/primaryName> "Sharb" .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#05adcdca-ef98-4904-a5b8-7603fef7b48e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sharb"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#05adcdca-ef98-4904-a5b8-7603fef7b48e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sharb> <http://www.w3.org/2000/01/rdf-schema#comment> "Sharb was an astronomical object within the territory of the Chiss Ascendancy in the Unknown Regions. At one point, the Chiss Syndic Mitth'ras'safis received a report on crop projections for Sharb's northern hemisphere. " .
<https://starwars.com#planet_Sharb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#planet_Sharb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .

