Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#04cf298c-828d-4682-997b-52ad1328e070> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bendeluum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#04cf298c-828d-4682-997b-52ad1328e070> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bendeluum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bendeluum> <http://www.w3.org/2000/01/rdf-schema#comment> "Bendeluum was a planet in the Anoat sector of the Outer Rim Territories. The independent Nothoiin cartel criminal organization was based there. At the time of the Iron Blockade, gang wars broke out across Bendeluum, which disrupted business and endangered citizens. In an attempt to protect their shops, some merchants offered crystals to individuals who would quell the violence. " .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Bendeluum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#04cf298c-828d-4682-997b-52ad1328e070> .
<https://starwars.com#planet_Bendeluum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bendeluum> <http://telicent.io/ontology/primaryName> "Bendeluum" .
<https://starwars.com#planet_Bendeluum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

