Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cantros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Saijo> .
<https://starwars.com#planet_Cantros> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Cantros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J20> .
<https://starwars.com#sector_Saijo> <http://telicent.io/ontology/primaryName> "Saijo" .
<https://starwars.com#planet_Cantros> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3af35437-ef81-41ca-a31f-c714c6260fc2> .
<https://starwars.com#planet_Cantros> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3af35437-ef81-41ca-a31f-c714c6260fc2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cantros"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Saijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cantros> <http://telicent.io/ontology/primaryName> "Cantros" .
<https://starwars.com#3af35437-ef81-41ca-a31f-c714c6260fc2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Saijo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

