Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ruusan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e9eb371c-37a0-41a2-b348-0726339561e7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ruusan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P11> .
<https://starwars.com#planet_Ruusan> <http://www.w3.org/2000/01/rdf-schema#comment> "Barren planet housing the Valley of the Jedi. Site of a great battle between the Sith and the Jedi." .
<https://starwars.com#e9eb371c-37a0-41a2-b348-0726339561e7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ruusan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ruusan> <http://telicent.io/ontology/primaryName> "Ruusan" .
<https://starwars.com#planet_Ruusan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Teraab> .
<https://starwars.com#planet_Ruusan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e9eb371c-37a0-41a2-b348-0726339561e7> .
<https://starwars.com#sector_Teraab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Teraab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Teraab> <http://telicent.io/ontology/primaryName> "Teraab" .

