Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Oseon> <http://www.w3.org/2000/01/rdf-schema#comment> "Oseon was an astronomical object located in the Centrality, a sector of the galaxy's Outer Rim Territories. It was connected by the Sanity Skip hyperspace route to the planet Kessel and to Junkfort Station by another hyperspace route. The former pirate Queen Maz Kanata marked it as a point of interest on a map she included in the book that would become known as the Smuggler's Guide. " .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Oseon> <http://telicent.io/ontology/primaryName> "Oseon" .
<https://starwars.com#planet_Oseon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#b2f9fb00-8103-4174-b7de-ec9caeed0f49> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Oseon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Oseon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2f9fb00-8103-4174-b7de-ec9caeed0f49> .
<https://starwars.com#b2f9fb00-8103-4174-b7de-ec9caeed0f49> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Oseon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Oseon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

