Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shasfath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shasfath> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5099bbe2-dd09-4e8c-9d77-d7703ea0f0de> .
<https://starwars.com#planet_Shasfath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Shasfath> <http://telicent.io/ontology/primaryName> "Shasfath" .
<https://starwars.com#planet_Shasfath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J14> .
<https://starwars.com#5099bbe2-dd09-4e8c-9d77-d7703ea0f0de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shasfath"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shasfath> <http://www.w3.org/2000/01/rdf-schema#comment> "The Shasfath Cluster was an Inner Rim star cluster. Following the Imperial occupation of Cloud City on the planet Bespin in 3 ABY, the Rebel Alliance was forced to search for other sources of the important Tibanna gas. Alliance Captain Eedan therefore tasked a group of Rebel agents with surveying gas giant planets in several star systems, as well as in the Shasfath Cluster. The exploration of the star cluster eventually proved fruitless, and the Rebel scouts continued with their search on the planet Taloraan. " .
<https://starwars.com#5099bbe2-dd09-4e8c-9d77-d7703ea0f0de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

