Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Venzeiia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sarko> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c2ccc978-9e93-4223-8393-a3e1f6337129> .
<https://starwars.com#c2ccc978-9e93-4223-8393-a3e1f6337129> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sarko"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Venzeiia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Sarko> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Venzeiia> .
<https://starwars.com#planet_Sarko> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#sector_Venzeiia> <http://telicent.io/ontology/primaryName> "Venzeiia" .
<https://starwars.com#planet_Sarko> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sarko> <http://www.w3.org/2000/01/rdf-schema#comment> "Sarko was a male Human bounty hunter who tried to capture Quinlan Vos on Ord Mantell in 30 BBY. " .
<https://starwars.com#planet_Sarko> <http://telicent.io/ontology/primaryName> "Sarko" .
<https://starwars.com#c2ccc978-9e93-4223-8393-a3e1f6337129> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

