Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Skynara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8fb53ac7-8df9-46f1-a43b-b1c3cb3a0750> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Skine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Skynara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P19> .
<https://starwars.com#sector_Skine> <http://telicent.io/ontology/primaryName> "Skine" .
<https://starwars.com#sector_Skine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#8fb53ac7-8df9-46f1-a43b-b1c3cb3a0750> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skynara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Skynara> <http://www.w3.org/2000/01/rdf-schema#comment> "Skynara was an astronomical object located in the Outer Rim Territories and Trailing Sectors, positioned at the coordinates P-19 on the Standard Galactic Grid. Skynara was located on a hyperspace route that branched to Spice Terminus, Suarbi and Vohai. " .
<https://starwars.com#planet_Skynara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Skine> .
<https://starwars.com#planet_Skynara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8fb53ac7-8df9-46f1-a43b-b1c3cb3a0750> .
<https://starwars.com#planet_Skynara> <http://telicent.io/ontology/primaryName> "Skynara" .

