Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kloper> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cd18841c-2b46-4ee5-8968-6d0ed8fb213c> .
<https://starwars.com#planet_Kloper> <http://telicent.io/ontology/primaryName> "Kloper" .
<https://starwars.com#planet_Kloper> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#cd18841c-2b46-4ee5-8968-6d0ed8fb213c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kloper"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kloper> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Kloper> <http://www.w3.org/2000/01/rdf-schema#comment> "Kloper was a New Republic member planet, and the homeworld of the Kloperian species. " .
<https://starwars.com#cd18841c-2b46-4ee5-8968-6d0ed8fb213c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kloper> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .

