Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f3b090d7-d53b-4d69-aad3-f90c0de4424e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Angratha> <http://telicent.io/ontology/primaryName> "Angratha" .
<https://starwars.com#planet_Angratha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Angratha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a8b6a82-5193-496d-bf36-c0536b598493> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_L18> <http://telicent.io/ontology/primaryName> "L18" .
<https://starwars.com#f3b090d7-d53b-4d69-aad3-f90c0de4424e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Angratha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#1a8b6a82-5193-496d-bf36-c0536b598493> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Angratha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f3b090d7-d53b-4d69-aad3-f90c0de4424e> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Angratha> <http://www.w3.org/2000/01/rdf-schema#comment> "Angratha was a Mid Rim planet located in the Senex sector. " .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Angratha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#1a8b6a82-5193-496d-bf36-c0536b598493> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

