Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Sprizen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Abafar> <http://www.w3.org/2000/01/rdf-schema#comment> "A desert planet located in the Outer Rim with a completely white surface. Known as The Void, the planet is barely populated but is home to massive amounts of rhydonium, a scarce and volatile fuel." .
<https://starwars.com#sector_Sprizen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Sprizen> <http://telicent.io/ontology/primaryName> "Sprizen" .
<https://starwars.com#grid_N5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#36dbcd8f-0390-46b2-8151-6c39f68d8b03> .
<https://starwars.com#planet_Abafar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2655fac-4941-4cc2-9538-ba69d45468f3> .
<https://starwars.com#planet_Abafar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sprizen> .
<https://starwars.com#planet_Abafar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#36dbcd8f-0390-46b2-8151-6c39f68d8b03> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Abafar> <http://telicent.io/ontology/primaryName> "Abafar" .
<https://starwars.com#a2655fac-4941-4cc2-9538-ba69d45468f3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_N5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#36dbcd8f-0390-46b2-8151-6c39f68d8b03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#a2655fac-4941-4cc2-9538-ba69d45468f3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abafar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Abafar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N5> .
<https://starwars.com#grid_N5> <http://telicent.io/ontology/primaryName> "N5" .
<https://starwars.com#grid_N5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

