Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_UR-2650> <http://telicent.io/ontology/primaryName> "UR-2650" .
<https://starwars.com#abe891d1-c994-4c07-b092-16884701a3fe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "UR-2650"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_UR-2650> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#abe891d1-c994-4c07-b092-16884701a3fe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_UR-2650> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_UR-2650> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#abe891d1-c994-4c07-b092-16884701a3fe> .
<https://starwars.com#planet_UR-2650> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_UR-2650> <http://www.w3.org/2000/01/rdf-schema#comment> "UR-2650 was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It shared a similar designation to the nearby UR-1060, UR-3741, UR-8827, and UR-9353. UR-2650 was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .

