Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Feena> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Feena> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Feena> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca9bd994-4129-40af-9adc-8873a6520022> .
<https://starwars.com#ca9bd994-4129-40af-9adc-8873a6520022> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Feena"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Feena> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Feena> <http://telicent.io/ontology/primaryName> "Feena" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Feena> <http://www.w3.org/2000/01/rdf-schema#comment> "Feena was a world located in the Feena system. It was situated in the Back Reach area of the Gordian Reach sector, within the Trans-Hydian portion of the Outer Rim Territories. Feena lay between the B'trilla and Kalishik systems on the hyperlane known as the Ardan Cross—a portion of which already linked it to the Ethain and Vynx systems by 25,126 BBY—while the Feena Run hyperspace route connected the world to the Barison system. " .
<https://starwars.com#ca9bd994-4129-40af-9adc-8873a6520022> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

