Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalarba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalarba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bf1d64f5-3b48-4978-8a6d-f092d4dbb526> .
<https://starwars.com#sector_Hevvrol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Hevvrol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Hevvrol> <http://telicent.io/ontology/primaryName> "Hevvrol" .
<https://starwars.com#planet_Kalarba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#bf1d64f5-3b48-4978-8a6d-f092d4dbb526> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalarba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#bf1d64f5-3b48-4978-8a6d-f092d4dbb526> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kalarba> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalarba was a planet located in the galaxy's Mid Rim. It was orbited by multiple moons, including one that had the Imperial space station Hosk Station built entirely around its surface. During the Galactic Civil War, the Ishi Tib pilot Sata Neek claimed that he and the Alliance to Restore the Republic RZ-1 A-wing interceptor squadron designated Riot Squadron and its commanding officer Creel had searched for a rebel base on Kalarba for six hours before realizing that Creel had mistaken a flight simulator mission for a set of redeployment orders. His squadron mate Kamala disputed the truth of this story. " .
<https://starwars.com#planet_Kalarba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hevvrol> .
<https://starwars.com#planet_Kalarba> <http://telicent.io/ontology/primaryName> "Kalarba" .

