Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brevost> .
<https://starwars.com#planet_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#sector_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#313551b6-0fa2-4884-b84e-a92d868aad33> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#313551b6-0fa2-4884-b84e-a92d868aad33> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Brevost"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Brevost> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#313551b6-0fa2-4884-b84e-a92d868aad33> .
<https://starwars.com#sector_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Brevost> <http://www.w3.org/2000/01/rdf-schema#comment> "Brevost was a planet in the Brevost system of the Expansion Region. It was on the Harrin Trade Corridor between the Krann system and the Cerenia system. " .

