Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Pinperu> <http://telicent.io/ontology/primaryName> "Pinperu" .
<https://starwars.com#99a93a08-f9bb-4886-ab4e-b820d94ad6ce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pinperu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pinperu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pinperu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pinperu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#99a93a08-f9bb-4886-ab4e-b820d94ad6ce> .
<https://starwars.com#planet_Pinperu> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Pinperu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#99a93a08-f9bb-4886-ab4e-b820d94ad6ce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

