Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f9190a84-b01c-4b63-b07a-aae844606642> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Takodana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Takodana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#f9190a84-b01c-4b63-b07a-aae844606642> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Takodana> <http://www.w3.org/2000/01/rdf-schema#comment> "Forest planet and site of Maz Kanata's castle. Neutral territory between First Order and Resistance." .
<https://starwars.com#planet_Takodana> <http://telicent.io/ontology/primaryName> "Takodana" .
<https://starwars.com#planet_Takodana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J16> .
<https://starwars.com#planet_Takodana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Takodana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f9190a84-b01c-4b63-b07a-aae844606642> .

