Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kassido> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#e5e08942-3896-4aa9-b150-d370cbf4e20f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kassido> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Kassido> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kassido> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e5e08942-3896-4aa9-b150-d370cbf4e20f> .
<https://starwars.com#e5e08942-3896-4aa9-b150-d370cbf4e20f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kassido"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kassido> <http://telicent.io/ontology/primaryName> "Kassido" .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kassido> <http://www.w3.org/2000/01/rdf-schema#comment> "Kassido was a terrestrial world located in the Kassido system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. The Senex-Juvex Loop hyperlane linked it to the Manforgon and Ossiathora systems, while the Kassido Bypass and the D'Aelgoth Trade Route connected it to the Yhifar system and the D'Aelgoth sector's Selenius system, respectively. " .

