Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tholatin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7aecad8d-2170-400c-8bf1-7a8b422a0081> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Tholatin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tholatin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#7aecad8d-2170-400c-8bf1-7a8b422a0081> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tholatin> <http://telicent.io/ontology/primaryName> "Tholatin" .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Tholatin> <http://www.w3.org/2000/01/rdf-schema#comment> "Tholatin was a planet located within the Tholatin system of the Mid Rim. It was the location of Esau's Ridge, a thin crevasse in a towering rock wall inhabited by smugglers. The planet's chief of security was Plaan in 25 ABY. Tholatin was conquered by the Yuuzhan Vong some time during the latter's onslaught into the galaxy. The planet was eventually liberated from the invaders by the Mandalorian Protectors under Boba Fett in 29 ABY. " .
<https://starwars.com#planet_Tholatin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#7aecad8d-2170-400c-8bf1-7a8b422a0081> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tholatin"^^<http://www.w3.org/2001/XMLSchema#string> .

