Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ulmatra> <http://telicent.io/ontology/primaryName> "Ulmatra" .
<https://starwars.com#52773d22-10aa-4bdf-8f3e-b5f4e8e6708e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Ulmatra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ulmatra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#52773d22-10aa-4bdf-8f3e-b5f4e8e6708e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ulmatra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ulmatra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ulmatra> <http://www.w3.org/2000/01/rdf-schema#comment> "Ulmatra was an astronomical object located in the galaxy that was connected to Randa, in the Kessel sector, by hyperspace route. It was also where the Hutt crime lord Durga was based. " .
<https://starwars.com#planet_Ulmatra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#52773d22-10aa-4bdf-8f3e-b5f4e8e6708e> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

