Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mshinni> <http://telicent.io/ontology/primaryName> "M'shinni" .
<https://starwars.com#planet_Genassa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7492c75d-cd1a-4dbf-ac94-aba9c7613152> .
<https://starwars.com#7492c75d-cd1a-4dbf-ac94-aba9c7613152> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Genassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mshinni> .
<https://starwars.com#planet_Genassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_Genassa> <http://telicent.io/ontology/primaryName> "Genassa" .
<https://starwars.com#sector_Mshinni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Genassa> <http://www.w3.org/2000/01/rdf-schema#comment> "Genassa was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Genassa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Mshinni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#7492c75d-cd1a-4dbf-ac94-aba9c7613152> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Genassa"^^<http://www.w3.org/2001/XMLSchema#string> .

