Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Telaris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1386a439-be82-40f0-bfc6-93e8253ea706> .
<https://starwars.com#planet_Telaris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Telaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#planet_Telaris> <http://www.w3.org/2000/01/rdf-schema#comment> "Telaris was a location in the Telaris system. During the early rebellion against the Galactic Empire, the Alliance to Restore the Republic utilized the UT-60D U-wing starfighter/support craft as a cargo and VIP escort between Mon Cala and Telaris. The information was on a report that was later incorporated into The Rebel Files. " .
<https://starwars.com#1386a439-be82-40f0-bfc6-93e8253ea706> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Telaris> <http://telicent.io/ontology/primaryName> "Telaris" .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#planet_Telaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#1386a439-be82-40f0-bfc6-93e8253ea706> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Telaris"^^<http://www.w3.org/2001/XMLSchema#string> .

