Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ganthel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9acb4454-27fd-4e2e-8d4e-abfbea5d0660> .
<https://starwars.com#planet_Ganthel> <http://telicent.io/ontology/primaryName> "Ganthel" .
<https://starwars.com#planet_Ganthel> <http://www.w3.org/2000/01/rdf-schema#comment> "Ganthel was a planet located in the galaxy's Core Worlds. A species of beetles known as night-beetles inhabited Ganthel's outback. It was an industrial world, with many shipyards and loading docks, of which commonly exported kelerium in large crates.  The spice- and slavery-dealing criminal group Kotaska operated on the planet until the Galactic Empire arrived and dismantled them, along with some other criminal elements. The native Human female Rae Sloane, who was young and unwealthy at the time, longed to leave the world for a richer and greener one. Eventually attaining much prestige within the Imperial ranks, she estimated that Baron Lero Danthe spent more time in his suit than her family had spent in their house on Ganthel. " .
<https://starwars.com#planet_Ganthel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9acb4454-27fd-4e2e-8d4e-abfbea5d0660> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ganthel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#9acb4454-27fd-4e2e-8d4e-abfbea5d0660> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ganthel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ganthel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .

