Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e4e71d7c-f7ad-4c69-b52a-dc2c801d6e9d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thrakia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thrakia> <http://www.w3.org/2000/01/rdf-schema#comment> "Thrakia was a planet with large land masses and rich in natural resources located in the Hapes Cluster. It was the homeworld of the Thrakians, an intelligent insect species. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thrakia> <http://telicent.io/ontology/primaryName> "Thrakia" .
<https://starwars.com#planet_Thrakia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thrakia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Thrakia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e4e71d7c-f7ad-4c69-b52a-dc2c801d6e9d> .
<https://starwars.com#planet_Thrakia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#e4e71d7c-f7ad-4c69-b52a-dc2c801d6e9d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

