Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KarstensWorld> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#96de8fb1-9aaa-4105-aecb-29610bab6d67> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KarstensWorld> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#96de8fb1-9aaa-4105-aecb-29610bab6d67> .
<https://starwars.com#planet_KarstensWorld> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KarstensWorld> <http://telicent.io/ontology/primaryName> "Karsten's World" .
<https://starwars.com#96de8fb1-9aaa-4105-aecb-29610bab6d67> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karsten's World"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KarstensWorld> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KarstensWorld> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

