Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Crovna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Crovna> <http://telicent.io/ontology/primaryName> "Crovna" .
<https://starwars.com#14b2dddc-abdb-446b-a205-5429730788a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Crovna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Crovna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#14b2dddc-abdb-446b-a205-5429730788a3> .
<https://starwars.com#planet_Crovna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#14b2dddc-abdb-446b-a205-5429730788a3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Crovna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Crovna> <http://www.w3.org/2000/01/rdf-schema#comment> "Crovna was a planet in Senex sector that was home to the Peven Auction House; and Birtraub Brothers Storage and Reclamation Center, located near the main spaceport on the planet, which was a front for the Birtraub Brothers' criminal activities. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

