Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5f360415-cc2a-4810-b46f-5da1b721a89b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Listehol"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Listehol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Listehol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Listehol> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5f360415-cc2a-4810-b46f-5da1b721a89b> .
<https://starwars.com#sector_Kwymar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kwymar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Listehol> <http://telicent.io/ontology/primaryName> "Listehol" .
<https://starwars.com#planet_Listehol> <http://www.w3.org/2000/01/rdf-schema#comment> "Listehol was an astronomical object located in the galaxy's Outer Rim Territories. Located on the Hydian Way, it was also connected to Mirial by another hyperspace route. It was the homeworld of the tyrant Baron Yasto Attsmun, captain of the Undisputed Victor on Cantonica. " .
<https://starwars.com#sector_Kwymar> <http://telicent.io/ontology/primaryName> "Kwymar" .
<https://starwars.com#5f360415-cc2a-4810-b46f-5da1b721a89b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Listehol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kwymar> .

