Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ce33d034-8762-465b-8255-c96a27d6283c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lialic"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lialic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#ce33d034-8762-465b-8255-c96a27d6283c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lialic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Lialic> <http://www.w3.org/2000/01/rdf-schema#comment> "Lialic was an astronomical object located in the regions known as the Deep Core and the Interior. It was also situated in the grid square K-12 of the Standard Galactic Grid. " .
<https://starwars.com#planet_Lialic> <http://telicent.io/ontology/primaryName> "Lialic" .
<https://starwars.com#planet_Lialic> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce33d034-8762-465b-8255-c96a27d6283c> .
<https://starwars.com#planet_Lialic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

