Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NearIndosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_NearIndosa> <http://www.w3.org/2000/01/rdf-schema#comment> "Near Indosa was a mining planet that was situated in the north-eastern quadrant of the galaxy and located within the Near Indosa system on the Junction-Tierell Loop hyperlane. The hyperlane was situated in the Gordian Reach sector of the Outer Rim Territories. Near Indosa had been heavily excavated by miners for millennia, which was the reason why most of the planet's mineral resources almost completely disappeared. It was also the reason that many of the miners went to the Far Indosa system during the last days of the Galactic Republic. " .
<https://starwars.com#planet_NearIndosa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#118467d9-2759-40a5-b1a7-4cb195fb2906> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_NearIndosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_NearIndosa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#118467d9-2759-40a5-b1a7-4cb195fb2906> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NearIndosa> <http://telicent.io/ontology/primaryName> "Near Indosa" .
<https://starwars.com#118467d9-2759-40a5-b1a7-4cb195fb2906> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Near Indosa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

