Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Seoul> <http://www.w3.org/2000/01/rdf-schema#comment> "Seoul was an astronomical object located in the galaxy's Wild Space. " .
<https://starwars.com#f6aba7bf-2f20-48da-b36f-c99787e2cd8e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Seoul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f6aba7bf-2f20-48da-b36f-c99787e2cd8e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Seoul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Seoul> <http://telicent.io/ontology/primaryName> "Seoul" .
<https://starwars.com#planet_Seoul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Seoul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f6aba7bf-2f20-48da-b36f-c99787e2cd8e> .
<https://starwars.com#planet_Seoul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H20> .

