Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Terrskiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Terrskiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_TornStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#91647038-3be0-4db0-bd9b-0224b2a067a7> .
<https://starwars.com#91647038-3be0-4db0-bd9b-0224b2a067a7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Torn Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Terrskiar> <http://telicent.io/ontology/primaryName> "Terr'skiar" .
<https://starwars.com#planet_TornStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#planet_TornStation> <http://telicent.io/ontology/primaryName> "Torn Station" .
<https://starwars.com#91647038-3be0-4db0-bd9b-0224b2a067a7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TornStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Terrskiar> .
<https://starwars.com#planet_TornStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Torn Station was a space station located in a star system within the Mytaranor sector. The sector was part of the Kashyyyk Region in the Slice section of the Mid Rim. The station was connected to the Kashyyyk and Quas Killam systems through the hyperlane known as the Great Kashyyyk Branch. " .
<https://starwars.com#planet_TornStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

