Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KunasFist> <http://telicent.io/ontology/primaryName> "Kuna's Fist" .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KunasFist> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KunasFist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_KunasFist> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#657e9b91-ac96-4409-93ff-2ffc24ce0503> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#657e9b91-ac96-4409-93ff-2ffc24ce0503> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KunasFist> <http://www.w3.org/2000/01/rdf-schema#comment> "Kuna's Fist was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. Hyperspace routes linked it to the celestial bodies Kuna's Eye, Kuna's Horn, and Kuna's Tail. Kuna's Fist was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_KunasFist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#657e9b91-ac96-4409-93ff-2ffc24ce0503> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuna's Fist"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

