Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ea5059e4-0db6-4255-8c1d-bf1f03d68d93> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Trianii> <http://telicent.io/ontology/primaryName> "Trianii" .
<https://starwars.com#planet_Ekibo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#planet_Ekibo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ea5059e4-0db6-4255-8c1d-bf1f03d68d93> .
<https://starwars.com#ea5059e4-0db6-4255-8c1d-bf1f03d68d93> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ekibo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ekibo> <http://www.w3.org/2000/01/rdf-schema#comment> "Ekibo was a Trianii colony planet in Trianii Space, famous for its farms and herdbeasts. Trianii Rangers Atuarre and Keeheen were responsible for overthrowing a herdbeast-rustling ring there. " .
<https://starwars.com#sector_Trianii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ekibo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trianii> .
<https://starwars.com#planet_Ekibo> <http://telicent.io/ontology/primaryName> "Ekibo" .
<https://starwars.com#planet_Ekibo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Trianii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .

