Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Draukyze> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Draukyze> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Draukyze> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a306965e-3e8e-456f-9dba-18e897fc024e> .
<https://starwars.com#sector_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Draukyze> <http://telicent.io/ontology/primaryName> "Draukyze" .
<https://starwars.com#planet_Draukyze> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thanium> .
<https://starwars.com#sector_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#planet_Draukyze> <http://www.w3.org/2000/01/rdf-schema#comment> "Draukyze was a planet in the Draukyze system of the Thanium sector. " .
<https://starwars.com#sector_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#a306965e-3e8e-456f-9dba-18e897fc024e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a306965e-3e8e-456f-9dba-18e897fc024e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Draukyze"^^<http://www.w3.org/2001/XMLSchema#string> .

