Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Geonosis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e30027cd-8c90-4d59-8383-958a863601fc> .
<https://starwars.com#planet_Geonosis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#e30027cd-8c90-4d59-8383-958a863601fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Geonosis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Geonosis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Geonosis> <http://telicent.io/ontology/primaryName> "Geonosis" .
<https://starwars.com#planet_Geonosis> <http://www.w3.org/2000/01/rdf-schema#comment> "Rocky desert planet where battle droids are manufactured, and the site of the opening battle of the Clone Wars. All life on the planet is presumed destroyed by the Empire in Star Wars Rebels, with two exceptions: Klik-Klak and his offspring. Primary construction site of the first Death Star. Homeworld of the Geonosians." .
<https://starwars.com#e30027cd-8c90-4d59-8383-958a863601fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Geonosis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

