Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Archais> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Archais> <http://www.w3.org/2000/01/rdf-schema#comment> "Archais was a planet in the Interior Region of the Hapes Cluster. Sometime before 2 ABY, Imperial lieutenant colonel Freja Covell and the Assassin's Guild fought three Rebel SpecForces units in the oriental seas of Archais during the battle of Archais. It was believed to be the site of mythical mountain peaks that were very high. On occasion, reference was made to these peaks as a form of hyperbole, such as the suggestion that if Moff Bandor's ambition were height, it would tower over the peaks. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Archais> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Archais> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#7048f64b-d0eb-45f1-808a-0825bd1afa83> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Archais"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Archais> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7048f64b-d0eb-45f1-808a-0825bd1afa83> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Archais> <http://telicent.io/ontology/primaryName> "Archais" .
<https://starwars.com#7048f64b-d0eb-45f1-808a-0825bd1afa83> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

