Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L12> <http://telicent.io/ontology/primaryName> "L12" .
<https://starwars.com#planet_Azbrian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Azbrian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#64af5253-32ba-4e7c-81df-c43f56df84f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#64af5253-32ba-4e7c-81df-c43f56df84f1> .
<https://starwars.com#grid_L12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#e179a224-b376-4968-87a1-84a6c242f832> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Azbrian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Azbrian> <http://www.w3.org/2000/01/rdf-schema#comment> "Azbrian was an agricultural world of sweeping plains and grasslands, dotted with farms that raised the eight-legged herd animals known as dray beasts. One such farm was owned by Condren Foreck, a potential suitor to Lando Calrissian. It played a minor part in the Yuuzhan Vong War as a base for the New Republic/Galactic Alliance. After the war the Galactic Alliance abandoned the base. It was never a part of the Alliance until after the war. The Prime Minister of the planet decided to join the Alliance, so he sent two senators to Coruscant to the Galactic Alliance Senate. The planet turned out to be valuable during the Second Galactic Civil War. " .
<https://starwars.com#e179a224-b376-4968-87a1-84a6c242f832> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Azbrian> <http://telicent.io/ontology/primaryName> "Azbrian" .
<https://starwars.com#planet_Azbrian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Azbrian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e179a224-b376-4968-87a1-84a6c242f832> .
<https://starwars.com#64af5253-32ba-4e7c-81df-c43f56df84f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

