Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Baroli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .
<https://starwars.com#planet_Baroli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7f54e744-51b7-480d-b4fc-90b6c1aa4eb7> .
<https://starwars.com#planet_Baroli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7f54e744-51b7-480d-b4fc-90b6c1aa4eb7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Baroli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Baroli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baroli> .
<https://starwars.com#sector_Baroli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#7f54e744-51b7-480d-b4fc-90b6c1aa4eb7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Baroli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Baroli> <http://telicent.io/ontology/primaryName> "Baroli" .
<https://starwars.com#planet_Baroli> <http://www.w3.org/2000/01/rdf-schema#comment> "Baroli was the homeworld of the Barolian pilots Jano Brayson and Teff. Around 231 BBY, when the two reunited on the Starlight Beacon space station after becoming Z-29 Skyhawk pilots in the Galactic Republic's Firebird Squadron, Teff commented that they were a long way from Baroli, which Brayson agreed with. " .
<https://starwars.com#planet_Baroli> <http://telicent.io/ontology/primaryName> "Baroli" .

