Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Copperline> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Copperline> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vatha> .
<https://starwars.com#planet_Copperline> <http://www.w3.org/2000/01/rdf-schema#comment> "Copperline was a world of poor farmers that was plagued by pirates for decades. In 18 BBY, the Imperial Navy and Army, including at least one unit of stormtroopers, cleaned out the pirates in a five-month-long operation. " .
<https://starwars.com#sector_Vatha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Copperline> <http://telicent.io/ontology/primaryName> "Copperline" .
<https://starwars.com#69f5c2e3-0f0f-4362-8b1d-43b9dc079cc1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Copperline"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Vatha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#69f5c2e3-0f0f-4362-8b1d-43b9dc079cc1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Copperline> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#69f5c2e3-0f0f-4362-8b1d-43b9dc079cc1> .
<https://starwars.com#planet_Copperline> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#sector_Vatha> <http://telicent.io/ontology/primaryName> "Vatha" .

