Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cf52a82a-3c4c-465b-90aa-abe6c69fccf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RunawayPrince> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_RunawayPrince> <http://telicent.io/ontology/primaryName> "Runaway Prince" .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_RunawayPrince> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R11> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_RunawayPrince> <http://www.w3.org/2000/01/rdf-schema#comment> "Runaway Prince, called Lordunkee Wanpolla in Huttese, was an uninhabited planet in Hutt Space which the Hutts gave to the Yuuzhan Vong. The origin of its peculiar name was lost in history. " .
<https://starwars.com#cf52a82a-3c4c-465b-90aa-abe6c69fccf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Runaway Prince"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RunawayPrince> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RunawayPrince> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf52a82a-3c4c-465b-90aa-abe6c69fccf0> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

