Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Parnabe> <http://telicent.io/ontology/primaryName> "Parnabe" .
<https://starwars.com#planet_QatChrystac> <http://telicent.io/ontology/primaryName> "Qat Chrystac" .
<https://starwars.com#planet_QatChrystac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_QatChrystac> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Parnabe> .
<https://starwars.com#planet_QatChrystac> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#312407e5-7702-40ac-8992-0e6847008939> .
<https://starwars.com#planet_QatChrystac> <http://www.w3.org/2000/01/rdf-schema#comment> "Qat Chrystac was an astronomical object located in the galaxy's Expansion Region. " .
<https://starwars.com#312407e5-7702-40ac-8992-0e6847008939> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Parnabe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#312407e5-7702-40ac-8992-0e6847008939> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Qat Chrystac"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Parnabe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_QatChrystac> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L16> .

