Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thracior> <http://www.w3.org/2000/01/rdf-schema#comment> "Thracior was a planet located within the Thracior system of the Core Worlds. The planet was ruled by tribal Warlords. Wars would periodically take place amongst the clans. Rival clans forbade interclan marriage, which could subject to capital punishment. The two best known tribes were Hnsi and Tantt. " .
<https://starwars.com#planet_Thracior> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thracior> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b53ad25e-1bcd-4b73-be71-99d39ec48487> .
<https://starwars.com#planet_Thracior> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Thracior> <http://telicent.io/ontology/primaryName> "Thracior" .
<https://starwars.com#planet_Thracior> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#b53ad25e-1bcd-4b73-be71-99d39ec48487> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thracior"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b53ad25e-1bcd-4b73-be71-99d39ec48487> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

