Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tothis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#976d1e42-ec39-4250-9a76-045d0a7ad326> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tothis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tothis> <http://telicent.io/ontology/primaryName> "Tothis" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tothis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Tothis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#976d1e42-ec39-4250-9a76-045d0a7ad326> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tothis> <http://www.w3.org/2000/01/rdf-schema#comment> "Tothis was a middling industrial planet located in the Tothis system of the Corporate Sector. " .
<https://starwars.com#planet_Tothis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#976d1e42-ec39-4250-9a76-045d0a7ad326> .

