Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yalara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d62fb92b-9ec5-4b27-b306-3b5f2347452b> .
<https://starwars.com#planet_Yalara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_I21> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_I21> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e127b484-f6b1-4f71-a4a7-6d74207ae730> .
<https://starwars.com#planet_Yalara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Yalara> <http://telicent.io/ontology/primaryName> "Yalara" .
<https://starwars.com#e127b484-f6b1-4f71-a4a7-6d74207ae730> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I21"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I21> <http://telicent.io/ontology/primaryName> "I21" .
<https://starwars.com#d62fb92b-9ec5-4b27-b306-3b5f2347452b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d62fb92b-9ec5-4b27-b306-3b5f2347452b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yalara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yalara> <http://www.w3.org/2000/01/rdf-schema#comment> "Yalara was a primitive planet located within the Yalara system of the Wild Space. " .
<https://starwars.com#grid_I21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Yalara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I21> .
<https://starwars.com#e127b484-f6b1-4f71-a4a7-6d74207ae730> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

