Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zakuul> <http://www.w3.org/2000/01/rdf-schema#comment> "Zakuul was a planet located in Wild Space that served as the capital planet of the Eternal Empire. " .
<https://starwars.com#grid_D13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Zakuul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_D13> .
<https://starwars.com#c506ebd3-aa9d-4ae4-b693-a39af9f90576> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Zakuul> <http://telicent.io/ontology/primaryName> "Zakuul" .
<https://starwars.com#f0977d79-9b27-4938-ba43-59d8b95b11c4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zakuul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#c506ebd3-aa9d-4ae4-b693-a39af9f90576> <http://ies.data.gov.uk/ontology/ies4#representationValue> "D13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zakuul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f0977d79-9b27-4938-ba43-59d8b95b11c4> .
<https://starwars.com#grid_D13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c506ebd3-aa9d-4ae4-b693-a39af9f90576> .
<https://starwars.com#f0977d79-9b27-4938-ba43-59d8b95b11c4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zakuul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_D13> <http://telicent.io/ontology/primaryName> "D13" .
<https://starwars.com#grid_D13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Zakuul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

