Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PeragusII> <http://www.w3.org/2000/01/rdf-schema#comment> "Peragus II was a planet in the Peragus system of the Outer Rim Territories' Xappyh sector. A major source of low-grade engine fuel, Peragus II was originally a terrestrial world, but it was nearly destroyed hundreds of years before 3959 BBY by the early attempts of miners to siphon off fuel from the planet. A mining accident caused an explosion beneath the crust, blowing a massive hole in the planet and forming an asteroid field around the world. By 3951 BBY, mercenaries and tradesmen constructed the Peragus Mining Facility in the Peragus asteroid field, but both the asteroid field and the station were destroyed when a stray blast during a firefight between the light freighter Ebon Hawk and the Hammerhead-class cruiser Harbinger ignited the fuel in the asteroid field. After the destruction of the asteroid field, no further mining projects were attempted in the ruins of Peragus II. " .
<https://starwars.com#planet_PeragusII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_PeragusII> <http://telicent.io/ontology/primaryName> "Peragus II" .
<https://starwars.com#756f5427-33a5-41a3-9baa-0f2822514347> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Peragus II"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Xappyh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#756f5427-33a5-41a3-9baa-0f2822514347> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PeragusII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#756f5427-33a5-41a3-9baa-0f2822514347> .
<https://starwars.com#sector_Xappyh> <http://telicent.io/ontology/primaryName> "Xappyh" .
<https://starwars.com#planet_PeragusII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PeragusII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Xappyh> .
<https://starwars.com#sector_Xappyh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

