Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Koradin> <http://telicent.io/ontology/primaryName> "Koradin" .
<https://starwars.com#sector_Koradin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#be06595e-1b08-4214-a777-63d378c2c6cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Keskin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be06595e-1b08-4214-a777-63d378c2c6cd> .
<https://starwars.com#sector_Koradin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Keskin> <http://telicent.io/ontology/primaryName> "Keskin" .
<https://starwars.com#planet_Keskin> <http://www.w3.org/2000/01/rdf-schema#comment> "Keskin was a planet which was the site of a battle during the Galactic Civil War between the Galactic Empire and Alliance to Restore the Republic. " .
<https://starwars.com#planet_Keskin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Keskin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J18> .
<https://starwars.com#be06595e-1b08-4214-a777-63d378c2c6cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Keskin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Keskin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Koradin> .

