Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Craci> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Craci> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac7e953a-fa7c-4ffb-9f0c-b2851090b364> .
<https://starwars.com#planet_Craci> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#ac7e953a-fa7c-4ffb-9f0c-b2851090b364> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Craci> <http://www.w3.org/2000/01/rdf-schema#comment> "Craci was a planet located in the Craci system in the Corporate Sector of the Outer Rim Territories. The planet was the home of the Cracian thumpers, a species used frequently as mounts by scouts. Controlled by the Corporate Sector Authority by the time of the Battle of Yavin, the planet had spaceports that were experience high levels of activity due to the agriculture and industry of the five worlds. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Craci> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ac7e953a-fa7c-4ffb-9f0c-b2851090b364> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Craci"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Craci> <http://telicent.io/ontology/primaryName> "Craci" .

