Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_CyrillianProtectorate> <http://telicent.io/ontology/primaryName> "Cyrillian Protectorate" .
<https://starwars.com#sector_CyrillianProtectorate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_CyrillianProtectorate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Prazhi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#planet_Prazhi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5f1b4ee3-f002-4dc7-b8a5-c0b3a46521ed> .
<https://starwars.com#planet_Prazhi> <http://www.w3.org/2000/01/rdf-schema#comment> "Prazhi was an Expansion Region planet located in the Cyrillian Protectorate. It was the homeworld of the Zexx species. A member of the galactic community since at least 5000 BBY, a millennium later Prazhi was situated on an important hyperspace trade route. By the time of the Galactic Empire's reign, Prazhi had become a trade world the economy of which was revitalized by Imperial efforts to resettle the Expansion Region. " .
<https://starwars.com#planet_Prazhi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Prazhi> <http://telicent.io/ontology/primaryName> "Prazhi" .
<https://starwars.com#5f1b4ee3-f002-4dc7-b8a5-c0b3a46521ed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5f1b4ee3-f002-4dc7-b8a5-c0b3a46521ed> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Prazhi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Prazhi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CyrillianProtectorate> .

