Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tandankin> <http://telicent.io/ontology/primaryName> "Tandankin" .
<https://starwars.com#sector_Spadja> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tandankin> <http://www.w3.org/2000/01/rdf-schema#comment> "Tandankin was a planet located in the Spadja sector of the Outer Rim Territories. " .
<https://starwars.com#5404c6a7-5873-42ed-9985-8d95fe7bbbef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tandankin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Tandankin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5404c6a7-5873-42ed-9985-8d95fe7bbbef> .
<https://starwars.com#planet_Tandankin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Spadja> .
<https://starwars.com#planet_Tandankin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Spadja> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5404c6a7-5873-42ed-9985-8d95fe7bbbef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tandankin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Spadja> <http://telicent.io/ontology/primaryName> "Spadja" .

