Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Antar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#403e8839-3b53-4f16-a9b3-d9b1d3739c13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Antar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#403e8839-3b53-4f16-a9b3-d9b1d3739c13> .
<https://starwars.com#planet_Antar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#403e8839-3b53-4f16-a9b3-d9b1d3739c13> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Antar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Antar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Antar> <http://www.w3.org/2000/01/rdf-schema#comment> "Antar was a gas giant located in the galaxy's Inner Rim, located in grid square N-12 on the Standard Galactic Grid, that was orbited by Antar 4, homeworld of the sentient Gotal species, and the Dead Moon of Antar. " .
<https://starwars.com#planet_Antar> <http://telicent.io/ontology/primaryName> "Antar" .

