Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bellassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Bellassa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8d0c251b-303a-48a2-a584-4a623be969a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bellassa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bellassa> <http://telicent.io/ontology/primaryName> "Bellassa" .
<https://starwars.com#planet_Bellassa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8d0c251b-303a-48a2-a584-4a623be969a4> .
<https://starwars.com#planet_Bellassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Bellassa> <http://www.w3.org/2000/01/rdf-schema#comment> "Bellassa was an astronomical object located in the galaxy's Core Worlds. It was connected via the Hydian Way hyperspace route to Skako and Fedalle. " .
<https://starwars.com#8d0c251b-303a-48a2-a584-4a623be969a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

