Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Geroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Geroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I8> .
<https://starwars.com#37d631cd-5f4e-4e6a-8484-d2e8382b33be> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Geroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Geroon> <http://www.w3.org/2000/01/rdf-schema#comment> "Geroon was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Geroon> <http://telicent.io/ontology/primaryName> "Geroon" .
<https://starwars.com#planet_Geroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#37d631cd-5f4e-4e6a-8484-d2e8382b33be> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#37d631cd-5f4e-4e6a-8484-d2e8382b33be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Geroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .

