Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kwookrrr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q9> .
<https://starwars.com#planet_Kwookrrr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e119e409-1ef0-4987-9a5c-95ab4d03df74> .
<https://starwars.com#planet_Kwookrrr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e119e409-1ef0-4987-9a5c-95ab4d03df74> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#e119e409-1ef0-4987-9a5c-95ab4d03df74> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kwookrrr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kwookrrr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kwookrrr> <http://telicent.io/ontology/primaryName> "Kwookrrr" .
<https://starwars.com#planet_Kwookrrr> <http://www.w3.org/2000/01/rdf-schema#comment> "Kwookrrr was a planet where the Galactic Empire used enslaved Wookiee children for labor in factories and farms. It had previously been a Wookiee colony world. " .

