Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_EmpressTeta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#175cf3a7-9200-4f24-ba4e-0487bb70a9e1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#175cf3a7-9200-4f24-ba4e-0487bb70a9e1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Empress Teta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_EmpressTeta> <http://www.w3.org/2000/01/rdf-schema#comment> "Empress Teta  was an ecumenopolis world located in the Empress Teta system, in the Koros sector of the Deep Core. Known as Koros or Koros Major during the lifetime of its namesake, it was home to one of the galaxy's most ancient and affluent human civilizations, and was a focal point of the Great Hyperspace War. A supplier of refined carbonite and andris spice for much of galactic history, Empress Teta was a major hub of operations for the Mining Guild, which exerted control over the planetary government. By the reign of the Galactic Empire, the world was alternatively known as Cinnagar, the name of its capital city. " .
<https://starwars.com#planet_EmpressTeta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_EmpressTeta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#175cf3a7-9200-4f24-ba4e-0487bb70a9e1> .
<https://starwars.com#planet_EmpressTeta> <http://telicent.io/ontology/primaryName> "Empress Teta" .
<https://starwars.com#planet_EmpressTeta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

