Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Koradin> <http://telicent.io/ontology/primaryName> "Koradin" .
<https://starwars.com#sector_Koradin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Virgillia> <http://www.w3.org/2000/01/rdf-schema#comment> "Virgillia was a world located in the Virgillia system. It was orbited by a forested moon. " .
<https://starwars.com#planet_Virgillia> <http://telicent.io/ontology/primaryName> "Virgillia" .
<https://starwars.com#planet_Virgillia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e1dfa644-615d-47f3-a38f-d040827989bf> .
<https://starwars.com#sector_Koradin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e1dfa644-615d-47f3-a38f-d040827989bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Virgillia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Virgillia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I18> .
<https://starwars.com#planet_Virgillia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Koradin> .
<https://starwars.com#e1dfa644-615d-47f3-a38f-d040827989bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Virgillia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

