Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#70ae958f-a117-4139-9726-9c83f48dc107> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rampa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#70ae958f-a117-4139-9726-9c83f48dc107> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rampa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rampa> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Rampa> <http://telicent.io/ontology/primaryName> "Rampa" .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rampa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Rampa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#70ae958f-a117-4139-9726-9c83f48dc107> .
<https://starwars.com#planet_Rampa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

