Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7102d51a-48c8-460d-ab3d-d5d36d8737ee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Reboam"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Reboam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7102d51a-48c8-460d-ab3d-d5d36d8737ee> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Reboam> <http://telicent.io/ontology/primaryName> "Reboam" .
<https://starwars.com#7102d51a-48c8-460d-ab3d-d5d36d8737ee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Reboam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Reboam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Reboam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Reboam> <http://www.w3.org/2000/01/rdf-schema#comment> "Reboam was a planet located within the Hapes Cluster which was noted for being a small world with a harsh climate that was relatively uninhabited and was comparable to Tatooine. " .

