Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rbollea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c5e1d190-1af8-4d0d-ab1f-4ef618ef318b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rbollea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rbollea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c5e1d190-1af8-4d0d-ab1f-4ef618ef318b> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Rbollea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Rbollea> <http://telicent.io/ontology/primaryName> "Rbollea" .
<https://starwars.com#planet_Rbollea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Rbollea> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#c5e1d190-1af8-4d0d-ab1f-4ef618ef318b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

