Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Milagro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Milagro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#a3857649-19e5-4c9f-8a19-927897d13d93> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Chaykin> <http://telicent.io/ontology/primaryName> "Chaykin" .
<https://starwars.com#planet_Milagro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chaykin> .
<https://starwars.com#sector_Chaykin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Milagro> <http://www.w3.org/2000/01/rdf-schema#comment> "Milagro was an astronomical object located in the galaxy's Expansion Region, located on the Corellian Run hyperspace route. " .
<https://starwars.com#planet_Milagro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a3857649-19e5-4c9f-8a19-927897d13d93> .
<https://starwars.com#sector_Chaykin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a3857649-19e5-4c9f-8a19-927897d13d93> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Milagro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Milagro> <http://telicent.io/ontology/primaryName> "Milagro" .

