Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#30066285-c8eb-47d9-bf4a-eacdf8b42dcf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ophideraan> <http://www.w3.org/2000/01/rdf-schema#comment> "Ophideraan was an arid desert planet in the Colonies that, by the era of the Galactic Civil War, was ruled by a group of bandits known as the Serpent Masters. Ophideraan's skies were dominated by a unique species of flying serpent that communicated through ultrasonic tones not audible to the Human ear—it was through discovery of these tones that the Serpent Masters learned to control and mount these fearsome beasts. The Serpent Masters maintained a society through salvaging wrecks and enslaving those unfortunates that crashed onto Ophideraan, using them to maintain the few sources of water on the planet. The Serpent Masters' rule was overthrown in 0 ABY, through the efforts of Rebel agent Luke Skywalker. " .
<https://starwars.com#planet_Ophideraan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30066285-c8eb-47d9-bf4a-eacdf8b42dcf> .
<https://starwars.com#30066285-c8eb-47d9-bf4a-eacdf8b42dcf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ophideraan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ophideraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#planet_Ophideraan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ophideraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Ophideraan> <http://telicent.io/ontology/primaryName> "Ophideraan" .

