Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hovan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Hovan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c979ce92-4f2f-4677-a259-5c299a309a83> .
<https://starwars.com#c979ce92-4f2f-4677-a259-5c299a309a83> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hovan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hovan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hovan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hovan> <http://telicent.io/ontology/primaryName> "Hovan" .
<https://starwars.com#c979ce92-4f2f-4677-a259-5c299a309a83> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hovan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

