Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yout> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Qiilura> .
<https://starwars.com#planet_Yout> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#cc85695a-5610-4a4f-ae41-e597849e6c86> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yout> <http://telicent.io/ontology/primaryName> "Yout" .
<https://starwars.com#planet_Yout> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc85695a-5610-4a4f-ae41-e597849e6c86> .
<https://starwars.com#cc85695a-5610-4a4f-ae41-e597849e6c86> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yout"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yout> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#planet_Yout> <http://www.w3.org/2000/01/rdf-schema#comment> "Yout was a planet with at least twelve moons, located in the Yout system. In 22 BBY, the assassin droid KRONOS-327, employee of crime lord Ziro the Hutt, returned to Ziro's Palace on the planet Coruscant after an unsuccessful mission to the twelfth moon of Yout. When KRONOS-327 reported the failure to Ziro, the Hutt sentenced the droid to be scrapped. " .
<https://starwars.com#sector_Qiilura> <http://telicent.io/ontology/primaryName> "Qiilura" .
<https://starwars.com#sector_Qiilura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Qiilura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

