Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4c2dada3-dda9-4252-aeed-a0d686f4463d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Harterra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4c2dada3-dda9-4252-aeed-a0d686f4463d> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Harterra> <http://www.w3.org/2000/01/rdf-schema#comment> "Harterra was a planet in the Interior Regions of the Hapes Cluster. It was home to the Harterran moonstone. " .
<https://starwars.com#planet_Harterra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Harterra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Harterra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#4c2dada3-dda9-4252-aeed-a0d686f4463d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Harterra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Harterra> <http://telicent.io/ontology/primaryName> "Harterra" .

