Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Velusia> <http://www.w3.org/2000/01/rdf-schema#comment> "Velusia was a planet located in the Velusia system and the homeworld of the Velusian species, which occupied most of the planet except the volcanic atoll of Kolo-ha. In 5 ABY, members of the New Republic, including Chancellor Mon Mothma and Leia Organa, traveled to Velusia to negotiate the surrender of Grand Vizier Mas Amedda. Velusia was also home to the chomong, a species of sea creatures. The fossilized corpses of the chomong created a ring of shimmering sediment off the coast of Kolo-ha. " .
<https://starwars.com#planet_Velusia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Velusia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6dc74928-225b-4d83-966b-a01950536f06> .
<https://starwars.com#planet_Velusia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Velusia> <http://telicent.io/ontology/primaryName> "Velusia" .
<https://starwars.com#planet_Velusia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#6dc74928-225b-4d83-966b-a01950536f06> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#6dc74928-225b-4d83-966b-a01950536f06> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Velusia"^^<http://www.w3.org/2001/XMLSchema#string> .

