Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ca589aa1-37fc-4fae-95f4-9fb889ea4317> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ompersan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca589aa1-37fc-4fae-95f4-9fb889ea4317> .
<https://starwars.com#planet_Ompersan> <http://www.w3.org/2000/01/rdf-schema#comment> "Ompersan was an Outer Rim planet located within Imperial Remnant space. It was the site of the Imperial Navy fleet records center. " .
<https://starwars.com#planet_Ompersan> <http://telicent.io/ontology/primaryName> "Ompersan" .
<https://starwars.com#ca589aa1-37fc-4fae-95f4-9fb889ea4317> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ompersan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .
<https://starwars.com#planet_Ompersan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prefsbelt> .
<https://starwars.com#planet_Ompersan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ompersan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

