Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d08df07f-df31-485e-8318-13e01de2c061> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d08df07f-df31-485e-8318-13e01de2c061> .
<https://starwars.com#planet_Agamar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lahara> .
<https://starwars.com#b12715a4-92d9-49bd-ae43-fbbfb68fcb16> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Agamar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lahara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_M5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Lahara> <http://telicent.io/ontology/primaryName> "Lahara" .
<https://starwars.com#grid_M5> <http://telicent.io/ontology/primaryName> "M5" .
<https://starwars.com#d08df07f-df31-485e-8318-13e01de2c061> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#b12715a4-92d9-49bd-ae43-fbbfb68fcb16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Lahara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_M5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Agamar> <http://telicent.io/ontology/primaryName> "Agamar" .
<https://starwars.com#planet_Agamar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b12715a4-92d9-49bd-ae43-fbbfb68fcb16> .
<https://starwars.com#planet_Agamar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Agamar> <http://www.w3.org/2000/01/rdf-schema#comment> "A barren, rocky planet in the Outer Rim. Site of a still-active reserve of Separatist droids that became known for surviving the Clone Wars." .
<https://starwars.com#planet_Agamar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M5> .

