Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pybus> <http://www.w3.org/2000/01/rdf-schema#comment> "Pybus was a planet located in the Bootana Hutta region of Hutt Space. " .
<https://starwars.com#73d4af91-1696-41fb-adce-c6e08a8b5455> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pybus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pybus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Pybus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73d4af91-1696-41fb-adce-c6e08a8b5455> .
<https://starwars.com#planet_Pybus> <http://telicent.io/ontology/primaryName> "Pybus" .
<https://starwars.com#73d4af91-1696-41fb-adce-c6e08a8b5455> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pybus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Pybus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

