Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_AndelmIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Svivreni> .
<https://starwars.com#sector_Svivreni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#651b8068-0fde-40ca-9fd2-32503be8b030> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_AndelmIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#212231ee-97d8-48a6-a4c2-a105fabb0371> .
<https://starwars.com#sector_Svivreni> <http://telicent.io/ontology/primaryName> "Svivreni" .
<https://starwars.com#planet_AndelmIV> <http://telicent.io/ontology/primaryName> "Andelm IV" .
<https://starwars.com#sector_Svivreni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_AndelmIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Andelm IV, also know simply as Andelm, was a planet in the Outer Rim Territories. During the Galactic Civil War, the planet was ruled by Jaum, a crime lord. " .
<https://starwars.com#651b8068-0fde-40ca-9fd2-32503be8b030> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_AndelmIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q19> .
<https://starwars.com#212231ee-97d8-48a6-a4c2-a105fabb0371> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_AndelmIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#212231ee-97d8-48a6-a4c2-a105fabb0371> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Andelm IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#651b8068-0fde-40ca-9fd2-32503be8b030> .
<https://starwars.com#grid_Q19> <http://telicent.io/ontology/primaryName> "Q19" .
<https://starwars.com#grid_Q19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

