Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d463d841-9820-41ad-b39f-89086fc30195> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Saqqar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#d463d841-9820-41ad-b39f-89086fc30195> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Saqqar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Saqqar> <http://www.w3.org/2000/01/rdf-schema#comment> "Saqqar was an icy planet that was located within the Saqqar system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet lay on the hyperlane called The Dead Road, which connected it to the worlds of Tisht and Usk. A smaller hyperlane linked the planet to the world of Nar Haaska. " .
<https://starwars.com#planet_Saqqar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Saqqar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#planet_Saqqar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d463d841-9820-41ad-b39f-89086fc30195> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Saqqar> <http://telicent.io/ontology/primaryName> "Saqqar" .

