Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#74c1052b-89ba-4817-9517-181af916abde> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RydonniPrime> <http://telicent.io/ontology/primaryName> "Rydonni Prime" .
<https://starwars.com#planet_RydonniPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#74c1052b-89ba-4817-9517-181af916abde> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rydonni Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RydonniPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#74c1052b-89ba-4817-9517-181af916abde> .
<https://starwars.com#planet_RydonniPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Rydonni Prime was the only habitable planet in the Namaryne system and home to Rythani Products, headed by the K'ntarr family. Moff Caerbellak ruled the planet during the Galactic Civil War and the early years of the New Republic. It was very wealthy and had very few disenfranchised inhabitants, which made it very loyal to the Galactic Empire. " .
<https://starwars.com#planet_RydonniPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_RydonniPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .

