Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#428d709d-713e-4a70-b0ce-4414be35dfba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Boordii> <http://telicent.io/ontology/primaryName> "Boordii" .
<https://starwars.com#428d709d-713e-4a70-b0ce-4414be35dfba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Boordii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Boordii> <http://www.w3.org/2000/01/rdf-schema#comment> "Boordii was a temperate planet in the Sumitra sector. Its central source of income came from smugglers transporting contraband offworld. After the death of King Alaric the whole sector including this planet, left the Galactic Republic and joined the Confederacy of Independent Systems. " .
<https://starwars.com#planet_Boordii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sumitra> <http://telicent.io/ontology/primaryName> "Sumitra" .
<https://starwars.com#planet_Boordii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sumitra> .
<https://starwars.com#sector_Sumitra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Sumitra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Boordii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#planet_Boordii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#428d709d-713e-4a70-b0ce-4414be35dfba> .

