Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4fa870b0-bdf8-4507-9536-b08dc532725e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewBalosar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ArcdStot> .
<https://starwars.com#planet_NewBalosar> <http://telicent.io/ontology/primaryName> "New Balosar" .
<https://starwars.com#planet_NewBalosar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_NewBalosar> <http://www.w3.org/2000/01/rdf-schema#comment> "New Balosar was a planet in the Expansion Region, located on the Great Gran Run. It was the location of The Kindest Cut, a beauty salon run by Zenn Bien. " .
<https://starwars.com#planet_NewBalosar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#sector_ArcdStot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_NewBalosar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4fa870b0-bdf8-4507-9536-b08dc532725e> .
<https://starwars.com#4fa870b0-bdf8-4507-9536-b08dc532725e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Balosar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ArcdStot> <http://telicent.io/ontology/primaryName> "Arc d'Stot" .
<https://starwars.com#sector_ArcdStot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

