Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Biewa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Biewa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#c7a08953-acfe-4299-a168-15d0e6a1b6c2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Biewa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Biewa> <http://www.w3.org/2000/01/rdf-schema#comment> "Biewa was an industrial planet in the Corporate Sector used as the headquarters of the Corporate Sector Authority Picket Fleet. It was a relatively poor world, and the Biewans spent what few credits they had on clothing, shelter and food. " .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#c7a08953-acfe-4299-a168-15d0e6a1b6c2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Biewa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Biewa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c7a08953-acfe-4299-a168-15d0e6a1b6c2> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Biewa> <http://telicent.io/ontology/primaryName> "Biewa" .

