Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O17> <http://telicent.io/ontology/primaryName> "O17" .
<https://starwars.com#planet_Alui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#planet_Alui> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_O17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Alui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Alui> .
<https://starwars.com#planet_Alui> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#79920699-948f-4bf1-8a21-cb34c67f1a56> .
<https://starwars.com#planet_Alui> <http://telicent.io/ontology/primaryName> "Alui" .
<https://starwars.com#grid_O17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#f4b532c5-6058-42c5-a428-30951c827e6c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#79920699-948f-4bf1-8a21-cb34c67f1a56> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alui"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Alui> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Alui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_O17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f4b532c5-6058-42c5-a428-30951c827e6c> .
<https://starwars.com#planet_Alui> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#79920699-948f-4bf1-8a21-cb34c67f1a56> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f4b532c5-6058-42c5-a428-30951c827e6c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Alui> <http://telicent.io/ontology/primaryName> "Alui" .

