Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f4f2cc0e-e792-434d-bc1b-b6369d9415be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trevura> <http://telicent.io/ontology/primaryName> "Trevura" .
<https://starwars.com#planet_Trevura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Trevura> <http://www.w3.org/2000/01/rdf-schema#comment> "During that time, a group of Rebel Alliance agents, seeking to escort a vital astromech droid off-planet, killed a pair of Imperial stormtroopers equipped with the experimental inhibitor guns. Shortly afterward, S-R6 established contact with the Rebels and met them at his garage, whereupon stormtrooper reinforcements engaged everyone present at the structure in a fierce firefight. " .
<https://starwars.com#planet_Trevura> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f4f2cc0e-e792-434d-bc1b-b6369d9415be> .
<https://starwars.com#planet_Trevura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K14> .
<https://starwars.com#planet_Trevura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f4f2cc0e-e792-434d-bc1b-b6369d9415be> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trevura"^^<http://www.w3.org/2001/XMLSchema#string> .

