Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_CorbettCLuster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corbett> .
<https://starwars.com#planet_CorbettCLuster> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_CorbettCLuster> <http://telicent.io/ontology/primaryName> "Corbett CLuster" .
<https://starwars.com#sector_Corbett> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_CorbettCLuster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_CorbettCLuster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#1a1b5d72-d310-4e1d-8c67-cd1f88bec6d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corbett CLuster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CorbettCLuster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a1b5d72-d310-4e1d-8c67-cd1f88bec6d2> .
<https://starwars.com#sector_Corbett> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#1a1b5d72-d310-4e1d-8c67-cd1f88bec6d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Corbett> <http://telicent.io/ontology/primaryName> "Corbett" .

