Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Voltare> <http://telicent.io/ontology/primaryName> "Voltare" .
<https://starwars.com#planet_Voltare> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Voltare> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3fa05469-794b-499f-889e-7eef4bef4df6> .
<https://starwars.com#3fa05469-794b-499f-889e-7eef4bef4df6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Voltare"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Voltare> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#planet_Voltare> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#3fa05469-794b-499f-889e-7eef4bef4df6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Voltare> <http://www.w3.org/2000/01/rdf-schema#comment> "Voltare was a spaceport planet in the Voltare system of the Inner Rim. " .

