Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Terrskiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Terrskiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Pizilis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4545b9e-f96d-41c0-8066-60d40e2bc231> .
<https://starwars.com#planet_Pizilis> <http://www.w3.org/2000/01/rdf-schema#comment> "Pizilis was a gas giant–type planet. It was located within the Pizilis system of the Terr'skiar sector, a part of the Kashyyyk Region in the Slice portion of the Mid Rim. The Dauntless Run hyperlane connected the planet to the world of Rorgam while the hyperspace route known as the Nightroad linked Pizilis to the worlds of Mytaranor and Terr'skiar. " .
<https://starwars.com#planet_Pizilis> <http://telicent.io/ontology/primaryName> "Pizilis" .
<https://starwars.com#b4545b9e-f96d-41c0-8066-60d40e2bc231> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pizilis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#planet_Pizilis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Terrskiar> .
<https://starwars.com#sector_Terrskiar> <http://telicent.io/ontology/primaryName> "Terr'skiar" .
<https://starwars.com#b4545b9e-f96d-41c0-8066-60d40e2bc231> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pizilis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pizilis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

