Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a0ae684f-9dd1-4341-803a-ff0c1350209e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dathomir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dathomir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quelii> .
<https://starwars.com#sector_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dathomir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0ae684f-9dd1-4341-803a-ff0c1350209e> .
<https://starwars.com#sector_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#planet_Dathomir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#a0ae684f-9dd1-4341-803a-ff0c1350209e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dathomir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dathomir> <http://telicent.io/ontology/primaryName> "Dathomir" .
<https://starwars.com#planet_Dathomir> <http://www.w3.org/2000/01/rdf-schema#comment> "Homeworld of the Force-sensitive Nightsisters, including Asajj Ventress. Also the homeworld of the Zabrak warriors, including Darth Maul. A remote world, perpetually bathed in blood-red sunlight and home to numerous dangerous predators." .
<https://starwars.com#sector_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

