Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_TaralV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TaralV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#planet_TaralV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0ffcac26-4208-47ca-b107-fe56b3f592ec> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_TaralV> <http://www.w3.org/2000/01/rdf-schema#comment> "Taral V was a planet controlled by the Sith Empire during the Cold War. During the Cold War, a Galactic Republic strike team was sent to Taral V to retrieve information on a missing Jedi. The planet was home to many dangerous species. " .
<https://starwars.com#0ffcac26-4208-47ca-b107-fe56b3f592ec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taral V"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TaralV> <http://telicent.io/ontology/primaryName> "Taral V" .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TaralV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#0ffcac26-4208-47ca-b107-fe56b3f592ec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

