Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Babbadod> <http://telicent.io/ontology/primaryName> "Babbadod" .
<https://starwars.com#3b3a2ea2-951e-48e5-ab50-fef357db7f44> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Babbadod"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Babbadod> <http://www.w3.org/2000/01/rdf-schema#comment> "Babbadod was a colony world in the Inner Rim between the planets Darepp and Motexx. It was visited by the passenger liner Star Morning. " .
<https://starwars.com#planet_Babbadod> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .
<https://starwars.com#957b3aa5-9b69-4deb-b7be-9331cf11e3fb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_N14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#957b3aa5-9b69-4deb-b7be-9331cf11e3fb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Babbadod> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#grid_N14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_N14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#957b3aa5-9b69-4deb-b7be-9331cf11e3fb> .
<https://starwars.com#planet_Babbadod> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_N14> <http://telicent.io/ontology/primaryName> "N14" .
<https://starwars.com#3b3a2ea2-951e-48e5-ab50-fef357db7f44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Babbadod> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b3a2ea2-951e-48e5-ab50-fef357db7f44> .

