Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Relgim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdBiniir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Relgim> .
<https://starwars.com#sector_Relgim> <http://telicent.io/ontology/primaryName> "Relgim" .
<https://starwars.com#planet_OrdBiniir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e0c4a3c-432a-4ffa-b72b-dd7247abecf0> .
<https://starwars.com#planet_OrdBiniir> <http://telicent.io/ontology/primaryName> "Ord Biniir" .
<https://starwars.com#0e0c4a3c-432a-4ffa-b72b-dd7247abecf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0e0c4a3c-432a-4ffa-b72b-dd7247abecf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Biniir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdBiniir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdBiniir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_OrdBiniir> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Biniir was an astronomical object located in the galaxy's Outer Rim Territories, in grid square K-5 on the Standard Galactic Grid. Prior to the Galactic Civil War, the Alliance to Restore the Republic launched a successful assault on Imperial targets there. However the resulting victory did not show the full potency of the rebellion. " .
<https://starwars.com#sector_Relgim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

