Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#67341cb6-e5bc-4219-b0dc-3c03ea6eae17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ediorung> <http://www.w3.org/2000/01/rdf-schema#comment> "Ediorung was a planet in the Interior Regions of the Hapes Cluster. The planet was known for the dynamic holosculptures it produced; however, these were strictly judged by the Commission for the Preservation of the New Order Art Group. Porcellus, the chef for Jabba the Hutt, occasionally prepared Ediorung icefish for his master. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ediorung> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Ediorung> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Ediorung> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#67341cb6-e5bc-4219-b0dc-3c03ea6eae17> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ediorung> <http://telicent.io/ontology/primaryName> "Ediorung" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#67341cb6-e5bc-4219-b0dc-3c03ea6eae17> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ediorung"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ediorung> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

