Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Rago> <http://telicent.io/ontology/primaryName> "Rago" .
<https://starwars.com#planet_Rago> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#85abe344-fb7d-48e2-b5b0-58b975221e08> .
<https://starwars.com#sector_Rago> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rago> <http://telicent.io/ontology/primaryName> "Rago" .
<https://starwars.com#planet_Rago> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#85abe344-fb7d-48e2-b5b0-58b975221e08> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rago"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rago> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rago> .
<https://starwars.com#planet_Rago> <http://www.w3.org/2000/01/rdf-schema#comment> "Rago was an astronomical object located in the galaxy's Mid Rim, connected by hyperspace route to Ansion and the Utegetu Nebula. " .
<https://starwars.com#planet_Rago> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#85abe344-fb7d-48e2-b5b0-58b975221e08> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Rago> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

