Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Marrovia> <http://www.w3.org/2000/01/rdf-schema#comment> "Marrovia was an agriworld located in the Marrovia system, a part of the Gordian Reach sector in the Trans-Hydian portion of the Outer Rim Territories. The Pinooran Spur hyperlane connected the world to the Kli'aar and Ladarra systems. " .
<https://starwars.com#36729a8a-503c-4415-83f9-6d75e7063573> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Marrovia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Marrovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Marrovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#36729a8a-503c-4415-83f9-6d75e7063573> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Marrovia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#36729a8a-503c-4415-83f9-6d75e7063573> .
<https://starwars.com#planet_Marrovia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Marrovia> <http://telicent.io/ontology/primaryName> "Marrovia" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

