Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rishi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rishi> <http://www.w3.org/2000/01/rdf-schema#comment> "Tropical planet used by the Republic to monitor the nearby cloning facility on Kamino." .
<https://starwars.com#a4dbe542-9bda-4e8a-913e-b01451061d2e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rishi> <http://telicent.io/ontology/primaryName> "Rishi" .
<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a4dbe542-9bda-4e8a-913e-b01451061d2e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rishi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rishi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a4dbe542-9bda-4e8a-913e-b01451061d2e> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#planet_Rishi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Rishi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .

