Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#718410e4-d932-4ad3-bf5f-d01742aee8de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Darek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Darek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Darek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#718410e4-d932-4ad3-bf5f-d01742aee8de> .
<https://starwars.com#planet_Darek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Darek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Darek> <http://telicent.io/ontology/primaryName> "Darek" .
<https://starwars.com#planet_Darek> <http://www.w3.org/2000/01/rdf-schema#comment> "Darek was a male Human who was a private in the Republic Army during the Galactic War, when he was stationed at Farnel Outpost on the planet Balmorra. " .
<https://starwars.com#718410e4-d932-4ad3-bf5f-d01742aee8de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

