Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tinallis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#c412ec74-20af-4c67-9de9-be02d81aa2d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tinallis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tinallis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c412ec74-20af-4c67-9de9-be02d81aa2d9> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tinallis> <http://www.w3.org/2000/01/rdf-schema#comment> "Tinallis was a planet located within the Tinallis system of the Mid Rim. Though it was an industrialized planet, it was noted for the wildlife in its oceans, seashores, and rainforests. One of its native creatures, the tresher, was a lucrative but illegal trade item. " .
<https://starwars.com#c412ec74-20af-4c67-9de9-be02d81aa2d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tinallis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Tinallis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tinallis> <http://telicent.io/ontology/primaryName> "Tinallis" .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

