Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rasterous> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rasterous> <http://telicent.io/ontology/primaryName> "Rasterous" .
<https://starwars.com#planet_Rasterous> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0529182a-1fd7-48da-989a-ddf049955058> .
<https://starwars.com#0529182a-1fd7-48da-989a-ddf049955058> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rasterous> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#planet_Rasterous> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Rasterous> <http://www.w3.org/2000/01/rdf-schema#comment> "Rasterous was a planet with a shipyard belonging to Kuat Drive Yards. " .
<https://starwars.com#0529182a-1fd7-48da-989a-ddf049955058> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rasterous"^^<http://www.w3.org/2001/XMLSchema#string> .

