Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fadden> <http://telicent.io/ontology/primaryName> "Fadden" .
<https://starwars.com#planet_Fadden> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#25f126bb-4ebf-4fbc-bfe4-0a730f5451df> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fadden"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fadden> <http://www.w3.org/2000/01/rdf-schema#comment> "Fadden was a world located in the Fadden system, a part of the Slice portion of the Inner Rim. It was settled by colonists of the Duros species, which was native to the Core Worlds planet Duro. " .
<https://starwars.com#planet_Fadden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Fadden> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#25f126bb-4ebf-4fbc-bfe4-0a730f5451df> .
<https://starwars.com#25f126bb-4ebf-4fbc-bfe4-0a730f5451df> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fadden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .

