Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sedratis> <http://www.w3.org/2000/01/rdf-schema#comment> "The Sedratis system was located in the Slice portion of the Core Worlds, specifically in the region known as the Arrowhead. It was situated on the super-hyperroute known as the Corellian Run, between the Rehemsa and Namaryne systems.[1] The Sedratis system contained[3] Sedratis City, which in turn was the site of the Sedratis Coliseum." .
<https://starwars.com#planet_Sedratis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#33d15ae8-f088-40bb-97fe-b4016620a664> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sedratis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sedratis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#33d15ae8-f088-40bb-97fe-b4016620a664> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sedratis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33d15ae8-f088-40bb-97fe-b4016620a664> .
<https://starwars.com#planet_Sedratis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Sedratis> <http://telicent.io/ontology/primaryName> "Sedratis" .

