Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Centares> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#7dfd057b-f792-43cb-9f1a-bb294263b374> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Centares"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Maldrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Maldrood> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Centares> <http://www.w3.org/2000/01/rdf-schema#comment> "Centares was an astronomical object located in the galaxy's Mid Rim on the Perlemian Trade Route. Imperial capital ships were re-deployed from Centares in order to try and protect targets that the stolen Imperial corvette Carrion Spike might attack. Moff Wilhuff Tarkin, owner of the corvette, was informed of these re-deployments by the captain of the Star Destroyer Liberator. " .
<https://starwars.com#planet_Centares> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maldrood> .
<https://starwars.com#7dfd057b-f792-43cb-9f1a-bb294263b374> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Centares> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7dfd057b-f792-43cb-9f1a-bb294263b374> .
<https://starwars.com#sector_Maldrood> <http://telicent.io/ontology/primaryName> "Maldrood" .
<https://starwars.com#planet_Centares> <http://telicent.io/ontology/primaryName> "Centares" .
<https://starwars.com#planet_Centares> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

