Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clythe> <http://telicent.io/ontology/primaryName> "Clythe" .
<https://starwars.com#sector_Clythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Iridonia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clythe> .
<https://starwars.com#planet_Iridonia> <http://www.w3.org/2000/01/rdf-schema#comment> "Home of the Iridonian Zabrak people and formerly rumored birthplace of Darth Maul." .
<https://starwars.com#planet_Iridonia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc64b494-9420-4708-a750-ec26fd7ccfd6> .
<https://starwars.com#sector_Clythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Iridonia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iridonia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#cc64b494-9420-4708-a750-ec26fd7ccfd6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iridonia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iridonia> <http://telicent.io/ontology/primaryName> "Iridonia" .
<https://starwars.com#cc64b494-9420-4708-a750-ec26fd7ccfd6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

