Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d7230ccf-a9a3-4f59-b4ce-c9283454dcb4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Garis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#d7230ccf-a9a3-4f59-b4ce-c9283454dcb4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Omwat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Omwat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Garis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Omwat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Garis> .
<https://starwars.com#sector_Garis> <http://telicent.io/ontology/primaryName> "Garis" .
<https://starwars.com#planet_Omwat> <http://www.w3.org/2000/01/rdf-schema#comment> "Omwat was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Omwat> <http://telicent.io/ontology/primaryName> "Omwat" .
<https://starwars.com#planet_Omwat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7230ccf-a9a3-4f59-b4ce-c9283454dcb4> .
<https://starwars.com#planet_Omwat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N18> .

