Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#587f7786-6f0c-4fd2-a30d-94dc3f67367d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Syngia> <http://www.w3.org/2000/01/rdf-schema#comment> "Syngia was a planet in the galaxy, located in the Sertar sector of the Outer Rim Territories. Syngia was also where the ancient Sith Lord Remulus Dreypa practiced his mastery over the creation of life, and where he left behind his mysterious Genesis pool. " .
<https://starwars.com#587f7786-6f0c-4fd2-a30d-94dc3f67367d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Syngia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Syngia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#587f7786-6f0c-4fd2-a30d-94dc3f67367d> .
<https://starwars.com#sector_Sertar> <http://telicent.io/ontology/primaryName> "Sertar" .
<https://starwars.com#sector_Sertar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Sertar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Syngia> <http://telicent.io/ontology/primaryName> "Syngia" .
<https://starwars.com#planet_Syngia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Syngia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Syngia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sertar> .

