Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdMantell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#planet_OrdMantell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdMantell> <http://www.w3.org/2000/01/rdf-schema#comment> "A planet where Han Solo tells of having a run-in with a bounty hunter." .
<https://starwars.com#e69db33b-c01d-4be3-b9ac-660aa05316d4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Mantell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e69db33b-c01d-4be3-b9ac-660aa05316d4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_OrdMantell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#planet_OrdMantell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e69db33b-c01d-4be3-b9ac-660aa05316d4> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdMantell> <http://telicent.io/ontology/primaryName> "Ord Mantell" .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .

