Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#31447453-ffbe-4e9c-8e78-c106786076ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Adarlon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#6c9f87f9-8e8d-48ff-98b0-6913f6e32ff8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Adarlon> <http://www.w3.org/2000/01/rdf-schema#comment> "Adarlon was a location whose population supposedly suffered a famine while under the control of the New Republic, according to claims made in the news feeds of the First Order. The stormtrooper FN-2187 viewed such a news report during a morale session within his training on Starkiller Base, shortly before his deployment to the planet Jakku in 34 ABY. " .
<https://starwars.com#planet_Adarlon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Adarlon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Minos> .
<https://starwars.com#grid_M20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M20> <http://telicent.io/ontology/primaryName> "M20" .
<https://starwars.com#planet_Adarlon> <http://telicent.io/ontology/primaryName> "Adarlon" .
<https://starwars.com#sector_Minos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#6c9f87f9-8e8d-48ff-98b0-6913f6e32ff8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_M20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#6c9f87f9-8e8d-48ff-98b0-6913f6e32ff8> .
<https://starwars.com#sector_Minos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Minos> <http://telicent.io/ontology/primaryName> "Minos" .
<https://starwars.com#planet_Adarlon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31447453-ffbe-4e9c-8e78-c106786076ea> .
<https://starwars.com#planet_Adarlon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#31447453-ffbe-4e9c-8e78-c106786076ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

