Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Levian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Levian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#f922970d-810a-4b4f-a7dd-fbd93a9acaf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Levian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Levian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f922970d-810a-4b4f-a7dd-fbd93a9acaf0> .
<https://starwars.com#planet_Levian> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#f922970d-810a-4b4f-a7dd-fbd93a9acaf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Levian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Levian> <http://telicent.io/ontology/primaryName> "Levian" .

