Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_M12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#25aeb2dc-c679-4639-9077-c24661fca55c> .
<https://starwars.com#planet_AratFraca> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_AratFraca> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1513bbf5-49d3-4815-b463-2542e5e19a30> .
<https://starwars.com#25aeb2dc-c679-4639-9077-c24661fca55c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1513bbf5-49d3-4815-b463-2542e5e19a30> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_M12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M12> <http://telicent.io/ontology/primaryName> "M12" .
<https://starwars.com#planet_AratFraca> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_AratFraca> <http://telicent.io/ontology/primaryName> "Arat Fraca" .
<https://starwars.com#1513bbf5-49d3-4815-b463-2542e5e19a30> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arat Fraca"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#25aeb2dc-c679-4639-9077-c24661fca55c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_M12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_AratFraca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_AratFraca> <http://www.w3.org/2000/01/rdf-schema#comment> "Arat Fraca was a planet located in the Arat Fraca system of the Colonies. The Star Morning suddenly reappeared over Arat Fraca a year after leaving Motexx for Gowdawl. Arat Fraca was two sectors away from Motexx. From Arat Fraca, the Star Morning proceeded to Darepp, where it landed. " .

