Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Wroona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Wroona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#planet_Wroona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a554aa38-df00-4f9a-b9d4-3dc3dfca660e> .
<https://starwars.com#planet_Wroona> <http://telicent.io/ontology/primaryName> "Wroona" .
<https://starwars.com#planet_Wroona> <http://www.w3.org/2000/01/rdf-schema#comment> "Wroona was an astronomical object located in the region known as the Inner Rim Territories. It lay at grid square L-15 on the Standard Galactic Grid, where it was situated along the Rimma Trade Route. " .
<https://starwars.com#planet_Wroona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#a554aa38-df00-4f9a-b9d4-3dc3dfca660e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a554aa38-df00-4f9a-b9d4-3dc3dfca660e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wroona"^^<http://www.w3.org/2001/XMLSchema#string> .

