Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ragoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Ragoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Ragoon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#34d7c90f-2014-4e69-81a9-bcf869c31d05> .
<https://starwars.com#34d7c90f-2014-4e69-81a9-bcf869c31d05> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ragoon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ragoon> <http://telicent.io/ontology/primaryName> "Ragoon" .
<https://starwars.com#planet_Ragoon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#34d7c90f-2014-4e69-81a9-bcf869c31d05> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ragoon> <http://www.w3.org/2000/01/rdf-schema#comment> "The Ragoons were the native sentient species of the planet Ragoon VI. A short species with brown, leathery skin, they had long and pointed ears. Ragoon society was pre-industrial, as the species preferred to keep the environment of their homeworld pristine and free from exploitation. In order to achieve that, they forbade colonization of Ragoon VI, and, when their numbers dwindled through sickness, entrusted their planet to the Galactic Republic Senate for safekeeping. Offworld visitors were then restricted, although members of the Jedi Order and the inhabitants of the neighboring planet Aaeton were allowed to visit more frequently. The Jedi Qui-Gon Jinn and Obi-Wan Kenobi encountered a group of Ragoons during a training mission to the world. " .

