Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L21> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#2858dc7e-1225-407f-bc9b-d3cff71abede> .
<https://starwars.com#planet_Shiva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L21> .
<https://starwars.com#084a1f9b-5974-4b76-89e9-650175c6ec86> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shiva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#2858dc7e-1225-407f-bc9b-d3cff71abede> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L21"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L21> <http://telicent.io/ontology/primaryName> "L21" .
<https://starwars.com#planet_Shiva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shiva> <http://www.w3.org/2000/01/rdf-schema#comment> "Shiva IV was a planet in Wild Space that was noted for its extremely remote location, far from the auspices of the Galactic Empire. A world with a history soaked in blood, Shiva IV was marked by generations of warfare between the Human Calian Confederacy and the Twelve Tribes of T'Syriél, which forged both peoples into extremely formidable fighters. In 2 ABY, that conflict was finally brought to an end when Calian Warlord Aron Peacebringer signed the Concordat of Peace with T'Syriél Demarch Kéral Longknife. Although the Galactic Empire attempted to conquer Shiva IV one year later, Peacebringer and elements of the Rebel Alliance repelled the invasion. " .
<https://starwars.com#grid_L21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#084a1f9b-5974-4b76-89e9-650175c6ec86> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shiva"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#2858dc7e-1225-407f-bc9b-d3cff71abede> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Shiva> <http://telicent.io/ontology/primaryName> "Shiva" .
<https://starwars.com#grid_L21> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Shiva> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#084a1f9b-5974-4b76-89e9-650175c6ec86> .

