Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Balnab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#planet_Balnab> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ff4714ac-f63a-4d29-bd21-6c95022cff88> .
<https://starwars.com#ff4714ac-f63a-4d29-bd21-6c95022cff88> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Balnab"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Balnab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#ff4714ac-f63a-4d29-bd21-6c95022cff88> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Balnab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .
<https://starwars.com#planet_Balnab> <http://www.w3.org/2000/01/rdf-schema#comment> "A Barbaric world once visited by R2-D2 and C-3PO." .
<https://starwars.com#planet_Balnab> <http://telicent.io/ontology/primaryName> "Balnab" .

