Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ebra> <http://telicent.io/ontology/primaryName> "Ebra" .
<https://starwars.com#grid_L6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_L6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b11e39b2-feb0-4eb8-85e6-19dd5b232032> .
<https://starwars.com#8cbf1123-b5ce-48f6-9205-1c5a53ca1b60> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ebra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b11e39b2-feb0-4eb8-85e6-19dd5b232032> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kesh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b11e39b2-feb0-4eb8-85e6-19dd5b232032> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Ebra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L6> <http://telicent.io/ontology/primaryName> "L6" .
<https://starwars.com#sector_Kesh> <http://telicent.io/ontology/primaryName> "Kesh" .
<https://starwars.com#sector_Kesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_L6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Ebra> <http://www.w3.org/2000/01/rdf-schema#comment> "The Galactic Empire subjugated Ebra, enslaving the Ebranites and forcing them to harvest lu-ramin. After the Ebranite sisters Rith Tar'ak, Nyik, and Tor'ara escaped Ebra and joined the Rebel Alliance, hundreds of Ebranites became members of the Alliance in order to fight the Empire on Ebra. By 12 ABY, Ebra was a part of the New Republic. " .
<https://starwars.com#8cbf1123-b5ce-48f6-9205-1c5a53ca1b60> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ebra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8cbf1123-b5ce-48f6-9205-1c5a53ca1b60> .
<https://starwars.com#planet_Ebra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L6> .
<https://starwars.com#planet_Ebra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kesh> .

