Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#81f78686-115a-4f01-bf2c-6df8c6f8ee85> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kadavo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kadavo> <http://telicent.io/ontology/primaryName> "Kadavo" .
<https://starwars.com#81f78686-115a-4f01-bf2c-6df8c6f8ee85> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kadavo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Kadavo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kadavo> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#planet_Kadavo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#81f78686-115a-4f01-bf2c-6df8c6f8ee85> .
<https://starwars.com#planet_Kadavo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .

