Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f9f1acf2-e5ac-4af2-844b-d534d532e296> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pygorix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f9f1acf2-e5ac-4af2-844b-d534d532e296> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pygorix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f9f1acf2-e5ac-4af2-844b-d534d532e296> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pygorix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pygorix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Pygorix> <http://www.w3.org/2000/01/rdf-schema#comment> "Pygorix was a planet in the Gordian Reach of the Outer Rim Territories. " .
<https://starwars.com#planet_Pygorix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Pygorix> <http://telicent.io/ontology/primaryName> "Pygorix" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

