Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#79f1b400-3c14-448d-b60a-03cc69653b64> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pesmenben> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#79f1b400-3c14-448d-b60a-03cc69653b64> .
<https://starwars.com#planet_Pesmenben> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pesmenben> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q11> .
<https://starwars.com#planet_Pesmenben> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Teraab> .
<https://starwars.com#planet_Pesmenben> <http://telicent.io/ontology/primaryName> "Pesmenben" .
<https://starwars.com#79f1b400-3c14-448d-b60a-03cc69653b64> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pesmenben"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pesmenben> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Teraab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Teraab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Teraab> <http://telicent.io/ontology/primaryName> "Teraab" .

