Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cirus> <http://telicent.io/ontology/primaryName> "Cirus" .
<https://starwars.com#planet_Cirus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Cirus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b05f26bd-4062-4f68-a467-f314b3a4f4f9> .
<https://starwars.com#planet_Cirus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b05f26bd-4062-4f68-a467-f314b3a4f4f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cirus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cirus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b05f26bd-4062-4f68-a467-f314b3a4f4f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cirus> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

