Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cortina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Cortina> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6fd61566-3ade-4c1a-8c6e-224836081303> .
<https://starwars.com#planet_Cortina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Cortina> <http://telicent.io/ontology/primaryName> "Cortina" .
<https://starwars.com#6fd61566-3ade-4c1a-8c6e-224836081303> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cortina"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cortina> <http://www.w3.org/2000/01/rdf-schema#comment> "Cortina was a planet directly represented in the New Republic Senate. Its government attempted to push its application to the New Republic through, thinking itself superior, but eventually calmed down and earned membership. " .
<https://starwars.com#6fd61566-3ade-4c1a-8c6e-224836081303> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cortina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

