Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Commenor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Commenor> <http://www.w3.org/2000/01/rdf-schema#comment> "Commenor was an ancient, conservative planet located in the Colonies region of the galaxy. " .
<https://starwars.com#55d992fe-577a-4c6b-a4a7-dd98401749a0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Commenor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c79e768c-2823-4bcf-a7f2-9b169bb0dc5e> .
<https://starwars.com#55d992fe-577a-4c6b-a4a7-dd98401749a0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Commenor> <http://telicent.io/ontology/primaryName> "Commenor" .
<https://starwars.com#c79e768c-2823-4bcf-a7f2-9b169bb0dc5e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Commenor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#c79e768c-2823-4bcf-a7f2-9b169bb0dc5e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Commenor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#55d992fe-577a-4c6b-a4a7-dd98401749a0> .
<https://starwars.com#grid_N10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_N10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Commenor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_N10> <http://telicent.io/ontology/primaryName> "N10" .

