Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Thesme> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Thesme> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#45af62df-33ee-42ff-8119-4314de64d766> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_JunctionV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_JunctionV> <http://www.w3.org/2000/01/rdf-schema#comment> "The people of Junction 5 and Delaluna made peace shortly before the Clone Wars and joined with the people of Vicondor and Bezim to build the Station 88 Spaceport. This coalition of planets chose to remain loyal to the Galactic Republic during the Clone Wars." .
<https://starwars.com#planet_JunctionV> <http://telicent.io/ontology/primaryName> "Junction V" .
<https://starwars.com#45af62df-33ee-42ff-8119-4314de64d766> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Junction V"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Thesme> <http://telicent.io/ontology/primaryName> "Thesme" .
<https://starwars.com#planet_JunctionV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#planet_JunctionV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#45af62df-33ee-42ff-8119-4314de64d766> .
<https://starwars.com#planet_JunctionV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thesme> .

