Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a399f7af-043d-4bb3-ba8d-a6fcf9f764b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Tessebok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Irishi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a399f7af-043d-4bb3-ba8d-a6fcf9f764b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdTessebok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#planet_OrdTessebok> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Tessebok was a Mid Rim world on the Entralla Route. Originally an Ordnance/Regional Depot, the planet was open to immigration sponsored by the Refugee Relief Movement in 22 BBY, shortly before the Clone Wars. At that time, its population had already grown to 2.5 billion people. " .
<https://starwars.com#planet_OrdTessebok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Irishi> .
<https://starwars.com#planet_OrdTessebok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a399f7af-043d-4bb3-ba8d-a6fcf9f764b5> .
<https://starwars.com#sector_Irishi> <http://telicent.io/ontology/primaryName> "Irishi" .
<https://starwars.com#planet_OrdTessebok> <http://telicent.io/ontology/primaryName> "Ord Tessebok" .
<https://starwars.com#sector_Irishi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_OrdTessebok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

