Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Corann> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#9fe257a7-3bd1-4deb-8dde-7e58a5304705> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corann"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Corann> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9fe257a7-3bd1-4deb-8dde-7e58a5304705> .
<https://starwars.com#9fe257a7-3bd1-4deb-8dde-7e58a5304705> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Corann> <http://telicent.io/ontology/primaryName> "Corann" .
<https://starwars.com#planet_Corann> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Corann> <http://www.w3.org/2000/01/rdf-schema#comment> "Corann was a planet in the Core Worlds. " .
<https://starwars.com#planet_Corann> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

