Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pirin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef3bc773-502f-45dc-ac9e-3c0928c04c67> .
<https://starwars.com#ef3bc773-502f-45dc-ac9e-3c0928c04c67> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ef3bc773-502f-45dc-ac9e-3c0928c04c67> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pirin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pirin> <http://www.w3.org/2000/01/rdf-schema#comment> "Pirin was a planet in Locris sector. It was the headquarters of Kontag. " .
<https://starwars.com#planet_Pirin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Locris> .
<https://starwars.com#planet_Pirin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Pirin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Locris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Locris> <http://telicent.io/ontology/primaryName> "Locris" .
<https://starwars.com#sector_Locris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Pirin> <http://telicent.io/ontology/primaryName> "Pirin" .

