Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pencael> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_Pencael> <http://telicent.io/ontology/primaryName> "Pencael" .
<https://starwars.com#planet_Pencael> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#692b31f0-a01a-46b3-8c2e-b06ec497ca57> .
<https://starwars.com#692b31f0-a01a-46b3-8c2e-b06ec497ca57> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pencael"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pencael> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Pencael> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#692b31f0-a01a-46b3-8c2e-b06ec497ca57> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pencael> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

