Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Bextar> <http://telicent.io/ontology/primaryName> "Bextar" .
<https://starwars.com#planet_Bextar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b69debaa-ad51-426d-8978-51afc479c32a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Bextar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Velcar> .
<https://starwars.com#sector_Velcar> <http://telicent.io/ontology/primaryName> "Velcar" .
<https://starwars.com#planet_Bextar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#b69debaa-ad51-426d-8978-51afc479c32a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bextar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d60c0717-74bf-4bac-9ac0-9722e5551a08> .
<https://starwars.com#d60c0717-74bf-4bac-9ac0-9722e5551a08> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bextar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d60c0717-74bf-4bac-9ac0-9722e5551a08> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bextar> <http://www.w3.org/2000/01/rdf-schema#comment> "Bextar was one of four gas giants in the Velcar Free Commerce Zone's Bextar system. It was the site of several Amber Sun Mining Corporate gas mines. Amber Sun imported Entymal slaves as miners. " .
<https://starwars.com#grid_J4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_J4> <http://telicent.io/ontology/primaryName> "J4" .
<https://starwars.com#sector_Velcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_J4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b69debaa-ad51-426d-8978-51afc479c32a> .
<https://starwars.com#sector_Velcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

