Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Demophon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9656606b-abb1-4c28-a718-8b87fc3a55b3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Demophon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Demophon> <http://www.w3.org/2000/01/rdf-schema#comment> "Demophon was a planet in the Core Worlds, the primary planet of the Demophon system. The planet had two continents, Junno and Klis, which were surrounded by a vast ocean. It was named for Alres Demophon, one of the founders of the Republic Scout Service. " .
<https://starwars.com#planet_Demophon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9656606b-abb1-4c28-a718-8b87fc3a55b3> .
<https://starwars.com#planet_Demophon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Demophon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Demophon> <http://telicent.io/ontology/primaryName> "Demophon" .
<https://starwars.com#9656606b-abb1-4c28-a718-8b87fc3a55b3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

