Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#23730428-f779-4ce8-a018-a61f368d8bf3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Elphrona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Elphrona> <http://telicent.io/ontology/primaryName> "Elphrona" .
<https://starwars.com#23730428-f779-4ce8-a018-a61f368d8bf3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elphrona"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Elphrona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#23730428-f779-4ce8-a018-a61f368d8bf3> .
<https://starwars.com#planet_Elphrona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#planet_Elphrona> <http://www.w3.org/2000/01/rdf-schema#comment> "Elphrona was a rocky planet in the Outer Rim Territories, on the edge of the Unknown Regions. It was home to an ancient High Republic Era Jedi outpost used as a treasure trove for a number of artifacts. While attempting to rebuild the Jedi Order, the Jedi Master Luke Skywalker visited the outpost with the explorer Lor San Tekka and his own student, Ben Solo. After escaping the destruction of Skywalker's Jedi temple and intending to join the dark side organization known as the Knights of Ren, Solo was tracked to Elphrona by Hennix, Tai, and Voe, three of Skywalker's students who survived. In the resulting duel, Hennix was killed, and Solo escaped, leaving Tai and Voe trapped in the ruins of the Jedi outpost." .
<https://starwars.com#planet_Elphrona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

