Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Usk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c6e7bb24-da98-4444-94c9-2dc6c81b7791> .
<https://starwars.com#planet_Usk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Usk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c6e7bb24-da98-4444-94c9-2dc6c81b7791> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Usk> <http://telicent.io/ontology/primaryName> "Usk" .
<https://starwars.com#planet_Usk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Usk> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#c6e7bb24-da98-4444-94c9-2dc6c81b7791> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Usk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

