Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5e876f16-e53e-487a-bd74-910b0c793bbe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tenara> <http://telicent.io/ontology/primaryName> "Tenara" .
<https://starwars.com#planet_Tenara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5e876f16-e53e-487a-bd74-910b0c793bbe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tenara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tenara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tenara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Tenara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5e876f16-e53e-487a-bd74-910b0c793bbe> .
<https://starwars.com#planet_Tenara> <http://www.w3.org/2000/01/rdf-schema#comment> "Tenara was a planet that was located in the Tenara system. It was situated in the Back Reach area of the Gordian Reach sector, within the Trans-Hydian portion of the Outer Rim Territories. A small hyperlane connected Tenara to the planet Korphir. " .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

