Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Seltos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vish> .
<https://starwars.com#sector_Vish> <http://telicent.io/ontology/primaryName> "Vish" .
<https://starwars.com#6a9c2694-0bc4-4e3b-944d-539cd9039b3c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Seltos> <http://telicent.io/ontology/primaryName> "Seltos" .
<https://starwars.com#sector_Vish> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Seltos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Seltos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#planet_Seltos> <http://www.w3.org/2000/01/rdf-schema#comment> "Seltos was a planet in the Mid Rim. Its Sommin City was home to the largest Tarro remnant. Its primary industries included agriculture, lumber production, and mining of valuable ores. Visitors to Seltos' nature preserves provided a small boost to the economy as well. Natives of Seltos were considered congenial and pleasant. " .
<https://starwars.com#6a9c2694-0bc4-4e3b-944d-539cd9039b3c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Seltos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Seltos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a9c2694-0bc4-4e3b-944d-539cd9039b3c> .

