Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shusugaunt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#0a99d4b8-c103-4d63-82f5-f6e39dc5a67c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shusugaunt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shusugaunt> <http://telicent.io/ontology/primaryName> "Shusugaunt" .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shusugaunt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Shusugaunt> <http://www.w3.org/2000/01/rdf-schema#comment> "Centuries later, archaeologists of the Galactic Republic discovered the bones of the previously-unknown Anx on Shusugaunt, initially believing them to be the remains of a native species of aquatic creature. Eventually, Shusugaunt became a part of the Republic's Raioballo sector and had sanctions placed against its native Shusugaunt by the Galactic Senate. The Anx Senator Horox Ryyder of the sector subsequently attempted to have the sanctions eased. Between 4 ABY and 12 ABY, Shusugaunt was situated in the territory of the Pentastar Alignment. " .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#0a99d4b8-c103-4d63-82f5-f6e39dc5a67c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shusugaunt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0a99d4b8-c103-4d63-82f5-f6e39dc5a67c> .
<https://starwars.com#planet_Shusugaunt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

