Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Giju> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Giju> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Giju> <http://www.w3.org/2000/01/rdf-schema#comment> "Giju was a planet located in the galaxy's Colonies region along the Rimma Trade Route. Shortly after the Battle of Yavin, Red Squadron from the Alliance to Restore the Republic evacuated rebel leaders from Giju before they could be discovered by Imperial agents. " .
<https://starwars.com#planet_Giju> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#caacea1e-5972-406d-ad40-7f3599a38517> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#caacea1e-5972-406d-ad40-7f3599a38517> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Giju"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Giju> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#caacea1e-5972-406d-ad40-7f3599a38517> .
<https://starwars.com#planet_Giju> <http://telicent.io/ontology/primaryName> "Giju" .

