Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lorahns> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sloo> .
<https://starwars.com#planet_Lorahns> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sloo> <http://telicent.io/ontology/primaryName> "Sloo" .
<https://starwars.com#planet_Lorahns> <http://telicent.io/ontology/primaryName> "Lorahns" .
<https://starwars.com#planet_Lorahns> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#305eace2-8161-4eba-a51d-8b8f7d4db647> .
<https://starwars.com#sector_Sloo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Lorahns> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#305eace2-8161-4eba-a51d-8b8f7d4db647> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lorahns> <http://www.w3.org/2000/01/rdf-schema#comment> "Lorahns was an astronomical object located in the regions known as the Mid Rim Territories and the Slice. It was also situated within grid square P-14 on the Standard Galactic Grid. It shared its name with the gravitational sink nicknamed Lorahns Cavity by the locals of the planet Vandor. " .
<https://starwars.com#sector_Sloo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#305eace2-8161-4eba-a51d-8b8f7d4db647> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lorahns"^^<http://www.w3.org/2001/XMLSchema#string> .

