Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Valtos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#359982ee-0488-48df-8b08-732bac3e154c> .
<https://starwars.com#planet_Valtos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Valtos> <http://telicent.io/ontology/primaryName> "Valtos" .
<https://starwars.com#planet_Valtos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#359982ee-0488-48df-8b08-732bac3e154c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Valtos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#359982ee-0488-48df-8b08-732bac3e154c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

