Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c21af73f-adab-4b80-a9df-fb5fbcfeef57> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Teardrop> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Teardrop> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Teardrop> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c21af73f-adab-4b80-a9df-fb5fbcfeef57> .
<https://starwars.com#planet_Teardrop> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#c21af73f-adab-4b80-a9df-fb5fbcfeef57> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Teardrop"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Teardrop> <http://www.w3.org/2000/01/rdf-schema#comment> "Teardrop was a planet located in Shelsha sector. It contained Por'ste Island and was near Briston. " .
<https://starwars.com#planet_Teardrop> <http://telicent.io/ontology/primaryName> "Teardrop" .

