Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nubia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#5296baf4-c4e2-4f9d-811e-b247db8bf646> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nubia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5296baf4-c4e2-4f9d-811e-b247db8bf646> .
<https://starwars.com#planet_Nubia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5296baf4-c4e2-4f9d-811e-b247db8bf646> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nubia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nubia> <http://telicent.io/ontology/primaryName> "Nubia" .
<https://starwars.com#planet_Nubia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Nubia> <http://www.w3.org/2000/01/rdf-schema#comment> "Nubia was a world home to Industrial Automaton droid factories and Nubian Design Collective shipyards. " .

