Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ziugen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ziugen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Ziugen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T12> .
<https://starwars.com#planet_Ziugen> <http://www.w3.org/2000/01/rdf-schema#comment> "Ziugen was a slave colony world that was located within the Ziugen system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet lay on the hyperlane called the Shag Pabol that connected it to the world of Ylesia and the Outland Transit Station. A smaller hyperspace route also linked Ziugen to the planet of Poytta. The inhabitants of Ziugen were equally devoted to industry and agriculture. " .
<https://starwars.com#planet_Ziugen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#29de4fa8-d1b1-4d29-bf64-cc2d48e80fd3> .
<https://starwars.com#29de4fa8-d1b1-4d29-bf64-cc2d48e80fd3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ziugen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ziugen> <http://telicent.io/ontology/primaryName> "Ziugen" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#29de4fa8-d1b1-4d29-bf64-cc2d48e80fd3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

