Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_K8> <http://telicent.io/ontology/primaryName> "K8" .
<https://starwars.com#planet_Aphran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#3a18af03-681f-4639-bc73-c880af67d342> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_K8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#e8fd0f52-30c3-4e88-815d-0330f1772c3b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aphran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aphran> <http://telicent.io/ontology/primaryName> "Aphran" .
<https://starwars.com#planet_Aphran> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a18af03-681f-4639-bc73-c880af67d342> .
<https://starwars.com#e8fd0f52-30c3-4e88-815d-0330f1772c3b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aphran> <http://www.w3.org/2000/01/rdf-schema#comment> "Aphran was the Aphran system's primary. On Aphran IV, Aphran appeared as a red-gold orb during sunset, making its green-blue lakes appear as brilliant gold. " .
<https://starwars.com#grid_K8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e8fd0f52-30c3-4e88-815d-0330f1772c3b> .
<https://starwars.com#3a18af03-681f-4639-bc73-c880af67d342> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aphran"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aphran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#grid_K8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

