Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Fath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_JanFathal> <http://www.w3.org/2000/01/rdf-schema#comment> "JanFathal was a planet in the Outer Rim Territories and was once part of the Republic. The city of Athar was its capital. " .
<https://starwars.com#f9edacad-ab63-48ac-9bd4-8138ff4aef27> <http://ies.data.gov.uk/ontology/ies4#representationValue> "JanFathal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_JanFathal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#planet_JanFathal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_JanFathal> <http://telicent.io/ontology/primaryName> "JanFathal" .
<https://starwars.com#f9edacad-ab63-48ac-9bd4-8138ff4aef27> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_JanFathal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f9edacad-ab63-48ac-9bd4-8138ff4aef27> .
<https://starwars.com#sector_Fath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Fath> <http://telicent.io/ontology/primaryName> "Fath" .
<https://starwars.com#planet_JanFathal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Fath> .

