Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Atchorb> <http://telicent.io/ontology/primaryName> "Atchorb" .
<https://starwars.com#f84e6375-1737-4be6-ad8d-a8fa0f931102> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Atchorb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Atchorb> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f84e6375-1737-4be6-ad8d-a8fa0f931102> .
<https://starwars.com#planet_Atchorb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#f84e6375-1737-4be6-ad8d-a8fa0f931102> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atchorb"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Atchorb> <http://www.w3.org/2000/01/rdf-schema#comment> "Atchorb was a world located in the Atchorb system of the Corporate Sector, a part of the Trans-Hydian portion of the Outer Rim Territories. The hyperlane known as the Shaltin Tunnels linked Atchorb to the D'ian and Ulicia systems, while the Authority Guardian Corridor connected it to the Hiit and Tothis systems. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Atchorb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

