Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Roxuli> <http://telicent.io/ontology/primaryName> "Roxuli" .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1a74684b-5521-45fe-b5ca-d22fbcad177d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Roxuli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Roxuli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a74684b-5521-45fe-b5ca-d22fbcad177d> .
<https://starwars.com#planet_Roxuli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Roxuli> <http://www.w3.org/2000/01/rdf-schema#comment> "Roxuli was an astronomical object in the galaxy's Expansion Region. " .
<https://starwars.com#planet_Roxuli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Roxuli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I8> .
<https://starwars.com#1a74684b-5521-45fe-b5ca-d22fbcad177d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

