Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Drackmar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drackmar> <http://www.w3.org/2000/01/rdf-schema#comment> "Drackmar was the Drackmarian homeworld, located in the Drackmar system, in the Quelii sector of the Outer Rim Territories. The atmosphere of Drackmar was composed of methane, requiring native Drackmarians to wear special methane helmets when traveling off-world. On the other hand, oxygen-breathing species could use environmentally-sealed vehicles, such as the Orbitblade-2000, to visit the planet. " .
<https://starwars.com#planet_Drackmar> <http://telicent.io/ontology/primaryName> "Drackmar" .
<https://starwars.com#sector_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Drackmar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#09e4aaf4-1e93-4081-b462-56ff0d869acf> .
<https://starwars.com#sector_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#planet_Drackmar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quelii> .
<https://starwars.com#09e4aaf4-1e93-4081-b462-56ff0d869acf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#09e4aaf4-1e93-4081-b462-56ff0d869acf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drackmar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Drackmar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .

