Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lannik> <http://www.w3.org/2000/01/rdf-schema#comment> "Lannik was a planet with a long history of war that was located in the galaxy's Mid Rim and was the homeworld of the Lannik species. " .
<https://starwars.com#planet_Lannik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R13> .
<https://starwars.com#planet_Lannik> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7b642fbe-b1e5-4ebe-a37b-0892bf810725> .
<https://starwars.com#planet_Lannik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7b642fbe-b1e5-4ebe-a37b-0892bf810725> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_LanicSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_LanicSpace> <http://telicent.io/ontology/primaryName> "Lanic Space" .
<https://starwars.com#sector_LanicSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#7b642fbe-b1e5-4ebe-a37b-0892bf810725> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lannik"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lannik> <http://telicent.io/ontology/primaryName> "Lannik" .
<https://starwars.com#planet_Lannik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_LanicSpace> .

