Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Copero> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6e717ebe-f731-4a44-ade3-859b9937e243> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Copero> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Copero> <http://telicent.io/ontology/primaryName> "Copero" .
<https://starwars.com#planet_Copero> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6e717ebe-f731-4a44-ade3-859b9937e243> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#6e717ebe-f731-4a44-ade3-859b9937e243> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Copero"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Copero> <http://www.w3.org/2000/01/rdf-schema#comment> "Copero was an astronomical object of the Chiss Ascendancy located in the Unknown Regions, situated in a star system near the Ascendancy's east and southeast sectors. It was a location of significance to the Chiss Erighal family, one of the forty Great Families of the Ascendancy. Around 18 BBY, Erighal warriors were called to Copero to activate Expeditionary Force Alpha with the purpose to claim a nyix mine located on the world of Hoxim. " .
<https://starwars.com#planet_Copero> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F9> .

