Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Talhovi> <http://www.w3.org/2000/01/rdf-schema#comment> "Talhovi was a planet located in the Talhovi system of the Juvex sector, in the Mid Rim of the galaxy. It was homeworld of House Mekuun. The Talhovian ale was from this planet. " .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Talhovi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Talhovi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#febbbdd6-3ca0-4a30-8a32-a669e2c5f973> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Talhovi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#febbbdd6-3ca0-4a30-8a32-a669e2c5f973> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#febbbdd6-3ca0-4a30-8a32-a669e2c5f973> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Talhovi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Talhovi> <http://telicent.io/ontology/primaryName> "Talhovi" .
<https://starwars.com#planet_Talhovi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

