Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_BiminThree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#planet_BiminThree> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cd7296bb-2be7-4d9b-8064-5c476dce767a> .
<https://starwars.com#sector_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_BiminThree> <http://telicent.io/ontology/primaryName> "Bimin Three" .
<https://starwars.com#cd7296bb-2be7-4d9b-8064-5c476dce767a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bimin Three"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#cd7296bb-2be7-4d9b-8064-5c476dce767a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_BiminThree> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_BiminThree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Majoor> .
<https://starwars.com#sector_Majoor> <http://telicent.io/ontology/primaryName> "Majoor" .
<https://starwars.com#sector_Majoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_BiminThree> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

