Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Relephon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Relephon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Relephon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c6ee9af9-5fb7-4938-815a-f3e3fadce648> .
<https://starwars.com#planet_Relephon> <http://telicent.io/ontology/primaryName> "Relephon" .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c6ee9af9-5fb7-4938-815a-f3e3fadce648> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#c6ee9af9-5fb7-4938-815a-f3e3fadce648> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Relephon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Relephon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Relephon> <http://www.w3.org/2000/01/rdf-schema#comment> "Relephon was a gas giant in the Hapes Cluster orbited by the Relephon Moons, of which several were populated. " .

