Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tennuutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Salvara> <http://telicent.io/ontology/primaryName> "Salvara" .
<https://starwars.com#planet_Salvara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#sector_Tennuutta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Salvara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tennuutta> .
<https://starwars.com#c00dd35e-3023-44ad-a2a1-0c57d72f45ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Salvara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Salvara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Tennuutta> <http://telicent.io/ontology/primaryName> "Tennuutta" .
<https://starwars.com#c00dd35e-3023-44ad-a2a1-0c57d72f45ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Salvara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c00dd35e-3023-44ad-a2a1-0c57d72f45ab> .
<https://starwars.com#planet_Salvara> <http://www.w3.org/2000/01/rdf-schema#comment> "Salvara was a planet located in the Tennuutta sector of the Mid Rim. During the Clone Wars, the planet was located within Separatist space. It was the site of a battle between the Galactic Republic and the Confederacy of Independent Systems during the Clone Wars. " .

