Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kluistar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kluistar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54899511-00d8-4ae0-9bcd-dca3f1bd9b81> .
<https://starwars.com#54899511-00d8-4ae0-9bcd-dca3f1bd9b81> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kluistar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#54899511-00d8-4ae0-9bcd-dca3f1bd9b81> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kluistar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kluistar> <http://telicent.io/ontology/primaryName> "Kluistar" .
<https://starwars.com#planet_Kluistar> <http://www.w3.org/2000/01/rdf-schema#comment> "Kluistar was a planet on the border of the Colonies region, and was considered a comfortable if undistinguished world. " .
<https://starwars.com#planet_Kluistar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .

