Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Drinba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sombure> .
<https://starwars.com#planet_Drinba> <http://telicent.io/ontology/primaryName> "D'rinba" .
<https://starwars.com#planet_Drinba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#planet_Drinba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drinba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#88e6b858-a988-4d2b-bc3e-1004f5576fa2> .
<https://starwars.com#sector_Sombure> <http://telicent.io/ontology/primaryName> "Sombure" .
<https://starwars.com#88e6b858-a988-4d2b-bc3e-1004f5576fa2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sombure> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#88e6b858-a988-4d2b-bc3e-1004f5576fa2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "D'rinba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sombure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Drinba> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

