Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_P7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b9cc4b5f-e447-4a15-8d0c-3b52ddbf8ccf> .
<https://starwars.com#c5b5cbd7-0991-48e9-90f5-4e79c67d90b6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anteevy"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P7> <http://telicent.io/ontology/primaryName> "P7" .
<https://starwars.com#planet_Anteevy> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c5b5cbd7-0991-48e9-90f5-4e79c67d90b6> .
<https://starwars.com#planet_Anteevy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P7> .
<https://starwars.com#sector_Esuain> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b9cc4b5f-e447-4a15-8d0c-3b52ddbf8ccf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Anteevy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_P7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Anteevy> <http://www.w3.org/2000/01/rdf-schema#comment> "Anteevy was an astronomical object located on the edge of the galaxy's Mid Rim. During the reign of the Galactic Empire, the Empire maintained a facility known as Ice Station Beta on Anteevy. When a group of dissidents stole the Imperial corvette Carrion Spike from Moff Wilhuff Tarkin and used it to attack Galidraan Station, Anteevy and its Imperial facility were considered as potential targets for the ship-jackers. They, along with Lantillies and a facility on Cartao, were listed as theoretical targets by Vice Admiral Dodd Rancit of Naval Intelligence when he was questioned on the situation by Galactic Emperor Sheev Palpatine. " .
<https://starwars.com#sector_Esuain> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_P7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#b9cc4b5f-e447-4a15-8d0c-3b52ddbf8ccf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c5b5cbd7-0991-48e9-90f5-4e79c67d90b6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anteevy> <http://telicent.io/ontology/primaryName> "Anteevy" .
<https://starwars.com#sector_Esuain> <http://telicent.io/ontology/primaryName> "Esuain" .
<https://starwars.com#planet_Anteevy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esuain> .

