Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Byss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#be02c6cf-ffef-4e03-8b96-56fa6b0ef4bc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_K11> <http://telicent.io/ontology/primaryName> "K11" .
<https://starwars.com#planet_Byss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K11> .
<https://starwars.com#grid_K11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#1a7a8ee2-2247-4f59-b80d-858e3bdd2ca3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Byss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Byss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a7a8ee2-2247-4f59-b80d-858e3bdd2ca3> .
<https://starwars.com#be02c6cf-ffef-4e03-8b96-56fa6b0ef4bc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_K11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#be02c6cf-ffef-4e03-8b96-56fa6b0ef4bc> .
<https://starwars.com#planet_Byss> <http://telicent.io/ontology/primaryName> "Byss" .
<https://starwars.com#planet_Byss> <http://www.w3.org/2000/01/rdf-schema#comment> "Byss was a planet located within the galaxy's Deep Core with a Standard Galactic Grid coordinate of K-11. Only discovered late during the Old Republic, it was the endpoint of the Byss Run hyperspace route after Prakith. An unusual world with an uncanny glow caused by its sun, it was considered extremely important by Emperor Palpatine. " .
<https://starwars.com#1a7a8ee2-2247-4f59-b80d-858e3bdd2ca3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Byss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

