Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_Venestria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .
<https://starwars.com#planet_Venestria> <http://telicent.io/ontology/primaryName> "Venestria" .
<https://starwars.com#planet_Venestria> <http://www.w3.org/2000/01/rdf-schema#comment> "Venestria was an astronomical object located in the Venestria system, a part of the Clacis sector in the New Territories portion of the Outer Rim Territories. It lay on the Braxant Run hyperlane between the Muunilinst and Kwevron systems, and another hyperspace route linked it to the Cezith system. " .
<https://starwars.com#b741a958-6b23-4b1f-8106-55ed594b0e7f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Venestria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Venestria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Venestria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b741a958-6b23-4b1f-8106-55ed594b0e7f> .
<https://starwars.com#planet_Venestria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b741a958-6b23-4b1f-8106-55ed594b0e7f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

