Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Koradin> <http://telicent.io/ontology/primaryName> "Koradin" .
<https://starwars.com#sector_Koradin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#12b8ed61-1a9c-49d3-ae0d-ead7174dd4d4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Koradin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sump> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I18> .
<https://starwars.com#planet_Sump> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sump> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Koradin> .
<https://starwars.com#planet_Sump> <http://telicent.io/ontology/primaryName> "Sump" .
<https://starwars.com#planet_Sump> <http://www.w3.org/2000/01/rdf-schema#comment> "Sump was an astronomical object in the galaxy's Outer Rim Territories that was the homeworld of the Nuknog species. It was connected to the worlds of Shuraden, Eiram, and Merokia by hyperspace routes. " .
<https://starwars.com#12b8ed61-1a9c-49d3-ae0d-ead7174dd4d4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sump"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sump> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12b8ed61-1a9c-49d3-ae0d-ead7174dd4d4> .

