Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nuvar> <http://www.w3.org/2000/01/rdf-schema#comment> "Nuvar was a planet in the Mid Rim near the modern Hydian Way. In 3701 BBY, Freia Kallea's scoutship Hope crash-landed on uncharted Nuvar after it was crippled by the Neimoidians Thoax and Farge Osaax, leaving her stranded for six standard years. Banu Hydia located her on the planet and found her in a wild state. " .
<https://starwars.com#bbb82b14-8b53-4437-baad-51ccc46698bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nuvar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nuvar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bbb82b14-8b53-4437-baad-51ccc46698bf> .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#planet_Nuvar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .
<https://starwars.com#planet_Nuvar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#planet_Nuvar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nuvar> <http://telicent.io/ontology/primaryName> "Nuvar" .
<https://starwars.com#bbb82b14-8b53-4437-baad-51ccc46698bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

