Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Deneba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#03e13720-fab5-4213-94a0-691c62efb1ef> .
<https://starwars.com#planet_Deneba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maerdocia> .
<https://starwars.com#planet_Deneba> <http://telicent.io/ontology/primaryName> "Deneba" .
<https://starwars.com#planet_Deneba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Maerdocia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#03e13720-fab5-4213-94a0-691c62efb1ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Deneba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Maerdocia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Maerdocia> <http://telicent.io/ontology/primaryName> "Maerdocia" .
<https://starwars.com#03e13720-fab5-4213-94a0-691c62efb1ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Deneba> <http://www.w3.org/2000/01/rdf-schema#comment> "Deneba was a location in the galaxy. When Commerce Guild scout Tibbs Ospe discovered the planet Vandor, he figured the planet could be a stopping place for traders heading towards Deneba and Manda. By 10 BBY, Ospe fixed the ruins of Ypsobay Trading Company's headquarters and started advertising that traders could find fuel and food at Fort Ypso for their travels. At some point bartender Tivoche Bilure learned Ospe's story about Vandor and wrote it in his journal. " .
<https://starwars.com#planet_Deneba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .

