Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ishanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Circarpous> .
<https://starwars.com#sector_Circarpous> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Ishanna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f64dfbb8-aa78-4678-a68d-e8934217eb81> .
<https://starwars.com#f64dfbb8-aa78-4678-a68d-e8934217eb81> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ishanna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f64dfbb8-aa78-4678-a68d-e8934217eb81> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ishanna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ishanna> <http://www.w3.org/2000/01/rdf-schema#comment> "Ishanna was a location where the Ishanna inversion occurred, which hampered the performance of the rebel starship Nautilian. " .
<https://starwars.com#sector_Circarpous> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ishanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#planet_Ishanna> <http://telicent.io/ontology/primaryName> "Ishanna" .
<https://starwars.com#sector_Circarpous> <http://telicent.io/ontology/primaryName> "Circarpous" .

