Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorOktanivii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f5a12436-ecfe-4c1a-8f02-6dacf2bc1490> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_KorOktanivii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Oktanivii was a planet located in the Bootana Hutta region of Hutt Space. It was a Hutt throneworld. " .
<https://starwars.com#planet_KorOktanivii> <http://telicent.io/ontology/primaryName> "Kor Oktanivii" .
<https://starwars.com#f5a12436-ecfe-4c1a-8f02-6dacf2bc1490> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Oktanivii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f5a12436-ecfe-4c1a-8f02-6dacf2bc1490> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorOktanivii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorOktanivii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorOktanivii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

