Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Adin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b346b588-73b7-400b-a1cb-c1542962c2f5> .
<https://starwars.com#grid_M7> <http://telicent.io/ontology/primaryName> "M7" .
<https://starwars.com#planet_Adin> <http://www.w3.org/2000/01/rdf-schema#comment> "Adin was a planet in the Expansion Region, located on the Corsin Run of the Hydian Way. Few in the galactic community trusted the bureaucrats that the planets put in power. With the election of Senator Meido to the New Republic Senate thirteen years after the Battle of Endor, the planets dealings were closely watched by former Chief of State Leia Organa Solo. " .
<https://starwars.com#planet_Adin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#grid_M7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#region_ExpansionRegion> <http://telicent.io/ontology/primaryName> "Expansion Region" .
<https://starwars.com#sector_Lostar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_M7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#region_ExpansionRegion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Adin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lostar> .
<https://starwars.com#d1dd6b99-2270-49e3-821c-7226fb37c3b2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Adin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Lostar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#b346b588-73b7-400b-a1cb-c1542962c2f5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Adin> <http://telicent.io/ontology/primaryName> "Adin" .
<https://starwars.com#b346b588-73b7-400b-a1cb-c1542962c2f5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Adin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#region_ExpansionRegion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#d1dd6b99-2270-49e3-821c-7226fb37c3b2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lostar> <http://telicent.io/ontology/primaryName> "Lostar" .
<https://starwars.com#grid_M7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d1dd6b99-2270-49e3-821c-7226fb37c3b2> .

