Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_N12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#22217ce3-310f-4d99-883e-1cff4beb47fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#22217ce3-310f-4d99-883e-1cff4beb47fa> .
<https://starwars.com#grid_N12> <http://telicent.io/ontology/primaryName> "N12" .
<https://starwars.com#planet_Ailon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#58043321-2ff7-4548-ade6-b0c8a0c9077b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ailon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ailon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#58043321-2ff7-4548-ade6-b0c8a0c9077b> .
<https://starwars.com#planet_Ailon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ailon> <http://www.w3.org/2000/01/rdf-schema#comment> "Ailon was an astronomical object located in the galaxy's Inner Rim. " .
<https://starwars.com#58043321-2ff7-4548-ade6-b0c8a0c9077b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_N12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Ailon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Ailon> <http://telicent.io/ontology/primaryName> "Ailon" .
<https://starwars.com#22217ce3-310f-4d99-883e-1cff4beb47fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

