Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rainboh> <http://telicent.io/ontology/primaryName> "Rainboh" .
<https://starwars.com#98c6211e-8e24-4c62-bad1-51ee1c1fc5e1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rainboh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rainboh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#98c6211e-8e24-4c62-bad1-51ee1c1fc5e1> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rainboh> <http://www.w3.org/2000/01/rdf-schema#comment> "Rainboh was a terrestrial planet located in the Rainboh system of the Inner Rim's Hapes Cluster. Positioned among the Hapan Rim Worlds, Rainboh could be reached from the Great Rim Route or the Rynmar Trail hyperlanes via the planet Rynmar itself. " .
<https://starwars.com#98c6211e-8e24-4c62-bad1-51ee1c1fc5e1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rainboh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Rainboh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Rainboh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .

