Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zonju> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Zonju> <http://telicent.io/ontology/primaryName> "Zonju" .
<https://starwars.com#9e055ecb-4e7a-44fe-aae7-c3d4368dc011> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zonju> <http://www.w3.org/2000/01/rdf-schema#comment> "Zonju was the Zonju system's primary star. " .
<https://starwars.com#planet_Zonju> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J21> .
<https://starwars.com#planet_Zonju> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9e055ecb-4e7a-44fe-aae7-c3d4368dc011> .
<https://starwars.com#planet_Zonju> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9e055ecb-4e7a-44fe-aae7-c3d4368dc011> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zonju"^^<http://www.w3.org/2001/XMLSchema#string> .

