Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#22baf828-5aa5-478a-9412-37c00321f517> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_CatoNeimoidia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_CatoNeimoidia> <http://www.w3.org/2000/01/rdf-schema#comment> "Colony world of the Neimoidian species. The site of battles throughout the Clone Wars, notable for its 'Bridge Cities'. Also the site of Plo Koon's death during the Great Jedi Purge." .
<https://starwars.com#19a19fa3-c516-4938-b5e1-7adaad6a83a9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cato Neimoidia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CatoNeimoidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#19a19fa3-c516-4938-b5e1-7adaad6a83a9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#22baf828-5aa5-478a-9412-37c00321f517> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_CatoNeimoidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_CatoNeimoidia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#19a19fa3-c516-4938-b5e1-7adaad6a83a9> .
<https://starwars.com#grid_N11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_N11> <http://telicent.io/ontology/primaryName> "N11" .
<https://starwars.com#planet_CatoNeimoidia> <http://telicent.io/ontology/primaryName> "Cato Neimoidia" .
<https://starwars.com#grid_N11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#22baf828-5aa5-478a-9412-37c00321f517> .

