Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dalchon> <http://telicent.io/ontology/primaryName> "Dalchon" .
<https://starwars.com#planet_Dalchon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#949dc81e-1e7a-4be2-be5c-1c2dc76772e6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dalchon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dalchon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalchon> .
<https://starwars.com#sector_Dalchon> <http://telicent.io/ontology/primaryName> "Dalchon" .
<https://starwars.com#sector_Dalchon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#949dc81e-1e7a-4be2-be5c-1c2dc76772e6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dalchon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dalchon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dalchon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#949dc81e-1e7a-4be2-be5c-1c2dc76772e6> .
<https://starwars.com#planet_Dalchon> <http://www.w3.org/2000/01/rdf-schema#comment> "Dalchon could refer to several things: " .

