Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5fd338a6-e578-41c6-b3a2-6d1c9f07b8f4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5fd338a6-e578-41c6-b3a2-6d1c9f07b8f4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cirrus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dantus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Dantus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cirrus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#sector_Dantus> <http://telicent.io/ontology/primaryName> "Dantus" .
<https://starwars.com#planet_Cirrus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dantus> .
<https://starwars.com#planet_Cirrus> <http://telicent.io/ontology/primaryName> "Cirrus" .
<https://starwars.com#planet_Cirrus> <http://www.w3.org/2000/01/rdf-schema#comment> "Cirrus was a Outer Rim world orbiting two orange suns. It had golden seas and lovely cities, including the capital Ciran near a bay. It was the homeworld of Talesan Fry and his parents. " .
<https://starwars.com#planet_Cirrus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5fd338a6-e578-41c6-b3a2-6d1c9f07b8f4> .
<https://starwars.com#planet_Cirrus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

