Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_MintitianGrant> <http://telicent.io/ontology/primaryName> "Mintitian Grant" .
<https://starwars.com#sector_MintitianGrant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Montitia> <http://www.w3.org/2000/01/rdf-schema#comment> "Montitia was a poverty-stricken planet in the Montitia system of the Montitian Grant sector, located within the Expansion Region of the galaxy. The region of space around Montitia was explored between 1000 and 25 BBY, and during the Extorin Minor skirmishes, the world's populace was threatened by the Extorin aggressors and evacuated. Montitia was within unaligned space during the Clone Wars, and by the Imperial Period the planet was inhabited again and was controlled by the Galactic Empire. Its alien residents were often recruited by the Corporate Sector Authority to work on the Corporate Sector world of Duroon, where they were kept in near-slavery. The Human fringer Bash Fateau was born on Montitia. " .
<https://starwars.com#planet_Montitia> <http://telicent.io/ontology/primaryName> "Montitia" .
<https://starwars.com#planet_Montitia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Montitia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J15> .
<https://starwars.com#0c4d9130-08f6-448a-a16f-89b4a405d068> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Montitia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0c4d9130-08f6-448a-a16f-89b4a405d068> .
<https://starwars.com#planet_Montitia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_MintitianGrant> .
<https://starwars.com#sector_MintitianGrant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0c4d9130-08f6-448a-a16f-89b4a405d068> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Montitia"^^<http://www.w3.org/2001/XMLSchema#string> .

