Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Hevvrol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Hevvrol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Hevvrol> <http://telicent.io/ontology/primaryName> "Hevvrol" .
<https://starwars.com#planet_Triffis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fe65195e-5d06-46e0-84f2-ceaa24a1ea69> .
<https://starwars.com#planet_Triffis> <http://telicent.io/ontology/primaryName> "Triffis" .
<https://starwars.com#planet_Triffis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#fe65195e-5d06-46e0-84f2-ceaa24a1ea69> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Triffis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#planet_Triffis> <http://www.w3.org/2000/01/rdf-schema#comment> "Triffis was a planet within the galaxy. It was the homeworld of the Triffian podracer Ebe E. Endocott. " .
<https://starwars.com#planet_Triffis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hevvrol> .
<https://starwars.com#fe65195e-5d06-46e0-84f2-ceaa24a1ea69> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Triffis"^^<http://www.w3.org/2001/XMLSchema#string> .

