Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dela> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89ceaa0d-f244-442f-8480-7f67f8135830> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dela> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#planet_Dela> <http://www.w3.org/2000/01/rdf-schema#comment> "Dela was a female who was the sister of Lindon Javes. At some point, she was killed during hazardous maneuvers. By around 4 ABY, she was mentioned on Javes' Imperial record. " .
<https://starwars.com#planet_Dela> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Dela> <http://telicent.io/ontology/primaryName> "Dela" .
<https://starwars.com#planet_Dela> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#89ceaa0d-f244-442f-8480-7f67f8135830> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dela"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#89ceaa0d-f244-442f-8480-7f67f8135830> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

