Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c16c9935-a7e5-4b94-b77b-c764ac99edf5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Serat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Serat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Serat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Serat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Serat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c16c9935-a7e5-4b94-b77b-c764ac99edf5> .
<https://starwars.com#planet_Serat> <http://telicent.io/ontology/primaryName> "Serat" .
<https://starwars.com#planet_Serat> <http://www.w3.org/2000/01/rdf-schema#comment> "Serat was the Seratian homeworld. The aggressive nocturnal Tymps were native to Serat, and considered pests. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#c16c9935-a7e5-4b94-b77b-c764ac99edf5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

