Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_I19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Tunka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#652786b7-f142-4d20-aa18-ec07f73ebe6f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#652786b7-f142-4d20-aa18-ec07f73ebe6f> .
<https://starwars.com#652786b7-f142-4d20-aa18-ec07f73ebe6f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Absit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fe370a00-3be3-4485-b011-cf8d267ad113> .
<https://starwars.com#planet_Absit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tunka> .
<https://starwars.com#sector_Tunka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Absit> <http://telicent.io/ontology/primaryName> "Absit" .
<https://starwars.com#fe370a00-3be3-4485-b011-cf8d267ad113> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Absit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I19> .
<https://starwars.com#fe370a00-3be3-4485-b011-cf8d267ad113> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Absit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Absit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_I19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_I19> <http://telicent.io/ontology/primaryName> "I19" .
<https://starwars.com#planet_Absit> <http://www.w3.org/2000/01/rdf-schema#comment> "Absit was a planet located in the Absit system, a part of the Outer Rim Territories' Tunka sector. It was the homeworld of the sentient humanoid species known as the Yatir. " .
<https://starwars.com#sector_Tunka> <http://telicent.io/ontology/primaryName> "Tunka" .

