Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_Q5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#cd1332eb-94d5-42dc-a499-da6dd02bc0d9> .
<https://starwars.com#planet_Atorra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9d999c4f-f640-42db-b8f6-4f049df28145> .
<https://starwars.com#grid_Q5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Atorra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#cd1332eb-94d5-42dc-a499-da6dd02bc0d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#9d999c4f-f640-42db-b8f6-4f049df28145> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#9d999c4f-f640-42db-b8f6-4f049df28145> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atorra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q5> <http://telicent.io/ontology/primaryName> "Q5" .
<https://starwars.com#planet_Atorra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Atorra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#grid_Q5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Atorra> <http://telicent.io/ontology/primaryName> "Atorra" .
<https://starwars.com#planet_Atorra> <http://www.w3.org/2000/01/rdf-schema#comment> "Atorra was a planet located in the Atorra system. It was situated in the Back Reach area of the Gordian Reach sector, within the Trans-Hydian portion of the Outer Rim Territories. The planet was connected by the Ardan Cross hyperlane to the Troos and the Chenowei systems. " .
<https://starwars.com#cd1332eb-94d5-42dc-a499-da6dd02bc0d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

