Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Noolian> <http://telicent.io/ontology/primaryName> "Noolian" .
<https://starwars.com#planet_Dressel> <http://www.w3.org/2000/01/rdf-schema#comment> "Dressel was an astronomical object located in the galaxy's Mid Rim that was the homeworld of the Dressellian species. " .
<https://starwars.com#planet_Dressel> <http://telicent.io/ontology/primaryName> "Dressel" .
<https://starwars.com#planet_Dressel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#sector_Noolian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dressel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Noolian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dressel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#810c154c-c6f6-4826-b36f-3ebf8c36dbad> .
<https://starwars.com#810c154c-c6f6-4826-b36f-3ebf8c36dbad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dressel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dressel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noolian> .
<https://starwars.com#810c154c-c6f6-4826-b36f-3ebf8c36dbad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

