Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kallea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Delrakkin> <http://www.w3.org/2000/01/rdf-schema#comment> "Delrakkin was an astronomical object located in the regions known as the Outer Rim Territories and the Western Reaches. It was also situated in grid square K-21 on the Standard Galactic Grid. " .
<https://starwars.com#grid_K21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Kallea> <http://telicent.io/ontology/primaryName> "Kallea" .
<https://starwars.com#grid_K21> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#82364cad-c174-4bf9-a0b9-ff7feed0c008> .
<https://starwars.com#planet_Delrakkin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9f374203-ac03-4132-94a0-069b5f4b9293> .
<https://starwars.com#9f374203-ac03-4132-94a0-069b5f4b9293> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#82364cad-c174-4bf9-a0b9-ff7feed0c008> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K21"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K21> <http://telicent.io/ontology/primaryName> "K21" .
<https://starwars.com#sector_Kallea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#82364cad-c174-4bf9-a0b9-ff7feed0c008> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_K21> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Delrakkin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9f374203-ac03-4132-94a0-069b5f4b9293> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Delrakkin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Delrakkin> <http://telicent.io/ontology/primaryName> "Delrakkin" .
<https://starwars.com#planet_Delrakkin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K21> .
<https://starwars.com#planet_Delrakkin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kallea> .

