Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Suliana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Suliana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a1dbc9b9-ac93-4d49-a537-dbfc8509e709> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Suliana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Suliana> <http://telicent.io/ontology/primaryName> "Suliana" .
<https://starwars.com#planet_Suliana> <http://www.w3.org/2000/01/rdf-schema#comment> "Suliana was an Agriworld in the Senex sector where fields of cotton grew. " .
<https://starwars.com#planet_Suliana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a1dbc9b9-ac93-4d49-a537-dbfc8509e709> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#a1dbc9b9-ac93-4d49-a537-dbfc8509e709> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Suliana"^^<http://www.w3.org/2001/XMLSchema#string> .

