Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Laertos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#232b654c-85d9-4295-b8b6-f572586a856d> .
<https://starwars.com#planet_Laertos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Laertos> <http://telicent.io/ontology/primaryName> "Laertos" .
<https://starwars.com#planet_Laertos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#planet_Laertos> <http://www.w3.org/2000/01/rdf-schema#comment> "Laertos was a planet the primary spaceport of which had a Rebel Alliance drop point. " .
<https://starwars.com#232b654c-85d9-4295-b8b6-f572586a856d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Laertos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Laertos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#232b654c-85d9-4295-b8b6-f572586a856d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

