Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Recopia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#ef8c47bc-8ee4-4a82-ad7b-d8dcdca60130> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Recopia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Recopia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ef8c47bc-8ee4-4a82-ad7b-d8dcdca60130> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Recopia> <http://www.w3.org/2000/01/rdf-schema#comment> "Recopia was a planet in the Recopi system in the Core Worlds, between the Corellian Run and the Hydian Way. It was the site of the annual Bandercamp Auctions in the Hinder Market. " .
<https://starwars.com#planet_Recopia> <http://telicent.io/ontology/primaryName> "Recopia" .
<https://starwars.com#planet_Recopia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef8c47bc-8ee4-4a82-ad7b-d8dcdca60130> .
<https://starwars.com#planet_Recopia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

