Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Corsin> <http://www.w3.org/2000/01/rdf-schema#comment> "Corsin was an astronomical object located in the galaxy's Expansion Region situated along the Hydian Way. The luxury liner Stellar Vista departed from Corsin before being pulled out of hyperspace in the Obroa-skai system as part of an attempt by the Galactic Empire to capture the stolen Imperial corvette Carrion Spike. " .
<https://starwars.com#planet_Corsin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5953eba5-54e7-4ff9-9d3e-c622d6b0fe63> .
<https://starwars.com#sector_GreaterPlooriod> <http://telicent.io/ontology/primaryName> "Greater Plooriod" .
<https://starwars.com#sector_GreaterPlooriod> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Corsin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#5953eba5-54e7-4ff9-9d3e-c622d6b0fe63> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corsin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Corsin> <http://telicent.io/ontology/primaryName> "Corsin" .
<https://starwars.com#sector_GreaterPlooriod> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#5953eba5-54e7-4ff9-9d3e-c622d6b0fe63> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Corsin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GreaterPlooriod> .
<https://starwars.com#planet_Corsin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

