Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dulathia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P8> .
<https://starwars.com#planet_Dulathia> <http://telicent.io/ontology/primaryName> "Dulathia" .
<https://starwars.com#planet_Dulathia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Landtillian> .
<https://starwars.com#sector_Landtillian> <http://telicent.io/ontology/primaryName> "Landtillian" .
<https://starwars.com#sector_Landtillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#488d8562-2e91-4b72-be64-6b94a03bb168> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#488d8562-2e91-4b72-be64-6b94a03bb168> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dulathia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Landtillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dulathia> <http://www.w3.org/2000/01/rdf-schema#comment> "Dulathia was an astronomical object in the Mid Rim Territories that was the homeworld of Kaydel Ko Connix, a human lieutenant of the Resistance. " .
<https://starwars.com#planet_Dulathia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dulathia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#488d8562-2e91-4b72-be64-6b94a03bb168> .

