Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#grid_I8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#60545399-5984-41ca-9d9b-64f4b4bfe06c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_I8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Celdaru> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd3327cf-e773-4738-8766-7c2b21ae9c68> .
<https://starwars.com#60545399-5984-41ca-9d9b-64f4b4bfe06c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Celdaru> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Celdaru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Celdaru> <http://telicent.io/ontology/primaryName> "Celdaru" .
<https://starwars.com#dd3327cf-e773-4738-8766-7c2b21ae9c68> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Celdaru> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Celdaru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I8> .
<https://starwars.com#dd3327cf-e773-4738-8766-7c2b21ae9c68> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Celdaru"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#60545399-5984-41ca-9d9b-64f4b4bfe06c> .
<https://starwars.com#grid_I8> <http://telicent.io/ontology/primaryName> "I8" .

