Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#583a35ba-052c-4e8d-a14e-9346af8c9fd3> .
<https://starwars.com#e1b5ba24-cdec-43d6-a837-d78d697e9c6f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e1b5ba24-cdec-43d6-a837-d78d697e9c6f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J19> <http://telicent.io/ontology/primaryName> "J19" .
<https://starwars.com#sector_Rayter> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Rayter> <http://telicent.io/ontology/primaryName> "Rayter" .
<https://starwars.com#planet_Karra> <http://www.w3.org/2000/01/rdf-schema#comment> "Karra was the Karran homeworld. It was briefly colonized by the Mineral Assets Partnership in 500 BBY. Later, the Galactic Empire established varmigio mines on the planet. Both offworld settlements were destroyed by swarms of insects controlled by the Karran hive mind. " .
<https://starwars.com#583a35ba-052c-4e8d-a14e-9346af8c9fd3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Karra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e1b5ba24-cdec-43d6-a837-d78d697e9c6f> .
<https://starwars.com#grid_J19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Karra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J19> .
<https://starwars.com#sector_Rayter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#583a35ba-052c-4e8d-a14e-9346af8c9fd3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Karra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Karra> <http://telicent.io/ontology/primaryName> "Karra" .
<https://starwars.com#grid_J19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Karra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rayter> .

