Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_PacanthReach> <http://telicent.io/ontology/primaryName> "Pacanth Reach" .
<https://starwars.com#planet_Bunduki> <http://www.w3.org/2000/01/rdf-schema#comment> "Bunduki was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Bunduki> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_PacanthReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bunduki> <http://telicent.io/ontology/primaryName> "Bunduki" .
<https://starwars.com#66b679e2-7138-4bdf-8277-9d24251eb30a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_PacanthReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bunduki> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_PacanthReach> .
<https://starwars.com#66b679e2-7138-4bdf-8277-9d24251eb30a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bunduki"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bunduki> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#66b679e2-7138-4bdf-8277-9d24251eb30a> .
<https://starwars.com#planet_Bunduki> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

