Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#2c40288c-9dd9-4205-803f-f9e10d70b9eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sanctuary"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sanctuary> <http://telicent.io/ontology/primaryName> "Sanctuary" .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sanctuary> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sanctuary> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Sanctuary> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#2c40288c-9dd9-4205-803f-f9e10d70b9eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sanctuary> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2c40288c-9dd9-4205-803f-f9e10d70b9eb> .
<https://starwars.com#planet_Sanctuary> <http://www.w3.org/2000/01/rdf-schema#comment> "Sanctuary was a location in the Outer Rim Territories that was a safe world of the nascent Alliance to Restore the Republic. A map of the galaxy with a legend listing the various Alliance safe worlds, starfighter hubs at level five or higher, rebel operations sectors and regional headquarters, and shadow planets with deep space caches, included Sanctuary. " .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

