Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2e9c6dbf-335a-4fa5-bd55-7bd6a426a9a9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Knolstee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Knolstee> <http://telicent.io/ontology/primaryName> "Knolstee" .
<https://starwars.com#2e9c6dbf-335a-4fa5-bd55-7bd6a426a9a9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Knolstee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Knolstee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Knolstee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Knolstee> <http://www.w3.org/2000/01/rdf-schema#comment> "Knolstee was a near-virgin planet in the Corporate Sector owned by Park Holdings Inc.. Park Holdings used the planet as a layover for traveling tourists. Sightseers were welcome to stay in small luxurious orbital stations then descend to Knolstee's surface where they could take tours lead by Park Holdings mostly Ithorian staff. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Knolstee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e9c6dbf-335a-4fa5-bd55-7bd6a426a9a9> .

