Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ojoster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Wayland> <http://www.w3.org/2000/01/rdf-schema#comment> "Wayland was a lush, semi-tropical planet in the Outer Rim Territories. " .
<https://starwars.com#planet_Wayland> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ojoster> .
<https://starwars.com#planet_Wayland> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Wayland> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a0c3018-e416-4361-bfd7-9f1249d1decb> .
<https://starwars.com#planet_Wayland> <http://telicent.io/ontology/primaryName> "Wayland" .
<https://starwars.com#1a0c3018-e416-4361-bfd7-9f1249d1decb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wayland"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ojoster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#1a0c3018-e416-4361-bfd7-9f1249d1decb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Wayland> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#sector_Ojoster> <http://telicent.io/ontology/primaryName> "Ojoster" .

