Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorUsilic> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1855a6fd-2ea5-40d5-996f-afdaf17f2444> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorUsilic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1855a6fd-2ea5-40d5-996f-afdaf17f2444> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Usilic"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorUsilic> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Usilic was a planet located in the Bootana Hutta region of Hutt Space. It was a Hutt throneworld. " .
<https://starwars.com#planet_KorUsilic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#planet_KorUsilic> <http://telicent.io/ontology/primaryName> "Kor Usilic" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_KorUsilic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#1855a6fd-2ea5-40d5-996f-afdaf17f2444> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

