Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Orelon> <http://www.w3.org/2000/01/rdf-schema#comment> "Orelon was a terrestrial astronomical object located in the galaxy that was the site of a weapons trade involving the Wookiee smuggler Chewbacca and Big Quince. During the weapons trade on Orelon, Big Quince's Wookiee bodyguard gave Chewbacca the pirate Maz Kanata's Smuggler's Guide. When Chewbacca's partner, Han Solo, learned where he had acquired the Smuggler's Guide months later, Solo recorded an account of the incident in the book. " .
<https://starwars.com#706b2f5e-05a9-4753-a37d-76665c65be7a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#706b2f5e-05a9-4753-a37d-76665c65be7a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orelon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Orelon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Orelon> <http://telicent.io/ontology/primaryName> "Orelon" .
<https://starwars.com#planet_Orelon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Orelon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Orelon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#706b2f5e-05a9-4753-a37d-76665c65be7a> .

