Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Quelii> <http://www.w3.org/2000/01/rdf-schema#comment> "Quelii was a planet in the Outer Rim Territories, which maintained a population of Humans who lived in villages. Quelii was devastated by a Mandalorian attack in the years leading up to the Mandalorian Wars, although some natives managed to escape the onslaught and make it to Republic space. One of these refugees grew to become the infamous Dark Lord of the Sith Darth Malak, who led a Sith army against the Republic in the Jedi Civil War. " .
<https://starwars.com#planet_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#9441207f-bfcb-4e33-a365-b48543fdd18f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Quelii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9441207f-bfcb-4e33-a365-b48543fdd18f> .
<https://starwars.com#sector_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#planet_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#planet_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quelii> .
<https://starwars.com#9441207f-bfcb-4e33-a365-b48543fdd18f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quelii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

