Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_K5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_K5> <http://telicent.io/ontology/primaryName> "K5" .
<https://starwars.com#ca7ec06f-eebb-4efc-a614-96d9e21f6bfd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Anemcoro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#b911a48c-7a21-41f4-8e1f-9b25a8d4be94> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anemcoro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .
<https://starwars.com#grid_K5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ca7ec06f-eebb-4efc-a614-96d9e21f6bfd> .
<https://starwars.com#b911a48c-7a21-41f4-8e1f-9b25a8d4be94> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anemcoro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Anemcoro> <http://telicent.io/ontology/primaryName> "Anemcoro" .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#ca7ec06f-eebb-4efc-a614-96d9e21f6bfd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Anemcoro> <http://www.w3.org/2000/01/rdf-schema#comment> "Anemcoro was a colony world located in the Anemcoro system of the Outer Rim Territories' Albarrio sector. " .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#planet_Anemcoro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b911a48c-7a21-41f4-8e1f-9b25a8d4be94> .
<https://starwars.com#planet_Anemcoro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

