Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4c643016-f106-4183-b44f-c05f7c913a23> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_DenariiStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4c643016-f106-4183-b44f-c05f7c913a23> .
<https://starwars.com#4c643016-f106-4183-b44f-c05f7c913a23> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Denarii Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DenariiStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_DenariiStation> <http://telicent.io/ontology/primaryName> "Denarii Station" .
<https://starwars.com#planet_DenariiStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Denarii Station was a base of laboratories and habitation modules in the Denarii Nebula—the gaseous, highly ionized remnant of a double-star system that was destroyed by the Sith Lord Naga Sadow during the Great Hyperspace War of 5000 BBY—in the Gordian Reach sector of the Trans-Hydian part of the Outer Rim Territories. It was originally used by astrophysicists for studying the nebula, but it fell into disuse centuries before 43 ABY. Nevertheless, the station was still used as a hideout by the desperate. " .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_DenariiStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_DenariiStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

