Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2fff741b-2357-47ea-a9ca-9d5ce6d25599> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Korriban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Korriban> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#2fff741b-2357-47ea-a9ca-9d5ce6d25599> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korriban"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Korriban> <http://telicent.io/ontology/primaryName> "Korriban" .
<https://starwars.com#planet_Korriban> <http://www.w3.org/2000/01/rdf-schema#comment> "It was close to Bosthirda and was located on the Nache Bhelfia and Kamat Krote hyperspace lanes. " .
<https://starwars.com#planet_Korriban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Korriban> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2fff741b-2357-47ea-a9ca-9d5ce6d25599> .

