Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cadma> <http://telicent.io/ontology/primaryName> "Cadma" .
<https://starwars.com#planet_Cadma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cadma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e1201969-ae3a-4415-a4be-48e81b181d49> .
<https://starwars.com#planet_Cadma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#e1201969-ae3a-4415-a4be-48e81b181d49> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cadma> <http://www.w3.org/2000/01/rdf-schema#comment> "Cadma could refer to one of the following: " .
<https://starwars.com#planet_Cadma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#e1201969-ae3a-4415-a4be-48e81b181d49> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cadma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

