Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jospro> <http://telicent.io/ontology/primaryName> "Jospro" .
<https://starwars.com#planet_Kile> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#774a075c-7e3f-456b-b3c2-3e7a89e5c6f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kile> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jospro> .
<https://starwars.com#774a075c-7e3f-456b-b3c2-3e7a89e5c6f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kile"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Jospro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kile> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#774a075c-7e3f-456b-b3c2-3e7a89e5c6f9> .
<https://starwars.com#planet_Kile> <http://www.w3.org/2000/01/rdf-schema#comment> "Kile was a moon of the gas giant Zhar in the Zhar system. Rogue Squadron established a base on the moon, from where they organized the mission to rescue Han Solo from Boba Fett's Slave I. The other moon, Gall, was a populated, terrestrial world home to an Imperial enclave. " .
<https://starwars.com#sector_Jospro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kile> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kile> <http://telicent.io/ontology/primaryName> "Kile" .

