Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#18ae5ad2-037f-48bd-832c-9840850841ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Handooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Handooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Phelleem> .
<https://starwars.com#18ae5ad2-037f-48bd-832c-9840850841ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Handooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Handooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#planet_Handooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#18ae5ad2-037f-48bd-832c-9840850841ef> .
<https://starwars.com#sector_Phelleem> <http://telicent.io/ontology/primaryName> "Phelleem" .
<https://starwars.com#sector_Phelleem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Handooine> <http://telicent.io/ontology/primaryName> "Handooine" .
<https://starwars.com#sector_Phelleem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Handooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Handooine was an astronomical object. The Outer Rim Territories world of Saleucami was located between Handooine and Kegan. " .

