Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shumogi> <http://telicent.io/ontology/primaryName> "Shumogi" .
<https://starwars.com#planet_Shumogi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0a505ad6-61f1-4ab2-9af1-6dd4287fc1bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shumogi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Shumogi> <http://www.w3.org/2000/01/rdf-schema#comment> "Shumogi was a planet located in the Core Worlds. " .
<https://starwars.com#planet_Shumogi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0a505ad6-61f1-4ab2-9af1-6dd4287fc1bf> .
<https://starwars.com#planet_Shumogi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#0a505ad6-61f1-4ab2-9af1-6dd4287fc1bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shumogi"^^<http://www.w3.org/2001/XMLSchema#string> .

