Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Brin> <http://telicent.io/ontology/primaryName> "Bri'n" .
<https://starwars.com#planet_Brin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Brin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Brin> <http://www.w3.org/2000/01/rdf-schema#comment> "Bri'n was an arboreal planet with a breathable atmosphere and various flora and fauna. A horned humanoid species lived on the planet. Sometime between 44 BBY and 32 BBY, the Jedi Master Qui-Gon Jinn and his Padawan, Obi-Wan Kenobi, were sent to Bri'n to assist with negotiations between Priestess Th'er and the Metal Clan, a group that opposed her and wished to destroy the trees present on the planet. Once the negotiations failed, the Jedi were forced to bring Th'er to safety on the planet Coruscant, but advised her to seek offworld allies." .
<https://starwars.com#cf1335cf-f9b1-421f-83cd-6d36c9ca8df8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Brin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf1335cf-f9b1-421f-83cd-6d36c9ca8df8> .
<https://starwars.com#cf1335cf-f9b1-421f-83cd-6d36c9ca8df8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bri'n"^^<http://www.w3.org/2001/XMLSchema#string> .

