Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Corroth> <http://www.w3.org/2000/01/rdf-schema#comment> "Corroth was a planet known for its duelists, such as Matta Tremayne. " .
<https://starwars.com#planet_Corroth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#abfcd849-3b4c-43e4-bce8-4303cf693f77> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corroth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Corroth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#abfcd849-3b4c-43e4-bce8-4303cf693f77> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Corroth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#abfcd849-3b4c-43e4-bce8-4303cf693f77> .
<https://starwars.com#planet_Corroth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Corroth> <http://telicent.io/ontology/primaryName> "Corroth" .

