Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_Endoraan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2861ce1c-0fe9-483a-813d-9edec121469c> .
<https://starwars.com#planet_Endoraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#2861ce1c-0fe9-483a-813d-9edec121469c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Endoraan> <http://telicent.io/ontology/primaryName> "Endoraan" .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#2861ce1c-0fe9-483a-813d-9edec121469c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Endoraan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Endoraan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Endoraan> <http://www.w3.org/2000/01/rdf-schema#comment> "Endoraan was a planet that was an endpoint of the Relgim Run, opposite Mantooine. " .
<https://starwars.com#planet_Endoraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .

