Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ichtor> <http://telicent.io/ontology/primaryName> "Ichtor" .
<https://starwars.com#planet_Ichtor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sombure> .
<https://starwars.com#f59962de-802d-4ea5-bbc3-23f09cf2c1b1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ichtor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ichtor> <http://www.w3.org/2000/01/rdf-schema#comment> "Madam Prisaal and her husband lived on this planet. " .
<https://starwars.com#planet_Ichtor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f59962de-802d-4ea5-bbc3-23f09cf2c1b1> .
<https://starwars.com#planet_Ichtor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sombure> <http://telicent.io/ontology/primaryName> "Sombure" .
<https://starwars.com#sector_Sombure> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f59962de-802d-4ea5-bbc3-23f09cf2c1b1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sombure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Ichtor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .

