Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Goorla> <http://www.w3.org/2000/01/rdf-schema#comment> "Goorla was a planet in the Goorla system of the Corellian sector in the Core Worlds. It was the source of the Goorlish light source. " .
<https://starwars.com#87a81203-edc1-49b9-8bf5-627b2a4e6ff7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Goorla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#87a81203-edc1-49b9-8bf5-627b2a4e6ff7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Goorla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Goorla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#87a81203-edc1-49b9-8bf5-627b2a4e6ff7> .
<https://starwars.com#planet_Goorla> <http://telicent.io/ontology/primaryName> "Goorla" .
<https://starwars.com#planet_Goorla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Goorla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .

