Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kromus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f37f0ae9-2799-41d9-bcff-f07a0def93a7> .
<https://starwars.com#planet_Kromus> <http://telicent.io/ontology/primaryName> "Kromus" .
<https://starwars.com#planet_Kromus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P7> .
<https://starwars.com#planet_Kromus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Esuain> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Esuain> <http://telicent.io/ontology/primaryName> "Esuain" .
<https://starwars.com#planet_Kromus> <http://www.w3.org/2000/01/rdf-schema#comment> "Kromus was the fourth planet in the Kro'eval system. It had a rich biosphere, and by the time of the Clone Wars, it had a sentient population of 1.3 billion. " .
<https://starwars.com#f37f0ae9-2799-41d9-bcff-f07a0def93a7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f37f0ae9-2799-41d9-bcff-f07a0def93a7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kromus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kromus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esuain> .
<https://starwars.com#sector_Esuain> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

