Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6f146a14-5e9a-4284-b38b-0e2c13567d30> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dellalt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dellalt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Dellalt> <http://www.w3.org/2000/01/rdf-schema#comment> "Dellalt was an astronomical object located within the Tion Cluster of the regions known as the Outer Rim Territories and the Slice. The astronomical object was positioned within grid square T-6 on the Standard Galactic Grid. " .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#6f146a14-5e9a-4284-b38b-0e2c13567d30> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dellalt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6f146a14-5e9a-4284-b38b-0e2c13567d30> .
<https://starwars.com#planet_Dellalt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .
<https://starwars.com#planet_Dellalt> <http://telicent.io/ontology/primaryName> "Dellalt" .
<https://starwars.com#planet_Dellalt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

