Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Msst> <http://telicent.io/ontology/primaryName> "Msst" .
<https://starwars.com#planet_Msst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Msst> .
<https://starwars.com#sector_Msst> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#23a07a18-065c-4f8b-bf5d-c0cdae049ee3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Msst"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#23a07a18-065c-4f8b-bf5d-c0cdae049ee3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Msst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Msst> <http://www.w3.org/2000/01/rdf-schema#comment> "Msst was a Mid Rim planet, and the homeworld of Brakiss. It was a small planet in the Msst system, which had an Imperial stronghold. The Empire had theoretically abandoned it after the Invasion of Bakura. Luke Skywalker came to Msst in search of Brakiss, where, shortly after landing, he was attacked by a group of mistmakers. " .
<https://starwars.com#planet_Msst> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#23a07a18-065c-4f8b-bf5d-c0cdae049ee3> .
<https://starwars.com#planet_Msst> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Msst> <http://telicent.io/ontology/primaryName> "Msst" .
<https://starwars.com#planet_Msst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P7> .

