Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5c1d13b1-5911-4ff2-8dd4-ee1b09cd97e6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Nkllon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L16> .
<https://starwars.com#planet_Nkllon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33ab9ed9-a5e6-42c2-bb77-83b64442a7ff> .
<https://starwars.com#planet_Nkllon> <http://telicent.io/ontology/primaryName> "Nkllon" .
<https://starwars.com#planet_Nkllon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_L16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5c1d13b1-5911-4ff2-8dd4-ee1b09cd97e6> .
<https://starwars.com#planet_Nkllon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Alchenaut> .
<https://starwars.com#grid_L16> <http://telicent.io/ontology/primaryName> "L16" .
<https://starwars.com#sector_Alchenaut> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Nkllon> <http://www.w3.org/2000/01/rdf-schema#comment> "Nkllon was an astronomical object located in the galaxy's Expansion Region, positioned at the coordinates L-16 on the Standard Galactic Grid. " .
<https://starwars.com#sector_Alchenaut> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Alchenaut> <http://telicent.io/ontology/primaryName> "Alchenaut" .
<https://starwars.com#33ab9ed9-a5e6-42c2-bb77-83b64442a7ff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#5c1d13b1-5911-4ff2-8dd4-ee1b09cd97e6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#33ab9ed9-a5e6-42c2-bb77-83b64442a7ff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nkllon"^^<http://www.w3.org/2001/XMLSchema#string> .

