Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#71ab4f46-6ee9-4688-a96b-03979e33be94> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lythos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lythos> <http://telicent.io/ontology/primaryName> "Lythos" .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Lythos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Lythos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lythos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#71ab4f46-6ee9-4688-a96b-03979e33be94> .
<https://starwars.com#71ab4f46-6ee9-4688-a96b-03979e33be94> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lythos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lythos> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

