Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Iego> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95699020-2666-4357-94c7-592e5e6e5953> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_Iego> <http://telicent.io/ontology/primaryName> "Iego" .
<https://starwars.com#planet_Iego> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#95699020-2666-4357-94c7-592e5e6e5953> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Iego> <http://www.w3.org/2000/01/rdf-schema#comment> "An Outer Rim planet which harbors flying creatures called xandu and medicinally important plants called reeska. Iego is surrounded by a 1000 moons and at least one of these, named Millius Prime, is home to a race called the Angels." .
<https://starwars.com#planet_Iego> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#95699020-2666-4357-94c7-592e5e6e5953> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iego"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iego> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .

