Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Neelgaimon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Xappyh> .
<https://starwars.com#sector_Xappyh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Neelgaimon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Xappyh> <http://telicent.io/ontology/primaryName> "Xappyh" .
<https://starwars.com#planet_Neelgaimon> <http://telicent.io/ontology/primaryName> "Neelgaimon" .
<https://starwars.com#planet_Neelgaimon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q3> .
<https://starwars.com#e181cb63-f809-4821-9722-a0a2a8701f66> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Neelgaimon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Neelgaimon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e181cb63-f809-4821-9722-a0a2a8701f66> .
<https://starwars.com#e181cb63-f809-4821-9722-a0a2a8701f66> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Neelgaimon> <http://www.w3.org/2000/01/rdf-schema#comment> "Neelgaimon was a hot, drought-ridden planet in the Xappyh sector of the Outer Rim Territories. " .
<https://starwars.com#sector_Xappyh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

