Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bozhnee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#9f74ce9c-524d-42dc-96c1-a9fa4b97a819> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Bozhnee> <http://telicent.io/ontology/primaryName> "Bozhnee" .
<https://starwars.com#sector_Bozhnee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Belsavis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Belsavis> <http://telicent.io/ontology/primaryName> "Belsavis" .
<https://starwars.com#planet_Belsavis> <http://www.w3.org/2000/01/rdf-schema#comment> "Belsavis was an astronomical object located in the Senex-Juvex, a part of the galaxy's Mid Rim. It was connected via hyperspace route to Karfeddion. Thull's Shroud was near Belsavis. " .
<https://starwars.com#planet_Belsavis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bozhnee> .
<https://starwars.com#planet_Belsavis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9f74ce9c-524d-42dc-96c1-a9fa4b97a819> .
<https://starwars.com#planet_Belsavis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#9f74ce9c-524d-42dc-96c1-a9fa4b97a819> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belsavis"^^<http://www.w3.org/2001/XMLSchema#string> .

