Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kurost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Farquar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kurost> .
<https://starwars.com#33bf0d4e-a76d-4ff1-91e3-9f91464a3969> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kurost> <http://telicent.io/ontology/primaryName> "Kurost" .
<https://starwars.com#planet_Farquar> <http://telicent.io/ontology/primaryName> "Farquar" .
<https://starwars.com#planet_Farquar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Farquar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33bf0d4e-a76d-4ff1-91e3-9f91464a3969> .
<https://starwars.com#planet_Farquar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#33bf0d4e-a76d-4ff1-91e3-9f91464a3969> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Farquar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Farquar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q11> .
<https://starwars.com#sector_Kurost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

