Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Salin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Salin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N5> .
<https://starwars.com#sector_Sprizen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Salin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sprizen> .
<https://starwars.com#sector_Sprizen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Salin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5ef8976a-0918-4d9f-892e-15d419fb351a> .
<https://starwars.com#sector_Sprizen> <http://telicent.io/ontology/primaryName> "Sprizen" .
<https://starwars.com#planet_Salin> <http://www.w3.org/2000/01/rdf-schema#comment> "Salin was a planet in the Outer Rim Territories that was part of the Kwa holdings during the Pre-Republic era. With the ascendancy of the Rakatan Infinite Empire, Salin was annexed and the Kwa species were annihilated and driven back to Dathomir. " .
<https://starwars.com#5ef8976a-0918-4d9f-892e-15d419fb351a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Salin> <http://telicent.io/ontology/primaryName> "Salin" .
<https://starwars.com#5ef8976a-0918-4d9f-892e-15d419fb351a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Salin"^^<http://www.w3.org/2001/XMLSchema#string> .

