Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4a428c82-b2cc-4d59-9360-0ef855433ad1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yutan> <http://telicent.io/ontology/primaryName> "Yutan" .
<https://starwars.com#sector_Ombakond> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Yutan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Yutan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Yutan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#planet_Yutan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ombakond> .
<https://starwars.com#planet_Yutan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4a428c82-b2cc-4d59-9360-0ef855433ad1> .
<https://starwars.com#sector_Ombakond> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Ombakond> <http://telicent.io/ontology/primaryName> "Ombakond" .
<https://starwars.com#4a428c82-b2cc-4d59-9360-0ef855433ad1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yutan"^^<http://www.w3.org/2001/XMLSchema#string> .

