Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7cf80014-2d0e-4b00-bc65-cd5cf9ec026f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_LittleKessel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7cf80014-2d0e-4b00-bc65-cd5cf9ec026f> .
<https://starwars.com#planet_LittleKessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_LittleKessel> <http://www.w3.org/2000/01/rdf-schema#comment> "Little Kessel was an astronomical object situated on the Pabol Sleheyron hyperspace route in the Outer Rim Territories. " .
<https://starwars.com#planet_LittleKessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#planet_LittleKessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#7cf80014-2d0e-4b00-bc65-cd5cf9ec026f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Little Kessel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_LittleKessel> <http://telicent.io/ontology/primaryName> "Little Kessel" .

