Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MalestromNebula> <http://telicent.io/ontology/primaryName> "Malestrom Nebula" .
<https://starwars.com#b212bd98-b018-459e-b248-004388c00869> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Malestrom Nebula"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MalestromNebula> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_MalestromNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#planet_MalestromNebula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MalestromNebula> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b212bd98-b018-459e-b248-004388c00869> .
<https://starwars.com#planet_MalestromNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .
<https://starwars.com#b212bd98-b018-459e-b248-004388c00869> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

