Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Barsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Barsa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5aac3600-f6a9-473a-a939-e130c11474ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Uba> <http://telicent.io/ontology/primaryName> "Uba" .
<https://starwars.com#planet_Uba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5aac3600-f6a9-473a-a939-e130c11474ab> .
<https://starwars.com#5aac3600-f6a9-473a-a939-e130c11474ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Uba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Uba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Barsa> <http://telicent.io/ontology/primaryName> "Barsa" .
<https://starwars.com#planet_Uba> <http://www.w3.org/2000/01/rdf-schema#comment> "Uba was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Uba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#planet_Uba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Barsa> .

