Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ciutric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#af91cd3c-85fa-4fe7-bd2a-44490b3d53a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ciutric> <http://www.w3.org/2000/01/rdf-schema#comment> "Ciutric was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#af91cd3c-85fa-4fe7-bd2a-44490b3d53a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ciutric"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ciutric> <http://telicent.io/ontology/primaryName> "Ciutric" .
<https://starwars.com#sector_Ciutric> <http://telicent.io/ontology/primaryName> "Ciutric" .
<https://starwars.com#planet_Ciutric> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#af91cd3c-85fa-4fe7-bd2a-44490b3d53a6> .
<https://starwars.com#planet_Ciutric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ciutric> .
<https://starwars.com#planet_Ciutric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ciutric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N5> .
<https://starwars.com#sector_Ciutric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

