Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ejolus> <http://telicent.io/ontology/primaryName> "Ejolus" .
<https://starwars.com#6d6a13bf-99b3-4867-89fd-3b279459c75b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ejolus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ejolus> <http://www.w3.org/2000/01/rdf-schema#comment> "Ejolus was a planet located in the Inner Rim. " .
<https://starwars.com#planet_Ejolus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ejolus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#6d6a13bf-99b3-4867-89fd-3b279459c75b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ejolus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ejolus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6d6a13bf-99b3-4867-89fd-3b279459c75b> .

