Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_CorvaYag> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_CorvaYag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rseik> .
<https://starwars.com#8686664c-9ccd-4c78-82fa-600ba30d1658> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_CorvaYag> <http://telicent.io/ontology/primaryName> "Corva Yag" .
<https://starwars.com#grid_N20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#8686664c-9ccd-4c78-82fa-600ba30d1658> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corva Yag"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CorvaYag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N20> .
<https://starwars.com#4d65b3ca-5777-4f7c-aa1c-95177e1a4c8b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Rseik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_N20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4d65b3ca-5777-4f7c-aa1c-95177e1a4c8b> .
<https://starwars.com#sector_Rseik> <http://telicent.io/ontology/primaryName> "Rseik" .
<https://starwars.com#grid_N20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_N20> <http://telicent.io/ontology/primaryName> "N20" .
<https://starwars.com#sector_Rseik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_CorvaYag> <http://www.w3.org/2000/01/rdf-schema#comment> "Later, during the reign of the Galactic Empire, several hundred colonists on Corva Yag died. Their deaths were ostensibly caused by a malfunctioning 87-RM Scout Collector droid, although it was theorized by 0 ABY that the Empire had merely used the malfunctioning droid to cover up secret activities on the planet. " .
<https://starwars.com#4d65b3ca-5777-4f7c-aa1c-95177e1a4c8b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CorvaYag> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8686664c-9ccd-4c78-82fa-600ba30d1658> .

