Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_BatorBai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#6828b2ed-5650-40a0-b848-de10f2c03f1c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bator Bai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BatorBai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6828b2ed-5650-40a0-b848-de10f2c03f1c> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#6828b2ed-5650-40a0-b848-de10f2c03f1c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_BatorBai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_BatorBai> <http://www.w3.org/2000/01/rdf-schema#comment> "Bator Bai was a planet located in the Western Reaches of the Mid Rim. Part of the Senex sector's Bator Bai system, the ice world was known for the exceptional clarity of its ice cliffs and caverns. " .
<https://starwars.com#planet_BatorBai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_BatorBai> <http://telicent.io/ontology/primaryName> "Bator Bai" .

