Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TheCometwash> <http://telicent.io/ontology/primaryName> "The Cometwash" .
<https://starwars.com#a1303ca3-6be6-406f-80f3-b2fcc059024d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a1303ca3-6be6-406f-80f3-b2fcc059024d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Cometwash"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TheCometwash> <http://www.w3.org/2000/01/rdf-schema#comment> "The Cometwash was the name for a blue giant star in the Gordian Reach along the Feena Run that was surrounded by swarms of comets. The system became a stopping point for many spacers rechecking their jump calculations after navigating around the Roil and tourists wanting to catch a glimpse. " .
<https://starwars.com#planet_TheCometwash> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TheCometwash> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a1303ca3-6be6-406f-80f3-b2fcc059024d> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_TheCometwash> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_TheCometwash> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

