Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NezPeron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d3f97838-48f2-4a52-9861-6dd02ec4ad51> .
<https://starwars.com#sector_DAstan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NezPeron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#sector_DAstan> <http://telicent.io/ontology/primaryName> "D'Astan" .
<https://starwars.com#planet_NezPeron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAstan> .
<https://starwars.com#d3f97838-48f2-4a52-9861-6dd02ec4ad51> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NezPeron> <http://telicent.io/ontology/primaryName> "Nez Peron" .
<https://starwars.com#planet_NezPeron> <http://www.w3.org/2000/01/rdf-schema#comment> "Nez Peron was an astronomical objected located in the regions known as the Outer Rim Territories and the New Territories. It was located within grid square O-5 on the Standard Galactic Grid. " .
<https://starwars.com#d3f97838-48f2-4a52-9861-6dd02ec4ad51> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nez Peron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_DAstan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_NezPeron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

