Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_RearquCluster> <http://telicent.io/ontology/primaryName> "Rearqu Cluster" .
<https://starwars.com#sector_Taldot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_RearquCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P8> .
<https://starwars.com#planet_RearquCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0d9688ce-833d-4346-b606-41ea5b1d4ba8> .
<https://starwars.com#0d9688ce-833d-4346-b606-41ea5b1d4ba8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Taldot> <http://telicent.io/ontology/primaryName> "Taldot" .
<https://starwars.com#planet_RearquCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Rearqu system, also known as Rearqu 10 and the Rearqu Cluster, was located in the Mid Rim's Taldot sector. " .
<https://starwars.com#0d9688ce-833d-4346-b606-41ea5b1d4ba8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rearqu Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Taldot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_RearquCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RearquCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Taldot> .

