Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yitabo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#planet_Yitabo> <http://telicent.io/ontology/primaryName> "Yitabo" .
<https://starwars.com#be8323a6-ed72-471f-9e94-98551c2dbf40> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yitabo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#be8323a6-ed72-471f-9e94-98551c2dbf40> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yitabo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yitabo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Yitabo> <http://www.w3.org/2000/01/rdf-schema#comment> "Yitabo was a minor agriworld located in the Yitabo system, at the intersection of the Pabol Sleheyron and Durkteel Loop in the Kastolar sector. It was the home to Borneck, Saurin, and Wookiee colonists. " .
<https://starwars.com#planet_Yitabo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be8323a6-ed72-471f-9e94-98551c2dbf40> .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

