Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_P16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Argus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lambda> .
<https://starwars.com#grid_P16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d7807eb5-8238-4454-9a6b-9934e7c8f35c> .
<https://starwars.com#2dbe01dd-71ab-4a33-9d7b-8ff85cd14c8c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Argus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Argus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_P16> <http://telicent.io/ontology/primaryName> "P16" .
<https://starwars.com#sector_Lambda> <http://telicent.io/ontology/primaryName> "Lambda" .
<https://starwars.com#d7807eb5-8238-4454-9a6b-9934e7c8f35c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Argus> <http://www.w3.org/2000/01/rdf-schema#comment> "Argus was a Human-inhabited planet in the Argus system. When the New Order was instituted, Argus's Celestial School of Spaceflight Engineering was closed down. At least one of the school's professors, Maggis, became a teacher at the Imperial Naval Academy on Imperial Center, rather than be blacklisted from ever teaching again. " .
<https://starwars.com#grid_P16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Lambda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Lambda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#2dbe01dd-71ab-4a33-9d7b-8ff85cd14c8c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Argus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P16> .
<https://starwars.com#planet_Argus> <http://telicent.io/ontology/primaryName> "Argus" .
<https://starwars.com#d7807eb5-8238-4454-9a6b-9934e7c8f35c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Argus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2dbe01dd-71ab-4a33-9d7b-8ff85cd14c8c> .

