Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b2842ac1-e869-4b96-bb88-428bdc14ec23> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Saila Na"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_SailaNa> <http://telicent.io/ontology/primaryName> "Saila Na" .
<https://starwars.com#planet_SailaNa> <http://www.w3.org/2000/01/rdf-schema#comment> "Saila Na was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_SailaNa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2842ac1-e869-4b96-bb88-428bdc14ec23> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_SailaNa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_SailaNa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#b2842ac1-e869-4b96-bb88-428bdc14ec23> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SailaNa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

