Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lekua> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#088d877c-1a7d-4489-bfa2-62a004680f1e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lekua> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Lekua> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#planet_Lekua> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#088d877c-1a7d-4489-bfa2-62a004680f1e> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#088d877c-1a7d-4489-bfa2-62a004680f1e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lekua"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lekua> <http://telicent.io/ontology/primaryName> "Lekua" .
<https://starwars.com#planet_Lekua> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

