Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Naalol> <http://www.w3.org/2000/01/rdf-schema#comment> "Naalol was a strategically insignificant mountainous planet in the Mid Rim Territories. It had a series of mountainous towns with small crooked mountainous houses. The people who lived here were valdeer shepherds as well as artisans or miners. " .
<https://starwars.com#be0738b2-f46d-48e6-9c3f-2c1f27153872> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Naalol"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#be0738b2-f46d-48e6-9c3f-2c1f27153872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Naalol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Naalol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Spirva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Naalol> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be0738b2-f46d-48e6-9c3f-2c1f27153872> .
<https://starwars.com#planet_Naalol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Spirva> .
<https://starwars.com#sector_Spirva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Spirva> <http://telicent.io/ontology/primaryName> "Spirva" .
<https://starwars.com#planet_Naalol> <http://telicent.io/ontology/primaryName> "Naalol" .

