Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bosthirda> <http://telicent.io/ontology/primaryName> "Bosthirda" .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bosthirda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4eea8049-d8fb-47ce-9dde-9869b5d9cd7c> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#4eea8049-d8fb-47ce-9dde-9869b5d9cd7c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#4eea8049-d8fb-47ce-9dde-9869b5d9cd7c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bosthirda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bosthirda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Bosthirda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bosthirda> <http://www.w3.org/2000/01/rdf-schema#comment> "Bosthirda was an astronomical object located in the Outer Rim Territories. " .
<https://starwars.com#planet_Bosthirda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .

