Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f7c4413a-00ca-458d-a111-2e772b485ee9> .
<https://starwars.com#planet_Belasco> <http://telicent.io/ontology/primaryName> "Belasco" .
<https://starwars.com#grid_O11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Belasco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#grid_O11> <http://telicent.io/ontology/primaryName> "O11" .
<https://starwars.com#sector_Belasco> <http://telicent.io/ontology/primaryName> "Belasco" .
<https://starwars.com#sector_Belasco> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Belasco> <http://www.w3.org/2000/01/rdf-schema#comment> "Belasco was an astronomical objected located in the regions known as the Expansion Region and the Slice. It lay in grid square O-11 on the Standard Galactic Grid and was connected via hyperspace route to the planet Gyndine and the Mid Rim Territories astronomical object New Apsolon. " .
<https://starwars.com#planet_Belasco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .
<https://starwars.com#f7c4413a-00ca-458d-a111-2e772b485ee9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f7c4413a-00ca-458d-a111-2e772b485ee9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#23f37527-e83a-464a-ae13-9e241548c99e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belasco"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Belasco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belasco> .
<https://starwars.com#planet_Belasco> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Belasco> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#23f37527-e83a-464a-ae13-9e241548c99e> .
<https://starwars.com#23f37527-e83a-464a-ae13-9e241548c99e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

