Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sakifwanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d7bd16b7-c436-4367-828b-0cda82bd3ee7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sakifwanna> <http://telicent.io/ontology/primaryName> "Sakifwanna" .
<https://starwars.com#d7bd16b7-c436-4367-828b-0cda82bd3ee7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sakifwanna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sakifwanna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7bd16b7-c436-4367-828b-0cda82bd3ee7> .
<https://starwars.com#planet_Sakifwanna> <http://www.w3.org/2000/01/rdf-schema#comment> "Sakifwanna was a planet that was located within the Sakifwanna system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet lay on the Elgit–M'Hanna Corridor hyperlane that connected it to the worlds of Elgit and M'Hanna. A smaller hyperspace route linked Sakifwanna to the Cyax system, and another hyperlane connected the world to the planet of Saki. " .
<https://starwars.com#planet_Sakifwanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Sakifwanna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

