Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c1abfcda-4501-48bb-8f15-1d5e845b0da5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Davirien> <http://telicent.io/ontology/primaryName> "Davirien" .
<https://starwars.com#planet_Davirien> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c1abfcda-4501-48bb-8f15-1d5e845b0da5> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Davirien> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#c1abfcda-4501-48bb-8f15-1d5e845b0da5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Davirien"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Davirien> <http://www.w3.org/2000/01/rdf-schema#comment> "Davirien was a jungle planet in the Corporate Sector owned by the Chiewab Amalgamated Pharmaceuticals Company. Chiewab used the planet for research, and also permitted the Galactic Empire to use the planet for training missions. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Davirien> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Davirien> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .

