Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6095fbea-b401-4bd5-9164-875b1f855a72> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_LolaSayu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_LolaSayu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6095fbea-b401-4bd5-9164-875b1f855a72> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lola Sayu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LolaSayu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_LolaSayu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6095fbea-b401-4bd5-9164-875b1f855a72> .
<https://starwars.com#planet_LolaSayu> <http://telicent.io/ontology/primaryName> "Lola Sayu" .
<https://starwars.com#planet_LolaSayu> <http://www.w3.org/2000/01/rdf-schema#comment> "Lola Sayu was a sulfurous, cracked planet that was home to the Citadel, a prison engineered to hold Jedi, during the Clone Wars. " .

