Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Burska> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5a59286b-015f-4b99-af87-60a50e3a70b9> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Burska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#5a59286b-015f-4b99-af87-60a50e3a70b9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Burska> <http://telicent.io/ontology/primaryName> "Burska" .
<https://starwars.com#5a59286b-015f-4b99-af87-60a50e3a70b9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Burska"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Burska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Burska> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Burska> <http://www.w3.org/2000/01/rdf-schema#comment> "The Burskan gundark was discovered by an atmospheric and geological scientist team that visited the planet during the final years of the Galactic Republic. Although the first contact ended disastrously for the researchers, one of the local gundarks was subsequently transported off-world for study, with Burska being declared a Republic-protected zone. Eventually, the planet became a part of the New Republic. " .

