Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_DAstan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_O5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_DAstan> <http://telicent.io/ontology/primaryName> "D'Astan" .
<https://starwars.com#planet_Axxila> <http://www.w3.org/2000/01/rdf-schema#comment> "Axxila was a planet located in the galaxy's Outer Rim Territories that was the homeworld of Imperial Admiral Firmus Piett. " .
<https://starwars.com#045695c4-52c9-4a3f-a4f6-383a4f9de25b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Axxila> <http://telicent.io/ontology/primaryName> "Axxila" .
<https://starwars.com#e067c988-a830-4cb9-83d1-c11c15ef3838> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#045695c4-52c9-4a3f-a4f6-383a4f9de25b> .
<https://starwars.com#045695c4-52c9-4a3f-a4f6-383a4f9de25b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Axxila> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAstan> .
<https://starwars.com#grid_O5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_O5> <http://telicent.io/ontology/primaryName> "O5" .
<https://starwars.com#sector_DAstan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Axxila> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e067c988-a830-4cb9-83d1-c11c15ef3838> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Axxila"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Axxila> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#planet_Axxila> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e067c988-a830-4cb9-83d1-c11c15ef3838> .

