Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8d6f8508-59f2-47f1-8520-6c99f666fa48> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Excarga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Excarga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Svetta> .
<https://starwars.com#grid_T16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_T16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8d6f8508-59f2-47f1-8520-6c99f666fa48> .
<https://starwars.com#planet_Excarga> <http://www.w3.org/2000/01/rdf-schema#comment> "Excarga was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Excarga> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7442d7af-0204-4fd2-b795-6994770b9cd2> .
<https://starwars.com#grid_T16> <http://telicent.io/ontology/primaryName> "T16" .
<https://starwars.com#planet_Excarga> <http://telicent.io/ontology/primaryName> "Excarga" .
<https://starwars.com#sector_Svetta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7442d7af-0204-4fd2-b795-6994770b9cd2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Excarga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T16> .
<https://starwars.com#8d6f8508-59f2-47f1-8520-6c99f666fa48> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7442d7af-0204-4fd2-b795-6994770b9cd2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Excarga"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Svetta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Svetta> <http://telicent.io/ontology/primaryName> "Svetta" .

