Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_DagelinMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_DagelinMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cadma> .
<https://starwars.com#planet_DagelinMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Cadma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cadma> <http://telicent.io/ontology/primaryName> "Cadma" .
<https://starwars.com#planet_DagelinMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Dagelin Minor was an Outer Rim Territories celestial body located in the Cadma sector. A shipment of the flying rodents known as Bogan's brown nafen was at one point imported there for the purposes of combating an infestation of dhuru flies. The nafen, however, caused an outbreak of the Hardan plague that wiped out ninety-eight percent of the local population. In response, Imperial Senator Leia Organa visited Dagelin Minor on a mercy mission. " .
<https://starwars.com#67e06745-3396-4d74-b28c-0011babc0897> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dagelin Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DagelinMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#67e06745-3396-4d74-b28c-0011babc0897> .
<https://starwars.com#sector_Cadma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_DagelinMinor> <http://telicent.io/ontology/primaryName> "Dagelin Minor" .
<https://starwars.com#67e06745-3396-4d74-b28c-0011babc0897> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

