Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pasaana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Ombakondsector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Pasaana> <http://telicent.io/ontology/primaryName> "Pasaana" .
<https://starwars.com#planet_Pasaana> <http://www.w3.org/2000/01/rdf-schema#comment> "A desert planet on the edge of the galaxy, home to the Aki-Aki species." .
<https://starwars.com#47f408c7-8968-41a1-80d0-975afcee8652> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pasaana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pasaana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#sector_Ombakondsector> <http://telicent.io/ontology/primaryName> "Ombakond sector" .
<https://starwars.com#sector_Ombakondsector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pasaana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#47f408c7-8968-41a1-80d0-975afcee8652> .
<https://starwars.com#planet_Pasaana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ombakondsector> .
<https://starwars.com#47f408c7-8968-41a1-80d0-975afcee8652> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

