Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Clantaano> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albanin> .
<https://starwars.com#sector_Albanin> <http://telicent.io/ontology/primaryName> "Albanin" .
<https://starwars.com#planet_Clantaano> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Clantaano> <http://www.w3.org/2000/01/rdf-schema#comment> "Clantaano III, also known as Clantaano, was a desert planet located within the Outer Rim Territories' Albanin sector. It was the homeworld of the nomadic and violent Clantaani species. The Clantaani gunman Longo Two-Guns and his cousins were born on Clantaano III, and they gave rise to a gang of Clantaani criminals that moved offworld by 32 BBY." .
<https://starwars.com#0fd2fada-77d2-44f9-a918-ded15488c718> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Clantaano"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Albanin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Clantaano> <http://telicent.io/ontology/primaryName> "Clantaano" .
<https://starwars.com#planet_Clantaano> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .
<https://starwars.com#sector_Albanin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Clantaano> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0fd2fada-77d2-44f9-a918-ded15488c718> .
<https://starwars.com#0fd2fada-77d2-44f9-a918-ded15488c718> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

