Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ruuria> <http://www.w3.org/2000/01/rdf-schema#comment> "Ruuria was an astronomical object located in the galaxy's Outer Rim Territories along the Hydian Way that was the homeworld of the Ruurian species. It was noted for having pink rivers, along the banks of which chroma-wings would eat, fly, and mate. " .
<https://starwars.com#planet_Ruuria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q3> .
<https://starwars.com#planet_Ruuria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#613aa0e1-8538-420f-ae1f-4bde7de6e4ac> .
<https://starwars.com#sector_Xappyh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ruuria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Xappyh> <http://telicent.io/ontology/primaryName> "Xappyh" .
<https://starwars.com#planet_Ruuria> <http://telicent.io/ontology/primaryName> "Ruuria" .
<https://starwars.com#613aa0e1-8538-420f-ae1f-4bde7de6e4ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ruuria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Xappyh> .
<https://starwars.com#613aa0e1-8538-420f-ae1f-4bde7de6e4ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ruuria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Xappyh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

