Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tatooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Desert planet and childhood home of Anakin Skywalker and Luke Skywalker. Location of Jabba the Hutt's palace." .
<https://starwars.com#planet_Tatooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#8c3764ef-10bc-4e1d-bb4a-9301d848338a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8c3764ef-10bc-4e1d-bb4a-9301d848338a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tatooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tatooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8c3764ef-10bc-4e1d-bb4a-9301d848338a> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tatooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tatooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_Tatooine> <http://telicent.io/ontology/primaryName> "Tatooine" .

