Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dubrillion> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#390dc29a-0f61-4e18-88d2-05318994fad8> .
<https://starwars.com#390dc29a-0f61-4e18-88d2-05318994fad8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dubrillion"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dubrillion> <http://telicent.io/ontology/primaryName> "Dubrillion" .
<https://starwars.com#planet_Dubrillion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Myto> .
<https://starwars.com#sector_Myto> <http://telicent.io/ontology/primaryName> "Myto" .
<https://starwars.com#sector_Myto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#390dc29a-0f61-4e18-88d2-05318994fad8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Myto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dubrillion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#planet_Dubrillion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dubrillion> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .

