Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shili> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a7141c60-5305-4696-bc98-3156acd4e843> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shili"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shili> <http://telicent.io/ontology/primaryName> "Shili" .
<https://starwars.com#planet_Shili> <http://www.w3.org/2000/01/rdf-schema#comment> "Home planet of the Togruta, including Jedi Council member Shaak Ti and Ahsoka Tano." .
<https://starwars.com#sector_Ehosiq> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shili> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#sector_Ehosiq> <http://telicent.io/ontology/primaryName> "Ehosiq" .
<https://starwars.com#a7141c60-5305-4696-bc98-3156acd4e843> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Ehosiq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Shili> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a7141c60-5305-4696-bc98-3156acd4e843> .
<https://starwars.com#planet_Shili> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ehosiq> .

