Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Grumani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Grumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sanrafsix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#planet_Sanrafsix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bc694a7e-3f5b-4ef2-a25c-2fd4339c02b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sanrafsix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Grumani> <http://telicent.io/ontology/primaryName> "Grumani" .
<https://starwars.com#planet_Sanrafsix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Grumani> .
<https://starwars.com#planet_Sanrafsix> <http://www.w3.org/2000/01/rdf-schema#comment> "Sanrafsix was an Outer Rim Territories astronomical object situated in grid square N-17 of the Standard Galactic Grid. It was connected by hyperspace routes to the celestial bodies Darkknell and Omwat as well as the Mid Rim Territories astronomical object Enarc. " .
<https://starwars.com#planet_Sanrafsix> <http://telicent.io/ontology/primaryName> "Sanrafsix" .
<https://starwars.com#bc694a7e-3f5b-4ef2-a25c-2fd4339c02b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sanrafsix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bc694a7e-3f5b-4ef2-a25c-2fd4339c02b7> .

