Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ator> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Ator> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ator> <http://www.w3.org/2000/01/rdf-schema#comment> "Ator was a location in the galaxy. At some point before the formation of the Galactic Empire, Cliegg Lars brought a Thornen Pyramid Puzzle from Ator back to his homestead on Tatooine. " .
<https://starwars.com#planet_Ator> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30b985a2-7f17-4d0b-bf6a-1b966514a192> .
<https://starwars.com#30b985a2-7f17-4d0b-bf6a-1b966514a192> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ator> <http://telicent.io/ontology/primaryName> "Ator" .
<https://starwars.com#30b985a2-7f17-4d0b-bf6a-1b966514a192> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ator"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ator> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

