Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Relgim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdTrasi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#planet_OrdTrasi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Relgim> <http://telicent.io/ontology/primaryName> "Relgim" .
<https://starwars.com#b2765301-95e7-4e67-8a4d-dfdbf9db9289> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdTrasi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Relgim> .
<https://starwars.com#planet_OrdTrasi> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Trasi was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#b2765301-95e7-4e67-8a4d-dfdbf9db9289> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Trasi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdTrasi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2765301-95e7-4e67-8a4d-dfdbf9db9289> .
<https://starwars.com#planet_OrdTrasi> <http://telicent.io/ontology/primaryName> "Ord Trasi" .
<https://starwars.com#sector_Relgim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

