Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kanz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ereesus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .
<https://starwars.com#7e3f34f3-af59-4d57-89f2-65ab566966e1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ereesus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kanz> .
<https://starwars.com#planet_Ereesus> <http://www.w3.org/2000/01/rdf-schema#comment> "Ereesus was a planet in the Kanz sector of the Outer Rim Territories and the homeworld of the Ereesi species. " .
<https://starwars.com#7e3f34f3-af59-4d57-89f2-65ab566966e1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ereesus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kanz> <http://telicent.io/ontology/primaryName> "Kanz" .
<https://starwars.com#planet_Ereesus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kanz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ereesus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e3f34f3-af59-4d57-89f2-65ab566966e1> .
<https://starwars.com#planet_Ereesus> <http://telicent.io/ontology/primaryName> "Ereesus" .

