Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Foless> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Foless> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#52244557-0000-4be6-a4e2-529ef2926abf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Foless"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Foless> <http://www.w3.org/2000/01/rdf-schema#comment> "Foless was an astronomical object located in the galaxy's Colonies region, situated on the Corellian Trade Spine. " .
<https://starwars.com#planet_Foless> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#52244557-0000-4be6-a4e2-529ef2926abf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Foless> <http://telicent.io/ontology/primaryName> "Foless" .
<https://starwars.com#planet_Foless> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#52244557-0000-4be6-a4e2-529ef2926abf> .

