Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hjaff> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#58024412-cfa8-42e9-924c-d10c2770f92a> .
<https://starwars.com#planet_Hjaff> <http://www.w3.org/2000/01/rdf-schema#comment> "Hjaff was a planet located in the Colonies. It was the homeworld of the Tarc, a isolationist species of sentient crustacean creatures. Hjaff had three continents. " .
<https://starwars.com#planet_Hjaff> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#58024412-cfa8-42e9-924c-d10c2770f92a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hjaff> <http://telicent.io/ontology/primaryName> "Hjaff" .
<https://starwars.com#planet_Hjaff> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#58024412-cfa8-42e9-924c-d10c2770f92a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hjaff"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hjaff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

