Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Periphery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#46fd876e-1baa-4d80-a68d-24d42576c8a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#46fd876e-1baa-4d80-a68d-24d42576c8a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yoribuunt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yoribuunt> <http://telicent.io/ontology/primaryName> "Yoribuunt" .
<https://starwars.com#planet_Yoribuunt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46fd876e-1baa-4d80-a68d-24d42576c8a4> .
<https://starwars.com#planet_Yoribuunt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Periphery> .
<https://starwars.com#planet_Yoribuunt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Periphery> <http://telicent.io/ontology/primaryName> "Periphery" .
<https://starwars.com#sector_Periphery> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Yoribuunt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#planet_Yoribuunt> <http://www.w3.org/2000/01/rdf-schema#comment> "Yoribuunt was a beautiful, swirling gas giant in the Yoribuunt system of the Tharin sector near Hutt Space. It was a popular stop for sight-seers on luxury liners. " .

