Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1e203cc4-f437-4609-ad91-3fedce50df91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dachat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dachat> <http://telicent.io/ontology/primaryName> "Dachat" .
<https://starwars.com#planet_Dachat> <http://www.w3.org/2000/01/rdf-schema#comment> "Dachat was a planet on the Hyabb-Twith Corridor. The Nelori Marauders had a base on the planet which allowed them to prey upon both the populations on Hyabb and Twith. The base was destroyed by the Jedi in 4050 BBY. " .
<https://starwars.com#planet_Dachat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dachat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#1e203cc4-f437-4609-ad91-3fedce50df91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dachat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1e203cc4-f437-4609-ad91-3fedce50df91> .
<https://starwars.com#planet_Dachat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .

