Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sedesia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#99ac7980-1e20-4395-86f2-d356cbd30561> .
<https://starwars.com#planet_Sedesia> <http://telicent.io/ontology/primaryName> "Sedesia" .
<https://starwars.com#planet_Sedesia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Druess> .
<https://starwars.com#planet_Sedesia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O16> .
<https://starwars.com#99ac7980-1e20-4395-86f2-d356cbd30561> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sedesia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Druess> <http://telicent.io/ontology/primaryName> "Druess" .
<https://starwars.com#99ac7980-1e20-4395-86f2-d356cbd30561> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Druess> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Druess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Sedesia> <http://www.w3.org/2000/01/rdf-schema#comment> "Sedesia was a high-gravity Mid Rim world with harsh terrain and rough weather. " .
<https://starwars.com#planet_Sedesia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

