Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Algor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Algor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .
<https://starwars.com#planet_Algor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Algor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d887afdd-fd36-4a5d-8b81-78f6c2d1e1e0> .
<https://starwars.com#d887afdd-fd36-4a5d-8b81-78f6c2d1e1e0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_S6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#662b033c-fde1-49a7-b573-b2291abcd007> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#662b033c-fde1-49a7-b573-b2291abcd007> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_S6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#662b033c-fde1-49a7-b573-b2291abcd007> .
<https://starwars.com#planet_Algor> <http://telicent.io/ontology/primaryName> "Algor" .
<https://starwars.com#planet_Algor> <http://www.w3.org/2000/01/rdf-schema#comment> "Algor was a planet in the Algor system of the Tion Cluster famous as a homeworld of pirates, smugglers, and lawyers. The Algorian people were known for their disputatiousness, which became the subject of humor throughout the Tion Cluster. It was the homeworld of Shamus Falconi. Once part of the original Kingdom of Cron, it was absorbed into Xim's Empire before it collapsed in 25,096 BBY, though unlike many worlds in the Tion, the Algorians were not especially proud of their integration into the empire. During the Galactic Civil War, a group of Algor pirates rescued the Wookiee Grasheel and taught him starship engineering. He went on to own a share in the Airlock cantina. " .
<https://starwars.com#grid_S6> <http://telicent.io/ontology/primaryName> "S6" .
<https://starwars.com#d887afdd-fd36-4a5d-8b81-78f6c2d1e1e0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Algor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

