Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Xorth> <http://www.w3.org/2000/01/rdf-schema#comment> "Xorth was a agriworld located within the Xorth system of the Core Worlds. " .
<https://starwars.com#planet_Xorth> <http://telicent.io/ontology/primaryName> "Xorth" .
<https://starwars.com#planet_Xorth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#17b5221c-034b-4129-a820-ae3a59400bc3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xorth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Xorth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#17b5221c-034b-4129-a820-ae3a59400bc3> .
<https://starwars.com#planet_Xorth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#17b5221c-034b-4129-a820-ae3a59400bc3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Xorth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

