Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jodaka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Jodaka> <http://telicent.io/ontology/primaryName> "Jodaka" .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#265365b4-02e6-4d70-b2a6-d9eceb3ee7e1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jodaka"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jodaka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#265365b4-02e6-4d70-b2a6-d9eceb3ee7e1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jodaka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Jodaka> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#265365b4-02e6-4d70-b2a6-d9eceb3ee7e1> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Jodaka> <http://www.w3.org/2000/01/rdf-schema#comment> "Jodaka was a planet of the Jodaka system, within the Corsair Outback area in the Hapes Cluster, a remote region on the Inner Rim of the galaxy. The vast saltwater seas of Jodaka were home to many strange yet deadly creatures, including the Jodakan needler crab, a deceptive and dangerous crustacean non-sentient species. The planet's surface was also composed of many rocky reefs, which the Needler crabs would hop on and use their poisonous projectile needles to take down gulls—a seabird species also native to Jodaka—or to be preyed upon by the birds instead. As with most worlds within the Hapes Cluster, Jodaka was part of the Hapes Consortium, a hereditary monarchy based on the capital world of Hapes. " .

