Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Krann> <http://www.w3.org/2000/01/rdf-schema#comment> "Krann was a planet in the Expansion Region, on the Harrin Trade Corridor. It was taken over by the Galactic Empire for its nova crystals, and the native Kluuzot were enslaved. Following the Battle of Endor, the sector governor seceded and established a neutral terrority. The Kluuzot were freed, and various commercial investors moved to the planet. " .
<https://starwars.com#planet_Krann> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brevost> .
<https://starwars.com#8aa35640-58d8-4d98-8cd3-3dbdea7cc849> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Krann> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8aa35640-58d8-4d98-8cd3-3dbdea7cc849> .
<https://starwars.com#planet_Krann> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Krann> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#sector_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Krann> <http://telicent.io/ontology/primaryName> "Krann" .
<https://starwars.com#8aa35640-58d8-4d98-8cd3-3dbdea7cc849> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Krann"^^<http://www.w3.org/2001/XMLSchema#string> .

