Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5ec96bab-2791-4234-b573-a2cac84e770c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Relatta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Relatta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5ec96bab-2791-4234-b573-a2cac84e770c> .
<https://starwars.com#planet_Relatta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Relatta> <http://www.w3.org/2000/01/rdf-schema#comment> "Relatta was a location in the galaxy. " .
<https://starwars.com#planet_Relatta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#5ec96bab-2791-4234-b573-a2cac84e770c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Relatta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Relatta> <http://telicent.io/ontology/primaryName> "Relatta" .

