Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vaklin> <http://telicent.io/ontology/primaryName> "Vaklin" .
<https://starwars.com#planet_Vaklin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bde65f89-7da5-4b66-93ab-e107383d1e2c> .
<https://starwars.com#planet_Vaklin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Vaklin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bde65f89-7da5-4b66-93ab-e107383d1e2c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vaklin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vaklin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#bde65f89-7da5-4b66-93ab-e107383d1e2c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vaklin> <http://www.w3.org/2000/01/rdf-schema#comment> "Vaklin was a planet located in the Vaklin system of the Inner Rim Territories and the homeworld of Shula Shevu. A world deeply-seated in pro-Jedi tradition, the planet was initially resistant to anti-Jedi propaganda by the Galactic Empire, but eventually succumbed to pressures from Darth Vader. " .

