Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fibuli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eb8b03b4-5729-459d-ad24-7b054a7d6e12> .
<https://starwars.com#planet_Fibuli> <http://www.w3.org/2000/01/rdf-schema#comment> "Fibuli was a planet in Trianii Space annexed by the Corporate Sector Authority. " .
<https://starwars.com#eb8b03b4-5729-459d-ad24-7b054a7d6e12> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fibuli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fibuli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Fibuli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Fibuli> <http://telicent.io/ontology/primaryName> "Fibuli" .
<https://starwars.com#planet_Fibuli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#eb8b03b4-5729-459d-ad24-7b054a7d6e12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

