Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pii> <http://telicent.io/ontology/primaryName> "Pii" .
<https://starwars.com#5357154e-4892-489f-84f2-7877bb569a26> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Pii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5357154e-4892-489f-84f2-7877bb569a26> .
<https://starwars.com#planet_Pii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pii> <http://www.w3.org/2000/01/rdf-schema#comment> "Pii was a planet in the Pii system, located near the Gulf of Tatooine. It was the location of the Galactic Empire's Imperial marshaling station Pii. Fourteen years before the Battle of Yavin, an Imperial convoy planned to travel there from Desolation Station, via a moon coreward of the Gulf of Tatooine, and then jump to Sentinel Base and Geonosis. These plans were interrupted, however, when the convoy was attacked by a rebel cell run by former Republic Intelligence Captain Berch Teller. " .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#5357154e-4892-489f-84f2-7877bb569a26> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Pii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

