Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AlliedTion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jaminere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#03fb3bb5-1490-45f9-84f7-2e2e48edfd53> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jaminere"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jaminere> <http://telicent.io/ontology/primaryName> "Jaminere" .
<https://starwars.com#03fb3bb5-1490-45f9-84f7-2e2e48edfd53> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jaminere> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_AlliedTion> <http://telicent.io/ontology/primaryName> "Allied Tion" .
<https://starwars.com#planet_Jaminere> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#03fb3bb5-1490-45f9-84f7-2e2e48edfd53> .
<https://starwars.com#planet_Jaminere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AlliedTion> .
<https://starwars.com#planet_Jaminere> <http://www.w3.org/2000/01/rdf-schema#comment> "Jaminere was an astronomical object located within the Tion Cluster of the regions known as the Outer Rim Territories and the Slice. Situated along the Shaltin Tunnels hyperspace, which connected it to the astronomical object Cadinth, Jaminere was located in grid square S-6 on the Standard Galactic Grid. " .
<https://starwars.com#sector_AlliedTion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

