Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Anorelga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Anorelga> <http://telicent.io/ontology/primaryName> "Anorelga" .
<https://starwars.com#1eca33ad-7cc9-4c0a-bc75-eca01d90c381> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anorelga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#1eca33ad-7cc9-4c0a-bc75-eca01d90c381> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anorelga"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Anorelga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Braxant> .
<https://starwars.com#planet_Anorelga> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Braxant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Anorelga> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1eca33ad-7cc9-4c0a-bc75-eca01d90c381> .
<https://starwars.com#sector_Braxant> <http://telicent.io/ontology/primaryName> "Braxant" .
<https://starwars.com#sector_Braxant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

