Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Selvaris> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Yuuzhan Vong War, it became the location of a major prisoner-of-war camp under the command of Malik Carr. " .
<https://starwars.com#planet_Selvaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#grid_I9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_I9> <http://telicent.io/ontology/primaryName> "I9" .
<https://starwars.com#grid_I9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_I9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4a0f6b64-7fe6-4200-8d38-b1e546cd713d> .
<https://starwars.com#4a0f6b64-7fe6-4200-8d38-b1e546cd713d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0d4eea96-1b00-4d81-ba02-c1d2458b9f5b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Selvaris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#4a0f6b64-7fe6-4200-8d38-b1e546cd713d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Selvaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I9> .
<https://starwars.com#0d4eea96-1b00-4d81-ba02-c1d2458b9f5b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Selvaris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Selvaris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0d4eea96-1b00-4d81-ba02-c1d2458b9f5b> .
<https://starwars.com#planet_Selvaris> <http://telicent.io/ontology/primaryName> "Selvaris" .

