Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hemei> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_Hemei> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hemei> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca83374c-a7b2-4415-b314-6e116f72e717> .
<https://starwars.com#planet_Hemei> <http://telicent.io/ontology/primaryName> "Hemei" .
<https://starwars.com#ca83374c-a7b2-4415-b314-6e116f72e717> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ca83374c-a7b2-4415-b314-6e116f72e717> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hemei"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hemei> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Hemei> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

