Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kelada> <http://www.w3.org/2000/01/rdf-schema#comment> "Kelada was an astronomical object located in the galaxy's Colonies region, situated along the Corellian Trade Spine. The Labyrinth, a cantina owned by Lorana, was located on Kelada. " .
<https://starwars.com#sector_Kuluur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Kelada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kuluur> .
<https://starwars.com#planet_Kelada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Kelada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#89b9dc3f-9c3e-4f10-92b3-dbe39d787de7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kuluur> <http://telicent.io/ontology/primaryName> "Kuluur" .
<https://starwars.com#planet_Kelada> <http://telicent.io/ontology/primaryName> "Kelada" .
<https://starwars.com#89b9dc3f-9c3e-4f10-92b3-dbe39d787de7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kelada"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kuluur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kelada> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89b9dc3f-9c3e-4f10-92b3-dbe39d787de7> .

