Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zebitrope> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zebitrope> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#87964e51-b5dc-41f0-a1e9-a1b858f283d8> .
<https://starwars.com#planet_Zebitrope> <http://telicent.io/ontology/primaryName> "Zebitrope" .
<https://starwars.com#87964e51-b5dc-41f0-a1e9-a1b858f283d8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zebitrope"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#87964e51-b5dc-41f0-a1e9-a1b858f283d8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zebitrope> <http://www.w3.org/2000/01/rdf-schema#comment> "The Zebitrope system was a part of the Centrality sector in the Slice portion of the Outer Rim Territories. It was situated at the endpoint of the Cadma Conduit hyperlane, which connected it to the Cadma system." .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Zebitrope> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Zebitrope> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .

