Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5c83c241-42ba-45b9-bb96-173998e03eb6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5c83c241-42ba-45b9-bb96-173998e03eb6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thomork"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thomork> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5c83c241-42ba-45b9-bb96-173998e03eb6> .
<https://starwars.com#planet_Thomork> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Thomork> <http://www.w3.org/2000/01/rdf-schema#comment> "A Core Worlds astronomical object, Thomork was the site of an Imperial Military shipyard. Shortly before the Battle of Endor, the facility produced Imperial-class Star Destroyers. Years before 10 ABY, the Empire spread the rumor that the Thomork shipyard was closed due to a hive virus outbreak and, to lend credence to the rumor, killed over 450 people there. The shipyard was then secretly re-opened and used for Imperial construction projects such as the first World Devastator superweapon. " .
<https://starwars.com#planet_Thomork> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Thomork> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thomork> <http://telicent.io/ontology/primaryName> "Thomork" .

