Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Randon> <http://www.w3.org/2000/01/rdf-schema#comment> "Randon was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Randon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#77af3a80-e1dc-4d69-a365-1f04700aa9cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Randon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Randon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Randon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#77af3a80-e1dc-4d69-a365-1f04700aa9cd> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Randon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#planet_Randon> <http://telicent.io/ontology/primaryName> "Randon" .
<https://starwars.com#77af3a80-e1dc-4d69-a365-1f04700aa9cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

