Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Baltizaar> <http://telicent.io/ontology/primaryName> "Baltizaar" .
<https://starwars.com#22e11e70-12dc-4ba0-b7ac-411d02f4cf38> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Baltizaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Baltizaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Baltizaar was a world in the galaxy. When Princess Leia Organa traveled to the Paucris system to warn the fleet of an impending Imperial attack, she realized that traveling directly back to Coruscant might be risky, so she instead set a course for Baltizaar. Before she could leave Paucris, however, she discovered that Kier Domadi had traveled to the system aboard a cutter. " .
<https://starwars.com#014bd885-3222-4a4b-b753-5ed217a3e580> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K7> <http://telicent.io/ontology/primaryName> "K7" .
<https://starwars.com#014bd885-3222-4a4b-b753-5ed217a3e580> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Baltizaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K7> .
<https://starwars.com#grid_K7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Corthenia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Corthenia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_K7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#014bd885-3222-4a4b-b753-5ed217a3e580> .
<https://starwars.com#22e11e70-12dc-4ba0-b7ac-411d02f4cf38> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Baltizaar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Baltizaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#22e11e70-12dc-4ba0-b7ac-411d02f4cf38> .
<https://starwars.com#grid_K7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Baltizaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corthenia> .
<https://starwars.com#sector_Corthenia> <http://telicent.io/ontology/primaryName> "Corthenia" .

