Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b42d2455-9ceb-471b-8cda-54da52f35a48> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_UR-8827> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b42d2455-9ceb-471b-8cda-54da52f35a48> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b42d2455-9ceb-471b-8cda-54da52f35a48> <http://ies.data.gov.uk/ontology/ies4#representationValue> "UR-8827"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_UR-8827> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_UR-8827> <http://www.w3.org/2000/01/rdf-schema#comment> "UR-8827 was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It shared a similar designation to the nearby UR-1060, UR-2650, UR-3741, and UR-9353. UR-8827 was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_UR-8827> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_UR-8827> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_UR-8827> <http://telicent.io/ontology/primaryName> "UR-8827" .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

