Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zaria> <http://www.w3.org/2000/01/rdf-schema#comment> "Zaria was a terrestrial world located in the Zaria system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. The Senex-Juvex Loop hyperlane linked it to the Anstares and Malador systems. " .
<https://starwars.com#planet_Zaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Zaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Zaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Zaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#659ac520-1a4b-4db2-9061-899b4fac4b8e> .
<https://starwars.com#659ac520-1a4b-4db2-9061-899b4fac4b8e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zaria> <http://telicent.io/ontology/primaryName> "Zaria" .
<https://starwars.com#659ac520-1a4b-4db2-9061-899b4fac4b8e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

