Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3f849156-77d3-4cec-a2ee-51dc600017bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ogem"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ogem> <http://telicent.io/ontology/primaryName> "Ogem" .
<https://starwars.com#planet_Ogem> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3f849156-77d3-4cec-a2ee-51dc600017bf> .
<https://starwars.com#planet_Ogem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_DAelgoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_DAelgoth> <http://telicent.io/ontology/primaryName> "D'Aelgoth" .
<https://starwars.com#planet_Ogem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#sector_DAelgoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ogem> <http://www.w3.org/2000/01/rdf-schema#comment> "Ogem was a planet in a remote section of the Western Reaches, near the desert planet Jakku. " .
<https://starwars.com#planet_Ogem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAelgoth> .
<https://starwars.com#3f849156-77d3-4cec-a2ee-51dc600017bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

