Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4309042d-0918-4bf4-bbf4-a3912a281de5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Groth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#4309042d-0918-4bf4-bbf4-a3912a281de5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Groth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Groth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Groth> <http://telicent.io/ontology/primaryName> "Groth" .
<https://starwars.com#planet_Groth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4309042d-0918-4bf4-bbf4-a3912a281de5> .
<https://starwars.com#planet_Groth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Groth> <http://www.w3.org/2000/01/rdf-schema#comment> "Groth was a planet that was located within the star system of the same name and lay deep within the Bootana Hutta area of the galaxy's Hutt Space region. A former throneworld of the Hutt species, the planet eventually became a resort that was the site of gladiatorial exhibitions and gambling. During the Cold War between the Galactic Republic and the resurgent Sith Empire in the year 3643 BBY, an information broker on Groth sliced into the military database of the Empire. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

