Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Betha> <http://telicent.io/ontology/primaryName> "Betha" .
<https://starwars.com#planet_Betha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P4> .
<https://starwars.com#planet_Betha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_P4> <http://telicent.io/ontology/primaryName> "P4" .
<https://starwars.com#fbc64bf0-cb6c-4c4b-b4a7-b004bae31714> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_P4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_P4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#434d44bf-2dd3-4d96-a73e-7971cd66f511> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Corva> <http://telicent.io/ontology/primaryName> "Corva" .
<https://starwars.com#434d44bf-2dd3-4d96-a73e-7971cd66f511> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Betha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#fbc64bf0-cb6c-4c4b-b4a7-b004bae31714> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Betha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#434d44bf-2dd3-4d96-a73e-7971cd66f511> .
<https://starwars.com#sector_Corva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Betha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corva> .
<https://starwars.com#sector_Corva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Betha> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#grid_P4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#fbc64bf0-cb6c-4c4b-b4a7-b004bae31714> .

