Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kubindi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89d6bb91-01d1-497e-a1ed-7c20f59db675> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#89d6bb91-01d1-497e-a1ed-7c20f59db675> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kubindi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#89d6bb91-01d1-497e-a1ed-7c20f59db675> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kubindi> <http://www.w3.org/2000/01/rdf-schema#comment> "Kubindi was a planet located in the galaxy's Outer Rim Territories that was the homeworld of the insectivorous Kubaz species. Its population was enslaved by the Galactic Empire, and the Kubaz spy and Kubindi native Garindan ezz Zavor plotted to free his world and its people from Imperial oppression. " .
<https://starwars.com#planet_Kubindi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T9> .
<https://starwars.com#planet_Kubindi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#planet_Kubindi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kubindi> <http://telicent.io/ontology/primaryName> "Kubindi" .

