Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Desevro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Desevro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#fc84b7a0-28f7-46fa-bbf0-d171b68ce338> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Desevro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Desevro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fc84b7a0-28f7-46fa-bbf0-d171b68ce338> .
<https://starwars.com#planet_Desevro> <http://telicent.io/ontology/primaryName> "Desevro" .
<https://starwars.com#planet_Desevro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Desevro> <http://www.w3.org/2000/01/rdf-schema#comment> "Desevro was an astronomical object located in the Tion Cluster of the galaxy's Outer Rim Territories. It was also located on the Perlemian Trade Route. It was contested territory during the Galactic Civil War. " .
<https://starwars.com#fc84b7a0-28f7-46fa-bbf0-d171b68ce338> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

