Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cularin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Thaere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Thaere> <http://telicent.io/ontology/primaryName> "Thaere" .
<https://starwars.com#fd057c1a-0eee-4de5-8565-31c018ffabca> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cularin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cularin> <http://www.w3.org/2000/01/rdf-schema#comment> "Cularin was an astronomical object located in the galaxy's Expansion Region. During the Clone Wars, a battle was fought there, during which the lead Maelstrom-class battle cruiser, Maelstrom, served with distinction under the command of Jedi General Darrus Jeht. " .
<https://starwars.com#planet_Cularin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thaere> .
<https://starwars.com#planet_Cularin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#planet_Cularin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fd057c1a-0eee-4de5-8565-31c018ffabca> .
<https://starwars.com#sector_Thaere> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#fd057c1a-0eee-4de5-8565-31c018ffabca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cularin> <http://telicent.io/ontology/primaryName> "Cularin" .

