Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jovan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#f7226b94-fbe1-47b9-bc78-faf57bec5c93> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jovan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jovan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_Jovan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f7226b94-fbe1-47b9-bc78-faf57bec5c93> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Jovan> <http://www.w3.org/2000/01/rdf-schema#comment> "Jovan was a male human who served in the military forces of the Galactic Empire in the years prior to the Battle of Yavin. He used his station within the Imperial military to enrich his own life, which resulted in his arrest by his former friend, Agent Kallus of the Imperial Security Bureau. " .
<https://starwars.com#planet_Jovan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jovan> <http://telicent.io/ontology/primaryName> "Jovan" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f7226b94-fbe1-47b9-bc78-faf57bec5c93> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

