Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mallordian> <http://www.w3.org/2000/01/rdf-schema#comment> "Mall'ordian was a planet in the Corporate Sector. A popular tourist destination, it was renown for its crystalline forests. The Corporate Sector Authority was interested in the planet for its potential resources. " .
<https://starwars.com#planet_Mallordian> <http://telicent.io/ontology/primaryName> "Mall'ordian" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#82c3da5d-6c98-4d71-91d1-2c908f5f8f34> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mall'ordian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mallordian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#82c3da5d-6c98-4d71-91d1-2c908f5f8f34> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mallordian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mallordian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#planet_Mallordian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82c3da5d-6c98-4d71-91d1-2c908f5f8f34> .

