Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mindabaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#54ecf63c-6294-4ed1-adf3-04b9b275ec13> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mindabaal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mindabaal> <http://telicent.io/ontology/primaryName> "Mindabaal" .
<https://starwars.com#planet_Mindabaal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mindabaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Mindabaal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54ecf63c-6294-4ed1-adf3-04b9b275ec13> .
<https://starwars.com#54ecf63c-6294-4ed1-adf3-04b9b275ec13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mindabaal> <http://www.w3.org/2000/01/rdf-schema#comment> "Mindabaal was a planet located in the Inner Rim of the galaxy. " .

