Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Meridian> <http://telicent.io/ontology/primaryName> "Meridian" .
<https://starwars.com#planet_Budpock> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#planet_Budpock> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#afafb9ef-669a-4877-a936-1c8d9df6d6da> .
<https://starwars.com#planet_Budpock> <http://www.w3.org/2000/01/rdf-schema#comment> "Budpock was a long time supporter of the Rebel Alliance and a New Republic-aligned planet in the Meridian sector. However, the world was also a haven for pirate gangs. Many of these groups were provoked by Dzym to attack neighboring Ampliquen, breaking the truce between Budpock and Ampliquen. " .
<https://starwars.com#afafb9ef-669a-4877-a936-1c8d9df6d6da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Meridian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Meridian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Budpock> <http://telicent.io/ontology/primaryName> "Budpock" .
<https://starwars.com#afafb9ef-669a-4877-a936-1c8d9df6d6da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Budpock"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Budpock> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meridian> .
<https://starwars.com#planet_Budpock> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

