Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0dfea7a0-3dab-4a99-b87d-956a04e1f6b1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kinoss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0dfea7a0-3dab-4a99-b87d-956a04e1f6b1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kinoss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0dfea7a0-3dab-4a99-b87d-956a04e1f6b1> .
<https://starwars.com#planet_Kinoss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Kinoss> <http://telicent.io/ontology/primaryName> "Kinoss" .
<https://starwars.com#planet_Kinoss> <http://www.w3.org/2000/01/rdf-schema#comment> "Kinoss was a planet located in the Kinoss system of the Unknown Regions. It was situated within the borders of the Chiss Ascendancy. " .
<https://starwars.com#planet_Kinoss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Kinoss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

