Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Salient> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Salient> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#4bded852-6a02-40b0-8868-e668e3a295d4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Salient"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Salient> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Salient> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Salient> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4bded852-6a02-40b0-8868-e668e3a295d4> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Salient> <http://telicent.io/ontology/primaryName> "Salient" .
<https://starwars.com#4bded852-6a02-40b0-8868-e668e3a295d4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

