Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Momansi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#82f261b4-3383-4e46-a1ab-072576654140> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#82f261b4-3383-4e46-a1ab-072576654140> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Momansi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Momansi> <http://telicent.io/ontology/primaryName> "Momansi" .
<https://starwars.com#planet_Momansi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brevost> .
<https://starwars.com#planet_Momansi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82f261b4-3383-4e46-a1ab-072576654140> .
<https://starwars.com#sector_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Momansi> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Momansi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

