Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chardaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1200ff55-806b-45c1-9d56-dfb4f62c47b3> .
<https://starwars.com#1200ff55-806b-45c1-9d56-dfb4f62c47b3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_N13> <http://telicent.io/ontology/primaryName> "N13" .
<https://starwars.com#planet_Chardaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Chardaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#grid_N13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_N13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#a8eec3eb-af1a-4c4f-a3fe-03a195c1a5a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chardaan> <http://telicent.io/ontology/primaryName> "Chardaan" .
<https://starwars.com#planet_Chardaan> <http://www.w3.org/2000/01/rdf-schema#comment> "Chardaan was an astronomical object located in the galaxy's Inner Rim, in the Chardaan system. It was on the Hydian Way hyperspace route. " .
<https://starwars.com#1200ff55-806b-45c1-9d56-dfb4f62c47b3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chardaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a8eec3eb-af1a-4c4f-a3fe-03a195c1a5a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_N13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#a8eec3eb-af1a-4c4f-a3fe-03a195c1a5a4> .
<https://starwars.com#planet_Chardaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

