Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FelHu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#07d02bc2-b2d7-4d48-b669-6ea3a1cd5d6c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aikhibba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ff46ce4e-2973-410c-8625-5ea9c7ca3149> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ff46ce4e-2973-410c-8625-5ea9c7ca3149> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aikhibba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P13> .
<https://starwars.com#planet_Aikhibba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#07d02bc2-b2d7-4d48-b669-6ea3a1cd5d6c> .
<https://starwars.com#grid_P13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Aikhibba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#07d02bc2-b2d7-4d48-b669-6ea3a1cd5d6c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aikhibba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FelHu> .
<https://starwars.com#planet_Aikhibba> <http://www.w3.org/2000/01/rdf-schema#comment> "Aikhibba was a Mid Rim planet in the Aikhibba system; a minor stopping point off the Gamor Run. " .
<https://starwars.com#planet_Aikhibba> <http://telicent.io/ontology/primaryName> "Aikhibba" .
<https://starwars.com#sector_FelHu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_P13> <http://telicent.io/ontology/primaryName> "P13" .
<https://starwars.com#grid_P13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ff46ce4e-2973-410c-8625-5ea9c7ca3149> .
<https://starwars.com#grid_P13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_FelHu> <http://telicent.io/ontology/primaryName> "Fel Hu" .

