Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hethar> <http://www.w3.org/2000/01/rdf-schema#comment> "Over the following years, gornt breeding on Hethar began to face problems related to the creatures' reproduction, drawing Imperial geneticists to visit the planet in an attempt to solve the difficulties. During the Galactic Civil War, a Rebel Alliance team on Hethar encountered a pack of local shredder bats that were eventually repelled via the use of the excluder device. " .
<https://starwars.com#planet_Hethar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hethar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#03f10ca4-e1ec-4766-b0f5-69c8ed2f80fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hethar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hethar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#03f10ca4-e1ec-4766-b0f5-69c8ed2f80fa> .
<https://starwars.com#planet_Hethar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Hethar> <http://telicent.io/ontology/primaryName> "Hethar" .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#03f10ca4-e1ec-4766-b0f5-69c8ed2f80fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

