Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ojom> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2d808402-b7e2-435c-aae3-e1e3c146f224> .
<https://starwars.com#planet_Ojom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Ojom> <http://www.w3.org/2000/01/rdf-schema#comment> "Ojom was a world located in the galaxy's Deep Core that was the homeworld of the Besalisk species. The chef Dexter Jettster and Jedi Master Pong Krell were both Besalisks from Ojom. " .
<https://starwars.com#2d808402-b7e2-435c-aae3-e1e3c146f224> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ojom"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ojom> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ojom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#2d808402-b7e2-435c-aae3-e1e3c146f224> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ojom> <http://telicent.io/ontology/primaryName> "Ojom" .

