Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalgo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#0444e465-789f-4b9c-907d-1a0f3742b21b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kalgo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0444e465-789f-4b9c-907d-1a0f3742b21b> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kalgo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalgo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Kalgo> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Kalgo> <http://telicent.io/ontology/primaryName> "Kalgo" .
<https://starwars.com#0444e465-789f-4b9c-907d-1a0f3742b21b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalgo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

