Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mortis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K2> .
<https://starwars.com#grid_K2> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Mortis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#22515a9b-a916-4ce2-8ebd-74c5e1a90314> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mortis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#22515a9b-a916-4ce2-8ebd-74c5e1a90314> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mortis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#0eabe2c5-3c4d-413a-83b0-59f9909a0fb5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Mortis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#22515a9b-a916-4ce2-8ebd-74c5e1a90314> .
<https://starwars.com#planet_Mortis> <http://telicent.io/ontology/primaryName> "Mortis" .
<https://starwars.com#0eabe2c5-3c4d-413a-83b0-59f9909a0fb5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K2"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mortis> <http://www.w3.org/2000/01/rdf-schema#comment> "Planet existing in the spiritual realm within the Force, with a wall surrounding it, home to the three near-omnipotent Force wielders known only in the Jedi Archives as the Mortis Gods. It is said that 'the planet is a conduit through which the Force flows.'" .
<https://starwars.com#grid_K2> <http://telicent.io/ontology/primaryName> "K2" .
<https://starwars.com#grid_K2> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0eabe2c5-3c4d-413a-83b0-59f9909a0fb5> .

