Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KlasseEphemora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_KlasseEphemora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F9> .
<https://starwars.com#planet_KlasseEphemora> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KlasseEphemora> <http://www.w3.org/2000/01/rdf-schema#comment> "Klasse Ephemora, also known as Mobus, was an astronomical object within the territory of the Chiss Ascendancy in the Unknown Regions. " .
<https://starwars.com#planet_KlasseEphemora> <http://telicent.io/ontology/primaryName> "Klasse Ephemora" .
<https://starwars.com#planet_KlasseEphemora> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6531e6e9-ae37-44d5-89cd-eea60dcfbc14> .
<https://starwars.com#6531e6e9-ae37-44d5-89cd-eea60dcfbc14> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Klasse Ephemora"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6531e6e9-ae37-44d5-89cd-eea60dcfbc14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

