Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#30f8ae8c-8f4f-46fa-a4c7-bf2a38b689be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_XaFel> <http://telicent.io/ontology/primaryName> "Xa Fel" .
<https://starwars.com#planet_XaFel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30f8ae8c-8f4f-46fa-a4c7-bf2a38b689be> .
<https://starwars.com#planet_XaFel> <http://www.w3.org/2000/01/rdf-schema#comment> "Xa Fel was an astronomical object in the Core Worlds that housed a shipyard. During the Galactic Civil War, the shipyard of Xa Fel served the Galactic Empire. After the start of Operation Ringbreaker, General Crix Madine of the Rebellion designated it as a medium-priority target with low security level on a galactic map included in The Rebel Files, a top-secret dossier of sensitive information vital to the Rebellion. In 5 ABY, the New Republic fought to gain control of it. " .
<https://starwars.com#planet_XaFel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#30f8ae8c-8f4f-46fa-a4c7-bf2a38b689be> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xa Fel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_XaFel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_XaFel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .

