Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Heffrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#57f70442-4a69-45f1-9365-111f1f9679eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Heffrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Heffrin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#57f70442-4a69-45f1-9365-111f1f9679eb> .
<https://starwars.com#planet_Heffrin> <http://www.w3.org/2000/01/rdf-schema#comment> "Heffrin was a planet located in the Arkanis sector of the Outer Rim. This mountainous world was a small mining colony maintained by the Galactic Empire. The planet held important ruins from a vanished civilization, including the Heffrin Aqueducts, which spanned Heffrin's continents; research during the Cold War between the Galactic Republic and the Sith Empire identified the Aqueducts' builders as early Ithorian explorers. " .
<https://starwars.com#57f70442-4a69-45f1-9365-111f1f9679eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Heffrin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Heffrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Heffrin> <http://telicent.io/ontology/primaryName> "Heffrin" .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

