Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Uogocor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trax> .
<https://starwars.com#planet_Uogocor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d6120617-e4ab-4646-903b-d8bf0243dbe5> .
<https://starwars.com#planet_Uogocor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#sector_Trax> <http://telicent.io/ontology/primaryName> "Trax" .
<https://starwars.com#sector_Trax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#d6120617-e4ab-4646-903b-d8bf0243dbe5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Uogocor> <http://www.w3.org/2000/01/rdf-schema#comment> "Uogo'cor was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_Trax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Uogocor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d6120617-e4ab-4646-903b-d8bf0243dbe5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Uogo'cor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Uogocor> <http://telicent.io/ontology/primaryName> "Uogo'cor" .

