Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#04d28ceb-3485-49ae-9559-7a7e08d69b71> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dasoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Agarix> .
<https://starwars.com#planet_Dasoor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#04d28ceb-3485-49ae-9559-7a7e08d69b71> .
<https://starwars.com#planet_Dasoor> <http://telicent.io/ontology/primaryName> "Dasoor" .
<https://starwars.com#sector_Agarix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Agarix> <http://telicent.io/ontology/primaryName> "Agarix" .
<https://starwars.com#planet_Dasoor> <http://www.w3.org/2000/01/rdf-schema#comment> "Dasoor was a planet located in the Mid Rim region of the galaxy. It was known as a world overrun by thieves, and gangs of slavers. Some months after the Battle of Endor, the smuggler Han Solo and his Wookiee co-pilot Chewbacca were headed to this planet, before changing course to the Wookiee's home planet of Kashyyyk. " .
<https://starwars.com#sector_Agarix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#04d28ceb-3485-49ae-9559-7a7e08d69b71> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dasoor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dasoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Dasoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

