Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Daemen> <http://telicent.io/ontology/primaryName> "Daemen" .
<https://starwars.com#sector_Woostri> <http://telicent.io/ontology/primaryName> "Woostri" .
<https://starwars.com#planet_Daemen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#53e9197e-33dd-4e3c-8565-ddb570040daf> .
<https://starwars.com#53e9197e-33dd-4e3c-8565-ddb570040daf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Daemen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Daemen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#planet_Daemen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Woostri> .
<https://starwars.com#planet_Daemen> <http://www.w3.org/2000/01/rdf-schema#comment> "Daemen was a planet on the Rimma Trade Route in the Expansion Region, home to the Clarion Scholars Academy. " .
<https://starwars.com#planet_Daemen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Woostri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#53e9197e-33dd-4e3c-8565-ddb570040daf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Woostri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

