Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thesme> <http://www.w3.org/2000/01/rdf-schema#comment> "Thesme was a planet located within the Thesme system of the Outer Rim Territories. An industrial world, it served as the lackluster sector capital of Thesme sector, on the Thesme Trace. " .
<https://starwars.com#planet_Thesme> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#19785b29-f0c6-4841-a14a-f37ac7051e12> .
<https://starwars.com#19785b29-f0c6-4841-a14a-f37ac7051e12> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thesme"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Thesme> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#19785b29-f0c6-4841-a14a-f37ac7051e12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Thesme> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Thesme> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#planet_Thesme> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thesme> .
<https://starwars.com#sector_Thesme> <http://telicent.io/ontology/primaryName> "Thesme" .
<https://starwars.com#planet_Thesme> <http://telicent.io/ontology/primaryName> "Thesme" .
<https://starwars.com#planet_Thesme> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

