Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Esstran> <http://telicent.io/ontology/primaryName> "Esstran" .
<https://starwars.com#planet_Odacer-Faustin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Odacer-Faustin> <http://www.w3.org/2000/01/rdf-schema#comment> "Odacer-Faustin was a planet with a cold harsh terrain. Heavy snow and high winds constantly buffeted the world. " .
<https://starwars.com#sector_Esstran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#341c66bd-87e9-4355-a206-8122babf293b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Odacer-Faustin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Odacer-Faustin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esstran> .
<https://starwars.com#planet_Odacer-Faustin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Odacer-Faustin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#341c66bd-87e9-4355-a206-8122babf293b> .
<https://starwars.com#planet_Odacer-Faustin> <http://telicent.io/ontology/primaryName> "Odacer-Faustin" .
<https://starwars.com#sector_Esstran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#341c66bd-87e9-4355-a206-8122babf293b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

