Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#46e0249f-2278-40e0-8872-31a6820af806> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kothlis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_BothanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kothlis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BothanSpace> .
<https://starwars.com#planet_Kothlis> <http://telicent.io/ontology/primaryName> "Kothlis" .
<https://starwars.com#planet_Kothlis> <http://www.w3.org/2000/01/rdf-schema#comment> "Kothlis was an astronomical object located within Bothan Space of the galaxy's Mid Rim. Luke Skywalker was stationed on Kothlis during the conclusion of Princess Leia Organa's involvement in Operation Yellow Moon. Following the completion of her mission, Organa contacted Skywalker at Kothlis, from where he informed her that the Rebel Alliance had discovered the whereabouts of Han Solo, still trapped in carbonite. Organa informed Skywalker that she would tell him about an idea she had about a role she could play in their attempt to rescue Solo when she reached Kothlis. " .
<https://starwars.com#sector_BothanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kothlis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#planet_Kothlis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46e0249f-2278-40e0-8872-31a6820af806> .
<https://starwars.com#planet_Kothlis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#46e0249f-2278-40e0-8872-31a6820af806> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BothanSpace> <http://telicent.io/ontology/primaryName> "Bothan Space" .

