Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mierukar> <http://telicent.io/ontology/primaryName> "Mieru'kar" .
<https://starwars.com#sector_Mierukar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MalthaObex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mierukar> .
<https://starwars.com#e56092e3-5b6b-4c5b-8a6c-877775ee7f4c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MalthaObex> <http://telicent.io/ontology/primaryName> "Maltha Obex" .
<https://starwars.com#planet_MalthaObex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MalthaObex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e56092e3-5b6b-4c5b-8a6c-877775ee7f4c> .
<https://starwars.com#planet_MalthaObex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O3> .
<https://starwars.com#sector_Mierukar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#e56092e3-5b6b-4c5b-8a6c-877775ee7f4c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Maltha Obex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MalthaObex> <http://www.w3.org/2000/01/rdf-schema#comment> "Maltha Obex was an astronomical object located in the galaxy's Outer Rim Territories. " .

