Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bortele> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#36104912-c969-4382-9bf6-4e51287aeaa0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ingo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#36104912-c969-4382-9bf6-4e51287aeaa0> .
<https://starwars.com#planet_Ingo> <http://telicent.io/ontology/primaryName> "Ingo" .
<https://starwars.com#planet_Ingo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bortele> .
<https://starwars.com#planet_Ingo> <http://www.w3.org/2000/01/rdf-schema#comment> "Ingo was a location in the galaxy. In 0 BBY, Rebel corporal Eskro Casrich sun-sailed its dunes prior to the Battle of Scarif. " .
<https://starwars.com#planet_Ingo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#36104912-c969-4382-9bf6-4e51287aeaa0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ingo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ingo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bortele> <http://telicent.io/ontology/primaryName> "Bortele" .
<https://starwars.com#sector_Bortele> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

