Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_OutlandTransit> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5f2f650f-70ec-4e67-9284-5debd541db6e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Outland Transit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_T12> <http://telicent.io/ontology/primaryName> "T12" .
<https://starwars.com#planet_OutlandTransit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#8c60dad6-317a-4c13-998d-16eda446ea6d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OutlandTransit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T12> .
<https://starwars.com#5f2f650f-70ec-4e67-9284-5debd541db6e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#grid_T12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8c60dad6-317a-4c13-998d-16eda446ea6d> .
<https://starwars.com#planet_OutlandTransit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5f2f650f-70ec-4e67-9284-5debd541db6e> .
<https://starwars.com#planet_OutlandTransit> <http://telicent.io/ontology/primaryName> "Outland Transit" .
<https://starwars.com#planet_OutlandTransit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_T12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#8c60dad6-317a-4c13-998d-16eda446ea6d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

