Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TertiaryKesmere> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b67b5e3f-412a-453c-b442-301d7ddb0715> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_TertiaryKesmere> <http://telicent.io/ontology/primaryName> "Tertiary Kesmere" .
<https://starwars.com#planet_TertiaryKesmere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#planet_TertiaryKesmere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#planet_TertiaryKesmere> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b67b5e3f-412a-453c-b442-301d7ddb0715> .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#b67b5e3f-412a-453c-b442-301d7ddb0715> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tertiary Kesmere"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TertiaryKesmere> <http://www.w3.org/2000/01/rdf-schema#comment> "Tertiary Kesmere was a cloudy, storm-wracked world located in the Tertiary Kesmere system, a part of the Raioballo sector in the New Territories portion of the Outer Rim Territories. It was the homeworld of the winged hornagaunt species, including the wing-clipped pet Grendel. Between 4 ABY and 12 ABY, Tertiary Kesmere fell within the borders of the Pentastar Alignment. " .

