Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kirtarkin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#5a5b57e0-0338-4c4f-8309-9a9371424442> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kirtarkin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kirtarkin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5a5b57e0-0338-4c4f-8309-9a9371424442> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kirtarkin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Kirtarkin> <http://telicent.io/ontology/primaryName> "Kirtarkin" .
<https://starwars.com#planet_Kirtarkin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kirtarkin> <http://www.w3.org/2000/01/rdf-schema#comment> "Kirtarkin was a planet located in Kirtarkin system of the Anoat sector, in the galaxy's Outer Rim Territories. The Galactic Empire had several depots on Kirtarkin that contained large recycling centers, though they were too late to save the world's polluted environment. " .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5a5b57e0-0338-4c4f-8309-9a9371424442> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

