Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d9106b30-72f9-4ea2-87c0-7496e704101e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "B'trilla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Btrilla> <http://telicent.io/ontology/primaryName> "B'trilla" .
<https://starwars.com#planet_Btrilla> <http://www.w3.org/2000/01/rdf-schema#comment> "B'trilla was a planet in the Gordian Reach of the Outer Rim. " .
<https://starwars.com#planet_Btrilla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d9106b30-72f9-4ea2-87c0-7496e704101e> .
<https://starwars.com#d9106b30-72f9-4ea2-87c0-7496e704101e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Btrilla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Btrilla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Btrilla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

