Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Malachor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Malachor> <http://telicent.io/ontology/primaryName> "Malachor" .
<https://starwars.com#planet_Malachor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Malachor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#5917c8d7-a52b-4902-b5a6-6d6b8818baa3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Malachor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Malachor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5917c8d7-a52b-4902-b5a6-6d6b8818baa3> .
<https://starwars.com#planet_Malachor> <http://www.w3.org/2000/01/rdf-schema#comment> "Desolate Sith temple world and site of two major battles thousands of year apart: one involving the Scourge of Malachor, the other between Darth Maul, several Rebels, Darth Vader, and several Inquisitors." .
<https://starwars.com#5917c8d7-a52b-4902-b5a6-6d6b8818baa3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

