Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Odik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Odik> <http://telicent.io/ontology/primaryName> "Odik" .
<https://starwars.com#6571f4f3-d258-4e24-883a-d86ee03a0209> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Odik> <http://www.w3.org/2000/01/rdf-schema#comment> "Odik was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Odik> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6571f4f3-d258-4e24-883a-d86ee03a0209> .
<https://starwars.com#planet_Odik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K11> .
<https://starwars.com#planet_Odik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#6571f4f3-d258-4e24-883a-d86ee03a0209> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Odik"^^<http://www.w3.org/2001/XMLSchema#string> .

