Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Caamas> <http://telicent.io/ontology/primaryName> "Caamas" .
<https://starwars.com#planet_Caamas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Caamas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#e388a8b3-b009-4f23-b364-6200b536e097> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Caamas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Caamas> <http://www.w3.org/2000/01/rdf-schema#comment> "Caamas was an astronomical body located in the Cirius system within the galaxy's Core Worlds. It shared its name with Caamasi light sculpture, and Caamasi cheese pie. During the reign of the Galactic Empire, Caamas suffered from the horrors inflicted upon it that were comparable to the destruction of Alderaan. " .
<https://starwars.com#planet_Caamas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e388a8b3-b009-4f23-b364-6200b536e097> .
<https://starwars.com#planet_Caamas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e388a8b3-b009-4f23-b364-6200b536e097> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

