Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_InnerCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .
<https://starwars.com#9d6b8acb-3ec3-40dd-891e-3bde69fe651e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9d6b8acb-3ec3-40dd-891e-3bde69fe651e> .
<https://starwars.com#planet_Cona> <http://telicent.io/ontology/primaryName> "Cona" .
<https://starwars.com#planet_Cona> <http://www.w3.org/2000/01/rdf-schema#comment> "Cona was a desert planet located in the galaxy's Inner Rim that was the homeworld of the Arcona species. Hem Dazon, a male Arcona frequently spent time in the Mos Eisley cantina after becoming stranded on Tatooine. He was unable to return to his home planet because he had spent all his credits on salt and juri juice. " .
<https://starwars.com#sector_InnerCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_InnerCluster> <http://telicent.io/ontology/primaryName> "Inner Cluster" .
<https://starwars.com#9d6b8acb-3ec3-40dd-891e-3bde69fe651e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cona"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_InnerCluster> .

