Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalevala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mandalore> .
<https://starwars.com#2e43cfed-acad-429d-aea4-6cad3ffe8d5d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalevala"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mandalore> <http://telicent.io/ontology/primaryName> "Mandalore" .
<https://starwars.com#planet_Kalevala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#2e43cfed-acad-429d-aea4-6cad3ffe8d5d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kalevala> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalevala> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e43cfed-acad-429d-aea4-6cad3ffe8d5d> .
<https://starwars.com#planet_Kalevala> <http://telicent.io/ontology/primaryName> "Kalevala" .
<https://starwars.com#sector_Mandalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kalevala> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalevala was a planet located in the Mandalore system, within the Mandalore sector of the galaxy's Outer Rim Territories, that was the homeworld of House Kryze. It was the birthplace of Duchess Satine Kryze, leader of the New Mandalorians and the Council of Neutral Systems during the Clone Wars. " .

