Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Quarzite> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33fc6d91-876c-4263-be86-d39d2927fa9b> .
<https://starwars.com#planet_Quarzite> <http://www.w3.org/2000/01/rdf-schema#comment> "Quarzite was a small planet located in the Inner Rim whose high atmospheric pressure rendered its surface uninhabitable. However, the planet's crystalline caverns were capable of supporting life, and were home to the warring Belugans and Kage. During the Clone Wars, it was ruled by the Belugan dictator Lord Otua Blank. When the Belugans kidnapped the Kage girl Pluma Sodi so that Blank could marry her, Major Rigosso hired a group of bounty hunters to defend a subtram, the primary method of travel on the planet, that would deliver the girl to Lord Blank. The hunters traveled to Quarzite in the Hound's Tooth and took a massive turbolift, which, due to the overwhelming atmospheric pressure, was the only way to reach Quarzite's suface. " .
<https://starwars.com#planet_Quarzite> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Quarzite> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Quarzite> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Quarzite> <http://telicent.io/ontology/primaryName> "Quarzite" .
<https://starwars.com#33fc6d91-876c-4263-be86-d39d2927fa9b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#33fc6d91-876c-4263-be86-d39d2927fa9b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quarzite"^^<http://www.w3.org/2001/XMLSchema#string> .

