Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#279a5f01-76c0-42b4-9f19-d2613a7b83da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#279a5f01-76c0-42b4-9f19-d2613a7b83da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_S10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#279a5f01-76c0-42b4-9f19-d2613a7b83da> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#0e15466c-b7da-40c5-ad8b-8ddada9a14a5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_BootanaShagplan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_BootanaShagplan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e15466c-b7da-40c5-ad8b-8ddada9a14a5> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#grid_S10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_S10> <http://telicent.io/ontology/primaryName> "S10" .
<https://starwars.com#planet_BootanaShagplan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_BootanaShagplan> <http://www.w3.org/2000/01/rdf-schema#comment> "Bootana Shagplan was a planet located in the Bootana Hutta region of Hutt Space. It was the region's most exclusive slave market, where were sold the most expensive and sought-after slaves. It also served as a clearinghouse for luxury goods that were popular on the nearby Hutt throneworlds. " .
<https://starwars.com#planet_BootanaShagplan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#0e15466c-b7da-40c5-ad8b-8ddada9a14a5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bootana Shagplan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_BootanaShagplan> <http://telicent.io/ontology/primaryName> "Bootana Shagplan" .

