Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kriz> <http://telicent.io/ontology/primaryName> "Kriz" .
<https://starwars.com#sector_Kriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_SilLume> <http://www.w3.org/2000/01/rdf-schema#comment> "Sil'Lume was the name of the primary star in the Sil'Lume system. " .
<https://starwars.com#planet_SilLume> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#94ffc81e-ebae-41b1-9e62-07641dd47264> .
<https://starwars.com#94ffc81e-ebae-41b1-9e62-07641dd47264> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sil'Lume"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#94ffc81e-ebae-41b1-9e62-07641dd47264> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SilLume> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_SilLume> <http://telicent.io/ontology/primaryName> "Sil'Lume" .
<https://starwars.com#planet_SilLume> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kriz> .
<https://starwars.com#planet_SilLume> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K19> .

