Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Humbarine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a131516b-cf85-48d8-8e7f-46f5d25504ed> .
<https://starwars.com#planet_Humbarine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Humbarine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#a131516b-cf85-48d8-8e7f-46f5d25504ed> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Humbarine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Humbarine> <http://www.w3.org/2000/01/rdf-schema#comment> "Humbarine was an ancient, conservative planet located in the galaxy's Core Worlds. Galen Walton Erso attended the Humbarine Academy of Advanced Studies after an internship at the Galactic Republic's Ministry of Energy. During the Imperial Era, Humbarine supported the Galactic Emperor Sheev Palpatine. After the signing of the Galactic Concordance, which conditionally allowed the remnants of the Empire to peacefully co-exist with the New Republic, Humbarine came under control of the Inner systems' Imperial remnant. Lega Fossang was a member of Humbarine's planetary defense force prior to her recruitment to the Resistance. " .
<https://starwars.com#planet_Humbarine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Humbarine> <http://telicent.io/ontology/primaryName> "Humbarine" .
<https://starwars.com#a131516b-cf85-48d8-8e7f-46f5d25504ed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

