Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LittleTalhovi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_LittleTalhovi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f7930080-9aaf-4636-9865-5cd2955b22c1> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#f7930080-9aaf-4636-9865-5cd2955b22c1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Little Talhovi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LittleTalhovi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_LittleTalhovi> <http://telicent.io/ontology/primaryName> "Little Talhovi" .
<https://starwars.com#planet_LittleTalhovi> <http://www.w3.org/2000/01/rdf-schema#comment> "Little Talhovi was a world located in the Little Talhovi system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. A hyperlane connected it to the Talhovi system. Little Talhovi was considered to be a promising agriworld by 43 ABY and, like the rest of the Senex-Juvex worlds, was under the control of the region's aristocratic Ancient Houses. " .
<https://starwars.com#f7930080-9aaf-4636-9865-5cd2955b22c1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_LittleTalhovi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

