Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J9> <http://telicent.io/ontology/primaryName> "J9" .
<https://starwars.com#planet_Batorine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1a24736a-b2c5-4dfc-b1b6-4becb808ce34> .
<https://starwars.com#planet_Batorine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J9> .
<https://starwars.com#planet_Batorine> <http://telicent.io/ontology/primaryName> "Batorine" .
<https://starwars.com#988a7012-f30a-4d62-ae04-eaa46877d40b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#988a7012-f30a-4d62-ae04-eaa46877d40b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Batorine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Batorine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#988a7012-f30a-4d62-ae04-eaa46877d40b> .
<https://starwars.com#planet_Batorine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#grid_J9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#1a24736a-b2c5-4dfc-b1b6-4becb808ce34> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Batorine> <http://www.w3.org/2000/01/rdf-schema#comment> "Batorine was the forested homeworld of the Blood Carver species. It joined the Galactic Republic in 110 BBY. " .
<https://starwars.com#grid_J9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#1a24736a-b2c5-4dfc-b1b6-4becb808ce34> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

