Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Apatros> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_Q16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#aa26288b-f0fb-4c1d-b515-dd9032c2de59> .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_Q16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#aa26288b-f0fb-4c1d-b515-dd9032c2de59> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Apatros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .
<https://starwars.com#01a614ca-1035-4f6d-8fc0-8cc606d335b6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Apatros"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#aa26288b-f0fb-4c1d-b515-dd9032c2de59> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_Q16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Apatros> <http://telicent.io/ontology/primaryName> "Apatros" .
<https://starwars.com#planet_Apatros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#01a614ca-1035-4f6d-8fc0-8cc606d335b6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Apatros> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#01a614ca-1035-4f6d-8fc0-8cc606d335b6> .
<https://starwars.com#planet_Apatros> <http://www.w3.org/2000/01/rdf-schema#comment> "Apatros was the homeworld of the Sith Lord Darth Bane. " .
<https://starwars.com#grid_Q16> <http://telicent.io/ontology/primaryName> "Q16" .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

