Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Altratonne> <http://www.w3.org/2000/01/rdf-schema#comment> "Altratonne was a planet in the Altratonne system, orbiting the star Altratonne Prime. " .
<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_S7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1faf6e6e-ae03-4ccb-882e-a6889935e617> .
<https://starwars.com#grid_S7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1faf6e6e-ae03-4ccb-882e-a6889935e617> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_S7> <http://telicent.io/ontology/primaryName> "S7" .
<https://starwars.com#planet_Altratonne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#planet_Altratonne> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d4c1efc-28a1-45db-a3bf-7b4e269edeac> .
<https://starwars.com#grid_S7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#5d4c1efc-28a1-45db-a3bf-7b4e269edeac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5d4c1efc-28a1-45db-a3bf-7b4e269edeac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Altratonne"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Altratonne> <http://telicent.io/ontology/primaryName> "Altratonne" .
<https://starwars.com#1faf6e6e-ae03-4ccb-882e-a6889935e617> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Altratonne> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Altratonne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .

