Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9ab5a1a7-f7a2-420c-8721-7fc9ef7d1708> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cademimu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cademimu> <http://www.w3.org/2000/01/rdf-schema#comment> "Cademimu V, also simply referred to as Cademimu, was a planet in the Cademimu sector along the Celanon Spur. " .
<https://starwars.com#planet_Cademimu> <http://telicent.io/ontology/primaryName> "Cademimu" .
<https://starwars.com#planet_Cademimu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ab5a1a7-f7a2-420c-8721-7fc9ef7d1708> .
<https://starwars.com#planet_Cademimu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .
<https://starwars.com#planet_Cademimu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cademimu> .
<https://starwars.com#sector_Cademimu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Cademimu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cademimu> <http://telicent.io/ontology/primaryName> "Cademimu" .
<https://starwars.com#9ab5a1a7-f7a2-420c-8721-7fc9ef7d1708> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cademimu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

