Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Korphir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Korphir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Korphir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a9ca9123-94cd-4ac0-95e8-2121fe926559> .
<https://starwars.com#a9ca9123-94cd-4ac0-95e8-2121fe926559> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a9ca9123-94cd-4ac0-95e8-2121fe926559> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korphir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Korphir> <http://www.w3.org/2000/01/rdf-schema#comment> "Korphir was an Imperial planet during the Galactic Civil War. " .
<https://starwars.com#planet_Korphir> <http://telicent.io/ontology/primaryName> "Korphir" .
<https://starwars.com#planet_Korphir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

