Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nigel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vish> .
<https://starwars.com#sector_Vish> <http://telicent.io/ontology/primaryName> "Vish" .
<https://starwars.com#planet_Nigel> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Vish> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nigel> <http://telicent.io/ontology/primaryName> "Nigel" .
<https://starwars.com#planet_Nigel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#870795e5-61e6-4b4e-a720-33052f608869> .
<https://starwars.com#planet_Nigel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nigel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#870795e5-61e6-4b4e-a720-33052f608869> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#870795e5-61e6-4b4e-a720-33052f608869> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nigel"^^<http://www.w3.org/2001/XMLSchema#string> .

