Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#250bbc71-ef1b-4b22-961e-70e2b6c62f99> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thoran"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thoran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Manda> .
<https://starwars.com#planet_Thoran> <http://www.w3.org/2000/01/rdf-schema#comment> "Thoran was a planet located within the Bothan sector of the Mid Rim. " .
<https://starwars.com#planet_Thoran> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#250bbc71-ef1b-4b22-961e-70e2b6c62f99> .
<https://starwars.com#sector_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#planet_Thoran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thoran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#sector_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Thoran> <http://telicent.io/ontology/primaryName> "Thoran" .
<https://starwars.com#sector_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#250bbc71-ef1b-4b22-961e-70e2b6c62f99> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

