Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#af22c9a0-b99a-40be-ba94-925e7a0a03d5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lazerian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lazerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#planet_Lazerian> <http://www.w3.org/2000/01/rdf-schema#comment> "Lazerian or Lazeria can refer to the following: " .
<https://starwars.com#af22c9a0-b99a-40be-ba94-925e7a0a03d5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#planet_Lazerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kira> .
<https://starwars.com#planet_Lazerian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#af22c9a0-b99a-40be-ba94-925e7a0a03d5> .
<https://starwars.com#planet_Lazerian> <http://telicent.io/ontology/primaryName> "Lazerian" .
<https://starwars.com#planet_Lazerian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

