Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Onderon> <http://telicent.io/ontology/primaryName> "Onderon" .
<https://starwars.com#568dd837-0db7-4a2b-8181-1d0044575abe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Japrael> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Japrael> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Onderon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Onderon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#568dd837-0db7-4a2b-8181-1d0044575abe> .
<https://starwars.com#planet_Onderon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_Japrael> <http://telicent.io/ontology/primaryName> "Japrael" .
<https://starwars.com#568dd837-0db7-4a2b-8181-1d0044575abe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Onderon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Onderon> <http://www.w3.org/2000/01/rdf-schema#comment> "Jungle planet where Anakin Skywalker and his padawan Ashoka Tano leads a revolt against its Separatist-controlled monarchy during the Clone Wars; birthplace of Saw Gerrera." .
<https://starwars.com#planet_Onderon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Japrael> .

