Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Affa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Affa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#d3bbac97-1a72-450c-8bac-10cd430a6988> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Affa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d3bbac97-1a72-450c-8bac-10cd430a6988> .
<https://starwars.com#planet_Affa> <http://telicent.io/ontology/primaryName> "Affa" .
<https://starwars.com#planet_Affa> <http://www.w3.org/2000/01/rdf-schema#comment> "Affa was a terrestrial planet that housed great droid factories. Arakyd Industries's RA-7 protocol droids, including DK-RA-43, were manufactured in the factories, while parts for Cybot Galactica's 3PO-series protocol droid were also manufactured on the planet. " .
<https://starwars.com#grid_M13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#81653d25-61df-46c1-a2bd-1bbc6e513819> .
<https://starwars.com#planet_Affa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#grid_M13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#81653d25-61df-46c1-a2bd-1bbc6e513819> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M13> <http://telicent.io/ontology/primaryName> "M13" .
<https://starwars.com#d3bbac97-1a72-450c-8bac-10cd430a6988> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Affa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#81653d25-61df-46c1-a2bd-1bbc6e513819> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_M13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

