Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#db2cb0f3-bff5-47ab-888a-8e7aeabedf9a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ketaris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Oplovis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Oplovis> <http://telicent.io/ontology/primaryName> "Oplovis" .
<https://starwars.com#planet_Ketaris> <http://www.w3.org/2000/01/rdf-schema#comment> "Ketaris was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Ketaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Oplovis> .
<https://starwars.com#planet_Ketaris> <http://telicent.io/ontology/primaryName> "Ketaris" .
<https://starwars.com#planet_Ketaris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ketaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_Ketaris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#db2cb0f3-bff5-47ab-888a-8e7aeabedf9a> .
<https://starwars.com#sector_Oplovis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#db2cb0f3-bff5-47ab-888a-8e7aeabedf9a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

