Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Paqwepori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_PaqweporMajor> <http://www.w3.org/2000/01/rdf-schema#comment> "Paqwepor Major, also known as Paqwepor, was a planet in the Mid Rim off the Corellian Run. It was within the region of Paqwepori. Paqwepor Major was the Paqwe homeworld and it was ruled by the Paqwe family. During the Clone Wars, Paqwepor Major was located within Separatist space. " .
<https://starwars.com#planet_PaqweporMajor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#planet_PaqweporMajor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6bcb091f-8e69-4e60-a757-067d05b33794> .
<https://starwars.com#sector_Paqwepori> <http://telicent.io/ontology/primaryName> "Paqwepori" .
<https://starwars.com#planet_PaqweporMajor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6bcb091f-8e69-4e60-a757-067d05b33794> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PaqweporMajor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Paqwepori> .
<https://starwars.com#planet_PaqweporMajor> <http://telicent.io/ontology/primaryName> "Paqwepor Major" .
<https://starwars.com#sector_Paqwepori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#6bcb091f-8e69-4e60-a757-067d05b33794> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Paqwepor Major"^^<http://www.w3.org/2001/XMLSchema#string> .

