Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7d646d33-ee97-4203-90c7-913584b69b1a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zaddja"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zaddja> <http://www.w3.org/2000/01/rdf-schema#comment> "Zaddja was a terrestrial astronomical object located in the Zaddja system of the Outer Rim Territories, situated at the coordinates H-15 on the Standard Galactic Grid. Its surface consisted of oceans broken up by archipelagoes of white sand beaches. At night, the beaches were covered by water from the high tides; as such, the inhabitants of Zaddja lived on flying skiffs. A hyperspace route connected Zaddja to Gannaria, a planet in the Trilon sector. " .
<https://starwars.com#sector_Trilon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zaddja> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trilon> .
<https://starwars.com#planet_Zaddja> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7d646d33-ee97-4203-90c7-913584b69b1a> .
<https://starwars.com#planet_Zaddja> <http://telicent.io/ontology/primaryName> "Zaddja" .
<https://starwars.com#sector_Trilon> <http://telicent.io/ontology/primaryName> "Trilon" .
<https://starwars.com#planet_Zaddja> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H15> .
<https://starwars.com#planet_Zaddja> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Trilon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7d646d33-ee97-4203-90c7-913584b69b1a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

