Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KitelPhard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b3a9702c-d0ba-4e4d-90b0-f625edd6e6cb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KitelPhard> <http://telicent.io/ontology/primaryName> "Kitel Phard" .
<https://starwars.com#planet_KitelPhard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_KitelPhard> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b3a9702c-d0ba-4e4d-90b0-f625edd6e6cb> .
<https://starwars.com#b3a9702c-d0ba-4e4d-90b0-f625edd6e6cb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kitel Phard"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KitelPhard> <http://www.w3.org/2000/01/rdf-schema#comment> "Kitel Phard was an astronomical object located in the regions known as the Core Worlds and the Interior, in the grid square J-12 of the Standard Galactic Grid. A hyperspace route connected it to the planet Giju. Kitel Phard shared its name with the Kitel Phard dynasty. During the reign of the Galactic Empire, the latter was associated with a style of expensive vases. " .
<https://starwars.com#planet_KitelPhard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J12> .

