Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_R10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#f5c7bc0e-75f2-4ebb-a779-97f19254507b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chalacta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f5c7bc0e-75f2-4ebb-a779-97f19254507b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3016ab81-7989-4aa1-a7e3-bbf04859b27e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chalacta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R10> .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#3016ab81-7989-4aa1-a7e3-bbf04859b27e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Chalacta> <http://telicent.io/ontology/primaryName> "Chalacta" .
<https://starwars.com#grid_R10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_R10> <http://telicent.io/ontology/primaryName> "R10" .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#planet_Chalacta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f5c7bc0e-75f2-4ebb-a779-97f19254507b> .
<https://starwars.com#planet_Chalacta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#planet_Chalacta> <http://www.w3.org/2000/01/rdf-schema#comment> "Chalacta was a planet located in the galaxy's Mid Rim. that was the homeworld of the Chalactan people. The human Jedi Master Depa Billaba was born on Chalacta. In the C.R.C. year 7941, Chalacta was represented in the Galactic Senate of the Galactic Republic by Yudrish Sedran. " .
<https://starwars.com#grid_R10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3016ab81-7989-4aa1-a7e3-bbf04859b27e> .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chalacta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

