Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Milvayne> <http://telicent.io/ontology/primaryName> "Milvayne" .
<https://starwars.com#planet_Milvayne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Milvayne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_Milvayne> <http://www.w3.org/2000/01/rdf-schema#comment> "Milvayne was a planet in the Inner Rim Territories controlled by the Milvayne Authority, a harsh, justice-oriented law enforcement agency. After the establishment of the Galactic Empire, Milvayne fell under its protection, under the terms it kept an invisible presence. Milvayne's law enforcement made it a good example for the Empire, and it was promoted through propaganda as an ideal world. After being linked with proximity bombs by Cornelius Evazan, Chelli Aphra and 0-0-0 traveled to Milvayne, where they were forced to evade the law as fugitives. After Evazan widened the broadcast from Triple Zero's eyes to reach the residents of Milvayne, the Empire's Coalition for Progress wished to intervene to prevent the live feed from inspiring mischievous ideas. They were eventually forced to fire on Milvayne City as the chase escalated. " .
<https://starwars.com#7a9d42eb-ee2e-4fb3-ad7f-6b7cb29bda20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Milvayne> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7a9d42eb-ee2e-4fb3-ad7f-6b7cb29bda20> .
<https://starwars.com#planet_Milvayne> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7a9d42eb-ee2e-4fb3-ad7f-6b7cb29bda20> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Milvayne"^^<http://www.w3.org/2001/XMLSchema#string> .

