Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Norah> <http://www.w3.org/2000/01/rdf-schema#comment> "Norah was a planet where Soara Antana and Darra Thel-Tanis went on a mission. " .
<https://starwars.com#planet_Norah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#176dca9d-0117-43c4-9a90-faa827cea56b> .
<https://starwars.com#planet_Norah> <http://telicent.io/ontology/primaryName> "Norah" .
<https://starwars.com#planet_Norah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Norah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Norah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#176dca9d-0117-43c4-9a90-faa827cea56b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#176dca9d-0117-43c4-9a90-faa827cea56b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Norah"^^<http://www.w3.org/2001/XMLSchema#string> .

