Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#552f2487-c5ed-43dc-bb8c-84d7c85e0ada> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kaliida Shoals"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ryndellian> <http://telicent.io/ontology/primaryName> "Ryndellian" .
<https://starwars.com#planet_KaliidaShoals> <http://www.w3.org/2000/01/rdf-schema#comment> "Kaliida Shoals was an astronomical object located near the Kaliida Shoals Medcentre, a Galactic Republic medical station situated in the Ryndellia system of the Outer Rim Territories. During the Clone Wars, the station was the site of a battle in which the Republic defended it from an attack by General Grievous' flagship Malevolence. " .
<https://starwars.com#sector_Ryndellian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#552f2487-c5ed-43dc-bb8c-84d7c85e0ada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KaliidaShoals> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#552f2487-c5ed-43dc-bb8c-84d7c85e0ada> .
<https://starwars.com#planet_KaliidaShoals> <http://telicent.io/ontology/primaryName> "Kaliida Shoals" .
<https://starwars.com#planet_KaliidaShoals> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ryndellian> .
<https://starwars.com#sector_Ryndellian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KaliidaShoals> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KaliidaShoals> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .

