Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ariarch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Keitum> <http://www.w3.org/2000/01/rdf-schema#comment> "Keitum was a planet located in the galaxy's Mid Rim, connected via hyperspace route to Ansion. Cartherston was a city located on the planet. " .
<https://starwars.com#planet_Keitum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#sector_Ariarch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Keitum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ariarch> .
<https://starwars.com#sector_Ariarch> <http://telicent.io/ontology/primaryName> "Ariarch" .
<https://starwars.com#30c2656a-008a-4010-a2b0-d1499b4fdc90> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Keitum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30c2656a-008a-4010-a2b0-d1499b4fdc90> .
<https://starwars.com#planet_Keitum> <http://telicent.io/ontology/primaryName> "Keitum" .
<https://starwars.com#30c2656a-008a-4010-a2b0-d1499b4fdc90> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Keitum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Keitum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

