Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Deminol> <http://telicent.io/ontology/primaryName> "Deminol" .
<https://starwars.com#planet_Deminol> <http://www.w3.org/2000/01/rdf-schema#comment> "Deminol was a terrestrial world located in the Deminol system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. The Senex-Juvex Loop hyperlane linked it to the Anstares and Ossiathora systems. " .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Deminol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Deminol> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fe9e554a-e1c5-42d3-89c3-96969cf88eb7> .
<https://starwars.com#planet_Deminol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#fe9e554a-e1c5-42d3-89c3-96969cf88eb7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Deminol"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Deminol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#fe9e554a-e1c5-42d3-89c3-96969cf88eb7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

