Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bruanii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#98a8acc7-a0ad-4c67-9175-7ff3a97e705e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cargamalis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cargamalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bruanii> .
<https://starwars.com#planet_Cargamalis> <http://telicent.io/ontology/primaryName> "Cargamalis" .
<https://starwars.com#sector_Bruanii> <http://telicent.io/ontology/primaryName> "Bruanii" .
<https://starwars.com#planet_Cargamalis> <http://www.w3.org/2000/01/rdf-schema#comment> "Cargamalis was an astronomical object in the Mugaari Space's Javin Sector. At some point prior to the Battle of Endor, Cargamalis was subjected to Street Wars, in which the human 'Happy' Dapp and the Aqualish Bohento Splinth fought. " .
<https://starwars.com#planet_Cargamalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Bruanii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#98a8acc7-a0ad-4c67-9175-7ff3a97e705e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cargamalis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cargamalis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#98a8acc7-a0ad-4c67-9175-7ff3a97e705e> .

