Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorJiramma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#e6661edf-5c3f-45f3-a59e-51f2f101570d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorJiramma> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Jiramma was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Jiramma kajidic. " .
<https://starwars.com#planet_KorJiramma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_KorJiramma> <http://telicent.io/ontology/primaryName> "Kor Jiramma" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e6661edf-5c3f-45f3-a59e-51f2f101570d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Jiramma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorJiramma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6661edf-5c3f-45f3-a59e-51f2f101570d> .
<https://starwars.com#planet_KorJiramma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

