Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vactooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Vactooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Vactooine was a mining colony in the Arkanis sector of the Outer Rim Territories. Its dense jungles made it a suitable habitat for the Elix. " .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Vactooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#20861cc2-0f05-4cc3-b6dc-884563e99107> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vactooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vactooine> <http://telicent.io/ontology/primaryName> "Vactooine" .
<https://starwars.com#planet_Vactooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#20861cc2-0f05-4cc3-b6dc-884563e99107> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vactooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#20861cc2-0f05-4cc3-b6dc-884563e99107> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

