Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1ca3fc60-fa13-4b92-b9ce-6048c15e517b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rafa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rafa> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#1ca3fc60-fa13-4b92-b9ce-6048c15e517b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rafa> <http://telicent.io/ontology/primaryName> "Rafa" .
<https://starwars.com#planet_Rafa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rafa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1ca3fc60-fa13-4b92-b9ce-6048c15e517b> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Rafa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#planet_Rafa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

