Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Doldur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Doldur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#27b51868-b423-421f-ad0a-d2451566b069> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Doldur> <http://www.w3.org/2000/01/rdf-schema#comment> "Doldur was the Imperial-controlled sector capital of Doldur sector. Imperial Moff Eisen Kerioth considered it his personal territory and sponsored research of an antiblaster energy shield. " .
<https://starwars.com#planet_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Doldur> .
<https://starwars.com#planet_Doldur> <http://telicent.io/ontology/primaryName> "Doldur" .
<https://starwars.com#planet_Doldur> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#27b51868-b423-421f-ad0a-d2451566b069> .
<https://starwars.com#sector_Doldur> <http://telicent.io/ontology/primaryName> "Doldur" .
<https://starwars.com#planet_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#27b51868-b423-421f-ad0a-d2451566b069> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Doldur"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

