Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_SomovRit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_SomovRit> <http://www.w3.org/2000/01/rdf-schema#comment> "Somov Rit was a sparsely populated green world with a native Human population. During the New Sith Wars, Jedi scout Torr Snapit came to the planet seeking Force-sensitive recruits, but his only luck was with three young children: Rain, Tomcat and Bug. Rain later helped rebuild the Sith Order as Darth Bane's apprentice, Darth Zannah. " .
<https://starwars.com#planet_SomovRit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Onatos> .
<https://starwars.com#planet_SomovRit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#038c588c-e310-4b31-b702-46dab8ea398c> .
<https://starwars.com#sector_Onatos> <http://telicent.io/ontology/primaryName> "Onatos" .
<https://starwars.com#038c588c-e310-4b31-b702-46dab8ea398c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Somov Rit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Onatos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Onatos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SomovRit> <http://telicent.io/ontology/primaryName> "Somov Rit" .
<https://starwars.com#038c588c-e310-4b31-b702-46dab8ea398c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SomovRit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R15> .

