Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Phaseera> <http://www.w3.org/2000/01/rdf-schema#comment> "Phaseera was a manufacturing planet that was the location of a battle near the end of the New Sith Wars. It had been occupied by the Galactic Republic before the conflict, but after the Republic defeat, it became Sith occupied. Its terrain included jungles, valleys, and plateaus. It orbited a yellow sun, and cydera trees grew on it. " .
<https://starwars.com#sector_Lantillian> <http://telicent.io/ontology/primaryName> "Lantillian" .
<https://starwars.com#sector_Lantillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Phaseera> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fabf0bdc-d570-49ed-8462-f27414da0ea4> .
<https://starwars.com#fabf0bdc-d570-49ed-8462-f27414da0ea4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Phaseera> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P8> .
<https://starwars.com#fabf0bdc-d570-49ed-8462-f27414da0ea4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phaseera"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Phaseera> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lantillian> .
<https://starwars.com#sector_Lantillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Phaseera> <http://telicent.io/ontology/primaryName> "Phaseera" .
<https://starwars.com#planet_Phaseera> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

