Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#311e3d91-b626-4dae-ae6a-4522e7a57473> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Surron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Surron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MekvaUil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#311e3d91-b626-4dae-ae6a-4522e7a57473> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mek va Uil"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MekvaUil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Surron> .
<https://starwars.com#planet_MekvaUil> <http://telicent.io/ontology/primaryName> "Mek va Uil" .
<https://starwars.com#sector_Surron> <http://telicent.io/ontology/primaryName> "Surron" .
<https://starwars.com#planet_MekvaUil> <http://www.w3.org/2000/01/rdf-schema#comment> "Mek va Uil was a planet in the Expansion Region. The Regent of Mek va Uil was from this world. " .
<https://starwars.com#planet_MekvaUil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MekvaUil> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#311e3d91-b626-4dae-ae6a-4522e7a57473> .

