Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cioral> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cioral> <http://telicent.io/ontology/primaryName> "Cioral" .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cioral> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#647d012d-97d0-417b-aeb8-024deaa8e962> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cioral> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#647d012d-97d0-417b-aeb8-024deaa8e962> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cioral"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cioral> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#647d012d-97d0-417b-aeb8-024deaa8e962> .
<https://starwars.com#planet_Cioral> <http://www.w3.org/2000/01/rdf-schema#comment> "Cioral was a terrestrial astronomical object located within the territory of the Chiss Ascendancy. It was a stronghold of the Ascendancy's Xodlak family, one of the forty Great Families and formerly one of the Ten Ruling Families. " .

