Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Rocantor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_OrdVaug> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rocantor> .
<https://starwars.com#sector_Rocantor> <http://telicent.io/ontology/primaryName> "Rocantor" .
<https://starwars.com#planet_OrdVaug> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Vaug was a planet in the Expansion Region. " .
<https://starwars.com#planet_OrdVaug> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c81fc3e0-29bc-475f-9dd1-d6f023296349> .
<https://starwars.com#planet_OrdVaug> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#c81fc3e0-29bc-475f-9dd1-d6f023296349> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Vaug"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c81fc3e0-29bc-475f-9dd1-d6f023296349> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Rocantor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdVaug> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdVaug> <http://telicent.io/ontology/primaryName> "Ord Vaug" .

