Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Quesaya> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Quesaya> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#00896183-810e-4c95-a9ea-c849d94d34b4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Quesaya> <http://telicent.io/ontology/primaryName> "Quesaya" .
<https://starwars.com#sector_Andirma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Andirma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Andirma> <http://telicent.io/ontology/primaryName> "Andirma" .
<https://starwars.com#planet_Quesaya> <http://www.w3.org/2000/01/rdf-schema#comment> "Quesaya could refer to one of the following: " .
<https://starwars.com#planet_Quesaya> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#00896183-810e-4c95-a9ea-c849d94d34b4> .
<https://starwars.com#00896183-810e-4c95-a9ea-c849d94d34b4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quesaya"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Quesaya> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Andirma> .

