Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gorno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#bdf7689c-222f-47e8-9bee-b996c7ed909b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gorno> <http://www.w3.org/2000/01/rdf-schema#comment> "Gorno was a planet in the Outer Rim, along the Corellian Run near Tatooine. The Galactic Empire had a secret research facility used to design the Superlaser for the second Death Star, codenamed Hammertong. A spaceport there was used as an embarkation point from which the Hammertong was to depart, shortly before the Battle of Yavin. " .
<https://starwars.com#planet_Gorno> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bdf7689c-222f-47e8-9bee-b996c7ed909b> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Gorno> <http://telicent.io/ontology/primaryName> "Gorno" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gorno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#bdf7689c-222f-47e8-9bee-b996c7ed909b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gorno"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gorno> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

