Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vanjervalis> <http://telicent.io/ontology/primaryName> "Vanjervalis" .
<https://starwars.com#269c7030-f848-4633-a3af-1dc093de057d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vanjervalis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vanjervalis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#269c7030-f848-4633-a3af-1dc093de057d> .
<https://starwars.com#planet_Vanjervalis> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Vanjervalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Vanjervalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Vanjervalis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#269c7030-f848-4633-a3af-1dc093de057d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

