Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Wornal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0e4b42b7-1f5e-4cca-9b60-65c46105cc40> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0e4b42b7-1f5e-4cca-9b60-65c46105cc40> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bomis Koori"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BomisKoori> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e4b42b7-1f5e-4cca-9b60-65c46105cc40> .
<https://starwars.com#planet_BomisKoori> <http://www.w3.org/2000/01/rdf-schema#comment> "Bomis Koori was an astronomical object located in the galaxy's Mid Rim, situated on the Corellian Trade Spine. " .
<https://starwars.com#planet_BomisKoori> <http://telicent.io/ontology/primaryName> "Bomis Koori" .
<https://starwars.com#planet_BomisKoori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#planet_BomisKoori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Wornal> <http://telicent.io/ontology/primaryName> "Wornal" .
<https://starwars.com#sector_Wornal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_BomisKoori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wornal> .

