Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Perma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Perma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fe0d7e91-71e0-4944-ae5f-48ba7a2ee730> .
<https://starwars.com#planet_Perma> <http://www.w3.org/2000/01/rdf-schema#comment> "Perma was a planet in the galaxy's Core Worlds. " .
<https://starwars.com#planet_Perma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Perma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#fe0d7e91-71e0-4944-ae5f-48ba7a2ee730> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#fe0d7e91-71e0-4944-ae5f-48ba7a2ee730> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Perma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Perma> <http://telicent.io/ontology/primaryName> "Perma" .

