Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FelHu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#ac1310a2-c7cb-4556-9b95-887ed948f863> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Beris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Beris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#201fe839-ecae-41c2-8984-fc5dd002a3fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_Q13> <http://telicent.io/ontology/primaryName> "Q13" .
<https://starwars.com#planet_Beris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FelHu> .
<https://starwars.com#grid_Q13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Beris> <http://www.w3.org/2000/01/rdf-schema#comment> "Beris, a Mid Rim planet in the Galactic Alliance Senate composition, seceded from the Galactic Alliance during the Second Galactic Civil War. The planet was located on the Gamor Run, in the Fei Hu sector. " .
<https://starwars.com#201fe839-ecae-41c2-8984-fc5dd002a3fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Beris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac1310a2-c7cb-4556-9b95-887ed948f863> .
<https://starwars.com#grid_Q13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#201fe839-ecae-41c2-8984-fc5dd002a3fc> .
<https://starwars.com#planet_Beris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#ac1310a2-c7cb-4556-9b95-887ed948f863> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_FelHu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Beris> <http://telicent.io/ontology/primaryName> "Beris" .
<https://starwars.com#sector_FelHu> <http://telicent.io/ontology/primaryName> "Fel Hu" .
<https://starwars.com#grid_Q13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

