Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LahagErli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_LahagErli> <http://www.w3.org/2000/01/rdf-schema#comment> "Lahag Erli was a planet whose natives attacked and occupied the Har system for many years. " .
<https://starwars.com#5ac7580f-0f1d-4109-9a31-65425e54607a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_J15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5ac7580f-0f1d-4109-9a31-65425e54607a> .
<https://starwars.com#sector_CantonsofLahag> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1a119880-2d7d-4004-9498-763b2bc62061> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lahag Erli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5ac7580f-0f1d-4109-9a31-65425e54607a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_LahagErli> <http://telicent.io/ontology/primaryName> "Lahag Erli" .
<https://starwars.com#planet_LahagErli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J15> .
<https://starwars.com#grid_J15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_CantonsofLahag> <http://telicent.io/ontology/primaryName> "Cantons of Lahag" .
<https://starwars.com#1a119880-2d7d-4004-9498-763b2bc62061> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CantonsofLahag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_LahagErli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CantonsofLahag> .
<https://starwars.com#planet_LahagErli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a119880-2d7d-4004-9498-763b2bc62061> .
<https://starwars.com#grid_J15> <http://telicent.io/ontology/primaryName> "J15" .

