Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Sujimis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrtoPlutonia> <http://telicent.io/ontology/primaryName> "Orto Plutonia" .
<https://starwars.com#sector_Sujimis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d7f2264b-435b-4f5c-851a-da49321c4c91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrtoPlutonia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P19> .
<https://starwars.com#planet_OrtoPlutonia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sujimis> .
<https://starwars.com#planet_OrtoPlutonia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrtoPlutonia> <http://www.w3.org/2000/01/rdf-schema#comment> "Orto Plutonia was a frigid planet located in the Pantora system of the Outer Rim Territories' Sujimis sector. It was orbited by the moon Pantora, which was long believed to be the only inhabited world in the system. It was the homeworld of the Talz species, but was considered to be a protectorate of Pantora until the presence of the Talz was discovered during the Clone Wars. The Pantoran Assembly gave formal recognition to the sovereignty of the Talz over Orto Plutonia following a brief war between the Talz and the Pantorans. Shortly after the Battle of Yavin, the Rebel Alliance hid its fleet in the planet's orbit. " .
<https://starwars.com#d7f2264b-435b-4f5c-851a-da49321c4c91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orto Plutonia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrtoPlutonia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7f2264b-435b-4f5c-851a-da49321c4c91> .
<https://starwars.com#sector_Sujimis> <http://telicent.io/ontology/primaryName> "Sujimis" .

