Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prefsbelt> .
<https://starwars.com#planet_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Prefsbelt> <http://www.w3.org/2000/01/rdf-schema#comment> "Prefsbelt IV, also known simply as Prefsbelt was a planet of the Outer Rim Territories that housed a naval academy. " .
<https://starwars.com#sector_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .
<https://starwars.com#ac7e22ab-5bbd-49e5-9bea-0618916461b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Prefsbelt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac7e22ab-5bbd-49e5-9bea-0618916461b7> .
<https://starwars.com#planet_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ac7e22ab-5bbd-49e5-9bea-0618916461b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .

