Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Unagin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Al-Nasrl> <http://telicent.io/ontology/primaryName> "Al-Nasrl" .
<https://starwars.com#planet_Unagin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6211e067-f3b4-4899-b23a-703e88abaf6f> .
<https://starwars.com#sector_Al-Nasrl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Unagin> <http://telicent.io/ontology/primaryName> "Unagin" .
<https://starwars.com#6211e067-f3b4-4899-b23a-703e88abaf6f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Unagin> <http://www.w3.org/2000/01/rdf-schema#comment> "Unagin was a minor trade planet. It was located within the Unagin system of the Al'Nasrl sector, a part of the Slice portion of the Outer Rim Territories. The planet lay on the hyperlane called the Hollastin Run, which connected it to the worlds of Tsyk and Syvris. A smaller hyperspace route also connected Unagin to the planet Riileb. Due to Unagin's location near Hutt Space, starships that prepared to enter or leave that region frequently stopped at the planet. " .
<https://starwars.com#planet_Unagin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T13> .
<https://starwars.com#planet_Unagin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Al-Nasrl> .
<https://starwars.com#6211e067-f3b4-4899-b23a-703e88abaf6f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Unagin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Al-Nasrl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

