Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zyluria> <http://telicent.io/ontology/primaryName> "Zyluria" .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Zyluria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Zyluria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zyluria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#0bb23afb-e350-40fc-9686-742877fea65c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zyluria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0bb23afb-e350-40fc-9686-742877fea65c> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zyluria> <http://www.w3.org/2000/01/rdf-schema#comment> "Zyluria was a world located in the Zyluria system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. A hyperlane linked it to the Carsanza system. Zyluria's surface featured gentle plains, and it was the homeworld of the Zylurians, a sentient species that, by 43 ABY, had long served the aristocratic Ancient Houses of the Senex-Juvex. " .
<https://starwars.com#0bb23afb-e350-40fc-9686-742877fea65c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zyluria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

