Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Morellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Morellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#96336345-7ede-4492-911e-07c7fa6a4219> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Morellia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#96336345-7ede-4492-911e-07c7fa6a4219> .
<https://starwars.com#planet_Morellia> <http://www.w3.org/2000/01/rdf-schema#comment> "Morellia was a planet in the galaxy. Prior to the Galactic Civil War, Auric Graf gave an emerald pendant to his wife, Rhyssa, while on Morellia. " .
<https://starwars.com#planet_Morellia> <http://telicent.io/ontology/primaryName> "Morellia" .
<https://starwars.com#96336345-7ede-4492-911e-07c7fa6a4219> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Morellia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Morellia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

