Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NewCylimba> <http://telicent.io/ontology/primaryName> "New Cylimba" .
<https://starwars.com#planet_NewCylimba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_NewCylimba> <http://www.w3.org/2000/01/rdf-schema#comment> "New Cylimba was a planet within a star system in the D'Aelgoth sector of the Mid Rim region of the galaxy. It was situated on the Veron Route, which connected it to Veron. It was an industrial world whose badlands were the location of an Alliance base during the Galactic Civil War. The base and its crew would likely have been crushed by Imperial forces, had Rivoche Tarkin not provided the necessary intelligence to avoid the attack. " .
<https://starwars.com#planet_NewCylimba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c515f520-c706-4ea8-8c53-8731a4270a5d> .
<https://starwars.com#planet_NewCylimba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAelgoth> .
<https://starwars.com#sector_DAelgoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#c515f520-c706-4ea8-8c53-8731a4270a5d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Cylimba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_DAelgoth> <http://telicent.io/ontology/primaryName> "D'Aelgoth" .
<https://starwars.com#planet_NewCylimba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_DAelgoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c515f520-c706-4ea8-8c53-8731a4270a5d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

