Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eliad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Minos> .
<https://starwars.com#planet_Eliad> <http://telicent.io/ontology/primaryName> "Eliad" .
<https://starwars.com#sector_Minos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Eliad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#planet_Eliad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#353915a2-e10e-4d0e-b240-c0e8448d3ecf> .
<https://starwars.com#planet_Eliad> <http://www.w3.org/2000/01/rdf-schema#comment> "Eliad was a planet of wealthy noble exiles in the Minos Cluster. " .
<https://starwars.com#353915a2-e10e-4d0e-b240-c0e8448d3ecf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Minos> <http://telicent.io/ontology/primaryName> "Minos" .
<https://starwars.com#sector_Minos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#353915a2-e10e-4d0e-b240-c0e8448d3ecf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eliad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Eliad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

