Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rekkiad> <http://telicent.io/ontology/primaryName> "Rekkiad" .
<https://starwars.com#planet_Rekkiad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chorlian> .
<https://starwars.com#planet_Rekkiad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e810de96-60c8-4ea1-9612-79902a52ab07> .
<https://starwars.com#planet_Rekkiad> <http://www.w3.org/2000/01/rdf-schema#comment> "Rekkiad was a planet in the remote Rekkiad system, located in the Outer Rim region of the galaxy. A desolate world covered in ice and snow, it was where the Jedi Knights Revan and Malak hid Mandalore's Mask following the Mandalorian Wars. " .
<https://starwars.com#sector_Chorlian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#e810de96-60c8-4ea1-9612-79902a52ab07> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#e810de96-60c8-4ea1-9612-79902a52ab07> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rekkiad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Chorlian> <http://telicent.io/ontology/primaryName> "Chorlian" .
<https://starwars.com#planet_Rekkiad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Chorlian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

