Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3de7d6e6-975f-4931-999f-be900985d312> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Moralan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Moralan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Moralan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3de7d6e6-975f-4931-999f-be900985d312> .
<https://starwars.com#planet_Moralan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Moralan> <http://telicent.io/ontology/primaryName> "Moralan" .
<https://starwars.com#3de7d6e6-975f-4931-999f-be900985d312> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Moralan> <http://www.w3.org/2000/01/rdf-schema#comment> "When the Tionese later withdrew from the system, they encouraged the Moralan to launch a successful rebellion against the Hutts, and a republic governed by the Parliament of Moralan was established. In response, however, Hutt forces led by Boonta Hestilic Shad'ruu defeated the Moralan, after which the planet was sterilized. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Moralan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .

