Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ryndellia> <http://www.w3.org/2000/01/rdf-schema#comment> "Ryndellia was located in the Ryndellia system of the Outer Rim Territories. In 22 BBY, during the Clone Wars between the Galactic Republic and the Confederacy of Independent Systems, the Subjugator-class heavy cruiser Malevolence, under the command of cyborg Kaleesh Separatist General Grievous, destroyed a Republic medical convoy of Pelta-class frigates and one Venator-class Star Destroyer near Ryndellia. " .
<https://starwars.com#planet_Ryndellia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d38f629f-e7ae-4428-bf53-288e9efcc279> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ryndellia> <http://telicent.io/ontology/primaryName> "Ryndellia" .
<https://starwars.com#sector_Ryndellian> <http://telicent.io/ontology/primaryName> "Ryndellian" .
<https://starwars.com#planet_Ryndellia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d38f629f-e7ae-4428-bf53-288e9efcc279> .
<https://starwars.com#planet_Ryndellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ryndellian> .
<https://starwars.com#sector_Ryndellian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#d38f629f-e7ae-4428-bf53-288e9efcc279> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ryndellia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ryndellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#sector_Ryndellian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

