Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TheGodsheart> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_TheGodsheart> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TheGodsheart> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_TheGodsheart> <http://www.w3.org/2000/01/rdf-schema#comment> "The Godsheart was a pulsar, a rapidly rotating neutron star, that was located within the Hutt Space region of the galaxy. The star lay off The Dead Road hyperlane. " .
<https://starwars.com#29899327-d917-4ada-9df3-3e53531586c5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Godsheart"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TheGodsheart> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#29899327-d917-4ada-9df3-3e53531586c5> .
<https://starwars.com#planet_TheGodsheart> <http://telicent.io/ontology/primaryName> "The Godsheart" .
<https://starwars.com#29899327-d917-4ada-9df3-3e53531586c5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

