Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Brochiib> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d8731217-c8db-4ce8-82b5-f6d6f38da969> .
<https://starwars.com#d8731217-c8db-4ce8-82b5-f6d6f38da969> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Brochiib"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Trianii> <http://telicent.io/ontology/primaryName> "Trianii" .
<https://starwars.com#planet_Brochiib> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trianii> .
<https://starwars.com#d8731217-c8db-4ce8-82b5-f6d6f38da969> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Brochiib> <http://telicent.io/ontology/primaryName> "Brochiib" .
<https://starwars.com#sector_Trianii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Brochiib> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Brochiib> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Brochiib> <http://www.w3.org/2000/01/rdf-schema#comment> "Brochiib was a Trianii colony planet in Trianii Space. Trianii Rangers Atuarre and Keeheen stopped thionarx dealers on the planet. " .
<https://starwars.com#sector_Trianii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .

