Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dulin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#d22657e6-b792-481a-9a0d-f49b318ec8d5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d22657e6-b792-481a-9a0d-f49b318ec8d5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_K14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Dulin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K14> .
<https://starwars.com#1ce33248-2035-41ea-aa17-02216f475c26> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dulin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dulin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1ce33248-2035-41ea-aa17-02216f475c26> .
<https://starwars.com#planet_Dulin> <http://www.w3.org/2000/01/rdf-schema#comment> "The Dulin system was located in the Inner Rim.[1] It contained Dulin starport.[2][3] One year, the northern approach vector to Dulin starport was temporarily closed for two hours due to the local city's celebration of the New Year Fete Week. As a result, starships arriving at the starport were instructed to use the southern approach vector instead." .
<https://starwars.com#planet_Dulin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1ce33248-2035-41ea-aa17-02216f475c26> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_K14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d22657e6-b792-481a-9a0d-f49b318ec8d5> .
<https://starwars.com#grid_K14> <http://telicent.io/ontology/primaryName> "K14" .
<https://starwars.com#grid_K14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Dulin> <http://telicent.io/ontology/primaryName> "Dulin" .

