Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jospro> <http://telicent.io/ontology/primaryName> "Jospro" .
<https://starwars.com#planet_Jomark> <http://www.w3.org/2000/01/rdf-schema#comment> "Jomark was an astronomical object located in the galaxy's Outer Rim Territories which housed an Imperial outpost and which was located close to the Galidraan system. When the Imperial corvette Carrion Spike was stolen and attacked Galidraan Station, Moff Wilhuff Tarkin requested a list of all nearby Imperial resources the ship might next attack; Jomark and its outpost were amongst those included in the list given to him. In 5 ABY, Han Solo told Maz Kanata in her castle over a tankard of Parkellan Sling that the long-range communicator of his ship, the Millennium Falcon, took a hit back at the planet and Chewbacca was fixing it. " .
<https://starwars.com#edd522ed-1441-46b6-9937-5ecd1f71fd92> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jomark> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jomark> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jospro> .
<https://starwars.com#planet_Jomark> <http://telicent.io/ontology/primaryName> "Jomark" .
<https://starwars.com#planet_Jomark> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#sector_Jospro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jomark> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#edd522ed-1441-46b6-9937-5ecd1f71fd92> .
<https://starwars.com#sector_Jospro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#edd522ed-1441-46b6-9937-5ecd1f71fd92> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jomark"^^<http://www.w3.org/2001/XMLSchema#string> .

