Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tharin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Taskeed> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#sector_Tharin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Taskeed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#cf5e48b5-d6d8-46d4-a050-143cf21ead9c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Taskeed> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf5e48b5-d6d8-46d4-a050-143cf21ead9c> .
<https://starwars.com#planet_Taskeed> <http://telicent.io/ontology/primaryName> "Taskeed" .
<https://starwars.com#planet_Taskeed> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tharin> .
<https://starwars.com#planet_Taskeed> <http://www.w3.org/2000/01/rdf-schema#comment> "Taskeed was an astronomical object located in the Outer Rim Territories of the galaxy. Linked to Jabiim and Dennogra by hyperspace routes, it was positioned at the coordinates S-7 on the Standard Galactic Grid. " .
<https://starwars.com#sector_Tharin> <http://telicent.io/ontology/primaryName> "Tharin" .
<https://starwars.com#cf5e48b5-d6d8-46d4-a050-143cf21ead9c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taskeed"^^<http://www.w3.org/2001/XMLSchema#string> .

