Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Fath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Wistril> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4a169b56-3b25-43d3-97bc-24061c919c21> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wistril"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Wistril> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4a169b56-3b25-43d3-97bc-24061c919c21> .
<https://starwars.com#planet_Wistril> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Fath> .
<https://starwars.com#planet_Wistril> <http://www.w3.org/2000/01/rdf-schema#comment> "Wistril was a planet in the Wistril system, located in the Outer Rim Territories. It was known for its smugglers. " .
<https://starwars.com#4a169b56-3b25-43d3-97bc-24061c919c21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Fath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Fath> <http://telicent.io/ontology/primaryName> "Fath" .
<https://starwars.com#planet_Wistril> <http://telicent.io/ontology/primaryName> "Wistril" .
<https://starwars.com#planet_Wistril> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .

