Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ee1f7a30-c5aa-453a-8ded-e254eac96433> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_HighChunah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_HighChunah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_HighChunah> <http://telicent.io/ontology/primaryName> "High Chunah" .
<https://starwars.com#planet_HighChunah> <http://www.w3.org/2000/01/rdf-schema#comment> "High Chunah was an astronomical object located in the Javin Sector of Mugaari Space along the Corellian Trade Spine. " .
<https://starwars.com#ee1f7a30-c5aa-453a-8ded-e254eac96433> <http://ies.data.gov.uk/ontology/ies4#representationValue> "High Chunah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_HighChunah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ee1f7a30-c5aa-453a-8ded-e254eac96433> .
<https://starwars.com#planet_HighChunah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .

