Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Celegia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#12541359-48e8-4f3d-ba8f-4607f9286bef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Celegia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Noori> <http://telicent.io/ontology/primaryName> "Noori" .
<https://starwars.com#sector_Noori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Celegia> <http://www.w3.org/2000/01/rdf-schema#comment> "Celegia was an astronomical object located in the regions known as the Expansion Region and the Slice. It was also situated in the grid square O-10 of the Standard Galactic Grid. " .
<https://starwars.com#planet_Celegia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12541359-48e8-4f3d-ba8f-4607f9286bef> .
<https://starwars.com#12541359-48e8-4f3d-ba8f-4607f9286bef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Celegia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noori> .
<https://starwars.com#planet_Celegia> <http://telicent.io/ontology/primaryName> "Celegia" .
<https://starwars.com#planet_Celegia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Noori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

