Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Atzerri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e80c7ac6-c145-499a-86e7-bac84d6e2b95> .
<https://starwars.com#planet_Atzerri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Atzerri> <http://www.w3.org/2000/01/rdf-schema#comment> "Atzerri was a Gotal colony world in the galaxy's Inner Rim, located in grid square M-13 on the Standard Galactic Grid. In the year 22 BBY, tens of millions of Gotal refugees fled to Atzerri when their homeworld of Antar 4 fell to the Confederacy of Independent Systems shortly after the First Battle of Geonosis, the first battle of the Clone Wars. " .
<https://starwars.com#planet_Atzerri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Atzerri> <http://telicent.io/ontology/primaryName> "Atzerri" .
<https://starwars.com#planet_Atzerri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e80c7ac6-c145-499a-86e7-bac84d6e2b95> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atzerri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e80c7ac6-c145-499a-86e7-bac84d6e2b95> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

