Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_FesweCorridor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_FesweCorridor> <http://www.w3.org/2000/01/rdf-schema#comment> "The Feswe Corridor was an uninhabited star system, located in the Gordian Reach sector of the Outer Rim Territories. " .
<https://starwars.com#planet_FesweCorridor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_FesweCorridor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8da4c727-a71a-449d-abb3-435c87d7d6c7> .
<https://starwars.com#planet_FesweCorridor> <http://telicent.io/ontology/primaryName> "Feswe Corridor" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#8da4c727-a71a-449d-abb3-435c87d7d6c7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Feswe Corridor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8da4c727-a71a-449d-abb3-435c87d7d6c7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_FesweCorridor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

