Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cerenia> <http://telicent.io/ontology/primaryName> "Cerenia" .
<https://starwars.com#sector_Mbandamonte> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cerenia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cerenia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#118ac771-d99f-4dea-9b6f-85aaadea82a3> .
<https://starwars.com#118ac771-d99f-4dea-9b6f-85aaadea82a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mbandamonte> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Cerenia> <http://www.w3.org/2000/01/rdf-schema#comment> "Ruten, or Cerenia, was a planet in the Cerenia system of the Expansion Region. The New Republic liberated the planet from Imperial Governor Bursthed. The planet hosted the Ruten Pet Show. " .
<https://starwars.com#118ac771-d99f-4dea-9b6f-85aaadea82a3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cerenia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cerenia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mbandamonte> .
<https://starwars.com#sector_Mbandamonte> <http://telicent.io/ontology/primaryName> "Mbandamonte" .
<https://starwars.com#planet_Cerenia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .

