Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Taanab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Taanab> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e25af71d-3c49-4384-8cec-121e2bf88fba> .
<https://starwars.com#planet_Taanab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e25af71d-3c49-4384-8cec-121e2bf88fba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Taanab> <http://telicent.io/ontology/primaryName> "Taanab" .
<https://starwars.com#planet_Taanab> <http://www.w3.org/2000/01/rdf-schema#comment> "The day after the Battle of Yavin, the Rebel Alliance Lieutenant Caluan Ematt was ambushed by Imperial forces on Taanab but managed to flee to the planet Cyrkon in Hutt Space before the Empire blockaded it. At some point before the Battle of Endor, the gambler Lando Calrissian participated in the Battle of Taanab where he defeated a pirate fleet. " .
<https://starwars.com#planet_Taanab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#e25af71d-3c49-4384-8cec-121e2bf88fba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taanab"^^<http://www.w3.org/2001/XMLSchema#string> .

