Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f780421a-f13b-42af-a91d-cfc34a747606> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#f780421a-f13b-42af-a91d-cfc34a747606> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bnar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bnar> <http://www.w3.org/2000/01/rdf-schema#comment> "Bnar VII was an astronomical object[2] located in the Bnar system, a part of the Braxant sector in the New Territories portion of the Outer Rim Territories.[1] The decades-long career of the Noehon slaver Tir'uh saw her operate within an area of the galaxy spanning from Bnar VII,[2] in the northern section of the galaxy,[1] to Kessel,[2] a planet in the galaxy's eastern portion.[3] In 2 ABY,[4] a Rebel Alliance Task Force on Alliance Security SecuriDex datafile on the Mytaranor Slaving Council, of which Tir'uh was a member, noted the possibility that the Noehon was familiar with every location between Bnar VII and Kessel that was related to the slaving business.[2]" .
<https://starwars.com#planet_Bnar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f780421a-f13b-42af-a91d-cfc34a747606> .
<https://starwars.com#planet_Bnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Braxant> .
<https://starwars.com#planet_Bnar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Braxant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Braxant> <http://telicent.io/ontology/primaryName> "Braxant" .
<https://starwars.com#sector_Braxant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bnar> <http://telicent.io/ontology/primaryName> "Bnar" .

