Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_S3> <http://telicent.io/ontology/primaryName> "S3" .
<https://starwars.com#7feb743c-faf8-4553-a1cb-c0d4020e095e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_AboDreth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#29cdedb4-b1a3-482b-8124-e7d0097db86b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abo Dreth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#7feb743c-faf8-4553-a1cb-c0d4020e095e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_AboDreth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#29cdedb4-b1a3-482b-8124-e7d0097db86b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_S3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_AboDreth> <http://www.w3.org/2000/01/rdf-schema#comment> "Abo Dreth was a planet in the Corporate Sector, thriving with lakes and rivers but with a nitrogen-based atmosphere. " .
<https://starwars.com#planet_AboDreth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AboDreth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#29cdedb4-b1a3-482b-8124-e7d0097db86b> .
<https://starwars.com#grid_S3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#7feb743c-faf8-4553-a1cb-c0d4020e095e> .
<https://starwars.com#planet_AboDreth> <http://telicent.io/ontology/primaryName> "Abo Dreth" .

