Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Noquivzor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Noquivzor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Noquivzor> <http://telicent.io/ontology/primaryName> "Noquivzor" .
<https://starwars.com#6c95be11-552c-4dad-b5ae-9ebe5eacdf22> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Noquivzor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Noquivzor> <http://www.w3.org/2000/01/rdf-schema#comment> "Noquivzor was a planet located in the Colonies. " .
<https://starwars.com#planet_Noquivzor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6c95be11-552c-4dad-b5ae-9ebe5eacdf22> .
<https://starwars.com#6c95be11-552c-4dad-b5ae-9ebe5eacdf22> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Noquivzor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .

