Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Kedorzha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Kedorzha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bca816e4-6920-41ed-94ba-1fcda34858c3> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kedorzha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#bca816e4-6920-41ed-94ba-1fcda34858c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kedorzha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kedorzha> <http://www.w3.org/2000/01/rdf-schema#comment> "Kedorzha was a planet in the Mid Rim inhabited by the species known as the Kedorzhans. Kedorzhans were commonly found enslaved by House Garonnin, working in the mines. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kedorzha> <http://telicent.io/ontology/primaryName> "Kedorzha" .
<https://starwars.com#planet_Kedorzha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bca816e4-6920-41ed-94ba-1fcda34858c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

