Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Trammen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Harron> .
<https://starwars.com#sector_Harron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#8d2ffa47-243a-42a4-a8d7-d080871e5621> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trammen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trammen> <http://telicent.io/ontology/primaryName> "Trammen" .
<https://starwars.com#8d2ffa47-243a-42a4-a8d7-d080871e5621> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trammen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trammen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .
<https://starwars.com#planet_Trammen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8d2ffa47-243a-42a4-a8d7-d080871e5621> .
<https://starwars.com#planet_Trammen> <http://www.w3.org/2000/01/rdf-schema#comment> "Trammen was a heavily-populated planet that was located in the Trammen system of the Harron sector. It contained an Imperial Army garrison; all the line squads of the Imperial Army stationed there were re-equipped with light repeating blasters. " .
<https://starwars.com#sector_Harron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Harron> <http://telicent.io/ontology/primaryName> "Harron" .

