Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Thermon> <http://www.w3.org/2000/01/rdf-schema#comment> "Thermon was a planet located within the Thermon system of the Mid Rim with many moons that spewed methane gas from geysers. " .
<https://starwars.com#planet_Thermon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c02b68da-24fb-46ef-b13f-2ae17debab66> .
<https://starwars.com#planet_Thermon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c02b68da-24fb-46ef-b13f-2ae17debab66> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thermon> <http://telicent.io/ontology/primaryName> "Thermon" .
<https://starwars.com#planet_Thermon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thermon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#c02b68da-24fb-46ef-b13f-2ae17debab66> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thermon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

