Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#09be6d76-3d46-472b-ba4c-6cb1c266c8f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Derra> <http://www.w3.org/2000/01/rdf-schema#comment> "Derra was an astronomical object located in the galaxy's Expansion Region. During the High Republic Era, it housed the Derra Outpost which was headed by Jedi Master Tera Sinube around 231 BBY. Derra was relatively close to the Mid Rim planet Cyclor, so when the Nihil attacked the Cyclor Shipyards, the Jedi outpost there was asked to assist. Sinube sent a Drift of Jedi Vectors headed by Master Porter Engle. " .
<https://starwars.com#planet_Derra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#09be6d76-3d46-472b-ba4c-6cb1c266c8f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Derra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mikaster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Derra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#planet_Derra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#09be6d76-3d46-472b-ba4c-6cb1c266c8f6> .
<https://starwars.com#sector_Mikaster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Derra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mikaster> .
<https://starwars.com#planet_Derra> <http://telicent.io/ontology/primaryName> "Derra" .
<https://starwars.com#sector_Mikaster> <http://telicent.io/ontology/primaryName> "Mikaster" .

