Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_R4> <http://telicent.io/ontology/primaryName> "R4" .
<https://starwars.com#8538e6f2-6545-4f3a-88b2-1b6691a41363> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#cd173d95-da2e-4864-8c1b-d4c68489d1fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Athiss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8538e6f2-6545-4f3a-88b2-1b6691a41363> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_R4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8538e6f2-6545-4f3a-88b2-1b6691a41363> .
<https://starwars.com#planet_Athiss> <http://www.w3.org/2000/01/rdf-schema#comment> "Athiss was a location in the galaxy which was a destination of a shipment of reedug from the Reekrider Cartel that was stolen by one of Strikes of Tempest Runner Pan Eyta before it got there. " .
<https://starwars.com#planet_Athiss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cd173d95-da2e-4864-8c1b-d4c68489d1fc> .
<https://starwars.com#planet_Athiss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Athiss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#grid_R4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Athiss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#cd173d95-da2e-4864-8c1b-d4c68489d1fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_R4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Athiss> <http://telicent.io/ontology/primaryName> "Athiss" .

