Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kuat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c6ec0869-8703-42f4-b8d4-962fa6c8ea1b> .
<https://starwars.com#planet_Kuat> <http://www.w3.org/2000/01/rdf-schema#comment> "Industrial planet home to Kuat Drive Yards, the manufacturer of Star Destroyers." .
<https://starwars.com#c6ec0869-8703-42f4-b8d4-962fa6c8ea1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kuat> <http://telicent.io/ontology/primaryName> "Kuat" .
<https://starwars.com#planet_Kuat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Kuat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Kuat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c6ec0869-8703-42f4-b8d4-962fa6c8ea1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuat"^^<http://www.w3.org/2001/XMLSchema#string> .

