Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nothoiin> <http://telicent.io/ontology/primaryName> "Nothoiin" .
<https://starwars.com#planet_Nothoiin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nothoiin> <http://www.w3.org/2000/01/rdf-schema#comment> "Nothoiin was a planet in the Anoat sector. It had a moon on which ur-diamonds were mined. During the Iron Blockade, a makeshift medical center on Nothoiin had to resort to smugglers to acquire supplies from Gerrenthum. The planet's native sentients species, the gold-skinned Nothoiins, once ruled the entire Anoat sector. " .
<https://starwars.com#1e44530a-6dd8-47ba-b5be-c4cee7bf34cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nothoiin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Nothoiin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1e44530a-6dd8-47ba-b5be-c4cee7bf34cd> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Nothoiin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Nothoiin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1e44530a-6dd8-47ba-b5be-c4cee7bf34cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

