Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zaloriis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Askarian> .
<https://starwars.com#planet_Zaloriis> <http://telicent.io/ontology/primaryName> "Zaloriis" .
<https://starwars.com#planet_Zaloriis> <http://www.w3.org/2000/01/rdf-schema#comment> "Zaloriis was a location inhabited by Zalorians. Shortly before the Battle of Hoth in the year 3 ABY, a campaign occurred on Zaloriis between the Zalorians and the Galactic Empire, involving a revolt there. The human male Maximilian Veers demonstrated his cunning, courage, and leadership in the campaign, and won it for the Empire with the use of new tactics he developed. The conflict on Zaloriis was one of several conflicts that led to Veers' eventual promotion to the rank of general in the Imperial Army, and assignment to the Sith Lord Darth Vader's Death Squadron. It was also mentioned in the Galactic Explorer's Guide published by Hondo Ohnaka after the Battle of Starkiller Base in 34 BBY " .
<https://starwars.com#sector_Askarian> <http://telicent.io/ontology/primaryName> "Askarian" .
<https://starwars.com#sector_Askarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Zaloriis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#planet_Zaloriis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9a5f591e-570c-4a2a-bbc9-24334765c149> .
<https://starwars.com#9a5f591e-570c-4a2a-bbc9-24334765c149> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zaloriis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Askarian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9a5f591e-570c-4a2a-bbc9-24334765c149> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zaloriis"^^<http://www.w3.org/2001/XMLSchema#string> .

