Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LenicoIV> <http://telicent.io/ontology/primaryName> "Lenico IV" .
<https://starwars.com#planet_LenicoIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Lenico IV was a planet in the Lenico system of the Outer Rim Territories. Its barren surface presented ruins and others desolated places, like the Ash Plains. Numerous space station colonies such as Lenico Colony Blue remained in its orbit. " .
<https://starwars.com#region_OuterRIm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_LenicoIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cademimu> .
<https://starwars.com#planet_LenicoIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L6> .
<https://starwars.com#planet_LenicoIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6f5839c-1390-4846-a2ac-ed65f88528ea> .
<https://starwars.com#sector_Cademimu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRIm> .
<https://starwars.com#planet_LenicoIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e6f5839c-1390-4846-a2ac-ed65f88528ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#e6f5839c-1390-4846-a2ac-ed65f88528ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lenico IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Cademimu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Cademimu> <http://telicent.io/ontology/primaryName> "Cademimu" .
<https://starwars.com#region_OuterRIm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#region_OuterRIm> <http://telicent.io/ontology/primaryName> "Outer RIm" .

