Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Citlik> <http://telicent.io/ontology/primaryName> "Citlik" .
<https://starwars.com#planet_Nivek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Citlik> .
<https://starwars.com#planet_Nivek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5fa1ce58-c75c-4a1e-adc6-054673888073> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nivek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nivek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#sector_Citlik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Nivek> <http://www.w3.org/2000/01/rdf-schema#comment> "Nivek, also know as Night Planet, was a planet in the Expansion Region, known as a 'night planet' due to the perpetual darkness which shrouded its surface. " .
<https://starwars.com#sector_Citlik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nivek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5fa1ce58-c75c-4a1e-adc6-054673888073> .
<https://starwars.com#5fa1ce58-c75c-4a1e-adc6-054673888073> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nivek> <http://telicent.io/ontology/primaryName> "Nivek" .

