Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0fa4c535-585e-4eaa-8af8-ed523f297677> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alzoc"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0fa4c535-585e-4eaa-8af8-ed523f297677> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c4af6868-fc50-4f9d-b128-ff58ea167518> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Alzoc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Alzoc> <http://telicent.io/ontology/primaryName> "Alzoc" .
<https://starwars.com#c4af6868-fc50-4f9d-b128-ff58ea167518> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Alzoc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sujimis> .
<https://starwars.com#grid_P19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Sujimis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Alzoc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P19> .
<https://starwars.com#planet_Alzoc> <http://www.w3.org/2000/01/rdf-schema#comment> "Alzoc III, also known as Alzoc, was a frozen planet located in the Sujimis sector of the galaxy's Outer Rim Territories that was the homeworld of the Talz species. The world was taken over by the Galactic Empire due to its exploitable mineral wealth. The pilot Praz Fateer was described as being the fastest on Alzoc III by a barker aboard the Frander's Bay space station. The Mandalorian bounty hunter Din Djarin was involved in a job on Alzoc III at some point before 9 ABY. " .
<https://starwars.com#planet_Alzoc> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0fa4c535-585e-4eaa-8af8-ed523f297677> .
<https://starwars.com#sector_Sujimis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_P19> <http://telicent.io/ontology/primaryName> "P19" .
<https://starwars.com#grid_P19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c4af6868-fc50-4f9d-b128-ff58ea167518> .
<https://starwars.com#grid_P19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Sujimis> <http://telicent.io/ontology/primaryName> "Sujimis" .

