Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#637ce5f5-2c01-406b-9091-84f9b3cdcffd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#637ce5f5-2c01-406b-9091-84f9b3cdcffd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T9> <http://telicent.io/ontology/primaryName> "T9" .
<https://starwars.com#grid_T9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Akrittar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#grid_T9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Akrittar> <http://www.w3.org/2000/01/rdf-schema#comment> "Akrit'tar was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#grid_T9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#637ce5f5-2c01-406b-9091-84f9b3cdcffd> .
<https://starwars.com#planet_Akrittar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T9> .
<https://starwars.com#c4beb630-17b5-4cff-9ca0-40159e73c1e2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Akrittar> <http://telicent.io/ontology/primaryName> "Akrit'tar" .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Akrittar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c4beb630-17b5-4cff-9ca0-40159e73c1e2> .
<https://starwars.com#planet_Akrittar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c4beb630-17b5-4cff-9ca0-40159e73c1e2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Akrit'tar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

