Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Delacrix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#856e0f7e-bb2f-4a4d-85cc-ca936df5d8bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Delacrix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#856e0f7e-bb2f-4a4d-85cc-ca936df5d8bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Delacrix> <http://telicent.io/ontology/primaryName> "Delacrix" .
<https://starwars.com#planet_Delacrix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T9> .
<https://starwars.com#planet_Delacrix> <http://www.w3.org/2000/01/rdf-schema#comment> "Delacrix was an astronomical object in the Outer Rim Territories and the Slice. Located at grid square T-9 on the Standard Galactic Grid, it was connected to the planet Klatooine via hyperspace route. " .
<https://starwars.com#planet_Delacrix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#856e0f7e-bb2f-4a4d-85cc-ca936df5d8bd> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Delacrix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .

