Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Foundry> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Foundry> <http://telicent.io/ontology/primaryName> "Foundry" .
<https://starwars.com#planet_Foundry> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Foundry> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e343acf-ae05-419a-bfa7-ccf4b31a8886> .
<https://starwars.com#planet_Foundry> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#0e343acf-ae05-419a-bfa7-ccf4b31a8886> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0e343acf-ae05-419a-bfa7-ccf4b31a8886> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Foundry"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Foundry> <http://www.w3.org/2000/01/rdf-schema#comment> "Foundry was a location in the galaxy that was under control of the Galactic Empire. During the operation at the Berullian Checkpoint, Imperial Grand General Ormeddon was dispatched to deal with the situation. With Ormeddon in less restrictive security, Beckett's gang stole Ormeddon's shuttle and returned to Foundry. They landed in Ormeddon's personal docking bay and stole experimental deflector shield generator technology. " .

