Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Comra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1cd4873a-c040-440e-b983-d73863b42949> .
<https://starwars.com#planet_Comra> <http://telicent.io/ontology/primaryName> "Comra" .
<https://starwars.com#1cd4873a-c040-440e-b983-d73863b42949> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Comra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Comra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#planet_Comra> <http://www.w3.org/2000/01/rdf-schema#comment> "Comra was an astronomical object located in Wild Space that was represented in the New Republic Senate by the Centrist Mortan in 28 ABY. " .
<https://starwars.com#sector_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .
<https://starwars.com#planet_Comra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1cd4873a-c040-440e-b983-d73863b42949> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Comra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prefsbelt> .
<https://starwars.com#sector_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

