Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dd025c44-c2ac-40e8-abfc-a8e8d09d70fe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ulicia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ulicia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd025c44-c2ac-40e8-abfc-a8e8d09d70fe> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Ulicia> <http://telicent.io/ontology/primaryName> "Ulicia" .
<https://starwars.com#planet_Ulicia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#dd025c44-c2ac-40e8-abfc-a8e8d09d70fe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ulicia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Ulicia> <http://www.w3.org/2000/01/rdf-schema#comment> "Ulicia was an industrial planet located in the Ulicia system of the Outer Rim Territories' Corporate Sector, which was governed by the Corporate Sector Authority. It was positioned along the hyperlane known as the Shaltin Tunnels. In 0 ABY, the CSA executive Hart-and-Parn Gorra-Fiolla recovered a prisoner named Naven Crel from the headquarters of the Commex corporation located on Ulicia. " .
<https://starwars.com#planet_Ulicia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

