Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#155b517d-4149-4d84-8d5c-327db242ee5a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Antillion> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#155b517d-4149-4d84-8d5c-327db242ee5a> .
<https://starwars.com#planet_Antillion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#155b517d-4149-4d84-8d5c-327db242ee5a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Antillion"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Antillion> <http://telicent.io/ontology/primaryName> "Antillion" .
<https://starwars.com#planet_Antillion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

