Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mindor> <http://telicent.io/ontology/primaryName> "Mindor" .
<https://starwars.com#planet_Mindor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Mindor> <http://www.w3.org/2000/01/rdf-schema#comment> "Mindor was an astronomical object in the Inner Rim of the galaxy. " .
<https://starwars.com#planet_Mindor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#33a4f3e1-85a7-4e48-ad0a-00e53095fcfe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mindor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33a4f3e1-85a7-4e48-ad0a-00e53095fcfe> .
<https://starwars.com#33a4f3e1-85a7-4e48-ad0a-00e53095fcfe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mindor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mindor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

