Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Almania> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4251b1b1-a394-4fa7-9ee6-948faef2a1c4> .
<https://starwars.com#grid_S5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#4251b1b1-a394-4fa7-9ee6-948faef2a1c4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Almania"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Almania> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4251b1b1-a394-4fa7-9ee6-948faef2a1c4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mortex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#55d209c2-9909-4235-aef3-d92329b3aa0c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Almania> <http://www.w3.org/2000/01/rdf-schema#comment> "Almania was an astronomical object situated within the regions known as the Outer Rim Territories and the New Territories. It was located in grid square S-5 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Almania> <http://telicent.io/ontology/primaryName> "Almania" .
<https://starwars.com#sector_Mortex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mortex> <http://telicent.io/ontology/primaryName> "Mortex" .
<https://starwars.com#55d209c2-9909-4235-aef3-d92329b3aa0c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_S5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#55d209c2-9909-4235-aef3-d92329b3aa0c> .
<https://starwars.com#planet_Almania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#planet_Almania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mortex> .
<https://starwars.com#grid_S5> <http://telicent.io/ontology/primaryName> "S5" .
<https://starwars.com#grid_S5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

