Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Trunska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#planet_Trunska> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trunska> <http://www.w3.org/2000/01/rdf-schema#comment> "Trunska was a planet located within the Trunska system of the Colonies. " .
<https://starwars.com#85c80d47-d28d-48f5-ae8a-198b0c0552c0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trunska"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trunska> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#85c80d47-d28d-48f5-ae8a-198b0c0552c0> .
<https://starwars.com#85c80d47-d28d-48f5-ae8a-198b0c0552c0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trunska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Trunska> <http://telicent.io/ontology/primaryName> "Trunska" .

