Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#fee18043-d19c-495d-97aa-937560495833> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bogden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Bogden> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#fee18043-d19c-495d-97aa-937560495833> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bogden"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bogden> <http://telicent.io/ontology/primaryName> "Bogden" .
<https://starwars.com#planet_Bogden> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fee18043-d19c-495d-97aa-937560495833> .
<https://starwars.com#planet_Bogden> <http://www.w3.org/2000/01/rdf-schema#comment> "Bogden was a planet located in the galaxy's Inner Rim on the Hydian Way that was orbited by multiple moons, one of which was the location where the Sith Lord Darth Tyranus secretly hired the bounty hunter Jango Fett to become the cloning template for the future Grand Army of the Republic. " .
<https://starwars.com#planet_Bogden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .

