Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AlliedTion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5c274efb-eca9-4bbf-b29e-41ab8a0fd3eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Barseg> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Barseg> <http://www.w3.org/2000/01/rdf-schema#comment> "Barseg was a planet located in the Tion Cluster of the Outer Rim Territories, along the Perlemian Trade Route. " .
<https://starwars.com#5c274efb-eca9-4bbf-b29e-41ab8a0fd3eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barseg"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_AlliedTion> <http://telicent.io/ontology/primaryName> "Allied Tion" .
<https://starwars.com#planet_Barseg> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Barseg> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AlliedTion> .
<https://starwars.com#sector_AlliedTion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Barseg> <http://telicent.io/ontology/primaryName> "Barseg" .
<https://starwars.com#planet_Barseg> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5c274efb-eca9-4bbf-b29e-41ab8a0fd3eb> .

