Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e2cf9939-47ae-4670-b0d1-4c2e26c8c07d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fether> <http://telicent.io/ontology/primaryName> "Fether" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Fether> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e2cf9939-47ae-4670-b0d1-4c2e26c8c07d> .
<https://starwars.com#planet_Fether> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Galactic Civil War, a group of bounty hunters ambushed the crew of a freighter in the streets of the town due to the starship's captain owing money to the bounty hunters' employer. The crew was subsequently chased to its ship and then left Fether. " .
<https://starwars.com#planet_Fether> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Fether> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Fether> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#e2cf9939-47ae-4670-b0d1-4c2e26c8c07d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fether"^^<http://www.w3.org/2001/XMLSchema#string> .

