Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a21cf207-156d-4ab9-b62f-a0d85c792fa5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KimmBesh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a21cf207-156d-4ab9-b62f-a0d85c792fa5> .
<https://starwars.com#planet_KimmBesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_KimmBesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_KimmBesh> <http://telicent.io/ontology/primaryName> "Kimm Besh" .
<https://starwars.com#a21cf207-156d-4ab9-b62f-a0d85c792fa5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kimm Besh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KimmBesh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KimmBesh> <http://www.w3.org/2000/01/rdf-schema#comment> "Kimm Besh was a planet located in the Kimm Besh system of the Juvex sector, in the Mid Rim of the galaxy. It was one of a trio of dingy industrial worlds belonging to House Sreethyn. " .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

