Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Symbia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Symbia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Symbia> <http://telicent.io/ontology/primaryName> "Symbia" .
<https://starwars.com#91d9b205-ffab-42b6-bf46-fa6b09d05bc9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Symbia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Symbia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Symbia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#91d9b205-ffab-42b6-bf46-fa6b09d05bc9> .
<https://starwars.com#91d9b205-ffab-42b6-bf46-fa6b09d05bc9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Symbia"^^<http://www.w3.org/2001/XMLSchema#string> .

