Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d860ebb9-3acb-4836-9f23-c1e2493e5ab4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d860ebb9-3acb-4836-9f23-c1e2493e5ab4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Columus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Columus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Columus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d860ebb9-3acb-4836-9f23-c1e2493e5ab4> .
<https://starwars.com#planet_Columus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Columus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Columus> <http://telicent.io/ontology/primaryName> "Columus" .
<https://starwars.com#planet_Columus> <http://www.w3.org/2000/01/rdf-schema#comment> "Columus was an astronomical object located in the galaxy's Core Worlds which was the homeworld of the Columi. The pirate queen Maz Kanata hid a portion of the spoils from her reign there in a buried vault equipped with an antitamper sub-space alarm. As of when she marked Columus on a map in the Smuggler's Guide logbook at some point prior to or during 10 BBY, the alarm protecting the cache of treasure on Columus had not sounded. " .

