Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#89325316-e7a4-435e-8f58-8e6e855c27cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dagary Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DagaryMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89325316-e7a4-435e-8f58-8e6e855c27cd> .
<https://starwars.com#planet_DagaryMinor> <http://telicent.io/ontology/primaryName> "Dagary Minor" .
<https://starwars.com#planet_DagaryMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_DagaryMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Dagary Minor was the location of a battle that was fought during the early stages of the Mandalorian Wars. Both the Meetra Surik and Xaart, who later became a Republic spy, fought in the battle, though the Republic did not win. " .
<https://starwars.com#planet_DagaryMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#89325316-e7a4-435e-8f58-8e6e855c27cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_DagaryMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .

