Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tennuutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_OrdTiddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tennuutta> .
<https://starwars.com#planet_OrdTiddell> <http://telicent.io/ontology/primaryName> "Ord Tiddell" .
<https://starwars.com#sector_Tennuutta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdTiddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#cdd47f8e-77f1-4698-9272-18673db2e97b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Tiddell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tennuutta> <http://telicent.io/ontology/primaryName> "Tennuutta" .
<https://starwars.com#planet_OrdTiddell> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Tiddell was a planet in the Mid Rim. During the Galactic Civil War between the Galactic Empire and the Alliance to Restore the Republic, Alliance forces, including Lieutenant Caluan Ematt attacked Ord Tiddell as part of the Mid Rim Offensive, an operation by the Alliance and the Mid Rim revolutionaries to take control of the Mid Rim. The operation ended in failure and the Alliance was forced to retreat from Ord Tiddell and many other worlds, including Jeyell, Durkteel, Pothor, Charros IV, and Trasse. Several revolutionaries evacuated with Alliance forces, although many remained on their planets to harass the Empire, who was expected to take quick control over the former Alliance territories. " .
<https://starwars.com#cdd47f8e-77f1-4698-9272-18673db2e97b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdTiddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdTiddell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cdd47f8e-77f1-4698-9272-18673db2e97b> .

