Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thokosia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thokosia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Thokosia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#planet_Thokosia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maerdocia> .
<https://starwars.com#sector_Maerdocia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Thokosia> <http://telicent.io/ontology/primaryName> "Thokosia" .
<https://starwars.com#1d896733-a075-473a-87fd-a9cfd24bf388> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Maerdocia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Maerdocia> <http://telicent.io/ontology/primaryName> "Maerdocia" .
<https://starwars.com#planet_Thokosia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1d896733-a075-473a-87fd-a9cfd24bf388> .
<https://starwars.com#1d896733-a075-473a-87fd-a9cfd24bf388> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thokosia"^^<http://www.w3.org/2001/XMLSchema#string> .

