Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_kFarri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_kFarri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#be6e2509-85af-4d15-b192-6a1c5b6f2488> <http://ies.data.gov.uk/ontology/ies4#representationValue> "k'Farri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_kFarri> <http://telicent.io/ontology/primaryName> "k'Farri" .
<https://starwars.com#planet_kFarri> <http://www.w3.org/2000/01/rdf-schema#comment> "The correct title of this article is k'Farri. It appears incorrectly above due to technical restrictions." .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#be6e2509-85af-4d15-b192-6a1c5b6f2488> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_kFarri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_kFarri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be6e2509-85af-4d15-b192-6a1c5b6f2488> .

