Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PorusVida> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_PorusVida> <http://telicent.io/ontology/primaryName> "Porus Vida" .
<https://starwars.com#planet_PorusVida> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_PorusVida> <http://www.w3.org/2000/01/rdf-schema#comment> "Porus Vida was a planet located in the Inner Rim and famous for its beauty and its culture. Despite its reputation as a peaceful world of museums, Porus Vida saw conflict throughout its history, including several sieges during the Alsakan Conflicts, and was devatasted by the Imperial Remnant in 12 ABY. " .
<https://starwars.com#d26b1a54-3b9a-44e9-8247-040e092c2f2f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d26b1a54-3b9a-44e9-8247-040e092c2f2f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Porus Vida"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PorusVida> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d26b1a54-3b9a-44e9-8247-040e092c2f2f> .
<https://starwars.com#planet_PorusVida> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

