Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Worrudu> <http://www.w3.org/2000/01/rdf-schema#comment> "Worru'du was a planet located within the Worru'du system of the Core Worlds and known for its grass fields. The grass from Worru'du could be used for basket weaving. " .
<https://starwars.com#0b06dcf8-f986-4fbc-9dea-0a4a30cf63ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0b06dcf8-f986-4fbc-9dea-0a4a30cf63ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Worru'du"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Worrudu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Worrudu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0b06dcf8-f986-4fbc-9dea-0a4a30cf63ad> .
<https://starwars.com#planet_Worrudu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Worrudu> <http://telicent.io/ontology/primaryName> "Worru'du" .
<https://starwars.com#planet_Worrudu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

