Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mandress> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Mondress> <http://telicent.io/ontology/primaryName> "Mondress" .
<https://starwars.com#9980d263-754d-434b-aed5-1a83bfed4e24> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mandress> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mondress> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Mandress> <http://telicent.io/ontology/primaryName> "Mandress" .
<https://starwars.com#planet_Mondress> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Mondress> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9980d263-754d-434b-aed5-1a83bfed4e24> .
<https://starwars.com#9980d263-754d-434b-aed5-1a83bfed4e24> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mondress"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mondress> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mondress> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mandress> .

