Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Orax> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b692de7e-cecc-4f2d-97fd-9c72b7483593> .
<https://starwars.com#planet_Orax> <http://telicent.io/ontology/primaryName> "Orax" .
<https://starwars.com#planet_Orax> <http://www.w3.org/2000/01/rdf-schema#comment> "Orax was a planet in the Outer Rim Territories, and was the homeworld of the crystalline Shard. " .
<https://starwars.com#sector_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#sector_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Orax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Orax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Subterrel> .
<https://starwars.com#b692de7e-cecc-4f2d-97fd-9c72b7483593> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orax"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b692de7e-cecc-4f2d-97fd-9c72b7483593> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Orax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L20> .

