Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Modus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Modus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c4272ce8-5b02-4488-ac17-9909257ee417> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Modus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c4272ce8-5b02-4488-ac17-9909257ee417> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Modus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c4272ce8-5b02-4488-ac17-9909257ee417> .
<https://starwars.com#planet_Modus> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Modus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Modus> <http://telicent.io/ontology/primaryName> "Modus" .

