Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Daruvvia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#21e99a53-1467-41ba-80dd-dfe08837c7c0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Daruvvia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#21e99a53-1467-41ba-80dd-dfe08837c7c0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Daruvvia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Daruvvia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Daruvvia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Daruvvia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#21e99a53-1467-41ba-80dd-dfe08837c7c0> .
<https://starwars.com#planet_Daruvvia> <http://telicent.io/ontology/primaryName> "Daruvvia" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .

