Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Ragith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Majoor> .
<https://starwars.com#planet_Ragith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5d864739-64d4-43ba-8615-552c2a05c776> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ragith> <http://telicent.io/ontology/primaryName> "Ragith" .
<https://starwars.com#5d864739-64d4-43ba-8615-552c2a05c776> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ragith"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ragith> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d864739-64d4-43ba-8615-552c2a05c776> .
<https://starwars.com#planet_Ragith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#planet_Ragith> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Majoor> <http://telicent.io/ontology/primaryName> "Majoor" .
<https://starwars.com#sector_Majoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

