Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Wobani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bryx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Wobani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bryx> .
<https://starwars.com#sector_Bryx> <http://telicent.io/ontology/primaryName> "Bryx" .
<https://starwars.com#planet_Wobani> <http://telicent.io/ontology/primaryName> "Wobani" .
<https://starwars.com#sector_Bryx> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#06566847-faac-4325-998a-45f53945e6ed> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wobani"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Wobani> <http://www.w3.org/2000/01/rdf-schema#comment> "A desolate wasteland and the site of an Imperial penal labor colony." .
<https://starwars.com#06566847-faac-4325-998a-45f53945e6ed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Wobani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#planet_Wobani> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#06566847-faac-4325-998a-45f53945e6ed> .

