Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#02b3981e-e96e-4016-8bdc-71c592878991> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Carnovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#02b3981e-e96e-4016-8bdc-71c592878991> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carnovia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Carnovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Carnovia> <http://www.w3.org/2000/01/rdf-schema#comment> "Carnovia was a planet located in Hutt Space that was home to Carnovian eel-pups. It was a humid world largely covered by water. The Floating Palace, the headquarters of the Vermilic kajidic, was situated on the world. " .
<https://starwars.com#planet_Carnovia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02b3981e-e96e-4016-8bdc-71c592878991> .
<https://starwars.com#planet_Carnovia> <http://telicent.io/ontology/primaryName> "Carnovia" .
<https://starwars.com#planet_Carnovia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

