Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nazzri> <http://www.w3.org/2000/01/rdf-schema#comment> "Nazzri was an astronomical object located in the regions known as the Mid Rim and the Slice. It was also situated in the grid square P-9 of the Standard Galactic Grid. A hyperspace route linked it to the celestial body Togoria as well as the Expansion Region astronomical object Vena. " .
<https://starwars.com#871cbae7-69ee-41a0-8a7a-d9be7ac5c312> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nazzri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_DonaLaza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_DonaLaza> <http://telicent.io/ontology/primaryName> "Dona Laza" .
<https://starwars.com#sector_DonaLaza> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#871cbae7-69ee-41a0-8a7a-d9be7ac5c312> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nazzri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#planet_Nazzri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nazzri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#871cbae7-69ee-41a0-8a7a-d9be7ac5c312> .
<https://starwars.com#planet_Nazzri> <http://telicent.io/ontology/primaryName> "Nazzri" .
<https://starwars.com#planet_Nazzri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DonaLaza> .

