Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3a4e1945-c5f0-41f7-b13d-c2772a3bc710> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fwatna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a4e1945-c5f0-41f7-b13d-c2772a3bc710> .
<https://starwars.com#sector_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#planet_Fwatna> <http://www.w3.org/2000/01/rdf-schema#comment> "Fwatna was a planet in the Subterrel sector near the site where Lando Calrissian found the abandoned freighter Spicy Lady. The ship belonged to his smuggling associate Jarril. This also led to the discovery of Dolph. " .
<https://starwars.com#sector_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Fwatna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K20> .
<https://starwars.com#planet_Fwatna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Subterrel> .
<https://starwars.com#3a4e1945-c5f0-41f7-b13d-c2772a3bc710> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fwatna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Fwatna> <http://telicent.io/ontology/primaryName> "Fwatna" .
<https://starwars.com#planet_Fwatna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

