Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bruanii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Quamar> <http://telicent.io/ontology/primaryName> "Quamar" .
<https://starwars.com#planet_Quamar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#planet_Quamar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#e09faa30-c61a-4394-ac50-add0e39969a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quamar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Quamar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bruanii> .
<https://starwars.com#planet_Quamar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e09faa30-c61a-4394-ac50-add0e39969a4> .
<https://starwars.com#sector_Bruanii> <http://telicent.io/ontology/primaryName> "Bruanii" .
<https://starwars.com#sector_Bruanii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Quamar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e09faa30-c61a-4394-ac50-add0e39969a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

