Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_Q4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Doniphon> <http://telicent.io/ontology/primaryName> "Doniphon" .
<https://starwars.com#sector_Kwymar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kwymar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f479dbc8-a5b1-4142-9387-2da3a0758d14> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Doniphon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#44f31efa-d949-4fe7-b2e5-8c4064183073> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Doniphon> <http://www.w3.org/2000/01/rdf-schema#comment> "Doniphon was a planet in the Outer Rim's Kwymar sector, in the system of the same name. Doniphon was invaded by the Galactic Empire in 17 BBY, during the Empire's suppressions of rebel activity in the sector. An Imperial platoon succeeded in rooting out Doniphon's dissidents, although promising stormtrooper commander Beilert Valance suffered grave wounds in the process. " .
<https://starwars.com#sector_Kwymar> <http://telicent.io/ontology/primaryName> "Kwymar" .
<https://starwars.com#f479dbc8-a5b1-4142-9387-2da3a0758d14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_Q4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_Q4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#44f31efa-d949-4fe7-b2e5-8c4064183073> .
<https://starwars.com#planet_Doniphon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f479dbc8-a5b1-4142-9387-2da3a0758d14> .
<https://starwars.com#planet_Doniphon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kwymar> .
<https://starwars.com#44f31efa-d949-4fe7-b2e5-8c4064183073> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Doniphon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#grid_Q4> <http://telicent.io/ontology/primaryName> "Q4" .
<https://starwars.com#planet_Doniphon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

