Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vicondor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#planet_Vicondor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vorc> .
<https://starwars.com#planet_Vicondor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#46390c46-3575-47d8-87a3-e3727de642bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vicondor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Vorc> <http://telicent.io/ontology/primaryName> "Vorc" .
<https://starwars.com#planet_Vicondor> <http://telicent.io/ontology/primaryName> "Vicondor" .
<https://starwars.com#planet_Vicondor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46390c46-3575-47d8-87a3-e3727de642bb> .
<https://starwars.com#sector_Vorc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Vorc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vicondor> <http://www.w3.org/2000/01/rdf-schema#comment> "Vicondor was an astronomical object located in the Mid Rim of the galaxy, connected to Vortex and Dorin by hyperspace routes. It was situated at the coordinates J-7 on the Standard Galactic Grid. " .
<https://starwars.com#46390c46-3575-47d8-87a3-e3727de642bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

