Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Krayiss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d10a9f35-6673-4da8-b30b-0b71f5582ed6> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Krayiss> <http://www.w3.org/2000/01/rdf-schema#comment> "Krayiss II, also referred to as Krayiss Two, was a planet in the Outer Rim, in the remote Sith Worlds region of the Stygian Caldera nebula. Connected to other nearby worlds by the Nache Bhelfia hyperlane, Krayiss II was considered one of the five sacred Sith planets that formed the heart of the Sith Empire. In ancient times, Krayiss II was home to a massive library-temple that was a place of meditation and study for Sith sorcerers. However, after 14,000 BBY, it was buried and largely forgotten, with its large obelisk being all that remained above ground. Still, Krayiss II attracted a number of Jedi seeking to learn the secrets of the ancient temple. In 4000 BBY, a Jedi Knight named Vara Nreem traveled to the world for this purpose, but she was deemed unworthy by the Sith spirits that dwelled within the ruin. As a result, Nreem was killed and made to suffer in torment for eternity. " .
<https://starwars.com#planet_Krayiss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#d10a9f35-6673-4da8-b30b-0b71f5582ed6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d10a9f35-6673-4da8-b30b-0b71f5582ed6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Krayiss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Krayiss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Krayiss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Krayiss> <http://telicent.io/ontology/primaryName> "Krayiss" .

