Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Reltooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Reltooine was a gas giant in the Tingel Arm. It was a part of the Corporate Sector and a member world of the Corporate Sector Authority. " .
<https://starwars.com#planet_Reltooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#383ebdee-ece0-4375-afd8-48c58e3eff50> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Reltooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Reltooine> <http://telicent.io/ontology/primaryName> "Reltooine" .
<https://starwars.com#planet_Reltooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Reltooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#383ebdee-ece0-4375-afd8-48c58e3eff50> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Reltooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#383ebdee-ece0-4375-afd8-48c58e3eff50> .

