Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#beea6046-d6c6-4b2a-b0e4-bf37f7f16de7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_PortEvokk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#beea6046-d6c6-4b2a-b0e4-bf37f7f16de7> .
<https://starwars.com#planet_PortEvokk> <http://telicent.io/ontology/primaryName> "Port Evokk" .
<https://starwars.com#planet_PortEvokk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#beea6046-d6c6-4b2a-b0e4-bf37f7f16de7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Port Evokk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PortEvokk> <http://www.w3.org/2000/01/rdf-schema#comment> "Port Evokk was the homeworld of con artist and gambler Tord Gamb. The locals of this planet would use ansmul-hide to make boots and jackets. The bounty hunter Sirenas Firil worked with a small guild out of Port Evokk. " .
<https://starwars.com#planet_PortEvokk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PortEvokk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

