Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#64663b72-6ca1-4868-81cb-84a96f539f2b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SkorII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Airam> .
<https://starwars.com#planet_SkorII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#64663b72-6ca1-4868-81cb-84a96f539f2b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skor II"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_SkorII> <http://www.w3.org/2000/01/rdf-schema#comment> "Skor II was a planet in the Squab system and the homeworld of the Squibs. It was located in the Outer Rim Territories just west of the Rimma Trade Route. The world was small, with a varied terrain and climate that provided it with vast natural resources. The planet's system of government, known as the polyanarchy, was headed by a king. One major population center was Metrobig City, site of the Metrobig Interplanetary Blastport." .
<https://starwars.com#planet_SkorII> <http://telicent.io/ontology/primaryName> "Skor II" .
<https://starwars.com#sector_Airam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Airam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SkorII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#planet_SkorII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#64663b72-6ca1-4868-81cb-84a96f539f2b> .
<https://starwars.com#sector_Airam> <http://telicent.io/ontology/primaryName> "Airam" .

