Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Maldra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c56a6975-ca5f-4e37-902d-004470e16db5> .
<https://starwars.com#sector_Shadola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Maldra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#sector_Shadola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c56a6975-ca5f-4e37-902d-004470e16db5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c56a6975-ca5f-4e37-902d-004470e16db5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Maldra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Maldra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Shadola> .
<https://starwars.com#planet_Maldra> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Maldra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Shadola> <http://telicent.io/ontology/primaryName> "Shadola" .
<https://starwars.com#planet_Maldra> <http://telicent.io/ontology/primaryName> "Maldra" .

