Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Nembus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Nembus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Praadost> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Praadost> <http://telicent.io/ontology/primaryName> "Praadost" .
<https://starwars.com#planet_Praadost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P4> .
<https://starwars.com#726ea8b2-c935-462f-a718-1011a1099d91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Praadost"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Praadost> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#726ea8b2-c935-462f-a718-1011a1099d91> .
<https://starwars.com#sector_Nembus> <http://telicent.io/ontology/primaryName> "Nembus" .
<https://starwars.com#planet_Praadost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#726ea8b2-c935-462f-a718-1011a1099d91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Praadost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nembus> .

