Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tython> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Tython> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#9ac11a72-29ed-4df5-b0d5-939ff8b13a0f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#9ac11a72-29ed-4df5-b0d5-939ff8b13a0f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tython"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tython> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ac11a72-29ed-4df5-b0d5-939ff8b13a0f> .
<https://starwars.com#planet_Tython> <http://www.w3.org/2000/01/rdf-schema#comment> "Tython was a planet located in the galaxy's Deep Core region that played a pivotal role in the history of the Jedi Order. A verdant world that was incredibly rich in the Force, Tython was eventually abandoned when the ever-changing hyperlanes in the region drifted away from the planet and became shrouded in myth. The Martyrium of Frozen Tears was built by Jedi there, and some Jedi scholars made the case that Tython was the site of the Jedi Order's first temple. During the Galactic Civil War, Doctor Chelli Lona Aphra led Darth Vader to Tython's Meridional Ice Cap to mislead him as to the location of the Rebel Alliance's main base, which was actually on the Outer Rim planet Hoth. " .
<https://starwars.com#planet_Tython> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tython> <http://telicent.io/ontology/primaryName> "Tython" .

