Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ghorman> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Ghorman> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Ghorman> <http://www.w3.org/2000/01/rdf-schema#comment> "Ghorman was a planet located in the galaxy's Colonies region along the Rimma Trade Route. At some point during the reign of the Galactic Empire, the Empire carried out one of its worst atrocities on Ghorman, an event which Senator Tynnra Pamlo was exposed to evidence of. " .
<https://starwars.com#planet_Ghorman> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ghorman> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5fc1f919-167e-4c27-8cfe-6960bd18e4bc> .
<https://starwars.com#planet_Ghorman> <http://telicent.io/ontology/primaryName> "Ghorman" .
<https://starwars.com#5fc1f919-167e-4c27-8cfe-6960bd18e4bc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ghorman"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5fc1f919-167e-4c27-8cfe-6960bd18e4bc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

