Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brema> <http://telicent.io/ontology/primaryName> "Brema" .
<https://starwars.com#planet_Bortras> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#15bc67cc-a3d4-4bdc-a417-ba4b061fb2b0> .
<https://starwars.com#15bc67cc-a3d4-4bdc-a417-ba4b061fb2b0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bortras> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bortras> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#planet_Bortras> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brema> .
<https://starwars.com#sector_Brema> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#15bc67cc-a3d4-4bdc-a417-ba4b061fb2b0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bortras"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bortras> <http://www.w3.org/2000/01/rdf-schema#comment> "Bortras was a tranquil world of lush valleys and fertile landscapes in the Brema sector of the Outer Rim Territories. It was known as the home planet of Jedi Master Jorus C'baoth. " .
<https://starwars.com#planet_Bortras> <http://telicent.io/ontology/primaryName> "Bortras" .
<https://starwars.com#sector_Brema> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

