Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ef4a94d8-a98f-4cb8-9eb9-aa6b068acf2c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ef4a94d8-a98f-4cb8-9eb9-aa6b068acf2c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Daupherm"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Daupherm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Daupherm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Daupherm> <http://www.w3.org/2000/01/rdf-schema#comment> "Daupherm was an astronomical object located in the galaxy's Core Worlds. " .
<https://starwars.com#planet_Daupherm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Daupherm> <http://telicent.io/ontology/primaryName> "Daupherm" .
<https://starwars.com#planet_Daupherm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef4a94d8-a98f-4cb8-9eb9-aa6b068acf2c> .

