Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_Q12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_ChromaZed> <http://telicent.io/ontology/primaryName> "Chroma Zed" .
<https://starwars.com#4f5ee590-b51b-46d8-931c-f90e56fc74b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ChromaZed> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q12> .
<https://starwars.com#sector_Maerdocia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#b02a9971-8afc-4e7e-a97f-028f0ca7d2c8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b02a9971-8afc-4e7e-a97f-028f0ca7d2c8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#4f5ee590-b51b-46d8-931c-f90e56fc74b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chroma Zed"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ChromaZed> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f5ee590-b51b-46d8-931c-f90e56fc74b8> .
<https://starwars.com#sector_Maerdocia> <http://telicent.io/ontology/primaryName> "Maerdocia" .
<https://starwars.com#planet_ChromaZed> <http://www.w3.org/2000/01/rdf-schema#comment> "Chroma Zed was a terrestrial planet located in the Maerdocian sector of the galaxy's Mid Rim. Home to the wormlike humanoid Chromans, who lived in moist mountain burrows near water, the planet featured some of the most magnificent amphitheater facilities, including one with twin waterfalls. " .
<https://starwars.com#planet_ChromaZed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_Q12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b02a9971-8afc-4e7e-a97f-028f0ca7d2c8> .
<https://starwars.com#planet_ChromaZed> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maerdocia> .
<https://starwars.com#grid_Q12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Maerdocia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q12> <http://telicent.io/ontology/primaryName> "Q12" .

