Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vardoss> <http://telicent.io/ontology/primaryName> "Vardoss" .
<https://starwars.com#planet_GlomTho> <http://www.w3.org/2000/01/rdf-schema#comment> "Glom Tho was a planet in Hevvrol sector, and the location of the Battle of Glom Tho. " .
<https://starwars.com#planet_GlomTho> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e9d56584-d11d-47fc-b595-0a6465de66d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Glom Tho"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_GlomTho> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I8> .
<https://starwars.com#planet_GlomTho> <http://telicent.io/ontology/primaryName> "Glom Tho" .
<https://starwars.com#planet_GlomTho> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e9d56584-d11d-47fc-b595-0a6465de66d9> .
<https://starwars.com#sector_Vardoss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_GlomTho> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vardoss> .
<https://starwars.com#sector_Vardoss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#e9d56584-d11d-47fc-b595-0a6465de66d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

