Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_U7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_U7> <http://telicent.io/ontology/primaryName> "U7" .
<https://starwars.com#planet_Atollon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0791a007-3340-48b3-8b00-5326c8b05944> .
<https://starwars.com#planet_Atollon> <http://telicent.io/ontology/primaryName> "Atollon" .
<https://starwars.com#0791a007-3340-48b3-8b00-5326c8b05944> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atollon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0791a007-3340-48b3-8b00-5326c8b05944> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_U7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#592e20c3-8e04-404b-831f-d2ee1717fb40> .
<https://starwars.com#592e20c3-8e04-404b-831f-d2ee1717fb40> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Atollon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Atollon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#planet_Atollon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Atollon> <http://www.w3.org/2000/01/rdf-schema#comment> "Desert planet, site of Phoenix Squadron Rebel base. Home of the spider-like hexapods known as the Krykna, and the powerful force-wielder Bendu." .
<https://starwars.com#grid_U7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#592e20c3-8e04-404b-831f-d2ee1717fb40> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

