Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Daalang> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#769d42fc-f865-4310-a9cb-f4e97d9db4ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Daalang> <http://telicent.io/ontology/primaryName> "Daalang" .
<https://starwars.com#769d42fc-f865-4310-a9cb-f4e97d9db4ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Daalang"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Daalang> <http://telicent.io/ontology/primaryName> "Daalang" .
<https://starwars.com#planet_Daalang> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#769d42fc-f865-4310-a9cb-f4e97d9db4ef> .
<https://starwars.com#planet_Daalang> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Daalang> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Daalang> .
<https://starwars.com#planet_Daalang> <http://www.w3.org/2000/01/rdf-schema#comment> "Daalang was an astronomical object located in the Daalang system of the Mid Rim. " .
<https://starwars.com#planet_Daalang> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q12> .
<https://starwars.com#sector_Daalang> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

