Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Maryo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Maryo> <http://www.w3.org/2000/01/rdf-schema#comment> "Maryo was a resort world in the Corporate Sector. It was well known for its bazaars and was often visited by idle wealthy beings. Those who visited the planet also enjoyed hunting the native peckvas and fishing for colossus fish amongst the world's vast seas. " .
<https://starwars.com#33667cd1-bf08-4ae3-b858-1844358bb3c9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Maryo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Maryo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33667cd1-bf08-4ae3-b858-1844358bb3c9> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Maryo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#33667cd1-bf08-4ae3-b858-1844358bb3c9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Maryo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Maryo> <http://telicent.io/ontology/primaryName> "Maryo" .

