Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ZenoxCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_ZenoxCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7fecb67e-abce-45a7-ab22-1c2cc9341337> .
<https://starwars.com#planet_ZenoxCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ZenoxCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#7fecb67e-abce-45a7-ab22-1c2cc9341337> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zenox Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7fecb67e-abce-45a7-ab22-1c2cc9341337> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ZenoxCluster> <http://telicent.io/ontology/primaryName> "Zenox Cluster" .
<https://starwars.com#planet_ZenoxCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .

