Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sarvchi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c5996507-db40-4178-870a-c1aab7e1990f> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Sarvchi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Sarvchi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c5996507-db40-4178-870a-c1aab7e1990f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sarvchi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Sarvchi> <http://telicent.io/ontology/primaryName> "Sarvchi" .
<https://starwars.com#c5996507-db40-4178-870a-c1aab7e1990f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sarvchi> <http://www.w3.org/2000/01/rdf-schema#comment> "Sarvchi was a planet within the territory of the Chiss Ascendancy, located in a star system of the Ascendancy's east and southeast sectors. A number of Chiss migrated to Sarvchi after the climate of the species' homeworld, Csilla, grew less habitable. " .
<https://starwars.com#planet_Sarvchi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F9> .

