Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9c0e642e-99a1-41cd-b239-6eeff6289077> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_G10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9c0e642e-99a1-41cd-b239-6eeff6289077> .
<https://starwars.com#grid_G10> <http://telicent.io/ontology/primaryName> "G10" .
<https://starwars.com#07e280c7-c362-4c2b-8a6f-9b6d557e4e47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Crakull> <http://telicent.io/ontology/primaryName> "Crakull" .
<https://starwars.com#9c0e642e-99a1-41cd-b239-6eeff6289077> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_G10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Crakull> <http://www.w3.org/2000/01/rdf-schema#comment> "Crakull was a planet located within the Crakull system of the Unknown Regions. It was home to the sentient Croke species. The Croke were diminutive in size, and had multiple legs as well as a natural ability to disguise themselves behind illusions. " .
<https://starwars.com#planet_Crakull> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G10> .
<https://starwars.com#planet_Crakull> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#07e280c7-c362-4c2b-8a6f-9b6d557e4e47> .
<https://starwars.com#planet_Crakull> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#grid_G10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Crakull> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#07e280c7-c362-4c2b-8a6f-9b6d557e4e47> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Crakull"^^<http://www.w3.org/2001/XMLSchema#string> .

