Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_HaruunKal> <http://telicent.io/ontology/primaryName> "Haruun Kal" .
<https://starwars.com#planet_HaruunKal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#782e4ab9-4ee7-4bad-a50d-a3bfb887dc5f> .
<https://starwars.com#planet_HaruunKal> <http://www.w3.org/2000/01/rdf-schema#comment> "Haruun Kal was a planet located in the galaxy's Mid Rim, in grid square M-17 on the Standard Galactic Grid, that was the homeworld of Mace Windu, a human Jedi Master and champion of the Jedi Order. During the Clone Wars, it was the site of a battle between the Galactic Republic and Confederacy of Independent Systems. " .
<https://starwars.com#planet_HaruunKal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#782e4ab9-4ee7-4bad-a50d-a3bfb887dc5f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#planet_HaruunKal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#782e4ab9-4ee7-4bad-a50d-a3bfb887dc5f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Haruun Kal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_HaruunKal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .

