Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mullan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Keldrath> .
<https://starwars.com#f22ca03c-9ba2-4763-96e6-8567374b7fec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mullan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Keldrath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mullan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#planet_Mullan> <http://www.w3.org/2000/01/rdf-schema#comment> "Mullan was a terrestrial world located in the Mullan system. It was a part of the Keldrath sector in the Greater Tion historical region, which in turn was situated within the Slice portion of the Outer Rim Territories. The hyperlane known as the Pakuuni Drift connected Mullan to the Gbu system as well as the Brigia system in the neighboring Tion Hegemony sector. " .
<https://starwars.com#f22ca03c-9ba2-4763-96e6-8567374b7fec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mullan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Keldrath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mullan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f22ca03c-9ba2-4763-96e6-8567374b7fec> .
<https://starwars.com#planet_Mullan> <http://telicent.io/ontology/primaryName> "Mullan" .
<https://starwars.com#sector_Keldrath> <http://telicent.io/ontology/primaryName> "Keldrath" .

