Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Febrini> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f51b91f6-1432-4ef2-af4a-abecd42d8fc8> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Febrini> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Febrini> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Febrini> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#f51b91f6-1432-4ef2-af4a-abecd42d8fc8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Febrini> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#f51b91f6-1432-4ef2-af4a-abecd42d8fc8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Febrini"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Febrini> <http://telicent.io/ontology/primaryName> "Febrini" .

