Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e27937ef-d8d7-4789-9fa3-aa445f7f16fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Umgul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mulgard> .
<https://starwars.com#e27937ef-d8d7-4789-9fa3-aa445f7f16fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Umgul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Umgul> <http://telicent.io/ontology/primaryName> "Umgul" .
<https://starwars.com#planet_Umgul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#sector_Mulgard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Mulgard> <http://telicent.io/ontology/primaryName> "Mulgard" .
<https://starwars.com#sector_Mulgard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Umgul> <http://www.w3.org/2000/01/rdf-schema#comment> "Umgul was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Umgul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e27937ef-d8d7-4789-9fa3-aa445f7f16fa> .
<https://starwars.com#planet_Umgul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

