Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Trindello> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bbc9a15f-f266-471b-8ec5-34396ec822db> .
<https://starwars.com#bbc9a15f-f266-471b-8ec5-34396ec822db> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trindello"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#bbc9a15f-f266-471b-8ec5-34396ec822db> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trindello> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Trindello> <http://www.w3.org/2000/01/rdf-schema#comment> "Trindello was an astronomical object located in the Trindello system of the Outer Rim Territories' Moddell sector. " .
<https://starwars.com#planet_Trindello> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_Trindello> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_Trindello> <http://telicent.io/ontology/primaryName> "Trindello" .

