Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Sarka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sarka> <http://www.w3.org/2000/01/rdf-schema#comment> "Sarka was a planet located in the galaxy's Mid Rim, in grid square Q-8 on the Standard Galactic Grid. It was the homeworld of the reptilian Sarkan species. By the time of the Galactic Civil War, Sarka was ruled by Queen Zil. " .
<https://starwars.com#planet_Sarka> <http://telicent.io/ontology/primaryName> "Sarka" .
<https://starwars.com#planet_Sarka> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3db99a9f-2894-414a-a57a-6b5c348c94bb> .
<https://starwars.com#3db99a9f-2894-414a-a57a-6b5c348c94bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sarka"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sarka> <http://telicent.io/ontology/primaryName> "Sarka" .
<https://starwars.com#planet_Sarka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sarka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#sector_Sarka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Sarka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sarka> .
<https://starwars.com#3db99a9f-2894-414a-a57a-6b5c348c94bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

