Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zygia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#bf506ef1-099b-41eb-af79-f807c236b975> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zygia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#bf506ef1-099b-41eb-af79-f807c236b975> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#planet_Zygia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bf506ef1-099b-41eb-af79-f807c236b975> .
<https://starwars.com#planet_Zygia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Zygia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zygia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Manda> .
<https://starwars.com#planet_Zygia> <http://telicent.io/ontology/primaryName> "Zygia" .
<https://starwars.com#sector_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

