Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#beb86943-7887-42be-96c6-a26c2f127866> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nirauan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#beb86943-7887-42be-96c6-a26c2f127866> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_I5> <http://telicent.io/ontology/primaryName> "I5" .
<https://starwars.com#planet_Nirauan> <http://www.w3.org/2000/01/rdf-schema#comment> "Nirauan was an astronomical object located in Wild Space. " .
<https://starwars.com#planet_Nirauan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#beb86943-7887-42be-96c6-a26c2f127866> .
<https://starwars.com#planet_Nirauan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nirauan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I5> .
<https://starwars.com#grid_I5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#75db17b4-85d4-4e1a-ac7a-bee2e3ba41f0> .
<https://starwars.com#grid_I5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Nirauan> <http://telicent.io/ontology/primaryName> "Nirauan" .
<https://starwars.com#75db17b4-85d4-4e1a-ac7a-bee2e3ba41f0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nirauan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#grid_I5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#75db17b4-85d4-4e1a-ac7a-bee2e3ba41f0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

