Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vanquo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#planet_Vanquo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meerian> .
<https://starwars.com#0aae32bc-7135-414b-8b43-2676f5d87780> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vanquo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vanquo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vanquo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0aae32bc-7135-414b-8b43-2676f5d87780> .
<https://starwars.com#planet_Vanquo> <http://www.w3.org/2000/01/rdf-schema#comment> "Vanquo was a mining world in the Outer Rim's Meerian sector that became the site of one of the early battles of the Mandalorian Wars. A mountainous planet, Vanquo was a resource world for the nearby ecumenopolis of Taris and a haven for refugees from the early conquests of the Mandalorian armies. When Taris was threatened by the Mandalorians, Vanquo became part of a Republic security cordon known as the Jebble-Vanquo-Tarnith line. In 3964 BBY, Vanquo was attacked by the Mandalorians in force, commanded by Mandalore the Ultimate and his lieutenant, Cassus Fett. After a heated space battle with Republic Navy forces led by Captain Saul Karath, the Mandalorians conquered Vanquo, giving them a stronghold that they did not relinquish during the war. " .
<https://starwars.com#0aae32bc-7135-414b-8b43-2676f5d87780> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Meerian> <http://telicent.io/ontology/primaryName> "Meerian" .
<https://starwars.com#sector_Meerian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vanquo> <http://telicent.io/ontology/primaryName> "Vanquo" .
<https://starwars.com#sector_Meerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

