Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Demetras> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Phindar> <http://www.w3.org/2000/01/rdf-schema#comment> "Phindar was a planet located in the Phindar system, part of the Mandalore sector in the Outer Rim Territories. The planet, which was home to the Phindian species, was attacked by the Confederacy of Independent Systems during the Clone Wars, and later became affiliated with the Galactic Empire. In orbit over the planet was a tanker facility. About five years after the Clone Wars, the facility was destroyed by a rebel group using the hijacked Imperial starship known as the Carrion Spike. The planet was later host to a battle during the Galactic Civil War. " .
<https://starwars.com#planet_Phindar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Demetras> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Phindar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e241fb71-59ce-468a-8152-89d6a677ce07> .
<https://starwars.com#e241fb71-59ce-468a-8152-89d6a677ce07> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Phindar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_Phindar> <http://telicent.io/ontology/primaryName> "Phindar" .
<https://starwars.com#e241fb71-59ce-468a-8152-89d6a677ce07> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phindar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Demetras> <http://telicent.io/ontology/primaryName> "Demetras" .
<https://starwars.com#planet_Phindar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Demetras> .

