Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PondutStation> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_PondutStation> <http://telicent.io/ontology/primaryName> "Pondut Station" .
<https://starwars.com#2aa58016-9a39-4bb0-8958-8c9d5c483b1d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pondut Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#2aa58016-9a39-4bb0-8958-8c9d5c483b1d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PondutStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2aa58016-9a39-4bb0-8958-8c9d5c483b1d> .
<https://starwars.com#planet_PondutStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PondutStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_PondutStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .

