Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ison> <http://www.w3.org/2000/01/rdf-schema#comment> "Ison was a planet in the Ison system and found on the Ison Trade Corridor. Ison was near pirate-controlled territory, and at the time of the Iron Blockade, it hosted a debris field which inflicted critical damage to a passenger transport attempting to navigate it. The transport drifted into the pirate territory, so the ship's captain requested help from a young smuggler. " .
<https://starwars.com#planet_Ison> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a67714a8-3786-4114-ac9f-e5cb36c240ad> .
<https://starwars.com#planet_Ison> <http://telicent.io/ontology/primaryName> "Ison" .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#a67714a8-3786-4114-ac9f-e5cb36c240ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Ison> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Ison> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a67714a8-3786-4114-ac9f-e5cb36c240ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ison"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ison> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

