Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_RampaMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_RampaMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RampaMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .
<https://starwars.com#30417563-8c24-4845-a42c-5ebb55a3050c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RampaMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#planet_RampaMinor> <http://telicent.io/ontology/primaryName> "Rampa Minor" .
<https://starwars.com#planet_RampaMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30417563-8c24-4845-a42c-5ebb55a3050c> .
<https://starwars.com#30417563-8c24-4845-a42c-5ebb55a3050c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rampa Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .

