Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mandalore> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#909ac904-4983-42fd-9097-f2f5fcf2ac25> .
<https://starwars.com#909ac904-4983-42fd-9097-f2f5fcf2ac25> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mandalore"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mandalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mandalore> <http://telicent.io/ontology/primaryName> "Mandalore" .
<https://starwars.com#sector_Mandalore> <http://telicent.io/ontology/primaryName> "Mandalore" .
<https://starwars.com#planet_Mandalore> <http://www.w3.org/2000/01/rdf-schema#comment> "Outer Rim planet that is the homeworld of the Mandalorians torn by wars between Mandalorians and Jedi and eventually purged by the Empire, scattering the few Mandalorians throughout the galaxy (including Bo-Katan).  Mandalore has one moon, Concordia, which is fully inhabited." .
<https://starwars.com#909ac904-4983-42fd-9097-f2f5fcf2ac25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#sector_Mandalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mandalore> .
<https://starwars.com#sector_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

