Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Japrael> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Japrael> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Dxun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dxun> <http://telicent.io/ontology/primaryName> "Dxun" .
<https://starwars.com#planet_Dxun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#afd98f02-de20-489b-873a-5ea96dd159fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Japrael> <http://telicent.io/ontology/primaryName> "Japrael" .
<https://starwars.com#afd98f02-de20-489b-873a-5ea96dd159fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dxun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dxun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Japrael> .
<https://starwars.com#planet_Dxun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#afd98f02-de20-489b-873a-5ea96dd159fa> .

