Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Denon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_Denon> <http://www.w3.org/2000/01/rdf-schema#comment> "Denon was an ancient, conservative planet located in the Denon system of the galaxy's Inner Rim, at the confluence of the Corellian Run and the Hydian Way. An ecumenopolis world, it had city growth covering the entire surface, similar to Coruscant. It was the homeworld of Imperial General Maximilian Veers and the Rebel pilot Pedrin Gaul. During the Imperial Era, Denon supported the Galactic Emperor Sheev Palpatine. After the signing of the Galactic Concordance, which conditionally allowed the remnants of the Empire to peacefully co-exist with the New Republic, Denon came under control of the Inner systems' Imperial remnant. " .
<https://starwars.com#planet_Denon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Denon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Denon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#753200a6-69ac-4bf5-b1e2-07295db3caa3> .
<https://starwars.com#753200a6-69ac-4bf5-b1e2-07295db3caa3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#753200a6-69ac-4bf5-b1e2-07295db3caa3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Denon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Denon> <http://telicent.io/ontology/primaryName> "Denon" .

