Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cophrigin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#159aac25-b74b-44bc-a66f-54ef2af45a02> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cophrigin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cophrigin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#159aac25-b74b-44bc-a66f-54ef2af45a02> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_Cophrigin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#159aac25-b74b-44bc-a66f-54ef2af45a02> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cophrigin> <http://telicent.io/ontology/primaryName> "Cophrigin" .
<https://starwars.com#planet_Cophrigin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cophrigin> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

