Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ploo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Serroco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ploo> .
<https://starwars.com#planet_Serroco> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#64941c68-2dcd-434c-bedb-bd399e7eae6f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Serroco> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#64941c68-2dcd-434c-bedb-bd399e7eae6f> .
<https://starwars.com#planet_Serroco> <http://telicent.io/ontology/primaryName> "Serroco" .
<https://starwars.com#planet_Serroco> <http://www.w3.org/2000/01/rdf-schema#comment> "Admiral Saul Karath, anticipating a Mandalorian advance on the planet, rounded up a sizable battle group to defend Serroco and placed camps among the Stereb cities. Disdainful of the location of the camps and seeing it as a dishonorable approach, the Mandalorians nuclear-bombed the planet directly when their force arrived at Serroco, destroying the cities entirely. One Republic Navy pilot, Carth Onasi, saved many Stereb lives by calling down false tornado warnings and sending them to their underground shelters, which shielded them from the blasts. Life on Serroco continued on despite the devastation of the planet, and a Republic military presence was reestablished there by the time of the Galactic War several centuries later. By the Imperial Period, a small population of Stereb continued to exist on Serroco. " .
<https://starwars.com#sector_Ploo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#64941c68-2dcd-434c-bedb-bd399e7eae6f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Serroco"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ploo> <http://telicent.io/ontology/primaryName> "Ploo" .
<https://starwars.com#planet_Serroco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .

