Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Khomm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Khomm> <http://www.w3.org/2000/01/rdf-schema#comment> "Khomm was a planet located in the Khomm system of the galaxy's Deep Core. It had many oceans and was the homeworld of the Khommites and the Khommite striders. " .
<https://starwars.com#planet_Khomm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8568c064-7452-4248-a50e-0e74b0859f22> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Khomm"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Khomm> <http://telicent.io/ontology/primaryName> "Khomm" .
<https://starwars.com#8568c064-7452-4248-a50e-0e74b0859f22> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Khomm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8568c064-7452-4248-a50e-0e74b0859f22> .
<https://starwars.com#planet_Khomm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .

