Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Manforgon> <http://www.w3.org/2000/01/rdf-schema#comment> "Manforgon was a planet located in the Mid Rim's Senex sector. It was used for centuries as a penal colony of the Senex-Juvex region. Eventually becoming a lawless world fought over by warlords, Manforgon was turned over to the Galactic Empire by the noble houses of the Senex-Juvex. The Empire used the planet for military purposes, and during the Galactic Civil War, Imperial Customs Officer Tellix served there. " .
<https://starwars.com#69663a39-8885-44b5-b310-29baa9bb503e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Manforgon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#69663a39-8885-44b5-b310-29baa9bb503e> .
<https://starwars.com#planet_Manforgon> <http://telicent.io/ontology/primaryName> "Manforgon" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Manforgon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Manforgon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Manforgon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#69663a39-8885-44b5-b310-29baa9bb503e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Manforgon"^^<http://www.w3.org/2001/XMLSchema#string> .

