Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Hollastin> <http://telicent.io/ontology/primaryName> "Hollastin" .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Hollastin> <http://www.w3.org/2000/01/rdf-schema#comment> "Hollastin was an astronomical object located in the regions known as Hutt Space and the Slice. It was situated in grid square S-12 of the Standard Galactic Grid and was connected by a hyperspace route to the celestial bodies Circumtore and Syvris. " .
<https://starwars.com#planet_Hollastin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#planet_Hollastin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#cbeb2875-ac91-4664-a513-d05e91baa2ba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hollastin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hollastin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cbeb2875-ac91-4664-a513-d05e91baa2ba> .
<https://starwars.com#cbeb2875-ac91-4664-a513-d05e91baa2ba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hollastin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

