Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdVaxal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_OrdVaxal> <http://telicent.io/ontology/primaryName> "Ord Vaxal" .
<https://starwars.com#sector_Callia> <http://telicent.io/ontology/primaryName> "Callia" .
<https://starwars.com#planet_OrdVaxal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdVaxal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Callia> .
<https://starwars.com#9b541cf1-55ea-4d33-8757-3ca150b39222> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Vaxal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdVaxal> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Vaxal was a planet on the outer periphery of the Inner Rim, near Hutt Space. " .
<https://starwars.com#sector_Callia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Callia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_OrdVaxal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9b541cf1-55ea-4d33-8757-3ca150b39222> .
<https://starwars.com#9b541cf1-55ea-4d33-8757-3ca150b39222> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

