Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L15> <http://telicent.io/ontology/primaryName> "L15" .
<https://starwars.com#planet_Borkyne> <http://www.w3.org/2000/01/rdf-schema#comment> "Borkyne was a planet located in the Bes Ber Bikade sector of the Expansion Region. " .
<https://starwars.com#1eac4dca-6609-48b3-a581-56c14f695c53> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Borkyne"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1eac4dca-6609-48b3-a581-56c14f695c53> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Borkyne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#9b8cb206-5b87-41e5-b7ae-b0517317cd2a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Borkyne> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1eac4dca-6609-48b3-a581-56c14f695c53> .
<https://starwars.com#grid_L15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Borkyne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BesBerBikade> .
<https://starwars.com#planet_Borkyne> <http://telicent.io/ontology/primaryName> "Borkyne" .
<https://starwars.com#sector_BesBerBikade> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_BesBerBikade> <http://telicent.io/ontology/primaryName> "Bes Ber Bikade" .
<https://starwars.com#sector_BesBerBikade> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_L15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9b8cb206-5b87-41e5-b7ae-b0517317cd2a> .
<https://starwars.com#planet_Borkyne> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#9b8cb206-5b87-41e5-b7ae-b0517317cd2a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

