Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cuvacia> <http://telicent.io/ontology/primaryName> "Cuvacia" .
<https://starwars.com#planet_Cuvacia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#79575551-ce67-4a13-a66f-3612fee906f7> .
<https://starwars.com#79575551-ce67-4a13-a66f-3612fee906f7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cuvacia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cuvacia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#planet_Cuvacia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Cuvacia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Cuvacia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#79575551-ce67-4a13-a66f-3612fee906f7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

