Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shihon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#bf6cfffe-c3a3-4031-8f76-bed12cafe580> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#bf6cfffe-c3a3-4031-8f76-bed12cafe580> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shihon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shihon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Shihon> <http://www.w3.org/2000/01/rdf-schema#comment> "Shihon was a planet of the Chiss Ascendancy. Home to a number of bird species, Shihon was host to the Grand Migration, a yearly event that saw the confluence of a number of different birds' migratory patterns. Haplif of the Agbui, while traveling with the Chiss Yoponek and Yomie in an attempt to study the Ascendancy prior to orchestrating its fall by sparking a civil war, was forced to remain on Shihon so that Yomie could view the Grand Migration. " .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Shihon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bf6cfffe-c3a3-4031-8f76-bed12cafe580> .
<https://starwars.com#planet_Shihon> <http://telicent.io/ontology/primaryName> "Shihon" .
<https://starwars.com#planet_Shihon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .

