Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kaon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Kaon> <http://telicent.io/ontology/primaryName> "Kaon" .
<https://starwars.com#planet_Kaon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d0a4a3a8-a1a6-415c-b9bb-624535640304> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kaon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#d0a4a3a8-a1a6-415c-b9bb-624535640304> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kaon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kaon> <http://www.w3.org/2000/01/rdf-schema#comment> "Kaon was a planet in the Tion Cluster. It was inhabited by scranges. " .
<https://starwars.com#planet_Kaon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d0a4a3a8-a1a6-415c-b9bb-624535640304> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

