Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#336b1159-8194-40c1-8e51-92915e8ec583> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trinovat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#336b1159-8194-40c1-8e51-92915e8ec583> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trinovat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trinovat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#336b1159-8194-40c1-8e51-92915e8ec583> .
<https://starwars.com#planet_Trinovat> <http://www.w3.org/2000/01/rdf-schema#comment> "Trinovat was a planet located within the Trinovat system of the Outer Rim Territories. It was a verdant world of small farms and mines, homeworld of the Trinovates. " .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Trinovat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trinovat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Trinovat> <http://telicent.io/ontology/primaryName> "Trinovat" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

