Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eibon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .
<https://starwars.com#c3f19182-44ba-4c9b-aae1-ce9db140bcd0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c3f19182-44ba-4c9b-aae1-ce9db140bcd0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eibon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Eibon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c3f19182-44ba-4c9b-aae1-ce9db140bcd0> .
<https://starwars.com#planet_Eibon> <http://telicent.io/ontology/primaryName> "Eibon" .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Eibon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Eibon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Eibon> <http://www.w3.org/2000/01/rdf-schema#comment> "Eibon was a planet located within the Tion Cluster of the Outer Rim Territories. One of the original member-worlds of the Kingdom of Cron, it was absorbed into Xim's empire. A planet known for its proud and independent people, Xer VIII and his son Xim respected Eibon, and one of Xim's flagships was named the Eibon Scimitar. After Xim's empire collapsed, Eibon would continue to thrive as a world, and when it joined the Cronese Mandate after the rise of the Galactic Empire, it was considered one of the most powerful worlds of the Cron region. " .

