Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Allanteen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tynna> .
<https://starwars.com#3ac00e9a-fd8e-4ed5-8171-8fcc95903bad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3ac00e9a-fd8e-4ed5-8171-8fcc95903bad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_O14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_O14> <http://telicent.io/ontology/primaryName> "O14" .
<https://starwars.com#grid_O14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3ac00e9a-fd8e-4ed5-8171-8fcc95903bad> .
<https://starwars.com#planet_Allanteen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#sector_Tynna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Allanteen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Allanteen> <http://telicent.io/ontology/primaryName> "Allanteen" .
<https://starwars.com#ed86987b-e0d3-432b-800f-f9ce42e6f840> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Allanteen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tynna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Tynna> <http://telicent.io/ontology/primaryName> "Tynna" .
<https://starwars.com#planet_Allanteen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ed86987b-e0d3-432b-800f-f9ce42e6f840> .
<https://starwars.com#planet_Allanteen> <http://www.w3.org/2000/01/rdf-schema#comment> "Allanteen VI, also known simply as Allanteen, was an astronomical object in the galaxy's Expansion Region, located on the Corellian Run to the galactic north of Gamor and across the Foless Crossroads from Foless. During the Galactic Civil War it was the site of an Imperial shipyard. Rebel agents located nearby reported to General Airen Cracken about the status of the shipyard. " .
<https://starwars.com#ed86987b-e0d3-432b-800f-f9ce42e6f840> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

