Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#fa22a38a-e6ed-438e-9cf2-9edf2e578d01> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corbos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Corbos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Esstran> <http://telicent.io/ontology/primaryName> "Esstran" .
<https://starwars.com#planet_Corbos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esstran> .
<https://starwars.com#planet_Corbos> <http://www.w3.org/2000/01/rdf-schema#comment> "Corbos was an Outer Rim planet near the Yavin system which was rich in ores. It had 'Black Rain Seasons' which saw whole sections of the planet become uninhabitable due to massive thunderstorms. " .
<https://starwars.com#sector_Esstran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Corbos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fa22a38a-e6ed-438e-9cf2-9edf2e578d01> .
<https://starwars.com#planet_Corbos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#fa22a38a-e6ed-438e-9cf2-9edf2e578d01> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Esstran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Corbos> <http://telicent.io/ontology/primaryName> "Corbos" .

