Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Glithnos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Glithnos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Glithnos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f126624c-1283-4221-853d-3d6fc22bcc66> .
<https://starwars.com#f126624c-1283-4221-853d-3d6fc22bcc66> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Glithnos> <http://telicent.io/ontology/primaryName> "Glithnos" .
<https://starwars.com#f126624c-1283-4221-853d-3d6fc22bcc66> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Glithnos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Glithnos> <http://www.w3.org/2000/01/rdf-schema#comment> "Glithnos was a Galactic Republic planet represented in the Galactic Senate by Jannie Ha'Nook. " .
<https://starwars.com#planet_Glithnos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

