Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bengat> <http://telicent.io/ontology/primaryName> "Bengat" .
<https://starwars.com#planet_Bengat> <http://www.w3.org/2000/01/rdf-schema#comment> "Bengat was an oceanic world where the Aruzan female Manaroo once danced in competitions. She also rafted the planet's stormy waters in between her participation in these events. " .
<https://starwars.com#planet_Bengat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Bengat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0b1675ba-66e5-48a3-87a4-f4882e4b177f> .
<https://starwars.com#planet_Bengat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#0b1675ba-66e5-48a3-87a4-f4882e4b177f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0b1675ba-66e5-48a3-87a4-f4882e4b177f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bengat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bengat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

