Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Talcharaim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Talcharaim> <http://telicent.io/ontology/primaryName> "Talcharaim" .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Talcharaim> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#60d3d280-4253-4f9f-8f00-8b7299f85b23> .
<https://starwars.com#60d3d280-4253-4f9f-8f00-8b7299f85b23> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Talcharaim"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#60d3d280-4253-4f9f-8f00-8b7299f85b23> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Talcharaim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Talcharaim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Talcharaim> <http://www.w3.org/2000/01/rdf-schema#comment> "Talcharaim could refer to one of the following: " .

