Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Alee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#31c48605-3d21-4edf-8c3e-69e54e3ddfb8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5881b1c9-5f23-49dd-aadb-7d2d71dc9c13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Alee> <http://telicent.io/ontology/primaryName> "Alee" .
<https://starwars.com#planet_Alee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R9> .
<https://starwars.com#planet_Alee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#grid_R9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#31c48605-3d21-4edf-8c3e-69e54e3ddfb8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5881b1c9-5f23-49dd-aadb-7d2d71dc9c13> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#grid_R9> <http://telicent.io/ontology/primaryName> "R9" .
<https://starwars.com#planet_Alee> <http://www.w3.org/2000/01/rdf-schema#comment> "Alee was a primarily agricultural world located in the Alee system, a part of Hutt Space in the Slice. It was situated on the Ilosian Spur hyperlane, which connected it to the Tal Nami system as well as the Boz Pity system in the Mid Rim. " .
<https://starwars.com#grid_R9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5881b1c9-5f23-49dd-aadb-7d2d71dc9c13> .
<https://starwars.com#planet_Alee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31c48605-3d21-4edf-8c3e-69e54e3ddfb8> .
<https://starwars.com#grid_R9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

