Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dahrtag> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e0460583-f269-4c59-b368-2d102a46f88c> .
<https://starwars.com#planet_Dahrtag> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e0460583-f269-4c59-b368-2d102a46f88c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dahrtag"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dahrtag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#e0460583-f269-4c59-b368-2d102a46f88c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dahrtag> <http://telicent.io/ontology/primaryName> "Dahrtag" .
<https://starwars.com#planet_Dahrtag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#planet_Dahrtag> <http://www.w3.org/2000/01/rdf-schema#comment> "Necropolis was a tombworld located on the Giju Run of the Core Worlds. Serving as a burial place for beings from all over the Core, it was also the home of boneworms and cryptberries. " .

