Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dd10d491-8bc2-4da0-8d00-e3ed2249b643> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdRadama> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd10d491-8bc2-4da0-8d00-e3ed2249b643> .
<https://starwars.com#sector_Esstran> <http://telicent.io/ontology/primaryName> "Esstran" .
<https://starwars.com#planet_OrdRadama> <http://telicent.io/ontology/primaryName> "Ord Radama" .
<https://starwars.com#planet_OrdRadama> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Radama was an astronomical object located in the galaxy's Outer Rim Territories that was the homeworld of the Devlikk podracer Wan Sandage. " .
<https://starwars.com#planet_OrdRadama> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Esstran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdRadama> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#sector_Esstran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdRadama> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esstran> .
<https://starwars.com#dd10d491-8bc2-4da0-8d00-e3ed2249b643> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Radama"^^<http://www.w3.org/2001/XMLSchema#string> .

