Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mika> <http://www.w3.org/2000/01/rdf-schema#comment> "Mika might refer to: " .
<https://starwars.com#planet_Mika> <http://telicent.io/ontology/primaryName> "Mika" .
<https://starwars.com#planet_Mika> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#27989cac-ebde-49f6-a618-3b653057369b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mika> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mika> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#27989cac-ebde-49f6-a618-3b653057369b> .
<https://starwars.com#planet_Mika> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#27989cac-ebde-49f6-a618-3b653057369b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mika"^^<http://www.w3.org/2001/XMLSchema#string> .

