Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tisht> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tisht> <http://www.w3.org/2000/01/rdf-schema#comment> "Tisht was a planet that was located within the Tisht system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet lay on the hyperlane called The Dead Road, which connected it to the worlds of M'Hanna and Saqqar. " .
<https://starwars.com#b4c058c9-c576-4e4c-ba9a-ff3501d9a3e9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tisht"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Tisht> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tisht> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Tisht> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4c058c9-c576-4e4c-ba9a-ff3501d9a3e9> .
<https://starwars.com#planet_Tisht> <http://telicent.io/ontology/primaryName> "Tisht" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#b4c058c9-c576-4e4c-ba9a-ff3501d9a3e9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

