Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chazwa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6b4ddc8-4a12-41fc-88f1-568401338c61> .
<https://starwars.com#planet_Chazwa> <http://telicent.io/ontology/primaryName> "Chazwa" .
<https://starwars.com#sector_Orus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chazwa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Orus> .
<https://starwars.com#planet_Chazwa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#e6b4ddc8-4a12-41fc-88f1-568401338c61> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chazwa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Orus> <http://telicent.io/ontology/primaryName> "Orus" .
<https://starwars.com#planet_Chazwa> <http://www.w3.org/2000/01/rdf-schema#comment> "Chazwa was an astronomical object located in the galaxy's Inner Rim, along the Perlemian Trade Route. After the Battle of Endor, remnants of the Galactic Empire had a presence on Chazwa, and the New Republic's Meteor Squadron were sent on a scouting mission to Chazwa. " .
<https://starwars.com#sector_Orus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Chazwa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e6b4ddc8-4a12-41fc-88f1-568401338c61> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

