Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kurost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#110e00ab-e795-4a1b-b461-0b83d576c5f0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sev Tok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_SevTok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kurost> <http://telicent.io/ontology/primaryName> "Kurost" .
<https://starwars.com#planet_SevTok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q11> .
<https://starwars.com#planet_SevTok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#110e00ab-e795-4a1b-b461-0b83d576c5f0> .
<https://starwars.com#110e00ab-e795-4a1b-b461-0b83d576c5f0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SevTok> <http://telicent.io/ontology/primaryName> "Sev Tok" .
<https://starwars.com#planet_SevTok> <http://www.w3.org/2000/01/rdf-schema#comment> "Sev Tok was a planet in the Mid Rim's Kurost sector. " .
<https://starwars.com#sector_Kurost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SevTok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kurost> .

