Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ComkinV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ComkinV> <http://telicent.io/ontology/primaryName> "Comkin V" .
<https://starwars.com#a8a110b3-51b6-4f14-83aa-4a7e18c039a9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Comkin V"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Nouane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Nouane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_ComkinV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nouane> .
<https://starwars.com#planet_ComkinV> <http://www.w3.org/2000/01/rdf-schema#comment> "Comkin V was a planet in the Inner Rim. " .
<https://starwars.com#planet_ComkinV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#a8a110b3-51b6-4f14-83aa-4a7e18c039a9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ComkinV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a8a110b3-51b6-4f14-83aa-4a7e18c039a9> .
<https://starwars.com#sector_Nouane> <http://telicent.io/ontology/primaryName> "Nouane" .

