Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3f44866f-cdd8-4bff-b34f-22e48aa67eb0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rondai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rondai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#planet_Rondai> <http://telicent.io/ontology/primaryName> "Rondai" .
<https://starwars.com#3f44866f-cdd8-4bff-b34f-22e48aa67eb0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rondai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Rondai> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Rondai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3f44866f-cdd8-4bff-b34f-22e48aa67eb0> .
<https://starwars.com#planet_Rondai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

