Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tasariq> <http://www.w3.org/2000/01/rdf-schema#comment> "Tasariq was a planet in the Inner Rim. It was a barren world with atmosphere-filled craters and tasar crystals. Tasariq joined the Republic 22 BBY. It was later part of the Galactic Empire. Barimoq Industries, a Tasari-run corporation that produced a variety of personal projectile weapons, was based on Tasariq. " .
<https://starwars.com#planet_Tasariq> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4dd541a4-6e19-419b-9e1b-e1cb279f4a94> .
<https://starwars.com#4dd541a4-6e19-419b-9e1b-e1cb279f4a94> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tasariq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Tasariq> <http://telicent.io/ontology/primaryName> "Tasariq" .
<https://starwars.com#planet_Tasariq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J14> .
<https://starwars.com#planet_Tasariq> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4dd541a4-6e19-419b-9e1b-e1cb279f4a94> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tasariq"^^<http://www.w3.org/2001/XMLSchema#string> .

