Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MelneasWorld> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_MelneasWorld> <http://www.w3.org/2000/01/rdf-schema#comment> "Melnea's World was a murky, swampy planet located in the Melnea's World system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. Melnea's World was located on the Cranan-Excarga Route. " .
<https://starwars.com#planet_MelneasWorld> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#08e2ad06-dc49-4bfb-8a52-ef273a0211d7> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_MelneasWorld> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_MelneasWorld> <http://telicent.io/ontology/primaryName> "Melnea's World" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#08e2ad06-dc49-4bfb-8a52-ef273a0211d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#08e2ad06-dc49-4bfb-8a52-ef273a0211d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Melnea's World"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_MelneasWorld> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

