Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Delphon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d79260db-a9c3-4c1b-a56e-a1da23767d33> .
<https://starwars.com#d79260db-a9c3-4c1b-a56e-a1da23767d33> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Delphon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Delphon> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#planet_Delphon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#d79260db-a9c3-4c1b-a56e-a1da23767d33> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Delphon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Delphon> <http://telicent.io/ontology/primaryName> "Delphon" .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Delphon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

