Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nedij> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4d56b2cc-6d38-4b9e-8b9f-8d9de84e23de> .
<https://starwars.com#planet_Nedij> <http://www.w3.org/2000/01/rdf-schema#comment> "Nedij was a planet in the Outer Rim on the eastern spiral arm of the galaxy. It had thin air in which its native species evolved. Natural terrain included snowy mountains which the Nediji preferred, and lowlands. The planet was inhabited by a species of humanoids which served as prey for the Nediji. The Black Sun operative Kaird hailed from this planet. " .
<https://starwars.com#planet_Nedij> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Merel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nedij> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Merel> .
<https://starwars.com#planet_Nedij> <http://telicent.io/ontology/primaryName> "Nedij" .
<https://starwars.com#sector_Merel> <http://telicent.io/ontology/primaryName> "Merel" .
<https://starwars.com#4d56b2cc-6d38-4b9e-8b9f-8d9de84e23de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nedij"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nedij> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q19> .
<https://starwars.com#4d56b2cc-6d38-4b9e-8b9f-8d9de84e23de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Merel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

