Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tharin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Dennogra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5b881f44-2175-444d-85e5-b81f5d7635c7> .
<https://starwars.com#planet_Dennogra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#sector_Tharin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5b881f44-2175-444d-85e5-b81f5d7635c7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dennogra> <http://telicent.io/ontology/primaryName> "Dennogra" .
<https://starwars.com#planet_Dennogra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tharin> .
<https://starwars.com#planet_Dennogra> <http://www.w3.org/2000/01/rdf-schema#comment> "Dennogra was an astronomical object in the galaxy's Outer Rim Territories, connected via hyperspace route to Junkfort Station and Taskeed. " .
<https://starwars.com#sector_Tharin> <http://telicent.io/ontology/primaryName> "Tharin" .
<https://starwars.com#planet_Dennogra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5b881f44-2175-444d-85e5-b81f5d7635c7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dennogra"^^<http://www.w3.org/2001/XMLSchema#string> .

