Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mantooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Despite the Imperial victory, Mantooine would soon serve as an Alliance to Restore the Republic regional headquarters and operations sector during the early rebellion against the Galactic Empire. Mantooine was included in a map of the galaxy that listed safe worlds, starfighter hubs at level five or higher, regional headquarters and operations sectors, and deep space caches. The map was then incorporated into The Rebel Files. During the early rebellion, the Alliance to Restore the Republic used the UT-60D U-wing starfighter/support craft as a troop transport on Mantooine, which was noted in a report from General Antoc Merrick to Commander-in-Chief Mon Mothma. That report would also be included in The Rebel Files. " .
<https://starwars.com#planet_Mantooine> <http://telicent.io/ontology/primaryName> "Mantooine" .
<https://starwars.com#833053e8-f56d-4601-94d3-1599c26ad2a0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mantooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mantooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#833053e8-f56d-4601-94d3-1599c26ad2a0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .
<https://starwars.com#planet_Mantooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#833053e8-f56d-4601-94d3-1599c26ad2a0> .
<https://starwars.com#planet_Mantooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mantooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .

