Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rugosa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d052e14-7dec-4011-a546-26ddb5411b61> .
<https://starwars.com#sector_Sanbra> <http://telicent.io/ontology/primaryName> "Sanbra" .
<https://starwars.com#planet_Rugosa> <http://telicent.io/ontology/primaryName> "Rugosa" .
<https://starwars.com#planet_Rugosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sanbra> .
<https://starwars.com#planet_Rugosa> <http://www.w3.org/2000/01/rdf-schema#comment> "A moon that consists of giant coral reefs. Yoda meets King Katuunko of the Toydarians here after being tested in battle by the Separatist Droid Army, during the early days of the Clone Wars. It is here where King Katuunko pledges Toydaria's allegiance to the Galactic Republic." .
<https://starwars.com#planet_Rugosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#5d052e14-7dec-4011-a546-26ddb5411b61> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rugosa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sanbra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5d052e14-7dec-4011-a546-26ddb5411b61> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rugosa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sanbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

