Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vuma> <http://telicent.io/ontology/primaryName> "Vuma" .
<https://starwars.com#planet_Vuma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Vuma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Vuma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d4f4437e-e320-4c17-8b03-10a6df5fe734> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vuma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vuma> <http://www.w3.org/2000/01/rdf-schema#comment> "Vuma was an entity associated with the group known as the Vuman. Upon sighting his old associate Velko Jahen aboard the Starlight Beacon space station, the Vuman Vane Sarpo invoked Vuma's name in surprise. " .
<https://starwars.com#planet_Vuma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d4f4437e-e320-4c17-8b03-10a6df5fe734> .
<https://starwars.com#d4f4437e-e320-4c17-8b03-10a6df5fe734> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

