Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sakiya> <http://www.w3.org/2000/01/rdf-schema#comment> "Sakiya, also known as Saki, was a planet located in the Bootana Hutta region of Hutt Space. It was the tropical and heavily industrialized homeworld of the Sakiyan species. " .
<https://starwars.com#d0205439-6057-4448-a507-1e546037d50a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sakiya> <http://telicent.io/ontology/primaryName> "Sakiya" .
<https://starwars.com#planet_Sakiya> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sakiya> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#d0205439-6057-4448-a507-1e546037d50a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sakiya"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sakiya> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Sakiya> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d0205439-6057-4448-a507-1e546037d50a> .

