Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Brentaal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Brentaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Brentaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#c70291a1-266c-4970-a653-ee614d093261> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Brentaal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Brentaal> <http://www.w3.org/2000/01/rdf-schema#comment> "Brentaal" .
<https://starwars.com#planet_Brentaal> <http://telicent.io/ontology/primaryName> "Brentaal" .
<https://starwars.com#planet_Brentaal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c70291a1-266c-4970-a653-ee614d093261> .
<https://starwars.com#c70291a1-266c-4970-a653-ee614d093261> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

