Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c13c2971-428b-48ac-a022-a706d68d4555> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vontor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vontor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Vontor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c13c2971-428b-48ac-a022-a706d68d4555> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vontor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vontor> <http://www.w3.org/2000/01/rdf-schema#comment> "Vontor was an entity associated with the event known as the Vontor's Eve and with a derelict treasure ship Graceful Promising. " .
<https://starwars.com#planet_Vontor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#c13c2971-428b-48ac-a022-a706d68d4555> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vontor> <http://telicent.io/ontology/primaryName> "Vontor" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

