Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Varadan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Varadan> <http://telicent.io/ontology/primaryName> "Varadan" .
<https://starwars.com#planet_Varadan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f3de7a55-946a-41ef-8834-31e99ea9bbdd> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Varadan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#f3de7a55-946a-41ef-8834-31e99ea9bbdd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Varadan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f3de7a55-946a-41ef-8834-31e99ea9bbdd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Varadan> <http://www.w3.org/2000/01/rdf-schema#comment> "Varadan was a desert mining world located in the Senex sector of the Mid Rim. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Varadan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

