Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0d8a99de-d7ce-4ca3-8aff-450814016659> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tinnel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tinnel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tinnel> <http://telicent.io/ontology/primaryName> "Tinnel" .
<https://starwars.com#planet_Tinnel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Tinnel> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Tinnel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0d8a99de-d7ce-4ca3-8aff-450814016659> .
<https://starwars.com#0d8a99de-d7ce-4ca3-8aff-450814016659> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tinnel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .

