Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ukatis> <http://www.w3.org/2000/01/rdf-schema#comment> "Ukatis was the ruling planet of the Ukatis system of the Inner Rim. " .
<https://starwars.com#planet_Ukatis> <http://telicent.io/ontology/primaryName> "Ukatis" .
<https://starwars.com#147e0d20-8a31-4a20-861c-416b1c798bb4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ukatis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ukatis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#planet_Ukatis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#147e0d20-8a31-4a20-861c-416b1c798bb4> .
<https://starwars.com#147e0d20-8a31-4a20-861c-416b1c798bb4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ukatis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ukatis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

