Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ehosiq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegions> .
<https://starwars.com#planet_Kiros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ehosiq> .
<https://starwars.com#c8fd82a7-06b4-4ef7-aa3c-b4af26c499f3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kiros> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#region_ExpansionRegions> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_Kiros> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c8fd82a7-06b4-4ef7-aa3c-b4af26c499f3> .
<https://starwars.com#planet_Kiros> <http://telicent.io/ontology/primaryName> "Kiros" .
<https://starwars.com#c8fd82a7-06b4-4ef7-aa3c-b4af26c499f3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kiros"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kiros> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#region_ExpansionRegions> <http://telicent.io/ontology/primaryName> "Expansion Regions" .
<https://starwars.com#planet_Kiros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#sector_Ehosiq> <http://telicent.io/ontology/primaryName> "Ehosiq" .
<https://starwars.com#region_ExpansionRegions> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Ehosiq> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

