Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tharin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Nimat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Tharin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nimat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#planet_Nimat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tharin> .
<https://starwars.com#planet_Nimat> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#fc755b8e-9201-4376-8092-e696af930531> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#fc755b8e-9201-4376-8092-e696af930531> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nimat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tharin> <http://telicent.io/ontology/primaryName> "Tharin" .
<https://starwars.com#planet_Nimat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fc755b8e-9201-4376-8092-e696af930531> .
<https://starwars.com#planet_Nimat> <http://telicent.io/ontology/primaryName> "Nimat" .

