Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Murgo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Murgo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7499fffe-e374-4b79-ad57-b7dac8d756b4> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Murgo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#planet_Murgo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Murgo> <http://telicent.io/ontology/primaryName> "Murgo" .
<https://starwars.com#planet_Murgo> <http://www.w3.org/2000/01/rdf-schema#comment> "Murgo was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#7499fffe-e374-4b79-ad57-b7dac8d756b4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Murgo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7499fffe-e374-4b79-ad57-b7dac8d756b4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

