Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Illoud> <http://telicent.io/ontology/primaryName> "Illoud" .
<https://starwars.com#planet_Illoud> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hali> .
<https://starwars.com#sector_Hali> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Hali> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Illoud> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#674cb5a0-e252-468a-b48a-9ad1e28abc50> .
<https://starwars.com#planet_Illoud> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Illoud> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#674cb5a0-e252-468a-b48a-9ad1e28abc50> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Illoud"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#674cb5a0-e252-468a-b48a-9ad1e28abc50> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Hali> <http://telicent.io/ontology/primaryName> "Hali" .
<https://starwars.com#planet_Illoud> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .

