Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Saijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K20> .
<https://starwars.com#planet_Saijo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#db39ee68-3615-40e7-ba8f-034f2a840259> .
<https://starwars.com#planet_Saijo> <http://www.w3.org/2000/01/rdf-schema#comment> "Saijo was an astronomical object located in the Outer Rim Territories of the galaxy, positioned at the coordinates K-20 on the Standard Galactic Grid. " .
<https://starwars.com#db39ee68-3615-40e7-ba8f-034f2a840259> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Saijo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Saijo> <http://telicent.io/ontology/primaryName> "Saijo" .
<https://starwars.com#planet_Saijo> <http://telicent.io/ontology/primaryName> "Saijo" .
<https://starwars.com#db39ee68-3615-40e7-ba8f-034f2a840259> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Saijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Saijo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Saijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Saijo> .
<https://starwars.com#sector_Saijo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

