Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Endex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Endex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#df9409e3-bec7-44a0-8713-228fc3997b12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Endex> <http://telicent.io/ontology/primaryName> "Endex" .
<https://starwars.com#sector_Velcar> <http://telicent.io/ontology/primaryName> "Velcar" .
<https://starwars.com#df9409e3-bec7-44a0-8713-228fc3997b12> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Endex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Endex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Velcar> .
<https://starwars.com#planet_Endex> <http://www.w3.org/2000/01/rdf-schema#comment> "Endex was a world of rocky canyons. It was the Entymal homeworld. During the time of the Old Republic, the Entymals were renowned as excellent pilots across the galaxy. For centuries, many pilots were trained in the canyons which left a lot of wreckage behind. " .
<https://starwars.com#sector_Velcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Endex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df9409e3-bec7-44a0-8713-228fc3997b12> .
<https://starwars.com#sector_Velcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

