Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zerm> <http://telicent.io/ontology/primaryName> "Zerm" .
<https://starwars.com#d30f0910-3bc3-420d-9b8b-4041f00184eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zerm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#d30f0910-3bc3-420d-9b8b-4041f00184eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zerm"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zerm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Zerm> <http://www.w3.org/2000/01/rdf-schema#comment> "Zerm was an astronomical object located in the Kessel sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Zerm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zerm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d30f0910-3bc3-420d-9b8b-4041f00184eb> .

