Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Instrop> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Shinbone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shinbone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Instrop> .
<https://starwars.com#planet_Shinbone> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d92f4fb0-bb22-447e-a51e-19d98c1923d9> .
<https://starwars.com#planet_Shinbone> <http://telicent.io/ontology/primaryName> "Shinbone" .
<https://starwars.com#planet_Shinbone> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_Instrop> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d92f4fb0-bb22-447e-a51e-19d98c1923d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Instrop> <http://telicent.io/ontology/primaryName> "Instrop" .
<https://starwars.com#d92f4fb0-bb22-447e-a51e-19d98c1923d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shinbone"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shinbone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T17> .

