Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#690a310e-f34c-4e8d-8952-e4992b737f6d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Itani"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#690a310e-f34c-4e8d-8952-e4992b737f6d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Itani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Itani> <http://www.w3.org/2000/01/rdf-schema#comment> "The Itani system was a star system located in the Itani Nebula of the Inner Rim." .
<https://starwars.com#planet_Itani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Itani> <http://telicent.io/ontology/primaryName> "Itani" .
<https://starwars.com#planet_Itani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .
<https://starwars.com#planet_Itani> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#690a310e-f34c-4e8d-8952-e4992b737f6d> .

