Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bacrana> <http://www.w3.org/2000/01/rdf-schema#comment> "Bacrana was an astronomical object located in the galaxy's Expansion Region along the Corellian Run. " .
<https://starwars.com#sector_Brak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Bacrana> <http://telicent.io/ontology/primaryName> "Bacrana" .
<https://starwars.com#ee58e793-01c2-49c4-9a97-c0488a8caebb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Brak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ee58e793-01c2-49c4-9a97-c0488a8caebb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bacrana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bacrana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ee58e793-01c2-49c4-9a97-c0488a8caebb> .
<https://starwars.com#sector_Brak> <http://telicent.io/ontology/primaryName> "Brak" .
<https://starwars.com#planet_Bacrana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brak> .
<https://starwars.com#planet_Bacrana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bacrana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .

