Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#d5cd0f9a-a56d-4a0b-852e-870b11af9032> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yhifar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d5cd0f9a-a56d-4a0b-852e-870b11af9032> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yhifar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yhifar> <http://www.w3.org/2000/01/rdf-schema#comment> "Yhifar was a Mid Rim gas giant located in the Juvex sector. It was the site of the Gas Vortex, the eye of an immense, millennia-old storm. The Gas Vortex provided living beings with tolerable atmospheric pressure and breathable air, allowing the construction of settlements in that area. Reckless gas miners dived into the high-pressure depths of Yhifar in armored submersibles tethered to mining platforms in the Gas Vortex. " .
<https://starwars.com#planet_Yhifar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Yhifar> <http://telicent.io/ontology/primaryName> "Yhifar" .
<https://starwars.com#planet_Yhifar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d5cd0f9a-a56d-4a0b-852e-870b11af9032> .
<https://starwars.com#planet_Yhifar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

