Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c897a1b8-e425-416c-ab7d-0f5701babb43> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#69cf7508-d3c7-46d5-ae81-84b608d50e84> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lasan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#grid_P20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#69cf7508-d3c7-46d5-ae81-84b608d50e84> .
<https://starwars.com#c897a1b8-e425-416c-ab7d-0f5701babb43> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lasan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lasan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c897a1b8-e425-416c-ab7d-0f5701babb43> .
<https://starwars.com#69cf7508-d3c7-46d5-ae81-84b608d50e84> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Lasan> <http://www.w3.org/2000/01/rdf-schema#comment> "Lasan was a planet located in the galaxy's Outer Rim Territories that was inhabited by the Lasat species after leaving their homeworld of Lira San. The planet was protected by the Lasan High Honor Guard. During the reign of the Galactic Empire, Imperial forces devastated Lasan and killed most of its population, though many Lasat still remained on Lira San. " .
<https://starwars.com#planet_Lasan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lasan> <http://telicent.io/ontology/primaryName> "Lasan" .
<https://starwars.com#planet_Lasan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P20> .
<https://starwars.com#grid_P20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_P20> <http://telicent.io/ontology/primaryName> "P20" .
<https://starwars.com#grid_P20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

