Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Corulag> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Corulag> <http://telicent.io/ontology/primaryName> "Corulag" .
<https://starwars.com#planet_Corulag> <http://www.w3.org/2000/01/rdf-schema#comment> "Corulag was a Core Worlds planet. It was the site of an Imperial Academy, the Corulag Military Academy. " .
<https://starwars.com#4b05b5e8-9e9a-4f03-875e-d1e17a55e0f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corulag"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Corulag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Corulag> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4b05b5e8-9e9a-4f03-875e-d1e17a55e0f9> .
<https://starwars.com#4b05b5e8-9e9a-4f03-875e-d1e17a55e0f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Corulag> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

