Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gannaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gannaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H15> .
<https://starwars.com#sector_Trilon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gannaria> <http://www.w3.org/2000/01/rdf-schema#comment> "Gannaria was a terrestrial planet located in the Trilon sector, a part of the Outer Rim Territories. Situated in grid square H-15 of the Standard Galactic Grid, it was linked by hyperspace routes to the Batuu and Zaddja systems and shared its name with the route known as the Gannarian Run. " .
<https://starwars.com#planet_Gannaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trilon> .
<https://starwars.com#planet_Gannaria> <http://telicent.io/ontology/primaryName> "Gannaria" .
<https://starwars.com#f69c6f9f-0bb0-48d7-a7ef-9149343931f7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f69c6f9f-0bb0-48d7-a7ef-9149343931f7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gannaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Trilon> <http://telicent.io/ontology/primaryName> "Trilon" .
<https://starwars.com#planet_Gannaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f69c6f9f-0bb0-48d7-a7ef-9149343931f7> .
<https://starwars.com#sector_Trilon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

