Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Epica> <http://www.w3.org/2000/01/rdf-schema#comment> "Epica was a naturally beautiful world with forested hills, mountain valleys, and cold water seas. During the Yuuzhan Vong War, the Hydians Auction House was relocated to Epica. At the time it was believed that Epica was too remote to attract the attention of the Yuuzhan Vong. At the wars end, many of the beings that had relocated the Hydians decided to remain on world, building rich palaces and mansion on the world. In time the planet's primary city had been transformed into an area of sophistication for the wealthy and privileged. The new level of decadence forced the native populace of Humans, Bothans, Duros, and Bimms to labor in order to satisfy the needs of the wealthy who co-opted their home. " .
<https://starwars.com#debf2030-39bb-4899-a3c1-050e1558bb29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#debf2030-39bb-4899-a3c1-050e1558bb29> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Epica"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Epica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_BesBerBikade> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Epica> <http://telicent.io/ontology/primaryName> "Epica" .
<https://starwars.com#sector_BesBerBikade> <http://telicent.io/ontology/primaryName> "Bes Ber Bikade" .
<https://starwars.com#sector_BesBerBikade> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Epica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#planet_Epica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BesBerBikade> .
<https://starwars.com#planet_Epica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#debf2030-39bb-4899-a3c1-050e1558bb29> .

