Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d5452db1-83e3-40b7-b567-4012100fe4b0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vultar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vultar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d5452db1-83e3-40b7-b567-4012100fe4b0> .
<https://starwars.com#planet_Vultar> <http://www.w3.org/2000/01/rdf-schema#comment> "Vultar was a planet located in the Vultar system, a part of the Arrowhead region in the Slice portion of the Core Worlds. Evidence pointed to the Celestials, an advanced species that disappeared from the galaxy in 30,000 BBY, having used a set of devices, including the gravity-manipulation machine known as the Cosmic Turbine, to construct the Vultar system, including its planets. " .
<https://starwars.com#planet_Vultar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vultar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Vultar> <http://telicent.io/ontology/primaryName> "Vultar" .
<https://starwars.com#planet_Vultar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#d5452db1-83e3-40b7-b567-4012100fe4b0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

