Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rendili> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rendili> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#ce2d5f57-e74c-465f-a9e6-cec72038bf85> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ce2d5f57-e74c-465f-a9e6-cec72038bf85> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rendili"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rendili> <http://telicent.io/ontology/primaryName> "Rendili" .
<https://starwars.com#planet_Rendili> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce2d5f57-e74c-465f-a9e6-cec72038bf85> .
<https://starwars.com#planet_Rendili> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Rendili> <http://www.w3.org/2000/01/rdf-schema#comment> "Rendili was an ancient, conservative planet located in the galaxy's Core Worlds. Arch-Provost was a governing position on the planet. " .

