Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shador> <http://telicent.io/ontology/primaryName> "Shador" .
<https://starwars.com#planet_Shador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#9474534d-0cbb-446f-8f4f-2d1b8e9b6abe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shador> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9474534d-0cbb-446f-8f4f-2d1b8e9b6abe> .
<https://starwars.com#planet_Shador> <http://www.w3.org/2000/01/rdf-schema#comment> "Shador was a Mid Rim planet on the Gamor Run. It was the Shadorian homeworld and had such a foul atmosphere, that it was painful for Humans to breathe. The planet was dominated by swamps, and the various towns were built on pylons rising above the wet terrain. " .
<https://starwars.com#sector_Maerdocia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Maerdocia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Maerdocia> <http://telicent.io/ontology/primaryName> "Maerdocia" .
<https://starwars.com#9474534d-0cbb-446f-8f4f-2d1b8e9b6abe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shador"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shador> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maerdocia> .

