Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Syned> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#910d5ee3-7aa4-48fb-bc85-423bdf2d380d> .
<https://starwars.com#910d5ee3-7aa4-48fb-bc85-423bdf2d380d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#910d5ee3-7aa4-48fb-bc85-423bdf2d380d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Syned"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Garis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Syned> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Syned> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Garis> .
<https://starwars.com#sector_Garis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Syned> <http://telicent.io/ontology/primaryName> "Syned" .
<https://starwars.com#sector_Garis> <http://telicent.io/ontology/primaryName> "Garis" .
<https://starwars.com#planet_Syned> <http://www.w3.org/2000/01/rdf-schema#comment> "Syned was an ice-covered planet in the Syned system, in Grumani sector. During the Republic Dark Age, Syned was under the control of Sith Lord Chagras, but after his death, it fell into the hands of his daughter Arkadia Calimondra. " .
<https://starwars.com#planet_Syned> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .

