Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Spira> <http://www.w3.org/2000/01/rdf-schema#comment> "Spira was a tropical planet known for its golden beaches. During the High Republic Era, it was a key member of the Galactic Republic and received a sky-island at the Republic Fair on Valo. The Resistance pilot Poe Dameron once took a vacation there, and was reminded of it when tasting a drink at an auction hosted by Nifera Shu on Corellia. " .
<https://starwars.com#planet_Spira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#cae23c30-5c6f-49a4-ab8f-760e69078d29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Spira> <http://telicent.io/ontology/primaryName> "Spira" .
<https://starwars.com#planet_Spira> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cae23c30-5c6f-49a4-ab8f-760e69078d29> .
<https://starwars.com#planet_Spira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#cae23c30-5c6f-49a4-ab8f-760e69078d29> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Spira"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Spira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .

