Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jestan> <http://telicent.io/ontology/primaryName> "Jestan" .
<https://starwars.com#sector_Corpheli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jestan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corpheli> .
<https://starwars.com#0172e7ee-0b80-4b58-a1c9-c771867f814c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jestan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0172e7ee-0b80-4b58-a1c9-c771867f814c> .
<https://starwars.com#sector_Corpheli> <http://telicent.io/ontology/primaryName> "Corpheli" .
<https://starwars.com#0172e7ee-0b80-4b58-a1c9-c771867f814c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jestan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jestan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_Jestan> <http://www.w3.org/2000/01/rdf-schema#comment> "Jestan was a planet located in the Corpheli sector of the Expansion Region. " .
<https://starwars.com#sector_Corpheli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Jestan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

