Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L17> <http://telicent.io/ontology/primaryName> "L17" .
<https://starwars.com#planet_Adoris> <http://www.w3.org/2000/01/rdf-schema#comment> "Adoris was a terrestrial astronomical object located in the Adoris system of the Senex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. A hyperlane linked it to the Caltinia and Knores systems. It was home to the tooka, a species of felines also referred to as 'Adoris Felines' that were famous throughout the galaxy. " .
<https://starwars.com#grid_L17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Adoris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#4e3117c8-b80f-4ab2-b239-768728ec0698> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#grid_L17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4e3117c8-b80f-4ab2-b239-768728ec0698> .
<https://starwars.com#ed3cd08c-eaac-46ec-9377-8087859dc7b1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ed3cd08c-eaac-46ec-9377-8087859dc7b1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Adoris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Adoris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ed3cd08c-eaac-46ec-9377-8087859dc7b1> .
<https://starwars.com#grid_L17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Adoris> <http://telicent.io/ontology/primaryName> "Adoris" .
<https://starwars.com#planet_Adoris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#4e3117c8-b80f-4ab2-b239-768728ec0698> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Adoris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .

