Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ganath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#grid_R12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#d6ebe510-e116-4583-9471-c595198d0945> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ganath"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ganath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R12> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_R12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Ganath> <http://www.w3.org/2000/01/rdf-schema#comment> "Ganath was a planet hidden within the unchartered depths of a cloud of intensely radioactive interstellar gas near Nal Hutta. " .
<https://starwars.com#grid_R12> <http://telicent.io/ontology/primaryName> "R12" .
<https://starwars.com#76e916c1-56b6-44d5-af41-b924f6ad6467> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Ganath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_R12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#76e916c1-56b6-44d5-af41-b924f6ad6467> .
<https://starwars.com#planet_Ganath> <http://telicent.io/ontology/primaryName> "Ganath" .
<https://starwars.com#d6ebe510-e116-4583-9471-c595198d0945> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ganath> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d6ebe510-e116-4583-9471-c595198d0945> .
<https://starwars.com#76e916c1-56b6-44d5-af41-b924f6ad6467> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R12"^^<http://www.w3.org/2001/XMLSchema#string> .

