Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Neimoidia> <http://telicent.io/ontology/primaryName> "Neimoidia" .
<https://starwars.com#planet_Neimoidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#ea192e62-b9ca-41b4-96ca-bd80a06905e9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Neimoidia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Neimoidia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ea192e62-b9ca-41b4-96ca-bd80a06905e9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Neimoidia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ea192e62-b9ca-41b4-96ca-bd80a06905e9> .
<https://starwars.com#planet_Neimoidia> <http://www.w3.org/2000/01/rdf-schema#comment> "Twenty-five millennia before the Battle of Yavin, the planet was discovered by Duros explorers from the planet Duro during their travels throughout the galaxy. After its colonization, Neimoidia became allied with but separate from the Duros homeworld, and later joined the Galactic Republic in 22,000 BBY as an independent world. Sometime later, the Neimoidians, determined to expand their influence, established a string of planets known as 'Purse Worlds' on Cato Neimoidia, Deko Neimoidia and Koru Neimoidia, and Neimoidia was eventually overshadowed by the three as they grew in wealth. As a result, much of Neimoidia's population left for either of the three Purse Worlds, but some, including the Trade Monarch, the ruler of Neimoidia and the Purse Worlds, remained on the planet. " .
<https://starwars.com#planet_Neimoidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

