Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Balmorra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Balmorra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Balmorra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Balmorra> <http://www.w3.org/2000/01/rdf-schema#comment> "Balmorra was a factory world located in the Balmorra system of the galaxy's Colonies region. Despite being close to the Core Worlds, the planet had a strong sense of independence and was slow to join the Galactic Republic. During the Clone Wars, Balmorra left the Republic and joined the Confederacy of Independent Systems. During the Imperial Era, the Galactic Empire made use of its foundries, using them to build many of its All Terrain Armored Transports. The former pirate Queen Maz Kanata marked it as the location of an outlaw garage on a map that she included in the book that became known as the Smuggler's Guide. " .
<https://starwars.com#planet_Balmorra> <http://telicent.io/ontology/primaryName> "Balmorra" .
<https://starwars.com#5cc86ae1-352c-4b14-878e-f8183d65a3b2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Balmorra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5cc86ae1-352c-4b14-878e-f8183d65a3b2> .
<https://starwars.com#5cc86ae1-352c-4b14-878e-f8183d65a3b2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Balmorra"^^<http://www.w3.org/2001/XMLSchema#string> .

