Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jovaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jovaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Jovaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#813ed873-3abc-4e16-8d0a-c7e8803965f3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#813ed873-3abc-4e16-8d0a-c7e8803965f3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jovaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jovaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#813ed873-3abc-4e16-8d0a-c7e8803965f3> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Jovaria> <http://telicent.io/ontology/primaryName> "Jovaria" .
<https://starwars.com#planet_Jovaria> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

