Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Herdessa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Habassa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6fcabe95-5d50-47ba-9a39-cbddd83387a4> .
<https://starwars.com#sector_Herdessa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Habassa> <http://www.w3.org/2000/01/rdf-schema#comment> "The Habassa was the Habassa system's primary race. " .
<https://starwars.com#6fcabe95-5d50-47ba-9a39-cbddd83387a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Habassa> <http://telicent.io/ontology/primaryName> "Habassa" .
<https://starwars.com#6fcabe95-5d50-47ba-9a39-cbddd83387a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Habassa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Habassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Herdessa> .
<https://starwars.com#planet_Habassa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Habassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#sector_Herdessa> <http://telicent.io/ontology/primaryName> "Herdessa" .

