Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Orvax> <http://telicent.io/ontology/primaryName> "Orvax" .
<https://starwars.com#planet_Orvax> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d5fb4550-96c6-45c9-8969-0c36c44276ca> .
<https://starwars.com#planet_Orvax> <http://www.w3.org/2000/01/rdf-schema#comment> "Orvax was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Orvax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Orvax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#planet_Orvax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#d5fb4550-96c6-45c9-8969-0c36c44276ca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d5fb4550-96c6-45c9-8969-0c36c44276ca> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orvax"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

