Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Parcelus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_ParcelusMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Parcelus Minor was a location in the galaxy. The mercenary Saponza once participated in the Retreat from Parcelus Minor. " .
<https://starwars.com#planet_ParcelusMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3aaa53ef-f08e-4e83-b5c7-21d27a358ea1> .
<https://starwars.com#planet_ParcelusMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Parcelus> .
<https://starwars.com#planet_ParcelusMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#3aaa53ef-f08e-4e83-b5c7-21d27a358ea1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Parcelus Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ParcelusMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ParcelusMinor> <http://telicent.io/ontology/primaryName> "Parcelus Minor" .
<https://starwars.com#3aaa53ef-f08e-4e83-b5c7-21d27a358ea1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Parcelus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Parcelus> <http://telicent.io/ontology/primaryName> "Parcelus" .

