Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Koensayr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Koensayr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f79f7238-6b10-440a-8cf7-12f994cde407> .
<https://starwars.com#planet_Koensayr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#f79f7238-6b10-440a-8cf7-12f994cde407> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Koensayr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f79f7238-6b10-440a-8cf7-12f994cde407> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Koensayr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Koensayr> <http://www.w3.org/2000/01/rdf-schema#comment> "Koensayr was a planet in the Colonies region. It was the headquarters of Koensayr Manufacturing. " .
<https://starwars.com#planet_Koensayr> <http://telicent.io/ontology/primaryName> "Koensayr" .

