Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_BogoRai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e9f6319-2af5-4c87-91c0-044e1f77622c> .
<https://starwars.com#0e9f6319-2af5-4c87-91c0-044e1f77622c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_BogoRai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_BogoRai> <http://telicent.io/ontology/primaryName> "Bogo Rai" .
<https://starwars.com#planet_BogoRai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .
<https://starwars.com#planet_BogoRai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0e9f6319-2af5-4c87-91c0-044e1f77622c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bogo Rai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BogoRai> <http://www.w3.org/2000/01/rdf-schema#comment> "Bogo Rai was an astronomical object located within the territory of the Unknown Regions' Chiss Ascendancy government. " .

