Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#adeac561-6f65-4376-a94e-c5dde0340eea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Sleheyron> <http://telicent.io/ontology/primaryName> "Sleheyron" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#adeac561-6f65-4376-a94e-c5dde0340eea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sleheyron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sleheyron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sleheyron> <http://www.w3.org/2000/01/rdf-schema#comment> "Sleheyron was a planet located in the galaxy's Hutt Space region, in grid square S-10 on the Standard Galactic Grid, that was connected to Kessel, Klatooine, Nimban, and Varl by a hyperspace route. Controlled by the Hutt Clan, it was the homeworld of Hutt crime lord Ziro, who was covered in colorful tattoos indicating his connection to Sleheyron. " .
<https://starwars.com#planet_Sleheyron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#planet_Sleheyron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Sleheyron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#adeac561-6f65-4376-a94e-c5dde0340eea> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

