Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_OuterJalor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_OuterJalor> <http://telicent.io/ontology/primaryName> "Outer Jalor" .
<https://starwars.com#planet_KrilDor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#planet_KrilDor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f5c799f3-251f-4ef1-9f09-ead9f139d5de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KrilDor> <http://www.w3.org/2000/01/rdf-schema#comment> "Kril'Dor was a planet located in the galaxy's Mid Rim that was a source of tibanna gas. Located close to the Uba system, Kril'Dor was positioned at the coordinates I-7 on the Standard Galactic Grid. " .
<https://starwars.com#planet_KrilDor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f5c799f3-251f-4ef1-9f09-ead9f139d5de> .
<https://starwars.com#planet_KrilDor> <http://telicent.io/ontology/primaryName> "Kril'Dor" .
<https://starwars.com#planet_KrilDor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_OuterJalor> .
<https://starwars.com#sector_OuterJalor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f5c799f3-251f-4ef1-9f09-ead9f139d5de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kril'Dor"^^<http://www.w3.org/2001/XMLSchema#string> .

