Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Terrskiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Terrskiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#fdcfca4d-8a5b-453d-9397-d64fda81571b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#fffb0d42-527b-4e55-bf0d-facb075ee81c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Coachelle> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#grid_P10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#fffb0d42-527b-4e55-bf0d-facb075ee81c> .
<https://starwars.com#fffb0d42-527b-4e55-bf0d-facb075ee81c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#fdcfca4d-8a5b-453d-9397-d64fda81571b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Coachelle"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P10> <http://telicent.io/ontology/primaryName> "P10" .
<https://starwars.com#planet_Coachelle> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Terrskiar> <http://telicent.io/ontology/primaryName> "Terr'skiar" .
<https://starwars.com#planet_Coachelle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#planet_Coachelle> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fdcfca4d-8a5b-453d-9397-d64fda81571b> .
<https://starwars.com#grid_P10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Coachelle> <http://telicent.io/ontology/primaryName> "Coachelle" .
<https://starwars.com#grid_P10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Coachelle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Terrskiar> .

