Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sarapin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c185fec1-9b65-4079-9c7d-2614c9e407bf> .
<https://starwars.com#planet_Sarapin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Sarapin> <http://telicent.io/ontology/primaryName> "Sarapin" .
<https://starwars.com#planet_Sarapin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Sarapin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sarapin> <http://www.w3.org/2000/01/rdf-schema#comment> "Sarapin was an astronomical object located in the galaxy's Core Worlds. At some point prior to the attack on the EF76 Nebulon-B escort frigate Hellion's Dare over Jiruus, a fleet battle occurred at Sarapin during which Riot Squadron members Wyl Lark and Sonogari were present, but grounded. " .
<https://starwars.com#c185fec1-9b65-4079-9c7d-2614c9e407bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c185fec1-9b65-4079-9c7d-2614c9e407bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sarapin"^^<http://www.w3.org/2001/XMLSchema#string> .

