Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4f44695f-9304-41be-beb7-b2e4ee18b625> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quintas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kriz> <http://telicent.io/ontology/primaryName> "Kriz" .
<https://starwars.com#planet_Quintas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J19> .
<https://starwars.com#sector_Kriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Quintas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f44695f-9304-41be-beb7-b2e4ee18b625> .
<https://starwars.com#planet_Quintas> <http://telicent.io/ontology/primaryName> "Quintas" .
<https://starwars.com#planet_Quintas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kriz> .
<https://starwars.com#sector_Kriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#4f44695f-9304-41be-beb7-b2e4ee18b625> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Quintas> <http://www.w3.org/2000/01/rdf-schema#comment> "The Black Hole of Quintas was a black hole in the Kriz sector, in the Outer Rim region of the galaxy.[1] It was known to be very far removed from the Denarii Nova." .
<https://starwars.com#planet_Quintas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

