Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tharin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Tharin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tammar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tammar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a8a4443-ee53-4d3a-983b-52021ad39da1> .
<https://starwars.com#planet_Tammar> <http://www.w3.org/2000/01/rdf-schema#comment> "Tammar, originally known as Lelrais, was the Tammarian homeworld. This planet had an unusually thin atmosphere, which caused native Tammarians to evolve a chemical pouch called a chaghizs torm to store oxygen. This allowed them to survive in the vacuum of space for short periods. Tammar also had no standing water. " .
<https://starwars.com#6a8a4443-ee53-4d3a-983b-52021ad39da1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tammar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Tharin> <http://telicent.io/ontology/primaryName> "Tharin" .
<https://starwars.com#planet_Tammar> <http://telicent.io/ontology/primaryName> "Tammar" .
<https://starwars.com#planet_Tammar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tharin> .
<https://starwars.com#6a8a4443-ee53-4d3a-983b-52021ad39da1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tammar"^^<http://www.w3.org/2001/XMLSchema#string> .

