Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Toydaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c2374694-576c-4d08-b684-bab8780507dc> .
<https://starwars.com#planet_Toydaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Toydaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#c2374694-576c-4d08-b684-bab8780507dc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Toydaria> <http://www.w3.org/2000/01/rdf-schema#comment> "Home planet of Watto and other Toydarians. Close to Nal Hutta." .
<https://starwars.com#c2374694-576c-4d08-b684-bab8780507dc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Toydaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Toydaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R11> .
<https://starwars.com#planet_Toydaria> <http://telicent.io/ontology/primaryName> "Toydaria" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

