Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_P3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#d3880609-049f-477c-b32f-f677b8b205df> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_EolSha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P3> .
<https://starwars.com#5b1190b4-37d3-419f-8cc8-d65af9ec6ac2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5b1190b4-37d3-419f-8cc8-d65af9ec6ac2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eol Sha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d3880609-049f-477c-b32f-f677b8b205df> .
<https://starwars.com#sector_Corva> <http://telicent.io/ontology/primaryName> "Corva" .
<https://starwars.com#d3880609-049f-477c-b32f-f677b8b205df> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_EolSha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5b1190b4-37d3-419f-8cc8-d65af9ec6ac2> .
<https://starwars.com#grid_P3> <http://telicent.io/ontology/primaryName> "P3" .
<https://starwars.com#planet_EolSha> <http://telicent.io/ontology/primaryName> "Eol Sha" .
<https://starwars.com#grid_P3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Corva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_EolSha> <http://www.w3.org/2000/01/rdf-schema#comment> "Settled by gas miners during the time of the Galactic Republic, the planet was orbited by a single moon that was noted for its unstable descending orbit. By the time of the planet's rediscovery in 9 ABY, it was predicted that Eol Sha's moon would collide with the planet in a matter of years. Under the direction of the New Republic, the planet's few remaining residents were evacuated and resettled on the planet Dantooine in the year 11 ABY. Later that year, however, the Cauldron Nebula was destroyed by the Sun Crusher, an Imperial superweapon piloted by the rogue Jedi Kyp Durron, an event that more than likely brought about the destruction of Eol Sha and its solar system. " .
<https://starwars.com#planet_EolSha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_EolSha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corva> .
<https://starwars.com#sector_Corva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

