Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Matra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Matra> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Matra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Matra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#848a6183-041d-4d50-a037-de60f061cdc6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Matra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#848a6183-041d-4d50-a037-de60f061cdc6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Matra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#848a6183-041d-4d50-a037-de60f061cdc6> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Matra> <http://telicent.io/ontology/primaryName> "Matra" .

