Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cambria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#64a6f32d-d816-4a52-88f2-891463658db3> .
<https://starwars.com#planet_Cambria> <http://telicent.io/ontology/primaryName> "Cambria" .
<https://starwars.com#planet_Cambria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Cambria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Cambria> <http://www.w3.org/2000/01/rdf-schema#comment> "Cambria was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#64a6f32d-d816-4a52-88f2-891463658db3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cambria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cambria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#64a6f32d-d816-4a52-88f2-891463658db3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

