Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_ColonialStationCamco> <http://www.w3.org/2000/01/rdf-schema#comment> "Colonial Station Camco, also known as Colonial Station Cam'co, was a terrestrial planet located within the territory of the Chiss Ascendancy in the Unknown Regions. The Chiss Caregiver Mitth'ali'astov, known by the core name 'Thalias,' was born there before she became a sky-walker navigator. " .
<https://starwars.com#planet_ColonialStationCamco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_ColonialStationCamco> <http://telicent.io/ontology/primaryName> "Colonial Station Cam'co" .
<https://starwars.com#1ddf225d-b2dc-4d48-ad87-9f777c3b4376> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Colonial Station Cam'co"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_ColonialStationCamco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#planet_ColonialStationCamco> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1ddf225d-b2dc-4d48-ad87-9f777c3b4376> .
<https://starwars.com#planet_ColonialStationCamco> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1ddf225d-b2dc-4d48-ad87-9f777c3b4376> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

