Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Erysthes> <http://www.w3.org/2000/01/rdf-schema#comment> "Erysthes, located in the Corporate Sector in the Tingel Arm of the galaxy, was the planet to which the chak-root was native. " .
<https://starwars.com#planet_Erysthes> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2649db0a-277e-4498-8ef5-e9125a0fd2ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Erysthes"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Erysthes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#2649db0a-277e-4498-8ef5-e9125a0fd2ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Erysthes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Erysthes> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2649db0a-277e-4498-8ef5-e9125a0fd2ae> .
<https://starwars.com#planet_Erysthes> <http://telicent.io/ontology/primaryName> "Erysthes" .

