Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cc8716c4-c031-4626-a4a9-969faf49f09a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#95b9fd52-1185-489a-9615-aef98f0a2520> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#grid_H10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#95b9fd52-1185-489a-9615-aef98f0a2520> .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_H10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Jedha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H10> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#95b9fd52-1185-489a-9615-aef98f0a2520> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#cc8716c4-c031-4626-a4a9-969faf49f09a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jedha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_H10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Jedha> <http://www.w3.org/2000/01/rdf-schema#comment> "Cold desert moon, and a sacred place for believers in the Force. A source of kyber crystals used for lightsabers and the Death Star's primary weapon. It is also the first location on which the Death Star's destructive capability is tested. Rogue One's director, Gareth Edwards, has described the location as 'a Mecca or Jerusalem within the Star Wars world'. It is also a homonym for Jeddah, the principal gateway to Mecca." .
<https://starwars.com#grid_H10> <http://telicent.io/ontology/primaryName> "H10" .
<https://starwars.com#planet_Jedha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc8716c4-c031-4626-a4a9-969faf49f09a> .
<https://starwars.com#planet_Jedha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jedha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Jedha> <http://telicent.io/ontology/primaryName> "Jedha" .

