Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Trestis> <http://telicent.io/ontology/primaryName> "Trestis" .
<https://starwars.com#sector_Trestis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Muzara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trestis> .
<https://starwars.com#planet_Muzara> <http://www.w3.org/2000/01/rdf-schema#comment> "Muzara was a planet in the Expansion Region. Humans from Brentaal colonized the planet in 4000 BBY, barely avoiding conflict with the native Muzaran people, who were also known as the Muza. " .
<https://starwars.com#planet_Muzara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#ffa58be7-9ff6-4609-a687-e222a0a43325> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Trestis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Muzara> <http://telicent.io/ontology/primaryName> "Muzara" .
<https://starwars.com#ffa58be7-9ff6-4609-a687-e222a0a43325> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Muzara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Muzara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ffa58be7-9ff6-4609-a687-e222a0a43325> .
<https://starwars.com#planet_Muzara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

