Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_CantrasGola> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#240a7010-8041-49c8-a2bd-e05a7df5d7f4> .
<https://starwars.com#planet_CantrasGola> <http://www.w3.org/2000/01/rdf-schema#comment> "Cantras Gola was a planet in the Pentastar Alignment. It was a corporate planet controlled by PowerOn Conglomerate. During the Thrawn Crisis, it decided to leave the Pentastar Alignment and join the New Republic. The Alignment threatened to kill the children of the Ambassador of Cantras Gola if he had any sort of meeting with the New Republic. The children had been taken by slavers to Gabredor III. They were rescued by a Red Moons mercenary team, allowing Cantras Gola to join the New Republic. " .
<https://starwars.com#sector_Perinn> <http://telicent.io/ontology/primaryName> "Perinn" .
<https://starwars.com#240a7010-8041-49c8-a2bd-e05a7df5d7f4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#240a7010-8041-49c8-a2bd-e05a7df5d7f4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cantras Gola"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CantrasGola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_CantrasGola> <http://telicent.io/ontology/primaryName> "Cantras Gola" .
<https://starwars.com#planet_CantrasGola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Perinn> .
<https://starwars.com#sector_Perinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_CantrasGola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Perinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

