Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Annaj> <http://www.w3.org/2000/01/rdf-schema#comment> "Annaj was an astronomical object in the Annaj system of the Outer Rim Territories' Moddell sector. Prior to the Battle of Endor in 4 ABY, Annaj was mapped as part of a Rebel Alliance report on the navigation of the Moddell sector by Corporal Ractivelle of Stardust unit in preparation for the Rebel Alliance's attack on the second Death Star. " .
<https://starwars.com#planet_Annaj> <http://telicent.io/ontology/primaryName> "Annaj" .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Annaj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#a0450268-8bdd-4d22-a0fc-deef8752ce08> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Annaj"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a0450268-8bdd-4d22-a0fc-deef8752ce08> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Annaj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Annaj> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0450268-8bdd-4d22-a0fc-deef8752ce08> .
<https://starwars.com#planet_Annaj> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

