Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Selenius> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Selenius> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Selenius> <http://telicent.io/ontology/primaryName> "Selenius" .
<https://starwars.com#planet_Selenius> <http://www.w3.org/2000/01/rdf-schema#comment> "The Selenius system was a star system containing the planet Selenius VII." .
<https://starwars.com#sector_DAelgoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#60a66a14-6963-4281-956e-2452478ec0a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Selenius"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Selenius> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAelgoth> .
<https://starwars.com#sector_DAelgoth> <http://telicent.io/ontology/primaryName> "D'Aelgoth" .
<https://starwars.com#sector_DAelgoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#60a66a14-6963-4281-956e-2452478ec0a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Selenius> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#60a66a14-6963-4281-956e-2452478ec0a6> .

