Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_G7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#79c31c26-6c98-4a7f-b1b0-cf8835c3adf4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ilum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_G7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#30c8851a-33c3-4a16-85e6-597f045f04c3> .
<https://starwars.com#30c8851a-33c3-4a16-85e6-597f045f04c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ilum> <http://www.w3.org/2000/01/rdf-schema#comment> "Remote ice planet where kyber crystals are mined. Converted into Starkiller Base by the First Order and destroyed in The Force Awakens." .
<https://starwars.com#grid_G7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Ilum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ilum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G7> .
<https://starwars.com#planet_Ilum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#79c31c26-6c98-4a7f-b1b0-cf8835c3adf4> .
<https://starwars.com#grid_G7> <http://telicent.io/ontology/primaryName> "G7" .
<https://starwars.com#79c31c26-6c98-4a7f-b1b0-cf8835c3adf4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ilum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Ilum> <http://telicent.io/ontology/primaryName> "Ilum" .
<https://starwars.com#30c8851a-33c3-4a16-85e6-597f045f04c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

