Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Florrum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Florrum> <http://www.w3.org/2000/01/rdf-schema#comment> "Sulfurous desert planet. Hondo Ohnaka is the leader of a pirate gang based on the planet." .
<https://starwars.com#c3a4c668-faae-462f-ab73-c66e7311bd4c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Florrum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#c3a4c668-faae-462f-ab73-c66e7311bd4c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Florrum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Florrum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Florrum> <http://telicent.io/ontology/primaryName> "Florrum" .
<https://starwars.com#planet_Florrum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c3a4c668-faae-462f-ab73-c66e7311bd4c> .

