Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Esstran> <http://telicent.io/ontology/primaryName> "Esstran" .
<https://starwars.com#planet_Thule> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esstran> .
<https://starwars.com#planet_Thule> <http://www.w3.org/2000/01/rdf-schema#comment> "Thule was a location in the Esstran sector of the galaxy. Doctor Chelli Lona Aphra owned a certificate from the Imperial Institute for Archaeological Exploitation that gave her limited clearance to access Thule, a site of historical importance to the Galactic Empire, according to bylaws 22.750-23.018 of the Harvester Accords. The mercenary gang known as Thugs of Thule were headquartered there. " .
<https://starwars.com#planet_Thule> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Esstran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#f41ad082-f037-488d-9c4f-ef3423d8ced2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f41ad082-f037-488d-9c4f-ef3423d8ced2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thule"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Esstran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thule> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Thule> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f41ad082-f037-488d-9c4f-ef3423d8ced2> .
<https://starwars.com#planet_Thule> <http://telicent.io/ontology/primaryName> "Thule" .

