Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Manda> <http://www.w3.org/2000/01/rdf-schema#comment> "Manda was an astronomical object located in the galaxy's Mid Rim with plenty of transport. The freighter Eclipse once set course in hyperspace to Manda to drop off several of its crewmembers. Tibbs Ospe, the owner of the Lodge on the planet Vandor, thought that Vandor might make a good stop for traders heading to Manda or Deneba, so by 10 BBY, he had fixed the ruins of Ypsobay Trading Company's old headquarters, filled in craters in old landing strips, and let people know they could find fuel and food at Fort Ypso. " .
<https://starwars.com#sector_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#e784cc59-6d14-4dde-8fb9-18f263e9d5f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Manda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e784cc59-6d14-4dde-8fb9-18f263e9d5f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#planet_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R15> .
<https://starwars.com#planet_Manda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e784cc59-6d14-4dde-8fb9-18f263e9d5f2> .
<https://starwars.com#sector_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Manda> .
<https://starwars.com#planet_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

