Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jaciprus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#b413f305-52d3-4598-bd2f-9b877a188480> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jaciprus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b413f305-52d3-4598-bd2f-9b877a188480> .
<https://starwars.com#planet_Jaciprus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jaciprus> <http://telicent.io/ontology/primaryName> "Jaciprus" .
<https://starwars.com#b413f305-52d3-4598-bd2f-9b877a188480> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jaciprus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jaciprus> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Jaciprus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

