Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e90a1467-b267-4665-a068-3192b1476727> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Urdur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Urdur> <http://telicent.io/ontology/primaryName> "Urdur" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#e90a1467-b267-4665-a068-3192b1476727> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Urdur"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Urdur> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e90a1467-b267-4665-a068-3192b1476727> .
<https://starwars.com#planet_Urdur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Urdur> <http://www.w3.org/2000/01/rdf-schema#comment> "Urdur was a location within the Outer Rim Territories' Corporate Sector. The former pirate Queen Maz Kanata marked it as the site of an outlaw garage on a map she included in the book that would become known as the Smuggler's Guide. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Urdur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .

