Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ThullsVault> <http://www.w3.org/2000/01/rdf-schema#comment> "Thull's Vault was a planet with luminescent sands that was located within the Thull's Vault system, in the Juvex sector of the Mid Rim. According to legend, an ancient fleet of treasure ships was hidden beneath the planet's sands. " .
<https://starwars.com#planet_ThullsVault> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#7aea8a4e-1503-4b47-ab63-ab8f111de717> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ThullsVault> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_ThullsVault> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7aea8a4e-1503-4b47-ab63-ab8f111de717> .
<https://starwars.com#7aea8a4e-1503-4b47-ab63-ab8f111de717> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thull's Vault"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ThullsVault> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ThullsVault> <http://telicent.io/ontology/primaryName> "Thull's Vault" .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

