Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#planet_Indellian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#planet_Indellian> <http://www.w3.org/2000/01/rdf-schema#comment> "Indellian was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Indellian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Indellian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Indellian> <http://telicent.io/ontology/primaryName> "Indellian" .
<https://starwars.com#planet_Indellian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#078ff9e5-7ba5-45f1-88fe-c523a1f4a387> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#078ff9e5-7ba5-45f1-88fe-c523a1f4a387> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#078ff9e5-7ba5-45f1-88fe-c523a1f4a387> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Indellian"^^<http://www.w3.org/2001/XMLSchema#string> .

