Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lahmu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lahmu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#planet_Lahmu> <http://telicent.io/ontology/primaryName> "Lah'mu" .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lahmu> <http://www.w3.org/2000/01/rdf-schema#comment> "A remote planet with black sands, where Jyn Erso and her parents go into hiding." .
<https://starwars.com#b76f6503-6193-40b3-a4da-9537b18752ca> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lah'mu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lahmu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b76f6503-6193-40b3-a4da-9537b18752ca> .
<https://starwars.com#planet_Lahmu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#b76f6503-6193-40b3-a4da-9537b18752ca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

