Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tund> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Tund> <http://telicent.io/ontology/primaryName> "Tund" .
<https://starwars.com#planet_Tund> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c83feb35-6605-481b-ae93-324ecfc6ab0f> .
<https://starwars.com#planet_Tund> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#c83feb35-6605-481b-ae93-324ecfc6ab0f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tund> <http://www.w3.org/2000/01/rdf-schema#comment> "Tund was a hidden planet located in the mysterious Tund system, within the Centrality sector of the galaxy's Outer Rim Territories, in grid square U-8 on the Standard Galactic Grid. It was the homeworld of the Toong species and became home to Ben Quadinaros, a Toong Podracer pilot that claimed to be from the Tund system. " .
<https://starwars.com#c83feb35-6605-481b-ae93-324ecfc6ab0f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tund"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tund> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .

