Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baroli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Vernet> <http://telicent.io/ontology/primaryName> "Vernet" .
<https://starwars.com#planet_Vernet> <http://www.w3.org/2000/01/rdf-schema#comment> "Vernet was an agriworld located within the Vernet system of the Expansion Region. " .
<https://starwars.com#sector_Baroli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vernet> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vernet> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baroli> .
<https://starwars.com#f9e18501-bbb6-4a5d-9de5-d87675e5fbbf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vernet"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Baroli> <http://telicent.io/ontology/primaryName> "Baroli" .
<https://starwars.com#planet_Vernet> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f9e18501-bbb6-4a5d-9de5-d87675e5fbbf> .
<https://starwars.com#f9e18501-bbb6-4a5d-9de5-d87675e5fbbf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vernet> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .

