Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Huk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_Huk> <http://www.w3.org/2000/01/rdf-schema#comment> "Huk was a planet located in Wild Space, the homeworld of the technologically-advanced, Insectoid Yam'rii species from the same system as Kalee. " .
<https://starwars.com#planet_Huk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bc8c76e4-c56c-4d62-b855-966b3c3e4b3c> .
<https://starwars.com#bc8c76e4-c56c-4d62-b855-966b3c3e4b3c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Huk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Huk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Huk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bc8c76e4-c56c-4d62-b855-966b3c3e4b3c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Huk> <http://telicent.io/ontology/primaryName> "Huk" .

