Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7f5052a9-5fda-4bc2-97f0-3126e98fd076> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Janodral Mizar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Indrexu> <http://telicent.io/ontology/primaryName> "Indrexu" .
<https://starwars.com#planet_JanodralMizar> <http://www.w3.org/2000/01/rdf-schema#comment> "Janodral Mizar was a planet in Outer Rim Territories in the Indrexu sector. " .
<https://starwars.com#planet_JanodralMizar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7f5052a9-5fda-4bc2-97f0-3126e98fd076> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_JanodralMizar> <http://telicent.io/ontology/primaryName> "Janodral Mizar" .
<https://starwars.com#sector_Indrexu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_JanodralMizar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#sector_Indrexu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_JanodralMizar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Indrexu> .
<https://starwars.com#planet_JanodralMizar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7f5052a9-5fda-4bc2-97f0-3126e98fd076> .

