Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dioll> <http://telicent.io/ontology/primaryName> "Dioll" .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Dioll> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ec5b39e9-08c9-47a4-b546-1cd352169caa> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dioll> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#ec5b39e9-08c9-47a4-b546-1cd352169caa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ec5b39e9-08c9-47a4-b546-1cd352169caa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dioll"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dioll> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Dioll> <http://www.w3.org/2000/01/rdf-schema#comment> "Dioll was a rocky planet located in the Dioll system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. The Kassido Bypass hyperlane linked it to the Kardura and Thermon systems. " .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dioll> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

