Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Generis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#planet_Generis> <http://www.w3.org/2000/01/rdf-schema#comment> "Generis was an astronomical object located in the Atrivis sector within the galaxy's Outer Rim Territories. The Rebel pilot Paril Ritta was from Generis. During the early rebellion against the Galactic Empire, Generis served as an Alliance to Restore the Republic regional headquarters and operations sector. Generis was included in a map of the galaxy that listed safe worlds, starfighter hubs at level five or higher, regional headquarters and operations sectors, and deep space caches. " .
<https://starwars.com#46c3fd6d-4319-48c8-857c-f3488b87b772> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Generis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Generis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Generis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46c3fd6d-4319-48c8-857c-f3488b87b772> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#46c3fd6d-4319-48c8-857c-f3488b87b772> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Generis> <http://telicent.io/ontology/primaryName> "Generis" .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Generis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

