Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Radnor> <http://telicent.io/ontology/primaryName> "Radnor" .
<https://starwars.com#d4eb56fc-f10c-4df4-9f7d-8e04a3bada1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d4eb56fc-f10c-4df4-9f7d-8e04a3bada1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Radnor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Radnor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d4eb56fc-f10c-4df4-9f7d-8e04a3bada1b> .
<https://starwars.com#planet_Radnor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Daimar> .
<https://starwars.com#sector_Daimar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Daimar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Daimar> <http://telicent.io/ontology/primaryName> "Daimar" .
<https://starwars.com#planet_Radnor> <http://www.w3.org/2000/01/rdf-schema#comment> "Radnor was an astronomical object located in the galaxy's Mid Rim on the Corellian Run. " .
<https://starwars.com#planet_Radnor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#planet_Radnor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

