Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Riflor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Riflor> <http://www.w3.org/2000/01/rdf-schema#comment> "Riflor was a volcanic planet located in the galaxy's Mid Rim, connected by hyperspace route to Cerea and Lorta. It was home to the Advozse species. On Riflor, volcanic eruptions frequently destroyed Advozsec settlements, so the Advozsec tended to care very little about material goods. " .
<https://starwars.com#3540a68a-1de5-4832-8a3c-94b53c6fe3d6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Narrant> <http://telicent.io/ontology/primaryName> "Narrant" .
<https://starwars.com#sector_Narrant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Riflor> <http://telicent.io/ontology/primaryName> "Riflor" .
<https://starwars.com#planet_Riflor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J16> .
<https://starwars.com#planet_Riflor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3540a68a-1de5-4832-8a3c-94b53c6fe3d6> .
<https://starwars.com#sector_Narrant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Riflor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Narrant> .
<https://starwars.com#3540a68a-1de5-4832-8a3c-94b53c6fe3d6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Riflor"^^<http://www.w3.org/2001/XMLSchema#string> .

