Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hillindor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#a8cba63d-0d9a-4025-9610-6ff0dcb173bc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hillindor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hillindor> <http://telicent.io/ontology/primaryName> "Hillindor" .
<https://starwars.com#planet_Hillindor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Hillindor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a8cba63d-0d9a-4025-9610-6ff0dcb173bc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hillindor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a8cba63d-0d9a-4025-9610-6ff0dcb173bc> .
<https://starwars.com#planet_Hillindor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

