Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#43a2fd26-83f5-46d0-86dd-c69f045ba3d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dartessex IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DartessexIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Dartessex IV was a planet in the Dartessex system. " .
<https://starwars.com#planet_DartessexIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#43a2fd26-83f5-46d0-86dd-c69f045ba3d9> .
<https://starwars.com#planet_DartessexIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_DartessexIV> <http://telicent.io/ontology/primaryName> "Dartessex IV" .
<https://starwars.com#planet_DartessexIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_DartessexIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#43a2fd26-83f5-46d0-86dd-c69f045ba3d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

