Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Trenwyth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Stensen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Trenwyth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6aaf9573-178a-49c8-840f-7d793516984c> .
<https://starwars.com#planet_Trenwyth> <http://www.w3.org/2000/01/rdf-schema#comment> "Trenwyth was a world located in the Mid Rim that was the homeworld of flesh-eating daggerworms, a species of parasitic worm that could infest happabores. " .
<https://starwars.com#sector_Stensen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#6aaf9573-178a-49c8-840f-7d793516984c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trenwyth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I16> .
<https://starwars.com#planet_Trenwyth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Stensen> .
<https://starwars.com#planet_Trenwyth> <http://telicent.io/ontology/primaryName> "Trenwyth" .
<https://starwars.com#6aaf9573-178a-49c8-840f-7d793516984c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trenwyth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Stensen> <http://telicent.io/ontology/primaryName> "Stensen" .

