Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Echnos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hadar> .
<https://starwars.com#planet_Echnos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Echnos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Echnos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#71807ca2-5c0f-4ece-8379-80a1a2e7c599> .
<https://starwars.com#71807ca2-5c0f-4ece-8379-80a1a2e7c599> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Echnos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Hadar> <http://telicent.io/ontology/primaryName> "Hadar" .
<https://starwars.com#sector_Hadar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Echnos> <http://telicent.io/ontology/primaryName> "Echnos" .
<https://starwars.com#71807ca2-5c0f-4ece-8379-80a1a2e7c599> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Echnos> <http://www.w3.org/2000/01/rdf-schema#comment> "Echnos, also known as Tinn VI-D, was a moon of Tinn VI with a nitrogen-rich atmosphere. Its sole settlement was an immense domed structure called Echnos City which arose as a way station for numerous ships that lost their magnetic bottle shielding from passing too close to Tinn VI's powerful negative magnetic field. Echnos City was the headquarters of the Mandellian Corporation, which hosted a demolition derby called the BlastBoast 2000 located at the bottom of the city inside Echnos Exhibition Dome. " .
<https://starwars.com#sector_Hadar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

