Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TsossBeacon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TsossBeacon> <http://telicent.io/ontology/primaryName> "Tsoss Beacon" .
<https://starwars.com#1367bc82-c6df-4617-ae94-b657ea891eba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TsossBeacon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L11> .
<https://starwars.com#planet_TsossBeacon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1367bc82-c6df-4617-ae94-b657ea891eba> .
<https://starwars.com#planet_TsossBeacon> <http://www.w3.org/2000/01/rdf-schema#comment> "Tsoss Beacon was an astronomical object located within the Deep Core, the dangerous innermost region of the galaxy. " .
<https://starwars.com#planet_TsossBeacon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#1367bc82-c6df-4617-ae94-b657ea891eba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tsoss Beacon"^^<http://www.w3.org/2001/XMLSchema#string> .

