Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#3f782009-4386-42c6-a1ff-4c2ed71ddc14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Taloraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I15> .
<https://starwars.com#planet_Taloraan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3f782009-4386-42c6-a1ff-4c2ed71ddc14> .
<https://starwars.com#planet_Taloraan> <http://telicent.io/ontology/primaryName> "Taloraan" .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Taloraan> <http://www.w3.org/2000/01/rdf-schema#comment> "Taloraan was a gas giant that contained a life zone. It was home to the Wind Raiders. While living as a hermit on the planet Pasaana, Lando Calrissian wore a Taloraan Wind Raider's helmet. " .
<https://starwars.com#3f782009-4386-42c6-a1ff-4c2ed71ddc14> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taloraan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Taloraan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Taloraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

