Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Betshish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#grid_P5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Betshish> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#fb692b88-b832-48ed-a5b0-e7b541e567ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#811ee40a-3798-4d94-885b-6b7440cc9e65> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Betshish"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#fb692b88-b832-48ed-a5b0-e7b541e567ac> .
<https://starwars.com#planet_Betshish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_Betshish> <http://www.w3.org/2000/01/rdf-schema#comment> "Betshish was a planet located in the Gordian Reach along the Pinooran Spur between Mogoshyn and Kli'aar. It was the homeworld of a sentient species. Betshish was discovered by a scout, Lile Gorsek, but his claim to the world had to be abandoned when the sentient species was discovered on landing. While it was interdicted by the Galactic Empire, the world escaped exploitation. " .
<https://starwars.com#planet_Betshish> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#811ee40a-3798-4d94-885b-6b7440cc9e65> .
<https://starwars.com#grid_P5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#fb692b88-b832-48ed-a5b0-e7b541e567ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Betshish> <http://telicent.io/ontology/primaryName> "Betshish" .
<https://starwars.com#grid_P5> <http://telicent.io/ontology/primaryName> "P5" .
<https://starwars.com#811ee40a-3798-4d94-885b-6b7440cc9e65> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

