Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Utapau> <http://telicent.io/ontology/primaryName> "Utapau" .
<https://starwars.com#planet_Utapau> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tarabba> .
<https://starwars.com#planet_Utapau> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5b82493e-ed91-4c42-9946-fd926a3ba6ee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Utapau"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tarabba> <http://telicent.io/ontology/primaryName> "Tarabba" .
<https://starwars.com#5b82493e-ed91-4c42-9946-fd926a3ba6ee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tarabba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Utapau> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N19> .
<https://starwars.com#sector_Tarabba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Utapau> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5b82493e-ed91-4c42-9946-fd926a3ba6ee> .
<https://starwars.com#planet_Utapau> <http://www.w3.org/2000/01/rdf-schema#comment> "Remote planet, covered in deep sinkholes and home to the Utai and Pau'ans. Site of General Grievous' death and a separatist base during the last days of the Clone Wars." .

