Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Plexis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Plexis> <http://telicent.io/ontology/primaryName> "Plexis" .
<https://starwars.com#planet_Plexis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Plexis> <http://www.w3.org/2000/01/rdf-schema#comment> "Plexis was a relatively small planet located in the Core Worlds region of the galaxy. During the Age of the Empire, it housed a number of spice gangs, all of which were under the authority of the Zenowai Crime Society via an overseer named Shoja Ko. " .
<https://starwars.com#eff2c4a0-5a35-488e-bf97-9964c339363d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Plexis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#eff2c4a0-5a35-488e-bf97-9964c339363d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Plexis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eff2c4a0-5a35-488e-bf97-9964c339363d> .
<https://starwars.com#planet_Plexis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .

