Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Lequabis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2d53fd0e-4843-4b96-94b7-2a5a9c3d58d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lequabis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#2d53fd0e-4843-4b96-94b7-2a5a9c3d58d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lequabis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2d53fd0e-4843-4b96-94b7-2a5a9c3d58d2> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lequabis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Lequabis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I14> .
<https://starwars.com#planet_Lequabis> <http://www.w3.org/2000/01/rdf-schema#comment> "The Lequabis system was an Expansion Region star system. Following the Imperial occupation of Cloud City on the planet Bespin in 3 ABY, the Rebel Alliance was forced to search for other sources of the important Tibanna gas. Alliance Captain Eedan therefore tasked a group of Rebel agents with surveying gas giant planets in several star systems. The exploration of the Lequabis system eventually proved fruitless, and the Rebel scouts continued with their search in the Poviduze system. " .
<https://starwars.com#planet_Lequabis> <http://telicent.io/ontology/primaryName> "Lequabis" .

