Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ZeemachtCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Tirahnn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ZeemachtCluster> .
<https://starwars.com#planet_Tirahnn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tirahnn> <http://telicent.io/ontology/primaryName> "Tirahnn" .
<https://starwars.com#sector_ZeemachtCluster> <http://telicent.io/ontology/primaryName> "Zeemacht Cluster" .
<https://starwars.com#planet_Tirahnn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#56146dac-5929-4cd3-9245-3d0ad3dc2a0b> .
<https://starwars.com#56146dac-5929-4cd3-9245-3d0ad3dc2a0b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ZeemachtCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#56146dac-5929-4cd3-9245-3d0ad3dc2a0b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tirahnn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tirahnn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Tirahnn> <http://www.w3.org/2000/01/rdf-schema#comment> "Tirahnn was an Imperial astronomical object located in the galaxy's Inner Rim along the Perlemian Trade Route. A thug working for the Gray Syndicate, while examining Merei Spanjaf, mentioned having seen someone with a hidden transmitter once during a gang war on Tirahnn. The thug, trying to scare her, suggested opening her skull to check. " .

