Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7c907788-3815-4f62-a33e-f638fb65f571> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kowak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7c907788-3815-4f62-a33e-f638fb65f571> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kowak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7c907788-3815-4f62-a33e-f638fb65f571> .
<https://starwars.com#sector_Svetta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kowak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kowak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Svetta> .
<https://starwars.com#planet_Kowak> <http://telicent.io/ontology/primaryName> "Kowak" .
<https://starwars.com#planet_Kowak> <http://www.w3.org/2000/01/rdf-schema#comment> "Kowak was a planet located in the galaxy's Outer Rim Territories that was the homeworld of the Kowakian monkey-lizards, the kowakian ape-lizards, and mole-fleas. " .
<https://starwars.com#planet_Kowak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S16> .
<https://starwars.com#sector_Svetta> <http://telicent.io/ontology/primaryName> "Svetta" .
<https://starwars.com#sector_Svetta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

