Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b095cd62-ff63-430b-a9a6-2556b8e8c9ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Juvex> <http://www.w3.org/2000/01/rdf-schema#comment> "Juvex was the sector capital of Juvex sector. It was ruled by House Sreethyn which engaged in the slave trade, and thus was denied Galactic Republic membership until shortly before the formation of the New Order. It was later part of the New Republic. " .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Juvex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b095cd62-ff63-430b-a9a6-2556b8e8c9ad> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b095cd62-ff63-430b-a9a6-2556b8e8c9ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Juvex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

