Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#91c29d0d-0647-4bab-9f8e-0ff8478fb0a9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Minntooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Minntooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#91c29d0d-0647-4bab-9f8e-0ff8478fb0a9> .
<https://starwars.com#planet_Minntooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Minntooine> <http://telicent.io/ontology/primaryName> "Minntooine" .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Minntooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Minntooine was a strategic world and stronghold of the Separatist Alliance located along the Perlemian Trade Route that served as a location for major interests of the Commerce Guild. Around the time of the Clone Wars between the Galactic Republic and Separatist Alliance, in which the Guild sided with the latter faction, Minntooine was protected by several Diamond-class cruisers and Recusant-class light destroyers, as well as corvettes and bombers that belonged to the Guild. " .
<https://starwars.com#planet_Minntooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Minntooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#91c29d0d-0647-4bab-9f8e-0ff8478fb0a9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

