Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jospro> <http://telicent.io/ontology/primaryName> "Jospro" .
<https://starwars.com#9d3b24bb-3661-440f-98cf-0f1880cbbf4b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SyMyrth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#planet_SyMyrth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jospro> .
<https://starwars.com#planet_SyMyrth> <http://www.w3.org/2000/01/rdf-schema#comment> "Sy Myrth was a planet located in the Outer Rim Territories of the galaxy, situated at the coordinates S-7 on the Standard Galactic Grid. It was linked via hyperspace routes to Belderone, Boonta, Centares, and Jabiim. Sy Myrth was the homeworld of the Sy Myrthian Brookish Boon and the Sy Myrthian Senator Toonbuck Toora, who represented the world in the Galactic Senate of the Galactic Republic. " .
<https://starwars.com#9d3b24bb-3661-440f-98cf-0f1880cbbf4b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sy Myrth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Jospro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SyMyrth> <http://telicent.io/ontology/primaryName> "Sy Myrth" .
<https://starwars.com#sector_Jospro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_SyMyrth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9d3b24bb-3661-440f-98cf-0f1880cbbf4b> .
<https://starwars.com#planet_SyMyrth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

