Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1780a48e-0a5e-47e8-b3b5-29b4b5949d14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Stassia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Stassia> <http://telicent.io/ontology/primaryName> "Stassia" .
<https://starwars.com#planet_Stassia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Stassia> <http://www.w3.org/2000/01/rdf-schema#comment> "Stassia was a planet located in the Core Worlds. Its inhabitants were very tolerant under any circumstances. During the Galactic Civil War, Stassia was ruled by the Galactic Empire under the governorship of Tren Pergallis. " .
<https://starwars.com#planet_Stassia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1780a48e-0a5e-47e8-b3b5-29b4b5949d14> .
<https://starwars.com#1780a48e-0a5e-47e8-b3b5-29b4b5949d14> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Stassia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Stassia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .

