Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_RestiKel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e1aaad76-b782-4afd-8ad4-4d7ce388e00a> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_RestiKel> <http://telicent.io/ontology/primaryName> "Resti Kel" .
<https://starwars.com#e1aaad76-b782-4afd-8ad4-4d7ce388e00a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Resti Kel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RestiKel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RestiKel> <http://www.w3.org/2000/01/rdf-schema#comment> "Resti Kel was a planet located in the Resti Kel system of the Juvex sector, in the Mid Rim of the galaxy. " .
<https://starwars.com#planet_RestiKel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_RestiKel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e1aaad76-b782-4afd-8ad4-4d7ce388e00a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

