Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Perin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6dd0232d-44f9-41bb-8fc8-9c6e595b0e96> .
<https://starwars.com#planet_Perin> <http://telicent.io/ontology/primaryName> "Perin" .
<https://starwars.com#6dd0232d-44f9-41bb-8fc8-9c6e595b0e96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#6dd0232d-44f9-41bb-8fc8-9c6e595b0e96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Perin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Perin> <http://www.w3.org/2000/01/rdf-schema#comment> "Perin was a Trianii colony planet in Trianii Space. " .
<https://starwars.com#planet_Perin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Perin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Perin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

