Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Glottal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U11> .
<https://starwars.com#017dc805-208a-4790-956e-6056ea3c96ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Glottal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Glottal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Glottal> <http://telicent.io/ontology/primaryName> "Glottal" .
<https://starwars.com#planet_Glottal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#planet_Glottal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#017dc805-208a-4790-956e-6056ea3c96ab> .
<https://starwars.com#017dc805-208a-4790-956e-6056ea3c96ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Glottal> <http://www.w3.org/2000/01/rdf-schema#comment> "Glottal was a planet located within the Glottal system in the Baxel sector of the Outer Rim region of the galaxy. It was the Glottalphib homeworld. It was a hot and humid planet, making it a perfect habitat for the 'Phibs. " .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .

