Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Drannik> <http://telicent.io/ontology/primaryName> "Drannik" .
<https://starwars.com#planet_Barenth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#sector_Drannik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Barenth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#eee2a10b-15d6-42f3-aae4-4b1d919a088c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Barenth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eee2a10b-15d6-42f3-aae4-4b1d919a088c> .
<https://starwars.com#planet_Barenth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Drannik> .
<https://starwars.com#planet_Barenth> <http://telicent.io/ontology/primaryName> "Barenth" .
<https://starwars.com#planet_Barenth> <http://www.w3.org/2000/01/rdf-schema#comment> "By the time of the New Republic millennia later, the Ho'Din Baji visited an ancient laboratory on Barenth while an ecological disaster was occurring there. The healer eventually resolved to take up permanent residence at the ruins of the laboratory to attempt to reverse the effects of the disaster there. " .
<https://starwars.com#sector_Drannik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#eee2a10b-15d6-42f3-aae4-4b1d919a088c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barenth"^^<http://www.w3.org/2001/XMLSchema#string> .

