Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GravanSeven> <http://www.w3.org/2000/01/rdf-schema#comment> "Gravan Seven was a volcanic planet in the Inner Rim. Its volcanoes polluted the skies, making them hard to navigate. Warlord Zsinj's forces ambushed Talon Squadron there, killing all in the New Republic training squadron, except for the squadron commander, Lieutenant Myn Donos, and his astromech droid Shiner. " .
<https://starwars.com#d34cc4fd-6329-4ae6-b924-82a15ab72aff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_GravanSeven> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d34cc4fd-6329-4ae6-b924-82a15ab72aff> .
<https://starwars.com#planet_GravanSeven> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_GravanSeven> <http://telicent.io/ontology/primaryName> "Gravan Seven" .
<https://starwars.com#planet_GravanSeven> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d34cc4fd-6329-4ae6-b924-82a15ab72aff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gravan Seven"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_GravanSeven> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

