Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c955f524-cf92-4548-aaa6-38a721f7dd00> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Leria Kerlsil"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LeriaKerlsil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_LeriaKerlsil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_LeriaKerlsil> <http://telicent.io/ontology/primaryName> "Leria Kerlsil" .
<https://starwars.com#planet_LeriaKerlsil> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c955f524-cf92-4548-aaa6-38a721f7dd00> .
<https://starwars.com#planet_LeriaKerlsil> <http://www.w3.org/2000/01/rdf-schema#comment> "Leria Kerlsil was a planet in the Core Worlds. It allowed Refugee Relief Movement settlement in 22 BBY, shortly before the Clone Wars, but only by wealthy single men. At the time of the New Republic, the planet had a population of 300,000. Leria Kerlsil was the only planet known to be home to Life-bearers, also known as life-witches. " .
<https://starwars.com#c955f524-cf92-4548-aaa6-38a721f7dd00> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_LeriaKerlsil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

