Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Quence> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Quence> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#5746bddd-3468-4c98-9af2-d4da784e2131> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Suarbi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Suarbi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5746bddd-3468-4c98-9af2-d4da784e2131> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Suarbi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O19> .
<https://starwars.com#planet_Suarbi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5746bddd-3468-4c98-9af2-d4da784e2131> .
<https://starwars.com#planet_Suarbi> <http://www.w3.org/2000/01/rdf-schema#comment> "Suarbi was an astronomical object located in the Outer Rim Territories of the galaxy, and linked to Vohai, Spice Terminus and Svivren. It was positioned at the coordinates O-19 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Suarbi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quence> .
<https://starwars.com#planet_Suarbi> <http://telicent.io/ontology/primaryName> "Suarbi" .
<https://starwars.com#sector_Quence> <http://telicent.io/ontology/primaryName> "Quence" .

