Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d44a3a0b-8a20-4482-b749-cc724b5f4f32> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Elbara> <http://telicent.io/ontology/primaryName> "Elbara" .
<https://starwars.com#sector_Elbaran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Elbaran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Elbara> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#grid_J17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_J17> <http://telicent.io/ontology/primaryName> "J17" .
<https://starwars.com#planet_Elbara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Elbaran> .
<https://starwars.com#planet_Elbara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J17> .
<https://starwars.com#2c6eb183-c021-4d94-9664-42515e16889e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Elbara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d44a3a0b-8a20-4482-b749-cc724b5f4f32> .
<https://starwars.com#grid_J17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#2c6eb183-c021-4d94-9664-42515e16889e> .
<https://starwars.com#2c6eb183-c021-4d94-9664-42515e16889e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_J17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#d44a3a0b-8a20-4482-b749-cc724b5f4f32> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elbara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Elbara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Elbaran> <http://telicent.io/ontology/primaryName> "Elbaran" .

