Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_BannistarStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#sector_Hevvrol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Hevvrol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Hevvrol> <http://telicent.io/ontology/primaryName> "Hevvrol" .
<https://starwars.com#planet_BannistarStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hevvrol> .
<https://starwars.com#b58232d0-6777-494d-919a-46eda5755b44> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bannistar Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BannistarStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Bannistar Station was a location in the Mid Rim of the galaxy, linked to Kalarba and Enarc by hyperspace routes. It was located at the coordinates O-15 on the Standard Galactic Grid. " .
<https://starwars.com#planet_BannistarStation> <http://telicent.io/ontology/primaryName> "Bannistar Station" .
<https://starwars.com#planet_BannistarStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b58232d0-6777-494d-919a-46eda5755b44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_BannistarStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b58232d0-6777-494d-919a-46eda5755b44> .

