Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b8f649aa-db93-470c-8b69-4121341af94e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_M21> <http://telicent.io/ontology/primaryName> "M21" .
<https://starwars.com#planet_KalShebbol> <http://telicent.io/ontology/primaryName> "Kal'Shebbol" .
<https://starwars.com#planet_KalShebbol> <http://www.w3.org/2000/01/rdf-schema#comment> "Kal'Shebbol was a planet located within the galaxy's Outer Rim Territories. It was located close to one end of the Rimma Trade Route, which connected it to the planet Karideph. Cal Alder, an Alliance to Restore the Republic lieutenant, hailed from the planet. " .
<https://starwars.com#grid_M21> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b8f649aa-db93-470c-8b69-4121341af94e> .
<https://starwars.com#grid_M21> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_KalShebbol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M21> .
<https://starwars.com#planet_KalShebbol> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab403818-69d1-426f-b7df-50191198d118> .
<https://starwars.com#sector_Kathol> <http://telicent.io/ontology/primaryName> "Kathol" .
<https://starwars.com#sector_Kathol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_M21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Kathol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KalShebbol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kathol> .
<https://starwars.com#ab403818-69d1-426f-b7df-50191198d118> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ab403818-69d1-426f-b7df-50191198d118> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kal'Shebbol"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b8f649aa-db93-470c-8b69-4121341af94e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M21"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KalShebbol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

