Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Trans-Nebular> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Goroth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_Goroth> <http://telicent.io/ontology/primaryName> "Goroth" .
<https://starwars.com#sector_Trans-Nebular> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Goroth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c1a67163-71a1-48a3-816e-94eda83fb4c6> .
<https://starwars.com#sector_Trans-Nebular> <http://telicent.io/ontology/primaryName> "Trans-Nebular" .
<https://starwars.com#planet_Goroth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trans-Nebular> .
<https://starwars.com#planet_Goroth> <http://www.w3.org/2000/01/rdf-schema#comment> "Goroth, also known as Goroth Prime, was a location in the galaxy. When Agent Alecia Beck of the Imperial Security Bureau requested a meeting with Senator Mon Mothma, Mothma's aide, Hendri Underholt, lied to Beck and told her that Mothma had already left Coruscant and had gone on a fact-finding mission to Goroth. " .
<https://starwars.com#c1a67163-71a1-48a3-816e-94eda83fb4c6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Goroth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Goroth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c1a67163-71a1-48a3-816e-94eda83fb4c6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

