Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#9b0a1a3a-1a53-4ad5-a37b-3c5f7cdcc78c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cyimarra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cyimarra> <http://www.w3.org/2000/01/rdf-schema#comment> "Cyimarra was famous for the Crystal Spires, a series of ancient towers of uniform height that were evenly spaced across the planet's surface. By 0 ABY, the planets Corellia and Corulag sent delegations to Cyimarra, and it was speculated that they would present a recreation of the Crystal Spires on the planet Coruscant during the festivities of that year's New Year Fete Week. " .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cyimarra> <http://telicent.io/ontology/primaryName> "Cyimarra" .
<https://starwars.com#planet_Cyimarra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Cyimarra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cyimarra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9b0a1a3a-1a53-4ad5-a37b-3c5f7cdcc78c> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Cyimarra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#9b0a1a3a-1a53-4ad5-a37b-3c5f7cdcc78c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

