Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5a66a370-dccc-4d1a-8a34-97347c66203f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5a66a370-dccc-4d1a-8a34-97347c66203f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gorse"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gorse> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5a66a370-dccc-4d1a-8a34-97347c66203f> .
<https://starwars.com#planet_Gorse> <http://www.w3.org/2000/01/rdf-schema#comment> "Gorse (pronounced /gɔːɹs/) was a tidally-locked planet located on the Inner Rim. It had one moon called Cynda, which was rich in thorilide crystals. During the Age of the Empire, Gorse had seemingly exhausted its thorilide reserves and had become a major refinery for thorilide exports from Cynda, which had been opened up to thorilide mining. Gorse served as the location of a conflict between the Galactic Empire and a small rebel cell led by Hera Syndulla and the former Jedi Padawan Kanan Jarrus. Following the Gorse conflict, thorilide mining was established in Gorse's sunward side while Cynda was restored to its former status as a nature reserve. " .
<https://starwars.com#planet_Gorse> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Gorse> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#planet_Gorse> <http://telicent.io/ontology/primaryName> "Gorse" .
<https://starwars.com#planet_Gorse> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

