Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NalHutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_NalHutta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b7e79960-e821-4aa7-bbcd-28cbe45418b5> .
<https://starwars.com#planet_NalHutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_NalHutta> <http://www.w3.org/2000/01/rdf-schema#comment> "Home planet of Jabba and other Hutts. Close to the urban moon of Nar Shaddaa." .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b7e79960-e821-4aa7-bbcd-28cbe45418b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NalHutta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b7e79960-e821-4aa7-bbcd-28cbe45418b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nal Hutta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NalHutta> <http://telicent.io/ontology/primaryName> "Nal Hutta" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

