Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#a81f7d6a-1864-4e32-b36d-170d9ffdbde9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MonCalamari> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a81f7d6a-1864-4e32-b36d-170d9ffdbde9> .
<https://starwars.com#planet_MonCalamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a81f7d6a-1864-4e32-b36d-170d9ffdbde9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mon Calamari"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_MonCalamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_MonCalamari> <http://telicent.io/ontology/primaryName> "Mon Calamari" .
<https://starwars.com#planet_MonCalamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MonCalamari> <http://www.w3.org/2000/01/rdf-schema#comment> "The Mon Calamari (also known as Mon Calamarians) were a humanoid, aquatic species native to the planet of Mon Cala. They shared their home planet with the Quarren. " .

