Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b9d0b3c5-3680-4135-b89d-412d11dfa8f7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Taldot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Charros> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b9d0b3c5-3680-4135-b89d-412d11dfa8f7> .
<https://starwars.com#planet_Charros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R9> .
<https://starwars.com#planet_Charros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Taldot> .
<https://starwars.com#planet_Charros> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Charros> <http://telicent.io/ontology/primaryName> "Charros" .
<https://starwars.com#sector_Taldot> <http://telicent.io/ontology/primaryName> "Taldot" .
<https://starwars.com#b9d0b3c5-3680-4135-b89d-412d11dfa8f7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Charros"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Charros> <http://www.w3.org/2000/01/rdf-schema#comment> "Charros was the primary star of the Charros system. " .
<https://starwars.com#sector_Taldot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

