Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Joiol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Orus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Joiol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#planet_Joiol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Orus> .
<https://starwars.com#1b450ff8-11f6-4e68-9572-d195447a576c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Joiol"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Joiol> <http://telicent.io/ontology/primaryName> "Joiol" .
<https://starwars.com#sector_Orus> <http://telicent.io/ontology/primaryName> "Orus" .
<https://starwars.com#planet_Joiol> <http://www.w3.org/2000/01/rdf-schema#comment> "Joiol was a planet located in the Orus sector of the Inner Rim that teemed with life. " .
<https://starwars.com#sector_Orus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Joiol> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1b450ff8-11f6-4e68-9572-d195447a576c> .
<https://starwars.com#1b450ff8-11f6-4e68-9572-d195447a576c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

