Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dornea> <http://telicent.io/ontology/primaryName> "Dornea" .
<https://starwars.com#planet_Dornea> <http://www.w3.org/2000/01/rdf-schema#comment> "Dornea was the homeworld of the Dornean species. The native species designed the Braha'tok-class gunship, which were manufactured by the Dornean Braha'ket Fleetworks Conglomerate to protect Dornea from the Galactic Empire Some of these gunships saw service with the Rebel Alliance during the early rebellion against the Empire. After the Alliance secured a decisive victory at the Battle of Yavin, Dornea joined their cause and brought more Braha'tok-class gunships with them. " .
<https://starwars.com#planet_Dornea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dominus> .
<https://starwars.com#planet_Dornea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dornea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#de21733d-e01a-4943-879c-3cc64b63a840> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dornea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dornea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#de21733d-e01a-4943-879c-3cc64b63a840> .
<https://starwars.com#de21733d-e01a-4943-879c-3cc64b63a840> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dominus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Dominus> <http://telicent.io/ontology/primaryName> "Dominus" .
<https://starwars.com#sector_Dominus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

