Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hewett> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hewett> .
<https://starwars.com#sector_Hewett> <http://telicent.io/ontology/primaryName> "Hewett" .
<https://starwars.com#planet_Hewett> <http://telicent.io/ontology/primaryName> "Hewett" .
<https://starwars.com#planet_Hewett> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3f4c888c-1ddd-479f-8484-1dc796e97907> .
<https://starwars.com#planet_Hewett> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hewett> <http://www.w3.org/2000/01/rdf-schema#comment> "The Hewett were a non-humanoid, sentient species from the Hewett system. In 34 BBY, an official banquet was held for Hewett senators, at which Konkeel pie was served on the menu. The pie was toxic to humanoids, and the Jedi Master Qui-Gon Jinn almost ate some before his contemporary Adi Gallia stopped him. " .
<https://starwars.com#sector_Hewett> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Hewett> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3f4c888c-1ddd-479f-8484-1dc796e97907> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3f4c888c-1ddd-479f-8484-1dc796e97907> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hewett"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hewett> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .

