Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ando> <http://telicent.io/ontology/primaryName> "Ando" .
<https://starwars.com#sector_Lambda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Lambda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c951446f-298e-40a3-ae9b-223924b86793> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ando> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lambda> .
<https://starwars.com#planet_Ando> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q15> .
<https://starwars.com#planet_Ando> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c951446f-298e-40a3-ae9b-223924b86793> .
<https://starwars.com#planet_Ando> <http://www.w3.org/2000/01/rdf-schema#comment> "A water-covered planet located in the Outer Rim, it is home to the amphibious Aqualish species and endures great turmoil during the Separatist Crisis." .
<https://starwars.com#planet_Ando> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c951446f-298e-40a3-ae9b-223924b86793> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ando"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lambda> <http://telicent.io/ontology/primaryName> "Lambda" .

