Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Quence> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_ElshandruuPica> <http://www.w3.org/2000/01/rdf-schema#comment> "Elshandruu Pica was a planet in the Elshandruu system of the Quence sector, in the Outer Rim. " .
<https://starwars.com#grid_O18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_ElshandruuPica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O18> .
<https://starwars.com#planet_ElshandruuPica> <http://telicent.io/ontology/primaryName> "Elshandruu Pica" .
<https://starwars.com#sector_Quence> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f8193948-610d-4441-afce-68454b4dde3e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#dbf86735-aa65-4c5d-809c-5dc2340251d7> .
<https://starwars.com#planet_ElshandruuPica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f8193948-610d-4441-afce-68454b4dde3e> .
<https://starwars.com#planet_ElshandruuPica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_O18> <http://telicent.io/ontology/primaryName> "O18" .
<https://starwars.com#f8193948-610d-4441-afce-68454b4dde3e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elshandruu Pica"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ElshandruuPica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quence> .
<https://starwars.com#dbf86735-aa65-4c5d-809c-5dc2340251d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#dbf86735-aa65-4c5d-809c-5dc2340251d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Quence> <http://telicent.io/ontology/primaryName> "Quence" .

