Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Authala> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mordagon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#planet_Mordagon> <http://www.w3.org/2000/01/rdf-schema#comment> "Mordagon was a planet in the Expansion Region, and was the homeworld of the Mordageen, bipedal sentients that had pink skin and pointy ears. One Mordageen from Mordagon was Bendix Fust, who became a smuggler working for the Dug crime lord Sebolto. " .
<https://starwars.com#planet_Mordagon> <http://telicent.io/ontology/primaryName> "Mordagon" .
<https://starwars.com#3047ed7a-4ab3-4e76-a39e-644cedf2e453> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mordagon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Authala> <http://telicent.io/ontology/primaryName> "Authala" .
<https://starwars.com#sector_Authala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#3047ed7a-4ab3-4e76-a39e-644cedf2e453> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mordagon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mordagon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3047ed7a-4ab3-4e76-a39e-644cedf2e453> .
<https://starwars.com#planet_Mordagon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Authala> .

