Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chamm> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Chamm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#95ff30ed-4c71-4d3d-84fb-8079b1ef2555> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Chamm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95ff30ed-4c71-4d3d-84fb-8079b1ef2555> .
<https://starwars.com#planet_Chamm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Chamm> <http://telicent.io/ontology/primaryName> "Chamm" .
<https://starwars.com#planet_Chamm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#95ff30ed-4c71-4d3d-84fb-8079b1ef2555> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chamm"^^<http://www.w3.org/2001/XMLSchema#string> .

