Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_YagaMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prefsbelt> .
<https://starwars.com#planet_YagaMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89e5ceba-e984-4185-9bb7-0b5ed53ee772> .
<https://starwars.com#planet_YagaMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#89e5ceba-e984-4185-9bb7-0b5ed53ee772> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yaga Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_YagaMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Yaga Minor was an industrialized planet located in the galaxy's Outer Rim Territories where shipyards were located. In 14 BBY, members of the Free Ryloth Movement rebel cell, led by the Twi'lek Pok, hijacked an Imperial weapons shipment at the Yaga Minor shipyards and fled into hyperspace. The incident was reported to the Dark Lord of the Sith Darth Vader by the Imperial Captain Luitt of the Imperial-class Star Destroyer Perilous, and Vader pursued and slaughtered Pok and his crew. " .
<https://starwars.com#sector_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .
<https://starwars.com#planet_YagaMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#89e5ceba-e984-4185-9bb7-0b5ed53ee772> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_YagaMinor> <http://telicent.io/ontology/primaryName> "Yaga Minor" .
<https://starwars.com#sector_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

