Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shumavar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L19> .
<https://starwars.com#sector_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#planet_Shumavar> <http://www.w3.org/2000/01/rdf-schema#comment> "Shumavar was an astronomical object located in the galaxy's Outer Rim Territories, situated along the Hydian Way. " .
<https://starwars.com#planet_Shumavar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atravis> .
<https://starwars.com#b3e0fbef-4a77-4f55-9e0f-bab99bfe2f45> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shumavar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shumavar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b3e0fbef-4a77-4f55-9e0f-bab99bfe2f45> .
<https://starwars.com#sector_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b3e0fbef-4a77-4f55-9e0f-bab99bfe2f45> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shumavar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shumavar> <http://telicent.io/ontology/primaryName> "Shumavar" .

