Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Veron> <http://www.w3.org/2000/01/rdf-schema#comment> "Veron was a terrestrial astronomical object where the species known as Gwerax-hai were captured, typically using net-throwers. The Rebel Alliance's 61st Mobile Infantry held an open recruiting drive on Veron sometime by the year 0 BBY. At the recruiting drive, the bounty hunter Brand joined the infantry company in an attempt to get close enough to Captain Micha Evon to assassinate him for his bounty. Lying about her identity, the bounty hunter smuggled her kit onto the 61st's CR90 corvette, the Thunderstrike. " .
<https://starwars.com#5e7707e6-a2c4-488b-87dd-cd04cb96e59c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Veron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Veron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Veron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Veron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#5e7707e6-a2c4-488b-87dd-cd04cb96e59c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Veron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5e7707e6-a2c4-488b-87dd-cd04cb96e59c> .
<https://starwars.com#planet_Veron> <http://telicent.io/ontology/primaryName> "Veron" .

