Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#67afd5fb-24f2-43b2-88f7-af97b5f79d15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Utaruun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#67afd5fb-24f2-43b2-88f7-af97b5f79d15> .
<https://starwars.com#planet_Utaruun> <http://www.w3.org/2000/01/rdf-schema#comment> "Utaruun was a terrestrial planet located in the Utaruun system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. Utaruun was located on the Old Corellian Run hyperlane between the Austan and Tatoo systems. " .
<https://starwars.com#planet_Utaruun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#67afd5fb-24f2-43b2-88f7-af97b5f79d15> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Utaruun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Utaruun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Utaruun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Utaruun> <http://telicent.io/ontology/primaryName> "Utaruun" .

