Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Neshig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#b193f419-09ef-4c2e-9828-9c2e0f6942e5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b193f419-09ef-4c2e-9828-9c2e0f6942e5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corvanni IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CorvanniIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b193f419-09ef-4c2e-9828-9c2e0f6942e5> .
<https://starwars.com#planet_CorvanniIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Neshig> .
<https://starwars.com#planet_CorvanniIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_CorvanniIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Neshig> <http://telicent.io/ontology/primaryName> "Neshig" .
<https://starwars.com#planet_CorvanniIV> <http://telicent.io/ontology/primaryName> "Corvanni IV" .
<https://starwars.com#sector_Neshig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_CorvanniIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Corvanni IV was an astronomical object that occupied the fourth orbital position in the Corvanni system, a part of the Neshig sector in the Slice portion of the Inner Rim. It was located near the Vorsia system, the origin point of the Vorsian crystal. " .

