Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cf52f4af-903b-4d87-9fef-9f59555a3e37> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Torque"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Torque> <http://telicent.io/ontology/primaryName> "Torque" .
<https://starwars.com#cf52f4af-903b-4d87-9fef-9f59555a3e37> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Torque> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Torque> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Torque> <http://www.w3.org/2000/01/rdf-schema#comment> "Torque ('Torqua-na' in Huttese) was a planet located within the Torque system of the Outer Rim Territories and the sector capital of the Gordian Reach. A lackluster industrial world, it was the headquarters of Bwahl the Hutt. " .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Torque> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf52f4af-903b-4d87-9fef-9f59555a3e37> .
<https://starwars.com#planet_Torque> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

