Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#44e0d052-c849-40c3-af8b-b2f54b9cd304> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corellia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Corellia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#44e0d052-c849-40c3-af8b-b2f54b9cd304> .
<https://starwars.com#planet_Corellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Corellia> <http://telicent.io/ontology/primaryName> "Corellia" .
<https://starwars.com#44e0d052-c849-40c3-af8b-b2f54b9cd304> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Corellia> <http://www.w3.org/2000/01/rdf-schema#comment> "Industrial planet located in the Core of the galaxy, with a strong culture of training pilots. Homeworld of Han Solo and Qi'ra." .
<https://starwars.com#planet_Corellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Corellia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

