Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Nojic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vena> <http://telicent.io/ontology/primaryName> "Vena" .
<https://starwars.com#planet_Vena> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Nojic> <http://telicent.io/ontology/primaryName> "Nojic" .
<https://starwars.com#planet_Vena> <http://www.w3.org/2000/01/rdf-schema#comment> "Vena was an astronomical object located in the Expansion Region of the galaxy. " .
<https://starwars.com#planet_Vena> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#cf5acca4-8b8d-472a-b343-8b5dbf9f57c5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vena> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf5acca4-8b8d-472a-b343-8b5dbf9f57c5> .
<https://starwars.com#cf5acca4-8b8d-472a-b343-8b5dbf9f57c5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vena"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Nojic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Vena> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nojic> .

