Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Von-Alai> <http://www.w3.org/2000/01/rdf-schema#comment> "Von-Alai was a planet in the Von-Alai system of the Expansion Region, polluted by Kontag factories. " .
<https://starwars.com#planet_Von-Alai> <http://telicent.io/ontology/primaryName> "Von-Alai" .
<https://starwars.com#planet_Von-Alai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Locris> .
<https://starwars.com#planet_Von-Alai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#3f4ccba1-04c8-4cb2-9c45-1fd3d9852473> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Von-Alai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3f4ccba1-04c8-4cb2-9c45-1fd3d9852473> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Von-Alai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Von-Alai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3f4ccba1-04c8-4cb2-9c45-1fd3d9852473> .
<https://starwars.com#sector_Locris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Locris> <http://telicent.io/ontology/primaryName> "Locris" .
<https://starwars.com#sector_Locris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

