Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nentan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K7> .
<https://starwars.com#sector_Clythe> <http://telicent.io/ontology/primaryName> "Clythe" .
<https://starwars.com#sector_Clythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nentan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nentan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clythe> .
<https://starwars.com#aa82044c-3e5f-4fbe-a65d-0910a5d57def> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nentan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nentan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aa82044c-3e5f-4fbe-a65d-0910a5d57def> .
<https://starwars.com#sector_Clythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nentan> <http://telicent.io/ontology/primaryName> "Nentan" .
<https://starwars.com#aa82044c-3e5f-4fbe-a65d-0910a5d57def> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nentan> <http://www.w3.org/2000/01/rdf-schema#comment> "Nentan was a terrestrial planet located in the Nentan system of the Glythe sector. Nentan was a barren planet, and the main point of interest was the ancient ruins of a city built by an unknown alien species. During the Galactic Civil War, Nentan briefly hosted an Alliance base. The facility was evacuated after being discovered two months after going operational. Captain Bren Derlin's actions during the evacuation earned him a promotion to the rank of Major. " .

