Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Circarpous> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Gyndine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gyndine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Circarpous> .
<https://starwars.com#planet_Gyndine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#sector_Circarpous> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c0107128-28a6-4683-997a-b8f4a91cc18d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gyndine> <http://telicent.io/ontology/primaryName> "Gyndine" .
<https://starwars.com#planet_Gyndine> <http://www.w3.org/2000/01/rdf-schema#comment> "Around 5 ABY, a Pyke Syndicate mole reported to New Republic Intelligence that an Imperial Quasar Fire-class cruiser carrier had gone to the Gyndine shipyards seeking assistance. The report was reviewed by New Republic Intelligence agent Caern Adan and his colleague Yrica Quell, who were trying to track down the Empire's 204th Imperial Fighter Wing. Quell found the source reliable but felt that the information was insufficient for their goal, and so marked the sighting with medium-confidence. " .
<https://starwars.com#c0107128-28a6-4683-997a-b8f4a91cc18d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gyndine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gyndine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c0107128-28a6-4683-997a-b8f4a91cc18d> .
<https://starwars.com#sector_Circarpous> <http://telicent.io/ontology/primaryName> "Circarpous" .

