Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kaal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kaal> <http://www.w3.org/2000/01/rdf-schema#comment> "Kaal was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Kaal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#32b5adaf-89e4-423a-8129-a287900ea0e4> .
<https://starwars.com#sector_Yushan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yushan> <http://telicent.io/ontology/primaryName> "Yushan" .
<https://starwars.com#32b5adaf-89e4-423a-8129-a287900ea0e4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Yushan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yushan> .
<https://starwars.com#planet_Kaal> <http://telicent.io/ontology/primaryName> "Kaal" .
<https://starwars.com#planet_Kaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#32b5adaf-89e4-423a-8129-a287900ea0e4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kaal"^^<http://www.w3.org/2001/XMLSchema#string> .

