Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Langoona> <http://www.w3.org/2000/01/rdf-schema#comment> "Langoona was a remote world located in the Bootana Hutta region of Hutt Space. " .
<https://starwars.com#d7028056-40bb-4241-a7d3-980651ec01ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Langoona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#d7028056-40bb-4241-a7d3-980651ec01ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Langoona"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Langoona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7028056-40bb-4241-a7d3-980651ec01ef> .
<https://starwars.com#planet_Langoona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#planet_Langoona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Langoona> <http://telicent.io/ontology/primaryName> "Langoona" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

