Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kiva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Venaarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#780f03ed-a1fd-4b45-8207-3ed4ce3ac928> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#780f03ed-a1fd-4b45-8207-3ed4ce3ac928> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kiva"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kiva> <http://telicent.io/ontology/primaryName> "Kiva" .
<https://starwars.com#planet_Kiva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#planet_Kiva> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#780f03ed-a1fd-4b45-8207-3ed4ce3ac928> .
<https://starwars.com#planet_Kiva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Venaarian> .
<https://starwars.com#sector_Venaarian> <http://telicent.io/ontology/primaryName> "Venaarian" .
<https://starwars.com#planet_Kiva> <http://www.w3.org/2000/01/rdf-schema#comment> "Kiva was a planet that was located within the Mid Rim. Its indigenous Kivan people were wiped out by Project Starscream, to the utter horror of Shi'ido anthropologist Mammon Hoole. The only remnants of the people were shadowy wraiths. " .
<https://starwars.com#sector_Venaarian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

