Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#469199d4-e393-42e3-9549-3677b1faba1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Naboo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Naboo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chommel> .
<https://starwars.com#planet_Naboo> <http://telicent.io/ontology/primaryName> "Naboo" .
<https://starwars.com#planet_Naboo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#469199d4-e393-42e3-9549-3677b1faba1b> .
<https://starwars.com#planet_Naboo> <http://www.w3.org/2000/01/rdf-schema#comment> "Home planet of the Gungans, including Jar-Jar Binks, and various humans, who compose a civilization called the Naboo, which includes Padmé Amidala and Emperor Palpatine." .
<https://starwars.com#planet_Naboo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#sector_Chommel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Chommel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Chommel> <http://telicent.io/ontology/primaryName> "Chommel" .
<https://starwars.com#469199d4-e393-42e3-9549-3677b1faba1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Naboo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

