Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#82100d44-6ad0-419e-a4ef-67cde93529c1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vladet"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vladet> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#82100d44-6ad0-419e-a4ef-67cde93529c1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vladet> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Vladet> <http://www.w3.org/2000/01/rdf-schema#comment> "Vladet was a planet in the Colonies. It was the sector capital of Rachuk sector. An Imperial base was located on Grand Isle. Without vaccination, any visitor to the planet would catch Rachuk Roseola. When Rogue Squadron attacked the planet, Imperial Admiral Devlia was killed. " .
<https://starwars.com#planet_Vladet> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82100d44-6ad0-419e-a4ef-67cde93529c1> .
<https://starwars.com#planet_Vladet> <http://telicent.io/ontology/primaryName> "Vladet" .
<https://starwars.com#planet_Vladet> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

