Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c6b1d97d-afa3-4564-b07d-d0024a63f665> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Reginard"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Reginard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Reginard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#planet_Reginard> <http://www.w3.org/2000/01/rdf-schema#comment> "Reginard was the location of a hidden Rebel base called Reginard Base. " .
<https://starwars.com#planet_Reginard> <http://telicent.io/ontology/primaryName> "Reginard" .
<https://starwars.com#planet_Reginard> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c6b1d97d-afa3-4564-b07d-d0024a63f665> .
<https://starwars.com#c6b1d97d-afa3-4564-b07d-d0024a63f665> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Reginard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .

