Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mogoshyn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#153c9d92-d3d3-4cd6-8dd8-79ac6e744d1b> .
<https://starwars.com#153c9d92-d3d3-4cd6-8dd8-79ac6e744d1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mogoshyn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mogoshyn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mogoshyn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_Mogoshyn> <http://www.w3.org/2000/01/rdf-schema#comment> "Mogoshyn was a run-down industrial world located in the Mogoshyn system, a part of the Gordian Reach sector in the Trans-Hydian portion of the Outer Rim Territories. The world lay between the Betshish and Kushibah systems on the Pinooran Spur hyperlane. " .
<https://starwars.com#planet_Mogoshyn> <http://telicent.io/ontology/primaryName> "Mogoshyn" .
<https://starwars.com#153c9d92-d3d3-4cd6-8dd8-79ac6e744d1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mogoshyn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

