Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ca49fc55-e976-431f-a907-9c99eb474ac3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca49fc55-e976-431f-a907-9c99eb474ac3> .
<https://starwars.com#planet_Hok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#ca49fc55-e976-431f-a907-9c99eb474ac3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hok> <http://telicent.io/ontology/primaryName> "Hok" .
<https://starwars.com#planet_Hok> <http://www.w3.org/2000/01/rdf-schema#comment> "Hok was an astronomical object located in the galaxy's Colonies region that was the homeworld of the Gran podracer Mawhonic. " .
<https://starwars.com#planet_Hok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Hok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

