Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Broest> <http://www.w3.org/2000/01/rdf-schema#comment> "Broest was a location from which ruica seeds were transported across the galaxy to the planet Alderaan for farmers to grow. When, during her childhood, Princess Leia Organa would not eat ruica, her father Bail Organa told her about the seeds being brought to Alderaan from Broest in order to convince her. " .
<https://starwars.com#18084632-bdbe-4d12-a602-61013f09372b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Broest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Broest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Broest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#18084632-bdbe-4d12-a602-61013f09372b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Broest"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Broest> <http://telicent.io/ontology/primaryName> "Broest" .
<https://starwars.com#planet_Broest> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#18084632-bdbe-4d12-a602-61013f09372b> .

