Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bosph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bosph> .
<https://starwars.com#sector_Bosph> <http://telicent.io/ontology/primaryName> "Bosph" .
<https://starwars.com#ccf79662-cfb8-423b-b61a-7a52aae8d9dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_Q3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#188e5f84-b293-48dd-9652-038fa8b0d903> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bosph> <http://telicent.io/ontology/primaryName> "Bosph" .
<https://starwars.com#sector_Bosph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_Q3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ccf79662-cfb8-423b-b61a-7a52aae8d9dd> .
<https://starwars.com#planet_Bosph> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bosph> <http://www.w3.org/2000/01/rdf-schema#comment> "One of the most famous Bosphs in the galaxy was the smuggler Bora Boru who worked during the reign of the Galactic Empire. Another Bosph during this period worked as a bounty hunter and answered Darth Vader's call to hunt the Corellian smuggler and Rebel Han Solo and his ship, the Millennium Falcon. During the reign of the New Republic, a Bosph named Morga Bunna opened a supply depot on Bosph's outermost moon after retiring from work as a bounty hunter. Bunna was questioned by the Jedi archivist Mander Zuma during the Jedi's quest to shut down the Tempest spice trade. " .
<https://starwars.com#grid_Q3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Bosph> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bosph> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#188e5f84-b293-48dd-9652-038fa8b0d903> .
<https://starwars.com#ccf79662-cfb8-423b-b61a-7a52aae8d9dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bosph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q3> .
<https://starwars.com#188e5f84-b293-48dd-9652-038fa8b0d903> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bosph"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q3> <http://telicent.io/ontology/primaryName> "Q3" .

