Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_R16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#1ab7a0fd-21ef-4677-9f73-45f633238798> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_A-Foroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#region_OuterRim> <http://telicent.io/ontology/primaryName> "Outer Rim" .
<https://starwars.com#region_OuterRim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#AGalaxyFarFarAway> <http://telicent.io/ontology/primaryName> "A Galaxy Far Far Away" .
<https://starwars.com#planet_A-Foroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1ab7a0fd-21ef-4677-9f73-45f633238798> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_A-Foroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1ab7a0fd-21ef-4677-9f73-45f633238798> <http://ies.data.gov.uk/ontology/ies4#representationValue> "A-Foroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8b0dc462-9d8a-49b6-bc04-62d95eb4cb74> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#region_OuterRim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_A-Foroon> <http://telicent.io/ontology/primaryName> "A-Foroon" .
<https://starwars.com#planet_A-Foroon> <http://www.w3.org/2000/01/rdf-schema#comment> "A-Foroon was the homeworld of the Hutt Arok. " .
<https://starwars.com#grid_R16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_R16> <http://telicent.io/ontology/primaryName> "R16" .
<https://starwars.com#grid_R16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8b0dc462-9d8a-49b6-bc04-62d95eb4cb74> .
<https://starwars.com#8b0dc462-9d8a-49b6-bc04-62d95eb4cb74> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#AGalaxyFarFarAway> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Galaxy> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_A-Foroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .

