Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LothoMinor> <http://telicent.io/ontology/primaryName> "Lotho Minor" .
<https://starwars.com#planet_LothoMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#cb88614a-4322-4955-ace4-608dd016e3c5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lotho Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LothoMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_LothoMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "A planetary junkyard and hiding place of Darth Maul after his presumed death." .
<https://starwars.com#sector_Wazta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#cb88614a-4322-4955-ace4-608dd016e3c5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Wazta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_LothoMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wazta> .
<https://starwars.com#sector_Wazta> <http://telicent.io/ontology/primaryName> "Wazta" .
<https://starwars.com#planet_LothoMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cb88614a-4322-4955-ace4-608dd016e3c5> .

