Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rinn> <http://www.w3.org/2000/01/rdf-schema#comment> "Rinn was an ice planet located in the Outer Rim Territories. Around 4 BBY, the people of Rinn faced an energy crisis: once their dwindling supply of fuel cells had run out, they would be unable to power the heaters necessary for their survival. This predicament prompted rebel commander Jun Sato to task the Spectres with acquiring more generators. " .
<https://starwars.com#c08fb785-1d0d-4b10-84a2-3409365d8abc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c08fb785-1d0d-4b10-84a2-3409365d8abc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rinn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .
<https://starwars.com#planet_Rinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .
<https://starwars.com#planet_Rinn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c08fb785-1d0d-4b10-84a2-3409365d8abc> .
<https://starwars.com#planet_Rinn> <http://telicent.io/ontology/primaryName> "Rinn" .

