Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9b979b78-e2a3-42bd-a203-40e643e6e256> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Paulking> <http://telicent.io/ontology/primaryName> "Paulking" .
<https://starwars.com#planet_Paulking> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Paulking> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Paulking> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9b979b78-e2a3-42bd-a203-40e643e6e256> .
<https://starwars.com#9b979b78-e2a3-42bd-a203-40e643e6e256> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Paulking"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Paulking> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Paulking> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

