Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Brigia> <http://www.w3.org/2000/01/rdf-schema#comment> "Brigia was a location in the galaxy that served as an Alliance to Restore the Republic regional headquarters and operations sector during the early rebellion against the Galactic Empire. Brigia was included in a map of the galaxy that listed safe worlds, starfighter hubs at level five or higher, regional headquarters and operations sectors, and deep space caches. " .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ea735522-5e3c-45a0-8c29-d24a6fc9b8cc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_T6> <http://telicent.io/ontology/primaryName> "T6" .
<https://starwars.com#planet_Brigia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7d01d1d1-012d-497a-b2eb-1f231864bcba> .
<https://starwars.com#planet_Brigia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ea735522-5e3c-45a0-8c29-d24a6fc9b8cc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Brigia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#planet_Brigia> <http://telicent.io/ontology/primaryName> "Brigia" .
<https://starwars.com#grid_T6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ea735522-5e3c-45a0-8c29-d24a6fc9b8cc> .
<https://starwars.com#grid_T6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Brigia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#7d01d1d1-012d-497a-b2eb-1f231864bcba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_T6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#7d01d1d1-012d-497a-b2eb-1f231864bcba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Brigia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

