Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vensensor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f4685318-e1f0-47d1-b067-42ee1742429e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Calonica"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Calonica> <http://www.w3.org/2000/01/rdf-schema#comment> "Calonica was an Imperial planet. The planet's capital was surrounded by 50,000 LX-2 comlink mines, but a spot inspection found that less than ten percent of the mines contained explosive charges. An investigation revealed that the Alliance to Restore the Republic had discovered the mine's comm code and disarmed them remotely. Then they were dug up, the explosives removed, and buried back in the ground. " .
<https://starwars.com#planet_Calonica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Calonica> <http://telicent.io/ontology/primaryName> "Calonica" .
<https://starwars.com#planet_Calonica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f4685318-e1f0-47d1-b067-42ee1742429e> .
<https://starwars.com#sector_Vensensor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#f4685318-e1f0-47d1-b067-42ee1742429e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Vensensor> <http://telicent.io/ontology/primaryName> "Vensensor" .
<https://starwars.com#planet_Calonica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vensensor> .
<https://starwars.com#planet_Calonica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .

