Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Elbaran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Elbaran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Porchello> <http://www.w3.org/2000/01/rdf-schema#comment> "Porchello was a planet in the Elbaran sector of the Mid Rim. " .
<https://starwars.com#14aa64b8-a152-478d-886c-9484f62d6b7a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#14aa64b8-a152-478d-886c-9484f62d6b7a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Porchello"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Porchello> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Porchello> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Elbaran> .
<https://starwars.com#planet_Porchello> <http://telicent.io/ontology/primaryName> "Porchello" .
<https://starwars.com#planet_Porchello> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J17> .
<https://starwars.com#planet_Porchello> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#14aa64b8-a152-478d-886c-9484f62d6b7a> .
<https://starwars.com#sector_Elbaran> <http://telicent.io/ontology/primaryName> "Elbaran" .

