Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3a7f0138-ba70-46b0-b545-d25296491ee8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Aruza> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Aruza> <http://www.w3.org/2000/01/rdf-schema#comment> "Aruza was a planet orbited by five moons of pale shades of tan, silver, and green. The planet was home to the peaceful Aruzans, an even-tempered society that abhorred violence. By 3 ABY, Aruza had not experienced a murder for over one hundred of their years. They were small people with light blue skin and very dark blue hair. " .
<https://starwars.com#6bc1fa5a-dd93-4a64-96e4-d850bbfc0671> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_I14> <http://telicent.io/ontology/primaryName> "I14" .
<https://starwars.com#grid_I14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Aruza> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6bc1fa5a-dd93-4a64-96e4-d850bbfc0671> .
<https://starwars.com#planet_Aruza> <http://telicent.io/ontology/primaryName> "Aruza" .
<https://starwars.com#grid_I14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#6bc1fa5a-dd93-4a64-96e4-d850bbfc0671> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aruza"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aruza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#grid_I14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3a7f0138-ba70-46b0-b545-d25296491ee8> .
<https://starwars.com#planet_Aruza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I14> .
<https://starwars.com#3a7f0138-ba70-46b0-b545-d25296491ee8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I14"^^<http://www.w3.org/2001/XMLSchema#string> .

