Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Vex> <http://www.w3.org/2000/01/rdf-schema#comment> "Vex was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. A hyperspace route linked it to the celestial body Vasha. Vex was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#ba2acb1b-02e6-49ca-a17d-023173f1fbf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ba2acb1b-02e6-49ca-a17d-023173f1fbf0> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#ba2acb1b-02e6-49ca-a17d-023173f1fbf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_Vex> <http://telicent.io/ontology/primaryName> "Vex" .

