Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ylix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Mshinni> <http://telicent.io/ontology/primaryName> "M'shinni" .
<https://starwars.com#planet_Ylix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_Ylix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4a3ab2d-0470-4ed1-8e0a-7a05ea4d52bf> .
<https://starwars.com#sector_Mshinni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ylix> <http://telicent.io/ontology/primaryName> "Ylix" .
<https://starwars.com#b4a3ab2d-0470-4ed1-8e0a-7a05ea4d52bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mshinni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#b4a3ab2d-0470-4ed1-8e0a-7a05ea4d52bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ylix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ylix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mshinni> .
<https://starwars.com#planet_Ylix> <http://www.w3.org/2000/01/rdf-schema#comment> "Ylix was a backwater Mid Rim planet located in the Ylix system between Anobis and Ithor. It was a long-time rival of nearby Goelitz, which it finally defeated in battle. It was also the home of the mercenary Gallandro. " .

