Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lovola> <http://telicent.io/ontology/primaryName> "Lovola" .
<https://starwars.com#2f88c8d9-5bb7-44a4-bc20-3117bb814ac3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lovola> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Lovola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Lovola> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2f88c8d9-5bb7-44a4-bc20-3117bb814ac3> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Lovola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Lovola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#2f88c8d9-5bb7-44a4-bc20-3117bb814ac3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lovola"^^<http://www.w3.org/2001/XMLSchema#string> .

