Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sembla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#sector_Sertar> <http://telicent.io/ontology/primaryName> "Sertar" .
<https://starwars.com#sector_Sertar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sembla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sertar> .
<https://starwars.com#sector_Sertar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#4065ed4e-ebc4-4e13-a82b-8195a735fa44> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sembla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sembla> <http://telicent.io/ontology/primaryName> "Sembla" .
<https://starwars.com#4065ed4e-ebc4-4e13-a82b-8195a735fa44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sembla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sembla> <http://www.w3.org/2000/01/rdf-schema#comment> "Sembla, formerly known as Utavurk, was a planet located in Mahrusha sector within the Outer Rim Territories. It was the homeworld of the Vurk, including Jedi Master Coleman Trebor. Sembla had four moons, which kept it tidally and tectonically active, and its terrain was made up of shallow seas and volcanic islands. The planet was located far from any major trade routes and, as such, was rarely traveled to. However, the Galactic Empire established a research base on the world and pressed native Vurk into cheap labor in strip-mining operations. " .
<https://starwars.com#planet_Sembla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4065ed4e-ebc4-4e13-a82b-8195a735fa44> .

