Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Voon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8cc46656-70eb-4087-b8c3-576f03fb66ae> .
<https://starwars.com#planet_Voon> <http://www.w3.org/2000/01/rdf-schema#comment> "The Arkanian-Sephi Jedi Arca Jeth then used the Force to detect signs of life below the fortress, in the subterranean pockets littering the planet's crust. Jeth then led his fellow Jedi into a large chamber underground, where the group faced an unexpected cave-in, followed by an ambush by the Nelori Marauders. Although the ensuing battle proved costly to the Jedi force, Jeth's use of the battle meditation technique allowed the Jedi to ultimately defeat the Marauders. " .
<https://starwars.com#planet_Voon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#8cc46656-70eb-4087-b8c3-576f03fb66ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Voon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Voon> <http://telicent.io/ontology/primaryName> "Voon" .
<https://starwars.com#planet_Voon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Voon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#8cc46656-70eb-4087-b8c3-576f03fb66ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

