Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Queyta> <http://telicent.io/ontology/primaryName> "Queyta" .
<https://starwars.com#planet_Queyta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Danjar> .
<https://starwars.com#sector_Danjar> <http://telicent.io/ontology/primaryName> "Danjar" .
<https://starwars.com#d67031cb-2802-45d0-900d-1a5e388bf7b4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Queyta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Queyta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d67031cb-2802-45d0-900d-1a5e388bf7b4> .
<https://starwars.com#sector_Danjar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#d67031cb-2802-45d0-900d-1a5e388bf7b4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Queyta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#sector_Danjar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Queyta> <http://www.w3.org/2000/01/rdf-schema#comment> "Queyta was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Queyta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

