Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Venjagga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Venjagga> <http://telicent.io/ontology/primaryName> "Venjagga" .
<https://starwars.com#planet_Venjagga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#97da84d9-7a50-4c9d-9e6b-ac48fb75621f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Venjagga"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Venjagga> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#97da84d9-7a50-4c9d-9e6b-ac48fb75621f> .
<https://starwars.com#planet_Venjagga> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Venjagga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#97da84d9-7a50-4c9d-9e6b-ac48fb75621f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

