Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_RakataPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Rakata Prime, also known as Lehon, was the homeworld of the long-extinct Rakata species, who were rumored to be the first to develop hyperspace travel, and was one of the few navigable worlds located in the Unknown Regions. At some point, the Resistance pilot Venisa Doza visited the planet along with her astromech droid, Torch. The Zabrak pirate Tryki was also once arrested for attempting to board a First Order cruiser near Rakata Prime. " .
<https://starwars.com#planet_RakataPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G11> .
<https://starwars.com#grid_G11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_G11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#7b354c30-eb5e-4e2b-bfee-0a36805b6797> .
<https://starwars.com#b2eb82db-c1c1-4550-9b34-69306ffd9955> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rakata Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RakataPrime> <http://telicent.io/ontology/primaryName> "Rakata Prime" .
<https://starwars.com#planet_RakataPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_RakataPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2eb82db-c1c1-4550-9b34-69306ffd9955> .
<https://starwars.com#b2eb82db-c1c1-4550-9b34-69306ffd9955> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RakataPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7b354c30-eb5e-4e2b-bfee-0a36805b6797> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#7b354c30-eb5e-4e2b-bfee-0a36805b6797> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_G11> <http://telicent.io/ontology/primaryName> "G11" .
<https://starwars.com#grid_G11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

