Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Xeron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4fe9fc42-7f59-473f-aa79-497fd8e8a747> .
<https://starwars.com#planet_Xeron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4fe9fc42-7f59-473f-aa79-497fd8e8a747> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Xeron> <http://telicent.io/ontology/primaryName> "Xeron" .
<https://starwars.com#planet_Xeron> <http://www.w3.org/2000/01/rdf-schema#comment> "Xeron was a planet located within the Xeron system, a part of the Trailing Sectors portion of the Inner Rim. Xeron was the site of a battle between the Rebel Alliance and Galactic Empire during the Galactic Civil War circa 3 ABY, where the Imperial Army attacked Rebel ground troops with a new warbot to devastating effect. " .
<https://starwars.com#planet_Xeron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#4fe9fc42-7f59-473f-aa79-497fd8e8a747> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xeron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Xeron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .

