Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KordaSix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#76b20be5-2fd5-4022-a857-fbd744d281a6> .
<https://starwars.com#planet_KordaSix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KordaSix> <http://www.w3.org/2000/01/rdf-schema#comment> "Korda Six was a planet that ranged from barren rocky plains to small forests in which the natives lived. It was also where Montross betrayed Jaster Mereel to the Death Watch. Jaster was killed by Tor Vizsla, and Jango Fett became the Mandalore. " .
<https://starwars.com#planet_KordaSix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#76b20be5-2fd5-4022-a857-fbd744d281a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KordaSix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_KordaSix> <http://telicent.io/ontology/primaryName> "Korda Six" .
<https://starwars.com#76b20be5-2fd5-4022-a857-fbd744d281a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korda Six"^^<http://www.w3.org/2001/XMLSchema#string> .

