Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_InduSan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rolion> .
<https://starwars.com#planet_InduSan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#planet_InduSan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5989d036-0d06-4a39-8f2a-7ea4b1f73683> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_InduSan> <http://telicent.io/ontology/primaryName> "Indu San" .
<https://starwars.com#sector_Rolion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_InduSan> <http://www.w3.org/2000/01/rdf-schema#comment> "Indu San was a location where the Galactic Empire's 204th Imperial Fighter Wing operated at in the weeks after the Battle of Endor 4 ABY, during which some of their members were killed. " .
<https://starwars.com#sector_Rolion> <http://telicent.io/ontology/primaryName> "Rolion" .
<https://starwars.com#5989d036-0d06-4a39-8f2a-7ea4b1f73683> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Indu San"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_InduSan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5989d036-0d06-4a39-8f2a-7ea4b1f73683> .
<https://starwars.com#sector_Rolion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

