Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Revyia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f93e7bd0-ad8a-4ea9-b9fb-28473ba54b90> .
<https://starwars.com#sector_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#planet_Revyia> <http://www.w3.org/2000/01/rdf-schema#comment> "Revyia was a planet in the Veragi sector of the Outer Rim, located halfway between the Pits of Plooma and the Galactic Rim. It was the homeworld of the Revwien species. In 30 BBY, the Tyia Force tradition was brought to the planet by a missionary aboard an independent freighter. " .
<https://starwars.com#planet_Revyia> <http://telicent.io/ontology/primaryName> "Revyia" .
<https://starwars.com#f93e7bd0-ad8a-4ea9-b9fb-28473ba54b90> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Revyia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f93e7bd0-ad8a-4ea9-b9fb-28473ba54b90> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Revyia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Revyia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L2> .
<https://starwars.com#planet_Revyia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Veragi> .

