Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cd7c3174-e0a9-4edb-be20-9bd40d7971ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Foerost"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Foerost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Foerost> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cd7c3174-e0a9-4edb-be20-9bd40d7971ac> .
<https://starwars.com#cd7c3174-e0a9-4edb-be20-9bd40d7971ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Foerost> <http://www.w3.org/2000/01/rdf-schema#comment> "Foerost was a terrestrial astronomical object and the site of the Battle of Foerost, which took place by 14 BBY. The Drabatan Pao carried out a demolitions job on Foerost, his first known mission with the Rebel Alliance, which involved taking out a communications tower sometime by 0 BBY. The rebel Captain Cassian Andor remembered the Drabatan's job shortly before the Battle of Scarif that year, where the captain's team carried out a similar job. Andor thought to himself that he would ask Pao about the job before the mission began. " .
<https://starwars.com#planet_Foerost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Foerost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Foerost> <http://telicent.io/ontology/primaryName> "Foerost" .

