Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Capella> <http://www.w3.org/2000/01/rdf-schema#comment> "Capella was a planet in the Gordian Reach of the Outer Rim. " .
<https://starwars.com#planet_Capella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Capella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#7de0eaf3-6eb6-4d16-9f5e-dfd6b66a6cdd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Capella"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Capella> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7de0eaf3-6eb6-4d16-9f5e-dfd6b66a6cdd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Capella> <http://telicent.io/ontology/primaryName> "Capella" .
<https://starwars.com#planet_Capella> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7de0eaf3-6eb6-4d16-9f5e-dfd6b66a6cdd> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

