Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9df282a5-b87f-42ac-abf1-f385e45e74da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Roqoo Depot"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_RoqooDepot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RoqooDepot> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9df282a5-b87f-42ac-abf1-f385e45e74da> .
<https://starwars.com#planet_RoqooDepot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_RoqooDepot> <http://telicent.io/ontology/primaryName> "Roqoo Depot" .
<https://starwars.com#planet_RoqooDepot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_RoqooDepot> <http://www.w3.org/2000/01/rdf-schema#comment> "Roqoo Depot was a refueling station and supply base located in the Hapes Cluster. It was here that Jedi Masters Luke and Mara Jade Skywalker dueled the Sith Lady Lumiya and her apprentice, Alema Rar. " .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#9df282a5-b87f-42ac-abf1-f385e45e74da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

