Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Gendius> <http://telicent.io/ontology/primaryName> "Gendius" .
<https://starwars.com#planet_Lorta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Gendius> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#194eafea-0e83-4044-8eb6-7207ce1bf248> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#194eafea-0e83-4044-8eb6-7207ce1bf248> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lorta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lorta> <http://www.w3.org/2000/01/rdf-schema#comment> "Lorta was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Lorta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gendius> .
<https://starwars.com#planet_Lorta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#194eafea-0e83-4044-8eb6-7207ce1bf248> .
<https://starwars.com#planet_Lorta> <http://telicent.io/ontology/primaryName> "Lorta" .
<https://starwars.com#sector_Gendius> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Lorta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J17> .

