Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mayvitch> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e3ccf692-17d5-4358-81cb-eceb4d0b4ce1> .
<https://starwars.com#sector_Immalia> <http://telicent.io/ontology/primaryName> "Immalia" .
<https://starwars.com#planet_Mayvitch> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#e3ccf692-17d5-4358-81cb-eceb4d0b4ce1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mayvitch"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Immalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Mayvitch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Immalia> .
<https://starwars.com#e3ccf692-17d5-4358-81cb-eceb4d0b4ce1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mayvitch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_Mayvitch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mayvitch> <http://telicent.io/ontology/primaryName> "Mayvitch" .
<https://starwars.com#sector_Immalia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

