Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pirralor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Pirralor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pirralor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9bb7b39b-a241-4c25-b86b-561eaa57a9bb> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Pirralor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pirralor> <http://telicent.io/ontology/primaryName> "Pirralor" .
<https://starwars.com#9bb7b39b-a241-4c25-b86b-561eaa57a9bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#9bb7b39b-a241-4c25-b86b-561eaa57a9bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pirralor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pirralor> <http://www.w3.org/2000/01/rdf-schema#comment> "Pirralor was a planet located in the Pirralor system of the Juvex sector, in the Mid Rim of the galaxy. It was the homeworld of House Pilor, and its spaceports were thick with outsiders from the Ninth Quadrant and the Agarix sector. Imperial Captain Dor Reder hailed from Pirralor. " .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

