Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sivoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sivoria> <http://www.w3.org/2000/01/rdf-schema#comment> "Sivoria was a planet located in the Hapes Cluster of the Inner Rim. It was the homeworld of the Sivorian species. " .
<https://starwars.com#planet_Sivoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Sivoria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f236b070-97fb-463c-b68f-edf8692a6bf9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#f236b070-97fb-463c-b68f-edf8692a6bf9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#f236b070-97fb-463c-b68f-edf8692a6bf9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sivoria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sivoria> <http://telicent.io/ontology/primaryName> "Sivoria" .
<https://starwars.com#planet_Sivoria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

