Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Poytta> <http://telicent.io/ontology/primaryName> "Poytta" .
<https://starwars.com#a583ce04-d277-40c4-a045-bf44d038d78e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Poytta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T12> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Poytta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Poytta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a583ce04-d277-40c4-a045-bf44d038d78e> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Poytta> <http://www.w3.org/2000/01/rdf-schema#comment> "Poytta was a planet in Hutt Space used by many slavers and smugglers as a refueling stop. It also served as Tuga SalPivo's base of operations. " .
<https://starwars.com#planet_Poytta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#a583ce04-d277-40c4-a045-bf44d038d78e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Poytta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

