Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6d66f2a4-3e70-4926-934d-1075048f1654> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Uviuy Exen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6d66f2a4-3e70-4926-934d-1075048f1654> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_UviuyExen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_UviuyExen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6d66f2a4-3e70-4926-934d-1075048f1654> .
<https://starwars.com#planet_UviuyExen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_UviuyExen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_UviuyExen> <http://www.w3.org/2000/01/rdf-schema#comment> "Uviuy Exen was an astronomical object located in the regions known as the Colonies and the Interior. It was also situated in grid square L-9 of the Standard Galactic Grid. The super-hyperroute known as the Hydian Way linked Uviuy Exen to the Brentaal System in the Core Worlds as well as the Inner Rim Territories world Champala. In addition, it was connected to Palanhi by the Shwuy Exchange hyperspace route. " .
<https://starwars.com#planet_UviuyExen> <http://telicent.io/ontology/primaryName> "Uviuy Exen" .

