Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vensensor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TarMordren> <http://telicent.io/ontology/primaryName> "Tar Mordren" .
<https://starwars.com#planet_TarMordren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vensensor> .
<https://starwars.com#planet_TarMordren> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4ef6bfd-8895-4736-b2dd-e0ad67c7eac2> .
<https://starwars.com#planet_TarMordren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#sector_Vensensor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_TarMordren> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet later became the site of a Rebel starfighter manufacturing operation. Information about this enterprise was gathered by Imperial Intelligence, which sent it in a Plexus Droid Vessel to Intelligence Sector HQ. Rebels intercepted this vessel, which self destructed, ejecting its I2-CG droid, which landed on Goratak III. " .
<https://starwars.com#b4ef6bfd-8895-4736-b2dd-e0ad67c7eac2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b4ef6bfd-8895-4736-b2dd-e0ad67c7eac2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tar Mordren"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Vensensor> <http://telicent.io/ontology/primaryName> "Vensensor" .
<https://starwars.com#planet_TarMordren> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

