Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#db23a11b-7708-477d-8a68-3dd635052d27> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Escalan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#db23a11b-7708-477d-8a68-3dd635052d27> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Escalan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#db23a11b-7708-477d-8a68-3dd635052d27> .
<https://starwars.com#planet_Escalan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Escalan> <http://telicent.io/ontology/primaryName> "Escalan" .
<https://starwars.com#planet_Escalan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

