Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MaarShaddam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rseik> .
<https://starwars.com#sector_Rseik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MaarShaddam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N20> .
<https://starwars.com#f3cf051c-0378-46d4-b3c7-691257caad18> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ma'ar Shaddam"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MaarShaddam> <http://www.w3.org/2000/01/rdf-schema#comment> "Ma'ar Shaddam was a remote Outer Rim planet, home to the armorers who served Boba Fett. The planet was settled by Galactic Republic Master Weaponsmiths not only for the quality of its ore, but because its remoteness made it difficult for the authorities to police the sale of illegal weaponry. " .
<https://starwars.com#planet_MaarShaddam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f3cf051c-0378-46d4-b3c7-691257caad18> .
<https://starwars.com#sector_Rseik> <http://telicent.io/ontology/primaryName> "Rseik" .
<https://starwars.com#f3cf051c-0378-46d4-b3c7-691257caad18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MaarShaddam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Rseik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_MaarShaddam> <http://telicent.io/ontology/primaryName> "Ma'ar Shaddam" .

