Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Praesitlyn> <http://www.w3.org/2000/01/rdf-schema#comment> "Praesitlyn was a planet in the Sluis sector of the Outer Rim. It was the location of the Intergalactic Communications Center, a major HoloNet hub in the galaxy. The Communications Center became a strategic asset during the Clone Wars, leading to the fierce Battle of Praesitlyn. " .
<https://starwars.com#planet_Praesitlyn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a67614c-fb67-42e8-87c4-0cb85df0b819> .
<https://starwars.com#planet_Praesitlyn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Praesitlyn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#1a67614c-fb67-42e8-87c4-0cb85df0b819> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sluis> <http://telicent.io/ontology/primaryName> "Sluis" .
<https://starwars.com#planet_Praesitlyn> <http://telicent.io/ontology/primaryName> "Praesitlyn" .
<https://starwars.com#sector_Sluis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Sluis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1a67614c-fb67-42e8-87c4-0cb85df0b819> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Praesitlyn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Praesitlyn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sluis> .

