Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Austan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Austan> <http://telicent.io/ontology/primaryName> "Austan" .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Austan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Austan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31fbb39e-24a5-4ecb-9e59-ef0f8bd0acf0> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#31fbb39e-24a5-4ecb-9e59-ef0f8bd0acf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Austan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Austan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#31fbb39e-24a5-4ecb-9e59-ef0f8bd0acf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Austan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .

