Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Feldwes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#0463d152-896e-49fa-84aa-9a35085e032d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Feldwes> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Feldwes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#0463d152-896e-49fa-84aa-9a35085e032d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Feldwes"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Feldwes> <http://telicent.io/ontology/primaryName> "Feldwes" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Feldwes> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0463d152-896e-49fa-84aa-9a35085e032d> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Feldwes> <http://www.w3.org/2000/01/rdf-schema#comment> "Feldwes was a planet in a system of the same name, located in the Gordian Reach sector of the Outer Rim. It sat on the Ardan Cross hyperspace route. Feldwes was the foremost industrial world in the trailing part of the sector known as the Back Reach, and the employment possibilities of its factories led numerous T'sarki, B'trillans, and Humans to seek work permits there. " .

