Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ad89b499-11d9-43fb-a7c2-53dd163ca961> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Sposia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ad89b499-11d9-43fb-a7c2-53dd163ca961> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sposia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sposia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Sposia> <http://telicent.io/ontology/primaryName> "Sposia" .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Sposia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ad89b499-11d9-43fb-a7c2-53dd163ca961> .
<https://starwars.com#planet_Sposia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#planet_Sposia> <http://www.w3.org/2000/01/rdf-schema#comment> "Sposia was a planet in the Chiss Ascendancy where thousands of Chiss families and millions of Chiss lived. Around 18 BBY, the Chiss Syndicure held a hearing about the safety of fish on Sposia. " .

