Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_I13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_I13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#183646da-cc96-405f-a24d-d0f9fa4e0812> .
<https://starwars.com#183646da-cc96-405f-a24d-d0f9fa4e0812> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I13> <http://telicent.io/ontology/primaryName> "I13" .
<https://starwars.com#5ef81ce4-1403-4fac-929d-781ce01ce236> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jakku> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I13> .
<https://starwars.com#planet_Jakku> <http://www.w3.org/2000/01/rdf-schema#comment> "Desert planet. Site of a 'graveyard' of ships damaged during the Battle of Jakku, the final battle between the New Republic and the Galactic Empire. Also the homeworld of Rey." .
<https://starwars.com#grid_I13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Jakku> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jakku> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5ef81ce4-1403-4fac-929d-781ce01ce236> .
<https://starwars.com#183646da-cc96-405f-a24d-d0f9fa4e0812> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Jakku> <http://telicent.io/ontology/primaryName> "Jakku" .
<https://starwars.com#planet_Jakku> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#5ef81ce4-1403-4fac-929d-781ce01ce236> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jakku"^^<http://www.w3.org/2001/XMLSchema#string> .

