Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Drogheda> <http://www.w3.org/2000/01/rdf-schema#comment> "Drogheda was an astronomical object. According to the smuggler Lando Calrissian, his father had prevented him from marrying into a mining fortune on Drogheda. After learning Calrissian's story about the celestial body, the bartender Tivoche Bilure included the tale in his journal. " .
<https://starwars.com#grid_Q11> <http://telicent.io/ontology/primaryName> "Q11" .
<https://starwars.com#grid_Q11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9a02d84c-d61e-4f8d-8f5b-7e68ed63093d> .
<https://starwars.com#9a02d84c-d61e-4f8d-8f5b-7e68ed63093d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9a02d84c-d61e-4f8d-8f5b-7e68ed63093d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Drogheda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drogheda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q11> .
<https://starwars.com#sector_Teraab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Teraab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Drogheda> <http://telicent.io/ontology/primaryName> "Drogheda" .
<https://starwars.com#planet_Drogheda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d8da2a60-8e2a-436a-b7b4-0985a7ca4729> .
<https://starwars.com#d8da2a60-8e2a-436a-b7b4-0985a7ca4729> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Drogheda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Teraab> .
<https://starwars.com#grid_Q11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#d8da2a60-8e2a-436a-b7b4-0985a7ca4729> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drogheda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Teraab> <http://telicent.io/ontology/primaryName> "Teraab" .

