Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Maires> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Maires> <http://www.w3.org/2000/01/rdf-schema#comment> "Maires was an astronomical object in the Inner Rim Territories that was the homeworld of the Mairan species. " .
<https://starwars.com#652359d1-751b-4e41-891b-6d37db8894b9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#652359d1-751b-4e41-891b-6d37db8894b9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Maires"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Maires> <http://telicent.io/ontology/primaryName> "Maires" .
<https://starwars.com#planet_Maires> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#652359d1-751b-4e41-891b-6d37db8894b9> .
<https://starwars.com#planet_Maires> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Maires> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .

