Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bryexx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Bryexx> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46dba076-fd42-4763-a919-1807d092085f> .
<https://starwars.com#planet_Bryexx> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#46dba076-fd42-4763-a919-1807d092085f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bryexx> <http://www.w3.org/2000/01/rdf-schema#comment> "Bryexx was a planet in Varvenna sector. " .
<https://starwars.com#46dba076-fd42-4763-a919-1807d092085f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bryexx"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bryexx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Bryexx> <http://telicent.io/ontology/primaryName> "Bryexx" .

