Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c971354f-9888-4973-9a52-42922b5f9c2c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c971354f-9888-4973-9a52-42922b5f9c2c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gulhadar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gulhadar> <http://telicent.io/ontology/primaryName> "Gulhadar" .
<https://starwars.com#planet_Gulhadar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c971354f-9888-4973-9a52-42922b5f9c2c> .
<https://starwars.com#planet_Gulhadar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Gulhadar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

