Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Lostar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Draria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Draria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_Draria> <http://www.w3.org/2000/01/rdf-schema#comment> "Draria was a planet. The Task Force on Alliance Security recorded it as the last known location of Granse Confederacy member Zayl Braith. " .
<https://starwars.com#planet_Draria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lostar> .
<https://starwars.com#69801992-3893-41e1-ba90-9d94a61c6dd5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Draria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lostar> <http://telicent.io/ontology/primaryName> "Lostar" .
<https://starwars.com#sector_Lostar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Draria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#69801992-3893-41e1-ba90-9d94a61c6dd5> .
<https://starwars.com#69801992-3893-41e1-ba90-9d94a61c6dd5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Draria> <http://telicent.io/ontology/primaryName> "Draria" .

