Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kanz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_N4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#6dfb1463-0b20-44cd-938a-8ef16be70be3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_N4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#779990ac-0760-4856-bed7-32d70860efd6> .
<https://starwars.com#grid_N4> <http://telicent.io/ontology/primaryName> "N4" .
<https://starwars.com#planet_Argazda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6dfb1463-0b20-44cd-938a-8ef16be70be3> .
<https://starwars.com#grid_N4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#779990ac-0760-4856-bed7-32d70860efd6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#779990ac-0760-4856-bed7-32d70860efd6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Argazda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kanz> .
<https://starwars.com#planet_Argazda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .
<https://starwars.com#6dfb1463-0b20-44cd-938a-8ef16be70be3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Argazda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Argazda> <http://telicent.io/ontology/primaryName> "Argazda" .
<https://starwars.com#sector_Kanz> <http://telicent.io/ontology/primaryName> "Kanz" .
<https://starwars.com#sector_Kanz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Argazda> <http://www.w3.org/2000/01/rdf-schema#comment> "Argazda was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Argazda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

