Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#10e0ebd2-2280-438f-bd58-c7d8d2dd9a4a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_M17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d778145b-d83f-4da1-9fc9-dedc73f7712d> .
<https://starwars.com#d778145b-d83f-4da1-9fc9-dedc73f7712d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#d778145b-d83f-4da1-9fc9-dedc73f7712d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chryya> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_Chryya> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#10e0ebd2-2280-438f-bd58-c7d8d2dd9a4a> .
<https://starwars.com#grid_M17> <http://telicent.io/ontology/primaryName> "M17" .
<https://starwars.com#planet_Chryya> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .
<https://starwars.com#planet_Chryya> <http://telicent.io/ontology/primaryName> "Chryya" .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#grid_M17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Chryya> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#10e0ebd2-2280-438f-bd58-c7d8d2dd9a4a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chryya"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chryya> <http://www.w3.org/2000/01/rdf-schema#comment> "Chryya was a planet with a thriving spice business. It was located in the Mid Rim, on the Hydian Way near the border of the Outer Rim Territories. Darth Maul was once sent on a mission to this planet by Darth Sidious to convince the miners to sell to the Trade Federation. Maul's failure to convince them was his only failure prior to the Invasion of Naboo. " .

