Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nantuker> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12e3f1ff-b417-4303-8a8d-78e9f9c0587d> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nantuker> <http://telicent.io/ontology/primaryName> "Nantuker" .
<https://starwars.com#planet_Nantuker> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Nantuker> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Nantuker> <http://www.w3.org/2000/01/rdf-schema#comment> "Nantuker was a planet in the Corsair Outback region of the Hapes Cluster. It was the source of premium Nantuker dates. " .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#12e3f1ff-b417-4303-8a8d-78e9f9c0587d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nantuker> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#12e3f1ff-b417-4303-8a8d-78e9f9c0587d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nantuker"^^<http://www.w3.org/2001/XMLSchema#string> .

