Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Usta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f1f9f0f0-7f26-4cb7-b59b-c7141c47318f> .
<https://starwars.com#planet_Usta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Usta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Usta> <http://telicent.io/ontology/primaryName> "Usta" .
<https://starwars.com#planet_Usta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#f1f9f0f0-7f26-4cb7-b59b-c7141c47318f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Usta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f1f9f0f0-7f26-4cb7-b59b-c7141c47318f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Usta> <http://www.w3.org/2000/01/rdf-schema#comment> "Usta was a mining world located on the Feena Run in the Gordian Reach sector. It was run as a joint venture between the Ardans of the Arda system and the T'sarki of Kalishik. Energy mining on Usta left the world cratered, and rendered it poisonous. " .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

