Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Loronar> <http://www.w3.org/2000/01/rdf-schema#comment> "Loronar was an astronomical object located in the galaxy's Colonies region that was situated along the Corellian Run. During the early rebellion against the Galactic Empire, the intelligence branch of the Rebel Alliance witnessed a spike in transmitter traffic from Loronar. Alliance Intelligence was able to deduce that a constellation of Torpedo Spheres were active. Paired with intelligence on equipment suppliers, Colonel Haxen Delto expressed to Chief of Rebel Intelligence General Airen Cracken that they should be worried. " .
<https://starwars.com#a32b385b-d75f-44c3-a54a-d9b9575f0d60> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Loronar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Loronar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Loronar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Loronar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a32b385b-d75f-44c3-a54a-d9b9575f0d60> .
<https://starwars.com#a32b385b-d75f-44c3-a54a-d9b9575f0d60> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Loronar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_Loronar> <http://telicent.io/ontology/primaryName> "Loronar" .

