Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Savareen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bd92edf3-bd79-4d91-8fa0-ea3303cfac46> .
<https://starwars.com#planet_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#bd92edf3-bd79-4d91-8fa0-ea3303cfac46> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Savareen> <http://www.w3.org/2000/01/rdf-schema#comment> "Desert and ocean planet. where destitute villages farm wind and refine coaxium. In Solo: A Star Wars Story, the Millennium Falcon arrives there after Han and his crew steal coaxium from Kessel, and Dryden Vos and Tobias Beckett die there." .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#bd92edf3-bd79-4d91-8fa0-ea3303cfac46> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Savareen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#planet_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .

