Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_StarswarmCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#81ab999d-e5b4-41fa-b7f4-f1c8b6807f0b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_StarswarmCluster> <http://telicent.io/ontology/primaryName> "Starswarm Cluster" .
<https://starwars.com#planet_StarswarmCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#81ab999d-e5b4-41fa-b7f4-f1c8b6807f0b> .
<https://starwars.com#81ab999d-e5b4-41fa-b7f4-f1c8b6807f0b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Starswarm Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_StarswarmCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_StarswarmCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Starswarm Cluster was an astronomical object located in the regions known as the Deep Core and the Interior. It was also situated in the grid square L-10 of the Standard Galactic Grid. " .
<https://starwars.com#planet_StarswarmCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .

