Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pesfavri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b92cc8d3-45bf-465c-a42c-0bd96a21edef> .
<https://starwars.com#planet_Pesfavri> <http://www.w3.org/2000/01/rdf-schema#comment> "Pesfavri was a location in the Unknown Regions, within the borders of the Chiss Ascendancy. Pirates affiliated with the Lioaoin Regime attacked Chiss freighters shipping off Pesfavri and Schesa. " .
<https://starwars.com#grid_G8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#b92cc8d3-45bf-465c-a42c-0bd96a21edef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pesfavri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pesfavri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_G8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_G8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ffb80cc1-0307-4741-a243-07dbbcab4d3e> .
<https://starwars.com#planet_Pesfavri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G8> .
<https://starwars.com#planet_Pesfavri> <http://telicent.io/ontology/primaryName> "Pesfavri" .
<https://starwars.com#grid_G8> <http://telicent.io/ontology/primaryName> "G8" .
<https://starwars.com#ffb80cc1-0307-4741-a243-07dbbcab4d3e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ffb80cc1-0307-4741-a243-07dbbcab4d3e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Pesfavri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#b92cc8d3-45bf-465c-a42c-0bd96a21edef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

