Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_HarBinande> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HarWorlds> .
<https://starwars.com#planet_HarBinande> <http://www.w3.org/2000/01/rdf-schema#comment> "Har Binande was the primary planet in the Har system. Invaded by the Lahag Erli during the early years of the Galactic Republic, their forces occupied the planet for many years until they were finally deposed. They left in their wake cities of exquisite architecture on many of the Har worlds. These cities would become profitable as tourist attractions, erasing memory of the occupation. " .
<https://starwars.com#9a90f782-2d0f-4145-84fe-749cd59c44e8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_HarBinande> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9a90f782-2d0f-4145-84fe-749cd59c44e8> .
<https://starwars.com#sector_HarWorlds> <http://telicent.io/ontology/primaryName> "Har Worlds" .
<https://starwars.com#sector_HarWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_HarBinande> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J16> .
<https://starwars.com#planet_HarBinande> <http://telicent.io/ontology/primaryName> "Har Binande" .
<https://starwars.com#sector_HarWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9a90f782-2d0f-4145-84fe-749cd59c44e8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Har Binande"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_HarBinande> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

