Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0c64b410-e7af-464a-b481-02794373230c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Valorsi> <http://telicent.io/ontology/primaryName> "Valorsi" .
<https://starwars.com#planet_Valorsi> <http://www.w3.org/2000/01/rdf-schema#comment> "Valorsi was a planet located within the Valorsi system of the Juvex sector in the Mid Rim. Its native inhabitants, who came from many species, were known as Valorsians. Spacers told rumors of the pleasure world, which was said to have something to please even the most depraved lusts. The world's harems, where beings of both sexes and of innumerable species were kept and carefully bred for their beauty, were whispered about in taverns across the galaxy. Valorsian harems were rumored to be carefully guarded. Only high-ranking nobles from the Senex and Juvex houses and their attendants could travel to the world. " .
<https://starwars.com#planet_Valorsi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0c64b410-e7af-464a-b481-02794373230c> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#0c64b410-e7af-464a-b481-02794373230c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Valorsi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Valorsi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Valorsi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Valorsi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

