Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KunasTail> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KunasTail> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_KunasTail> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KunasTail> <http://telicent.io/ontology/primaryName> "Kuna's Tail" .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b8740cb3-d531-43a6-9f71-ed556af6d2fe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KunasTail> <http://www.w3.org/2000/01/rdf-schema#comment> "Kuna's Tail was a location in the Moddell sector of the Outer Rim Territories. Before the Battle of Endor in 4 ABY, Kuna's Tail was featured as part of a map composed by Corporal Ractivelle of the Stardust unit for the preparation of the Rebel Alliance's attack on the second Death Star. " .
<https://starwars.com#planet_KunasTail> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b8740cb3-d531-43a6-9f71-ed556af6d2fe> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#b8740cb3-d531-43a6-9f71-ed556af6d2fe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuna's Tail"^^<http://www.w3.org/2001/XMLSchema#string> .

