Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pluthan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5352557-de52-4ac7-9cf8-7afb8f02705c> .
<https://starwars.com#planet_Pluthan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Pluthan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pluthan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#planet_Pluthan> <http://telicent.io/ontology/primaryName> "Pluthan" .
<https://starwars.com#planet_Pluthan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#b5352557-de52-4ac7-9cf8-7afb8f02705c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pluthan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b5352557-de52-4ac7-9cf8-7afb8f02705c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

