Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yulant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#40e8f385-17e1-45e7-b63b-a56d37eb3676> .
<https://starwars.com#planet_Yulant> <http://www.w3.org/2000/01/rdf-schema#comment> "Yulant was an agricultural planet in the Core Worlds owned by the Salliche Agricultural Corporation who sued Dasobo Meats, a meat shipping company based on the planet. It was one of the worlds on the Ag Circuit. " .
<https://starwars.com#planet_Yulant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Yulant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#40e8f385-17e1-45e7-b63b-a56d37eb3676> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yulant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yulant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#40e8f385-17e1-45e7-b63b-a56d37eb3676> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yulant> <http://telicent.io/ontology/primaryName> "Yulant" .

