Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Stobar> <http://telicent.io/ontology/primaryName> "Stobar" .
<https://starwars.com#sector_Boeus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegions> .
<https://starwars.com#planet_Stobar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M15> .
<https://starwars.com#planet_Stobar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Stobar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Boeus> .
<https://starwars.com#sector_Boeus> <http://telicent.io/ontology/primaryName> "Boeus" .
<https://starwars.com#48720ccc-f1b2-4e83-b618-dd306fb721e2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Stobar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Stobar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#48720ccc-f1b2-4e83-b618-dd306fb721e2> .
<https://starwars.com#sector_Boeus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Stobar> <http://www.w3.org/2000/01/rdf-schema#comment> "Stobar was a planet located in the Outer Rim Territories that was the site of the Stobar Spaceport. Savage Opress would visit Stobar during his search for his long-lost brother, the former Sith Lord Maul. After a confrontation between Opress and several individuals at a local diner, Jedi Knight Anakin Skywalker and his Padawan Ahsoka Tano would visit the diner to see what had happened, with the former sensing a disturbance in the Force shortly after they arrived. " .
<https://starwars.com#48720ccc-f1b2-4e83-b618-dd306fb721e2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

