Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vergill> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vergill> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d1684e2b-5582-4adb-9ef0-482114c5251d> .
<https://starwars.com#planet_Vergill> <http://telicent.io/ontology/primaryName> "Vergill" .
<https://starwars.com#planet_Vergill> <http://www.w3.org/2000/01/rdf-schema#comment> "Vergill was a planet located within the Vergill system of the Inner Rim. It was an influential member of the Hapes Consortium. In 25 ABY, the planet's archon was Beed Thane. " .
<https://starwars.com#d1684e2b-5582-4adb-9ef0-482114c5251d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vergill"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#d1684e2b-5582-4adb-9ef0-482114c5251d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vergill> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vergill> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .

