Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mattri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cd517193-b14f-4677-a11c-986611a0d0ef> .
<https://starwars.com#planet_Mattri> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#cd517193-b14f-4677-a11c-986611a0d0ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mattri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#cd517193-b14f-4677-a11c-986611a0d0ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mattri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mattri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Mattri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#planet_Mattri> <http://telicent.io/ontology/primaryName> "Mattri" .

