Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Carsanza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Carsanza> <http://www.w3.org/2000/01/rdf-schema#comment> "Carsanza was the site of a skirmish prior to the Galactic Civil War. The Rebellion's tactics during the skirmish were later re-used—along with tactics from a skirmish at Nexator—during the pivotal Battle of Scarif. " .
<https://starwars.com#2cee3bc7-ef48-4e4f-98bf-f8e5624f18d9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carsanza"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Carsanza> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Carsanza> <http://telicent.io/ontology/primaryName> "Carsanza" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Carsanza> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2cee3bc7-ef48-4e4f-98bf-f8e5624f18d9> .
<https://starwars.com#2cee3bc7-ef48-4e4f-98bf-f8e5624f18d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Carsanza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

