Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gerrenthum> <http://www.w3.org/2000/01/rdf-schema#comment> "Gerrenthum was a planet located in the Gerrenthum system of the galaxy's Outer Rim Territories, serving as the Anoat sector's capital after the previous capital, Anoat, was rendered uninhabitable. For many years, Imperial Governor Ubrik Adelhard governed the sector with an iron fist and absolute loyalty to the Galactic Empire. Orbited by a security station, many business owners and politicians on Gerrenthum openly bribed Imperials to ignore their illegal activities. " .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gerrenthum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#8e1ecd19-aeb9-4be8-9e29-e7afd35f78a7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gerrenthum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gerrenthum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8e1ecd19-aeb9-4be8-9e29-e7afd35f78a7> .
<https://starwars.com#planet_Gerrenthum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8e1ecd19-aeb9-4be8-9e29-e7afd35f78a7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gerrenthum> <http://telicent.io/ontology/primaryName> "Gerrenthum" .
<https://starwars.com#planet_Gerrenthum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .

