Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kwenn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c86a8416-7e7b-4f60-beb7-05339bd6eef0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kwenn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c86a8416-7e7b-4f60-beb7-05339bd6eef0> .
<https://starwars.com#c86a8416-7e7b-4f60-beb7-05339bd6eef0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kwenn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#planet_Kwenn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R10> .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kwenn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#planet_Kwenn> <http://www.w3.org/2000/01/rdf-schema#comment> "Kwenn was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kwenn> <http://telicent.io/ontology/primaryName> "Kwenn" .

