Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Monor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#399d2ab9-56a7-4527-88f8-cdea8f712586> .
<https://starwars.com#sector_Doldur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Monor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Doldur> .
<https://starwars.com#planet_Monor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Monor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#sector_Doldur> <http://telicent.io/ontology/primaryName> "Doldur" .
<https://starwars.com#399d2ab9-56a7-4527-88f8-cdea8f712586> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Monor> <http://telicent.io/ontology/primaryName> "Monor" .
<https://starwars.com#planet_Monor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#399d2ab9-56a7-4527-88f8-cdea8f712586> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Monor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

