Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Euceron> <http://telicent.io/ontology/primaryName> "Euceron" .
<https://starwars.com#planet_Euceron> <http://www.w3.org/2000/01/rdf-schema#comment> "Euceron was a planet located in the Eucer sector of the Mid Rim. It was located near Anzat. " .
<https://starwars.com#8a8491f0-1489-4d6d-9ea2-4cb77f7bd5dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Euceron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Euceron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8a8491f0-1489-4d6d-9ea2-4cb77f7bd5dd> .
<https://starwars.com#sector_Eucer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Euceron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Eucer> .
<https://starwars.com#planet_Euceron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Eucer> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Euceron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#8a8491f0-1489-4d6d-9ea2-4cb77f7bd5dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Eucer> <http://telicent.io/ontology/primaryName> "Eucer" .

