Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Schesa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#c6f9e9bb-a117-41e7-bc38-f1e1ee1003e2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Schesa> <http://www.w3.org/2000/01/rdf-schema#comment> "Schesa was a terrestrial planet in the Unknown Regions, situated near the edge of the Chiss Ascendancy. It was a major Chiss world. Pirates connected to the Lioaoin Regime attacked shipping off of Schesa and Pesfavri. " .
<https://starwars.com#planet_Schesa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Schesa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c6f9e9bb-a117-41e7-bc38-f1e1ee1003e2> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#c6f9e9bb-a117-41e7-bc38-f1e1ee1003e2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Schesa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Schesa> <http://telicent.io/ontology/primaryName> "Schesa" .
<https://starwars.com#planet_Schesa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .

