Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Manpha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1010c17d-cc7a-4184-b164-b2ab099c1c21> .
<https://starwars.com#planet_Manpha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Seitia> .
<https://starwars.com#planet_Manpha> <http://telicent.io/ontology/primaryName> "Manpha" .
<https://starwars.com#sector_Seitia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Seitia> <http://telicent.io/ontology/primaryName> "Seitia" .
<https://starwars.com#sector_Seitia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Manpha> <http://www.w3.org/2000/01/rdf-schema#comment> "Manpha was a swampy, wet Outer Rim planet and the homeworld of the Shawda Ubb musician Rappertunie. Located on the Corellian Trade Spine, it was positioned at the coordinates K-20 on the Standard Galactic Grid. " .
<https://starwars.com#1010c17d-cc7a-4184-b164-b2ab099c1c21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Manpha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Manpha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K20> .
<https://starwars.com#1010c17d-cc7a-4184-b164-b2ab099c1c21> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Manpha"^^<http://www.w3.org/2001/XMLSchema#string> .

