Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Belderone> <http://telicent.io/ontology/primaryName> "Belderone" .
<https://starwars.com#planet_Kodai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Kodai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#403305f8-9d33-4641-9c93-42b2d24f6363> .
<https://starwars.com#403305f8-9d33-4641-9c93-42b2d24f6363> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kodai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Belderone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kodai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belderone> .
<https://starwars.com#planet_Kodai> <http://telicent.io/ontology/primaryName> "Kodai" .
<https://starwars.com#planet_Kodai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Belderone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kodai> <http://www.w3.org/2000/01/rdf-schema#comment> "Kodai was a remote planet in the Belderone sector of the Outer Rim Territories. Some time prior to 29 BBY, its entire surface had been flooded save for the city of Rena. " .
<https://starwars.com#403305f8-9d33-4641-9c93-42b2d24f6363> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

