Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Varl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#420e0a84-f93b-467b-9b41-eecb499e0f44> .
<https://starwars.com#420e0a84-f93b-467b-9b41-eecb499e0f44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Varl> <http://telicent.io/ontology/primaryName> "Varl" .
<https://starwars.com#planet_Varl> <http://www.w3.org/2000/01/rdf-schema#comment> "Varl was an astronomical object located in the Outer Rim Territories of the galaxy. Located within Hutt Space, Varl was the original homeworld of the Hutt species. It was connected to Saki and Nal Hutta by hyperspace routes, and positioned at the coordinates S-11 on the Standard Galactic Grid. " .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Varl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Varl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Varl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#420e0a84-f93b-467b-9b41-eecb499e0f44> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Varl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

