Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sriluur> <http://www.w3.org/2000/01/rdf-schema#comment> "Sriluur was a desert planet located in the Hutt Space region of the galaxy's Outer Rim Territories that was the homeworld of the Weequays, a species whose tough, leathery skin helped them endure its harsh conditions, and the Sriluurian butterfly. " .
<https://starwars.com#sector_Periphery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sriluur> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#47167821-5eee-401d-abd2-6e38122c7cc0> .
<https://starwars.com#47167821-5eee-401d-abd2-6e38122c7cc0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Periphery> <http://telicent.io/ontology/primaryName> "Periphery" .
<https://starwars.com#planet_Sriluur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Periphery> .
<https://starwars.com#planet_Sriluur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Periphery> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sriluur> <http://telicent.io/ontology/primaryName> "Sriluur" .
<https://starwars.com#planet_Sriluur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#47167821-5eee-401d-abd2-6e38122c7cc0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sriluur"^^<http://www.w3.org/2001/XMLSchema#string> .

