Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Walinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Shiwal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Walinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a8ec14ed-bd2e-49c1-94b4-63fa7f27273f> .
<https://starwars.com#a8ec14ed-bd2e-49c1-94b4-63fa7f27273f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Walinor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Walinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Walinor was the president of a Galactic Republic-allied planet on the border of the Republic during the Galactic War between the Republic and the reconstituted Sith Empire. Wailor was one of several heads of state summoned by the Imperial General Arkos Rakton to a diplomatic summit on Outpost 256, but Rakton seized the heads of state by force. Wailor and the others were rescued from Rakton's forces by Havoc Squad. " .
<https://starwars.com#planet_Walinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#sector_Shiwal> <http://telicent.io/ontology/primaryName> "Shiwal" .
<https://starwars.com#planet_Walinor> <http://telicent.io/ontology/primaryName> "Walinor" .
<https://starwars.com#a8ec14ed-bd2e-49c1-94b4-63fa7f27273f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Shiwal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Walinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Shiwal> .

