Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OHS1782-03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_OHS1782-03> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#02f4adab-1da3-4188-9611-b5d2c1868e20> <http://ies.data.gov.uk/ontology/ies4#representationValue> "OHS1782-03"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OHS1782-03> <http://telicent.io/ontology/primaryName> "OHS1782-03" .
<https://starwars.com#planet_OHS1782-03> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#02f4adab-1da3-4188-9611-b5d2c1868e20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OHS1782-03> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_OHS1782-03> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02f4adab-1da3-4188-9611-b5d2c1868e20> .

