Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#70d58888-c346-482f-b7b1-bf4dcbcdb431> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Erilnar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Erilnar> <http://www.w3.org/2000/01/rdf-schema#comment> "Erilnar was a planet located in the Outer Rim Territories's Centrality. Serving as the capital of the Centrality, Erilnar had three hundred thousand lakes on its surface, which forced the planet's transportation to go underwater. At some point by the reign of the Galactic Empire, a terrorist attack on Erilnar destroyed most of the world's monorail network and resulted in a million casualties. Blaming the Empire for its non-reaction to the attack, the Erilnar native Kulbart Zamoon joined the Rebel Alliance. " .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Erilnar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Erilnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#70d58888-c346-482f-b7b1-bf4dcbcdb431> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Erilnar> <http://telicent.io/ontology/primaryName> "Erilnar" .
<https://starwars.com#planet_Erilnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Erilnar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#70d58888-c346-482f-b7b1-bf4dcbcdb431> .

