Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Champala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_Champala> <http://telicent.io/ontology/primaryName> "Champala" .
<https://starwars.com#planet_Champala> <http://www.w3.org/2000/01/rdf-schema#comment> "Champala was a world in the galaxy's Inner Rim. Located on the Hydian Way, it was home to the Chagrian species, including Mas Amedda, Vice Chancellor of the Galactic Republic and later Grand Vizier of the Galactic Empire. A popular pastime on Champala was fishing, but, according to Amedda, by the Clone Wars its oceans were 'not what they once were.' Nevertheless, the human architect Orson Callan Krennic used such as an analogy to explain his plans for scientist Galen Walton Erso to Amedda. The world had its own embassy on Coruscant. It was occupied by the Galactic Empire. " .
<https://starwars.com#planet_Champala> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9ebfd4fb-0c93-4f72-9f6b-b8df18d6d18a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Champala> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ebfd4fb-0c93-4f72-9f6b-b8df18d6d18a> .
<https://starwars.com#9ebfd4fb-0c93-4f72-9f6b-b8df18d6d18a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Champala"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Champala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

