Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vestar> <http://www.w3.org/2000/01/rdf-schema#comment> "Vestar was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Vestar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0d6a0666-790a-46e8-8126-fb9eea287c72> .
<https://starwars.com#planet_Vestar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N20> .
<https://starwars.com#sector_Rseik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Rseik> <http://telicent.io/ontology/primaryName> "Rseik" .
<https://starwars.com#planet_Vestar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0d6a0666-790a-46e8-8126-fb9eea287c72> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vestar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0d6a0666-790a-46e8-8126-fb9eea287c72> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Rseik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vestar> <http://telicent.io/ontology/primaryName> "Vestar" .
<https://starwars.com#planet_Vestar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rseik> .

