Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6cc43378-16d7-4157-9254-898b358221c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elom"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sertar> <http://telicent.io/ontology/primaryName> "Sertar" .
<https://starwars.com#sector_Sertar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Elom> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6cc43378-16d7-4157-9254-898b358221c3> .
<https://starwars.com#planet_Elom> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sertar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Elom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sertar> .
<https://starwars.com#planet_Elom> <http://www.w3.org/2000/01/rdf-schema#comment> "The Elom were a mysterious sentient species that were native to Elom who lived in frozen grottos. They were short and stocky, and covered in thick, oily fur. As a result of living in darkness, Eloms had exceptional eyesight, but found natural or bright lights intolerable. They had two tusks covering the opening of their mouth and small, black eyes located on the far ends of their wide faces. Though as a species that rarely ventured outside their caves, one Elom did make a name for himself offworld. Tanus Spijek was a spy for the Rebel Alliance during the Galactic Civil War. Most, though not all, members of this species were sympathetic to the Rebel Alliance. " .
<https://starwars.com#planet_Elom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#6cc43378-16d7-4157-9254-898b358221c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Elom> <http://telicent.io/ontology/primaryName> "Elom" .

