Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fornax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Clythe> <http://telicent.io/ontology/primaryName> "Clythe" .
<https://starwars.com#sector_Clythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Fornax> <http://www.w3.org/2000/01/rdf-schema#comment> "Fornax was an astronomical object located in the galaxy's Mid Rim, in grid square J-7 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Fornax> <http://telicent.io/ontology/primaryName> "Fornax" .
<https://starwars.com#grid_J7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Fornax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clythe> .
<https://starwars.com#planet_Fornax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Clythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9844b84a-409c-4ee3-93fe-2c201bc8375a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#1e1a9789-21d6-4e78-9f9b-7c992a725ec2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fornax"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_J7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9844b84a-409c-4ee3-93fe-2c201bc8375a> .
<https://starwars.com#grid_J7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_J7> <http://telicent.io/ontology/primaryName> "J7" .
<https://starwars.com#planet_Fornax> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1e1a9789-21d6-4e78-9f9b-7c992a725ec2> .
<https://starwars.com#9844b84a-409c-4ee3-93fe-2c201bc8375a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1e1a9789-21d6-4e78-9f9b-7c992a725ec2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

