Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vandor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3124b9db-b446-4efa-a7cf-4501b9cb113a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vandor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sloo> <http://telicent.io/ontology/primaryName> "Sloo" .
<https://starwars.com#planet_Vandor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3124b9db-b446-4efa-a7cf-4501b9cb113a> .
<https://starwars.com#planet_Vandor> <http://telicent.io/ontology/primaryName> "Vandor" .
<https://starwars.com#planet_Vandor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#sector_Sloo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Vandor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sloo> .
<https://starwars.com#3124b9db-b446-4efa-a7cf-4501b9cb113a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sloo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vandor> <http://www.w3.org/2000/01/rdf-schema#comment> "Vandor, also known as Vandor-1 or ID 53-80, was a cold frontier planet in the Sloo sector of the galaxy's Mid Rim. Despite being sparsely settled, the Galactic Empire had a growing presence on the planet. Fort Ypso was a snowy mountain village located on Vandor. " .

