Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Troiken> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Troiken> <http://www.w3.org/2000/01/rdf-schema#comment> "Troiken was a planet located in the Outer Rim Territories region of the galaxy that was the homeworld of the Xexto species. It was also home to raw spice mining operations, controlled by the Pyke Syndicate. " .
<https://starwars.com#sector_Colundra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#8d275529-43f5-4e0c-b304-bd2b4127ca15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Troiken> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Colundra> .
<https://starwars.com#sector_Colundra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Troiken> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8d275529-43f5-4e0c-b304-bd2b4127ca15> .
<https://starwars.com#sector_Colundra> <http://telicent.io/ontology/primaryName> "Colundra" .
<https://starwars.com#planet_Troiken> <http://telicent.io/ontology/primaryName> "Troiken" .
<https://starwars.com#planet_Troiken> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8d275529-43f5-4e0c-b304-bd2b4127ca15> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Troiken"^^<http://www.w3.org/2001/XMLSchema#string> .

