Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Edusa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Morshdine> .
<https://starwars.com#2189ea48-51b9-460b-9141-b3e6ce508796> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Edusa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Edusa> <http://telicent.io/ontology/primaryName> "Edusa" .
<https://starwars.com#planet_Edusa> <http://www.w3.org/2000/01/rdf-schema#comment> "Edusa was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Edusa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#2189ea48-51b9-460b-9141-b3e6ce508796> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Edusa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Edusa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2189ea48-51b9-460b-9141-b3e6ce508796> .
<https://starwars.com#sector_Morshdine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Morshdine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Morshdine> <http://telicent.io/ontology/primaryName> "Morshdine" .

