Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Halthor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3d12ec0e-e701-4d3d-a79a-5748cc4fd6bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Noonar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Noonar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halthor> .
<https://starwars.com#3d12ec0e-e701-4d3d-a79a-5748cc4fd6bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Halthor> <http://telicent.io/ontology/primaryName> "Halthor" .
<https://starwars.com#planet_Noonar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Noonar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .
<https://starwars.com#planet_Noonar> <http://www.w3.org/2000/01/rdf-schema#comment> "Noonar was a planet located in the Noonian system of the Outer Rim Territories. During the Cold War between the Galactic Republic and the Sith Empire, Noonar was host to the pacifist Noonar Confederacy, which controlled a key stretch of territory between the two galactic powers. During the Galactic Civil War, Noonar was run by Imperial governor Trophan Thanis. " .
<https://starwars.com#planet_Noonar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d12ec0e-e701-4d3d-a79a-5748cc4fd6bd> .
<https://starwars.com#planet_Noonar> <http://telicent.io/ontology/primaryName> "Noonar" .
<https://starwars.com#sector_Halthor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

