Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Resht> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Resht> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d28c899c-4777-490c-a665-cb0cf85659a8> .
<https://starwars.com#d28c899c-4777-490c-a665-cb0cf85659a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Resht"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Resht> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Resht> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#d28c899c-4777-490c-a665-cb0cf85659a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Resht> <http://telicent.io/ontology/primaryName> "Resht" .
<https://starwars.com#planet_Resht> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .

