Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#649e89e8-6230-499d-a020-1cbbc3192119> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Duinarbulon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#649e89e8-6230-499d-a020-1cbbc3192119> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Duinarbulon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Duinarbulon> <http://www.w3.org/2000/01/rdf-schema#comment> "Duinarbulon was a planet located within the Tion Cluster in the Outer Rim Territories. One of the original member-worlds of the Kingdom of Cron, it was absorbed into Xim's empire. This planet was home to the Duinarbulon Star Lancers, the elite soldiers of Xim's empire that fought for him during the war against the Hutts. According to later legend, massive stones of polished ebon marked their Parade Grounds, though by the era of the Galactic Empire, any sign of these stones had vanished, and Ximologists considered the Parade Grounds on Duinarbulon that survived to be obvious fakes to attract tourists. " .
<https://starwars.com#planet_Duinarbulon> <http://telicent.io/ontology/primaryName> "Duinarbulon" .
<https://starwars.com#planet_Duinarbulon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#649e89e8-6230-499d-a020-1cbbc3192119> .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Duinarbulon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Duinarbulon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .

