Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Isis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Isis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#6455884c-17e0-4b94-ab86-8cf06d510943> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Isis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Isis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#6455884c-17e0-4b94-ab86-8cf06d510943> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Isis> <http://telicent.io/ontology/primaryName> "Isis" .
<https://starwars.com#planet_Isis> <http://www.w3.org/2000/01/rdf-schema#comment> "Isis was a terrestrial planet in the Anoat sector of the Outer Rim Territories. The homeworld of the Gutretee, it was a secret Rebel Alliance safe world during the Galactic Civil War, and later became one of the Mining Worlds under the control of the Figg conglomerate. " .
<https://starwars.com#planet_Isis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6455884c-17e0-4b94-ab86-8cf06d510943> .

