Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c90c5caa-85f9-4857-b5c3-e5bfb70fd245> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Transel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Transel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Transel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c90c5caa-85f9-4857-b5c3-e5bfb70fd245> .
<https://starwars.com#planet_Transel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Transel> <http://telicent.io/ontology/primaryName> "Transel" .
<https://starwars.com#planet_Transel> <http://www.w3.org/2000/01/rdf-schema#comment> "Transel was a planet located within the Transel system of the Colonies, where the Ebon Hawk was originally registered. " .
<https://starwars.com#c90c5caa-85f9-4857-b5c3-e5bfb70fd245> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Transel"^^<http://www.w3.org/2001/XMLSchema#string> .

