Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Nuiri> <http://telicent.io/ontology/primaryName> "Nuiri" .
<https://starwars.com#planet_Lucazec> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#7eb4d1ce-ecce-47cb-8747-d9617d64a21a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lucazec"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lucazec> <http://telicent.io/ontology/primaryName> "Lucazec" .
<https://starwars.com#planet_Lucazec> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7eb4d1ce-ecce-47cb-8747-d9617d64a21a> .
<https://starwars.com#7eb4d1ce-ecce-47cb-8747-d9617d64a21a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lucazec> <http://www.w3.org/2000/01/rdf-schema#comment> "Lucazec was an astronomical object located in the Outer Rim Territories along the Salin Corridor that was controlled by the Galactic Empire. A group of rebels once stole an Imperial corvette known as the Carrion Spike and launched an attack on the Empire's mining operations on Lucazec, controlled through TaggeCo. They broadcasted a holovid of their activities. " .
<https://starwars.com#sector_Nuiri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lucazec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lucazec> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nuiri> .
<https://starwars.com#sector_Nuiri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

