Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ryvellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#5c66a505-4f22-4d37-afbf-a6645ffef69a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ryvellia> <http://telicent.io/ontology/primaryName> "Ryvellia" .
<https://starwars.com#planet_Ryvellia> <http://www.w3.org/2000/01/rdf-schema#comment> "Ryvellia was a planet located in the Avhn-Bendara system. Its capital city, V'eldalv, was the site of a brutal uprising that was crushed by the Galactic Empire via orbital bombardment. " .
<https://starwars.com#sector_Treffani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5c66a505-4f22-4d37-afbf-a6645ffef69a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ryvellia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ryvellia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5c66a505-4f22-4d37-afbf-a6645ffef69a> .
<https://starwars.com#planet_Ryvellia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Treffani> <http://telicent.io/ontology/primaryName> "Treffani" .
<https://starwars.com#planet_Ryvellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Treffani> .
<https://starwars.com#sector_Treffani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

