Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rnda> <http://telicent.io/ontology/primaryName> "Rnda" .
<https://starwars.com#planet_Rnda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Rnda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#3ae03f08-5c25-4c57-8ffb-8da8cda07c01> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rnda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rnda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rnda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3ae03f08-5c25-4c57-8ffb-8da8cda07c01> .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rnda> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#3ae03f08-5c25-4c57-8ffb-8da8cda07c01> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

