Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Pria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8dbf61e4-45fd-4a35-9a8c-a82a89e5754e> .
<https://starwars.com#planet_Pria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#8dbf61e4-45fd-4a35-9a8c-a82a89e5754e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pria> <http://telicent.io/ontology/primaryName> "Pria" .
<https://starwars.com#planet_Pria> <http://www.w3.org/2000/01/rdf-schema#comment> "Pria was a waterworld. Orbited by a single moon, the planet experienced two tidal cycles each day, as well as tectonic activity, causing an ice age every 10,000 years. " .
<https://starwars.com#8dbf61e4-45fd-4a35-9a8c-a82a89e5754e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pria"^^<http://www.w3.org/2001/XMLSchema#string> .

