Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Grandine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Grandine> <http://www.w3.org/2000/01/rdf-schema#comment> "The Grandine system was a star system located in the Colonies. It shared the name of the Grandine Swoop Loop." .
<https://starwars.com#planet_Grandine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5feb34fa-a1c1-4226-80a5-feea8fde8960> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Grandine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#5feb34fa-a1c1-4226-80a5-feea8fde8960> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Grandine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Grandine> <http://telicent.io/ontology/primaryName> "Grandine" .
<https://starwars.com#planet_Grandine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5feb34fa-a1c1-4226-80a5-feea8fde8960> .

