Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Roona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BesBerBikade> .
<https://starwars.com#planet_Roona> <http://www.w3.org/2000/01/rdf-schema#comment> "Roona was the homeworld of the Roonan species. Roona was represented in the Galactic Senate by Senator Aang. " .
<https://starwars.com#ef131bca-97c8-4553-809e-ea9028e0d94e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Roona"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_BesBerBikade> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_BesBerBikade> <http://telicent.io/ontology/primaryName> "Bes Ber Bikade" .
<https://starwars.com#planet_Roona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef131bca-97c8-4553-809e-ea9028e0d94e> .
<https://starwars.com#sector_BesBerBikade> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Roona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ef131bca-97c8-4553-809e-ea9028e0d94e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Roona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#planet_Roona> <http://telicent.io/ontology/primaryName> "Roona" .

