Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eshan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRIm> .
<https://starwars.com#planet_Eshan> <http://www.w3.org/2000/01/rdf-schema#comment> "Eshan was a planet in the galaxy where the infamous Droid Gotra caused a gang dispute, resulting in the loss of many innocents. Eshan was also the homeworld of Tayshin Maxa and Moda Maxa. " .
<https://starwars.com#planet_Eshan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#region_InnerRIm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#2ad3dc3c-aa9a-4a17-aa7b-10e8fc1df0b6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eshan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#region_InnerRIm> <http://telicent.io/ontology/primaryName> "Inner RIm" .
<https://starwars.com#planet_Eshan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2ad3dc3c-aa9a-4a17-aa7b-10e8fc1df0b6> .
<https://starwars.com#2ad3dc3c-aa9a-4a17-aa7b-10e8fc1df0b6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Eshan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#region_InnerRIm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_Eshan> <http://telicent.io/ontology/primaryName> "Eshan" .

