Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tshindral> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_Tshindral> <http://telicent.io/ontology/primaryName> "Tshindral" .
<https://starwars.com#planet_Tshindral> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#38ceab5a-a95b-462f-953f-4afbfdc57d11> .
<https://starwars.com#planet_Tshindral> <http://www.w3.org/2000/01/rdf-schema#comment> "Tshindral was one of a number of locations around the Rimma Trade Route that housed manufacturing facilities, spacedocks, and shipping lanes. In 3 ABY, the Rebel Alliance's 61st Mobile Infantry attacked numerous targets along the trade route. The Imperial Captain Tabor Seitaron, who was tracking the rebels, predicted Tshindral as one of their next possible targets, alongside the planets Sullust and Malastare. He prepared Tshindral and the other two locations for an attack, and the 61st ultimately targeted Sullust. " .
<https://starwars.com#sector_Ado> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#38ceab5a-a95b-462f-953f-4afbfdc57d11> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tshindral"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#38ceab5a-a95b-462f-953f-4afbfdc57d11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Ado> <http://telicent.io/ontology/primaryName> "Ado" .
<https://starwars.com#sector_Ado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Tshindral> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tshindral> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ado> .

