Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1b2e8f88-640d-49bc-8ed3-cd5141039dc1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ione"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ione> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1b2e8f88-640d-49bc-8ed3-cd5141039dc1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ione> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1b2e8f88-640d-49bc-8ed3-cd5141039dc1> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Ione> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Ione> <http://telicent.io/ontology/primaryName> "Ione" .
<https://starwars.com#planet_Ione> <http://www.w3.org/2000/01/rdf-schema#comment> "Ione was a planet in the Ione system of the Outer Rim Territories. During the Galactic Empire's Iron Blockade of the Anoat sector, Imperials seized all crystal shipments landing on Ione, causing an overflow of crystals in Imperial holdings. At the time of the Iron Blockade, many of the planet's inhabitants resented the Empire, but could not fight back as they lacked proper training. " .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ione> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

