Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Dufilvian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#ddd4561f-442a-4b0a-a7bf-07652a452cc7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Blenjeel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dufilvian> .
<https://starwars.com#planet_Blenjeel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q15> .
<https://starwars.com#planet_Blenjeel> <http://www.w3.org/2000/01/rdf-schema#comment> "Ten years after the Battle of Endor, a merchant vessel was attacked by an Imperial Immobilizer 418 cruiser and crashed on Blenjeel, and Jedi Initiate Jaden Korr was sent to investigate. However, his shuttle was struck by lightning on its landing approach and also crash-landed. He was unable to save the merchants, the last of whom was eaten by a sandworm shortly after his arrival, but was able to avoid the native sandworms for long enough to salvage from the merchant's ship the parts necessary to repair his shuttle. Shortly after this, Blenjeel was listed in the New Republic Galactic Database as a dangerous planet to be avoided. " .
<https://starwars.com#ddd4561f-442a-4b0a-a7bf-07652a452cc7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Blenjeel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Blenjeel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Blenjeel> <http://telicent.io/ontology/primaryName> "Blenjeel" .
<https://starwars.com#sector_Dufilvian> <http://telicent.io/ontology/primaryName> "Dufilvian" .
<https://starwars.com#sector_Dufilvian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Blenjeel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ddd4561f-442a-4b0a-a7bf-07652a452cc7> .

