Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pieldi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Pieldi> <http://telicent.io/ontology/primaryName> "Pieldi" .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Pieldi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pieldi> <http://www.w3.org/2000/01/rdf-schema#comment> "Pieldi was a planet in the Juvex sector of the Mid Rim. It was a thriving port located at the intersection of the Agarix Trade Route and the Senex-Juvex Loop. " .
<https://starwars.com#planet_Pieldi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#42d64d90-34d8-4128-a21a-4c0f9791764a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#42d64d90-34d8-4128-a21a-4c0f9791764a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pieldi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Pieldi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#42d64d90-34d8-4128-a21a-4c0f9791764a> .

