Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d222a32c-367f-444a-be26-52b61c7751a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Telti> <http://telicent.io/ontology/primaryName> "Telti" .
<https://starwars.com#planet_Telti> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Telti> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d222a32c-367f-444a-be26-52b61c7751a3> .
<https://starwars.com#d222a32c-367f-444a-be26-52b61c7751a3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Telti"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Telti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Telti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#planet_Telti> <http://www.w3.org/2000/01/rdf-schema#comment> "Telti was an astronomical object in the galaxy's Inner Rim. " .

