Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yashuvhu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Yashuvhu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b7627329-ba1a-40a0-aefd-ed57b42ac034> .
<https://starwars.com#planet_Yashuvhu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F9> .
<https://starwars.com#planet_Yashuvhu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Yashuvhu> <http://www.w3.org/2000/01/rdf-schema#comment> "Yashuvhu was an astronomical object located within the territory of the Unknown Regions' Chiss Ascendancy government. " .
<https://starwars.com#b7627329-ba1a-40a0-aefd-ed57b42ac034> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yashuvhu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b7627329-ba1a-40a0-aefd-ed57b42ac034> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yashuvhu> <http://telicent.io/ontology/primaryName> "Yashuvhu" .

