Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a35a73c3-1b48-4345-8efb-cf29c640985b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vaykaaris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vaykaaris> <http://telicent.io/ontology/primaryName> "Vaykaaris" .
<https://starwars.com#a35a73c3-1b48-4345-8efb-cf29c640985b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vaykaaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#planet_Vaykaaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Vaykaaris> <http://www.w3.org/2000/01/rdf-schema#comment> "The Vaykaaris system was located in the Southern Core portion of[2] the Colonies.[1] In approximately 41 BBY,[3] a terrorist group[4] based in the system[2] threatened more than a hundred worlds in the Colonies in what became known as the Vaykaaris Uprising. To resolve the dispute, twelve members of the Jedi Order were dispatched aboard the corvette Freedom's Messenger." .
<https://starwars.com#planet_Vaykaaris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vaykaaris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a35a73c3-1b48-4345-8efb-cf29c640985b> .

