Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Belderone> <http://telicent.io/ontology/primaryName> "Belderone" .
<https://starwars.com#planet_RhenVar> <http://www.w3.org/2000/01/rdf-schema#comment> "Rhen Var was a planet with frigid environments located near the Galidraan system in the galaxy's Outer Rim Territories. During the galaxy-spanning conflict known as the Clone Wars, the Galactic Republic deployed clone cold assault troopers on the world; troops specifically equipped to deal with cold environments. During the reign of the Galactic Empire, an Imperial outpost was located on Rhen Var. After the stolen Imperial corvette Carrion Spike attacked Imperial facilities in the Galidraan star system, the planet's outpost was considered as one of the potential targets for the corvette by Moff Wilhuff Tarkin. Due to the relative unimportance of the outpost on Rhen Var, Tarkin decided that the Imperial assets on the planet Nam Chorios were a more likely choice for the rebel cell piloting the stolen starship. " .
<https://starwars.com#cfc8af8f-f885-431f-8a57-816266408028> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#cfc8af8f-f885-431f-8a57-816266408028> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rhen Var"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RhenVar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belderone> .
<https://starwars.com#planet_RhenVar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cfc8af8f-f885-431f-8a57-816266408028> .
<https://starwars.com#planet_RhenVar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Belderone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Belderone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_RhenVar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_RhenVar> <http://telicent.io/ontology/primaryName> "Rhen Var" .

