Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Povanaria> <http://www.w3.org/2000/01/rdf-schema#comment> "Povanaria was a planet in the Gordian Reach. It was located on the Junction-Tierell Loop, between Durgen's Star and Bronsoon. Povanaria was windswept, and most of the world was covered by low grasses and mosses. It was also home to a sentient species, the Povanarians. " .
<https://starwars.com#planet_Povanaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#ca1ea0f5-7fea-4849-af9c-76ea6bdc2d2a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ca1ea0f5-7fea-4849-af9c-76ea6bdc2d2a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Povanaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Povanaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Povanaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca1ea0f5-7fea-4849-af9c-76ea6bdc2d2a> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Povanaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_Povanaria> <http://telicent.io/ontology/primaryName> "Povanaria" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

