Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c78eca5a-e780-440c-b796-25abd06296cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Truuine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c78eca5a-e780-440c-b796-25abd06296cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Truuine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Truuine> <http://www.w3.org/2000/01/rdf-schema#comment> "Truuine was an Inner Rim waterworld planet. It featured an equatorial belt of islands as well as a polar region with mountains and glaciers. By 4000 BBY, the planet was the site of the Truuine Jedi Praxeum, a training facility established by Jedi Master Mroon Jassa. Around that time, the Gotal Kith Kark visited Truuine and encountered Jassa, which eventually led to the former taking up Jedi studies at the Praxeum. During the reign of the Galactic Empire millennia later, Truuine's islands were home to Karkarodon and Patrolian settlers. " .
<https://starwars.com#planet_Truuine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c78eca5a-e780-440c-b796-25abd06296cd> .
<https://starwars.com#planet_Truuine> <http://telicent.io/ontology/primaryName> "Truuine" .
<https://starwars.com#planet_Truuine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Truuine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .

