Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Renillis> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Renillis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#822ef34f-53ad-489f-9855-c0caeb15d939> .
<https://starwars.com#planet_Renillis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#822ef34f-53ad-489f-9855-c0caeb15d939> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Renillis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Renillis> <http://telicent.io/ontology/primaryName> "Renillis" .
<https://starwars.com#822ef34f-53ad-489f-9855-c0caeb15d939> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Renillis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Renillis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .

