Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aargau> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#d59ad9b2-72c3-416c-9f18-1cf1fc490d0b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aargau> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#e7edc586-ade1-4d02-b72f-95c8c80f4b42> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aargau> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d59ad9b2-72c3-416c-9f18-1cf1fc490d0b> .
<https://starwars.com#grid_L10> <http://telicent.io/ontology/primaryName> "L10" .
<https://starwars.com#planet_Aargau> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#e7edc586-ade1-4d02-b72f-95c8c80f4b42> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aargau> <http://telicent.io/ontology/primaryName> "Aargau" .
<https://starwars.com#planet_Aargau> <http://www.w3.org/2000/01/rdf-schema#comment> "Aargau was an astronomical object located in the galaxy's Core Worlds, in grid square L-10 on the Standard Galactic Grid, that was headquarters of the Bank of Aargau. Colossal seventh-stage bank-courier repulsor-trucks were used on Aargau. " .
<https://starwars.com#grid_L10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#d59ad9b2-72c3-416c-9f18-1cf1fc490d0b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aargau"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e7edc586-ade1-4d02-b72f-95c8c80f4b42> .

