Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tyluun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7feb4eed-2ac9-4da3-9b10-0a3a817d9b55> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tyluun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Tyluun> <http://telicent.io/ontology/primaryName> "Tyluun" .
<https://starwars.com#7feb4eed-2ac9-4da3-9b10-0a3a817d9b55> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tyluun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7feb4eed-2ac9-4da3-9b10-0a3a817d9b55> .
<https://starwars.com#planet_Tyluun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Tyluun> <http://www.w3.org/2000/01/rdf-schema#comment> "Tyluun was a gloomy planet located in the Tyluun system of the Juvex sector. It was the homeworld of the Night-Soarers. " .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Tyluun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .

