Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_I-Sector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thila> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Thila> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thila> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c61e0721-74fd-467c-8b09-8efb1451ea8d> .
<https://starwars.com#sector_I-Sector> <http://telicent.io/ontology/primaryName> "I-Sector" .
<https://starwars.com#c61e0721-74fd-467c-8b09-8efb1451ea8d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c61e0721-74fd-467c-8b09-8efb1451ea8d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thila"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thila> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_I-Sector> .
<https://starwars.com#planet_Thila> <http://telicent.io/ontology/primaryName> "Thila" .
<https://starwars.com#planet_Thila> <http://www.w3.org/2000/01/rdf-schema#comment> "Thila was an astronomical object located in the galaxy's Outer Rim Territories. During the Imperial Era, the reinforcement of Thila was carried out by the Alliance to Restore the Republic. Thila's reinforcement, alongside the Battle of Scarif and the evacuation of Hoth, were favorite harrowing tales that veteran Resistance officers liked to impress new recruits with. " .
<https://starwars.com#sector_I-Sector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

