Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sinton> <http://telicent.io/ontology/primaryName> "Sinton" .
<https://starwars.com#b5cb039e-60f9-43a2-a55c-d81bda60fa5a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sinton"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Rago> <http://telicent.io/ontology/primaryName> "Rago" .
<https://starwars.com#planet_Sinton> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet Sinton was located in the Sinton system, a part of the Mid Rim's Rago sector. It lay along the Rago Run hyperlane, which connected it to the Moro and Gilatter systems. Sinton was populated by non-Humans, and at some point by 3 ABY, the planet was subjugated by the Galactic Empire, which subjected the planet's inhabitants to slave labor. " .
<https://starwars.com#sector_Rago> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b5cb039e-60f9-43a2-a55c-d81bda60fa5a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sinton> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sinton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#sector_Rago> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Sinton> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5cb039e-60f9-43a2-a55c-d81bda60fa5a> .
<https://starwars.com#planet_Sinton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rago> .

