Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TaspirIII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TaspirIII> <http://www.w3.org/2000/01/rdf-schema#comment> "Taspir III was a mountainous planet located in the Outer Rim Territories. " .
<https://starwars.com#991eedf7-7964-4ffc-99f0-0c9cb7d65be6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taspir III"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#991eedf7-7964-4ffc-99f0-0c9cb7d65be6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dynali> <http://telicent.io/ontology/primaryName> "Dynali" .
<https://starwars.com#sector_Dynali> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TaspirIII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#991eedf7-7964-4ffc-99f0-0c9cb7d65be6> .
<https://starwars.com#planet_TaspirIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dynali> .
<https://starwars.com#sector_Dynali> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_TaspirIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_TaspirIII> <http://telicent.io/ontology/primaryName> "Taspir III" .

