Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_NewHeurkea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#planet_NewHeurkea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc1ac60e-d546-44df-9476-6acccf4fc903> .
<https://starwars.com#planet_NewHeurkea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_NewHeurkea> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#cc1ac60e-d546-44df-9476-6acccf4fc903> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Heurkea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NewHeurkea> <http://telicent.io/ontology/primaryName> "New Heurkea" .
<https://starwars.com#cc1ac60e-d546-44df-9476-6acccf4fc903> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewHeurkea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

