Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9f4c2172-8186-49cc-96e2-335f00e94cea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Andosha> <http://telicent.io/ontology/primaryName> "Andosha" .
<https://starwars.com#sector_Lambda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Lambda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Andosha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#planet_Andosha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lambda> .
<https://starwars.com#planet_Andosha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9f4c2172-8186-49cc-96e2-335f00e94cea> .
<https://starwars.com#planet_Andosha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Andosha> <http://www.w3.org/2000/01/rdf-schema#comment> "Andosha II was an Aqualish colony world located in the Mid Rim's Lambda sector, on the Corellian Run hyperlane. It was a part of the Andoan Free Colonies, which during the last century of the Galactic Republic struggled against the Aqualish of the planet Ando and the worlds it held influence over. As part of that struggle, the Andoan-affiliated Harch Trench led raids against Andosha II." .
<https://starwars.com#9f4c2172-8186-49cc-96e2-335f00e94cea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Andosha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lambda> <http://telicent.io/ontology/primaryName> "Lambda" .

