Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#856eb9c5-743f-4c2a-867c-13ce51016063> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gromas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Perkell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Perkell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Gromas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#856eb9c5-743f-4c2a-867c-13ce51016063> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gromas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gromas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#856eb9c5-743f-4c2a-867c-13ce51016063> .
<https://starwars.com#planet_Gromas> <http://www.w3.org/2000/01/rdf-schema#comment> "Gromas was an astronomical object located in the Perkell sector of the galaxy's Mid Rim. It was the location of an Imperial depot and supported a mining operation for phrik, a metallic compound that was nearly indestructible. In the year 14 BBY, the Imperial Joint Chiefs believed Gromas' depot was a possible target for former Republic Intelligence captain Berch Teller and his rebel cell and dispatched a task force to defend the installation. The rebels learned of this, however, and attacked Phindar instead. " .
<https://starwars.com#planet_Gromas> <http://telicent.io/ontology/primaryName> "Gromas" .
<https://starwars.com#sector_Perkell> <http://telicent.io/ontology/primaryName> "Perkell" .
<https://starwars.com#planet_Gromas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Perkell> .

