Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b5a7565d-d1bf-4326-a91d-de664b5e220b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Csilla> <http://www.w3.org/2000/01/rdf-schema#comment> "Csilla (pronounced /ˈt͡ʃiːlə/) was a frigid, ice-locked planet in the Unknown Regions. It was the homeworld of the sentient, near-human Chiss species and the capital world of the Chiss Ascendancy. Though largely unknown to the wider galaxy during the age of the Galactic Empire, exploratory missions to the Unknown Regions conducted years later revealed Csilla and other worlds that could be reached through cautious hyperspace jumps. " .
<https://starwars.com#b5a7565d-d1bf-4326-a91d-de664b5e220b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Csilla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Csilla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Csilla> <http://telicent.io/ontology/primaryName> "Csilla" .
<https://starwars.com#planet_Csilla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5a7565d-d1bf-4326-a91d-de664b5e220b> .
<https://starwars.com#planet_Csilla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Csilla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .

