Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Targon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Targon> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Targon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#planet_Targon> <http://telicent.io/ontology/primaryName> "Targon" .
<https://starwars.com#planet_Targon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#feb9dcae-202c-430d-b3e7-8a1230cae4f6> .
<https://starwars.com#feb9dcae-202c-430d-b3e7-8a1230cae4f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Targon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#feb9dcae-202c-430d-b3e7-8a1230cae4f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Targon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

