Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Etti> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Etti> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#407810d2-5d32-44d1-b6a4-5c6acad3d932> .
<https://starwars.com#planet_Etti> <http://www.w3.org/2000/01/rdf-schema#comment> "The Etti were a sentient species of near-Humans who were originally native to the Galactic Core. " .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Etti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Etti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#407810d2-5d32-44d1-b6a4-5c6acad3d932> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Etti"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#407810d2-5d32-44d1-b6a4-5c6acad3d932> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Etti> <http://telicent.io/ontology/primaryName> "Etti" .

