Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#df46f5e4-d58a-4079-85a0-fff633e80059> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zephry"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zephry> <http://www.w3.org/2000/01/rdf-schema#comment> "Zephry was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Zephry> <http://telicent.io/ontology/primaryName> "Zephry" .
<https://starwars.com#planet_Zephry> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df46f5e4-d58a-4079-85a0-fff633e80059> .
<https://starwars.com#planet_Zephry> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Zephry> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#df46f5e4-d58a-4079-85a0-fff633e80059> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zephry> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

