Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Uaua> <http://telicent.io/ontology/primaryName> "Uaua" .
<https://starwars.com#planet_Uaua> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a general location. You can help Wookieepedia by expanding it. " .
<https://starwars.com#planet_Uaua> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Uaua> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Uaua> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#f28363f7-2c91-424b-ab37-904dfab9336c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f28363f7-2c91-424b-ab37-904dfab9336c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Uaua"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Uaua> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f28363f7-2c91-424b-ab37-904dfab9336c> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

