Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vensensor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pendari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0f545614-a8ca-42d4-b8a0-1c707e9826d6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pendari> <http://telicent.io/ontology/primaryName> "Pendari" .
<https://starwars.com#0f545614-a8ca-42d4-b8a0-1c707e9826d6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pendari"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pendari> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0f545614-a8ca-42d4-b8a0-1c707e9826d6> .
<https://starwars.com#planet_Pendari> <http://www.w3.org/2000/01/rdf-schema#comment> "Pendari was a planet in the Expansion Region, located on the Corellian Trade Spine rimward of the Kinyen system. " .
<https://starwars.com#planet_Pendari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vensensor> .
<https://starwars.com#sector_Vensensor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Vensensor> <http://telicent.io/ontology/primaryName> "Vensensor" .
<https://starwars.com#planet_Pendari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .

