Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Lostar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Kidriff> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#e6d86c98-bc30-4c5d-9761-121d5751185f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kidriff> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6d86c98-bc30-4c5d-9761-121d5751185f> .
<https://starwars.com#planet_Kidriff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Lostar> <http://telicent.io/ontology/primaryName> "Lostar" .
<https://starwars.com#sector_Lostar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kidriff> <http://telicent.io/ontology/primaryName> "Kidriff" .
<https://starwars.com#e6d86c98-bc30-4c5d-9761-121d5751185f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kidriff"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kidriff> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Kidriff> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lostar> .

