Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Denebia> <http://telicent.io/ontology/primaryName> "Denebia" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Denebia> <http://www.w3.org/2000/01/rdf-schema#comment> "Denebia was an agriworld in the Senex sector of the Mid Rim. It was located on the Senex-Juvex Loop, at the junction of a hyperlane that led to the planet Suliana in The Tangles. It was a cool world, covered by dry plains which were punctuated by plantations and towns belonging to House Hax. " .
<https://starwars.com#50a1d2b3-d234-4677-9d38-fa8c7219ff73> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Denebia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Denebia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#50a1d2b3-d234-4677-9d38-fa8c7219ff73> .
<https://starwars.com#planet_Denebia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Denebia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#50a1d2b3-d234-4677-9d38-fa8c7219ff73> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Denebia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .

