Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorVosadii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorVosadii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#645dcecc-6e1f-47b6-928f-e41a8b572068> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Vosadii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorVosadii> <http://telicent.io/ontology/primaryName> "Kor Vosadii" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#645dcecc-6e1f-47b6-928f-e41a8b572068> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorVosadii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Vosadii was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Vosadii kajidic. " .
<https://starwars.com#planet_KorVosadii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#645dcecc-6e1f-47b6-928f-e41a8b572068> .
<https://starwars.com#planet_KorVosadii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

