Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jamiron> <http://www.w3.org/2000/01/rdf-schema#comment> "Jamiron was a world of the Chiss Ascendancy. Mitth'ali'astov undertook her formal schooling on Jamiron. The Ascendancy's Clarr family owned an electronics factory on the world. " .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jamiron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#90009d49-2f08-46fb-8811-d3d1bd85ba21> .
<https://starwars.com#planet_Jamiron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#90009d49-2f08-46fb-8811-d3d1bd85ba21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jamiron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Jamiron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jamiron> <http://telicent.io/ontology/primaryName> "Jamiron" .
<https://starwars.com#90009d49-2f08-46fb-8811-d3d1bd85ba21> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jamiron"^^<http://www.w3.org/2001/XMLSchema#string> .

