Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gandolo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2f4e7c9e-9893-43af-b2e4-f16e7accb74d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Lahara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gandolo> <http://www.w3.org/2000/01/rdf-schema#comment> "Although the Wookiees were forced to abandon their colonization effort, Solo and Chewbacca promised to help them set up a new colony elsewhere. The incident turned into an utter humiliation for Bossk, whom Solo and Chewbacca had left trapped in his ruined ship, rather than killing him. Bossk, determined to avenge himself for the embarrassment, would be painfully reminded of the Gandolo IV fiasco on occasion for the next twenty-five years. " .
<https://starwars.com#planet_Gandolo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M5> .
<https://starwars.com#planet_Gandolo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lahara> .
<https://starwars.com#sector_Lahara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Lahara> <http://telicent.io/ontology/primaryName> "Lahara" .
<https://starwars.com#2f4e7c9e-9893-43af-b2e4-f16e7accb74d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gandolo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gandolo> <http://telicent.io/ontology/primaryName> "Gandolo" .
<https://starwars.com#planet_Gandolo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2f4e7c9e-9893-43af-b2e4-f16e7accb74d> .

