Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#21dfcc2b-e280-441d-abcf-8883b0ddbf7d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "F13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#be2fdd5f-8aeb-465a-8bad-86065bb7bd39> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zonama Sekot"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_F13> <http://telicent.io/ontology/primaryName> "F13" .
<https://starwars.com#planet_ZonamaSekot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_ZonamaSekot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F13> .
<https://starwars.com#be2fdd5f-8aeb-465a-8bad-86065bb7bd39> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ZonamaSekot> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be2fdd5f-8aeb-465a-8bad-86065bb7bd39> .
<https://starwars.com#grid_F13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#21dfcc2b-e280-441d-abcf-8883b0ddbf7d> .
<https://starwars.com#21dfcc2b-e280-441d-abcf-8883b0ddbf7d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_ZonamaSekot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_F13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_ZonamaSekot> <http://telicent.io/ontology/primaryName> "Zonama Sekot" .
<https://starwars.com#grid_F13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_ZonamaSekot> <http://www.w3.org/2000/01/rdf-schema#comment> "Zonama Sekot was an astronomical object located in the Unknown Regions in grid square F-13 on the Standard Galactic Grid. It was situated in an otherwise empty and unexplored area in the neighborhood of the planets Ahch-To and Rakata Prime, westward of the desert world Jakku, which was located in the Western Reaches of the Inner Rim. " .

