Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ninzan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ryndellian> .
<https://starwars.com#planet_Ninzan> <http://telicent.io/ontology/primaryName> "Ninzan" .
<https://starwars.com#planet_Ninzan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P17> .
<https://starwars.com#planet_Ninzan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Ryndellian> <http://telicent.io/ontology/primaryName> "Ryndellian" .
<https://starwars.com#planet_Ninzan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Ninzan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#684df4f4-5a0c-42bb-bedd-1cbcc3d214c2> .
<https://starwars.com#sector_Ryndellian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#684df4f4-5a0c-42bb-bedd-1cbcc3d214c2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ninzan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ryndellian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#684df4f4-5a0c-42bb-bedd-1cbcc3d214c2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

