Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdVaree> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Varee was a Republic Ordnance/Regional Depot world located in the Belshar sector of the Mid Rim. In 22 BBY, Ord Varee was one of the ten planets of the Refugee Relief Coalition, which allowed beings that were displaced by the ongoing Separatist Crisis to resettle on their worlds. " .
<https://starwars.com#c97bbda2-8a69-4180-8e57-2d18b7e3ac69> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdVaree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belshar> .
<https://starwars.com#planet_OrdVaree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Belshar> <http://telicent.io/ontology/primaryName> "Belshar" .
<https://starwars.com#planet_OrdVaree> <http://telicent.io/ontology/primaryName> "Ord Varee" .
<https://starwars.com#sector_Belshar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_OrdVaree> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c97bbda2-8a69-4180-8e57-2d18b7e3ac69> .
<https://starwars.com#planet_OrdVaree> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c97bbda2-8a69-4180-8e57-2d18b7e3ac69> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Varee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Belshar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

