Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7597a20d-d04f-4210-8ee8-9191f84d705a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Venaarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Rendel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Venaarian> .
<https://starwars.com#7597a20d-d04f-4210-8ee8-9191f84d705a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rendel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rendel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rendel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#sector_Venaarian> <http://telicent.io/ontology/primaryName> "Venaarian" .
<https://starwars.com#planet_Rendel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7597a20d-d04f-4210-8ee8-9191f84d705a> .
<https://starwars.com#planet_Rendel> <http://telicent.io/ontology/primaryName> "Rendel" .
<https://starwars.com#sector_Venaarian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

