Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#planet_Shuxl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b44f213f-6752-44dc-95b6-1001aaf159ff> .
<https://starwars.com#planet_Shuxl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shuxl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#b44f213f-6752-44dc-95b6-1001aaf159ff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Shuxl> <http://telicent.io/ontology/primaryName> "Shuxl" .
<https://starwars.com#b44f213f-6752-44dc-95b6-1001aaf159ff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shuxl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shuxl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#planet_Shuxl> <http://www.w3.org/2000/01/rdf-schema#comment> "Shuxl was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .

