Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#89425131-38ff-466a-a065-11f7cc3a02d0> .
<https://starwars.com#planet_Altier> <http://www.w3.org/2000/01/rdf-schema#comment> "Altier was an astronomical object located in the Altier system, a part of the Altier sector in the Slice portion of the Expansion Region. " .
<https://starwars.com#89425131-38ff-466a-a065-11f7cc3a02d0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Altier> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#grid_O13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Altier> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Altier> .
<https://starwars.com#grid_O13> <http://telicent.io/ontology/primaryName> "O13" .
<https://starwars.com#planet_Altier> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1843ca82-b202-4414-951e-2bb24c1c2299> .
<https://starwars.com#sector_Altier> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Altier> <http://telicent.io/ontology/primaryName> "Altier" .
<https://starwars.com#planet_Altier> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#89425131-38ff-466a-a065-11f7cc3a02d0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#1843ca82-b202-4414-951e-2bb24c1c2299> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Altier"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Altier> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Altier> <http://telicent.io/ontology/primaryName> "Altier" .
<https://starwars.com#grid_O13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#1843ca82-b202-4414-951e-2bb24c1c2299> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

