Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Javin> <http://www.w3.org/2000/01/rdf-schema#comment> "Javin was an astronomical object in the Mugaari Space's Javin Sector. " .
<https://starwars.com#planet_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .
<https://starwars.com#planet_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#42317ce6-2d9d-4397-8ac8-c9d781e80829> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Javin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#42317ce6-2d9d-4397-8ac8-c9d781e80829> .
<https://starwars.com#planet_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#42317ce6-2d9d-4397-8ac8-c9d781e80829> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Javin"^^<http://www.w3.org/2001/XMLSchema#string> .

