Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tyus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Tyus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#82aab590-ab8f-466f-bcf1-b6027cd0c65c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TyusCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Tyus Cluster was a cluster of black holes located in the Tyus sector of the Mid Rim. " .
<https://starwars.com#planet_TyusCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tyus> .
<https://starwars.com#planet_TyusCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#82aab590-ab8f-466f-bcf1-b6027cd0c65c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tyus Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tyus> <http://telicent.io/ontology/primaryName> "Tyus" .
<https://starwars.com#planet_TyusCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TyusCluster> <http://telicent.io/ontology/primaryName> "Tyus Cluster" .
<https://starwars.com#planet_TyusCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82aab590-ab8f-466f-bcf1-b6027cd0c65c> .

