Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bakura> <http://www.w3.org/2000/01/rdf-schema#comment> "Bakura was a planet located in the galaxy's Wild Space. It was connected to the planet Endor by a hyperspace route. At some point, the Resistance pilot Venisa Doza and her astromech droid Torch had an adventure on Bakura, which Doza brought up while attempting to plan her escape from the First Order Star Destroyer that had captured her starfighter. " .
<https://starwars.com#planet_Bakura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bakura> .
<https://starwars.com#grid_G16> <http://telicent.io/ontology/primaryName> "G16" .
<https://starwars.com#grid_G16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Bakura> <http://telicent.io/ontology/primaryName> "Bakura" .
<https://starwars.com#83a9dfff-530c-4561-9fec-d36b04e71bc4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#ee0a3dd4-a908-419a-9b8f-b3db91217911> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_G16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Bakura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#83a9dfff-530c-4561-9fec-d36b04e71bc4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bakura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bakura> <http://telicent.io/ontology/primaryName> "Bakura" .
<https://starwars.com#sector_Bakura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#grid_G16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#83a9dfff-530c-4561-9fec-d36b04e71bc4> .
<https://starwars.com#ee0a3dd4-a908-419a-9b8f-b3db91217911> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bakura"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bakura> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ee0a3dd4-a908-419a-9b8f-b3db91217911> .
<https://starwars.com#planet_Bakura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G16> .

