Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d94faf60-a185-4384-a07d-352152f6668e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Troos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Troos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Troos> <http://www.w3.org/2000/01/rdf-schema#comment> "Troos was a planet located within the Gordian Reach of the Outer Rim Territories. " .
<https://starwars.com#planet_Troos> <http://telicent.io/ontology/primaryName> "Troos" .
<https://starwars.com#planet_Troos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Troos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d94faf60-a185-4384-a07d-352152f6668e> .
<https://starwars.com#d94faf60-a185-4384-a07d-352152f6668e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Troos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

