Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4782a2ca-b8fb-4ffb-8253-ccdc09cadf7e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#4782a2ca-b8fb-4ffb-8253-ccdc09cadf7e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elgit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Elgit> <http://telicent.io/ontology/primaryName> "Elgit" .
<https://starwars.com#planet_Elgit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Elgit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4782a2ca-b8fb-4ffb-8253-ccdc09cadf7e> .
<https://starwars.com#planet_Elgit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Elgit> <http://www.w3.org/2000/01/rdf-schema#comment> "Elgit was a minor trade world that was located within the Elgit system of the galaxy's Hutt Space region and lay on the hyperlane called The Dead Road, which connected it to the planets of Zisia and Usk. The Elgit–M'Hanna Corridor linked Elgit to the world of Sakifwanna, and the trade planet was also joined by a hyperspace route to the Gos Hutta system. " .
<https://starwars.com#planet_Elgit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

