Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Esseles> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0824c66d-1e1c-451e-9f89-26b18a017de4> .
<https://starwars.com#planet_Esseles> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Esseles> <http://telicent.io/ontology/primaryName> "Esseles" .
<https://starwars.com#planet_Esseles> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Esseles> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#0824c66d-1e1c-451e-9f89-26b18a017de4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Esseles> <http://www.w3.org/2000/01/rdf-schema#comment> "Under Imperial Control. The Empire has a listening post concealed in Esseles icy ring." .
<https://starwars.com#0824c66d-1e1c-451e-9f89-26b18a017de4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Esseles"^^<http://www.w3.org/2001/XMLSchema#string> .

