Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Naos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#19e4ba6b-5e27-49f1-8378-84d724ec107d> .
<https://starwars.com#19e4ba6b-5e27-49f1-8378-84d724ec107d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Naos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Naos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#19e4ba6b-5e27-49f1-8378-84d724ec107d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Naos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Naos> <http://telicent.io/ontology/primaryName> "Naos" .
<https://starwars.com#planet_Naos> <http://www.w3.org/2000/01/rdf-schema#comment> "Naos was an astronomical object located in the regions known as the Outer Rim Territories and the Slice. It was situated in grid square S-18 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Naos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S18> .

