Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rutan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L20> .
<https://starwars.com#sector_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#7d5901a3-4734-4ee7-a47d-9059850becc3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rutan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rutan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atravis> .
<https://starwars.com#planet_Rutan> <http://www.w3.org/2000/01/rdf-schema#comment> "Rutan was an astronomical object in the Outer Rim Territories of the galaxy, situated on the Hydian Way. " .
<https://starwars.com#planet_Rutan> <http://telicent.io/ontology/primaryName> "Rutan" .
<https://starwars.com#7d5901a3-4734-4ee7-a47d-9059850becc3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rutan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Rutan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7d5901a3-4734-4ee7-a47d-9059850becc3> .

