Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#be2423f2-18a7-481d-aa31-95bdc23bceac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Plesstil> <http://www.w3.org/2000/01/rdf-schema#comment> "Plesstil was an astronomical object located in the Plesstil system, a part of the Outer Rim Territories' Veragi sector. A hyperlane linked Plesstil to the Veragi system as well as the northern reaches of the galaxy. " .
<https://starwars.com#planet_Plesstil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Veragi> .
<https://starwars.com#planet_Plesstil> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be2423f2-18a7-481d-aa31-95bdc23bceac> .
<https://starwars.com#grid_L3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#80221cfa-6882-47a7-ad73-8b5f4f665250> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#planet_Plesstil> <http://telicent.io/ontology/primaryName> "Plesstil" .
<https://starwars.com#be2423f2-18a7-481d-aa31-95bdc23bceac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Plesstil"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Plesstil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L3> <http://telicent.io/ontology/primaryName> "L3" .
<https://starwars.com#grid_L3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#80221cfa-6882-47a7-ad73-8b5f4f665250> .
<https://starwars.com#planet_Plesstil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L3> .
<https://starwars.com#grid_L3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#80221cfa-6882-47a7-ad73-8b5f4f665250> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

