Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Linuri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#af663571-6121-4c32-a350-a4f303cd5f38> .
<https://starwars.com#sector_Doldur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Linuri> <http://telicent.io/ontology/primaryName> "Linuri" .
<https://starwars.com#planet_Linuri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Doldur> .
<https://starwars.com#af663571-6121-4c32-a350-a4f303cd5f38> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#af663571-6121-4c32-a350-a4f303cd5f38> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Linuri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Linuri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Linuri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#sector_Doldur> <http://telicent.io/ontology/primaryName> "Doldur" .
<https://starwars.com#planet_Linuri> <http://www.w3.org/2000/01/rdf-schema#comment> "Linuri was a planet in the Doldur sector with a diverse ecosystem. Most of the planet's regions could support humanoid life. " .
<https://starwars.com#sector_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

