Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NearPando> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#9570c7b5-b32c-4011-aee3-ed32b3069193> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Near Pando"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NearPando> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S14> .
<https://starwars.com#planet_NearPando> <http://www.w3.org/2000/01/rdf-schema#comment> "Near Pando was an emerging trade world that was located within the Near Pando system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet lay on the hyperlane called the Pando Spur that connected it to the world of Far Pando. Near Pando was the site of ancient and mysterious ruins known as the Malabar Construct. " .
<https://starwars.com#planet_NearPando> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#9570c7b5-b32c-4011-aee3-ed32b3069193> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NearPando> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9570c7b5-b32c-4011-aee3-ed32b3069193> .
<https://starwars.com#planet_NearPando> <http://telicent.io/ontology/primaryName> "Near Pando" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

