Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Coonee> <http://telicent.io/ontology/primaryName> "Coonee" .
<https://starwars.com#eb03c9b6-1b87-44fd-ab08-d5094b3e29c2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Coonee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Coonee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Coonee> <http://www.w3.org/2000/01/rdf-schema#comment> "Coonee was a planet in the galaxy. According to a theory from smuggler Tregga, the Wookiee Chewbacca raised an orphaned Han Solo after the end of the Clone Wars, and before being captured by the Galactic Empire on the planet Mimban they made their living on planets such as Coonee and Saberhing. " .
<https://starwars.com#eb03c9b6-1b87-44fd-ab08-d5094b3e29c2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Coonee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brevost> .
<https://starwars.com#planet_Coonee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#sector_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Coonee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eb03c9b6-1b87-44fd-ab08-d5094b3e29c2> .

