Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nimban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Nimban> <http://www.w3.org/2000/01/rdf-schema#comment> "Nimban was a planet located in Hutt Space that was the homeworld of the Nimbanel species. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#f4fd5f8e-bd85-4279-94fd-7bfc54168729> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nimban> <http://telicent.io/ontology/primaryName> "Nimban" .
<https://starwars.com#f4fd5f8e-bd85-4279-94fd-7bfc54168729> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nimban"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nimban> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f4fd5f8e-bd85-4279-94fd-7bfc54168729> .
<https://starwars.com#planet_Nimban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Nimban> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

