Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Hevvrol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#fa0ed532-f441-4187-9c0c-d8bdca58bca7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Indobok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Indobok> <http://www.w3.org/2000/01/rdf-schema#comment> "Indobok was the living moon of Kalarba, orbiting near Hosk Station. In actuality, it was a giant B'rknaa. The other B'rknaa that lived on Indobok were Indobok's children. " .
<https://starwars.com#planet_Indobok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fa0ed532-f441-4187-9c0c-d8bdca58bca7> .
<https://starwars.com#sector_Hevvrol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Hevvrol> <http://telicent.io/ontology/primaryName> "Hevvrol" .
<https://starwars.com#planet_Indobok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#planet_Indobok> <http://telicent.io/ontology/primaryName> "Indobok" .
<https://starwars.com#fa0ed532-f441-4187-9c0c-d8bdca58bca7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Indobok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Indobok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hevvrol> .

