Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#baf67916-2855-4464-9907-1a13870063dc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xochtl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#baf67916-2855-4464-9907-1a13870063dc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Xochtl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#baf67916-2855-4464-9907-1a13870063dc> .
<https://starwars.com#planet_Xochtl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Xochtl> <http://www.w3.org/2000/01/rdf-schema#comment> "Xochtl was a planet in the Xochtl system of the Gordian Reach in the Outer Rim. It was a rocky world of crags and spires, and with gravity that was slightly lighter than normal. It was the homeworld of the Bagmims. " .
<https://starwars.com#planet_Xochtl> <http://telicent.io/ontology/primaryName> "Xochtl" .
<https://starwars.com#planet_Xochtl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Xochtl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

