Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lankashiir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#02790af3-e5b6-41fb-84f6-f61a1c82f05b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lankashiir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02790af3-e5b6-41fb-84f6-f61a1c82f05b> .
<https://starwars.com#02790af3-e5b6-41fb-84f6-f61a1c82f05b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lankashiir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lankashiir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Lankashiir> <http://telicent.io/ontology/primaryName> "Lankashiir" .
<https://starwars.com#planet_Lankashiir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Lankashiir> <http://www.w3.org/2000/01/rdf-schema#comment> "Lankashiir was a planet of the Lankashiir system, within the Colonies region of the galaxy. During the Imperial Period, Lankashiir was under the control of the Galactic Empire. A planet thriving with forests, Lankashiir was home to Adion Lang, a lieutenant serving with the Imperial Security Bureau, and the Durasha family, a Human family with strong Imperial ties. " .

