Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_FarIndosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#5163306d-c307-4ee4-83cf-835bce2b37ba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Far Indosa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_FarIndosa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5163306d-c307-4ee4-83cf-835bce2b37ba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_FarIndosa> <http://telicent.io/ontology/primaryName> "Far Indosa" .
<https://starwars.com#planet_FarIndosa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5163306d-c307-4ee4-83cf-835bce2b37ba> .
<https://starwars.com#planet_FarIndosa> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_FarIndosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

