Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cc1709e5-dda5-48bd-913f-bb90aa4e9e8b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Nembus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Nembus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Carosi> <http://www.w3.org/2000/01/rdf-schema#comment> "Carosi was the primary star in the Carosus system. In 200 BBY the five innermost planets were destroyed when it expanded into a red giant. " .
<https://starwars.com#planet_Carosi> <http://telicent.io/ontology/primaryName> "Carosi" .
<https://starwars.com#planet_Carosi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nembus> .
<https://starwars.com#cc1709e5-dda5-48bd-913f-bb90aa4e9e8b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carosi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Nembus> <http://telicent.io/ontology/primaryName> "Nembus" .
<https://starwars.com#planet_Carosi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Carosi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc1709e5-dda5-48bd-913f-bb90aa4e9e8b> .
<https://starwars.com#planet_Carosi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P4> .

