Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sinsang> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#988730d2-02c4-4a47-bf01-087a4dd7b182> .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sinsang> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sinsang> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#planet_Sinsang> <http://telicent.io/ontology/primaryName> "Sinsang" .
<https://starwars.com#988730d2-02c4-4a47-bf01-087a4dd7b182> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sinsang"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sinsang> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#planet_Sinsang> <http://www.w3.org/2000/01/rdf-schema#comment> "Sinsang was an industrious world located in the Sinsang system, a part of the Raioballo sector in the New Territories portion of the Outer Rim Territories. It was situated on the hyperlane known as the Veragi Trade Route, which connected it to the Anx Minor and Dantooine systems. " .
<https://starwars.com#988730d2-02c4-4a47-bf01-087a4dd7b182> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

