Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Parkis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Parkis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Parkis> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#16a83aa2-8812-400b-85f2-24be28e36e71> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Parkis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#16a83aa2-8812-400b-85f2-24be28e36e71> .
<https://starwars.com#planet_Parkis> <http://telicent.io/ontology/primaryName> "Parkis" .
<https://starwars.com#planet_Parkis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#16a83aa2-8812-400b-85f2-24be28e36e71> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Parkis"^^<http://www.w3.org/2001/XMLSchema#string> .

