Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Honoghr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#a2843d97-32c6-449e-b7c1-c7339173cfd8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Honoghr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Honoghr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Honoghr> <http://telicent.io/ontology/primaryName> "Honoghr" .
<https://starwars.com#planet_Honoghr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#a2843d97-32c6-449e-b7c1-c7339173cfd8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Honoghr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2843d97-32c6-449e-b7c1-c7339173cfd8> .
<https://starwars.com#planet_Honoghr> <http://www.w3.org/2000/01/rdf-schema#comment> "Honoghr was an astronomical object located in the galaxy's Outer Rim Territories that was the homeworld of the Noghri species. " .

