Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vanik> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#762aead3-eaac-43f4-a267-0b3fe35bcbdd> .
<https://starwars.com#planet_Vanik> <http://telicent.io/ontology/primaryName> "Vanik" .
<https://starwars.com#planet_Vanik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#762aead3-eaac-43f4-a267-0b3fe35bcbdd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vanik> <http://www.w3.org/2000/01/rdf-schema#comment> "Vanik was a world located within the Vanik system of the Inner Rim. " .
<https://starwars.com#762aead3-eaac-43f4-a267-0b3fe35bcbdd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vanik"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vanik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#planet_Vanik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

