Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#76024330-648c-421c-8bc5-85e6cd66c735> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#b9748bba-5fab-43be-93d7-a2965ed65a00> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Baradas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Baradas> <http://telicent.io/ontology/primaryName> "Baradas" .
<https://starwars.com#b9748bba-5fab-43be-93d7-a2965ed65a00> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#76024330-648c-421c-8bc5-85e6cd66c735> .
<https://starwars.com#planet_Baradas> <http://www.w3.org/2000/01/rdf-schema#comment> "Baradas was a terrestrial astronomical object. During the Galactic Civil War between the Rebel Alliance and the Galactic Empire, the rebel pilot and squadron commander Nath Tensent experienced a bad landing on Baradas in his first Y-wing starfighter sometime after his defection to the Alliance from the Empire around 0 BBY. The incident resulted in the starfighter's underside and one of its nacelles being torn off, the remains of the Y-wing being irreparable. " .
<https://starwars.com#planet_Baradas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#grid_L8> <http://telicent.io/ontology/primaryName> "L8" .
<https://starwars.com#planet_Baradas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#76024330-648c-421c-8bc5-85e6cd66c735> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Baradas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b9748bba-5fab-43be-93d7-a2965ed65a00> .
<https://starwars.com#planet_Baradas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

