Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Namta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#planet_Namta> <http://telicent.io/ontology/primaryName> "Nam'ta" .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Namta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dc877c48-72a5-45c6-a5c6-8e1db9683c07> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dc877c48-72a5-45c6-a5c6-8e1db9683c07> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nam'ta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Namta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dc877c48-72a5-45c6-a5c6-8e1db9683c07> .
<https://starwars.com#planet_Namta> <http://www.w3.org/2000/01/rdf-schema#comment> "Nam'ta was a gas giant located in the Nam'ta system, a part of the Outer Rim Territories' Atrivis sector. Its clouds formed bands of red, orange, and white. The planet was inhabited during the Galactic War between the Galactic Republic and the resurgent Sith Empire, and governed by a local government. At that time a local organization planned to leak thousands of Republic diplomatic dispatches, prompting a Republic-allied individual to urge the local government to clamp down on the organization. " .
<https://starwars.com#planet_Namta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

