Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ruul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ruul> <http://telicent.io/ontology/primaryName> "Ruul" .
<https://starwars.com#planet_Ruul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#baab75a2-14ca-461d-b132-70d61bca3ab1> .
<https://starwars.com#baab75a2-14ca-461d-b132-70d61bca3ab1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ruul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#baab75a2-14ca-461d-b132-70d61bca3ab1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ruul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ruul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Ruul> <http://www.w3.org/2000/01/rdf-schema#comment> "Ruul was a Dathomirian Zabrak male from the planet Dathomir who was part of a clan of the Nightbrothers during the Clone Wars. Prior to the Second Battle of Dathomir of 19 BBY, Ruul met with Mak Eak, a Nightbrother leader, in a warehouse-like building on a mission for the runaway Nightbrother Arzo Suun to help steal supplies for Eak. Ruul and Eak were eventually caught by a group of Nightsisters led by Nelsel, who detected the Nightbrothers' presence through the Force. " .

