Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tamarin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sevarcos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tamarin> .
<https://starwars.com#planet_Sevarcos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N19> .
<https://starwars.com#planet_Sevarcos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#729ad6d7-87c4-4fc4-b02a-e479930f91f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sevarcos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#729ad6d7-87c4-4fc4-b02a-e479930f91f9> .
<https://starwars.com#729ad6d7-87c4-4fc4-b02a-e479930f91f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sevarcos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sevarcos> <http://www.w3.org/2000/01/rdf-schema#comment> "Sevarcos was a planet in the galaxy's Outer Rim Territories that was the site of a battle in the months after the Battle of Endor. During the battle, the New Republic successfully liberated at least one spice mine that had been operating on slave labor under the control of the Empire. The area of the spice mine was dry, dusty, and surrounded by canyons, and at least one of the slavemasters was Zygerrian. " .
<https://starwars.com#sector_Tamarin> <http://telicent.io/ontology/primaryName> "Tamarin" .
<https://starwars.com#sector_Tamarin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sevarcos> <http://telicent.io/ontology/primaryName> "Sevarcos" .

