Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f5424d5b-f951-4bfa-a4b4-17c111425090> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kafane> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f5424d5b-f951-4bfa-a4b4-17c111425090> .
<https://starwars.com#planet_Kafane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#f5424d5b-f951-4bfa-a4b4-17c111425090> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kafane"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kafane> <http://telicent.io/ontology/primaryName> "Kafane" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kafane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#planet_Kafane> <http://www.w3.org/2000/01/rdf-schema#comment> "Kafane was a poor agricultural planet that was located within the Kafane system of the galaxy's Hutt Space region. Kafane was connected to the worlds of Nimia and Ulmatra by the hyperlane called The Dead Road. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Kafane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

