Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_UtegetuNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_UtegetuNebula> <http://www.w3.org/2000/01/rdf-schema#comment> "The Utegetu Nebula was a nebula located in the galaxy's Mid Rim in grid square I-8 of the Standard Galactic Grid. It was connected to the world of Benath by a hyperspace route. " .
<https://starwars.com#planet_UtegetuNebula> <http://telicent.io/ontology/primaryName> "Utegetu Nebula" .
<https://starwars.com#planet_UtegetuNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I8> .
<https://starwars.com#04b5708d-6be6-438b-8627-e93b40b24f1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#04b5708d-6be6-438b-8627-e93b40b24f1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Utegetu Nebula"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_UtegetuNebula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_UtegetuNebula> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#04b5708d-6be6-438b-8627-e93b40b24f1b> .

