Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Garqi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7fcb1c41-49b6-43c7-9e3f-ab23ae3256b2> .
<https://starwars.com#planet_Garqi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#7fcb1c41-49b6-43c7-9e3f-ab23ae3256b2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7fcb1c41-49b6-43c7-9e3f-ab23ae3256b2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Garqi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Garqi> <http://telicent.io/ontology/primaryName> "Garqi" .
<https://starwars.com#planet_Garqi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Garqi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Garqi> <http://www.w3.org/2000/01/rdf-schema#comment> "Garqi was an astronomical object in the galaxy's Outer Rim Territories. " .

