Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#537e50df-a04d-4c4f-8038-2e1eeb711055> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorHestilic> <http://telicent.io/ontology/primaryName> "Kor Hestilic" .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#537e50df-a04d-4c4f-8038-2e1eeb711055> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Hestilic"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorHestilic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorHestilic> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Hestilic was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Hestilic kajidic. " .
<https://starwars.com#planet_KorHestilic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#planet_KorHestilic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorHestilic> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#537e50df-a04d-4c4f-8038-2e1eeb711055> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

