Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Trammis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Trammis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#6fb2c9b6-cf9b-4e41-9ab3-c04320580256> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trammis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Trammis> <http://www.w3.org/2000/01/rdf-schema#comment> "Trammis was the primary star of the Trammis system. " .
<https://starwars.com#6fb2c9b6-cf9b-4e41-9ab3-c04320580256> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trammis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trammis> <http://telicent.io/ontology/primaryName> "Trammis" .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Trammis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6fb2c9b6-cf9b-4e41-9ab3-c04320580256> .

