Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clythe> <http://telicent.io/ontology/primaryName> "Clythe" .
<https://starwars.com#sector_Clythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Vortex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K7> .
<https://starwars.com#planet_Vortex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clythe> .
<https://starwars.com#f19ae95e-8370-4cf8-ad8d-439270d0062f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vortex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Clythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f19ae95e-8370-4cf8-ad8d-439270d0062f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vortex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f19ae95e-8370-4cf8-ad8d-439270d0062f> .
<https://starwars.com#planet_Vortex> <http://telicent.io/ontology/primaryName> "Vortex" .
<https://starwars.com#planet_Vortex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vortex> <http://www.w3.org/2000/01/rdf-schema#comment> "Vortex was an astronomical object located in the galaxy's Mid Rim. It was connected to Vicondor via hyperspace routes. " .

