Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jtptan> <http://telicent.io/ontology/primaryName> "J't'p'tan" .
<https://starwars.com#planet_Jtptan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#0714969d-b8fd-4534-a19c-2a7074e31c2e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J't'p'tan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jtptan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0714969d-b8fd-4534-a19c-2a7074e31c2e> .
<https://starwars.com#planet_Jtptan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jtptan> <http://www.w3.org/2000/01/rdf-schema#comment> "An almost untouched world in the Koornacht Cluster, J't'p'tan (known to most simply as Doornik-628E) was settled by the H'kig, fleeing a conflict on Rishi. The planet was named after four sacred glyphs: 'Jeh' (the Immanent), 'Teh' (the Transcendent), 'Peh' (the Eternal), and 'Tan' (the Conscious Essence). Only the last of these glyphs was considered secular enough to be spelled out fully. " .
<https://starwars.com#planet_Jtptan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#0714969d-b8fd-4534-a19c-2a7074e31c2e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

