Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Farnica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d2f3be88-7f06-4e49-929e-db8386797238> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Farnica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#d2f3be88-7f06-4e49-929e-db8386797238> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Farnica"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Farnica> <http://telicent.io/ontology/primaryName> "Farnica" .
<https://starwars.com#planet_Farnica> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#d2f3be88-7f06-4e49-929e-db8386797238> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Farnica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Farnica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .

