Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Myomar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Deadalis> .
<https://starwars.com#planet_Myomar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#planet_Myomar> <http://telicent.io/ontology/primaryName> "Myomar" .
<https://starwars.com#planet_Myomar> <http://www.w3.org/2000/01/rdf-schema#comment> "Myomar was a planet located in the galaxy's Expansion Region. Myomar Academy, an Imperial Academy, was located on the planet. " .
<https://starwars.com#50930a57-2436-4f4e-bfe4-f79f31a63637> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Myomar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#50930a57-2436-4f4e-bfe4-f79f31a63637> .
<https://starwars.com#sector_Deadalis> <http://telicent.io/ontology/primaryName> "Deadalis" .
<https://starwars.com#sector_Deadalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Myomar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Deadalis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#50930a57-2436-4f4e-bfe4-f79f31a63637> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Myomar"^^<http://www.w3.org/2001/XMLSchema#string> .

