Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#55171ed5-654f-491f-9234-977b61a9fadf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorAnjiliac> <http://telicent.io/ontology/primaryName> "Kor Anjiliac" .
<https://starwars.com#planet_KorAnjiliac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#55171ed5-654f-491f-9234-977b61a9fadf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Anjiliac"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorAnjiliac> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Anjiliac was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Anjiliac kajidic. " .
<https://starwars.com#planet_KorAnjiliac> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_KorAnjiliac> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#55171ed5-654f-491f-9234-977b61a9fadf> .
<https://starwars.com#planet_KorAnjiliac> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .

