Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tion> <http://telicent.io/ontology/primaryName> "Tion" .
<https://starwars.com#planet_Tion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#48c4f49d-bc4d-4b30-860f-8a7953309f6e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tion"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#48c4f49d-bc4d-4b30-860f-8a7953309f6e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tion> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#48c4f49d-bc4d-4b30-860f-8a7953309f6e> .
<https://starwars.com#planet_Tion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Tion> <http://www.w3.org/2000/01/rdf-schema#comment> "Tion, sometimes referred as Tion Proper, was a planet located within the Tion Hegemony of the Outer Rim Territories, considered as the original center of the Hegemony. " .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

