Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#350699dc-9626-4fa6-a34a-307e0b923ea3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gwori> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#350699dc-9626-4fa6-a34a-307e0b923ea3> .
<https://starwars.com#planet_Gwori> <http://www.w3.org/2000/01/rdf-schema#comment> "Gwori was a planet located in the Clacis sector of the Outer Rim Territories. " .
<https://starwars.com#planet_Gwori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .
<https://starwars.com#planet_Gwori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#350699dc-9626-4fa6-a34a-307e0b923ea3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gwori"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gwori> <http://telicent.io/ontology/primaryName> "Gwori" .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gwori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .

