Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Chitarghar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Chitarghar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gholondreine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chitarghar> .
<https://starwars.com#grid_K15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#8dac45db-eaba-4af5-8945-c6a301131423> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3aaeb7c0-7e70-4d49-adbf-1aff650d0663> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gholondreine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3aaeb7c0-7e70-4d49-adbf-1aff650d0663> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gholondreine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gholondreine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3aaeb7c0-7e70-4d49-adbf-1aff650d0663> .
<https://starwars.com#planet_Gholondreine> <http://www.w3.org/2000/01/rdf-schema#comment> "The Gholondreine were the natives of the planet Gholondreine-β. The scholars and philosophers of the Gholondreine were renowned across the galaxy, and held that all beings owed their highest loyalty to truth, regardless of temporal consequences. Consequently, they were reluctant to implement the changes of the New Order, and around 10 BBY, began circulating critiques of the Galactic Empire's rule. As punishment, Palpatine had all the water stripped from their homeworld and taken to Coruscant. The dying desert world was subsequently abandoned as they moved to nearby systems. " .
<https://starwars.com#grid_K15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8dac45db-eaba-4af5-8945-c6a301131423> .
<https://starwars.com#grid_K15> <http://telicent.io/ontology/primaryName> "K15" .
<https://starwars.com#grid_K15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Chitarghar> <http://telicent.io/ontology/primaryName> "Chitarghar" .
<https://starwars.com#8dac45db-eaba-4af5-8945-c6a301131423> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Gholondreine> <http://telicent.io/ontology/primaryName> "Gholondreine" .
<https://starwars.com#planet_Gholondreine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K15> .

