Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Datar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_Datar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8848f813-17c4-46e0-90f4-efd3f9330415> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8848f813-17c4-46e0-90f4-efd3f9330415> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Datar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Datar> <http://www.w3.org/2000/01/rdf-schema#comment> "Datar was an astronomical object located in the galaxy's Inner Rim. " .
<https://starwars.com#planet_Datar> <http://telicent.io/ontology/primaryName> "Datar" .
<https://starwars.com#planet_Datar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8848f813-17c4-46e0-90f4-efd3f9330415> .
<https://starwars.com#planet_Datar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

