Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Hinakuu> <http://www.w3.org/2000/01/rdf-schema#comment> "Hinakuu was a planet located in the Hinakuu system of the Calamari sector. It was settled by the Mon Calamari at some point between 4400 BBY and 4200 BBY, and lay along the Tidal Circuit hyperlane. " .
<https://starwars.com#df341667-9722-4a43-86f1-c284d9e7f83c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hinakuu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Hinakuu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#df341667-9722-4a43-86f1-c284d9e7f83c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hinakuu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hinakuu> <http://telicent.io/ontology/primaryName> "Hinakuu" .
<https://starwars.com#planet_Hinakuu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hinakuu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df341667-9722-4a43-86f1-c284d9e7f83c> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

