Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Grizmallt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Grizmallt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#2839349c-42c3-4a27-94f7-1642509c97bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Grizmallt> <http://www.w3.org/2000/01/rdf-schema#comment> "Grizmallt was a war-torn planet in the Core Worlds, and the origin of the humans who crash-landed on and colonized Naboo long before the Clone Wars. Commissar was a position of authority on the planet. " .
<https://starwars.com#2839349c-42c3-4a27-94f7-1642509c97bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Grizmallt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Grizmallt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Grizmallt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2839349c-42c3-4a27-94f7-1642509c97bb> .
<https://starwars.com#planet_Grizmallt> <http://telicent.io/ontology/primaryName> "Grizmallt" .

