Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kailion> <http://telicent.io/ontology/primaryName> "Kailion" .
<https://starwars.com#planet_BovoYagen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kailion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_BovoYagen> <http://www.w3.org/2000/01/rdf-schema#comment> "Bovo Yagen was a former Imperial captain who fled the Empire with his wife and four sons. After a period of wandering, the family landed on a planet with a humanoid species. Proving their good intentions to the natives, the family was allowed to settle on the world. Over time, more Humans fleeing the Empire arrived, forming a small outpost. By the time Yagen passed away, the planet bore his name. " .
<https://starwars.com#dd6c1c76-a9af-49c1-8c55-6f1bdcdd3a8a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bovo Yagen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dd6c1c76-a9af-49c1-8c55-6f1bdcdd3a8a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_BovoYagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kailion> .
<https://starwars.com#planet_BovoYagen> <http://telicent.io/ontology/primaryName> "Bovo Yagen" .
<https://starwars.com#planet_BovoYagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#planet_BovoYagen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd6c1c76-a9af-49c1-8c55-6f1bdcdd3a8a> .
<https://starwars.com#sector_Kailion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

