Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jerrist> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jerrist> <http://telicent.io/ontology/primaryName> "Jerrist" .
<https://starwars.com#f3f2c085-6780-4a01-81f4-1cf9e345706f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jerrist"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Jerrist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Jerrist> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#f3f2c085-6780-4a01-81f4-1cf9e345706f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jerrist> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f3f2c085-6780-4a01-81f4-1cf9e345706f> .
<https://starwars.com#planet_Jerrist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .

