Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lansono> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Lansono> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Lansono> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5fec3231-ebdb-4cb1-8507-a03a0daa5449> .
<https://starwars.com#planet_Lansono> <http://telicent.io/ontology/primaryName> "Lansono" .
<https://starwars.com#5fec3231-ebdb-4cb1-8507-a03a0daa5449> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lansono"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lansono> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lansono> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#5fec3231-ebdb-4cb1-8507-a03a0daa5449> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

