Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PatititePattuna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1066bf00-655f-454b-a8ab-c310ade177d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Patitite Pattuna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PatititePattuna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1066bf00-655f-454b-a8ab-c310ade177d7> .
<https://starwars.com#planet_PatititePattuna> <http://telicent.io/ontology/primaryName> "Patitite Pattuna" .
<https://starwars.com#1066bf00-655f-454b-a8ab-c310ade177d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PatititePattuna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_PatititePattuna> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .
<https://starwars.com#planet_PatititePattuna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .

