Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9b984943-206e-433e-8def-e1a561a43c2a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Colla IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_CollaIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#9b984943-206e-433e-8def-e1a561a43c2a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_CollaIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Colla IV was a planet located in the galaxy's Inner Rim, in grid square N-9 on the Standard Galactic Grid where droidekas were manufactured by the Colicoids, while the droid tri-fighter's three-armed design mimicked the skull features of one of its ferocious predators. " .
<https://starwars.com#planet_CollaIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_CollaIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_CollaIV> <http://telicent.io/ontology/primaryName> "Colla IV" .
<https://starwars.com#planet_CollaIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9b984943-206e-433e-8def-e1a561a43c2a> .

