Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Damendine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#696a9f08-b6b7-466a-84db-c621dfe1f19f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Damendine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Damendine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Damendine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Damendine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#696a9f08-b6b7-466a-84db-c621dfe1f19f> .
<https://starwars.com#planet_Damendine> <http://telicent.io/ontology/primaryName> "Damendine" .
<https://starwars.com#696a9f08-b6b7-466a-84db-c621dfe1f19f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Damendine> <http://www.w3.org/2000/01/rdf-schema#comment> "Damendine was a planet located in the Damendine system of the Outer Rim Territories. " .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

