Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Swellen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ddfc03f-4eb3-4d53-9230-d233ec04f39b> .
<https://starwars.com#planet_Swellen> <http://telicent.io/ontology/primaryName> "Swellen" .
<https://starwars.com#9ddfc03f-4eb3-4d53-9230-d233ec04f39b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Swellen> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Swellen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Swellen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L20> .
<https://starwars.com#sector_Airam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Airam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9ddfc03f-4eb3-4d53-9230-d233ec04f39b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Swellen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Swellen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Airam> .
<https://starwars.com#sector_Airam> <http://telicent.io/ontology/primaryName> "Airam" .

