Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Juris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Stend> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#fe22ba42-79ad-45d2-b367-5117b54e6735> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Stend> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Stend> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fe22ba42-79ad-45d2-b367-5117b54e6735> .
<https://starwars.com#planet_Stend> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juris> .
<https://starwars.com#planet_Stend> <http://telicent.io/ontology/primaryName> "Stend" .
<https://starwars.com#fe22ba42-79ad-45d2-b367-5117b54e6735> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Stend"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juris> <http://telicent.io/ontology/primaryName> "Juris" .
<https://starwars.com#sector_Juris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Stend> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P17> .

