Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Venaari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#0d3eb4a0-084f-4749-98ba-e9d4617c8582> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Venaarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Venaari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Venaari> <http://telicent.io/ontology/primaryName> "Venaari" .
<https://starwars.com#planet_Venaari> <http://www.w3.org/2000/01/rdf-schema#comment> "Venaari was a Mid Rim world, and the third planet in the Vellakiya system. It was the headquarters of Venaari Enterprises. The Galactic Empire increased its presence on the planet following the Battle of Endor due to Project Orrad, which was exposed by Shandria L'hnnar. The heightened Imperial security made it difficult for the New Republic to gain a foothold on Venaari. " .
<https://starwars.com#planet_Venaari> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0d3eb4a0-084f-4749-98ba-e9d4617c8582> .
<https://starwars.com#sector_Venaarian> <http://telicent.io/ontology/primaryName> "Venaarian" .
<https://starwars.com#planet_Venaari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Venaarian> .
<https://starwars.com#sector_Venaarian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0d3eb4a0-084f-4749-98ba-e9d4617c8582> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Venaari"^^<http://www.w3.org/2001/XMLSchema#string> .

