Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9686cbf6-3579-4096-a034-1a3ff490959d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Raydonia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belsmuth> .
<https://starwars.com#planet_Raydonia> <http://www.w3.org/2000/01/rdf-schema#comment> "Raydonia was a temperate, forested planet located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Belsmuth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Belsmuth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9686cbf6-3579-4096-a034-1a3ff490959d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Raydonia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Raydonia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#planet_Raydonia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Raydonia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9686cbf6-3579-4096-a034-1a3ff490959d> .
<https://starwars.com#sector_Belsmuth> <http://telicent.io/ontology/primaryName> "Belsmuth" .
<https://starwars.com#planet_Raydonia> <http://telicent.io/ontology/primaryName> "Raydonia" .

