Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KunasHorn> <http://www.w3.org/2000/01/rdf-schema#comment> "Kuna's Horn was a celestial body located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was connected via hyperspace route linked it to the astronomical object Kuna's Fist. Kuna's Horn was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4bae1778-86b7-4347-95d2-a339a6a4c018> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KunasHorn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KunasHorn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_KunasHorn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4bae1778-86b7-4347-95d2-a339a6a4c018> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KunasHorn> <http://telicent.io/ontology/primaryName> "Kuna's Horn" .
<https://starwars.com#planet_KunasHorn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#4bae1778-86b7-4347-95d2-a339a6a4c018> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuna's Horn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

