Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tibro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_Tibro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#e2e01f43-68ea-416f-8f52-de1e5a9a1122> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#e2e01f43-68ea-416f-8f52-de1e5a9a1122> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tibro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tibro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e2e01f43-68ea-416f-8f52-de1e5a9a1122> .
<https://starwars.com#planet_Tibro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tibro> <http://www.w3.org/2000/01/rdf-schema#comment> "Tibro was an astronomical object located in the Tibro system, a part of the Baronos sector in the Slice portion of the Colonies. The Human male Beyla Rus was born on Tibro in 24 BBY. Tibro was also the homeworld of the Human female Maxig Kress. " .
<https://starwars.com#planet_Tibro> <http://telicent.io/ontology/primaryName> "Tibro" .

