Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Zaric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_KorevVII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6a19f822-9b98-4c51-91a6-86eb6a311286> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korev VII"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorevVII> <http://telicent.io/ontology/primaryName> "Korev VII" .
<https://starwars.com#planet_KorevVII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_KorevVII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a19f822-9b98-4c51-91a6-86eb6a311286> .
<https://starwars.com#planet_KorevVII> <http://www.w3.org/2000/01/rdf-schema#comment> "Korev VII was an astronomical object that occupied the seventh orbital position in the Korev system, a part of the Zaric sector in the Slice portion of the Inner Rim. At some point between 0 ABY and 4 ABY, Moff Linis of the Galactic Empire issued from Korev VII a bounty on the Wookiee Cherioer. " .
<https://starwars.com#planet_KorevVII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zaric> .
<https://starwars.com#sector_Zaric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Zaric> <http://telicent.io/ontology/primaryName> "Zaric" .
<https://starwars.com#6a19f822-9b98-4c51-91a6-86eb6a311286> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

