Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Concordia> <http://telicent.io/ontology/primaryName> "Concordia" .
<https://starwars.com#planet_Concordia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#d42c1c82-d475-45cc-b6d7-60a6df66ad90> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Concordia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d42c1c82-d475-45cc-b6d7-60a6df66ad90> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Concordia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mandalore> .
<https://starwars.com#sector_Mandalore> <http://telicent.io/ontology/primaryName> "Mandalore" .
<https://starwars.com#planet_Concordia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Concordia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d42c1c82-d475-45cc-b6d7-60a6df66ad90> .
<https://starwars.com#sector_Mandalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

