Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3b9b6a36-4014-4d0a-8274-4dede16ed1ff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ast Kikorie"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_AstKikorie> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_AstKikorie> <http://www.w3.org/2000/01/rdf-schema#comment> "Ast Kikorie was a location in the Moddell sector of the Outer Rim Territories. Prior to the Battle of Endor in 4 ABY, Ast Kikorie was documented by Corporal Ractivelle of the Stardust unit as part of a Rebel Alliance report on the navigation of the Moddell sector in preparation for the Rebel Alliance's attack on the second Death Star. " .
<https://starwars.com#planet_AstKikorie> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AstKikorie> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#3b9b6a36-4014-4d0a-8274-4dede16ed1ff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_AstKikorie> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b9b6a36-4014-4d0a-8274-4dede16ed1ff> .
<https://starwars.com#planet_AstKikorie> <http://telicent.io/ontology/primaryName> "Ast Kikorie" .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

