Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dorin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#47d837c0-875d-451b-a2ea-65cee90ce120> .
<https://starwars.com#planet_Dorin> <http://www.w3.org/2000/01/rdf-schema#comment> "Dorin was a planet located in the galaxy's Expansion Region that was the homeworld of the Kel Dor species. Its Dorin gas and helium-rich environment meant that they were forced to rely on rebreathers to survive off-world, as oxygen was deadly to them. During the Clone Wars, Jedi General Anakin Skywalker and Commander Ahsoka Tano routed Separatist forces near Dorin. " .
<https://starwars.com#47d837c0-875d-451b-a2ea-65cee90ce120> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#47d837c0-875d-451b-a2ea-65cee90ce120> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dorin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Deadalis> <http://telicent.io/ontology/primaryName> "Deadalis" .
<https://starwars.com#sector_Deadalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Dorin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#planet_Dorin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Deadalis> .
<https://starwars.com#planet_Dorin> <http://telicent.io/ontology/primaryName> "Dorin" .
<https://starwars.com#sector_Deadalis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dorin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

