Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Nembus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kirtania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nembus> .
<https://starwars.com#sector_Nembus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kirtania> <http://www.w3.org/2000/01/rdf-schema#comment> "Kirtania was the homeworld of the spider-like, pacifist Araquia people. The Kubaz crime lord Schnil Hakoon settled on the planet and centered his operations in Kinkosa City. " .
<https://starwars.com#planet_Kirtania> <http://telicent.io/ontology/primaryName> "Kirtania" .
<https://starwars.com#37997765-3193-484a-aacf-f7dee0c402c6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Nembus> <http://telicent.io/ontology/primaryName> "Nembus" .
<https://starwars.com#planet_Kirtania> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kirtania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P4> .
<https://starwars.com#planet_Kirtania> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#37997765-3193-484a-aacf-f7dee0c402c6> .
<https://starwars.com#37997765-3193-484a-aacf-f7dee0c402c6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kirtania"^^<http://www.w3.org/2001/XMLSchema#string> .

