Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_E9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Rhigar> <http://telicent.io/ontology/primaryName> "Rhigar" .
<https://starwars.com#grid_E9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#64221968-6383-453e-ac71-d5e89b1e12ac> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#4e55d2bc-3fa5-4946-a379-77c41b3bf6ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rhigar> <http://www.w3.org/2000/01/rdf-schema#comment> "Rhigar, also known as Rhigal, was a terrestrial planet of the Chiss Ascendancy that was affiliated with the Clarr family. The Kilji war cruiser Whetstone, commanded by Generalirius Nakirre, arrived above Rhigar, bringing a supposed warning from Jixtus, who was traveling aboard the starship. Jixtus, claiming to be an information broker, requested to pass on a warning to the Clarr family Patriarch, Rivlex, while communicating with Captain Clarr'os'culry 'Roscu,' who instead asked that he provide her with the information. When Jixtus suggested that the danger to the Ascendancy was from within, asking that he be allowed to land on Rhigar, Roscu instead agreed to board the Whetstone in order to speak more securely. " .
<https://starwars.com#64221968-6383-453e-ac71-d5e89b1e12ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Rhigar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4e55d2bc-3fa5-4946-a379-77c41b3bf6ac> .
<https://starwars.com#grid_E9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#4e55d2bc-3fa5-4946-a379-77c41b3bf6ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rhigar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rhigar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E9> .
<https://starwars.com#planet_Rhigar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Rhigar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_E9> <http://telicent.io/ontology/primaryName> "E9" .
<https://starwars.com#64221968-6383-453e-ac71-d5e89b1e12ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "E9"^^<http://www.w3.org/2001/XMLSchema#string> .

