Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Qiilura> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet fell within the area conquered by the Yuuzhan Vong during their galactic invasion. " .
<https://starwars.com#planet_Qiilura> <http://telicent.io/ontology/primaryName> "Qiilura" .
<https://starwars.com#d8170333-db88-4b00-9807-9e574aee3b84> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d8170333-db88-4b00-9807-9e574aee3b84> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Qiilura"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Qiilura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#planet_Qiilura> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d8170333-db88-4b00-9807-9e574aee3b84> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Qiilura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .
<https://starwars.com#planet_Qiilura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .

