Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gigor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#a51f60f1-ecd5-43ca-9ddb-cae0cfbd1fa6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tynquay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a51f60f1-ecd5-43ca-9ddb-cae0cfbd1fa6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gigor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gigor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tynquay> .
<https://starwars.com#planet_Gigor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gigor> <http://www.w3.org/2000/01/rdf-schema#comment> "Gigor was a frigid planet located in the Tynquay sector of the galaxy's Outer Rim Territories that was the homeworld of the Gigoran species. During the age of the Galactic Empire, many Gigorans on their homeworld were rounded up by Zygerrian slavers and forced in labor. Among these individuals was Senna, a Gigoran who was forced to work as a slave in the spice mines of Kessel. " .
<https://starwars.com#planet_Gigor> <http://telicent.io/ontology/primaryName> "Gigor" .
<https://starwars.com#sector_Tynquay> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gigor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a51f60f1-ecd5-43ca-9ddb-cae0cfbd1fa6> .
<https://starwars.com#sector_Tynquay> <http://telicent.io/ontology/primaryName> "Tynquay" .

