Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Emmer> <http://telicent.io/ontology/primaryName> "Emmer" .
<https://starwars.com#planet_Emmer> <http://www.w3.org/2000/01/rdf-schema#comment> "Emmer, originally known as Umhul while it was part of Xim's empire, was a high-gravity planet in the Nilgaard sector that was covered in glowing grass and urban sprawls. The planet joined the Galactic Republic prior to 45 BBY. Emmerian walker vehicles inspired those built by Kuat Drive Yards, such as the AT-AT. " .
<https://starwars.com#planet_Emmer> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4a80c3a1-26ad-418b-8863-382af78ef21c> .
<https://starwars.com#sector_Nilgaard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Nilgaard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Emmer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#planet_Emmer> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4a80c3a1-26ad-418b-8863-382af78ef21c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Emmer"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Emmer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nilgaard> .
<https://starwars.com#4a80c3a1-26ad-418b-8863-382af78ef21c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Nilgaard> <http://telicent.io/ontology/primaryName> "Nilgaard" .

