Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4bd0cfe5-82f1-41ca-b556-f59086258d62> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mokk IX"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MokkIX> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_MokkIX> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#planet_MokkIX> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MokkIX> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4bd0cfe5-82f1-41ca-b556-f59086258d62> .
<https://starwars.com#planet_MokkIX> <http://www.w3.org/2000/01/rdf-schema#comment> "Mokk IX was a planet in the Inner Rim Territories. It was an Imperial labor camp covered in work settlements and wastelands. After stowing away in an Imperial shuttle, Sish Sadeet was left there to die, but rescued by Mirith Sinn when the New Republic liberated the world sometime before 11 ABY. " .
<https://starwars.com#planet_MokkIX> <http://telicent.io/ontology/primaryName> "Mokk IX" .
<https://starwars.com#4bd0cfe5-82f1-41ca-b556-f59086258d62> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

