Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorTrinivii> <http://telicent.io/ontology/primaryName> "Kor Trinivii" .
<https://starwars.com#planet_KorTrinivii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Trinivii was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Trinivii kajidic. " .
<https://starwars.com#planet_KorTrinivii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorTrinivii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f29920ee-0b93-4643-bd60-54bcc6e35b89> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#f29920ee-0b93-4643-bd60-54bcc6e35b89> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f29920ee-0b93-4643-bd60-54bcc6e35b89> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Trinivii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorTrinivii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorTrinivii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

