Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Knores> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#0f7cfc4f-58ba-4802-ae0d-15b141d3bb82> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Knores> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0f7cfc4f-58ba-4802-ae0d-15b141d3bb82> .
<https://starwars.com#0f7cfc4f-58ba-4802-ae0d-15b141d3bb82> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Knores"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Knores> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Knores> <http://www.w3.org/2000/01/rdf-schema#comment> "Knores was a Mid Rim world located in the Senex sector that was famous for its red seas. The world also featured a deep equatorial trench, appealing cities, and violent weather. By 3637 BBY, the seismologist Fez Burba hypothesized that a civilization once existing on Knores had been rendered extinct due to shifts in Knores' crust. Millennia later, the world was ruled by the aristocratic House Viholn. " .
<https://starwars.com#planet_Knores> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Knores> <http://telicent.io/ontology/primaryName> "Knores" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

