Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kail> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kail> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c83a7724-c691-4678-8311-a641b4bbabaf> .
<https://starwars.com#planet_Kail> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#c83a7724-c691-4678-8311-a641b4bbabaf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kail"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kail> <http://www.w3.org/2000/01/rdf-schema#comment> "Kail was a planet in the Corporate Sector. Torm Dadeferron, an associate of Han Solo, had family on Kail who controlled several large tracts of land known as the Kail Ranges. Torm's father and brother disappeared after a dispute with the Corporate Sector Authority over land-use rights and stock prices. " .
<https://starwars.com#c83a7724-c691-4678-8311-a641b4bbabaf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kail> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kail> <http://telicent.io/ontology/primaryName> "Kail" .

