Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Roche> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jeyell> <http://www.w3.org/2000/01/rdf-schema#comment> "Jeyell was a planet in the Mid Rim. During the Galactic Civil War between the Galactic Empire and the Alliance to Restore the Republic, the Alliance was forced to retreat from its failed Mid Rim Offensive, an operation by the Alliance and the Mid Rim revolutionaries to take control of the Mid Rim. The Alliance also retreated from Pothor, Durkteel, Ord Tiddell, Charros IV, and Trasse. Several revolutionaries evacuated with Alliance forces, although most remained on their planets to harass the Empire, who was expected to take quick control over the former Alliance territories. " .
<https://starwars.com#planet_Jeyell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Roche> .
<https://starwars.com#planet_Jeyell> <http://telicent.io/ontology/primaryName> "Jeyell" .
<https://starwars.com#planet_Jeyell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#sector_Roche> <http://telicent.io/ontology/primaryName> "Roche" .
<https://starwars.com#3b38d7cc-473c-4d29-847a-ad89e534162e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3b38d7cc-473c-4d29-847a-ad89e534162e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jeyell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Roche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Jeyell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jeyell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b38d7cc-473c-4d29-847a-ad89e534162e> .

