Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_R-Duba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e1e2608d-faa2-4513-98da-08744c91e120> .
<https://starwars.com#planet_R-Duba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T15> .
<https://starwars.com#planet_R-Duba> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_Quiberon> <http://telicent.io/ontology/primaryName> "Quiberon" .
<https://starwars.com#sector_Quiberon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_R-Duba> <http://telicent.io/ontology/primaryName> "R-Duba" .
<https://starwars.com#e1e2608d-faa2-4513-98da-08744c91e120> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R-Duba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e1e2608d-faa2-4513-98da-08744c91e120> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_R-Duba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quiberon> .
<https://starwars.com#planet_R-Duba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Quiberon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

