Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5cf169be-3928-4206-9055-492483ff0294> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Moorja"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Moorja> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#planet_Moorja> <http://telicent.io/ontology/primaryName> "Moorja" .
<https://starwars.com#planet_Moorja> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Moorja> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5cf169be-3928-4206-9055-492483ff0294> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Moorja> <http://www.w3.org/2000/01/rdf-schema#comment> "Moorja was a planet that was once home to Zare Leonis and his family. " .
<https://starwars.com#planet_Moorja> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5cf169be-3928-4206-9055-492483ff0294> .

