Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0f27e0ac-14f1-4312-a099-5ecd7f5dd660> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Talravin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0f27e0ac-14f1-4312-a099-5ecd7f5dd660> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Talravin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0f27e0ac-14f1-4312-a099-5ecd7f5dd660> .
<https://starwars.com#planet_Talravin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Talravin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Talravin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Talravin> <http://www.w3.org/2000/01/rdf-schema#comment> "Talravin was one of the planets of the Core Worlds. It was also Bastila, Helena Shan, and Bastila's father's home planet. " .
<https://starwars.com#planet_Talravin> <http://telicent.io/ontology/primaryName> "Talravin" .

