Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3ea43e5d-ba3b-450a-aa28-64feafeee706> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kiffu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kiffu> <http://www.w3.org/2000/01/rdf-schema#comment> "Kiffu was a planet located in the Inner Rim region of the galaxy. It was one of two home planets of the sentient Kiffar species, along with Kiffex. It was the homeworld of the Kiffar Jedi Master Quinlan Vos, who was active in the Jedi Order from at least 32 years before the Battle of Yavin until at least near the end of the Clone Wars. " .
<https://starwars.com#planet_Kiffu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kiffu> .
<https://starwars.com#planet_Kiffu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kiffu> <http://telicent.io/ontology/primaryName> "Kiffu" .
<https://starwars.com#3ea43e5d-ba3b-450a-aa28-64feafeee706> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kiffu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3ea43e5d-ba3b-450a-aa28-64feafeee706> .
<https://starwars.com#sector_Kiffu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kiffu> <http://telicent.io/ontology/primaryName> "Kiffu" .
<https://starwars.com#sector_Kiffu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Kiffu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .

