Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e67a14f4-bb85-439f-9e04-858540da0b7e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Drualkiin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drualkiin> <http://telicent.io/ontology/primaryName> "Drualkiin" .
<https://starwars.com#planet_Drualkiin> <http://www.w3.org/2000/01/rdf-schema#comment> "Drualkiin was an astronomical object situated on the Pabol Sleheyron hyperspace route in the Outer Rim Territories. " .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e67a14f4-bb85-439f-9e04-858540da0b7e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drualkiin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Drualkiin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#planet_Drualkiin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e67a14f4-bb85-439f-9e04-858540da0b7e> .
<https://starwars.com#planet_Drualkiin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .

