Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tirsa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#593dc891-e592-4751-880e-8dd2c61007f8> .
<https://starwars.com#planet_Tirsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Tirsa> <http://telicent.io/ontology/primaryName> "Tirsa" .
<https://starwars.com#593dc891-e592-4751-880e-8dd2c61007f8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tirsa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tirsa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Tirsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Tirsa> <http://www.w3.org/2000/01/rdf-schema#comment> "Tirsa was an industrial planet located within the Tirsa system of the Outer Rim Territories. It was home to the Tirsa Wargear armaments company that manufactured the Leviathan submersible carrier. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#593dc891-e592-4751-880e-8dd2c61007f8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

