Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7361597f-6c70-4177-a6ae-76f6c87175b3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Red Nebula"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_G21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_RedNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#3eb8f144-e529-452c-96cb-075e0fb1f0f0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_G21> <http://telicent.io/ontology/primaryName> "G21" .
<https://starwars.com#planet_RedNebula> <http://www.w3.org/2000/01/rdf-schema#comment> "The Red Nebula was a nebula located in Wild Space, positioned at the coordinates G-21 on the Standard Galactic Grid. " .
<https://starwars.com#grid_G21> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3eb8f144-e529-452c-96cb-075e0fb1f0f0> .
<https://starwars.com#planet_RedNebula> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7361597f-6c70-4177-a6ae-76f6c87175b3> .
<https://starwars.com#planet_RedNebula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7361597f-6c70-4177-a6ae-76f6c87175b3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RedNebula> <http://telicent.io/ontology/primaryName> "Red Nebula" .
<https://starwars.com#3eb8f144-e529-452c-96cb-075e0fb1f0f0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G21"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RedNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G21> .
<https://starwars.com#grid_G21> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

