Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Terman> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0e7e2942-2dae-46ce-8ada-2c14c2304940> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Terman"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Terman> <http://telicent.io/ontology/primaryName> "Terman" .
<https://starwars.com#planet_Terman> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Terman> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#0e7e2942-2dae-46ce-8ada-2c14c2304940> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Terman> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e7e2942-2dae-46ce-8ada-2c14c2304940> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Terman> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

