Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Nfolgai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Nfolgai> <http://telicent.io/ontology/primaryName> "Nfolgai" .
<https://starwars.com#b18cdb5e-f5dd-4acd-98bd-fe031e027f08> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nfolgai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nfolgai> <http://www.w3.org/2000/01/rdf-schema#comment> "Nfolgai was a world on the Descri Wris in Sith Space. Sorzus Syn encountered a Mrlssi slave on this world, burdened with stones and nearly unrecognizable under its soot-slicked feathers. " .
<https://starwars.com#b18cdb5e-f5dd-4acd-98bd-fe031e027f08> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nfolgai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b18cdb5e-f5dd-4acd-98bd-fe031e027f08> .
<https://starwars.com#planet_Nfolgai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nfolgai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .

