Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rynmar> <http://www.w3.org/2000/01/rdf-schema#comment> "Rynmar was a planet located in the Hapes Cluster and home of the rare creature known as a hover beak. " .
<https://starwars.com#planet_Rynmar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#90b127cb-1612-476a-9ba9-11b7e89f4b6d> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rynmar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rynmar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Rynmar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#90b127cb-1612-476a-9ba9-11b7e89f4b6d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Rynmar> <http://telicent.io/ontology/primaryName> "Rynmar" .
<https://starwars.com#90b127cb-1612-476a-9ba9-11b7e89f4b6d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rynmar"^^<http://www.w3.org/2001/XMLSchema#string> .

