Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#730a86b2-be82-43e6-bd74-7f7cbdc95b46> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Palanhi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Palanhi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Palanhi> <http://telicent.io/ontology/primaryName> "Palanhi" .
<https://starwars.com#planet_Palanhi> <http://www.w3.org/2000/01/rdf-schema#comment> "Palanhi was an astronomical object located in the galaxy's Colonies region, along the Shwuy Exchange hyperspace route. " .
<https://starwars.com#planet_Palanhi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#730a86b2-be82-43e6-bd74-7f7cbdc95b46> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Palanhi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#730a86b2-be82-43e6-bd74-7f7cbdc95b46> .
<https://starwars.com#planet_Palanhi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

