Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GalatorIII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4bb07c5b-22a1-4cdd-8fdd-a7ef8c68b5c9> .
<https://starwars.com#4bb07c5b-22a1-4cdd-8fdd-a7ef8c68b5c9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Galator III"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_GalatorIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#4bb07c5b-22a1-4cdd-8fdd-a7ef8c68b5c9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_GalatorIII> <http://telicent.io/ontology/primaryName> "Galator III" .
<https://starwars.com#planet_GalatorIII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

