Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a40eb146-8cf0-4d42-bedb-79a96a617104> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lianna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Lianna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a40eb146-8cf0-4d42-bedb-79a96a617104> .
<https://starwars.com#sector_AlliedTion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lianna> <http://telicent.io/ontology/primaryName> "Lianna" .
<https://starwars.com#a40eb146-8cf0-4d42-bedb-79a96a617104> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lianna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_AlliedTion> <http://telicent.io/ontology/primaryName> "Allied Tion" .
<https://starwars.com#planet_Lianna> <http://www.w3.org/2000/01/rdf-schema#comment> "Lianna was an astronomical object located in the Tion Cluster of the galaxy's Outer Rim Territories that was home to the powerful Santhe family. " .
<https://starwars.com#planet_Lianna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_AlliedTion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lianna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AlliedTion> .

