Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ef0fe6c8-732d-4fd8-ab81-e29d36e24991> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Noolian> <http://telicent.io/ontology/primaryName> "Noolian" .
<https://starwars.com#planet_Nooli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ef0fe6c8-732d-4fd8-ab81-e29d36e24991> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nooli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nooli> <http://www.w3.org/2000/01/rdf-schema#comment> "Nooli was a world located in the Nooli system in the Noolian sector in the Mid Rim. " .
<https://starwars.com#sector_Noolian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nooli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noolian> .
<https://starwars.com#planet_Nooli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef0fe6c8-732d-4fd8-ab81-e29d36e24991> .
<https://starwars.com#sector_Noolian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nooli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#planet_Nooli> <http://telicent.io/ontology/primaryName> "Nooli" .

