Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rannon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c2fa4acd-7042-4147-a6f7-eb3d4dff7284> .
<https://starwars.com#planet_Rannon> <http://www.w3.org/2000/01/rdf-schema#comment> "Following the Battle of Endor in 4 ABY, the Dark Jedi Danaan Kerr took up residence in Rannon's Valley of Ternaax. By 7 ABY, Kerr had sensed that the Galactic Emperor Palpatine had survived his death at Endor, which caused Kerr's dark side corruption to manifest, transforming the valley he resided in. Kerr began to terrorize Rannon's populace, with rumors concerning atrocities committed by the Dark Jedi spreading off-world. Eventually, a group of individuals investigated the Valley of Ternaax and encountered Kerr himself. " .
<https://starwars.com#sector_Instrop> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Instrop> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rannon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Instrop> .
<https://starwars.com#grid_T17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#bd3d35e2-7f37-42ec-b67f-e53370cacc8b> .
<https://starwars.com#c2fa4acd-7042-4147-a6f7-eb3d4dff7284> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rannon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c2fa4acd-7042-4147-a6f7-eb3d4dff7284> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#bd3d35e2-7f37-42ec-b67f-e53370cacc8b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Rannon> <http://telicent.io/ontology/primaryName> "Rannon" .
<https://starwars.com#grid_T17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Rannon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_T17> <http://telicent.io/ontology/primaryName> "T17" .
<https://starwars.com#planet_Rannon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T17> .
<https://starwars.com#bd3d35e2-7f37-42ec-b67f-e53370cacc8b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Instrop> <http://telicent.io/ontology/primaryName> "Instrop" .
<https://starwars.com#grid_T17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

