Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Relgim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vykos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vykos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Relgim> <http://telicent.io/ontology/primaryName> "Relgim" .
<https://starwars.com#planet_Vykos> <http://telicent.io/ontology/primaryName> "Vykos" .
<https://starwars.com#planet_Vykos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4544220d-89a0-47d4-95e3-dbbd6445c3d6> .
<https://starwars.com#planet_Vykos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Relgim> .
<https://starwars.com#4544220d-89a0-47d4-95e3-dbbd6445c3d6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#4544220d-89a0-47d4-95e3-dbbd6445c3d6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vykos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Relgim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vykos> <http://www.w3.org/2000/01/rdf-schema#comment> "Vykos was a planet located within the Vykos system of the Outer Rim Territories. It was a stopping point on the Relgim Run of the luxury liner Kuari Princess, a planet of fast-flowing rivers (such as the Tueinami) which attacted white-water rapid rafters and deep canyons (such as the Grand Aderian Range, a kilometer deep). " .

