Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HijoanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Hijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#planet_Hijo> <http://www.w3.org/2000/01/rdf-schema#comment> "Hijo was an astronomical object located in the Hijoian system, a part of the Expansion Region's Hijoian Space. By 12 ABY, it fell within the territory controlled by the New Republic. " .
<https://starwars.com#sector_HijoanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hijo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#efd6882f-f1a7-4224-8d36-6bc00fab5e9c> .
<https://starwars.com#planet_Hijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HijoanSpace> .
<https://starwars.com#efd6882f-f1a7-4224-8d36-6bc00fab5e9c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hijo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HijoanSpace> <http://telicent.io/ontology/primaryName> "Hijoan Space" .
<https://starwars.com#efd6882f-f1a7-4224-8d36-6bc00fab5e9c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hijo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hijo> <http://telicent.io/ontology/primaryName> "Hijo" .

