Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Herdessa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Herdessa> .
<https://starwars.com#sector_Herdessa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Herdessa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Herdessa> <http://telicent.io/ontology/primaryName> "Herdessa" .
<https://starwars.com#planet_Herdessa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#sector_Herdessa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Herdessa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#32789b00-f8d7-4817-93a2-ef0408fc4f36> .
<https://starwars.com#32789b00-f8d7-4817-93a2-ef0408fc4f36> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#32789b00-f8d7-4817-93a2-ef0408fc4f36> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Herdessa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Herdessa> <http://www.w3.org/2000/01/rdf-schema#comment> "Herdessa was an astronomical object located in the galaxy's Mid Rim that was situated along the Corellian Run at Q-16 on the Standard Galactic Grid. Herdessa was represented in the Galactic Senate and later the Imperial Senate by Senator Shea Sadashassa. Vryant, a soldier in the Imperial Army, served six years on Herdessa. " .
<https://starwars.com#sector_Herdessa> <http://telicent.io/ontology/primaryName> "Herdessa" .

