Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6f7eb331-a9a6-4111-b30e-589cc8698807> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hakassi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hakassi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6f7eb331-a9a6-4111-b30e-589cc8698807> .
<https://starwars.com#planet_Hakassi> <http://www.w3.org/2000/01/rdf-schema#comment> "Hakassi was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Hakassi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Hakassi> <http://telicent.io/ontology/primaryName> "Hakassi" .
<https://starwars.com#planet_Hakassi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hakassi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#6f7eb331-a9a6-4111-b30e-589cc8698807> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

