Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Byblos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7997ad41-0b85-40bd-9bec-4504ded791c6> .
<https://starwars.com#planet_Byblos> <http://telicent.io/ontology/primaryName> "Byblos" .
<https://starwars.com#planet_Byblos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#7997ad41-0b85-40bd-9bec-4504ded791c6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Byblos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Byblos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Byblos> <http://www.w3.org/2000/01/rdf-schema#comment> "Byblos was an astronomical object located in the galaxy's Colonies region that was situated along the Corellian Run. The former pirate Queen Maz Kanata marked it as the location of an outlaw garage on a map that she included in the book that became known as the Smuggler's Guide. Around 10 BBY, the crime lord Dryden Vos owned a storehouse on Byblos which contained items he had collected. " .
<https://starwars.com#planet_Byblos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#7997ad41-0b85-40bd-9bec-4504ded791c6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

