Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_AtapapI> <http://www.w3.org/2000/01/rdf-schema#comment> "Atapap I, part of the Atapap system in the Inner Rim was a planet colonized by Duros explorers during the early centuries of the Galactic Republic. It later became part of the Galactic Empire. " .
<https://starwars.com#55700aff-3dd0-40e7-973b-94cfa062af7d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atapap I"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_AtapapI> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_AtapapI> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#55700aff-3dd0-40e7-973b-94cfa062af7d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_AtapapI> <http://telicent.io/ontology/primaryName> "Atapap I" .
<https://starwars.com#planet_AtapapI> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#55700aff-3dd0-40e7-973b-94cfa062af7d> .
<https://starwars.com#planet_AtapapI> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .

