Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_Kalee> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalee was a planet located in Wild Space that was the homeworld of the Kaleesh species. Grievous, a male Kaleesh warlord, was from this world. " .
<https://starwars.com#planet_Kalee> <http://telicent.io/ontology/primaryName> "Kalee" .
<https://starwars.com#9ba72f26-4b5d-4c5b-8081-ee8e5026671d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kalee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ba72f26-4b5d-4c5b-8081-ee8e5026671d> .
<https://starwars.com#planet_Kalee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#9ba72f26-4b5d-4c5b-8081-ee8e5026671d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kalee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

