Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ubrikkia> <http://telicent.io/ontology/primaryName> "Ubrikkia" .
<https://starwars.com#planet_Ubrikkia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#planet_Ubrikkia> <http://www.w3.org/2000/01/rdf-schema#comment> "Ubrikkia was a Mid Rim celestial body that shared its name with several companies. By 3 ABY, the Ubrikkian enclave that was situated at Ubrikkia numbered among the major shipyards and drydocks of the Galactic Empire. " .
<https://starwars.com#bf8842eb-a1b9-4323-aec9-f2bfb165a1f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ubrikkia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ubrikkia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bf8842eb-a1b9-4323-aec9-f2bfb165a1f9> .
<https://starwars.com#bf8842eb-a1b9-4323-aec9-f2bfb165a1f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#planet_Ubrikkia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ubrikkia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .

