Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Holess> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bce1347e-d4b5-4251-ab69-754327640ac6> .
<https://starwars.com#planet_Holess> <http://telicent.io/ontology/primaryName> "Holess" .
<https://starwars.com#sector_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#planet_Holess> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Holess> <http://www.w3.org/2000/01/rdf-schema#comment> "Holess was a planet in the Galactic Federation of Free Alliances and the Holessian homeworld. It had more laws than any other world. Its capital city was the location of the Mount of Justice. Most of the population lived in towering cities built with the wealth derived from thousands of years of exporting the planet's rich local deposits of duranium. " .
<https://starwars.com#planet_Holess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Manda> .
<https://starwars.com#sector_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Holess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#bce1347e-d4b5-4251-ab69-754327640ac6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Holess"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#bce1347e-d4b5-4251-ab69-754327640ac6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

