Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0ef38ed1-d796-4acf-b00a-f6ace55ea615> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ryloth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Gaulus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ryloth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gaulus> .
<https://starwars.com#planet_Ryloth> <http://telicent.io/ontology/primaryName> "Ryloth" .
<https://starwars.com#0ef38ed1-d796-4acf-b00a-f6ace55ea615> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ryloth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ryloth> <http://www.w3.org/2000/01/rdf-schema#comment> "Dry, hot home planet of the Twi'leks, including Hera Syndulla and Jedi Master Aayla Secura." .
<https://starwars.com#planet_Ryloth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#planet_Ryloth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0ef38ed1-d796-4acf-b00a-f6ace55ea615> .
<https://starwars.com#sector_Gaulus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Gaulus> <http://telicent.io/ontology/primaryName> "Gaulus" .

