Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#b4a0ca76-88f9-47b3-bf86-1968348b7cb4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Simoom> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b4a0ca76-88f9-47b3-bf86-1968348b7cb4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Simoom"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Simoom> <http://telicent.io/ontology/primaryName> "Simoom" .
<https://starwars.com#planet_Simoom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Simoom> <http://www.w3.org/2000/01/rdf-schema#comment> "Simoom" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Simoom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Simoom> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4a0ca76-88f9-47b3-bf86-1968348b7cb4> .

