Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2079c400-f578-421a-9cbf-709d275e9f59> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Genian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2079c400-f578-421a-9cbf-709d275e9f59> .
<https://starwars.com#planet_Genian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trax> .
<https://starwars.com#planet_Genian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2079c400-f578-421a-9cbf-709d275e9f59> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Genian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Genian> <http://www.w3.org/2000/01/rdf-schema#comment> "Genian was a Mid Rim world. The planet remained neutral during the Clone Wars due to its vast corporate holdings, research labs, and secure banks. Many Senators, both Separatists and Republic alike, would store their money here, due to its neutrality. Its large, prosperous cities included Bruit, located near a rocky desert surrounded by mountain ranges. Fry Industries was headquartered on Genian. " .
<https://starwars.com#planet_Genian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#sector_Trax> <http://telicent.io/ontology/primaryName> "Trax" .
<https://starwars.com#sector_Trax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Genian> <http://telicent.io/ontology/primaryName> "Genian" .
<https://starwars.com#sector_Trax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

