Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Maldrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Maldrood> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TheWheel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TheWheel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f0daa67-85c3-4616-99c1-fb6f906091fb> .
<https://starwars.com#planet_TheWheel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#4f0daa67-85c3-4616-99c1-fb6f906091fb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Wheel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TheWheel> <http://www.w3.org/2000/01/rdf-schema#comment> "The Wheel, also known as space station BDT-0978, was a space station located in the Besh Gorgon system of the galaxy's Mid Rim. " .
<https://starwars.com#4f0daa67-85c3-4616-99c1-fb6f906091fb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TheWheel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maldrood> .
<https://starwars.com#sector_Maldrood> <http://telicent.io/ontology/primaryName> "Maldrood" .
<https://starwars.com#planet_TheWheel> <http://telicent.io/ontology/primaryName> "The Wheel" .

