Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gacerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baroli> .
<https://starwars.com#planet_Gacerian> <http://www.w3.org/2000/01/rdf-schema#comment> "Gacerian was the fourth planet in the Gacerian system. It was home to many Gacerite mines and was the homeworld of the Gacerite species. During Imperial reign, the Imperial governor of the planet, Ulbrek Gostech, was compassionate and kind, allowing the general populace to run the planet. Thus, the Gacerites were happy to abide by Imperial values and obey the laws dictated to them through their governor. " .
<https://starwars.com#c61a46fa-8f51-48bc-a96f-09a0ebef1d25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Baroli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Gacerian> <http://telicent.io/ontology/primaryName> "Gacerian" .
<https://starwars.com#planet_Gacerian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Baroli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gacerian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c61a46fa-8f51-48bc-a96f-09a0ebef1d25> .
<https://starwars.com#sector_Baroli> <http://telicent.io/ontology/primaryName> "Baroli" .
<https://starwars.com#c61a46fa-8f51-48bc-a96f-09a0ebef1d25> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gacerian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gacerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .

