Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Heptalia> <http://telicent.io/ontology/primaryName> "Heptalia" .
<https://starwars.com#04153c46-74f1-4ea7-90b9-e8611b8c3354> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Heptalia> <http://www.w3.org/2000/01/rdf-schema#comment> "Heptalia was a planet located in the Heptalia system, a part of the Trailing Sectors portion of the Inner Rim. Heptalia's artisans produced furniture coverings and embroidered rugs that were considered to be exquisite and lent renown to the planet. " .
<https://starwars.com#planet_Heptalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Heptalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#04153c46-74f1-4ea7-90b9-e8611b8c3354> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Heptalia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Heptalia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#04153c46-74f1-4ea7-90b9-e8611b8c3354> .
<https://starwars.com#planet_Heptalia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

