Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kriz> <http://telicent.io/ontology/primaryName> "Kriz" .
<https://starwars.com#sector_Kriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4c6680b0-32ab-4268-b102-96066d3e47c7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_BerrolsDonn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K19> .
<https://starwars.com#planet_BerrolsDonn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4c6680b0-32ab-4268-b102-96066d3e47c7> .
<https://starwars.com#planet_BerrolsDonn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#4c6680b0-32ab-4268-b102-96066d3e47c7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Berrol's Donn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BerrolsDonn> <http://telicent.io/ontology/primaryName> "Berrol's Donn" .
<https://starwars.com#planet_BerrolsDonn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kriz> .
<https://starwars.com#planet_BerrolsDonn> <http://www.w3.org/2000/01/rdf-schema#comment> "Berrol's Donn was an astronomical object in the Outer Rim Territories, situated on the Corellian Trade Spine. " .

