Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rodia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .
<https://starwars.com#planet_Rodia> <http://telicent.io/ontology/primaryName> "Rodia" .
<https://starwars.com#d4124309-1814-4eff-a738-d78c90e1edee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rodia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d4124309-1814-4eff-a738-d78c90e1edee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rodia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Rodia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#planet_Rodia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d4124309-1814-4eff-a738-d78c90e1edee> .
<https://starwars.com#planet_Rodia> <http://www.w3.org/2000/01/rdf-schema#comment> "Home planet of the Rodians, including Greedo. A remote swampy, jungle planet, it was represented by Onaconda Farr in the Galactic Senate during the Clone Wars." .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

