Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ninn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f82364c4-ef4e-4459-ac09-d8c187e35a47> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ninn> <http://telicent.io/ontology/primaryName> "Ninn" .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Ninn> <http://www.w3.org/2000/01/rdf-schema#comment> "Ninn was a small planet located in the Ninn system of the Outer Rim Territories. The world was despoiled and depopulated in an ancient conflict, but was later resettled by a group that became known as the Priests of Ninn. Ninn came to be part of the Corporate Sector following that region's expansion, and so fell under the control of the Corporate Sector Authority. " .
<https://starwars.com#f82364c4-ef4e-4459-ac09-d8c187e35a47> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ninn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ninn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ninn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f82364c4-ef4e-4459-ac09-d8c187e35a47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ninn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .

