Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gorsh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#15db1039-6afa-4195-9a44-14e5a19912e9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Gorsh> <http://www.w3.org/2000/01/rdf-schema#comment> "Gorsh was the third planet of the Gorsh system, located in Wild Space 100,000 light years away from the Core. The watery planet had a population of 100,000. " .
<https://starwars.com#15db1039-6afa-4195-9a44-14e5a19912e9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O3> <http://telicent.io/ontology/primaryName> "O3" .
<https://starwars.com#planet_Gorsh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_O3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#6e2eaaa6-3534-4854-9df3-fce5a9ecddec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gorsh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O3> .
<https://starwars.com#grid_O3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_O3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#15db1039-6afa-4195-9a44-14e5a19912e9> .
<https://starwars.com#planet_Gorsh> <http://telicent.io/ontology/primaryName> "Gorsh" .
<https://starwars.com#planet_Gorsh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6e2eaaa6-3534-4854-9df3-fce5a9ecddec> .
<https://starwars.com#6e2eaaa6-3534-4854-9df3-fce5a9ecddec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gorsh"^^<http://www.w3.org/2001/XMLSchema#string> .

