Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Iktotchon> <http://www.w3.org/2000/01/rdf-schema#comment> "Iktotchon was a planet located in the Expansion Region of the galaxy. It had a moon, Iktotch, which was the homeworld of Iktotchi Jedi Master Saesee Tiin. " .
<https://starwars.com#planet_Iktotchon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iktotchon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f5c4fb33-ce8c-481e-8771-811911858ac4> .
<https://starwars.com#f5c4fb33-ce8c-481e-8771-811911858ac4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iktotchon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f5c4fb33-ce8c-481e-8771-811911858ac4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Narvath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Iktotchon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#sector_Narvath> <http://telicent.io/ontology/primaryName> "Narvath" .
<https://starwars.com#planet_Iktotchon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Narvath> .
<https://starwars.com#planet_Iktotchon> <http://telicent.io/ontology/primaryName> "Iktotchon" .
<https://starwars.com#sector_Narvath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

