Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cormit> <http://telicent.io/ontology/primaryName> "Cormit" .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cormit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Cormit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#ac6a6cba-a6dd-45cc-99aa-e557c41feb8d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cormit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Cormit> <http://www.w3.org/2000/01/rdf-schema#comment> "Cormit was an astronomical object of the Chiss Ascendancy in the Unknown Regions. A fleet depot of the Ascendancy's Clarr family was situated at Cormit, anchored by the light cruiser Orisson. " .
<https://starwars.com#ac6a6cba-a6dd-45cc-99aa-e557c41feb8d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cormit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cormit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac6a6cba-a6dd-45cc-99aa-e557c41feb8d> .

