Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mamendin> <http://telicent.io/ontology/primaryName> "Mamendin" .
<https://starwars.com#planet_Mamendin> <http://www.w3.org/2000/01/rdf-schema#comment> "Mamendin was a planet located in the Farrfin sector of the Core Worlds. It was the homeworld of a sentient species that was humanoid in form. The criminal gang known as the Slams was composed of several members of this species, such as Roper Slam and Valadon. " .
<https://starwars.com#planet_Mamendin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#61c1c1a6-eea1-4a9f-b412-63e2fc8794f7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mamendin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mamendin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Mamendin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Mamendin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#61c1c1a6-eea1-4a9f-b412-63e2fc8794f7> .
<https://starwars.com#61c1c1a6-eea1-4a9f-b412-63e2fc8794f7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

