Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_J5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#09071278-e516-4ab4-9c13-00509a55f050> .
<https://starwars.com#planet_Alashan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a0362303-6306-41be-8f0c-a66a00ab16b0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alashan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Alashan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Alashan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#planet_Alashan> <http://www.w3.org/2000/01/rdf-schema#comment> "Alashan was a planet located on the fringe of the Outer Rim Territories; an area of the galaxy known as Wild Space. " .
<https://starwars.com#09071278-e516-4ab4-9c13-00509a55f050> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_J5> <http://telicent.io/ontology/primaryName> "J5" .
<https://starwars.com#a0362303-6306-41be-8f0c-a66a00ab16b0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Alashan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0362303-6306-41be-8f0c-a66a00ab16b0> .
<https://starwars.com#planet_Alashan> <http://telicent.io/ontology/primaryName> "Alashan" .
<https://starwars.com#09071278-e516-4ab4-9c13-00509a55f050> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J5"^^<http://www.w3.org/2001/XMLSchema#string> .

