Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Baummu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#sector_Shadola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Baummu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Shadola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Baummu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Shadola> .
<https://starwars.com#planet_Baummu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#96c8bcea-41de-40dd-8641-5e2a71c59b50> .
<https://starwars.com#planet_Baummu> <http://www.w3.org/2000/01/rdf-schema#comment> "Baummu was a planet located in the Shadola sector of the Outer Rim. It was violently attacked during the Galactic Civil War by Imperial forces led by Captain Briera. Briera was later known as the 'Butcher of Baummu'. " .
<https://starwars.com#96c8bcea-41de-40dd-8641-5e2a71c59b50> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Baummu> <http://telicent.io/ontology/primaryName> "Baummu" .
<https://starwars.com#96c8bcea-41de-40dd-8641-5e2a71c59b50> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Baummu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Shadola> <http://telicent.io/ontology/primaryName> "Shadola" .

