Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jubilar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Jubilar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jubilar> .
<https://starwars.com#sector_Jubilar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e7dc5db0-b2a5-4830-86e8-7453c396b2f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jubilar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e7dc5db0-b2a5-4830-86e8-7453c396b2f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jubilar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_Jubilar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e7dc5db0-b2a5-4830-86e8-7453c396b2f6> .
<https://starwars.com#sector_Jubilar> <http://telicent.io/ontology/primaryName> "Jubilar" .
<https://starwars.com#planet_Jubilar> <http://telicent.io/ontology/primaryName> "Jubilar" .
<https://starwars.com#planet_Jubilar> <http://www.w3.org/2000/01/rdf-schema#comment> "Jubilar was a location that was used as a prison by the Confederacy of Independent Systems. During the Clone Wars, it was one of several locations where a majority of Separatist prisoners were sent. Jubilar remained a prison after the rise of the New Republic, which incarcerated Borbin Todds there to serve a twenty-five-year sentence for harbouring a wanted fugitive. " .
<https://starwars.com#planet_Jubilar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

