Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sagar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Sagar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2e6fc100-0715-4a2d-8f9e-6a2915ea8e41> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sagar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sagar> <http://telicent.io/ontology/primaryName> "Sagar" .
<https://starwars.com#planet_Sagar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e6fc100-0715-4a2d-8f9e-6a2915ea8e41> .
<https://starwars.com#planet_Sagar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#2e6fc100-0715-4a2d-8f9e-6a2915ea8e41> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sagar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .

