Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kanz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lorrd> <http://www.w3.org/2000/01/rdf-schema#comment> "Lorrd was an astronomical object located in the galaxy's Outer Rim Territories. During the early rebellion against the Galactic Empire, Freemarch had operations on Lorrd. " .
<https://starwars.com#planet_Lorrd> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d464c25b-ed78-4014-a805-c61fbc83e8b6> .
<https://starwars.com#d464c25b-ed78-4014-a805-c61fbc83e8b6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lorrd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kanz> <http://telicent.io/ontology/primaryName> "Kanz" .
<https://starwars.com#planet_Lorrd> <http://telicent.io/ontology/primaryName> "Lorrd" .
<https://starwars.com#sector_Kanz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#d464c25b-ed78-4014-a805-c61fbc83e8b6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lorrd"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lorrd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kanz> .
<https://starwars.com#planet_Lorrd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .

