Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d2c53dd3-6d4a-4cd0-bd11-39444eda6749> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Virujansi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Virujansi> <http://www.w3.org/2000/01/rdf-schema#comment> "Virujansi was a planet in the galaxy. It was ruled by the Virujansi council, supported by the Virujansi Rarified Air Cavalry until the Galactic Empire arrived and replaced the council's rule with an Imperial governor. The members of the Air Cavalry were given the opportunity to join the Imperial Navy, but some pilots like Antoc Merrick and Garven Dreis, instead chose to join the Alliance to Restore the Republic during the Galactic Civil War. " .
<https://starwars.com#planet_Virujansi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Virujansi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d2c53dd3-6d4a-4cd0-bd11-39444eda6749> .
<https://starwars.com#d2c53dd3-6d4a-4cd0-bd11-39444eda6749> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Virujansi> <http://telicent.io/ontology/primaryName> "Virujansi" .
<https://starwars.com#planet_Virujansi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Virujansi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .

