Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Molavar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a590310-0c48-4702-bcfe-42f64ac94579> .
<https://starwars.com#planet_Molavar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .
<https://starwars.com#planet_Molavar> <http://telicent.io/ontology/primaryName> "Molavar" .
<https://starwars.com#planet_Molavar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#planet_Molavar> <http://www.w3.org/2000/01/rdf-schema#comment> "Molavar was an astronomical object located in the galaxy's Outer Rim Territories, on the junction of the Triellus Trade Route and the Manda Merchant Run, just a short jump south of Scarif. The hyperlanes that linked Molavar to the planet Tatooine were controlled by the crime lord Jabba Desilijic Tiure. " .
<https://starwars.com#3a590310-0c48-4702-bcfe-42f64ac94579> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3a590310-0c48-4702-bcfe-42f64ac94579> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Molavar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Molavar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

