Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#58903df5-b9e9-4ffa-8c15-79558767710f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Alui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Enarc> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#58903df5-b9e9-4ffa-8c15-79558767710f> .
<https://starwars.com#planet_Enarc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#planet_Enarc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Enarc> <http://www.w3.org/2000/01/rdf-schema#comment> "Enarc was an astronomical object located in the galaxy's Mid Rim and Trailing Sectors. Situated near the planet Naboo, Enarc was located in square O-17 of the Standard Galactic Grid. " .
<https://starwars.com#planet_Enarc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Alui> .
<https://starwars.com#sector_Alui> <http://telicent.io/ontology/primaryName> "Alui" .
<https://starwars.com#planet_Enarc> <http://telicent.io/ontology/primaryName> "Enarc" .
<https://starwars.com#58903df5-b9e9-4ffa-8c15-79558767710f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Enarc"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Alui> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

