Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1f0614cb-4e00-4660-93e1-de3d0f461eb5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Maridun> <http://www.w3.org/2000/01/rdf-schema#comment> "Grassy planet remaining undiscovered until the Clone Wars." .
<https://starwars.com#1f0614cb-4e00-4660-93e1-de3d0f461eb5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Maridun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Maridun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1f0614cb-4e00-4660-93e1-de3d0f461eb5> .
<https://starwars.com#sector_Rolion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Maridun> <http://telicent.io/ontology/primaryName> "Maridun" .
<https://starwars.com#sector_Rolion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Maridun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rolion> .
<https://starwars.com#planet_Maridun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#sector_Rolion> <http://telicent.io/ontology/primaryName> "Rolion" .
<https://starwars.com#planet_Maridun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

