Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#efe5f540-693f-465d-8261-adacbb85a3e4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jagomir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Esstran> <http://telicent.io/ontology/primaryName> "Esstran" .
<https://starwars.com#planet_Jagomir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#efe5f540-693f-465d-8261-adacbb85a3e4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Esstran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Jagomir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Esstran> .
<https://starwars.com#planet_Jagomir> <http://telicent.io/ontology/primaryName> "Jagomir" .
<https://starwars.com#planet_Jagomir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jagomir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#efe5f540-693f-465d-8261-adacbb85a3e4> .
<https://starwars.com#sector_Esstran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jagomir> <http://www.w3.org/2000/01/rdf-schema#comment> "The surface of the planet contained thirty continents and a number of seas. Nearly seventy-five percent of the planet's surface was swampland. " .

