Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cerea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Semagi> .
<https://starwars.com#e382961b-4aae-42c7-8559-8a712d839a46> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_I16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e382961b-4aae-42c7-8559-8a712d839a46> .
<https://starwars.com#planet_Cerea> <http://telicent.io/ontology/primaryName> "Cerea" .
<https://starwars.com#sector_Semagi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cerea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5dc2915-7c40-4350-87f0-dc65778470e3> .
<https://starwars.com#planet_Cerea> <http://www.w3.org/2000/01/rdf-schema#comment> "The native Cereans were very protective of their homeworld's ecology, and thus only allowed off-world visitors and immigrants to enter and reside city-sized structures called Outsider Citadels. One such structure was Asphodar 3. " .
<https://starwars.com#grid_I16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Cerea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e382961b-4aae-42c7-8559-8a712d839a46> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Semagi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#b5dc2915-7c40-4350-87f0-dc65778470e3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Semagi> <http://telicent.io/ontology/primaryName> "Semagi" .
<https://starwars.com#b5dc2915-7c40-4350-87f0-dc65778470e3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cerea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Cerea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I16> .
<https://starwars.com#grid_I16> <http://telicent.io/ontology/primaryName> "I16" .

