Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Kayri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b883f92-9406-4242-bf67-81bd98f065d8> .
<https://starwars.com#grid_I15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Kayri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a5572ea4-ba12-4816-a864-0cf27be3f7bc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kayri> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#3b883f92-9406-4242-bf67-81bd98f065d8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kayri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a5572ea4-ba12-4816-a864-0cf27be3f7bc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#3b883f92-9406-4242-bf67-81bd98f065d8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_I15> <http://telicent.io/ontology/primaryName> "I15" .
<https://starwars.com#planet_Kayri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I15> .
<https://starwars.com#planet_Kayri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kayri> <http://telicent.io/ontology/primaryName> "Kayri" .
<https://starwars.com#grid_I15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_I15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#a5572ea4-ba12-4816-a864-0cf27be3f7bc> .

