Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#51e484b7-5a2b-4c89-89ef-21cccde653ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bonadan> <http://telicent.io/ontology/primaryName> "Bonadan" .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#51e484b7-5a2b-4c89-89ef-21cccde653ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bonadan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bonadan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Bonadan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#51e484b7-5a2b-4c89-89ef-21cccde653ab> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bonadan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Bonadan> <http://www.w3.org/2000/01/rdf-schema#comment> "Bonadan was a planet in the Corporate Sector of the galaxy's Outer Rim Territories, and the starting point of the Hydian Way. An embassy for Bonadan was located on the planet Coruscant. " .
<https://starwars.com#planet_Bonadan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

