Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e6a3eb69-1243-4af8-9ad8-7d3abe3f7c65> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Geris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e6a3eb69-1243-4af8-9ad8-7d3abe3f7c65> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Geris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TransVulta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TransVulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Geris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TransVulta> .
<https://starwars.com#sector_TransVulta> <http://telicent.io/ontology/primaryName> "Trans'Vulta" .
<https://starwars.com#planet_Geris> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Geris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6a3eb69-1243-4af8-9ad8-7d3abe3f7c65> .
<https://starwars.com#planet_Geris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#planet_Geris> <http://telicent.io/ontology/primaryName> "Geris" .

