Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#fda7bfc6-fa94-48db-aa51-edfe0d61ee31> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Deltooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#fda7bfc6-fa94-48db-aa51-edfe0d61ee31> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Deltooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Deltooine> <http://telicent.io/ontology/primaryName> "Deltooine" .
<https://starwars.com#planet_Deltooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Deltooine was a world in the Corporate Sector. It was home to a Corporate Sector Authority military base used to monitor Farana and Wild Space. It was part of the Tertiary Solenbaran hyperlane. " .
<https://starwars.com#planet_Deltooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Deltooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Deltooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fda7bfc6-fa94-48db-aa51-edfe0d61ee31> .

