Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shulxi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Shulxi> <http://telicent.io/ontology/primaryName> "Shulxi" .
<https://starwars.com#planet_Shulxi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#a577ec3f-d12f-46f4-baa8-d005e4a475cc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shulxi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a577ec3f-d12f-46f4-baa8-d005e4a475cc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shulxi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a577ec3f-d12f-46f4-baa8-d005e4a475cc> .
<https://starwars.com#planet_Shulxi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shulxi> <http://www.w3.org/2000/01/rdf-schema#comment> "Shulxi was a Galactic Core world known for its beachside resorts. " .

