Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fwillsving> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#d72b3ba7-845c-4633-928d-cbc5d120bec2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fwillsving> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Fwillsving> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fwillsving> <http://telicent.io/ontology/primaryName> "Fwillsving" .
<https://starwars.com#d72b3ba7-845c-4633-928d-cbc5d120bec2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fwillsving"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fwillsving> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d72b3ba7-845c-4633-928d-cbc5d120bec2> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Fwillsving> <http://www.w3.org/2000/01/rdf-schema#comment> "Fwillsving was a planet near Kessel and Honoghr. It was sometimes used by smugglers as a repair depot and a hideaway from Imperial patrol starships while smuggling spice on the Kessel Run. " .

