Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ranroon> <http://www.w3.org/2000/01/rdf-schema#comment> "Ranroon was a planet located within the Mortex sector of the Outer Rim Territories. It was particularly known for its legendary Queen Indrexu. " .
<https://starwars.com#planet_Ranroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4c560c05-f54a-4328-8102-28486c4c54c6> .
<https://starwars.com#planet_Ranroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Ranroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mortex> .
<https://starwars.com#4c560c05-f54a-4328-8102-28486c4c54c6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ranroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#4c560c05-f54a-4328-8102-28486c4c54c6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mortex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ranroon> <http://telicent.io/ontology/primaryName> "Ranroon" .
<https://starwars.com#planet_Ranroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Mortex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mortex> <http://telicent.io/ontology/primaryName> "Mortex" .

