Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Metalorn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Talcene> .
<https://starwars.com#sector_Talcene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Metalorn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#sector_Talcene> <http://telicent.io/ontology/primaryName> "Talcene" .
<https://starwars.com#e413db97-e629-48c8-acd1-dbba77a44250> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Metalorn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Talcene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Metalorn> <http://www.w3.org/2000/01/rdf-schema#comment> "Metalorn was an industrial planet located in the galaxy's Mid Rim. A vital Techno Union world, it was aligned with the Confederacy of Independent Systems during the Clone Wars. Its Skakoan population was enslaved by the Galactic Empire for their Separatists sympathies, causing some to join the Alliance to Restore the Republic. Metalorn's production capacity supported the Imperial Military during the Galactic Civil War, causing the Rebel Alliance to consider it a potential target. The Skakoan Wat Tambor began his career in techology on Metalorn, going on to become Foreman of the Techno Union. " .
<https://starwars.com#planet_Metalorn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e413db97-e629-48c8-acd1-dbba77a44250> .
<https://starwars.com#planet_Metalorn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Metalorn> <http://telicent.io/ontology/primaryName> "Metalorn" .
<https://starwars.com#e413db97-e629-48c8-acd1-dbba77a44250> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

