Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c2085f13-c077-401a-85b0-ee47ca13ad47> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Besadii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorBesadii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_KorBesadii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Besadii was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Besadii kajidic. Ancient palaces of the Besadii kajidic sprawled across its surface. " .
<https://starwars.com#planet_KorBesadii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c2085f13-c077-401a-85b0-ee47ca13ad47> .
<https://starwars.com#planet_KorBesadii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c2085f13-c077-401a-85b0-ee47ca13ad47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorBesadii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorBesadii> <http://telicent.io/ontology/primaryName> "Kor Besadii" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

