Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tamban> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tamban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#a61bc573-7f7b-4350-9bc5-f3f99adad401> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a61bc573-7f7b-4350-9bc5-f3f99adad401> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tamban"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tamban> <http://telicent.io/ontology/primaryName> "Tamban" .
<https://starwars.com#planet_Tamban> <http://www.w3.org/2000/01/rdf-schema#comment> "Tamban was an inhabited planet in Core Worlds from which the Koornacht Cluster could be observed through a telescope. It was ruled by Emperor Preedu III before Palpatine rose to power. " .
<https://starwars.com#planet_Tamban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Tamban> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a61bc573-7f7b-4350-9bc5-f3f99adad401> .

