Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_KorUtoradii> <http://telicent.io/ontology/primaryName> "Kor Utoradii" .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorUtoradii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#22d675e1-37ba-4684-81e7-c4b104c77065> .
<https://starwars.com#22d675e1-37ba-4684-81e7-c4b104c77065> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Utoradii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#22d675e1-37ba-4684-81e7-c4b104c77065> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorUtoradii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Utoradii was a planet located in the Bootana Hutta region of Hutt Space. It was a throneworld of the Utoradii kajidic. " .
<https://starwars.com#planet_KorUtoradii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorUtoradii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorUtoradii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .

