Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_DAstan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#fe246b59-bc53-4e1c-82d9-e1e624691ed7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Serenno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAstan> .
<https://starwars.com#sector_DAstan> <http://telicent.io/ontology/primaryName> "D'Astan" .
<https://starwars.com#fe246b59-bc53-4e1c-82d9-e1e624691ed7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Serenno"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Serenno> <http://telicent.io/ontology/primaryName> "Serenno" .
<https://starwars.com#planet_Serenno> <http://www.w3.org/2000/01/rdf-schema#comment> "A planet in the Outer Rim Territories. Homeworld of Count Dooku." .
<https://starwars.com#planet_Serenno> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fe246b59-bc53-4e1c-82d9-e1e624691ed7> .
<https://starwars.com#planet_Serenno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_DAstan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Serenno> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

