Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Scardia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#sector_Inra-su-Mar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Scardia> <http://telicent.io/ontology/primaryName> "Scardia" .
<https://starwars.com#bc3d2f62-aff3-47ae-80a5-ab4ece64b0d6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#bc3d2f62-aff3-47ae-80a5-ab4ece64b0d6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Scardia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Scardia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Inra-su-Mar> .
<https://starwars.com#sector_Inra-su-Mar> <http://telicent.io/ontology/primaryName> "Inra-su-Mar" .
<https://starwars.com#planet_Scardia> <http://www.w3.org/2000/01/rdf-schema#comment> "Scardia Station, also Space Station Scardia, was a cubical space station in the Null Zone. " .
<https://starwars.com#planet_Scardia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Scardia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bc3d2f62-aff3-47ae-80a5-ab4ece64b0d6> .
<https://starwars.com#sector_Inra-su-Mar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

