Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Qina> <http://telicent.io/ontology/primaryName> "Qina" .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Qina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#97b22b26-db41-4004-b4f7-44d11bef7166> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Qina"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#97b22b26-db41-4004-b4f7-44d11bef7166> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Qina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Qina> <http://www.w3.org/2000/01/rdf-schema#comment> "Qina was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was linked by hyperspace routes to the celestial bodies Kuna's Tooth, Thonner, and Trindello. Qina was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Qina> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#97b22b26-db41-4004-b4f7-44d11bef7166> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_Qina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .

