Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Janara> <http://telicent.io/ontology/primaryName> "Janara" .
<https://starwars.com#cadaf555-fa05-45da-bf29-8f7050a5a1d6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Janara> <http://www.w3.org/2000/01/rdf-schema#comment> "Janara can refer to: " .
<https://starwars.com#planet_Janara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#387b9663-7a47-4cf8-83a9-dd2b0789f108> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#cadaf555-fa05-45da-bf29-8f7050a5a1d6> .
<https://starwars.com#grid_L14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#387b9663-7a47-4cf8-83a9-dd2b0789f108> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Janara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Janara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#cadaf555-fa05-45da-bf29-8f7050a5a1d6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Janara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#387b9663-7a47-4cf8-83a9-dd2b0789f108> .
<https://starwars.com#planet_Janara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#grid_L14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_L14> <http://telicent.io/ontology/primaryName> "L14" .

