Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Equanus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#planet_Equanus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#d167a209-3a2f-4ef1-8b0e-fa0db4a27dd2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Equanus> <http://www.w3.org/2000/01/rdf-schema#comment> "Equanus was a planet in the Outer Rim Territories. It was one of five planets in the Nharl system. " .
<https://starwars.com#d167a209-3a2f-4ef1-8b0e-fa0db4a27dd2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Equanus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Equanus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Veragi> .
<https://starwars.com#planet_Equanus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d167a209-3a2f-4ef1-8b0e-fa0db4a27dd2> .
<https://starwars.com#planet_Equanus> <http://telicent.io/ontology/primaryName> "Equanus" .

