Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Neshtab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Neshtab> <http://telicent.io/ontology/primaryName> "Neshtab" .
<https://starwars.com#planet_Neshtab> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4567f91a-677b-4476-97f3-90d24dd2e7d3> .
<https://starwars.com#planet_Neshtab> <http://www.w3.org/2000/01/rdf-schema#comment> "Neshtab was a planet of snowy ice plains located in the Inner Rim region of the galaxy. " .
<https://starwars.com#planet_Neshtab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4567f91a-677b-4476-97f3-90d24dd2e7d3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#4567f91a-677b-4476-97f3-90d24dd2e7d3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Neshtab"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Neshtab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .

