Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Helska> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#796d5190-4cf1-4dd8-bab9-9afa11c80f75> .
<https://starwars.com#planet_Helska> <http://www.w3.org/2000/01/rdf-schema#comment> "Helska was an astronomical object located in the Outer Rim Territories and New Territories regions. It was situated in grid square L-2 on the Standard Galactic Grid. " .
<https://starwars.com#796d5190-4cf1-4dd8-bab9-9afa11c80f75> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#796d5190-4cf1-4dd8-bab9-9afa11c80f75> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Helska"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dalonbian> <http://telicent.io/ontology/primaryName> "Dalonbian" .
<https://starwars.com#planet_Helska> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Helska> <http://telicent.io/ontology/primaryName> "Helska" .
<https://starwars.com#sector_Dalonbian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Helska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalonbian> .
<https://starwars.com#sector_Dalonbian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Helska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L2> .

