Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Velabri> <http://www.w3.org/2000/01/rdf-schema#comment> "Velabri was a planet located within the Velabri system of the Outer Rim Territories. It was conquered by the Galactic Empire. " .
<https://starwars.com#planet_Velabri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#6d9a3711-8ee8-477b-aa54-f9a55d6cf9d4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Velabri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Velabri> <http://telicent.io/ontology/primaryName> "Velabri" .
<https://starwars.com#6d9a3711-8ee8-477b-aa54-f9a55d6cf9d4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Velabri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Velabri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S18> .
<https://starwars.com#planet_Velabri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6d9a3711-8ee8-477b-aa54-f9a55d6cf9d4> .

