Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#54eb7575-3b0c-477c-85f0-838c2e0b8ff6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Atron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#54eb7575-3b0c-477c-85f0-838c2e0b8ff6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Atron> <http://telicent.io/ontology/primaryName> "Atron" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Atron> <http://www.w3.org/2000/01/rdf-schema#comment> "Atron was a planet located within the Atron system of the Mid Rim's Senex sector. " .
<https://starwars.com#planet_Atron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Atron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54eb7575-3b0c-477c-85f0-838c2e0b8ff6> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Atron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

