Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bruanii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d327f6c0-679d-47fc-ab4a-740457280b92> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mugaar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mugaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Mugaar was an astronomical object located in the Javin Sector of the Mid Rim. " .
<https://starwars.com#planet_Mugaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mugaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bruanii> .
<https://starwars.com#d327f6c0-679d-47fc-ab4a-740457280b92> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Bruanii> <http://telicent.io/ontology/primaryName> "Bruanii" .
<https://starwars.com#planet_Mugaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Mugaar> <http://telicent.io/ontology/primaryName> "Mugaar" .
<https://starwars.com#sector_Bruanii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Mugaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d327f6c0-679d-47fc-ab4a-740457280b92> .

