Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_BeltrixIII> <http://www.w3.org/2000/01/rdf-schema#comment> "Beltrix III was a factory planet in the Beltrix system, one of the Six Local Systems. It was the site of the Rebel headquarters in the Six Local Systems and also the headquarters of the Holstrum Talent Agency, a front for Rebel recruitment in which Alliance Intelligence Agent Keth Beamis worked as a talent scout. The cell on Beltrix III was established by Tet Tramys, Tendis Ancum, and Jioie Ancum. " .
<https://starwars.com#planet_BeltrixIII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_BeltrixIII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5fd056b0-b01e-447a-bd42-fc5dbbeef63d> .
<https://starwars.com#planet_BeltrixIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_BeltrixIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#5fd056b0-b01e-447a-bd42-fc5dbbeef63d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Beltrix III"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BeltrixIII> <http://telicent.io/ontology/primaryName> "Beltrix III" .
<https://starwars.com#5fd056b0-b01e-447a-bd42-fc5dbbeef63d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

