Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ozu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#103edd7f-99fd-42de-bb73-e843265f5008> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ozu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ozu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ozu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#103edd7f-99fd-42de-bb73-e843265f5008> .
<https://starwars.com#103edd7f-99fd-42de-bb73-e843265f5008> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ozu> <http://telicent.io/ontology/primaryName> "Ozu" .
<https://starwars.com#planet_Ozu> <http://www.w3.org/2000/01/rdf-schema#comment> "Ozu was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Ozu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .

