Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_SeleniusVII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d359db1-fd29-4299-9d01-998bb9cad895> .
<https://starwars.com#planet_SeleniusVII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAelgoth> .
<https://starwars.com#5d359db1-fd29-4299-9d01-998bb9cad895> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Selenius VII"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_SeleniusVII> <http://telicent.io/ontology/primaryName> "Selenius VII" .
<https://starwars.com#sector_DAelgoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_DAelgoth> <http://telicent.io/ontology/primaryName> "D'Aelgoth" .
<https://starwars.com#planet_SeleniusVII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_DAelgoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SeleniusVII> <http://www.w3.org/2000/01/rdf-schema#comment> "Selenius VII, also referred to as Selenius, was an astronomical object that lay in the Mid Rim's D'Aelgoth sector, along the D'Aelgoth Trade Route. A busy spaceport, it was the location of the establishment known as 'Arc of Fire' Bar & Grill." .
<https://starwars.com#5d359db1-fd29-4299-9d01-998bb9cad895> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SeleniusVII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .

