Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ce3ea275-0f4b-48da-b5e1-a2587c836e41> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Brodo Asogi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BrodoAsogi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#ce3ea275-0f4b-48da-b5e1-a2587c836e41> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Perinn> <http://telicent.io/ontology/primaryName> "Perinn" .
<https://starwars.com#planet_BrodoAsogi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce3ea275-0f4b-48da-b5e1-a2587c836e41> .
<https://starwars.com#planet_BrodoAsogi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_BrodoAsogi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Perinn> .
<https://starwars.com#planet_BrodoAsogi> <http://telicent.io/ontology/primaryName> "Brodo Asogi" .
<https://starwars.com#sector_Perinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_BrodoAsogi> <http://www.w3.org/2000/01/rdf-schema#comment> "It was represented by Senator Grebleips and two aides in the Galactic Senate. According to the HoloNet News, Grebleips was to fund an extragalactic expedition project shortly before the Clone Wars. " .
<https://starwars.com#sector_Perinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

