Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Valgauth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#sector_Nojic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#19fbd1c7-f2aa-450f-a2ba-638435041c05> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Valgauth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Valgauth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nojic> .
<https://starwars.com#sector_Nojic> <http://telicent.io/ontology/primaryName> "Nojic" .
<https://starwars.com#planet_Valgauth> <http://www.w3.org/2000/01/rdf-schema#comment> "Valgauth was a location in the galaxy. Its human inhabitants, the Valgauthians, had a reputation as berserkers when boarding starships. As such, a Valgauthian was regarded as a valuable addition to any pirate crew. " .
<https://starwars.com#planet_Valgauth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#19fbd1c7-f2aa-450f-a2ba-638435041c05> .
<https://starwars.com#19fbd1c7-f2aa-450f-a2ba-638435041c05> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Valgauth> <http://telicent.io/ontology/primaryName> "Valgauth" .
<https://starwars.com#planet_Valgauth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Nojic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

