Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Anturus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#d544e3ec-1dd7-4d83-9fb6-2a4bc5705346> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anturus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Anturus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Anturus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Anturus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d544e3ec-1dd7-4d83-9fb6-2a4bc5705346> .
<https://starwars.com#d544e3ec-1dd7-4d83-9fb6-2a4bc5705346> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anturus> <http://telicent.io/ontology/primaryName> "Anturus" .
<https://starwars.com#planet_Anturus> <http://www.w3.org/2000/01/rdf-schema#comment> "Anturus was a planet located in the Anturus system of the Senex sector, in the Mid Rim of the galaxy. It was the homeworld of House Picutorion. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

