Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#planet_Anantapar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#178a48d6-2a06-4889-aa01-cae6609c52bf> .
<https://starwars.com#planet_Anantapar> <http://www.w3.org/2000/01/rdf-schema#comment> "Anantapar was a planet located in the Anoat sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Anantapar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Anantapar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Anantapar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Anantapar> <http://telicent.io/ontology/primaryName> "Anantapar" .
<https://starwars.com#178a48d6-2a06-4889-aa01-cae6609c52bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#178a48d6-2a06-4889-aa01-cae6609c52bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anantapar"^^<http://www.w3.org/2001/XMLSchema#string> .

