Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mev> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eacea3ed-4385-4776-a7ab-553604850e32> .
<https://starwars.com#eacea3ed-4385-4776-a7ab-553604850e32> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mev> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mev> <http://telicent.io/ontology/primaryName> "Mev" .
<https://starwars.com#eacea3ed-4385-4776-a7ab-553604850e32> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mev"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Mev> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Mev> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mev> <http://www.w3.org/2000/01/rdf-schema#comment> "Mev was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .

