Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sorrus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5f1b751d-0049-4fa6-b0f8-527a4109680c> .
<https://starwars.com#sector_Kalamith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sorrus> <http://telicent.io/ontology/primaryName> "Sorrus" .
<https://starwars.com#sector_Kalamith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5f1b751d-0049-4fa6-b0f8-527a4109680c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sorrus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kalamith> <http://telicent.io/ontology/primaryName> "Kalamith" .
<https://starwars.com#planet_Sorrus> <http://www.w3.org/2000/01/rdf-schema#comment> "Sorrus was a planet in the Sorrus system located in the Outer Rim Territories. Its terrain consisted of mountain ranges and large deserts. The planet also had many sprawling cities. It had three capitals, one of which was Yinn La Hi. The Sorrusian people were xenophobic, and known for being unfriendly to outsiders. Jenna Zan Arbor once had her scientific lab located on Sorrus. " .
<https://starwars.com#planet_Sorrus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kalamith> .
<https://starwars.com#planet_Sorrus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#5f1b751d-0049-4fa6-b0f8-527a4109680c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sorrus"^^<http://www.w3.org/2001/XMLSchema#string> .

