Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Illodia> <http://telicent.io/ontology/primaryName> "Illodia" .
<https://starwars.com#planet_Illodia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#a45dbf31-a85d-4b69-83b7-d0f1d11f990d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Illodia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Illodia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a45dbf31-a85d-4b69-83b7-d0f1d11f990d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Illodia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a45dbf31-a85d-4b69-83b7-d0f1d11f990d> .
<https://starwars.com#planet_Illodia> <http://www.w3.org/2000/01/rdf-schema#comment> "Illodia was the sector capital of Illodia sector and home to the Illodian culture of Humans. The Illodians colonized 20 planets in Illodia sector. " .
<https://starwars.com#planet_Illodia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .

