Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Maldrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Maldrood> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NewHolstice> <http://telicent.io/ontology/primaryName> "New Holstice" .
<https://starwars.com#planet_NewHolstice> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maldrood> .
<https://starwars.com#22b488f9-e3c7-41e4-92ff-4c41c73b7555> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewHolstice> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#22b488f9-e3c7-41e4-92ff-4c41c73b7555> .
<https://starwars.com#sector_Maldrood> <http://telicent.io/ontology/primaryName> "Maldrood" .
<https://starwars.com#planet_NewHolstice> <http://www.w3.org/2000/01/rdf-schema#comment> "New Holstice was a location in the galaxy which had medical facilities associated with the Galactic Republic. The people from New Holstice hosted a monument to Jedi lost in service to the Republic. " .
<https://starwars.com#planet_NewHolstice> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#22b488f9-e3c7-41e4-92ff-4c41c73b7555> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Holstice"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NewHolstice> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .

