Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Crustai> <http://www.w3.org/2000/01/rdf-schema#comment> "Crustai was the second planet of the Crustai system in the Unknown Regions. It was part of the Chiss Ascendancy. " .
<https://starwars.com#grid_H8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_H8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3bb5e539-a49c-43f3-bc0c-5ebb1a82f8b7> .
<https://starwars.com#planet_Crustai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Crustai> <http://telicent.io/ontology/primaryName> "Crustai" .
<https://starwars.com#planet_Crustai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#3bb5e539-a49c-43f3-bc0c-5ebb1a82f8b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#1f4ebbbd-aa84-4314-b149-5b88bd36a7f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3bb5e539-a49c-43f3-bc0c-5ebb1a82f8b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Crustai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1f4ebbbd-aa84-4314-b149-5b88bd36a7f1> .
<https://starwars.com#grid_H8> <http://telicent.io/ontology/primaryName> "H8" .
<https://starwars.com#planet_Crustai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H8> .
<https://starwars.com#1f4ebbbd-aa84-4314-b149-5b88bd36a7f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Crustai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_H8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

