Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shelkonwa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#f876b424-aab3-437f-96d2-34af7cb28705> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shelkonwa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shelkonwa> <http://telicent.io/ontology/primaryName> "Shelkonwa" .
<https://starwars.com#planet_Shelkonwa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#f876b424-aab3-437f-96d2-34af7cb28705> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shelkonwa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shelkonwa> <http://www.w3.org/2000/01/rdf-schema#comment> "Shelkonwa was a planet in the Shelsha sector of the Colonies. " .
<https://starwars.com#planet_Shelkonwa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f876b424-aab3-437f-96d2-34af7cb28705> .

