Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Minos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pergitor> <http://telicent.io/ontology/primaryName> "Pergitor" .
<https://starwars.com#planet_Pergitor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pergitor> <http://www.w3.org/2000/01/rdf-schema#comment> "Pergitor was a planet in the Minos Cluster settled by Jesa Corporation miners. Excessive mining resulted in volcanic eruptions that poisoned the atmosphere and destroyed the ecosystem. The inhabitants were forced to retreat to sealed cities. " .
<https://starwars.com#a619b692-50d0-4b21-84fe-2e079e5bff69> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pergitor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Minos> .
<https://starwars.com#planet_Pergitor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a619b692-50d0-4b21-84fe-2e079e5bff69> .
<https://starwars.com#planet_Pergitor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#sector_Minos> <http://telicent.io/ontology/primaryName> "Minos" .
<https://starwars.com#sector_Minos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a619b692-50d0-4b21-84fe-2e079e5bff69> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pergitor"^^<http://www.w3.org/2001/XMLSchema#string> .

