Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tarabba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#sector_Tarabba> <http://telicent.io/ontology/primaryName> "Tarabba" .
<https://starwars.com#4200e027-4a45-49f9-8391-3c2ba2654e50> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tarabba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tarabba> .
<https://starwars.com#planet_Tarabba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Tarabba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tarabba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4200e027-4a45-49f9-8391-3c2ba2654e50> .
<https://starwars.com#sector_Tarabba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4200e027-4a45-49f9-8391-3c2ba2654e50> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tarabba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tarabba> <http://telicent.io/ontology/primaryName> "Tarabba" .
<https://starwars.com#planet_Tarabba> <http://www.w3.org/2000/01/rdf-schema#comment> "This article is about Tarabba. You may be looking for Tarabba Prime." .

