Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Stenos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Stenos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Spadja> .
<https://starwars.com#sector_Spadja> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Stenos> <http://telicent.io/ontology/primaryName> "Stenos" .
<https://starwars.com#sector_Spadja> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#bd67435b-ba2e-49a5-ba5a-0c89d984e97e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Stenos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Stenos> <http://www.w3.org/2000/01/rdf-schema#comment> "Stenos was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Stenos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bd67435b-ba2e-49a5-ba5a-0c89d984e97e> .
<https://starwars.com#planet_Stenos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bd67435b-ba2e-49a5-ba5a-0c89d984e97e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Spadja> <http://telicent.io/ontology/primaryName> "Spadja" .

