Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8d67f762-4537-496e-933f-84b18268dc9b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#943c45cc-aa3e-40dc-8a6d-43608773ff95> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Borgo Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BorgoPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Borgo Prime was a shadowport in the galaxy's Outer Rim Territories. Located on the Hydian Way, the former pirate Queen Maz Kanata marked it on a map that she included in the book that would eventually become known as the Smuggler's Guide. " .
<https://starwars.com#sector_Oricho> <http://telicent.io/ontology/primaryName> "Oricho" .
<https://starwars.com#8d67f762-4537-496e-933f-84b18268dc9b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_BorgoPrime> <http://telicent.io/ontology/primaryName> "Borgo Prime" .
<https://starwars.com#planet_BorgoPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#943c45cc-aa3e-40dc-8a6d-43608773ff95> .
<https://starwars.com#planet_BorgoPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Oricho> .
<https://starwars.com#planet_BorgoPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .
<https://starwars.com#943c45cc-aa3e-40dc-8a6d-43608773ff95> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_M6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8d67f762-4537-496e-933f-84b18268dc9b> .
<https://starwars.com#sector_Oricho> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_M6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_BorgoPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Oricho> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_M6> <http://telicent.io/ontology/primaryName> "M6" .

