Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tauber> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jaso> .
<https://starwars.com#sector_Jaso> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#da229ddc-1e0a-47a7-81ae-17c29bf4d35d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tauber> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#da229ddc-1e0a-47a7-81ae-17c29bf4d35d> .
<https://starwars.com#planet_Tauber> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#da229ddc-1e0a-47a7-81ae-17c29bf4d35d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tauber"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Jaso> <http://telicent.io/ontology/primaryName> "Jaso" .
<https://starwars.com#planet_Tauber> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tauber> <http://www.w3.org/2000/01/rdf-schema#comment> "Tauber was an Inner Rim world that lay on the Rimma Trade Route super-hyperroute. In 214 BBY, an antidote to the disease known as the Bordal Contagion was created on Tauber. Two centuries later, a hospital on Tauber was where the A4 laboratory assistant droid designated EV-A4-D began his service, while Neuro-Saav Corporation ran material-design laboratories on the world by 2 ABY. Doctor Cinto Alaras and the undercover Rebel Alliance Agent Sommen both worked at the Neuro-Saav facilities. " .
<https://starwars.com#sector_Jaso> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Tauber> <http://telicent.io/ontology/primaryName> "Tauber" .

