Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_YabolOpa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_YabolOpa> <http://www.w3.org/2000/01/rdf-schema#comment> "Yabol Opa was a terrestrial planet located in the regions known as the Colonies and the Interior. It was also situated in grid square M-9 of the Standard Galactic Grid, and the super-hyperroute known as the Perlemian Trade Route linked Yabol Opa to the Castell system as well as the Core Worlds' Brentaal System. " .
<https://starwars.com#planet_YabolOpa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_YabolOpa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#643d8ca9-e15f-49c4-95b6-421071951d17> .
<https://starwars.com#643d8ca9-e15f-49c4-95b6-421071951d17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_YabolOpa> <http://telicent.io/ontology/primaryName> "Yabol Opa" .
<https://starwars.com#planet_YabolOpa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#643d8ca9-e15f-49c4-95b6-421071951d17> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yabol Opa"^^<http://www.w3.org/2001/XMLSchema#string> .

