Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lyran> <http://www.w3.org/2000/01/rdf-schema#comment> "Lyran was a world in the galaxy where Chass na Chadic, pilot in the New Republic's Alphabet Squadron, had once visited. Several weeks after the Battle of Endor in 4 ABY, Chadic and her squadron visited a Jedi temple on the moon of the planet Harkrova I, where they found a holographic map of the galaxy. Chadick recognized Lyran in the map. " .
<https://starwars.com#93e8e5ef-9118-44bb-bd95-eb411a1297a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lyran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#planet_Lyran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#93e8e5ef-9118-44bb-bd95-eb411a1297a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lyran"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lyran> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#93e8e5ef-9118-44bb-bd95-eb411a1297a6> .
<https://starwars.com#sector_Quiberon> <http://telicent.io/ontology/primaryName> "Quiberon" .
<https://starwars.com#sector_Quiberon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lyran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quiberon> .
<https://starwars.com#planet_Lyran> <http://telicent.io/ontology/primaryName> "Lyran" .
<https://starwars.com#sector_Quiberon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

