Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7e28a761-5380-432f-a2c2-a46cdfce917f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nepoy"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Nepoy> <http://www.w3.org/2000/01/rdf-schema#comment> "Nepoy was a Mid Rim planet in the Nepoy system, Senex sector known for its legendary fruit fields. Nectarwine and other sugary alcoholic beverages were the planets' chief exports. " .
<https://starwars.com#planet_Nepoy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Nepoy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7e28a761-5380-432f-a2c2-a46cdfce917f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nepoy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Nepoy> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e28a761-5380-432f-a2c2-a46cdfce917f> .
<https://starwars.com#planet_Nepoy> <http://telicent.io/ontology/primaryName> "Nepoy" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

