Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KidietOlgo> <http://www.w3.org/2000/01/rdf-schema#comment> "Kidiet Olgo was a planet located in the Galactic Core. It was both a hotbed of slavery and a shadowport during the time of the Old Republic. Smugglers who did business with slave trader Graxol Kelvyyn operated out of Kidiet Olgo. " .
<https://starwars.com#planet_KidietOlgo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_KidietOlgo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac17d39b-0348-44a5-8072-14c26a82507e> .
<https://starwars.com#planet_KidietOlgo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_KidietOlgo> <http://telicent.io/ontology/primaryName> "Kidiet Olgo" .
<https://starwars.com#ac17d39b-0348-44a5-8072-14c26a82507e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kidiet Olgo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ac17d39b-0348-44a5-8072-14c26a82507e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KidietOlgo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

