Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Questal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J12> .
<https://starwars.com#planet_Questal> <http://www.w3.org/2000/01/rdf-schema#comment> "Questal was a location that the Imperial Lambda-class shuttle CS-831 was supposed to travel to. Instead, Adea Rite, the aide of Grand Admiral Rae Sloane, rerouted the shuttle to transport naamite batteries to Coruscant. " .
<https://starwars.com#planet_Questal> <http://telicent.io/ontology/primaryName> "Questal" .
<https://starwars.com#planet_Questal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#943bbd86-2325-4dcf-805c-0bfd012baa10> .
<https://starwars.com#planet_Questal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Questal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#943bbd86-2325-4dcf-805c-0bfd012baa10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#943bbd86-2325-4dcf-805c-0bfd012baa10> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Questal"^^<http://www.w3.org/2001/XMLSchema#string> .

