Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Krinemonen> <http://telicent.io/ontology/primaryName> "Krinemonen" .
<https://starwars.com#89a30ee9-2f55-4cdf-9681-5921e5d9ad05> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Krinemonen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#89a30ee9-2f55-4cdf-9681-5921e5d9ad05> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Krinemonen> <http://www.w3.org/2000/01/rdf-schema#comment> "Krinemonen was a gas giant planet in Calamari sector orbited by the oceanic moon of Krinemonen III. " .
<https://starwars.com#planet_Krinemonen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89a30ee9-2f55-4cdf-9681-5921e5d9ad05> .
<https://starwars.com#planet_Krinemonen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Krinemonen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Krinemonen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

