Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mataou> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mataou> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#83c0efae-fe82-4ae0-93aa-1642aab45ecf> .
<https://starwars.com#planet_Mataou> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#83c0efae-fe82-4ae0-93aa-1642aab45ecf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mataou"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mataou> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mataou> <http://www.w3.org/2000/01/rdf-schema#comment> "Mataou was a hot desert planet located in the Mataou system, in the Anoat sector of the Outer Rim Territories, on the edge of the Ivax Nebula. Long before the Galactic Civil War, Mataou was ruled by Hutts, including the Gnuda Kajidic. In their heyday, the Hutts of Mataou established vast settlements in the classical architectural Hutt style. " .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Mataou> <http://telicent.io/ontology/primaryName> "Mataou" .
<https://starwars.com#83c0efae-fe82-4ae0-93aa-1642aab45ecf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

