Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6230f720-46fa-4d5e-89c1-af218e479afe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gallinore"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gallinore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Gallinore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Gallinore> <http://telicent.io/ontology/primaryName> "Gallinore" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Gallinore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Gallinore> <http://www.w3.org/2000/01/rdf-schema#comment> "Gallinore was a planet in the Interior Regions of the Hapes Cluster that was famed for its rainbow gems. Gallinore was also home to a number of high-tech labs, including a lockdown facility where imprisoned researchers, including a former Jedi, were allowed to continue some work. " .
<https://starwars.com#planet_Gallinore> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6230f720-46fa-4d5e-89c1-af218e479afe> .
<https://starwars.com#6230f720-46fa-4d5e-89c1-af218e479afe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

