Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Karfeddion> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd127245-1048-4e16-acc5-1e7663d46f58> .
<https://starwars.com#planet_Karfeddion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Karfeddion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Karfeddion> <http://www.w3.org/2000/01/rdf-schema#comment> "Karfeddion was a planet located in the Senex sector within the galaxy's Mid Rim. Years prior to the Battle of Naboo, Q'anah's lover, a pirate leader in the Senex and member of House Elegin, was captured, sentenced to death, and executed on the planet. Karfeddion was connected via hyperspace route to Belsavis and Dolla. " .
<https://starwars.com#dd127245-1048-4e16-acc5-1e7663d46f58> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Karfeddion> <http://telicent.io/ontology/primaryName> "Karfeddion" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#dd127245-1048-4e16-acc5-1e7663d46f58> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karfeddion"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Karfeddion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .

