Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Nyny> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_Nyny> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#planet_Nyny> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_Nyny> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0fb12f69-d2b8-4f6a-9220-1de583a2669d> .
<https://starwars.com#0fb12f69-d2b8-4f6a-9220-1de583a2669d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0fb12f69-d2b8-4f6a-9220-1de583a2669d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nyny"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nyny> <http://www.w3.org/2000/01/rdf-schema#comment> "Nyny was a planet represented in the New Republic Senate. It was home to a three-headed sentient species. " .
<https://starwars.com#planet_Nyny> <http://telicent.io/ontology/primaryName> "Nyny" .

