Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Arcan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e9511dd7-e24a-4a20-a3d5-bfc5ec329247> .
<https://starwars.com#7ce2e8e8-452e-4f54-977b-08614a66113d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#e9511dd7-e24a-4a20-a3d5-bfc5ec329247> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Arcan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#sector_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#grid_R6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#e9511dd7-e24a-4a20-a3d5-bfc5ec329247> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arcan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arcan> <http://telicent.io/ontology/primaryName> "Arcan" .
<https://starwars.com#grid_R6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#7ce2e8e8-452e-4f54-977b-08614a66113d> .
<https://starwars.com#7ce2e8e8-452e-4f54-977b-08614a66113d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arcan> <http://www.w3.org/2000/01/rdf-schema#comment> "Arcan IV, sometimes known simply as Arcan, was a planet located within the Tion Cluster of the Outer Rim Territories. " .
<https://starwars.com#grid_R6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_R6> <http://telicent.io/ontology/primaryName> "R6" .
<https://starwars.com#sector_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Arcan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thanium> .
<https://starwars.com#planet_Arcan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

