Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_SpiceTerminus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Parmic> .
<https://starwars.com#planet_SpiceTerminus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_SpiceTerminus> <http://telicent.io/ontology/primaryName> "Spice Terminus" .
<https://starwars.com#sector_Parmic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#bace83ef-e956-4aba-93ba-2524f1b93319> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Spice Terminus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Parmic> <http://telicent.io/ontology/primaryName> "Parmic" .
<https://starwars.com#sector_Parmic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_SpiceTerminus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P18> .
<https://starwars.com#bace83ef-e956-4aba-93ba-2524f1b93319> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SpiceTerminus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bace83ef-e956-4aba-93ba-2524f1b93319> .
<https://starwars.com#planet_SpiceTerminus> <http://www.w3.org/2000/01/rdf-schema#comment> "Spice Terminus was a location in the Outer Rim Territories of the galaxy. " .

