Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#226abb69-851a-4371-8329-1a2371f09ded> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bresnia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#226abb69-851a-4371-8329-1a2371f09ded> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bresnia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#226abb69-851a-4371-8329-1a2371f09ded> .
<https://starwars.com#planet_Bresnia> <http://www.w3.org/2000/01/rdf-schema#comment> "Bresnia was a planet located in the Tandon sector of the Mid Rim. " .
<https://starwars.com#sector_Tandon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q14> <http://telicent.io/ontology/primaryName> "Q14" .
<https://starwars.com#grid_Q14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#90d35994-f0fb-4b70-8c9f-67e0778589d6> .
<https://starwars.com#sector_Tandon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Bresnia> <http://telicent.io/ontology/primaryName> "Bresnia" .
<https://starwars.com#grid_Q14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Bresnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q14> .
<https://starwars.com#sector_Tandon> <http://telicent.io/ontology/primaryName> "Tandon" .
<https://starwars.com#planet_Bresnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tandon> .
<https://starwars.com#90d35994-f0fb-4b70-8c9f-67e0778589d6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bresnia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#90d35994-f0fb-4b70-8c9f-67e0778589d6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

