Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Cheku> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cheku> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f563184b-334b-4103-9356-58a0d642ecc0> .
<https://starwars.com#planet_Cheku> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brevost> .
<https://starwars.com#f563184b-334b-4103-9356-58a0d642ecc0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cheku> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Cheku> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#planet_Cheku> <http://telicent.io/ontology/primaryName> "Cheku" .
<https://starwars.com#sector_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#f563184b-334b-4103-9356-58a0d642ecc0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cheku"^^<http://www.w3.org/2001/XMLSchema#string> .

