Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ecc6b02f-463a-42f9-97dd-e992bba5a2d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Poderis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Poderis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Orus> .
<https://starwars.com#planet_Poderis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#planet_Poderis> <http://www.w3.org/2000/01/rdf-schema#comment> "Poderis was a planet in the Orus sector of the Inner Rim. " .
<https://starwars.com#sector_Orus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Poderis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ecc6b02f-463a-42f9-97dd-e992bba5a2d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Poderis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ecc6b02f-463a-42f9-97dd-e992bba5a2d7> .
<https://starwars.com#sector_Orus> <http://telicent.io/ontology/primaryName> "Orus" .
<https://starwars.com#sector_Orus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Poderis> <http://telicent.io/ontology/primaryName> "Poderis" .

