Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ota> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ota> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ota> <http://www.w3.org/2000/01/rdf-schema#comment> "Ota was a frozen world in the Kashyyyk Region of the Mid Rim which was the home of the furry sentient species known as the Snogars. The Snogars lived in cities built within the planet's ice canyons by their ancestors, a highly intelligent race referred to as the 'Old Ones.' By 1 ABY the heating machines that kept the Snogar cities warm began to fail, leading Ota's natives to seek out offworlders who could repair the devices and help them survive the planet's biting cold. " .
<https://starwars.com#planet_Ota> <http://telicent.io/ontology/primaryName> "Ota" .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Ota> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#794460d5-5b31-4a64-916a-dd387f9e74bf> .
<https://starwars.com#planet_Ota> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#794460d5-5b31-4a64-916a-dd387f9e74bf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ota"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#794460d5-5b31-4a64-916a-dd387f9e74bf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

