Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Korbin> <http://telicent.io/ontology/primaryName> "Korbin" .
<https://starwars.com#planet_Korbin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J14> .
<https://starwars.com#planet_Korbin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2621f98f-2fb4-4769-aad0-cf3ddf0b4b1e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korbin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Korbin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2621f98f-2fb4-4769-aad0-cf3ddf0b4b1e> .
<https://starwars.com#planet_Korbin> <http://www.w3.org/2000/01/rdf-schema#comment> "Korbin was a planet in the Inner Rim. " .
<https://starwars.com#2621f98f-2fb4-4769-aad0-cf3ddf0b4b1e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Korbin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

