Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NarKaaga> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6b5a0a8d-6b80-4b7e-b26c-b2ff4e0dc9b7> .
<https://starwars.com#planet_NarKaaga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S13> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#6b5a0a8d-6b80-4b7e-b26c-b2ff4e0dc9b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NarKaaga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_NarKaaga> <http://telicent.io/ontology/primaryName> "Nar Kaaga" .
<https://starwars.com#planet_NarKaaga> <http://www.w3.org/2000/01/rdf-schema#comment> "Nar Kaaga was an astronomical object located in the Hutt Space region of the galaxy. It was connected to fellow Hutt Space world Circumtore and the Bothan Space planet Bothawui by hyperspace routes. Nar Kaaga was located at galactic coordinates S-13. " .
<https://starwars.com#6b5a0a8d-6b80-4b7e-b26c-b2ff4e0dc9b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nar Kaaga"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NarKaaga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

