Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kira> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7f5bd0e6-ee64-4fb7-8193-d4bb371c1d7f> .
<https://starwars.com#planet_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#sector_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#planet_Kira> <http://www.w3.org/2000/01/rdf-schema#comment> "Kira was an astronomical object located in the Expansion Region and the Trailing Sectors regions, in grid square N-16 of the Standard Galactic Grid. Hyperspace routes linked Kira to the celestial bodies Bacrana, Kalinda, Pax, and Wroona. " .
<https://starwars.com#7f5bd0e6-ee64-4fb7-8193-d4bb371c1d7f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kira"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kira> .
<https://starwars.com#planet_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#7f5bd0e6-ee64-4fb7-8193-d4bb371c1d7f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

