Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Charubah> <http://telicent.io/ontology/primaryName> "Charubah" .
<https://starwars.com#16ae4bd6-b46c-47fd-8816-9562ad61c0b3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Charubah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Charubah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Charubah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Charubah> <http://www.w3.org/2000/01/rdf-schema#comment> "Charubah was a technology-oriented planet located within the Hapes Cluster, and famed for their Guns of Command designed by Royal Armaments Guild of Charubah. " .
<https://starwars.com#planet_Charubah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#16ae4bd6-b46c-47fd-8816-9562ad61c0b3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Charubah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#16ae4bd6-b46c-47fd-8816-9562ad61c0b3> .

