Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Merakai> <http://telicent.io/ontology/primaryName> "Merakai" .
<https://starwars.com#planet_Merakai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Merakai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Merakai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e7afca61-2d8c-4b9e-92fe-62248f766b8c> .
<https://starwars.com#e7afca61-2d8c-4b9e-92fe-62248f766b8c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Merakai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Merakai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e7afca61-2d8c-4b9e-92fe-62248f766b8c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Merakai> <http://www.w3.org/2000/01/rdf-schema#comment> "Merakai was a colony of the Khil species. " .

