Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tinoon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tinoon> <http://www.w3.org/2000/01/rdf-schema#comment> "Tinoon was a planet located in the Anoat sector of the Outer Rim Territories. Months into the blockade of the sector by the Galactic Empire, a Rebel cargo filled with foodstuffs and armor was impounded at the Tinoon spaceport. " .
<https://starwars.com#1d72b257-23e5-415e-ab22-177cbc94212d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tinoon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Tinoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1d72b257-23e5-415e-ab22-177cbc94212d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tinoon> <http://telicent.io/ontology/primaryName> "Tinoon" .
<https://starwars.com#planet_Tinoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Tinoon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1d72b257-23e5-415e-ab22-177cbc94212d> .

