Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Voktunma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d895b5ca-9300-476d-9098-28a70d84731a> .
<https://starwars.com#planet_Voktunma> <http://telicent.io/ontology/primaryName> "Voktunma" .
<https://starwars.com#planet_Voktunma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Voktunma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d895b5ca-9300-476d-9098-28a70d84731a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Voktunma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Voktunma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Voktunma> <http://www.w3.org/2000/01/rdf-schema#comment> "Voktunma was a planet in the Voktunma system of the Core Worlds. " .
<https://starwars.com#d895b5ca-9300-476d-9098-28a70d84731a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

