Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Renatasia> <http://www.w3.org/2000/01/rdf-schema#comment> "Renatasia was an astronomical object located in the Centrality, a sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Renatasia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2260c447-121e-4787-9a8d-d29cd5be0119> .
<https://starwars.com#planet_Renatasia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#2260c447-121e-4787-9a8d-d29cd5be0119> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Renatasia> <http://telicent.io/ontology/primaryName> "Renatasia" .
<https://starwars.com#planet_Renatasia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#planet_Renatasia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#2260c447-121e-4787-9a8d-d29cd5be0119> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Renatasia"^^<http://www.w3.org/2001/XMLSchema#string> .

