Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f9eb048c-537c-460a-8238-ee4d17bb09b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f9eb048c-537c-460a-8238-ee4d17bb09b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bseto"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bseto> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f9eb048c-537c-460a-8238-ee4d17bb09b5> .
<https://starwars.com#sector_Msst> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bseto> <http://telicent.io/ontology/primaryName> "Bseto" .
<https://starwars.com#planet_Bseto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Msst> .
<https://starwars.com#planet_Bseto> <http://www.w3.org/2000/01/rdf-schema#comment> "Bseto was a white dwarf found in the Bseto system. It was orbited by three planets, Bseto I, Indikir and Sarahwiee. Between Indikir and Sarahwiee was the Lweilot Asteroid Belt. " .
<https://starwars.com#sector_Msst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Bseto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P7> .
<https://starwars.com#sector_Msst> <http://telicent.io/ontology/primaryName> "Msst" .
<https://starwars.com#planet_Bseto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

