Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Carcel> <http://www.w3.org/2000/01/rdf-schema#comment> "Carcel was a planet located in the Expansion Region, and was described by Tobb Jadak as a miserable piece of rock. Carcel had a prison that Jadak and Flitcher Poste visited Rej Taunt in. " .
<https://starwars.com#c084c652-8aed-4302-b360-ec2942d94514> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Carcel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c084c652-8aed-4302-b360-ec2942d94514> .
<https://starwars.com#planet_Carcel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#c084c652-8aed-4302-b360-ec2942d94514> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carcel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Carcel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Carcel> <http://telicent.io/ontology/primaryName> "Carcel" .
<https://starwars.com#sector_Locris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Locris> <http://telicent.io/ontology/primaryName> "Locris" .
<https://starwars.com#sector_Locris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Carcel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Locris> .

