Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Nouane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#adfbe37c-a807-4e44-8041-dad4fcbb58c4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Telerath"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Nouane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Telerath> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#adfbe37c-a807-4e44-8041-dad4fcbb58c4> .
<https://starwars.com#planet_Telerath> <http://telicent.io/ontology/primaryName> "Telerath" .
<https://starwars.com#planet_Telerath> <http://www.w3.org/2000/01/rdf-schema#comment> "Telerath was a planet located in the Nouane sector of the Inner Rim. It was allegedly a resort world but had problems with gang violence. Disputes on Telerath were settled through sword combat, in a convention known as Sword Law. In a cantina on Telerath, the bounty hunter Jango Fett and his son, Boba, met with fellow hunters Neelda, Rinn, and Tiver, who Fett had hired for an upcoming mission. " .
<https://starwars.com#planet_Telerath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nouane> .
<https://starwars.com#planet_Telerath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#sector_Nouane> <http://telicent.io/ontology/primaryName> "Nouane" .
<https://starwars.com#planet_Telerath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#adfbe37c-a807-4e44-8041-dad4fcbb58c4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

