Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Skartis> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Skartis> <http://telicent.io/ontology/primaryName> "Skartis" .
<https://starwars.com#e3b73bab-e982-4aa7-98b4-f499c19fe192> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skartis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Skartis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e3b73bab-e982-4aa7-98b4-f499c19fe192> .
<https://starwars.com#planet_Skartis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Skartis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e3b73bab-e982-4aa7-98b4-f499c19fe192> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Skartis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .

