Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d535c557-4f14-4f27-8fc7-f2e959bf2950> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rehemsa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rehemsa> <http://www.w3.org/2000/01/rdf-schema#comment> "Rehemsa was a Core Worlds planet. " .
<https://starwars.com#d535c557-4f14-4f27-8fc7-f2e959bf2950> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rehemsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Rehemsa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rehemsa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d535c557-4f14-4f27-8fc7-f2e959bf2950> .
<https://starwars.com#planet_Rehemsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Rehemsa> <http://telicent.io/ontology/primaryName> "Rehemsa" .

