Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chanosant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .
<https://starwars.com#sector_Harron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Chanosant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Harron> .
<https://starwars.com#planet_Chanosant> <http://www.w3.org/2000/01/rdf-schema#comment> "Chanosant was a world in the Expansion Region's Chanosant system. During the Clone Wars, it was the site of a Separatist convention which was attended by Count Dooku and held during the Clone Wars. Dooku and Kob Mondray attended it and tried to use it to rally more support for the CIS. " .
<https://starwars.com#35fc88fc-d126-4300-b532-316ba9b14b0b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Chanosant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#35fc88fc-d126-4300-b532-316ba9b14b0b> .
<https://starwars.com#35fc88fc-d126-4300-b532-316ba9b14b0b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chanosant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Harron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Harron> <http://telicent.io/ontology/primaryName> "Harron" .
<https://starwars.com#planet_Chanosant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chanosant> <http://telicent.io/ontology/primaryName> "Chanosant" .

