Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Xobome> <http://www.w3.org/2000/01/rdf-schema#comment> "Xobome was the Xobome system's primary star. The planet Xobome 6 orbited this sun. " .
<https://starwars.com#planet_Xobome> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Xobome> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Xobome> <http://telicent.io/ontology/primaryName> "Xobome" .
<https://starwars.com#b0804672-1b2c-467e-85b7-7d7e2dfd38cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b0804672-1b2c-467e-85b7-7d7e2dfd38cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xobome"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Xobome> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#planet_Xobome> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b0804672-1b2c-467e-85b7-7d7e2dfd38cd> .

