Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tanjay> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#0f4b16eb-c1de-4c25-adfa-218b882bb33c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tanjay"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tanjay> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#0f4b16eb-c1de-4c25-adfa-218b882bb33c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tanjay> <http://telicent.io/ontology/primaryName> "Tanjay" .
<https://starwars.com#planet_Tanjay> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0f4b16eb-c1de-4c25-adfa-218b882bb33c> .
<https://starwars.com#planet_Tanjay> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Tanjay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

