Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nierport> <http://telicent.io/ontology/primaryName> "Nierport" .
<https://starwars.com#7ada3622-ecba-4b98-95d2-7110c81cf039> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7ada3622-ecba-4b98-95d2-7110c81cf039> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nierport"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nierport> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_Nierport> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Nierport> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nierport> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Nierport> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7ada3622-ecba-4b98-95d2-7110c81cf039> .

