Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#7fa13530-a32b-4d8a-bc06-a2d19c1338c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7fa13530-a32b-4d8a-bc06-a2d19c1338c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mytaranor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7fa13530-a32b-4d8a-bc06-a2d19c1338c3> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mytaranor> <http://www.w3.org/2000/01/rdf-schema#comment> "Mytaranor was a bleak industrial world located in the Mytaranor system, a part of the Kashyyyk Region's Mytaranor sector in the Slice portion of the Mid Rim. The hyperlane known as the Nightroad linked it to the Tholatin system as well as the Terr'skiar sector's Pizilis system. " .
<https://starwars.com#planet_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .

