Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Meridian> <http://telicent.io/ontology/primaryName> "Meridian" .
<https://starwars.com#planet_Cybloc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meridian> .
<https://starwars.com#fce00619-709e-4a98-82b9-d1f33ff909c0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cybloc"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cybloc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#fce00619-709e-4a98-82b9-d1f33ff909c0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cybloc> <http://telicent.io/ontology/primaryName> "Cybloc" .
<https://starwars.com#planet_Cybloc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Meridian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cybloc> <http://www.w3.org/2000/01/rdf-schema#comment> "Cybloc was a greenish planet orbiting the star Erg Es 992 in the Meridian sector. During the Clone Wars there was a space station in orbit over the planet. Darth Maul and his brother Savage Opress broke into the space station and stole some credits. One of its moons, Cybloc XII, housed a New Republic trade base. However, the region was purged during the Death Seed incident. " .
<https://starwars.com#sector_Meridian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cybloc> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fce00619-709e-4a98-82b9-d1f33ff909c0> .

