Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d9afd837-b066-44b9-b24f-0d6f6ff66f88> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Svivren"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Svivren> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Svivreni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Svivren> <http://www.w3.org/2000/01/rdf-schema#comment> "Svivren was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Svivren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Svivreni> .
<https://starwars.com#planet_Svivren> <http://telicent.io/ontology/primaryName> "Svivren" .
<https://starwars.com#sector_Svivreni> <http://telicent.io/ontology/primaryName> "Svivreni" .
<https://starwars.com#sector_Svivreni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Svivren> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d9afd837-b066-44b9-b24f-0d6f6ff66f88> .
<https://starwars.com#planet_Svivren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O19> .
<https://starwars.com#d9afd837-b066-44b9-b24f-0d6f6ff66f88> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

