Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thoadeye> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Thoadeye> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2225554f-d610-4b0d-a749-f20259de9836> .
<https://starwars.com#planet_Thoadeye> <http://www.w3.org/2000/01/rdf-schema#comment> "Thoadeye was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Thoadeye> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2225554f-d610-4b0d-a749-f20259de9836> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thoadeye"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thoadeye> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#2225554f-d610-4b0d-a749-f20259de9836> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thoadeye> <http://telicent.io/ontology/primaryName> "Thoadeye" .

