Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdGrovner> <http://telicent.io/ontology/primaryName> "Ord Grovner" .
<https://starwars.com#planet_OrdGrovner> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Khuiumin> .
<https://starwars.com#planet_OrdGrovner> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#62cf5551-b427-4ea7-b9e9-4f2e8786eb59> .
<https://starwars.com#62cf5551-b427-4ea7-b9e9-4f2e8786eb59> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Grovner"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdGrovner> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Grovner was a planet in the Outer Rim Territories near Courkrus. Originally an Ordnance/Regional Depot, the planet served as a staging area for the Imperial task force, led by Admiral Freeda, which wiped out the Eyttyrmin Batiiv pirates. " .
<https://starwars.com#planet_OrdGrovner> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Khuiumin> <http://telicent.io/ontology/primaryName> "Khuiumin" .
<https://starwars.com#sector_Khuiumin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#62cf5551-b427-4ea7-b9e9-4f2e8786eb59> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Khuiumin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdGrovner> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O18> .

