Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#990ec740-5dee-47ff-b2fe-12e277e07042> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Moltok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Moltok> <http://telicent.io/ontology/primaryName> "Moltok" .
<https://starwars.com#planet_Moltok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#planet_Moltok> <http://www.w3.org/2000/01/rdf-schema#comment> "Moltok was an astronomical object located in the galaxy's Outer Rim Territories that was home to a Ho'Din settlement. During the reign of the Galactic Empire, the settlement came under attack from a local Makurth boss leading the Ho'Din to request the aid of Imperial muscle to prevent the crisis from becoming a full-fledged war. Imperial forces stationed aboard the Gozanti-class cruiser Blood Crow under the command of Captain Filia Rossi were sent to settle the matter. " .
<https://starwars.com#planet_Moltok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#990ec740-5dee-47ff-b2fe-12e277e07042> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Moltok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#990ec740-5dee-47ff-b2fe-12e277e07042> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Moltok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

