Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#2175094a-4d7f-44f7-8606-d258d8e87d6c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tekurr'k"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tekurrk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tekurrk> <http://telicent.io/ontology/primaryName> "Tekurr'k" .
<https://starwars.com#planet_Tekurrk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2175094a-4d7f-44f7-8606-d258d8e87d6c> .
<https://starwars.com#planet_Tekurrk> <http://www.w3.org/2000/01/rdf-schema#comment> "Tekurr'k was a planet located within the Tekurr'k system of the Mid Rim's Senex sector. " .
<https://starwars.com#2175094a-4d7f-44f7-8606-d258d8e87d6c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tekurrk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Tekurrk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .

