Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7ee7cea4-a8b6-4af5-926c-5461f5ced8cb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7ee7cea4-a8b6-4af5-926c-5461f5ced8cb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Phu> <http://www.w3.org/2000/01/rdf-schema#comment> "Phu was an astronomical object located in the Phu system of the Colonies region of the galaxy that was colonized by the Bardottan species of Bardotta. It was the homeworld of the Bardottan podracer Mars Guo. " .
<https://starwars.com#planet_Phu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Phu> <http://telicent.io/ontology/primaryName> "Phu" .
<https://starwars.com#planet_Phu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#planet_Phu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7ee7cea4-a8b6-4af5-926c-5461f5ced8cb> .
<https://starwars.com#planet_Phu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

