Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Omonoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#planet_Omonoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Omonoth> <http://www.w3.org/2000/01/rdf-schema#comment> "    Exogorths devouring the asteroids around Omonoth.  " .
<https://starwars.com#9c1ce748-5534-458f-8065-536af7e63f30> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Omonoth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9c1ce748-5534-458f-8065-536af7e63f30> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Omonoth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9c1ce748-5534-458f-8065-536af7e63f30> .
<https://starwars.com#planet_Omonoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Omonoth> <http://telicent.io/ontology/primaryName> "Omonoth" .

