Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Surron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Surron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Surron> <http://telicent.io/ontology/primaryName> "Surron" .
<https://starwars.com#b55198e5-c6fd-4f39-adf5-9280be4ab614> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Surron> <http://www.w3.org/2000/01/rdf-schema#comment> "Surron was a planet in the Expansion Region. It was the headquarters of Surron StarTech. The Surronians, which lived on this planet, had a guild-based society. " .
<https://starwars.com#planet_Surron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#sector_Surron> <http://telicent.io/ontology/primaryName> "Surron" .
<https://starwars.com#planet_Surron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Surron> .
<https://starwars.com#b55198e5-c6fd-4f39-adf5-9280be4ab614> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Surron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Surron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Surron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b55198e5-c6fd-4f39-adf5-9280be4ab614> .

