Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thalassia> <http://telicent.io/ontology/primaryName> "Thalassia" .
<https://starwars.com#34db8b5e-37ac-41aa-8c06-0968df53bf98> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thalassia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thalassia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#34db8b5e-37ac-41aa-8c06-0968df53bf98> .
<https://starwars.com#sector_Meram> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thalassia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meram> .
<https://starwars.com#sector_Meram> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Thalassia> <http://www.w3.org/2000/01/rdf-schema#comment> "Thalassia was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Meram> <http://telicent.io/ontology/primaryName> "Meram" .
<https://starwars.com#planet_Thalassia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thalassia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P4> .
<https://starwars.com#34db8b5e-37ac-41aa-8c06-0968df53bf98> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

