Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zalori> <http://telicent.io/ontology/primaryName> "Zalori" .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#cf52f58b-793c-4c7b-9483-8977c2f14fbd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zalori"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zalori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zalori> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf52f58b-793c-4c7b-9483-8977c2f14fbd> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Zalori> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#cf52f58b-793c-4c7b-9483-8977c2f14fbd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Zalori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Zalori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .

