Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Dufilvian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Womrik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dufilvian> .
<https://starwars.com#planet_Womrik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q15> .
<https://starwars.com#b34e4744-8800-4684-89ee-c2f1c129aba3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Womrik"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Womrik> <http://www.w3.org/2000/01/rdf-schema#comment> "Garm Bel Iblis used it as a location for Peregrine's Nest. " .
<https://starwars.com#planet_Womrik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Womrik> <http://telicent.io/ontology/primaryName> "Womrik" .
<https://starwars.com#planet_Womrik> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b34e4744-8800-4684-89ee-c2f1c129aba3> .
<https://starwars.com#sector_Dufilvian> <http://telicent.io/ontology/primaryName> "Dufilvian" .
<https://starwars.com#sector_Dufilvian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b34e4744-8800-4684-89ee-c2f1c129aba3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

