Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9be19983-addd-4041-aae7-aa20e72691cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thonner"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#9be19983-addd-4041-aae7-aa20e72691cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thonner> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thonner> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thonner> <http://www.w3.org/2000/01/rdf-schema#comment> "Thonner was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was linked by the Houche Run hyperspace route to the celestial bodies Maya Kovel and Ovise, while another route connected it to Qina. Thonner was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_Thonner> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Thonner> <http://telicent.io/ontology/primaryName> "Thonner" .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_Thonner> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9be19983-addd-4041-aae7-aa20e72691cd> .

