Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TertiaryFeswe> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf4ac7c1-9f22-4b73-9c88-b9b273ae1a92> .
<https://starwars.com#planet_TertiaryFeswe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#cf4ac7c1-9f22-4b73-9c88-b9b273ae1a92> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tertiary Feswe"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_TertiaryFeswe> <http://telicent.io/ontology/primaryName> "Tertiary Feswe" .
<https://starwars.com#planet_TertiaryFeswe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#cf4ac7c1-9f22-4b73-9c88-b9b273ae1a92> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TertiaryFeswe> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_TertiaryFeswe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

