Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1a188e84-6cd2-4832-9e4e-07b6ebe7923d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Weerden> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a188e84-6cd2-4832-9e4e-07b6ebe7923d> .
<https://starwars.com#planet_Weerden> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Weerden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Weerden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Weerden> <http://telicent.io/ontology/primaryName> "Weerden" .
<https://starwars.com#1a188e84-6cd2-4832-9e4e-07b6ebe7923d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Weerden"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Weerden> <http://www.w3.org/2000/01/rdf-schema#comment> "Weerden was an Imperial planet located within the Weerden system of the Core Worlds, near Coruscant. It was here that an assassin droid killed Grand Inquisitor Laddinare Torbin by crashing his shuttle, Sark-I into Torbin's palace. " .

