Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_DarlynBoda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_DarlynBoda> <http://telicent.io/ontology/primaryName> "Darlyn Boda" .
<https://starwars.com#planet_DarlynBoda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b6606149-6ac9-4d9c-b39a-3543ba02400b> .
<https://starwars.com#planet_DarlynBoda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_DarlynBoda> <http://www.w3.org/2000/01/rdf-schema#comment> "Darlyn Boda was a planet in the Anoat sector of the Outer Rim Territories. During the Galactic Empire's Iron Blockade, Darlyn Boda had a criminal network which included the Trade Spine League and the Ivax Syndicate. " .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#b6606149-6ac9-4d9c-b39a-3543ba02400b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b6606149-6ac9-4d9c-b39a-3543ba02400b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Darlyn Boda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DarlynBoda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

