Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b9fc6893-ea1d-4f59-a29a-dac09d426df4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L1"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#bc00ed97-d52c-4f7b-a8e5-6524e9e22de0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_L1> <http://telicent.io/ontology/primaryName> "L1" .
<https://starwars.com#sector_Dalonbian> <http://telicent.io/ontology/primaryName> "Dalonbian" .
<https://starwars.com#planet_Belkadan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Dalonbian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Belkadan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L1> .
<https://starwars.com#planet_Belkadan> <http://www.w3.org/2000/01/rdf-schema#comment> "Belkadan was an astronomical object located in the regions known as the Outer Rim Territories and the New Territories. It was situated within grid square L-1 on the Standard Galactic Grid. " .
<https://starwars.com#sector_Dalonbian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Belkadan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalonbian> .
<https://starwars.com#b9fc6893-ea1d-4f59-a29a-dac09d426df4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L1> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_L1> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b9fc6893-ea1d-4f59-a29a-dac09d426df4> .
<https://starwars.com#planet_Belkadan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bc00ed97-d52c-4f7b-a8e5-6524e9e22de0> .
<https://starwars.com#planet_Belkadan> <http://telicent.io/ontology/primaryName> "Belkadan" .
<https://starwars.com#bc00ed97-d52c-4f7b-a8e5-6524e9e22de0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belkadan"^^<http://www.w3.org/2001/XMLSchema#string> .

