Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MayaKovel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MayaKovel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#ce44b9f7-7b41-4c70-a61f-a0c8e231e574> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Maya Kovel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_MayaKovel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_MayaKovel> <http://www.w3.org/2000/01/rdf-schema#comment> "The celestial body Maya Kovel was located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was linked via the Houche Run hyperspace route to the astronomical objects Thonner and Vasha. Maya Kovel was depicted on a Moddell sector map included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_MayaKovel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce44b9f7-7b41-4c70-a61f-a0c8e231e574> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MayaKovel> <http://telicent.io/ontology/primaryName> "Maya Kovel" .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#ce44b9f7-7b41-4c70-a61f-a0c8e231e574> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

