Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Selitan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_Selitan> <http://www.w3.org/2000/01/rdf-schema#comment> "Selitan was a mining planet in the Gordian Reach. " .
<https://starwars.com#f0f0abf2-5fa3-4c82-a8db-9762eb50f118> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f0f0abf2-5fa3-4c82-a8db-9762eb50f118> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Selitan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Selitan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Selitan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f0f0abf2-5fa3-4c82-a8db-9762eb50f118> .
<https://starwars.com#planet_Selitan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Selitan> <http://telicent.io/ontology/primaryName> "Selitan" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

