Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vaced> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6305a43a-84a3-4140-b081-59146a7986b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vaced"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vaced> <http://www.w3.org/2000/01/rdf-schema#comment> "Vaced was a terrestrial astronomical object in the galaxy. At some point between 32 BBY and 22 BBY, Jedi Knight Obi-Wan Kenobi and his Padawan, Anakin Skywalker, visited Vaced. The two encountered a Moggonite bounty hunter there, and Skywalker saved Kenobi's life. Later, during a mission to the planet Cato Neimoidia after Skywalker had become a Knight himself, he brought up the incident on Vaced while telling Kenobi he intended to start tracking how many times he had saved the Jedi Master. " .
<https://starwars.com#planet_Vaced> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Jalor> <http://telicent.io/ontology/primaryName> "Jalor" .
<https://starwars.com#planet_Vaced> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6305a43a-84a3-4140-b081-59146a7986b5> .
<https://starwars.com#6305a43a-84a3-4140-b081-59146a7986b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vaced> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jalor> .
<https://starwars.com#sector_Jalor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vaced> <http://telicent.io/ontology/primaryName> "Vaced" .
<https://starwars.com#sector_Jalor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

