Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d1742edf-5e43-486b-8e33-bb8842fd1c77> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Arkania> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d1742edf-5e43-486b-8e33-bb8842fd1c77> .
<https://starwars.com#5124c24e-0356-4a56-8e3e-ec8fa4861d69> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#5124c24e-0356-4a56-8e3e-ec8fa4861d69> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_M8> <http://telicent.io/ontology/primaryName> "M8" .
<https://starwars.com#planet_Arkania> <http://www.w3.org/2000/01/rdf-schema#comment> "Arkania was a cold planet located in the galaxy's Colonies region, positioned at the coordinates M-8 on the Standard Galactic Grid that was the homeworld of Arkanian species. It shared its name with the creatures known as Arkanian dragons. In the weeks following the Battle of Endor, the New Republic was involved in a battle on Arkania that included ground-level fighting. " .
<https://starwars.com#planet_Arkania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#planet_Arkania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#grid_M8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5124c24e-0356-4a56-8e3e-ec8fa4861d69> .
<https://starwars.com#grid_M8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#d1742edf-5e43-486b-8e33-bb8842fd1c77> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arkania"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arkania> <http://telicent.io/ontology/primaryName> "Arkania" .
<https://starwars.com#planet_Arkania> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

