Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sif-Uwana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b72948f8-56f7-4a72-93c5-6ef1ed590a75> .
<https://starwars.com#b72948f8-56f7-4a72-93c5-6ef1ed590a75> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sif-Uwana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b72948f8-56f7-4a72-93c5-6ef1ed590a75> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sif-Uwana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Sif-Uwana> <http://telicent.io/ontology/primaryName> "Sif-Uwana" .
<https://starwars.com#planet_Sif-Uwana> <http://www.w3.org/2000/01/rdf-schema#comment> "Sif-Uwana was a planet within the Colonies area of the galaxy. It was the homeworld of the individuals known as Sif-Uwani and was administered by the Sif-Uwana Council. The planet was controlled by Alsakan during the Alsakan Conflicts but was eventually lost to the Galactic Republic. At some point, the Emperor's agent Mara Jade visited the world. " .
<https://starwars.com#planet_Sif-Uwana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#planet_Sif-Uwana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

