Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_U12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#c25f64f7-6c01-4d30-b220-0a52ad216e76> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#01aa6b41-dfd7-4188-a1f2-db2304195f96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barab"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c25f64f7-6c01-4d30-b220-0a52ad216e76> .
<https://starwars.com#sector_Albanin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Albanin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_U12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Barab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .
<https://starwars.com#planet_Barab> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#01aa6b41-dfd7-4188-a1f2-db2304195f96> .
<https://starwars.com#sector_Albanin> <http://telicent.io/ontology/primaryName> "Albanin" .
<https://starwars.com#grid_U12> <http://telicent.io/ontology/primaryName> "U12" .
<https://starwars.com#planet_Barab> <http://telicent.io/ontology/primaryName> "Barab" .
<https://starwars.com#planet_Barab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albanin> .
<https://starwars.com#planet_Barab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c25f64f7-6c01-4d30-b220-0a52ad216e76> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Barab> <http://www.w3.org/2000/01/rdf-schema#comment> "Barab I, also known simply as Barab, was an irradiated planet in the Outer Rim Territories of the galaxy, connected to Teth and Dubrava via hyperspace routes. It was positioned at the coordinates U-12 on the Standard Galactic Grid and was the homeworld of the Barabel species. " .
<https://starwars.com#01aa6b41-dfd7-4188-a1f2-db2304195f96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

