Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Calus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dddbe7b3-73ea-46de-bf73-1d1df54093c3> .
<https://starwars.com#planet_Calus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Calus> <http://www.w3.org/2000/01/rdf-schema#comment> "Calus was a planet in the Calus system of the Inner Rim, near Bestine IV. Sweet-sand cookies were made on Calus. It was located at the end of Keller's Void, opposite Wroona. " .
<https://starwars.com#planet_Calus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Calus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#planet_Calus> <http://telicent.io/ontology/primaryName> "Calus" .
<https://starwars.com#dddbe7b3-73ea-46de-bf73-1d1df54093c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Calus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dddbe7b3-73ea-46de-bf73-1d1df54093c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

