Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Talcene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#a140e002-59da-4d9e-abd0-1d52d1f0394d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Talcene> <http://telicent.io/ontology/primaryName> "Talcene" .
<https://starwars.com#planet_Orleon> <http://www.w3.org/2000/01/rdf-schema#comment> "Orleon was a rainy planet in the Mid Rim. The rain was torrential and never stopped, leaving the planet covered in mud. " .
<https://starwars.com#planet_Orleon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Talcene> .
<https://starwars.com#sector_Talcene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Orleon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a140e002-59da-4d9e-abd0-1d52d1f0394d> .
<https://starwars.com#planet_Orleon> <http://telicent.io/ontology/primaryName> "Orleon" .
<https://starwars.com#planet_Orleon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Orleon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#a140e002-59da-4d9e-abd0-1d52d1f0394d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orleon"^^<http://www.w3.org/2001/XMLSchema#string> .

