Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#151f91ec-98f2-472c-824b-306e154fef6e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Andooweel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Andooweel> <http://telicent.io/ontology/primaryName> "Andooweel" .
<https://starwars.com#planet_Andooweel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Andooweel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#151f91ec-98f2-472c-824b-306e154fef6e> .
<https://starwars.com#planet_Andooweel> <http://www.w3.org/2000/01/rdf-schema#comment> "Andooweel was a world within the reaches of the galaxy. " .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Andooweel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#151f91ec-98f2-472c-824b-306e154fef6e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Andooweel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .

