Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kabal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mayagil> .
<https://starwars.com#planet_Kabal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Mayagil> <http://telicent.io/ontology/primaryName> "Mayagil" .
<https://starwars.com#planet_Kabal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N18> .
<https://starwars.com#sector_Mayagil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kabal> <http://telicent.io/ontology/primaryName> "Kabal" .
<https://starwars.com#f22f6bc6-e472-4955-b221-06e6def5d17a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kabal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mayagil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kabal> <http://www.w3.org/2000/01/rdf-schema#comment> "Kabal was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#f22f6bc6-e472-4955-b221-06e6def5d17a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kabal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f22f6bc6-e472-4955-b221-06e6def5d17a> .

