Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2be77d72-92cd-46c0-8ca9-9360b6f634c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Baros"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Baros> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Baros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#planet_Baros> <http://telicent.io/ontology/primaryName> "Baros" .
<https://starwars.com#planet_Baros> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2be77d72-92cd-46c0-8ca9-9360b6f634c3> .
<https://starwars.com#planet_Baros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dominus> .
<https://starwars.com#planet_Baros> <http://www.w3.org/2000/01/rdf-schema#comment> "Baros was an astronomical object located in the regions known as the Outer Rim Territories and the Slice. It was positioned in grid square U-7 on the Standard Galactic Grid. " .
<https://starwars.com#2be77d72-92cd-46c0-8ca9-9360b6f634c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dominus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Dominus> <http://telicent.io/ontology/primaryName> "Dominus" .
<https://starwars.com#sector_Dominus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

