Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dra> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Wyl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#e14fbdcd-e18b-405c-9fcd-526d8bac35cb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Wyl> <http://telicent.io/ontology/primaryName> "Wyl" .
<https://starwars.com#planet_Dra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wyl> .
<https://starwars.com#planet_Dra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Wyl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#planet_Dra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e14fbdcd-e18b-405c-9fcd-526d8bac35cb> .
<https://starwars.com#planet_Dra> <http://telicent.io/ontology/primaryName> "Dra" .
<https://starwars.com#e14fbdcd-e18b-405c-9fcd-526d8bac35cb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

