Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Angor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a25ccb32-4b9b-4b44-b54c-5dc392e60514> .
<https://starwars.com#grid_K4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Angor> <http://telicent.io/ontology/primaryName> "Angor" .
<https://starwars.com#a25ccb32-4b9b-4b44-b54c-5dc392e60514> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Angor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#ad914744-882f-4532-8620-d3b2a416531e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Angor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_K4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ad914744-882f-4532-8620-d3b2a416531e> .
<https://starwars.com#ad914744-882f-4532-8620-d3b2a416531e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Angor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#a25ccb32-4b9b-4b44-b54c-5dc392e60514> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Angor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Myto> <http://telicent.io/ontology/primaryName> "Myto" .
<https://starwars.com#grid_K4> <http://telicent.io/ontology/primaryName> "K4" .
<https://starwars.com#sector_Myto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Angor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Myto> .
<https://starwars.com#sector_Myto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

