Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shimia> <http://telicent.io/ontology/primaryName> "Shimia" .
<https://starwars.com#planet_Shimia> <http://www.w3.org/2000/01/rdf-schema#comment> "Shimia was an astronomical object in the galaxy's Outer Rim Territories. It was the homeworld of the Pacithhip female Bok Askol. " .
<https://starwars.com#planet_Shimia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1fd94b01-976f-41ab-8c28-27654ed87adb> .
<https://starwars.com#sector_Dalchon> <http://telicent.io/ontology/primaryName> "Dalchon" .
<https://starwars.com#sector_Dalchon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Dalchon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1fd94b01-976f-41ab-8c28-27654ed87adb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shimia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shimia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#1fd94b01-976f-41ab-8c28-27654ed87adb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shimia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shimia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalchon> .

