Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#202cecab-e46b-44b9-ac17-07c610d50b3a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ch'hodos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Chhodos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Chhodos> <http://telicent.io/ontology/primaryName> "Ch'hodos" .
<https://starwars.com#planet_Chhodos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#202cecab-e46b-44b9-ac17-07c610d50b3a> .
<https://starwars.com#planet_Chhodos> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Dark Lord of the Sith Naga Sadow's preparations to attack the Galactic Republic, Ch'hodos became a rally ground for his Sith soldiers, with Sadow himself and his apprentice, Gav Daragon, overlooking the embarking of the troops. More than a millennium later, the radiation from Ch'hodos's sun had increased, leading to mutations in the local desert wildlife. " .
<https://starwars.com#planet_Chhodos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chhodos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#202cecab-e46b-44b9-ac17-07c610d50b3a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

