Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Marmoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .
<https://starwars.com#planet_Marmoth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b0e1ccf2-89db-4bb3-ba89-d7995b718134> .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Marmoth> <http://www.w3.org/2000/01/rdf-schema#comment> "Marmoth was a planet located in the Albarrio sector of the Outer Rim Territories, and was a part of the Relgim Run. It was one of the ports of call of the luxury liner Kuari Princess. " .
<https://starwars.com#b0e1ccf2-89db-4bb3-ba89-d7995b718134> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Marmoth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#b0e1ccf2-89db-4bb3-ba89-d7995b718134> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Marmoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#planet_Marmoth> <http://telicent.io/ontology/primaryName> "Marmoth" .
<https://starwars.com#planet_Marmoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

