Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aylayl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#8ea3c0d4-c7f9-4440-ad6d-af3f413aab96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aylayl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#8ea3c0d4-c7f9-4440-ad6d-af3f413aab96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aylayl> <http://www.w3.org/2000/01/rdf-schema#comment> "Aylayl was a verdant planet that was located within the Aylayl system of the galaxy's Hutt Space region and lay on the hyperlane called the Hollastin Run, which connected it to the worlds of Hollastin and Tsyk. " .
<https://starwars.com#planet_Aylayl> <http://telicent.io/ontology/primaryName> "Aylayl" .
<https://starwars.com#planet_Aylayl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8ea3c0d4-c7f9-4440-ad6d-af3f413aab96> .
<https://starwars.com#planet_Aylayl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Aylayl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .

