Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_StygeonPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Stygeon Prime, also known simply as Stygeon, was a mountainous, snowy planet located in the Stygeon system of the Outer Rim Territories' Nuiri sector. The world's blizzard conditions made it the perfect location for a prison, as prisoners attempting escape would not survive outside the prison walls unless they could use a Tibidee to fly them to safety. During the Clone Wars, the Sith Lords Darth Tyranus and Darth Sidious imprisoned Sidious's former apprentice Maul in the Spire, a Confederate prison on Stygeon Prime. Maul was later broken out by Mandalorian forces that were part of the Shadow Collective. After the Clone Wars, the planet was occupied by the Galactic Empire. " .
<https://starwars.com#sector_Nuiri> <http://telicent.io/ontology/primaryName> "Nuiri" .
<https://starwars.com#4aae7cb5-60b0-4900-a6e7-507ab5fe9784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_StygeonPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nuiri> .
<https://starwars.com#4aae7cb5-60b0-4900-a6e7-507ab5fe9784> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Stygeon Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_StygeonPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4aae7cb5-60b0-4900-a6e7-507ab5fe9784> .
<https://starwars.com#sector_Nuiri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_StygeonPrime> <http://telicent.io/ontology/primaryName> "Stygeon Prime" .
<https://starwars.com#planet_StygeonPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#planet_StygeonPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Nuiri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

