Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c0f0403c-1c70-4097-91e6-6d2661fca98d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Seline"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Seline> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M3> .
<https://starwars.com#planet_Seline> <http://www.w3.org/2000/01/rdf-schema#comment> "Seline was a remote outpost planet—cold, rocky, harsh and barren—with a Jedi starport, located in the Dalonbian sector of the galaxy's Tingel Arm. " .
<https://starwars.com#planet_Seline> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c0f0403c-1c70-4097-91e6-6d2661fca98d> .
<https://starwars.com#sector_Dalonbian> <http://telicent.io/ontology/primaryName> "Dalonbian" .
<https://starwars.com#planet_Seline> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Dalonbian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#c0f0403c-1c70-4097-91e6-6d2661fca98d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dalonbian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Seline> <http://telicent.io/ontology/primaryName> "Seline" .
<https://starwars.com#planet_Seline> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalonbian> .

