Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0dd9ddd0-b289-45d3-8c58-cddb973c7431> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#4fd306c8-a721-48a0-80f5-3f6e895fc841> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_R3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Aparo> <http://telicent.io/ontology/primaryName> "Aparo" .
<https://starwars.com#planet_Cadomai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Aparo> .
<https://starwars.com#sector_Aparo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_R3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4fd306c8-a721-48a0-80f5-3f6e895fc841> .
<https://starwars.com#planet_Cadomai> <http://www.w3.org/2000/01/rdf-schema#comment> "Cadomai Prime, also known as simply Cadomai, was a planet located in the galaxy's Outer Rim Territories, situated along the Hydian Way that was the homeworld of the Snivvian species. The winters of Cadomai Prime were very harsh for the Snivvians to survive, during which they spent the time in underground caverns in artistic pursuits. Some did escape the icy tundras to become bounty hunters offworld. " .
<https://starwars.com#grid_R3> <http://telicent.io/ontology/primaryName> "R3" .
<https://starwars.com#4fd306c8-a721-48a0-80f5-3f6e895fc841> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_R3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Cadomai> <http://telicent.io/ontology/primaryName> "Cadomai" .
<https://starwars.com#planet_Cadomai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Aparo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cadomai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#planet_Cadomai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0dd9ddd0-b289-45d3-8c58-cddb973c7431> .
<https://starwars.com#0dd9ddd0-b289-45d3-8c58-cddb973c7431> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cadomai"^^<http://www.w3.org/2001/XMLSchema#string> .

