Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Wodan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#21c9dea0-c00e-4173-ae7b-5f0a69ebb861> .
<https://starwars.com#planet_Wodan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#21c9dea0-c00e-4173-ae7b-5f0a69ebb861> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wodan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Wodan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Wodan> <http://telicent.io/ontology/primaryName> "Wodan" .
<https://starwars.com#21c9dea0-c00e-4173-ae7b-5f0a69ebb861> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Wodan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Wodan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .

