Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dd04c250-6dd7-4b69-a263-8d714165de3e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dd04c250-6dd7-4b69-a263-8d714165de3e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lolnar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lolnar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lolnar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd04c250-6dd7-4b69-a263-8d714165de3e> .
<https://starwars.com#planet_Lolnar> <http://telicent.io/ontology/primaryName> "Lolnar" .
<https://starwars.com#planet_Lolnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Lolnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Lolnar> <http://www.w3.org/2000/01/rdf-schema#comment> "Lolnar was a planet in the Core Worlds. Moff Lesan Ramier, commander of the Imperial forces in the Brak sector during the Galactic Civil War, was from Lolnar. " .

