Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#475ac92c-1f5e-4b0d-ae36-b82442e6da93> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Krylon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#475ac92c-1f5e-4b0d-ae36-b82442e6da93> .
<https://starwars.com#planet_Krylon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Krylon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Krylon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#475ac92c-1f5e-4b0d-ae36-b82442e6da93> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Krylon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Krylon> <http://telicent.io/ontology/primaryName> "Krylon" .
<https://starwars.com#planet_Krylon> <http://www.w3.org/2000/01/rdf-schema#comment> "Krylon was a planet in the Gordian Reach. It was the dominant planet of the Pinooran Spur, a polluted, industrial world dominated by Hynese companies, however it was not very important in this region of space. " .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

