Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sneeve> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#planet_Sneeve> <http://www.w3.org/2000/01/rdf-schema#comment> "Sneeve was an astronomical object in the Mid Rim that served as the homeworld of the Sneevel podracer Boles Roor. " .
<https://starwars.com#planet_Sneeve> <http://telicent.io/ontology/primaryName> "Sneeve" .
<https://starwars.com#planet_Sneeve> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5b0d4dfb-e4f6-46bd-be8b-0910ef746350> .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#5b0d4dfb-e4f6-46bd-be8b-0910ef746350> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5b0d4dfb-e4f6-46bd-be8b-0910ef746350> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sneeve"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sneeve> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sneeve> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .

