Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2c874f30-9336-4722-91df-c4a9e0172bb3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Odona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Odona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q17> .
<https://starwars.com#planet_Odona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Odona> <http://telicent.io/ontology/primaryName> "Odona" .
<https://starwars.com#planet_Odona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2c874f30-9336-4722-91df-c4a9e0172bb3> .
<https://starwars.com#2c874f30-9336-4722-91df-c4a9e0172bb3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Odona"^^<http://www.w3.org/2001/XMLSchema#string> .

