Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#47636118-86b8-4913-b899-b57d9ab9fefa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_K16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Balis-Baurgh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#sector_Sombure> <http://telicent.io/ontology/primaryName> "Sombure" .
<https://starwars.com#planet_Balis-Baurgh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sombure> .
<https://starwars.com#grid_K16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#47636118-86b8-4913-b899-b57d9ab9fefa> .
<https://starwars.com#planet_Balis-Baurgh> <http://telicent.io/ontology/primaryName> "Balis-Baurgh" .
<https://starwars.com#a815f88b-330b-4d1a-b6bc-35b54a47835f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sombure> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Sombure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Balis-Baurgh> <http://www.w3.org/2000/01/rdf-schema#comment> "Balis-Baurgh was a planet in the Mid Rim's Balis-Baurgh system and the only planet in the system that could sustain life. " .
<https://starwars.com#47636118-86b8-4913-b899-b57d9ab9fefa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Balis-Baurgh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a815f88b-330b-4d1a-b6bc-35b54a47835f> .
<https://starwars.com#grid_K16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Balis-Baurgh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_K16> <http://telicent.io/ontology/primaryName> "K16" .
<https://starwars.com#a815f88b-330b-4d1a-b6bc-35b54a47835f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Balis-Baurgh"^^<http://www.w3.org/2001/XMLSchema#string> .

