Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pollillus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Pollillus> <http://www.w3.org/2000/01/rdf-schema#comment> "Pollillus was a planet in the galaxy that was the homeworld of the Troig species. The Troig podrace announcer Fodesinbeed Annodue hailed from Pollillus. " .
<https://starwars.com#ba43fd86-9a72-4c06-beec-19ec07a46f80> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pollillus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ba43fd86-9a72-4c06-beec-19ec07a46f80> .
<https://starwars.com#planet_Pollillus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J10> .
<https://starwars.com#planet_Pollillus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pollillus> <http://telicent.io/ontology/primaryName> "Pollillus" .
<https://starwars.com#ba43fd86-9a72-4c06-beec-19ec07a46f80> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pollillus"^^<http://www.w3.org/2001/XMLSchema#string> .

