Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tranthellix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tranthellix> <http://www.w3.org/2000/01/rdf-schema#comment> "Tranthellix was a planet in the Tranthellix system, located in the Tangles of the Senex sector in the Mid Rim. The rugged, mountainous planet was controlled by the Human noble family House Petro. Like many worlds in the Senex-Juvex, House Petro had conquered the planet's native species and consigned them to slavery. " .
<https://starwars.com#187e08c9-1185-47bf-9362-70ead87c60be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tranthellix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#187e08c9-1185-47bf-9362-70ead87c60be> .
<https://starwars.com#planet_Tranthellix> <http://telicent.io/ontology/primaryName> "Tranthellix" .
<https://starwars.com#planet_Tranthellix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#187e08c9-1185-47bf-9362-70ead87c60be> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tranthellix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Tranthellix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .

