Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Barison> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b01e0cf6-3d1a-40f8-85c8-4e8cc007d96c> .
<https://starwars.com#b01e0cf6-3d1a-40f8-85c8-4e8cc007d96c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barison"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b01e0cf6-3d1a-40f8-85c8-4e8cc007d96c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Barison> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Barison> <http://telicent.io/ontology/primaryName> "Barison" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Barison> <http://www.w3.org/2000/01/rdf-schema#comment> "Barison was a water world along the Feena Run in the Gordian Reach. It supplied fish, seafood, and kelp to worlds in the Back Reach. Its inhabitants were known as the Barisoni. For religious reasons, many of the Barisoni had renounced technology. " .
<https://starwars.com#planet_Barison> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Barison> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

