Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Farstey> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Jendorn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#sector_Farstey> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Farstey> <http://telicent.io/ontology/primaryName> "Farstey" .
<https://starwars.com#f8241143-b5fa-4433-b1e6-897923574e79> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jendorn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f8241143-b5fa-4433-b1e6-897923574e79> .
<https://starwars.com#planet_Jendorn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f8241143-b5fa-4433-b1e6-897923574e79> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jendorn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jendorn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Farstey> .
<https://starwars.com#planet_Jendorn> <http://www.w3.org/2000/01/rdf-schema#comment> "After the battle, the Empire occupied the Jendorn city of Bruzion, where captured pilots that had been downed in the confrontation were held prisoner in an Imperial compound. Two members of the New Republic Katarn Commandos unit, Gottu and Idow, were subsequently dispatched on a mission to rescue the pilots. The lightly-armed pair of commandos were successful in their mission, during which Gottu used a vibro-ax to cause the prison compound's turbolaser tower to explode. " .
<https://starwars.com#planet_Jendorn> <http://telicent.io/ontology/primaryName> "Jendorn" .

