Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Crystan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#8272d3ea-728f-4b47-a983-e78b9058f923> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Crystan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Crystan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Crystan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8272d3ea-728f-4b47-a983-e78b9058f923> .
<https://starwars.com#planet_Crystan> <http://www.w3.org/2000/01/rdf-schema#comment> "Crystan was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Crystan> <http://telicent.io/ontology/primaryName> "Crystan" .
<https://starwars.com#planet_Crystan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8272d3ea-728f-4b47-a983-e78b9058f923> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

