Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Denova> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ojoster> .
<https://starwars.com#sector_Ojoster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3403e269-c37a-4e82-8b00-7dbbfc60e5dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Denova"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Denova> <http://telicent.io/ontology/primaryName> "Denova" .
<https://starwars.com#planet_Denova> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Denova> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3403e269-c37a-4e82-8b00-7dbbfc60e5dd> .
<https://starwars.com#3403e269-c37a-4e82-8b00-7dbbfc60e5dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Ojoster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Denova> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#planet_Denova> <http://www.w3.org/2000/01/rdf-schema#comment> "Thus, a Trandoshan group known as the Warstalkers, led by the veteran Kephess, was hired to prevent the world, and the ores, from falling into the hands of the Sith Empire. However, the mercenaries went rogue and formed an alliance with renegade forces within the Imperial Army. " .
<https://starwars.com#sector_Ojoster> <http://telicent.io/ontology/primaryName> "Ojoster" .

