Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shulstine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Shulstine> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Shulstine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#88687d68-cb1d-4648-8345-e5f4554150ec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shulstine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shulstine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Shulstine> <http://telicent.io/ontology/primaryName> "Shulstine" .
<https://starwars.com#planet_Shulstine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#88687d68-cb1d-4648-8345-e5f4554150ec> .
<https://starwars.com#88687d68-cb1d-4648-8345-e5f4554150ec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

