Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_PacanthReach> <http://telicent.io/ontology/primaryName> "Pacanth Reach" .
<https://starwars.com#planet_Panatha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Panatha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4e547271-0b66-412a-bd1b-364ad646f5d0> .
<https://starwars.com#sector_PacanthReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_PacanthReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Panatha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_PacanthReach> .
<https://starwars.com#planet_Panatha> <http://telicent.io/ontology/primaryName> "Panatha" .
<https://starwars.com#4e547271-0b66-412a-bd1b-364ad646f5d0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Panatha> <http://www.w3.org/2000/01/rdf-schema#comment> "Panatha, also known as Epicanthix was a jungle planet in the Pacanth Reach in the Outer Rim Territories. It was the homeworld of the Epicanthix. It was close to the Unknown Regions. " .
<https://starwars.com#4e547271-0b66-412a-bd1b-364ad646f5d0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Panatha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Panatha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .

