Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ec668ca4-3476-4d04-9026-915106b06275> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tovarskl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tovarskl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_Tovarskl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#ec668ca4-3476-4d04-9026-915106b06275> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tovarskl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tovarskl> <http://www.w3.org/2000/01/rdf-schema#comment> "Tovarskl was a terrestrial planet in Wild Space and a colony world of the Yam'rii. " .
<https://starwars.com#planet_Tovarskl> <http://telicent.io/ontology/primaryName> "Tovarskl" .
<https://starwars.com#planet_Tovarskl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ec668ca4-3476-4d04-9026-915106b06275> .

