Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Gaulus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_SmugglersRun> <http://www.w3.org/2000/01/rdf-schema#comment> "The Smuggler's Run was an asteroid belt located in the Outer Rim Territories on the Corellian Run. It was near the planet Wrea. During the Galactic Civil War, Imperial TIEs marked with blue stripes patrolled the Smuggler's Run and intercepted freighters suspected of carrying illicit cargo. Any pilots who didn't submit for Imperial boarding inspection were obliterated immediately. " .
<https://starwars.com#54fabdf6-456e-4331-9ad2-e0789784a74b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SmugglersRun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54fabdf6-456e-4331-9ad2-e0789784a74b> .
<https://starwars.com#planet_SmugglersRun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gaulus> .
<https://starwars.com#planet_SmugglersRun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_SmugglersRun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S18> .
<https://starwars.com#planet_SmugglersRun> <http://telicent.io/ontology/primaryName> "Smuggler's Run" .
<https://starwars.com#54fabdf6-456e-4331-9ad2-e0789784a74b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Smuggler's Run"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Gaulus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Gaulus> <http://telicent.io/ontology/primaryName> "Gaulus" .

