Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pax> <http://telicent.io/ontology/primaryName> "Pax" .
<https://starwars.com#planet_Pax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kira> .
<https://starwars.com#35188583-d959-4a7c-a344-9c5518123893> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pax"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Pax> <http://www.w3.org/2000/01/rdf-schema#comment> "Pax was an astronomical object located in the Expansion Region and the Trailing Sectors regions in grid square N-16 of the Standard Galactic Grid. The hyperspace route known as the Hydian Way linked Pax to the Chardaan system and the celestial body ZeHeth, while another route connected it to the astronomical objects Kira and Vondarc. " .
<https://starwars.com#planet_Pax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#planet_Pax> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#35188583-d959-4a7c-a344-9c5518123893> .
<https://starwars.com#sector_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#35188583-d959-4a7c-a344-9c5518123893> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

