Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Caltinia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#73a34da9-be24-4d60-b47c-3b282b23123f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Caltinia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Caltinia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73a34da9-be24-4d60-b47c-3b282b23123f> .
<https://starwars.com#planet_Caltinia> <http://telicent.io/ontology/primaryName> "Caltinia" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Caltinia> <http://www.w3.org/2000/01/rdf-schema#comment> "Caltinia was the lush Human-inhabited homeworld of House Elegin, famous for its hundreds of dueling fields surrounded by numerous mausoleums, temples, and museums celebrating and mourning epic duels of the past. Caltinia was once visited by Lando Calrissian. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Caltinia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#73a34da9-be24-4d60-b47c-3b282b23123f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Caltinia"^^<http://www.w3.org/2001/XMLSchema#string> .

