Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Retep> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#planet_Retep> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Daimar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Daimar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Retep> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Daimar> .
<https://starwars.com#5201114b-9483-427d-9f93-41a515c2d5da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5201114b-9483-427d-9f93-41a515c2d5da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Retep"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Daimar> <http://telicent.io/ontology/primaryName> "Daimar" .
<https://starwars.com#planet_Retep> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5201114b-9483-427d-9f93-41a515c2d5da> .
<https://starwars.com#planet_Retep> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Retep> <http://telicent.io/ontology/primaryName> "Retep" .

