Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#eb0c5169-8928-4de8-b73f-5317871e34af> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jelucan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eb0c5169-8928-4de8-b73f-5317871e34af> .
<https://starwars.com#planet_Jelucan> <http://www.w3.org/2000/01/rdf-schema#comment> "A rocky, mountainous planet in the Outer Rim, and the homeworld of Thane Kyrell and Ciena Ree." .
<https://starwars.com#planet_Jelucan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kwymar> .
<https://starwars.com#sector_Kwymar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#eb0c5169-8928-4de8-b73f-5317871e34af> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jelucan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kwymar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jelucan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Jelucan> <http://telicent.io/ontology/primaryName> "Jelucan" .
<https://starwars.com#sector_Kwymar> <http://telicent.io/ontology/primaryName> "Kwymar" .
<https://starwars.com#planet_Jelucan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

