Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f2abddc0-02ac-41d6-82fb-985ca9a1bcda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f2abddc0-02ac-41d6-82fb-985ca9a1bcda> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Diyu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Diyu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Diyu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f2abddc0-02ac-41d6-82fb-985ca9a1bcda> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Diyu> <http://telicent.io/ontology/primaryName> "Diyu" .
<https://starwars.com#planet_Diyu> <http://www.w3.org/2000/01/rdf-schema#comment> "Diyu was a planet that was located within the Diyu system of the galaxy's Hutt Space region and lay on the hyperlane called the Shag Pabol, which connected it to the Rorak system and the world of Ylesia. " .
<https://starwars.com#planet_Diyu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Diyu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .

