Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kinooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Kinooine was an astronomical object located in Wild Space, positioned at the coordinates J-21 on the Standard Galactic Grid. " .
<https://starwars.com#c4005a3a-73a4-4318-8abc-37d59d14a8ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kinooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kinooine> <http://telicent.io/ontology/primaryName> "Kinooine" .
<https://starwars.com#planet_Kinooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J21> .
<https://starwars.com#planet_Kinooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c4005a3a-73a4-4318-8abc-37d59d14a8ab> .
<https://starwars.com#c4005a3a-73a4-4318-8abc-37d59d14a8ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kinooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Kinooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

