Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#10ce31f9-a4a7-4819-946b-2e7c9faf890e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arami> <http://www.w3.org/2000/01/rdf-schema#comment> "Arami was an astronomical object located in the regions known as the Outer Rim Territories and the Slice. It was situated in grid square T-13 of the Standard Galactic Grid and lay on the hyperspace route known as the Triellus Trade Route, which linked it to the planet Gamorr and the moon Syvris. " .
<https://starwars.com#a9d5e4dd-b502-4e2c-862d-da4197db72de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a9d5e4dd-b502-4e2c-862d-da4197db72de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arami"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arami> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_T13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Arami> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Galov> .
<https://starwars.com#planet_Arami> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T13> .
<https://starwars.com#sector_Galov> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Arami> <http://telicent.io/ontology/primaryName> "Arami" .
<https://starwars.com#grid_T13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#10ce31f9-a4a7-4819-946b-2e7c9faf890e> .
<https://starwars.com#grid_T13> <http://telicent.io/ontology/primaryName> "T13" .
<https://starwars.com#planet_Arami> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a9d5e4dd-b502-4e2c-862d-da4197db72de> .
<https://starwars.com#10ce31f9-a4a7-4819-946b-2e7c9faf890e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Galov> <http://telicent.io/ontology/primaryName> "Galov" .
<https://starwars.com#grid_T13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Galov> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

