Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Exegol> <http://telicent.io/ontology/primaryName> "Exegol" .
<https://starwars.com#grid_F7> <http://telicent.io/ontology/primaryName> "F7" .
<https://starwars.com#planet_Exegol> <http://www.w3.org/2000/01/rdf-schema#comment> "Exegol (also spelled Ixigul in ancient texts) was a dark desert planet located within the Unknown Regions that, according to legend, was the hidden redoubt world of the Sith. It was occupied by the Sith Lord Darth Sidious and the Sith Eternal by 35 ABY. It was also the birthplace of Supreme Leader Snoke, whom Sidious created to rule the First Order while concealing himself in the shadows. Exegol was used to hide the Final Order, which was a fleet amassed by Sidious and the Sith Eternal, from where they planned to deploy their Star Destroyers and establish a new Sith Empire. Exegol was the site of a battle during the war between the First Order and the Resistance, which saw the defeat of the Sith loyalists." .
<https://starwars.com#add26d42-0710-4cf9-9216-7896966dcb77> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Exegol"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_F7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_F7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#6dd5dcc2-94fc-4063-922d-f9bae9f78709> .
<https://starwars.com#planet_Exegol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F7> .
<https://starwars.com#grid_F7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#add26d42-0710-4cf9-9216-7896966dcb77> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Exegol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#6dd5dcc2-94fc-4063-922d-f9bae9f78709> <http://ies.data.gov.uk/ontology/ies4#representationValue> "F7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6dd5dcc2-94fc-4063-922d-f9bae9f78709> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Exegol> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#add26d42-0710-4cf9-9216-7896966dcb77> .
<https://starwars.com#planet_Exegol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

