Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_T7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#9d08f08d-afba-41e8-aa5a-9b9a8290ef86> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Agon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9d08f08d-afba-41e8-aa5a-9b9a8290ef86> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Agon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Agon> <http://www.w3.org/2000/01/rdf-schema#comment> "Agon was an individual who lived on the planet Ridlay during the time of the Clone Wars. In one of the planet's total eclipses—which occurred every fifty years, bringing with it the appearance of beings that Ridlay's inhabitants believed to be ghosts—the beings instead attacked the inhabitants, driving them from their homes. After Jedi Master Mace Windu and a group of Galactic Republic clone troopers were dispatched to investigate the subsequent lack of communications on Ridlay, Agon was sent to warn them. Shortly after Agon's arrival, the supposed ghosts arrived, and Agon led Windu and the clones to the shelter where the displaced residents were hiding. " .
<https://starwars.com#grid_T7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Agon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_Agon> <http://telicent.io/ontology/primaryName> "Agon" .
<https://starwars.com#grid_T7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#a5ffd7df-ccae-4184-a313-db62cce131d1> .
<https://starwars.com#a5ffd7df-ccae-4184-a313-db62cce131d1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Agon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_Agon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9d08f08d-afba-41e8-aa5a-9b9a8290ef86> .
<https://starwars.com#grid_T7> <http://telicent.io/ontology/primaryName> "T7" .
<https://starwars.com#a5ffd7df-ccae-4184-a313-db62cce131d1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

