Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aquilae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Aquilae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Aquilae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aquilae> <http://telicent.io/ontology/primaryName> "Aquilae" .
<https://starwars.com#planet_Aquilae> <http://www.w3.org/2000/01/rdf-schema#comment> "Aquilae, or Aguilae, could refer to several things: " .
<https://starwars.com#947bb2a9-ed1a-4b8b-bc25-629f77e6423d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#947bb2a9-ed1a-4b8b-bc25-629f77e6423d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aquilae"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#region_Colonies> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#region_Colonies> <http://telicent.io/ontology/primaryName> "Colonies" .
<https://starwars.com#planet_Aquilae> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#947bb2a9-ed1a-4b8b-bc25-629f77e6423d> .
<https://starwars.com#region_Colonies> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

