Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Dufilvian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Algarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dufilvian> .
<https://starwars.com#grid_Q15> <http://telicent.io/ontology/primaryName> "Q15" .
<https://starwars.com#b0c1e02b-9e88-45f2-89cb-97bc647fd798> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#fa78b95a-b5b1-43a2-899e-2a52129e1ce4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Algarian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b0c1e02b-9e88-45f2-89cb-97bc647fd798> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Algarian> <http://telicent.io/ontology/primaryName> "Algarian" .
<https://starwars.com#planet_Algarian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fa78b95a-b5b1-43a2-899e-2a52129e1ce4> .
<https://starwars.com#sector_Dufilvian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b0c1e02b-9e88-45f2-89cb-97bc647fd798> .
<https://starwars.com#planet_Algarian> <http://www.w3.org/2000/01/rdf-schema#comment> "Algarian was a planet in the Mid Rim's Dufilvian sector. It was raided by the Galactic Empire, which was attempting to defeat all Alliance support on-planet. " .
<https://starwars.com#planet_Algarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q15> .
<https://starwars.com#grid_Q15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Dufilvian> <http://telicent.io/ontology/primaryName> "Dufilvian" .
<https://starwars.com#fa78b95a-b5b1-43a2-899e-2a52129e1ce4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Algarian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

