Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yutusk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sertar> .
<https://starwars.com#planet_Yutusk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Yutusk> <http://telicent.io/ontology/primaryName> "Yutusk" .
<https://starwars.com#sector_Sertar> <http://telicent.io/ontology/primaryName> "Sertar" .
<https://starwars.com#sector_Sertar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#de9583e3-3c64-4c10-87ae-c82fa75c0b1f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yutusk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yutusk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sertar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Yutusk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#de9583e3-3c64-4c10-87ae-c82fa75c0b1f> .
<https://starwars.com#planet_Yutusk> <http://www.w3.org/2000/01/rdf-schema#comment> "Yutusk was a temperate backwater planet in the Yutusk system subjugated by the Galactic Empire. It was the homeworld of chef Vimran Trell, whom was conscripted in the Imperial Navy. His parents Tranira Trell and Francill Trell were killed when Imperial forces rounded up and executed suspected Rebel sympathizers on Yutusk. " .
<https://starwars.com#de9583e3-3c64-4c10-87ae-c82fa75c0b1f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

