Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b6b3e59a-250f-4ba1-bcbd-1ec8cf3afb26> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pantolomin> <http://www.w3.org/2000/01/rdf-schema#comment> "Pantolomin was an astronomical object located in the galaxy's Core Worlds. It shared its name with the Pantolomin cruiser, a type of luxury cruiser used by Black Sun. " .
<https://starwars.com#planet_Pantolomin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Pantolomin> <http://telicent.io/ontology/primaryName> "Pantolomin" .
<https://starwars.com#planet_Pantolomin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pantolomin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#b6b3e59a-250f-4ba1-bcbd-1ec8cf3afb26> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pantolomin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pantolomin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b6b3e59a-250f-4ba1-bcbd-1ec8cf3afb26> .

