Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Grumani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Phaegon_III> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#615b8022-ee3c-43ff-89f8-cc8ef60419de> .
<https://starwars.com#planet_Phaegon_III> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#sector_Grumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Phaegon_III> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Grumani> <http://telicent.io/ontology/primaryName> "Grumani" .
<https://starwars.com#planet_Phaegon_III> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Grumani> .
<https://starwars.com#planet_Phaegon_III> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#615b8022-ee3c-43ff-89f8-cc8ef60419de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phaegon_III"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#615b8022-ee3c-43ff-89f8-cc8ef60419de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Phaegon_III> <http://telicent.io/ontology/primaryName> "Phaegon_III" .

