Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2a7bd143-77f3-4929-9916-0fd6f78eea5e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chandrila"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chandrila> <http://www.w3.org/2000/01/rdf-schema#comment> "Homeworld of Mon Mothma, it serves as the first capital of the New Republic. Serene planet known for calm seas and rolling hills." .
<https://starwars.com#planet_Chandrila> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Chandrila> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chandrila> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2a7bd143-77f3-4929-9916-0fd6f78eea5e> .
<https://starwars.com#planet_Chandrila> <http://telicent.io/ontology/primaryName> "Chandrila" .
<https://starwars.com#planet_Chandrila> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#2a7bd143-77f3-4929-9916-0fd6f78eea5e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

