Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ramordia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Majoor> .
<https://starwars.com#planet_Ramordia> <http://telicent.io/ontology/primaryName> "Ramordia" .
<https://starwars.com#sector_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Ramordia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4cbb34fd-935b-4b60-bd2e-b760240c7e7e> .
<https://starwars.com#planet_Ramordia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#4cbb34fd-935b-4b60-bd2e-b760240c7e7e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ramordia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#4cbb34fd-935b-4b60-bd2e-b760240c7e7e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ramordia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ramordia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Majoor> <http://telicent.io/ontology/primaryName> "Majoor" .
<https://starwars.com#sector_Majoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

