Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shalam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_Shalam> <http://www.w3.org/2000/01/rdf-schema#comment> "Shalam was a planet bombarded by the Emperor's Disciple under Ishin-Il-Raz during the height of the Galactic Empire. " .
<https://starwars.com#planet_Shalam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a525168d-e716-4979-8dcc-a135b86fd140> .
<https://starwars.com#planet_Shalam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shalam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#a525168d-e716-4979-8dcc-a135b86fd140> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shalam> <http://telicent.io/ontology/primaryName> "Shalam" .
<https://starwars.com#a525168d-e716-4979-8dcc-a135b86fd140> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shalam"^^<http://www.w3.org/2001/XMLSchema#string> .

