Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Soullex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P3> .
<https://starwars.com#planet_Soullex> <http://telicent.io/ontology/primaryName> "Soullex" .
<https://starwars.com#9afd7a3c-bb07-4c84-a2a7-e9bd31d8cf0d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Soullex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Soullex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corva> .
<https://starwars.com#9afd7a3c-bb07-4c84-a2a7-e9bd31d8cf0d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Soullex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Soullex> <http://www.w3.org/2000/01/rdf-schema#comment> "Soullex was a Wild Space planet in the Fardon system near the Oplovis sector. After the Battle of Tantive V, it was garrisoned as the headquarters of Fleet Admiral Gaen Drommel. Drommel was betrayed and killed by Colonel Niovi, who surrendered the Guardian to the New Republic. " .
<https://starwars.com#sector_Corva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Corva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Soullex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9afd7a3c-bb07-4c84-a2a7-e9bd31d8cf0d> .
<https://starwars.com#sector_Corva> <http://telicent.io/ontology/primaryName> "Corva" .

