Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Grumani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Grumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Darkknell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#04410dd0-e663-4004-a13a-aefeb3534175> .
<https://starwars.com#04410dd0-e663-4004-a13a-aefeb3534175> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Darkknell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Grumani> <http://telicent.io/ontology/primaryName> "Grumani" .
<https://starwars.com#planet_Darkknell> <http://telicent.io/ontology/primaryName> "Darkknell" .
<https://starwars.com#planet_Darkknell> <http://www.w3.org/2000/01/rdf-schema#comment> "Darkknell was an astronomical object located in the Darkknell system of the galaxy's Outer Rim Territories, situated along the Hydian Way at grid coordinates M-17. The Rebel Alliance intelligence officer Cassian Jeron Andor acted under the alias 'Aach' as a senatorial contact on Darkknell. " .
<https://starwars.com#planet_Darkknell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Grumani> .
<https://starwars.com#04410dd0-e663-4004-a13a-aefeb3534175> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Darkknell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_Darkknell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

