Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Immalia> <http://telicent.io/ontology/primaryName> "Immalia" .
<https://starwars.com#planet_Immalia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a0191d2-a68a-46a5-8c54-b81185c6416b> .
<https://starwars.com#6a0191d2-a68a-46a5-8c54-b81185c6416b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Immalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Immalia> <http://www.w3.org/2000/01/rdf-schema#comment> "Millennia later, the astronomical object was the site of fighting between Galactic Empire and Rebel Alliance forces. When the Alliance force noticed an Imperial squad donning radiation zone assault trooper armor, the Rebels incorrectly assumed they were fighting in a radioactive area and retreated. " .
<https://starwars.com#planet_Immalia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6a0191d2-a68a-46a5-8c54-b81185c6416b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Immalia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Immalia> <http://telicent.io/ontology/primaryName> "Immalia" .
<https://starwars.com#sector_Immalia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Immalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#planet_Immalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Immalia> .

