Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e560f041-5b2d-4718-af4d-6704ae664230> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Seelos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#e560f041-5b2d-4718-af4d-6704ae664230> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Seelos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kwymar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Seelos> <http://telicent.io/ontology/primaryName> "Seelos" .
<https://starwars.com#sector_Kwymar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Seelos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e560f041-5b2d-4718-af4d-6704ae664230> .
<https://starwars.com#planet_Seelos> <http://www.w3.org/2000/01/rdf-schema#comment> "Seelos was a remote desert planet in the star system of the same name in the Kwymar sector of the Outer Rim Territories. Once considered a prospective mining world, by the Age of the Empire all attempts at settlement and exploitation had been abandoned, in part due to the deadly joopa worms living under the surface of the vast salt plains. Seelos was largely uninhabited, though there were isolated settlements of outlaws at the foot of the mountains, as well as retired clone troopers Rex, Wolffe, and Gregor. " .
<https://starwars.com#sector_Kwymar> <http://telicent.io/ontology/primaryName> "Kwymar" .
<https://starwars.com#planet_Seelos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kwymar> .
<https://starwars.com#planet_Seelos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

