Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2c22c551-c89b-4299-b4e7-6c9636124bb4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Biitu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Biitu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Biitu> <http://www.w3.org/2000/01/rdf-schema#comment> "Biitu was the Biituian homeworld in the Cassandran Worlds region. " .
<https://starwars.com#planet_Biitu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_Biitu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2c22c551-c89b-4299-b4e7-6c9636124bb4> .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Biitu> <http://telicent.io/ontology/primaryName> "Biitu" .
<https://starwars.com#2c22c551-c89b-4299-b4e7-6c9636124bb4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Biitu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .

