Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Glade> <http://www.w3.org/2000/01/rdf-schema#comment> "Glade was a planet in the Gordian Reach. It was a polluted industrial world plagued by acidic rains that rusted machinery within weeks. " .
<https://starwars.com#c676f61d-eea6-4557-af42-af17d2e48618> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Glade"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Glade> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#c676f61d-eea6-4557-af42-af17d2e48618> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Glade> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c676f61d-eea6-4557-af42-af17d2e48618> .
<https://starwars.com#planet_Glade> <http://telicent.io/ontology/primaryName> "Glade" .
<https://starwars.com#planet_Glade> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Glade> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .

