Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Meastrinnar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Meastrinnar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1e330423-c20f-4df1-9c56-27c2586282a6> .
<https://starwars.com#planet_Meastrinnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Meastrinnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#1e330423-c20f-4df1-9c56-27c2586282a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Meastrinnar> <http://telicent.io/ontology/primaryName> "Meastrinnar" .
<https://starwars.com#planet_Meastrinnar> <http://www.w3.org/2000/01/rdf-schema#comment> "Meastrinnar was a planet that was subject to a pacification campaign by the Galactic Empire during the Galactic Civil War as a result of an insurgency against Imperial authority on the planet. During this period in Meastrinnar's history, a squad of stormtroopers led by Vin Northal attacked an orphanage while mistakenly believing that it was the headquarters of a cell of spies affiliated with the Alliance to Restore the Republic due to faulty intelligence provided by the Imperial Security Bureau. The stormtroopers killed many children in their sleep, and though the planet's media networks hailed the raid as a 'military victory' and Northal was congratulated by his superiors, the incident ultimately led him to leave the Imperial military to join the Alliance. " .
<https://starwars.com#1e330423-c20f-4df1-9c56-27c2586282a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Meastrinnar"^^<http://www.w3.org/2001/XMLSchema#string> .

