Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_U10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Bheriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U10> .
<https://starwars.com#grid_U10> <http://telicent.io/ontology/primaryName> "U10" .
<https://starwars.com#47e0268f-3a7a-4873-bde7-d5f0d9935608> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#9b5c8e0c-6868-40b4-83f6-6328cb35ce6e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9b5c8e0c-6868-40b4-83f6-6328cb35ce6e> .
<https://starwars.com#sector_Bheriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Bheriz> <http://telicent.io/ontology/primaryName> "Bheriz" .
<https://starwars.com#grid_U10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#9b5c8e0c-6868-40b4-83f6-6328cb35ce6e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Bheriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bheriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bheriz> .
<https://starwars.com#planet_Bheriz> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#47e0268f-3a7a-4873-bde7-d5f0d9935608> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bheriz"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bheriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bheriz> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#47e0268f-3a7a-4873-bde7-d5f0d9935608> .
<https://starwars.com#planet_Bheriz> <http://telicent.io/ontology/primaryName> "Bheriz" .

