Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Quesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Quesh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Quesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Quesh> <http://telicent.io/ontology/primaryName> "Quesh" .
<https://starwars.com#2fef59ae-c46d-4b7c-ba1d-8b6f57a22bfc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quesh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Quesh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2fef59ae-c46d-4b7c-ba1d-8b6f57a22bfc> .
<https://starwars.com#2fef59ae-c46d-4b7c-ba1d-8b6f57a22bfc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Quesh> <http://www.w3.org/2000/01/rdf-schema#comment> "Queshː (pronounciation: /'kwɛʃ/) was a world riddled with toxic waste within Hutt Space, due to a period of geological instability in the past dubbed the Quake. It was discovered by the Galactic Republic during the Great War, but was promptly abandoned due to its poisonous atmosphere. " .

