Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_K12> <http://telicent.io/ontology/primaryName> "K12" .
<https://starwars.com#89997f9f-c76b-40a0-99b2-ff579b34ef57> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Botor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Botor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89997f9f-c76b-40a0-99b2-ff579b34ef57> .
<https://starwars.com#0a7b310b-5b7e-4fea-9d0e-58baf2a718a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Botor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#grid_K12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0a7b310b-5b7e-4fea-9d0e-58baf2a718a4> .
<https://starwars.com#planet_Botor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Botor> <http://telicent.io/ontology/primaryName> "Botor" .
<https://starwars.com#89997f9f-c76b-40a0-99b2-ff579b34ef57> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0a7b310b-5b7e-4fea-9d0e-58baf2a718a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Botor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Botor> <http://www.w3.org/2000/01/rdf-schema#comment> "Botor was a planet located in the galaxy's Core Worlds that was home to the pirate faction known as the Flesh Mongers during the Republic Era. The youngling Lo was from Botor. " .
<https://starwars.com#grid_K12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

