Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dilbana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#planet_Dilbana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0f2b581-c802-473f-a218-e9c49c54e16c> .
<https://starwars.com#a0f2b581-c802-473f-a218-e9c49c54e16c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a0f2b581-c802-473f-a218-e9c49c54e16c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dilbana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dilbana> <http://www.w3.org/2000/01/rdf-schema#comment> "Dilbana was a planet in the Baxel sector of the Outer Rim. Located along the Triellus Trade Route, the planet was under a de facto rulership overseen by Jiliac Desilijic Tiron. This form of rule ended with the Hutt Lord's death at the hands of Durga Besadii Tai. " .
<https://starwars.com#planet_Dilbana> <http://telicent.io/ontology/primaryName> "Dilbana" .
<https://starwars.com#planet_Dilbana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .
<https://starwars.com#planet_Dilbana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .

