Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ottabesk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Ottabesk> <http://www.w3.org/2000/01/rdf-schema#comment> "Ottabesk was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Ottabesk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#201fd551-1aad-46cf-afda-57ed88eef6f2> .
<https://starwars.com#planet_Ottabesk> <http://telicent.io/ontology/primaryName> "Ottabesk" .
<https://starwars.com#planet_Ottabesk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ottabesk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#201fd551-1aad-46cf-afda-57ed88eef6f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ottabesk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#201fd551-1aad-46cf-afda-57ed88eef6f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

