Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Korriz> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca1cfae7-01f2-4843-9809-bb6759789751> .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Korriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Korriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#ca1cfae7-01f2-4843-9809-bb6759789751> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korriz"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Korriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Korriz> <http://www.w3.org/2000/01/rdf-schema#comment> "Korriz was an industrial planet in the Korriz system in the Sith Worlds, a region of space within the Stygian Caldera nebula in the Outer Rim's Esstran sector. Located on the Descri Wris hyperlane, Korriz was part of the Sith Empire before its collapse in the Great Hyperspace War of 5000 BBY, and around that time, it was the site of a workshop owned by the Sith Lord Tritos Nal. Agents of the Sith Lord known as the Patron went to Korriz in order to steal Garu's Warblade, a Sith sword that Tritos Nal had made for the Sith Lord Garu, and they successfully stole the weapon despite the efforts of Garu's agents to stop them. Korriz became a part of the reconstituted Empire by the time of the Cold War between the Empire and the Galactic Republic, when an Imperial cargo ship was diverted from its flight plan by pirates after departing Korriz. " .
<https://starwars.com#ca1cfae7-01f2-4843-9809-bb6759789751> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Korriz> <http://telicent.io/ontology/primaryName> "Korriz" .

