Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chamble> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#planet_Chamble> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f0220d46-90cb-4fdb-bc6e-9c3c93fb73ad> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Chamble> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chamble> <http://telicent.io/ontology/primaryName> "Chamble" .
<https://starwars.com#f0220d46-90cb-4fdb-bc6e-9c3c93fb73ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f0220d46-90cb-4fdb-bc6e-9c3c93fb73ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chamble"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Chamble> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#planet_Chamble> <http://www.w3.org/2000/01/rdf-schema#comment> "Chamble was a planet in the Mid Rim where Bansche Tech was headquartered. After the Battle of Yavin, the corporation was nationalized by the Empire, dealing a heavy blow to the Ralltiir Exchange. " .

