Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#506d7130-e85f-4e23-84ff-8f2ccff0b85b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ilos Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_IlosMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Ilos Minor was a planet that was located within the Ilos Minor system of the galaxy's Hutt Space region and lay on the hyperlane called the Pabol Sleheyron, which connected it to the planets of Ilos and Nar Kreeta. Another hyperspace route called the Ilosian Spur linked Ilos Minor to the world of Tal Nami. Ilos Minor was colonized by the sentient Ilosian species and served as a transfer point for goods that were transported from the planets of the Ilosian Spur. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_IlosMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#506d7130-e85f-4e23-84ff-8f2ccff0b85b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_IlosMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#506d7130-e85f-4e23-84ff-8f2ccff0b85b> .
<https://starwars.com#planet_IlosMinor> <http://telicent.io/ontology/primaryName> "Ilos Minor" .
<https://starwars.com#planet_IlosMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_IlosMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R10> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

