Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ques> <http://www.w3.org/2000/01/rdf-schema#comment> "Ques was a swampy planet near the inner border of Hutt Space, and its population primarily consisted of scavengers, such as Dec Hansen. The axton-tarsier, the ferin, the slime crab, and the Snarlap were creatures native to Ques. A school named teacher's cabin was located on Ques. " .
<https://starwars.com#planet_Ques> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Ques> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ques> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Ques> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#10473122-8c5e-4b9d-ba54-7e3540e3ff25> .
<https://starwars.com#planet_Ques> <http://telicent.io/ontology/primaryName> "Ques" .
<https://starwars.com#10473122-8c5e-4b9d-ba54-7e3540e3ff25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#10473122-8c5e-4b9d-ba54-7e3540e3ff25> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ques"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

