Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Talcene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Talcene> <http://telicent.io/ontology/primaryName> "Talcene" .
<https://starwars.com#sector_Talcene> <http://telicent.io/ontology/primaryName> "Talcene" .
<https://starwars.com#planet_Talcene> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31c42b9b-3c0d-419f-b13c-9c6fc3d94dce> .
<https://starwars.com#sector_Talcene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#31c42b9b-3c0d-419f-b13c-9c6fc3d94dce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Talcene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Talcene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#planet_Talcene> <http://www.w3.org/2000/01/rdf-schema#comment> "Talcene was a planet located along the Perlemian Trade Route. It was the homeworld of Shea Hublin and a world with notoriously competitive commerce guilds. " .
<https://starwars.com#31c42b9b-3c0d-419f-b13c-9c6fc3d94dce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Talcene"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Talcene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Talcene> .

