Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7ccced62-30a1-4c07-8d9e-4e69ebe7f778> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kabray"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kabray> <http://telicent.io/ontology/primaryName> "Kabray" .
<https://starwars.com#planet_Kabray> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corweillian> .
<https://starwars.com#planet_Kabray> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kabray> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#7ccced62-30a1-4c07-8d9e-4e69ebe7f778> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Corweillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kabray> <http://www.w3.org/2000/01/rdf-schema#comment> "Kabray was a Mid Rim forest world orbited by the Kabray Station, a neutral meeting place for diplomats from all over the galaxy. " .
<https://starwars.com#sector_Corweillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Corweillian> <http://telicent.io/ontology/primaryName> "Corweillian" .
<https://starwars.com#planet_Kabray> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7ccced62-30a1-4c07-8d9e-4e69ebe7f778> .

