Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ordo> <http://telicent.io/ontology/primaryName> "Ordo" .
<https://starwars.com#planet_Ordo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mandalore> .
<https://starwars.com#sector_Mandalore> <http://telicent.io/ontology/primaryName> "Mandalore" .
<https://starwars.com#planet_Ordo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d97ed14d-4e99-44f9-84d3-a1f940b0d185> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ordo> <http://www.w3.org/2000/01/rdf-schema#comment> "During the reign of the Galactic Empire, crime lord Dryden Vos of the Crimson Dawn syndicate had the rally master lance stolen for his private collection. For a while, Ordo suspected the people of Krownest―a fellow Mandalorian-inhabited world―of the artifact's theft, though the Scabbard Monument of Krownest had also found itself burglarized by Dryden Vos around the same time. " .
<https://starwars.com#d97ed14d-4e99-44f9-84d3-a1f940b0d185> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ordo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ordo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d97ed14d-4e99-44f9-84d3-a1f940b0d185> .
<https://starwars.com#planet_Ordo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#sector_Mandalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

