Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2da45dbf-d2a4-4e81-abc8-62c0df88d2ce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Feenix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Feenix> <http://telicent.io/ontology/primaryName> "Feenix" .
<https://starwars.com#planet_Feenix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2da45dbf-d2a4-4e81-abc8-62c0df88d2ce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_DAelgoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Feenix> <http://www.w3.org/2000/01/rdf-schema#comment> "Feenix was a planet represented by Senator Tanner Cadaman in the Galactic Senate of the Galactic Republic until he was arrested one day after the formation of the Galactic Empire. " .
<https://starwars.com#sector_DAelgoth> <http://telicent.io/ontology/primaryName> "D'Aelgoth" .
<https://starwars.com#planet_Feenix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAelgoth> .
<https://starwars.com#sector_DAelgoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Feenix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2da45dbf-d2a4-4e81-abc8-62c0df88d2ce> .
<https://starwars.com#planet_Feenix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .

