Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8b93fb7f-cf96-4f4c-b3fc-9875659bbac7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zolan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zolan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P16> .
<https://starwars.com#planet_Zolan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Lambda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Lambda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zolan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lambda> .
<https://starwars.com#planet_Zolan> <http://www.w3.org/2000/01/rdf-schema#comment> "Zolan was a warm and arid planet located in the galaxy's Mid Rim, near the Corellian Run. At some point, during the development of Zolan's native Clawdite species, a spike in solar activity bathed the planet in radiation. The Clawdite's ability to modify their skin color and body shape, similar to the predatory monzu also native to the world, resulted from this spike in solar activity, and many of the other native species developed different ways to survive. However, many other species were unable to cope and went extinct. " .
<https://starwars.com#8b93fb7f-cf96-4f4c-b3fc-9875659bbac7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zolan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8b93fb7f-cf96-4f4c-b3fc-9875659bbac7> .
<https://starwars.com#planet_Zolan> <http://telicent.io/ontology/primaryName> "Zolan" .
<https://starwars.com#sector_Lambda> <http://telicent.io/ontology/primaryName> "Lambda" .

