Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Natalon> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#dc45dbf3-810c-4550-a14e-edae049d2ff9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Natalon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dc45dbf3-810c-4550-a14e-edae049d2ff9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Natalon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_PirynSHar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Natalon> <http://telicent.io/ontology/primaryName> "Natalon" .
<https://starwars.com#sector_PirynSHar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Natalon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_PirynSHar> .
<https://starwars.com#planet_Natalon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#planet_Natalon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dc45dbf3-810c-4550-a14e-edae049d2ff9> .
<https://starwars.com#sector_PirynSHar> <http://telicent.io/ontology/primaryName> "Piryn SHar" .

