Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#631df9d9-8350-4341-8753-eeeb85f4d720> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bonnyuw-Luq> <http://telicent.io/ontology/primaryName> "Bon'nyuw-Luq" .
<https://starwars.com#planet_Arbra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c39950e-282f-4427-81bf-d1c83b4ec4b6> .
<https://starwars.com#grid_N17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#631df9d9-8350-4341-8753-eeeb85f4d720> .
<https://starwars.com#planet_Arbra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Arbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#planet_Arbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bonnyuw-Luq> .
<https://starwars.com#grid_N17> <http://telicent.io/ontology/primaryName> "N17" .
<https://starwars.com#grid_N17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#3c39950e-282f-4427-81bf-d1c83b4ec4b6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Bonnyuw-Luq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3c39950e-282f-4427-81bf-d1c83b4ec4b6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arbra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arbra> <http://www.w3.org/2000/01/rdf-schema#comment> "Arbra was a planet covered in woodlands that was located in the Bon'nyuw-Luq sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#631df9d9-8350-4341-8753-eeeb85f4d720> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Bonnyuw-Luq> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_N17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Arbra> <http://telicent.io/ontology/primaryName> "Arbra" .

