Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Anobis> <http://www.w3.org/2000/01/rdf-schema#comment> "Anobis was a terrestrial planet located into the Anobis system of the Bright Jewel sector in the Mid Rim Territories. It was located near Ord Mantell and was primarily known as an agriworld and a mining colony, providing major foodstuffs to the nearby and more distant star systems. " .
<https://starwars.com#planet_Anobis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Anobis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#af65b8fe-c477-464c-a4af-c3643dfe6aa3> .
<https://starwars.com#planet_Anobis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#af65b8fe-c477-464c-a4af-c3643dfe6aa3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .
<https://starwars.com#planet_Anobis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#planet_Anobis> <http://telicent.io/ontology/primaryName> "Anobis" .
<https://starwars.com#af65b8fe-c477-464c-a4af-c3643dfe6aa3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anobis"^^<http://www.w3.org/2001/XMLSchema#string> .

