Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tantive> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Tantive> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d05b76a3-1c80-4d71-b955-4233bfeb5d88> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tantive"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kwymar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tantive> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kwymar> .
<https://starwars.com#sector_Kwymar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d05b76a3-1c80-4d71-b955-4233bfeb5d88> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tantive> <http://telicent.io/ontology/primaryName> "Tantive" .
<https://starwars.com#planet_Tantive> <http://www.w3.org/2000/01/rdf-schema#comment> "The Tantive system (pronounced /ˈtæntɪˌvi/) contained the planets Tantive IV and Tantive V. In honor of diplomats from Tantive IV who visited Alderaan, the Star of Alderaan was renamed Tantive IV." .
<https://starwars.com#planet_Tantive> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d05b76a3-1c80-4d71-b955-4233bfeb5d88> .
<https://starwars.com#sector_Kwymar> <http://telicent.io/ontology/primaryName> "Kwymar" .

