Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#faa5dd20-42f4-45d6-b022-e0e3653c280b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Herzob> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Herzob> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Herzob> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#faa5dd20-42f4-45d6-b022-e0e3653c280b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Herzob"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Herzob> <http://telicent.io/ontology/primaryName> "Herzob" .
<https://starwars.com#planet_Herzob> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#faa5dd20-42f4-45d6-b022-e0e3653c280b> .
<https://starwars.com#planet_Herzob> <http://www.w3.org/2000/01/rdf-schema#comment> "Herzob was an agriworld in the Colonies. It exported grains to several worlds in the Galactic Core and Mid Rim. The planet was infested with jevesects, which tore through the planet-spanning farms. " .

