Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#884d4c7b-3f71-48b2-9b65-798909a3bc49> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Rentor> <http://telicent.io/ontology/primaryName> "Rentor" .
<https://starwars.com#planet_Rentor> <http://www.w3.org/2000/01/rdf-schema#comment> "Rentor was a planet of the Chiss Ascendancy, situated near the capital of Csilla. It was the homeworld of at least one branch of the Kivu family, including Kivu'raw'nuru, later known as Mitth'raw'nuruodo.  There was also an academy on the planet which Vurawn attended. " .
<https://starwars.com#884d4c7b-3f71-48b2-9b65-798909a3bc49> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rentor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Rentor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rentor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Rentor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#884d4c7b-3f71-48b2-9b65-798909a3bc49> .
<https://starwars.com#planet_Rentor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .

