Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1fce49b4-acfc-4e41-825d-7cb3b947ffb6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Koradin> <http://telicent.io/ontology/primaryName> "Koradin" .
<https://starwars.com#sector_Koradin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#1fce49b4-acfc-4e41-825d-7cb3b947ffb6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Koradin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_I18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Coveway> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#83d3195f-d3c5-4af5-aa07-8447ae7ed255> .
<https://starwars.com#planet_Coveway> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Koradin> .
<https://starwars.com#planet_Coveway> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Galactic Civil War, the Empire established a hidden garrison on Coveway. The commander of the garrison decided that his assignment would be achieved best if the native residents of the local area were eliminated, and Bremen's village was destroyed, with his wife and daughter being killed. The constable, who was away at the time, tracked the killers to the garrison and eventually helped a recently arrived Rebel Alliance strike team to neutralize the Imperial base. In return, the Rebels took Bremen off-world, and he became a member of the Alliance. " .
<https://starwars.com#grid_I18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_I18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1fce49b4-acfc-4e41-825d-7cb3b947ffb6> .
<https://starwars.com#83d3195f-d3c5-4af5-aa07-8447ae7ed255> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Coveway"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Coveway> <http://telicent.io/ontology/primaryName> "Coveway" .
<https://starwars.com#planet_Coveway> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I18> .
<https://starwars.com#planet_Coveway> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#83d3195f-d3c5-4af5-aa07-8447ae7ed255> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_I18> <http://telicent.io/ontology/primaryName> "I18" .

