Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Borosk> <http://telicent.io/ontology/primaryName> "Borosk" .
<https://starwars.com#planet_Borosk> <http://www.w3.org/2000/01/rdf-schema#comment> "Borosk was an astronomical object located in the Prefsbelt sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Borosk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f66b1a01-4803-4cf0-bdd8-9b12cd82bb87> .
<https://starwars.com#planet_Borosk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#f66b1a01-4803-4cf0-bdd8-9b12cd82bb87> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Borosk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prefsbelt> .
<https://starwars.com#sector_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .
<https://starwars.com#f66b1a01-4803-4cf0-bdd8-9b12cd82bb87> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Borosk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Borosk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

