Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#39d6d192-f79c-4bde-8d22-6a73f4596b57> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L2> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Gree> <http://telicent.io/ontology/primaryName> "Gree" .
<https://starwars.com#sector_Gree> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#10cb7488-fe59-4d1e-8e37-5483b41e71ee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L2> <http://telicent.io/ontology/primaryName> "L2" .
<https://starwars.com#sector_Gree> <http://telicent.io/ontology/primaryName> "Gree" .
<https://starwars.com#39d6d192-f79c-4bde-8d22-6a73f4596b57> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L2"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L2> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#39d6d192-f79c-4bde-8d22-6a73f4596b57> .
<https://starwars.com#planet_Gree> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#10cb7488-fe59-4d1e-8e37-5483b41e71ee> .
<https://starwars.com#grid_L2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Gree> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#10cb7488-fe59-4d1e-8e37-5483b41e71ee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gree"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gree> <http://www.w3.org/2000/01/rdf-schema#comment> "Gree was an astronomical object located in the galaxy's Outer Rim Territories, in the grid square L-2 of the Standard Galactic Grid. " .
<https://starwars.com#planet_Gree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gree> .
<https://starwars.com#planet_Gree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L2> .
<https://starwars.com#sector_Gree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

