Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cdcc0ac0-4be0-424f-8a4d-892ff71d8091> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Itopol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_LlonNebulae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_LlonNebulae> <http://www.w3.org/2000/01/rdf-schema#comment> "The Llon Nebulae, located in the Expansion Region, was the site of the Battle of the Llon Nebulae, where the Storm Fleet incurred some losses. " .
<https://starwars.com#planet_LlonNebulae> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cdcc0ac0-4be0-424f-8a4d-892ff71d8091> .
<https://starwars.com#sector_Itopol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_LlonNebulae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K15> .
<https://starwars.com#planet_LlonNebulae> <http://telicent.io/ontology/primaryName> "Llon Nebulae" .
<https://starwars.com#planet_LlonNebulae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Itopol> .
<https://starwars.com#sector_Itopol> <http://telicent.io/ontology/primaryName> "Itopol" .
<https://starwars.com#cdcc0ac0-4be0-424f-8a4d-892ff71d8091> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Llon Nebulae"^^<http://www.w3.org/2001/XMLSchema#string> .

