Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Irith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Irith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#aec74fe8-d091-4e75-a4ce-fd016f69efda> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Irith"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Irith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#aec74fe8-d091-4e75-a4ce-fd016f69efda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Irith> <http://www.w3.org/2000/01/rdf-schema#comment> "Irith was a polluted, motley and overcrowded planet located in the Irith system of Hutt Space, a region of the galaxy controlled by the Hutt species. The world was a stop on the Ootmian Pabol, a hyperlane that ran through the Hutt controlled area and connected Irith to the planets Du Hutta abd Nar Bo Sholla. Irith was the homeworld of the criminal Romort Raort, and while growing up there he acted as a bully, stealing other childrens' lunch money. " .
<https://starwars.com#planet_Irith> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aec74fe8-d091-4e75-a4ce-fd016f69efda> .
<https://starwars.com#planet_Irith> <http://telicent.io/ontology/primaryName> "Irith" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

