Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bettel> <http://www.w3.org/2000/01/rdf-schema#comment> "Bettel was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#f5419ebb-b017-4b1c-9508-843e7a839641> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bettel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bettel> <http://telicent.io/ontology/primaryName> "Bettel" .
<https://starwars.com#planet_Bettel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .
<https://starwars.com#planet_Bettel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f5419ebb-b017-4b1c-9508-843e7a839641> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bettel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Bettel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f5419ebb-b017-4b1c-9508-843e7a839641> .

