Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kailor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kailor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#531a4134-766c-45dc-86ad-77fa7213366b> .
<https://starwars.com#531a4134-766c-45dc-86ad-77fa7213366b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kailor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kailor> <http://telicent.io/ontology/primaryName> "Kailor" .
<https://starwars.com#531a4134-766c-45dc-86ad-77fa7213366b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kailor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Kailor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Kailor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

