Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Delle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Delle> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Delle> <http://telicent.io/ontology/primaryName> "Delle" .
<https://starwars.com#planet_Delle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Delle> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b61f6423-2954-429b-92dc-50af500e9381> .
<https://starwars.com#b61f6423-2954-429b-92dc-50af500e9381> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Delle"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b61f6423-2954-429b-92dc-50af500e9381> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Delle> <http://www.w3.org/2000/01/rdf-schema#comment> "Delle was a planet located along the Perlemian Trade Route. " .

