Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Spintir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Spintir> <http://www.w3.org/2000/01/rdf-schema#comment> "Spintir was a planet that was home to an unusually high number of mammals. " .
<https://starwars.com#planet_Spintir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Spintir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Spintir> <http://telicent.io/ontology/primaryName> "Spintir" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b03cb887-084e-48e8-bfbb-86413ce229ed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Spintir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b03cb887-084e-48e8-bfbb-86413ce229ed> .
<https://starwars.com#b03cb887-084e-48e8-bfbb-86413ce229ed> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Spintir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

