Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ukio> <http://telicent.io/ontology/primaryName> "Ukio" .
<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ukio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#planet_Ukio> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a258c6b9-50a4-4dc8-8824-505de6760d23> .
<https://starwars.com#planet_Ukio> <http://www.w3.org/2000/01/rdf-schema#comment> "Ukio was a bountiful agrarian planet located in the Abrion sector of the galaxy's Outer Rim Territories, connected by hyperlane to Rishi and Molavar. Its native inhabitants were the Ukians. During the last decades of the Galactic Republic, Ukio acted as a breadbasket of the Core Worlds and overall Republic. However, during the Secessionist Movement, the Ukians began to resent the Republic for not helping them enough. Eventually, Ukio joined the Confederacy of Independent Systems. " .
<https://starwars.com#a258c6b9-50a4-4dc8-8824-505de6760d23> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ukio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a258c6b9-50a4-4dc8-8824-505de6760d23> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ukio"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ukio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .

