Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#005b4211-6b44-4bad-8016-b1e29860b0af> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ool> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ool> <http://www.w3.org/2000/01/rdf-schema#comment> "Ool was a terrestrial planet within the territory of the Chiss Ascendancy in the Unknown Regions. " .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Ool> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#005b4211-6b44-4bad-8016-b1e29860b0af> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ool"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ool> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .
<https://starwars.com#planet_Ool> <http://telicent.io/ontology/primaryName> "Ool" .
<https://starwars.com#planet_Ool> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#005b4211-6b44-4bad-8016-b1e29860b0af> .

