Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Nilgaard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Toola> <http://www.w3.org/2000/01/rdf-schema#comment> "Toola was a frigid planet located in the galaxy's Outer Rim Territories that was the homeworld of both the sentient Whiphid species and massive beast of burden known as mastmots. The Galactic Republic's clone cold assault troopers served on this frozen world during the Clone Wars and Jedi Master Quinlan Vos mistakenly believed it home to a Separatist supply base. J'Quille, a male Whiphid who worked as a bounty hunter, hailed from Toola. " .
<https://starwars.com#54258ae2-d6ab-496e-a5fa-3fa2f091e85f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Toola"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Toola> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54258ae2-d6ab-496e-a5fa-3fa2f091e85f> .
<https://starwars.com#sector_Nilgaard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Toola> <http://telicent.io/ontology/primaryName> "Toola" .
<https://starwars.com#planet_Toola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#54258ae2-d6ab-496e-a5fa-3fa2f091e85f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Toola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nilgaard> .
<https://starwars.com#sector_Nilgaard> <http://telicent.io/ontology/primaryName> "Nilgaard" .
<https://starwars.com#planet_Toola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

