Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2a3fdcf4-ded9-4d00-8687-221c1b3b116c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vergesso"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bajic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vergesso> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vergesso> <http://telicent.io/ontology/primaryName> "Vergesso" .
<https://starwars.com#planet_Vergesso> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2a3fdcf4-ded9-4d00-8687-221c1b3b116c> .
<https://starwars.com#planet_Vergesso> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bajic> .
<https://starwars.com#sector_Bajic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vergesso> <http://www.w3.org/2000/01/rdf-schema#comment> "Vergesso was an asteroid in the galaxy's Outer Rim Territories. The former pirate Queen Maz Kanata marked it as a shadowport on a map that she included in the book that became known as the Smuggler's Guide. During the early rebellion against the Galactic Empire, after being rejected for help by the Grand Hutt Council and the Bounty Hunters' Guild in fighting the Galactic Empire, the Alliance to Restore the Republic considered a possible alliance with the Mining Guild, and at the time, the Rebel Alliance maintained an investigation of Mining Guild operations on Vergesso. " .
<https://starwars.com#planet_Vergesso> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P18> .
<https://starwars.com#sector_Bajic> <http://telicent.io/ontology/primaryName> "Bajic" .
<https://starwars.com#2a3fdcf4-ded9-4d00-8687-221c1b3b116c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

