Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NewCov> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#planet_NewCov> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5faed019-eafb-48c7-984e-506dabc7b0dd> .
<https://starwars.com#sector_Churba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NewCov> <http://www.w3.org/2000/01/rdf-schema#comment> "New Cov was an astronomical object located in the galaxy's Mid Rim in grid square P-14. It was situated along the Corellian Run, which connected New Cov to Milagro and Druckenwell, and was also connected to Kalarba by a lesser hyperspace route. " .
<https://starwars.com#sector_Churba> <http://telicent.io/ontology/primaryName> "Churba" .
<https://starwars.com#planet_NewCov> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churba> .
<https://starwars.com#5faed019-eafb-48c7-984e-506dabc7b0dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewCov> <http://telicent.io/ontology/primaryName> "New Cov" .
<https://starwars.com#5faed019-eafb-48c7-984e-506dabc7b0dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Cov"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NewCov> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Churba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

