Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fennesa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K14> .
<https://starwars.com#planet_Fennesa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02597b33-a879-436e-8784-46b7092bb15f> .
<https://starwars.com#planet_Fennesa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fennesa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Fennesa> <http://telicent.io/ontology/primaryName> "Fennesa" .
<https://starwars.com#02597b33-a879-436e-8784-46b7092bb15f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fennesa> <http://www.w3.org/2000/01/rdf-schema#comment> "The nerfs on Fennesa were kept by local herders. The latter were a tough people who, as a part of their profession, had to deal with predation, the nerfs' own rambunctious nature, and the eventual loss of the sense of smell due to the herd creatures' foul odor. At some point, an individual hid in the hills on Fennesa. A group of individuals tracking the fugitive in the mountains then had to deal with the local nerfs interfering with their search. " .
<https://starwars.com#02597b33-a879-436e-8784-46b7092bb15f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fennesa"^^<http://www.w3.org/2001/XMLSchema#string> .

