Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#fb04f51b-cefc-437f-b27e-c4081ef4ea38> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pengalan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#fb04f51b-cefc-437f-b27e-c4081ef4ea38> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pengalan> <http://www.w3.org/2000/01/rdf-schema#comment> "Pengalan was an astronomical object located in the galaxy's Inner Rim. " .
<https://starwars.com#planet_Pengalan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Pengalan> <http://telicent.io/ontology/primaryName> "Pengalan" .
<https://starwars.com#planet_Pengalan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Pengalan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pengalan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fb04f51b-cefc-437f-b27e-c4081ef4ea38> .

