Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bhargebba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#2cb603c5-251c-467d-9ace-e8347644a82a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2cb603c5-251c-467d-9ace-e8347644a82a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bhargebba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bhargebba> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Bhargebba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Bhargebba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bhargebba> <http://telicent.io/ontology/primaryName> "Bhargebba" .
<https://starwars.com#planet_Bhargebba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2cb603c5-251c-467d-9ace-e8347644a82a> .

