Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hosko> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f8266005-c3e2-4610-b3ad-dc8ef683baa4> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#f8266005-c3e2-4610-b3ad-dc8ef683baa4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hosko"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hosko> <http://telicent.io/ontology/primaryName> "Hosko" .
<https://starwars.com#planet_Hosko> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Hosko> <http://www.w3.org/2000/01/rdf-schema#comment> "Hosko was an agricultural planet located in Hutt Space. During the Hutt Cataclysms, the factions of the Hutt Empire fought a battle on Hosko with ancient weapons and battle droids. It was orbited by a space station frequented by traders and smugglers. " .
<https://starwars.com#planet_Hosko> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#f8266005-c3e2-4610-b3ad-dc8ef683baa4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Hosko> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

