Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brema> <http://telicent.io/ontology/primaryName> "Brema" .
<https://starwars.com#planet_OrdIbanna> <http://telicent.io/ontology/primaryName> "Ord Ibanna" .
<https://starwars.com#planet_OrdIbanna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#77dd3ca2-eb99-40aa-8827-3c4d5703d773> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Ibanna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdIbanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brema> .
<https://starwars.com#77dd3ca2-eb99-40aa-8827-3c4d5703d773> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Brema> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdIbanna> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Ibanna was a gas giant in the Outer Rim Territories. The planet once housed a Tibanna mining colony, which was abandoned sometime prior to the Invasion of Naboo as well as being the site of an intense naval engagement between the Galactic Republic and Sith Empire during the Great Galactic War. " .
<https://starwars.com#planet_OrdIbanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_OrdIbanna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#77dd3ca2-eb99-40aa-8827-3c4d5703d773> .
<https://starwars.com#sector_Brema> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

