Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Myrkr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0251e610-0b90-4bc3-87bd-e4a3b4d9d560> .
<https://starwars.com#planet_Myrkr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Myrkr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#planet_Myrkr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#0251e610-0b90-4bc3-87bd-e4a3b4d9d560> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Myrkr> <http://www.w3.org/2000/01/rdf-schema#comment> "Myrkr was an astronomical object located in the galaxy's Inner Rim. Myrkr sat at grid square N-7 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Myrkr> <http://telicent.io/ontology/primaryName> "Myrkr" .
<https://starwars.com#0251e610-0b90-4bc3-87bd-e4a3b4d9d560> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Myrkr"^^<http://www.w3.org/2001/XMLSchema#string> .

