Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_U13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5c085505-b6ab-4072-83b2-6ce7f275f1da> .
<https://starwars.com#planet_Altor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zoraster> .
<https://starwars.com#5c085505-b6ab-4072-83b2-6ce7f275f1da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Altor> <http://telicent.io/ontology/primaryName> "Altor" .
<https://starwars.com#planet_Altor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U13> .
<https://starwars.com#sector_Zoraster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Altor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Altor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#5c085505-b6ab-4072-83b2-6ce7f275f1da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Zoraster> <http://telicent.io/ontology/primaryName> "Zoraster" .
<https://starwars.com#sector_Zoraster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Altor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2cd65283-b75a-4625-954c-88865813ce3a> .
<https://starwars.com#grid_U13> <http://telicent.io/ontology/primaryName> "U13" .
<https://starwars.com#2cd65283-b75a-4625-954c-88865813ce3a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Altor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#2cd65283-b75a-4625-954c-88865813ce3a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_U13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

