Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ZardossaStix> <http://telicent.io/ontology/primaryName> "Zardossa Stix" .
<https://starwars.com#planet_ZardossaStix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ZardossaStix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#planet_ZardossaStix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3dcd8b05-c4d2-4479-a650-8877265993ff> .
<https://starwars.com#planet_ZardossaStix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#3dcd8b05-c4d2-4479-a650-8877265993ff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3dcd8b05-c4d2-4479-a650-8877265993ff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zardossa Stix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ZardossaStix> <http://www.w3.org/2000/01/rdf-schema#comment> "Zardossa Stix was a moon with a desert climate, in the Colonies located near Bardotta. The clay warriors of Zardossa Stix were associated with the moon, and according to Zardossan legend would return an enemy army to life if they were ever destroyed. It had a spaceport village which Jedi Master Mace Windu and Jar Jar Binks visited while tracking the Frangawl Cult that had kidnapped the Queen of Bardotta, Julia. The moon also featured a pyramid called the Temple of Malmourral, which was used by the Frangawl Cult, as well as their leader, Mother Talzin, as part of a ceremony to drain the Living Force from members of the Dagoyan Order. " .

