Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Loovria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#2d404775-c153-4dea-9b6d-1754239e6294> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Loovria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Loovria> <http://www.w3.org/2000/01/rdf-schema#comment> "Loovria was a location in the galaxy, that was gaining popularity as a competitor to the Grakkus Arena on Nar Shaddaa. " .
<https://starwars.com#planet_Loovria> <http://telicent.io/ontology/primaryName> "Loovria" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Loovria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2d404775-c153-4dea-9b6d-1754239e6294> .
<https://starwars.com#planet_Loovria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#2d404775-c153-4dea-9b6d-1754239e6294> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Loovria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

