Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_H16> <http://telicent.io/ontology/primaryName> "H16" .
<https://starwars.com#sector_Zuma> <http://telicent.io/ontology/primaryName> "Zuma" .
<https://starwars.com#grid_H16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#4ebe05d9-d65c-4649-baac-0dbd33bd76b0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Abbaji> <http://telicent.io/ontology/primaryName> "Abbaji" .
<https://starwars.com#0c6d4261-cf7f-488b-94f5-c0809554dd31> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_H16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_H16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4ebe05d9-d65c-4649-baac-0dbd33bd76b0> .
<https://starwars.com#sector_Zuma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Abbaji> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zuma> .
<https://starwars.com#0c6d4261-cf7f-488b-94f5-c0809554dd31> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abbaji"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Abbaji> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Abbaji> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0c6d4261-cf7f-488b-94f5-c0809554dd31> .
<https://starwars.com#planet_Abbaji> <http://www.w3.org/2000/01/rdf-schema#comment> "Abbaji was a planet within the Zuma sector of the Outer Rim Territories. It was mostly composed of rainforests, including the Irugian Rain Forest, the only place in the galaxy where firethorn trees could be found. One of those such trees was given to the renowned criminal Xizor, leader of the Black Sun crime syndicate." .
<https://starwars.com#4ebe05d9-d65c-4649-baac-0dbd33bd76b0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Abbaji> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Zuma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

