Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bakura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Timora> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bcc5ab10-ae01-498a-aec2-19c50bd4aa20> .
<https://starwars.com#planet_Timora> <http://www.w3.org/2000/01/rdf-schema#comment> "Timora was a planet located in the Timora system of the Outer Rim Territories and the inner endpoint of the Shiritoku Way. It was the closest planet in the Empire 'proper' to Bakura. Its people exported sunpetals. It also served as a shipping point for repulsorlift products from Bakura. " .
<https://starwars.com#bcc5ab10-ae01-498a-aec2-19c50bd4aa20> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Timora"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#bcc5ab10-ae01-498a-aec2-19c50bd4aa20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Timora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bakura> .
<https://starwars.com#planet_Timora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_G16> .
<https://starwars.com#planet_Timora> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bakura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Timora> <http://telicent.io/ontology/primaryName> "Timora" .
<https://starwars.com#sector_Bakura> <http://telicent.io/ontology/primaryName> "Bakura" .

