Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9f1438a4-9c61-4af8-b32f-b12b1d48520e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_VarHagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_VarHagen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vondarc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#sector_VarHagen> <http://telicent.io/ontology/primaryName> "Var Hagen" .
<https://starwars.com#planet_Vondarc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vondarc> <http://telicent.io/ontology/primaryName> "Vondarc" .
<https://starwars.com#planet_Vondarc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_VarHagen> .
<https://starwars.com#planet_Vondarc> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9f1438a4-9c61-4af8-b32f-b12b1d48520e> .
<https://starwars.com#9f1438a4-9c61-4af8-b32f-b12b1d48520e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vondarc"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vondarc> <http://www.w3.org/2000/01/rdf-schema#comment> "Vondarc was an astronomical object located in the galaxy's Mid Rim, along the Rimma Trade Route. " .

