Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gabredor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gabredor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#362d3552-ec50-4b10-92bd-5b80f042f7b7> .
<https://starwars.com#362d3552-ec50-4b10-92bd-5b80f042f7b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#362d3552-ec50-4b10-92bd-5b80f042f7b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gabredor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Myto> <http://telicent.io/ontology/primaryName> "Myto" .
<https://starwars.com#sector_Myto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gabredor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Myto> .
<https://starwars.com#planet_Gabredor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Gabredor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#sector_Myto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gabredor> <http://telicent.io/ontology/primaryName> "Gabredor" .

