Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Issagra> <http://telicent.io/ontology/primaryName> "Issagra" .
<https://starwars.com#planet_Issagra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#78119fd7-e9d0-43f2-b095-93bfc4278e75> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Issagra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Issagra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#78119fd7-e9d0-43f2-b095-93bfc4278e75> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Issagra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Issagra> <http://www.w3.org/2000/01/rdf-schema#comment> "Issagra was a planet in the Issagra system. It was located approximately twelve hours hyperspace travel from Fether. Its most notable location was a large space station. Over three kilometers long, the station was devoted to trade and gambling, and could house tens of thousands of visitors and hundreds of freighters at a time. The station's atmosphere was often regarded as grand and exotic, though organized crime held sway in the background and contraband could be found in numerous locations. " .
<https://starwars.com#78119fd7-e9d0-43f2-b095-93bfc4278e75> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Issagra"^^<http://www.w3.org/2001/XMLSchema#string> .

