Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mephout> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0ecaf48f-8f57-4007-b5f2-db942a4a046d> .
<https://starwars.com#planet_Mephout> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mephout> <http://telicent.io/ontology/primaryName> "Mephout" .
<https://starwars.com#planet_Mephout> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H20> .
<https://starwars.com#0ecaf48f-8f57-4007-b5f2-db942a4a046d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0ecaf48f-8f57-4007-b5f2-db942a4a046d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mephout"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mephout> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Mephout> <http://www.w3.org/2000/01/rdf-schema#comment> "Mephout was a Wild Space celestial body located in grid square H-20 of the Standard Galactic Grid. " .

