Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Xo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#db1a2758-937e-481b-b1d6-eb536e2d8f51> .
<https://starwars.com#db1a2758-937e-481b-b1d6-eb536e2d8f51> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Xo> <http://telicent.io/ontology/primaryName> "Xo" .
<https://starwars.com#sector_Spinward> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3df8d419-959c-46f7-bfc5-ba3991f24d59> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N2"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3df8d419-959c-46f7-bfc5-ba3991f24d59> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_N2> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Xo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N2> .
<https://starwars.com#sector_Spinward> <http://telicent.io/ontology/primaryName> "Spinward" .
<https://starwars.com#planet_Xo> <http://www.w3.org/2000/01/rdf-schema#comment> "Xo was a planet located within the Xo system in the Spinward sector of the Outer Rim Territories. It was the homeworld of the Zanibar species and the site of their sacrificial rituals. " .
<https://starwars.com#grid_N2> <http://telicent.io/ontology/primaryName> "N2" .
<https://starwars.com#grid_N2> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3df8d419-959c-46f7-bfc5-ba3991f24d59> .
<https://starwars.com#db1a2758-937e-481b-b1d6-eb536e2d8f51> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Xo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Spinward> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Xo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Spinward> .

