Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eclipse> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#0a9196a0-64e8-4987-b482-0dab7fbafcd5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eclipse"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Eclipse> <http://telicent.io/ontology/primaryName> "Eclipse" .
<https://starwars.com#0a9196a0-64e8-4987-b482-0dab7fbafcd5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L11> <http://telicent.io/ontology/primaryName> "L11" .
<https://starwars.com#planet_Eclipse> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Eclipse> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L11> .
<https://starwars.com#grid_L11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#3be79333-b51a-4f4f-80f4-ee6c7e3d6cc2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Eclipse> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0a9196a0-64e8-4987-b482-0dab7fbafcd5> .
<https://starwars.com#planet_Eclipse> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#grid_L11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#3be79333-b51a-4f4f-80f4-ee6c7e3d6cc2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3be79333-b51a-4f4f-80f4-ee6c7e3d6cc2> .

