Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Carratos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#c7ae8dc6-0768-41fb-af34-b2771efd6298> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Carratos> <http://telicent.io/ontology/primaryName> "Carratos" .
<https://starwars.com#planet_Carratos> <http://www.w3.org/2000/01/rdf-schema#comment> "Carratos was a planet in the Inner Rim, roughly forty parsecs from Coruscant. " .
<https://starwars.com#planet_Carratos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c7ae8dc6-0768-41fb-af34-b2771efd6298> .
<https://starwars.com#planet_Carratos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c7ae8dc6-0768-41fb-af34-b2771efd6298> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carratos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Carratos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .

