Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Loedorvia> <http://www.w3.org/2000/01/rdf-schema#comment> "Loedorvia was a celestial body located in the Core Worlds' Weemell sector. During the Clone Wars, it was the site of a battle between the Galactic Republic and the Confederacy of Independent Systems. During that confrontation, Confederate General Grievous ordered the release on Loedorvia of the disease known as the Brainrot Plague. The act killed tens of thousands of individuals and led to the deaths of nearly every Human in the Weemell sector. " .
<https://starwars.com#planet_Loedorvia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be84c65c-13e0-4edf-8048-dacdd67acfc1> .
<https://starwars.com#planet_Loedorvia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Loedorvia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Loedorvia> <http://telicent.io/ontology/primaryName> "Loedorvia" .
<https://starwars.com#be84c65c-13e0-4edf-8048-dacdd67acfc1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Loedorvia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Loedorvia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#be84c65c-13e0-4edf-8048-dacdd67acfc1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

