Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5eccbfef-7ef3-4a9c-9a32-df5ae452a83a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5eccbfef-7ef3-4a9c-9a32-df5ae452a83a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_M10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5eccbfef-7ef3-4a9c-9a32-df5ae452a83a> .
<https://starwars.com#a359d2ea-ffff-4e13-9490-6f8b712888cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a359d2ea-ffff-4e13-9490-6f8b712888cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alderaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M10> <http://telicent.io/ontology/primaryName> "M10" .
<https://starwars.com#grid_M10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Alderaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Alderaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a359d2ea-ffff-4e13-9490-6f8b712888cd> .
<https://starwars.com#planet_Alderaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Alderaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Alderaan> <http://www.w3.org/2000/01/rdf-schema#comment> "Forests, mountains; home planet of Princess Leia and the House of Organa. Destroyed by the first Death Star as punishment for involvement in the Rebel Alliance and also as a demonstration of power." .
<https://starwars.com#planet_Alderaan> <http://telicent.io/ontology/primaryName> "Alderaan" .

