Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Iast> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82f0e423-243e-4d9a-b519-3bec1fa558b5> .
<https://starwars.com#planet_Iast> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#82f0e423-243e-4d9a-b519-3bec1fa558b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iast"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Aldino> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Iast> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Aldino> .
<https://starwars.com#sector_Aldino> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Iast> <http://telicent.io/ontology/primaryName> "Iast" .
<https://starwars.com#planet_Iast> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J17> .
<https://starwars.com#planet_Iast> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Aldino> <http://telicent.io/ontology/primaryName> "Aldino" .
<https://starwars.com#82f0e423-243e-4d9a-b519-3bec1fa558b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

