Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1afab0ac-ad44-40bf-8751-a4372f94a73d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Palawa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Palawa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Palawa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#1afab0ac-ad44-40bf-8751-a4372f94a73d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Palawa> <http://telicent.io/ontology/primaryName> "Palawa" .
<https://starwars.com#planet_Palawa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Palawa> <http://www.w3.org/2000/01/rdf-schema#comment> "Palawa was a planet in the Core Worlds. It was the planet of origin of two mystic Force traditions, the Followers of Palawa and the Chatos Academy. " .
<https://starwars.com#planet_Palawa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1afab0ac-ad44-40bf-8751-a4372f94a73d> .

