Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Simpla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f1c6ea93-2253-43ea-85fc-611c6cd194ae> .
<https://starwars.com#sector_Kalamith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Simpla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kalamith> .
<https://starwars.com#planet_Simpla> <http://telicent.io/ontology/primaryName> "Simpla" .
<https://starwars.com#f1c6ea93-2253-43ea-85fc-611c6cd194ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Simpla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kalamith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Simpla> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Simpla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Simpla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_Kalamith> <http://telicent.io/ontology/primaryName> "Kalamith" .
<https://starwars.com#f1c6ea93-2253-43ea-85fc-611c6cd194ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

