Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4e091f31-a079-4e05-83b4-fa3ab1a4279a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Hangshan> <http://telicent.io/ontology/primaryName> "Hangshan" .
<https://starwars.com#sector_Hangshan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Erai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P11> .
<https://starwars.com#planet_Erai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4e091f31-a079-4e05-83b4-fa3ab1a4279a> .
<https://starwars.com#4e091f31-a079-4e05-83b4-fa3ab1a4279a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Erai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Erai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hangshan> .
<https://starwars.com#planet_Erai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Hangshan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Erai> <http://www.w3.org/2000/01/rdf-schema#comment> "The Erai system was a star system located in the region of the galaxy known as the Expansion Region. The system contained the planet Erai." .
<https://starwars.com#planet_Erai> <http://telicent.io/ontology/primaryName> "Erai" .

