Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gaurick> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Gaurick> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#ee6cbdda-2c51-4300-8c5b-1ce90be466e2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gaurick"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ee6cbdda-2c51-4300-8c5b-1ce90be466e2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Gaurick> <http://telicent.io/ontology/primaryName> "Gaurick" .
<https://starwars.com#planet_Gaurick> <http://www.w3.org/2000/01/rdf-schema#comment> "Gaurick was a planet in Corporate Sector. It was controlled by a religious cult, with leaders known as muftis. " .
<https://starwars.com#planet_Gaurick> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gaurick> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ee6cbdda-2c51-4300-8c5b-1ce90be466e2> .

