Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Skako> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Clone Wars, the world indirectly supported the Confederacy of Independent Systems, due to Tambor's allegiance with them. As a consequence, following the end of the war the Galactic Empire placed emigration restrictions on Skako and caused its people to suffer greatly, although many Skakoans were happy to remain isolated from the galaxy on Skako. " .
<https://starwars.com#planet_Skako> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4b874fb-10ed-4d73-800a-6b3533132418> .
<https://starwars.com#planet_Skako> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Skako> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Skako> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#b4b874fb-10ed-4d73-800a-6b3533132418> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skako"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b4b874fb-10ed-4d73-800a-6b3533132418> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Skako> <http://telicent.io/ontology/primaryName> "Skako" .

