Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8ef9695a-0375-4b95-8ee2-4d07a9a4452c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nantama"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Nantama> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Nantama> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8ef9695a-0375-4b95-8ee2-4d07a9a4452c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nantama> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Nantama> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8ef9695a-0375-4b95-8ee2-4d07a9a4452c> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nantama> <http://www.w3.org/2000/01/rdf-schema#comment> "Nantama was a wealthy resort world, controlled by House Elegin, renowned for the natural beauty of its fields. The Third Nantama Synod was held there. " .
<https://starwars.com#planet_Nantama> <http://telicent.io/ontology/primaryName> "Nantama" .

