Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#46d9bb3d-0fd2-4a2d-8d45-4f290c9847f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belazura"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Belazura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Belazura> <http://telicent.io/ontology/primaryName> "Belazura" .
<https://starwars.com#46d9bb3d-0fd2-4a2d-8d45-4f290c9847f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Belazura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Belazura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Belazura> <http://www.w3.org/2000/01/rdf-schema#comment> "Belazura was a Galactic Republic member world, and one of the most visually stunning planets in the galaxy. Belazura was directly represented in the Galactic Senate. " .
<https://starwars.com#planet_Belazura> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46d9bb3d-0fd2-4a2d-8d45-4f290c9847f2> .

