Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Merthian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a7a0449f-4d1e-4873-9561-35e119cc4f33> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rhommamool> <http://telicent.io/ontology/primaryName> "Rhommamool" .
<https://starwars.com#sector_Merthian> <http://telicent.io/ontology/primaryName> "Merthian" .
<https://starwars.com#planet_Rhommamool> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a7a0449f-4d1e-4873-9561-35e119cc4f33> .
<https://starwars.com#planet_Rhommamool> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rhommamool> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Merthian> .
<https://starwars.com#planet_Rhommamool> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#a7a0449f-4d1e-4873-9561-35e119cc4f33> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rhommamool"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rhommamool> <http://www.w3.org/2000/01/rdf-schema#comment> "Rhommamool was an astronomical object located in the galaxy's Expansion Region. " .
<https://starwars.com#sector_Merthian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

