Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Trandosha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9ed7f545-a99b-44e8-8201-29043f896ceb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trandosha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9ed7f545-a99b-44e8-8201-29043f896ceb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trandosha> <http://telicent.io/ontology/primaryName> "Trandosha" .
<https://starwars.com#planet_Trandosha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Trandosha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#planet_Trandosha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ed7f545-a99b-44e8-8201-29043f896ceb> .
<https://starwars.com#planet_Trandosha> <http://www.w3.org/2000/01/rdf-schema#comment> "Homeworld of the Trandoshan hunters. In the same solar system as Kashyyyk." .

