Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#54da2c19-56e1-4f77-96ac-5d92dca28350> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Bronsoon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#18326e56-71ba-4e71-b9b1-72e01bb872c2> .
<https://starwars.com#planet_Bronsoon> <http://telicent.io/ontology/primaryName> "Bronsoon" .
<https://starwars.com#planet_Bronsoon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bronsoon> <http://www.w3.org/2000/01/rdf-schema#comment> "Bronsoon was a trading port on the original Gordian Reach founded by Human colonists from the Core in ancient times. Bronsoonians had strict rules about gender relations, with laws governing everything from marriage between casts to making eye contact and who could walk where. Inevitably, Bronsoonian drama was all about forbidden love between different casts. A slow, little-used route connected Bronsoon with the Maridun system. " .
<https://starwars.com#18326e56-71ba-4e71-b9b1-72e01bb872c2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_P6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#54da2c19-56e1-4f77-96ac-5d92dca28350> .
<https://starwars.com#grid_P6> <http://telicent.io/ontology/primaryName> "P6" .
<https://starwars.com#grid_P6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#18326e56-71ba-4e71-b9b1-72e01bb872c2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bronsoon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bronsoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#54da2c19-56e1-4f77-96ac-5d92dca28350> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bronsoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .

