Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#4efa303d-8f67-4f01-a95c-b97778d0a56b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Hoth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4efa303d-8f67-4f01-a95c-b97778d0a56b> .
<https://starwars.com#planet_Hoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4efa303d-8f67-4f01-a95c-b97778d0a56b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hoth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Hoth> <http://www.w3.org/2000/01/rdf-schema#comment> "Desolate ice planet and base for the Rebel Alliance." .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hoth> <http://telicent.io/ontology/primaryName> "Hoth" .

