Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bozhnee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#238cea58-0dcd-44e5-8ebf-02845e2d6941> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Garnib"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bozhnee> <http://telicent.io/ontology/primaryName> "Bozhnee" .
<https://starwars.com#sector_Bozhnee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Garnib> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Garnib> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Garnib> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bozhnee> .
<https://starwars.com#planet_Garnib> <http://www.w3.org/2000/01/rdf-schema#comment> "Garnib was the primary world of the Garnib system. It was subjugated by the Galactic Empire and many native Balinaka (considered to be the galaxy's most artistic beings) were exported as slaves to the breeding farms on Karfeddion. The planet was headquarters of Galactic Crystal Creations, which exported Garnib crystals. " .
<https://starwars.com#238cea58-0dcd-44e5-8ebf-02845e2d6941> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Garnib> <http://telicent.io/ontology/primaryName> "Garnib" .
<https://starwars.com#planet_Garnib> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#238cea58-0dcd-44e5-8ebf-02845e2d6941> .

