Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Saleucami> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8c2de69f-0399-4bb0-9032-ce7efe287671> .
<https://starwars.com#planet_Saleucami> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Suolriep> .
<https://starwars.com#planet_Saleucami> <http://www.w3.org/2000/01/rdf-schema#comment> "Primary terrain deserts and swamps. Home of the clone trooper deserter Cut Lawquane. Jedi Master Stass Allie is killed here during the Great Jedi Purge." .
<https://starwars.com#sector_Suolriep> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Saleucami> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#8c2de69f-0399-4bb0-9032-ce7efe287671> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8c2de69f-0399-4bb0-9032-ce7efe287671> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Saleucami"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Saleucami> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Saleucami> <http://telicent.io/ontology/primaryName> "Saleucami" .
<https://starwars.com#sector_Suolriep> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Suolriep> <http://telicent.io/ontology/primaryName> "Suolriep" .

