Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_BurninKonn> <http://www.w3.org/2000/01/rdf-schema#comment> "Burnin Konn was a planet in the Anoat sector that served as a mining colony for chromium and other ores. The surface was almost entirely uninhabitable, with the planet's population being contained to areas like the Konn-Nevos Spaceport, Longstar Marketplace, and the Carbon Score Cantina. Imperial Governor Ubrik Adelhard's Iron Blockade of the Anoat sector forced the citizenry of Burnin Konn to resort to acquiring much-needed goods from local crime bosses. Three months after the Battle of Endor, Burnin Konn was one of dozens of worlds targeted by the remnants of the Empire during Operation: Cinder. " .
<https://starwars.com#planet_BurninKonn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1b42d641-e393-4b0a-90d1-d5392075ef90> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Burnin Konn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_BurninKonn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_BurninKonn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_BurninKonn> <http://telicent.io/ontology/primaryName> "Burnin Konn" .
<https://starwars.com#planet_BurninKonn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1b42d641-e393-4b0a-90d1-d5392075ef90> .
<https://starwars.com#1b42d641-e393-4b0a-90d1-d5392075ef90> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

