Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tarsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Tarsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAelgoth> .
<https://starwars.com#planet_Tarsa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#16cea055-2201-4081-8d3a-9906c4ab34c0> .
<https://starwars.com#sector_DAelgoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_DAelgoth> <http://telicent.io/ontology/primaryName> "D'Aelgoth" .
<https://starwars.com#planet_Tarsa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_DAelgoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#16cea055-2201-4081-8d3a-9906c4ab34c0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tarsa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#16cea055-2201-4081-8d3a-9906c4ab34c0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tarsa> <http://www.w3.org/2000/01/rdf-schema#comment> "Tarsa was a forested planet in the Tarsa system, which was located in the Mid Rim. " .
<https://starwars.com#planet_Tarsa> <http://telicent.io/ontology/primaryName> "Tarsa" .

