Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jerrilek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jerrilek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#83cf92b2-959c-4cb1-a57b-aa0716abfa96> .
<https://starwars.com#planet_Jerrilek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Jerrilek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#83cf92b2-959c-4cb1-a57b-aa0716abfa96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jerrilek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jerrilek> <http://telicent.io/ontology/primaryName> "Jerrilek" .
<https://starwars.com#planet_Jerrilek> <http://www.w3.org/2000/01/rdf-schema#comment> "Jerrilek was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#83cf92b2-959c-4cb1-a57b-aa0716abfa96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

