Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a93d55c4-6614-4e70-98bf-f0bf951c1cac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Plooma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#planet_Plooma> <http://www.w3.org/2000/01/rdf-schema#comment> "Plooma was an astronomical object located in the galaxy's Outer Rim Territories, in the grid square L-3 of the Standard Galactic Grid. " .
<https://starwars.com#a93d55c4-6614-4e70-98bf-f0bf951c1cac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Plooma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a93d55c4-6614-4e70-98bf-f0bf951c1cac> .
<https://starwars.com#planet_Plooma> <http://telicent.io/ontology/primaryName> "Plooma" .
<https://starwars.com#planet_Plooma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Plooma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L3> .
<https://starwars.com#planet_Plooma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Veragi> .

