Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lettow> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#44010a2b-1e8e-4ecc-89b8-4e1e75207009> .
<https://starwars.com#planet_Lettow> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#44010a2b-1e8e-4ecc-89b8-4e1e75207009> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lettow"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#44010a2b-1e8e-4ecc-89b8-4e1e75207009> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lettow> <http://www.w3.org/2000/01/rdf-schema#comment> "Lettow, known as 'Old Lettow', was a location mentioned in Our Empire's Army, an Imperial marching song that Zare Leonis and other Imperial cadets sang during their morning running drills. " .
<https://starwars.com#planet_Lettow> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Lettow> <http://telicent.io/ontology/primaryName> "Lettow" .
<https://starwars.com#planet_Lettow> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

