Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c3c3fc67-8ceb-4a8d-8476-86e64af7749e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Naporar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Naporar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Naporar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c3c3fc67-8ceb-4a8d-8476-86e64af7749e> .
<https://starwars.com#planet_Naporar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Naporar> <http://www.w3.org/2000/01/rdf-schema#comment> "Naporar was a planet in the Chiss Ascendancy and was also the headquarters of the Chiss Expansionary Defense Fleet. Naporar contained a medcenter where Mitth'raw'nuruodo underwent physical therapy after the Vagaari pirate operations. Mitth'ali'astov received her sky-walker training at the Expansionary Fleet complex there. After Csaplar was targeted by three alien warships, four Expansionary Fleet]] warships were sent from Naporar to support defenses on Csilla. " .
<https://starwars.com#planet_Naporar> <http://telicent.io/ontology/primaryName> "Naporar" .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Naporar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#c3c3fc67-8ceb-4a8d-8476-86e64af7749e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

