Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Chorlian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#45a92d5a-73d3-4e79-ae20-cb19a2bd3652> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nathema"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#45a92d5a-73d3-4e79-ae20-cb19a2bd3652> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nathema> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nathema> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#45a92d5a-73d3-4e79-ae20-cb19a2bd3652> .
<https://starwars.com#planet_Nathema> <http://telicent.io/ontology/primaryName> "Nathema" .
<https://starwars.com#sector_Chorlian> <http://telicent.io/ontology/primaryName> "Chorlian" .
<https://starwars.com#planet_Nathema> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Nathema> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chorlian> .
<https://starwars.com#sector_Chorlian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nathema> <http://www.w3.org/2000/01/rdf-schema#comment> "The Commander used the holocron to destroy the spirit of Vitiate, whose final death caused the Force to return to Nathema, which became overgrown with plant life and inhabited by surviving Zealots and escaped experiments. A group known as the Order of Zildrog found the ancient superweapon on Nathema and planned to reactivate Zildrog and use it against the Alliance. Thanks to the information provided by Theron Shan, Beniko and the Commander returned to Nathema to stop the Order. They were able to destroy Zildrog and defeat the Order's leaders Vinn Atrius and GEMINI 16, though at the cost of losing both the Eternal Fleet and the Gravestone. " .

