Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Lostar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Nessem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#planet_Nessem> <http://telicent.io/ontology/primaryName> "Nessem" .
<https://starwars.com#planet_Nessem> <http://www.w3.org/2000/01/rdf-schema#comment> "Nessem was a Trade Federation planet in the Expansion Region. It was orbited by the modest Nessem Shipyards. " .
<https://starwars.com#planet_Nessem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lostar> .
<https://starwars.com#planet_Nessem> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#616b55e7-8349-4071-9dab-75421258cf5f> .
<https://starwars.com#sector_Lostar> <http://telicent.io/ontology/primaryName> "Lostar" .
<https://starwars.com#sector_Lostar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#616b55e7-8349-4071-9dab-75421258cf5f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nessem"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nessem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#616b55e7-8349-4071-9dab-75421258cf5f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

