Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zigoola> <http://www.w3.org/2000/01/rdf-schema#comment> "Zigoola was a planet and a potent dark side vergence in The Force located in Wild Space, near the Calamari sector. " .
<https://starwars.com#planet_Zigoola> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fdc6bcad-2fc5-42ed-9ffd-7ce682cd40a6> .
<https://starwars.com#planet_Zigoola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Zigoola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#planet_Zigoola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zigoola> <http://telicent.io/ontology/primaryName> "Zigoola" .
<https://starwars.com#fdc6bcad-2fc5-42ed-9ffd-7ce682cd40a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zigoola"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#fdc6bcad-2fc5-42ed-9ffd-7ce682cd40a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

