Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gama> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7a1b4639-1ef9-444a-88cd-d77ec2dcd7d3> .
<https://starwars.com#planet_Gama> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gama> <http://telicent.io/ontology/primaryName> "Gama" .
<https://starwars.com#7a1b4639-1ef9-444a-88cd-d77ec2dcd7d3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gama> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Gama> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Gama> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#7a1b4639-1ef9-444a-88cd-d77ec2dcd7d3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gama"^^<http://www.w3.org/2001/XMLSchema#string> .

