Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Arporatal-Lanin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Arporatal-Lanin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Arporatal-Lanin> <http://telicent.io/ontology/primaryName> "Arporatal-Lanin" .
<https://starwars.com#planet_Arporatal-Lanin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#91e494c1-25a1-4dab-b48c-c44307ef8aa8> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Arporatal-Lanin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#91e494c1-25a1-4dab-b48c-c44307ef8aa8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#91e494c1-25a1-4dab-b48c-c44307ef8aa8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arporatal-Lanin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arporatal-Lanin> <http://www.w3.org/2000/01/rdf-schema#comment> "Arporatal-Lanin was the planet in the Arporatal-Lanin system and the homeworld of the Arpor-Lan species. " .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

