Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f4a046a7-1842-4690-8532-4a8e461c4f4c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Phateem> <http://www.w3.org/2000/01/rdf-schema#comment> "Phateem was an uninhabited planet located in the Nouane sector, near Telerath, covered in bamboo forests and mountains. The Ashlendu Mountains on Phateem contained the Halls of Knowledge, a former Jedi artifact cache. A tournament was held at the Halls of Knowledge, though it was a front for an operation led by Imperial Security Bureau Colonel Sadao Emtri to catch Force-sensitive individuals. " .
<https://starwars.com#planet_Phateem> <http://telicent.io/ontology/primaryName> "Phateem" .
<https://starwars.com#f4a046a7-1842-4690-8532-4a8e461c4f4c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phateem"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Phateem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Phateem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Phateem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Phateem> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f4a046a7-1842-4690-8532-4a8e461c4f4c> .

