Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#aed14e1f-93e2-494b-90d6-3770c0681fff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Darada"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Darada> <http://www.w3.org/2000/01/rdf-schema#comment> "Darada was a planet on the edge of the Core Worlds, near Krayiss Two. Jev Sunrider was a Jedi Watchman of Darada. His grandson, Andur Sunrider, spent the first nineteen years of his life there. " .
<https://starwars.com#planet_Darada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Darada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Darada> <http://telicent.io/ontology/primaryName> "Darada" .
<https://starwars.com#planet_Darada> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aed14e1f-93e2-494b-90d6-3770c0681fff> .
<https://starwars.com#aed14e1f-93e2-494b-90d6-3770c0681fff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Darada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

