Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Tumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Tumani> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#a1ca51c5-5916-4524-a604-94a6e72ee49f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tumani"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tumani> <http://telicent.io/ontology/primaryName> "Tumani" .
<https://starwars.com#planet_Tumani> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a1ca51c5-5916-4524-a604-94a6e72ee49f> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#a1ca51c5-5916-4524-a604-94a6e72ee49f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Tumani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

