Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PhoPheah> <http://www.w3.org/2000/01/rdf-schema#comment> "Pho Ph'eah was an astronomical object located within the galaxy's Outer Rim Territories, in the grid square P-5 of the Standard Galactic Grid. It was connected to the planets of Telos and Toprawa by the Hydian Way hyperspace route. " .
<https://starwars.com#planet_PhoPheah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kalamith> .
<https://starwars.com#sector_Kalamith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_PhoPheah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_Kalamith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1ef4b033-36c1-492c-b8f7-4ac66d77103d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#1ef4b033-36c1-492c-b8f7-4ac66d77103d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pho Ph'eah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kalamith> <http://telicent.io/ontology/primaryName> "Kalamith" .
<https://starwars.com#planet_PhoPheah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1ef4b033-36c1-492c-b8f7-4ac66d77103d> .
<https://starwars.com#planet_PhoPheah> <http://telicent.io/ontology/primaryName> "Pho Ph'eah" .
<https://starwars.com#planet_PhoPheah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

