Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Bardotta> <http://www.w3.org/2000/01/rdf-schema#comment> "Bardotta was a remote planet located in the Bardotta system of the Shasos sector of the the galaxy's Colonies region. Renowned for the art and music produced by the simple locals, the planet was ruled by a monarch who was guided in their decisions by the Dagoyan Order, a group reputed for their mysticism and attention to spiritual matters. " .
<https://starwars.com#de92c1da-c971-412f-b59f-51f2da765bb2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#790c4cfd-d34c-49a2-ae7b-174469bdd67e> .
<https://starwars.com#planet_Bardotta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Bardotta> <http://telicent.io/ontology/primaryName> "Bardotta" .
<https://starwars.com#planet_Bardotta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#de92c1da-c971-412f-b59f-51f2da765bb2> .
<https://starwars.com#grid_J13> <http://telicent.io/ontology/primaryName> "J13" .
<https://starwars.com#planet_Bardotta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#790c4cfd-d34c-49a2-ae7b-174469bdd67e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#de92c1da-c971-412f-b59f-51f2da765bb2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bardotta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bardotta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#790c4cfd-d34c-49a2-ae7b-174469bdd67e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J13"^^<http://www.w3.org/2001/XMLSchema#string> .

