Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ac92d9e2-d2ae-4438-acd5-2fd2ff2bbee2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ac92d9e2-d2ae-4438-acd5-2fd2ff2bbee2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q'mara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Qmara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Qmara> <http://telicent.io/ontology/primaryName> "Q'mara" .
<https://starwars.com#planet_Qmara> <http://www.w3.org/2000/01/rdf-schema#comment> "Q'mara, located in the Q'mara system of the Juvex sector, was a desert planet with a number of shabby spaceports, where all manner of smugglers and thugs sought illicit employment. Juvex nobles frequented Q'mara's houses of ill repute; foolish ones were drawn into its subterranean gambling and spice dens, sometimes never to return. Qellrin was attacked by pirates near Q'mara. " .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Qmara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Qmara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac92d9e2-d2ae-4438-acd5-2fd2ff2bbee2> .
<https://starwars.com#planet_Qmara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

