Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sanza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#063d7f16-1238-47c1-b9d3-5ab51cecc0a6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sloo> <http://telicent.io/ontology/primaryName> "Sloo" .
<https://starwars.com#sector_Sloo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#063d7f16-1238-47c1-b9d3-5ab51cecc0a6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sanza"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sanza> <http://telicent.io/ontology/primaryName> "Sanza" .
<https://starwars.com#planet_Sanza> <http://www.w3.org/2000/01/rdf-schema#comment> "Sanza, also known as Krish, was a Mid Rim world dedicated to casinos, race tracks, arenas, agriculture, and manufacturing. It was the home of the Krish species. " .
<https://starwars.com#planet_Sanza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sloo> .
<https://starwars.com#planet_Sanza> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sloo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sanza> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#063d7f16-1238-47c1-b9d3-5ab51cecc0a6> .

