Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Endor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Endor> <http://www.w3.org/2000/01/rdf-schema#comment> "Blue gas giant with a complex planetary system, including moons like Sanctuary and Kef Bir, this system was controlled by the Empire until the second Death Star was destroyed" .
<https://starwars.com#planet_Endor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8ad750ee-79f2-4b90-a4d5-9371748a52d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Endor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8ad750ee-79f2-4b90-a4d5-9371748a52d7> .
<https://starwars.com#8ad750ee-79f2-4b90-a4d5-9371748a52d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Endor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Endor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_Endor> <http://telicent.io/ontology/primaryName> "Endor" .

