Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cal-Seti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Cal-Seti> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cal-Seti> <http://telicent.io/ontology/primaryName> "Cal-Seti" .
<https://starwars.com#planet_Cal-Seti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#ae82c141-cf6c-4a4b-8560-779ad19b65dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ae82c141-cf6c-4a4b-8560-779ad19b65dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cal-Seti"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cal-Seti> <http://www.w3.org/2000/01/rdf-schema#comment> "Cal-Seti was a planet located several sectors from N'zoth. It was at the intersection of the Agricultural Circuit and the Metellos Trade Route. " .
<https://starwars.com#planet_Cal-Seti> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ae82c141-cf6c-4a4b-8560-779ad19b65dd> .

