Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Loretto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Loretto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Loretto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Loretto> <http://telicent.io/ontology/primaryName> "Loretto" .
<https://starwars.com#planet_Loretto> <http://www.w3.org/2000/01/rdf-schema#comment> "Loretto was the homeworld of the famed artist, Duos'tine. " .
<https://starwars.com#dd01f074-f7d5-427f-88ad-86091f7bba2e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Loretto"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Loretto> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd01f074-f7d5-427f-88ad-86091f7bba2e> .
<https://starwars.com#dd01f074-f7d5-427f-88ad-86091f7bba2e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

