Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dankayo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Dankayo> <http://www.w3.org/2000/01/rdf-schema#comment> "Dankayo was a location in the galaxy's Colonies that was a suspected base of rebel operations. Dankayo and several other locations were identified in a 3 ABY Imperial Security Bureau report that generated targets for Viper probe droid surveys by cross-referencing areas with a high degree of suspicious activity with the unsettled parts of the galaxy favored by the rebels. " .
<https://starwars.com#planet_Dankayo> <http://telicent.io/ontology/primaryName> "Dankayo" .
<https://starwars.com#971f66a6-fe03-400a-9b89-10a1eefa7631> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dankayo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dankayo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#971f66a6-fe03-400a-9b89-10a1eefa7631> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dankayo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#971f66a6-fe03-400a-9b89-10a1eefa7631> .
<https://starwars.com#planet_Dankayo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

