Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#planet_Shuldene> <http://www.w3.org/2000/01/rdf-schema#comment> "Shuldene was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Shuldene> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d2d23f3b-46bf-4025-b977-a0d1d5459f09> .
<https://starwars.com#planet_Shuldene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J18> .
<https://starwars.com#d2d23f3b-46bf-4025-b977-a0d1d5459f09> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shuldene"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#d2d23f3b-46bf-4025-b977-a0d1d5459f09> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shuldene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#planet_Shuldene> <http://telicent.io/ontology/primaryName> "Shuldene" .
<https://starwars.com#planet_Shuldene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

