Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Albanin> <http://telicent.io/ontology/primaryName> "Albanin" .
<https://starwars.com#planet_Dubrava> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albanin> .
<https://starwars.com#b602a56a-743a-458f-8921-5376964cf83c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dubrava"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Albanin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Dubrava> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T13> .
<https://starwars.com#sector_Albanin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dubrava> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dubrava> <http://telicent.io/ontology/primaryName> "Dubrava" .
<https://starwars.com#planet_Dubrava> <http://www.w3.org/2000/01/rdf-schema#comment> "Dubrava was an astronomical object in the Outer Rim Territories of the galaxy, linked via hyperspace routes to Barab and Syvris, and positioned at the coordinates T-13 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Dubrava> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b602a56a-743a-458f-8921-5376964cf83c> .
<https://starwars.com#b602a56a-743a-458f-8921-5376964cf83c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

