Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Xan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Thape> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#99ddca2e-117a-4141-a12e-9680fb8ae149> .
<https://starwars.com#sector_Xan> <http://telicent.io/ontology/primaryName> "Xan" .
<https://starwars.com#planet_Thape> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q15> .
<https://starwars.com#planet_Thape> <http://www.w3.org/2000/01/rdf-schema#comment> "Thape was an astronomical object located in the Thape system, a part of the Lambda sector in The Slice portion of the Mid Rim. It lay on a hyperlane between Ando and Leritor. It was a place of origin of the Order of Dai Bendu, a mystic Force tradition that preceded the birth of the Jedi Order. " .
<https://starwars.com#sector_Xan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#99ddca2e-117a-4141-a12e-9680fb8ae149> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#99ddca2e-117a-4141-a12e-9680fb8ae149> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thape"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thape> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Xan> .
<https://starwars.com#planet_Thape> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thape> <http://telicent.io/ontology/primaryName> "Thape" .

