Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5a911931-7ddf-40a5-94c5-1cc5f973a2bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hynah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hynah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hynah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kalamith> .
<https://starwars.com#planet_Hynah> <http://www.w3.org/2000/01/rdf-schema#comment> "Hynah was an industrial world located in the Kalamith sector of the Outer Rim Territories, on the Hydian Way hyperlane. It was home to the Hynese, a cosmopolitan population of various different species. Prior to the evacuation of the Rebel Alliance's Yavin system base, Rebel scouts charted an escape hyperlane leading from the Feswe Corridor star system to Hynah. " .
<https://starwars.com#sector_Kalamith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kalamith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hynah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#planet_Hynah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5a911931-7ddf-40a5-94c5-1cc5f973a2bb> .
<https://starwars.com#sector_Kalamith> <http://telicent.io/ontology/primaryName> "Kalamith" .
<https://starwars.com#planet_Hynah> <http://telicent.io/ontology/primaryName> "Hynah" .
<https://starwars.com#5a911931-7ddf-40a5-94c5-1cc5f973a2bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

