Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rhinnal> <http://telicent.io/ontology/primaryName> "Rhinnal" .
<https://starwars.com#planet_Rhinnal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7e7938f0-8ab3-4c49-bcca-d2529f77c336> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rhinnal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#7e7938f0-8ab3-4c49-bcca-d2529f77c336> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rhinnal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rhinnal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e7938f0-8ab3-4c49-bcca-d2529f77c336> .
<https://starwars.com#planet_Rhinnal> <http://www.w3.org/2000/01/rdf-schema#comment> "Rhinnal was a cold planet which was a member of the Galactic Republic during the High Republic Era. Considered a key world of the Republic, Rhinnal received a sky-island with a replication of its environment for the Valo Republic Fair held around 231 BBY, which contained a turbo-ski run. " .
<https://starwars.com#planet_Rhinnal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

