Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Elamposnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Elamposnia> <http://www.w3.org/2000/01/rdf-schema#comment> "Elamposnia was a planet in the Gordian Reach of the Outer Rim. " .
<https://starwars.com#b8b1aef4-bf7a-49dd-9e3f-be0629a2ce07> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Elamposnia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b8b1aef4-bf7a-49dd-9e3f-be0629a2ce07> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elamposnia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Elamposnia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b8b1aef4-bf7a-49dd-9e3f-be0629a2ce07> .
<https://starwars.com#planet_Elamposnia> <http://telicent.io/ontology/primaryName> "Elamposnia" .
<https://starwars.com#planet_Elamposnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .

