Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#06eb16d8-b18e-4443-99b6-bb03aa36dcf3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Bissillirus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#planet_Bissillirus> <http://www.w3.org/2000/01/rdf-schema#comment> "Bissillirus was the primary star of the Bissillirus system. It was discovered sometime in 200 BBY by hyperspace scouts looking for a route through the southern outskirts of the Thornhedge Nebula. " .
<https://starwars.com#sector_Trax> <http://telicent.io/ontology/primaryName> "Trax" .
<https://starwars.com#5ece0dc3-7f20-4e38-bdb5-ed7dc385570d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bissillirus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Trax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#06eb16d8-b18e-4443-99b6-bb03aa36dcf3> .
<https://starwars.com#grid_Q10> <http://telicent.io/ontology/primaryName> "Q10" .
<https://starwars.com#planet_Bissillirus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5ece0dc3-7f20-4e38-bdb5-ed7dc385570d> .
<https://starwars.com#06eb16d8-b18e-4443-99b6-bb03aa36dcf3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bissillirus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5ece0dc3-7f20-4e38-bdb5-ed7dc385570d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_Q10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Bissillirus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trax> .
<https://starwars.com#planet_Bissillirus> <http://telicent.io/ontology/primaryName> "Bissillirus" .
<https://starwars.com#sector_Trax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_Q10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

