Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cheelit> <http://telicent.io/ontology/primaryName> "Cheelit" .
<https://starwars.com#7297e49a-2afc-4c2a-9eea-e7adfcce7812> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7297e49a-2afc-4c2a-9eea-e7adfcce7812> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cheelit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Semagi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Cheelit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cheelit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I16> .
<https://starwars.com#planet_Cheelit> <http://www.w3.org/2000/01/rdf-schema#comment> "Cheelit was the homeworld of brain crawlers, a species of parasitic worm that could infest happabores. " .
<https://starwars.com#sector_Semagi> <http://telicent.io/ontology/primaryName> "Semagi" .
<https://starwars.com#sector_Semagi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cheelit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Semagi> .
<https://starwars.com#planet_Cheelit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7297e49a-2afc-4c2a-9eea-e7adfcce7812> .

