Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yminis> <http://telicent.io/ontology/primaryName> "Yminis" .
<https://starwars.com#planet_KolandaStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d8bbe1c5-2792-4f7f-bff0-a20291866d0f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Yminis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KolandaStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Kolanda Station was located on Latharra in the Yminis sector. During the Galactic Civil War, it was the site of a massacre of Rebel soldiers by Imperial forces acting on intelligence supplied by Krova the Hutt. " .
<https://starwars.com#planet_KolandaStation> <http://telicent.io/ontology/primaryName> "Kolanda Station" .
<https://starwars.com#d8bbe1c5-2792-4f7f-bff0-a20291866d0f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kolanda Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Yminis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KolandaStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yminis> .
<https://starwars.com#planet_KolandaStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S14> .
<https://starwars.com#planet_KolandaStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d8bbe1c5-2792-4f7f-bff0-a20291866d0f> .

