Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Gendius> <http://telicent.io/ontology/primaryName> "Gendius" .
<https://starwars.com#planet_QuaensanPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#18426fd9-3523-4bf6-b61b-c1d5fa2ff5d7> .
<https://starwars.com#sector_Gendius> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#18426fd9-3523-4bf6-b61b-c1d5fa2ff5d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_QuaensanPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J17> .
<https://starwars.com#planet_QuaensanPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gendius> .
<https://starwars.com#18426fd9-3523-4bf6-b61b-c1d5fa2ff5d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quaensan Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_QuaensanPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Gendius> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_QuaensanPrime> <http://telicent.io/ontology/primaryName> "Quaensan Prime" .
<https://starwars.com#planet_QuaensanPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Quaensan Prime was a Gendius sector, Mid Rim world on the Cerean Reach, near the Jiroch system. Its inhabitants were wiped out by the Reslian Purge, similar to what happened to the Tunroth. " .

