Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lujo> <http://telicent.io/ontology/primaryName> "Lujo" .
<https://starwars.com#planet_Lujo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lujo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#a7ee4d45-225b-431a-ba8a-b96d4980113d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lujo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a7ee4d45-225b-431a-ba8a-b96d4980113d> .
<https://starwars.com#planet_Lujo> <http://www.w3.org/2000/01/rdf-schema#comment> "Lujo was a planet in the Core. It had a temperate climate, and was home to magnificent oceans and landscapes. " .
<https://starwars.com#a7ee4d45-225b-431a-ba8a-b96d4980113d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lujo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lujo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .

