Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tythe> <http://www.w3.org/2000/01/rdf-schema#comment> "Tythe was a location in the galaxy. At some point after the first battle of the Outer Rim planet Geonosis, which started the Clone Wars between the Confederacy of Independent Systems and Galactic Republic in 22 BBY, Jedi General Anakin Skywalker fought Count Dooku at Tythe. As had occurred during their confrontation on Geonosis and at other locations, Dooku avoided defeat at the hands of Skywalker. " .
<https://starwars.com#planet_Tythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .
<https://starwars.com#planet_Tythe> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1565660f-7219-4afa-9a39-d5fb9eceecaf> .
<https://starwars.com#planet_Tythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1565660f-7219-4afa-9a39-d5fb9eceecaf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tythe"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#planet_Tythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#planet_Tythe> <http://telicent.io/ontology/primaryName> "Tythe" .
<https://starwars.com#1565660f-7219-4afa-9a39-d5fb9eceecaf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

