Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdPardron> <http://telicent.io/ontology/primaryName> "Ord Pardron" .
<https://starwars.com#b98b8106-5fac-4941-a475-0488d98353c7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdPardron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dufilvian> .
<https://starwars.com#sector_Dufilvian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_OrdPardron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdPardron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R15> .
<https://starwars.com#planet_OrdPardron> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Pardron was a planet located in the galaxy's Mid Rim that was a safe world for the Alliance to Restore the Republic. A map of the galaxy with a legend listing the various Alliance safe worlds, starfighter hubs at level five or higher, rebel operations sectors and regional headquarters, and shadow planets with deep space caches, included Ord Pardron. " .
<https://starwars.com#planet_OrdPardron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b98b8106-5fac-4941-a475-0488d98353c7> .
<https://starwars.com#sector_Dufilvian> <http://telicent.io/ontology/primaryName> "Dufilvian" .
<https://starwars.com#sector_Dufilvian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b98b8106-5fac-4941-a475-0488d98353c7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Pardron"^^<http://www.w3.org/2001/XMLSchema#string> .

