Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kinyen> <http://www.w3.org/2000/01/rdf-schema#comment> "Kinyen was the homeworld of the Gran senators Philo and Kharrus, who represented Kinyen in the Galactic Republic Senate during the Clone Wars. " .
<https://starwars.com#3e22eb93-5c10-4f74-8c26-ee4fbb201a21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3e22eb93-5c10-4f74-8c26-ee4fbb201a21> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kinyen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kinyen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_BesBerBikade> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Kinyen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#sector_BesBerBikade> <http://telicent.io/ontology/primaryName> "Bes Ber Bikade" .
<https://starwars.com#sector_BesBerBikade> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kinyen> <http://telicent.io/ontology/primaryName> "Kinyen" .
<https://starwars.com#planet_Kinyen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3e22eb93-5c10-4f74-8c26-ee4fbb201a21> .
<https://starwars.com#planet_Kinyen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BesBerBikade> .

