Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Wrea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a1496f9-9fac-4810-81ca-28b87b0ddd75> .
<https://starwars.com#planet_Wrea> <http://telicent.io/ontology/primaryName> "Wrea" .
<https://starwars.com#1a1496f9-9fac-4810-81ca-28b87b0ddd75> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Gaulus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Wrea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gaulus> .
<https://starwars.com#planet_Wrea> <http://www.w3.org/2000/01/rdf-schema#comment> "A planet near an asteroid field where Saw Gerrara raises Jyn Erso after her father is taken by the Empire." .
<https://starwars.com#planet_Wrea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S17> .
<https://starwars.com#planet_Wrea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1a1496f9-9fac-4810-81ca-28b87b0ddd75> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wrea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Gaulus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Gaulus> <http://telicent.io/ontology/primaryName> "Gaulus" .

