Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Terephon> <http://telicent.io/ontology/primaryName> "Terephon" .
<https://starwars.com#701af30c-972e-40b7-9b2c-919010b0f010> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Terephon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Terephon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#701af30c-972e-40b7-9b2c-919010b0f010> .
<https://starwars.com#planet_Terephon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#701af30c-972e-40b7-9b2c-919010b0f010> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Terephon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Terephon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Terephon> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet offered little to the Hapes Cluster other than several of the amazon guards who protected the Hapan Royal Family. However, once Hapes and the New Republic began to interact with one another, Terephon became the occasional location of galactic intrigue. As with many Hapan worlds, it was presided over by a Ducha. Terephon was generally not a notable planet in the galaxy, though during the Second Galactic Civil War in 40 ABY, it was embroiled in the galaxy-wide conflict that reached Hapes. Later that year, the planet the site of a climactic duel where Jedi Grand Master Luke Skywalker killed Dark Lady of the Sith Lumiya. " .

