Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Borleias> <http://telicent.io/ontology/primaryName> "Borleias" .
<https://starwars.com#planet_Borleias> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ea2de19b-fe86-4645-9e47-090857cc4664> .
<https://starwars.com#ea2de19b-fe86-4645-9e47-090857cc4664> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Borleias> <http://www.w3.org/2000/01/rdf-schema#comment> "Borleias was an astronomical object located in the Borleias system of the Colonies region. Borleias sat at grid square K-9 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Borleias> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Borleias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#ea2de19b-fe86-4645-9e47-090857cc4664> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Borleias"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Borleias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .

