Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Leritor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q15> .
<https://starwars.com#c0d2620c-8e62-4f97-a251-a7a4b8c2e251> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Leritor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c0d2620c-8e62-4f97-a251-a7a4b8c2e251> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Leritor> <http://telicent.io/ontology/primaryName> "Leritor" .
<https://starwars.com#sector_Yucrales> <http://telicent.io/ontology/primaryName> "Yucrales" .
<https://starwars.com#planet_Leritor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yucrales> .
<https://starwars.com#planet_Leritor> <http://www.w3.org/2000/01/rdf-schema#comment> "Leritor was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_Yucrales> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yucrales> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Leritor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c0d2620c-8e62-4f97-a251-a7a4b8c2e251> .
<https://starwars.com#planet_Leritor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

