Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chalcedon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Tashtor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Chalcedon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tashtor> .
<https://starwars.com#b29bef1e-e27d-4685-aba3-a669ed934c39> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chalcedon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chalcedon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b29bef1e-e27d-4685-aba3-a669ed934c39> .
<https://starwars.com#sector_Tashtor> <http://telicent.io/ontology/primaryName> "Tashtor" .
<https://starwars.com#planet_Chalcedon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I16> .
<https://starwars.com#planet_Chalcedon> <http://telicent.io/ontology/primaryName> "Chalcedon" .
<https://starwars.com#b29bef1e-e27d-4685-aba3-a669ed934c39> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tashtor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chalcedon> <http://www.w3.org/2000/01/rdf-schema#comment> "Chalcedon was astronomical object located in the galaxy's the Tashtor sector within the Mid Rim. Located on a hyperspace route between Cerea and Takodana, it was the center of the galactic slave trade. Chalcedon also housed a shadowport and was marked on a map included by the former pirate Queen Maz Kanata in the book that became known as the Smuggler's Guide. " .

