Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#89247078-66ce-4e59-8150-8de50a4af2b0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#89247078-66ce-4e59-8150-8de50a4af2b0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tala"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tala> <http://www.w3.org/2000/01/rdf-schema#comment> "Tala was a female human Imperial officer who was stationed on Mapuzo. While initially joining the Galactic Empire to try and make a difference, she became disillusioned and eventually saw the Empire for its tyranny. She then secretly became a member of an underground movement that helped smuggle surviving Jedi to safety. She tried to help Obi-Wan Kenobi return Leia Organa to her homeworld Alderaan, taking her through an underground tunnel system while Kenobi distracted their pursuers, but later left Leia to meet with one of her companions and saved Kenobi from being captured by Darth Vader. " .
<https://starwars.com#planet_Tala> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tala> <http://telicent.io/ontology/primaryName> "Tala" .
<https://starwars.com#planet_Tala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_Tala> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89247078-66ce-4e59-8150-8de50a4af2b0> .

