Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_CorvisMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a star. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_Ciutric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_CorvisMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ciutric> .
<https://starwars.com#planet_CorvisMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N5> .
<https://starwars.com#169c05f8-5a54-4617-8785-32b6e52cc79e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corvis Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ciutric> <http://telicent.io/ontology/primaryName> "Ciutric" .
<https://starwars.com#planet_CorvisMinor> <http://telicent.io/ontology/primaryName> "Corvis Minor" .
<https://starwars.com#169c05f8-5a54-4617-8785-32b6e52cc79e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_CorvisMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Ciutric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_CorvisMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#169c05f8-5a54-4617-8785-32b6e52cc79e> .

