Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Christophsis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c361d41e-3c90-4e8e-8c2a-5f6e8d2e95f1> .
<https://starwars.com#planet_Christophsis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Christophsis> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Clone Wars, the Battle of Christophsis occurs here, serving as an introduction to Ahsoka Tano." .
<https://starwars.com#c361d41e-3c90-4e8e-8c2a-5f6e8d2e95f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Christophsis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#planet_Christophsis> <http://telicent.io/ontology/primaryName> "Christophsis" .
<https://starwars.com#c361d41e-3c90-4e8e-8c2a-5f6e8d2e95f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Christophsis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#planet_Christophsis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

