Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ifmix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Ifmix> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d20d4d5-2b47-41d7-ba2e-0dd380fcea55> .
<https://starwars.com#5d20d4d5-2b47-41d7-ba2e-0dd380fcea55> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ifmix> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Ifmix> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5d20d4d5-2b47-41d7-ba2e-0dd380fcea55> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ifmix"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ifmix> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Ifmix> <http://telicent.io/ontology/primaryName> "Ifmix" .

