Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gavryn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Romintine> .
<https://starwars.com#grid_Q8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Gavryn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#8b79262b-ee55-4d6a-a524-85c0596f947a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Gavryn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aef71cdf-8440-4d61-8ba4-b7033c624494> .
<https://starwars.com#aef71cdf-8440-4d61-8ba4-b7033c624494> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gavryn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Romintine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Romintine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_Q8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8b79262b-ee55-4d6a-a524-85c0596f947a> .
<https://starwars.com#planet_Gavryn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#aef71cdf-8440-4d61-8ba4-b7033c624494> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8b79262b-ee55-4d6a-a524-85c0596f947a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q8> <http://telicent.io/ontology/primaryName> "Q8" .
<https://starwars.com#planet_Gavryn> <http://www.w3.org/2000/01/rdf-schema#comment> "Gavryn was a planet with a powerful magnetic pole. Ensign Gilad Pellaeon first distinguished himself while commanding an escort for a convoy to Gavryn. As the convoy entered orbit, pirates attacked. Pellaeon flew his ship into the magnetic pole, obscuring his ship from the pirates' sensors. As the pirate vessel moved to board the convoy ships, Pellaeon emerged from the pole and destroyed them. His quick thinking in this incident earned him the first in a string of promotions. " .
<https://starwars.com#planet_Gavryn> <http://telicent.io/ontology/primaryName> "Gavryn" .
<https://starwars.com#sector_Romintine> <http://telicent.io/ontology/primaryName> "Romintine" .

