Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AlliedTion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Amarin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Amarin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7bed8953-04dc-4494-8cf8-68859722f67a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Amarin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_AlliedTion> <http://telicent.io/ontology/primaryName> "Allied Tion" .
<https://starwars.com#planet_Amarin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AlliedTion> .
<https://starwars.com#7bed8953-04dc-4494-8cf8-68859722f67a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Amarin> <http://www.w3.org/2000/01/rdf-schema#comment> "Amarin was a planet of dense forests in the Amarin system of the Allied Tion sector, and one of the busiest agriworlds of the Tion Cluster. " .
<https://starwars.com#sector_AlliedTion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Amarin> <http://telicent.io/ontology/primaryName> "Amarin" .
<https://starwars.com#planet_Amarin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7bed8953-04dc-4494-8cf8-68859722f67a> .

