Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TheRedTwins> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TheRedTwins> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_TheRedTwins> <http://telicent.io/ontology/primaryName> "The Red Twins" .
<https://starwars.com#planet_TheRedTwins> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a100032-bda5-4a3f-8950-935df27fbba6> .
<https://starwars.com#3a100032-bda5-4a3f-8950-935df27fbba6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TheRedTwins> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#3a100032-bda5-4a3f-8950-935df27fbba6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Red Twins"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TheRedTwins> <http://www.w3.org/2000/01/rdf-schema#comment> "The Red Twins was a location in the galaxy's Mid Rim. " .

