Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dd3ac5ad-6f7a-4740-a3e1-76ff2d7d5441> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shawken"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shawken> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Shawken> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shawken> <http://telicent.io/ontology/primaryName> "Shawken" .
<https://starwars.com#planet_Shawken> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd3ac5ad-6f7a-4740-a3e1-76ff2d7d5441> .
<https://starwars.com#planet_Shawken> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Shawken> <http://www.w3.org/2000/01/rdf-schema#comment> "Shawken was a Core World. It boasted one of the most ancient civilizations in the known galaxy, and was the home of the Shawkenese. Shawken was connected to Coruscant by the Shawken Spur. " .
<https://starwars.com#dd3ac5ad-6f7a-4740-a3e1-76ff2d7d5441> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

