Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ventooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P3> .
<https://starwars.com#8492ef73-aac6-4672-9289-81700d7f72ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ventooine> <http://telicent.io/ontology/primaryName> "Ventooine" .
<https://starwars.com#planet_Ventooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ventooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corva> .
<https://starwars.com#planet_Ventooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Ventooine was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#8492ef73-aac6-4672-9289-81700d7f72ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ventooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Corva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Corva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ventooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8492ef73-aac6-4672-9289-81700d7f72ab> .
<https://starwars.com#sector_Corva> <http://telicent.io/ontology/primaryName> "Corva" .

