Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Begeren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#a26f69e5-7da1-45ff-97e9-d8659505e9d1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Begeren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Begeren> <http://www.w3.org/2000/01/rdf-schema#comment> "Begeren was a planet in the Sith Worlds region of the Outer Rim Territories. It was originally part of the Sith Empire, which constructed enormous monuments dedicated to notable Sith on the planet's surface—a project that cost the lives of an estimated hundred thousand slaves. Following the Empire's defeat in the Great Hyperspace War, Begeren was claimed by the Galactic Republic. The Republic allowed the construction of a gemstone quarry at the expense of the Sith statues, which fell into ruin. In 3678 BBY, the planet was seized by a revived Sith Empire. During the Galactic Civil War, Begeren was the site of a battle between the Alliance to Restore the Republic and the Galactic Empire. " .
<https://starwars.com#planet_Begeren> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a26f69e5-7da1-45ff-97e9-d8659505e9d1> .
<https://starwars.com#planet_Begeren> <http://telicent.io/ontology/primaryName> "Begeren" .
<https://starwars.com#planet_Begeren> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a26f69e5-7da1-45ff-97e9-d8659505e9d1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Begeren"^^<http://www.w3.org/2001/XMLSchema#string> .

