Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#aad1831b-3945-45c5-b777-26c12d242777> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eiattu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#aad1831b-3945-45c5-b777-26c12d242777> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Eiattu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Eiattu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ado> .
<https://starwars.com#sector_Ado> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Eiattu> <http://www.w3.org/2000/01/rdf-schema#comment> "Eiattu was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Eiattu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aad1831b-3945-45c5-b777-26c12d242777> .
<https://starwars.com#planet_Eiattu> <http://telicent.io/ontology/primaryName> "Eiattu" .
<https://starwars.com#sector_Ado> <http://telicent.io/ontology/primaryName> "Ado" .
<https://starwars.com#sector_Ado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Eiattu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

