Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_R15> <http://telicent.io/ontology/primaryName> "R15" .
<https://starwars.com#0e484643-8d3d-4614-8757-ec7568ec69a1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dennaskar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#fb07079f-2262-4449-80d8-37ff5d5a3463> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_R15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#planet_Dennaskar> <http://telicent.io/ontology/primaryName> "Dennaskar" .
<https://starwars.com#planet_Dennaskar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Manda> .
<https://starwars.com#planet_Dennaskar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0e484643-8d3d-4614-8757-ec7568ec69a1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dennaskar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e484643-8d3d-4614-8757-ec7568ec69a1> .
<https://starwars.com#fb07079f-2262-4449-80d8-37ff5d5a3463> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_R15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Dennaskar> <http://www.w3.org/2000/01/rdf-schema#comment> "Dennaskar was a forest planet located in the Mid Rim. " .
<https://starwars.com#planet_Dennaskar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R15> .
<https://starwars.com#sector_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_R15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#fb07079f-2262-4449-80d8-37ff5d5a3463> .

