Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Samaria> <http://www.w3.org/2000/01/rdf-schema#comment> "Samaria was a small desert planet in the Leemurtoo system, in a strategic part of the Core Worlds. " .
<https://starwars.com#652cfeeb-693d-49bb-a7a5-ccf25b7a9ad0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Samaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Samaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#652cfeeb-693d-49bb-a7a5-ccf25b7a9ad0> .
<https://starwars.com#planet_Samaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#652cfeeb-693d-49bb-a7a5-ccf25b7a9ad0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Samaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Samaria> <http://telicent.io/ontology/primaryName> "Samaria" .
<https://starwars.com#planet_Samaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

