Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Smarteel> <http://telicent.io/ontology/primaryName> "Smarteel" .
<https://starwars.com#planet_Smarteel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U14> .
<https://starwars.com#planet_Smarteel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Smarteel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5cf7d6f5-d38a-479f-a9fd-0413fb64040d> .
<https://starwars.com#planet_Smarteel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5cf7d6f5-d38a-479f-a9fd-0413fb64040d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Smarteel> <http://www.w3.org/2000/01/rdf-schema#comment> "Smarteel was a desert planet in Wild Space. " .
<https://starwars.com#5cf7d6f5-d38a-479f-a9fd-0413fb64040d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Smarteel"^^<http://www.w3.org/2001/XMLSchema#string> .

