Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#ab1d04ac-274c-4158-a477-23230dfcbb56> <http://ies.data.gov.uk/ontology/ies4#representationValue> "D'ian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Dian> <http://telicent.io/ontology/primaryName> "D'ian" .
<https://starwars.com#ab1d04ac-274c-4158-a477-23230dfcbb56> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab1d04ac-274c-4158-a477-23230dfcbb56> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Dian> <http://www.w3.org/2000/01/rdf-schema#comment> "Sen III, best known as D'ian, was a planet with balmy weather and shallow seas that was located within the D'ian system of the Outer Rim Territories. After the rise of the Galactic Empire, which formed in 19 BBY, the planet came to be part of the Corporate Sector, an area of space controlled by the Corporate Sector Authority. While a part of the Corporate Sector, D'ian became a thriving merchant world with several successful business schools. " .

