Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Boudolayz> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4be35248-ea75-46cb-a8c3-eecb1611cefb> .
<https://starwars.com#4be35248-ea75-46cb-a8c3-eecb1611cefb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Boudolayz> <http://www.w3.org/2000/01/rdf-schema#comment> "Boudolayz was a planet in the Colonies. " .
<https://starwars.com#4be35248-ea75-46cb-a8c3-eecb1611cefb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Boudolayz"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Boudolayz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Boudolayz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Boudolayz> <http://telicent.io/ontology/primaryName> "Boudolayz" .
<https://starwars.com#planet_Boudolayz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

