Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chibias> <http://telicent.io/ontology/primaryName> "Chibias" .
<https://starwars.com#planet_Chibias> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ccbf82b5-8486-4269-9a9c-5c23a627c3de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chibias"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chibias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#planet_Chibias> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ccbf82b5-8486-4269-9a9c-5c23a627c3de> .
<https://starwars.com#planet_Chibias> <http://www.w3.org/2000/01/rdf-schema#comment> "Chibias was a Mid Rim world near Sibisime. " .
<https://starwars.com#planet_Chibias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sombure> .
<https://starwars.com#sector_Sombure> <http://telicent.io/ontology/primaryName> "Sombure" .
<https://starwars.com#ccbf82b5-8486-4269-9a9c-5c23a627c3de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sombure> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Sombure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

