Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0176e746-b46f-4c8d-9cee-0929701d44a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Argai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Argai> <http://telicent.io/ontology/primaryName> "Argai" .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Argai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Argai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .
<https://starwars.com#planet_Argai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0176e746-b46f-4c8d-9cee-0929701d44a8> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Argai> <http://www.w3.org/2000/01/rdf-schema#comment> "Argai was a planet located in the Cronese Mandate of the Outer Rim. It was best known for having been the homeworld of the ancient pre-Republic conqueror Xim the Despot, and the first capital of his empire. " .
<https://starwars.com#0176e746-b46f-4c8d-9cee-0929701d44a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Argai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .

