Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kanz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bimmiel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#906ec7c7-1933-47ef-876c-661327f57bf8> .
<https://starwars.com#planet_Bimmiel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kanz> .
<https://starwars.com#planet_Bimmiel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bimmiel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .
<https://starwars.com#sector_Kanz> <http://telicent.io/ontology/primaryName> "Kanz" .
<https://starwars.com#planet_Bimmiel> <http://www.w3.org/2000/01/rdf-schema#comment> "Bimmiel was an astronomical object located in the Outer Rim Territories and New Territories. Situated in grid square N-4 on the Standard Galactic Grid, Bimmiel was connected through a hyperspace route to the astronomical objects Argazda and Birgis. " .
<https://starwars.com#906ec7c7-1933-47ef-876c-661327f57bf8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kanz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#906ec7c7-1933-47ef-876c-661327f57bf8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bimmiel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bimmiel> <http://telicent.io/ontology/primaryName> "Bimmiel" .

