Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Huldamun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#78da7b0f-5ce8-47a7-a913-b46ea15825e0> .
<https://starwars.com#planet_Huldamun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Huldamun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#78da7b0f-5ce8-47a7-a913-b46ea15825e0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#78da7b0f-5ce8-47a7-a913-b46ea15825e0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Huldamun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Huldamun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Huldamun> <http://www.w3.org/2000/01/rdf-schema#comment> "Huldamun was an industrialized planet in the Arkanis sector of the Outer Rim. It was one of the Regency Worlds. " .
<https://starwars.com#planet_Huldamun> <http://telicent.io/ontology/primaryName> "Huldamun" .

