Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Exodeen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Exodeen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#8a61b31b-3037-42ff-8535-4bc265ae7b8e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Exodeen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8a61b31b-3037-42ff-8535-4bc265ae7b8e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Exodeen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8a61b31b-3037-42ff-8535-4bc265ae7b8e> .
<https://starwars.com#planet_Exodeen> <http://www.w3.org/2000/01/rdf-schema#comment> "Exodeen was an astronomical object located in the Exodeen system within the galaxy's Colonies region that was situated along the Hydian Way. " .
<https://starwars.com#planet_Exodeen> <http://telicent.io/ontology/primaryName> "Exodeen" .
<https://starwars.com#planet_Exodeen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

