Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Arkuda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab613eff-08d1-4847-bf8c-929a8874c413> .
<https://starwars.com#planet_Arkuda> <http://telicent.io/ontology/primaryName> "Arkuda" .
<https://starwars.com#ab613eff-08d1-4847-bf8c-929a8874c413> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Arkuda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Arkuda> <http://www.w3.org/2000/01/rdf-schema#comment> "Arkuda was a small rocky planet in the Gordian Reach inhabited by the Arkudans. The planet was renowned for its nighttime view of the stars, due to its proximity to the Roil, a large stellar nursery in the Reach. Arkuda was also one endpoint to the Korphir Trace which pushed through the Roil. " .
<https://starwars.com#ab613eff-08d1-4847-bf8c-929a8874c413> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arkuda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arkuda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Arkuda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

