Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Entuur> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d1204186-e8f5-41a2-ad09-b0653e85b202> .
<https://starwars.com#sector_Kesh> <http://telicent.io/ontology/primaryName> "Kesh" .
<https://starwars.com#planet_Entuur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Entuur> <http://www.w3.org/2000/01/rdf-schema#comment> "Entuur was a planet inhabited by the Human race known as the Entuurans. " .
<https://starwars.com#sector_Kesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#d1204186-e8f5-41a2-ad09-b0653e85b202> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Entuur"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kesh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Entuur> <http://telicent.io/ontology/primaryName> "Entuur" .
<https://starwars.com#planet_Entuur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L6> .
<https://starwars.com#planet_Entuur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kesh> .
<https://starwars.com#d1204186-e8f5-41a2-ad09-b0653e85b202> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

