Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Najiba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#4cd873a7-1bc3-4c18-bf8b-a01d1f8a288e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Najiba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Najiba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#planet_Najiba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4cd873a7-1bc3-4c18-bf8b-a01d1f8a288e> .
<https://starwars.com#4cd873a7-1bc3-4c18-bf8b-a01d1f8a288e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Najiba> <http://www.w3.org/2000/01/rdf-schema#comment> "Najiba was the home planet of Corovene Manakor, a Troglof who worked for the InterGalactic Banking Clan. During the Imperial Era, the planet was occupied by the Galactic Empire, and Manakor participated in a heist on Scipio in an attempt to secure funds to help liberate it. " .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Najiba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Najiba> <http://telicent.io/ontology/primaryName> "Najiba" .

