Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ixtlar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#43e45861-3f58-4cdb-b621-0b8490add038> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ixtlar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ixtlar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Ixtlar> <http://telicent.io/ontology/primaryName> "Ixtlar" .
<https://starwars.com#planet_Ixtlar> <http://www.w3.org/2000/01/rdf-schema#comment> "Ixtlar was an astronomical object located in the galaxy's Core Worlds, along the Corellian Run, which connected it to Coruscant. " .
<https://starwars.com#planet_Ixtlar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#43e45861-3f58-4cdb-b621-0b8490add038> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ixtlar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#43e45861-3f58-4cdb-b621-0b8490add038> .

