Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Guiteica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Guiteica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#a91d5ba6-c520-4699-9989-180daf34d7b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Guiteica"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Guiteica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Guiteica> <http://telicent.io/ontology/primaryName> "Guiteica" .
<https://starwars.com#planet_Guiteica> <http://www.w3.org/2000/01/rdf-schema#comment> "Guiteica was the homeworld of the Bitthævrian. Historically, Kaleesh warlords took roggwarts from Guiteica as trophies. " .
<https://starwars.com#planet_Guiteica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a91d5ba6-c520-4699-9989-180daf34d7b7> .
<https://starwars.com#a91d5ba6-c520-4699-9989-180daf34d7b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

