Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Devon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5eee119-afb1-40d0-aad3-294b3729dae7> .
<https://starwars.com#14257b0f-daf2-4e52-99fb-72da30e89f51> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#14257b0f-daf2-4e52-99fb-72da30e89f51> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .
<https://starwars.com#planet_Devon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#b5eee119-afb1-40d0-aad3-294b3729dae7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Devon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Devon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#b5eee119-afb1-40d0-aad3-294b3729dae7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Devon> <http://www.w3.org/2000/01/rdf-schema#comment> "The Devon were a sentient species native to Teagan. Doctor Tobias was a Devon. " .
<https://starwars.com#14257b0f-daf2-4e52-99fb-72da30e89f51> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_L5> <http://telicent.io/ontology/primaryName> "L5" .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Devon> <http://telicent.io/ontology/primaryName> "Devon" .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Devon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

