Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chandaar> <http://telicent.io/ontology/primaryName> "Chandaar" .
<https://starwars.com#planet_Chandaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Chandaar was the throneworld of the Kingdom of Cron following the death of Xim the Despot, it had been conquered by Xim's father. Many years later, it became capital of the Cronese Mandate under the Galactic Empire and was the headquarters of numerous Cronese mining companies. It was known as the 'Jewel of the Tion', but by the time of the Galactic Civil War, the Cronese Kings were mere figureheads and the planet was a polluted urban world, covered with both decaying cities and ancient ruins. " .
<https://starwars.com#6be59156-d58b-4f14-9fcf-ae0cacf07b95> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chandaar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6be59156-d58b-4f14-9fcf-ae0cacf07b95> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chandaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Chandaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Chandaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6be59156-d58b-4f14-9fcf-ae0cacf07b95> .
<https://starwars.com#planet_Chandaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .

