Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Duroon> <http://telicent.io/ontology/primaryName> "Duroon" .
<https://starwars.com#planet_Duroon> <http://www.w3.org/2000/01/rdf-schema#comment> "Duroon was a planet in Corporate Sector visited by Han Solo in 2 BBY. " .
<https://starwars.com#2cc67c9b-1f89-4b8e-b8dd-bc304d2fb894> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Duroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Duroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#2cc67c9b-1f89-4b8e-b8dd-bc304d2fb894> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Duroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Duroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Duroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2cc67c9b-1f89-4b8e-b8dd-bc304d2fb894> .

