Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a82ecc51-00bd-4612-9f51-097c732b0d93> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Triton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mayagil> .
<https://starwars.com#planet_Triton> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a82ecc51-00bd-4612-9f51-097c732b0d93> .
<https://starwars.com#sector_Mayagil> <http://telicent.io/ontology/primaryName> "Mayagil" .
<https://starwars.com#sector_Mayagil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Triton> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Mayagil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Triton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#planet_Triton> <http://telicent.io/ontology/primaryName> "Triton" .
<https://starwars.com#planet_Triton> <http://www.w3.org/2000/01/rdf-schema#comment> "Triton was an astronomical object in the galaxy's Outer Rim Territories, situated on the Rimma Trade Route. " .
<https://starwars.com#a82ecc51-00bd-4612-9f51-097c732b0d93> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Triton"^^<http://www.w3.org/2001/XMLSchema#string> .

