Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Harloen> <http://telicent.io/ontology/primaryName> "Harloen" .
<https://starwars.com#planet_Harloen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#883cee83-2446-4869-ab0b-528ffb7ae5b9> .
<https://starwars.com#planet_Harloen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belsmuth> .
<https://starwars.com#sector_Belsmuth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Belsmuth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#883cee83-2446-4869-ab0b-528ffb7ae5b9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Harloen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#883cee83-2446-4869-ab0b-528ffb7ae5b9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Harloen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Belsmuth> <http://telicent.io/ontology/primaryName> "Belsmuth" .
<https://starwars.com#planet_Harloen> <http://www.w3.org/2000/01/rdf-schema#comment> "Harloen was a planet in the Belsmuth sector of the Outer Rim Territories. It was considered to be the swoop racing capital of the Outer Rim. " .
<https://starwars.com#planet_Harloen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .

