Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Botajef> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#d6ef8889-c3da-44cd-805e-447301322b71> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Belsmuth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Botajef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Belsmuth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Botajef> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belsmuth> .
<https://starwars.com#planet_Botajef> <http://telicent.io/ontology/primaryName> "Botajef" .
<https://starwars.com#planet_Botajef> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d6ef8889-c3da-44cd-805e-447301322b71> .
<https://starwars.com#d6ef8889-c3da-44cd-805e-447301322b71> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Botajef"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Belsmuth> <http://telicent.io/ontology/primaryName> "Belsmuth" .
<https://starwars.com#planet_Botajef> <http://www.w3.org/2000/01/rdf-schema#comment> "Botajef was an ecumenopolis planet located in the Belsmuth sector of the Outer Rim Territories, at the confluence of the Salin Corridor and Hydian Way hyperspace routes. It was the homeworld of the Jefi species and the headquarters of Botajef Shipyards. " .

