Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a5b74fc1-3b0b-4b47-abdf-9fe39fbb699d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Devaron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Devaron> <http://telicent.io/ontology/primaryName> "Devaron" .
<https://starwars.com#sector_Duluur> <http://telicent.io/ontology/primaryName> "Duluur" .
<https://starwars.com#a5b74fc1-3b0b-4b47-abdf-9fe39fbb699d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Devaron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a5b74fc1-3b0b-4b47-abdf-9fe39fbb699d> .
<https://starwars.com#sector_Duluur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Devaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Duluur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Devaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Devaron> <http://www.w3.org/2000/01/rdf-schema#comment> "Forest planet with an ancient Jedi Temple. Home to the horned Devaronian species." .
<https://starwars.com#planet_Devaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Duluur> .

