Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#35d3f5f8-dd5e-4ff3-bd24-72e2dbf9a18c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Void Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dohlbani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_VoidStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_VoidStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#planet_VoidStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#35d3f5f8-dd5e-4ff3-bd24-72e2dbf9a18c> .
<https://starwars.com#planet_VoidStation> <http://telicent.io/ontology/primaryName> "Void Station" .
<https://starwars.com#planet_VoidStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dohlbani> .
<https://starwars.com#planet_VoidStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Void Station was a palace-like space station built on an asteroid, located near an unidentified planet. " .
<https://starwars.com#35d3f5f8-dd5e-4ff3-bd24-72e2dbf9a18c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dohlbani> <http://telicent.io/ontology/primaryName> "Dohlbani" .
<https://starwars.com#sector_Dohlbani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

