Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NarChunna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_NarChunna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NarChunna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#6bb2c87e-bc64-424d-9831-f4ce3ba57cac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#6bb2c87e-bc64-424d-9831-f4ce3ba57cac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nar Chunna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NarChunna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6bb2c87e-bc64-424d-9831-f4ce3ba57cac> .
<https://starwars.com#planet_NarChunna> <http://telicent.io/ontology/primaryName> "Nar Chunna" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_NarChunna> <http://www.w3.org/2000/01/rdf-schema#comment> "Nar Chunna was a planet located in the Bootana Hutta region of Hutt Space. It served primarily as a trade outpost and was said to be awash in priceless artifacts. " .

