Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zhar> <http://telicent.io/ontology/primaryName> "Zhar" .
<https://starwars.com#planet_Zhar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#48397108-c505-44b1-8f0f-b2c6be823646> .
<https://starwars.com#planet_Zhar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zhar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cadavine> .
<https://starwars.com#planet_Zhar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P17> .
<https://starwars.com#sector_Cadavine> <http://telicent.io/ontology/primaryName> "Cadavine" .
<https://starwars.com#48397108-c505-44b1-8f0f-b2c6be823646> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zhar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zhar> <http://www.w3.org/2000/01/rdf-schema#comment> "Zhar was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Cadavine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#48397108-c505-44b1-8f0f-b2c6be823646> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Cadavine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

