Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Llanic> <http://telicent.io/ontology/primaryName> "Llanic" .
<https://starwars.com#462dc2f2-3252-4b54-8139-2513bcd9adf7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Llanic"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Karthakk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Llanic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Karthakk> <http://telicent.io/ontology/primaryName> "Karthakk" .
<https://starwars.com#planet_Llanic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#planet_Llanic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Karthakk> .
<https://starwars.com#462dc2f2-3252-4b54-8139-2513bcd9adf7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Llanic> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#462dc2f2-3252-4b54-8139-2513bcd9adf7> .
<https://starwars.com#sector_Karthakk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Llanic> <http://www.w3.org/2000/01/rdf-schema#comment> "Llanic was a planet located in the Llanic system within the galaxy's Outer Rim Territories. It was situated at the intersection of the Llanic Spice Route and the Triellus Trade Route. Bustling with smugglers and other shady characters, Llanic was considered to be similar to Mos Eisley. The Galactic Empire kept watch on Llanic due to the illicit credits that circulated there. " .

