Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_Wyndigal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Wyndigal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#62d8f8c2-71fe-477b-b02b-da1954807df8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Wyndigal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#planet_Wyndigal> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Wyndigal> <http://telicent.io/ontology/primaryName> "Wyndigal" .
<https://starwars.com#planet_Wyndigal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#62d8f8c2-71fe-477b-b02b-da1954807df8> .
<https://starwars.com#62d8f8c2-71fe-477b-b02b-da1954807df8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wyndigal"^^<http://www.w3.org/2001/XMLSchema#string> .

