Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Zarracina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Selsor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Selsor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zarracina> .
<https://starwars.com#planet_Selsor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2392e819-fd57-4a58-836d-a86ace25587b> .
<https://starwars.com#2392e819-fd57-4a58-836d-a86ace25587b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Selsor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Zarracina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Selsor> <http://telicent.io/ontology/primaryName> "Selsor" .
<https://starwars.com#2392e819-fd57-4a58-836d-a86ace25587b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Selsor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#sector_Zarracina> <http://telicent.io/ontology/primaryName> "Zarracina" .
<https://starwars.com#planet_Selsor> <http://www.w3.org/2000/01/rdf-schema#comment> "Selsor was a terrestrial astronomical object located in the Selsor system, a part of the Zarracina sector in the Trailing Sectors portion of the Expansion Region. It featured several continents. " .

