Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fresia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Fresia> <http://www.w3.org/2000/01/rdf-schema#comment> "Fresia was a world with a human population. During the Clone Wars, it was represented in the Galactic Senate by Seti Ashgad. Jaldine Gerams was from this world, and joined the Alliance to Restore the Republic when they arrived on Fresia. " .
<https://starwars.com#planet_Fresia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fresia> <http://telicent.io/ontology/primaryName> "Fresia" .
<https://starwars.com#fc396669-9280-42df-bd1b-79b82874c934> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fresia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fresia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fc396669-9280-42df-bd1b-79b82874c934> .
<https://starwars.com#planet_Fresia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#fc396669-9280-42df-bd1b-79b82874c934> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

