Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_StarForgeNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_StarForgeNebula> <http://telicent.io/ontology/primaryName> "StarForge Nebula" .
<https://starwars.com#planet_StarForgeNebula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_StarForgeNebula> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#68fbaff5-6332-4ec1-a8f8-58e301a9d8f1> .
<https://starwars.com#68fbaff5-6332-4ec1-a8f8-58e301a9d8f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "StarForge Nebula"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ado> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#68fbaff5-6332-4ec1-a8f8-58e301a9d8f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Ado> <http://telicent.io/ontology/primaryName> "Ado" .
<https://starwars.com#sector_Ado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_StarForgeNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ado> .
<https://starwars.com#planet_StarForgeNebula> <http://www.w3.org/2000/01/rdf-schema#comment> "The StarForge Nebula was a nebula located in Ado sector in the Mid Rim, along the Ado Spine hyperlane. StarForge Station was hidden in the nebula. Although its name was similar to that of the Star Forge, an ancient automated shipyard built by the Rakata, no relation existed; the nebula took its name from the large number of stars undergoing stellar formation within it. " .

