Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8bf65219-6ff6-4a22-a4c7-c6b564fc9889> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dakshee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dakshee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Dakshee> <http://telicent.io/ontology/primaryName> "Dakshee" .
<https://starwars.com#planet_Dakshee> <http://www.w3.org/2000/01/rdf-schema#comment> "Dakshee was the sector capital of the Barma sector. An Imperial-held planet in the Colonies region, it was marked by constant unrest and agitation against Imperial rule. Gerald Weizel, Imperial governor of Chandrila, was once the governor of Dakshee, where he resolved the Brella Temior crisis. Weizel discovered that several union heads were ringleaders of the terrorist group Justice Action Network, and ended the situation without bloodshed. " .
<https://starwars.com#planet_Dakshee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8bf65219-6ff6-4a22-a4c7-c6b564fc9889> .
<https://starwars.com#8bf65219-6ff6-4a22-a4c7-c6b564fc9889> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dakshee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dakshee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

