Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Kamur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kamur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Kamur> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#41c46112-ebf8-4bc5-9b1b-1932c039beb1> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kamur> <http://www.w3.org/2000/01/rdf-schema#comment> "Kamur was an agricultural world owned by House Petro, and the homeworld of the Thanu species, which inhabited the planet's volcanic regions. " .
<https://starwars.com#41c46112-ebf8-4bc5-9b1b-1932c039beb1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kamur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#41c46112-ebf8-4bc5-9b1b-1932c039beb1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kamur"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kamur> <http://telicent.io/ontology/primaryName> "Kamur" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

