Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Koba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J16> .
<https://starwars.com#planet_Koba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#270d5281-23e5-4ed1-8137-6700f53e94d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Koba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Koba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Narrant> .
<https://starwars.com#planet_Koba> <http://telicent.io/ontology/primaryName> "Koba" .
<https://starwars.com#sector_Narrant> <http://telicent.io/ontology/primaryName> "Narrant" .
<https://starwars.com#sector_Narrant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#270d5281-23e5-4ed1-8137-6700f53e94d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Koba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#270d5281-23e5-4ed1-8137-6700f53e94d2> .
<https://starwars.com#planet_Koba> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_Narrant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

