Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fabrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Circarpous> .
<https://starwars.com#sector_Circarpous> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Fabrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fabrin> <http://telicent.io/ontology/primaryName> "Fabrin" .
<https://starwars.com#planet_Fabrin> <http://www.w3.org/2000/01/rdf-schema#comment> "Fabrin was a world located on the Nanth'ri Trade Route, situated within the Expansion Region. The world was defended by the Resistance's Cobalt Squadron. " .
<https://starwars.com#planet_Fabrin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c291c3ba-3356-418b-853c-13bebe563b33> .
<https://starwars.com#sector_Circarpous> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Fabrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#c291c3ba-3356-418b-853c-13bebe563b33> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c291c3ba-3356-418b-853c-13bebe563b33> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fabrin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Circarpous> <http://telicent.io/ontology/primaryName> "Circarpous" .

