Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TheRing> <http://telicent.io/ontology/primaryName> "The Ring" .
<https://starwars.com#8f6c95fa-c94d-4046-9bcf-c1ef5130ae9c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TheRing> <http://www.w3.org/2000/01/rdf-schema#comment> "The Ring was an astronomical object found within the Anoat sector of the galaxy's Outer Rim Territories. It was situated inside the Ivax Nebula and was positioned relatively close to the planets Gerrenthum and Nothoiin. " .
<https://starwars.com#planet_TheRing> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8f6c95fa-c94d-4046-9bcf-c1ef5130ae9c> .
<https://starwars.com#planet_TheRing> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_TheRing> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_TheRing> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#8f6c95fa-c94d-4046-9bcf-c1ef5130ae9c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Ring"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

