Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Denevar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Denevar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5393d8ce-7ed0-46c5-887f-1adcc3fe8a29> .
<https://starwars.com#5393d8ce-7ed0-46c5-887f-1adcc3fe8a29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5393d8ce-7ed0-46c5-887f-1adcc3fe8a29> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Denevar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Denevar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Denevar> <http://www.w3.org/2000/01/rdf-schema#comment> "Denevar was a planet. During the Galactic Civil War, the planet was controlled by Imperial Prefect Adar. " .
<https://starwars.com#planet_Denevar> <http://telicent.io/ontology/primaryName> "Denevar" .
<https://starwars.com#planet_Denevar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .

