Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Sarka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#4c4845e6-b530-449a-9179-568a4ae39cb4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trasse"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trasse> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4c4845e6-b530-449a-9179-568a4ae39cb4> .
<https://starwars.com#4c4845e6-b530-449a-9179-568a4ae39cb4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trasse> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sarka> <http://telicent.io/ontology/primaryName> "Sarka" .
<https://starwars.com#planet_Trasse> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sarka> .
<https://starwars.com#planet_Trasse> <http://www.w3.org/2000/01/rdf-schema#comment> "Trasse was a planet in the Mid Rim. During the Galactic Civil War between the Galactic Empire and the Alliance to Restore the Republic, the Alliance was forced to retreat from its failed Mid Rim Offensive, an operation by the Alliance and the Mid Rim revolutionaries to take control of the Mid Rim. The Alliance was forced to retreat from many worlds including Jeyell, Durkteel, Ord Tiddell, Charros IV, and Pothor. Several revolutionaries evacuated with Alliance forces, although many decided to remain on their planets to harass the Empire. " .
<https://starwars.com#planet_Trasse> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#planet_Trasse> <http://telicent.io/ontology/primaryName> "Trasse" .
<https://starwars.com#sector_Sarka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

