Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Marzoon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Marzoon> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Marzoon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bce15d17-ee25-4904-ab86-566655ed1f01> .
<https://starwars.com#planet_Marzoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Marzoon> .
<https://starwars.com#bce15d17-ee25-4904-ab86-566655ed1f01> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Marzoon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Marzoon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Marzoon> <http://telicent.io/ontology/primaryName> "Marzoon" .
<https://starwars.com#planet_Marzoon> <http://telicent.io/ontology/primaryName> "Marzoon" .
<https://starwars.com#sector_Marzoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Marzoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I16> .
<https://starwars.com#bce15d17-ee25-4904-ab86-566655ed1f01> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

