Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e10b1ceb-7c8e-4495-aaca-e9aae8cbe865> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drongar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e10b1ceb-7c8e-4495-aaca-e9aae8cbe865> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Drongar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e10b1ceb-7c8e-4495-aaca-e9aae8cbe865> .
<https://starwars.com#planet_Drongar> <http://telicent.io/ontology/primaryName> "Drongar" .
<https://starwars.com#planet_Drongar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drongar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T5> .
<https://starwars.com#planet_Drongar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Drongar> <http://www.w3.org/2000/01/rdf-schema#comment> "Drongar was an astronomical object located in the Outer Rim Territories of the galaxy, positioned at the coordinates T-5 on the Standard Galactic Grid. " .

