Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Siskeen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#218ce9b9-981b-4ab9-aa5f-3a4996660958> .
<https://starwars.com#sector_Hunnovers> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#218ce9b9-981b-4ab9-aa5f-3a4996660958> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Siskeen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Siskeen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#218ce9b9-981b-4ab9-aa5f-3a4996660958> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Hunnovers> <http://telicent.io/ontology/primaryName> "Hunnovers" .
<https://starwars.com#planet_Siskeen> <http://telicent.io/ontology/primaryName> "Siskeen" .
<https://starwars.com#sector_Hunnovers> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Siskeen> <http://www.w3.org/2000/01/rdf-schema#comment> "Siskeen was an astronomical object in the Outer Rim Territories of the galaxy, positioned at the coordinates R-17 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Siskeen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hunnovers> .
<https://starwars.com#planet_Siskeen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .

