Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#476bd079-bf64-43c8-b447-81e885d945c5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Norkronia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Norkronia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Norkronia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Norkronia> <http://telicent.io/ontology/primaryName> "Norkronia" .
<https://starwars.com#planet_Norkronia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Norkronia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#476bd079-bf64-43c8-b447-81e885d945c5> .
<https://starwars.com#planet_Norkronia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#476bd079-bf64-43c8-b447-81e885d945c5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

