Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Iliabath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#planet_Iliabath> <http://telicent.io/ontology/primaryName> "Iliabath" .
<https://starwars.com#planet_Iliabath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mortex> .
<https://starwars.com#planet_Iliabath> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b0e53a2-fc10-48e4-9257-b8908916d98d> .
<https://starwars.com#planet_Iliabath> <http://www.w3.org/2000/01/rdf-schema#comment> "Iliabath was a planet located in the Mortex sector of the Outer Rim Territories. " .
<https://starwars.com#sector_Mortex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3b0e53a2-fc10-48e4-9257-b8908916d98d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Iliabath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3b0e53a2-fc10-48e4-9257-b8908916d98d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iliabath"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mortex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mortex> <http://telicent.io/ontology/primaryName> "Mortex" .

