Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dohu> <http://telicent.io/ontology/primaryName> "Dohu" .
<https://starwars.com#planet_Dohu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dohu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dohu> .
<https://starwars.com#sector_Dohu> <http://telicent.io/ontology/primaryName> "Dohu" .
<https://starwars.com#planet_Dohu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K7> .
<https://starwars.com#sector_Dohu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dohu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d00503a9-bf8b-482c-aa90-1c7f999f2275> .
<https://starwars.com#sector_Dohu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dohu> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#d00503a9-bf8b-482c-aa90-1c7f999f2275> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dohu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d00503a9-bf8b-482c-aa90-1c7f999f2275> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

