Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NarBoSholla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R10> .
<https://starwars.com#21acc1fd-94e5-473f-8189-e685609ffb7d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_NarBoSholla> <http://www.w3.org/2000/01/rdf-schema#comment> "Nar Bo Sholla was a Hutt Space world that was the homeworld of the poisonous spor crawler insect. It was a part of the Hutt Empire twenty-five millennia before the Battle of Yavin. In 25 BBY, the Human Morteos was born on Nar Bo Sholla. Three years later, it became one of the worlds that suffered damage from an infestation of the structure-damaging arthropods known as stone mites. The Nar Bo Sholla system was later conquered by the extra-galactic Yuuzhan Vong during their invasion of the galaxy. " .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NarBoSholla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#21acc1fd-94e5-473f-8189-e685609ffb7d> .
<https://starwars.com#planet_NarBoSholla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#21acc1fd-94e5-473f-8189-e685609ffb7d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nar Bo Sholla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NarBoSholla> <http://telicent.io/ontology/primaryName> "Nar Bo Sholla" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_NarBoSholla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

