Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#29d724a4-78f0-4e41-afa5-8fdb9bb63d52> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#29d724a4-78f0-4e41-afa5-8fdb9bb63d52> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Saffalore"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Saffalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Saffalore> <http://telicent.io/ontology/primaryName> "Saffalore" .
<https://starwars.com#planet_Saffalore> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#29d724a4-78f0-4e41-afa5-8fdb9bb63d52> .
<https://starwars.com#planet_Saffalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Saffalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Saffalore> <http://www.w3.org/2000/01/rdf-schema#comment> "Saffalore was a planet in the Corporate Sector, at one end of the Lucaya Cross. It was one of the Sector's most recent boomworlds. It remained neutral in the Galactic Civil War. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

