Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ahch-To> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E13> .
<https://starwars.com#471000e5-181d-40e5-85f7-27a0e22185b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ahch-To"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ahch-To> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#471000e5-181d-40e5-85f7-27a0e22185b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_E13> <http://telicent.io/ontology/primaryName> "E13" .
<https://starwars.com#grid_E13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#5c4095c1-144b-46c0-abb9-4d75f6f12f5a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "E13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ahch-To> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#471000e5-181d-40e5-85f7-27a0e22185b5> .
<https://starwars.com#region_UnknownRegions> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_Ahch-To> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ahch-To> <http://telicent.io/ontology/primaryName> "Ahch-To" .
<https://starwars.com#grid_E13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_E13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5c4095c1-144b-46c0-abb9-4d75f6f12f5a> .
<https://starwars.com#region_UnknownRegions> <http://telicent.io/ontology/primaryName> "Unknown Regions" .
<https://starwars.com#5c4095c1-144b-46c0-abb9-4d75f6f12f5a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#region_UnknownRegions> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Ahch-To> <http://www.w3.org/2000/01/rdf-schema#comment> "Largely oceanic planet on which Luke Skywalker has been hiding for several years, and the location of the first Jedi Temple and the Tree Library of sacred Jedi texts. Porgs and thala-sirens are among the native species." .

