Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Parshoone> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9e9c7e56-f1c0-428b-9dac-2e746a212dd0> .
<https://starwars.com#planet_Parshoone> <http://www.w3.org/2000/01/rdf-schema#comment> "Parshoone was a planet in the Outer Rim Territories, controlled by the Imperial Remnant. It was an Ubiqtorate contact station. " .
<https://starwars.com#9e9c7e56-f1c0-428b-9dac-2e746a212dd0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Parshoone"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Parshoone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#9e9c7e56-f1c0-428b-9dac-2e746a212dd0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Parshoone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Parshoone> <http://telicent.io/ontology/primaryName> "Parshoone" .
<https://starwars.com#planet_Parshoone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

