Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Xagobah> <http://telicent.io/ontology/primaryName> "Xagobah" .
<https://starwars.com#sector_Mayagil> <http://telicent.io/ontology/primaryName> "Mayagil" .
<https://starwars.com#planet_Xagobah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#sector_Mayagil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0e50b195-43d4-44b6-8f01-ce429c646cb6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mayagil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Xagobah> <http://www.w3.org/2000/01/rdf-schema#comment> "Xagobah was an astronomical object in the Outer Rim Territories which produced war resources for the Galactic Empire during the Galactic Civil War. The Rebel Alliance's 61st Mobile Infantry fought the Empire there as part of a campaign in 3 ABY. In 5 ABY, New Republic forces led by General Ria undertook a campaign against an Imperial-Royalist coalition at the astronomical body. " .
<https://starwars.com#planet_Xagobah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0e50b195-43d4-44b6-8f01-ce429c646cb6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xagobah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Xagobah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e50b195-43d4-44b6-8f01-ce429c646cb6> .
<https://starwars.com#planet_Xagobah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mayagil> .

