Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_B-Foroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0131034b-663d-4271-8ad6-881f07e7b180> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#0131034b-663d-4271-8ad6-881f07e7b180> <http://ies.data.gov.uk/ontology/ies4#representationValue> "B-Foroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_B-Foroon> <http://www.w3.org/2000/01/rdf-schema#comment> "B-Foroon was a mucky world located in the B-Foroon system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. It was situated on the Triellus Trade Route hyperlane, which linked it to the A-Foroon and C-Foroon systems. " .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_B-Foroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_B-Foroon> <http://telicent.io/ontology/primaryName> "B-Foroon" .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#0131034b-663d-4271-8ad6-881f07e7b180> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_B-Foroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_B-Foroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .

