Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalishik> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#35a62d06-1a70-43e0-bcba-9ef73a7ab722> .
<https://starwars.com#planet_Kalishik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalishik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_Kalishik> <http://telicent.io/ontology/primaryName> "Kalishik" .
<https://starwars.com#35a62d06-1a70-43e0-bcba-9ef73a7ab722> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalishik"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#35a62d06-1a70-43e0-bcba-9ef73a7ab722> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kalishik> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalishik was a planet in a system of the same name, located in the Gordian Reach sector of the Outer Rim. It sat on the Ardan Cross hyperspace route. Kalishik was the homeworld of the phocine T'sarki species. " .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kalishik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

