Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#93c26290-6ad5-47a8-970d-823eeda42f89> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Fath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#93c26290-6ad5-47a8-970d-823eeda42f89> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Cantrell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdCantrell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdCantrell> <http://telicent.io/ontology/primaryName> "Ord Cantrell" .
<https://starwars.com#planet_OrdCantrell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Fath> .
<https://starwars.com#planet_OrdCantrell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#93c26290-6ad5-47a8-970d-823eeda42f89> .
<https://starwars.com#sector_Fath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Fath> <http://telicent.io/ontology/primaryName> "Fath" .
<https://starwars.com#planet_OrdCantrell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#planet_OrdCantrell> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Cantrell was an astronomical object located in the galaxy's Outer Rim Territories. " .

