Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Roldalna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vish> .
<https://starwars.com#sector_Vish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Vish> <http://telicent.io/ontology/primaryName> "Vish" .
<https://starwars.com#sector_Vish> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Roldalna> <http://telicent.io/ontology/primaryName> "Roldalna" .
<https://starwars.com#planet_Roldalna> <http://www.w3.org/2000/01/rdf-schema#comment> "The Buzchub Und'l arranged a meeting at the cantina with a group of smugglers, hiring them on behalf of his employer to transport what he believed to be spice. In reality, the cargo was the lethal poison lexonite, and Und'l's employer had the smugglers' freighter sabotaged during their stay on Roldalna in order to later hijack the shipment. " .
<https://starwars.com#a2867e3d-2432-4be6-92d2-f0837ad1ffac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Roldalna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Roldalna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#a2867e3d-2432-4be6-92d2-f0837ad1ffac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Roldalna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Roldalna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2867e3d-2432-4be6-92d2-f0837ad1ffac> .

