Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Merren> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Merren> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Merren> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1cc44dd5-7943-4674-965c-156f4310499c> .
<https://starwars.com#planet_Merren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#1cc44dd5-7943-4674-965c-156f4310499c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#1cc44dd5-7943-4674-965c-156f4310499c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Merren"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Chaykin> <http://telicent.io/ontology/primaryName> "Chaykin" .
<https://starwars.com#planet_Merren> <http://telicent.io/ontology/primaryName> "Merren" .
<https://starwars.com#sector_Chaykin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Chaykin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Merren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chaykin> .

