Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_VarHagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e0b37bd3-d914-4b81-8ed0-5326f0b65526> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e0b37bd3-d914-4b81-8ed0-5326f0b65526> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_VarHagen> <http://telicent.io/ontology/primaryName> "Var Hagen" .
<https://starwars.com#39f04a20-21b8-4b94-9ae7-72b7a6c694ee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alakatha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Alakatha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#39f04a20-21b8-4b94-9ae7-72b7a6c694ee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Alakatha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#39f04a20-21b8-4b94-9ae7-72b7a6c694ee> .
<https://starwars.com#planet_Alakatha> <http://www.w3.org/2000/01/rdf-schema#comment> "Alakatha was a terrestrial astronomical object known for its beaches. Several weeks after the Battle of Endor, while playing the game Who? What? Where? with other New Republic pilots aboard the frigate Hellion's Dare, the pilot Rep Boy claimed that he wished to live until old age and die of heatstroke on the beaches of Alakatha. However, Rep Boy's wish was not fulfilled, as he was killed shortly afterwards by the forces of the Galactic Empire's 204th Imperial Fighter Wing during an attack on the Hellion's Dare. " .
<https://starwars.com#planet_Alakatha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_VarHagen> .
<https://starwars.com#grid_M16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_VarHagen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Alakatha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_M16> <http://telicent.io/ontology/primaryName> "M16" .
<https://starwars.com#planet_Alakatha> <http://telicent.io/ontology/primaryName> "Alakatha" .
<https://starwars.com#grid_M16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e0b37bd3-d914-4b81-8ed0-5326f0b65526> .
<https://starwars.com#grid_M16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

