Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thakwaa> <http://www.w3.org/2000/01/rdf-schema#comment> "Thakwaa was a terrestrial astronomical object located in the Outer Rim Territories and positioned at the coordinates I-19 on the Standard Galactic Grid. The Red Isles was a location on Thakwaa, where the Rebel Alliance pilot Nath Tensent and his astromech droid T5 had to spend a night some time prior to the Battle of Endor, fought in 4 ABY. For protection against flies, T5 convinced Tensent to create an ointment from plant stems, which had a side effect of causing rashes. According to Tensent, nothing interesting occurred during his time on Thakwaa, and the two departed several days later. " .
<https://starwars.com#planet_Thakwaa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tunka> .
<https://starwars.com#planet_Thakwaa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thakwaa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I19> .
<https://starwars.com#planet_Thakwaa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aad1b2c9-6720-4fd2-ad32-c1db46ffb495> .
<https://starwars.com#planet_Thakwaa> <http://telicent.io/ontology/primaryName> "Thakwaa" .
<https://starwars.com#aad1b2c9-6720-4fd2-ad32-c1db46ffb495> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thakwaa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tunka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Tunka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Tunka> <http://telicent.io/ontology/primaryName> "Tunka" .
<https://starwars.com#aad1b2c9-6720-4fd2-ad32-c1db46ffb495> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

