Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sacorria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d5d99acb-1922-425a-aa18-2daacbdd509e> .
<https://starwars.com#d5d99acb-1922-425a-aa18-2daacbdd509e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sacorria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sacorria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d5d99acb-1922-425a-aa18-2daacbdd509e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sacorria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Sacorria> <http://telicent.io/ontology/primaryName> "Sacorria" .
<https://starwars.com#planet_Sacorria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Sacorria> <http://www.w3.org/2000/01/rdf-schema#comment> "Sacorria was an agriworld in the Sacorrian system, located on the fringe of the Corellian sector. " .

