Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cabce7bd-222d-401f-802c-90465f7e8435> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gestrex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gestrex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gestrex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cabce7bd-222d-401f-802c-90465f7e8435> .
<https://starwars.com#planet_Gestrex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T9> .
<https://starwars.com#cabce7bd-222d-401f-802c-90465f7e8435> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gestrex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#planet_Gestrex> <http://telicent.io/ontology/primaryName> "Gestrex" .
<https://starwars.com#planet_Gestrex> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

