Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Usnia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Usnia> <http://telicent.io/ontology/primaryName> "Usnia" .
<https://starwars.com#317573d9-9859-462a-ae96-5f3499158848> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Usnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#317573d9-9859-462a-ae96-5f3499158848> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Usnia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Usnia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#317573d9-9859-462a-ae96-5f3499158848> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Usnia> <http://www.w3.org/2000/01/rdf-schema#comment> "Usnia was a forested planet located in the Usnia system of the Senex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. It was also situated close to the Tangles, an area of intersecting hyperlanes. Usnia was connected via hyperspace routes to the Dornean, Trenthellix, and Varadan systems. It was declared a nature reserve by House Petro, one of the aristocratic Ancient Houses of the Senex-Juvex region. " .
<https://starwars.com#planet_Usnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .

