Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_AsmeruAnomaly> <http://telicent.io/ontology/primaryName> "Asmeru Anomaly" .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_AsmeruAnomaly> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#0b462b79-ae9e-4158-b693-8426b7710f28> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AsmeruAnomaly> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0b462b79-ae9e-4158-b693-8426b7710f28> .
<https://starwars.com#planet_AsmeruAnomaly> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_AsmeruAnomaly> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_AsmeruAnomaly> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0b462b79-ae9e-4158-b693-8426b7710f28> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Asmeru Anomaly"^^<http://www.w3.org/2001/XMLSchema#string> .

