Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sanbra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e213db6-2fe4-4e18-902c-da8d44e0501e> .
<https://starwars.com#sector_Sanbra> <http://telicent.io/ontology/primaryName> "Sanbra" .
<https://starwars.com#planet_Sanbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sanbra> .
<https://starwars.com#planet_Sanbra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sanbra> <http://telicent.io/ontology/primaryName> "Sanbra" .
<https://starwars.com#0e213db6-2fe4-4e18-902c-da8d44e0501e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sanbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#sector_Sanbra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sanbra> <http://www.w3.org/2000/01/rdf-schema#comment> "Sanbra was the location of the University of Sanbra. It also the location of the Shoapy Hostel. " .
<https://starwars.com#sector_Sanbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#0e213db6-2fe4-4e18-902c-da8d44e0501e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sanbra"^^<http://www.w3.org/2001/XMLSchema#string> .

