Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vaathkree> <http://www.w3.org/2000/01/rdf-schema#comment> "Vaathkree was an astronomical object located in the regions known as the Outer Rim Territories and the Slice. It was also situated in the grid square S-8 of the Standard Galactic Grid. A hyperspace route linked Vaathkree to the celestial body Boonta and the planet Klatooine. " .
<https://starwars.com#sector_Periphery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#2ccd4ed4-2212-4d38-89f6-f8bf9051d67b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vaathkree> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2ccd4ed4-2212-4d38-89f6-f8bf9051d67b> .
<https://starwars.com#planet_Vaathkree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#sector_Periphery> <http://telicent.io/ontology/primaryName> "Periphery" .
<https://starwars.com#sector_Periphery> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vaathkree> <http://telicent.io/ontology/primaryName> "Vaathkree" .
<https://starwars.com#planet_Vaathkree> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2ccd4ed4-2212-4d38-89f6-f8bf9051d67b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vaathkree"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vaathkree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Periphery> .

