Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Asrat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#68c70964-6fda-4c11-a2d5-8dcf3c701cd8> .
<https://starwars.com#planet_Asrat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Asrat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Asrat> <http://www.w3.org/2000/01/rdf-schema#comment> "Asrat was a planet where the Holy Children of Asrat were worshiped. The Children opposed the New Order and were targeted for assassination by the Galactic Empire. Dengar left service as an Imperial assassin rather than kill the Children. " .
<https://starwars.com#grid_N8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5b0a3321-5df3-4a9d-bac1-a644cb45c581> .
<https://starwars.com#grid_N8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#5b0a3321-5df3-4a9d-bac1-a644cb45c581> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Asrat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#68c70964-6fda-4c11-a2d5-8dcf3c701cd8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Asrat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#68c70964-6fda-4c11-a2d5-8dcf3c701cd8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5b0a3321-5df3-4a9d-bac1-a644cb45c581> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Asrat> <http://telicent.io/ontology/primaryName> "Asrat" .
<https://starwars.com#grid_N8> <http://telicent.io/ontology/primaryName> "N8" .

