Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PerLupelo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_PerLupelo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PerLupelo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2590e666-3151-46ee-8696-51625685f23e> .
<https://starwars.com#2590e666-3151-46ee-8696-51625685f23e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Per Lupelo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PerLupelo> <http://telicent.io/ontology/primaryName> "Per Lupelo" .
<https://starwars.com#planet_PerLupelo> <http://www.w3.org/2000/01/rdf-schema#comment> "Per Lupelo was a cosmopolitan planet in the Per Lupelo system. It was dotted by a number of clean cities and bodies of water, and it was also dotted with a number of mountain ranges. A crime organization led by the gangster Raze had its headquarters on the planet at the height of the Galactic Civil War. " .
<https://starwars.com#2590e666-3151-46ee-8696-51625685f23e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PerLupelo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

