Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Doreen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#3be24f36-481d-4854-aa4c-bd5f98ef955f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Doreen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3be24f36-481d-4854-aa4c-bd5f98ef955f> .
<https://starwars.com#planet_Doreen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3be24f36-481d-4854-aa4c-bd5f98ef955f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Doreen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Doreen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Doreen> <http://www.w3.org/2000/01/rdf-schema#comment> "Doreen was an ocean planet in the Tangles region of Senex sector in the Mid Rim. The planet was controlled by the aristocratic House Petro. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Doreen> <http://telicent.io/ontology/primaryName> "Doreen" .

