Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#grid_H15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#d885f55b-14d9-48b6-8390-9a2347bf32e5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Codia> <http://www.w3.org/2000/01/rdf-schema#comment> "Codia was a Mid Rim Territories planet situated in grid square H-15 of the Standard Galactic Grid. It shared its name with both the Codian Moon and the location known as New Codia. At some point, the historian Eloc Throno noted the location of Codia on a map of the galaxy included in his book Traveler's Guide to Batuu. " .
<https://starwars.com#planet_Codia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H15> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a42b9ed1-7ff3-4435-b18b-fffe1c444492> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_H15> <http://telicent.io/ontology/primaryName> "H15" .
<https://starwars.com#grid_H15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d885f55b-14d9-48b6-8390-9a2347bf32e5> .
<https://starwars.com#planet_Codia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a42b9ed1-7ff3-4435-b18b-fffe1c444492> .
<https://starwars.com#planet_Codia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#a42b9ed1-7ff3-4435-b18b-fffe1c444492> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Codia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Codia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d885f55b-14d9-48b6-8390-9a2347bf32e5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Codia> <http://telicent.io/ontology/primaryName> "Codia" .
<https://starwars.com#grid_H15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

