Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Taroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54a44b7b-033c-47b9-b890-1ef57706f34c> .
<https://starwars.com#planet_Taroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N20> .
<https://starwars.com#sector_Rseik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Rseik> <http://telicent.io/ontology/primaryName> "Rseik" .
<https://starwars.com#planet_Taroon> <http://www.w3.org/2000/01/rdf-schema#comment> "Taroon was a male Rutanian and the son of King Frane of Rutan. " .
<https://starwars.com#54a44b7b-033c-47b9-b890-1ef57706f34c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Taroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#54a44b7b-033c-47b9-b890-1ef57706f34c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Rseik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Taroon> <http://telicent.io/ontology/primaryName> "Taroon" .
<https://starwars.com#planet_Taroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rseik> .

