Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Formos> <http://telicent.io/ontology/primaryName> "Formos" .
<https://starwars.com#74743d0d-62ff-42d3-b95e-afefba882837> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Formos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#74743d0d-62ff-42d3-b95e-afefba882837> .
<https://starwars.com#planet_Formos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Formos> <http://www.w3.org/2000/01/rdf-schema#comment> "Formos was an Outer Rim Territories astronomical object lying on the hyperspace routes known as the Pabol Sleheyron and the Triellus Trade Route. During the reign of the Galactic Empire, Formos served as a processing location for spice transported off of the planet Kessel. Following the collapse of the Empire, heavy fighting between competitors in the spice trade engulfed Formos. " .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#planet_Formos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Formos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#74743d0d-62ff-42d3-b95e-afefba882837> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Formos"^^<http://www.w3.org/2001/XMLSchema#string> .

