Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Triewahl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fff3faf7-8935-42fc-a6cb-0ebc6f38c58e> .
<https://starwars.com#planet_Triewahl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Triewahl> <http://telicent.io/ontology/primaryName> "Triewahl" .
<https://starwars.com#planet_Triewahl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Homon> .
<https://starwars.com#fff3faf7-8935-42fc-a6cb-0ebc6f38c58e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#fff3faf7-8935-42fc-a6cb-0ebc6f38c58e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Triewahl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Homon> <http://telicent.io/ontology/primaryName> "Homon" .
<https://starwars.com#planet_Triewahl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#sector_Homon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Homon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Triewahl> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

