Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0ff2be40-f141-490e-b3b5-24811e5ac17c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lalmy'ash"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lalmyash> <http://telicent.io/ontology/primaryName> "Lalmy'ash" .
<https://starwars.com#0ff2be40-f141-490e-b3b5-24811e5ac17c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lalmyash> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0ff2be40-f141-490e-b3b5-24811e5ac17c> .
<https://starwars.com#planet_Lalmyash> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Lalmyash> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Lalmyash> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Lalmyash> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

