Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Csaus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aa9166b8-3b8c-4697-8d40-105269186b0d> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Csaus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F9> .
<https://starwars.com#aa9166b8-3b8c-4697-8d40-105269186b0d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Csaus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#aa9166b8-3b8c-4697-8d40-105269186b0d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Csaus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Csaus> <http://telicent.io/ontology/primaryName> "Csaus" .
<https://starwars.com#planet_Csaus> <http://www.w3.org/2000/01/rdf-schema#comment> "Csaus was an astronomical object located in the territory of the Unknown Regions government known as the Chiss Ascendancy. During a period of crisis, a skirmish was fought near Csaus between the forces of the Tahmie and Droc families. " .
<https://starwars.com#planet_Csaus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .

