Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_VurdonKa> <http://www.w3.org/2000/01/rdf-schema#comment> "Vurdon Ka was a planet located within the galaxy's Inner Rim that was the homeworld of the Vuvrian species. It was located close to one end of the Perlemian Trade Route, which connected it to the planets Castell and Chazwa. " .
<https://starwars.com#sector_Darlonn> <http://telicent.io/ontology/primaryName> "Darlonn" .
<https://starwars.com#planet_VurdonKa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#f3a31531-25b3-4e4b-aca4-c47e1ac67be4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Darlonn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Darlonn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_VurdonKa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f3a31531-25b3-4e4b-aca4-c47e1ac67be4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vurdon Ka"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_VurdonKa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f3a31531-25b3-4e4b-aca4-c47e1ac67be4> .
<https://starwars.com#planet_VurdonKa> <http://telicent.io/ontology/primaryName> "Vurdon Ka" .
<https://starwars.com#planet_VurdonKa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Darlonn> .

