Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0493671b-780e-4ec2-9cc0-88fbfd12c18e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Candoria> <http://telicent.io/ontology/primaryName> "Candoria" .
<https://starwars.com#planet_Candoria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Candoria> <http://www.w3.org/2000/01/rdf-schema#comment> "Candoria was a depopulated planet located in the Colonies region of the galaxy. " .
<https://starwars.com#planet_Candoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Candoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#0493671b-780e-4ec2-9cc0-88fbfd12c18e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Candoria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Candoria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0493671b-780e-4ec2-9cc0-88fbfd12c18e> .

