Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Raxus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2f11a3b-df64-44e4-893f-c022de26b940> .
<https://starwars.com#b2f11a3b-df64-44e4-893f-c022de26b940> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Raxus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Raxus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Raxus> <http://telicent.io/ontology/primaryName> "Raxus" .
<https://starwars.com#planet_Raxus> <http://www.w3.org/2000/01/rdf-schema#comment> "After the war, Raxus found itself in the crosshairs of the Republic's successor, the Galactic Empire, which committed the Antar Atrocity to pressure Raxus and other worlds into surrendering all former Separatists to Imperial custody. Raxus Senator Avi Singh, who refused to voice support of the Imperial occupation, was arrested and later extracted by the Bad Batch. " .
<https://starwars.com#b2f11a3b-df64-44e4-893f-c022de26b940> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Raxus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#planet_Raxus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

