Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ZeHeth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .
<https://starwars.com#planet_ZeHeth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#c16e809d-845f-48b8-adeb-2cefe9099a76> <http://ies.data.gov.uk/ontology/ies4#representationValue> "ZeHeth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ZeHeth> <http://www.w3.org/2000/01/rdf-schema#comment> "ZeHeth was an Mid Rim astronomical object located in grid square N-16 of the Standard Galactic Grid. The super-hyperroute known as the Hydian Way connected it to the Malastare system as well as the Expansion Region celestial body Pax. " .
<https://starwars.com#c16e809d-845f-48b8-adeb-2cefe9099a76> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_ZeHeth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c16e809d-845f-48b8-adeb-2cefe9099a76> .
<https://starwars.com#planet_ZeHeth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ZeHeth> <http://telicent.io/ontology/primaryName> "ZeHeth" .

