Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ithull> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ef3bc1f-c70b-4fd1-a895-f5223175f62b> .
<https://starwars.com#9ef3bc1f-c70b-4fd1-a895-f5223175f62b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ithull> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Airon> .
<https://starwars.com#planet_Ithull> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Airon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Airon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ithull> <http://www.w3.org/2000/01/rdf-schema#comment> "Ithull was the gigantic homeworld of the Ithullans and the colossus wasps. The Ithullans were almost wiped out by the Mandalorians in the year 200 BBY. " .
<https://starwars.com#planet_Ithull> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#9ef3bc1f-c70b-4fd1-a895-f5223175f62b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ithull"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Airon> <http://telicent.io/ontology/primaryName> "Airon" .
<https://starwars.com#planet_Ithull> <http://telicent.io/ontology/primaryName> "Ithull" .

