Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MarkbeesStar> <http://www.w3.org/2000/01/rdf-schema#comment> "Markbee's Star was the primary star of the planet Zeffliffl, the fourth planet of the system. " .
<https://starwars.com#planet_MarkbeesStar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_MarkbeesStar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#planet_MarkbeesStar> <http://telicent.io/ontology/primaryName> "Markbee's Star" .
<https://starwars.com#14a1576b-05ba-4074-b8b2-2922f4e4fab2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#14a1576b-05ba-4074-b8b2-2922f4e4fab2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Markbee's Star"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MarkbeesStar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MarkbeesStar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#14a1576b-05ba-4074-b8b2-2922f4e4fab2> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

