Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3c64b7cc-666d-416d-a2d9-d36ba14caab8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ossiathora"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ossiathora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ossiathora> <http://www.w3.org/2000/01/rdf-schema#comment> "Ossiathora was an agriworld located in the Ossiathora system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. The Senex-Juvex Loop hyperlane linked it to the Deminol and Kassido systems. Ossiathora was the origin point of Ossiathoran noodles and was controlled by House Kassido, a noble house based on the world of Kassido. " .
<https://starwars.com#planet_Ossiathora> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c64b7cc-666d-416d-a2d9-d36ba14caab8> .
<https://starwars.com#planet_Ossiathora> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ossiathora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#3c64b7cc-666d-416d-a2d9-d36ba14caab8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Ossiathora> <http://telicent.io/ontology/primaryName> "Ossiathora" .

