Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Aztubek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cf32923d-4b97-4a0d-a075-f1299f4c10dd> .
<https://starwars.com#cf32923d-4b97-4a0d-a075-f1299f4c10dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#cf32923d-4b97-4a0d-a075-f1299f4c10dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aztubek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aztubek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .
<https://starwars.com#planet_Aztubek> <http://telicent.io/ontology/primaryName> "Aztubek" .
<https://starwars.com#planet_Aztubek> <http://www.w3.org/2000/01/rdf-schema#comment> "Aztubek was an astronomical object located within the Javin Sector of Mugaari Space and along the Corellian Trade Spine. " .
<https://starwars.com#planet_Aztubek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Aztubek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

