Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Briahl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5105eb54-5c2d-4a36-b8a6-bd7bf1b5630a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lanteeb"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lanteeb> <http://www.w3.org/2000/01/rdf-schema#comment> "Lanteeb was a planet that was the origin of Maxilan's explosive bloatworm. " .
<https://starwars.com#sector_Briahl> <http://telicent.io/ontology/primaryName> "Bri'ahl" .
<https://starwars.com#planet_Lanteeb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#5105eb54-5c2d-4a36-b8a6-bd7bf1b5630a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lanteeb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lanteeb> <http://telicent.io/ontology/primaryName> "Lanteeb" .
<https://starwars.com#sector_Briahl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lanteeb> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5105eb54-5c2d-4a36-b8a6-bd7bf1b5630a> .
<https://starwars.com#planet_Lanteeb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Briahl> .

