Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GelviddisCluster> <http://telicent.io/ontology/primaryName> "Gelviddis Cluster" .
<https://starwars.com#planet_GelviddisCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_GelviddisCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2a431e0b-c483-450e-9a4e-4067fc5215a8> .
<https://starwars.com#planet_GelviddisCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2a431e0b-c483-450e-9a4e-4067fc5215a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gelviddis Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_GelviddisCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#2a431e0b-c483-450e-9a4e-4067fc5215a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_GelviddisCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Gelviddis Cluster was a star cluster that contained a planet with sands that the Jedi Order discovered would assume the shape of what an observer was thinking. " .

