Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorGejalli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dcd95d02-e996-4484-81a7-01f5739d50c0> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_KorGejalli> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Gejalli was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Gejalli kajidic, until the Anjiliacs crushed the Gejallis during a clan war and took over their throneworld. The sole survivor of the Gejalli kajidic, Vago Gejalli Thokka, was adopted by Popara Anjiliac Diresto. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#dcd95d02-e996-4484-81a7-01f5739d50c0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Gejalli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorGejalli> <http://telicent.io/ontology/primaryName> "Kor Gejalli" .
<https://starwars.com#planet_KorGejalli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dcd95d02-e996-4484-81a7-01f5739d50c0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorGejalli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#planet_KorGejalli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .

