Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Grumani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Grumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Crait> <http://www.w3.org/2000/01/rdf-schema#comment> "Small mineral planet located in a remote section of the galaxy, its surface is covered with a layer of white salt over its red-colored soil. In Leia, Princess of Alderaan it is the location of an early Rebel Alliance outpost. Leia and her remaining Resistance forces flee there in The Last Jedi, where they face off with the First Order." .
<https://starwars.com#planet_Crait> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Crait> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#fa559357-fe60-4a5a-a737-d4123bb75ddb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Crait> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fa559357-fe60-4a5a-a737-d4123bb75ddb> .
<https://starwars.com#sector_Grumani> <http://telicent.io/ontology/primaryName> "Grumani" .
<https://starwars.com#planet_Crait> <http://telicent.io/ontology/primaryName> "Crait" .
<https://starwars.com#planet_Crait> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Grumani> .
<https://starwars.com#fa559357-fe60-4a5a-a737-d4123bb75ddb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Crait"^^<http://www.w3.org/2001/XMLSchema#string> .

