Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#84e42b61-cf3f-48ea-b422-0154a96d8cb9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_T14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Gamorr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T14> .
<https://starwars.com#planet_Gamorr> <http://telicent.io/ontology/primaryName> "Gamorr" .
<https://starwars.com#planet_Gamorr> <http://www.w3.org/2000/01/rdf-schema#comment> "It was located to the galactic east of Kupoh. Shortly after the Battle of Yavin, the Givin Drusil Bephorin needed to escape Kupoh with the Alliance to Restore the Republic agents Luke Skywalker and Nakari Kelen and suggested they travel to the east, causing Skywalker to question if she was using the distant Gamorr as her navigation point. Bephorin was in fact using the location of a theoretical star she had calculated must exist as a navigation point. " .
<https://starwars.com#741ffd03-1a67-4668-9ad6-cb1d906b7717> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gamorr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#741ffd03-1a67-4668-9ad6-cb1d906b7717> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gamorr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gamorr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Galov> .
<https://starwars.com#sector_Galov> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_T14> <http://telicent.io/ontology/primaryName> "T14" .
<https://starwars.com#grid_T14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Galov> <http://telicent.io/ontology/primaryName> "Galov" .
<https://starwars.com#84e42b61-cf3f-48ea-b422-0154a96d8cb9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gamorr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#741ffd03-1a67-4668-9ad6-cb1d906b7717> .
<https://starwars.com#grid_T14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#84e42b61-cf3f-48ea-b422-0154a96d8cb9> .
<https://starwars.com#sector_Galov> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

