Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jospro> <http://telicent.io/ontology/primaryName> "Jospro" .
<https://starwars.com#planet_Trogan> <http://www.w3.org/2000/01/rdf-schema#comment> "Trogan was an astronomical object located in the galaxy's Outer Rim Territories. It housed an Imperial outpost and was located close to the Galidraan system. When the Imperial corvette Carrion Spike was stolen and attacked Galidraan Station, Moff Wilhuff Tarkin requested a list of all nearby Imperial resources the ship might next attack; Trogan and its outpost were amongst those included in the list given to him. " .
<https://starwars.com#51cb7212-fdb5-41b0-9c3c-a3b05bf5959d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trogan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trogan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trogan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jospro> .
<https://starwars.com#sector_Jospro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#51cb7212-fdb5-41b0-9c3c-a3b05bf5959d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Jospro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Trogan> <http://telicent.io/ontology/primaryName> "Trogan" .
<https://starwars.com#planet_Trogan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#planet_Trogan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#51cb7212-fdb5-41b0-9c3c-a3b05bf5959d> .

