Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Carlac> <http://telicent.io/ontology/primaryName> "Carlac" .
<https://starwars.com#planet_Carlac> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#01cf0325-ac59-40d9-b925-5a3b1ae15cf9> .
<https://starwars.com#01cf0325-ac59-40d9-b925-5a3b1ae15cf9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Carlac> <http://www.w3.org/2000/01/rdf-schema#comment> "Carlac was a peaceful, snow-covered planet in the Outer Rim Territories. A town inhabited by members of the Ming Po culture existed on the planet during the Clone Wars. However, that village was burned to the ground by the Death Watch, a radical Mandalorian terrorist group. " .
<https://starwars.com#sector_Prefsbelt> <http://telicent.io/ontology/primaryName> "Prefsbelt" .
<https://starwars.com#planet_Carlac> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Carlac> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prefsbelt> .
<https://starwars.com#01cf0325-ac59-40d9-b925-5a3b1ae15cf9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carlac"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Prefsbelt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Carlac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Prefsbelt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

