Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Mantan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Mantan> <http://www.w3.org/2000/01/rdf-schema#comment> "The world of Mantan was located in the Mantan system of the Calamari sector. " .
<https://starwars.com#131083f3-9d21-41d1-aa5e-9235e058887d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mantan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#131083f3-9d21-41d1-aa5e-9235e058887d> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mantan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#planet_Mantan> <http://telicent.io/ontology/primaryName> "Mantan" .
<https://starwars.com#131083f3-9d21-41d1-aa5e-9235e058887d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mantan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mantan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

