Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kesmere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#planet_Kesmere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kesmere> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ca9e58a-1ac2-455f-ab84-e841039a666f> .
<https://starwars.com#planet_Kesmere> <http://www.w3.org/2000/01/rdf-schema#comment> "The Kesmere system was located in the Raioballo sector, a part of the New Territories portion of the Outer Rim Territories. It shared its name with the Kesmere Minor and Tertiary Kesmere systems. The star system fell within the borders of the Pentastar Alignment between 4 ABY and 12 ABY and was a part of the Imperial Remnant between 18 ABY and 35 ABY" .
<https://starwars.com#9ca9e58a-1ac2-455f-ab84-e841039a666f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#9ca9e58a-1ac2-455f-ab84-e841039a666f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kesmere"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kesmere> <http://telicent.io/ontology/primaryName> "Kesmere" .
<https://starwars.com#planet_Kesmere> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

