Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thanium> <http://www.w3.org/2000/01/rdf-schema#comment> "Thanium was a planet located within the Thanium system of the Outer Rim Territories. It was absorbed into Xim's Empire as he expanded his borders from the Kingdom of Cron. " .
<https://starwars.com#planet_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#sector_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Thanium> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#38e7a152-f3f1-43fb-ad7c-babbb5d95132> .
<https://starwars.com#38e7a152-f3f1-43fb-ad7c-babbb5d95132> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#sector_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thanium> .
<https://starwars.com#38e7a152-f3f1-43fb-ad7c-babbb5d95132> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thanium"^^<http://www.w3.org/2001/XMLSchema#string> .

