Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Koradin> <http://telicent.io/ontology/primaryName> "Koradin" .
<https://starwars.com#sector_Koradin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4a578302-ffe0-43cd-bc9c-33fb6b619f69> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lipsec"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Koradin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lipsec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lipsec> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4a578302-ffe0-43cd-bc9c-33fb6b619f69> .
<https://starwars.com#planet_Lipsec> <http://www.w3.org/2000/01/rdf-schema#comment> "Lipsec was an Outer Rim Territories astronomical object located in grid square I-18 of the Standard Galactic Grid. A hyperspace route connected it to the Virgillia system. Lipsec shared its name with the Expansion Region route known as the Lipsec Run. " .
<https://starwars.com#planet_Lipsec> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I18> .
<https://starwars.com#4a578302-ffe0-43cd-bc9c-33fb6b619f69> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lipsec> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Koradin> .
<https://starwars.com#planet_Lipsec> <http://telicent.io/ontology/primaryName> "Lipsec" .

