Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sermeria> <http://www.w3.org/2000/01/rdf-schema#comment> "Sermeria was an agriworld in the Expansion Region. " .
<https://starwars.com#0272074d-2a6c-4880-bbb3-db02d4e578d1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sermeria> <http://telicent.io/ontology/primaryName> "Sermeria" .
<https://starwars.com#planet_Sermeria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0272074d-2a6c-4880-bbb3-db02d4e578d1> .
<https://starwars.com#planet_Sermeria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Locris> .
<https://starwars.com#planet_Sermeria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#0272074d-2a6c-4880-bbb3-db02d4e578d1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sermeria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sermeria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Locris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Locris> <http://telicent.io/ontology/primaryName> "Locris" .
<https://starwars.com#sector_Locris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

