Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bajic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a63b3d28-af4c-4bd0-a296-159e59acc92c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bajic"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bajic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bajic> .
<https://starwars.com#a63b3d28-af4c-4bd0-a296-159e59acc92c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bajic> <http://www.w3.org/2000/01/rdf-schema#comment> "Bajic could refer to one of the following: " .
<https://starwars.com#sector_Bajic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bajic> <http://telicent.io/ontology/primaryName> "Bajic" .
<https://starwars.com#planet_Bajic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P18> .
<https://starwars.com#planet_Bajic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bajic> <http://telicent.io/ontology/primaryName> "Bajic" .
<https://starwars.com#planet_Bajic> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a63b3d28-af4c-4bd0-a296-159e59acc92c> .

