Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#70ae059a-2879-4226-945c-2bde2e949182> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#70ae059a-2879-4226-945c-2bde2e949182> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bisellia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bisellia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#70ae059a-2879-4226-945c-2bde2e949182> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bisellia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Bisellia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bisellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .
<https://starwars.com#planet_Bisellia> <http://telicent.io/ontology/primaryName> "Bisellia" .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bisellia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .

