Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Arrgaw> <http://telicent.io/ontology/primaryName> "Arrgaw" .
<https://starwars.com#a5037e3c-790f-4f10-8c4c-945818f6b3a5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_N16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_N16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#a5037e3c-790f-4f10-8c4c-945818f6b3a5> .
<https://starwars.com#sector_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#grid_N16> <http://telicent.io/ontology/primaryName> "N16" .
<https://starwars.com#sector_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#a5037e3c-790f-4f10-8c4c-945818f6b3a5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arrgaw> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kira> .
<https://starwars.com#planet_Arrgaw> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#1165ed73-d5d6-48ae-bf6c-a8729b3a3711> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arrgaw"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arrgaw> <http://www.w3.org/2000/01/rdf-schema#comment> "During the era of the Alsakan Conflicts, Arrgaw's strategic position allowed it to become an important trade center supporting the wide-spread settlement of the Trailing Sectors. The planet was known as one of the wealthiest worlds of the Expansion Region millennia later, and refineries at Arrgaw were used to process the highly unstable nova crystals—basis for much of the hard currency used by the New Republic. " .
<https://starwars.com#grid_N16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Arrgaw> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Arrgaw> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1165ed73-d5d6-48ae-bf6c-a8729b3a3711> .
<https://starwars.com#1165ed73-d5d6-48ae-bf6c-a8729b3a3711> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

