Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Spirana> <http://www.w3.org/2000/01/rdf-schema#comment> "Spirana was an astronomical object in the galaxy's Inner Rim, situated along the Corellian Run. " .
<https://starwars.com#planet_Spirana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_Spirana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#7e535cf6-beb1-4ea2-b924-fa47b075bb4d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Spirana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Spirana> <http://telicent.io/ontology/primaryName> "Spirana" .
<https://starwars.com#planet_Spirana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e535cf6-beb1-4ea2-b924-fa47b075bb4d> .
<https://starwars.com#planet_Spirana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7e535cf6-beb1-4ea2-b924-fa47b075bb4d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

