Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_K10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Alland> <http://telicent.io/ontology/primaryName> "Alland" .
<https://starwars.com#planet_Alland> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#cab35da0-e0d8-41c4-b137-66eea787358a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alland"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Alland> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cab35da0-e0d8-41c4-b137-66eea787358a> .
<https://starwars.com#e6f4dc62-72f4-4b43-b211-1715978d227a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#cab35da0-e0d8-41c4-b137-66eea787358a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_K10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e6f4dc62-72f4-4b43-b211-1715978d227a> .
<https://starwars.com#grid_K10> <http://telicent.io/ontology/primaryName> "K10" .
<https://starwars.com#e6f4dc62-72f4-4b43-b211-1715978d227a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Alland> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Alland> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Alland> <http://www.w3.org/2000/01/rdf-schema#comment> "Alland was a planet located in the Core Worlds. It was situated on Metellos Trade Route. " .

