Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pallaxides> <http://www.w3.org/2000/01/rdf-schema#comment> "Pallaxides was a planet of the Ojoster sector in the Outer Rim. It was owned by TaggeCo, who used it as a resort world. " .
<https://starwars.com#sector_Noonian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pallaxides> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#3fbe4d05-d47e-4fdd-bf87-4e456a02dcd3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3fbe4d05-d47e-4fdd-bf87-4e456a02dcd3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pallaxides"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pallaxides> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3fbe4d05-d47e-4fdd-bf87-4e456a02dcd3> .
<https://starwars.com#sector_Noonian> <http://telicent.io/ontology/primaryName> "Noonian" .
<https://starwars.com#planet_Pallaxides> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pallaxides> <http://telicent.io/ontology/primaryName> "Pallaxides" .
<https://starwars.com#planet_Pallaxides> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noonian> .
<https://starwars.com#sector_Noonian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

