Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TyedKant> <http://www.w3.org/2000/01/rdf-schema#comment> "Tyed Kant was an inhabited gas giant in the Core Worlds, near Demophon. It was the only planet in the Kantel system. " .
<https://starwars.com#planet_TyedKant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#078f74cc-9da2-438c-87b4-9d1601645857> .
<https://starwars.com#078f74cc-9da2-438c-87b4-9d1601645857> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TyedKant> <http://telicent.io/ontology/primaryName> "Tyed Kant" .
<https://starwars.com#planet_TyedKant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TyedKant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#078f74cc-9da2-438c-87b4-9d1601645857> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tyed Kant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TyedKant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .

