Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_UldaFrav> <http://www.w3.org/2000/01/rdf-schema#comment> "Ulda Frav was a tropical Expansion Region planet located in the Hangshan sector. Located in widely explored space by 5000 BBY, by 3998 BBY the world was visited by both a group of Jedi who arbitrated a treaty there and the Nazzar Crown Prince Qrrrl Toq. On the planet, the Jedi informed Toq of his potential for becoming a Jedi, which he eventually did. Millennia later, Vlaydm Churhee served as a sharpshooter on Ulda Frav before forming the Churhee's Riflemen mercenary unit. " .
<https://starwars.com#sector_Hangshan> <http://telicent.io/ontology/primaryName> "Hangshan" .
<https://starwars.com#sector_Hangshan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_UldaFrav> <http://telicent.io/ontology/primaryName> "Ulda Frav" .
<https://starwars.com#planet_UldaFrav> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P11> .
<https://starwars.com#b32ca734-94fd-4680-8d6d-c19a60b774a0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ulda Frav"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_UldaFrav> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b32ca734-94fd-4680-8d6d-c19a60b774a0> .
<https://starwars.com#sector_Hangshan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b32ca734-94fd-4680-8d6d-c19a60b774a0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_UldaFrav> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hangshan> .
<https://starwars.com#planet_UldaFrav> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

