Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalinda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4ea49474-f685-4b79-92a3-be924b1b6c38> .
<https://starwars.com#sector_Vilonis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kalinda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vilonis> .
<https://starwars.com#sector_Vilonis> <http://telicent.io/ontology/primaryName> "Vilonis" .
<https://starwars.com#planet_Kalinda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O16> .
<https://starwars.com#planet_Kalinda> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalinda was an astronomical object located in the Mid Rim and the Trailing Sectors regions, in grid square O-16 of the Standard Galactic Grid. A hyperspace route linked Kalinda to the planet Naboo and the celestial body Kira. " .
<https://starwars.com#planet_Kalinda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4ea49474-f685-4b79-92a3-be924b1b6c38> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalinda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kalinda> <http://telicent.io/ontology/primaryName> "Kalinda" .
<https://starwars.com#sector_Vilonis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#4ea49474-f685-4b79-92a3-be924b1b6c38> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

