Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Churruma> <http://www.w3.org/2000/01/rdf-schema#comment> "Churruma was a planet with deposits of valuable metals that was located within the Velcar sector of the Outer Rim Territories. During the Galactic Civil War, the Galactic Empire mined Churruma's metals and captured the shaman Chrech Estha, a respected leader of the planet's natives who possessed a carved stick that served as a powerful political and religious symbol on his homeworld. The return of Estha and the stick to Churruma sparked a rebellion that ended the Empire's presence on the planet. " .
<https://starwars.com#planet_Churruma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Velcar> .
<https://starwars.com#planet_Churruma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a27cc95-0a92-4722-a434-9e65592cfb9c> .
<https://starwars.com#planet_Churruma> <http://telicent.io/ontology/primaryName> "Churruma" .
<https://starwars.com#planet_Churruma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3a27cc95-0a92-4722-a434-9e65592cfb9c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Churruma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Churruma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#3a27cc95-0a92-4722-a434-9e65592cfb9c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Velcar> <http://telicent.io/ontology/primaryName> "Velcar" .
<https://starwars.com#sector_Velcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Velcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

