Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OldMankoo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Quess> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#36aa3890-c64e-47b0-811a-28724b8433fd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Quess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_OldMankoo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quess> .
<https://starwars.com#36aa3890-c64e-47b0-811a-28724b8433fd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Old Mankoo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OldMankoo> <http://telicent.io/ontology/primaryName> "Old Mankoo" .
<https://starwars.com#planet_OldMankoo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#36aa3890-c64e-47b0-811a-28724b8433fd> .
<https://starwars.com#planet_OldMankoo> <http://www.w3.org/2000/01/rdf-schema#comment> "Old Mankoo was a planet located in the Old Mankoo system, a part of the Quess sector in the Trailing Sectors portion of the Mid Rim. The planet was impoverished, and by 23 BBY, the royal family of Old Mankoo had been overthrown. " .
<https://starwars.com#planet_OldMankoo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#sector_Quess> <http://telicent.io/ontology/primaryName> "Quess" .

