Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b5cd4b69-25c6-4409-aef4-a3ad788a6180> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Farana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Farana> <http://telicent.io/ontology/primaryName> "Farana" .
<https://starwars.com#sector_Farana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Farana> <http://www.w3.org/2000/01/rdf-schema#comment> "Farana was a terrestrial Wild Space planet located in the grid square S-3 of the Standard Galactic Grid. A collector of antiquities on Farana maintained an arsenal of starships that included six Flarestar-class attack shuttles and a Corona-class armed frigate—one of a limited run that its manufacturer, Haor Chall Engineering Corporation, had sold off to various interested third parties. " .
<https://starwars.com#planet_Farana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Farana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5cd4b69-25c6-4409-aef4-a3ad788a6180> .
<https://starwars.com#b5cd4b69-25c6-4409-aef4-a3ad788a6180> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Farana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Farana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Farana> .
<https://starwars.com#planet_Farana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Farana> <http://telicent.io/ontology/primaryName> "Farana" .

