Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vensori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Katarr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Katarr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b9bddb8d-aa41-4eb7-89c9-f0585bd3eb31> .
<https://starwars.com#planet_Katarr> <http://www.w3.org/2000/01/rdf-schema#comment> "Katarr was the homeworld of the sentient Reeman species. It shared it's name with the Katarr adumbrature, texts studied by the Jedi Master and seer Oorallon, with the help of Padawan Qui-Gon Jinn. " .
<https://starwars.com#sector_Vensori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Katarr> <http://telicent.io/ontology/primaryName> "Katarr" .
<https://starwars.com#planet_Katarr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vensori> .
<https://starwars.com#b9bddb8d-aa41-4eb7-89c9-f0585bd3eb31> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Katarr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b9bddb8d-aa41-4eb7-89c9-f0585bd3eb31> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Vensori> <http://telicent.io/ontology/primaryName> "Vensori" .
<https://starwars.com#planet_Katarr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .

