Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Skorrupon> <http://telicent.io/ontology/primaryName> "Skorrupon" .
<https://starwars.com#planet_Skorrupon> <http://www.w3.org/2000/01/rdf-schema#comment> "Skorrupon was a terrestrial astronomical object where the New Republic pilots Wyl Lark and Kamala encountered a Twi'lek. Several weeks after the Battle of Endor in 4 ABY, Kamala, in a game of 'Who? What? Where?' chose the Twi'lek on Skorrupon to be the first to hear in the event of her death. " .
<https://starwars.com#02fc55db-4605-4aaa-8f4c-21babc051b6b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skorrupon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TransVulta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TransVulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_TransVulta> <http://telicent.io/ontology/primaryName> "Trans'Vulta" .
<https://starwars.com#planet_Skorrupon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02fc55db-4605-4aaa-8f4c-21babc051b6b> .
<https://starwars.com#planet_Skorrupon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TransVulta> .
<https://starwars.com#planet_Skorrupon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Skorrupon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#02fc55db-4605-4aaa-8f4c-21babc051b6b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

