Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#223b49be-ac78-46f7-91db-bf812ed8a8c9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nuswatta> <http://telicent.io/ontology/primaryName> "Nuswatta" .
<https://starwars.com#planet_Nuswatta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Nuswatta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#223b49be-ac78-46f7-91db-bf812ed8a8c9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nuswatta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nuswatta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#223b49be-ac78-46f7-91db-bf812ed8a8c9> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Nuswatta> <http://www.w3.org/2000/01/rdf-schema#comment> "Nuswatta was a planet in the Tion Cluster of the Outer Rim Territories. " .
<https://starwars.com#planet_Nuswatta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .

