Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdThoden> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b4d4322b-c264-4346-8ad3-6b668745b2ce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdThoden> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4d4322b-c264-4346-8ad3-6b668745b2ce> .
<https://starwars.com#b4d4322b-c264-4346-8ad3-6b668745b2ce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Thoden"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdThoden> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Thoden was a tectonically active planet in the Dynali sector. Its capital was Domitree, and it was represented in the Galactic Senate by Boganni Hrul prior to the Clone Wars. It was the headquarters of Bengel Shipbuilders, and relied on the company's XQ1 Space Platforms as stopover points for travelers to alleviate space transport traffic. The Tenloss Syndicate also had dealings on the planet. It was the site of a deadly groundquake 23 BBY, and was the homeworld of Aris-Del Wari and her mother, Jonava Billane. " .
<https://starwars.com#planet_OrdThoden> <http://telicent.io/ontology/primaryName> "Ord Thoden" .
<https://starwars.com#sector_Dynali> <http://telicent.io/ontology/primaryName> "Dynali" .
<https://starwars.com#sector_Dynali> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdThoden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dynali> .
<https://starwars.com#sector_Dynali> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdThoden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .

