Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NarHaaska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#e731c81d-1ae2-464f-86ef-6feb39fb158a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nar Haaska"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NarHaaska> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e731c81d-1ae2-464f-86ef-6feb39fb158a> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NarHaaska> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_NarHaaska> <http://telicent.io/ontology/primaryName> "Nar Haaska" .
<https://starwars.com#planet_NarHaaska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_NarHaaska> <http://www.w3.org/2000/01/rdf-schema#comment> "Nar Haaska was a shadowport on the border of Hutt Space and the Outer Rim Territories. At some point by 10 BBY, Bandit Billie and her crew of shipjackers accosted the space yacht of the crime lord Jabba Desilijic Tiure, the Star Jewel, while it was on a layover on Nar Haaska. The theft attempt was thwarted, and the yacht subsequently changed course for a repair yard at Keldooine. " .
<https://starwars.com#e731c81d-1ae2-464f-86ef-6feb39fb158a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

