Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Twith> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dfbb08f7-6484-4493-8312-b402703c2028> .
<https://starwars.com#planet_Twith> <http://telicent.io/ontology/primaryName> "Twith" .
<https://starwars.com#planet_Twith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#dfbb08f7-6484-4493-8312-b402703c2028> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Twith"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dfbb08f7-6484-4493-8312-b402703c2028> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Twith> <http://www.w3.org/2000/01/rdf-schema#comment> "Twith was a planet located within the Twith system of the Core Worlds on one end of the Hyabb-Twith Corridor. It was constantly at war with Hyabb. " .
<https://starwars.com#planet_Twith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Twith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

