Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kroctar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#sector_Shataum> <http://telicent.io/ontology/primaryName> "Shataum" .
<https://starwars.com#sector_Shataum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Kroctar> <http://telicent.io/ontology/primaryName> "Kroctar" .
<https://starwars.com#planet_Kroctar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kroctar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Shataum> .
<https://starwars.com#sector_Shataum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kroctar> <http://www.w3.org/2000/01/rdf-schema#comment> "Kroctar was the homeworld of the Kroctari, and the capital and merchant center of the Shataum sector. " .
<https://starwars.com#planet_Kroctar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd6144f4-8a37-4cdc-8b67-981b5c626213> .
<https://starwars.com#dd6144f4-8a37-4cdc-8b67-981b5c626213> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dd6144f4-8a37-4cdc-8b67-981b5c626213> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kroctar"^^<http://www.w3.org/2001/XMLSchema#string> .

