Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Morishim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Morishim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .
<https://starwars.com#520d2763-902d-405c-8208-0fb9da83bf0d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Morishim> <http://www.w3.org/2000/01/rdf-schema#comment> "Morishim was a planet in the Albarrio sector of the Outer Rim and the homeworld of the Morish species. " .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Morishim> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#520d2763-902d-405c-8208-0fb9da83bf0d> .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Morishim> <http://telicent.io/ontology/primaryName> "Morishim" .
<https://starwars.com#planet_Morishim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#520d2763-902d-405c-8208-0fb9da83bf0d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Morishim"^^<http://www.w3.org/2001/XMLSchema#string> .

