Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jandur> <http://www.w3.org/2000/01/rdf-schema#comment> "Jandur was a planet in the Inner Rim and was represented in the New Republic Senate. " .
<https://starwars.com#grid_J14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#180041bb-6b10-4232-8e88-33ae683ca869> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Jandur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#9efc2ef3-f81a-429a-9ca8-f3a1e87a4695> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jandur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J14> .
<https://starwars.com#planet_Jandur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J14> <http://telicent.io/ontology/primaryName> "J14" .
<https://starwars.com#9efc2ef3-f81a-429a-9ca8-f3a1e87a4695> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jandur"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_J14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#180041bb-6b10-4232-8e88-33ae683ca869> .
<https://starwars.com#planet_Jandur> <http://telicent.io/ontology/primaryName> "Jandur" .
<https://starwars.com#180041bb-6b10-4232-8e88-33ae683ca869> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_J14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Jandur> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9efc2ef3-f81a-429a-9ca8-f3a1e87a4695> .

