Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ConcordDawn> <http://www.w3.org/2000/01/rdf-schema#comment> "Home planet of Jango Fett. Habitable planet that is surrounded by a large amount of debris from many vicious wars. Formerly controlled by the Mandalorians." .
<https://starwars.com#da1f1bbc-147a-4c14-957f-a74887d518b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#deccdcba-e7e3-49e1-9a75-8e978a93d9e9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ConcordDawn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thursa> .
<https://starwars.com#deccdcba-e7e3-49e1-9a75-8e978a93d9e9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Concord Dawn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Thursa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_O7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_O7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_ConcordDawn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#deccdcba-e7e3-49e1-9a75-8e978a93d9e9> .
<https://starwars.com#grid_O7> <http://telicent.io/ontology/primaryName> "O7" .
<https://starwars.com#da1f1bbc-147a-4c14-957f-a74887d518b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_ConcordDawn> <http://telicent.io/ontology/primaryName> "Concord Dawn" .
<https://starwars.com#grid_O7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#da1f1bbc-147a-4c14-957f-a74887d518b8> .
<https://starwars.com#planet_ConcordDawn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#sector_Thursa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_ConcordDawn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Thursa> <http://telicent.io/ontology/primaryName> "Thursa" .

