Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorHunamma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorHunamma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#87c896e5-8f15-46c2-9387-6ca8306a2a26> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#87c896e5-8f15-46c2-9387-6ca8306a2a26> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Hunamma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorHunamma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorHunamma> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Hunamma was a planet located in the Bootana Hutta region of Hutt Space. It was a Hutt throneworld. " .
<https://starwars.com#planet_KorHunamma> <http://telicent.io/ontology/primaryName> "Kor Hunamma" .
<https://starwars.com#87c896e5-8f15-46c2-9387-6ca8306a2a26> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorHunamma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

