Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sionia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sionia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sionia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4315c69b-74a5-4a39-9c53-666b8cb82b56> .
<https://starwars.com#4315c69b-74a5-4a39-9c53-666b8cb82b56> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sionia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#4315c69b-74a5-4a39-9c53-666b8cb82b56> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sionia> <http://www.w3.org/2000/01/rdf-schema#comment> "Sionia was home to the Sionian Skups, a near-human species. The planet was noted for the number of master thieves it produced. " .
<https://starwars.com#planet_Sionia> <http://telicent.io/ontology/primaryName> "Sionia" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Sionia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .

