Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Anoat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8c14723f-a8dd-4209-b008-0076158fbc95> .
<https://starwars.com#8c14723f-a8dd-4209-b008-0076158fbc95> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8c14723f-a8dd-4209-b008-0076158fbc95> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anoat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Anoat> <http://www.w3.org/2000/01/rdf-schema#comment> "Polluted; A nearly inhospitable planet used by the Empire." .
<https://starwars.com#planet_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .

