Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Anstares> <http://telicent.io/ontology/primaryName> "Anstares" .
<https://starwars.com#planet_Anstares> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#a4c31e1b-9798-4a05-b6af-d8c020360494> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anstares"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Anstares> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a4c31e1b-9798-4a05-b6af-d8c020360494> .
<https://starwars.com#planet_Anstares> <http://www.w3.org/2000/01/rdf-schema#comment> "Anstares VI, also known as Anstares, was a Mid Rim gas giant located in the Juvex sector. It was orbited by three planetary rings and eight moons, the latter of which were a popular destination for visitors from both the Senex-Juvex region and the wider galaxy." .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Anstares> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a4c31e1b-9798-4a05-b6af-d8c020360494> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anstares> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

