Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Omar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1906d7c0-73fe-4009-82a6-0749e7a7963d> .
<https://starwars.com#1906d7c0-73fe-4009-82a6-0749e7a7963d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Omar> <http://telicent.io/ontology/primaryName> "Omar" .
<https://starwars.com#planet_Omar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#planet_Omar> <http://www.w3.org/2000/01/rdf-schema#comment> "Omar was a planet located in the system of the same name. " .
<https://starwars.com#planet_Omar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#1906d7c0-73fe-4009-82a6-0749e7a7963d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Omar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Omar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

