Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#b34a16ff-4e61-4c0a-b851-bfad583849a0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OHS2132-04> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#planet_OHS2132-04> <http://telicent.io/ontology/primaryName> "OHS2132-04" .
<https://starwars.com#planet_OHS2132-04> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b34a16ff-4e61-4c0a-b851-bfad583849a0> .
<https://starwars.com#planet_OHS2132-04> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_OHS2132-04> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_OHS2132-04> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b34a16ff-4e61-4c0a-b851-bfad583849a0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "OHS2132-04"^^<http://www.w3.org/2001/XMLSchema#string> .

