Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kamino> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kamino> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#4d4c0feb-fadb-4198-8511-407c931f7fb5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kamino"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kamino> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kamino> <http://www.w3.org/2000/01/rdf-schema#comment> "Ocean planet located outside the main galaxy, where cloning technology is developed and the Clone Army is created and trained. Obi-Wan Kenobi discovers that the planet is missing from the Jedi archives; it is later revealed to have been deleted as of a part of the Sith plot to start the Clone Wars, and take over the galaxy." .
<https://starwars.com#4d4c0feb-fadb-4198-8511-407c931f7fb5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kamino> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4d4c0feb-fadb-4198-8511-407c931f7fb5> .
<https://starwars.com#planet_Kamino> <http://telicent.io/ontology/primaryName> "Kamino" .

