Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mossak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thanium> .
<https://starwars.com#planet_Mossak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f647caf3-3f8a-4989-baad-e22aca0c8bf6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mossak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#planet_Mossak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Mossak> <http://telicent.io/ontology/primaryName> "Mossak" .
<https://starwars.com#planet_Mossak> <http://www.w3.org/2000/01/rdf-schema#comment> "Mossak was a planet in the Outer Rim Territories' Thanium sector, located at the end of the Perlemian Trade Route and at the start of the Tingel Arm. It was located near Felucia and Galidraan. It was part of Xim's Empire. " .
<https://starwars.com#sector_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#f647caf3-3f8a-4989-baad-e22aca0c8bf6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mossak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f647caf3-3f8a-4989-baad-e22aca0c8bf6> .

