Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_TransVulta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TransVulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Null> <http://www.w3.org/2000/01/rdf-schema#comment> "Null was an astronomical object located in the galaxy's Mid Rim. The Whisper bird, a species of bird native to the moon of Yavin 4, could also be found on Null. " .
<https://starwars.com#sector_TransVulta> <http://telicent.io/ontology/primaryName> "Trans'Vulta" .
<https://starwars.com#planet_Null> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#50943fe6-f92c-4d4c-8ff8-5a717b506bbd> .
<https://starwars.com#planet_Null> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TransVulta> .
<https://starwars.com#planet_Null> <http://telicent.io/ontology/primaryName> "Null" .
<https://starwars.com#50943fe6-f92c-4d4c-8ff8-5a717b506bbd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#50943fe6-f92c-4d4c-8ff8-5a717b506bbd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Null"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Null> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Null> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .

