Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#27e8d7ab-d8b6-4d02-ae8b-9f4a937492ff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "D'Qar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DQar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sanbra> .
<https://starwars.com#planet_DQar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#27e8d7ab-d8b6-4d02-ae8b-9f4a937492ff> .
<https://starwars.com#planet_DQar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_DQar> <http://telicent.io/ontology/primaryName> "D'Qar" .
<https://starwars.com#sector_Sanbra> <http://telicent.io/ontology/primaryName> "Sanbra" .
<https://starwars.com#27e8d7ab-d8b6-4d02-ae8b-9f4a937492ff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_DQar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O17> .
<https://starwars.com#sector_Sanbra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Sanbra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_DQar> <http://www.w3.org/2000/01/rdf-schema#comment> "Site of a Resistance operations base led by General Leia Organa." .

