Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_DAstan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_DAstan> <http://telicent.io/ontology/primaryName> "D'Astan" .
<https://starwars.com#planet_OrdCestus> <http://telicent.io/ontology/primaryName> "Ord Cestus" .
<https://starwars.com#planet_OrdCestus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdCestus> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Cestus, also referred to as simply Cestus, was a planet in the galaxy's Outer Rim Territories. Located in the vicinity of the Perlemian Trade Route, it was situated a considerable distance away from common routes between Geonosis and Coruscant. During the Clone Wars, the Galactic Republic established a medical station near Ord Cestus. " .
<https://starwars.com#planet_OrdCestus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f95d966e-dcb7-4840-b0d9-d748904cccf0> .
<https://starwars.com#planet_OrdCestus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#f95d966e-dcb7-4840-b0d9-d748904cccf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Cestus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdCestus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAstan> .
<https://starwars.com#f95d966e-dcb7-4840-b0d9-d748904cccf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_DAstan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

