Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ccac601f-c79d-4b8c-95b3-d43c408d2137> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hull's Star"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_HullsStar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ccac601f-c79d-4b8c-95b3-d43c408d2137> .
<https://starwars.com#sector_Farana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_HullsStar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_HullsStar> <http://telicent.io/ontology/primaryName> "Hull's Star" .
<https://starwars.com#planet_HullsStar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#ccac601f-c79d-4b8c-95b3-d43c408d2137> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Farana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_HullsStar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Farana> .
<https://starwars.com#planet_HullsStar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Farana> <http://telicent.io/ontology/primaryName> "Farana" .

