Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c661ede2-0d9b-4ddd-8c04-f51e5b99e58e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Bryx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_R8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#780c827f-335d-415e-86b3-6c891aae5af2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Bryx> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c661ede2-0d9b-4ddd-8c04-f51e5b99e58e> .
<https://starwars.com#grid_R8> <http://telicent.io/ontology/primaryName> "R8" .
<https://starwars.com#planet_Bryx> <http://www.w3.org/2000/01/rdf-schema#comment> "Bryx was a planet in the Bryx sector of the Mid Rim. " .
<https://starwars.com#sector_Bryx> <http://telicent.io/ontology/primaryName> "Bryx" .
<https://starwars.com#780c827f-335d-415e-86b3-6c891aae5af2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bryx> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bryx> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bryx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#grid_R8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_R8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#780c827f-335d-415e-86b3-6c891aae5af2> .
<https://starwars.com#planet_Bryx> <http://telicent.io/ontology/primaryName> "Bryx" .
<https://starwars.com#planet_Bryx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bryx> .
<https://starwars.com#c661ede2-0d9b-4ddd-8c04-f51e5b99e58e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bryx"^^<http://www.w3.org/2001/XMLSchema#string> .

