Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lavisar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Strabin> .
<https://starwars.com#sector_Strabin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#904715f6-cfcf-43f8-b3e6-3b3dadeaad45> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#904715f6-cfcf-43f8-b3e6-3b3dadeaad45> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lavisar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lavisar> <http://www.w3.org/2000/01/rdf-schema#comment> "Lavisar was the homeworld of the human Jedi Master Cin Drallig. " .
<https://starwars.com#sector_Strabin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Lavisar> <http://telicent.io/ontology/primaryName> "Lavisar" .
<https://starwars.com#planet_Lavisar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_Lavisar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lavisar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#904715f6-cfcf-43f8-b3e6-3b3dadeaad45> .
<https://starwars.com#sector_Strabin> <http://telicent.io/ontology/primaryName> "Strabin" .

