Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Oplovis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Oplovis> <http://telicent.io/ontology/primaryName> "Oplovis" .
<https://starwars.com#14fe828c-0c04-4423-af66-5ddcdcc4dcb9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#14fe828c-0c04-4423-af66-5ddcdcc4dcb9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Akuria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Akuria> <http://telicent.io/ontology/primaryName> "Akuria" .
<https://starwars.com#planet_Akuria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#14fe828c-0c04-4423-af66-5ddcdcc4dcb9> .
<https://starwars.com#planet_Akuria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Oplovis> .
<https://starwars.com#planet_Akuria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M5> .
<https://starwars.com#planet_Akuria> <http://www.w3.org/2000/01/rdf-schema#comment> "Akuria was an astronomical object located in the galaxy's Outer Rim Territories, not far from the planet Dantooine, that was a suspected base of rebel operations. Akuria and several other locations were identified in a 3 ABY Imperial Security Bureau report that generated targets for Viper probe droid surveys by cross-referencing areas with a high degree of suspicious activity with the unsettled parts of the galaxy favored by the rebels. " .
<https://starwars.com#planet_Akuria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Oplovis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

