Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ralla> <http://telicent.io/ontology/primaryName> "R'alla" .
<https://starwars.com#planet_Ralla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1abadf5c-729d-4d6f-b935-ba48289841ce> .
<https://starwars.com#1abadf5c-729d-4d6f-b935-ba48289841ce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ralla> <http://www.w3.org/2000/01/rdf-schema#comment> "R'alla was a planet in the Corporate Sector, located on the Solenbaran Merchant Route between Bonadan and Kir. R'alla was home to many of the Corporate Sector Authority's top media companies, and its lush, green landscape had many farms and bubbling water springs. R'alla mineral water—which was found in underground caverns below a mountain town also called R'alla— was widely exported throughout the Corporate Sector and beyond, and was often smuggled to nearby, drought-ridden Rampa II. The short route between R'alla and Rampa II was heavy policed by Authority gunships, and was popularly referred to as the Rampa Rapids. " .
<https://starwars.com#1abadf5c-729d-4d6f-b935-ba48289841ce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R'alla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ralla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Ralla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ralla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

