Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ambria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Airon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Airon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#4aa91c1d-8913-4141-b7ec-8ca65bc1bf61> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_O10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Ambria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Airon> .
<https://starwars.com#planet_Ambria> <http://telicent.io/ontology/primaryName> "Ambria" .
<https://starwars.com#964c8c6c-5ee8-43a0-9d2f-59bbfdda79ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ambria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#964c8c6c-5ee8-43a0-9d2f-59bbfdda79ac> .
<https://starwars.com#sector_Airon> <http://telicent.io/ontology/primaryName> "Airon" .
<https://starwars.com#planet_Ambria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#grid_O10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4aa91c1d-8913-4141-b7ec-8ca65bc1bf61> .
<https://starwars.com#grid_O10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_O10> <http://telicent.io/ontology/primaryName> "O10" .
<https://starwars.com#planet_Ambria> <http://www.w3.org/2000/01/rdf-schema#comment> "Ambria was an unpleasant desert planet, in tune with the dark side of the Force, that was located in the galaxy's Inner Rim. It was rumored that Darth Bane, creator of the Rule of Two and the Great Plan, was killed by his Sith apprentice Darth Zannah in a duel on Ambria. " .
<https://starwars.com#964c8c6c-5ee8-43a0-9d2f-59bbfdda79ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ambria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#4aa91c1d-8913-4141-b7ec-8ca65bc1bf61> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O10"^^<http://www.w3.org/2001/XMLSchema#string> .

