Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8db1bbaa-e5fe-4e02-93b2-bc79ff739f49> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jilrua"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jilrua> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Jilrua> <http://telicent.io/ontology/primaryName> "Jilrua" .
<https://starwars.com#planet_Jilrua> <http://www.w3.org/2000/01/rdf-schema#comment> "Jilrua was a desert planet that orbited a blue giant star within the Jilrua system of the galaxy's Hutt Space region, in the immediate vicinity of the Oktos Nebula. " .
<https://starwars.com#8db1bbaa-e5fe-4e02-93b2-bc79ff739f49> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jilrua> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Jilrua> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8db1bbaa-e5fe-4e02-93b2-bc79ff739f49> .
<https://starwars.com#planet_Jilrua> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R12> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

