Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#27092fad-b773-433e-8998-249030f2d150> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q17> .
<https://starwars.com#grid_Q17> <http://telicent.io/ontology/primaryName> "Q17" .
<https://starwars.com#planet_Lok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#27092fad-b773-433e-8998-249030f2d150> .
<https://starwars.com#sector_Karthakk> <http://telicent.io/ontology/primaryName> "Karthakk" .
<https://starwars.com#planet_Lok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4139ed37-788f-491b-87f9-6e739afc2ce8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_Q17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Lok> <http://www.w3.org/2000/01/rdf-schema#comment> "Lok was a world located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#4139ed37-788f-491b-87f9-6e739afc2ce8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Karthakk> .
<https://starwars.com#27092fad-b773-433e-8998-249030f2d150> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lok> <http://telicent.io/ontology/primaryName> "Lok" .
<https://starwars.com#sector_Karthakk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_Q17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4139ed37-788f-491b-87f9-6e739afc2ce8> .
<https://starwars.com#sector_Karthakk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

