Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Refnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#planet_Refnar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e60cd19-90bc-4fd1-a26f-0b41d5f96bb5> .
<https://starwars.com#0e60cd19-90bc-4fd1-a26f-0b41d5f96bb5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Refnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#planet_Refnar> <http://telicent.io/ontology/primaryName> "Refnar" .
<https://starwars.com#0e60cd19-90bc-4fd1-a26f-0b41d5f96bb5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Refnar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#planet_Refnar> <http://www.w3.org/2000/01/rdf-schema#comment> "Refnar was a celestial body located in the Refnar system, a part of the Pakuuni sector in the Slice portion of the Outer Rim Territories. During the early Galactic Civil War, it was the site of a Rebel Alliance base. At some point by 1 BBY, the Galactic Empire discovered the facility and launched an attack on it. Amid the ensuing confrontation between the Alliance and Imperial forces that became known as the 'Last Stand at Refnar,' most of the Rebel freighters, troop transports, and starfighters were able to escape from the Refnar system. " .
<https://starwars.com#planet_Refnar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

