Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PaTho> <http://www.w3.org/2000/01/rdf-schema#comment> "Pa Tho was an astronomical object located in the Inner Rim's Pa Tho system. It shared its name with the alien culture known as the Pa Tho, which had vanished at some point by 16 ABY. Pa Tho was also the homeworld of the Human Rebel pilot Nala Hetsime, who participated in the Battle of Hoth in 3 ABY. " .
<https://starwars.com#planet_PaTho> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#a5b66f92-34ff-4642-a3d8-ae1b5662b25f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pa Tho"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PaTho> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K14> .
<https://starwars.com#planet_PaTho> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a5b66f92-34ff-4642-a3d8-ae1b5662b25f> .
<https://starwars.com#planet_PaTho> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a5b66f92-34ff-4642-a3d8-ae1b5662b25f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PaTho> <http://telicent.io/ontology/primaryName> "Pa Tho" .

