Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_S11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#c501e115-5fc5-435d-80ca-35e8045d2f37> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8c13e2ca-0a53-4c77-b9d6-1db92ef79c28> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cyax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_S11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8c13e2ca-0a53-4c77-b9d6-1db92ef79c28> .
<https://starwars.com#grid_S11> <http://telicent.io/ontology/primaryName> "S11" .
<https://starwars.com#c501e115-5fc5-435d-80ca-35e8045d2f37> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cyax"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#8c13e2ca-0a53-4c77-b9d6-1db92ef79c28> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Cyax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cyax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#planet_Cyax> <http://www.w3.org/2000/01/rdf-schema#comment> "Cyax was the Cyax system's primary star. It was the brightest star in the skies of Varl, and early in the history of the Hutts, they created legends about it and its planets. When the Hutts began their expansion from Varl, they left the Cyax system alone, preferring to allow their myths to remain unchallenged. " .
<https://starwars.com#planet_Cyax> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c501e115-5fc5-435d-80ca-35e8045d2f37> .
<https://starwars.com#planet_Cyax> <http://telicent.io/ontology/primaryName> "Cyax" .

