Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vakkar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#daf9c6bd-44c8-4224-9b2d-a8ff5fee53ee> .
<https://starwars.com#planet_Vakkar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#sector_Fakir> <http://telicent.io/ontology/primaryName> "Fakir" .
<https://starwars.com#daf9c6bd-44c8-4224-9b2d-a8ff5fee53ee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vakkar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Fakir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Vakkar> <http://telicent.io/ontology/primaryName> "Vakkar" .
<https://starwars.com#planet_Vakkar> <http://www.w3.org/2000/01/rdf-schema#comment> "Vakkar was an astronomical object located in the galaxy's Colonies region, along the Shwuy Exchange hyperspace route. " .
<https://starwars.com#sector_Fakir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vakkar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Fakir> .
<https://starwars.com#daf9c6bd-44c8-4224-9b2d-a8ff5fee53ee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vakkar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

