Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Karvoss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#ceb9327a-2fb1-451d-81d0-f1455c564507> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karvoss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Karvoss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ceb9327a-2fb1-451d-81d0-f1455c564507> .
<https://starwars.com#planet_Karvoss> <http://telicent.io/ontology/primaryName> "Karvoss" .
<https://starwars.com#planet_Karvoss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ceb9327a-2fb1-451d-81d0-f1455c564507> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Karvoss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .

