Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Korvaii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Korvaii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kordu> .
<https://starwars.com#planet_Korvaii> <http://telicent.io/ontology/primaryName> "Korvaii" .
<https://starwars.com#sector_Kordu> <http://telicent.io/ontology/primaryName> "Kordu" .
<https://starwars.com#planet_Korvaii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#2e0c7688-f4ed-44d6-a374-22fc6e459189> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kordu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Korvaii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e0c7688-f4ed-44d6-a374-22fc6e459189> .
<https://starwars.com#planet_Korvaii> <http://www.w3.org/2000/01/rdf-schema#comment> "Korvaii was a small agriworld located in the Kordu sector of the Mid Rim. " .
<https://starwars.com#sector_Kordu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#2e0c7688-f4ed-44d6-a374-22fc6e459189> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korvaii"^^<http://www.w3.org/2001/XMLSchema#string> .

