Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lowick> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ceb8bb98-7b54-432c-a6a4-fe93afe3ffc7> .
<https://starwars.com#planet_Lowick> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#ceb8bb98-7b54-432c-a6a4-fe93afe3ffc7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lowick"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ceb8bb98-7b54-432c-a6a4-fe93afe3ffc7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_U9> <http://telicent.io/ontology/primaryName> "U9" .
<https://starwars.com#planet_Lowick> <http://www.w3.org/2000/01/rdf-schema#comment> "Lowick was the swampy homeworld of the Pa'lowick singer Sy Snootles. " .
<https://starwars.com#0242c197-566e-434c-8555-07e3dda4f182> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lowick> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U9> .
<https://starwars.com#grid_U9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_U9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0242c197-566e-434c-8555-07e3dda4f182> .
<https://starwars.com#planet_Lowick> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lowick> <http://telicent.io/ontology/primaryName> "Lowick" .
<https://starwars.com#grid_U9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#0242c197-566e-434c-8555-07e3dda4f182> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

