Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#67729e65-f25a-469d-8418-2264bacba5ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Makeb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#planet_Makeb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Makeb> <http://telicent.io/ontology/primaryName> "Makeb" .
<https://starwars.com#planet_Makeb> <http://www.w3.org/2000/01/rdf-schema#comment> "Makeb was a planet invaded by the Hutt Cartel during the Galactic War. It was a major source of isotope-5, one of the rarest minerals in the galaxy. " .
<https://starwars.com#planet_Makeb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Makeb> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#67729e65-f25a-469d-8418-2264bacba5ef> .
<https://starwars.com#67729e65-f25a-469d-8418-2264bacba5ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Makeb"^^<http://www.w3.org/2001/XMLSchema#string> .

