Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Poseidenna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bb46bf89-c902-4b75-b9c6-8dc282fcfc5d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Poseidenna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Poseidenna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bb46bf89-c902-4b75-b9c6-8dc282fcfc5d> .
<https://starwars.com#bb46bf89-c902-4b75-b9c6-8dc282fcfc5d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Poseidenna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Poseidenna> <http://telicent.io/ontology/primaryName> "Poseidenna" .
<https://starwars.com#planet_Poseidenna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Poseidenna> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

