Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e44ff69e-7156-49fd-9d95-89e05b4c15f5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Columex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Columex> <http://www.w3.org/2000/01/rdf-schema#comment> "Columex was an astronomical object located in the galaxy's Outer Rim Territories along the Perlemian Trade Route and the Salin Corridor. " .
<https://starwars.com#planet_Columex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e44ff69e-7156-49fd-9d95-89e05b4c15f5> .
<https://starwars.com#e44ff69e-7156-49fd-9d95-89e05b4c15f5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Vorzyd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Columex> <http://telicent.io/ontology/primaryName> "Columex" .
<https://starwars.com#sector_Vorzyd> <http://telicent.io/ontology/primaryName> "Vorzyd" .
<https://starwars.com#sector_Vorzyd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Columex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vorzyd> .
<https://starwars.com#planet_Columex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Columex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

