Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_M19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Bpfassh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sluis> .
<https://starwars.com#grid_M19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#93a6e56d-79bd-42a5-aceb-86b427990505> .
<https://starwars.com#planet_Bpfassh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bpfassh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#683be8ef-ca32-4481-a5d8-3711b4ab4e3e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bpfassh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sluis> <http://telicent.io/ontology/primaryName> "Sluis" .
<https://starwars.com#planet_Bpfassh> <http://telicent.io/ontology/primaryName> "Bpfassh" .
<https://starwars.com#planet_Bpfassh> <http://www.w3.org/2000/01/rdf-schema#comment> "Bpfassh was an arid double planet in the Sluis sector orbited by a complicated system of moons, located near Praesitlyn and Sluis Van. It was the homeworld of the Bpfasshi. " .
<https://starwars.com#grid_M19> <http://telicent.io/ontology/primaryName> "M19" .
<https://starwars.com#683be8ef-ca32-4481-a5d8-3711b4ab4e3e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sluis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_M19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Sluis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#93a6e56d-79bd-42a5-aceb-86b427990505> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#93a6e56d-79bd-42a5-aceb-86b427990505> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bpfassh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#683be8ef-ca32-4481-a5d8-3711b4ab4e3e> .

