Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tierfon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tierfon> <http://telicent.io/ontology/primaryName> "Tierfon" .
<https://starwars.com#planet_Tierfon> <http://www.w3.org/2000/01/rdf-schema#comment> "Tierfon was a planet in the Mid Rim that was considered a Rebel Alliance starfighter hub that was at least a level five during the early rebellion against the Galactic Empire. Tierfon was included in a map of the galaxy that listed safe worlds, starfighter hubs at level five or higher, regional headquarters and operations sectors, and deep space caches. The map was later included in The Rebel Files. " .
<https://starwars.com#planet_Tierfon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dentari> .
<https://starwars.com#2880ed3f-adef-4779-9fce-ba18090dfdee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2880ed3f-adef-4779-9fce-ba18090dfdee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tierfon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tierfon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2880ed3f-adef-4779-9fce-ba18090dfdee> .
<https://starwars.com#sector_Dentari> <http://telicent.io/ontology/primaryName> "Dentari" .
<https://starwars.com#planet_Tierfon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#sector_Dentari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Dentari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

