Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_C16> <http://telicent.io/ontology/primaryName> "C16" .
<https://starwars.com#grid_C16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#4a6e7d7d-b559-431b-8111-4b5d94faac79> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lwhekk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lwhekk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_C16> .
<https://starwars.com#grid_C16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_C16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4888a0b5-90b2-4ce7-9779-1ef7e9d4b1d8> .
<https://starwars.com#4888a0b5-90b2-4ce7-9779-1ef7e9d4b1d8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#4888a0b5-90b2-4ce7-9779-1ef7e9d4b1d8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "C16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lwhekk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4a6e7d7d-b559-431b-8111-4b5d94faac79> .
<https://starwars.com#planet_Lwhekk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4a6e7d7d-b559-431b-8111-4b5d94faac79> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lwhekk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Lwhekk> <http://telicent.io/ontology/primaryName> "Lwhekk" .
<https://starwars.com#planet_Lwhekk> <http://www.w3.org/2000/01/rdf-schema#comment> "Lwhekk was an astronomical object located in the galaxy's Unknown Regions. " .

