Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lown> <http://www.w3.org/2000/01/rdf-schema#comment> "Low'n was a populous world in the Romintine sector of the Mid Rim. It was the homeworld of the Lowen. " .
<https://starwars.com#planet_Lown> <http://telicent.io/ontology/primaryName> "Low'n" .
<https://starwars.com#df4bccf3-ead8-43d0-a1b7-6feb099193c8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Low'n"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lown> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Romintine> .
<https://starwars.com#df4bccf3-ead8-43d0-a1b7-6feb099193c8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Romintine> <http://telicent.io/ontology/primaryName> "Romintine" .
<https://starwars.com#planet_Lown> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df4bccf3-ead8-43d0-a1b7-6feb099193c8> .
<https://starwars.com#sector_Romintine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Romintine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lown> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lown> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .

