Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Miztoc> <http://telicent.io/ontology/primaryName> "Miztoc" .
<https://starwars.com#planet_Miztoc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#82585a6f-76a0-4bfd-a9e1-4e2513389715> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Miztoc"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Miztoc> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82585a6f-76a0-4bfd-a9e1-4e2513389715> .
<https://starwars.com#sector_Irnaj> <http://telicent.io/ontology/primaryName> "Irnaj" .
<https://starwars.com#planet_Miztoc> <http://www.w3.org/2000/01/rdf-schema#comment> "Miztoc was a planet liberated from the Galactic Empire by the Rebel Alliance. " .
<https://starwars.com#82585a6f-76a0-4bfd-a9e1-4e2513389715> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Irnaj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Miztoc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Irnaj> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Miztoc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Irnaj> .

