Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Corlass> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Corlass> <http://www.w3.org/2000/01/rdf-schema#comment> "Corlass was a planet of pirates, both seafaring and spacefaring. Located within the Outer Rim Territories, it was one of the original member-worlds of the Kingdom of Cron. It was absorbed into Xim's empire, and the Despot used many former Corlassi pirates as the captains of his warships. " .
<https://starwars.com#a257cf0b-ca77-4c1f-aea8-5a3298d03750> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Corlass> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .
<https://starwars.com#planet_Corlass> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a257cf0b-ca77-4c1f-aea8-5a3298d03750> .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Corlass> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a257cf0b-ca77-4c1f-aea8-5a3298d03750> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Corlass"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Corlass> <http://telicent.io/ontology/primaryName> "Corlass" .

