Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Klatooine> <http://telicent.io/ontology/primaryName> "Klatooine" .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Klatooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#17addd29-00f0-44eb-a743-9dfceab30ceb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Klatooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Klatooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Klatooine was a desert planet located within Hutt Space of the galaxy's Outer Rim Territories that was the homeworld of the Klatooinian species. The former pirate Queen Maz Kanata marked it as a point of interest on a map she included in the book that would become known as the Smuggler's Guide. The xenolinguist Jaiyna Sibinth, who studied the language of Pasaana's Aki-Aki, saw similar recurring symbols and themes to the native cultures of other desert planets, including Klatooine's. " .
<https://starwars.com#planet_Klatooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#17addd29-00f0-44eb-a743-9dfceab30ceb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Klatooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Klatooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#17addd29-00f0-44eb-a743-9dfceab30ceb> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

