Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a6243a12-428a-4f3a-a89e-796c006b5444> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ket"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ket> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ket> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Ket> <http://www.w3.org/2000/01/rdf-schema#comment> "Ket was a planet in the Lorelli Reach region of the Hapes Cluster. It was the homeworld of the nomadic Ketton species. " .
<https://starwars.com#a6243a12-428a-4f3a-a89e-796c006b5444> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Ket> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a6243a12-428a-4f3a-a89e-796c006b5444> .
<https://starwars.com#planet_Ket> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ket> <http://telicent.io/ontology/primaryName> "Ket" .

