Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thebeon> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Thebeon> <http://telicent.io/ontology/primaryName> "Thebeon" .
<https://starwars.com#planet_Thebeon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thebeon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#99225f9b-0d89-46cc-9bec-fc84d29c1935> .
<https://starwars.com#99225f9b-0d89-46cc-9bec-fc84d29c1935> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#99225f9b-0d89-46cc-9bec-fc84d29c1935> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thebeon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thebeon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Thebeon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

