Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Asation> <http://telicent.io/ontology/primaryName> "Asation" .
<https://starwars.com#planet_Asation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gree> .
<https://starwars.com#planet_Asation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1b79bd93-35b4-4a67-a5ab-baaa17041e80> .
<https://starwars.com#sector_Gree> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1b79bd93-35b4-4a67-a5ab-baaa17041e80> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Asation> <http://www.w3.org/2000/01/rdf-schema#comment> "Asation was the major port world of the Gree Enclave and was home to the Crafter caste of the Gree. " .
<https://starwars.com#sector_Gree> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Gree> <http://telicent.io/ontology/primaryName> "Gree" .
<https://starwars.com#planet_Asation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#planet_Asation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1b79bd93-35b4-4a67-a5ab-baaa17041e80> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Asation"^^<http://www.w3.org/2001/XMLSchema#string> .

