Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Seyugi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#2933e042-1833-4b47-a198-a5d8b9049b0c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Seyugi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Seyugi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Seyugi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Seyugi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2933e042-1833-4b47-a198-a5d8b9049b0c> .
<https://starwars.com#planet_Seyugi> <http://www.w3.org/2000/01/rdf-schema#comment> "Seyugi was an astronomical object located in the Seyugi system of the Arrowhead, a region in the Slice portion of the Core Worlds. Seyugi fell within the borders of the Galactic Republic around 22,000 BBY. " .
<https://starwars.com#planet_Seyugi> <http://telicent.io/ontology/primaryName> "Seyugi" .
<https://starwars.com#2933e042-1833-4b47-a198-a5d8b9049b0c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

