Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_DuHutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#e6a3c0b7-b5a2-4c60-b014-4b113417d6ee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Du Hutta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e6a3c0b7-b5a2-4c60-b014-4b113417d6ee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_DuHutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_DuHutta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6a3c0b7-b5a2-4c60-b014-4b113417d6ee> .
<https://starwars.com#planet_DuHutta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_DuHutta> <http://www.w3.org/2000/01/rdf-schema#comment> "Du Hutta was a planet located in Hutt Space. It was a Hutt colony world and was home to many private retreats owned by Nal Hutta's Hutts. After the Battle of Endor, Umpass-stay went to work for Jocoro Desilijic Tiure on Du Hutta. " .
<https://starwars.com#planet_DuHutta> <http://telicent.io/ontology/primaryName> "Du Hutta" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

