Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Filordis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Filordis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Larrin> .
<https://starwars.com#planet_Filordis> <http://telicent.io/ontology/primaryName> "Filordis" .
<https://starwars.com#planet_Filordis> <http://www.w3.org/2000/01/rdf-schema#comment> "Filordis was an Inner Rim Territories astronomical object located in grid square N-8 of the Standard Galactic Grid. " .
<https://starwars.com#fb4523f8-d7d8-4c6a-b414-c0442581e7c4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Filordis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fb4523f8-d7d8-4c6a-b414-c0442581e7c4> .
<https://starwars.com#sector_Larrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Larrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_Larrin> <http://telicent.io/ontology/primaryName> "Larrin" .
<https://starwars.com#fb4523f8-d7d8-4c6a-b414-c0442581e7c4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Filordis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Filordis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

