Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bastooine> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Bastooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_I17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#2f96f81f-006c-4266-970a-31c67ef62a55> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bastooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Graador> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_I17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c0f44de6-46be-40e0-972e-0336de556505> .
<https://starwars.com#planet_Bastooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Graador> .
<https://starwars.com#2f96f81f-006c-4266-970a-31c67ef62a55> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_I17> <http://telicent.io/ontology/primaryName> "I17" .
<https://starwars.com#sector_Graador> <http://telicent.io/ontology/primaryName> "Graador" .
<https://starwars.com#grid_I17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#c0f44de6-46be-40e0-972e-0336de556505> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Graador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Bastooine> <http://telicent.io/ontology/primaryName> "Bastooine" .
<https://starwars.com#planet_Bastooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#c0f44de6-46be-40e0-972e-0336de556505> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Bastooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2f96f81f-006c-4266-970a-31c67ef62a55> .

