Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Brosi> <http://www.w3.org/2000/01/rdf-schema#comment> "Brosi was the homeworld of the Brosin species, in the Thandon Cluster, a remote place in the Corporate Sector. It was the fourth planet in the Dostra system, and one of the few homeworlds within the Corporate Sector. " .
<https://starwars.com#ca5e197e-91fc-476d-83b4-232d2325cf81> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Brosi> <http://telicent.io/ontology/primaryName> "Brosi" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Brosi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#ca5e197e-91fc-476d-83b4-232d2325cf81> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Brosi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Brosi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Brosi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Brosi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca5e197e-91fc-476d-83b4-232d2325cf81> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

