Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gibbela> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#planet_Gibbela> <http://telicent.io/ontology/primaryName> "Gibbela" .
<https://starwars.com#planet_Gibbela> <http://www.w3.org/2000/01/rdf-schema#comment> "During the reign of the Galactic Empire, an Imperial detachment was sent to Gibbela to scout the planet before its planned colonization. Landing at a farm of one of the local Dazouri, the officer leading the Imperial force claimed the planet for the Empire and demanded the farmer's surrender. In response, however, the Dazouri transformed into a large, ferocious killer and wiped out the Imperials, subsequently repurposing their leftover equipment as farming tools. " .
<https://starwars.com#planet_Gibbela> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bea21038-31a6-4876-9e3a-2efccf115795> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#bea21038-31a6-4876-9e3a-2efccf115795> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gibbela> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gibbela> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .
<https://starwars.com#bea21038-31a6-4876-9e3a-2efccf115795> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gibbela"^^<http://www.w3.org/2001/XMLSchema#string> .

