Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ladarra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ladarra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Ladarra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_Ladarra> <http://www.w3.org/2000/01/rdf-schema#comment> "Ladarra was a desert planet in the Gordian Reach along the Pinooran Spur. It was the location of the Human colony of New Hope Settlement. The planet was colonized during the days of the Old Republic and ended up becoming a failed chromium mine. By the time of the Galactic Empire, the planet's people were dying out. All that was left were poor farmers, hermits and fugitives, as well as some dust balls from the rust-colored desert. " .
<https://starwars.com#planet_Ladarra> <http://telicent.io/ontology/primaryName> "Ladarra" .
<https://starwars.com#planet_Ladarra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33059bc0-8a41-4d5c-b12f-b1a461b59e74> .
<https://starwars.com#33059bc0-8a41-4d5c-b12f-b1a461b59e74> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#33059bc0-8a41-4d5c-b12f-b1a461b59e74> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ladarra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

