Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#169c1f1e-5a92-4547-b2e9-f42991dcc504> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ebaq"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ebaq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Ebaq> <http://telicent.io/ontology/primaryName> "Ebaq" .
<https://starwars.com#planet_Ebaq> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#169c1f1e-5a92-4547-b2e9-f42991dcc504> .
<https://starwars.com#planet_Ebaq> <http://www.w3.org/2000/01/rdf-schema#comment> "Ebaq was an astronomical object situated in the treacherous Deep Core region. " .
<https://starwars.com#169c1f1e-5a92-4547-b2e9-f42991dcc504> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ebaq> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ebaq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .

