Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kumru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .
<https://starwars.com#planet_Kumru> <http://www.w3.org/2000/01/rdf-schema#comment> "Kumru was an astronomical object located in the Javin Sector of Mugaari Space along the Corellian Trade Spine. " .
<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kumru> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kumru> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d6418df7-aff0-4640-9e94-f35f752d4f5e> .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kumru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#d6418df7-aff0-4640-9e94-f35f752d4f5e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d6418df7-aff0-4640-9e94-f35f752d4f5e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kumru"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kumru> <http://telicent.io/ontology/primaryName> "Kumru" .

