Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GosHutta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0bbb2b82-2ba5-428a-99ab-12628fc5388c> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#0bbb2b82-2ba5-428a-99ab-12628fc5388c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gos Hutta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_GosHutta> <http://telicent.io/ontology/primaryName> "Gos Hutta" .
<https://starwars.com#0bbb2b82-2ba5-428a-99ab-12628fc5388c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_GosHutta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_GosHutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#planet_GosHutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_GosHutta> <http://www.w3.org/2000/01/rdf-schema#comment> "The Gos Hutta system, also called Gos Hutta, was a Hutt Space star system that lay within the Bootana Hutta area. The system contained three planets and several space stations, and it served as a gateway to the Bootana Hutta, being frequently patrolled by warships of the Hutt species. The system was used at some point by Hutt clan leaders to meet privileged foreigners. " .

