Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Spefik> <http://www.w3.org/2000/01/rdf-schema#comment> "Spefik was a barren, rocky planet in the Atrivis sector of the Outer Rim Territories. The planet was home to a Rebel base during the Galactic Civil War; however, the base was destroyed by Imperial forces in the battle of Spefik around 0.5 ABY. Imperial pilot Ranulf Trommer distinguished himself in that battle. " .
<https://starwars.com#planet_Spefik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Spefik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_Spefik> <http://telicent.io/ontology/primaryName> "Spefik" .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#95cdc047-c885-470a-a9b2-57847b958869> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Spefik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Spefik> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95cdc047-c885-470a-a9b2-57847b958869> .
<https://starwars.com#95cdc047-c885-470a-a9b2-57847b958869> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Spefik"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

