Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gulma> <http://www.w3.org/2000/01/rdf-schema#comment> "Gulma was a planet located within the Gulma system in Wild Space and was the homeworld of the Gulmarid species. The planet was covered by swampy terrain. " .
<https://starwars.com#planet_Gulma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P3> .
<https://starwars.com#planet_Gulma> <http://telicent.io/ontology/primaryName> "Gulma" .
<https://starwars.com#planet_Gulma> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f01e964-e18e-4cfe-9fe0-50f6244070da> .
<https://starwars.com#4f01e964-e18e-4cfe-9fe0-50f6244070da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gulma"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gulma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gulma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#4f01e964-e18e-4cfe-9fe0-50f6244070da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

