Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sorjus> <http://telicent.io/ontology/primaryName> "Sorjus" .
<https://starwars.com#sector_Meridian> <http://telicent.io/ontology/primaryName> "Meridian" .
<https://starwars.com#planet_Sorjus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95e228cf-be01-4dc0-97fa-4326caaadeaa> .
<https://starwars.com#planet_Sorjus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#95e228cf-be01-4dc0-97fa-4326caaadeaa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sorjus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#95e228cf-be01-4dc0-97fa-4326caaadeaa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sorjus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meridian> .
<https://starwars.com#sector_Meridian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Meridian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sorjus> <http://www.w3.org/2000/01/rdf-schema#comment> "Sorjus was the Basic name for the home planet of the Paaerduag. The true name was only pronounceable and understandable by the Paaerduag. The planet was far off from the Perlemian Trade Route. " .
<https://starwars.com#planet_Sorjus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .

