Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_AlliedTion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cadinth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cadinth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#91fbadd8-b9d1-45fb-a09f-c5871cb0b409> .
<https://starwars.com#planet_Cadinth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AlliedTion> .
<https://starwars.com#sector_AlliedTion> <http://telicent.io/ontology/primaryName> "Allied Tion" .
<https://starwars.com#91fbadd8-b9d1-45fb-a09f-c5871cb0b409> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#91fbadd8-b9d1-45fb-a09f-c5871cb0b409> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cadinth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cadinth> <http://telicent.io/ontology/primaryName> "Cadinth" .
<https://starwars.com#planet_Cadinth> <http://www.w3.org/2000/01/rdf-schema#comment> "Cadinth was an astronomical object located in the Tion Cluster of the regions known as the Outer Rim Territories and the Slice. Located in grid square S-6 on the Standard Galactic Grid, Cadinth was situated along the Shaltin Tunnels hyperspace route, which connected it to the astronomical objects Lianna and Jaminere. " .
<https://starwars.com#sector_AlliedTion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cadinth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .

