Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3c3ba07a-d3a5-4970-aaa1-265f0039ecd5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Motexx"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Motexx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#3c3ba07a-d3a5-4970-aaa1-265f0039ecd5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Motexx> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c3ba07a-d3a5-4970-aaa1-265f0039ecd5> .
<https://starwars.com#planet_Motexx> <http://www.w3.org/2000/01/rdf-schema#comment> "Motexx was a planet located in the Colonies region on the other side of the Black Nebula from Arat Fraca. " .
<https://starwars.com#planet_Motexx> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Motexx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Motexx> <http://telicent.io/ontology/primaryName> "Motexx" .

