Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3717585b-8d7e-4d48-8f49-55fcc7d3b497> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Marquarra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3717585b-8d7e-4d48-8f49-55fcc7d3b497> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Marquarra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Marquarra> <http://www.w3.org/2000/01/rdf-schema#comment> "Marquarra was an Outer Rim planet with a weapons cache of the Ubiqtorate. It was allied with the Imperial Remnant. " .
<https://starwars.com#planet_Marquarra> <http://telicent.io/ontology/primaryName> "Marquarra" .
<https://starwars.com#planet_Marquarra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3717585b-8d7e-4d48-8f49-55fcc7d3b497> .
<https://starwars.com#planet_Marquarra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#planet_Marquarra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .

