Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b8c33151-0e1d-407c-aa41-7271490c387a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#grid_R17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0f20ced0-76f0-4762-8bf6-b18486cb6788> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#0f20ced0-76f0-4762-8bf6-b18486cb6788> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_R17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_R17> <http://telicent.io/ontology/primaryName> "R17" .
<https://starwars.com#planet_Arkanis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b8c33151-0e1d-407c-aa41-7271490c387a> .
<https://starwars.com#planet_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b8c33151-0e1d-407c-aa41-7271490c387a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arkanis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_R17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Arkanis> <http://www.w3.org/2000/01/rdf-schema#comment> "Following the Galactic Empire's losses at the Battle of Endor, Arkanis remained under the Empire's control for a time, but the system was targeted by the New Republic, freed from the Empire's influence and claimed for the New Republic's side. Arkanis eventually became a wealthy planet of the New Republic, aligned with the Centrists, and represented in the Galactic Senate by Senator Carise Sindian. " .
<https://starwars.com#0f20ced0-76f0-4762-8bf6-b18486cb6788> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .

