Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Subterrel> .
<https://starwars.com#planet_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#planet_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#planet_Subterrel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#57c1f523-460c-4550-a4ca-97c4d0320a2f> .
<https://starwars.com#sector_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L20> .
<https://starwars.com#57c1f523-460c-4550-a4ca-97c4d0320a2f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#57c1f523-460c-4550-a4ca-97c4d0320a2f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Subterrel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Subterrel> <http://www.w3.org/2000/01/rdf-schema#comment> "Mining planet mentioned by Dexter Jettster who spent time prospecting there. Located near Kamino, beyond the Outer Rim." .

