Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Derellium> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2442bd8-7423-4b7c-b25d-6af95141c5a3> .
<https://starwars.com#planet_Derellium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a2442bd8-7423-4b7c-b25d-6af95141c5a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Derellium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#planet_Derellium> <http://telicent.io/ontology/primaryName> "Derellium" .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#a2442bd8-7423-4b7c-b25d-6af95141c5a3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Derellium"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Derellium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Derellium> <http://www.w3.org/2000/01/rdf-schema#comment> "Derellium was a planet of located within the Cronese Mandate of the Outer Rim. " .

