Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bavva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Bavva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#de4b4ed2-f2f2-454c-8d46-4962278ac654> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bavva"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#de4b4ed2-f2f2-454c-8d46-4962278ac654> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Bavva> <http://www.w3.org/2000/01/rdf-schema#comment> "Bavva was a planet inside the Anoat sector in the the galaxy. Over several months during the Iron Blockade of the sector by the Galactic Empire, a merchant on Bavva was robbed several times. The merchant then offered payment for an experienced individual to provide them personal security. " .
<https://starwars.com#planet_Bavva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Bavva> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#de4b4ed2-f2f2-454c-8d46-4962278ac654> .
<https://starwars.com#planet_Bavva> <http://telicent.io/ontology/primaryName> "Bavva" .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

