Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Dominus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lothal> <http://telicent.io/ontology/primaryName> "Lothal" .
<https://starwars.com#planet_Lothal> <http://www.w3.org/2000/01/rdf-schema#comment> "Remote farm planet and birthplace of Ezra Bridger." .
<https://starwars.com#planet_Lothal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#planet_Lothal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#11b59501-dca0-4a79-8c5e-ac009eab2552> .
<https://starwars.com#planet_Lothal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#11b59501-dca0-4a79-8c5e-ac009eab2552> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#11b59501-dca0-4a79-8c5e-ac009eab2552> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lothal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dominus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Dominus> <http://telicent.io/ontology/primaryName> "Dominus" .
<https://starwars.com#planet_Lothal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dominus> .

