Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9aada726-7c66-4292-a8fd-db6b999358f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Camden"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9aada726-7c66-4292-a8fd-db6b999358f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Camden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Morshdine> .
<https://starwars.com#planet_Camden> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9aada726-7c66-4292-a8fd-db6b999358f6> .
<https://starwars.com#planet_Camden> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#planet_Camden> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Morshdine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Camden> <http://telicent.io/ontology/primaryName> "Camden" .
<https://starwars.com#sector_Morshdine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Morshdine> <http://telicent.io/ontology/primaryName> "Morshdine" .
<https://starwars.com#planet_Camden> <http://www.w3.org/2000/01/rdf-schema#comment> "Camden was an Outer Rim Imperial planet in the Camden system. The Snakes' Den starport was on Camden. " .

