Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#bedd5888-5394-456f-b8ab-12f96a30047e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fondor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fondor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Fondor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Fondor> <http://telicent.io/ontology/primaryName> "Fondor" .
<https://starwars.com#planet_Fondor> <http://www.w3.org/2000/01/rdf-schema#comment> "Imperial manufacturing center with large shipyards." .
<https://starwars.com#planet_Fondor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fondor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bedd5888-5394-456f-b8ab-12f96a30047e> .
<https://starwars.com#bedd5888-5394-456f-b8ab-12f96a30047e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

