Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Polus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Polus> <http://www.w3.org/2000/01/rdf-schema#comment> "Polus was an ice world orbiting the binary star Avindia of the Avindia system in the Outer Rim Territories. A frigid, mountainous planet, it had a massive frozen ocean and blizzards as well as ice storms that would frequently scour the planet's surface. Its average day temperature was 50 degrees below freezing. Polus was the homeworld of the Pyn'gani, a near-Human species. " .
<https://starwars.com#planet_Polus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6b7fae27-dc23-4a72-b9ac-fdc16af5d5cd> .
<https://starwars.com#sector_Oricho> <http://telicent.io/ontology/primaryName> "Oricho" .
<https://starwars.com#planet_Polus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Oricho> .
<https://starwars.com#sector_Oricho> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Polus> <http://telicent.io/ontology/primaryName> "Polus" .
<https://starwars.com#6b7fae27-dc23-4a72-b9ac-fdc16af5d5cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Polus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .
<https://starwars.com#6b7fae27-dc23-4a72-b9ac-fdc16af5d5cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Polus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Oricho> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

