Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Taboon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#ceaae1f2-2d12-45a7-9dbc-2a9829e77c90> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taboon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ceaae1f2-2d12-45a7-9dbc-2a9829e77c90> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Taboon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Airon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Taboon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ceaae1f2-2d12-45a7-9dbc-2a9829e77c90> .
<https://starwars.com#sector_Airon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Taboon> <http://www.w3.org/2000/01/rdf-schema#comment> "Taboon was a gas giant in the Aweris system. It was the source of Taboon hardwood. Bogga the Hutt's palace was on Vo Dasha, the moon orbiting Taboon. " .
<https://starwars.com#planet_Taboon> <http://telicent.io/ontology/primaryName> "Taboon" .
<https://starwars.com#planet_Taboon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Airon> .
<https://starwars.com#sector_Airon> <http://telicent.io/ontology/primaryName> "Airon" .

