Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Barcaria> <http://telicent.io/ontology/primaryName> "Barcaria" .
<https://starwars.com#planet_Barcaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#planet_Barcaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sombure> .
<https://starwars.com#planet_Barcaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#028edabd-87e7-442f-b3cf-05ea76107243> .
<https://starwars.com#028edabd-87e7-442f-b3cf-05ea76107243> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Barcaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sombure> <http://telicent.io/ontology/primaryName> "Sombure" .
<https://starwars.com#planet_Barcaria> <http://www.w3.org/2000/01/rdf-schema#comment> "Barcaria was the primary planet of the Barcaria system. The homeworld of famous Republic soldier Jace Malcom, the planet was famous for its Barcarian claw salt. " .
<https://starwars.com#sector_Sombure> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#028edabd-87e7-442f-b3cf-05ea76107243> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barcaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sombure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

