Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Druckenwell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#71edb1fd-0362-4422-9476-7784fc60ad0e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Druckenwell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Druckenwell> <http://telicent.io/ontology/primaryName> "Druckenwell" .
<https://starwars.com#planet_Druckenwell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#71edb1fd-0362-4422-9476-7784fc60ad0e> .
<https://starwars.com#sector_Doldur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#71edb1fd-0362-4422-9476-7784fc60ad0e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Druckenwell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Doldur> .
<https://starwars.com#sector_Doldur> <http://telicent.io/ontology/primaryName> "Doldur" .
<https://starwars.com#planet_Druckenwell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#planet_Druckenwell> <http://www.w3.org/2000/01/rdf-schema#comment> "Druckenwell was an astronomical object located in the galaxy's Mid Rim along the Corellian Run. " .
<https://starwars.com#sector_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

