Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Wornal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kriselist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#planet_Kriselist> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#214cc4c7-8548-409d-99b4-04712ebf0067> .
<https://starwars.com#planet_Kriselist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wornal> .
<https://starwars.com#planet_Kriselist> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kriselist> <http://telicent.io/ontology/primaryName> "Kriselist" .
<https://starwars.com#planet_Kriselist> <http://www.w3.org/2000/01/rdf-schema#comment> "Kriselist was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#214cc4c7-8548-409d-99b4-04712ebf0067> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#214cc4c7-8548-409d-99b4-04712ebf0067> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kriselist"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Wornal> <http://telicent.io/ontology/primaryName> "Wornal" .
<https://starwars.com#sector_Wornal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

