Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#01ed9fc9-1bc5-484d-806d-f71a4d6b9826> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vaynai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Chorlian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vaynai> <http://www.w3.org/2000/01/rdf-schema#comment> "Vaynai was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Vaynai> <http://telicent.io/ontology/primaryName> "Vaynai" .
<https://starwars.com#01ed9fc9-1bc5-484d-806d-f71a4d6b9826> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vaynai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vaynai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#sector_Chorlian> <http://telicent.io/ontology/primaryName> "Chorlian" .
<https://starwars.com#planet_Vaynai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chorlian> .
<https://starwars.com#planet_Vaynai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#01ed9fc9-1bc5-484d-806d-f71a4d6b9826> .
<https://starwars.com#sector_Chorlian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

