Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Karlinus> <http://www.w3.org/2000/01/rdf-schema#comment> "Karlinus was a prosperous planet located in the Chommell sector of the galaxy's Mid Rim, known for its agricultural industry and its workforce with a high turnover rate. When Padmé Amidala wished to rescue slaves from Tatooine, she and Sabé chose to let them live a new life on Karlinus. Sabé managed to rescue twenty-five slaves, giving them jobs on Karlinus with the help of the planet's governor, Kelma. " .
<https://starwars.com#planet_Karlinus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chommel> .
<https://starwars.com#planet_Karlinus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O16> .
<https://starwars.com#planet_Karlinus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2fc74b56-91b4-444c-a344-3fbea8f175b8> .
<https://starwars.com#sector_Chommel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Chommel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Karlinus> <http://telicent.io/ontology/primaryName> "Karlinus" .
<https://starwars.com#sector_Chommel> <http://telicent.io/ontology/primaryName> "Chommel" .
<https://starwars.com#2fc74b56-91b4-444c-a344-3fbea8f175b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Karlinus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2fc74b56-91b4-444c-a344-3fbea8f175b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karlinus"^^<http://www.w3.org/2001/XMLSchema#string> .

