Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tsurr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_NuoneSafyd> .
<https://starwars.com#planet_Tsurr> <http://telicent.io/ontology/primaryName> "T'surr" .
<https://starwars.com#planet_Tsurr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_NuoneSafyd> <http://telicent.io/ontology/primaryName> "Nuon e Safyd" .
<https://starwars.com#sector_NuoneSafyd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tsurr> <http://www.w3.org/2000/01/rdf-schema#comment> "T'surr was a cold and windswept high-gravity planet in the Expansion Region's Nuon e Safyd sector. Most of the planet's lifeforms had excellent low-light vision, and the harsh conditions of the world gave rise to a predatory sentient species also known as the T'surr. T'surr males often left their homeworld for the wider galaxy, but their planet was never represented in the Galactic Republic or the New Republic. " .
<https://starwars.com#planet_Tsurr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f08732d4-d29d-483e-893e-6c0f49b0786a> .
<https://starwars.com#planet_Tsurr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#f08732d4-d29d-483e-893e-6c0f49b0786a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T'surr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f08732d4-d29d-483e-893e-6c0f49b0786a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_NuoneSafyd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

