Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nadiem> <http://www.w3.org/2000/01/rdf-schema#comment> "Nadiem was a remote planet in the Outer Rim Territories. It was close to Teth. " .
<https://starwars.com#planet_Nadiem> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2bb3701c-925c-4d49-b7b5-5c25ce423c56> .
<https://starwars.com#planet_Nadiem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#planet_Nadiem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2bb3701c-925c-4d49-b7b5-5c25ce423c56> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nadiem"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#2bb3701c-925c-4d49-b7b5-5c25ce423c56> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nadiem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U11> .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .
<https://starwars.com#planet_Nadiem> <http://telicent.io/ontology/primaryName> "Nadiem" .

