Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vuchelle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#planet_Vuchelle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#428d39d0-78dc-4f37-a7ed-599b0eba2adb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vuchelle"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vuchelle> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#428d39d0-78dc-4f37-a7ed-599b0eba2adb> .
<https://starwars.com#planet_Vuchelle> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vuchelle> <http://www.w3.org/2000/01/rdf-schema#comment> "Vuchelle was an orange-colored astronomical object located in the Outer Rim Territories' Atrivis sector. Situated along the Braxant Run hyperlane, Vuchelle in 22 BBY became the site of attempted negotiations between a Jedi-led Galactic Republic task force and the pirates of Iridium, who had been committing raids against Republic convoys. The pirates attacked the Jedi task force but were eventually defeated, with one of their starfighters believed to have reentered Vuchelle's atmosphere and burned up as a result. " .
<https://starwars.com#planet_Vuchelle> <http://telicent.io/ontology/primaryName> "Vuchelle" .
<https://starwars.com#428d39d0-78dc-4f37-a7ed-599b0eba2adb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

