Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kobaria> <http://telicent.io/ontology/primaryName> "Kobaria" .
<https://starwars.com#planet_Kobaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#ef26a705-fd32-473d-bb1b-095dfc1fa865> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kobaria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef26a705-fd32-473d-bb1b-095dfc1fa865> .
<https://starwars.com#planet_Kobaria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_Kobaria> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#ef26a705-fd32-473d-bb1b-095dfc1fa865> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kobaria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kobaria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

