Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#89042915-eea0-48da-b813-1658eefa9c5a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Socorro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Socorro> <http://telicent.io/ontology/primaryName> "Socorro" .
<https://starwars.com#sector_Kiblini> <http://telicent.io/ontology/primaryName> "Kiblini" .
<https://starwars.com#planet_Socorro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89042915-eea0-48da-b813-1658eefa9c5a> .
<https://starwars.com#planet_Socorro> <http://www.w3.org/2000/01/rdf-schema#comment> "Socorro was a an astronomical object located in the Gold system within the galaxy's Outer Rim Territories. It was the homeworld of Lando Calrissian, former Baron Administrator of Cloud City. It was also the location of asteroid belts with large quantities of doonium ore. The former pirate queen Maz Kanata marked it as a shadowport on a map she included in the book that became known as the Smuggler's Guide. " .
<https://starwars.com#planet_Socorro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kiblini> .
<https://starwars.com#planet_Socorro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kiblini> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Socorro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q17> .
<https://starwars.com#sector_Kiblini> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#89042915-eea0-48da-b813-1658eefa9c5a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

