Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Urce> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L6> .
<https://starwars.com#planet_Urce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Urce> <http://telicent.io/ontology/primaryName> "Urce" .
<https://starwars.com#sector_Urce> <http://telicent.io/ontology/primaryName> "Urce" .
<https://starwars.com#planet_Urce> <http://www.w3.org/2000/01/rdf-schema#comment> "Urce was an astronomical object located in the regions known as the Mid Rim and the New Territories. It was also situated in grid square L-6 of the Standard Galactic Grid. Urce shared its name with the Urce sector. " .
<https://starwars.com#sector_Urce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d7ccc2d7-fd13-40b2-9261-f508b5fa961c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Urce"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Urce> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Urce> .
<https://starwars.com#sector_Urce> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Urce> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7ccc2d7-fd13-40b2-9261-f508b5fa961c> .
<https://starwars.com#d7ccc2d7-fd13-40b2-9261-f508b5fa961c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

