Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bortele> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ultaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#26971f33-bb8f-4de6-91ae-e4d02c864256> .
<https://starwars.com#planet_Ultaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#26971f33-bb8f-4de6-91ae-e4d02c864256> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ultaar> <http://telicent.io/ontology/primaryName> "Ultaar" .
<https://starwars.com#planet_Ultaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ultaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bortele> .
<https://starwars.com#sector_Bortele> <http://telicent.io/ontology/primaryName> "Bortele" .
<https://starwars.com#26971f33-bb8f-4de6-91ae-e4d02c864256> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ultaar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ultaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Ultaar was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_Bortele> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

