Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ValluskCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#3d832c8a-5099-4d42-bed9-365c89dc2d82> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vallusk Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3d832c8a-5099-4d42-bed9-365c89dc2d82> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ValluskCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d832c8a-5099-4d42-bed9-365c89dc2d82> .
<https://starwars.com#planet_ValluskCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#planet_ValluskCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_ValluskCluster> <http://telicent.io/ontology/primaryName> "Vallusk Cluster" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_ValluskCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Vallusk Cluster was a cluster of protostars near the Roil in the Gordian Reach sector of the Outer Rim Territories. It lacked habitable planets. " .

