Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LoUran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b221654a-3a60-4f17-aa12-91c3c8505e8f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_LoUran> <http://telicent.io/ontology/primaryName> "Lo'Uran" .
<https://starwars.com#b221654a-3a60-4f17-aa12-91c3c8505e8f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lo'Uran"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LoUran> <http://www.w3.org/2000/01/rdf-schema#comment> "Lo'Uran was a planet located in the Aparo sector of the Outer Rim Territories. Its governor was Blithane. " .
<https://starwars.com#planet_LoUran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_LoUran> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b221654a-3a60-4f17-aa12-91c3c8505e8f> .
<https://starwars.com#planet_LoUran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

