Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Demos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#e62a3e7c-f4b8-4b5a-87c1-938b0569e095> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#e62a3e7c-f4b8-4b5a-87c1-938b0569e095> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Demos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Demos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e62a3e7c-f4b8-4b5a-87c1-938b0569e095> .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#planet_Demos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Demos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Demos> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Demos> <http://telicent.io/ontology/primaryName> "Demos" .

