Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Venzeiia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Terrijo> <http://telicent.io/ontology/primaryName> "Terrijo" .
<https://starwars.com#sector_Venzeiia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#c8ab1e70-1687-4d5a-b6ca-8fb0eb542c0d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Venzeiia> <http://telicent.io/ontology/primaryName> "Venzeiia" .
<https://starwars.com#planet_Terrijo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c8ab1e70-1687-4d5a-b6ca-8fb0eb542c0d> .
<https://starwars.com#planet_Terrijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#planet_Terrijo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c8ab1e70-1687-4d5a-b6ca-8fb0eb542c0d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Terrijo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Terrijo> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Terrijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Venzeiia> .

