Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sochi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5acec3b0-1f01-4387-b1ab-82296842a8da> .
<https://starwars.com#planet_Sochi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Sochi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sochi> <http://telicent.io/ontology/primaryName> "Sochi" .
<https://starwars.com#planet_Sochi> <http://www.w3.org/2000/01/rdf-schema#comment> "Sochi was an Imperial vacation world, located in the Sochi system. It was the location of the stormtrooper retirement home, Troopers' Rest. " .
<https://starwars.com#5acec3b0-1f01-4387-b1ab-82296842a8da> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5acec3b0-1f01-4387-b1ab-82296842a8da> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sochi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sochi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .

