Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shadda-BiBoran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Toblain> .
<https://starwars.com#sector_Toblain> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shadda-BiBoran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Toblain> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Toblain> <http://telicent.io/ontology/primaryName> "Toblain" .
<https://starwars.com#planet_Shadda-BiBoran> <http://telicent.io/ontology/primaryName> "Shadda-Bi Boran" .
<https://starwars.com#planet_Shadda-BiBoran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O18> .
<https://starwars.com#planet_Shadda-BiBoran> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a5e5ae05-40ea-498c-8828-4a97f8604712> .
<https://starwars.com#a5e5ae05-40ea-498c-8828-4a97f8604712> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shadda-BiBoran> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#a5e5ae05-40ea-498c-8828-4a97f8604712> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shadda-Bi Boran"^^<http://www.w3.org/2001/XMLSchema#string> .

