Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Medth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ado> .
<https://starwars.com#planet_Medth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#40b68d43-aa5b-41f2-bac6-a76736405da9> .
<https://starwars.com#planet_Medth> <http://telicent.io/ontology/primaryName> "Medth" .
<https://starwars.com#planet_Medth> <http://www.w3.org/2000/01/rdf-schema#comment> "Medth was a planet. The privateer Urias Xhaxin once raided the planet's region in his ship, the Free Lance. " .
<https://starwars.com#40b68d43-aa5b-41f2-bac6-a76736405da9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Ado> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Medth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_Medth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Ado> <http://telicent.io/ontology/primaryName> "Ado" .
<https://starwars.com#sector_Ado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#40b68d43-aa5b-41f2-bac6-a76736405da9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Medth"^^<http://www.w3.org/2001/XMLSchema#string> .

