Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tammuz> .
<https://starwars.com#grid_U14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#1630f98f-a102-4cf2-ac95-8fe95fcb0a53> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1630f98f-a102-4cf2-ac95-8fe95fcb0a53> .
<https://starwars.com#planet_Shola> <http://telicent.io/ontology/primaryName> "Shola" .
<https://starwars.com#9bdc9b4c-7d27-4b1a-b09b-91c1b2eeb36b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shola"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tammuz> <http://telicent.io/ontology/primaryName> "Tammuz" .
<https://starwars.com#planet_Shola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U14> .
<https://starwars.com#1630f98f-a102-4cf2-ac95-8fe95fcb0a53> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_U14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_U14> <http://telicent.io/ontology/primaryName> "U14" .
<https://starwars.com#sector_Tammuz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shola> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9bdc9b4c-7d27-4b1a-b09b-91c1b2eeb36b> .
<https://starwars.com#sector_Tammuz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#9bdc9b4c-7d27-4b1a-b09b-91c1b2eeb36b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shola> <http://www.w3.org/2000/01/rdf-schema#comment> "Shola was an astronomical object in the galaxy's Outer Rim Territories, positioned at the coordinates U-14 on the Standard Galactic Grid. " .

