Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#941ce7cd-6dad-4851-8d6d-d69df0a5bc5f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Roon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Roon> <http://www.w3.org/2000/01/rdf-schema#comment> "Roon was an astronomical object located in the galaxy's Outer Rim Territories, in a region called the Cloak of the Sith at the top of Spice Triangle. It was located on the Triellus Trade Route hyperspace route and the smugglers' route Mumble's Turnaround and was ruled by the Imperial governor. The former pirate Queen Maz Kanata marked it as a point of interest on a map she included in the book that would become known as the Smuggler's Guide. It shared its name with the Roon Tours travel agency, and the Roon Drainsweeper sport. " .
<https://starwars.com#planet_Roon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .
<https://starwars.com#planet_Roon> <http://telicent.io/ontology/primaryName> "Roon" .
<https://starwars.com#941ce7cd-6dad-4851-8d6d-d69df0a5bc5f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Roon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#planet_Roon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#941ce7cd-6dad-4851-8d6d-d69df0a5bc5f> .
<https://starwars.com#planet_Roon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

