Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e7db68f2-4d4d-43d4-a8fa-60a865c5d064> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iotra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iotra> <http://telicent.io/ontology/primaryName> "Iotra" .
<https://starwars.com#e7db68f2-4d4d-43d4-a8fa-60a865c5d064> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Iotra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#planet_Iotra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Iotra> .
<https://starwars.com#sector_Iotra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Iotra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iotra> <http://www.w3.org/2000/01/rdf-schema#comment> "Iotra was the fifth planet in the Iotran system and the temperate, industrial homeworld to the militant Iotran species. The planet was ruled by the Joint Council, eight top-ranking leaders of the Iotran Police Force (IPF). " .
<https://starwars.com#planet_Iotra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e7db68f2-4d4d-43d4-a8fa-60a865c5d064> .
<https://starwars.com#sector_Iotra> <http://telicent.io/ontology/primaryName> "Iotra" .
<https://starwars.com#sector_Iotra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

