Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bilbringi> <http://www.w3.org/2000/01/rdf-schema#comment> "Bilbringi was a world located in the galaxy's Inner Rim. It was home to the Bilbringi shipyards, a facility which dismantled the Separatist dreadnought Lucid Voice within a year after the end of the Clone Wars. The smuggler Han Solo was fond of Bilbringi food, and shared cheesy meat pies with pepper from Bilbringi with his wife, Leia Organa, at their home on Hosnian Prime twenty-four years after the Battle of Endor. " .
<https://starwars.com#planet_Bilbringi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#3207d6a5-14da-41c0-9b82-f059e1df3c1f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bilbringi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bilbringi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3207d6a5-14da-41c0-9b82-f059e1df3c1f> .
<https://starwars.com#planet_Bilbringi> <http://telicent.io/ontology/primaryName> "Bilbringi" .
<https://starwars.com#planet_Bilbringi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#3207d6a5-14da-41c0-9b82-f059e1df3c1f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bilbringi"^^<http://www.w3.org/2001/XMLSchema#string> .

