Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Talasea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#36fb8691-37dd-4dd5-a3c3-1a1cd0b5806b> .
<https://starwars.com#planet_Talasea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Talasea> <http://www.w3.org/2000/01/rdf-schema#comment> "The fourth planet in the Morobe system, Talasea orbited the yellow primary star in a red/yellow binary group. A cool, moist, forested, and fog-shrouded world, Talasea had a higher gravity than standard and was lashed by severe thunderstorms during the rainy season. Island continents made up its land masses. Animal life included native insects and reptiles, along with feral mammals descended from those brought for an early farming colony, including banthas and rycrits. Indigenous plant life included green ivy, tendril-moss, and the kaha tree. It was the site of several minor conflicts from multiple entities in the galaxy. " .
<https://starwars.com#planet_Talasea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Talasea> <http://telicent.io/ontology/primaryName> "Talasea" .
<https://starwars.com#36fb8691-37dd-4dd5-a3c3-1a1cd0b5806b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Talasea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#36fb8691-37dd-4dd5-a3c3-1a1cd0b5806b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Talasea"^^<http://www.w3.org/2001/XMLSchema#string> .

