Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mygeeto> <http://telicent.io/ontology/primaryName> "Mygeeto" .
<https://starwars.com#planet_Mygeeto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mygeeto> <http://www.w3.org/2000/01/rdf-schema#comment> "Cold, urban planet that served as a battle site in the final days of the Clone Wars, as well as the death place of Jedi Master Ki Adi Mundi by Order 66. Colony world of the Muun species." .
<https://starwars.com#ac29d75f-bfb1-4e80-9afa-8268816aa05f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mygeeto"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ac29d75f-bfb1-4e80-9afa-8268816aa05f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#planet_Mygeeto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Mygeeto> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac29d75f-bfb1-4e80-9afa-8268816aa05f> .
<https://starwars.com#planet_Mygeeto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

