Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c99c69b2-fc8a-4a3c-95d3-e93a86af2050> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Damoria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c99c69b2-fc8a-4a3c-95d3-e93a86af2050> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Damoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Damoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Damoria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c99c69b2-fc8a-4a3c-95d3-e93a86af2050> .
<https://starwars.com#planet_Damoria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Damoria> <http://telicent.io/ontology/primaryName> "Damoria" .
<https://starwars.com#planet_Damoria> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

