Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Churnis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kalaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Churnis> <http://telicent.io/ontology/primaryName> "Churnis" .
<https://starwars.com#968ed1a6-74ee-4c92-aefe-28c7321addae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Churnis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#968ed1a6-74ee-4c92-aefe-28c7321addae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kalaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#968ed1a6-74ee-4c92-aefe-28c7321addae> .
<https://starwars.com#planet_Kalaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churnis> .
<https://starwars.com#planet_Kalaan> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalaan was a location in the galaxy. Prior to the Galactic Civil War, Visler Korda, a captain in the Imperial Navy, threatened to send Dil Pexton to an Imperial prison camp on Kalaan if he didn't betray Lina Graf. " .
<https://starwars.com#planet_Kalaan> <http://telicent.io/ontology/primaryName> "Kalaan" .

