Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#5afb8ce4-4701-4f63-bcea-0de3c33eb3ac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tangrene"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O4> <http://telicent.io/ontology/primaryName> "O4" .
<https://starwars.com#2704ba4c-66eb-41f7-9a66-adf67a36b61e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Morshdine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5afb8ce4-4701-4f63-bcea-0de3c33eb3ac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#2704ba4c-66eb-41f7-9a66-adf67a36b61e> .
<https://starwars.com#planet_Tangrene> <http://telicent.io/ontology/primaryName> "Tangrene" .
<https://starwars.com#2704ba4c-66eb-41f7-9a66-adf67a36b61e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_O4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Tangrene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Morshdine> .
<https://starwars.com#planet_Tangrene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O4> .
<https://starwars.com#planet_Tangrene> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5afb8ce4-4701-4f63-bcea-0de3c33eb3ac> .
<https://starwars.com#planet_Tangrene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Morshdine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Morshdine> <http://telicent.io/ontology/primaryName> "Morshdine" .
<https://starwars.com#planet_Tangrene> <http://www.w3.org/2000/01/rdf-schema#comment> "Tangrene was an astronomical object located in the galaxy's Outer Rim Territories, connected via hyperspace route to Edusa. " .

