Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f4613b1c-32d6-4901-a03c-90dc7d74fd52> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Nuiri> <http://telicent.io/ontology/primaryName> "Nuiri" .
<https://starwars.com#planet_Vjun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f4613b1c-32d6-4901-a03c-90dc7d74fd52> .
<https://starwars.com#planet_Vjun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nuiri> .
<https://starwars.com#planet_Vjun> <http://telicent.io/ontology/primaryName> "Vjun" .
<https://starwars.com#planet_Vjun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vjun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#sector_Nuiri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vjun> <http://www.w3.org/2000/01/rdf-schema#comment> "Vjun was a planet located in the galaxy's Outer Rim Territories in grid square Q-6 on the Standard Galactic Grid, situated between Lucazec and Phindar along the Salin Corridor hyperspace route. In the wake of the Emergences of the Great Hyperspace Disaster during the High Republic Era, Vjun was among many locations in the Outer Rim whose hospitals were overrun with victims. It was home to the famous tailors who wove Count Dooku's elegant cloak. " .
<https://starwars.com#f4613b1c-32d6-4901-a03c-90dc7d74fd52> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vjun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Nuiri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

