Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Haseria> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Haseria> <http://telicent.io/ontology/primaryName> "Haseria" .
<https://starwars.com#sector_Haserian> <http://telicent.io/ontology/primaryName> "Haserian" .
<https://starwars.com#e6fa03d7-4f7e-45dc-92ff-3d755fb6fe1a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Haseria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Haserian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Haseria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Haseria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#planet_Haseria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6fa03d7-4f7e-45dc-92ff-3d755fb6fe1a> .
<https://starwars.com#sector_Haserian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Haseria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Haserian> .
<https://starwars.com#e6fa03d7-4f7e-45dc-92ff-3d755fb6fe1a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

