Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vuzsa> <http://www.w3.org/2000/01/rdf-schema#comment> "Vuzsa was an astronomical object that the CR90 corvette Tantive IV jumped to from the planet Iskalon during its journey to the planet Tatooine after escaping the Battle of Scarif in 0 BBY. During the journey, the corvette's captain, rebel Raymus Antilles, took no direct route and doubled back on himself to try and evade Imperial pursuit; however, the Sith Lord Darth Vader was able to track the Tantive IV as it arrived at Vuzsa and then jumped from there to Tatooine. " .
<https://starwars.com#ce815271-3273-41a7-8d51-78cdae4c52f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vuzsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Vuzsa> <http://telicent.io/ontology/primaryName> "Vuzsa" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vuzsa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce815271-3273-41a7-8d51-78cdae4c52f6> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vuzsa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vuzsa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#ce815271-3273-41a7-8d51-78cdae4c52f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vuzsa"^^<http://www.w3.org/2001/XMLSchema#string> .

