Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8195c699-ea6f-41ed-b36b-c2bf39248121> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gand> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8195c699-ea6f-41ed-b36b-c2bf39248121> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gand"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Shadola> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gand> <http://telicent.io/ontology/primaryName> "Gand" .
<https://starwars.com#sector_Shadola> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gand> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8195c699-ea6f-41ed-b36b-c2bf39248121> .
<https://starwars.com#planet_Gand> <http://www.w3.org/2000/01/rdf-schema#comment> "Gand were an insectoid sentient species native to the planet Gand. One subspecies breathed ammonia, forcing them to wear respirators to survive in oxygen-rich atmospheres. A notable member of this species was Zuckuss, a bounty hunter who was one of the first traditional findsmen to leave his homeworld. " .
<https://starwars.com#planet_Gand> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Shadola> <http://telicent.io/ontology/primaryName> "Shadola" .
<https://starwars.com#planet_Gand> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Shadola> .

