Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f0b94a17-94ee-41e4-ad5f-4e393a2d85f0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Phelope> <http://telicent.io/ontology/primaryName> "Phelope" .
<https://starwars.com#planet_Phelope> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Phelope> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f0b94a17-94ee-41e4-ad5f-4e393a2d85f0> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Phelope> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Phelope> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Phelope> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#f0b94a17-94ee-41e4-ad5f-4e393a2d85f0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phelope"^^<http://www.w3.org/2001/XMLSchema#string> .

