Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GalacticCenter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#2aa94b5e-0363-4648-87d4-11b72582114a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Galactic Center"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_GalacticCenter> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2aa94b5e-0363-4648-87d4-11b72582114a> .
<https://starwars.com#planet_GalacticCenter> <http://telicent.io/ontology/primaryName> "Galactic Center" .
<https://starwars.com#planet_GalacticCenter> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2aa94b5e-0363-4648-87d4-11b72582114a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_GalacticCenter> <http://www.w3.org/2000/01/rdf-schema#comment> "The Galactic Center was a supermassive black hole that existed at the center of the galaxy. Its mass was estimated to be four million stellar masses. While no living sentient had ever witnessed it firsthand, probe droids had been sent to observe and confirm its existence. " .

