Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#10fd290d-9b4d-453f-8980-67556f49e265> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Parada"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Hadar> <http://telicent.io/ontology/primaryName> "Hadar" .
<https://starwars.com#planet_Parada> <http://telicent.io/ontology/primaryName> "Parada" .
<https://starwars.com#planet_Parada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hadar> .
<https://starwars.com#sector_Hadar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Parada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Parada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Parada> <http://www.w3.org/2000/01/rdf-schema#comment> "Parada was an agriworld located in the Parada system of the Hadar sector, a part of the Western Reaches portion of the Mid Rim. The Senex Trace hyperlane linked it to the Rindao system as well as the Bortras system of the Outer Rim Territories' Brema sector. " .
<https://starwars.com#10fd290d-9b4d-453f-8980-67556f49e265> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Parada> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#10fd290d-9b4d-453f-8980-67556f49e265> .
<https://starwars.com#sector_Hadar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

