Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#218b3850-6db9-44e0-a2e1-0e7561a9bddd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sanyassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sanyassa> <http://www.w3.org/2000/01/rdf-schema#comment> "Sanyassa was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was situated on the Bakura Trace hyperspace route, which linked it to the celestial body Ast Kikorie as well as the Endor system. The Moddell sector's hyperspace anomalies sometimes transported starships to the Endor system from as far away as Sanyassa. Sanyassa was eventually depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_Sanyassa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sanyassa> <http://telicent.io/ontology/primaryName> "Sanyassa" .
<https://starwars.com#218b3850-6db9-44e0-a2e1-0e7561a9bddd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sanyassa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sanyassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Sanyassa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#218b3850-6db9-44e0-a2e1-0e7561a9bddd> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

