Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vandelhelm> <http://telicent.io/ontology/primaryName> "Vandelhelm" .
<https://starwars.com#26190aab-0dd5-4132-bb93-04947f0a822b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vandelhelm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M15> .
<https://starwars.com#planet_Vandelhelm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_EpsiCollective> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#26190aab-0dd5-4132-bb93-04947f0a822b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vandelhelm"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vandelhelm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#26190aab-0dd5-4132-bb93-04947f0a822b> .
<https://starwars.com#planet_Vandelhelm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_EpsiCollective> .
<https://starwars.com#sector_EpsiCollective> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vandelhelm> <http://www.w3.org/2000/01/rdf-schema#comment> "Vandelhelm was an astronomical object located in the galaxy's Expansion Region, along the Rimma Trade Route. " .
<https://starwars.com#sector_EpsiCollective> <http://telicent.io/ontology/primaryName> "Epsi Collective" .

