Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#76bcb4b3-ac54-4c30-8bee-a7d43b7c4a66> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#76bcb4b3-ac54-4c30-8bee-a7d43b7c4a66> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bandomeer> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#77daf44c-7cda-406d-9890-b00f5c911cca> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bandomeer"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Bandomeer> <http://www.w3.org/2000/01/rdf-schema#comment> "Bandomeer was an agricultural planet located in the galaxy's Outer Rim Territories, at the junction of the Hydian Way and the Braxant Run. The planet remained focused on agriculture until it was discovered to be rich in mineral resources, which were in turn exploited over the course of galactic history. Over the course of Bandomeer's history, the world's miners sometimes had disputes with the companies that ran the mining operations. After the Galactic Empire came to power, it eventually set its sights on Bandomeer to exploit its resources. When the miners tried to resist, the Sith Lord Darth Vader arrived and duly punished them. " .
<https://starwars.com#sector_Meerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#77daf44c-7cda-406d-9890-b00f5c911cca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bandomeer> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#77daf44c-7cda-406d-9890-b00f5c911cca> .
<https://starwars.com#planet_Bandomeer> <http://telicent.io/ontology/primaryName> "Bandomeer" .
<https://starwars.com#planet_Bandomeer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#sector_Meerian> <http://telicent.io/ontology/primaryName> "Meerian" .
<https://starwars.com#sector_Meerian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bandomeer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meerian> .
<https://starwars.com#grid_O6> <http://telicent.io/ontology/primaryName> "O6" .
<https://starwars.com#grid_O6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#76bcb4b3-ac54-4c30-8bee-a7d43b7c4a66> .

