Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TalNami> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_TalNami> <http://www.w3.org/2000/01/rdf-schema#comment> "Tal Nami was a planet located in Hutt Space and was the homeworld of the Tal Nami species. " .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TalNami> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TalNami> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f0b718c1-eca8-4baa-b75e-1478f1b05bc8> .
<https://starwars.com#planet_TalNami> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R9> .
<https://starwars.com#planet_TalNami> <http://telicent.io/ontology/primaryName> "Tal Nami" .
<https://starwars.com#f0b718c1-eca8-4baa-b75e-1478f1b05bc8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tal Nami"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#f0b718c1-eca8-4baa-b75e-1478f1b05bc8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

