Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Faldos> <http://www.w3.org/2000/01/rdf-schema#comment> "Faldos was a dirty backwater Outer Rim Territories world used by smugglers to sell stolen weapons, armor, and technology. It sat on the very edge of the galaxy, making it far more removed than most of the Outer Rim Territories. " .
<https://starwars.com#02cf0299-4eec-4602-a144-e2ff902f1cae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Faldos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#385d4d8c-3c08-4681-b9d0-4865a291727b> .
<https://starwars.com#grid_K20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#02cf0299-4eec-4602-a144-e2ff902f1cae> .
<https://starwars.com#planet_Faldos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K20> .
<https://starwars.com#sector_Saijo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Faldos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Saijo> .
<https://starwars.com#sector_Saijo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_K20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#385d4d8c-3c08-4681-b9d0-4865a291727b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Faldos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Saijo> <http://telicent.io/ontology/primaryName> "Saijo" .
<https://starwars.com#planet_Faldos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#385d4d8c-3c08-4681-b9d0-4865a291727b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Faldos> <http://telicent.io/ontology/primaryName> "Faldos" .
<https://starwars.com#02cf0299-4eec-4602-a144-e2ff902f1cae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_K20> <http://telicent.io/ontology/primaryName> "K20" .

