Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brema> <http://telicent.io/ontology/primaryName> "Brema" .
<https://starwars.com#planet_Sullust> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sullust> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brema> .
<https://starwars.com#planet_Sullust> <http://www.w3.org/2000/01/rdf-schema#comment> "A volcanic planet whose atmosphere was highly toxic forcing the native Sullustans to build technologically advanced subterranean cities. It was the base of Imperial factories and the SoroSuub corporation employed roughly half the population." .
<https://starwars.com#planet_Sullust> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#sector_Brema> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7272006c-82ec-4f41-952d-686e84cba938> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sullust"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7272006c-82ec-4f41-952d-686e84cba938> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sullust> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7272006c-82ec-4f41-952d-686e84cba938> .
<https://starwars.com#planet_Sullust> <http://telicent.io/ontology/primaryName> "Sullust" .
<https://starwars.com#sector_Brema> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

