Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8b86af4d-6dcc-41ad-8499-f9cd5de3c387> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Frego> <http://telicent.io/ontology/primaryName> "Frego" .
<https://starwars.com#planet_Frego> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Frego> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8b86af4d-6dcc-41ad-8499-f9cd5de3c387> .
<https://starwars.com#planet_Frego> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Frego> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Frego> <http://www.w3.org/2000/01/rdf-schema#comment> "Frego was a wealthy planet controlled by a crime ring led by the Cobral family since 61 BBY. However, after Lena Cobral testified in front of the Galactic Senate in 41 BBY, exposing Cobral's patronage from Frego's Senator Crote, Frego started on the road to a new beginning. Nevertheless, the Cobral ring survived on Naboo. " .
<https://starwars.com#8b86af4d-6dcc-41ad-8499-f9cd5de3c387> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Frego"^^<http://www.w3.org/2001/XMLSchema#string> .

