Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Eridicon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Eridicon> <http://telicent.io/ontology/primaryName> "Eridicon" .
<https://starwars.com#planet_Eridicon> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Eridicon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Eridicon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#672e6ffa-a01a-45d8-81be-d4c7d9bf3e1a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eridicon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Eridicon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#672e6ffa-a01a-45d8-81be-d4c7d9bf3e1a> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#672e6ffa-a01a-45d8-81be-d4c7d9bf3e1a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

