Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nanthri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q12> .
<https://starwars.com#84231ebf-89b5-446d-a207-4856f3658895> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nanth'ri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kurost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nanthri> <http://telicent.io/ontology/primaryName> "Nanth'ri" .
<https://starwars.com#planet_Nanthri> <http://www.w3.org/2000/01/rdf-schema#comment> "Nanth'ri was a planet located in the Nanth'ri system within the galaxy's Mid Rim. " .
<https://starwars.com#sector_Kurost> <http://telicent.io/ontology/primaryName> "Kurost" .
<https://starwars.com#84231ebf-89b5-446d-a207-4856f3658895> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nanthri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nanthri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kurost> .
<https://starwars.com#sector_Kurost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nanthri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#84231ebf-89b5-446d-a207-4856f3658895> .

