Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Elrood> <http://www.w3.org/2000/01/rdf-schema#comment> "Elrood was a planet in the galaxy's Outer Rim Territories. The location Dinbar and its starport were located on the planet. " .
<https://starwars.com#planet_Elrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#planet_Elrood> <http://telicent.io/ontology/primaryName> "Elrood" .
<https://starwars.com#b1be352e-4d9e-4a4b-8e4e-f936181ac72f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Elrood> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b1be352e-4d9e-4a4b-8e4e-f936181ac72f> .
<https://starwars.com#b1be352e-4d9e-4a4b-8e4e-f936181ac72f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Elrood"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Elrood> <http://telicent.io/ontology/primaryName> "Elrood" .
<https://starwars.com#sector_Elrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Elrood> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Elrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Elrood> .
<https://starwars.com#sector_Elrood> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

