Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Issor> <http://www.w3.org/2000/01/rdf-schema#comment> "Issor was the most powerful planet in the Trulalis system, and the homeworld of the Issori and Odenji. " .
<https://starwars.com#planet_Issor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#e96e4437-d36d-4e30-9a92-d15f2fe21738> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Issor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Issor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e96e4437-d36d-4e30-9a92-d15f2fe21738> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#e96e4437-d36d-4e30-9a92-d15f2fe21738> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Issor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Issor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Issor> <http://telicent.io/ontology/primaryName> "Issor" .

