Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Illarreen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Herios> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#73c3a3b1-bc60-48c2-a410-835efc6185a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Herios> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Illarreen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73c3a3b1-bc60-48c2-a410-835efc6185a8> .
<https://starwars.com#planet_Illarreen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Herios> .
<https://starwars.com#planet_Illarreen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T16> .
<https://starwars.com#sector_Herios> <http://telicent.io/ontology/primaryName> "Herios" .
<https://starwars.com#planet_Illarreen> <http://telicent.io/ontology/primaryName> "Illarreen" .
<https://starwars.com#73c3a3b1-bc60-48c2-a410-835efc6185a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Illarreen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Illarreen> <http://www.w3.org/2000/01/rdf-schema#comment> "Illarreen was a planet discovered in 100 BBY. It joined the galactic community in 90 BBY. " .

