Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Neelanon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Neelanon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Neelanon> <http://telicent.io/ontology/primaryName> "Neelanon" .
<https://starwars.com#bbad7443-8d44-49b6-a98d-d02720a052eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Neelanon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Neelanon> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet Neelanon was the homeworld of the human senator Terr Taneel, who represented the world Senex in the Galactic Senate of the Republic during the Clone Wars. " .
<https://starwars.com#planet_Neelanon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#bbad7443-8d44-49b6-a98d-d02720a052eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Neelanon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bbad7443-8d44-49b6-a98d-d02720a052eb> .

