Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Malastare> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#810f2426-52a5-4f7a-a515-96c84cdf66e5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Malastare> <http://telicent.io/ontology/primaryName> "Malastare" .
<https://starwars.com#planet_Malastare> <http://www.w3.org/2000/01/rdf-schema#comment> "Forested planet where podracing is popular. Birthplace of Sebulba and homeworld of the Dug." .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#810f2426-52a5-4f7a-a515-96c84cdf66e5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Malastare"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Malastare> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#810f2426-52a5-4f7a-a515-96c84cdf66e5> .
<https://starwars.com#planet_Malastare> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .
<https://starwars.com#planet_Malastare> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

