Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_P12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#edcc598d-4c08-4ae9-afb2-3d5d44a17c9b> .
<https://starwars.com#edcc598d-4c08-4ae9-afb2-3d5d44a17c9b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dc253831-0be6-40bb-80ed-c33317cf4941> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Attahox"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dc253831-0be6-40bb-80ed-c33317cf4941> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Attahox> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hocatar> .
<https://starwars.com#sector_Hocatar> <http://telicent.io/ontology/primaryName> "Hocatar" .
<https://starwars.com#planet_Attahox> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Attahox> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dc253831-0be6-40bb-80ed-c33317cf4941> .
<https://starwars.com#grid_P12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#edcc598d-4c08-4ae9-afb2-3d5d44a17c9b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Attahox> <http://www.w3.org/2000/01/rdf-schema#comment> "Attahox was an astronomical object in the galaxy's Expansion Region. It was connected to Mimban and Nanth'ri by a hyperspace route. " .
<https://starwars.com#planet_Attahox> <http://telicent.io/ontology/primaryName> "Attahox" .
<https://starwars.com#sector_Hocatar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_P12> <http://telicent.io/ontology/primaryName> "P12" .
<https://starwars.com#sector_Hocatar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Attahox> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#grid_P12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

