Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Falleen> <http://www.w3.org/2000/01/rdf-schema#comment> "Falleen were a repto-mammalian sentient species native to the planet of the same name. They were capable of projecting powerful pheromones. During the Clone Wars, the Black Sun criminal syndicate was run by a cabal of Falleen nobles, Ziton Moj, from their fortress on Mustafar. " .
<https://starwars.com#planet_Falleen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Falleen> <http://telicent.io/ontology/primaryName> "Falleen" .
<https://starwars.com#sector_Doldur> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9595ff81-5336-4c6e-bc4c-c5a09d826d35> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Falleen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9595ff81-5336-4c6e-bc4c-c5a09d826d35> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Falleen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#planet_Falleen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Doldur> .
<https://starwars.com#sector_Doldur> <http://telicent.io/ontology/primaryName> "Doldur" .
<https://starwars.com#planet_Falleen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9595ff81-5336-4c6e-bc4c-c5a09d826d35> .
<https://starwars.com#sector_Doldur> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

