Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Boranda> <http://telicent.io/ontology/primaryName> "Boranda" .
<https://starwars.com#1798ae27-e65d-4e8e-92cb-7f43ee1afb25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Boranda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Manda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_R14> <http://telicent.io/ontology/primaryName> "R14" .
<https://starwars.com#16c6a1a6-7372-4703-8575-acbdfc86dc3a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#1798ae27-e65d-4e8e-92cb-7f43ee1afb25> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Manda> <http://telicent.io/ontology/primaryName> "Manda" .
<https://starwars.com#grid_R14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1798ae27-e65d-4e8e-92cb-7f43ee1afb25> .
<https://starwars.com#grid_R14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Boranda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Manda> .
<https://starwars.com#planet_Boranda> <http://www.w3.org/2000/01/rdf-schema#comment> "Boranda was a location within the Galactic Empire. It was apparently a desirable vacation spot, as when Merei Spanjaf made it up as a possible prize for a raffle on the spot, a woman purchased five tickets for the raffle. " .
<https://starwars.com#grid_R14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Boranda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#16c6a1a6-7372-4703-8575-acbdfc86dc3a> .
<https://starwars.com#planet_Boranda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#16c6a1a6-7372-4703-8575-acbdfc86dc3a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Boranda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Manda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

