Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ooo-temiuk> <http://telicent.io/ontology/primaryName> "Ooo-temiuk" .
<https://starwars.com#8aa8e7cd-579d-4413-bee7-2b0b986b1f9b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ooo-temiuk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ooo-temiuk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Ooo-temiuk> <http://www.w3.org/2000/01/rdf-schema#comment> "Ooo-temiuk was a forested world located in the Ooo-temiuk system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. It was situated on the Triellus Trade Route hyperlane, which linked it to the C-Foroon and Tatoo systems. " .
<https://starwars.com#planet_Ooo-temiuk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ooo-temiuk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#8aa8e7cd-579d-4413-bee7-2b0b986b1f9b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ooo-temiuk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8aa8e7cd-579d-4413-bee7-2b0b986b1f9b> .

