Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ronyards> <http://telicent.io/ontology/primaryName> "Ronyards" .
<https://starwars.com#planet_Ronyards> <http://www.w3.org/2000/01/rdf-schema#comment> "Ronyards, also known as the Body of the Living God by its droid inhabitants, was a junkyard planet located in the Ronyards system of the galaxy's Inner Rim. Ronyards was a common dumping ground for obsolete, inoperative and unwanted droids, and was covered in metal piles that could reach up to five miles deep. Ronyards was home to a large population of active droids who worshipped Ronyards itself—and their 'living god' was known to defend its inhabitants when they were threatened by outsiders. " .
<https://starwars.com#c335379a-9dce-4133-be2b-bb076641b066> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ronyards"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ronyards> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ronyards> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c335379a-9dce-4133-be2b-bb076641b066> .
<https://starwars.com#c335379a-9dce-4133-be2b-bb076641b066> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ronyards> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_Ronyards> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

