Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6516610a-1869-42c9-9327-df5e4b5cb2f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trantor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trantor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trantor> <http://www.w3.org/2000/01/rdf-schema#comment> "Trantor was an ecumenopolis located within the Trantor system of the Core Worlds and the homeworld of Trantor pigeons. " .
<https://starwars.com#planet_Trantor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Trantor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6516610a-1869-42c9-9327-df5e4b5cb2f1> .
<https://starwars.com#6516610a-1869-42c9-9327-df5e4b5cb2f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trantor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Trantor> <http://telicent.io/ontology/primaryName> "Trantor" .

