Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gwenee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Weneen> <http://telicent.io/ontology/primaryName> "Weneen" .
<https://starwars.com#planet_Gwenee> <http://telicent.io/ontology/primaryName> "G'wenee" .
<https://starwars.com#c4cb801a-3173-471e-917c-a0b528b3bfb9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gwenee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c4cb801a-3173-471e-917c-a0b528b3bfb9> .
<https://starwars.com#planet_Gwenee> <http://www.w3.org/2000/01/rdf-schema#comment> "G'wenee was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Gwenee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N6> .
<https://starwars.com#sector_Weneen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#c4cb801a-3173-471e-917c-a0b528b3bfb9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "G'wenee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Weneen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gwenee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Weneen> .

