Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_F8> <http://telicent.io/ontology/primaryName> "F8" .
<https://starwars.com#grid_F8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#f9e192b4-9d00-4c7e-90f9-b1ed9bd7e563> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#769a93c8-4335-4696-a78b-aa9a662ce27f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_F8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Celwis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#planet_Celwis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Celwis> <http://telicent.io/ontology/primaryName> "Celwis" .
<https://starwars.com#planet_Celwis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#769a93c8-4335-4696-a78b-aa9a662ce27f> .
<https://starwars.com#planet_Celwis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Celwis> <http://www.w3.org/2000/01/rdf-schema#comment> "Celwis was a planet of the Chiss Ascendancy and a stronghold of the Xodlak family. Though Celwis was economically valuable, the world was politically insignificant. While plotting to lead the Chiss into a civil war, Haplif of the Agbui resided on Celwis for a time in order to manipulate the Xodlak Councilor Xodlak'uvi'vil. " .
<https://starwars.com#769a93c8-4335-4696-a78b-aa9a662ce27f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Celwis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f9e192b4-9d00-4c7e-90f9-b1ed9bd7e563> <http://ies.data.gov.uk/ontology/ies4#representationValue> "F8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_F8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f9e192b4-9d00-4c7e-90f9-b1ed9bd7e563> .

