Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TerrSkiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#sector_Terrskiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Terrskiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#5e44d746-90d2-44f3-bf2a-5c1d249e5110> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Terr'Skiar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TerrSkiar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_TerrSkiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TerrSkiar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5e44d746-90d2-44f3-bf2a-5c1d249e5110> .
<https://starwars.com#sector_Terrskiar> <http://telicent.io/ontology/primaryName> "Terr'skiar" .
<https://starwars.com#planet_TerrSkiar> <http://telicent.io/ontology/primaryName> "Terr'Skiar" .
<https://starwars.com#planet_TerrSkiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Terrskiar> .
<https://starwars.com#5e44d746-90d2-44f3-bf2a-5c1d249e5110> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

