Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1d2073b3-a49c-4399-b55c-c1e861b813c9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#dbc2dd6c-a172-41c8-b38e-bcb109a8f5d8> .
<https://starwars.com#sector_Druess> <http://telicent.io/ontology/primaryName> "Druess" .
<https://starwars.com#grid_O15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#dbc2dd6c-a172-41c8-b38e-bcb109a8f5d8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dbc2dd6c-a172-41c8-b38e-bcb109a8f5d8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_AnkKitaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1d2073b3-a49c-4399-b55c-c1e861b813c9> .
<https://starwars.com#planet_AnkKitaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#planet_AnkKitaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Druess> .
<https://starwars.com#planet_AnkKitaar> <http://telicent.io/ontology/primaryName> "Ank Kit'aar" .
<https://starwars.com#grid_O15> <http://telicent.io/ontology/primaryName> "O15" .
<https://starwars.com#sector_Druess> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AnkKitaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Ank Kit'aar was a planet in the Ank Kit'aar system that was located within the Druess sector in the Mid Rim. " .
<https://starwars.com#grid_O15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Druess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_AnkKitaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1d2073b3-a49c-4399-b55c-c1e861b813c9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ank Kit'aar"^^<http://www.w3.org/2001/XMLSchema#string> .

