Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Shoon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e2ab9d38-9bcb-4175-8343-84e16febabe0> .
<https://starwars.com#planet_Shoon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e2ab9d38-9bcb-4175-8343-84e16febabe0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shoon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e2ab9d38-9bcb-4175-8343-84e16febabe0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shoon> <http://telicent.io/ontology/primaryName> "Shoon" .
<https://starwars.com#planet_Shoon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Shoon> <http://www.w3.org/2000/01/rdf-schema#comment> "Shoon was a planet in the Senex sector of the Mid Rim. " .

