Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mayagil> <http://telicent.io/ontology/primaryName> "Mayagil" .
<https://starwars.com#planet_Bith> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#23dc546b-b700-48e1-bff8-c6b2c208e55f> .
<https://starwars.com#sector_Mayagil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bith> <http://telicent.io/ontology/primaryName> "Bith" .
<https://starwars.com#sector_Mayagil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bith> <http://www.w3.org/2000/01/rdf-schema#comment> "The Bith were a peaceful and intelligent sentient species that were native to the planet Bith. They had hairless, domed heads and black, glassy eyes that lacked eyelids and could not shed tears. Bith often found work as musicians, scientists, and engineers. Bith also had very sensitive hearing, being able to separate and isolate sounds around them. Because Bith had no noses, they smelled through special organs beneath the skin flaps on their faces. " .
<https://starwars.com#planet_Bith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mayagil> .
<https://starwars.com#planet_Bith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#23dc546b-b700-48e1-bff8-c6b2c208e55f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bith"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#23dc546b-b700-48e1-bff8-c6b2c208e55f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

