Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#adbf724a-becf-41df-8c2b-eeb317d6ee3c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cranan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cranan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_Cranan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Cranan> <http://telicent.io/ontology/primaryName> "Cranan" .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Cranan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cranan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#adbf724a-becf-41df-8c2b-eeb317d6ee3c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cranan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#adbf724a-becf-41df-8c2b-eeb317d6ee3c> .

