Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Utrost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#774fd907-9a92-4cff-a3f8-6e7b608a7dd9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#774fd907-9a92-4cff-a3f8-6e7b608a7dd9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Utrost"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Utrost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Utrost> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#774fd907-9a92-4cff-a3f8-6e7b608a7dd9> .
<https://starwars.com#planet_Utrost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Utrost> <http://www.w3.org/2000/01/rdf-schema#comment> "Utrost was a cosmopolitan planet located a few light-years from Coruscant within the Utrost system of the Core Worlds. It was Pash Galae's homeworld. " .
<https://starwars.com#planet_Utrost> <http://telicent.io/ontology/primaryName> "Utrost" .

