Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_Q9> <http://telicent.io/ontology/primaryName> "Q9" .
<https://starwars.com#grid_Q9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Balamak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bdb28908-a574-452f-a378-c33675cc6c1c> .
<https://starwars.com#99ee44a1-99c8-4556-a69e-8213f7d3b850> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Taldot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Balamak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Taldot> .
<https://starwars.com#planet_Balamak> <http://www.w3.org/2000/01/rdf-schema#comment> "Balamak was an astronomical object located in the galaxy's Mid Rim. Sometime before the Battle of Scarif, a battle was fought on Balamak, the battle was denoted by red lining on the garb of senator Vasp Vaspar. The population of Balamak was brutally suppressed by the New Republic according to the news feeds of the First Order. The stormtrooper FN-2187 saw one such broadcast in a morale session during his training shortly before his deployment to the planet Jakku. " .
<https://starwars.com#planet_Balamak> <http://telicent.io/ontology/primaryName> "Balamak" .
<https://starwars.com#sector_Taldot> <http://telicent.io/ontology/primaryName> "Taldot" .
<https://starwars.com#grid_Q9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#99ee44a1-99c8-4556-a69e-8213f7d3b850> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Taldot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Balamak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q9> .
<https://starwars.com#bdb28908-a574-452f-a378-c33675cc6c1c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#bdb28908-a574-452f-a378-c33675cc6c1c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Balamak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_Q9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#99ee44a1-99c8-4556-a69e-8213f7d3b850> .
<https://starwars.com#planet_Balamak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

