Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nakat> <http://www.w3.org/2000/01/rdf-schema#comment> "The Black Hole of Nakat was a black hole located in the Inner Rim region of the galaxy.[1] It gave rise to a common phrase that said: 'trapped between the Black Hole of Nakat and the Magataran Maelstrom.'" .
<https://starwars.com#planet_Nakat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#b9d7c5b3-b58f-4e08-80c4-0a13aff32cbd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nakat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#region_InnerRim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#b9d7c5b3-b58f-4e08-80c4-0a13aff32cbd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nakat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nakat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b9d7c5b3-b58f-4e08-80c4-0a13aff32cbd> .
<https://starwars.com#planet_Nakat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#region_InnerRim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Nakat> <http://telicent.io/ontology/primaryName> "Nakat" .
<https://starwars.com#region_InnerRim> <http://telicent.io/ontology/primaryName> "InnerRim" .

