Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Contruum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#sector_Truum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Contruum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b7f179f9-b200-487e-b2cd-1e8faf3f26bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Contruum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Truum> .
<https://starwars.com#planet_Contruum> <http://www.w3.org/2000/01/rdf-schema#comment> "Contruum was an astronomical object in the galaxy's Expansion Region. Angilar Bosh, who created the Galactic Republic propaganda poster Strength and Unity, was an art director for a leading Contruum advertising agency. The Rebel Alliance general Airen Cracken was from Contruum. " .
<https://starwars.com#b7f179f9-b200-487e-b2cd-1e8faf3f26bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Contruum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Truum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Contruum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b7f179f9-b200-487e-b2cd-1e8faf3f26bb> .
<https://starwars.com#sector_Truum> <http://telicent.io/ontology/primaryName> "Truum" .
<https://starwars.com#planet_Contruum> <http://telicent.io/ontology/primaryName> "Contruum" .

