Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kailion> <http://telicent.io/ontology/primaryName> "Kailion" .
<https://starwars.com#planet_Tlactehon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tlactehon> <http://www.w3.org/2000/01/rdf-schema#comment> "A trade world lying on the Corellian Run super-hyperroute, Tlactehon was located in the Expansion Region's Kailion sector. A delegation from Tlactehon that was in reality a front for a gang of smugglers once traveled to the planet Muunilinst, where it was scheduled to meet with representatives of the InterGalactic Banking Clan. As part of the conquest of the galaxy by the extragalactic Yuuzhan Vong, the invaders held the Tlactehon system until at least 27 ABY. " .
<https://starwars.com#planet_Tlactehon> <http://telicent.io/ontology/primaryName> "Tlactehon" .
<https://starwars.com#sector_Kailion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tlactehon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#31c83dc8-f6be-4e54-b7fa-e07ae2c29b7f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tlactehon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#31c83dc8-f6be-4e54-b7fa-e07ae2c29b7f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tlactehon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kailion> .
<https://starwars.com#planet_Tlactehon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31c83dc8-f6be-4e54-b7fa-e07ae2c29b7f> .
<https://starwars.com#sector_Kailion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

