Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#24a8d471-cff9-4ad8-b389-d847c4095064> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ruan> <http://telicent.io/ontology/primaryName> "Ruan" .
<https://starwars.com#planet_Ruan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ruan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Ruan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Ruan> <http://www.w3.org/2000/01/rdf-schema#comment> "Ruan was an agriworld in the Core Worlds. " .
<https://starwars.com#24a8d471-cff9-4ad8-b389-d847c4095064> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ruan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ruan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#24a8d471-cff9-4ad8-b389-d847c4095064> .

