Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#6870d5c9-5ec9-4cc6-9fa1-475f367d3494> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alsakan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Alsakan> <http://www.w3.org/2000/01/rdf-schema#comment> "Alsakan was an astronomical object located in the galaxy's Core Worlds, in grid square L-9 on the Standard Galactic Grid, on the Perlemian Trade Route. It was the homeworld of both Doctor Cornelius Evazan and Allegiant General Enric Pryde. " .
<https://starwars.com#grid_L9> <http://telicent.io/ontology/primaryName> "L9" .
<https://starwars.com#planet_Alsakan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Alsakan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#3bcd6aa7-a7e8-4977-bb94-356648d0c767> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Alsakan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#grid_L9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#3bcd6aa7-a7e8-4977-bb94-356648d0c767> .
<https://starwars.com#planet_Alsakan> <http://telicent.io/ontology/primaryName> "Alsakan" .
<https://starwars.com#3bcd6aa7-a7e8-4977-bb94-356648d0c767> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Alsakan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6870d5c9-5ec9-4cc6-9fa1-475f367d3494> .
<https://starwars.com#6870d5c9-5ec9-4cc6-9fa1-475f367d3494> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

