Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zanbar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mandalore> .
<https://starwars.com#1cc05dcf-fb73-4cb4-951c-07c6ccd9cde7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zanbar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1cc05dcf-fb73-4cb4-951c-07c6ccd9cde7> .
<https://starwars.com#planet_Zanbar> <http://telicent.io/ontology/primaryName> "Zanbar" .
<https://starwars.com#planet_Zanbar> <http://www.w3.org/2000/01/rdf-schema#comment> "Zanbar was a temperate swamp moon in the Outer Rim Territories covered with massive rocky plateaus. During the Clone Wars, the Mandalorian splinter group Death Watch established a temporary camp on its surface, which continued to be used after Death Watch allied with Maul to form the Shadow Collective. Zanbar was later the site of a battle between the Shadow Collective and the Confederacy of Independent Systems. " .
<https://starwars.com#sector_Mandalore> <http://telicent.io/ontology/primaryName> "Mandalore" .
<https://starwars.com#planet_Zanbar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1cc05dcf-fb73-4cb4-951c-07c6ccd9cde7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zanbar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Mandalore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mandalore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Zanbar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .

