Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brema> <http://telicent.io/ontology/primaryName> "Brema" .
<https://starwars.com#planet_CmaoliDi> <http://www.w3.org/2000/01/rdf-schema#comment> "Cmaoli Di was a world in the Brema sector. Between 3701 BBY and 3699 BBY, the Hydian Way was charted through the planet as part of the Seswenna Expansion. Cmaoli Di was known to receive broadcasts from the Brema News service. " .
<https://starwars.com#planet_CmaoliDi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#planet_CmaoliDi> <http://telicent.io/ontology/primaryName> "Cmaoli Di" .
<https://starwars.com#planet_CmaoliDi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#769a4726-3e59-4b23-8462-eae7753e0535> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cmaoli Di"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Brema> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#769a4726-3e59-4b23-8462-eae7753e0535> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_CmaoliDi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#769a4726-3e59-4b23-8462-eae7753e0535> .
<https://starwars.com#planet_CmaoliDi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brema> .
<https://starwars.com#sector_Brema> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

