Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_SluisVan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0fb9cc92-e058-45be-985b-2b85e90c0e6b> .
<https://starwars.com#planet_SluisVan> <http://telicent.io/ontology/primaryName> "Sluis Van" .
<https://starwars.com#0fb9cc92-e058-45be-985b-2b85e90c0e6b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sluis Van"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_SluisVan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#sector_Sluis> <http://telicent.io/ontology/primaryName> "Sluis" .
<https://starwars.com#0fb9cc92-e058-45be-985b-2b85e90c0e6b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SluisVan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sluis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_SluisVan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sluis> .
<https://starwars.com#sector_Sluis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SluisVan> <http://www.w3.org/2000/01/rdf-schema#comment> "Sluis Van was an astronomical object in the southern region of the galaxy's Outer Rim Territories and Western Reaches, along the Rimma Trade Route, in square M-19 of the Standard Galactic Grid. It provided ships to Seswenna's Outland Regions Security Force prior to the Clone Wars. Count Dooku later turned both Sluis Van and Yag'Dhul over to the side of the Confederacy of Independent Systems. " .

