Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Manress> <http://www.w3.org/2000/01/rdf-schema#comment> "Manress was a planet located in the Inner Rim Territories. The world was home to the sentient Stokhli species as well as megafauna that were hunted using spray sticks. " .
<https://starwars.com#planet_Manress> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Manress> <http://telicent.io/ontology/primaryName> "Manress" .
<https://starwars.com#planet_Manress> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_Manress> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4e44fcfd-dcd9-4eda-9c9f-f0831219ce32> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Manress"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Manress> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4e44fcfd-dcd9-4eda-9c9f-f0831219ce32> .
<https://starwars.com#4e44fcfd-dcd9-4eda-9c9f-f0831219ce32> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

