Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Zuma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Zuma> <http://telicent.io/ontology/primaryName> "Zuma" .
<https://starwars.com#planet_Houche> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#407111dd-1e21-4754-89b7-49f78523eaee> .
<https://starwars.com#407111dd-1e21-4754-89b7-49f78523eaee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Houche"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Houche> <http://telicent.io/ontology/primaryName> "Houche" .
<https://starwars.com#planet_Houche> <http://www.w3.org/2000/01/rdf-schema#comment> "Houche was a planet in the Zuma sector, which surrounded the Moddell sector. Houche was an endpoint of the Annaj-Houche Run. " .
<https://starwars.com#planet_Houche> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Houche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#407111dd-1e21-4754-89b7-49f78523eaee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Houche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zuma> .
<https://starwars.com#sector_Zuma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

