Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#52094f14-026b-4eb2-8043-9bbcbf1d919a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_GoldenNyss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#52094f14-026b-4eb2-8043-9bbcbf1d919a> .
<https://starwars.com#planet_GoldenNyss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Fellwe> <http://telicent.io/ontology/primaryName> "Fellwe" .
<https://starwars.com#sector_Fellwe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_GoldenNyss> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_GoldenNyss> <http://telicent.io/ontology/primaryName> "Golden Nyss" .
<https://starwars.com#sector_Fellwe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#52094f14-026b-4eb2-8043-9bbcbf1d919a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Golden Nyss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_GoldenNyss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Fellwe> .
<https://starwars.com#planet_GoldenNyss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .

