Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tibrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hadar> .
<https://starwars.com#planet_Tibrin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9c392a7c-6a50-4950-b9fc-785651f14d10> .
<https://starwars.com#planet_Tibrin> <http://telicent.io/ontology/primaryName> "Tibrin" .
<https://starwars.com#sector_Hadar> <http://telicent.io/ontology/primaryName> "Hadar" .
<https://starwars.com#9c392a7c-6a50-4950-b9fc-785651f14d10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tibrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Hadar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#9c392a7c-6a50-4950-b9fc-785651f14d10> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tibrin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tibrin> <http://www.w3.org/2000/01/rdf-schema#comment> "Tibrin was a aquatic planet covered in phosphorescent seas with towering coral reefs as tall as the sky located on the edge of the Hadar sector, in a trinary star system, within the galaxy's Mid Rim. It was the homeworld of the Ishi Tib species. " .
<https://starwars.com#sector_Hadar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tibrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .

