Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e3e32b8c-f8d4-4baf-a277-e2a3132af149> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bestine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bestine> <http://www.w3.org/2000/01/rdf-schema#comment> "In 3 ABY, the Rebel Alliance's Twenty-First was present on Bestine as a part of a coordinated effort to distract forces and allow the Alliance fleet to complete its withdrawal from the Mid Rim. " .
<https://starwars.com#planet_Bestine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e3e32b8c-f8d4-4baf-a277-e2a3132af149> .
<https://starwars.com#planet_Bestine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Bestine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#e3e32b8c-f8d4-4baf-a277-e2a3132af149> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bestine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bestine> <http://telicent.io/ontology/primaryName> "Bestine" .

