Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d165f7d3-f78f-44c0-8874-126269603983> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dalisor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dalisor> <http://telicent.io/ontology/primaryName> "Dalisor" .
<https://starwars.com#planet_Dalisor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Yushan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d165f7d3-f78f-44c0-8874-126269603983> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Yushan> <http://telicent.io/ontology/primaryName> "Yushan" .
<https://starwars.com#sector_Yushan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dalisor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yushan> .
<https://starwars.com#planet_Dalisor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d165f7d3-f78f-44c0-8874-126269603983> .
<https://starwars.com#planet_Dalisor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#planet_Dalisor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

