Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6628cfe9-c2af-4fe3-83f7-033794025cc3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_N9> <http://telicent.io/ontology/primaryName> "N9" .
<https://starwars.com#planet_Berri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_Berri> <http://telicent.io/ontology/primaryName> "Berri" .
<https://starwars.com#grid_N9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#6628cfe9-c2af-4fe3-83f7-033794025cc3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_N9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#6628cfe9-c2af-4fe3-83f7-033794025cc3> .
<https://starwars.com#planet_Berri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Berri> <http://www.w3.org/2000/01/rdf-schema#comment> "Berri was a planet in the Inner Rim. It was a hot, smog-shrouded world with high gravity and little natural food sources. " .
<https://starwars.com#130c27cd-a549-4035-9728-e6ef09978ea4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Berri"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Berri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#130c27cd-a549-4035-9728-e6ef09978ea4> .
<https://starwars.com#planet_Berri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#130c27cd-a549-4035-9728-e6ef09978ea4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

