Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sirpar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c31edfb-c020-4bc8-a4d1-ea13a0edaf7a> .
<https://starwars.com#3c31edfb-c020-4bc8-a4d1-ea13a0edaf7a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sirpar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sirpar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sirpar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#3c31edfb-c020-4bc8-a4d1-ea13a0edaf7a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Sirpar> <http://www.w3.org/2000/01/rdf-schema#comment> "Sirpar was a planet found within the Galactic Empire. It was known for its extremely high gravity compared to that of other human-inhabited planets in the Empire, as well as a dazzlingly intense sun that was so bright that non-natives needed to wear polarized goggles in order to be able to bear it. Generations of humans living on Sirpar had become adapted to the planet, broad in size and possessed of thick layers of muscle. Many of these had become instructors to Imperial cadets. The planet was used as a training forge for cadets of the Arkanis Academy. During the three-day tour, the cadets were granted provisional ranks as they participated in live exercises commanding stormtroopers that had been rotated off active duty. " .
<https://starwars.com#planet_Sirpar> <http://telicent.io/ontology/primaryName> "Sirpar" .
<https://starwars.com#planet_Sirpar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .

