Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gizer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P8> .
<https://starwars.com#planet_Gizer> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bdfce283-408f-430e-a51c-d1cdfe993d3b> .
<https://starwars.com#planet_Gizer> <http://www.w3.org/2000/01/rdf-schema#comment> "Gizer was an astronomical object located in the galaxy's Expansion Region, located on Perlemian Trade Route. " .
<https://starwars.com#planet_Gizer> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gizer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Locris> .
<https://starwars.com#bdfce283-408f-430e-a51c-d1cdfe993d3b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gizer> <http://telicent.io/ontology/primaryName> "Gizer" .
<https://starwars.com#bdfce283-408f-430e-a51c-d1cdfe993d3b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gizer"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Locris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Locris> <http://telicent.io/ontology/primaryName> "Locris" .
<https://starwars.com#sector_Locris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

