Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L13> <http://telicent.io/ontology/primaryName> "L13" .
<https://starwars.com#planet_Andara> <http://telicent.io/ontology/primaryName> "Andara" .
<https://starwars.com#planet_Andara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#40609c0e-678c-47f0-939d-5dcab72a3589> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#ab994da1-a168-42d7-b18e-b1968ad1f803> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Andara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Andara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#grid_L13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#40609c0e-678c-47f0-939d-5dcab72a3589> .
<https://starwars.com#planet_Andara> <http://www.w3.org/2000/01/rdf-schema#comment> "Andara was an astronomical object located in the galaxy's Core Worlds. Around 5 ABY, the New Republic captured Andara from the Galactic Empire. Reports reached the Empire's 204th Imperial Fighter Wing, and the personnel among the fighter wing were unhappy, some seeking to take revenge. The 204th attacked and destroyed a New Republic outpost on the terrestrial astronomical object Mon Gazza the next day in retaliation to Andara's capture. " .
<https://starwars.com#ab994da1-a168-42d7-b18e-b1968ad1f803> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#40609c0e-678c-47f0-939d-5dcab72a3589> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Andara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Andara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab994da1-a168-42d7-b18e-b1968ad1f803> .

