Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lelmra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#sector_Churba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lelmra> <http://telicent.io/ontology/primaryName> "Lelmra" .
<https://starwars.com#planet_Lelmra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#104daffe-24b9-4cbe-aa04-effac04609ad> .
<https://starwars.com#planet_Lelmra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#104daffe-24b9-4cbe-aa04-effac04609ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Churba> <http://telicent.io/ontology/primaryName> "Churba" .
<https://starwars.com#planet_Lelmra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churba> .
<https://starwars.com#104daffe-24b9-4cbe-aa04-effac04609ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lelmra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lelmra> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_Churba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

