Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#fbfb1f55-bfa3-4e4c-976c-4a152da109d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#planet_Kessel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fbfb1f55-bfa3-4e4c-976c-4a152da109d2> .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#planet_Kessel> <http://www.w3.org/2000/01/rdf-schema#comment> "A mining planet that has been fought over by crime lords for its valuable Spice. A fissure vent beneath the spice mines served as a source of astatic coaxium, an element that could be refined into hyperfuel for starships." .
<https://starwars.com#fbfb1f55-bfa3-4e4c-976c-4a152da109d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kessel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .

