Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Anaxes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Anaxes> <http://telicent.io/ontology/primaryName> "Anaxes" .
<https://starwars.com#planet_Anaxes> <http://www.w3.org/2000/01/rdf-schema#comment> "A rocky planet located in the Azure sector of the galaxy's Core Worlds region. A majority of its surface was covered with tall, red plant-like life. In the early years of the Imperial Era, the planet was destroyed in a cataclysm, with the remains becoming the Anaxes asteroid belt." .
<https://starwars.com#planet_Anaxes> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Anaxes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#8de3210e-5885-49ae-9ecd-63b61404cee1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anaxes"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8de3210e-5885-49ae-9ecd-63b61404cee1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anaxes> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8de3210e-5885-49ae-9ecd-63b61404cee1> .

