Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_S13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_FarPando> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#df1d705f-ace4-4c09-9b2d-7983e3d8bf8f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_S13> <http://telicent.io/ontology/primaryName> "S13" .
<https://starwars.com#planet_FarPando> <http://www.w3.org/2000/01/rdf-schema#comment> "Far Pando was a peaceful agrarian planet in the Far Pando system of Hutt Space. It was situated along the Pando Spur hyperlane, an offshoot of the larger Hollastin Run. The planet was under the control of the sentient Yahk-Tosh species. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#5e62c51a-471a-4899-870c-ba568dcb1e29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_FarPando> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df1d705f-ace4-4c09-9b2d-7983e3d8bf8f> .
<https://starwars.com#planet_FarPando> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#grid_S13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_FarPando> <http://telicent.io/ontology/primaryName> "Far Pando" .
<https://starwars.com#grid_S13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5e62c51a-471a-4899-870c-ba568dcb1e29> .
<https://starwars.com#5e62c51a-471a-4899-870c-ba568dcb1e29> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_FarPando> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S13> .
<https://starwars.com#df1d705f-ace4-4c09-9b2d-7983e3d8bf8f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Far Pando"^^<http://www.w3.org/2001/XMLSchema#string> .

