Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#36833f15-7ef1-4670-ac1b-5639b8160540> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Velga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Velga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Velga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Velga> <http://www.w3.org/2000/01/rdf-schema#comment> "Velga was a planet located within the Velga system of the Mid Rim and orbited by the moon Velga Prime. " .
<https://starwars.com#planet_Velga> <http://telicent.io/ontology/primaryName> "Velga" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#36833f15-7ef1-4670-ac1b-5639b8160540> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Velga"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Velga> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#36833f15-7ef1-4670-ac1b-5639b8160540> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

