Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hestria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#37217ce8-d9be-48a9-9be9-7fc9ade4ef58> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hestria> <http://telicent.io/ontology/primaryName> "Hestria" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hestria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#37217ce8-d9be-48a9-9be9-7fc9ade4ef58> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hestria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hestria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#37217ce8-d9be-48a9-9be9-7fc9ade4ef58> .
<https://starwars.com#planet_Hestria> <http://www.w3.org/2000/01/rdf-schema#comment> "Hestria was a thriving agriworld in the Senex sector known for its wines. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Hestria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

