Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Droxu> <http://www.w3.org/2000/01/rdf-schema#comment> "Droxu was a ringed moon in the Cignet system on the Outer Rim of the galaxy. " .
<https://starwars.com#90e9a3b4-340d-48a1-acc5-1d668a90ee82> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Droxu> <http://telicent.io/ontology/primaryName> "Droxu" .
<https://starwars.com#grid_T11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#90e9a3b4-340d-48a1-acc5-1d668a90ee82> .
<https://starwars.com#sector_Bheriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Bheriz> <http://telicent.io/ontology/primaryName> "Bheriz" .
<https://starwars.com#cc9f783d-3ea7-4778-8389-93bca2582136> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Droxu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Droxu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc9f783d-3ea7-4778-8389-93bca2582136> .
<https://starwars.com#planet_Droxu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#sector_Bheriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Droxu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_T11> <http://telicent.io/ontology/primaryName> "T11" .
<https://starwars.com#grid_T11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#cc9f783d-3ea7-4778-8389-93bca2582136> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Droxu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bheriz> .
<https://starwars.com#grid_T11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#90e9a3b4-340d-48a1-acc5-1d668a90ee82> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T11"^^<http://www.w3.org/2001/XMLSchema#string> .

