Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2f4b4d50-07cd-4127-86b8-10bc4fcabc62> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tisssharl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#sector_Xappyh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#2f4b4d50-07cd-4127-86b8-10bc4fcabc62> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tiss'sharl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tisssharl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2f4b4d50-07cd-4127-86b8-10bc4fcabc62> .
<https://starwars.com#sector_Xappyh> <http://telicent.io/ontology/primaryName> "Xappyh" .
<https://starwars.com#planet_Tisssharl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Xappyh> .
<https://starwars.com#planet_Tisssharl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tisssharl> <http://telicent.io/ontology/primaryName> "Tiss'sharl" .
<https://starwars.com#planet_Tisssharl> <http://www.w3.org/2000/01/rdf-schema#comment> "Tiss'sharl was a planet in the Xappyh sector, located in the Outer Rim Territories. It was home to the Tiss'shar, a species of intelligent therapods. " .
<https://starwars.com#sector_Xappyh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

