Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L3> .
<https://starwars.com#sector_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#502466a3-467a-4227-a8d6-50077a288f1c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Veragi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#planet_Veragi> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#502466a3-467a-4227-a8d6-50077a288f1c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Veragi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#502466a3-467a-4227-a8d6-50077a288f1c> .
<https://starwars.com#planet_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#planet_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Veragi> .

