Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e2ae646a-175e-43b8-bc83-e2f265a0b965> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Piroket"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Piroket> <http://telicent.io/ontology/primaryName> "Piroket" .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Piroket> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e2ae646a-175e-43b8-bc83-e2f265a0b965> .
<https://starwars.com#planet_Piroket> <http://www.w3.org/2000/01/rdf-schema#comment> "Piroket was a world located near to the desert planet Tatooine, which was located in the Tatoo system of the Outer Rim Territories' Arkanis sector. Some of the residents and transients of Mos Eisley spaceport on Tatooine had travelled to the desert world from Piroket. " .
<https://starwars.com#planet_Piroket> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#e2ae646a-175e-43b8-bc83-e2f265a0b965> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Piroket> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Piroket> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

