Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tregillis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tregillis> .
<https://starwars.com#planet_Tregillis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#56629ea2-12d7-488d-b344-9be6ef95fb91> .
<https://starwars.com#sector_Tregillis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tregillis> <http://telicent.io/ontology/primaryName> "Tregillis" .
<https://starwars.com#sector_Tregillis> <http://telicent.io/ontology/primaryName> "Tregillis" .
<https://starwars.com#56629ea2-12d7-488d-b344-9be6ef95fb91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tregillis> <http://www.w3.org/2000/01/rdf-schema#comment> "Tregillis was a planet located within the Tregillis system of the Expansion Region. " .
<https://starwars.com#sector_Tregillis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Tregillis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tregillis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M15> .
<https://starwars.com#56629ea2-12d7-488d-b344-9be6ef95fb91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tregillis"^^<http://www.w3.org/2001/XMLSchema#string> .

