Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Donadus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bamula> <http://telicent.io/ontology/primaryName> "Bamula" .
<https://starwars.com#planet_Donadus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df76f2a8-aff8-45c2-9c63-02fe154f10ea> .
<https://starwars.com#planet_Donadus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#df76f2a8-aff8-45c2-9c63-02fe154f10ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Donadus> <http://www.w3.org/2000/01/rdf-schema#comment> "Donadus was an astronomical object located in the Donadus system, a part of the Inner Rim's Bamula sector. It shared its name with the sentient species Donadi. " .
<https://starwars.com#sector_Bamula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Bamula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Donadus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bamula> .
<https://starwars.com#planet_Donadus> <http://telicent.io/ontology/primaryName> "Donadus" .
<https://starwars.com#df76f2a8-aff8-45c2-9c63-02fe154f10ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Donadus"^^<http://www.w3.org/2001/XMLSchema#string> .

