Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ut> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ut> <http://www.w3.org/2000/01/rdf-schema#comment> "Ut was a planet located in the Ut system of the Hapes Cluster. It provided a song to Leia Organa Solo when the Hapes Consortium sent a diplomatic envoy to Coruscant in 8 ABY. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#dd2ada0e-a90d-46ec-8855-a289da017ca1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ut> <http://telicent.io/ontology/primaryName> "Ut" .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ut> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Ut> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd2ada0e-a90d-46ec-8855-a289da017ca1> .
<https://starwars.com#dd2ada0e-a90d-46ec-8855-a289da017ca1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ut"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Ut> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .

