Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fedalle> <http://telicent.io/ontology/primaryName> "Fedalle" .
<https://starwars.com#planet_Fedalle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Fedalle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Fedalle> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#656a5ab5-8147-4b6b-8e86-d000c1534a9b> .
<https://starwars.com#planet_Fedalle> <http://www.w3.org/2000/01/rdf-schema#comment> "Fedalle was a terrestrial planet within the galaxy's Core Worlds. It was connected via the Hydian Way hyperspace route to the planets Skako and Bellassa. A separate hyperspace lane connected it to the planet Kuat. " .
<https://starwars.com#656a5ab5-8147-4b6b-8e86-d000c1534a9b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#656a5ab5-8147-4b6b-8e86-d000c1534a9b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fedalle"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fedalle> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

