Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Meridian> <http://telicent.io/ontology/primaryName> "Meridian" .
<https://starwars.com#planet_NimDrovis> <http://telicent.io/ontology/primaryName> "Nim Drovis" .
<https://starwars.com#planet_NimDrovis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#abc69fd8-8582-4151-8a70-367a21c2dc62> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nim Drovis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#abc69fd8-8582-4151-8a70-367a21c2dc62> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NimDrovis> <http://www.w3.org/2000/01/rdf-schema#comment> "The world of Nim Drovis was located in the Drovian system in the Meridian sector, and was a rainy planet which boasted a Sector Medical Facility and Medical Research Facility attended to by the Ho'Din physician Doctor Ism Oolos, along with a small New Republic base. The largest free port on Nim Drovis was Bagsho, which was originally settled by colonists from Alderaan turned into a link between the sector's neutral worlds and the New Republic. " .
<https://starwars.com#planet_NimDrovis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_NimDrovis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#abc69fd8-8582-4151-8a70-367a21c2dc62> .
<https://starwars.com#sector_Meridian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NimDrovis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meridian> .
<https://starwars.com#sector_Meridian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRIm> .

