Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tamarin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b3cd562a-cc56-4fe7-a196-5f60ad077adb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_N19> <http://telicent.io/ontology/primaryName> "N19" .
<https://starwars.com#planet_Kirdo> <http://www.w3.org/2000/01/rdf-schema#comment> "Kirdo III was a planet in the Tamarin sector of the Outer Rim Territories, located on the Sanrafsix Corridor between Sevarcos II and Ma'ar Shaddam. It was the home world of the Kitonak race. " .
<https://starwars.com#b3cd562a-cc56-4fe7-a196-5f60ad077adb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kirdo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4d5924b3-0cae-4abc-99e4-f846f306128c> .
<https://starwars.com#grid_N19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Kirdo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kirdo> <http://telicent.io/ontology/primaryName> "Kirdo" .
<https://starwars.com#planet_Kirdo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tamarin> .
<https://starwars.com#4d5924b3-0cae-4abc-99e4-f846f306128c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kirdo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N19> .
<https://starwars.com#grid_N19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Tamarin> <http://telicent.io/ontology/primaryName> "Tamarin" .
<https://starwars.com#planet_Kirdo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b3cd562a-cc56-4fe7-a196-5f60ad077adb> .
<https://starwars.com#4d5924b3-0cae-4abc-99e4-f846f306128c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Tamarin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

