Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#56a68c3a-6b82-44aa-a415-2dddaf29f900> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#c39ce8fd-73bb-4826-bc91-be5cc4ba34fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Algara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c39ce8fd-73bb-4826-bc91-be5cc4ba34fa> .
<https://starwars.com#grid_P15> <http://telicent.io/ontology/primaryName> "P15" .
<https://starwars.com#sector_Corweillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#c39ce8fd-73bb-4826-bc91-be5cc4ba34fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Algara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_P15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#56a68c3a-6b82-44aa-a415-2dddaf29f900> .
<https://starwars.com#planet_Algara> <http://telicent.io/ontology/primaryName> "Algara" .
<https://starwars.com#planet_Algara> <http://www.w3.org/2000/01/rdf-schema#comment> "Algara II, also referred to simply as Algara and Algar was a planet in the Algaran system of the Lambda sector, located in the Mid Rim with a population of approximately 1 billion. It was also the homeworld of the Xan. Algara II was orbited by four moons: Kevron, Omakaton, Radeon and Tallakron. " .
<https://starwars.com#56a68c3a-6b82-44aa-a415-2dddaf29f900> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Algara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Corweillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Algara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corweillian> .
<https://starwars.com#planet_Algara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P15> .
<https://starwars.com#sector_Corweillian> <http://telicent.io/ontology/primaryName> "Corweillian" .

