Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f7ca8f6c-4e0a-42fd-a724-85fa4b03336c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Divora"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f7ca8f6c-4e0a-42fd-a724-85fa4b03336c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Divora> <http://telicent.io/ontology/primaryName> "Divora" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Divora> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Divora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Divora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Divora> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f7ca8f6c-4e0a-42fd-a724-85fa4b03336c> .
<https://starwars.com#planet_Divora> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

