Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Circumtore> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f3821050-4b83-41c7-8c6c-a7c2279d9fe7> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Circumtore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f3821050-4b83-41c7-8c6c-a7c2279d9fe7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Circumtore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Circumtore> <http://telicent.io/ontology/primaryName> "Circumtore" .
<https://starwars.com#planet_Circumtore> <http://www.w3.org/2000/01/rdf-schema#comment> "Circumtore was a world located in the Hutt Space region of the galaxy. It was connected to fellow Hutt Space worlds Rorak, Nar Kaaga and Hollastin by hyperspace routes as well as Daalang outside of the region. Circumtore was located at galactic coordinates S-12. " .
<https://starwars.com#f3821050-4b83-41c7-8c6c-a7c2279d9fe7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Circumtore"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Circumtore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

