Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Wukkar> <http://telicent.io/ontology/primaryName> "Wukkar" .
<https://starwars.com#planet_Wukkar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#3df18571-972a-47c3-83e3-d1743944b3ec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3df18571-972a-47c3-83e3-d1743944b3ec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wukkar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Wukkar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Wukkar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3df18571-972a-47c3-83e3-d1743944b3ec> .
<https://starwars.com#planet_Wukkar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Wukkar> <http://www.w3.org/2000/01/rdf-schema#comment> "Wukkar was a location from which a shuttle of excited schoolchildren attended the Republic Fair on the planet Valo. Shortly after the arrival of the shuttle, which was cleared for approach by space traffic controller Milon Thakkery, Valo fell under attack by Nihil raiders. " .

