Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ovise> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6e6704b5-d9b8-4d70-a52a-c242cb7238e3> .
<https://starwars.com#planet_Ovise> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#6e6704b5-d9b8-4d70-a52a-c242cb7238e3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ovise"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ovise> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#6e6704b5-d9b8-4d70-a52a-c242cb7238e3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ovise> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_Ovise> <http://telicent.io/ontology/primaryName> "Ovise" .
<https://starwars.com#planet_Ovise> <http://www.w3.org/2000/01/rdf-schema#comment> "Ovise was an astronomical object located in the galaxy's Moddell sector. " .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

