Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Abregado-rae> <http://telicent.io/ontology/primaryName> "Abregado-rae" .
<https://starwars.com#02a8a5a5-faab-48e2-92e3-36a7dc4a5671> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Abregado-rae> <http://www.w3.org/2000/01/rdf-schema#comment> "Abregado-rae, also known simply as Abregado and sometimes spelled Abregado-Rae, was a trade world located in the galaxy's Core Worlds. It was situated at the beginning of the Rimma Trade Route. Abregado-rae had the reputation to be a rather lawless world, and its main spaceport was as close to a safe dock for smugglers as could be found in the Core. " .
<https://starwars.com#9f11749e-f7f1-4613-871e-e5bbc0d230cb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Abregado-rae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#02a8a5a5-faab-48e2-92e3-36a7dc4a5671> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abregado-rae"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Abregado-rae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#grid_K13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#9f11749e-f7f1-4613-871e-e5bbc0d230cb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_K13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#9f11749e-f7f1-4613-871e-e5bbc0d230cb> .
<https://starwars.com#grid_K13> <http://telicent.io/ontology/primaryName> "K13" .
<https://starwars.com#planet_Abregado-rae> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02a8a5a5-faab-48e2-92e3-36a7dc4a5671> .
<https://starwars.com#planet_Abregado-rae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .

