Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0932a212-a25a-4580-9805-af20096f3d21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Xerton> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0932a212-a25a-4580-9805-af20096f3d21> .
<https://starwars.com#planet_Xerton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J3> .
<https://starwars.com#planet_Xerton> <http://telicent.io/ontology/primaryName> "Xerton" .
<https://starwars.com#planet_Xerton> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Xerton> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0932a212-a25a-4580-9805-af20096f3d21> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xerton"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Xerton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .

