Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#12dfe964-616b-48b2-bc2b-29cf2416c33a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vaal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vaal> <http://www.w3.org/2000/01/rdf-schema#comment> "Vaal was a planet. " .
<https://starwars.com#planet_Vaal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_Vaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Vaal> <http://telicent.io/ontology/primaryName> "Vaal" .
<https://starwars.com#planet_Vaal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12dfe964-616b-48b2-bc2b-29cf2416c33a> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#12dfe964-616b-48b2-bc2b-29cf2416c33a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

