Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gala> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d4b6f891-4de3-46b8-b45e-1f01330d2147> .
<https://starwars.com#planet_Gala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nuiri> .
<https://starwars.com#sector_Nuiri> <http://telicent.io/ontology/primaryName> "Nuiri" .
<https://starwars.com#planet_Gala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#planet_Gala> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d4b6f891-4de3-46b8-b45e-1f01330d2147> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d4b6f891-4de3-46b8-b45e-1f01330d2147> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gala"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Nuiri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gala> <http://www.w3.org/2000/01/rdf-schema#comment> "Gala was a beautiful and wealthy world at one point ruled by the Beju-Tallah dynasty. It was fairly close to Phindar. " .
<https://starwars.com#sector_Nuiri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gala> <http://telicent.io/ontology/primaryName> "Gala" .

