Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Obana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Obana> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Obana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_Obana> <http://telicent.io/ontology/primaryName> "Obana" .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#24aaa9bc-0b9a-4dc8-8da3-1b9d7f757285> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Obana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#24aaa9bc-0b9a-4dc8-8da3-1b9d7f757285> .
<https://starwars.com#24aaa9bc-0b9a-4dc8-8da3-1b9d7f757285> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Obana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Obana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .

