Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ylesia> <http://telicent.io/ontology/primaryName> "Ylesia" .
<https://starwars.com#dc648482-a99f-4bbf-bf13-7da7bdc794ec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dc648482-a99f-4bbf-bf13-7da7bdc794ec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ylesia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ylesia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T12> .
<https://starwars.com#planet_Ylesia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ylesia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dc648482-a99f-4bbf-bf13-7da7bdc794ec> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Ylesia> <http://www.w3.org/2000/01/rdf-schema#comment> "Ylesia was a terrestrial planet in the Outer Rim Territories section of Hutt Space that, along with the Codian Moon, was the homeworld of the reek species. It was located within the Hutt Space region of the galaxy's Outer Rim Territories and was connected to Teth and Rorak by hyperspace routes. The former pirate queen Maz Kanata marked it as a point of interest on a map she included in the book that would become known as the Smuggler's Guide. " .
<https://starwars.com#planet_Ylesia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .

