Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Djurmo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#830699c5-19c2-4a46-8d46-d09d7ea2073a> .
<https://starwars.com#830699c5-19c2-4a46-8d46-d09d7ea2073a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Djurmo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Strabin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Djurmo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Strabin> .
<https://starwars.com#sector_Strabin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Djurmo> <http://telicent.io/ontology/primaryName> "Djurmo" .
<https://starwars.com#planet_Djurmo> <http://www.w3.org/2000/01/rdf-schema#comment> "Djurmo was a volcanic planet located within the Djurmo system in the Strabin sector of the Mid Rim region of the galaxy. It was the homeworld of the reptilian Huralok species, including the pirate Redkihl Rokk. The region of space around Djurmo was explored between 3000 BBY and 1004 BBY, and it was in unaligned space during the New Sith Wars. It was within space loyal to the Galactic Republic during the Clone Wars and was under the control of the Galactic Empire until at least 11 ABY, but was outside of the Empire's territory by the following year. " .
<https://starwars.com#planet_Djurmo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#sector_Strabin> <http://telicent.io/ontology/primaryName> "Strabin" .
<https://starwars.com#830699c5-19c2-4a46-8d46-d09d7ea2073a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Djurmo"^^<http://www.w3.org/2001/XMLSchema#string> .

