Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tomo-Reth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Tomo-Reth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#071cb0b8-17ff-4c47-9712-be4335c09471> .
<https://starwars.com#planet_Tomo-Reth> <http://telicent.io/ontology/primaryName> "Tomo-Reth" .
<https://starwars.com#planet_Tomo-Reth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#071cb0b8-17ff-4c47-9712-be4335c09471> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tomo-Reth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tomo-Reth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#071cb0b8-17ff-4c47-9712-be4335c09471> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tomo-Reth> <http://www.w3.org/2000/01/rdf-schema#comment> "Tomo-Reth was an astronomical object located in the Tomo-Reth system, a part of the Trailing Sectors portion of the Inner Rim. It was the site of the Caliginous Automaton of Tomo-Reth, a famous, more than fifty meters–high droid that sat on a brick throne and breathed fire at visitors, causing them to become amazed. " .

