Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Boro-borosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Boro-borosa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e404af49-792b-4d49-b182-e878d98527fa> .
<https://starwars.com#e404af49-792b-4d49-b182-e878d98527fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Boro-borosa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Boro-borosa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Boro-borosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Boro-borosa> <http://telicent.io/ontology/primaryName> "Boro-borosa" .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e404af49-792b-4d49-b182-e878d98527fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Boro-borosa> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

