Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e9803eb7-25c6-43d0-8270-213560b6906e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_N6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e9803eb7-25c6-43d0-8270-213560b6906e> .
<https://starwars.com#planet_Cathar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c422d0cf-6ce4-4af0-ada7-6b3d9a588d49> .
<https://starwars.com#planet_Cathar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N6> .
<https://starwars.com#c422d0cf-6ce4-4af0-ada7-6b3d9a588d49> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c422d0cf-6ce4-4af0-ada7-6b3d9a588d49> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cathar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N6> <http://telicent.io/ontology/primaryName> "N6" .
<https://starwars.com#sector_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cathar> <http://www.w3.org/2000/01/rdf-schema#comment> "The Cathar were a catlike, humanoid sentient species. Members of the species possessed fur and manes. " .
<https://starwars.com#grid_N6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#planet_Cathar> <http://telicent.io/ontology/primaryName> "Cathar" .
<https://starwars.com#planet_Cathar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quelii> .
<https://starwars.com#grid_N6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#e9803eb7-25c6-43d0-8270-213560b6906e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cathar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

