Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ornfra> <http://telicent.io/ontology/primaryName> "Ornfra" .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Ornfra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#72a60cff-bd83-497d-b1cd-c69fee4cb3c6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#72a60cff-bd83-497d-b1cd-c69fee4cb3c6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ornfra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ornfra> <http://www.w3.org/2000/01/rdf-schema#comment> "Ornfra was a terrestrial planet of the Chiss Ascendancy within the Unknown Regions' Ornfra system. Located within the Ascendancy's northeast-zenith sector, Ornfra was an important economic and political hub, home to strongholds of all the Nine Ruling Families and seventeen of the Forty Great Families. Out of the nine Ruling Families, the Dasklo family had comparatively higher holdings on the planet, including Krolling Sen, a shipyard and research center. " .
<https://starwars.com#planet_Ornfra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Ornfra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ornfra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#72a60cff-bd83-497d-b1cd-c69fee4cb3c6> .

