Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tammuz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#26bcc362-4418-4a48-967d-e17492eb4488> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#26bcc362-4418-4a48-967d-e17492eb4488> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tammuz-an"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tammuz-an> <http://www.w3.org/2000/01/rdf-schema#comment> "Tammuz-an was a planet located in the galaxy's Outer Rim Territories. Shortly after the end of the Clone Wars, the kingdom of Tammuz-an purchased a batch of R-22 prototypes from Kuat Systems Engineering designers for their planetary defense fleet, after the Galactic Empire rejected the ship for mass production. Tammuz-an was responsible for nicknaming the R-22 as 'Spearheads' after their resemblance to local spears. " .
<https://starwars.com#planet_Tammuz-an> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#26bcc362-4418-4a48-967d-e17492eb4488> .
<https://starwars.com#planet_Tammuz-an> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tammuz> .
<https://starwars.com#planet_Tammuz-an> <http://telicent.io/ontology/primaryName> "Tammuz-an" .
<https://starwars.com#sector_Tammuz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tammuz-an> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T14> .
<https://starwars.com#sector_Tammuz> <http://telicent.io/ontology/primaryName> "Tammuz" .
<https://starwars.com#planet_Tammuz-an> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

