Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#aa9fce7f-3c9d-478e-86ad-4db8ee9e2968> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mechis III"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MechisIII> <http://www.w3.org/2000/01/rdf-schema#comment> "Mechis III was a vital Techno Union world located in the galaxy. It was defended by a mix of starships from member corporations and design firms such as SoroSuub Corporation. " .
<https://starwars.com#planet_MechisIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#planet_MechisIII> <http://telicent.io/ontology/primaryName> "Mechis III" .
<https://starwars.com#aa9fce7f-3c9d-478e-86ad-4db8ee9e2968> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MechisIII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aa9fce7f-3c9d-478e-86ad-4db8ee9e2968> .
<https://starwars.com#planet_MechisIII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MechisIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

