Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Entralla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Entralla> <http://telicent.io/ontology/primaryName> "Entralla" .
<https://starwars.com#4266503b-57ec-4a3f-81ce-2e7369573aa0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Entralla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Velcar> <http://telicent.io/ontology/primaryName> "Velcar" .
<https://starwars.com#planet_Entralla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Velcar> .
<https://starwars.com#planet_Entralla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4266503b-57ec-4a3f-81ce-2e7369573aa0> .
<https://starwars.com#planet_Entralla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#4266503b-57ec-4a3f-81ce-2e7369573aa0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Velcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Entralla> <http://www.w3.org/2000/01/rdf-schema#comment> "Entralla was an astronomical object located within the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Velcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

