Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cd32b635-8230-4510-a3c2-425ed345f85d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thaere> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cd32b635-8230-4510-a3c2-425ed345f85d> .
<https://starwars.com#sector_Thaere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Thaere> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Thaere> <http://telicent.io/ontology/primaryName> "Thaere" .
<https://starwars.com#planet_Thaere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thaere> .
<https://starwars.com#planet_Thaere> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#sector_Thaere> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#cd32b635-8230-4510-a3c2-425ed345f85d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thaere"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thaere> <http://www.w3.org/2000/01/rdf-schema#comment> "The Thaereian system was a Expansion Region star system centered around a dying yellow star, near the Cularin system. Planets in the system included Odae Ripp, Thaere Privo, Zham Hlar. " .
<https://starwars.com#planet_Thaere> <http://telicent.io/ontology/primaryName> "Thaere" .

