Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Teth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Teth> <http://telicent.io/ontology/primaryName> "Teth" .
<https://starwars.com#planet_Teth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .
<https://starwars.com#planet_Teth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#planet_Teth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#05ae85ca-8326-4d23-8dfb-ef663b5580af> .
<https://starwars.com#05ae85ca-8326-4d23-8dfb-ef663b5580af> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#05ae85ca-8326-4d23-8dfb-ef663b5580af> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Teth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Teth> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Clone Wars, Jabba's son Rotta is abducted by the Separatists and brought to this planet. Anakin and Ahsoka Tano travel to Teth and rescue Rotta from Asajj Ventress." .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .

