Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Metellos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Metellos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Metellos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#552a4089-8998-445a-b036-d1058bcf545f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Metellos> <http://www.w3.org/2000/01/rdf-schema#comment> "Metellos was a planet in the galaxy's Core Worlds region connected via hyperspace route to the planet Ilum. The route was mapped by hyperspace surveyors hired by the Jedi Order as Ilum was a world important to the training of a Jedi. " .
<https://starwars.com#552a4089-8998-445a-b036-d1058bcf545f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Metellos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Metellos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#552a4089-8998-445a-b036-d1058bcf545f> .
<https://starwars.com#planet_Metellos> <http://telicent.io/ontology/primaryName> "Metellos" .

