Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_C-Foroon> <http://www.w3.org/2000/01/rdf-schema#comment> "C-Foroon was a planet in the Arkanis sector of the Outer Rim. " .
<https://starwars.com#planet_C-Foroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_C-Foroon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#124a8b56-946b-4ecb-ba91-14751b9dd156> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_C-Foroon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#124a8b56-946b-4ecb-ba91-14751b9dd156> <http://ies.data.gov.uk/ontology/ies4#representationValue> "C-Foroon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#124a8b56-946b-4ecb-ba91-14751b9dd156> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_C-Foroon> <http://telicent.io/ontology/primaryName> "C-Foroon" .
<https://starwars.com#planet_C-Foroon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

