Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dilonexa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#66c191a7-b9f4-4162-894a-f2f9bab6b23b> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#66c191a7-b9f4-4162-894a-f2f9bab6b23b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dilonexa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#planet_Dilonexa> <http://www.w3.org/2000/01/rdf-schema#comment> "Dilonexa XXIII was a large agriworld located in the Outer Rim Territories' Centrality sector. Each year the planet exported billions of tons of agricultural products, and it served as the Centrality's main producer of foodstuffs, with orbital weather-control satellites helping disperse the local city-sized tornados. Due to Dilonexa XXIII lacking heavy metals in its geological makeup, its inhabitants, the Dilonexicans, developed an allergic reaction to foods that contained high quantities of trace metals." .
<https://starwars.com#66c191a7-b9f4-4162-894a-f2f9bab6b23b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dilonexa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dilonexa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Dilonexa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dilonexa> <http://telicent.io/ontology/primaryName> "Dilonexa" .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

