Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Antiquity> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Antiquity> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#bad529e7-5755-4b69-a357-4423ac7002de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Antiquity"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Antiquity> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Antiquity> <http://www.w3.org/2000/01/rdf-schema#comment> "Antiquity was a Mid Rim planet located in the Senex sector. " .
<https://starwars.com#planet_Antiquity> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bad529e7-5755-4b69-a357-4423ac7002de> .
<https://starwars.com#bad529e7-5755-4b69-a357-4423ac7002de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Antiquity> <http://telicent.io/ontology/primaryName> "Antiquity" .

