Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vorsia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#53b76236-743d-4768-8b98-52fa02273327> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#53b76236-743d-4768-8b98-52fa02273327> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vorsia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vorsia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_Vorsia> <http://telicent.io/ontology/primaryName> "Vorsia" .
<https://starwars.com#planet_Vorsia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vorsia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#53b76236-743d-4768-8b98-52fa02273327> .
<https://starwars.com#planet_Vorsia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

