Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Danteel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#8567658a-2d90-4bf1-8ec7-9a1a36f18bce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Danteel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Danteel> <http://telicent.io/ontology/primaryName> "Danteel" .
<https://starwars.com#planet_Danteel> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet Danteel was the capital of the Emmo sector. " .
<https://starwars.com#planet_Danteel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#8567658a-2d90-4bf1-8ec7-9a1a36f18bce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Danteel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Danteel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8567658a-2d90-4bf1-8ec7-9a1a36f18bce> .

