Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ibanjji> <http://telicent.io/ontology/primaryName> "Ibanjji" .
<https://starwars.com#sector_Mierukar> <http://telicent.io/ontology/primaryName> "Mieru'kar" .
<https://starwars.com#705a9d20-c79b-4dec-adc4-3b276c0e277e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mierukar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ibanjji> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#705a9d20-c79b-4dec-adc4-3b276c0e277e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ibanjji"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ibanjji> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .
<https://starwars.com#planet_Ibanjji> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mierukar> .
<https://starwars.com#planet_Ibanjji> <http://www.w3.org/2000/01/rdf-schema#comment> "Ibanjji was a terrestrial world located in the Ibanjji system, a part of the Mieru'kar sector in the New Territories portion of the Outer Rim Territories. The conditions on Ibanjji were harsh, and it was home to packs of creatures known as varns. During the reign of the Galactic Empire, it was the site of a special motivational camp used to harden Imperial recruits. " .
<https://starwars.com#planet_Ibanjji> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#705a9d20-c79b-4dec-adc4-3b276c0e277e> .
<https://starwars.com#sector_Mierukar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

