Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Koradin> <http://telicent.io/ontology/primaryName> "Koradin" .
<https://starwars.com#sector_Koradin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_J18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Abridon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J18> .
<https://starwars.com#dd30b6cc-83fe-48fc-92de-3921a729d920> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abridon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Koradin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Abridon> <http://telicent.io/ontology/primaryName> "Abridon" .
<https://starwars.com#planet_Abridon> <http://www.w3.org/2000/01/rdf-schema#comment> "Abridon was a pleasant, mountainous planet with special significance to the career of Brenn Tantor. Its capital housed the Abridon Government Center, while Sayan was the center of its shipbuilding industry. It was primarily notable to the greater galaxy as the site of Luke Skywalker's capture by the Galactic Empire. It was located on the Northern Corridor's Lipsec Run. " .
<https://starwars.com#planet_Abridon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd30b6cc-83fe-48fc-92de-3921a729d920> .
<https://starwars.com#grid_J18> <http://telicent.io/ontology/primaryName> "J18" .
<https://starwars.com#grid_J18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_J18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5c4d4484-94c3-405e-afcc-2b9296db60bd> .
<https://starwars.com#planet_Abridon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Abridon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Koradin> .
<https://starwars.com#dd30b6cc-83fe-48fc-92de-3921a729d920> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5c4d4484-94c3-405e-afcc-2b9296db60bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5c4d4484-94c3-405e-afcc-2b9296db60bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

