Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_HadAbbadon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_HadAbbadon> <http://www.w3.org/2000/01/rdf-schema#comment> "Had Abbadon was an astronomical object situated in the Deep Core, the treacherous central region of the galaxy. " .
<https://starwars.com#planet_HadAbbadon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_HadAbbadon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d8b3b181-ef45-43e4-84fb-4a1315d7b876> .
<https://starwars.com#d8b3b181-ef45-43e4-84fb-4a1315d7b876> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d8b3b181-ef45-43e4-84fb-4a1315d7b876> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Had Abbadon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_HadAbbadon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_HadAbbadon> <http://telicent.io/ontology/primaryName> "Had Abbadon" .

