Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_DAstan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Celanon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#planet_Celanon> <http://telicent.io/ontology/primaryName> "Celanon" .
<https://starwars.com#sector_DAstan> <http://telicent.io/ontology/primaryName> "D'Astan" .
<https://starwars.com#d5a17b13-bd6f-4683-b665-acbd0c984ccb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#d5a17b13-bd6f-4683-b665-acbd0c984ccb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Celanon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Celanon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_DAstan> .
<https://starwars.com#planet_Celanon> <http://www.w3.org/2000/01/rdf-schema#comment> "Celanon was an astronomical object located in the galaxy's Outer Rim Territories, situated along the Hydian Way which connected it to Junction and Botajef. It was home to the Astarte line. " .
<https://starwars.com#planet_Celanon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Celanon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d5a17b13-bd6f-4683-b665-acbd0c984ccb> .
<https://starwars.com#sector_DAstan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

