Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ertegas> <http://www.w3.org/2000/01/rdf-schema#comment> "Assumption ends here." .
<https://starwars.com#planet_Ertegas> <http://telicent.io/ontology/primaryName> "Ertegas" .
<https://starwars.com#planet_Ertegas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#a2f698dd-0ce7-45ae-ad97-8a452f5bcdde> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#a2f698dd-0ce7-45ae-ad97-8a452f5bcdde> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ertegas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Ertegas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Ertegas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ertegas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2f698dd-0ce7-45ae-ad97-8a452f5bcdde> .

