Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Livien> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Livien> <http://www.w3.org/2000/01/rdf-schema#comment> "Livien was a planet located within the Outer Rim Territories and the founding world of the Livien League. " .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Livien> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .
<https://starwars.com#planet_Livien> <http://telicent.io/ontology/primaryName> "Livien" .
<https://starwars.com#planet_Livien> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#452b50aa-34ca-4936-b46f-71f7f8e3b1a8> .
<https://starwars.com#452b50aa-34ca-4936-b46f-71f7f8e3b1a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#452b50aa-34ca-4936-b46f-71f7f8e3b1a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Livien"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Livien> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

