Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Dolis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#93b1cf30-7c0c-4348-bffa-345151a3a09e> .
<https://starwars.com#grid_J3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#93b1cf30-7c0c-4348-bffa-345151a3a09e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dolis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J3> .
<https://starwars.com#planet_Dolis> <http://telicent.io/ontology/primaryName> "Dolis" .
<https://starwars.com#sector_Obtrexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_J3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c523b079-e00e-474c-a406-95fa6962b079> .
<https://starwars.com#c523b079-e00e-474c-a406-95fa6962b079> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Dolis> <http://www.w3.org/2000/01/rdf-schema#comment> "Dolis 3 was an Imperial Remnant planet in the Outer Rim Territories, in the influence of Yaga Minor. It was locked in perpetual winter because of its distance from its sun. " .
<https://starwars.com#93b1cf30-7c0c-4348-bffa-345151a3a09e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dolis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dolis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J3> <http://telicent.io/ontology/primaryName> "J3" .
<https://starwars.com#sector_Obtrexta> <http://telicent.io/ontology/primaryName> "Obtrexta" .
<https://starwars.com#sector_Obtrexta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dolis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Obtrexta> .
<https://starwars.com#c523b079-e00e-474c-a406-95fa6962b079> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J3"^^<http://www.w3.org/2001/XMLSchema#string> .

