Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#15886b8d-eed7-4352-a061-f70a5488bdb9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Turkana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Turkana> <http://telicent.io/ontology/primaryName> "Turkana" .
<https://starwars.com#planet_Turkana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Turkana> <http://www.w3.org/2000/01/rdf-schema#comment> "Turkana was a planet in the Outer Rim Territories that served as an Alliance to Restore the Republic regional headquarters and operations sector during the Galactic Civil War. Turkana was included in a map of the galaxy that listed safe worlds, starfighter hubs at level five or higher, regional headquarters and operations sectors, and deep space caches. " .
<https://starwars.com#planet_Turkana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#15886b8d-eed7-4352-a061-f70a5488bdb9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Turkana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Turkana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#15886b8d-eed7-4352-a061-f70a5488bdb9> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

