Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Roche> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Roche> <http://telicent.io/ontology/primaryName> "Roche" .
<https://starwars.com#6536dd4f-7900-4542-b3a4-19140cc11c71> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Roche> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6536dd4f-7900-4542-b3a4-19140cc11c71> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Roche"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Roche> <http://telicent.io/ontology/primaryName> "Roche" .
<https://starwars.com#planet_Roche> <http://www.w3.org/2000/01/rdf-schema#comment> "Roche was a location in the galaxy's Mid Rim, in grid square Q-8 on the Standard Galactic Grid, situated between Lantillies and Abhean on the Perlemian Trade Route. It shared its name with the Verpine Roche Hive, a droid manufacturer, and the Roche Foundation Prize award. During the Clone Wars, a sneak attack on Roche occurred, a battle which the Dressellian smuggler Has Obitt was caught in the middle of. " .
<https://starwars.com#sector_Roche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Roche> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6536dd4f-7900-4542-b3a4-19140cc11c71> .
<https://starwars.com#planet_Roche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .
<https://starwars.com#planet_Roche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Roche> .

