Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vulta> <http://telicent.io/ontology/primaryName> "Vulta" .
<https://starwars.com#sector_TransVulta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TransVulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_TransVulta> <http://telicent.io/ontology/primaryName> "Trans'Vulta" .
<https://starwars.com#f6dcbde2-8102-4398-a5c5-07beb029a0aa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vulta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f6dcbde2-8102-4398-a5c5-07beb029a0aa> .
<https://starwars.com#planet_Vulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TransVulta> .
<https://starwars.com#planet_Vulta> <http://www.w3.org/2000/01/rdf-schema#comment> "Vulta was a planet located within the Atreyis system of the Mid Rim. It was the homeworld of the Vultan species, as well as Greff-Timms Industrial and Oss Wilum. " .
<https://starwars.com#f6dcbde2-8102-4398-a5c5-07beb029a0aa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vulta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vulta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .

