Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#47c1d027-2a8e-46d3-8526-422ca5d49c84> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kerkoidia> <http://www.w3.org/2000/01/rdf-schema#comment> "Kerkoidia was a blue-gray planet located in the Expansion Region, in the grid square N-15 of the Standard Galactic Grid. The Kerkoiden male Whorm Loathsom was a native of Kerkoidia and for a long time served in its planetary defense forces. Loathsom eventually earned the rank of general with the Confederacy of Independent Systems. In addition to Loathsom joining the Confederacy of Independent Systems, the Retail Caucus was headquarted on Kerkoida and was a large donor of the CIS. After the Battle of Endor, the New Republic managed to liberate Kerkoidia from the Galactic Empire. " .
<https://starwars.com#planet_Kerkoidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kira> .
<https://starwars.com#sector_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Kerkoidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#sector_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#planet_Kerkoidia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#47c1d027-2a8e-46d3-8526-422ca5d49c84> .
<https://starwars.com#47c1d027-2a8e-46d3-8526-422ca5d49c84> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kerkoidia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kerkoidia> <http://telicent.io/ontology/primaryName> "Kerkoidia" .
<https://starwars.com#planet_Kerkoidia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

