Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#042e8363-4f63-4ed1-bfd4-5b007cca0ef8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aeneid> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#planet_Aeneid> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#grid_T10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Aeneid> <http://telicent.io/ontology/primaryName> "Aeneid" .
<https://starwars.com#3e9c98b2-e32b-4911-9f8c-48e7c9f609f0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#042e8363-4f63-4ed1-bfd4-5b007cca0ef8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#3e9c98b2-e32b-4911-9f8c-48e7c9f609f0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aeneid"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T10> <http://telicent.io/ontology/primaryName> "T10" .
<https://starwars.com#planet_Aeneid> <http://www.w3.org/2000/01/rdf-schema#comment> "Aeneid was an astronomical object located in the Kessel sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Aeneid> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3e9c98b2-e32b-4911-9f8c-48e7c9f609f0> .
<https://starwars.com#planet_Aeneid> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_T10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_T10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#042e8363-4f63-4ed1-bfd4-5b007cca0ef8> .

