Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Minashee> <http://www.w3.org/2000/01/rdf-schema#comment> "Minashee was the homeworld of Jedi Master Sifo-Dyas and of his father, who worked as a fisherman. It was part of the Cassandran Worlds. While recording a holocomm for his sister, Jenza, Jedi Initiate Dooku mentioned that Sifo-Dyas was from Minashee. " .
<https://starwars.com#planet_Minashee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Minashee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#50ee483b-b509-4af4-93f3-ba112d8f9c91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Minashee> <http://telicent.io/ontology/primaryName> "Minashee" .
<https://starwars.com#planet_Minashee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#50ee483b-b509-4af4-93f3-ba112d8f9c91> .
<https://starwars.com#planet_Minashee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#50ee483b-b509-4af4-93f3-ba112d8f9c91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Minashee"^^<http://www.w3.org/2001/XMLSchema#string> .

