Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PolisMassa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9f4a6dee-ec62-4cb8-8777-04e9dd287cbc> .
<https://starwars.com#sector_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#planet_PolisMassa> <http://www.w3.org/2000/01/rdf-schema#comment> "Outer Rim planetoid within an asteroid field of the same name; birthplace of Luke Skywalker and Leia Organa." .
<https://starwars.com#planet_PolisMassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K20> .
<https://starwars.com#sector_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#9f4a6dee-ec62-4cb8-8777-04e9dd287cbc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#9f4a6dee-ec62-4cb8-8777-04e9dd287cbc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Polis Massa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PolisMassa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PolisMassa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Subterrel> .
<https://starwars.com#planet_PolisMassa> <http://telicent.io/ontology/primaryName> "Polis Massa" .
<https://starwars.com#sector_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

