Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Lantillian> <http://telicent.io/ontology/primaryName> "Lantillian" .
<https://starwars.com#planet_Uyter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#planet_Uyter> <http://telicent.io/ontology/primaryName> "Uyter" .
<https://starwars.com#sector_Lantillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Uyter> <http://www.w3.org/2000/01/rdf-schema#comment> "Uyter was a planet in the Mid Rim Territories known mostly for its agriculture and farming of crops and foodstuffs. During the Imperial Era, the Galactic Empire established an Imperial Academy in Uyter's capital city, Central City. Around the time of the Battle of Scarif, Uyter was represented in the Imperial Senate by Senator Nower Jebel. Just a few months after the pivotal Battle of Endor, the Alliance to Restore the Republic invaded Uyter and liberated the Imperial Academy from the Empire. Thirty years later, Uyter was a member world in the New Republic, where it was represented by Nahani Gillen in the Galactic Senate. " .
<https://starwars.com#planet_Uyter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lantillian> .
<https://starwars.com#planet_Uyter> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9ad4059f-6260-49a7-a61b-50697c6d9254> .
<https://starwars.com#planet_Uyter> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9ad4059f-6260-49a7-a61b-50697c6d9254> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Lantillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#9ad4059f-6260-49a7-a61b-50697c6d9254> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Uyter"^^<http://www.w3.org/2001/XMLSchema#string> .

