Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#9f2da0ad-5b27-43b5-9dac-95bbeaf39813> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Halla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bimmisaari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R9> .
<https://starwars.com#planet_Bimmisaari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bimmisaari> <http://telicent.io/ontology/primaryName> "Bimmisaari" .
<https://starwars.com#9f2da0ad-5b27-43b5-9dac-95bbeaf39813> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bimmisaari"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Halla> <http://telicent.io/ontology/primaryName> "Halla" .
<https://starwars.com#sector_Halla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Bimmisaari> <http://www.w3.org/2000/01/rdf-schema#comment> "Bimmisaari was an astronomical object in the galaxy's Mid Rim that was located on a hyperspace route between Charros IV and Boonta. " .
<https://starwars.com#planet_Bimmisaari> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9f2da0ad-5b27-43b5-9dac-95bbeaf39813> .
<https://starwars.com#planet_Bimmisaari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halla> .

