Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jubilar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Toongl> <http://telicent.io/ontology/primaryName> "Toong'l" .
<https://starwars.com#sector_Jubilar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c46da750-3c3e-40df-9441-e68ca39e2ea7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Toong'l"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Toongl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c46da750-3c3e-40df-9441-e68ca39e2ea7> .
<https://starwars.com#planet_Toongl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jubilar> .
<https://starwars.com#planet_Toongl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_Toongl> <http://www.w3.org/2000/01/rdf-schema#comment> "Toong'l was an astronomical object located in the Outer Rim Territories of the galaxy, positioned at the coordinates T-7 on the Standard Galactic Grid. " .
<https://starwars.com#sector_Jubilar> <http://telicent.io/ontology/primaryName> "Jubilar" .
<https://starwars.com#planet_Toongl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c46da750-3c3e-40df-9441-e68ca39e2ea7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

