Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KunasEye> <http://www.w3.org/2000/01/rdf-schema#comment> "Kuna's Eye was a celestial body situated in the Outer Rim Territories' Moddell sector in grid square H-16 of the Standard Galactic Grid. It was connected to the astronomical objects Kuna's Fist and Kuna's Tooth via hyperspace routes. Kuna's Eye was depicted on a map of the Moddell sector included with the collection of non-electronic Rebel Alliance documents known as The Rebel Files. " .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KunasEye> <http://telicent.io/ontology/primaryName> "Kuna's Eye" .
<https://starwars.com#da07b7e3-06c9-4749-a03c-c36a535072b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KunasEye> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#da07b7e3-06c9-4749-a03c-c36a535072b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuna's Eye"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KunasEye> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#da07b7e3-06c9-4749-a03c-c36a535072b8> .
<https://starwars.com#planet_KunasEye> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_KunasEye> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

