Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GravlexMed> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#87275866-b0dc-4c38-80eb-c96f530b2179> .
<https://starwars.com#87275866-b0dc-4c38-80eb-c96f530b2179> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#87275866-b0dc-4c38-80eb-c96f530b2179> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gravlex Med"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_GravlexMed> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#planet_GravlexMed> <http://www.w3.org/2000/01/rdf-schema#comment> "Gravlex Med was a high gravity planet located in the galaxy's Outer Rim Territories. It was the homeworld of the Anx species. " .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#planet_GravlexMed> <http://telicent.io/ontology/primaryName> "Gravlex Med" .
<https://starwars.com#planet_GravlexMed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_GravlexMed> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .

