Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8537721a-23bb-4eee-b87e-5ff5583522c1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barkhesh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K19> <http://telicent.io/ontology/primaryName> "K19" .
<https://starwars.com#sector_Seitia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Seitia> <http://telicent.io/ontology/primaryName> "Seitia" .
<https://starwars.com#8deb474e-53c2-4e94-a532-6789e9b2c709> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Barkhesh> <http://www.w3.org/2000/01/rdf-schema#comment> "Barkhesh was a planet located in the Seitia sector of the Outer Rim Territories. " .
<https://starwars.com#grid_K19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#8deb474e-53c2-4e94-a532-6789e9b2c709> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Barkhesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K19> .
<https://starwars.com#planet_Barkhesh> <http://telicent.io/ontology/primaryName> "Barkhesh" .
<https://starwars.com#planet_Barkhesh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Barkhesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Seitia> .
<https://starwars.com#grid_K19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8deb474e-53c2-4e94-a532-6789e9b2c709> .
<https://starwars.com#grid_K19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Seitia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#8537721a-23bb-4eee-b87e-5ff5583522c1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Barkhesh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8537721a-23bb-4eee-b87e-5ff5583522c1> .

