Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kiribi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Kiribi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kiribi> <http://www.w3.org/2000/01/rdf-schema#comment> "Kiribi was a planet located in the Colonies. Its galactic coordinates were 099,099,011. Although it was located 5000 light-years away from Coruscant, because Kiribi's coordinates were positive and began with zero, it was part of the Imperial Center Oversector during the Imperial Period. " .
<https://starwars.com#planet_Kiribi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3638fbe5-c944-4367-bcd4-3542d787fbc9> .
<https://starwars.com#3638fbe5-c944-4367-bcd4-3542d787fbc9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kiribi> <http://telicent.io/ontology/primaryName> "Kiribi" .
<https://starwars.com#planet_Kiribi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#3638fbe5-c944-4367-bcd4-3542d787fbc9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kiribi"^^<http://www.w3.org/2001/XMLSchema#string> .

