Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Norval> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#planet_Norval> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Norval> <http://telicent.io/ontology/primaryName> "Norval" .
<https://starwars.com#planet_Norval> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T9> .
<https://starwars.com#planet_Norval> <http://www.w3.org/2000/01/rdf-schema#comment> "Norval was the primary star of the Norval system. Norval II orbited it. " .
<https://starwars.com#a6c5954a-75c3-42d4-bd37-7ae970733b7b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a6c5954a-75c3-42d4-bd37-7ae970733b7b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Norval"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Norval> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a6c5954a-75c3-42d4-bd37-7ae970733b7b> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

