Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Boeus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Lohopa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M15> .
<https://starwars.com#planet_Lohopa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Boeus> .
<https://starwars.com#planet_Lohopa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lohopa> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Boeus> <http://telicent.io/ontology/primaryName> "Boeus" .
<https://starwars.com#dd6971e0-e7ba-4051-9e7c-e2bcd07eea6e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lohopa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#dd6971e0-e7ba-4051-9e7c-e2bcd07eea6e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Boeus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lohopa> <http://telicent.io/ontology/primaryName> "Lohopa" .
<https://starwars.com#planet_Lohopa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd6971e0-e7ba-4051-9e7c-e2bcd07eea6e> .

