Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#planet_Lutrillia> <http://www.w3.org/2000/01/rdf-schema#comment> "Lutrillia was a planet in the Greater Javin Region of the galaxy's Outer Rim Territories that was the homeworld of the Lutrillian species. " .
<https://starwars.com#926cf0b6-4ab1-4bf0-886d-fbd6500c82a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#926cf0b6-4ab1-4bf0-886d-fbd6500c82a3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lutrillia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lutrillia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#planet_Lutrillia> <http://telicent.io/ontology/primaryName> "Lutrillia" .
<https://starwars.com#planet_Lutrillia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Lutrillia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#926cf0b6-4ab1-4bf0-886d-fbd6500c82a3> .
<https://starwars.com#planet_Lutrillia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J18> .

