Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Isiring> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Isiring> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_Isiring> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_Isiring> <http://www.w3.org/2000/01/rdf-schema#comment> "Isiring was an Outer Rim Territories world located in the Cassander sector. An ore-rich mining world, Isiring became a part of the domain known as the Cassandran Worlds, founded by the former businessman Cassander Tadrin during the reign of the Galactic Republic. When the Galactic Empire later divided the domain into subsectors, Isiring became the capital of the Tendrannan sector. The world was subsequently a part of the Pentastar Alignment and the Imperial Remnant. " .
<https://starwars.com#37e350ad-a53a-421f-9b0d-ab39978829fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Isiring> <http://telicent.io/ontology/primaryName> "Isiring" .
<https://starwars.com#37e350ad-a53a-421f-9b0d-ab39978829fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Isiring"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Isiring> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#37e350ad-a53a-421f-9b0d-ab39978829fc> .

