Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#65739945-a151-43ec-8b83-ed43bbf564ab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KeearaMajor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#65739945-a151-43ec-8b83-ed43bbf564ab> .
<https://starwars.com#planet_KeearaMajor> <http://telicent.io/ontology/primaryName> "Keeara Major" .
<https://starwars.com#planet_KeearaMajor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_KeearaMajor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_KeearaMajor> <http://www.w3.org/2000/01/rdf-schema#comment> "Keeara Major was a world that Sargo VenHalgon had once encountered some trouble. " .
<https://starwars.com#65739945-a151-43ec-8b83-ed43bbf564ab> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Keeara Major"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KeearaMajor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

