Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Manwess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#planet_Manwess> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#59fe8b58-0633-4d6b-9328-93bc2138c9f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Manwess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Manwess> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#59fe8b58-0633-4d6b-9328-93bc2138c9f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Manwess"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Manwess> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#59fe8b58-0633-4d6b-9328-93bc2138c9f2> .
<https://starwars.com#planet_Manwess> <http://telicent.io/ontology/primaryName> "Manwess" .

