Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rulaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Rulaar> <http://telicent.io/ontology/primaryName> "Rulaar" .
<https://starwars.com#planet_Rulaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rulaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Rulaar was a planet in the Mid Rim's Senex sector. The Rulaarian pleasure yacht existed in the galaxy by the time of the Galactic Civil War. " .
<https://starwars.com#3d121be6-9991-4197-af53-693da7eeac08> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rulaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d121be6-9991-4197-af53-693da7eeac08> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Rulaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3d121be6-9991-4197-af53-693da7eeac08> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rulaar"^^<http://www.w3.org/2001/XMLSchema#string> .

