Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Anzat> <http://www.w3.org/2000/01/rdf-schema#comment> "Anzat was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_Bryx> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Bryx> <http://telicent.io/ontology/primaryName> "Bryx" .
<https://starwars.com#planet_Anzat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Anzat> <http://telicent.io/ontology/primaryName> "Anzat" .
<https://starwars.com#planet_Anzat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#17373809-c25c-474e-b63b-34c116011248> .
<https://starwars.com#sector_Bryx> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#17373809-c25c-474e-b63b-34c116011248> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Anzat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#planet_Anzat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bryx> .
<https://starwars.com#17373809-c25c-474e-b63b-34c116011248> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anzat"^^<http://www.w3.org/2001/XMLSchema#string> .

