Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Belderone> <http://telicent.io/ontology/primaryName> "Belderone" .
<https://starwars.com#5bde3274-7ce9-4382-9da0-5768a84cbc5d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belderone"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Belderone> <http://www.w3.org/2000/01/rdf-schema#comment> "Belderone was a planet located in the Outer Rim Territories. In the early days of the Galactic Empire, members of the Imperial Army were reluctant to be stationed on Belderone, as it was understood that the troops stationed the farthest from Imperial Center were of least importance to the Empire's cause. As such, virtually any reassignment to the planet was viewed as punishment or demotion. " .
<https://starwars.com#planet_Belderone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#5bde3274-7ce9-4382-9da0-5768a84cbc5d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Belderone> <http://telicent.io/ontology/primaryName> "Belderone" .
<https://starwars.com#planet_Belderone> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5bde3274-7ce9-4382-9da0-5768a84cbc5d> .
<https://starwars.com#planet_Belderone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belderone> .
<https://starwars.com#sector_Belderone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Belderone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Belderone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

