Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kalsunor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#planet_Kalsunor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3784e1ef-68af-4649-81af-93cc542f9051> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3784e1ef-68af-4649-81af-93cc542f9051> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalsunor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Kalsunor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Kalsunor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalsunor> <http://telicent.io/ontology/primaryName> "Kalsunor" .
<https://starwars.com#planet_Kalsunor> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#3784e1ef-68af-4649-81af-93cc542f9051> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

