Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gandeal> <http://www.w3.org/2000/01/rdf-schema#comment> "Gandeal was a Planet in the Core Worlds and partner planet to the world of Fondor, a fortress world situated on the Corellian Trade Spine. " .
<https://starwars.com#678a122c-df40-43f3-9f3c-5b03b478615f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gandeal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gandeal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gandeal> <http://telicent.io/ontology/primaryName> "Gandeal" .
<https://starwars.com#planet_Gandeal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#678a122c-df40-43f3-9f3c-5b03b478615f> .
<https://starwars.com#planet_Gandeal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#678a122c-df40-43f3-9f3c-5b03b478615f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gandeal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .

