Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eriadu> <http://www.w3.org/2000/01/rdf-schema#comment> "Planet located in the galaxy's Outer Rim. Homeworld of Grand Moff Tarkin and his family." .
<https://starwars.com#planet_Eriadu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Eriadu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#planet_Eriadu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Seswenna> .
<https://starwars.com#sector_Seswenna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7e0baa24-e9f7-475a-9ca7-e52de4376235> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eriadu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Seswenna> <http://telicent.io/ontology/primaryName> "Seswenna" .
<https://starwars.com#sector_Seswenna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Eriadu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e0baa24-e9f7-475a-9ca7-e52de4376235> .
<https://starwars.com#7e0baa24-e9f7-475a-9ca7-e52de4376235> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Eriadu> <http://telicent.io/ontology/primaryName> "Eriadu" .

