Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Adari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_M9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Adari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Adari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Adari> <http://www.w3.org/2000/01/rdf-schema#comment> "Eventually, the Adarians expanded outward into the Adari system, and the discovery of hyperdrive technology led to the species controlling the entire Adari sector and joining the Galactic Republic millennium before the Battle of Yavin. Adari later signed a non-aggression treaty with the Galactic Empire and supplied it with raw materials necessary for starship construction, and the Rebel Alliance eventually established a presence on the planet. " .
<https://starwars.com#planet_Adari> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab7fdba6-1f74-4762-b4be-353b2bed316a> .
<https://starwars.com#18cd0ecd-e27d-4c7d-966b-399497b2aef2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Adari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#region_InnerRim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Adari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Adari> .
<https://starwars.com#18cd0ecd-e27d-4c7d-966b-399497b2aef2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#ab7fdba6-1f74-4762-b4be-353b2bed316a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Adari> <http://telicent.io/ontology/primaryName> "Adari" .
<https://starwars.com#grid_M9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M9> <http://telicent.io/ontology/primaryName> "M9" .
<https://starwars.com#region_InnerRim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#region_InnerRim> <http://telicent.io/ontology/primaryName> "Inner Rim" .
<https://starwars.com#planet_Adari> <http://telicent.io/ontology/primaryName> "Adari" .
<https://starwars.com#grid_M9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#18cd0ecd-e27d-4c7d-966b-399497b2aef2> .
<https://starwars.com#ab7fdba6-1f74-4762-b4be-353b2bed316a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Adari"^^<http://www.w3.org/2001/XMLSchema#string> .

