Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Qonto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Qonto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J3> .
<https://starwars.com#7467ae72-d827-4104-ba03-711a30e4341b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Qonto"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Qonto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Qonto> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7467ae72-d827-4104-ba03-711a30e4341b> .
<https://starwars.com#planet_Qonto> <http://telicent.io/ontology/primaryName> "Qonto" .
<https://starwars.com#7467ae72-d827-4104-ba03-711a30e4341b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Qonto> <http://www.w3.org/2000/01/rdf-schema#comment> "The Qonto were a sentient species from the Qonto system, which was located in Wild Space just outside the Braxant sector. Although generally not known for their perception, some exceptional Qonto had senses considerably sharper than the Human standard. During the Galactic Civil War, Lina Adonais was a Qonto space urchin who worked aboard the Kuari Princess, a giant luxury liner, while she traveled the galaxy. She considered joining the Alliance to Restore the Republic, and while on a tour of the Relgim Run, she encountered a group of Rebels disguised as Anomids. She immediately saw through their disguise and questioned them about what they were doing aboard the Princess. Adonais was also present on the cruise when it was attacked by pirates while passing through the Maelstrom. " .

