Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jaemus> <http://telicent.io/ontology/primaryName> "Jaemus" .
<https://starwars.com#planet_Jaemus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jaemus> <http://www.w3.org/2000/01/rdf-schema#comment> "Jaemus was an astronomical object in the galaxy's Outer Rim Territories. It was connected by hyperspace route to Muunilinst and Bescane. " .
<https://starwars.com#planet_Jaemus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Obtrexta> .
<https://starwars.com#200cd900-0446-47ee-8015-644492689432> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jaemus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jaemus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#200cd900-0446-47ee-8015-644492689432> .
<https://starwars.com#planet_Jaemus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#sector_Obtrexta> <http://telicent.io/ontology/primaryName> "Obtrexta" .
<https://starwars.com#sector_Obtrexta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Obtrexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#200cd900-0446-47ee-8015-644492689432> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

