Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_OrdSedra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .
<https://starwars.com#planet_OrdSedra> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Sedra was originally an Ordnance/Regional Depot located in the Clacis sector of the Outer Rim Territories. " .
<https://starwars.com#planet_OrdSedra> <http://telicent.io/ontology/primaryName> "Ord Sedra" .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdSedra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#2a27f334-f8c2-4202-ba8e-eadaef8db9e3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdSedra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2a27f334-f8c2-4202-ba8e-eadaef8db9e3> .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_OrdSedra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#2a27f334-f8c2-4202-ba8e-eadaef8db9e3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Sedra"^^<http://www.w3.org/2001/XMLSchema#string> .

