Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Romin> <http://telicent.io/ontology/primaryName> "Romin" .
<https://starwars.com#planet_Romin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4de4526d-592b-4ab9-ad54-3d1fb00004ae> .
<https://starwars.com#4de4526d-592b-4ab9-ad54-3d1fb00004ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Romin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Romintine> .
<https://starwars.com#4de4526d-592b-4ab9-ad54-3d1fb00004ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Romin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Romin> <http://www.w3.org/2000/01/rdf-schema#comment> "Romin was a small Mid Rim planet. It was the homeworld of the Romins. " .
<https://starwars.com#sector_Romintine> <http://telicent.io/ontology/primaryName> "Romintine" .
<https://starwars.com#sector_Romintine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Romintine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Romin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Romin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q8> .

