Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Veragi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Veragi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Veragi> <http://telicent.io/ontology/primaryName> "Veragi" .
<https://starwars.com#planet_Trassitan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0e198eb8-4682-4cdb-b9b1-fc78a4d9b487> .
<https://starwars.com#planet_Trassitan> <http://telicent.io/ontology/primaryName> "Trassitan" .
<https://starwars.com#planet_Trassitan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trassitan> <http://www.w3.org/2000/01/rdf-schema#comment> "Trassitan was an astronomical object located in the Trassitan system, a part of the Veragi sector in the New Territories portion of the Outer Rim Territories. The Veragi Trade Route hyperlane linked Trassitan to the Veragi system as well as the Dubrillion system in the Myto sector. " .
<https://starwars.com#planet_Trassitan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Veragi> .
<https://starwars.com#planet_Trassitan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L3> .
<https://starwars.com#0e198eb8-4682-4cdb-b9b1-fc78a4d9b487> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#0e198eb8-4682-4cdb-b9b1-fc78a4d9b487> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trassitan"^^<http://www.w3.org/2001/XMLSchema#string> .

