Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Basilisk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#353ca1d6-3d53-4b7a-a95d-70361e770493> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Basilisk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Basilisk> <http://www.w3.org/2000/01/rdf-schema#comment> "Basilisk was a Core world in the Arrowhead of the Slice, near Coruscant. " .
<https://starwars.com#planet_Basilisk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#353ca1d6-3d53-4b7a-a95d-70361e770493> .
<https://starwars.com#planet_Basilisk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Basilisk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#353ca1d6-3d53-4b7a-a95d-70361e770493> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Basilisk> <http://telicent.io/ontology/primaryName> "Basilisk" .

