Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#51bc56de-cb2a-4ea7-82da-0fc2245e5dcd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TeyrVulvarch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_TeyrVulvarch> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_TeyrVulvarch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#51bc56de-cb2a-4ea7-82da-0fc2245e5dcd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Teyr Vulvarch"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TeyrVulvarch> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#51bc56de-cb2a-4ea7-82da-0fc2245e5dcd> .
<https://starwars.com#planet_TeyrVulvarch> <http://telicent.io/ontology/primaryName> "Teyr Vulvarch" .
<https://starwars.com#planet_TeyrVulvarch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

