Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Messert> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Messert> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#09420ec7-4342-480d-b507-dd9af8746d9f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Messert> <http://telicent.io/ontology/primaryName> "Messert" .
<https://starwars.com#09420ec7-4342-480d-b507-dd9af8746d9f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Messert"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Messert> <http://www.w3.org/2000/01/rdf-schema#comment> "Messert was a world located in the Messert system that was the homeworld of the human Resistance pilot Seftin Vanik. " .
<https://starwars.com#planet_Messert> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#09420ec7-4342-480d-b507-dd9af8746d9f> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Messert> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .

