Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tamarin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_DravianStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Dravian Starport, also known as Dravian Station, was a space station located between the planets Cotellier and Syned. The station was a haven for smugglers because it was a great distance from any inhabited systems. Due to the types of people that frequented Dravian Starport, the space station eventually became full with different kinds of businesses, including casinos, hotels, and restaurants. Topatz Shipping and Skypath Industries were two such businesses. Jontz Freight was a shipping company which operated in the Dravian Starport. With a standard Class 1 hyperdrive, Dravian Spaceport was 16 days from Dreffon IV, 2 days from Ather, 23 days from Bazaar, and 5 days from Vlemoth Port. " .
<https://starwars.com#grid_N18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#47856566-1e0f-47f8-be27-802ab8eae777> .
<https://starwars.com#planet_DravianStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f2e8c0f9-a065-453b-92be-65de978978b8> .
<https://starwars.com#planet_DravianStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tamarin> .
<https://starwars.com#grid_N18> <http://telicent.io/ontology/primaryName> "N18" .
<https://starwars.com#f2e8c0f9-a065-453b-92be-65de978978b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dravian Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#47856566-1e0f-47f8-be27-802ab8eae777> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_DravianStation> <http://telicent.io/ontology/primaryName> "Dravian Station" .
<https://starwars.com#47856566-1e0f-47f8-be27-802ab8eae777> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_DravianStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N18> .
<https://starwars.com#planet_DravianStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_N18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#f2e8c0f9-a065-453b-92be-65de978978b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tamarin> <http://telicent.io/ontology/primaryName> "Tamarin" .
<https://starwars.com#sector_Tamarin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

