Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Halori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Velmor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halori> .
<https://starwars.com#sector_Halori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Velmor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Velmor> <http://telicent.io/ontology/primaryName> "Velmor" .
<https://starwars.com#planet_Velmor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b9e850db-5c17-4a96-81f1-9f6a9a88f4f9> .
<https://starwars.com#planet_Velmor> <http://www.w3.org/2000/01/rdf-schema#comment> "Velmor was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#b9e850db-5c17-4a96-81f1-9f6a9a88f4f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b9e850db-5c17-4a96-81f1-9f6a9a88f4f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Velmor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Velmor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P7> .
<https://starwars.com#sector_Halori> <http://telicent.io/ontology/primaryName> "Halori" .

