Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#fc1acaa9-cca6-415e-bbfd-73dddfb36dea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sernpidal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalonbian> .
<https://starwars.com#planet_Sernpidal> <http://telicent.io/ontology/primaryName> "Sernpidal" .
<https://starwars.com#fc1acaa9-cca6-415e-bbfd-73dddfb36dea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sernpidal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sernpidal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L3> .
<https://starwars.com#sector_Dalonbian> <http://telicent.io/ontology/primaryName> "Dalonbian" .
<https://starwars.com#planet_Sernpidal> <http://www.w3.org/2000/01/rdf-schema#comment> "Sernpidal was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Dalonbian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Dalonbian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sernpidal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sernpidal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fc1acaa9-cca6-415e-bbfd-73dddfb36dea> .

