Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hast> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hast> <http://telicent.io/ontology/primaryName> "Hast" .
<https://starwars.com#planet_Hast> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4932fdf7-acd9-4e86-b0b7-7eadb9fc966d> .
<https://starwars.com#4932fdf7-acd9-4e86-b0b7-7eadb9fc966d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hast> <http://www.w3.org/2000/01/rdf-schema#comment> "Hast was a planet in the galaxy. It  was the site of a secret New Republic shipyard that came under Imperial attack. " .
<https://starwars.com#planet_Hast> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Hast> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#4932fdf7-acd9-4e86-b0b7-7eadb9fc966d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hast"^^<http://www.w3.org/2001/XMLSchema#string> .

