Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Periphery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_AfEl> <http://www.w3.org/2000/01/rdf-schema#comment> "Af'El was the homeworld to the Defel, who dwelt in underground cities. It was a high-gravity planet with no ozone layer, and it orbited the ultraviolet supergiant Ka'Dedus. Because of the lack of ozone, ultraviolet light passed freely to the surface, while other light wavelengths were blocked by the heavy gases in the planet's atmosphere. Thus, all animals on Af'El could only see in ultraviolet light ranges. A main export of the planet was the metal meleenium used in durasteel. " .
<https://starwars.com#planet_AfEl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Periphery> .
<https://starwars.com#grid_S8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_AfEl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cef3c9a7-368c-4bd9-ab1f-c5330f22a90f> .
<https://starwars.com#planet_AfEl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#planet_AfEl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_S8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b866a631-09a0-410b-961b-fcc66da8a534> .
<https://starwars.com#grid_S8> <http://telicent.io/ontology/primaryName> "S8" .
<https://starwars.com#cef3c9a7-368c-4bd9-ab1f-c5330f22a90f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_S8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#cef3c9a7-368c-4bd9-ab1f-c5330f22a90f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Af'El"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Periphery> <http://telicent.io/ontology/primaryName> "Periphery" .
<https://starwars.com#sector_Periphery> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AfEl> <http://telicent.io/ontology/primaryName> "Af'El" .
<https://starwars.com#b866a631-09a0-410b-961b-fcc66da8a534> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#b866a631-09a0-410b-961b-fcc66da8a534> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S8"^^<http://www.w3.org/2001/XMLSchema#string> .

