Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7addf077-7cc7-4951-9ef4-741f2ef66004> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aldraig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aldraig> <http://telicent.io/ontology/primaryName> "Aldraig" .
<https://starwars.com#planet_Aldraig> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7addf077-7cc7-4951-9ef4-741f2ef66004> .
<https://starwars.com#planet_Aldraig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Aldraig> <http://www.w3.org/2000/01/rdf-schema#comment> "Aldraig was an astronomical object in the Alderaan sector of the Core Worlds. During the early rebellion against the Galactic Empire, Senator Bail Organa of the Imperial Senate attempted to cover up the theft of a UT-60D transport shipment by having an Aldraig data clerk mistakenly route a shipment of U-wings to Coruscant through Baylagon. " .
<https://starwars.com#planet_Aldraig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#7addf077-7cc7-4951-9ef4-741f2ef66004> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aldraig"^^<http://www.w3.org/2001/XMLSchema#string> .

