Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vohai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O18> .
<https://starwars.com#5d8faf2b-9d9d-4174-8ac5-4b826c8248c9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Parmel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vohai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d8faf2b-9d9d-4174-8ac5-4b826c8248c9> .
<https://starwars.com#sector_Parmel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5d8faf2b-9d9d-4174-8ac5-4b826c8248c9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vohai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vohai> <http://telicent.io/ontology/primaryName> "Vohai" .
<https://starwars.com#sector_Parmel> <http://telicent.io/ontology/primaryName> "Parmel" .
<https://starwars.com#planet_Vohai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Parmel> .
<https://starwars.com#planet_Vohai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vohai> <http://www.w3.org/2000/01/rdf-schema#comment> "Vohai was an astronomical object in the galaxy's Outer Rim Territories. " .

