Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pasmin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#482da80d-920c-4fdb-93b3-05615f7cad7b> .
<https://starwars.com#planet_Pasmin> <http://telicent.io/ontology/primaryName> "Pasmin" .
<https://starwars.com#planet_Pasmin> <http://www.w3.org/2000/01/rdf-schema#comment> "Pasmin was a planet located within the Outer Rim Territories. One of the original member-worlds of the Kingdom of Cron, it was absorbed into Xim's Empire. After the fall of the empire in 25,100 BBY, it would eventually join the Galactic Republic. It would continue to thrive as a world, eventually joining the Cronese Mandate after the rise of the Galactic Empire. Known for its weavers, they created extremely light, yet warm, blankets and clothes. " .
<https://starwars.com#482da80d-920c-4fdb-93b3-05615f7cad7b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#482da80d-920c-4fdb-93b3-05615f7cad7b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pasmin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CroneseMandate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pasmin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_CroneseMandate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pasmin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CroneseMandate> <http://telicent.io/ontology/primaryName> "Cronese Mandate" .
<https://starwars.com#planet_Pasmin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CroneseMandate> .

