Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gerrard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Gerrard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Gerrard> <http://www.w3.org/2000/01/rdf-schema#comment> "Gerrard was a male Human who served as a captain in the Imperial Military of the reconstituted Sith Empire during the Cold War with the Galactic Republic. A dark-skinned Human with black eyes and black hair cut in a series of stripes, Gerrard was assigned to Watcher One of Imperial Intelligence in the search for the Republic scientist Doctor Nasan Godera on the planet Taris in 3643 BBY. He carried a blaster rifle in combat and wore the standard armor for Imperial soldiers. However, Captain Gerrard and many of his men were killed on a raid on one of Godera's research facilities when a young Jedi Knight, who was also looking for Godera, encountered the Imperials in the subterranean laboratory. " .
<https://starwars.com#planet_Gerrard> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#adb73d72-9cda-4f44-b5e7-e28e658c19e1> .
<https://starwars.com#planet_Gerrard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gerrard> <http://telicent.io/ontology/primaryName> "Gerrard" .
<https://starwars.com#adb73d72-9cda-4f44-b5e7-e28e658c19e1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gerrard"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#adb73d72-9cda-4f44-b5e7-e28e658c19e1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

