Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Rocantor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_RainosCLuster> <http://telicent.io/ontology/primaryName> "Rainos CLuster" .
<https://starwars.com#sector_Rocantor> <http://telicent.io/ontology/primaryName> "Rocantor" .
<https://starwars.com#9788f397-45bf-4e75-8198-4f203fcefd17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RainosCLuster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RainosCLuster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#sector_Rocantor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9788f397-45bf-4e75-8198-4f203fcefd17> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rainos CLuster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_RainosCLuster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rocantor> .
<https://starwars.com#planet_RainosCLuster> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_RainosCLuster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9788f397-45bf-4e75-8198-4f203fcefd17> .

