Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ringneldia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#40b3f205-76cc-414e-8ebc-e639072930ba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ringneldia> <http://telicent.io/ontology/primaryName> "Ringneldia" .
<https://starwars.com#40b3f205-76cc-414e-8ebc-e639072930ba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ringneldia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ringneldia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#40b3f205-76cc-414e-8ebc-e639072930ba> .
<https://starwars.com#planet_Ringneldia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Ringneldia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Ringneldia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

