Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5a702498-1bb6-4802-89de-69c78a726a1a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#5a702498-1bb6-4802-89de-69c78a726a1a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thearterra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thearterra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Thearterra> <http://telicent.io/ontology/primaryName> "Thearterra" .
<https://starwars.com#planet_Thearterra> <http://www.w3.org/2000/01/rdf-schema#comment> "Thearterra was a terrestrial astronomical object located in the Unknown Regions within the Chiss sentient species' government of the Chiss Ascendancy. A mining field located at Thearterra was opened around 19 BBY and was sought over by the Chiss Mitth and Ufsa families. " .
<https://starwars.com#planet_Thearterra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5a702498-1bb6-4802-89de-69c78a726a1a> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Thearterra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thearterra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .

