Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Paramatan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Paramatan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Paramatan> <http://telicent.io/ontology/primaryName> "Paramatan" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Paramatan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Paramatan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0cdd6ea-d9d4-4a7a-9bdf-cc6f9e241019> .
<https://starwars.com#a0cdd6ea-d9d4-4a7a-9bdf-cc6f9e241019> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Paramatan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#a0cdd6ea-d9d4-4a7a-9bdf-cc6f9e241019> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Paramatan> <http://www.w3.org/2000/01/rdf-schema#comment> "Paramatan was a primitive terrestrial world located in the Mid Rim's Senex sector. Its surface featured forests and jungles as well as plains and oceans. The world's fauna included birds, reptiles, and great oopiks, a species having both avian and reptilian traits. The oopiks were a relic species of flightless creatures that made their home in the Paramatan fruit trees of the continent of Grxy. Paramatan was discovered by scouts of the aristocratic House Elegin and eventually came to be used by the nobles of the Senex-Juvex region as a destination for hunting safaris. " .

