Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Iope> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iope> <http://telicent.io/ontology/primaryName> "Iope" .
<https://starwars.com#planet_Iope> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7b08beb8-3b64-4659-91a3-11722318c104> .
<https://starwars.com#planet_Iope> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#7b08beb8-3b64-4659-91a3-11722318c104> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7b08beb8-3b64-4659-91a3-11722318c104> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iope"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iope> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Iope> <http://www.w3.org/2000/01/rdf-schema#comment> "Iope was the third moon of the planet Rinn, in the Baxel sector. It was here that the assassin X-7 hired a team of mercenary pilots to hunt down and kill Luke Skywalker. " .

