Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_AnxMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .
<https://starwars.com#planet_AnxMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a3ca07e0-2bcf-46cb-97f2-51e767974e4f> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_AnxMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#a24144c8-6c30-434d-8ac4-258c72e70728> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L4> <http://telicent.io/ontology/primaryName> "L4" .
<https://starwars.com#grid_L4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_L4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#a24144c8-6c30-434d-8ac4-258c72e70728> .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AnxMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Anx Minor was a location where a massacre occurred during the Galactic Civil War. Around 5 ABY, the massacre was among several events reviewed by New Republic Intelligence agent Caern Adan and Alphabet Squadron pilot Yrica Quell in search of the Galactic Empire's 204th Imperial Fighter Wing after the New Republic Intelligence flagged it as possible 204th activity. Quell felt that the massacre at Anx Minor shared similarities with the fighter wing's raid on Beauchen, but the location was distant from other possible 204th sightings on her and Adan's map. " .
<https://starwars.com#a3ca07e0-2bcf-46cb-97f2-51e767974e4f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anx Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a24144c8-6c30-434d-8ac4-258c72e70728> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_AnxMinor> <http://telicent.io/ontology/primaryName> "Anx Minor" .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#planet_AnxMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#a3ca07e0-2bcf-46cb-97f2-51e767974e4f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

