Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chenowei> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#6a0b0ea4-abb5-4d13-aa03-ea370deccba9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Chenowei> <http://www.w3.org/2000/01/rdf-schema#comment> "Chenowei was a planet in the Gordian Reach of the Outer Rim. " .
<https://starwars.com#planet_Chenowei> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chenowei> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Chenowei> <http://telicent.io/ontology/primaryName> "Chenowei" .
<https://starwars.com#6a0b0ea4-abb5-4d13-aa03-ea370deccba9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chenowei"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chenowei> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a0b0ea4-abb5-4d13-aa03-ea370deccba9> .

