Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Garos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Garos> <http://www.w3.org/2000/01/rdf-schema#comment> "Garos was an astronomical object located in the galaxy's Mid Rim. It was the location of a university and Imperial facility five years after the Clone Wars. " .
<https://starwars.com#sector_Msst> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#82cc6ad8-ebc2-47b8-8d41-e86bd8f97dcb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Garos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Msst> .
<https://starwars.com#planet_Garos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#82cc6ad8-ebc2-47b8-8d41-e86bd8f97dcb> .
<https://starwars.com#sector_Msst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#82cc6ad8-ebc2-47b8-8d41-e86bd8f97dcb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Garos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Garos> <http://telicent.io/ontology/primaryName> "Garos" .
<https://starwars.com#sector_Msst> <http://telicent.io/ontology/primaryName> "Msst" .
<https://starwars.com#planet_Garos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P7> .

