Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PerithalVI> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2c3d61a5-4d5b-491a-8e70-8fea488a170b> .
<https://starwars.com#planet_PerithalVI> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PerithalVI> <http://www.w3.org/2000/01/rdf-schema#comment> "Perithal VI was a planet in the Perithal system of the Inner Rim. It was the location of a branch campus of the Institute of Starship Engineers. " .
<https://starwars.com#planet_PerithalVI> <http://telicent.io/ontology/primaryName> "Perithal VI" .
<https://starwars.com#2c3d61a5-4d5b-491a-8e70-8fea488a170b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Perithal VI"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PerithalVI> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_PerithalVI> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#2c3d61a5-4d5b-491a-8e70-8fea488a170b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

