Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lexrul> <http://www.w3.org/2000/01/rdf-schema#comment> "Lexrul was a heavily industrialized planet in the galaxy's Mid Rim. Orson Callan Krennic was born in Sativran City on the planet in 51 BBY. " .
<https://starwars.com#planet_Lexrul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#5b5b9e25-f787-4d60-9618-905a8ab58b51> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lexrul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lexrul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5b5b9e25-f787-4d60-9618-905a8ab58b51> .
<https://starwars.com#planet_Lexrul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trax> .
<https://starwars.com#planet_Lexrul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Trax> <http://telicent.io/ontology/primaryName> "Trax" .
<https://starwars.com#sector_Trax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Lexrul> <http://telicent.io/ontology/primaryName> "Lexrul" .
<https://starwars.com#5b5b9e25-f787-4d60-9618-905a8ab58b51> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Trax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

