Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#bdc1227f-66ed-4229-9cb9-28b74e4242bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Coruscant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Coruscant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bdc1227f-66ed-4229-9cb9-28b74e4242bd> .
<https://starwars.com#planet_Coruscant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Coruscant> <http://www.w3.org/2000/01/rdf-schema#comment> "Cosmopolitan urban world consisting of one planet-wide city. Coruscant is situated in the heart of the Star Wars galaxy with a population of over one trillion, and is Governmental center of the Galactic Republic and later the Galactic Empire." .
<https://starwars.com#planet_Coruscant> <http://telicent.io/ontology/primaryName> "Coruscant" .
<https://starwars.com#planet_Coruscant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bdc1227f-66ed-4229-9cb9-28b74e4242bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

