Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Buchich> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#eea4ffbe-9001-44db-8bc3-3cc6cdff5170> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Buchich> <http://telicent.io/ontology/primaryName> "Buchich" .
<https://starwars.com#grid_U6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Buchich> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#608ff02d-796c-4867-8224-a6a9b92571a8> .
<https://starwars.com#eea4ffbe-9001-44db-8bc3-3cc6cdff5170> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_U6> <http://telicent.io/ontology/primaryName> "U6" .
<https://starwars.com#planet_Buchich> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#608ff02d-796c-4867-8224-a6a9b92571a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_U6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Buchich> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Buchich> <http://www.w3.org/2000/01/rdf-schema#comment> "Buchich was a planet in the Buchich system in the Outer Rim Territories. Part of the Calamari sector, the Quarren species colonized the planet for mining resources to keep up with the Mon Calamari's work in shipbuilding. " .
<https://starwars.com#608ff02d-796c-4867-8224-a6a9b92571a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Buchich"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_U6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#eea4ffbe-9001-44db-8bc3-3cc6cdff5170> .

