Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thustra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#planet_Thustra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c1078eb8-f761-4028-aba3-22b31698d905> .
<https://starwars.com#planet_Thustra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thustra> <http://www.w3.org/2000/01/rdf-schema#comment> "Thustra was a planet located in the Thustra system of the Expansion Region. Sephi flyers came from here. " .
<https://starwars.com#c1078eb8-f761-4028-aba3-22b31698d905> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thustra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sumitra> <http://telicent.io/ontology/primaryName> "Sumitra" .
<https://starwars.com#sector_Sumitra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Thustra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sumitra> .
<https://starwars.com#planet_Thustra> <http://telicent.io/ontology/primaryName> "Thustra" .
<https://starwars.com#sector_Sumitra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c1078eb8-f761-4028-aba3-22b31698d905> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

