Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Korfo> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Korfo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0c9839bf-4c46-422e-ab90-7e0342d270ae> .
<https://starwars.com#planet_Korfo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Korfo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0c9839bf-4c46-422e-ab90-7e0342d270ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Korfo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Korfo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#0c9839bf-4c46-422e-ab90-7e0342d270ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Korfo> <http://telicent.io/ontology/primaryName> "Korfo" .

