Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mandell> <http://www.w3.org/2000/01/rdf-schema#comment> "Mandell was a Bothan colony world. It was once devastated by drought, requiring grain shipments from Bothawui. Unfortunately, these shipments contained radarks, which infested the planet. " .
<https://starwars.com#planet_Mandell> <http://telicent.io/ontology/primaryName> "Mandell" .
<https://starwars.com#sector_BothanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Mandell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#2cbdd95f-7921-460d-bce1-b2270aaa4fad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2cbdd95f-7921-460d-bce1-b2270aaa4fad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mandell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_BothanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mandell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BothanSpace> .
<https://starwars.com#planet_Mandell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_BothanSpace> <http://telicent.io/ontology/primaryName> "Bothan Space" .
<https://starwars.com#planet_Mandell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2cbdd95f-7921-460d-bce1-b2270aaa4fad> .

