Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b65ac81d-11f6-4abe-ba19-f3f0c5e39cfc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hijarna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Orus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hijarna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Orus> .
<https://starwars.com#planet_Hijarna> <http://www.w3.org/2000/01/rdf-schema#comment> "Hijarna was a planet that was located near or in Orus sector, within the Inner Rim of the galaxy. The planet was once part of the Rakatan Infinite Empire, and was discovered by the Fifth Alderaanian Expedition, which also discovered the one thousand-year old remains of an ancient civilization. The civilization had fallen to alien invaders. Their last stronghold was the Fortress of Hijarna, made of what was dubbed Hijarna stone, similar to the Hand of Thrawn on Nirauan. The Fortress was used as a rendezvous by Talon Karrde's organization. Karrde assembled the leaders of the Smugglers' Alliance at the Fortress to plan locating the crystal gravfield trap Thrawn had set for the New Republic. At the assembly, Niles Ferrier was revealed as a traitor. " .
<https://starwars.com#planet_Hijarna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b65ac81d-11f6-4abe-ba19-f3f0c5e39cfc> .
<https://starwars.com#planet_Hijarna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#b65ac81d-11f6-4abe-ba19-f3f0c5e39cfc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hijarna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hijarna> <http://telicent.io/ontology/primaryName> "Hijarna" .
<https://starwars.com#sector_Orus> <http://telicent.io/ontology/primaryName> "Orus" .
<https://starwars.com#sector_Orus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

