Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nimia> <http://www.w3.org/2000/01/rdf-schema#comment> "Nimia was a planet located in the Hutt Space between Klatooine and Yoribuunt. It was located near the Si'Klaata Cluster. A lackluster industrial world, Nimia was occasionally used as a meeting place between Hutt servants and outlanders who had failed to attract much favor with the Hutts. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nimia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#232d7bb2-2d35-427b-ab9f-c5bb2b1878bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nimia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nimia> <http://telicent.io/ontology/primaryName> "Nimia" .
<https://starwars.com#232d7bb2-2d35-427b-ab9f-c5bb2b1878bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nimia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nimia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#232d7bb2-2d35-427b-ab9f-c5bb2b1878bd> .
<https://starwars.com#planet_Nimia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

