Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kushibah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kushibah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_Kushibah> <http://www.w3.org/2000/01/rdf-schema#comment> "Kushibah was a planet in the Gordian Reach sector of the Outer Rim Territories. It was home to the primitive lagomorph Kushiban species, most notably the Jedi Master Ikrit. The planet had no cities and limited technology. " .
<https://starwars.com#planet_Kushibah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7c47f4f8-5280-4120-8ad2-0210cc7ee0dc> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7c47f4f8-5280-4120-8ad2-0210cc7ee0dc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7c47f4f8-5280-4120-8ad2-0210cc7ee0dc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kushibah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kushibah> <http://telicent.io/ontology/primaryName> "Kushibah" .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kushibah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .

