Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ropagi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c22a8c2a-13a2-433d-ae39-d7f702e0789f> .
<https://starwars.com#planet_Ropagi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kira> .
<https://starwars.com#planet_Ropagi> <http://telicent.io/ontology/primaryName> "Ropagi" .
<https://starwars.com#sector_Kira> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Ropagi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#c22a8c2a-13a2-433d-ae39-d7f702e0789f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ropagi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kira> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kira> <http://telicent.io/ontology/primaryName> "Kira" .
<https://starwars.com#planet_Ropagi> <http://www.w3.org/2000/01/rdf-schema#comment> "Ropagi was a yellow-white F-class main sequence star in the galaxy. " .
<https://starwars.com#c22a8c2a-13a2-433d-ae39-d7f702e0789f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ropagi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

