Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Hilo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Hilo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#sector_Hilo> <http://telicent.io/ontology/primaryName> "Hilo" .
<https://starwars.com#planet_Hilo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hilo> .
<https://starwars.com#planet_Hilo> <http://telicent.io/ontology/primaryName> "Hilo" .
<https://starwars.com#259b4828-1404-4081-ac56-f8766db2a157> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hilo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hilo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#259b4828-1404-4081-ac56-f8766db2a157> .
<https://starwars.com#sector_Hilo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hilo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#259b4828-1404-4081-ac56-f8766db2a157> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hilo> <http://www.w3.org/2000/01/rdf-schema#comment> "Hilo was a planet located in the Hilo sector of the Expansion Region. " .

