Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_H7> <http://telicent.io/ontology/primaryName> "H7" .
<https://starwars.com#1f8732b8-fe39-4bdf-b2c7-a8fdef408a06> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TheRedoubt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#grid_H7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_TheRedoubt> <http://www.w3.org/2000/01/rdf-schema#comment> "The Redoubt was an astronomical object located in Wild Space, in grid square H-7 of the Standard Galactic Grid. " .
<https://starwars.com#fce2c7f8-ec3a-48b8-aba9-c2c7e2780bf6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Redoubt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TheRedoubt> <http://telicent.io/ontology/primaryName> "The Redoubt" .
<https://starwars.com#grid_H7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_H7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1f8732b8-fe39-4bdf-b2c7-a8fdef408a06> .
<https://starwars.com#1f8732b8-fe39-4bdf-b2c7-a8fdef408a06> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_TheRedoubt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H7> .
<https://starwars.com#planet_TheRedoubt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_TheRedoubt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fce2c7f8-ec3a-48b8-aba9-c2c7e2780bf6> .
<https://starwars.com#fce2c7f8-ec3a-48b8-aba9-c2c7e2780bf6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

