Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ariarch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dalron> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Dalron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2a56568a-30a9-4d53-96e6-4ce6facf4557> .
<https://starwars.com#2a56568a-30a9-4d53-96e6-4ce6facf4557> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2a56568a-30a9-4d53-96e6-4ce6facf4557> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dalron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ariarch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Ariarch> <http://telicent.io/ontology/primaryName> "Ariarch" .
<https://starwars.com#planet_Dalron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#planet_Dalron> <http://telicent.io/ontology/primaryName> "Dalron" .
<https://starwars.com#planet_Dalron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dalron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ariarch> .

