Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Endocray> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Argovia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5e72bc5a-23ac-42ab-a4b5-a361cda1f544> .
<https://starwars.com#sector_Endocray> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_S14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Argovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Endocray> .
<https://starwars.com#planet_Argovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S14> .
<https://starwars.com#planet_Argovia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Argovia> <http://www.w3.org/2000/01/rdf-schema#comment> "Argovia was a planet of stormy, misty, marshy wetlands in the Endocray sector, rich in minerals and ores. It was the location of an Imperial sensor network complex that analyzed data from thousands of sensor buoys, ships, and probe droids in the sector. To protect both the sensor complex and the valuable ore, the mining companies and the Empire mutually restricted any non-personnel from immigrating to the planet. " .
<https://starwars.com#grid_S14> <http://telicent.io/ontology/primaryName> "S14" .
<https://starwars.com#1179a108-9169-4d90-be8f-05d2900f878a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5e72bc5a-23ac-42ab-a4b5-a361cda1f544> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Endocray> <http://telicent.io/ontology/primaryName> "Endocray" .
<https://starwars.com#grid_S14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#5e72bc5a-23ac-42ab-a4b5-a361cda1f544> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Argovia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Argovia> <http://telicent.io/ontology/primaryName> "Argovia" .
<https://starwars.com#1179a108-9169-4d90-be8f-05d2900f878a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_S14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1179a108-9169-4d90-be8f-05d2900f878a> .

