Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mijos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Mijos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mijos> <http://telicent.io/ontology/primaryName> "Mijos" .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Mijos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#18803782-6623-4a16-b941-817ee40890db> .
<https://starwars.com#planet_Mijos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#18803782-6623-4a16-b941-817ee40890db> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mijos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mijos> <http://www.w3.org/2000/01/rdf-schema#comment> "Assumption ends here." .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#18803782-6623-4a16-b941-817ee40890db> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

