Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#28394d75-8ee4-4d8f-b1a7-70c073fbb534> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#28394d75-8ee4-4d8f-b1a7-70c073fbb534> <http://ies.data.gov.uk/ontology/ies4#representationValue> "OHS3842-03"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_OHS3842-03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OHS3842-03> <http://www.w3.org/2000/01/rdf-schema#comment> "OHS3842-03 was a planet located within the Outer Rim Territories. Originally known as Astigone, it was absorbed into Xim's Empire as he expanded his borders from the Kingdom of Cron. " .
<https://starwars.com#planet_OHS3842-03> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#28394d75-8ee4-4d8f-b1a7-70c073fbb534> .
<https://starwars.com#planet_OHS3842-03> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#planet_OHS3842-03> <http://telicent.io/ontology/primaryName> "OHS3842-03" .
<https://starwars.com#planet_OHS3842-03> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .

