Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#354ad778-8d1f-4e89-babe-fec9adef6335> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kimm Aurek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KimmAurek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#354ad778-8d1f-4e89-babe-fec9adef6335> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KimmAurek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#354ad778-8d1f-4e89-babe-fec9adef6335> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KimmAurek> <http://www.w3.org/2000/01/rdf-schema#comment> "Kimm Aurek was a planet located in the Kimm Aurek system of the Juvex sector, in the Mid Rim of the galaxy. It was one of a trio of dingy industrial worlds belonging to House Sreethyn. " .
<https://starwars.com#planet_KimmAurek> <http://telicent.io/ontology/primaryName> "Kimm Aurek" .
<https://starwars.com#planet_KimmAurek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_KimmAurek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

