Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TolAmn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c5892c08-49b5-467f-a6d9-4c01dbfa9978> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tol Amn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#c5892c08-49b5-467f-a6d9-4c01dbfa9978> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TolAmn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_TolAmn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c5892c08-49b5-467f-a6d9-4c01dbfa9978> .
<https://starwars.com#planet_TolAmn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R11> .
<https://starwars.com#planet_TolAmn> <http://www.w3.org/2000/01/rdf-schema#comment> "Tol Amn was a murky, stormy planet that was located within the star system of the same name, in the Hutt Space region of the galaxy. The planet lay on the hyperlane called the Oktos Route that connected it both to the planet Toydaria and the hyperspace route known as the Trax Tube. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_TolAmn> <http://telicent.io/ontology/primaryName> "Tol Amn" .

