Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kanz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KolHuro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kanz> .
<https://starwars.com#planet_KolHuro> <http://www.w3.org/2000/01/rdf-schema#comment> "Kol Huro was a terrestrial astronomical object. The journalist Caern Adan was detained and imprisoned by the Galactic Empire after he published a story about droid production forecasts on Kol Huro. " .
<https://starwars.com#planet_KolHuro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8074e51d-3b8e-4287-a598-90ffc5b62aee> .
<https://starwars.com#planet_KolHuro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kanz> <http://telicent.io/ontology/primaryName> "Kanz" .
<https://starwars.com#planet_KolHuro> <http://telicent.io/ontology/primaryName> "Kol Huro" .
<https://starwars.com#sector_Kanz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#8074e51d-3b8e-4287-a598-90ffc5b62aee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kol Huro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8074e51d-3b8e-4287-a598-90ffc5b62aee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KolHuro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .

