Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#28d7f145-3b79-4072-a8a8-5887c9d96369> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Denab"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Denab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#28d7f145-3b79-4072-a8a8-5887c9d96369> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Denab> <http://telicent.io/ontology/primaryName> "Denab" .
<https://starwars.com#planet_Denab> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#sector_Sluis> <http://telicent.io/ontology/primaryName> "Sluis" .
<https://starwars.com#planet_Denab> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#28d7f145-3b79-4072-a8a8-5887c9d96369> .
<https://starwars.com#planet_Denab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sluis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Sluis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Denab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sluis> .

