Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3ace05e6-88f5-411a-bb18-bf2704340cfc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Alderaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3ace05e6-88f5-411a-bb18-bf2704340cfc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewAlderaan> <http://www.w3.org/2000/01/rdf-schema#comment> "New Alderaan was a safeworld that the Alderaanian survivor Janray Tessime spent time on during the Galactic Civil War tending to civilian populations. " .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_NewAlderaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#planet_NewAlderaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3ace05e6-88f5-411a-bb18-bf2704340cfc> .
<https://starwars.com#planet_NewAlderaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_NewAlderaan> <http://telicent.io/ontology/primaryName> "New Alderaan" .
<https://starwars.com#planet_NewAlderaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .

