Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Drearia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#90c92eac-f6ad-4285-a4d7-4ceffbb4cd49> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drearia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Drearia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#planet_Drearia> <http://telicent.io/ontology/primaryName> "Drearia" .
<https://starwars.com#planet_Drearia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#90c92eac-f6ad-4285-a4d7-4ceffbb4cd49> .
<https://starwars.com#planet_Drearia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#90c92eac-f6ad-4285-a4d7-4ceffbb4cd49> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Drearia> <http://www.w3.org/2000/01/rdf-schema#comment> "Drearia was an astronomical object located in the regions known as the Inner Rim and the Interior. It was also situated in grid square L-8 of the Standard Galactic Grid, and the super-hyperroute known as the Hydian Way linked Drearia to the Paqualis system as well as the world Champala. Drearia shared its name with the company Drearian Defense Conglomerate. " .

