Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Douglas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Douglas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f49b422-6bb7-4518-8a6f-8279f04160c4> .
<https://starwars.com#planet_Douglas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4f49b422-6bb7-4518-8a6f-8279f04160c4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Douglas> <http://telicent.io/ontology/primaryName> "Douglas" .
<https://starwars.com#planet_Douglas> <http://www.w3.org/2000/01/rdf-schema#comment> "Douglas III, the third planet of the remote Douglas system, was a member of the Centrality region of the Outer Rim Territories. Far from the Galactic Core and of little interest to the rest of the galaxy, Douglas III was made famous by the game hunter Mendel Douglas, who failed to return from the planet during a quest to acquire the hide of Douglas III's elusive native jackelope. The planet later attracted pirates and black-marketeers." .
<https://starwars.com#planet_Douglas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4f49b422-6bb7-4518-8a6f-8279f04160c4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Douglas"^^<http://www.w3.org/2001/XMLSchema#string> .

