Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_CritonsPoint> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#5f6537a5-7c46-4cfe-8c3f-be6c2402c2b3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5f6537a5-7c46-4cfe-8c3f-be6c2402c2b3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Criton's Point"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Myto> <http://telicent.io/ontology/primaryName> "Myto" .
<https://starwars.com#sector_Myto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_CritonsPoint> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5f6537a5-7c46-4cfe-8c3f-be6c2402c2b3> .
<https://starwars.com#sector_Myto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_CritonsPoint> <http://www.w3.org/2000/01/rdf-schema#comment> "Criton's Point was a quarantined planet in the Myto sector. Its Library of Xer was built 26,000 BBY. Not much was known of the planet, but many historians had expressed interest in gaining access to the Imperial-controlled library. " .
<https://starwars.com#planet_CritonsPoint> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Myto> .
<https://starwars.com#planet_CritonsPoint> <http://telicent.io/ontology/primaryName> "Criton's Point" .
<https://starwars.com#planet_CritonsPoint> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

