Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7fb8d875-cb42-4368-afc5-583f56ec42b1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Nars> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Nars> <http://telicent.io/ontology/primaryName> "Nars" .
<https://starwars.com#7fb8d875-cb42-4368-afc5-583f56ec42b1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nars"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nars> <http://www.w3.org/2000/01/rdf-schema#comment> "Nars was a terrestrial planet located in the Nars system of the Senex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. A hyperlane linked it to the Knores system. " .
<https://starwars.com#planet_Nars> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7fb8d875-cb42-4368-afc5-583f56ec42b1> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nars> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Nars> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

