Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ossus> <http://www.w3.org/2000/01/rdf-schema#comment> "According to legend, what few Jedi survived the blast banded together to survive. Over millennia, those humans became tribal Ysanna, a group of near-humans with a high percentage of Force-sensitivity among them, who regarded it as atavistic magic. The other humans on the planet were considered a minority population. " .
<https://starwars.com#aecb908f-9a1f-47d1-a41a-4c9f86ba2128> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ossus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ossus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aecb908f-9a1f-47d1-a41a-4c9f86ba2128> .
<https://starwars.com#sector_Auril> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ossus> <http://telicent.io/ontology/primaryName> "Ossus" .
<https://starwars.com#sector_Auril> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ossus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ossus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#aecb908f-9a1f-47d1-a41a-4c9f86ba2128> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Auril> <http://telicent.io/ontology/primaryName> "Auril" .
<https://starwars.com#planet_Ossus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Auril> .

