Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c3b040ad-2ba7-43c7-b988-22ae649eb326> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gbu> <http://telicent.io/ontology/primaryName> "Gbu" .
<https://starwars.com#planet_Gbu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c3b040ad-2ba7-43c7-b988-22ae649eb326> .
<https://starwars.com#planet_Gbu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gbu> <http://www.w3.org/2000/01/rdf-schema#comment> "Gbu was a planet in the Outer Rim Territories, located in the Tion Cluster's Keldrath sector. " .
<https://starwars.com#c3b040ad-2ba7-43c7-b988-22ae649eb326> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gbu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gbu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#planet_Gbu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

