Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Constancia> <http://www.w3.org/2000/01/rdf-schema#comment> "Constancia was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Constancia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Constancia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#05a28f8c-27da-433c-82d1-a299a4b2a3ef> .
<https://starwars.com#planet_Constancia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Constancia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#05a28f8c-27da-433c-82d1-a299a4b2a3ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Constancia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Constancia> <http://telicent.io/ontology/primaryName> "Constancia" .
<https://starwars.com#05a28f8c-27da-433c-82d1-a299a4b2a3ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

