Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d5bd128b-a173-4699-9798-ca6b39b85d74> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Galantos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Galantos> <http://telicent.io/ontology/primaryName> "Galantos" .
<https://starwars.com#planet_Galantos> <http://www.w3.org/2000/01/rdf-schema#comment> "Galantos was the second planet in the Utos system on the Widek Bypass, near the Koornacht Cluster. Its first contact with the galactic community was quite ancient, as at least one Fian served as a Jedi 500 years before the First Great Schism. " .
<https://starwars.com#d5bd128b-a173-4699-9798-ca6b39b85d74> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Galantos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Galantos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Galantos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Galantos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d5bd128b-a173-4699-9798-ca6b39b85d74> .

