Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e240f51b-24dc-40c4-a44c-0ac2b3c8b7e5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Soun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#planet_Soun> <http://www.w3.org/2000/01/rdf-schema#comment> "Soun could refer to one of the following: " .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Soun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e240f51b-24dc-40c4-a44c-0ac2b3c8b7e5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Soun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Soun> <http://telicent.io/ontology/primaryName> "Soun" .
<https://starwars.com#planet_Soun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e240f51b-24dc-40c4-a44c-0ac2b3c8b7e5> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Soun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .

