Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#070e69f8-bd27-47e3-82a1-1ce9ed8f9eeb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gatalenta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gatalenta> <http://telicent.io/ontology/primaryName> "Gatalenta" .
<https://starwars.com#070e69f8-bd27-47e3-82a1-1ce9ed8f9eeb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gatalenta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#070e69f8-bd27-47e3-82a1-1ce9ed8f9eeb> .
<https://starwars.com#planet_Gatalenta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Gatalenta> <http://www.w3.org/2000/01/rdf-schema#comment> "A member of the New Republic, Gatalenta was represented in the Galactic Senate for over twenty years by Senator Tai-Lin Garr. New Republic pilot Joph Seastriker also came from Gatalenta,[2] as did Resistance Vice Admiral Amilyn Holdo.[5] Due to the planet's strong Jedi tradition, Gatalenta became one of Jedi Knight Luke Skywalker's first destinations when he began studying the history of the Jedi Order.[2]" .
<https://starwars.com#planet_Gatalenta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Gatalenta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

