Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ferro> <http://telicent.io/ontology/primaryName> "Ferro" .
<https://starwars.com#planet_Ferro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_I-Sector> .
<https://starwars.com#planet_Ferro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#77017360-51c0-4c02-93b9-d28ece29f703> .
<https://starwars.com#planet_Ferro> <http://www.w3.org/2000/01/rdf-schema#comment> "Ferro was the Ferroan homeworld. In 89 BBY, the Ferroans colonized Zonama Sekot. " .
<https://starwars.com#sector_I-Sector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#77017360-51c0-4c02-93b9-d28ece29f703> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_I-Sector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#77017360-51c0-4c02-93b9-d28ece29f703> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ferro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_I-Sector> <http://telicent.io/ontology/primaryName> "I-Sector" .
<https://starwars.com#planet_Ferro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Ferro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

