Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pantora> <http://telicent.io/ontology/primaryName> "Pantora" .
<https://starwars.com#sector_Sujimis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pantora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sujimis> .
<https://starwars.com#planet_Pantora> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P19> .
<https://starwars.com#sector_Sujimis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pantora> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7aa83af2-6338-449e-b77e-9076df82b98f> .
<https://starwars.com#planet_Pantora> <http://www.w3.org/2000/01/rdf-schema#comment> "Pantora was the primary moon in orbit around the planet Orto Plutonia, in the Pantora system, located in the Sujimis sector of the Outer Rim Territories, in grid square P-19 on the Standard Galactic Grid. It was the homeworld of the Pantorans, who were led by the Pantoran Assembly and the Supreme Chairman of Pantora, a post held by Chi Cho, who was later replaced by Baron Notluwiski Papanoida. Pantora was a member of the Galactic Republic and therefore represented in the Galactic Senate. During the Clone Wars, Pantora remained loyal to the Republic and Riyo Chuchi served as its senator. " .
<https://starwars.com#7aa83af2-6338-449e-b77e-9076df82b98f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pantora"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7aa83af2-6338-449e-b77e-9076df82b98f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sujimis> <http://telicent.io/ontology/primaryName> "Sujimis" .
<https://starwars.com#planet_Pantora> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

