Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rudrig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Rudrig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rudrig> <http://www.w3.org/2000/01/rdf-schema#comment> "Rudrig was the location of a university that Lyra Erso studied at in 29 BBY. " .
<https://starwars.com#planet_Rudrig> <http://telicent.io/ontology/primaryName> "Rudrig" .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Rudrig> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#274b5bff-6ff4-4724-929a-61376d674d0b> .
<https://starwars.com#planet_Rudrig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#274b5bff-6ff4-4724-929a-61376d674d0b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#274b5bff-6ff4-4724-929a-61376d674d0b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rudrig"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

