Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1f34ebc8-a59d-4f11-9ac0-e6b586a0ca7b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sestria> <http://telicent.io/ontology/primaryName> "Sestria" .
<https://starwars.com#planet_Sestria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#1f34ebc8-a59d-4f11-9ac0-e6b586a0ca7b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sestria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sestria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sestria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Sestria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1f34ebc8-a59d-4f11-9ac0-e6b586a0ca7b> .
<https://starwars.com#planet_Sestria> <http://www.w3.org/2000/01/rdf-schema#comment> "Sestria was a banking world in the Testarr sector. It was considered corrupt and not as trustworthy as Muunilinst. " .

