Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NewAtor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#86ca93df-83ea-4ba8-a28c-0bb50796c9b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewAtor> <http://telicent.io/ontology/primaryName> "New Ator" .
<https://starwars.com#planet_NewAtor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_NewAtor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#86ca93df-83ea-4ba8-a28c-0bb50796c9b7> .
<https://starwars.com#planet_NewAtor> <http://www.w3.org/2000/01/rdf-schema#comment> "New Ator was an agriworld located in the New Ator system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. It was situated on the Triellus Trade Route hyperlane, which linked it to the Kemal Station and Trulalis systems. New Ator was a part of the informal grouping of planets known as the Regency Worlds, and it was settled by Atorese colonists in approximately 80 BBY. " .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_NewAtor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#86ca93df-83ea-4ba8-a28c-0bb50796c9b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Ator"^^<http://www.w3.org/2001/XMLSchema#string> .

