Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdMirit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdMirit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#202a77be-a5ce-4f1f-8d0b-cf7dfaccde03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdMirit> <http://telicent.io/ontology/primaryName> "Ord Mirit" .
<https://starwars.com#planet_OrdMirit> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Mirit was originally one of the Republic's Ordnance/Regional Depots. After the Battle of Endor, the planet's Imperial garrison relocated to Corellia. During the Yuuzhan Vong War, the planet was a strategic world of the New Republic. It was the homeworld of Habeer Zignean. " .
<https://starwars.com#202a77be-a5ce-4f1f-8d0b-cf7dfaccde03> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Mirit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdMirit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#202a77be-a5ce-4f1f-8d0b-cf7dfaccde03> .
<https://starwars.com#planet_OrdMirit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

