Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bortele> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_PusatStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Pusat Station was a space station on the Mid Rim's Lesser Lantillian Route, in the Bortele Cluster. The M'hendosat berthed there in 0 ABY. " .
<https://starwars.com#45dc130f-d825-4a7e-a713-623dce34fd16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PusatStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#45dc130f-d825-4a7e-a713-623dce34fd16> .
<https://starwars.com#planet_PusatStation> <http://telicent.io/ontology/primaryName> "Pusat Station" .
<https://starwars.com#planet_PusatStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#planet_PusatStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Bortele> <http://telicent.io/ontology/primaryName> "Bortele" .
<https://starwars.com#planet_PusatStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bortele> .
<https://starwars.com#45dc130f-d825-4a7e-a713-623dce34fd16> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pusat Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bortele> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

