Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b5323716-6b2c-49f3-adf0-ebb8d357b297> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nouane"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nouane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nouane> .
<https://starwars.com#sector_Nouane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Nouane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Nouane> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b5323716-6b2c-49f3-adf0-ebb8d357b297> .
<https://starwars.com#planet_Nouane> <http://www.w3.org/2000/01/rdf-schema#comment> "Nouane was an astronomical object located within its eponymous star system in the Nouane sector, which was located in the regions known as the Inner Rim Territories and the Interior. It lay within grid square N-8 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Nouane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Nouane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Nouane> <http://telicent.io/ontology/primaryName> "Nouane" .
<https://starwars.com#b5323716-6b2c-49f3-adf0-ebb8d357b297> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nouane> <http://telicent.io/ontology/primaryName> "Nouane" .

