Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Drog> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drog> <http://telicent.io/ontology/primaryName> "Drog" .
<https://starwars.com#planet_Drog> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#10a4f6cd-fbbe-4378-a49e-14d8f6ddefa8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Drog> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#10a4f6cd-fbbe-4378-a49e-14d8f6ddefa8> .
<https://starwars.com#planet_Drog> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Drog> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#10a4f6cd-fbbe-4378-a49e-14d8f6ddefa8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drog"^^<http://www.w3.org/2001/XMLSchema#string> .

