Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#e2054239-73f0-48ea-9060-843b16ed79e7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pakuuni"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#planet_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e2054239-73f0-48ea-9060-843b16ed79e7> .
<https://starwars.com#e2054239-73f0-48ea-9060-843b16ed79e7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#planet_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pakuuni> <http://www.w3.org/2000/01/rdf-schema#comment> "Pakuuni was an astronomical object located in the regions known as the Outer Rim Territories and the Slice. Situated in grid square T-6 on the Standard Galactic Grid, Pakuuni was connected via hyperspace route to the astronomical objects Munto Codru and Florn. " .

