Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nixor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9d9d2802-f77e-4751-8261-d42d0ea4101a> .
<https://starwars.com#9d9d2802-f77e-4751-8261-d42d0ea4101a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nixor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Eclorar> <http://telicent.io/ontology/primaryName> "Eclorar" .
<https://starwars.com#planet_Nixor> <http://telicent.io/ontology/primaryName> "Nixor" .
<https://starwars.com#planet_Nixor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9d9d2802-f77e-4751-8261-d42d0ea4101a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Eclorar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Nixor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Eclorar> .
<https://starwars.com#sector_Eclorar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nixor> <http://www.w3.org/2000/01/rdf-schema#comment> "Nixor was an astronomical object located in the regions known as the Mid Rim Territories and the Slice. Situated within grid square Q-12 on the Standard Galactic Grid, Nixor was connected via hyperspace route to the astronomical object Daalang and the planet Nanth'ri. " .
<https://starwars.com#planet_Nixor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q12> .

