Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#26296d85-68f9-4be1-8135-0897f99c0222> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kliaar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kliaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Kliaar> <http://telicent.io/ontology/primaryName> "Kli'aar" .
<https://starwars.com#planet_Kliaar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kliaar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#26296d85-68f9-4be1-8135-0897f99c0222> .
<https://starwars.com#planet_Kliaar> <http://www.w3.org/2000/01/rdf-schema#comment> "Kli'aar was a planet located on the Pinooran Spur in the Gordian Reach. It was inhabited by the Kli'aari, a four-armed species that were largely known for their mechanical skills. Many Kli'aari enclaves could be found on planets around the Reach. " .
<https://starwars.com#26296d85-68f9-4be1-8135-0897f99c0222> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kli'aar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

