Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kath> <http://telicent.io/ontology/primaryName> "Kath" .
<https://starwars.com#planet_Kath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dustig> .
<https://starwars.com#planet_Kath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Dustig> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Dustig> <http://telicent.io/ontology/primaryName> "Dustig" .
<https://starwars.com#planet_Kath> <http://www.w3.org/2000/01/rdf-schema#comment> "Kath was a planet in the Dustig sector of the Mid Rim and the Kath homeworld. " .
<https://starwars.com#099e26c0-3815-420a-8c94-a5f55219cb06> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#099e26c0-3815-420a-8c94-a5f55219cb06> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kath"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#sector_Dustig> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kath> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#099e26c0-3815-420a-8c94-a5f55219cb06> .

