Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Raxxa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Raxxa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Raxxa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Raxxa> <http://telicent.io/ontology/primaryName> "Raxxa" .
<https://starwars.com#planet_Raxxa> <http://www.w3.org/2000/01/rdf-schema#comment> "Raxxa was a planet represented in the New Republic Senate by Dall Thara Dru. " .
<https://starwars.com#c988f23d-f099-4b8f-b563-fc4c27ecc4a5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Raxxa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c988f23d-f099-4b8f-b563-fc4c27ecc4a5> .
<https://starwars.com#c988f23d-f099-4b8f-b563-fc4c27ecc4a5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Raxxa"^^<http://www.w3.org/2001/XMLSchema#string> .

