Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kanaver> <http://www.w3.org/2000/01/rdf-schema#comment> "Kanaver was one of the worlds once ruled by the Livien League, before being conquered by Xim the Despot in 25,130 BBY. Located within the Tion Hegemony, on the Outer Rim of the galaxy, it would later join the Galactic Republic, and eventually the Galactic Empire. " .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kanaver> <http://telicent.io/ontology/primaryName> "Kanaver" .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kanaver> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Kanaver> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#509c8293-eb20-4c84-ba3c-d133bafe69ea> .
<https://starwars.com#509c8293-eb20-4c84-ba3c-d133bafe69ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kanaver"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kanaver> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#planet_Kanaver> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#509c8293-eb20-4c84-ba3c-d133bafe69ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

