Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a929ed0a-b531-42a2-b932-511373de2e79> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Rseik> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cotellier> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rseik> .
<https://starwars.com#planet_Cotellier> <http://telicent.io/ontology/primaryName> "Cotellier" .
<https://starwars.com#planet_Cotellier> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cotellier> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N20> .
<https://starwars.com#sector_Rseik> <http://telicent.io/ontology/primaryName> "Rseik" .
<https://starwars.com#sector_Rseik> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#a929ed0a-b531-42a2-b932-511373de2e79> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cotellier"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cotellier> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a929ed0a-b531-42a2-b932-511373de2e79> .
<https://starwars.com#planet_Cotellier> <http://www.w3.org/2000/01/rdf-schema#comment> "Cotellier was an astronomical object in the galaxy's Outer Rim Territories. " .

