Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bothawui> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9720ff87-0d6d-4d2a-beac-54b0377af4ea> .
<https://starwars.com#9720ff87-0d6d-4d2a-beac-54b0377af4ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BothanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Bothawui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BothanSpace> .
<https://starwars.com#planet_Bothawui> <http://telicent.io/ontology/primaryName> "Bothawui" .
<https://starwars.com#sector_BothanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bothawui> <http://www.w3.org/2000/01/rdf-schema#comment> "Bothawui was an asteroid field–ringed gas giant located in the Bothan Space region of the galaxy's Mid Rim. Bothawui was considered to be strategically important during the Clone Wars, leading to it being the site of a battle between Jedi General Anakin Skywalker and General Grievous that halted a Separatist advance. Later in the war, around the time the Galactic Republic suffered a loss on Ryloth, Bothawui hosted another battle, though this engagement ended with many Republic losses. " .
<https://starwars.com#planet_Bothawui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#planet_Bothawui> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9720ff87-0d6d-4d2a-beac-54b0377af4ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bothawui"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_BothanSpace> <http://telicent.io/ontology/primaryName> "Bothan Space" .

