Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7ab7d9e8-a451-4c9d-988b-008dc1f8bfce> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_LanicSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dractu> <http://telicent.io/ontology/primaryName> "Dractu" .
<https://starwars.com#planet_Dractu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#7ab7d9e8-a451-4c9d-988b-008dc1f8bfce> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dractu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dractu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7ab7d9e8-a451-4c9d-988b-008dc1f8bfce> .
<https://starwars.com#sector_LanicSpace> <http://telicent.io/ontology/primaryName> "Lanic Space" .
<https://starwars.com#planet_Dractu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_LanicSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dractu> <http://www.w3.org/2000/01/rdf-schema#comment> "Dractu was a peaceful Mid Rim farming planet. It was the home of the Dractuvian people, as well as creatures mostly used as delicacies on the planet, such as Dractuvian cave slugs. " .
<https://starwars.com#planet_Dractu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_LanicSpace> .

