Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KimmCresh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KimmCresh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_KimmCresh> <http://www.w3.org/2000/01/rdf-schema#comment> "Kimm Cresh was a planet located in the Kimm Cresh system of the Juvex sector, in the Mid Rim of the galaxy. It was one of a trio of dingy industrial worlds belonging to House Sreethyn. " .
<https://starwars.com#33573121-1b03-4d4e-ba08-bd3858ceecf0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KimmCresh> <http://telicent.io/ontology/primaryName> "Kimm Cresh" .
<https://starwars.com#planet_KimmCresh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#33573121-1b03-4d4e-ba08-bd3858ceecf0> .
<https://starwars.com#33573121-1b03-4d4e-ba08-bd3858ceecf0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kimm Cresh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_KimmCresh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .

