Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Halmad> <http://www.w3.org/2000/01/rdf-schema#comment> "Halmad was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#455f68a5-37f9-4b04-8fec-85f472b0401d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Halmad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N6> .
<https://starwars.com#455f68a5-37f9-4b04-8fec-85f472b0401d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Halmad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Halmad> <http://telicent.io/ontology/primaryName> "Halmad" .
<https://starwars.com#planet_Halmad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quelii> .
<https://starwars.com#sector_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Halmad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#455f68a5-37f9-4b04-8fec-85f472b0401d> .
<https://starwars.com#planet_Halmad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

