Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e0998fbb-82c0-4083-a89a-752e4ceea908> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Teya IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lostar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_TeyaIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lostar> .
<https://starwars.com#planet_TeyaIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e0998fbb-82c0-4083-a89a-752e4ceea908> .
<https://starwars.com#planet_TeyaIV> <http://telicent.io/ontology/primaryName> "Teya IV" .
<https://starwars.com#sector_Lostar> <http://telicent.io/ontology/primaryName> "Lostar" .
<https://starwars.com#sector_Lostar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e0998fbb-82c0-4083-a89a-752e4ceea908> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TeyaIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M7> .
<https://starwars.com#planet_TeyaIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Teya IV was a planet located within the Teya system of the Expansion Region and was the homeworld of the Strak. It was where Willm Lywin founded the Teyan Praxeum in 4600 BBY. In 4000 BBY, Mistress Tannis taught Vici Ramunee and Veni Ramunee at the Praxeum. This is where the Teyan Apologia was written. The planet was made up of many villages and hamlets, with no real colonization. " .
<https://starwars.com#planet_TeyaIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

