Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lafra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#planet_Lafra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#941da425-feb9-478e-9767-3db8fc0cf46d> .
<https://starwars.com#sector_Wyl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Wyl> <http://telicent.io/ontology/primaryName> "Wyl" .
<https://starwars.com#941da425-feb9-478e-9767-3db8fc0cf46d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lafra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Wyl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#941da425-feb9-478e-9767-3db8fc0cf46d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lafra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lafra> <http://www.w3.org/2000/01/rdf-schema#comment> "The planet's smashball team played against that of Gathus. " .
<https://starwars.com#planet_Lafra> <http://telicent.io/ontology/primaryName> "Lafra" .
<https://starwars.com#planet_Lafra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wyl> .

