Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Deysum> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#de63b5ac-0f4b-4ac6-b0cd-c4e1c516082e> .
<https://starwars.com#planet_Deysum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trax> .
<https://starwars.com#planet_Deysum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Deysum> <http://telicent.io/ontology/primaryName> "Deysum" .
<https://starwars.com#planet_Deysum> <http://www.w3.org/2000/01/rdf-schema#comment> "Deysum was an astronomical object located within the regions known as the Mid Rim Territories and the Slice. Situated in grid square Q-10 on the Standard Galactic Grid, Deysum was connected via a hyperspace route to the astronomical objects Randon and Uogo'cor. " .
<https://starwars.com#de63b5ac-0f4b-4ac6-b0cd-c4e1c516082e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#de63b5ac-0f4b-4ac6-b0cd-c4e1c516082e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Deysum"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Trax> <http://telicent.io/ontology/primaryName> "Trax" .
<https://starwars.com#sector_Trax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Deysum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#sector_Trax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

