Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Kath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kath> <http://telicent.io/ontology/primaryName> "K'ath" .
<https://starwars.com#4cc56040-5c53-40ad-b743-19c174cf0cb3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kath> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4cc56040-5c53-40ad-b743-19c174cf0cb3> .
<https://starwars.com#4cc56040-5c53-40ad-b743-19c174cf0cb3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K'ath"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kath> <http://www.w3.org/2000/01/rdf-schema#comment> "K'ath was a planet located in the K'ath system of the Juvex sector, in the Mid Rim of the galaxy. An agriworld, K'ath was most notable for its seashells, which local artisans would craft into figurines. In addition to these trinkets, visitors knew K'ath for its wide beaches and terraced hills. " .
<https://starwars.com#planet_Kath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Kath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

