Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bortele> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zchtek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#8453eaee-a253-4f39-9c08-0424cea783d7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zchtek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zchtek> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Zchtek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8453eaee-a253-4f39-9c08-0424cea783d7> .
<https://starwars.com#planet_Zchtek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zchtek> <http://telicent.io/ontology/primaryName> "Zchtek" .
<https://starwars.com#planet_Zchtek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bortele> .
<https://starwars.com#sector_Bortele> <http://telicent.io/ontology/primaryName> "Bortele" .
<https://starwars.com#8453eaee-a253-4f39-9c08-0424cea783d7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Bortele> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

