Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jospro> <http://telicent.io/ontology/primaryName> "Jospro" .
<https://starwars.com#5c65a047-39a9-4758-865e-7588e9b0e369> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5c65a047-39a9-4758-865e-7588e9b0e369> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5c65a047-39a9-4758-865e-7588e9b0e369> .
<https://starwars.com#planet_Chad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Jospro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Chad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jospro> .
<https://starwars.com#sector_Jospro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Chad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#planet_Chad> <http://telicent.io/ontology/primaryName> "Chad" .
<https://starwars.com#planet_Chad> <http://www.w3.org/2000/01/rdf-schema#comment> "Chad was a planet located in the galaxy's Outer Rim Territories that was the homeworld of the sentient Chadra-Fan species. A blue dressing known as Chadian dressing was from this world. " .

