Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Paonid> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Paonid> <http://telicent.io/ontology/primaryName> "Paonid" .
<https://starwars.com#planet_Paonid> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#921b3379-1270-4748-88c6-1f56e7a87cb6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Paonid"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#921b3379-1270-4748-88c6-1f56e7a87cb6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Paonid> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#921b3379-1270-4748-88c6-1f56e7a87cb6> .
<https://starwars.com#planet_Paonid> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Paonid> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

