Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_DinPulsar> <http://www.w3.org/2000/01/rdf-schema#comment> "The Din Pulsar was situated in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. Located near the Din Nebula, the pulsar was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_DinPulsar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#7e96adda-741d-440b-856f-29ccd1db4b4d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_DinPulsar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e96adda-741d-440b-856f-29ccd1db4b4d> .
<https://starwars.com#planet_DinPulsar> <http://telicent.io/ontology/primaryName> "Din Pulsar" .
<https://starwars.com#planet_DinPulsar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_DinPulsar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7e96adda-741d-440b-856f-29ccd1db4b4d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Din Pulsar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

