Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Harrin> <http://telicent.io/ontology/primaryName> "Harrin" .
<https://starwars.com#3510680a-e81b-4f09-97c2-995b755ec004> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Harrin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Harrin> <http://www.w3.org/2000/01/rdf-schema#comment> "Harrin was an astronomical object located in the regions known as the Inner Rim and the Trailing Sectors. It was situated in the grid square L-15 of the Standard Galactic Grid. The super-hyperroute known as the Corellian Trade Spine connected Harrin to the world Yag'Dhul as well as the Expansion Region's Kinyen, while another hyperspace route linked it to Wroona. " .
<https://starwars.com#planet_Harrin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3510680a-e81b-4f09-97c2-995b755ec004> .
<https://starwars.com#sector_Harrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Harrin> <http://telicent.io/ontology/primaryName> "Harrin" .
<https://starwars.com#planet_Harrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Harrin> .
<https://starwars.com#sector_Harrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Harrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Harrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L15> .
<https://starwars.com#3510680a-e81b-4f09-97c2-995b755ec004> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

