Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Merson> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Airon> .
<https://starwars.com#planet_Merson> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Airon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Airon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#ddf64c66-b58f-4167-8d6e-0c29fc79e72c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Merson> <http://www.w3.org/2000/01/rdf-schema#comment> "Merson was a planet that was located in the Stenness Node within the Inner Rim, near the Merson asteroid belt. " .
<https://starwars.com#planet_Merson> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#planet_Merson> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ddf64c66-b58f-4167-8d6e-0c29fc79e72c> .
<https://starwars.com#planet_Merson> <http://telicent.io/ontology/primaryName> "Merson" .
<https://starwars.com#sector_Airon> <http://telicent.io/ontology/primaryName> "Airon" .
<https://starwars.com#ddf64c66-b58f-4167-8d6e-0c29fc79e72c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Merson"^^<http://www.w3.org/2001/XMLSchema#string> .

