Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_SheduMaad> <http://telicent.io/ontology/primaryName> "Shedu Maad" .
<https://starwars.com#635a9b1e-afc1-4786-a807-ed12632e8879> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shedu Maad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SheduMaad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#635a9b1e-afc1-4786-a807-ed12632e8879> .
<https://starwars.com#planet_SheduMaad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_SheduMaad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_SheduMaad> <http://www.w3.org/2000/01/rdf-schema#comment> "Shedu Maad was a planet in the Hapes Cluster, located within its Transitory Mists region. It was used as a hidden base for the Jedi Coalition after they evacuated their temporary base at Endor. It was here that the Coalition defeated Darth Caedus and ended the Second Galactic Civil War. A Jedi academy was established on the planet after the war and was still in use as of 44 ABY. " .
<https://starwars.com#635a9b1e-afc1-4786-a807-ed12632e8879> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_SheduMaad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

