Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zygerria> <http://www.w3.org/2000/01/rdf-schema#comment> "A planet in the Outer Rim Territories home of the Zygerrian species. Zygerria was also known for a slave empire." .
<https://starwars.com#planet_Zygerria> <http://telicent.io/ontology/primaryName> "Zygerria" .
<https://starwars.com#sector_Chorlian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Zygerria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Zygerria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chorlian> .
<https://starwars.com#ced69d13-d3b4-418c-a42d-62129a4fb72b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zygerria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Chorlian> <http://telicent.io/ontology/primaryName> "Chorlian" .
<https://starwars.com#planet_Zygerria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ced69d13-d3b4-418c-a42d-62129a4fb72b> .
<https://starwars.com#sector_Chorlian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ced69d13-d3b4-418c-a42d-62129a4fb72b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zygerria"^^<http://www.w3.org/2001/XMLSchema#string> .

