Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ac466240-3a56-43ac-a3ac-cebd85ed807c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ac466240-3a56-43ac-a3ac-cebd85ed807c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kir> <http://telicent.io/ontology/primaryName> "Kir" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Kir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac466240-3a56-43ac-a3ac-cebd85ed807c> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kir> <http://www.w3.org/2000/01/rdf-schema#comment> "Kir was a planet that was located within the Corporate Sector. A mineral found on this planet was used in the production of crystalline vertex. " .
<https://starwars.com#planet_Kir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Kir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

