Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Baraboo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a1ae781-c383-421a-b714-1cdaa80262a8> .
<https://starwars.com#6a1ae781-c383-421a-b714-1cdaa80262a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Baraboo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_M11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_M11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e4a79e1a-928f-4fcd-886c-d92c15368ecf> .
<https://starwars.com#grid_M11> <http://telicent.io/ontology/primaryName> "M11" .
<https://starwars.com#planet_Baraboo> <http://telicent.io/ontology/primaryName> "Baraboo" .
<https://starwars.com#e4a79e1a-928f-4fcd-886c-d92c15368ecf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Baraboo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#e4a79e1a-928f-4fcd-886c-d92c15368ecf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Baraboo> <http://www.w3.org/2000/01/rdf-schema#comment> "Baraboo was an oceanic New Republic planet in the Core Worlds, along the Hydian Way. It was the headquarters of the Institute for Sentient Studies as well as the biomold homeworld. " .
<https://starwars.com#planet_Baraboo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#grid_M11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#6a1ae781-c383-421a-b714-1cdaa80262a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Baraboo"^^<http://www.w3.org/2001/XMLSchema#string> .

