Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7bc5ae1b-7be8-4bc2-aec6-4f12f49bd85e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dantooine> <http://www.w3.org/2000/01/rdf-schema#comment> "Rural planet and the former site of a Rebel base. The writers of Rogue One considered depicting the Rebels evacuating the base for Yavin 4, but 'it didn't move the story forward and it would have cost a ton of money.'" .
<https://starwars.com#sector_Raioballo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dantooine> <http://telicent.io/ontology/primaryName> "Dantooine" .
<https://starwars.com#planet_Dantooine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7bc5ae1b-7be8-4bc2-aec6-4f12f49bd85e> .
<https://starwars.com#sector_Raioballo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Dantooine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7bc5ae1b-7be8-4bc2-aec6-4f12f49bd85e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dantooine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dantooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Raioballo> .
<https://starwars.com#sector_Raioballo> <http://telicent.io/ontology/primaryName> "Raioballo" .
<https://starwars.com#planet_Dantooine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L4> .

