Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Kamdon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kamdon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#0351df22-5222-44b2-b57e-2e512cea518a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kamdon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0351df22-5222-44b2-b57e-2e512cea518a> .
<https://starwars.com#planet_Kamdon> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#0351df22-5222-44b2-b57e-2e512cea518a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kamdon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kamdon> <http://telicent.io/ontology/primaryName> "Kamdon" .
<https://starwars.com#planet_Kamdon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

