Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0fd4ca34-6ca6-4a75-a945-34246f723654> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Faro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Faro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#planet_Faro> <http://www.w3.org/2000/01/rdf-schema#comment> "Faro was a planet in the Faro system within the Colonies region of the galaxy. " .
<https://starwars.com#0fd4ca34-6ca6-4a75-a945-34246f723654> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Faro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Faro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0fd4ca34-6ca6-4a75-a945-34246f723654> .
<https://starwars.com#planet_Faro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Faro> <http://telicent.io/ontology/primaryName> "Faro" .

