Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gaulus> <http://telicent.io/ontology/primaryName> "Gaulus" .
<https://starwars.com#planet_Gaulus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S17> .
<https://starwars.com#planet_Gaulus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_S17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Gaulus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ad98a77d-990b-40ed-b8b8-002d824c88bd> .
<https://starwars.com#planet_Gaulus> <http://www.w3.org/2000/01/rdf-schema#comment> "Gaulus was a location in the galaxy. Alliance to Restore the Republic Lieutenant Caluan Ematt and Sergeant Ruescott Melshi served together on Gaulus during the early rebellion against the Galactic Empire. During the Alliance's retreat from Gaulus, they deployed the UT-60D U-wing starfighter/support craft as a medevac lifter. It shared its name with the Gaulus sector of the Outer Rim Territories. " .
<https://starwars.com#768669d2-7978-4b2a-b8a0-01996dab15be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Gaulus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#ad98a77d-990b-40ed-b8b8-002d824c88bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gaulus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gaulus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Gaulus> .
<https://starwars.com#grid_S17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_S17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#768669d2-7978-4b2a-b8a0-01996dab15be> .
<https://starwars.com#grid_S17> <http://telicent.io/ontology/primaryName> "S17" .
<https://starwars.com#ad98a77d-990b-40ed-b8b8-002d824c88bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#768669d2-7978-4b2a-b8a0-01996dab15be> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Gaulus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Gaulus> <http://telicent.io/ontology/primaryName> "Gaulus" .

