Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6e817197-7e21-448c-8cf1-8f6ecc387420> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Doldrums"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Doldrums> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#6e817197-7e21-448c-8cf1-8f6ecc387420> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Doldrums> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Doldrums> <http://www.w3.org/2000/01/rdf-schema#comment> "Doldrums was a star in the Inner Rim. " .
<https://starwars.com#planet_Doldrums> <http://telicent.io/ontology/primaryName> "Doldrums" .
<https://starwars.com#planet_Doldrums> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Doldrums> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6e817197-7e21-448c-8cf1-8f6ecc387420> .

