Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Joodrudda> <http://www.w3.org/2000/01/rdf-schema#comment> "Joodrudda was a barren, nearly uninhabited world located on the Tingel Route, just outside the borders of the Corporate Sector. Its only point of interest was a sprawling palace constructed hundreds of years before the Battle of Yavin by a clan of eccentric Hutts. " .
<https://starwars.com#planet_Joodrudda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Joodrudda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6099e2cf-f72c-4c68-89b9-157f925b6c47> .
<https://starwars.com#6099e2cf-f72c-4c68-89b9-157f925b6c47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Joodrudda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#6099e2cf-f72c-4c68-89b9-157f925b6c47> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Joodrudda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Joodrudda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Joodrudda> <http://telicent.io/ontology/primaryName> "Joodrudda" .

