Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Trans-Nebular> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Iskalon> <http://www.w3.org/2000/01/rdf-schema#comment> "Iskalon was a planet located in the galaxy's Mid Rim. The pirate Queen Maz Kanata hid a portion of the spoils from her reign there in a buried vault equipped with a antitamper sub-space alarm. As of when she began writing the book that would become known as the Smuggler's Guide, the alarm protecting the cache of treasure on Iskalon had not sounded. " .
<https://starwars.com#cc554180-ef20-4dd8-877b-5e2d6b7cca48> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Iskalon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Trans-Nebular> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Iskalon> <http://telicent.io/ontology/primaryName> "Iskalon" .
<https://starwars.com#planet_Iskalon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc554180-ef20-4dd8-877b-5e2d6b7cca48> .
<https://starwars.com#cc554180-ef20-4dd8-877b-5e2d6b7cca48> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iskalon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Trans-Nebular> <http://telicent.io/ontology/primaryName> "Trans-Nebular" .
<https://starwars.com#planet_Iskalon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iskalon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trans-Nebular> .

