Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tarsunt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#planet_Tarsunt> <http://www.w3.org/2000/01/rdf-schema#comment> "The Tarsunt were a species of furry sentients from the planet of the same name. They were represented by Senator Colandrus in the Galactic Republic, and by Lanever Villecham in the New Republic; the latter went on to serve as chancellor in the New Republic Senate until his death in the Hosnian Cataclysm. " .
<https://starwars.com#sector_BothanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_BothanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#586d9488-b3e4-425d-b35b-ab515c7b6453> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tarsunt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#586d9488-b3e4-425d-b35b-ab515c7b6453> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tarsunt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tarsunt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#586d9488-b3e4-425d-b35b-ab515c7b6453> .
<https://starwars.com#planet_Tarsunt> <http://telicent.io/ontology/primaryName> "Tarsunt" .
<https://starwars.com#planet_Tarsunt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BothanSpace> .
<https://starwars.com#sector_BothanSpace> <http://telicent.io/ontology/primaryName> "Bothan Space" .

