Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jaguada> <http://www.w3.org/2000/01/rdf-schema#comment> "Jaguada was a desert planet and one of the noteworthy worlds of the ancient Sith. According to legend, the Sith Lord Darth Noctyss carried out research on the planet that eventually led her to the lost Sith world of Exegol in her quest to attain immortality. In the time of the Galactic Republic, Jaguada was quarantined along with the likes of Malachor, Ziost, and Rhelg, and its affiliation to the Sith was hidden from history. " .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#2d3558d4-318c-4d4c-8dde-1123ab6f4497> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jaguada"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Jaguada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Jaguada> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2d3558d4-318c-4d4c-8dde-1123ab6f4497> .
<https://starwars.com#planet_Jaguada> <http://telicent.io/ontology/primaryName> "Jaguada" .
<https://starwars.com#2d3558d4-318c-4d4c-8dde-1123ab6f4497> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jaguada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jaguada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .

