Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_GleeAnselm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7188ddfe-c909-4838-9006-4e7dea18888b> .
<https://starwars.com#7188ddfe-c909-4838-9006-4e7dea18888b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#7188ddfe-c909-4838-9006-4e7dea18888b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Glee Anselm"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Jalor> <http://telicent.io/ontology/primaryName> "Jalor" .
<https://starwars.com#planet_GleeAnselm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#planet_GleeAnselm> <http://telicent.io/ontology/primaryName> "Glee Anselm" .
<https://starwars.com#planet_GleeAnselm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jalor> .
<https://starwars.com#planet_GleeAnselm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Jalor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_GleeAnselm> <http://www.w3.org/2000/01/rdf-schema#comment> "Glee Anselm was an ocean planet located in the Jalor system of the galaxy's Mid Rim that was the homeworld of the Anselmi and Nautolan species. Star Tours, a tour company, offered vacation tours of Glee Anselm during the Clone Wars. During the reign of the Galactic Empire, senators representing the planet in the Imperial Senate were fiercely loyal to the Empire. Glee Anselm was also the homeworld of the criminal Tobias Beckett and the Jedi Master Kit Fisto. " .
<https://starwars.com#sector_Jalor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

