Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a2ef0432-0935-4036-97dd-edd15a769e08> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Falko"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Falko> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2ef0432-0935-4036-97dd-edd15a769e08> .
<https://starwars.com#a2ef0432-0935-4036-97dd-edd15a769e08> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Falko> <http://telicent.io/ontology/primaryName> "Falko" .
<https://starwars.com#planet_Falko> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#planet_Falko> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Falko> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Falko> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

