Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gulvitch> <http://telicent.io/ontology/primaryName> "Gulvitch" .
<https://starwars.com#planet_Gulvitch> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8e3e8372-6570-4443-b8eb-bce6fb2c1dc6> .
<https://starwars.com#planet_Gulvitch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_Gulvitch> <http://www.w3.org/2000/01/rdf-schema#comment> "Gulvitch was a mining planet located in the Gordian Reach. It sat on the Junction-Tierell Loop, between Bronsoon and Arkuda. The planet was home to a struggling colony founded by the Povanarians and Bagmims. Gulvitch was rarely visited by those who could afford to go elsewhere. " .
<https://starwars.com#8e3e8372-6570-4443-b8eb-bce6fb2c1dc6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#planet_Gulvitch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gulvitch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#8e3e8372-6570-4443-b8eb-bce6fb2c1dc6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gulvitch"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

