Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Daan/Melida> <http://telicent.io/ontology/primaryName> "Daan/Melida" .
<https://starwars.com#e68e9d3a-1886-478c-8d45-8f139ba50a96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_P17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e68e9d3a-1886-478c-8d45-8f139ba50a96> .
<https://starwars.com#grid_P17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Daan/Melida> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e68e9d3a-1886-478c-8d45-8f139ba50a96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Daan/Melida> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fd018083-0b9e-48c7-8374-2e199d15ae27> .
<https://starwars.com#sector_Cadavine> <http://telicent.io/ontology/primaryName> "Cadavine" .
<https://starwars.com#planet_Daan/Melida> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P17> .
<https://starwars.com#planet_Daan/Melida> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#fd018083-0b9e-48c7-8374-2e199d15ae27> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_P17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Daan/Melida> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cadavine> .
<https://starwars.com#grid_P17> <http://telicent.io/ontology/primaryName> "P17" .
<https://starwars.com#fd018083-0b9e-48c7-8374-2e199d15ae27> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Daan/Melida"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Cadavine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cadavine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

