Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_K18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Allyuen> <http://www.w3.org/2000/01/rdf-schema#comment> "Assumption ends here." .
<https://starwars.com#grid_K18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0c21459e-01ab-4903-903b-45a41ba86e54> .
<https://starwars.com#grid_K18> <http://telicent.io/ontology/primaryName> "K18" .
<https://starwars.com#planet_Allyuen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#215e9160-740b-4939-ac6c-3084569d0679> .
<https://starwars.com#planet_Allyuen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Allyuen> <http://telicent.io/ontology/primaryName> "Allyuen" .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#grid_K18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#0c21459e-01ab-4903-903b-45a41ba86e54> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Allyuen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Allyuen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#215e9160-740b-4939-ac6c-3084569d0679> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#215e9160-740b-4939-ac6c-3084569d0679> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Allyuen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0c21459e-01ab-4903-903b-45a41ba86e54> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K18"^^<http://www.w3.org/2001/XMLSchema#string> .

