Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hirsi> <http://www.w3.org/2000/01/rdf-schema#comment> "Hirsi was a planet on the Cerean Reach in the Mid Rim. " .
<https://starwars.com#sector_Elbaran> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Elbaran> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#00d7dc22-c33d-448d-9a29-abfd3d6af894> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hirsi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Elbaran> .
<https://starwars.com#planet_Hirsi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hirsi> <http://telicent.io/ontology/primaryName> "Hirsi" .
<https://starwars.com#planet_Hirsi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J17> .
<https://starwars.com#00d7dc22-c33d-448d-9a29-abfd3d6af894> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hirsi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hirsi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#00d7dc22-c33d-448d-9a29-abfd3d6af894> .
<https://starwars.com#sector_Elbaran> <http://telicent.io/ontology/primaryName> "Elbaran" .

