Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_Dactruria> <http://telicent.io/ontology/primaryName> "Dactruria" .
<https://starwars.com#planet_Dactruria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_Dactruria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b45992fa-995f-4ca2-9383-a7c962aacd44> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#b45992fa-995f-4ca2-9383-a7c962aacd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b45992fa-995f-4ca2-9383-a7c962aacd44> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dactruria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dactruria> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Dactruria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .
<https://starwars.com#planet_Dactruria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

