Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gargon> <http://www.w3.org/2000/01/rdf-schema#comment> "Gargon was a mountainous planet. It was settled by the Old Mandalorians, who were exiled from their homeworld of Mandalore by the pacifistic New Mandalorians after a civil war in approximately 42 BBY. On Gargon, they lived as mercenaries working for the highest bidder, as Mandalorians had done for millennia. " .
<https://starwars.com#sector_Meerian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gargon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#aa7a28ec-71a0-4978-920c-38f74b92ae4c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gargon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gargon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meerian> .
<https://starwars.com#planet_Gargon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Meerian> <http://telicent.io/ontology/primaryName> "Meerian" .
<https://starwars.com#planet_Gargon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aa7a28ec-71a0-4978-920c-38f74b92ae4c> .
<https://starwars.com#aa7a28ec-71a0-4978-920c-38f74b92ae4c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Meerian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gargon> <http://telicent.io/ontology/primaryName> "Gargon" .

