Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Balosar> <http://telicent.io/ontology/primaryName> "Balosar" .
<https://starwars.com#planet_Balosar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Balosar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L12> .
<https://starwars.com#planet_Balosar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#a79c84d6-daf2-4840-b2a9-c324db3b290e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Balosar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a79c84d6-daf2-4840-b2a9-c324db3b290e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Balosar> <http://www.w3.org/2000/01/rdf-schema#comment> "Balosar was a ruined planet in the galaxy's Core Worlds that was the homeworld of the Balosar species. Balosar was known for its balo mushrooms, exclusive to the planet, which were refined by companies such as BioTech Industries and Fergriss Pharmaceuticals into ixetal cilona, a powerful narcotic used in death sticks and interrogation drugs. " .
<https://starwars.com#planet_Balosar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a79c84d6-daf2-4840-b2a9-c324db3b290e> .

