Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Prakith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3ebcb054-64ef-4f04-94b1-cc7664ebdb48> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Prakith> <http://www.w3.org/2000/01/rdf-schema#comment> "Prakith was an astronomical object located within the galaxy's Deep Core. It was connected via the Byss Run hyperspace route to Byss and Empress Teta. " .
<https://starwars.com#3ebcb054-64ef-4f04-94b1-cc7664ebdb48> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Prakith"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Prakith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Prakith> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3ebcb054-64ef-4f04-94b1-cc7664ebdb48> .
<https://starwars.com#planet_Prakith> <http://telicent.io/ontology/primaryName> "Prakith" .
<https://starwars.com#planet_Prakith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .

