Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#85c48066-dc8d-4b09-8936-e95498b71714> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pammant> <http://telicent.io/ontology/primaryName> "Pammant" .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pammant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pammant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#planet_Pammant> <http://www.w3.org/2000/01/rdf-schema#comment> "Pammant was home to Pammant Docks, the location where the Invisible Hand, a Providence-class Dreadnought that served as General Grievous' flagship during the Battle of Coruscant, was constructed by the Free Dac Volunteers Engineering Corps, a Quarren starship manufacturer that aligned itself with the Confederacy of Independent Systems during the Clone Wars. One of two examples of a Subjugator-class heavy cruiser, the Malevolence was manufactured in secret by the Quarren engineers of Free Dac Volunteers Engineering Corps and Pammant Docks on Pammant, where it was designed by Ruggle Schmong in equal secrecy, who used a discarded SoroSuub Corporation starship design. " .
<https://starwars.com#85c48066-dc8d-4b09-8936-e95498b71714> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pammant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pammant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#85c48066-dc8d-4b09-8936-e95498b71714> .
<https://starwars.com#planet_Pammant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

