Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rrulinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#planet_Rrulinn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9e93c1b5-fecb-464d-b1b6-b4f9c0e85b86> .
<https://starwars.com#sector_Yushan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yushan> <http://telicent.io/ontology/primaryName> "Yushan" .
<https://starwars.com#sector_Yushan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Rrulinn> <http://www.w3.org/2000/01/rdf-schema#comment> "Rrulinn was a Mid Rim world in the Yushan sector. Its population fell victim to the Reslian Purge, much as did the Tunroth. " .
<https://starwars.com#planet_Rrulinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9e93c1b5-fecb-464d-b1b6-b4f9c0e85b86> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rrulinn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rrulinn> <http://telicent.io/ontology/primaryName> "Rrulinn" .
<https://starwars.com#planet_Rrulinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yushan> .
<https://starwars.com#9e93c1b5-fecb-464d-b1b6-b4f9c0e85b86> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

