Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Raithal> <http://telicent.io/ontology/primaryName> "Raithal" .
<https://starwars.com#planet_Raithal> <http://www.w3.org/2000/01/rdf-schema#comment> "Raithal was a planet in the Colonies along the Perlemian Trade Route that hosted an Imperial Academy several years before the Battle of Yavin. " .
<https://starwars.com#planet_Raithal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5fed9be8-8053-43c4-a9ca-dd02ca86e2a9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Raithal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#5fed9be8-8053-43c4-a9ca-dd02ca86e2a9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Raithal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Raithal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5fed9be8-8053-43c4-a9ca-dd02ca86e2a9> .
<https://starwars.com#planet_Raithal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .

