Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Enisca> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Enisca> <http://telicent.io/ontology/primaryName> "Enisca" .
<https://starwars.com#planet_Enisca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#b49fb903-8ede-4f41-919c-a712d741a804> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Enisca"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Enisca> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b49fb903-8ede-4f41-919c-a712d741a804> .
<https://starwars.com#b49fb903-8ede-4f41-919c-a712d741a804> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Enisca> <http://www.w3.org/2000/01/rdf-schema#comment> "Enisca was a planet that, along with Sern Prime and Kashyyyk, were considered prime candidates for anti-Imperial rebellion by Mon Mothma. " .
<https://starwars.com#planet_Enisca> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

