Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zeltros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Zeltros> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O10> .
<https://starwars.com#planet_Zeltros> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a general location. You can help Wookieepedia by expanding it. " .
<https://starwars.com#planet_Zeltros> <http://telicent.io/ontology/primaryName> "Zeltros" .
<https://starwars.com#planet_Zeltros> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#143857d6-d6c7-434f-b2d9-17596ea1ed98> .
<https://starwars.com#planet_Zeltros> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#143857d6-d6c7-434f-b2d9-17596ea1ed98> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zeltros"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#143857d6-d6c7-434f-b2d9-17596ea1ed98> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

