Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalist> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1af79bb3-5f2d-43ed-9808-00d9c0ab747a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalist"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kalist> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1af79bb3-5f2d-43ed-9808-00d9c0ab747a> .
<https://starwars.com#planet_Kalist> <http://telicent.io/ontology/primaryName> "Kalist" .
<https://starwars.com#planet_Kalist> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalist VI, also known as Kalist, was a world located in the galaxy's Deep Core where the Galactic Empire had a penal colony. It was the homeworld of the Rebel pilot Dak Ralter, who was born to a family of political prisoners in the colony. Ralter escaped the world with bright ambitions, but was killed in the Battle of Hoth. " .
<https://starwars.com#planet_Kalist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Kalist> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#1af79bb3-5f2d-43ed-9808-00d9c0ab747a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

