Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Felucia> <http://telicent.io/ontology/primaryName> "Felucia" .
<https://starwars.com#sector_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Felucia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thanium> .
<https://starwars.com#planet_Felucia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ecb36f27-3d77-4d1c-a64a-ed3594357fd9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Felucia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Felucia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ecb36f27-3d77-4d1c-a64a-ed3594357fd9> .
<https://starwars.com#sector_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#ecb36f27-3d77-4d1c-a64a-ed3594357fd9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Felucia> <http://www.w3.org/2000/01/rdf-schema#comment> "Jungle planet teeming with plants but little animal life. Aayla Secura is assassinated here during the Jedi Purge." .
<https://starwars.com#sector_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Felucia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .

