Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_VarHagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#73e58397-efd3-4a2e-8fef-ef8539650e19> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Opiteihr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Opiteihr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Opiteihr> <http://www.w3.org/2000/01/rdf-schema#comment> "Opiteihr was one of the four red giants in the Opiteihr system. " .
<https://starwars.com#sector_VarHagen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_VarHagen> <http://telicent.io/ontology/primaryName> "Var Hagen" .
<https://starwars.com#planet_Opiteihr> <http://telicent.io/ontology/primaryName> "Opiteihr" .
<https://starwars.com#planet_Opiteihr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#planet_Opiteihr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73e58397-efd3-4a2e-8fef-ef8539650e19> .
<https://starwars.com#planet_Opiteihr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_VarHagen> .
<https://starwars.com#73e58397-efd3-4a2e-8fef-ef8539650e19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

