Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dirha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#planet_Dirha> <http://www.w3.org/2000/01/rdf-schema#comment> "Dirha was a gritty industrial planet that was located within the Dirha system of the galaxy's Hutt Space region and lay on the hyperlane called the Sisar Run, which connected it to the world of Cyborrea and the Sespe system. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#6d83f893-9bf6-444a-914f-0f94d86e5c97> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dirha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dirha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6d83f893-9bf6-444a-914f-0f94d86e5c97> .
<https://starwars.com#planet_Dirha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dirha> <http://telicent.io/ontology/primaryName> "Dirha" .
<https://starwars.com#planet_Dirha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#6d83f893-9bf6-444a-914f-0f94d86e5c97> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

