Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ShaumHii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N5> .
<https://starwars.com#sector_TraganCluster> <http://telicent.io/ontology/primaryName> "Tragan Cluster" .
<https://starwars.com#planet_ShaumHii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6526fce2-9d05-4951-856e-79d388fb99b2> .
<https://starwars.com#6526fce2-9d05-4951-856e-79d388fb99b2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ShaumHii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TraganCluster> .
<https://starwars.com#sector_TraganCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#6526fce2-9d05-4951-856e-79d388fb99b2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shaum Hii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ShaumHii> <http://www.w3.org/2000/01/rdf-schema#comment> "Shaum Hii was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_ShaumHii> <http://telicent.io/ontology/primaryName> "Shaum Hii" .
<https://starwars.com#sector_TraganCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_ShaumHii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

