Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Trans-Nebular> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e3f2ebb7-f120-4549-80e0-d008bd58fbbb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Milarian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Milarian> <http://www.w3.org/2000/01/rdf-schema#comment> "Milarian was the sector capital of the Trans-Nebular sector. " .
<https://starwars.com#sector_Trans-Nebular> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e3f2ebb7-f120-4549-80e0-d008bd58fbbb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Milarian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e3f2ebb7-f120-4549-80e0-d008bd58fbbb> .
<https://starwars.com#sector_Trans-Nebular> <http://telicent.io/ontology/primaryName> "Trans-Nebular" .
<https://starwars.com#planet_Milarian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Milarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#planet_Milarian> <http://telicent.io/ontology/primaryName> "Milarian" .
<https://starwars.com#planet_Milarian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trans-Nebular> .

