Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sargon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Sargon> <http://telicent.io/ontology/primaryName> "Sargon" .
<https://starwars.com#7880b67a-eec6-433a-bbde-98480804e7eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sargon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Sargon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Sargon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#7880b67a-eec6-433a-bbde-98480804e7eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sargon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7880b67a-eec6-433a-bbde-98480804e7eb> .
<https://starwars.com#planet_Sargon> <http://www.w3.org/2000/01/rdf-schema#comment> "Sargon was a male Imperial Army Captain who lived during the Galactic Civil War. " .

