Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Borao> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#a4a1a91e-b314-4799-a91f-6952afa18aff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Borao> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Borao> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a4a1a91e-b314-4799-a91f-6952afa18aff> .
<https://starwars.com#planet_Borao> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#planet_Borao> <http://www.w3.org/2000/01/rdf-schema#comment> "Borao was a world within the Inner Rim that was located between Coruscant and Ramodi. Its surface was covered in yorik coral spires and forests after its Vongforming and abandonment by the Yuuzhan Vong. It was adopted as the new home world of the Ithorians, along with Felucia after the devastation of Ithor, under the Galactic Alliance. " .
<https://starwars.com#planet_Borao> <http://telicent.io/ontology/primaryName> "Borao" .
<https://starwars.com#a4a1a91e-b314-4799-a91f-6952afa18aff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Borao"^^<http://www.w3.org/2001/XMLSchema#string> .

