Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Talay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Dufilvian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Talay> <http://telicent.io/ontology/primaryName> "Talay" .
<https://starwars.com#acad8724-9402-48f4-86a3-c2c9dad880c2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Talay> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#acad8724-9402-48f4-86a3-c2c9dad880c2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Talay"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Talay> <http://www.w3.org/2000/01/rdf-schema#comment> "Talay was a location in the galaxy that served as an Alliance to Restore the Republic regional headquarters and operations sector during the early rebellion against the Galactic Empire. Talay would be included in a map of the galaxy that listed safe worlds, starfighter hubs at level five or higher, regional headquarters and operations sectors, and deep space caches. Ord Pardron, an Alliance safe world, was nearby. " .
<https://starwars.com#planet_Talay> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#acad8724-9402-48f4-86a3-c2c9dad880c2> .
<https://starwars.com#planet_Talay> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dufilvian> .
<https://starwars.com#sector_Dufilvian> <http://telicent.io/ontology/primaryName> "Dufilvian" .
<https://starwars.com#sector_Dufilvian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

