Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a3ec337f-af2b-4dd9-b355-cf955656d871> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Galand"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Galand> <http://www.w3.org/2000/01/rdf-schema#comment> "Galand was a Core world. It was homeworld of the near-Human Galandans, including the religious martyr H'kig. His teachings formed the basis of the H'kig philosophy. To escape persecution, the H'kig fled to distant Rishi. " .
<https://starwars.com#planet_Galand> <http://telicent.io/ontology/primaryName> "Galand" .
<https://starwars.com#planet_Galand> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Galand> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#a3ec337f-af2b-4dd9-b355-cf955656d871> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Galand> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a3ec337f-af2b-4dd9-b355-cf955656d871> .
<https://starwars.com#planet_Galand> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .

