Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Blimph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#009bb290-ac6e-410d-ae07-6d6c33db8570> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Blimph> <http://www.w3.org/2000/01/rdf-schema#comment> "Blimph was a Mid Rim gas giant in the Blimph system. One of its moons was Blimph 3, which was strategically important to the Rebel Alliance due to trading with the Jokhalli. " .
<https://starwars.com#planet_Blimph> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#planet_Blimph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Blimph> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#009bb290-ac6e-410d-ae07-6d6c33db8570> .
<https://starwars.com#009bb290-ac6e-410d-ae07-6d6c33db8570> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Blimph"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Blimph> <http://telicent.io/ontology/primaryName> "Blimph" .

