Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jazbina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Lostar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Jazbina> <http://www.w3.org/2000/01/rdf-schema#comment> "Jazbina was an astronomical object located in the galaxy's Expansion Region, positioned at the coordinates M-8 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Jazbina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .
<https://starwars.com#0af3a203-96a3-4b88-a13d-8255452ecbf6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jazbina"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Lostar> <http://telicent.io/ontology/primaryName> "Lostar" .
<https://starwars.com#sector_Lostar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jazbina> <http://telicent.io/ontology/primaryName> "Jazbina" .
<https://starwars.com#0af3a203-96a3-4b88-a13d-8255452ecbf6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jazbina> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0af3a203-96a3-4b88-a13d-8255452ecbf6> .
<https://starwars.com#planet_Jazbina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lostar> .

