Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dentaal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce14a231-da8c-4fa1-9543-f1a4f1809f3b> .
<https://starwars.com#planet_Dentaal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dentaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Dentaal> <http://telicent.io/ontology/primaryName> "Dentaal" .
<https://starwars.com#planet_Dentaal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#ce14a231-da8c-4fa1-9543-f1a4f1809f3b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dentaal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ce14a231-da8c-4fa1-9543-f1a4f1809f3b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dentaal> <http://www.w3.org/2000/01/rdf-schema#comment> "Dentaal was an astronomical object located in the galaxy's Core Worlds along the Rimma Trade Route. " .

