Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ahakista> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Myto> .
<https://starwars.com#planet_Ahakista> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_K3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_K3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5811a52a-61ee-4d7a-a68b-ca082de3042c> .
<https://starwars.com#planet_Ahakista> <http://www.w3.org/2000/01/rdf-schema#comment> "Ahakista was a location in the Ahakista system where the Daystar Casino was built. The Dug gambler Gronson Takkaro, who at one point worked as operations manager of the casino, fell into large amounts of debt on Ahakista and fled to the planet Lothal. The bounty hunter Bossk tracked Takkaro down to Lothal in order to capture him and bring him back to Ahakista to claim a bounty placed on the Dug. " .
<https://starwars.com#planet_Ahakista> <http://telicent.io/ontology/primaryName> "Ahakista" .
<https://starwars.com#e5e75574-3d65-49c2-a7b8-242b15062867> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5811a52a-61ee-4d7a-a68b-ca082de3042c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#e5e75574-3d65-49c2-a7b8-242b15062867> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ahakista"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K3> <http://telicent.io/ontology/primaryName> "K3" .
<https://starwars.com#5811a52a-61ee-4d7a-a68b-ca082de3042c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ahakista> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#sector_Myto> <http://telicent.io/ontology/primaryName> "Myto" .
<https://starwars.com#sector_Myto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ahakista> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e5e75574-3d65-49c2-a7b8-242b15062867> .
<https://starwars.com#sector_Myto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_K3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

