Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Lantillian> <http://telicent.io/ontology/primaryName> "Lantillian" .
<https://starwars.com#52d72e88-37ae-47b2-aae0-9cb5d4bcec95> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Avenelle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lantillian> .
<https://starwars.com#sector_Lantillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Avenelle> <http://www.w3.org/2000/01/rdf-schema#comment> "Avenelle was a planet in the Lantillian sector. It was a luxurious world known as a place to rest while traveling along the Lesser Lantillian Route or for retirement. " .
<https://starwars.com#grid_P9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#52d72e88-37ae-47b2-aae0-9cb5d4bcec95> .
<https://starwars.com#grid_P9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#2b191b78-a102-4384-9b7b-935a839117e7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Avenelle> <http://telicent.io/ontology/primaryName> "Avenelle" .
<https://starwars.com#2b191b78-a102-4384-9b7b-935a839117e7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Avenelle"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P9> <http://telicent.io/ontology/primaryName> "P9" .
<https://starwars.com#planet_Avenelle> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2b191b78-a102-4384-9b7b-935a839117e7> .
<https://starwars.com#52d72e88-37ae-47b2-aae0-9cb5d4bcec95> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Avenelle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#sector_Lantillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Avenelle> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_P9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

