Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f1377854-aec4-4cc7-a4c7-190c96b6ac9d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Trianii> <http://telicent.io/ontology/primaryName> "Trianii" .
<https://starwars.com#planet_Trian> <http://www.w3.org/2000/01/rdf-schema#comment> "Trian was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Trian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f1377854-aec4-4cc7-a4c7-190c96b6ac9d> .
<https://starwars.com#sector_Trianii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Trian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trian> <http://telicent.io/ontology/primaryName> "Trian" .
<https://starwars.com#planet_Trian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#f1377854-aec4-4cc7-a4c7-190c96b6ac9d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trianii> .
<https://starwars.com#sector_Trianii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .

