Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hosrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hosrel> <http://telicent.io/ontology/primaryName> "Hosrel" .
<https://starwars.com#1b61b96e-0f49-4359-8ed8-90cbbd8ebedf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hosrel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hosrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#1b61b96e-0f49-4359-8ed8-90cbbd8ebedf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hosrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#planet_Hosrel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1b61b96e-0f49-4359-8ed8-90cbbd8ebedf> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Hosrel> <http://www.w3.org/2000/01/rdf-schema#comment> "Hosrel was the Hosrel system's primary star, located within the Outer Rim Territories of the galaxy. " .

