Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bastion> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#16c3ec6c-4121-4d89-bc6d-c2cca3a8e6cd> .
<https://starwars.com#planet_Bastion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#16c3ec6c-4121-4d89-bc6d-c2cca3a8e6cd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bastion> <http://telicent.io/ontology/primaryName> "Bastion" .
<https://starwars.com#planet_Bastion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#planet_Bastion> <http://www.w3.org/2000/01/rdf-schema#comment> "Bastion was an industrialized planet located in the Outer Rim Territories of the galaxy. Also part of the New Territories, it was connected via hyperspace route to Anthan Prime. " .
<https://starwars.com#16c3ec6c-4121-4d89-bc6d-c2cca3a8e6cd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bastion"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Braxant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Braxant> <http://telicent.io/ontology/primaryName> "Braxant" .
<https://starwars.com#sector_Braxant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bastion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Braxant> .

