Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_Fodro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ff37a8c9-bc0d-4480-81ae-984b7632d905> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Fodro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .
<https://starwars.com#planet_Fodro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ff37a8c9-bc0d-4480-81ae-984b7632d905> .
<https://starwars.com#planet_Fodro> <http://www.w3.org/2000/01/rdf-schema#comment> "Fodro was an Outer Rim Territories planet located in the Clacis sector, on the Braxant Run hyperlane. During the Galactic Civil War, it served as the endpoint of the Dahvil-Fodro Hyperspace Promenade, a popular interstellar racing route. The racer Siro Simito once participated in the race, during which he estimated that his rival, Seeg, would arrive at Fodro several hours earlier than himself. Fodro later fell within the borders of the Pentastar Alignment. " .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#ff37a8c9-bc0d-4480-81ae-984b7632d905> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fodro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fodro> <http://telicent.io/ontology/primaryName> "Fodro" .
<https://starwars.com#planet_Fodro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .

