Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Perkell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Trancret> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#planet_Trancret> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Perkell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Trancret> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#18ca1186-8d46-4503-8d83-93be9eead5a9> .
<https://starwars.com#planet_Trancret> <http://www.w3.org/2000/01/rdf-schema#comment> "Trancret was a planet in the Trancret system and the sector capital of the Perkell sector. It was home to the Human Trancretes. The Trancret Stock Exchange Swindle was pulled off by the Red & Black League of Herstell V. " .
<https://starwars.com#planet_Trancret> <http://telicent.io/ontology/primaryName> "Trancret" .
<https://starwars.com#18ca1186-8d46-4503-8d83-93be9eead5a9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#18ca1186-8d46-4503-8d83-93be9eead5a9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trancret"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Perkell> <http://telicent.io/ontology/primaryName> "Perkell" .
<https://starwars.com#planet_Trancret> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Perkell> .

