Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#planet_IsdeNaha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#planet_IsdeNaha> <http://telicent.io/ontology/primaryName> "Isde Naha" .
<https://starwars.com#planet_IsdeNaha> <http://www.w3.org/2000/01/rdf-schema#comment> "Isde Naha was a world trailing on the Outer Rim edge of the Western Reaches. It was home to the Clan of the Toribota, a nomadic enclave. " .
<https://starwars.com#planet_IsdeNaha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_IsdeNaha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3b1c05cc-b531-4d2e-8fd2-796e2b5c55fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Isde Naha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_IsdeNaha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b1c05cc-b531-4d2e-8fd2-796e2b5c55fa> .
<https://starwars.com#3b1c05cc-b531-4d2e-8fd2-796e2b5c55fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

