Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#edbf0ca7-1b8a-4c81-b9ae-ce218d5dbda4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kriz> <http://telicent.io/ontology/primaryName> "Kriz" .
<https://starwars.com#planet_Taul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#edbf0ca7-1b8a-4c81-b9ae-ce218d5dbda4> .
<https://starwars.com#sector_Kriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Taul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Taul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J18> .
<https://starwars.com#planet_Taul> <http://telicent.io/ontology/primaryName> "Taul" .
<https://starwars.com#sector_Kriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Taul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kriz> .
<https://starwars.com#edbf0ca7-1b8a-4c81-b9ae-ce218d5dbda4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Taul> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .

