Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Meridian> <http://telicent.io/ontology/primaryName> "Meridian" .
<https://starwars.com#planet_NamChorios> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Meridian> .
<https://starwars.com#c842bea9-8b0d-4ecd-9272-a79e9562ab3d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nam Chorios"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NamChorios> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c842bea9-8b0d-4ecd-9272-a79e9562ab3d> .
<https://starwars.com#planet_NamChorios> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_NamChorios> <http://telicent.io/ontology/primaryName> "Nam Chorios" .
<https://starwars.com#sector_Meridian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#c842bea9-8b0d-4ecd-9272-a79e9562ab3d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Meridian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NamChorios> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_NamChorios> <http://www.w3.org/2000/01/rdf-schema#comment> "Nam Chorios was a planet located in the galaxy's Outer Rim Territories that housed both an Imperial mining colony and prison facility by the fifth year of Darth Sidious' reign as Emperor. The primary star in its planetary system provided barely enough sunshine to illuminate Nam Chorios properly, conferring it a bleak appearance. For that reason, Nam Chorios was considered too cold and unwelcoming by human standards. " .

