Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Condular> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7c624f54-f536-4297-965e-6ca3eb955f5b> .
<https://starwars.com#planet_Condular> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#7c624f54-f536-4297-965e-6ca3eb955f5b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Condular"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Condular> <http://telicent.io/ontology/primaryName> "Condular" .
<https://starwars.com#planet_Condular> <http://www.w3.org/2000/01/rdf-schema#comment> "Condular was a planet of the Core Worlds and was home to the Grand Astrocartographic Institute. " .
<https://starwars.com#planet_Condular> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#7c624f54-f536-4297-965e-6ca3eb955f5b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Condular> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

