Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Obredaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Irishi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Obredaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3756aa63-ca04-45ab-9be5-f788abbe76c9> .
<https://starwars.com#planet_Obredaan> <http://telicent.io/ontology/primaryName> "Obredaan" .
<https://starwars.com#planet_Obredaan> <http://www.w3.org/2000/01/rdf-schema#comment> "After the Orinda campaign in the Galactic Civil War the planet became the last major stopping point before entering the Imperial Space on the Entralla Route. Thus the New Republic hosted its military presence here just in case an invasion would be imminent. " .
<https://starwars.com#planet_Obredaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#3756aa63-ca04-45ab-9be5-f788abbe76c9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3756aa63-ca04-45ab-9be5-f788abbe76c9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Obredaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Obredaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Irishi> .
<https://starwars.com#sector_Irishi> <http://telicent.io/ontology/primaryName> "Irishi" .
<https://starwars.com#sector_Irishi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

