Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Havricus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fed29afb-eda6-4a94-8e7d-978304162e3e> .
<https://starwars.com#planet_Havricus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Havricus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#fed29afb-eda6-4a94-8e7d-978304162e3e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Havricus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Havricus> <http://www.w3.org/2000/01/rdf-schema#comment> "Havricus was a Galactic Republic planet that was infested with stone mites in 22 BBY, prior to the Clone Wars. " .
<https://starwars.com#planet_Havricus> <http://telicent.io/ontology/primaryName> "Havricus" .
<https://starwars.com#fed29afb-eda6-4a94-8e7d-978304162e3e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Havricus"^^<http://www.w3.org/2001/XMLSchema#string> .

