Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Grumani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Grumani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Verdanth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4e2b00b0-b692-42d0-b3ee-b70b9396e339> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Verdanth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4e2b00b0-b692-42d0-b3ee-b70b9396e339> .
<https://starwars.com#4e2b00b0-b692-42d0-b3ee-b70b9396e339> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Verdanth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Grumani> <http://telicent.io/ontology/primaryName> "Grumani" .
<https://starwars.com#planet_Verdanth> <http://www.w3.org/2000/01/rdf-schema#comment> "Verdanth was a rainforest planet in the Verdanth system. It was located on a strategic position on the Duros Space Run and the Sanrafsix Corridor and near the intersection of the Grumani, Sanbra, and Bon'nyuw-Luq sectors. Verdanth's indigenous species included rimebats. During the New Sith Wars, the planet was frequently fought over by Sith Lords, while, during the Galactic Civil War, Darth Vader tried and failed to capture Luke Skywalker on the world. " .
<https://starwars.com#planet_Verdanth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#planet_Verdanth> <http://telicent.io/ontology/primaryName> "Verdanth" .
<https://starwars.com#planet_Verdanth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Grumani> .

