Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kardura> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#bd191a65-c19b-47e3-ab89-923439c1edb2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kardura"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kardura> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bd191a65-c19b-47e3-ab89-923439c1edb2> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kardura> <http://telicent.io/ontology/primaryName> "Kardura" .
<https://starwars.com#planet_Kardura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Kardura> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Kardura> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#bd191a65-c19b-47e3-ab89-923439c1edb2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

