Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Reuss> <http://www.w3.org/2000/01/rdf-schema#comment> "Reuss was an astronomical object in the Outer Rim Territories of the galaxy, linked to Socorro and Spice Terminus by hyperspace routes. It was positioned at the coordinates P-18 on the Standard Galactic Grid. " .
<https://starwars.com#sector_Corric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Corric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3c87f493-66b9-4a29-aab3-00598bd3c128> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Reuss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P18> .
<https://starwars.com#3c87f493-66b9-4a29-aab3-00598bd3c128> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Reuss"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Corric> <http://telicent.io/ontology/primaryName> "Cor'ric" .
<https://starwars.com#planet_Reuss> <http://telicent.io/ontology/primaryName> "Reuss" .
<https://starwars.com#planet_Reuss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corric> .
<https://starwars.com#planet_Reuss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Reuss> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c87f493-66b9-4a29-aab3-00598bd3c128> .

