Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#da181960-718a-4146-a652-b2802395eb41> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Quess> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Trevi> <http://www.w3.org/2000/01/rdf-schema#comment> "Two decades before the Galactic Civil War, the Bith Fiz Cor'gril arrived on Trevi IV, bought an old garage complex in Trevi City, and established the used starship dealership known as Fizzi's Slightly Used Starships. By the time of the Galactic Civil War, the Galactic Empire maintained a token presence on the planet in the form of a small post outside Trevi City. " .
<https://starwars.com#planet_Trevi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Trevi> <http://telicent.io/ontology/primaryName> "Trevi" .
<https://starwars.com#sector_Quess> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Trevi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quess> .
<https://starwars.com#planet_Trevi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#da181960-718a-4146-a652-b2802395eb41> .
<https://starwars.com#da181960-718a-4146-a652-b2802395eb41> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trevi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trevi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N17> .
<https://starwars.com#sector_Quess> <http://telicent.io/ontology/primaryName> "Quess" .

