Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mirial> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Mirial> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_I-Sector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mirial> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#322e9010-e35e-4fe7-a607-280e6d23aca1> .
<https://starwars.com#planet_Mirial> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_I-Sector> .
<https://starwars.com#sector_I-Sector> <http://telicent.io/ontology/primaryName> "I-Sector" .
<https://starwars.com#322e9010-e35e-4fe7-a607-280e6d23aca1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#322e9010-e35e-4fe7-a607-280e6d23aca1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mirial"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mirial> <http://telicent.io/ontology/primaryName> "Mirial" .
<https://starwars.com#sector_I-Sector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mirial> <http://www.w3.org/2000/01/rdf-schema#comment> "Mirial was a cold and dry desert planet located in the Mirial system of the Outer Rim Territories. It was the homeworld of the near-human Mirialan species, including Jedi Master Luminara Unduli and her Padawan Barriss Offee. Unduli honored the traditions of the world by selecting a fellow Mirialan as her apprentice. " .

