Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Malagarr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#60a120d5-4a8b-4f80-9b20-a2c11f036656> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Malagarr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Malagarr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_V8> .
<https://starwars.com#planet_Malagarr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Malagarr> <http://telicent.io/ontology/primaryName> "Malagarr" .
<https://starwars.com#60a120d5-4a8b-4f80-9b20-a2c11f036656> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Malagarr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#60a120d5-4a8b-4f80-9b20-a2c11f036656> .
<https://starwars.com#grid_V8> <http://telicent.io/ontology/primaryName> "V8" .
<https://starwars.com#14c0e621-5dfa-4312-8b82-76dfa205035f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "V8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_V8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_V8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#14c0e621-5dfa-4312-8b82-76dfa205035f> .
<https://starwars.com#14c0e621-5dfa-4312-8b82-76dfa205035f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Malagarr> <http://www.w3.org/2000/01/rdf-schema#comment> "Malagarr was an astronomical object located within the galaxy's Outer Rim Territories. " .
<https://starwars.com#grid_V8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

