Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_RimceeStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6178b70a-8795-4504-bb71-34fb8834b805> .
<https://starwars.com#planet_RimceeStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Rimcee Station was an Imperial space station in the Rimcee system. In 19 ABY it was the location of imprisonment of Fleet Admiral Gilad Pellaeon's aide, Colonel Meizh Vermel, who had been captured by order of Moff Disra in his attempt to foil Pellaeon's peace proposal. " .
<https://starwars.com#planet_RimceeStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J3> .
<https://starwars.com#6178b70a-8795-4504-bb71-34fb8834b805> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RimceeStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_RimceeStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Braxant> .
<https://starwars.com#planet_RimceeStation> <http://telicent.io/ontology/primaryName> "Rimcee Station" .
<https://starwars.com#6178b70a-8795-4504-bb71-34fb8834b805> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rimcee Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Braxant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Braxant> <http://telicent.io/ontology/primaryName> "Braxant" .
<https://starwars.com#sector_Braxant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

