Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ef753064-742e-422d-8fb8-db84dcf7c963> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Las Lagon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LasLagon> <http://www.w3.org/2000/01/rdf-schema#comment> "A planet in the Galactic Alliance Senate composition, Las Lagon seceded from the Galactic Alliance during the Second Galactic Civil War. " .
<https://starwars.com#planet_LasLagon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_LasLagon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#ef753064-742e-422d-8fb8-db84dcf7c963> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_LasLagon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_LasLagon> <http://telicent.io/ontology/primaryName> "Las Lagon" .
<https://starwars.com#planet_LasLagon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef753064-742e-422d-8fb8-db84dcf7c963> .

