Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vensensor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#929bd34c-fd7e-42c5-90ae-9dc96ce9d309> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sarrish"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sarrish> <http://telicent.io/ontology/primaryName> "Sarrish" .
<https://starwars.com#planet_Sarrish> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#929bd34c-fd7e-42c5-90ae-9dc96ce9d309> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sarrish> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#929bd34c-fd7e-42c5-90ae-9dc96ce9d309> .
<https://starwars.com#sector_Vensensor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegions> .
<https://starwars.com#planet_Sarrish> <http://www.w3.org/2000/01/rdf-schema#comment> "Sarrish was a planet where the Battle of Sarrish took place during the Clone Wars. The Galactic Republic lost the battle and suffered tremendous casualties, and it was considered a devastating loss. " .
<https://starwars.com#sector_Vensensor> <http://telicent.io/ontology/primaryName> "Vensensor" .
<https://starwars.com#planet_Sarrish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vensensor> .
<https://starwars.com#planet_Sarrish> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .

