Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NZoth> <http://www.w3.org/2000/01/rdf-schema#comment> "N'Zoth was a planet located in the Koornacht Cluster in the galaxy's Core Worlds. On the periphery of the Deep Core, it was connected via hyperspace route to Jedha and Coruscant. " .
<https://starwars.com#planet_NZoth> <http://telicent.io/ontology/primaryName> "N'Zoth" .
<https://starwars.com#planet_NZoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#40fc1eec-462d-41d2-8ad1-003c8e5fedc2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NZoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_NZoth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#40fc1eec-462d-41d2-8ad1-003c8e5fedc2> .
<https://starwars.com#planet_NZoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#40fc1eec-462d-41d2-8ad1-003c8e5fedc2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N'Zoth"^^<http://www.w3.org/2001/XMLSchema#string> .

