Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e36ab47e-7e01-46fc-9a70-3038f6d4988e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Endor Gate"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_EndorGate> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e36ab47e-7e01-46fc-9a70-3038f6d4988e> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_EndorGate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#e36ab47e-7e01-46fc-9a70-3038f6d4988e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_EndorGate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_EndorGate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_EndorGate> <http://www.w3.org/2000/01/rdf-schema#comment> "The Endor Gate was a black hole located near Endor, in the Moddell sector of the Outer Rim Territories. One of many spatial anomalies found in the area, it could easily destroy a starship or throw it off course way past Endor, out into Wild Space or the Unknown Regions. " .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_EndorGate> <http://telicent.io/ontology/primaryName> "Endor Gate" .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

