Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hoylin> <http://telicent.io/ontology/primaryName> "Hoylin" .
<https://starwars.com#f8ea0420-f3a6-48f3-9eb1-3a674d88e849> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_FelHu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Hoylin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P13> .
<https://starwars.com#sector_FelHu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hoylin> <http://www.w3.org/2000/01/rdf-schema#comment> "Hoylin was a world located in the Hoylin system, a part of the Fei Hu sector in the Slice portion of the Mid Rim. It was situated on the Gamor Run hyperlane, which connected it to the Aikhibba and Beris systems. " .
<https://starwars.com#planet_Hoylin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f8ea0420-f3a6-48f3-9eb1-3a674d88e849> .
<https://starwars.com#planet_Hoylin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hoylin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FelHu> .
<https://starwars.com#sector_FelHu> <http://telicent.io/ontology/primaryName> "Fel Hu" .
<https://starwars.com#f8ea0420-f3a6-48f3-9eb1-3a674d88e849> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hoylin"^^<http://www.w3.org/2001/XMLSchema#string> .

