Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Farstone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Farstone> <http://www.w3.org/2000/01/rdf-schema#comment> "Farstone was a world located in the Farstone system of the Juvex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. A hyperlane connected Farstone to the Umthyg system. " .
<https://starwars.com#20f53140-8111-4291-86cb-58679e02abc8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#20f53140-8111-4291-86cb-58679e02abc8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Farstone"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Farstone> <http://telicent.io/ontology/primaryName> "Farstone" .
<https://starwars.com#planet_Farstone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Farstone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Farstone> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#20f53140-8111-4291-86cb-58679e02abc8> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

