Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Station88> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#31061dee-b3c3-44a1-9d56-0f9054b15963> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Station 88"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Station88> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31061dee-b3c3-44a1-9d56-0f9054b15963> .
<https://starwars.com#sector_Vorc> <http://telicent.io/ontology/primaryName> "Vorc" .
<https://starwars.com#31061dee-b3c3-44a1-9d56-0f9054b15963> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Vorc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Vorc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Station88> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vorc> .
<https://starwars.com#planet_Station88> <http://telicent.io/ontology/primaryName> "Station 88" .
<https://starwars.com#planet_Station88> <http://www.w3.org/2000/01/rdf-schema#comment> "The Station 88 Spaceport, or simply Station 88, was a large spaceport founded by the rulers of Delaluna, Junction V, Bezim and the Vicondor systems. Located along the Celanon Spur in the Mid Rim's Vorc sector, it was a key strategic area for the Confederacy of Independent Systems, for it was the gateway to the Mid Rim star systems. " .
<https://starwars.com#planet_Station88> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .

