Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_M15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f70109ad-eb4d-4922-a28a-ec8d81cdac56> .
<https://starwars.com#sector_Boeus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#grid_M15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Boeus> <http://telicent.io/ontology/primaryName> "Boeus" .
<https://starwars.com#planet_Droecil> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95b5d705-9a62-45e4-950b-6079947df8b5> .
<https://starwars.com#95b5d705-9a62-45e4-950b-6079947df8b5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Droecil"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f70109ad-eb4d-4922-a28a-ec8d81cdac56> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Droecil> <http://www.w3.org/2000/01/rdf-schema#comment> "Droecil was a planet home to a Rebel Alliance cell. " .
<https://starwars.com#f70109ad-eb4d-4922-a28a-ec8d81cdac56> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Droecil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Droecil> <http://telicent.io/ontology/primaryName> "Droecil" .
<https://starwars.com#95b5d705-9a62-45e4-950b-6079947df8b5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Droecil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M15> .
<https://starwars.com#planet_Droecil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Boeus> .
<https://starwars.com#grid_M15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M15> <http://telicent.io/ontology/primaryName> "M15" .
<https://starwars.com#sector_Boeus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

