Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hiit> <http://www.w3.org/2000/01/rdf-schema#comment> "Hiit was a desolate moon which orbited the gas giant of Maal. It was located at the intersection of the Authority Guardian Corridor and the Trianii Shunt, in space annexed by the Corporate Sector in 5 BBY. " .
<https://starwars.com#planet_Hiit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a1cbdce1-a61e-41cf-95a7-7020e9f74c22> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Hiit> <http://telicent.io/ontology/primaryName> "Hiit" .
<https://starwars.com#planet_Hiit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#a1cbdce1-a61e-41cf-95a7-7020e9f74c22> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hiit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hiit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a1cbdce1-a61e-41cf-95a7-7020e9f74c22> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hiit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

