Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Khubeaie> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f828666b-dcf0-4206-9ff5-2a1702e20951> .
<https://starwars.com#f828666b-dcf0-4206-9ff5-2a1702e20951> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Khubeaie> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#f828666b-dcf0-4206-9ff5-2a1702e20951> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Khubeaie"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Khubeaie> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Khubeaie> <http://www.w3.org/2000/01/rdf-schema#comment> "Khubeaie was an industrial world that was located within the Arkanis sector of the galaxy's Outer Rim Territories region. The planet lay on the hyperlanes called the Old Corellian Run and the Vaschean Way, and it was better known as a stopover for spice smugglers. Members of such species as Humans, Hutts, Rodians and Twi'leks could all be encountered on Khubeaie. " .
<https://starwars.com#planet_Khubeaie> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Khubeaie> <http://telicent.io/ontology/primaryName> "Khubeaie" .

