Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_TheMaw> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_TheMaw> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c254dd28-7403-4a81-814f-250f6e2c3263> .
<https://starwars.com#planet_TheMaw> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c254dd28-7403-4a81-814f-250f6e2c3263> <http://ies.data.gov.uk/ontology/ies4#representationValue> "The Maw"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_TheMaw> <http://telicent.io/ontology/primaryName> "The Maw" .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#planet_TheMaw> <http://www.w3.org/2000/01/rdf-schema#comment> "The stability of the cluster itself was something of a mystery, with some believing that an advanced civilization might have constructed it, rather than it merging together like a normal cluster would. In 44 ABY, the Jedi Order learned from the Thuruht hive that the Maw was created by Thuruht and other Killik hives to serve as a prison for the dark side entity Abeloth. Under the direction of the Son and Daughter (who had joined the hivemind), the Killiks created Centerpoint Station and Sinkhole Station. Centerpoint was used by The Ones to create the Maw itself, while Sinkhole Station was built to maintain the prison from within. " .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c254dd28-7403-4a81-814f-250f6e2c3263> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_TheMaw> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .

