Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_Q6> <http://telicent.io/ontology/primaryName> "Q6" .
<https://starwars.com#grid_Q6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Arda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cad44fe1-a892-44fe-96b8-8106f589e119> .
<https://starwars.com#planet_Arda> <http://www.w3.org/2000/01/rdf-schema#comment> "Arda was an astronomical object located in the Gordian Reach of the regions known as the Outer Rim Territories and New Territories. The celestial body was situated in grid square Q-6 on the Standard Galactic Grid. " .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Arda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Arda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#8bbef028-de21-4db1-a935-a48ea6fdc113> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_Q6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Arda> <http://telicent.io/ontology/primaryName> "Arda" .
<https://starwars.com#cad44fe1-a892-44fe-96b8-8106f589e119> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#8bbef028-de21-4db1-a935-a48ea6fdc113> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#cad44fe1-a892-44fe-96b8-8106f589e119> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#grid_Q6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8bbef028-de21-4db1-a935-a48ea6fdc113> .

