Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Farstine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P17> .
<https://starwars.com#sector_Ryndellian> <http://telicent.io/ontology/primaryName> "Ryndellian" .
<https://starwars.com#268a0933-0e9b-47b1-879d-f994fa4e36fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#268a0933-0e9b-47b1-879d-f994fa4e36fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Farstine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Ryndellian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Farstine> <http://telicent.io/ontology/primaryName> "Farstine" .
<https://starwars.com#planet_Farstine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Ryndellian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Farstine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ryndellian> .
<https://starwars.com#planet_Farstine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#268a0933-0e9b-47b1-879d-f994fa4e36fc> .
<https://starwars.com#planet_Farstine> <http://www.w3.org/2000/01/rdf-schema#comment> "Farstine was an astronomical object located in the galaxy's Mid Rim. " .

