Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Scipio> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#272980e5-7c6e-4ac6-ab28-8cf03946242d> .
<https://starwars.com#272980e5-7c6e-4ac6-ab28-8cf03946242d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Scipio"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Scipio> <http://telicent.io/ontology/primaryName> "Scipio" .
<https://starwars.com#planet_Scipio> <http://www.w3.org/2000/01/rdf-schema#comment> "Scipio was an ice-covered planet located in the galaxy's Outer Rim Territories. It was positioned in the Albarrio system, and served as the headquarters of the InterGalactic Banking Clan. " .
<https://starwars.com#planet_Scipio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#272980e5-7c6e-4ac6-ab28-8cf03946242d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Scipio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Scipio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

