Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vallt> <http://www.w3.org/2000/01/rdf-schema#comment> "Galen Erso and his team were working on Vallt for Zerpen Industries when the Vallt government was overthrown in a coup by those sympathetic to the Separatist movement. This led to Erso quickly being thrown into Tambolor prison on charges of espionage. The planet thus shifted from being a Republic–aligned planet to a Separatist one during this period. " .
<https://starwars.com#planet_Vallt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vallt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#eb910282-3db6-4d11-ab5b-efc6df46601b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vallt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vallt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eb910282-3db6-4d11-ab5b-efc6df46601b> .
<https://starwars.com#planet_Vallt> <http://telicent.io/ontology/primaryName> "Vallt" .
<https://starwars.com#eb910282-3db6-4d11-ab5b-efc6df46601b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

