Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Seswenna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#2cd8d75a-7ab9-43b0-aa5c-eb97d3fc349a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Seswenna> <http://telicent.io/ontology/primaryName> "Seswenna" .
<https://starwars.com#2cd8d75a-7ab9-43b0-aa5c-eb97d3fc349a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Seswenna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Averam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Seswenna> .
<https://starwars.com#planet_Averam> <http://telicent.io/ontology/primaryName> "Averam" .
<https://starwars.com#planet_Averam> <http://www.w3.org/2000/01/rdf-schema#comment> "Averam was a planet in the Seswenna sector in the Outer Rim Territories. It was one of the few planets to openly sympathize with small groups of Rebel Alliance supporters early in the Galactic Civil War. " .
<https://starwars.com#planet_Averam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54da422a-209c-40ec-9a73-785f2d1826f2> .
<https://starwars.com#grid_M18> <http://telicent.io/ontology/primaryName> "M18" .
<https://starwars.com#grid_M18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#54da422a-209c-40ec-9a73-785f2d1826f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Averam"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Averam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Averam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#54da422a-209c-40ec-9a73-785f2d1826f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_M18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#2cd8d75a-7ab9-43b0-aa5c-eb97d3fc349a> .
<https://starwars.com#grid_M18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

