Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Pitrolea> <http://telicent.io/ontology/primaryName> "Pitrolea" .
<https://starwars.com#planet_Pitrolea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Pitrolea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#planet_Pitrolea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0f2fe8c8-f97e-45e2-bf58-c0a03bba6b06> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pitrolea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pitrolea> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#0f2fe8c8-f97e-45e2-bf58-c0a03bba6b06> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pitrolea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0f2fe8c8-f97e-45e2-bf58-c0a03bba6b06> .

