Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Xoman> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#sector_Halla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Xoman> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1c6b8cf3-faea-469c-96cf-1db0eb7757f1> .
<https://starwars.com#1c6b8cf3-faea-469c-96cf-1db0eb7757f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#1c6b8cf3-faea-469c-96cf-1db0eb7757f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xoman"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Xoman> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Xoman> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Halla> <http://telicent.io/ontology/primaryName> "Halla" .
<https://starwars.com#planet_Xoman> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halla> .
<https://starwars.com#sector_Halla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Xoman> <http://telicent.io/ontology/primaryName> "Xoman" .

