Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Danuta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halla> .
<https://starwars.com#sector_Halla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Halla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Danuta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4869f311-1efb-4142-b87f-a6b2315e10e9> .
<https://starwars.com#planet_Danuta> <http://www.w3.org/2000/01/rdf-schema#comment> "Danuta was a dull, barren brown planet in the Colavas system, thinly populated mostly by miners and hardscrabble farmers. Trid was the planet's de facto capital. " .
<https://starwars.com#planet_Danuta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#4869f311-1efb-4142-b87f-a6b2315e10e9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Danuta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Halla> <http://telicent.io/ontology/primaryName> "Halla" .
<https://starwars.com#planet_Danuta> <http://telicent.io/ontology/primaryName> "Danuta" .
<https://starwars.com#planet_Danuta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4869f311-1efb-4142-b87f-a6b2315e10e9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

