Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Telos> <http://telicent.io/ontology/primaryName> "Telos" .
<https://starwars.com#planet_Telos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#831a6406-1a6a-4cb5-9d59-4db1d55dcdec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kwymar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Telos> <http://www.w3.org/2000/01/rdf-schema#comment> "Telos was an astronomical object located in the galaxy's Outer Rim Territories, along the Hydian Way. During the campaign at Salient, an Imperial battle group was stationed at Telos under the command of Admiral Utu. Moff Wilhuff Tarkin requested that Utu dispatch whatever vessels she could spare from Telos to Salient, and was later informed by a commander that Utu hoped to send two Star Destroyers. " .
<https://starwars.com#sector_Kwymar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#831a6406-1a6a-4cb5-9d59-4db1d55dcdec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Telos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Telos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#831a6406-1a6a-4cb5-9d59-4db1d55dcdec> .
<https://starwars.com#sector_Kwymar> <http://telicent.io/ontology/primaryName> "Kwymar" .
<https://starwars.com#planet_Telos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kwymar> .
<https://starwars.com#planet_Telos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

