Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ba677e34-03c1-4c50-a888-d290430b7414> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Namadii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ba677e34-03c1-4c50-a888-d290430b7414> .
<https://starwars.com#ba677e34-03c1-4c50-a888-d290430b7414> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Namadii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Churnis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Namadii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churnis> .
<https://starwars.com#planet_Namadii> <http://telicent.io/ontology/primaryName> "Namadii" .
<https://starwars.com#sector_Churnis> <http://telicent.io/ontology/primaryName> "Churnis" .
<https://starwars.com#sector_Churnis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Namadii> <http://www.w3.org/2000/01/rdf-schema#comment> "Namadii was a Mid Rim astronomical object located in grid square I-6 of the Standard Galactic Grid. It was linked by a hyperspace route to the celestial body Ansion and shared its name with the Namadii Corridor, a route along which the Core Worlds planet Coruscant was situated. " .
<https://starwars.com#planet_Namadii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Namadii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I6> .

