Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#182aa710-41ce-4728-b26b-018d52144c15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_FeswePrime> <http://telicent.io/ontology/primaryName> "Feswe Prime" .
<https://starwars.com#planet_FeswePrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_FeswePrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Feswe Prime was a star located within the Gordian Reach of the Outer Rim Territories. " .
<https://starwars.com#planet_FeswePrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#182aa710-41ce-4728-b26b-018d52144c15> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Feswe Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_FeswePrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#182aa710-41ce-4728-b26b-018d52144c15> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_FeswePrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

