Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rorak> <http://www.w3.org/2000/01/rdf-schema#comment> "Rorak was an astronomical object located in the Hutt Space region of the galaxy. It was connected to Ylesia, Nal Hutta and Circumtore, also of Hutt Space, by hyperspace routes. Rorak was located at galactic coordinates S-12. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rorak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#planet_Rorak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Rorak> <http://telicent.io/ontology/primaryName> "Rorak" .
<https://starwars.com#3eac39ed-5b87-4806-b810-48cfb80e355b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rorak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#3eac39ed-5b87-4806-b810-48cfb80e355b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rorak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3eac39ed-5b87-4806-b810-48cfb80e355b> .
<https://starwars.com#planet_Rorak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

