Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MHanna> <http://telicent.io/ontology/primaryName> "M'Hanna" .
<https://starwars.com#planet_MHanna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_MHanna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#10a25c39-e7b8-4a3b-9c1d-f8f48e550a27> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MHanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#10a25c39-e7b8-4a3b-9c1d-f8f48e550a27> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M'Hanna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MHanna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T11> .
<https://starwars.com#10a25c39-e7b8-4a3b-9c1d-f8f48e550a27> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_MHanna> <http://www.w3.org/2000/01/rdf-schema#comment> "M'Hanna was a desolate planet that was located within the M'Hanna system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet was connected to the worlds of Tisht and Varl by the hyperlane called The Dead Road, while the Elgit–M'Hanna Corridor linked M'Hanna to the planet of Sakifwanna. M'Hanna was a world of black dust that was scoured by supersonic winds, and its history was the subject of various rumors and legends. " .

