Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c7a18738-7556-4daa-956e-536186eef401> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dorlo> <http://www.w3.org/2000/01/rdf-schema#comment> "Dorlo was a planet located in the Atravis sector of the Outer Rim Territories and was controlled by the Galactic Empire. " .
<https://starwars.com#c7a18738-7556-4daa-956e-536186eef401> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dorlo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dorlo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c7a18738-7556-4daa-956e-536186eef401> .
<https://starwars.com#sector_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#planet_Dorlo> <http://telicent.io/ontology/primaryName> "Dorlo" .
<https://starwars.com#planet_Dorlo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Dorlo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L19> .
<https://starwars.com#planet_Dorlo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atravis> .

