Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Ojoster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3d020bfd-c116-44fb-b5fd-74a9453125c3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Taris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#planet_Taris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ojoster> .
<https://starwars.com#planet_Taris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Taris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d020bfd-c116-44fb-b5fd-74a9453125c3> .
<https://starwars.com#sector_Ojoster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3d020bfd-c116-44fb-b5fd-74a9453125c3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Taris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Taris> <http://www.w3.org/2000/01/rdf-schema#comment> "Taris was a polluted urban planet located in the Outer Rim. Although Taris was a heavily populated ecumenopolis, much of the surface itself was polluted with wrecked starships and dense, overgrown swamps. Makeshift tenements made of shipping containers and crashed starships stacked on top of one another, while yellow smog drifted in the atmosphere. The elite of the planet dwelled in nicer skyscrapers. " .
<https://starwars.com#planet_Taris> <http://telicent.io/ontology/primaryName> "Taris" .
<https://starwars.com#sector_Ojoster> <http://telicent.io/ontology/primaryName> "Ojoster" .

