Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorNasirii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorNasirii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#695fe320-3f4b-43ad-b4ec-671ad780076b> .
<https://starwars.com#planet_KorNasirii> <http://telicent.io/ontology/primaryName> "Kor Nasirii" .
<https://starwars.com#695fe320-3f4b-43ad-b4ec-671ad780076b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorNasirii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#695fe320-3f4b-43ad-b4ec-671ad780076b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Nasirii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorNasirii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Nasirii was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Nasirii kajidic. A hyperlane connected Kor Nasirii to the planet of Kor Vosadii. During the Cold War between the Galactic Republic and the resurgent Sith Empire in 3643 BBY, Kor Nasirii housed databases belonging to members of the Hutt species. The information contained within the databases was used to blackmail prominent figures throughout the galaxy. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_KorNasirii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .

