Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1cf8bef1-b03d-48ba-bb53-e5821a935e4c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Chasin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1cf8bef1-b03d-48ba-bb53-e5821a935e4c> .
<https://starwars.com#1cf8bef1-b03d-48ba-bb53-e5821a935e4c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chasin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chasin> <http://telicent.io/ontology/primaryName> "Chasin" .
<https://starwars.com#planet_Chasin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Chasin> <http://www.w3.org/2000/01/rdf-schema#comment> "Chasin was a planet of the Core Worlds. " .
<https://starwars.com#planet_Chasin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_Chasin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

