Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Ankus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Ankus> <http://telicent.io/ontology/primaryName> "Ankus" .
<https://starwars.com#planet_Ankus> <http://www.w3.org/2000/01/rdf-schema#comment> "Ankus was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e2397178-9d86-465f-be0f-e6af4a809147> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ca4373b9-0d6f-42f4-ba50-f7ea0d8ecffa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ankus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e2397178-9d86-465f-be0f-e6af4a809147> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_I7> <http://telicent.io/ontology/primaryName> "I7" .
<https://starwars.com#ca4373b9-0d6f-42f4-ba50-f7ea0d8ecffa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#e2397178-9d86-465f-be0f-e6af4a809147> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ankus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_I7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ca4373b9-0d6f-42f4-ba50-f7ea0d8ecffa> .
<https://starwars.com#planet_Ankus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ankus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#grid_I7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

