Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Donovia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f4ed4e31-b4d5-415d-b09e-444482c58f82> .
<https://starwars.com#sector_Hali> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Hali> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Donovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Donovia> <http://telicent.io/ontology/primaryName> "Donovia" .
<https://starwars.com#sector_Hali> <http://telicent.io/ontology/primaryName> "Hali" .
<https://starwars.com#planet_Donovia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Donovia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hali> .
<https://starwars.com#f4ed4e31-b4d5-415d-b09e-444482c58f82> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Donovia> <http://www.w3.org/2000/01/rdf-schema#comment> "Donovia was a rainy planet where mechanics known as Donovian rainmen maintained signal towers. During the Separatist Crisis, some rainmen who had left Donovia became freighter trampers and traveled on board the AA-9 Freighter-Liner Jendirian Valley as it carried refugees fleeing the crisis from the planet Coruscant to the planet Naboo in 22 BBY. " .
<https://starwars.com#f4ed4e31-b4d5-415d-b09e-444482c58f82> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Donovia"^^<http://www.w3.org/2001/XMLSchema#string> .

