Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Javin> <http://telicent.io/ontology/primaryName> "Javin" .
<https://starwars.com#sector_Javin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Varonat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6357ca10-f24e-4b99-aa6b-f3fc5e59b717> .
<https://starwars.com#planet_Varonat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Varonat> <http://www.w3.org/2000/01/rdf-schema#comment> "Varonat was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Javin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#6357ca10-f24e-4b99-aa6b-f3fc5e59b717> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#6357ca10-f24e-4b99-aa6b-f3fc5e59b717> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Varonat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Varonat> <http://telicent.io/ontology/primaryName> "Varonat" .
<https://starwars.com#planet_Varonat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Varonat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Javin> .

