Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Reecee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#64db1f77-973e-47a5-a268-4c48a62c86e4> .
<https://starwars.com#planet_Reecee> <http://www.w3.org/2000/01/rdf-schema#comment> "Reecee was an astronomical object in the galaxy's Inner Rim. " .
<https://starwars.com#planet_Reecee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Reecee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Reecee> <http://telicent.io/ontology/primaryName> "Reecee" .
<https://starwars.com#64db1f77-973e-47a5-a268-4c48a62c86e4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Reecee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#64db1f77-973e-47a5-a268-4c48a62c86e4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Reecee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .

