Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rindao> <http://www.w3.org/2000/01/rdf-schema#comment> "Rindao was a drab training station in the days of the Galactic Empire, close to the Outer Rim Territories. When the Empire arrived to take over the planet, the local populace had not resisted outright, and so avoided any significant persecution by the new regime. An exception to this was when an Imperial officer heard an old woman singing songs of the glorious days of the Galactic Republic and the Jedi Knights. The old woman was swiftly executed by blaster rifles for her perceived slur on the glory of the Empire. However, her legacy was continued through her granddaughter, Tionne Solusar, who saved her double viol and fled the planet. She later became a Jedi Knight herself. " .
<https://starwars.com#planet_Rindao> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rindao> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hadar> .
<https://starwars.com#sector_Hadar> <http://telicent.io/ontology/primaryName> "Hadar" .
<https://starwars.com#planet_Rindao> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#sector_Hadar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Rindao> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e4421877-385a-4519-870d-3e2682bb2f7e> .
<https://starwars.com#e4421877-385a-4519-870d-3e2682bb2f7e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#e4421877-385a-4519-870d-3e2682bb2f7e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rindao"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Hadar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rindao> <http://telicent.io/ontology/primaryName> "Rindao" .

