Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_L7> <http://telicent.io/ontology/primaryName> "L7" .
<https://starwars.com#planet_Aleen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#grid_L7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_L7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#6127a566-f9af-4b8d-886d-6a89cfce1228> .
<https://starwars.com#4c1c81fb-e6b6-404f-a79b-312e7e72ed5b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aleen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6127a566-f9af-4b8d-886d-6a89cfce1228> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aleen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .
<https://starwars.com#grid_L7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Aleen> <http://telicent.io/ontology/primaryName> "Aleen" .
<https://starwars.com#4c1c81fb-e6b6-404f-a79b-312e7e72ed5b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aleen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6127a566-f9af-4b8d-886d-6a89cfce1228> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Aleen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4c1c81fb-e6b6-404f-a79b-312e7e72ed5b> .
<https://starwars.com#planet_Aleen> <http://www.w3.org/2000/01/rdf-schema#comment> "Aleen was a rocky planet located within the Bright Jewel sector, of the galaxy's Mid Rim. It was home to the diminutive, surface-dwelling Aleena species, and a bioluminescent tree-like species, the Kindalo. At one point in their history, the two species clashed which almost resulted in the destruction of all sentient life on the planet. During the Clone Wars, the Galactic Republic arrived to help the Aleena rebuild after a series of devastating groundquakes. " .

