Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_AshasRee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_AshasRee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_AshasRee> <http://www.w3.org/2000/01/rdf-schema#comment> "Ashas Ree was a forested planet located in the Outer Rim Territories. Its sole inhabited trading outpost was situated next to a Jedi temple that had been built to seal the power of a Sith temple beneath it. During the First Order-Resistance War, traveler Mika Grey came to Ashas Ree seeking a relic hidden in the Sith temple, intending to keep it out of the First Order's hands, but became trapped inside the temple as a result until she was found and released by Colossus resistance members Kazuda Xiono, CB-23, Eila, and Kel two days later. " .
<https://starwars.com#grid_R5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#grid_R5> <http://telicent.io/ontology/primaryName> "R5" .
<https://starwars.com#planet_AshasRee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#496da267-8bcd-497d-a2de-bbbbc83da2b4> .
<https://starwars.com#496da267-8bcd-497d-a2de-bbbbc83da2b4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_R5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#fb2d5022-751c-4b42-aabb-a223824278e7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AshasRee> <http://telicent.io/ontology/primaryName> "Ashas Ree" .
<https://starwars.com#fb2d5022-751c-4b42-aabb-a223824278e7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_R5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#fb2d5022-751c-4b42-aabb-a223824278e7> .
<https://starwars.com#planet_AshasRee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#496da267-8bcd-497d-a2de-bbbbc83da2b4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ashas Ree"^^<http://www.w3.org/2001/XMLSchema#string> .

