Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hapes> <http://telicent.io/ontology/primaryName> "Hapes" .
<https://starwars.com#planet_Hapes> <http://www.w3.org/2000/01/rdf-schema#comment> "Hapes was an astronomical object located in the Hapes Consortium, a sector of the galaxy's Inner Rim. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hapes> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hapes> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#408e2437-6bc2-4689-8cce-ce5acc03085b> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#408e2437-6bc2-4689-8cce-ce5acc03085b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Hapes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Hapes> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#408e2437-6bc2-4689-8cce-ce5acc03085b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hapes"^^<http://www.w3.org/2001/XMLSchema#string> .

