Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Tsyk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#463fc535-3f8a-4efc-9a5d-5272bb436f22> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#463fc535-3f8a-4efc-9a5d-5272bb436f22> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tsyk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tsyk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T13> .
<https://starwars.com#planet_Tsyk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tsyk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Tsyk> <http://www.w3.org/2000/01/rdf-schema#comment> "Tsyk was a murky, polluted planet in the Tsyk system. It was the homeworld of the Tsyklen. " .
<https://starwars.com#planet_Tsyk> <http://telicent.io/ontology/primaryName> "Tsyk" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#463fc535-3f8a-4efc-9a5d-5272bb436f22> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

