Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ktaktaxka> <http://telicent.io/ontology/primaryName> "K'taktaxka" .
<https://starwars.com#planet_Ktaktaxka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#663daad7-77cf-4740-bb87-a7a8b520aeef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K'taktaxka"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ktaktaxka> <http://www.w3.org/2000/01/rdf-schema#comment> "The K'taktaxka system was a star system located in the Inner Rim region of the galaxy. " .
<https://starwars.com#planet_Ktaktaxka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ktaktaxka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J14> .
<https://starwars.com#663daad7-77cf-4740-bb87-a7a8b520aeef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ktaktaxka> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#663daad7-77cf-4740-bb87-a7a8b520aeef> .

