Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Brevost> <http://telicent.io/ontology/primaryName> "Brevost" .
<https://starwars.com#planet_Sika> <http://www.w3.org/2000/01/rdf-schema#comment> "Sika was a planet in the Expansion Region that was invaded by opportunistic Chekut forces during the Second Galactic Civil War. It was home to the Sikan. " .
<https://starwars.com#planet_Sika> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Brevost> .
<https://starwars.com#sector_Brevost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sika> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6e368bbf-0ce1-47b0-ac00-4441c9b132a4> .
<https://starwars.com#6e368bbf-0ce1-47b0-ac00-4441c9b132a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sika"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sika> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O15> .
<https://starwars.com#planet_Sika> <http://telicent.io/ontology/primaryName> "Sika" .
<https://starwars.com#planet_Sika> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6e368bbf-0ce1-47b0-ac00-4441c9b132a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Brevost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

