Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KunasTooth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#c7036c94-1a7a-4e38-a0d4-fcad53775bee> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuna's Tooth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KunasTooth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_KunasTooth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KunasTooth> <http://telicent.io/ontology/primaryName> "Kuna's Tooth" .
<https://starwars.com#planet_KunasTooth> <http://www.w3.org/2000/01/rdf-schema#comment> "Kuna's Tooth was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was connected by hyperspace routes to the celestial bodies Annaj, Kuna's Eye, and Qina. Kuna's Tooth was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_KunasTooth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c7036c94-1a7a-4e38-a0d4-fcad53775bee> .
<https://starwars.com#c7036c94-1a7a-4e38-a0d4-fcad53775bee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

