Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ac4b79a9-d19d-48a0-b914-e0110978ef8d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Noonian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_OrdSigatt> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Sigatt was an Outer Rim Territories mining planet in the Galactic Republic. The planet was originally settled by the Republic militia as an Ordnance/Regional Depot, but upon the discovery of carvanium by one of the settlers, it quickly evolved into a mining colony. " .
<https://starwars.com#planet_OrdSigatt> <http://telicent.io/ontology/primaryName> "Ord Sigatt" .
<https://starwars.com#ac4b79a9-d19d-48a0-b914-e0110978ef8d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Sigatt"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdSigatt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N6> .
<https://starwars.com#sector_Noonian> <http://telicent.io/ontology/primaryName> "Noonian" .
<https://starwars.com#planet_OrdSigatt> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noonian> .
<https://starwars.com#planet_OrdSigatt> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac4b79a9-d19d-48a0-b914-e0110978ef8d> .
<https://starwars.com#planet_OrdSigatt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Noonian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

