Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rustibar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a0135b82-b5dc-45b5-a5ef-0d55d2e32104> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rustibar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rustibar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Churnis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Churnis> <http://telicent.io/ontology/primaryName> "Churnis" .
<https://starwars.com#sector_Churnis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rustibar> <http://telicent.io/ontology/primaryName> "Rustibar" .
<https://starwars.com#planet_Rustibar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churnis> .
<https://starwars.com#planet_Rustibar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0135b82-b5dc-45b5-a5ef-0d55d2e32104> .
<https://starwars.com#a0135b82-b5dc-45b5-a5ef-0d55d2e32104> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rustibar> <http://www.w3.org/2000/01/rdf-schema#comment> "Rustibar was a Mid Rim planet subjugated by the Galactic Empire. " .

