Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#baf3ef73-1ad6-4282-86d9-cc3abe5935b2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ryoone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wazta> .
<https://starwars.com#baf3ef73-1ad6-4282-86d9-cc3abe5935b2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ryoone"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ryoone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ryoone> <http://www.w3.org/2000/01/rdf-schema#comment> "Ryoone was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Wazta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Wazta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ryoone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#sector_Wazta> <http://telicent.io/ontology/primaryName> "Wazta" .
<https://starwars.com#planet_Ryoone> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#baf3ef73-1ad6-4282-86d9-cc3abe5935b2> .
<https://starwars.com#planet_Ryoone> <http://telicent.io/ontology/primaryName> "Ryoone" .

