Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_H20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#ab85dd27-e72e-4d61-a478-10a81f1a730d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dosuun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H20> .
<https://starwars.com#planet_Dosuun> <http://www.w3.org/2000/01/rdf-schema#comment> "Dosuun was a world in the Wild Space, and was outside the control of the New Republic following the Battle of Endor. From space, the planet could be seen to possess varied terrain and several seas. It also had at least one area of hilly temperate grassland. " .
<https://starwars.com#e71d2ec0-a544-462b-9622-d00d446f65f7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dosuun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ab85dd27-e72e-4d61-a478-10a81f1a730d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dosuun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dosuun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Dosuun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab85dd27-e72e-4d61-a478-10a81f1a730d> .
<https://starwars.com#grid_H20> <http://telicent.io/ontology/primaryName> "H20" .
<https://starwars.com#planet_Dosuun> <http://telicent.io/ontology/primaryName> "Dosuun" .
<https://starwars.com#grid_H20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#e71d2ec0-a544-462b-9622-d00d446f65f7> .
<https://starwars.com#grid_H20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#e71d2ec0-a544-462b-9622-d00d446f65f7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

