Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dulvoyinn> <http://www.w3.org/2000/01/rdf-schema#comment> "Dulvoyinn was an astronomical object located in the regions known as the Deep Core and the Interior. It was also situated in the grid square K-12 of the Standard Galactic Grid. " .
<https://starwars.com#8afe007e-682d-4b14-929e-423d526d80cc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dulvoyinn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dulvoyinn> <http://telicent.io/ontology/primaryName> "Dulvoyinn" .
<https://starwars.com#planet_Dulvoyinn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8afe007e-682d-4b14-929e-423d526d80cc> .
<https://starwars.com#planet_Dulvoyinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#8afe007e-682d-4b14-929e-423d526d80cc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dulvoyinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Dulvoyinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

