Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdAntalaha> <http://telicent.io/ontology/primaryName> "Ord Antalaha" .
<https://starwars.com#df56d3f8-688f-40ad-9a0a-7fed3e71b026> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Antalaha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdAntalaha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#df56d3f8-688f-40ad-9a0a-7fed3e71b026> .
<https://starwars.com#planet_OrdAntalaha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdAntalaha> <http://www.w3.org/2000/01/rdf-schema#comment> "This new wave of fringe elements soon inhabited Ord Antalaha's unoccupied warehouses, arming and barricading them into impenetrable fortresses referred to as 'Resorts.' The colonists, despite the arrival of their new neighbors, continued living their lives in peace as simple farmers. In fact, the majority of Ord Antalaha's criminal population found it wise to prevent the harassment of the colonists for fear of attracting unwanted Imperial attention. Though no formal government ruled over the planet after the Clone Wars, the collective fringe presence on the world operated under a code consisting of three fundamental rules. Ord Antalaha's sole starport was Fort Divin, a center of black marketeering and smuggling. " .
<https://starwars.com#planet_OrdAntalaha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#df56d3f8-688f-40ad-9a0a-7fed3e71b026> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdAntalaha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

