Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4aafdfb0-55a8-4b65-88b6-63eb9c9badd0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Thesme> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Thesme> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Hijado> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4aafdfb0-55a8-4b65-88b6-63eb9c9badd0> .
<https://starwars.com#planet_Hijado> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Thesme> <http://telicent.io/ontology/primaryName> "Thesme" .
<https://starwars.com#planet_Hijado> <http://telicent.io/ontology/primaryName> "Hijado" .
<https://starwars.com#planet_Hijado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O6> .
<https://starwars.com#4aafdfb0-55a8-4b65-88b6-63eb9c9badd0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hijado"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hijado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thesme> .
<https://starwars.com#planet_Hijado> <http://www.w3.org/2000/01/rdf-schema#comment> "Hijado was a planet on the Hydian Way, halfway to Bonadan. The Human natives of Hijado were called Hijadoans. It was located in the Hijado system of the Thesme sector. " .

