Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Endregaad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#31dcca2f-0ad6-4a64-b9e5-985412ed659e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Endregaad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Endregaad> <http://telicent.io/ontology/primaryName> "Endregaad" .
<https://starwars.com#planet_Endregaad> <http://www.w3.org/2000/01/rdf-schema#comment> "Endregaad, a world near the Indrexu Spiral, was the oasis mother homeworld. " .
<https://starwars.com#31dcca2f-0ad6-4a64-b9e5-985412ed659e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Endregaad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Endregaad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31dcca2f-0ad6-4a64-b9e5-985412ed659e> .
<https://starwars.com#planet_Endregaad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

