Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a3842982-be41-4d26-99eb-7d011d5cf1a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jabiim"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a3842982-be41-4d26-99eb-7d011d5cf1a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jabiim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Phelleem> .
<https://starwars.com#planet_Jabiim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#sector_Phelleem> <http://telicent.io/ontology/primaryName> "Phelleem" .
<https://starwars.com#planet_Jabiim> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a3842982-be41-4d26-99eb-7d011d5cf1a8> .
<https://starwars.com#sector_Phelleem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Jabiim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Phelleem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jabiim> <http://telicent.io/ontology/primaryName> "Jabiim" .
<https://starwars.com#planet_Jabiim> <http://www.w3.org/2000/01/rdf-schema#comment> "Jabiim was a terrestrial astronomical object situated within the regions known as the Outer Rim Territories and the Slice. Connected to Sy Myrth and Taskeed by hyperspace routes, it was positioned at the coordinates S-7 on the Standard Galactic Grid. Ore was one of the main exports of Jabiim. " .

