Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Phaeda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fb593931-a2ee-42e6-8716-ff96a9fb8879> .
<https://starwars.com#planet_Phaeda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cademimu> .
<https://starwars.com#planet_Phaeda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L6> .
<https://starwars.com#fb593931-a2ee-42e6-8716-ff96a9fb8879> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Phaeda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Phaeda> <http://www.w3.org/2000/01/rdf-schema#comment> "Phaeda was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#sector_Cademimu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Phaeda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Cademimu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cademimu> <http://telicent.io/ontology/primaryName> "Cademimu" .
<https://starwars.com#planet_Phaeda> <http://telicent.io/ontology/primaryName> "Phaeda" .
<https://starwars.com#fb593931-a2ee-42e6-8716-ff96a9fb8879> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

