Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3c29ab34-cdb5-47bc-bc10-0cda260311e9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tynquay> .
<https://starwars.com#planet_Thosa> <http://telicent.io/ontology/primaryName> "Thosa" .
<https://starwars.com#planet_Thosa> <http://www.w3.org/2000/01/rdf-schema#comment> "Thosa was a planet of barren rock orbiting Dostra Major in the Dostra system. It was the fifth planet in the system, and was orbited by two moons. " .
<https://starwars.com#sector_Tynquay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thosa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c29ab34-cdb5-47bc-bc10-0cda260311e9> .
<https://starwars.com#planet_Thosa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thosa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#3c29ab34-cdb5-47bc-bc10-0cda260311e9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thosa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tynquay> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Tynquay> <http://telicent.io/ontology/primaryName> "Tynquay" .

