Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chokan> <http://www.w3.org/2000/01/rdf-schema#comment> "Chokan was a planet on the Gamor Run in the Mid Rim's Maerdocian sector. " .
<https://starwars.com#planet_Chokan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#planet_Chokan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maerdocia> .
<https://starwars.com#planet_Chokan> <http://telicent.io/ontology/primaryName> "Chokan" .
<https://starwars.com#planet_Chokan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Maerdocia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#46aad61d-d909-42a2-802e-7ce42374f331> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Maerdocia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Maerdocia> <http://telicent.io/ontology/primaryName> "Maerdocia" .
<https://starwars.com#planet_Chokan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#46aad61d-d909-42a2-802e-7ce42374f331> .
<https://starwars.com#46aad61d-d909-42a2-802e-7ce42374f331> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chokan"^^<http://www.w3.org/2001/XMLSchema#string> .

