Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lanthe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#sector_VarHagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Lanthe> <http://telicent.io/ontology/primaryName> "Lanthe" .
<https://starwars.com#74ab9cc3-938e-43e9-bc6d-e7de899f9f46> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lanthe"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_VarHagen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lanthe> <http://www.w3.org/2000/01/rdf-schema#comment> "Lanthe was a planet in the Mid Rim's Var Hagen sector. It was the original headquarters of Lanthe Artifice, but when the local Imperial Moff nationalized all corporations, Lanthe Artifice relocated to the Tapani sector. " .
<https://starwars.com#planet_Lanthe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_VarHagen> .
<https://starwars.com#sector_VarHagen> <http://telicent.io/ontology/primaryName> "Var Hagen" .
<https://starwars.com#planet_Lanthe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lanthe> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#74ab9cc3-938e-43e9-bc6d-e7de899f9f46> .
<https://starwars.com#74ab9cc3-938e-43e9-bc6d-e7de899f9f46> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

