Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shaylin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#61b7eb06-2339-420d-8f5b-b8139002fa39> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#61b7eb06-2339-420d-8f5b-b8139002fa39> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#61b7eb06-2339-420d-8f5b-b8139002fa39> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shaylin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shaylin> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Shaylin> <http://telicent.io/ontology/primaryName> "Shaylin" .
<https://starwars.com#planet_Shaylin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#planet_Shaylin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Shaylin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .

