Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PavoPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12dedf88-7e92-4550-8e89-c9802de7e2b4> .
<https://starwars.com#planet_PavoPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#planet_PavoPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#12dedf88-7e92-4550-8e89-c9802de7e2b4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pavo Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PavoPrime> <http://telicent.io/ontology/primaryName> "Pavo Prime" .
<https://starwars.com#12dedf88-7e92-4550-8e89-c9802de7e2b4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PavoPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PavoPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Pavo Prime was a location in the galaxy. " .

