Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vasch> <http://telicent.io/ontology/primaryName> "Vasch" .
<https://starwars.com#a19d22fe-22f9-4334-b3df-854cb9f11a71> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vasch"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vasch> <http://www.w3.org/2000/01/rdf-schema#comment> "Vasch was a planet located within the Vasch system of the Outer Rim Territories. An agriworld of lush green, rolling hills, it was the source of Vaschean rye, and was possibly the homeworld of Sam Heggs. " .
<https://starwars.com#planet_Vasch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Vasch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vasch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#a19d22fe-22f9-4334-b3df-854cb9f11a71> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vasch> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a19d22fe-22f9-4334-b3df-854cb9f11a71> .

