Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Yarith> <http://telicent.io/ontology/primaryName> "Yarith" .
<https://starwars.com#a893d9ae-b558-445e-b6f1-ae44a2a30f68> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Togominda> <http://telicent.io/ontology/primaryName> "Togominda" .
<https://starwars.com#planet_Togominda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Yarith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Togominda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a893d9ae-b558-445e-b6f1-ae44a2a30f68> .
<https://starwars.com#sector_Yarith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Togominda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yarith> .
<https://starwars.com#a893d9ae-b558-445e-b6f1-ae44a2a30f68> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Togominda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Togominda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Togominda> <http://www.w3.org/2000/01/rdf-schema#comment> "Togominda was an astronomical object in the Greater Javin Region of the galaxy's Outer Rim Territories. " .

