Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b5495708-651b-496a-bb2a-87d69267428b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "I6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Ansion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churnis> .
<https://starwars.com#sector_Churnis> <http://telicent.io/ontology/primaryName> "Churnis" .
<https://starwars.com#grid_I6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b5495708-651b-496a-bb2a-87d69267428b> .
<https://starwars.com#sector_Churnis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a8d4c65a-a427-4ee0-902f-fd68dd3b6fa0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ansion"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_I6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Ansion> <http://telicent.io/ontology/primaryName> "Ansion" .
<https://starwars.com#planet_Ansion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Churnis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#a8d4c65a-a427-4ee0-902f-fd68dd3b6fa0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_I6> <http://telicent.io/ontology/primaryName> "I6" .
<https://starwars.com#planet_Ansion> <http://www.w3.org/2000/01/rdf-schema#comment> "Ansion was a planet located in the galaxy's Mid Rim. A border dispute occurred on Ansion during the Separatist Crisis, which, along with turmoil on the planet Ando, was enough to stagger the galaxy. Ansion was connected via hyperspace route to the planets Keitum, Glee Anselm, Namadii, Rago, and Benath. " .
<https://starwars.com#b5495708-651b-496a-bb2a-87d69267428b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Ansion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I6> .
<https://starwars.com#planet_Ansion> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a8d4c65a-a427-4ee0-902f-fd68dd3b6fa0> .

