Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dd0b9278-593d-43ff-89dc-baeac46fc323> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abraxas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Yushan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_K17> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Yushan> <http://telicent.io/ontology/primaryName> "Yushan" .
<https://starwars.com#planet_Abraxas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Yushan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Abraxas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yushan> .
<https://starwars.com#planet_Abraxas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#f6aab4e8-1e31-40cb-84cd-792dd515761a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_K17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Abraxas> <http://www.w3.org/2000/01/rdf-schema#comment> "Abraxas was a planet in the Abraxas system situated within the Yushan sector of the Mid Rim Territories. Abraxas was run dry of its rich natural resources by overwhelming mining, and became a base for the Eiattu pirates. Soon after the Battle of Endor, the New Republic discovered and threw the pirates out. " .
<https://starwars.com#grid_K17> <http://telicent.io/ontology/primaryName> "K17" .
<https://starwars.com#dd0b9278-593d-43ff-89dc-baeac46fc323> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f6aab4e8-1e31-40cb-84cd-792dd515761a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K17"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K17> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f6aab4e8-1e31-40cb-84cd-792dd515761a> .
<https://starwars.com#planet_Abraxas> <http://telicent.io/ontology/primaryName> "Abraxas" .
<https://starwars.com#planet_Abraxas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd0b9278-593d-43ff-89dc-baeac46fc323> .

