Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_M3> <http://telicent.io/ontology/primaryName> "M3" .
<https://starwars.com#decb8a6b-315a-4fe7-922c-8946ec035595> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M3"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dalonbian> <http://telicent.io/ontology/primaryName> "Dalonbian" .
<https://starwars.com#grid_M3> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Birgis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dalonbian> .
<https://starwars.com#sector_Dalonbian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Dalonbian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Birgis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#75be2ef0-2532-4e74-86d5-d4ab5783dc17> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Birgis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_M3> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#decb8a6b-315a-4fe7-922c-8946ec035595> .
<https://starwars.com#grid_M3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#decb8a6b-315a-4fe7-922c-8946ec035595> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Birgis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#75be2ef0-2532-4e74-86d5-d4ab5783dc17> .
<https://starwars.com#planet_Birgis> <http://www.w3.org/2000/01/rdf-schema#comment> "Birgis was an astronomical object in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Birgis> <http://telicent.io/ontology/primaryName> "Birgis" .
<https://starwars.com#75be2ef0-2532-4e74-86d5-d4ab5783dc17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Birgis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M3> .

