Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sukkult> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sukkult> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#0b69c308-c9e2-47d8-ae96-a34fa14ee19b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sukkult> <http://telicent.io/ontology/primaryName> "Sukkult" .
<https://starwars.com#planet_Sukkult> <http://www.w3.org/2000/01/rdf-schema#comment> "Sukkult was a planet in the Inner Rim. Residing there was a Herglic collector of Tritonite documents. During the Clone Wars, the planet was located within Separatist space. " .
<https://starwars.com#planet_Sukkult> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Sukkult> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0b69c308-c9e2-47d8-ae96-a34fa14ee19b> .
<https://starwars.com#0b69c308-c9e2-47d8-ae96-a34fa14ee19b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sukkult"^^<http://www.w3.org/2001/XMLSchema#string> .

