Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tyus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Tyus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nuralee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nuralee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N16> .
<https://starwars.com#d1e67905-93ac-4738-95e6-27c6aa268920> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nuralee"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nuralee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tyus> .
<https://starwars.com#d1e67905-93ac-4738-95e6-27c6aa268920> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tyus> <http://telicent.io/ontology/primaryName> "Tyus" .
<https://starwars.com#planet_Nuralee> <http://telicent.io/ontology/primaryName> "Nuralee" .
<https://starwars.com#planet_Nuralee> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d1e67905-93ac-4738-95e6-27c6aa268920> .
<https://starwars.com#planet_Nuralee> <http://www.w3.org/2000/01/rdf-schema#comment> "Nuralee was a Mid Rim world in the Tyus sector. It had an economic breakdown shortly before the Clone Wars. It was represented in the Galactic Senate by Bog Divinian, a wealthy landowner with ties to the Commerce Guild. " .

