Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Carrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Vexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#93f3f3c8-338c-4578-be91-8b476192d51a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vexta> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#93f3f3c8-338c-4578-be91-8b476192d51a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vexta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Carrion> <http://telicent.io/ontology/primaryName> "Carrion" .
<https://starwars.com#planet_Vexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Carrion> .
<https://starwars.com#planet_Vexta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vexta> <http://telicent.io/ontology/primaryName> "Vexta" .
<https://starwars.com#sector_Carrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vexta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#93f3f3c8-338c-4578-be91-8b476192d51a> .

