Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Irishi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_K6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#3a5cd86e-df4c-489e-86d8-ce22ef0b02e8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gonmore"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K6> <http://telicent.io/ontology/primaryName> "K6" .
<https://starwars.com#sector_Irishi> <http://telicent.io/ontology/primaryName> "Irishi" .
<https://starwars.com#f2407cc9-3f70-4250-b8e6-e7efa6e6c232> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gonmore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#sector_Irishi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Gonmore> <http://www.w3.org/2000/01/rdf-schema#comment> "Gonmore was a planet in the Gonmore system in the Outer Rim. It was the location of a clearinghouse of Talon Karrde. " .
<https://starwars.com#planet_Gonmore> <http://telicent.io/ontology/primaryName> "Gonmore" .
<https://starwars.com#grid_K6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f2407cc9-3f70-4250-b8e6-e7efa6e6c232> .
<https://starwars.com#planet_Gonmore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Irishi> .
<https://starwars.com#3a5cd86e-df4c-489e-86d8-ce22ef0b02e8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_K6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#f2407cc9-3f70-4250-b8e6-e7efa6e6c232> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Gonmore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gonmore> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a5cd86e-df4c-489e-86d8-ce22ef0b02e8> .

