Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Besnia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Besnia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Besnia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3f6036b3-373e-47ab-9604-3089b3514b1e> .
<https://starwars.com#planet_Besnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#3f6036b3-373e-47ab-9604-3089b3514b1e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Besnia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#planet_Besnia> <http://telicent.io/ontology/primaryName> "Besnia" .
<https://starwars.com#3f6036b3-373e-47ab-9604-3089b3514b1e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Besnia"^^<http://www.w3.org/2001/XMLSchema#string> .

