Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Grakouine> <http://telicent.io/ontology/primaryName> "Grakouine" .
<https://starwars.com#70159416-20d8-42dd-a443-144687002575> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Grakouine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Grakouine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Onatos> <http://telicent.io/ontology/primaryName> "Onatos" .
<https://starwars.com#70159416-20d8-42dd-a443-144687002575> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Grakouine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R15> .
<https://starwars.com#sector_Onatos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Onatos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Grakouine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Onatos> .
<https://starwars.com#planet_Grakouine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#70159416-20d8-42dd-a443-144687002575> .
<https://starwars.com#planet_Grakouine> <http://www.w3.org/2000/01/rdf-schema#comment> "Grakouine was a world on which an Alliance to Restore the Republic storage depot was located. It was here that Boba Fett's ship Slave I was impounded by the New Republic after he was presumed killed by the Sarlacc on Tatooine. Sometime after escaping the Sarlacc, he made his way to Grakouine and recovered Slave I. " .

