Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clythe> <http://telicent.io/ontology/primaryName> "Clythe" .
<https://starwars.com#sector_Clythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Valrar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Valrar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J7> .
<https://starwars.com#sector_Clythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Valrar> <http://www.w3.org/2000/01/rdf-schema#comment> "Valrar was a planet located within the Valrar system of the Mid Rim. Its dense canopy forests blocked most sunlight from reaching the planet's surface. Khabarakh was reassigned here by Thrawn after his failure to capture Leia Organa Solo on Kashyyyk. " .
<https://starwars.com#planet_Valrar> <http://telicent.io/ontology/primaryName> "Valrar" .
<https://starwars.com#a1bc827c-c072-45f8-9cde-041c42ba34d0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Valrar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Valrar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clythe> .
<https://starwars.com#planet_Valrar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a1bc827c-c072-45f8-9cde-041c42ba34d0> .
<https://starwars.com#a1bc827c-c072-45f8-9cde-041c42ba34d0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

