Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_J12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#1f8631b0-173c-4ce1-88d6-3a9940f40d1b> .
<https://starwars.com#planet_Inysh> <http://www.w3.org/2000/01/rdf-schema#comment> "The ecology of Inysh was devastated as a result, with toxic waste being dumped across the planet and native flora and fauna dying off. The Abinyshi were enslaved and brought to the brink of extinction, and the galaxy at large was misled to believe the species had eradicated itself in a civil war. At some point, the Empire abandoned the mining operations on Inysh, leaving the natives on their ruined homeworld. " .
<https://starwars.com#1f8631b0-173c-4ce1-88d6-3a9940f40d1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1f8631b0-173c-4ce1-88d6-3a9940f40d1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Inysh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Inysh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#00e9e5c4-b271-4348-b2d6-43b4bd487275> .
<https://starwars.com#planet_Inysh> <http://telicent.io/ontology/primaryName> "Inysh" .
<https://starwars.com#grid_J12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#00e9e5c4-b271-4348-b2d6-43b4bd487275> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J12> <http://telicent.io/ontology/primaryName> "J12" .
<https://starwars.com#00e9e5c4-b271-4348-b2d6-43b4bd487275> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Inysh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Inysh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J12> .
<https://starwars.com#planet_Inysh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

