Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#92d2768e-2690-488a-9d54-de0614d5dc35> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_L19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0b3b0db6-2a9b-42b7-8a0d-a2581f9f1593> .
<https://starwars.com#sector_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#92d2768e-2690-488a-9d54-de0614d5dc35> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Atravis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Atravis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#92d2768e-2690-488a-9d54-de0614d5dc35> .
<https://starwars.com#planet_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#sector_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Atravis> <http://www.w3.org/2000/01/rdf-schema#comment> "Atravis was an astronomical object located in the regions known as the Outer Rim Territories and the Western Reaches. It was also situated in the grid square L-19 of the Standard Galactic Grid. The super-hyperroute known as the Hydian Way connected Atravis to Rutan and Shumavar. Atravis also shared its name with the Atravis sector, which contained the nearby Mustafar system. " .
<https://starwars.com#sector_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#planet_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L19> .
<https://starwars.com#0b3b0db6-2a9b-42b7-8a0d-a2581f9f1593> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atravis> .
<https://starwars.com#planet_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0b3b0db6-2a9b-42b7-8a0d-a2581f9f1593> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_L19> <http://telicent.io/ontology/primaryName> "L19" .

