Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0a26f9b3-ce48-4448-b0bc-138fd88b3bc6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Belassar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sarla> .
<https://starwars.com#bba59ba7-1a99-4f42-b7a8-7b568f82cedb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Belassar> <http://telicent.io/ontology/primaryName> "Belassar" .
<https://starwars.com#planet_Belassar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0a26f9b3-ce48-4448-b0bc-138fd88b3bc6> .
<https://starwars.com#0a26f9b3-ce48-4448-b0bc-138fd88b3bc6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belassar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Belassar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#bba59ba7-1a99-4f42-b7a8-7b568f82cedb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Sarla> <http://telicent.io/ontology/primaryName> "Sarla" .
<https://starwars.com#sector_Sarla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#grid_J8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#bba59ba7-1a99-4f42-b7a8-7b568f82cedb> .
<https://starwars.com#planet_Belassar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J8> .
<https://starwars.com#grid_J8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_J8> <http://telicent.io/ontology/primaryName> "J8" .
<https://starwars.com#sector_Sarla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Belassar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

