Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dagobah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sluis> .
<https://starwars.com#planet_Dagobah> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dagobah> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M19> .
<https://starwars.com#72c6ce6a-ae94-42a9-8b55-4565295cee8f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dagobah"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dagobah> <http://telicent.io/ontology/primaryName> "Dagobah" .
<https://starwars.com#planet_Dagobah> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#72c6ce6a-ae94-42a9-8b55-4565295cee8f> .
<https://starwars.com#sector_Sluis> <http://telicent.io/ontology/primaryName> "Sluis" .
<https://starwars.com#planet_Dagobah> <http://www.w3.org/2000/01/rdf-schema#comment> "Swamp planet and Yoda's residence after the fall of the Jedi." .
<https://starwars.com#sector_Sluis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#72c6ce6a-ae94-42a9-8b55-4565295cee8f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Sluis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

