Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aeten> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#73d09662-a56f-4e50-85ad-1b5366b0b243> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aeten"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aeten> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aeten> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#73d09662-a56f-4e50-85ad-1b5366b0b243> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aeten> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73d09662-a56f-4e50-85ad-1b5366b0b243> .
<https://starwars.com#planet_Aeten> <http://www.w3.org/2000/01/rdf-schema#comment> "Aeten redirects here. You may be looking for the star." .
<https://starwars.com#planet_Aeten> <http://telicent.io/ontology/primaryName> "Aeten" .

