Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Albanin> <http://telicent.io/ontology/primaryName> "Albanin" .
<https://starwars.com#planet_Daluuj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albanin> .
<https://starwars.com#50b79679-d8d7-451f-aa79-33e3169f8aa9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Daluuj"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Daluuj> <http://www.w3.org/2000/01/rdf-schema#comment> "Daluuj was an astronomical object located in the Outer Rim Territories of the galaxy, positioned at the coordinates U-13 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Daluuj> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Daluuj> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#50b79679-d8d7-451f-aa79-33e3169f8aa9> .
<https://starwars.com#50b79679-d8d7-451f-aa79-33e3169f8aa9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Daluuj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U13> .
<https://starwars.com#sector_Albanin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Albanin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Daluuj> <http://telicent.io/ontology/primaryName> "Daluuj" .

