Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#63566c54-6d48-432c-bed3-be821c7ff8fb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sepan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sepan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sepan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sepan> .
<https://starwars.com#planet_Sepan> <http://telicent.io/ontology/primaryName> "Sepan" .
<https://starwars.com#63566c54-6d48-432c-bed3-be821c7ff8fb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sepan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sepan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#63566c54-6d48-432c-bed3-be821c7ff8fb> .
<https://starwars.com#planet_Sepan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P13> .
<https://starwars.com#sector_Sepan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Sepan> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Sepan> <http://telicent.io/ontology/primaryName> "Sepan" .

