Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MuntoCodru> <http://www.w3.org/2000/01/rdf-schema#comment> "Munto Codru was an astronomical objected located within the regions known as the Outer Rim Territories and the Slice. It lay in grid square T-6 on the Standard Galactic Grid, where it was situated along a hyperspace route, which connected it to the astronomical object Pakuuni and the planet Mon Cala. " .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MuntoCodru> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#709c35da-dffd-444b-95a2-78d1a010df78> .
<https://starwars.com#planet_MuntoCodru> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MuntoCodru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#709c35da-dffd-444b-95a2-78d1a010df78> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#709c35da-dffd-444b-95a2-78d1a010df78> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Munto Codru"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MuntoCodru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#planet_MuntoCodru> <http://telicent.io/ontology/primaryName> "Munto Codru" .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

