Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Trianii> <http://telicent.io/ontology/primaryName> "Trianii" .
<https://starwars.com#planet_Pypin> <http://www.w3.org/2000/01/rdf-schema#comment> "Pypin was one of the Trianii colony worlds within the disputed border of the Corporate Sector. " .
<https://starwars.com#04f918a0-350f-4754-8d1b-673c545aea36> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pypin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pypin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Trianii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pypin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R3> .
<https://starwars.com#04f918a0-350f-4754-8d1b-673c545aea36> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pypin> <http://telicent.io/ontology/primaryName> "Pypin" .
<https://starwars.com#planet_Pypin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trianii> .
<https://starwars.com#planet_Pypin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#04f918a0-350f-4754-8d1b-673c545aea36> .
<https://starwars.com#sector_Trianii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .

