Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ralltiir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#56eb37e2-8310-4894-bea0-34cf6ae8ef4d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ralltiir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ralltiir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Ralltiir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ralltiir> <http://telicent.io/ontology/primaryName> "Ralltiir" .
<https://starwars.com#planet_Ralltiir> <http://www.w3.org/2000/01/rdf-schema#comment> "Ralltiir was a terrestrial planet located in the Core Worlds region. During the Clone Wars, Lieutenant Commander Orson Krennic of the Galactic Republic financed a few weeks of vacation on the planet for the smuggler Has Obitt's former crew, as compensation for replacing them. Ralltiir later served as a Rebel Alliance safe world during the Galactic Civil War. The planet was also the homeworld of General Pharl McQuarrie and the pilot Derek Klivian, who were members of the Alliance. " .
<https://starwars.com#56eb37e2-8310-4894-bea0-34cf6ae8ef4d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ralltiir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#56eb37e2-8310-4894-bea0-34cf6ae8ef4d> .

