Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Atravis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tosste> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#76574291-da2a-48ec-83aa-748731f6d622> .
<https://starwars.com#planet_Tosste> <http://www.w3.org/2000/01/rdf-schema#comment> "Tosste was a location within the Galactic Empire. In describing early Imperial history in his Strategy and Tactics class at the officer's academy on the planet Arkanis, Colonel Julyan taught his students that it was on Tosste that Admiral Terrinald Screed and the Imperial Navy smashed the Iska pirates that they had driven from Fanha. " .
<https://starwars.com#sector_Atravis> <http://telicent.io/ontology/primaryName> "Atravis" .
<https://starwars.com#76574291-da2a-48ec-83aa-748731f6d622> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#76574291-da2a-48ec-83aa-748731f6d622> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tosste"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tosste> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L19> .
<https://starwars.com#sector_Atravis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tosste> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tosste> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atravis> .
<https://starwars.com#planet_Tosste> <http://telicent.io/ontology/primaryName> "Tosste" .

