Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Arleen> <http://www.w3.org/2000/01/rdf-schema#comment> "Arleen" .
<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#41079003-ef14-4bf7-9993-66929a1db889> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arleen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arleen> <http://telicent.io/ontology/primaryName> "Arleen" .
<https://starwars.com#grid_T8> <http://telicent.io/ontology/primaryName> "T8" .
<https://starwars.com#grid_T8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Arleen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#41079003-ef14-4bf7-9993-66929a1db889> .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_T8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0603c376-947d-4a49-bb38-1c7b89a26821> .
<https://starwars.com#planet_Arleen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#0603c376-947d-4a49-bb38-1c7b89a26821> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#0603c376-947d-4a49-bb38-1c7b89a26821> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#41079003-ef14-4bf7-9993-66929a1db889> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Arleen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#grid_T8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Arleen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

