Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Riileb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T12> .
<https://starwars.com#86c6269a-d052-4339-852d-4c9581f96a07> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Riileb"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Riileb> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#86c6269a-d052-4339-852d-4c9581f96a07> .
<https://starwars.com#planet_Riileb> <http://www.w3.org/2000/01/rdf-schema#comment> "Riileb was an astronomical object located in the Hutt Space sector of the Outer Rim Territories, positioned at the coordinates T-12 on the Standard Galactic Grid. " .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Riileb> <http://telicent.io/ontology/primaryName> "Riileb" .
<https://starwars.com#planet_Riileb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Riileb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#86c6269a-d052-4339-852d-4c9581f96a07> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

