Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Charra> <http://www.w3.org/2000/01/rdf-schema#comment> "Charra was a terrestrial astronomical object where Governor Tarkin of the Galactic Empire attended a trade conference. " .
<https://starwars.com#sector_Charra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Charra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_P14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#8b8733ef-0605-44e9-ae03-da82dcc24e2d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P14> <http://telicent.io/ontology/primaryName> "P14" .
<https://starwars.com#sector_Charra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#8b8733ef-0605-44e9-ae03-da82dcc24e2d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_P14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#3e19b9ab-d356-4a52-8d3a-ccf5632c2a43> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Charra> <http://telicent.io/ontology/primaryName> "Charra" .
<https://starwars.com#sector_Charra> <http://telicent.io/ontology/primaryName> "Charra" .
<https://starwars.com#grid_P14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8b8733ef-0605-44e9-ae03-da82dcc24e2d> .
<https://starwars.com#planet_Charra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3e19b9ab-d356-4a52-8d3a-ccf5632c2a43> .
<https://starwars.com#3e19b9ab-d356-4a52-8d3a-ccf5632c2a43> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Charra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Charra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P14> .
<https://starwars.com#planet_Charra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Charra> .

