Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ilos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R10> .
<https://starwars.com#planet_Ilos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#011e130a-b4d8-48b1-b5ee-a957091075d4> .
<https://starwars.com#011e130a-b4d8-48b1-b5ee-a957091075d4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ilos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ilos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ilos> <http://www.w3.org/2000/01/rdf-schema#comment> "Ilos was a bland agricultural world that was located within the Ilos system of the galaxy's Hutt Space region and lay on the hyperlane called the Pabol Sleheyron, which connected it to the planets of Chalacta and Ilos Minor. " .
<https://starwars.com#planet_Ilos> <http://telicent.io/ontology/primaryName> "Ilos" .
<https://starwars.com#planet_Ilos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#011e130a-b4d8-48b1-b5ee-a957091075d4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

