Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_DurgensStar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8769202e-ba0d-415d-a0ae-67a9da71aa96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_DurgensStar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_DurgensStar> <http://www.w3.org/2000/01/rdf-schema#comment> "Durgen's Star was a white dwarf star that was located in the Durgen's Star system. It was situated in the Loop Worlds area of the Gordian Reach sector, within the Trans-Hydian portion of the Outer Rim Territories. Durgen's Star lay on the hyperlane known as the Junction-Tierell Loop, which connected it to the Povanaria and Trinovat systems. " .
<https://starwars.com#planet_DurgensStar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8769202e-ba0d-415d-a0ae-67a9da71aa96> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_DurgensStar> <http://telicent.io/ontology/primaryName> "Durgen's Star" .
<https://starwars.com#planet_DurgensStar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#8769202e-ba0d-415d-a0ae-67a9da71aa96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Durgen's Star"^^<http://www.w3.org/2001/XMLSchema#string> .

