Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tinta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tinta> <http://www.w3.org/2000/01/rdf-schema#comment> "       Tinta   Production information  Type Toy   Owners Jyn Erso   Locations Erso homestead, Lah'mu     Tinta was a white, fluffy toy tauntaun, known to its owner, Jyn Erso, the daughter of Galen, and Lyra Erso, as a 'snow lizard'. The toy was one of Jyn's playthings while she lived in her family's homestead on the planet Lah'mu. Jyn generally kept Tinta with her other toys in her toybox, but in the year 13 BBY, it and several other toys were out on her bed when the Galactic Empire arrived at the homestead in search of Galen. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tinta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#f3a32a2f-7c7e-49eb-b0db-efac4314901d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tinta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f3a32a2f-7c7e-49eb-b0db-efac4314901d> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Tinta> <http://telicent.io/ontology/primaryName> "Tinta" .
<https://starwars.com#f3a32a2f-7c7e-49eb-b0db-efac4314901d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tinta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tinta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .

