Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f24b3197-ad6e-44a2-9087-12990cf7fd22> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jatir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Jatir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f24b3197-ad6e-44a2-9087-12990cf7fd22> .
<https://starwars.com#planet_Jatir> <http://www.w3.org/2000/01/rdf-schema#comment> "Jatir was a planet in the Jatir system within the Colonies. It was one endpoint of the Corulag-Jatir Hyperroute, which was plied by Trade Federation freighters. " .
<https://starwars.com#planet_Jatir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Jatir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f24b3197-ad6e-44a2-9087-12990cf7fd22> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jatir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jatir> <http://telicent.io/ontology/primaryName> "Jatir" .

