Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Cyrillia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CyrillianProtectorate> .
<https://starwars.com#a004baa2-dc92-4481-8d13-9a760e1cfc31> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Cyrillia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#grid_O12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#be48051c-7f59-4296-a64a-2e95e5c4973b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cyrillia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CyrillianProtectorate> <http://telicent.io/ontology/primaryName> "Cyrillian Protectorate" .
<https://starwars.com#sector_CyrillianProtectorate> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_CyrillianProtectorate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a004baa2-dc92-4481-8d13-9a760e1cfc31> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cyrillia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cyrillia> <http://telicent.io/ontology/primaryName> "Cyrillia" .
<https://starwars.com#planet_Cyrillia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#be48051c-7f59-4296-a64a-2e95e5c4973b> .
<https://starwars.com#grid_O12> <http://telicent.io/ontology/primaryName> "O12" .
<https://starwars.com#be48051c-7f59-4296-a64a-2e95e5c4973b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#a004baa2-dc92-4481-8d13-9a760e1cfc31> .
<https://starwars.com#planet_Cyrillia> <http://www.w3.org/2000/01/rdf-schema#comment> "Cyrillia was a world located in the galaxy's Expansion Region. " .

