Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PrimusGoluud> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_PrimusGoluud> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd2741f2-7568-4ff8-b7f3-ca4b5b6be2ad> .
<https://starwars.com#dd2741f2-7568-4ff8-b7f3-ca4b5b6be2ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Primus Goluud"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PrimusGoluud> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dd2741f2-7568-4ff8-b7f3-ca4b5b6be2ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PrimusGoluud> <http://www.w3.org/2000/01/rdf-schema#comment> "Primus Goluud was a red supergiant star situated in the Deep Core region. One of billions of stars in the Deep Core, Primus Goluud and the other stars in the region were constantly shifting as a result of the gravitational force of the Galactic Centre black hole. " .
<https://starwars.com#planet_PrimusGoluud> <http://telicent.io/ontology/primaryName> "Primus Goluud" .
<https://starwars.com#planet_PrimusGoluud> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .

