Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Vilonis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_AlassaMajor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O16> .
<https://starwars.com#7afd2fcd-f70c-48dc-9a01-819495af969c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#7afd2fcd-f70c-48dc-9a01-819495af969c> .
<https://starwars.com#grid_O16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_AlassaMajor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#80fe4073-d42f-4ef0-b98f-89fc776a04f2> .
<https://starwars.com#sector_Vilonis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#7afd2fcd-f70c-48dc-9a01-819495af969c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_AlassaMajor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vilonis> .
<https://starwars.com#80fe4073-d42f-4ef0-b98f-89fc776a04f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_AlassaMajor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Vilonis> <http://telicent.io/ontology/primaryName> "Vilonis" .
<https://starwars.com#planet_AlassaMajor> <http://www.w3.org/2000/01/rdf-schema#comment> "Alassa Major was a resort world located along the Enarc Run, known as a major tourist destination for people dwelling in the wealthy core regions. " .
<https://starwars.com#grid_O16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_O16> <http://telicent.io/ontology/primaryName> "O16" .
<https://starwars.com#planet_AlassaMajor> <http://telicent.io/ontology/primaryName> "Alassa Major" .
<https://starwars.com#80fe4073-d42f-4ef0-b98f-89fc776a04f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alassa Major"^^<http://www.w3.org/2001/XMLSchema#string> .

