Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Andalasa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P18> .
<https://starwars.com#grid_P18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Corric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#44788cd8-3fbb-46fc-b190-90d2407ad1f4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Andalasa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cc144353-890e-4acc-809c-46c9cd29f866> .
<https://starwars.com#cc144353-890e-4acc-809c-46c9cd29f866> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Andalasa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#cc144353-890e-4acc-809c-46c9cd29f866> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Corric> <http://telicent.io/ontology/primaryName> "Cor'ric" .
<https://starwars.com#grid_P18> <http://telicent.io/ontology/primaryName> "P18" .
<https://starwars.com#grid_P18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#44788cd8-3fbb-46fc-b190-90d2407ad1f4> .
<https://starwars.com#grid_P18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Corric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Andalasa> <http://telicent.io/ontology/primaryName> "Andalasa" .
<https://starwars.com#planet_Andalasa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corric> .
<https://starwars.com#planet_Andalasa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#44788cd8-3fbb-46fc-b190-90d2407ad1f4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Andalasa> <http://www.w3.org/2000/01/rdf-schema#comment> "Andasala was a mining world, located on the Llanic Spice Run in the Andasala system near Svivren. " .

