Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_P8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_P8> <http://telicent.io/ontology/primaryName> "P8" .
<https://starwars.com#sector_Truum> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9d114094-867e-48fb-8379-1aa6a4e972d5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Azure"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Truum> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Truum> <http://telicent.io/ontology/primaryName> "Truum" .
<https://starwars.com#grid_P8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_P8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#430654f6-2d3f-42e6-a833-a7fd384808e2> .
<https://starwars.com#9d114094-867e-48fb-8379-1aa6a4e972d5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Azure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P8> .
<https://starwars.com#planet_Azure> <http://telicent.io/ontology/primaryName> "Azure" .
<https://starwars.com#430654f6-2d3f-42e6-a833-a7fd384808e2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Azure> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Azure> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Truum> .
<https://starwars.com#planet_Azure> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9d114094-867e-48fb-8379-1aa6a4e972d5> .
<https://starwars.com#planet_Azure> <http://www.w3.org/2000/01/rdf-schema#comment> "Azure was an astronomical object located in the regions known as the Mid Rim Territories and the Slice. It was positioned in grid square P-8 on the Standard Galactic Grid. " .
<https://starwars.com#430654f6-2d3f-42e6-a833-a7fd384808e2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P8"^^<http://www.w3.org/2001/XMLSchema#string> .

