Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Sakidopa> <http://telicent.io/ontology/primaryName> "Sakidopa" .
<https://starwars.com#planet_Sakidopa> <http://www.w3.org/2000/01/rdf-schema#comment> "Sakidopa, which could be translated as 'Second Saki,' was a planet located in the Bootana Hutta region of Hutt Space. " .
<https://starwars.com#a844235e-1884-46db-a0ed-aae41ed0f538> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sakidopa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sakidopa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a844235e-1884-46db-a0ed-aae41ed0f538> .
<https://starwars.com#planet_Sakidopa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a844235e-1884-46db-a0ed-aae41ed0f538> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sakidopa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Sakidopa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .

