Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thrantin> <http://telicent.io/ontology/primaryName> "Thrantin" .
<https://starwars.com#sector_OllonirBoundaries> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Thrantin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_OllonirBoundaries> .
<https://starwars.com#planet_Thrantin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thrantin> <http://www.w3.org/2000/01/rdf-schema#comment> "Thrantin, or OM813, was the planet headquarters of Barosa Warren and the Galactic Outdoor Survival School. It was located in the Ollonir Boundaries of the Colonies. " .
<https://starwars.com#8ff3c6e8-aaff-4185-a402-65e9ba41645b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thrantin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_OllonirBoundaries> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thrantin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8ff3c6e8-aaff-4185-a402-65e9ba41645b> .
<https://starwars.com#planet_Thrantin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J9> .
<https://starwars.com#sector_OllonirBoundaries> <http://telicent.io/ontology/primaryName> "Ollonir Boundaries" .
<https://starwars.com#8ff3c6e8-aaff-4185-a402-65e9ba41645b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

