Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gendrah-Narvin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#361a20f4-f48c-400c-8112-396d23b8b4b3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gendrah-Narvin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gendrah-Narvin> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#361a20f4-f48c-400c-8112-396d23b8b4b3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gendrah-Narvin> <http://telicent.io/ontology/primaryName> "Gendrah-Narvin" .
<https://starwars.com#planet_Gendrah-Narvin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#361a20f4-f48c-400c-8112-396d23b8b4b3> .
<https://starwars.com#planet_Gendrah-Narvin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_Gendrah-Narvin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

