Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ae41012f-acf1-4a91-9c7a-ec078cb0b34b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Drexel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dail> .
<https://starwars.com#98d6ea8d-42a1-4d5f-8f72-baae523454f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Drexel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#98d6ea8d-42a1-4d5f-8f72-baae523454f9> .
<https://starwars.com#sector_Dail> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Dail> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Drexel> <http://telicent.io/ontology/primaryName> "Drexel" .
<https://starwars.com#planet_Drexel> <http://www.w3.org/2000/01/rdf-schema#comment> "Drexel was an astronomical object located in the galaxy's Outer Rim Territories, positioned at the coordinates Q-18 on the Standard Galactic Grid. The astronomical object was associated with individuals known as Drexelian shell-diggers, who often dressed in ragged clothing. " .
<https://starwars.com#grid_Q18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ae41012f-acf1-4a91-9c7a-ec078cb0b34b> .
<https://starwars.com#grid_Q18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#98d6ea8d-42a1-4d5f-8f72-baae523454f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Drexel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ae41012f-acf1-4a91-9c7a-ec078cb0b34b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Dail> <http://telicent.io/ontology/primaryName> "Dail" .
<https://starwars.com#planet_Drexel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Drexel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q18> .
<https://starwars.com#grid_Q18> <http://telicent.io/ontology/primaryName> "Q18" .
<https://starwars.com#grid_Q18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

