Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Iseno> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Iseno> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Iseno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Iseno> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e8c0918d-7cb4-4d59-92db-54e0bd00e9b7> .
<https://starwars.com#planet_Iseno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_Iseno> <http://www.w3.org/2000/01/rdf-schema#comment> "Iseno was an astronomical object located in the galaxy's Inner Rim that was situated along the Corellian Run. " .
<https://starwars.com#planet_Iseno> <http://telicent.io/ontology/primaryName> "Iseno" .
<https://starwars.com#e8c0918d-7cb4-4d59-92db-54e0bd00e9b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Iseno> <http://telicent.io/ontology/primaryName> "Iseno" .
<https://starwars.com#e8c0918d-7cb4-4d59-92db-54e0bd00e9b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iseno"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iseno> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Iseno> .

