Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Droma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#9b600eae-730f-4fa1-a614-75c55d17fcd4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lonnaw"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lonnaw> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lonnaw> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#planet_Lonnaw> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9b600eae-730f-4fa1-a614-75c55d17fcd4> .
<https://starwars.com#planet_Lonnaw> <http://www.w3.org/2000/01/rdf-schema#comment> "Lonnaw was a Mid Rim planet located on the Entralla Route. It served as the first scheduled stop on the shakedown cruise of the Galactic Republic exploratory vessel Outbound Flight in 27 BBY. Thirty-nine years later, Lonnaw was temporarily captured from the New Republic by the Imperial Remnant. " .
<https://starwars.com#9b600eae-730f-4fa1-a614-75c55d17fcd4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Lonnaw> <http://telicent.io/ontology/primaryName> "Lonnaw" .
<https://starwars.com#sector_Droma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Droma> <http://telicent.io/ontology/primaryName> "Droma" .
<https://starwars.com#planet_Lonnaw> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Droma> .

