Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Sujimis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Karazak> <http://telicent.io/ontology/primaryName> "Karazak" .
<https://starwars.com#planet_Karazak> <http://www.w3.org/2000/01/rdf-schema#comment> "Karazak was a terrestrial world located in the Outer Rim Territories and Trailing Sectors, positioned at the coordinates P-19 on the Standard Galactic Grid. Karazak was known for its slavery, a trade that was tolerated, but also regulated, by the Galactic Empire. It shared its name with the slaver organization known as the Karazak Slavers' Cooperative. " .
<https://starwars.com#planet_Karazak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Sujimis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Karazak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a518df1-117d-49ab-9c1a-5e5cfbf5f580> .
<https://starwars.com#3a518df1-117d-49ab-9c1a-5e5cfbf5f580> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karazak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Karazak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sujimis> .
<https://starwars.com#sector_Sujimis> <http://telicent.io/ontology/primaryName> "Sujimis" .
<https://starwars.com#3a518df1-117d-49ab-9c1a-5e5cfbf5f580> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Karazak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P19> .

