Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Halm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J16> .
<https://starwars.com#planet_Halm> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12baea5c-0565-4873-a307-dbec5b2a3ce7> .
<https://starwars.com#planet_Halm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#54855dcb-8c6c-4f70-8ca4-e94719386253> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_J16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#54855dcb-8c6c-4f70-8ca4-e94719386253> .
<https://starwars.com#sector_Halm> <http://telicent.io/ontology/primaryName> "Halm" .
<https://starwars.com#planet_Halm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halm> .
<https://starwars.com#12baea5c-0565-4873-a307-dbec5b2a3ce7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Halm> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Halm> <http://telicent.io/ontology/primaryName> "Halm" .
<https://starwars.com#grid_J16> <http://telicent.io/ontology/primaryName> "J16" .
<https://starwars.com#grid_J16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#54855dcb-8c6c-4f70-8ca4-e94719386253> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Halm> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#12baea5c-0565-4873-a307-dbec5b2a3ce7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Halm"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Halm> <http://www.w3.org/2000/01/rdf-schema#comment> "Halm was an arid desert world, famous for its extensive mines. These mines contained rare Adegan crystals, which were used in the construction of lightsabers. " .

