Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Karideph> <http://www.w3.org/2000/01/rdf-schema#comment> "Karideph was an astronomical object located in the galaxy's Outer Rim Territories, situated along the Rimma Trade Route. " .
<https://starwars.com#planet_Karideph> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8403c536-b722-473a-9a7b-f818460f4d3b> .
<https://starwars.com#sector_Minos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Karideph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Minos> .
<https://starwars.com#8403c536-b722-473a-9a7b-f818460f4d3b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8403c536-b722-473a-9a7b-f818460f4d3b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karideph"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Karideph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#sector_Minos> <http://telicent.io/ontology/primaryName> "Minos" .
<https://starwars.com#sector_Minos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Karideph> <http://telicent.io/ontology/primaryName> "Karideph" .
<https://starwars.com#planet_Karideph> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

