Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tammuz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Shiffrin> <http://telicent.io/ontology/primaryName> "Shiffrin" .
<https://starwars.com#planet_Shiffrin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#56baa8fe-e945-405a-8d2e-afaf0fe78088> .
<https://starwars.com#planet_Shiffrin> <http://www.w3.org/2000/01/rdf-schema#comment> "Shiffrin was an Outer Rim Territories planet located in the Tammuz sector. Constable Kallin Bremen maintained law and order in a small village there. At one point, a Shiffrin farmer discovered what turned out to be large deposits of the valuable ore hfredium, and the Galactic Empire subsequently established a garrison there and began confiscating the properties of local landowners. Bremen was eventually executed after planning a peaceful demonstration against the confiscations, and his son, Jak Bremen, went on to leave the planet. " .
<https://starwars.com#planet_Shiffrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T15> .
<https://starwars.com#planet_Shiffrin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Tammuz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Shiffrin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tammuz> .
<https://starwars.com#sector_Tammuz> <http://telicent.io/ontology/primaryName> "Tammuz" .
<https://starwars.com#56baa8fe-e945-405a-8d2e-afaf0fe78088> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shiffrin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#56baa8fe-e945-405a-8d2e-afaf0fe78088> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

