Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#87d49a3f-512a-45fb-a410-a86bcdfbf96d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Ferra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e3e13d58-62f1-4680-8388-f6f840372814> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hypori"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hypori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S16> .
<https://starwars.com#e3e13d58-62f1-4680-8388-f6f840372814> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_S16> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Hypori> <http://telicent.io/ontology/primaryName> "Hypori" .
<https://starwars.com#grid_S16> <http://telicent.io/ontology/primaryName> "S16" .
<https://starwars.com#planet_Hypori> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e3e13d58-62f1-4680-8388-f6f840372814> .
<https://starwars.com#sector_Ferra> <http://telicent.io/ontology/primaryName> "Ferra" .
<https://starwars.com#planet_Hypori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ferra> .
<https://starwars.com#grid_S16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Ferra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_S16> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#87d49a3f-512a-45fb-a410-a86bcdfbf96d> .
<https://starwars.com#planet_Hypori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#87d49a3f-512a-45fb-a410-a86bcdfbf96d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S16"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hypori> <http://www.w3.org/2000/01/rdf-schema#comment> "Hypori was a remote world located in the Outer Rim Territories along the Corellian Run with a hydrothermal landscape that was host to a Techno Union droid factory. The hulk of a crashed Acclamator-class transgalactic military assault ship stood as a grim memorial of a battle during the Clone Wars in which a group of Jedi Knights were taken by surprise. During the Imperial Era, Commander Orson Krennic's engineering team was based at an Imperial facility on the planet where they worked in weapon development for the Galactic Empire. In 18 BBY, the research station was destroyed by Star Destroyer turbolasers. At some point Sheev Palpatine ordered for the Cosinga-class Heavy Corvette Imperialis to be constructed over Hypori. " .

