Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#aee9dfc0-afa6-4452-bbb9-43260634c537> .
<https://starwars.com#planet_Alpheridies> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Farstey> .
<https://starwars.com#grid_O8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#aee9dfc0-afa6-4452-bbb9-43260634c537> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Farstey> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#aee9dfc0-afa6-4452-bbb9-43260634c537> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8b7e44b1-ab5f-4ba7-8eff-6b3f540021f3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Alpheridies"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#8b7e44b1-ab5f-4ba7-8eff-6b3f540021f3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Farstey> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Alpheridies> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8b7e44b1-ab5f-4ba7-8eff-6b3f540021f3> .
<https://starwars.com#sector_Farstey> <http://telicent.io/ontology/primaryName> "Farstey" .
<https://starwars.com#grid_O8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_O8> <http://telicent.io/ontology/primaryName> "O8" .
<https://starwars.com#planet_Alpheridies> <http://www.w3.org/2000/01/rdf-schema#comment> "Alpheridies was an astronomical body located in the galaxy's Expansion Region. " .
<https://starwars.com#planet_Alpheridies> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Alpheridies> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Alpheridies> <http://telicent.io/ontology/primaryName> "Alpheridies" .

