Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Steelious> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#36637619-728b-4c1f-9863-05d8ff6590a4> .
<https://starwars.com#planet_Steelious> <http://telicent.io/ontology/primaryName> "Steelious" .
<https://starwars.com#planet_Steelious> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#planet_Steelious> <http://www.w3.org/2000/01/rdf-schema#comment> "Steelious was a Core Worlds planet that was located near the world Yarrv. The Hervack Spaceport on Steelious served as an important port for Rebel Alliance smuggling. Shortly after the Battle of Yavin, diplomats from Steelious traveled to Yarrv in order to negotiate a trade agreement with the latter planet's ruling royal family. Yarrv's Baron Karin, in the hopes of subjugating Steelious, planned to assassinate the diplomats, causing a war between the two planets that would benefit the military conglomerate owned by the baron. " .
<https://starwars.com#planet_Steelious> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#36637619-728b-4c1f-9863-05d8ff6590a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Steelious"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Steelious> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#36637619-728b-4c1f-9863-05d8ff6590a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

