Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rorgam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Terrskiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Terrskiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#6131d057-358a-4375-8bcb-1a0373240ca4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rorgam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#planet_Rorgam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Terrskiar> .
<https://starwars.com#planet_Rorgam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6131d057-358a-4375-8bcb-1a0373240ca4> .
<https://starwars.com#sector_Terrskiar> <http://telicent.io/ontology/primaryName> "Terr'skiar" .
<https://starwars.com#6131d057-358a-4375-8bcb-1a0373240ca4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rorgam"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rorgam> <http://www.w3.org/2000/01/rdf-schema#comment> "Rorgam was a Mid Rim planet whose population consisted mainly of immigrants from other planets. Many of the world's elite were known to wear wrapped cloth headpieces. " .
<https://starwars.com#planet_Rorgam> <http://telicent.io/ontology/primaryName> "Rorgam" .

