Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Uquine> <http://www.w3.org/2000/01/rdf-schema#comment> "Uquine was a placid planet located in the galaxy's Colonies region. The agricultural scientist Tepha Leonis gave birth to her second child, Zare Leonis on the planet, although the Leonis family left the world, living in a number of locations including the space station Hosk Station and the planet Lothal. Uquine was also the homeworld of the rebel pilot Col Takbright. Before he left Uquine, Takbright watched in agitation as the Galactic Empire spread across the galaxy devouring worlds for ore and killing those who opposed them. After realizing he couldn't spend another day on his homeworld doing nothing, he left Uquine with credits, a duffel bag, and a vow to avenge those that had been wronged by the Empire. " .
<https://starwars.com#planet_Uquine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#4e346d1f-0d6c-4533-afba-3f2af125fce8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Uquine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4e346d1f-0d6c-4533-afba-3f2af125fce8> .
<https://starwars.com#4e346d1f-0d6c-4533-afba-3f2af125fce8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Uquine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Uquine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Uquine> <http://telicent.io/ontology/primaryName> "Uquine" .
<https://starwars.com#planet_Uquine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

