Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#3391ec01-d85c-4c71-85c2-051e60b63a4e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Trellen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Trellen> <http://telicent.io/ontology/primaryName> "Trellen" .
<https://starwars.com#planet_Trellen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3391ec01-d85c-4c71-85c2-051e60b63a4e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trellen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trellen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3391ec01-d85c-4c71-85c2-051e60b63a4e> .
<https://starwars.com#planet_Trellen> <http://www.w3.org/2000/01/rdf-schema#comment> "Trellen was a planet at the junction of the Hydian Way and the Trellen Trade Route. " .
<https://starwars.com#planet_Trellen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .

