Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ketal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ketal> <http://telicent.io/ontology/primaryName> "Ketal" .
<https://starwars.com#f09b2cc1-e129-4776-b49e-86f2fa8bea46> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ketal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ketal> <http://www.w3.org/2000/01/rdf-schema#comment> "Ketal was a planet located in the Ketal system in the Inner Rim Territories. " .
<https://starwars.com#planet_Ketal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f09b2cc1-e129-4776-b49e-86f2fa8bea46> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ketal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f09b2cc1-e129-4776-b49e-86f2fa8bea46> .
<https://starwars.com#planet_Ketal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .

