Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Trigalis> <http://telicent.io/ontology/primaryName> "Trigalis" .
<https://starwars.com#planet_Trigalis> <http://www.w3.org/2000/01/rdf-schema#comment> "Trigalis was an astronomical object located in the regions known as the Outer Rim Territories and the Trailing Sectors. It was situated in grid square P-17 of the Standard Galactic Grid. A hyperspace route connected Trigalis to the asteroid Vergesso as well as the celestial body Farstine in the Mid Rim Territories. " .
<https://starwars.com#c6cee0d6-bdcd-454f-aea0-95f7e72473c7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Trigalis"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Trigalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cadavine> .
<https://starwars.com#planet_Trigalis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P17> .
<https://starwars.com#sector_Cadavine> <http://telicent.io/ontology/primaryName> "Cadavine" .
<https://starwars.com#planet_Trigalis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c6cee0d6-bdcd-454f-aea0-95f7e72473c7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Cadavine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Trigalis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c6cee0d6-bdcd-454f-aea0-95f7e72473c7> .
<https://starwars.com#sector_Cadavine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

