Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SeventhSecurityZone> <http://telicent.io/ontology/primaryName> "Seventh Security Zone" .
<https://starwars.com#planet_Walalla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3adef9b9-5901-42ca-aa94-3e51af370c1b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Walalla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Walalla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3adef9b9-5901-42ca-aa94-3e51af370c1b> .
<https://starwars.com#planet_Walalla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J13> .
<https://starwars.com#planet_Walalla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SeventhSecurityZone> .
<https://starwars.com#3adef9b9-5901-42ca-aa94-3e51af370c1b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Walalla> <http://www.w3.org/2000/01/rdf-schema#comment> "Walalla was a planet located within the Walalla system of the Inner Rim. " .
<https://starwars.com#sector_SeventhSecurityZone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Walalla> <http://telicent.io/ontology/primaryName> "Walalla" .
<https://starwars.com#sector_SeventhSecurityZone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

