Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#97087f9d-a394-47ed-ab6a-240205a6d8ff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Voorsbain> <http://www.w3.org/2000/01/rdf-schema#comment> "Voorsbain was a planet located within the Voorsbain system of Senex sector of the Mid Rim. It was an industrial world where House Picutorion-funded research into advanced technology was conducted. " .
<https://starwars.com#planet_Voorsbain> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Voorsbain> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#97087f9d-a394-47ed-ab6a-240205a6d8ff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Voorsbain"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Voorsbain> <http://telicent.io/ontology/primaryName> "Voorsbain" .
<https://starwars.com#planet_Voorsbain> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Voorsbain> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#97087f9d-a394-47ed-ab6a-240205a6d8ff> .

