Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Emberlene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P12> .
<https://starwars.com#sector_Authala> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Emberlene> <http://telicent.io/ontology/primaryName> "Emberlene" .
<https://starwars.com#planet_Emberlene> <http://www.w3.org/2000/01/rdf-schema#comment> "Emberlene was a planet located in the Authala sector of the Expansion Region. " .
<https://starwars.com#planet_Emberlene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Authala> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#ddfe41a3-8ec9-4a90-978a-c8621a473aff> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ddfe41a3-8ec9-4a90-978a-c8621a473aff> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Emberlene"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Emberlene> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ddfe41a3-8ec9-4a90-978a-c8621a473aff> .
<https://starwars.com#planet_Emberlene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Authala> .
<https://starwars.com#sector_Authala> <http://telicent.io/ontology/primaryName> "Authala" .

