Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Grohl> <http://telicent.io/ontology/primaryName> "Grohl" .
<https://starwars.com#planet_Koiogra> <http://telicent.io/ontology/primaryName> "Koiogra" .
<https://starwars.com#5acfcf62-0075-47b9-9170-fa76a26f927f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Koiogra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Koiogra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5acfcf62-0075-47b9-9170-fa76a26f927f> .
<https://starwars.com#planet_Koiogra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Grohl> .
<https://starwars.com#planet_Koiogra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Koiogra> <http://www.w3.org/2000/01/rdf-schema#comment> "Koiogra was a world which had been visited by the New Republic pilot Chass na Chadic. While on Koiogra, she discovered a recording of Jyn Erso's speech prior to the Battle of Scarif, realizing she had previously met the rebel on Uchinao a year earlier. " .
<https://starwars.com#planet_Koiogra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Grohl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#5acfcf62-0075-47b9-9170-fa76a26f927f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Grohl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

