Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vulcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Vulcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#c411cc01-093c-4bd0-84b7-d2fb635acb94> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#c411cc01-093c-4bd0-84b7-d2fb635acb94> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vulcar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vulcar> <http://telicent.io/ontology/primaryName> "Vulcar" .
<https://starwars.com#planet_Vulcar> <http://www.w3.org/2000/01/rdf-schema#comment> "Vulcar was a baleful orange, sulfurous planet located in the Vulcar system, within the Juvex sector of the galaxy's Mid Rim. A hyperlane branching off the Senex-Juvex Loop connected it to the worlds of Tinallis and Tyluun. Home to the eponymous Sulphur Pits of Vulcar, its acrid atmosphere made employing humanoid workers to extract the world's oridium deposits barely cost-effective. Instead, Vulcar was primarily worked by droids of all types, including crab droids, reprogrammed to serve as miners until they froze up and rusted into scrap. In 15 BBY, an Intergalactic Droid Agency shuttle traveled to the Sulphur Pits of Vulcar after delivering the droids R2-D2 and C-3PO to the planet Dodz. " .
<https://starwars.com#planet_Vulcar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c411cc01-093c-4bd0-84b7-d2fb635acb94> .
<https://starwars.com#planet_Vulcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

