Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_SkustellCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Skustell Cluster was a star cluster located within the Tarabba sector in the Outer Rim region of the galaxy which contained the planet Skustell. " .
<https://starwars.com#sector_Tarabba> <http://telicent.io/ontology/primaryName> "Tarabba" .
<https://starwars.com#planet_SkustellCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tarabba> .
<https://starwars.com#758d9830-9da0-41e3-a40c-17b0668ef2dc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skustell Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_SkustellCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#758d9830-9da0-41e3-a40c-17b0668ef2dc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tarabba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_SkustellCluster> <http://telicent.io/ontology/primaryName> "Skustell Cluster" .
<https://starwars.com#planet_SkustellCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#758d9830-9da0-41e3-a40c-17b0668ef2dc> .
<https://starwars.com#sector_Tarabba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_SkustellCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N19> .

