Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Circarpous> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Mimban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#planet_Mimban> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1062ca92-7e60-4902-b937-2981d3417fda> .
<https://starwars.com#1062ca92-7e60-4902-b937-2981d3417fda> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mimban"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mimban> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Circarpous> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mimban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Circarpous> .
<https://starwars.com#planet_Mimban> <http://telicent.io/ontology/primaryName> "Mimban" .
<https://starwars.com#planet_Mimban> <http://www.w3.org/2000/01/rdf-schema#comment> "Swamp planet with perpetual fog and overcast sky." .
<https://starwars.com#1062ca92-7e60-4902-b937-2981d3417fda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Circarpous> <http://telicent.io/ontology/primaryName> "Circarpous" .

