Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rakhuuun> <http://www.w3.org/2000/01/rdf-schema#comment> "Rakhuuun was a planet that was located in the Rakhuuun system of the Mytaranor sector. It was a part of the Kashyyyk Region, in the Slice portion of the Mid Rim. The Randon Run hyperlane connected the planet to the worlds of Chamble and Kashyyyk. " .
<https://starwars.com#73cde4e4-900f-4a9c-b77b-50abd020814b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rakhuuun"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rakhuuun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Rakhuuun> <http://telicent.io/ontology/primaryName> "Rakhuuun" .
<https://starwars.com#planet_Rakhuuun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#planet_Rakhuuun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#planet_Rakhuuun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73cde4e4-900f-4a9c-b77b-50abd020814b> .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#73cde4e4-900f-4a9c-b77b-50abd020814b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

