Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tokmia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Tokmia> <http://telicent.io/ontology/primaryName> "Tokmia" .
<https://starwars.com#planet_Tokmia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1a4e2cf3-faf1-4448-b496-7e3e86b9ff6d> .
<https://starwars.com#planet_Tokmia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#1a4e2cf3-faf1-4448-b496-7e3e86b9ff6d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tokmia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tokmia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#1a4e2cf3-faf1-4448-b496-7e3e86b9ff6d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tokmia> <http://www.w3.org/2000/01/rdf-schema#comment> "Assumption ends here." .

