Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tepasi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tepasi> <http://www.w3.org/2000/01/rdf-schema#comment> "Tepasi was a planet located in the galaxy's Core Worlds region. Tepasi was the homeworld of Grand General Cassio Tagge, a member of the Galactic Empire during the Galactic Civil War who was born into the noble House of Tagge. It shared its name with Tepasi taffy. " .
<https://starwars.com#planet_Tepasi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Tepasi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#1f426694-29f9-4db8-8659-01254706579d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tepasi"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tepasi> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1f426694-29f9-4db8-8659-01254706579d> .
<https://starwars.com#planet_Tepasi> <http://telicent.io/ontology/primaryName> "Tepasi" .
<https://starwars.com#1f426694-29f9-4db8-8659-01254706579d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

