Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_N7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Aquaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sumitra> .
<https://starwars.com#sector_Sumitra> <http://telicent.io/ontology/primaryName> "Sumitra" .
<https://starwars.com#sector_Sumitra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Sumitra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#de370bdf-cf55-4323-a9f9-448e2bc1f2e8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#de370bdf-cf55-4323-a9f9-448e2bc1f2e8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aquaris> <http://telicent.io/ontology/primaryName> "Aquaris" .
<https://starwars.com#grid_N7> <http://telicent.io/ontology/primaryName> "N7" .
<https://starwars.com#grid_N7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#de370bdf-cf55-4323-a9f9-448e2bc1f2e8> .
<https://starwars.com#grid_N7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Aquaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#planet_Aquaris> <http://www.w3.org/2000/01/rdf-schema#comment> "Aquaris was a planet located in the galaxy's Expansion Region. It and Thustra were the closest principal planets to the location of the stolen Imperial corvette Carrion Spike while it was at the location sector-designated as LCC-4-4-7. Aquaris had a notable criminal presence, and was located near the Perlemian Trade Route. The former pirate Queen Maz Kanata marked it as the location of an outlaw garage on a map that she included in the book that became known as the Smuggler's Guide. The planet shared its name with the Aquaris Freeholders. " .
<https://starwars.com#planet_Aquaris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a309f78f-4901-4a05-8cf1-8ba3879def57> .
<https://starwars.com#a309f78f-4901-4a05-8cf1-8ba3879def57> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aquaris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#a309f78f-4901-4a05-8cf1-8ba3879def57> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aquaris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

