Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vinsoth> <http://www.w3.org/2000/01/rdf-schema#comment> "Vinsoth was an astronomical object located in the galaxy's Outer Rim Territories. At some point, the Chevin Jol Bengim encountered slavers and slave camps on Vinsoth, although he later moved to the planet Jakku. " .
<https://starwars.com#planet_Vinsoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vinsoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Quelii> .
<https://starwars.com#sector_Quelii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#813b60f7-9ff1-4560-af71-a273a3356335> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vinsoth> <http://telicent.io/ontology/primaryName> "Vinsoth" .
<https://starwars.com#planet_Vinsoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N5> .
<https://starwars.com#sector_Quelii> <http://telicent.io/ontology/primaryName> "Quelii" .
<https://starwars.com#813b60f7-9ff1-4560-af71-a273a3356335> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vinsoth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vinsoth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#813b60f7-9ff1-4560-af71-a273a3356335> .
<https://starwars.com#sector_Quelii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

