Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_RingofKafrene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thand> .
<https://starwars.com#planet_RingofKafrene> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ec695232-d304-4a55-bce6-09b40c454937> .
<https://starwars.com#planet_RingofKafrene> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ec695232-d304-4a55-bce6-09b40c454937> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ring of Kafrene"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Thand> <http://telicent.io/ontology/primaryName> "Thand" .
<https://starwars.com#planet_RingofKafrene> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J15> .
<https://starwars.com#sector_Thand> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_RingofKafrene> <http://telicent.io/ontology/primaryName> "Ring of Kafrene" .
<https://starwars.com#planet_RingofKafrene> <http://www.w3.org/2000/01/rdf-schema#comment> "The Ring of Kafrene, also referred to simply as Kafrene, was a mining colony and deep-space trading post in the Kafrene asteroid belt of the Thand sector. The Alliance to Restore the Republic sent intelligence agent Cassian Andor here prior to the outbreak of the Galactic Civil War. There, Andor learned of the existence of the Death Star. " .
<https://starwars.com#sector_Thand> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ec695232-d304-4a55-bce6-09b40c454937> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

