Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_Kwevron> <http://www.w3.org/2000/01/rdf-schema#comment> "Kwevron was an Outer Rim Territories agriworld. It was a lightly populated world, with almost of all of its people engaged in farming to provide food for neighboring sectors. An Imperial Prefect oversaw its starport during the Galactic Civil War. Hills and fields covered most of its surface. " .
<https://starwars.com#planet_Kwevron> <http://telicent.io/ontology/primaryName> "Kwevron" .
<https://starwars.com#planet_Kwevron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#a44c7ce4-1e3a-49f6-a333-6dd78e332e61> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a44c7ce4-1e3a-49f6-a333-6dd78e332e61> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kwevron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kwevron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a44c7ce4-1e3a-49f6-a333-6dd78e332e61> .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kwevron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kwevron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .

