Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Toprawa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#43d5e9ce-922f-44a5-ae6d-f47089cfdd61> .
<https://starwars.com#sector_Kalamith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Toprawa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kalamith> .
<https://starwars.com#sector_Kalamith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#43d5e9ce-922f-44a5-ae6d-f47089cfdd61> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Toprawa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Toprawa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Toprawa> <http://telicent.io/ontology/primaryName> "Toprawa" .
<https://starwars.com#planet_Toprawa> <http://www.w3.org/2000/01/rdf-schema#comment> "Toprawa was a planet located in the regions known as the Outer Rim Territories and the New Territories, in the grid square P-5 of the Standard Galactic Grid. It was connected to the locations Junction and Pho Ph'eah by the Hydian Way hyperspace route. From space, the surface of Toprawa appeared light and dark green in color. " .
<https://starwars.com#planet_Toprawa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_Kalamith> <http://telicent.io/ontology/primaryName> "Kalamith" .
<https://starwars.com#43d5e9ce-922f-44a5-ae6d-f47089cfdd61> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

