Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Baxel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lirra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lirra> <http://www.w3.org/2000/01/rdf-schema#comment> "By 2 ABY, Lirra was a resort world, with over a million Humans serving the Hutts as slaves. When an undercover news crew discovered the status of the Humans, the Galactic Empire drove the Jhank Shel off Lirra and claimed the planet, causing Lirra's Human population to be retrained to become Imperial citizens. " .
<https://starwars.com#planet_Lirra> <http://telicent.io/ontology/primaryName> "Lirra" .
<https://starwars.com#planet_Lirra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b3a7082-eabf-482f-991d-75c8de1fb2ef> .
<https://starwars.com#planet_Lirra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U12> .
<https://starwars.com#3b3a7082-eabf-482f-991d-75c8de1fb2ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#3b3a7082-eabf-482f-991d-75c8de1fb2ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lirra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lirra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Baxel> .
<https://starwars.com#sector_Baxel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Baxel> <http://telicent.io/ontology/primaryName> "Baxel" .

