Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Orron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f120fc5b-5469-49cf-a7ab-708b03dab1bb> .
<https://starwars.com#planet_Orron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Orron> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#f120fc5b-5469-49cf-a7ab-708b03dab1bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#f120fc5b-5469-49cf-a7ab-708b03dab1bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orron"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Orron> <http://telicent.io/ontology/primaryName> "Orron" .
<https://starwars.com#planet_Orron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Orron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .

