Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kegan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0958924c-5956-4982-a8dc-b645faede48a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kegan> <http://telicent.io/ontology/primaryName> "Kegan" .
<https://starwars.com#planet_Kegan> <http://www.w3.org/2000/01/rdf-schema#comment> "Kegan was a planet located in the Outer Rim Territories. The planet was run by the Benevolent Guides, who isolated the planet from the rest of the galaxy after having visions of the destruction of Kegan. During the Yuuzhan Vong War, Kegan was conquered by the extragalactic Yuuzhan Vong. " .
<https://starwars.com#0958924c-5956-4982-a8dc-b645faede48a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kegan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kegan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0958924c-5956-4982-a8dc-b645faede48a> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#planet_Kegan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T9> .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kegan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .

