Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Scillal> <http://www.w3.org/2000/01/rdf-schema#comment> "The Scillal system was located in the Centrality sector, a part of the Slice portion of the Outer Rim Territories. The Cadma Conduit hyperlane connected it to the Erilnar and Lekua systems" .
<https://starwars.com#planet_Scillal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Scillal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e5f5f343-a6dd-4648-ad9f-69c9d3363a6b> .
<https://starwars.com#e5f5f343-a6dd-4648-ad9f-69c9d3363a6b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Scillal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#e5f5f343-a6dd-4648-ad9f-69c9d3363a6b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Scillal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Scillal> <http://telicent.io/ontology/primaryName> "Scillal" .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Scillal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .

