Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Salliche> <http://telicent.io/ontology/primaryName> "Salliche" .
<https://starwars.com#planet_Salliche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Salliche> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#125920d8-e3d5-4638-a6c1-4a3cf08af8f9> .
<https://starwars.com#planet_Salliche> <http://www.w3.org/2000/01/rdf-schema#comment> "   This article is a stub about a planet. You can help Wookieepedia by expanding it. " .
<https://starwars.com#planet_Salliche> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#125920d8-e3d5-4638-a6c1-4a3cf08af8f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Salliche"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Salliche> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#125920d8-e3d5-4638-a6c1-4a3cf08af8f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

