Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#380b88b1-40b0-43cb-8ecc-1fea26278d31> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M'haeli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#380b88b1-40b0-43cb-8ecc-1fea26278d31> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mhaeli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#sector_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Mhaeli> <http://telicent.io/ontology/primaryName> "M'haeli" .
<https://starwars.com#planet_Mhaeli> <http://www.w3.org/2000/01/rdf-schema#comment> "M'haeli was an agriworld located in the galaxy's Expansion Region. The world contained the D'olop mountain range, where dragite gems were mined for use in lightsabers. " .
<https://starwars.com#sector_Majoor> <http://telicent.io/ontology/primaryName> "Majoor" .
<https://starwars.com#sector_Majoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mhaeli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Majoor> .
<https://starwars.com#planet_Mhaeli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mhaeli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#380b88b1-40b0-43cb-8ecc-1fea26278d31> .

