Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Barlok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Marcol> .
<https://starwars.com#planet_Barlok> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#a6582ba5-f0cd-4569-97ed-df359d0fd772> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Barlok"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Marcol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#a6582ba5-f0cd-4569-97ed-df359d0fd772> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Marcol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Marcol> <http://telicent.io/ontology/primaryName> "Marcol" .
<https://starwars.com#planet_Barlok> <http://www.w3.org/2000/01/rdf-schema#comment> "Barlok was a planet in the Barlok system of the Marcol sector, between three and six days of hyperspace travel from Coruscant, and was also a member world of the Galactic Republic. It was known for tisvollt forests, inhabited by the indigenous Karfs; its agricultural produce, including delicious prisht fruit; its sprawling Patameene District, including the Starbright hotel, Panky's restaurant, and the Covered Brush housing ring; and its mines, the ownership of which was a point of dispute between the guilds of the indigenous Brolfi and the Corporate Alliance, including the Mining Guild. " .
<https://starwars.com#planet_Barlok> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Barlok> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a6582ba5-f0cd-4569-97ed-df359d0fd772> .
<https://starwars.com#planet_Barlok> <http://telicent.io/ontology/primaryName> "Barlok" .

