Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#7ee7cb9c-067a-4ab6-b7b7-2d896c4d0595> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_RingoVinda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Eucer> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_RingoVinda> <http://www.w3.org/2000/01/rdf-schema#comment> "Ringo Vinda was a planet located in the galaxy's Mid Rim, along the Perlemian Trade Route. It was encircled by a massive civilian graving dock. The Ringo Vindans, a human cultural group, spoke Galactic Basic Standard with a distinctive accent. In the waning decades of the Galactic Republic, Jedi Knight Rael Averross hailed from Ringo Vinda. " .
<https://starwars.com#planet_RingoVinda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#planet_RingoVinda> <http://telicent.io/ontology/primaryName> "Ringo Vinda" .
<https://starwars.com#planet_RingoVinda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Eucer> .
<https://starwars.com#sector_Eucer> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_RingoVinda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7ee7cb9c-067a-4ab6-b7b7-2d896c4d0595> .
<https://starwars.com#sector_Eucer> <http://telicent.io/ontology/primaryName> "Eucer" .
<https://starwars.com#7ee7cb9c-067a-4ab6-b7b7-2d896c4d0595> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ringo Vinda"^^<http://www.w3.org/2001/XMLSchema#string> .

