Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jalarren> <http://telicent.io/ontology/primaryName> "Jalarren" .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jalarren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#ce12f7ca-a413-4d39-9120-8d02db2a4768> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jalarren"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jalarren> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Jalarren> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ce12f7ca-a413-4d39-9120-8d02db2a4768> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jalarren> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Jalarren> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ce12f7ca-a413-4d39-9120-8d02db2a4768> .

