Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_VarHagen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Vogel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_VarHagen> .
<https://starwars.com#4b469231-20a6-4ad8-a96a-8b438cac61af> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vogel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#4b469231-20a6-4ad8-a96a-8b438cac61af> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vogel> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Vogel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4b469231-20a6-4ad8-a96a-8b438cac61af> .
<https://starwars.com#sector_VarHagen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_VarHagen> <http://telicent.io/ontology/primaryName> "Var Hagen" .
<https://starwars.com#planet_Vogel> <http://telicent.io/ontology/primaryName> "Vogel" .
<https://starwars.com#planet_Vogel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#planet_Vogel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

