Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tharin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Tharin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Oovo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#1acef8b0-8bff-4543-a66e-47aad650e9fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Oovo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1acef8b0-8bff-4543-a66e-47aad650e9fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Oovo> <http://www.w3.org/2000/01/rdf-schema#comment> "Oovo was a gas giant located in the Oovo system of the Outer Rim's Tharin sector. It was orbited by an asteroid belt which contained the asteroid Oovo IV, which housed the maximum security prison named Desolation Alley. " .
<https://starwars.com#planet_Oovo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1acef8b0-8bff-4543-a66e-47aad650e9fc> .
<https://starwars.com#planet_Oovo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tharin> .
<https://starwars.com#sector_Tharin> <http://telicent.io/ontology/primaryName> "Tharin" .
<https://starwars.com#planet_Oovo> <http://telicent.io/ontology/primaryName> "Oovo" .
<https://starwars.com#planet_Oovo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

