Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Boonta> <http://www.w3.org/2000/01/rdf-schema#comment> "Boonta was an astronomical object located in the galaxy's Outer Rim Territories, in grid square S-8 on the Standard Galactic Grid, that was connected to Bimmisaari, Junkfort Station, Klatooine, Sriluur, and Sy Myrth by a hyperspace route. " .
<https://starwars.com#02c4fe3b-6f13-4e82-84aa-3b6b62fb0dac> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Boonta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Boonta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Suolriep> .
<https://starwars.com#02c4fe3b-6f13-4e82-84aa-3b6b62fb0dac> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Suolriep> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Boonta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Boonta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#planet_Boonta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02c4fe3b-6f13-4e82-84aa-3b6b62fb0dac> .
<https://starwars.com#sector_Suolriep> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Boonta> <http://telicent.io/ontology/primaryName> "Boonta" .
<https://starwars.com#sector_Suolriep> <http://telicent.io/ontology/primaryName> "Suolriep" .

