Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yetoom> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e4cc1b1d-6924-4f60-a698-895c3d50ae2c> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Yetoom> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Yetoom> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Yetoom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#e4cc1b1d-6924-4f60-a698-895c3d50ae2c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yetoom"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Yetoom> <http://telicent.io/ontology/primaryName> "Yetoom" .
<https://starwars.com#planet_Yetoom> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#e4cc1b1d-6924-4f60-a698-895c3d50ae2c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

