Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Whelori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Whelori> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Whelori> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f16b6227-fb96-42b0-95e7-dfe139715e9f> .
<https://starwars.com#planet_Whelori> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f16b6227-fb96-42b0-95e7-dfe139715e9f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Whelori> <http://telicent.io/ontology/primaryName> "Whelori" .
<https://starwars.com#planet_Whelori> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#f16b6227-fb96-42b0-95e7-dfe139715e9f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Whelori"^^<http://www.w3.org/2001/XMLSchema#string> .

