Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cyphar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Spirva> .
<https://starwars.com#a13b0639-8f94-452c-95ed-880fa4a8e188> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cyphar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Spirva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Cyphar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Cyphar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a13b0639-8f94-452c-95ed-880fa4a8e188> .
<https://starwars.com#planet_Cyphar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a13b0639-8f94-452c-95ed-880fa4a8e188> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Spirva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Spirva> <http://telicent.io/ontology/primaryName> "Spirva" .
<https://starwars.com#planet_Cyphar> <http://telicent.io/ontology/primaryName> "Cyphar" .
<https://starwars.com#planet_Cyphar> <http://www.w3.org/2000/01/rdf-schema#comment> "Cyphar was a planet located in the galaxy's Mid Rim that was the homeworld of the Cyphari species. " .

