Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Krant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9c473986-97ba-4622-affe-9a7b52b15402> .
<https://starwars.com#planet_Krant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BothanSpace> .
<https://starwars.com#planet_Krant> <http://telicent.io/ontology/primaryName> "Krant" .
<https://starwars.com#9c473986-97ba-4622-affe-9a7b52b15402> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Krant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_BothanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Krant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_BothanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Krant> <http://www.w3.org/2000/01/rdf-schema#comment> "Krant was a wilderness planet in the Bothan sector. It saw action from the Clone Wars and the Galactic Civil War, and the Jedi Master Echuu Shen-Jon hid on Krant during decades until Princess Leia Organa appeared on the planet, searching for the Bothan agent Utric Sandov. " .
<https://starwars.com#planet_Krant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#9c473986-97ba-4622-affe-9a7b52b15402> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BothanSpace> <http://telicent.io/ontology/primaryName> "Bothan Space" .

