Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Fellwe> <http://telicent.io/ontology/primaryName> "Fellwe" .
<https://starwars.com#sector_Fellwe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Yinchorr> <http://www.w3.org/2000/01/rdf-schema#comment> "Yinchorr was an astronomical object located in the galaxy's Expansion Region, located in grid square L-8 on the Standard Galactic Grid. Following the Battle of Endor, the New Republic was involved in a battle on Yinchorr that devolved in to a siege situation. " .
<https://starwars.com#52da3b4a-453c-417c-a4ca-a3289d78da61> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#52da3b4a-453c-417c-a4ca-a3289d78da61> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yinchorr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yinchorr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Fellwe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Yinchorr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Fellwe> .
<https://starwars.com#planet_Yinchorr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#52da3b4a-453c-417c-a4ca-a3289d78da61> .
<https://starwars.com#planet_Yinchorr> <http://telicent.io/ontology/primaryName> "Yinchorr" .
<https://starwars.com#planet_Yinchorr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .

