Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Noris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#3d33f376-3925-4418-b4a8-817cc2eee342> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Noris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Noris> <http://telicent.io/ontology/primaryName> "Noris" .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Noris> <http://www.w3.org/2000/01/rdf-schema#comment> "Noris was an astromical object located in the Unknown Regions' Chiss Ascendancy. A ship leaving Rhigal was able to reach Noris by traveling on a similar vector to the one it would take to reach Ornfra, Sharb, or Schesa. " .
<https://starwars.com#planet_Noris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F8> .
<https://starwars.com#planet_Noris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#planet_Noris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d33f376-3925-4418-b4a8-817cc2eee342> .
<https://starwars.com#3d33f376-3925-4418-b4a8-817cc2eee342> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

