Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#5e55c32e-b113-47eb-a9cb-f16607fad370> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MonGazza> <http://www.w3.org/2000/01/rdf-schema#comment> "Mon Gazza was a planet located in the galaxy's Mid Rim along the Corellian Run. It hosted raw spice mining operations, which were controlled by the Pyke Syndicate during the Clone Wars. The pirate queen Maz Kanata marked it as a shadowport on a map she included in the book that became known as the Smuggler's Guide. A number of weeks after the Battle of Endor in 4 ABY, Soran Keize, an ex-member of the Galactic Empire's 204th Imperial Fighter Wing, traveled to Mon Gazza, where he was caught up in a war between spice traders. Keize chose to move on when the violence escalated. The 204th later attacked and destroyed a New Republic outpost on the object in retaliation to the capture of Andara. " .
<https://starwars.com#planet_MonGazza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#sector_Lambda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Lambda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MonGazza> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MonGazza> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5e55c32e-b113-47eb-a9cb-f16607fad370> .
<https://starwars.com#planet_MonGazza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lambda> .
<https://starwars.com#5e55c32e-b113-47eb-a9cb-f16607fad370> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mon Gazza"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MonGazza> <http://telicent.io/ontology/primaryName> "Mon Gazza" .
<https://starwars.com#sector_Lambda> <http://telicent.io/ontology/primaryName> "Lambda" .

