Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#da51f293-9d5a-4bd2-a5f2-1e782e055711> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fengrine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#da51f293-9d5a-4bd2-a5f2-1e782e055711> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fengrine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#planet_Fengrine> <http://telicent.io/ontology/primaryName> "Fengrine" .
<https://starwars.com#planet_Fengrine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#da51f293-9d5a-4bd2-a5f2-1e782e055711> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Fengrine> <http://www.w3.org/2000/01/rdf-schema#comment> "Fengrine was an agri-industrial world that had hydroponic shells, in which farmers led a relatively easy life. Around the year 22 BBY, it enjoyed a certain degree of prestige, at least compared to Tatooine. " .
<https://starwars.com#planet_Fengrine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Fengrine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

