Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mantessa> <http://telicent.io/ontology/primaryName> "Mantessa" .
<https://starwars.com#planet_Mantessa> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Yuuzhan Vong War, a force of Fire Breathers were driven off the planet by the Orange Panthacs. " .
<https://starwars.com#sector_Orus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#8e8db409-d4f8-460b-bde9-947b6e2260dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mantessa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mantessa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mantessa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8e8db409-d4f8-460b-bde9-947b6e2260dd> .
<https://starwars.com#8e8db409-d4f8-460b-bde9-947b6e2260dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Orus> <http://telicent.io/ontology/primaryName> "Orus" .
<https://starwars.com#sector_Orus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Mantessa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Orus> .
<https://starwars.com#planet_Mantessa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M8> .

