Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Quell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Nuiri> <http://telicent.io/ontology/primaryName> "Nuiri" .
<https://starwars.com#planet_Quell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#6cbc47f2-6af9-44e7-809e-af33e2025735> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Quell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6cbc47f2-6af9-44e7-809e-af33e2025735> .
<https://starwars.com#planet_Quell> <http://www.w3.org/2000/01/rdf-schema#comment> "Quell was a planet located in the Quell system of the Outer Rim Territories. In 21 BBY, the planet served as a site of a Clone Wars engagement, where the Galactic Republic task force of Jedi General Aayla Secura was attacked by a Confederacy of Independent Systems squadron of frigates commanded by the T-series tactical droid TF-1726. During the battle, the Republic forces were inflicted with heavy casualties as the Confederacy claimed victory. " .
<https://starwars.com#6cbc47f2-6af9-44e7-809e-af33e2025735> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Quell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nuiri> .
<https://starwars.com#sector_Nuiri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Quell> <http://telicent.io/ontology/primaryName> "Quell" .
<https://starwars.com#sector_Nuiri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

