Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ocsin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Ocsin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7dd935ae-50c5-4b54-b3fb-7f0494d8d701> .
<https://starwars.com#planet_Ocsin> <http://www.w3.org/2000/01/rdf-schema#comment> "The Ocsin, also known as the Ocsinin, were a Near-Human species from planet Farana, near the Corporate Sector. Due to this proximity, the Ocsin history was always related with this sector. " .
<https://starwars.com#planet_Ocsin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ocsin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#7dd935ae-50c5-4b54-b3fb-7f0494d8d701> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#7dd935ae-50c5-4b54-b3fb-7f0494d8d701> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ocsin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ocsin> <http://telicent.io/ontology/primaryName> "Ocsin" .

