Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#f6e6d318-ff20-44c9-ac45-fa42b1a2ba42> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Yn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K14> .
<https://starwars.com#f6e6d318-ff20-44c9-ac45-fa42b1a2ba42> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Yn> <http://telicent.io/ontology/primaryName> "Yn" .
<https://starwars.com#planet_Yn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f6e6d318-ff20-44c9-ac45-fa42b1a2ba42> .
<https://starwars.com#planet_Yn> <http://www.w3.org/2000/01/rdf-schema#comment> "Yn was a planet located within the Yn system of the Inner Rim. It was represented in the New Republic Senate by Wwebyls, a tiny humanoid. " .

