Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NarKreeta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_NarKreeta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#6421806d-6c53-4eae-9fec-7d564b3c94ef> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NarKreeta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_NarKreeta> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6421806d-6c53-4eae-9fec-7d564b3c94ef> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NarKreeta> <http://www.w3.org/2000/01/rdf-schema#comment> "Nar Kreeta was a Hutt colony and major trade world, located at the nexus of the Pabol Kreeta and Pabol Sleheyron. " .
<https://starwars.com#6421806d-6c53-4eae-9fec-7d564b3c94ef> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nar Kreeta"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NarKreeta> <http://telicent.io/ontology/primaryName> "Nar Kreeta" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

