Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KalkiNebula> <http://telicent.io/ontology/primaryName> "Kalki Nebula" .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#fdaba809-20d9-429f-a5eb-442c2198e57d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KalkiNebula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KalkiNebula> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fdaba809-20d9-429f-a5eb-442c2198e57d> .
<https://starwars.com#planet_KalkiNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#planet_KalkiNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_KalkiNebula> <http://www.w3.org/2000/01/rdf-schema#comment> "The Kalki Nebula was a nebula located in the Cassander sector, a part of the Trans-Hydian Borderlands region. Around 34 ABY, the Resistance gunner Paige Tico wrote in her journal that pirates had been building bases inside the nebula for centuries, allowing them to organize hit-and-run attacks on nearby star systems. " .
<https://starwars.com#fdaba809-20d9-429f-a5eb-442c2198e57d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalki Nebula"^^<http://www.w3.org/2001/XMLSchema#string> .

