Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zhanox> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Zhanox> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f783c574-3be4-4571-b4f2-48607f3b827a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zhanox"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zhanox> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Zhanox> <http://telicent.io/ontology/primaryName> "Zhanox" .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Zhanox> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f783c574-3be4-4571-b4f2-48607f3b827a> .
<https://starwars.com#f783c574-3be4-4571-b4f2-48607f3b827a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zhanox> <http://www.w3.org/2000/01/rdf-schema#comment> "Zhanox was a mining world located in the Anoat sector of the galaxy. Ugnaught miners were known to work there, although they feared the presence of spiny nexus. During the Iron Blockade, one Zhanox mining outpost requested specific off-world supplies to be delivered by a young smuggler. " .

