Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ArgaiMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "Argai Minor was a terrestrial planet. The Galactic Empire had forces within the Treinhaus Citadel on Argai Minor, and when the New Republic attacked the citadel, the Barma Battle Group sent Meteor Squadron, Hail Squadron, and Vanguard Squadron to support their ground forces. " .
<https://starwars.com#planet_ArgaiMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ae0ec6bc-6c60-4d70-bea3-464e6938a3d0> .
<https://starwars.com#ae0ec6bc-6c60-4d70-bea3-464e6938a3d0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Argai Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ArgaiMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#ae0ec6bc-6c60-4d70-bea3-464e6938a3d0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ArgaiMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ArgaiMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_ArgaiMinor> <http://telicent.io/ontology/primaryName> "Argai Minor" .

