Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Challon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Challon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Challon> <http://telicent.io/ontology/primaryName> "Challon" .
<https://starwars.com#planet_Challon> <http://www.w3.org/2000/01/rdf-schema#comment> "Challon was a planet in the Core Worlds that remained neutral during the Galactic Civil War. While on Challon, Leia Organa tried to convince local Governor Tchai to support the Rebel Alliance. Organa was forced to kill Giles Durane, her 'weapons master,' in self-defense. " .
<https://starwars.com#planet_Challon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1216285a-a5d9-401d-b449-4adb7554f47e> .
<https://starwars.com#1216285a-a5d9-401d-b449-4adb7554f47e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Challon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1216285a-a5d9-401d-b449-4adb7554f47e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Challon"^^<http://www.w3.org/2001/XMLSchema#string> .

