Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Media> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef004f99-53d8-4dc1-8aa0-37070afb90b7> .
<https://starwars.com#planet_Media> <http://telicent.io/ontology/primaryName> "Media" .
<https://starwars.com#planet_Media> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#ef004f99-53d8-4dc1-8aa0-37070afb90b7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Media> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Media> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Media> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#ef004f99-53d8-4dc1-8aa0-37070afb90b7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Media"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

