Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0e44b90a-642b-4151-9cfc-0df27580f908> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Silken> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Silken> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Silken> <http://telicent.io/ontology/primaryName> "Silken" .
<https://starwars.com#planet_Silken> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d6c07ec6-5ece-45d6-94d4-db4221f2f734> .
<https://starwars.com#grid_O20> <http://telicent.io/ontology/primaryName> "O20" .
<https://starwars.com#0e44b90a-642b-4151-9cfc-0df27580f908> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Silken> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Silken> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O20> .
<https://starwars.com#d6c07ec6-5ece-45d6-94d4-db4221f2f734> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Silken"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0e44b90a-642b-4151-9cfc-0df27580f908> .
<https://starwars.com#d6c07ec6-5ece-45d6-94d4-db4221f2f734> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

