Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fedje> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#ad8aee63-13fd-46ca-b653-4327ff4f1db4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fedje> <http://www.w3.org/2000/01/rdf-schema#comment> "Fedje was a planet in the Outer Rim's Atrivis sector. It was home to many exotic creatures, including the rare folded ear boosqueak. The planet was visited by members of the Alliance to Restore the Republic during the Galactic Civil War. Imperial Intelligence operatives later posed as natives of the planet while carrying out sabotage on the Bothan homeworld Bothawui. " .
<https://starwars.com#planet_Fedje> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fedje> <http://telicent.io/ontology/primaryName> "Fedje" .
<https://starwars.com#ad8aee63-13fd-46ca-b653-4327ff4f1db4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fedje"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Fedje> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ad8aee63-13fd-46ca-b653-4327ff4f1db4> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .
<https://starwars.com#planet_Fedje> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .

