Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_UR-3741> <http://telicent.io/ontology/primaryName> "UR-3741" .
<https://starwars.com#planet_UR-3741> <http://www.w3.org/2000/01/rdf-schema#comment> "UR-3741 was a celestial body situated in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. Its designation was similar to those of the nearby UR-1060, UR-2650, UR-8827, and UR-9353. UR-3741 was depicted on a Moddell sector map included with the collection of non-electronic Rebel Alliance documents known as The Rebel Files. " .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#556e8ab7-70f3-4fc9-8dd9-981ab84b2ce3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "UR-3741"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_UR-3741> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_UR-3741> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#556e8ab7-70f3-4fc9-8dd9-981ab84b2ce3> .
<https://starwars.com#556e8ab7-70f3-4fc9-8dd9-981ab84b2ce3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_UR-3741> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_UR-3741> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

