Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Presbalin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e0e6bf9a-2144-4fea-baa0-5a11bbfdb1e7> .
<https://starwars.com#planet_Presbalin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Presbalin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#e0e6bf9a-2144-4fea-baa0-5a11bbfdb1e7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Presbalin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_Presbalin> <http://telicent.io/ontology/primaryName> "Presbalin" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Presbalin> <http://www.w3.org/2000/01/rdf-schema#comment> "Presbalin was a planet in the southern Gordian Reach, across the Denarii Nebula from such worlds as Pinoora, Yavin Prime and Torque. It was located on the Junction-Tierell Loop and was part of the Loop Worlds. Presbalin became one of the Loop Worlds' primary commercial hubs after Humans settled onto the planet. It was discovered to be dotted with abandoned alien cities with strange architecture. " .
<https://starwars.com#e0e6bf9a-2144-4fea-baa0-5a11bbfdb1e7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Presbalin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

