Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Imynusoph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kallea> .
<https://starwars.com#sector_Kallea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_J21> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_J21> <http://telicent.io/ontology/primaryName> "J21" .
<https://starwars.com#4d62e686-5405-4232-aa8b-73cd55a964a5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Kallea> <http://telicent.io/ontology/primaryName> "Kallea" .
<https://starwars.com#planet_Imynusoph> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J21> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4d62e686-5405-4232-aa8b-73cd55a964a5> .
<https://starwars.com#grid_J21> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Imynusoph> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#374ceaf1-3214-461a-a783-5841ba15f057> .
<https://starwars.com#planet_Imynusoph> <http://www.w3.org/2000/01/rdf-schema#comment> "Imynusoph was an Outer Rim Territories astronomical object located in grid square J-21 of the Standard Galactic Grid. It was situated at the endpoint of the super-hyperroute known as the Hydian Way, which connected it to the celestial body Terminus. " .
<https://starwars.com#sector_Kallea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4d62e686-5405-4232-aa8b-73cd55a964a5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J21"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Imynusoph> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J21> .
<https://starwars.com#374ceaf1-3214-461a-a783-5841ba15f057> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Imynusoph> <http://telicent.io/ontology/primaryName> "Imynusoph" .
<https://starwars.com#374ceaf1-3214-461a-a783-5841ba15f057> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Imynusoph"^^<http://www.w3.org/2001/XMLSchema#string> .

