Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Noehaon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dde4b94a-897f-4b6c-9743-bbca99d36251> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dde4b94a-897f-4b6c-9743-bbca99d36251> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Noe'ha'on"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_PirynSHar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Noehaon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K16> .
<https://starwars.com#planet_Noehaon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dde4b94a-897f-4b6c-9743-bbca99d36251> .
<https://starwars.com#sector_PirynSHar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Noehaon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_PirynSHar> .
<https://starwars.com#planet_Noehaon> <http://telicent.io/ontology/primaryName> "Noe'ha'on" .
<https://starwars.com#planet_Noehaon> <http://www.w3.org/2000/01/rdf-schema#comment> "Noe'ha'on was a jungle world located in the Expansion Region. It was situated in grid square K-16 of the Standard Galactic Grid and also lay on the hyperspace route known as the Great Gran Run, between Kinyen and the Mid Rim's Takodana system. " .
<https://starwars.com#sector_PirynSHar> <http://telicent.io/ontology/primaryName> "Piryn SHar" .

