Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Togoria> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Togoria> <http://telicent.io/ontology/primaryName> "Togoria" .
<https://starwars.com#planet_Togoria> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f74df457-1773-4a4f-bf33-4d76cf3b10e7> .
<https://starwars.com#sector_Taldot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Togoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Taldot> .
<https://starwars.com#planet_Togoria> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#planet_Togoria> <http://www.w3.org/2000/01/rdf-schema#comment> "Togoria was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#sector_Taldot> <http://telicent.io/ontology/primaryName> "Taldot" .
<https://starwars.com#f74df457-1773-4a4f-bf33-4d76cf3b10e7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f74df457-1773-4a4f-bf33-4d76cf3b10e7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Togoria"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Taldot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

