Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#grid_E8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_E8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#c23484be-bbab-4158-9415-71b73e78057c> .
<https://starwars.com#planet_Avidich> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#planet_Avidich> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#grid_E8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Avidich> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#80a21931-aaab-41ad-b9b0-ddfb07019432> .
<https://starwars.com#c23484be-bbab-4158-9415-71b73e78057c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Avidich> <http://telicent.io/ontology/primaryName> "Avidich" .
<https://starwars.com#80a21931-aaab-41ad-b9b0-ddfb07019432> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Avidich> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .
<https://starwars.com#grid_E8> <http://telicent.io/ontology/primaryName> "E8" .
<https://starwars.com#c23484be-bbab-4158-9415-71b73e78057c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "E8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Avidich> <http://www.w3.org/2000/01/rdf-schema#comment> "Avidich was a planet of the Chiss Ascendancy, located in the Unknown Regions. After a majority of the population of the Chiss capital of Csilla were forced offworld by changes in the planet's climate, Avidich was one of the planets they were sent to. " .
<https://starwars.com#80a21931-aaab-41ad-b9b0-ddfb07019432> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Avidich"^^<http://www.w3.org/2001/XMLSchema#string> .

