Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Nara> <http://telicent.io/ontology/primaryName> "Nara" .
<https://starwars.com#e742248b-c9a6-4e2e-8824-ba3f51379bb9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Nara> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#e742248b-c9a6-4e2e-8824-ba3f51379bb9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Nara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Nara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e742248b-c9a6-4e2e-8824-ba3f51379bb9> .

