Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Fest> <http://telicent.io/ontology/primaryName> "Fest" .
<https://starwars.com#ab3cdf21-04ef-4455-9324-114b57f17717> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Fest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_Fest> <http://www.w3.org/2000/01/rdf-schema#comment> "Fest was a planet located within the Atrivis sector of the galaxy's Outer Rim Territories that was the home to a human population. " .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Fest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Fest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .
<https://starwars.com#planet_Fest> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ab3cdf21-04ef-4455-9324-114b57f17717> .
<https://starwars.com#ab3cdf21-04ef-4455-9324-114b57f17717> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Fest"^^<http://www.w3.org/2001/XMLSchema#string> .

