Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hensara> <http://www.w3.org/2000/01/rdf-schema#comment> "Hensara was the sun that was orbited by the planet of Hensara III. " .
<https://starwars.com#planet_Hensara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Hensara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Hensara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#07aacee3-a2dc-4c45-9de6-b2e1f9f00984> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hensara> <http://telicent.io/ontology/primaryName> "Hensara" .
<https://starwars.com#planet_Hensara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#07aacee3-a2dc-4c45-9de6-b2e1f9f00984> .
<https://starwars.com#07aacee3-a2dc-4c45-9de6-b2e1f9f00984> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hensara"^^<http://www.w3.org/2001/XMLSchema#string> .

