Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#278d9f20-92f8-405a-b7c3-0ce02001c4f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Garel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Garel> <http://telicent.io/ontology/primaryName> "Garel" .
<https://starwars.com#278d9f20-92f8-405a-b7c3-0ce02001c4f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Garel> <http://www.w3.org/2000/01/rdf-schema#comment> "Garel was a planet located in the Garel system of the Outer Rim Territories' Lothal sector that was controlled by the Galactic Empire. It was the homeworld of Imperial Supply Master Yogar Lyste. Garel was several minutes away from the planet Lothal via hyperspace travel. Several years before the Battle of Yavin, the rebel cell Phoenix Cell established a temporary hiding place on Garel. The rebels were forced to move after the Empire discovered their presence and assembled a fleet to attack them. Many years later, individuals such as Ushos O. Statura fought to liberate Garel from the yoke of the Galactic Empire. " .
<https://starwars.com#planet_Garel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dominus> .
<https://starwars.com#planet_Garel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Garel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U7> .
<https://starwars.com#sector_Dominus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Dominus> <http://telicent.io/ontology/primaryName> "Dominus" .
<https://starwars.com#planet_Garel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#278d9f20-92f8-405a-b7c3-0ce02001c4f9> .
<https://starwars.com#sector_Dominus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

