Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zamael> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#7037c749-67e6-4776-bf26-c80ffc093506> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zamael"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zamael> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K12> .
<https://starwars.com#planet_Zamael> <http://telicent.io/ontology/primaryName> "Zamael" .
<https://starwars.com#planet_Zamael> <http://www.w3.org/2000/01/rdf-schema#comment> "Zamael was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Zamael> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7037c749-67e6-4776-bf26-c80ffc093506> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zamael> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7037c749-67e6-4776-bf26-c80ffc093506> .

