Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mexeluine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#d99596e8-98e2-4044-852e-f920b478cc18> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mexeluine"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d99596e8-98e2-4044-852e-f920b478cc18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Mexeluine> <http://www.w3.org/2000/01/rdf-schema#comment> "Mexeluine was a planet located in the Anoat sector of the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Mexeluine> <http://telicent.io/ontology/primaryName> "Mexeluine" .
<https://starwars.com#planet_Mexeluine> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Mexeluine> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mexeluine> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d99596e8-98e2-4044-852e-f920b478cc18> .

