Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rettna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q11> .
<https://starwars.com#sector_Essaga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Rettna> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Rettna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Essaga> .
<https://starwars.com#sector_Essaga> <http://telicent.io/ontology/primaryName> "Essaga" .
<https://starwars.com#planet_Rettna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rettna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#eafcd62b-9b23-44ae-99cc-2353d594cfca> .
<https://starwars.com#planet_Rettna> <http://telicent.io/ontology/primaryName> "Rettna" .
<https://starwars.com#eafcd62b-9b23-44ae-99cc-2353d594cfca> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rettna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#eafcd62b-9b23-44ae-99cc-2353d594cfca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Essaga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

