Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Murkhana> <http://telicent.io/ontology/primaryName> "Murkhana" .
<https://starwars.com#planet_Murkhana> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#9499bb4b-3a06-424e-b739-d35b3667d234> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Murkhana"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Auril> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Auril> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Murkhana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Auril> .
<https://starwars.com#9499bb4b-3a06-424e-b739-d35b3667d234> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Murkhana> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9499bb4b-3a06-424e-b739-d35b3667d234> .
<https://starwars.com#sector_Auril> <http://telicent.io/ontology/primaryName> "Auril" .
<https://starwars.com#planet_Murkhana> <http://www.w3.org/2000/01/rdf-schema#comment> "Murkhana was a planet in the Outer Rim Territories. Known for its natural beauty, it was a major tourist attraction in the last years of the Republic Era. During the Clone Wars, the world was the headquaters of the Corporate Alliance and became a major Separatist bastion; consequently, much of its environment was destroyed by a Republic orbital bombardment. By the Imperial Era, Murkhana was an impoverished, polluted world crippled by Imperial sanctions and a ruined environment. The planet was also a crime haven that was dominated by smugglers and crime lords such as the Sugi Faazah. In 14 BBY, the insurgent leader Berch Teller stole Moff Wilhuff Tarkin's corvette Carrion Spike whilst the latter, along with Darth Vader, were investigating a communications cache in Murkhana City. " .
<https://starwars.com#planet_Murkhana> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S6> .

