Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kanz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Jerne> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jerne> <http://www.w3.org/2000/01/rdf-schema#comment> "After crashing and being captured by the Empire, the Rebels were then captured again, this time by a new group: a local band of guerrillas, who were led by a pirate named Meeka Reen. The guerrillas were very interested in Skywalker and Organa's presence and convinced them to explain why they had come to Jerne, resulting in Reen pretending to make a deal with the Rebels so that she could acquire the crystal for herself. The guerrillas and Rebels made their way to the Eternity Crystal's supposed location, Adony Station, where—following a short skirmish with Imperial stormtroopers—Reen betrayed the Rebels, entered the ruins that Organa recognized from the datatapes, and was subsequently blown up by Vader's planted explosives. Skywalker and Organa survived the ordeal, escaping the Jerne system on an Imperial scout ship. " .
<https://starwars.com#sector_Kanz> <http://telicent.io/ontology/primaryName> "Kanz" .
<https://starwars.com#planet_Jerne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kanz> .
<https://starwars.com#planet_Jerne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N4> .
<https://starwars.com#d0b79abd-0bc9-4ce0-846b-ba02794f038f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jerne"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jerne> <http://telicent.io/ontology/primaryName> "Jerne" .
<https://starwars.com#d0b79abd-0bc9-4ce0-846b-ba02794f038f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kanz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Jerne> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d0b79abd-0bc9-4ce0-846b-ba02794f038f> .

