Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdCanfre> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#planet_OrdCanfre> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Canfre was a location in the galaxy. It was home to the Ord Canfre Institute for Ethics in Art Criticism, which Cepa Bonshu, creator of the anti-Imperial propaganda poster What Will You Do, taught at after retiring from a lengthy communication arts career. " .
<https://starwars.com#ac050fef-23a7-487a-a9c5-cf01d70e48c5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Canfre"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OrdCanfre> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ac050fef-23a7-487a-a9c5-cf01d70e48c5> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_OrdCanfre> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#ac050fef-23a7-487a-a9c5-cf01d70e48c5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdCanfre> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdCanfre> <http://telicent.io/ontology/primaryName> "Ord Canfre" .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

