Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dorvalla> <http://telicent.io/ontology/primaryName> "Dorvalla" .
<https://starwars.com#sector_Videnda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Dorvalla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ea96fec7-c5e1-4e70-8d44-3f40915289a7> .
<https://starwars.com#planet_Dorvalla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M18> .
<https://starwars.com#sector_Videnda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Videnda> <http://telicent.io/ontology/primaryName> "Videnda" .
<https://starwars.com#ea96fec7-c5e1-4e70-8d44-3f40915289a7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#ea96fec7-c5e1-4e70-8d44-3f40915289a7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dorvalla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dorvalla> <http://www.w3.org/2000/01/rdf-schema#comment> "Dorvalla was a celestial body where the Rebel Alliance's 61st Mobile Infantry recruited a number of new soldiers at some point by the year 0 BBY. The company's Captain Micha Evon soon noticed that the soldier Brand, who was secretly a bounty hunter, lingered around those new recruits. Evon cited this when Brand attempted to take a bounty on the captain during a battle on the planet Allst Prime. He mentioned his point about the recruits from Dorvalla while trying to convince Brand to stay with the 61st. " .
<https://starwars.com#planet_Dorvalla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dorvalla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Videnda> .

