Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Surcaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TransVulta> .
<https://starwars.com#sector_TransVulta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TransVulta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_TransVulta> <http://telicent.io/ontology/primaryName> "Trans'Vulta" .
<https://starwars.com#planet_Surcaris> <http://www.w3.org/2000/01/rdf-schema#comment> "Surcaris was a planet in the Mid Rim's Trans-Vulta sector where a group of Mandalorian mercenaries, possibly under Munin Skirata, fought. It was also the located where Munin found a young Kal Skirata. " .
<https://starwars.com#305bb757-2a08-4760-8c46-80aad4276e5d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Surcaris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#305bb757-2a08-4760-8c46-80aad4276e5d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Surcaris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#305bb757-2a08-4760-8c46-80aad4276e5d> .
<https://starwars.com#planet_Surcaris> <http://telicent.io/ontology/primaryName> "Surcaris" .
<https://starwars.com#planet_Surcaris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O7> .
<https://starwars.com#planet_Surcaris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

