Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#97367970-0470-4e42-b151-5b84e2df9580> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pijal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pijal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#97367970-0470-4e42-b151-5b84e2df9580> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Pijal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#97367970-0470-4e42-b151-5b84e2df9580> .
<https://starwars.com#planet_Pijal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Pijal> <http://telicent.io/ontology/primaryName> "Pijal" .
<https://starwars.com#planet_Pijal> <http://www.w3.org/2000/01/rdf-schema#comment> "Pijal was a planet located in the Pijal system of the Inner Rim. Some time prior to the year 40 BBY, the planet's throne was inherited by the six year old Crown Princess Fanry. The Jedi Rael Averross was then sent to the planet to serve as its lord regent until the time when Fanry would be old enough to lead her people." .

