Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8473e13f-50c3-4953-b3a0-247f73856d5f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_M14> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_M14> <http://telicent.io/ontology/primaryName> "M14" .
<https://starwars.com#planet_Arkam> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Arkam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Arkam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#acf2faa0-4639-4b2e-80d9-474cfbd4a74e> .
<https://starwars.com#8473e13f-50c3-4953-b3a0-247f73856d5f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "M14"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arkam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#acf2faa0-4639-4b2e-80d9-474cfbd4a74e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arkam"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arkam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Arkam> <http://telicent.io/ontology/primaryName> "Arkam" .
<https://starwars.com#grid_M14> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_M14> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#8473e13f-50c3-4953-b3a0-247f73856d5f> .
<https://starwars.com#acf2faa0-4639-4b2e-80d9-474cfbd4a74e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

