Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_R11> <http://telicent.io/ontology/primaryName> "R11" .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Kleeva> <http://telicent.io/ontology/primaryName> "Kleeva" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kleeva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_R11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#b6ad73e2-ba6c-494d-a16b-c4f96eb8fc99> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#78bf0f73-fa96-4323-b733-d4feeeb087b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Kleeva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#grid_R11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#78bf0f73-fa96-4323-b733-d4feeeb087b8> .
<https://starwars.com#planet_Kleeva> <http://www.w3.org/2000/01/rdf-schema#comment> "Kleeva was a gas giant world that was orbited by Boonda's Moon. It was located in Hutt Space in the Mid Rim of the galaxy. " .
<https://starwars.com#b6ad73e2-ba6c-494d-a16b-c4f96eb8fc99> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kleeva"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kleeva> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b6ad73e2-ba6c-494d-a16b-c4f96eb8fc99> .
<https://starwars.com#planet_Kleeva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R11> .
<https://starwars.com#78bf0f73-fa96-4323-b733-d4feeeb087b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_R11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

