Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#80de8e9d-09b9-4351-bc60-5442df414edc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Couronne> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_QuasKillam> <http://telicent.io/ontology/primaryName> "Quas Killam" .
<https://starwars.com#sector_Couronne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_QuasKillam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_QuasKillam> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#80de8e9d-09b9-4351-bc60-5442df414edc> .
<https://starwars.com#planet_QuasKillam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Couronne> .
<https://starwars.com#planet_QuasKillam> <http://www.w3.org/2000/01/rdf-schema#comment> "Quas Killam was a planet on the edge of the Mid Rim. Its people were the Killam. Quas Killam was a world of weapons manufacturing factories and trinium mines, and so was conquered by the Trade Federation early in the Clone Wars. Throughout the war the planet changed sides several times. " .
<https://starwars.com#planet_QuasKillam> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#80de8e9d-09b9-4351-bc60-5442df414edc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quas Killam"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Couronne> <http://telicent.io/ontology/primaryName> "Couronne" .

