Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Froswythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Froswythe> <http://telicent.io/ontology/primaryName> "Froswythe" .
<https://starwars.com#planet_Froswythe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Froswythe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Froswythe> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#17349b98-88f2-4c45-a715-1a9e514e953e> .
<https://starwars.com#17349b98-88f2-4c45-a715-1a9e514e953e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Froswythe> <http://www.w3.org/2000/01/rdf-schema#comment> "Froswythe was a planet in the Colonies. It was a major source of meat and animal-based textiles for the Colonies and Core Worlds. Roaming herds of livestock included banthas and nerfs. Ycaqt were used for transportation. " .
<https://starwars.com#17349b98-88f2-4c45-a715-1a9e514e953e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Froswythe"^^<http://www.w3.org/2001/XMLSchema#string> .

