Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Clacis> <http://telicent.io/ontology/primaryName> "Clacis" .
<https://starwars.com#planet_Cezith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#sector_Clacis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cezith> <http://telicent.io/ontology/primaryName> "Cezith" .
<https://starwars.com#planet_Cezith> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1573fed1-66c2-47f1-a8e6-167991d017dd> .
<https://starwars.com#1573fed1-66c2-47f1-a8e6-167991d017dd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#1573fed1-66c2-47f1-a8e6-167991d017dd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cezith"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Clacis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cezith> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Cezith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cezith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Clacis> .

