Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Askaj> <http://www.w3.org/2000/01/rdf-schema#comment> "Askaj was the home planet of the Askajians in the Outer Rim Territories, far off the Rimma Trade Route. The planet had one moon, the Moon Lady, whom the people worshiped as a deity. " .
<https://starwars.com#d145be46-2710-481d-abe2-6fe8af957ea4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Askaj"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d145be46-2710-481d-abe2-6fe8af957ea4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#planet_Askaj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Subterrel> .
<https://starwars.com#sector_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Askaj> <http://telicent.io/ontology/primaryName> "Askaj" .
<https://starwars.com#planet_Askaj> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Askaj> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d145be46-2710-481d-abe2-6fe8af957ea4> .
<https://starwars.com#planet_Askaj> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M20> .
<https://starwars.com#sector_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

