Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kelrodo-Ai> <http://telicent.io/ontology/primaryName> "Kelrodo-Ai" .
<https://starwars.com#planet_Kelrodo-Ai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Steniplis> <http://telicent.io/ontology/primaryName> "Steniplis" .
<https://starwars.com#55fbf66b-8765-4cfd-b656-27ea153c619d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kelrodo-Ai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Steniplis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kelrodo-Ai> <http://www.w3.org/2000/01/rdf-schema#comment> "Kelrodo-Ai was a planet with famous gelatin mines and known for its water-sculptures. In 12 ABY, its Baron Administrator was Drom Guldi. " .
<https://starwars.com#planet_Kelrodo-Ai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#55fbf66b-8765-4cfd-b656-27ea153c619d> .
<https://starwars.com#sector_Steniplis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kelrodo-Ai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#55fbf66b-8765-4cfd-b656-27ea153c619d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kelrodo-Ai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Steniplis> .

