Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hutlar> <http://www.w3.org/2000/01/rdf-schema#comment> "Hutlar was a small, chilly world located in the Mid Rim's Senex sector. Orbiting a red dwarf star, it was the homeworld of the sentient Hutlarians. They served the aristocratic Ancient Houses of the Senex-Juvex region in various roles until 553 BBY, when their home was liberated from the nobles' control. " .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#313b7080-e1f2-4b9f-ae91-c04286d8cfc4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hutlar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#313b7080-e1f2-4b9f-ae91-c04286d8cfc4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hutlar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hutlar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#313b7080-e1f2-4b9f-ae91-c04286d8cfc4> .
<https://starwars.com#planet_Hutlar> <http://telicent.io/ontology/primaryName> "Hutlar" .
<https://starwars.com#planet_Hutlar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Hutlar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .

