Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Woostri> <http://telicent.io/ontology/primaryName> "Woostri" .
<https://starwars.com#planet_Woostri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Woostri> .
<https://starwars.com#planet_Woostri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Woostri> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e60f5ac-b3cd-4412-94fd-76854fe8f411> .
<https://starwars.com#2e60f5ac-b3cd-4412-94fd-76854fe8f411> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Woostri> <http://www.w3.org/2000/01/rdf-schema#comment> "Woostri was an astronomical object in the galaxy's Expansion Region, situated along the Rimma Trade Route. " .
<https://starwars.com#planet_Woostri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M16> .
<https://starwars.com#planet_Woostri> <http://telicent.io/ontology/primaryName> "Woostri" .
<https://starwars.com#sector_Woostri> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Woostri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#2e60f5ac-b3cd-4412-94fd-76854fe8f411> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Woostri"^^<http://www.w3.org/2001/XMLSchema#string> .

