Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Videnda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Dolla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Videnda> .
<https://starwars.com#planet_Dolla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Videnda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Videnda> <http://telicent.io/ontology/primaryName> "Videnda" .
<https://starwars.com#planet_Dolla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#2e7519cb-f907-48d2-9da3-e293c8fa2fa9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dolla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dolla> <http://www.w3.org/2000/01/rdf-schema#comment> "Dolla was an astronomical object located in the regions known as the Outer Rim Territories and the Western Reaches. It was situated in grid square L-18 of the Standard Galactic Grid. Dolla was connected via hyperspace routes to the celestial body Karfeddion in the Mid Rim Territories as well as the Outer Rim's Eriadu system and the astronomical object Bavva. " .
<https://starwars.com#planet_Dolla> <http://telicent.io/ontology/primaryName> "Dolla" .
<https://starwars.com#planet_Dolla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e7519cb-f907-48d2-9da3-e293c8fa2fa9> .
<https://starwars.com#2e7519cb-f907-48d2-9da3-e293c8fa2fa9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

