Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#540375b1-6d8b-4b81-a305-c2bea9e948c8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orondia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Orondia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#540375b1-6d8b-4b81-a305-c2bea9e948c8> .
<https://starwars.com#planet_Orondia> <http://www.w3.org/2000/01/rdf-schema#comment> "Orondia was a desolate planet in the galaxy. During the Clone Wars, Obi-Wan Kenobi, disguised as Rako Hardeen, Cad Bane, and Moralo Eval were scammed into stopping there when a Bith gave him only enough fuel to reach Orondia, where his brother ran a fueling station. " .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Orondia> <http://telicent.io/ontology/primaryName> "Orondia" .
<https://starwars.com#planet_Orondia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Orondia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Orondia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#540375b1-6d8b-4b81-a305-c2bea9e948c8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

