Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a272025d-0055-4e8e-be73-13ca33212331> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Majoor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Majoor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a272025d-0055-4e8e-be73-13ca33212331> .
<https://starwars.com#planet_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Majoor> .
<https://starwars.com#a272025d-0055-4e8e-be73-13ca33212331> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Majoor> <http://www.w3.org/2000/01/rdf-schema#comment> "Majoor was the homeworld of a native sentient species. It was located in the Expansion Region. " .
<https://starwars.com#planet_Majoor> <http://telicent.io/ontology/primaryName> "Majoor" .
<https://starwars.com#planet_Majoor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#sector_Majoor> <http://telicent.io/ontology/primaryName> "Majoor" .
<https://starwars.com#sector_Majoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Majoor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

