Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_T15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#5fb2849a-43dd-4cec-8ec3-997055d4f580> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#5fb2849a-43dd-4cec-8ec3-997055d4f580> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#d7017cc0-1799-43da-ba4b-b2cc6c2e1f94> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pzob"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Pzob> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T15> .
<https://starwars.com#grid_T15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5fb2849a-43dd-4cec-8ec3-997055d4f580> .
<https://starwars.com#planet_Pzob> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Pzob> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Herios> .
<https://starwars.com#sector_Herios> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Pzob> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7017cc0-1799-43da-ba4b-b2cc6c2e1f94> .
<https://starwars.com#sector_Herios> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pzob> <http://www.w3.org/2000/01/rdf-schema#comment> "Pzob was an astronomical object located in the regions known as the Outer Rim Territories and the Slice. It was situated in grid square T-15 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Pzob> <http://telicent.io/ontology/primaryName> "Pzob" .
<https://starwars.com#grid_T15> <http://telicent.io/ontology/primaryName> "T15" .
<https://starwars.com#sector_Herios> <http://telicent.io/ontology/primaryName> "Herios" .
<https://starwars.com#d7017cc0-1799-43da-ba4b-b2cc6c2e1f94> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

