Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ryloon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ryloon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#17bd8bb8-de08-49f7-8b11-81823116960f> .
<https://starwars.com#planet_Ryloon> <http://telicent.io/ontology/primaryName> "Ryloon" .
<https://starwars.com#planet_Ryloon> <http://www.w3.org/2000/01/rdf-schema#comment> "Ryloon was Outer Rim Territories planet in Velcar sector, Ryloon systemand the site of several Imperial controlled orbital factories where captured prisoners were sent to work. The world remained part of the Imperial Remnant following its peace agreement with the New Republic. " .
<https://starwars.com#planet_Ryloon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Velcar> .
<https://starwars.com#17bd8bb8-de08-49f7-8b11-81823116960f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ryloon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Velcar> <http://telicent.io/ontology/primaryName> "Velcar" .
<https://starwars.com#17bd8bb8-de08-49f7-8b11-81823116960f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ryloon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#sector_Velcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Velcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

