Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PegShar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R8> .
<https://starwars.com#sector_Halla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#a7f242d0-b20d-4f82-8baa-011f7290f09b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PegShar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halla> .
<https://starwars.com#planet_PegShar> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Halla> <http://telicent.io/ontology/primaryName> "Halla" .
<https://starwars.com#sector_Halla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_PegShar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a7f242d0-b20d-4f82-8baa-011f7290f09b> .
<https://starwars.com#a7f242d0-b20d-4f82-8baa-011f7290f09b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Peg Shar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PegShar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PegShar> <http://telicent.io/ontology/primaryName> "Peg Shar" .

