Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Lahsbane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lahsbane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R15> .
<https://starwars.com#f93ea4f9-b945-4ef6-a971-deb6b13f76aa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Onatos> <http://telicent.io/ontology/primaryName> "Onatos" .
<https://starwars.com#planet_Lahsbane> <http://telicent.io/ontology/primaryName> "Lahsbane" .
<https://starwars.com#planet_Lahsbane> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f93ea4f9-b945-4ef6-a971-deb6b13f76aa> .
<https://starwars.com#sector_Onatos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Onatos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lahsbane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Onatos> .
<https://starwars.com#f93ea4f9-b945-4ef6-a971-deb6b13f76aa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lahsbane"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lahsbane> <http://www.w3.org/2000/01/rdf-schema#comment> "Lahsbane was an astronomical object located in the regions known as the Mid Rim Territories and the Slice, and was situated in grid square R-15 on the Standard Galactic Grid. During his time as a Padawan of the Jedi Order, Dooku and his Jedi Master, Yoda, traveled to Lahsbane, which the Serennian later documented in his personal journal. " .

