Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ragna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#planet_Ragna> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Daimar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Ragna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ragna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Daimar> .
<https://starwars.com#planet_Ragna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#117bdb89-3466-4874-93a5-b4e6fc45cff5> .
<https://starwars.com#sector_Daimar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Daimar> <http://telicent.io/ontology/primaryName> "Daimar" .
<https://starwars.com#117bdb89-3466-4874-93a5-b4e6fc45cff5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ragna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#117bdb89-3466-4874-93a5-b4e6fc45cff5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ragna> <http://telicent.io/ontology/primaryName> "Ragna" .

