Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vorzyd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vorzyd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Vorzyd> .
<https://starwars.com#sector_Vorzyd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Vorzyd> <http://telicent.io/ontology/primaryName> "Vorzyd" .
<https://starwars.com#30f3561c-eed0-4eaa-94dc-62fc33584b91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vorzyd> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30f3561c-eed0-4eaa-94dc-62fc33584b91> .
<https://starwars.com#planet_Vorzyd> <http://telicent.io/ontology/primaryName> "Vorzyd" .
<https://starwars.com#planet_Vorzyd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#planet_Vorzyd> <http://www.w3.org/2000/01/rdf-schema#comment> "Vorzyd was the primary of the Vorzyd system. It was orbited by five planets. " .
<https://starwars.com#sector_Vorzyd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#30f3561c-eed0-4eaa-94dc-62fc33584b91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vorzyd"^^<http://www.w3.org/2001/XMLSchema#string> .

