Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Nelvaan> <http://www.w3.org/2000/01/rdf-schema#comment> "Nelvaan was a frigid Outer Rim planet located in the Savareen sector. It was home to the peaceful, sentient Nelvaanian species. During the Clone Wars, the planet's exploitation rights were ceded to the Confederacy of Independent Systems by Onaconda Farr, the Galactic Republic senator of Rodia. The Confederacy-aligned Techno Union used the natives to perform experiments, turning them into cyborg monsters. " .
<https://starwars.com#planet_Nelvaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Savareen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#8cc17cb7-f180-4fee-bb0b-188c9acfcc1f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#8cc17cb7-f180-4fee-bb0b-188c9acfcc1f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nelvaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Nelvaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q16> .
<https://starwars.com#sector_Savareen> <http://telicent.io/ontology/primaryName> "Savareen" .
<https://starwars.com#planet_Nelvaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8cc17cb7-f180-4fee-bb0b-188c9acfcc1f> .
<https://starwars.com#sector_Savareen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Nelvaan> <http://telicent.io/ontology/primaryName> "Nelvaan" .
<https://starwars.com#planet_Nelvaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Savareen> .

