Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aradia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .
<https://starwars.com#planet_Aradia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bcaa3eff-4fbe-434f-95e9-337877cd3a15> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aradia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aradia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bcaa3eff-4fbe-434f-95e9-337877cd3a15> .
<https://starwars.com#planet_Aradia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Aradia> <http://telicent.io/ontology/primaryName> "Aradia" .
<https://starwars.com#planet_Aradia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#bcaa3eff-4fbe-434f-95e9-337877cd3a15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

