Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bortele> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kalkovak> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalkovak was a remote planet populated by various species including a large sector populated by Quarren. It was a port world for travelers going to the Outer Rim Territories. Illyan Webble was left on the planet after he irritated the crew he was traveling with. Han Solo and Lando Calrissian once frequented the world in search of Webble and his information on the whereabouts of the Yavin Vassilika. " .
<https://starwars.com#7a6b77ca-ecf4-4162-8202-9995291579a7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalkovak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7a6b77ca-ecf4-4162-8202-9995291579a7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kalkovak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bortele> .
<https://starwars.com#planet_Kalkovak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7a6b77ca-ecf4-4162-8202-9995291579a7> .
<https://starwars.com#planet_Kalkovak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalkovak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#sector_Bortele> <http://telicent.io/ontology/primaryName> "Bortele" .
<https://starwars.com#planet_Kalkovak> <http://telicent.io/ontology/primaryName> "Kalkovak" .
<https://starwars.com#sector_Bortele> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

