Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kamar> <http://telicent.io/ontology/primaryName> "Kamar" .
<https://starwars.com#planet_Kamar> <http://www.w3.org/2000/01/rdf-schema#comment> "Kamar was an astronomical object that was home to a sentient insectoid species. " .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kamar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Kamar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#planet_Kamar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d50fc2c1-ef8b-4d82-800e-67bcf54ecf29> .
<https://starwars.com#planet_Kamar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d50fc2c1-ef8b-4d82-800e-67bcf54ecf29> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kamar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d50fc2c1-ef8b-4d82-800e-67bcf54ecf29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

