Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aris> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e8b66e40-2bac-496d-b562-34655c845df0> .
<https://starwars.com#planet_Aris> <http://www.w3.org/2000/01/rdf-schema#comment> "Aris was a rustic terrestrial planet. During the High Republic Era, Aris was one of the locations where the Unified Republic Task Force dealt with Nihil marauders in the aftermath of the attack on Valo. It was the homeworld of the human Resistance member Byrco Hansid. " .
<https://starwars.com#planet_Aris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Aris> <http://telicent.io/ontology/primaryName> "Aris" .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#e8b66e40-2bac-496d-b562-34655c845df0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aris"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#e8b66e40-2bac-496d-b562-34655c845df0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aris> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .

