Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#region_Core> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_K9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#region_Core> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_Aaeton> <http://telicent.io/ontology/primaryName> "Aaeton" .
<https://starwars.com#f5951b29-e8f2-4fba-930f-b76acdac4b0f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "K9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_K9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#f5951b29-e8f2-4fba-930f-b76acdac4b0f> .
<https://starwars.com#planet_Aaeton> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#region_Core> <http://telicent.io/ontology/primaryName> "Core" .
<https://starwars.com#grid_K9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Aaeton> <http://www.w3.org/2000/01/rdf-schema#comment> "Aaeton was a planet of the Aaeton system, in the Core Worlds region. During the Cold War between the Galactic Republic and the reconstituted Sith Empire, an Imperial bioweapon activated on the planet. During the last days of the Republic, the government of Aaeton had authorization to allow its citizens to visit the generally off-limits neighboring world of Ragoon VI. " .
<https://starwars.com#f5951b29-e8f2-4fba-930f-b76acdac4b0f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aaeton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Aaeton> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#b41ae89c-a6f5-47a9-8046-e45eb8107e38> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aaeton> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b41ae89c-a6f5-47a9-8046-e45eb8107e38> .
<https://starwars.com#grid_K9> <http://telicent.io/ontology/primaryName> "K9" .
<https://starwars.com#b41ae89c-a6f5-47a9-8046-e45eb8107e38> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aaeton"^^<http://www.w3.org/2001/XMLSchema#string> .

