Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Junction> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thesme> .
<https://starwars.com#sector_Thesme> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Junction> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b9bda23-1ca8-49f4-bd06-80c232389878> .
<https://starwars.com#sector_Thesme> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Junction> <http://www.w3.org/2000/01/rdf-schema#comment> "The Junction system was a star system located within the Vorc sector of the Mid Rim which contained the planet Junction V and the moon Delaluna." .
<https://starwars.com#planet_Junction> <http://telicent.io/ontology/primaryName> "Junction" .
<https://starwars.com#sector_Thesme> <http://telicent.io/ontology/primaryName> "Thesme" .
<https://starwars.com#3b9bda23-1ca8-49f4-bd06-80c232389878> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Junction> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O5> .
<https://starwars.com#planet_Junction> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3b9bda23-1ca8-49f4-bd06-80c232389878> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Junction"^^<http://www.w3.org/2001/XMLSchema#string> .

