Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#80088325-e5bf-469c-a506-5130ce5e4c8b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Iphigin> <http://telicent.io/ontology/primaryName> "Iphigin" .
<https://starwars.com#80088325-e5bf-469c-a506-5130ce5e4c8b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iphigin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iphigin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#80088325-e5bf-469c-a506-5130ce5e4c8b> .
<https://starwars.com#planet_Iphigin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iphigin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Iphigin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Iphigin> <http://www.w3.org/2000/01/rdf-schema#comment> "Iphigin was a planet in the Iphigin system of the Core Worlds and the homeworld of the Iphigini species. " .

