Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#94b2d22e-fe35-49c8-be1d-570d353e3aeb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Monastery> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Monastery> <http://www.w3.org/2000/01/rdf-schema#comment> "Monastery was a planet located in the galaxy's Mid Rim, in grid square Q-16 on the Standard Galactic Grid. " .
<https://starwars.com#sector_Haserian> <http://telicent.io/ontology/primaryName> "Haserian" .
<https://starwars.com#sector_Haserian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Monastery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q14> .
<https://starwars.com#94b2d22e-fe35-49c8-be1d-570d353e3aeb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Monastery"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Monastery> <http://telicent.io/ontology/primaryName> "Monastery" .
<https://starwars.com#planet_Monastery> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#94b2d22e-fe35-49c8-be1d-570d353e3aeb> .
<https://starwars.com#sector_Haserian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Monastery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Haserian> .

