Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sennex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c1b2b3a-c328-4441-9fe9-8ac50e9b00d2> .
<https://starwars.com#3c1b2b3a-c328-4441-9fe9-8ac50e9b00d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sennex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sennex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Sennex> <http://telicent.io/ontology/primaryName> "Sennex" .
<https://starwars.com#planet_Sennex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Sennex> <http://www.w3.org/2000/01/rdf-schema#comment> "The Sennex or Sennex Pirates were slave traders from the Sennex system. They were considered among the most despicable pirates in the galaxy during the time of the Galactic Civil War. " .
<https://starwars.com#3c1b2b3a-c328-4441-9fe9-8ac50e9b00d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Sennex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

