Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cholganna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T5> .
<https://starwars.com#grid_T5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#ccf6f30a-cebf-4400-a8f6-7c7ed3bdf5f2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T5"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T5> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Cholganna> <http://www.w3.org/2000/01/rdf-schema#comment> "Cholganna was a dark, cool forest planet in the Outer Rim Territories that was the homeworld of the nexus, a species of predatory felines that spread off-world as a result of their value as attack beasts. " .
<https://starwars.com#grid_T5> <http://telicent.io/ontology/primaryName> "T5" .
<https://starwars.com#sector_Colundra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_T5> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ccf6f30a-cebf-4400-a8f6-7c7ed3bdf5f2> .
<https://starwars.com#planet_Cholganna> <http://telicent.io/ontology/primaryName> "Cholganna" .
<https://starwars.com#sector_Colundra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Colundra> <http://telicent.io/ontology/primaryName> "Colundra" .
<https://starwars.com#planet_Cholganna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ccf6f30a-cebf-4400-a8f6-7c7ed3bdf5f2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Cholganna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6b96220f-5937-4cc8-b1af-d29de14ca290> .
<https://starwars.com#6b96220f-5937-4cc8-b1af-d29de14ca290> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#6b96220f-5937-4cc8-b1af-d29de14ca290> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cholganna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Cholganna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Colundra> .

