Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Iridium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Iridium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#planet_Iridium> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d7a3417-26d8-4409-b3ce-7ef4af05779e> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Iridium> <http://www.w3.org/2000/01/rdf-schema#comment> "Iridium was a planet in the Atrivis sector of the Outer Rim Territories. It was home to the infamous Pirates of Iridium, who utilized Iridium 'power gems' to disable the shields of their victims' starships, raiding Atrivis space lanes for a year. However, a task force of Jedi and Galactic Republic Judicials routed the pirates in a battle over Vuchelle in 22 BBY. " .
<https://starwars.com#planet_Iridium> <http://telicent.io/ontology/primaryName> "Iridium" .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5d7a3417-26d8-4409-b3ce-7ef4af05779e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Iridium"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Iridium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#5d7a3417-26d8-4409-b3ce-7ef4af05779e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

