Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Durkteel> <http://telicent.io/ontology/primaryName> "Durkteel" .
<https://starwars.com#planet_Durkteel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kastolar> .
<https://starwars.com#planet_Durkteel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Durkteel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c31514d8-4cc8-44df-ac80-17244faff50a> .
<https://starwars.com#c31514d8-4cc8-44df-ac80-17244faff50a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kastolar> <http://telicent.io/ontology/primaryName> "Kastolar" .
<https://starwars.com#sector_Kastolar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Durkteel> <http://www.w3.org/2000/01/rdf-schema#comment> "Durkteel was an agricultural planet located in the galaxy's Mid Rim that was the homeworld of the reptilian Saurin species. Durkteel was also the homeworld of Mattis Banz, a Force-sensitive human who joined the Resistance. Lund Gourley and Lund Berlo were cities located on Durkteel. " .
<https://starwars.com#planet_Durkteel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q10> .
<https://starwars.com#c31514d8-4cc8-44df-ac80-17244faff50a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Durkteel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kastolar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

