Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Monhudle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#3fb95cce-2fa6-4254-ba33-97c80535c09a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Monhudle"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_Monhudle> <http://telicent.io/ontology/primaryName> "Monhudle" .
<https://starwars.com#3fb95cce-2fa6-4254-ba33-97c80535c09a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Monhudle> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Monhudle> <http://www.w3.org/2000/01/rdf-schema#comment> "Monhudle was a mining planet in the Cassandran sectors region. During the Outer Rim Sieges of the Clone Wars, Jedi General Traavis led clone forces to war against the Separatists on this planet. " .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Monhudle> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3fb95cce-2fa6-4254-ba33-97c80535c09a> .
<https://starwars.com#planet_Monhudle> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

