Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Gilatter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I7> .
<https://starwars.com#845ea127-775b-4a59-a271-2013a97f46d0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gilatter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Churnis> .
<https://starwars.com#sector_Churnis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Gilatter> <http://telicent.io/ontology/primaryName> "Gilatter" .
<https://starwars.com#sector_Churnis> <http://telicent.io/ontology/primaryName> "Churnis" .
<https://starwars.com#sector_Churnis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gilatter> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#845ea127-775b-4a59-a271-2013a97f46d0> .
<https://starwars.com#845ea127-775b-4a59-a271-2013a97f46d0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gilatter"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gilatter> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Gilatter> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

