Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cantonica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1c4dcda6-3a67-458b-9b34-340d931dbfd5> .
<https://starwars.com#planet_Cantonica> <http://www.w3.org/2000/01/rdf-schema#comment> "An arid planet where the resort city of Canto Bight, home of the Canto Casino and Racetrack, is located." .
<https://starwars.com#planet_Cantonica> <http://telicent.io/ontology/primaryName> "Cantonica" .
<https://starwars.com#1c4dcda6-3a67-458b-9b34-340d931dbfd5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cantonica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Cantonica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Cantonica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1c4dcda6-3a67-458b-9b34-340d931dbfd5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cantonica"^^<http://www.w3.org/2001/XMLSchema#string> .

