Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cilpar> <http://www.w3.org/2000/01/rdf-schema#comment> "Cilpar was an agriworld in the Colonies, nearly covered in mountains, jungles, and forests. It was characterized by the near-indestructible ancient temples scattered across the surface. Local flora and fauna included the predatory ronk. " .
<https://starwars.com#planet_Cilpar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#efa258b7-8003-4e43-899d-3021f2039376> .
<https://starwars.com#planet_Cilpar> <http://telicent.io/ontology/primaryName> "Cilpar" .
<https://starwars.com#planet_Cilpar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cilpar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Cilpar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#efa258b7-8003-4e43-899d-3021f2039376> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cilpar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#efa258b7-8003-4e43-899d-3021f2039376> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

