Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#63809726-c1a1-40e3-8b5a-a034434d14a4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Perkell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_Q7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#6b352a3e-7a2a-40b7-a371-814013a364a2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aargonar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#region_MidRim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Perkell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Aargonar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aargonar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6b352a3e-7a2a-40b7-a371-814013a364a2> .
<https://starwars.com#sector_Perkell> <http://telicent.io/ontology/primaryName> "Perkell" .
<https://starwars.com#6b352a3e-7a2a-40b7-a371-814013a364a2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aargonar> <http://www.w3.org/2000/01/rdf-schema#comment> "Aargonar was a planet located in the galaxy. During the Clone Wars, the husband of Confederacy of Independent Systems Senator Mina Bonteri went there to set up a base for the Separatists, but was killed when Republic clone troopers attacked. It was the homeworld of the human Imperial stormtrooper TK-14057. " .
<https://starwars.com#grid_Q7> <http://telicent.io/ontology/primaryName> "Q7" .
<https://starwars.com#region_MidRim> <http://telicent.io/ontology/primaryName> "Mid Rim" .
<https://starwars.com#planet_Aargonar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Perkell> .
<https://starwars.com#grid_Q7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#63809726-c1a1-40e3-8b5a-a034434d14a4> .
<https://starwars.com#planet_Aargonar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#grid_Q7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Aargonar> <http://telicent.io/ontology/primaryName> "Aargonar" .
<https://starwars.com#region_MidRim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#63809726-c1a1-40e3-8b5a-a034434d14a4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Q7"^^<http://www.w3.org/2001/XMLSchema#string> .

