Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Osmani> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7751ef0e-c2cf-462c-ac3a-b3d68ed67e13> .
<https://starwars.com#planet_Osmani> <http://telicent.io/ontology/primaryName> "Osmani" .
<https://starwars.com#planet_Osmani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Osmani> <http://www.w3.org/2000/01/rdf-schema#comment> "Osmani was a planet located in the Western Reaches of the Mid Rim. Part of the Senex sector's Osmani system, is a minor trade world owing to its location in the Tangles. " .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#7751ef0e-c2cf-462c-ac3a-b3d68ed67e13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Osmani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Osmani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#7751ef0e-c2cf-462c-ac3a-b3d68ed67e13> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Osmani"^^<http://www.w3.org/2001/XMLSchema#string> .

