Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jarnollen> <http://www.w3.org/2000/01/rdf-schema#comment> "Jarnollen was a planet in close proximity to Ord Mantell in the Mid Rim. It was covered in tropical jungle, and its trees possessed overgrown vines. " .
<https://starwars.com#planet_Jarnollen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c0514e02-546f-41c9-a7cd-a17e9560831b> .
<https://starwars.com#planet_Jarnollen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#c0514e02-546f-41c9-a7cd-a17e9560831b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jarnollen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jarnollen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Jarnollen> <http://telicent.io/ontology/primaryName> "Jarnollen" .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Jarnollen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#c0514e02-546f-41c9-a7cd-a17e9560831b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .

