Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PolnSystem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J5> .
<https://starwars.com#planet_PolnSystem> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5150ce04-aeac-4923-b874-4e736a8ee11a> .
<https://starwars.com#5150ce04-aeac-4923-b874-4e736a8ee11a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Poln System"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PolnSystem> <http://telicent.io/ontology/primaryName> "Poln System" .
<https://starwars.com#planet_PolnSystem> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_PolnSystem> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PolnSystem> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#5150ce04-aeac-4923-b874-4e736a8ee11a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

