Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Grange> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#asteroidbelt_TheGraveyard> <http://www.w3.org/2000/01/rdf-schema#comment> "When arriving at the previous location of the planet, the Millennium Falcon, with Han Solo and Chewbacca piloting, exited hyperspace in the thick of the newly created asteroid belt. Many Alderaanian Exiles performed a private ceremony called the Returning, wherein they would shoot capsules filled with gifts for their friends and family. Some Alderaanians, who called themselves the Guardians, took to patrolling the Graveyard to prevent pirates from stealing the capsules. These Alderaanians were held in rather high regard among the exiles." .
<https://starwars.com#asteroidbelt_TheGraveyard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Ajara> <http://www.w3.org/2000/01/rdf-schema#comment> "Ajara was a gas giant planet located in the Cademimu sector of the galaxy's Outer Rim Territories, situated in a partially explored region of space off the Celanon Spur. It was orbited by the jungle moon Ajan Kloss, which had two moons itself. Ajara's intense magnetic field shielded Ajan Kloss from cosmic radiation." .
<https://starwars.com#moon_AjanKloss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#asteroidbelt_TheGraveyard> <http://telicent.io/ontology/primaryName> "The Graveyard" .
<https://starwars.com#moon_NarShaddaa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#moon_Yavin4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#moon_NarShaddaa> <http://ies.data.gov.uk/ontology/ies4#orbiting> <https://starwars.com#planet_NalHutta> .
<https://starwars.com#moon_NarShaddaa> <http://telicent.io/ontology/primaryName> "Nar Shaddaa" .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#planet_Exegol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#facility_CloudCity> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Facility> .
<https://starwars.com#planet_Stewjon> <http://telicent.io/ontology/primaryName> "Stewjon" .
<https://starwars.com#astronomicalobject_Marquinn> <http://telicent.io/ontology/primaryName> "Marquinn" .
<https://starwars.com#planet_Daiyu> <http://telicent.io/ontology/primaryName> "Daiyu" .
<https://starwars.com#moon_NarShaddaa> <http://www.w3.org/2000/01/rdf-schema#comment> "Nar Shaddaa, nicknamed the 'Smuggler's Moon,' was the notorious moon of the planet Nal Hutta, homeworld of the Hutt species. It was home to a large criminal underworld dominated by bounty hunters and Hutt crime lords. An ecumenopolis, the entire surface of Nar Shaddaa was covered in urban sprawl. It was the homeworld of the Palliduvan bounty hunter Aurra Sing, the Zabrak Jedi Master Eeth Koth, and the Jablogian slaver Azmorigan." .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Daiyu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ajara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cademimu> .
<https://starwars.com#planet_Exegol> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_F7> .
<https://starwars.com#planet_Stewjon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ajara> <http://telicent.io/ontology/primaryName> "Ajara" .
<https://starwars.com#moon_Yavin4> <http://www.w3.org/2000/01/rdf-schema#comment> "Yavin 4, also known as Yavin, was the jungle-covered fourth moon in orbit around the red gas giant Yavin Prime. Prior to and during the Galactic Civil War, it hosted the headquarters of the Alliance to Restore the Republic, a group of resistance fighters that opposed the dominant Galactic Empire. Following a major battle that took place around Yavin, the Alliance went on the run, and eventually relocated its headquarters to Hoth." .
<https://starwars.com#moon_ForestMoonOfEndor> <http://www.w3.org/2000/01/rdf-schema#comment> "Endor, designated IX3244-A, also known as the Forest Moon of Endor or the Sanctuary Moon, was a small forested moon that was the ninth moon that orbited the Outer Rim planet of the same name. It was the homeworld of the sentient Dulok, Ewok, and Yuzzum species, as well as the Wistie and semi-sentient Gorax races." .
<https://starwars.com#astronomicalobject_Sakreen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S7> .
<https://starwars.com#asteroidbelt_TheGraveyard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#AsteroidBelt> .
<https://starwars.com#planet_Exegol> <http://telicent.io/ontology/primaryName> "Exegol" .
<https://starwars.com#astronomicalobject_Marquinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#AstronomicalObject> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#facility_CloudCity> <http://www.w3.org/2000/01/rdf-schema#comment> "Cloud City was an outpost and a tibanna gas mining colony above the planet Bespin, named as such because it was perpetually surrounded by giant clouds. The city floated 60,000 kilometers above the core of the gas giant. It contained a large and famous luxury resort district on its upper levels, complete with hotels and casinos." .
<https://starwars.com#astronomicalobject_Marquinn> <http://www.w3.org/2000/01/rdf-schema#comment> "Marquinn was an astronomical object in the Inner Rim Territories where Zefin Tuzo ran a resort casino. Han Solo and Chewbacca went to Marquinn to sell several marked sabacc decks, but were pursued by Vullen Candroon, who was working with Tuzo." .
<https://starwars.com#moon_AjanKloss> <http://ies.data.gov.uk/ontology/ies4#orbiting> <https://starwars.com#planet_Ajara> .
<https://starwars.com#moon_Yavin4> <http://ies.data.gov.uk/ontology/ies4#orbiting> <https://starwars.com#planet_Yavin> .
<https://starwars.com#moon_AjanKloss> <http://telicent.io/ontology/primaryName> "Ajan Kloss" .
<https://starwars.com#moon_AjanKloss> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Moon> .
<https://starwars.com#sector_Rocantor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#moon_ForestMoonOfEndor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#astronomicalobject_Marquinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K8> .
<https://starwars.com#moon_ForestMoonOfEndor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Moon> .
<https://starwars.com#moon_ForestMoonOfEndor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#moon_NarShaddaa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Moon> .
<https://starwars.com#planet_Ajara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#moon_AjanKloss> <http://www.w3.org/2000/01/rdf-schema#comment> "Ajan Kloss was a jungle moon located in the Cademimu sector of the Outer Rim Territories, in grid square L-5 on the Standard Galactic Grid, orbiting the gas giant Ajara. It was notably used by Luke Skywalker to train Leia Organa in the way of the Jedi Order as his first student of a new generation of Jedi and later the Resistance during the war against the First Order, who established a base there." .
<https://starwars.com#planet_Daiyu> <http://www.w3.org/2000/01/rdf-schema#comment> "Daiyu was a temperate planet in the galaxy under the control of the Galactic Empire during its reign. In 9 BBY, Third Sister of the Inquisitorius devised a plan to lure Jedi Master Obi-Wan Kenobi out of hiding by learning of his relationship with Senator Bail Organa. The Third Sister had Vect Nokru and his gang kidnap Organa's daughter Leia." .
<https://starwars.com#moon_Yavin4> <http://telicent.io/ontology/primaryName> "Yavin 4" .
<https://starwars.com#moon_Yavin4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Moon> .
<https://starwars.com#planet_Exegol> <http://www.w3.org/2000/01/rdf-schema#comment> "Exegol (also spelled Ixigul in ancient texts) was a dark desert planet located within the Unknown Regions that, according to legend, was the hidden redoubt world of the Sith. It was occupied by the Sith Lord Darth Sidious and the Sith Eternal by 35 ABY. It was also the birthplace of Supreme Leader Snoke, whom Sidious created to rule the First Order while concealing himself in the shadows. Exegol was used to hide the Final Order, which was a fleet amassed by Sidious and the Sith Eternal, from where they planned to deploy their Star Destroyers and establish a new Sith Empire. Exegol was the site of a battle during the war between the First Order and the Resistance, which saw the defeat of the Sith loyalists." .
<https://starwars.com#planet_Grange> <http://www.w3.org/2000/01/rdf-schema#comment> "Grange was an agrarian planet located in the Rocantor sector of the Mid Rim Territories. It was the homeworld of Galen Erso. During the Clone Wars, Grange was a strategically-important world, being well situated for hyperspace jump points to remote sectors. As such, it was besieged by the Confederacy of Independent Systems in 21 BBY." .
<https://starwars.com#astronomicalobject_Sakreen> <http://www.w3.org/2000/01/rdf-schema#comment> "Sakreen was a rocky astronomical object in the Outer Rim Territories of the galaxy. It was the hiding place of the pirate Rane Mahal, whose starship had crashed on the astronomical object." .
<https://starwars.com#sector_Rocantor> <http://telicent.io/ontology/primaryName> "Rocantor" .
<https://starwars.com#sector_Cademimu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#astronomicalobject_Sakreen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#AstronomicalObject> .
<https://starwars.com#moon_ForestMoonOfEndor> <http://ies.data.gov.uk/ontology/ies4#orbiting> <https://starwars.com#planet_Endor> .
<https://starwars.com#planet_Grange> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rocantor> .
<https://starwars.com#astronomicalobject_Sakreen> <http://telicent.io/ontology/primaryName> "Sakreen" .
<https://starwars.com#facility_CloudCity> <http://ies.data.gov.uk/ontology/ies4#orbiting> <https://starwars.com#planet_Bespin> .
<https://starwars.com#moon_AjanKloss> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cademimu> .
<https://starwars.com#moon_NarShaddaa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#planet_Stewjon> <http://www.w3.org/2000/01/rdf-schema#comment> "Stewjon was a planet that was the homeworld of Obi-Wan Kenobi, a male human Jedi Master. Between 32 and 29 BBY, Kenobi told his Padawan, Anakin Skywalker, that he did not remember leaving his homeworld." .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Grange> <http://telicent.io/ontology/primaryName> "Grange" .
<https://starwars.com#moon_ForestMoonOfEndor> <http://telicent.io/ontology/primaryName> "Forest Moon Of Endor" .
<https://starwars.com#planet_Ajara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Cademimu> <http://telicent.io/ontology/primaryName> "Cademimu" .
<https://starwars.com#facility_CloudCity> <http://telicent.io/ontology/primaryName> "Cloud City" .
<https://starwars.com#moon_Yavin4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

