Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Scarif> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .
<https://starwars.com#planet_Scarif> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#planet_Scarif> <http://telicent.io/ontology/primaryName> "Scarif" .
<https://starwars.com#planet_Scarif> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Scarif> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#659e5089-c408-4a82-be42-2efda67ae55c> .
<https://starwars.com#planet_Scarif> <http://www.w3.org/2000/01/rdf-schema#comment> "Oceanic 'paradise world' used for construction of the Death Star after the project was moved from Geonosis during the Imperial Era. When Rebel Alliance members raid the Imperial database from the secret base on one of its tropical islands, the planet is destroyed to impede their escape with the Death Star plans." .
<https://starwars.com#659e5089-c408-4a82-be42-2efda67ae55c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Scarif"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#659e5089-c408-4a82-be42-2efda67ae55c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

