Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#ecc3b760-fa86-4cf2-8ec3-c6b308d08fec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Kalamith> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tandun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kalamith> .
<https://starwars.com#planet_Tandun> <http://telicent.io/ontology/primaryName> "Tandun" .
<https://starwars.com#sector_Kalamith> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tandun> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ecc3b760-fa86-4cf2-8ec3-c6b308d08fec> .
<https://starwars.com#planet_Tandun> <http://www.w3.org/2000/01/rdf-schema#comment> "Tandun III, also known as Tandun Three, was a youthful planet that occupied a young star system in the Outer Rim Territories. " .
<https://starwars.com#planet_Tandun> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tandun> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#sector_Kalamith> <http://telicent.io/ontology/primaryName> "Kalamith" .
<https://starwars.com#ecc3b760-fa86-4cf2-8ec3-c6b308d08fec> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tandun"^^<http://www.w3.org/2001/XMLSchema#string> .

