Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Diamal> <http://www.w3.org/2000/01/rdf-schema#comment> "The Diamala (singular Diamal) were a species from the planet Diamal, in the Core Worlds, who, along with their rivals the Ishori, became prominent during the crises over the Caamas Document and the apparent return of Grand Admiral Thrawn. Diamala were recognizable by their leathery skin, white manes, and fan-shaped ears, which they could move independently to gesture with. The Diamala temperament was generally calm and unemotional, with a strong sense of personal pride. They had extensive financial and business holdings, which they attributed to hard work rather than luck. " .
<https://starwars.com#planet_Diamal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#73836fee-9023-4caa-885d-e657a336e584> .
<https://starwars.com#73836fee-9023-4caa-885d-e657a336e584> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Diamal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Diamal> <http://telicent.io/ontology/primaryName> "Diamal" .
<https://starwars.com#planet_Diamal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#73836fee-9023-4caa-885d-e657a336e584> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Diamal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Diamal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

