Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Belasco> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zirulast> <http://www.w3.org/2000/01/rdf-schema#comment> "Zirulast was a terrestrial backwater planet located in the Zirulast system, a part of the Belasco sector in the Slice portion of the Expansion Region. Orbiting the white dwarf star of the same name, Zirulast was situated on the Ootmian Pabol hyperlane, which connected it to the Belasco system as well as the New Apsolon system in the Mid Rim. Zirulast was a dry and dusty world encircled by rings of ice particles. The Temolaks, sentient humanoids speaking the Temolish language, were native to the planet, evolving redundant internal organs in order to survive the rigors of their homeworld. " .
<https://starwars.com#planet_Zirulast> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f9175930-9b9e-474a-9a77-856c5dce7728> .
<https://starwars.com#planet_Zirulast> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Belasco> .
<https://starwars.com#f9175930-9b9e-474a-9a77-856c5dce7728> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zirulast"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Zirulast> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zirulast> <http://telicent.io/ontology/primaryName> "Zirulast" .
<https://starwars.com#f9175930-9b9e-474a-9a77-856c5dce7728> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Belasco> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Zirulast> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P11> .
<https://starwars.com#sector_Belasco> <http://telicent.io/ontology/primaryName> "Belasco" .

