Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jiroch> <http://telicent.io/ontology/primaryName> "Jiroch" .
<https://starwars.com#planet_Jiroch> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#663854ed-b369-41bd-b501-13aef62b2d4a> .
<https://starwars.com#planet_Jiroch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Yushan> .
<https://starwars.com#planet_Jiroch> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K17> .
<https://starwars.com#sector_Yushan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Yushan> <http://telicent.io/ontology/primaryName> "Yushan" .
<https://starwars.com#663854ed-b369-41bd-b501-13aef62b2d4a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jiroch"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Yushan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#663854ed-b369-41bd-b501-13aef62b2d4a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Jiroch> <http://www.w3.org/2000/01/rdf-schema#comment> "Jiroch was an astronomical object located in the galaxy's Mid Rim on the Corellian Trade Spine. " .
<https://starwars.com#planet_Jiroch> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

