Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mannova> <http://www.w3.org/2000/01/rdf-schema#comment> "Mannova was an industrial dumping ground located within the Mannova system in the Gordian Reach of the Outer Rim Territories region of the galaxy. It was the home to the Mannovans, a sardonic gray-furred species that seemingly unruffled by the ecological disaster their homeworld has become. The mountains of junk were picked over by speculators, scavengers and those looking for impossible-to-find parts. The fighting after the Battle of Yavin made fortunes on Mannova as scavengers hauled wrecked ship parts and equipment there in bulk. " .
<https://starwars.com#planet_Mannova> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_Mannova> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f1691a1d-83a6-48e0-9ed5-eb2225ad6493> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#f1691a1d-83a6-48e0-9ed5-eb2225ad6493> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mannova"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mannova> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f1691a1d-83a6-48e0-9ed5-eb2225ad6493> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Mannova> <http://telicent.io/ontology/primaryName> "Mannova" .
<https://starwars.com#planet_Mannova> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

