Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Galidraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thanium> .
<https://starwars.com#b7af5161-e778-43ac-bdbd-1faf008d5ed1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Galidraan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Galidraan> <http://telicent.io/ontology/primaryName> "Galidraan" .
<https://starwars.com#sector_Thanium> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Thanium> <http://telicent.io/ontology/primaryName> "Thanium" .
<https://starwars.com#planet_Galidraan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Thanium> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Galidraan> <http://www.w3.org/2000/01/rdf-schema#comment> "Galidraan was a planet located in the Galidraan system within the galaxy's Outer Rim Territories. It shared its name with Galidraan III and Galidraan IV, all of which were located in the same system. " .
<https://starwars.com#planet_Galidraan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R6> .
<https://starwars.com#b7af5161-e778-43ac-bdbd-1faf008d5ed1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Galidraan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b7af5161-e778-43ac-bdbd-1faf008d5ed1> .

