Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eredenn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Eredenn> <http://telicent.io/ontology/primaryName> "Eredenn" .
<https://starwars.com#planet_Eredenn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#903ab224-a07e-4b8d-8d6e-9f939bca4c22> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eredenn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#903ab224-a07e-4b8d-8d6e-9f939bca4c22> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Eredenn> <http://www.w3.org/2000/01/rdf-schema#comment> "Eredenn Prime, also known as Eredenn IV, was a frozen planet in the Tion Hegemony. " .
<https://starwars.com#planet_Eredenn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#planet_Eredenn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#903ab224-a07e-4b8d-8d6e-9f939bca4c22> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

