Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Mussubir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#527a7307-2255-499c-b3c9-ea50083d497b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mussubir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mussubir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Mussubir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#527a7307-2255-499c-b3c9-ea50083d497b> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mussubir> <http://www.w3.org/2000/01/rdf-schema#comment> "Mussubir III, or simply Mussubir, was a planet located in the Mussubir system of the Senex sector, in the Mid Rim of the galaxy. It was an important industrial world controlled by House Araba. " .
<https://starwars.com#planet_Mussubir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#527a7307-2255-499c-b3c9-ea50083d497b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Mussubir> <http://telicent.io/ontology/primaryName> "Mussubir" .

