Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_U11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b165df32-32d4-4ad0-890e-59d6d7f6af8d> .
<https://starwars.com#grid_U11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Aduba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Aduba> <http://www.w3.org/2000/01/rdf-schema#comment> "Aduba was an astronomical object located in the galaxy's Outer Rim Territories way out on the edge of Wild Space, positioned at the coordinates U-11 of the Standard Galactic Grid. It was the homeworld of Cobalt Hammer pilot Finch Dallow. Dallow flew crop-dusters and spotter rigs on Aduba before qualifying for a post in the New Republic Scout Service. " .
<https://starwars.com#b165df32-32d4-4ad0-890e-59d6d7f6af8d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U11"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bheriz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Bheriz> <http://telicent.io/ontology/primaryName> "Bheriz" .
<https://starwars.com#planet_Aduba> <http://telicent.io/ontology/primaryName> "Aduba" .
<https://starwars.com#planet_Aduba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U11> .
<https://starwars.com#2a52c976-5b8f-4720-977a-06615e299e09> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aduba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U11> <http://telicent.io/ontology/primaryName> "U11" .
<https://starwars.com#sector_Bheriz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Aduba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2a52c976-5b8f-4720-977a-06615e299e09> .
<https://starwars.com#grid_U11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#2a52c976-5b8f-4720-977a-06615e299e09> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b165df32-32d4-4ad0-890e-59d6d7f6af8d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aduba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bheriz> .

