Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rintonne> <http://www.w3.org/2000/01/rdf-schema#comment> "Rintonne was an astronomical object located in the Lambda sector of the regions known as the Mid Rim Territories and the Trailing Sectors. It was situated within grid square P-16 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Rintonne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lambda> .
<https://starwars.com#sector_Lambda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_Lambda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rintonne> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rintonne> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P16> .
<https://starwars.com#610123b1-7227-4830-b5ee-ceba13be0290> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#610123b1-7227-4830-b5ee-ceba13be0290> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rintonne"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rintonne> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#610123b1-7227-4830-b5ee-ceba13be0290> .
<https://starwars.com#planet_Rintonne> <http://telicent.io/ontology/primaryName> "Rintonne" .
<https://starwars.com#sector_Lambda> <http://telicent.io/ontology/primaryName> "Lambda" .

