Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#bf1d3749-a1e3-4f1f-93a5-510d6a99a331> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#bf1d3749-a1e3-4f1f-93a5-510d6a99a331> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wakeelmui"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Wakeelmui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Wakeelmui> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Wakeelmui> <http://www.w3.org/2000/01/rdf-schema#comment> "Wakeelmui was a planet located in the Colonies. " .
<https://starwars.com#planet_Wakeelmui> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Wakeelmui> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bf1d3749-a1e3-4f1f-93a5-510d6a99a331> .
<https://starwars.com#planet_Wakeelmui> <http://telicent.io/ontology/primaryName> "Wakeelmui" .

