Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Oricon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Oricon> <http://www.w3.org/2000/01/rdf-schema#comment> "Oricon was a moon in the Outer Rim Territories just outside the Seat of The Empire. " .
<https://starwars.com#planet_Oricon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b88fab99-6a70-4e86-a5e1-f3ba151f2415> .
<https://starwars.com#planet_Oricon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P3> .
<https://starwars.com#sector_Corva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b88fab99-6a70-4e86-a5e1-f3ba151f2415> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Oricon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Oricon> <http://telicent.io/ontology/primaryName> "Oricon" .
<https://starwars.com#sector_Corva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Oricon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Corva> .
<https://starwars.com#b88fab99-6a70-4e86-a5e1-f3ba151f2415> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Corva> <http://telicent.io/ontology/primaryName> "Corva" .

