Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NumidianPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Rainforest paradise that is a haven to smugglers and thieves." .
<https://starwars.com#planet_NumidianPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BrightJewel> .
<https://starwars.com#planet_NumidianPrime> <http://telicent.io/ontology/primaryName> "Numidian Prime" .
<https://starwars.com#planet_NumidianPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a0ae1ebd-15f1-4f5e-b148-ccb6975bb912> .
<https://starwars.com#sector_BrightJewel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#sector_BrightJewel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NumidianPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L7> .
<https://starwars.com#sector_BrightJewel> <http://telicent.io/ontology/primaryName> "Bright Jewel" .
<https://starwars.com#a0ae1ebd-15f1-4f5e-b148-ccb6975bb912> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#a0ae1ebd-15f1-4f5e-b148-ccb6975bb912> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Numidian Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NumidianPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

