Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_BozPity> <http://telicent.io/ontology/primaryName> "Boz Pity" .
<https://starwars.com#planet_BozPity> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7df87713-70bf-4ca9-a55d-7f6ae471a36b> .
<https://starwars.com#planet_BozPity> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_S9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#4f068cda-c7be-4666-85e3-c13db77bf9f8> .
<https://starwars.com#7df87713-70bf-4ca9-a55d-7f6ae471a36b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Boz Pity"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_S9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#grid_S9> <http://telicent.io/ontology/primaryName> "S9" .
<https://starwars.com#planet_BozPity> <http://www.w3.org/2000/01/rdf-schema#comment> "Boz Pity was a planet located in the Boz Pity system of the galaxy's Mid Rim. During the High Republic Era, it was considered a key member of the Galactic Republic, and received a sky-island with a representation of its environment at the Valo Republic Fair. By the time of the Clone Wars, Boz Pity was largely uninhabited, and the Confederacy of Independent Systems established a presence on it during the conflict, enabling them to frequently strike at nearby Republic targets. It was then subject to a siege by Republic forces; after the conclusion of the Siege of Saleucami during the Outer Rim Sieges, Jedi General Quinlan Vos moved his troops to support the siege. " .
<https://starwars.com#sector_Halla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#4f068cda-c7be-4666-85e3-c13db77bf9f8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Halla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_BozPity> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#7df87713-70bf-4ca9-a55d-7f6ae471a36b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#4f068cda-c7be-4666-85e3-c13db77bf9f8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Halla> <http://telicent.io/ontology/primaryName> "Halla" .
<https://starwars.com#planet_BozPity> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Halla> .

