Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thokos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Thokos> <http://telicent.io/ontology/primaryName> "Thokos" .
<https://starwars.com#planet_Thokos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#905d52fd-7be4-41ea-98f0-265cd6fc56b0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#905d52fd-7be4-41ea-98f0-265cd6fc56b0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thokos"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thokos> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#905d52fd-7be4-41ea-98f0-265cd6fc56b0> .
<https://starwars.com#planet_Thokos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thokos> <http://www.w3.org/2000/01/rdf-schema#comment> "Thokos was a planet located within the Thokos system of the Core Worlds. Colonists from Thokos settled Ammuud. " .

