Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Aquella> <http://telicent.io/ontology/primaryName> "Aquella" .
<https://starwars.com#planet_Aquella> <http://www.w3.org/2000/01/rdf-schema#comment> "Aquella was a Mid Rim world located in the Senex sector. By 3643 BBY, an aristocrat residing on Aquella offered valuable items as dowry to anyone who would marry his cousin. Aquella was colonized by Human settlers at one point; however, the colony was lost by the time the Senex-Juvex region came under the rule of the aristocratic Ancient Houses. The Aquellans, the descendants of the original colonists, were a culture notable for their rituals involving the dyeing and tattooing of young males' bodies. " .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Aquella> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a5d7bb1-656c-4a14-a547-607ffb2935ea> .
<https://starwars.com#6a5d7bb1-656c-4a14-a547-607ffb2935ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Aquella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Aquella> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#6a5d7bb1-656c-4a14-a547-607ffb2935ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aquella"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aquella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

