Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Berchest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anthos> .
<https://starwars.com#edbb6e69-768a-42eb-9962-ebcd58cca701> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Berchest"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Berchest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#edbb6e69-768a-42eb-9962-ebcd58cca701> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Anthos> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Berchest> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#edbb6e69-768a-42eb-9962-ebcd58cca701> .
<https://starwars.com#planet_Berchest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Berchest> <http://www.w3.org/2000/01/rdf-schema#comment> "Berchest was an astronomical object located in the galaxy's Inner Rim. In 4 ABY, General Hera Syndulla led a New Republic strike at Berchest in hopes of capturing Imperial Yachts and securing useful data. " .
<https://starwars.com#sector_Anthos> <http://telicent.io/ontology/primaryName> "Anthos" .
<https://starwars.com#sector_Anthos> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Berchest> <http://telicent.io/ontology/primaryName> "Berchest" .

