Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dd36b80d-dce6-436f-93d2-40ddc21a99bd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dd36b80d-dce6-436f-93d2-40ddc21a99bd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ushruu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ushruu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dd36b80d-dce6-436f-93d2-40ddc21a99bd> .
<https://starwars.com#planet_Ushruu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ushruu> <http://telicent.io/ontology/primaryName> "Ushruu" .
<https://starwars.com#planet_Ushruu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Ushruu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .

