Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Spirador> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#900a21f3-6f78-47aa-86ec-86835a5dc75e> .
<https://starwars.com#sector_Tandon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Spirador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tandon> .
<https://starwars.com#planet_Spirador> <http://www.w3.org/2000/01/rdf-schema#comment> "Spirador was the capital planet of the Tandon sector and the site of Moff Harlov Jarnek's palace. " .
<https://starwars.com#planet_Spirador> <http://telicent.io/ontology/primaryName> "Spirador" .
<https://starwars.com#900a21f3-6f78-47aa-86ec-86835a5dc75e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tandon> <http://telicent.io/ontology/primaryName> "Tandon" .
<https://starwars.com#planet_Spirador> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#900a21f3-6f78-47aa-86ec-86835a5dc75e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Spirador"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tandon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Spirador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q14> .

