Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sikurd> <http://www.w3.org/2000/01/rdf-schema#comment> "Sikurd was a planet located in the Sikurd system within the Tynquay sector in the Outer Rim Territories, and it was the homeworld of the Sikurdian species. It was also where Sikurdian battle-axes were made. " .
<https://starwars.com#planet_Sikurd> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#460e5089-96a4-4591-8b51-90f88d25f78c> .
<https://starwars.com#460e5089-96a4-4591-8b51-90f88d25f78c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_I-Sector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sikurd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q4> .
<https://starwars.com#planet_Sikurd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sikurd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_I-Sector> .
<https://starwars.com#460e5089-96a4-4591-8b51-90f88d25f78c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sikurd"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_I-Sector> <http://telicent.io/ontology/primaryName> "I-Sector" .
<https://starwars.com#planet_Sikurd> <http://telicent.io/ontology/primaryName> "Sikurd" .
<https://starwars.com#sector_I-Sector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

