Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#dc5c300e-59b6-44b7-bb94-d397cde40d37> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Council> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Council> <http://telicent.io/ontology/primaryName> "Council" .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Council> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dc5c300e-59b6-44b7-bb94-d397cde40d37> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Council"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Council> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dc5c300e-59b6-44b7-bb94-d397cde40d37> .
<https://starwars.com#planet_Council> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Council> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

