Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tarnoonga> <http://www.w3.org/2000/01/rdf-schema#comment> "Tarnoonga was an ocean-covered planet located in the Arkanis sector. " .
<https://starwars.com#16742ef5-effc-4401-9637-01e65e0bd477> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_Tarnoonga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_Tarnoonga> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#16742ef5-effc-4401-9637-01e65e0bd477> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tarnoonga"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Tarnoonga> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#16742ef5-effc-4401-9637-01e65e0bd477> .
<https://starwars.com#planet_Tarnoonga> <http://telicent.io/ontology/primaryName> "Tarnoonga" .
<https://starwars.com#planet_Tarnoonga> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .

