Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Asmeru> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Asmeru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Asmeru> <http://www.w3.org/2000/01/rdf-schema#comment> "Asmeru was a planet located in the galaxy's Mid Rim. On the 234th day of the world's sixteenth month, the natives at one point celebrated a festival known as Q'anah in their language. The noble House Elegin were based on the planet, and during the reign of the Galactic Republic they hired a man from the planet Brentaal IV to oversee their security. The man's daughter fell in love with a young Elegin noble who secretly lived as a pirate, and when the daughter too took up piracy she began using the name Q'anah in honor of the Asmeru festival. " .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Asmeru> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Asmeru> <http://telicent.io/ontology/primaryName> "Asmeru" .
<https://starwars.com#planet_Asmeru> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1f681155-0aeb-441c-bd8e-33f2f436c75d> .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#1f681155-0aeb-441c-bd8e-33f2f436c75d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Asmeru"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1f681155-0aeb-441c-bd8e-33f2f436c75d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

