Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#a96eddf2-7cf7-42c9-827b-9a6b15b15160> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Reytha"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Reytha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Harron> .
<https://starwars.com#sector_Harron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Reytha> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a96eddf2-7cf7-42c9-827b-9a6b15b15160> .
<https://starwars.com#planet_Reytha> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O12> .
<https://starwars.com#planet_Reytha> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a96eddf2-7cf7-42c9-827b-9a6b15b15160> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Harron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Harron> <http://telicent.io/ontology/primaryName> "Harron" .
<https://starwars.com#planet_Reytha> <http://www.w3.org/2000/01/rdf-schema#comment> "Reytha was one of the most productive agriworlds of the Galactic Republic and later the Galactic Empire. At the time of the Battle of Yavin, Reytha was governed by Governor Antes Belladar. " .
<https://starwars.com#planet_Reytha> <http://telicent.io/ontology/primaryName> "Reytha" .

