Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Jaso> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Thyferra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jaso> .
<https://starwars.com#sector_Jaso> <http://telicent.io/ontology/primaryName> "Jaso" .
<https://starwars.com#planet_Thyferra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#planet_Thyferra> <http://www.w3.org/2000/01/rdf-schema#comment> "Arvel Crynyd piloted Z-95 Headhunters for a bacta cartel on the world. Following the Battle of Exegol in 35 ABY, Thyferra was in open rebellion against the First Order. " .
<https://starwars.com#87763750-63f0-4ca6-8a8b-e60da8732843> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thyferra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Jaso> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Thyferra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thyferra> <http://telicent.io/ontology/primaryName> "Thyferra" .
<https://starwars.com#87763750-63f0-4ca6-8a8b-e60da8732843> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thyferra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#87763750-63f0-4ca6-8a8b-e60da8732843> .

