Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chiron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_AshWorlds> .
<https://starwars.com#sector_AshWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Chiron> <http://telicent.io/ontology/primaryName> "Chiron" .
<https://starwars.com#f62e61d8-d00e-485b-8320-b496e4505142> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_AshWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_AshWorlds> <http://telicent.io/ontology/primaryName> "Ash Worlds" .
<https://starwars.com#planet_Chiron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T7> .
<https://starwars.com#planet_Chiron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chiron> <http://www.w3.org/2000/01/rdf-schema#comment> "Chiron's end came when he was unable to break his loyalty to the Empire even when confronted with direct evidence that everything he had suspected about the Empire's corruption was true. During Zare Leonis's rescue of his sister, he came face-to-face with Dhara Leonis. Zare Leonis pleaded with him, telling him that what had happened to his sister was proof of everything he had said. Chiron, however, insisted that he surrender, adamant that he would receive a fair hearing. When Zare still refused, Chiron said that he would do his duty, but Dhara would not allow things to continue. She drew upon the power of the Force to summon chunks of rocks and metal, which buried Chiron and his accompanying stormtroopers. Before escaping, Zare closed Chiron's lifeless eyes. " .
<https://starwars.com#planet_Chiron> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f62e61d8-d00e-485b-8320-b496e4505142> .
<https://starwars.com#f62e61d8-d00e-485b-8320-b496e4505142> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chiron"^^<http://www.w3.org/2001/XMLSchema#string> .

