Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d9417fc5-027b-4719-b7f9-a11c1683bd38> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gamor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Gamor> <http://www.w3.org/2000/01/rdf-schema#comment> "Gamor was an astronomical object located in the regions known as the Expansion Region and the Slice. It was also situated in the grid square O-14 of the Standard Galactic Grid. The super-hyperroute known as the Corellian Run connected Gamor to Allanteen VI and Bacrana, and another hyperspace route linked it to the world Aridus. Gamor shared its name with the trade route known as the Gamor Run. " .
<https://starwars.com#planet_Gamor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chaykin> .
<https://starwars.com#planet_Gamor> <http://telicent.io/ontology/primaryName> "Gamor" .
<https://starwars.com#planet_Gamor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d9417fc5-027b-4719-b7f9-a11c1683bd38> .
<https://starwars.com#sector_Chaykin> <http://telicent.io/ontology/primaryName> "Chaykin" .
<https://starwars.com#d9417fc5-027b-4719-b7f9-a11c1683bd38> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gamor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Chaykin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Gamor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#sector_Chaykin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

