Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_ZebitropeIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#15ac7985-49db-47ce-b36d-dfb320fca152> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ZebitropeIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#15ac7985-49db-47ce-b36d-dfb320fca152> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zebitrope IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ZebitropeIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_ZebitropeIV> <http://telicent.io/ontology/primaryName> "Zebitrope IV" .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_ZebitropeIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#15ac7985-49db-47ce-b36d-dfb320fca152> .
<https://starwars.com#planet_ZebitropeIV> <http://www.w3.org/2000/01/rdf-schema#comment> "Zebitrope IV was a terrestrial planet[4] located in the Zebitrope system,[2] a part of the Centrality sector in the Slice portion of the Outer Rim Territories.[1] It occupied the fourth orbital position in its star system,[3] which was connected to the Cadma system via the Cadma Conduit hyperlane." .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

