Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0b76a81b-0c22-4810-a5b0-2e137994c6f9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kooriva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#0b76a81b-0c22-4810-a5b0-2e137994c6f9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kooriva"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kooriva> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kooriva> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M14> .
<https://starwars.com#planet_Kooriva> <http://telicent.io/ontology/primaryName> "Kooriva" .
<https://starwars.com#planet_Kooriva> <http://www.w3.org/2000/01/rdf-schema#comment> "Kooriva was a planet located in the galaxy's Inner Rim. " .
<https://starwars.com#planet_Kooriva> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0b76a81b-0c22-4810-a5b0-2e137994c6f9> .

