Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kuar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Kuar> <http://telicent.io/ontology/primaryName> "Kuar" .
<https://starwars.com#planet_Kuar> <http://www.w3.org/2000/01/rdf-schema#comment> "Kuar was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Kuar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kuar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aa57267a-7e41-4de8-ae63-2596f94ebe96> .
<https://starwars.com#aa57267a-7e41-4de8-ae63-2596f94ebe96> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kuar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#aa57267a-7e41-4de8-ae63-2596f94ebe96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kuar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K10> .

