Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Varvrona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Obtrexta> .
<https://starwars.com#5819a8d7-87dd-4656-8993-8388cef15d8a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Varvrona> <http://telicent.io/ontology/primaryName> "Varvrona" .
<https://starwars.com#sector_Obtrexta> <http://telicent.io/ontology/primaryName> "Obtrexta" .
<https://starwars.com#5819a8d7-87dd-4656-8993-8388cef15d8a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Varvrona"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Varvrona> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5819a8d7-87dd-4656-8993-8388cef15d8a> .
<https://starwars.com#sector_Obtrexta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Obtrexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Varvrona> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .
<https://starwars.com#planet_Varvrona> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Varvrona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

