Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bescane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Obtrexta> .
<https://starwars.com#7538cbe7-03b4-4797-aca9-bb32ac5abe4e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bescane> <http://www.w3.org/2000/01/rdf-schema#comment> "Bescane was an astronomical object located in the regions known as the Outer Rim Territories and the New Territories. Located in grid square K-3 on the Standard Galactic Grid, Bescane was connected via hyperspace routes to the astronomical objects Bastion, Dubrillion and Jaemus. " .
<https://starwars.com#7538cbe7-03b4-4797-aca9-bb32ac5abe4e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bescane"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Obtrexta> <http://telicent.io/ontology/primaryName> "Obtrexta" .
<https://starwars.com#planet_Bescane> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bescane> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7538cbe7-03b4-4797-aca9-bb32ac5abe4e> .
<https://starwars.com#sector_Obtrexta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bescane> <http://telicent.io/ontology/primaryName> "Bescane" .
<https://starwars.com#sector_Obtrexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bescane> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K3> .

