Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Cassander> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d66bb17b-0a39-4c35-882e-3d9543d935b9> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#d66bb17b-0a39-4c35-882e-3d9543d935b9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#planet_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cassander> <http://www.w3.org/2000/01/rdf-schema#comment> "Cassander was the chief planet of the Cassandran sectors. It was the sector capital of Cassander sector under the New Order, and it was on the Braxant Run. " .
<https://starwars.com#d66bb17b-0a39-4c35-882e-3d9543d935b9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cassander"^^<http://www.w3.org/2001/XMLSchema#string> .

