Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c9cb2d0a-3e4c-4d17-8df7-1756754c76a8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bespin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bespin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .
<https://starwars.com#planet_Bespin> <http://telicent.io/ontology/primaryName> "Bespin" .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#c9cb2d0a-3e4c-4d17-8df7-1756754c76a8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bespin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c9cb2d0a-3e4c-4d17-8df7-1756754c76a8> .
<https://starwars.com#planet_Bespin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Bespin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Bespin> <http://www.w3.org/2000/01/rdf-schema#comment> "A gas planet with a thin layer of habitable atmosphere where Cloud City was located. The planet's gas layers were a source of rare tibanna gas which was harvested and refined at mining complexes like Cloud City." .

