Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Komnor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c2537ea3-8569-4906-ba92-61ee8937ca19> .
<https://starwars.com#c2537ea3-8569-4906-ba92-61ee8937ca19> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Komnor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Komnor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Suolriep> .
<https://starwars.com#planet_Komnor> <http://www.w3.org/2000/01/rdf-schema#comment> "Komnor was a planet located within the Outer Rim Territories. The planet was absorbed into Xim's Empire as he expanded his borders from the Kingdom of Cron. A few years before the Galactic Civil War, Han Solo met Chewbacca during a skirmish near Komnor. A vicious warlord later arrived in the system and evicted the Hutts from their home. The homeless Hutts complained to Jabba Desilijic Tiure, who assigned Dyyz Nataz with the job of assassinating the warlord. " .
<https://starwars.com#planet_Komnor> <http://telicent.io/ontology/primaryName> "Komnor" .
<https://starwars.com#sector_Suolriep> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Komnor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Komnor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .
<https://starwars.com#sector_Suolriep> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#c2537ea3-8569-4906-ba92-61ee8937ca19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Suolriep> <http://telicent.io/ontology/primaryName> "Suolriep" .

