Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#2cedf2e5-78f3-4fb5-bc16-85c165271836> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vor Deo"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_VorDeo> <http://telicent.io/ontology/primaryName> "Vor Deo" .
<https://starwars.com#planet_VorDeo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#planet_VorDeo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#2cedf2e5-78f3-4fb5-bc16-85c165271836> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_VorDeo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R17> .
<https://starwars.com#planet_VorDeo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2cedf2e5-78f3-4fb5-bc16-85c165271836> .
<https://starwars.com#planet_VorDeo> <http://www.w3.org/2000/01/rdf-schema#comment> "Vor Deo was a terrestrial planet located in the Vor Deo system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. Vor Deo was located on the Old Corellian Run hyperlane and on the tip of the Cranan-Excarga Route. " .

