Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kalla> <http://telicent.io/ontology/primaryName> "Kalla" .
<https://starwars.com#planet_Kalla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#d4c29715-41e4-4591-a319-0acfafe2e336> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kalla"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Kalla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Kalla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Kalla> <http://www.w3.org/2000/01/rdf-schema#comment> "Kalla VII, also simply known as Kalla, was a planet in the Corporate Sector. It was the location of the University of Kalla, an Imperial base, and the headquarters of Unlimited Horizons Inc. " .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Kalla> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d4c29715-41e4-4591-a319-0acfafe2e336> .
<https://starwars.com#d4c29715-41e4-4591-a319-0acfafe2e336> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

