Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Capza> <http://www.w3.org/2000/01/rdf-schema#comment> "Capza was a lush, tropical planet in the Velcar Free Commerce Zone. It was also home to Commerce Master Commissioner Gregor Raquoran. " .
<https://starwars.com#planet_Capza> <http://telicent.io/ontology/primaryName> "Capza" .
<https://starwars.com#planet_Capza> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89f121aa-3703-45d3-b21c-4f0c3d46d1fa> .
<https://starwars.com#planet_Capza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Velcar> .
<https://starwars.com#sector_Velcar> <http://telicent.io/ontology/primaryName> "Velcar" .
<https://starwars.com#planet_Capza> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#89f121aa-3703-45d3-b21c-4f0c3d46d1fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Capza> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Velcar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#89f121aa-3703-45d3-b21c-4f0c3d46d1fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Capza"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Velcar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

