Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KodaStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#37865e08-d94f-45a2-bef0-5c6251e05c5a> .
<https://starwars.com#planet_KodaStation> <http://telicent.io/ontology/primaryName> "Koda Station" .
<https://starwars.com#planet_KodaStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wazta> .
<https://starwars.com#sector_Wazta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KodaStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Koda Station was a space station located in the Outer Rim Territories, in grid square I-18 on the Standard Galactic Grid. A hyperspace route connected it to the astronomical object Ryoone. Koda Station was pictured on a galactic map included in the book Traveler's Guide to Batuu, which was written by the historian Eloc Throno. " .
<https://starwars.com#sector_Wazta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#37865e08-d94f-45a2-bef0-5c6251e05c5a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Wazta> <http://telicent.io/ontology/primaryName> "Wazta" .
<https://starwars.com#37865e08-d94f-45a2-bef0-5c6251e05c5a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Koda Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KodaStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I18> .
<https://starwars.com#planet_KodaStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

