Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Oyokal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d6684f8e-af8e-412e-8607-2a6340bd548a> .
<https://starwars.com#planet_Oyokal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ChissAscendancy> .
<https://starwars.com#sector_ChissAscendancy> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Oyokal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ChissAscendancy> <http://telicent.io/ontology/primaryName> "Chiss Ascendancy" .
<https://starwars.com#planet_Oyokal> <http://telicent.io/ontology/primaryName> "Oyokal" .
<https://starwars.com#planet_Oyokal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_E8> .
<https://starwars.com#sector_ChissAscendancy> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_UnknownRegions> .
<https://starwars.com#d6684f8e-af8e-412e-8607-2a6340bd548a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Oyokal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d6684f8e-af8e-412e-8607-2a6340bd548a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Oyokal> <http://www.w3.org/2000/01/rdf-schema#comment> "Oyokal was a terrestrial astronomical object in the Unknown Regions and part of the Chiss Ascendancy. It was the homeworld of Senior Captain Xodlak'in'daro 'Lakinda,' where she belonged to a farming community before she joined the Chiss Expansionary Defense Fleet. " .

