Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Indupar> <http://www.w3.org/2000/01/rdf-schema#comment> "Indupar was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_Indupar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ado> .
<https://starwars.com#planet_Indupar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#4f23a5e6-6ec9-4f73-a029-c66162abbd47> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Indupar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Indupar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f23a5e6-6ec9-4f73-a029-c66162abbd47> .
<https://starwars.com#sector_Ado> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Ado> <http://telicent.io/ontology/primaryName> "Ado" .
<https://starwars.com#sector_Ado> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Indupar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M17> .
<https://starwars.com#4f23a5e6-6ec9-4f73-a029-c66162abbd47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Indupar> <http://telicent.io/ontology/primaryName> "Indupar" .

