Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Murk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#planet_Murk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ae87d4a2-fcbc-42f3-992b-74625bee0b3e> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Murk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Murk> <http://telicent.io/ontology/primaryName> "Murk" .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#ae87d4a2-fcbc-42f3-992b-74625bee0b3e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Murk> <http://www.w3.org/2000/01/rdf-schema#comment> "Murk was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It lay on the Sanctuary Pipeline, a hyperspace route that connected the Moddell sector moon of Endor to the Sullust sector planet Sullust. Murk was depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#planet_Murk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .
<https://starwars.com#ae87d4a2-fcbc-42f3-992b-74625bee0b3e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Murk"^^<http://www.w3.org/2001/XMLSchema#string> .

