Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_WannTsir> <http://telicent.io/ontology/primaryName> "Wann Tsir" .
<https://starwars.com#planet_WannTsir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sepan> .
<https://starwars.com#planet_WannTsir> <http://www.w3.org/2000/01/rdf-schema#comment> "Wann Tsir was a planet located in the Wann Tsir system, a part of the Sepan sector in the Slice portion of the Expansion Region. During the Galactic Civil War, Wann Tsir was protected by a planetary shield. " .
<https://starwars.com#planet_WannTsir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#534f3774-ed12-44e5-aa3f-62a1dc52113c> .
<https://starwars.com#planet_WannTsir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P13> .
<https://starwars.com#sector_Sepan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#534f3774-ed12-44e5-aa3f-62a1dc52113c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_WannTsir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#534f3774-ed12-44e5-aa3f-62a1dc52113c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wann Tsir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sepan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Sepan> <http://telicent.io/ontology/primaryName> "Sepan" .

