Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O9> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#06a09fda-6b28-4d10-94c4-28e366b73e05> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Algnadesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#06a09fda-6b28-4d10-94c4-28e366b73e05> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#06a09fda-6b28-4d10-94c4-28e366b73e05> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O9"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O9> <http://telicent.io/ontology/primaryName> "O9" .
<https://starwars.com#planet_Algnadesh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#76939f12-ab45-42f8-a914-3941552d7d03> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Algnadesh"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Algnadesh> <http://telicent.io/ontology/primaryName> "Algnadesh" .
<https://starwars.com#planet_Algnadesh> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#76939f12-ab45-42f8-a914-3941552d7d03> .
<https://starwars.com#planet_Algnadesh> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Algnadesh> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#76939f12-ab45-42f8-a914-3941552d7d03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_O9> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

