Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ploo> <http://telicent.io/ontology/primaryName> "Ploo" .
<https://starwars.com#e97cb37a-b8fd-4452-9a3e-8f01888977b9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ploo> <http://www.w3.org/2000/01/rdf-schema#comment> "Ploo was an astronomical object located in the galaxy's Expansion Region. " .
<https://starwars.com#planet_Ploo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Ploo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ploo> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e97cb37a-b8fd-4452-9a3e-8f01888977b9> .
<https://starwars.com#planet_Ploo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Ploo> .
<https://starwars.com#planet_Ploo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N7> .
<https://starwars.com#sector_Ploo> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Ploo> <http://telicent.io/ontology/primaryName> "Ploo" .
<https://starwars.com#e97cb37a-b8fd-4452-9a3e-8f01888977b9> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ploo"^^<http://www.w3.org/2001/XMLSchema#string> .

