Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dalcretti> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Dalcretti> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e228b93-14f2-480c-a98e-805a467b7ed7> .
<https://starwars.com#planet_Dalcretti> <http://telicent.io/ontology/primaryName> "Dalcretti" .
<https://starwars.com#7e228b93-14f2-480c-a98e-805a467b7ed7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dalcretti"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dalcretti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Dalcretti> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#7e228b93-14f2-480c-a98e-805a467b7ed7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dalcretti> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .

