Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Hyabb> <http://telicent.io/ontology/primaryName> "Hyabb" .
<https://starwars.com#planet_Hyabb> <http://www.w3.org/2000/01/rdf-schema#comment> "Decades before 4050 BBY, both Hyabb and Twith came under the oppression of the Nelori Marauders, a group of bandits that established their base in the Hyabb-Twith Corridor. Due to the hyperlane serving as a no-man's-land zone for the two rival worlds, the Marauders preyed unopposed on both Hyabb and Twith and surrounding star systems. The Republic's Jedi Order eventually defeated the Nelori, freeing both Hyabb and Twith from the outlaws' influence. " .
<https://starwars.com#planet_Hyabb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3c55d2d4-59ed-4577-b036-02f783bbb1f5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hyabb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Hyabb> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Hyabb> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3c55d2d4-59ed-4577-b036-02f783bbb1f5> .
<https://starwars.com#3c55d2d4-59ed-4577-b036-02f783bbb1f5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hyabb"^^<http://www.w3.org/2001/XMLSchema#string> .

