Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_S12> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#193e0dbe-bf4a-4e7e-9a47-85564c1fa0d0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Affavan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S12> <http://telicent.io/ontology/primaryName> "S12" .
<https://starwars.com#bf735611-e45d-4055-965b-b285346e6ac0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_S12> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Affavan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S12> .
<https://starwars.com#193e0dbe-bf4a-4e7e-9a47-85564c1fa0d0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Affavan> <http://telicent.io/ontology/primaryName> "Affavan" .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Affavan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#region_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .
<https://starwars.com#planet_Affavan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#region_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#region_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_Affavan> <http://www.w3.org/2000/01/rdf-schema#comment> "Affavan was a smoggy Hutt Space gambling world that lay on the Hollastin Run hyperlane. During the Kymoodon Era, it was the site of a retaliatory attack by the Belasco Free Volunteers militia on the Utoradii clan of the Hutt species after the latter's forces attempted a raid on the planet Parcovey Minor. Millennia later, Affavan was featured in the holodrama series True Tales of the Ancient Republic, which depicted a fictionalized version of the raid and its aftermath. " .
<https://starwars.com#grid_S12> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#bf735611-e45d-4055-965b-b285346e6ac0> .
<https://starwars.com#bf735611-e45d-4055-965b-b285346e6ac0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S12"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Affavan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#193e0dbe-bf4a-4e7e-9a47-85564c1fa0d0> .

