Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Najarka> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#07d11fdf-8068-4dd8-bd8d-0a7ffe618193> .
<https://starwars.com#sector_Rayter> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Najarka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Rayter> .
<https://starwars.com#planet_Najarka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Najarka> <http://www.w3.org/2000/01/rdf-schema#comment> "Najarka was a planet located in the Outer Rim's Rayter sector. " .
<https://starwars.com#sector_Rayter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#07d11fdf-8068-4dd8-bd8d-0a7ffe618193> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Najarka> <http://telicent.io/ontology/primaryName> "Najarka" .
<https://starwars.com#sector_Rayter> <http://telicent.io/ontology/primaryName> "Rayter" .
<https://starwars.com#planet_Najarka> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J19> .
<https://starwars.com#07d11fdf-8068-4dd8-bd8d-0a7ffe618193> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Najarka"^^<http://www.w3.org/2001/XMLSchema#string> .

