Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Cyborrea> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9db77885-e457-4fc1-b2b8-48d3aebf917f> .
<https://starwars.com#planet_Cyborrea> <http://www.w3.org/2000/01/rdf-schema#comment> "Cyborrea was an astronomical object located in the Outer Rim Territories, within Hutt Space. It was positioned at the coordinates S-9 on the Standard Galactic Grid. " .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cyborrea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Cyborrea> <http://telicent.io/ontology/primaryName> "Cyborrea" .
<https://starwars.com#9db77885-e457-4fc1-b2b8-48d3aebf917f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cyborrea"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#9db77885-e457-4fc1-b2b8-48d3aebf917f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Cyborrea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cyborrea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S9> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

