Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dramassia> <http://telicent.io/ontology/primaryName> "Dramassia" .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#d27c7eb1-43bf-4036-94a0-6552751f79d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dramassia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dramassia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d27c7eb1-43bf-4036-94a0-6552751f79d2> .
<https://starwars.com#planet_Dramassia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#d27c7eb1-43bf-4036-94a0-6552751f79d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dramassia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#planet_Dramassia> <http://www.w3.org/2000/01/rdf-schema#comment> "Dramassia was a planet in the Juvex sector of the Mid Rim, near the Agarix Trade Route. " .
<https://starwars.com#planet_Dramassia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

