Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#cecb95d7-4fb6-4e4f-b2f3-b3b8f746a077> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Manaan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Manaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Manaan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .
<https://starwars.com#cecb95d7-4fb6-4e4f-b2f3-b3b8f746a077> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Manaan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#cecb95d7-4fb6-4e4f-b2f3-b3b8f746a077> .
<https://starwars.com#planet_Manaan> <http://www.w3.org/2000/01/rdf-schema#comment> "Manaan was an ocean planet located in the galaxy's Inner Rim, in grid square O-11 on the Standard Galactic Grid. It was the homeworld of the sentient Selkath species, which had been historically devoted to the care of their native oceans. The Selkath bounty hunters Mantu and Chata Hyoki hailed from Manaan. " .
<https://starwars.com#planet_Manaan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Manaan> <http://telicent.io/ontology/primaryName> "Manaan" .

