Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MakemTe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#planet_MakemTe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MakemTe> <http://telicent.io/ontology/primaryName> "Makem Te" .
<https://starwars.com#sector_Nilgaard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#89ca90d4-f5de-4752-be1d-c168be751813> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MakemTe> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nilgaard> .
<https://starwars.com#planet_MakemTe> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#89ca90d4-f5de-4752-be1d-c168be751813> .
<https://starwars.com#sector_Nilgaard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#89ca90d4-f5de-4752-be1d-c168be751813> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Makem Te"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MakemTe> <http://www.w3.org/2000/01/rdf-schema#comment> "Makem Te was an astronomical object located in the galaxy's Outer Rim Territories that was the homeworld of the Swokes Swokes species. It was located close to one end of the Perlemian Trade Route, which connected it to the planets Quermia and Desevro. " .
<https://starwars.com#sector_Nilgaard> <http://telicent.io/ontology/primaryName> "Nilgaard" .

