Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sanjin> <http://www.w3.org/2000/01/rdf-schema#comment> "Sanjin was a planet that hosted several moons. Some time prior to the mission to Vassek's third moon, Jedi Master Neebo traveled to one of these moons to aid refugees. " .
<https://starwars.com#b19f61f8-cf15-4d0e-b189-e026632f83be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sanjin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M13> .
<https://starwars.com#planet_Sanjin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sanjin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#b19f61f8-cf15-4d0e-b189-e026632f83be> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sanjin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Sanjin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b19f61f8-cf15-4d0e-b189-e026632f83be> .
<https://starwars.com#planet_Sanjin> <http://telicent.io/ontology/primaryName> "Sanjin" .

