Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Muunilinst> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d7f8592-8ae2-486c-8087-994b50375744> .
<https://starwars.com#planet_Muunilinst> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3d7f8592-8ae2-486c-8087-994b50375744> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Muunilinst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Obtrexta> .
<https://starwars.com#sector_Obtrexta> <http://telicent.io/ontology/primaryName> "Obtrexta" .
<https://starwars.com#planet_Muunilinst> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K4> .
<https://starwars.com#sector_Obtrexta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3d7f8592-8ae2-486c-8087-994b50375744> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Muunilinst"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Obtrexta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Muunilinst> <http://www.w3.org/2000/01/rdf-schema#comment> "Muunilinst was a planet located in the galaxy's Outer Rim Territories that was home to a division of the InterGalactic Banking Clan and inhabited by members of the Muun species. It was the site of the Battle of Muunilinst during the Clone Wars, where the Galactic Republic took the planet. " .
<https://starwars.com#planet_Muunilinst> <http://telicent.io/ontology/primaryName> "Muunilinst" .

