Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Torolis> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d09ef71a-6a6c-4318-981f-1233f4727c39> .
<https://starwars.com#sector_Noolian> <http://telicent.io/ontology/primaryName> "Noolian" .
<https://starwars.com#planet_Torolis> <http://www.w3.org/2000/01/rdf-schema#comment> "Torolis was a Bothan colony world located within the Torolis system of the Mid Rim. " .
<https://starwars.com#planet_Torolis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Torolis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q13> .
<https://starwars.com#sector_Noolian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#d09ef71a-6a6c-4318-981f-1233f4727c39> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Torolis> <http://telicent.io/ontology/primaryName> "Torolis" .
<https://starwars.com#sector_Noolian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Torolis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noolian> .
<https://starwars.com#d09ef71a-6a6c-4318-981f-1233f4727c39> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Torolis"^^<http://www.w3.org/2001/XMLSchema#string> .

