Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vassek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I17> .
<https://starwars.com#e0244893-bf7c-4c9d-bcb6-1be27c7129d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vassek"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vassek> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e0244893-bf7c-4c9d-bcb6-1be27c7129d2> .
<https://starwars.com#e0244893-bf7c-4c9d-bcb6-1be27c7129d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Wazta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vassek> <http://telicent.io/ontology/primaryName> "Vassek" .
<https://starwars.com#sector_Wazta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Wazta> <http://telicent.io/ontology/primaryName> "Wazta" .
<https://starwars.com#planet_Vassek> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Wazta> .
<https://starwars.com#planet_Vassek> <http://www.w3.org/2000/01/rdf-schema#comment> "Vassek was a small blue-and-green planet located in the Wazta sector's Vassek system—to which the planet gave its name—of the Outer Rim Territories, at grid square I-17 on the Standard Galactic Grid. Vassek was situated far enough off the Koda Spur hyperspace route that it did not receive many visitors. " .
<https://starwars.com#planet_Vassek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

