Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Shibric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#daa4af0a-edd8-430c-b595-1f055c6922de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Shibric"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Shibric> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Shibric> <http://telicent.io/ontology/primaryName> "Shibric" .
<https://starwars.com#planet_Shibric> <http://www.w3.org/2000/01/rdf-schema#comment> "Shibric was an Inner Rim planet situated on the Hydian Way. The crew of the Hopskip claimed that Shibric was their destination when they were captured by the Galactic Empire. " .
<https://starwars.com#daa4af0a-edd8-430c-b595-1f055c6922de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Shibric> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#daa4af0a-edd8-430c-b595-1f055c6922de> .
<https://starwars.com#planet_Shibric> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .

