Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OrdLithone> <http://telicent.io/ontology/primaryName> "Ord Lithone" .
<https://starwars.com#planet_OrdLithone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_OrdLithone> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#a01f481d-1ee9-41c9-bfcf-1994a01f463f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_OrdLithone> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OrdLithone> <http://www.w3.org/2000/01/rdf-schema#comment> "Ord Lithone was a planet in the Ord Lithone system, part of the Inner Rim. In the years preceding the Clone Wars, it was the site of a Baktoid Armor Workshop droid manufacturing facility. Baktoid left the planet in 22 BBY, intending to move its factories to the Outer Rim Territories. " .
<https://starwars.com#planet_OrdLithone> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a01f481d-1ee9-41c9-bfcf-1994a01f463f> .
<https://starwars.com#a01f481d-1ee9-41c9-bfcf-1994a01f463f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ord Lithone"^^<http://www.w3.org/2001/XMLSchema#string> .

