Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Irishi> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#30aa6911-5186-4887-9715-13ac7fd0a269> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Orinda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Irishi> .
<https://starwars.com#planet_Orinda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#30aa6911-5186-4887-9715-13ac7fd0a269> .
<https://starwars.com#30aa6911-5186-4887-9715-13ac7fd0a269> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Orinda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Orinda> <http://www.w3.org/2000/01/rdf-schema#comment> "Orinda was an astronomical object located in the galaxy's Mid Rim. In the decades after the Galactic Civil War, Orinda was represented in the Galactic Senate by senator Fatil. " .
<https://starwars.com#sector_Irishi> <http://telicent.io/ontology/primaryName> "Irishi" .
<https://starwars.com#planet_Orinda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Orinda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K6> .
<https://starwars.com#sector_Irishi> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Orinda> <http://telicent.io/ontology/primaryName> "Orinda" .

