Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Mendicat> <http://www.w3.org/2000/01/rdf-schema#comment> "Mendicat was a scrap mining and recycling space station that orbited a star within a Wild Space system. The station was located outside the borders of space controlled by the New Republic by 12 ABY. By that date, the individual Sulamar served aboard the station. When he made an error in programming Mendicat's orbital computers, the space station diverted from its previous course and, as a result, fell into the star it was orbiting. " .
<https://starwars.com#planet_Mendicat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mendicat> <http://telicent.io/ontology/primaryName> "Mendicat" .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#06b1a57f-8946-4912-a403-926d8a8160b6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mendicat"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mendicat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#06b1a57f-8946-4912-a403-926d8a8160b6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mendicat> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#06b1a57f-8946-4912-a403-926d8a8160b6> .
<https://starwars.com#planet_Mendicat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I8> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

