Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#54e012c2-bc06-47b8-be59-f54f5580b41a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Esfandia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Esfandia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_I6> .
<https://starwars.com#planet_Esfandia> <http://telicent.io/ontology/primaryName> "Esfandia" .
<https://starwars.com#planet_Esfandia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#54e012c2-bc06-47b8-be59-f54f5580b41a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Esfandia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Esfandia> <http://www.w3.org/2000/01/rdf-schema#comment> "Esfandia was an astronomical object located in Wild Space. " .
<https://starwars.com#planet_Esfandia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#54e012c2-bc06-47b8-be59-f54f5580b41a> .

