Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Rattatak> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2d33ec71-739b-4051-837b-0f16dc66aa68> .
<https://starwars.com#planet_Rattatak> <http://telicent.io/ontology/primaryName> "Rattatak" .
<https://starwars.com#sector_Trilon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rattatak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Trilon> .
<https://starwars.com#2d33ec71-739b-4051-837b-0f16dc66aa68> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rattatak"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Rattatak> <http://www.w3.org/2000/01/rdf-schema#comment> "Rattatak was a mountainous planet located in the galaxy's Outer Rim Territories. After killing the warlords responsible for the death of Jedi Knight Ky Narec, former Jedi Padawan Asajj Ventress ruled Rattatak until she was found and recruited by former Jedi Master Count Dooku, a Sith Lord. " .
<https://starwars.com#planet_Rattatak> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Trilon> <http://telicent.io/ontology/primaryName> "Trilon" .
<https://starwars.com#2d33ec71-739b-4051-837b-0f16dc66aa68> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rattatak> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Trilon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

