Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ktil> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ktil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N9> .
<https://starwars.com#sector_KtilacRegions> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5841c31a-111b-4ae7-915c-e17e2079759f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_KtilacRegions> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Ktil> <http://telicent.io/ontology/primaryName> "Ktil" .
<https://starwars.com#planet_Ktil> <http://www.w3.org/2000/01/rdf-schema#comment> "Ktil was an Inner Rim astronomical object located in the grid square N-9 of the Standard Galactic Grid. " .
<https://starwars.com#5841c31a-111b-4ae7-915c-e17e2079759f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ktil"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ktil> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5841c31a-111b-4ae7-915c-e17e2079759f> .
<https://starwars.com#sector_KtilacRegions> <http://telicent.io/ontology/primaryName> "Ktilac Regions" .
<https://starwars.com#planet_Ktil> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_KtilacRegions> .

