Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_ErKit> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Noonian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#7e378cca-f87b-48fa-b905-f44f955a94fc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ErKit> <http://telicent.io/ontology/primaryName> "Er'Kit" .
<https://starwars.com#planet_ErKit> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7e378cca-f87b-48fa-b905-f44f955a94fc> .
<https://starwars.com#sector_Noonian> <http://telicent.io/ontology/primaryName> "Noonian" .
<https://starwars.com#planet_ErKit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M6> .
<https://starwars.com#7e378cca-f87b-48fa-b905-f44f955a94fc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Er'Kit"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ErKit> <http://www.w3.org/2000/01/rdf-schema#comment> "Er'Kit was a desert planet located in the galaxy's Outer Rim Territories. It was the homeworld of the Er'Kit species. Before the outbreak of the Clone Wars, Er'Kit senator Danry Ledwellow took bribes from Thalassian slavers, allowing them to use his planet for their illicit activities in exchange for a private army of IG-227 Hailfire-class droid tanks. " .
<https://starwars.com#planet_ErKit> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Noonian> .
<https://starwars.com#sector_Noonian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

