Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Troska> <http://telicent.io/ontology/primaryName> "Troska" .
<https://starwars.com#b4411a4a-038f-439c-85e3-97aa25efc3f1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Troska> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Troska> <http://www.w3.org/2000/01/rdf-schema#comment> "Troska was a forested planet located within the Troska system of the Outer Rim Territories. " .
<https://starwars.com#sector_Dantus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Troska> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b4411a4a-038f-439c-85e3-97aa25efc3f1> .
<https://starwars.com#sector_Dantus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Troska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#b4411a4a-038f-439c-85e3-97aa25efc3f1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Troska"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Troska> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dantus> .
<https://starwars.com#sector_Dantus> <http://telicent.io/ontology/primaryName> "Dantus" .

