Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LittleCapella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#94ef66f3-0e60-41bc-89d2-e694a882aa2e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Little Capella"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_LittleCapella> <http://www.w3.org/2000/01/rdf-schema#comment> "Little Capella was a planet in the Little Capella system in the Gordian Reach, a region in the Outer Rim Territories. In 2 ABY, the company Rapora Mining operated the Rapora Mining Center on Little Capella as one of many new facilities throughout the Outer Rim. " .
<https://starwars.com#planet_LittleCapella> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_LittleCapella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q6> .
<https://starwars.com#94ef66f3-0e60-41bc-89d2-e694a882aa2e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_LittleCapella> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#94ef66f3-0e60-41bc-89d2-e694a882aa2e> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_LittleCapella> <http://telicent.io/ontology/primaryName> "Little Capella" .

