Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Carrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Gelda> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Gelda> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Gelda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#planet_Gelda> <http://telicent.io/ontology/primaryName> "Gelda" .
<https://starwars.com#sector_Carrion> <http://telicent.io/ontology/primaryName> "Carrion" .
<https://starwars.com#d812226d-9379-488b-8184-68ca37f0ac34> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Gelda> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d812226d-9379-488b-8184-68ca37f0ac34> .
<https://starwars.com#d812226d-9379-488b-8184-68ca37f0ac34> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Gelda"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Carrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Gelda> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Carrion> .

