Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b8e25dce-2de2-4c05-a65f-4fe955250cdf> <http://ies.data.gov.uk/ontology/ies4#representationValue> "L20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_L20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Subterrel> <http://telicent.io/ontology/primaryName> "Subterrel" .
<https://starwars.com#grid_L20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#b8e25dce-2de2-4c05-a65f-4fe955250cdf> .
<https://starwars.com#sector_Subterrel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#b2089d07-3d60-448a-8232-ccacf9d82cba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Besberra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Besberra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2089d07-3d60-448a-8232-ccacf9d82cba> .
<https://starwars.com#planet_Besberra> <http://telicent.io/ontology/primaryName> "Besberra" .
<https://starwars.com#sector_Subterrel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Besberra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Subterrel> .
<https://starwars.com#b2089d07-3d60-448a-8232-ccacf9d82cba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Besberra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_L20> <http://telicent.io/ontology/primaryName> "L20" .
<https://starwars.com#planet_Besberra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L20> .
<https://starwars.com#grid_L20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#b8e25dce-2de2-4c05-a65f-4fe955250cdf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Besberra> <http://www.w3.org/2000/01/rdf-schema#comment> "Besberra was an astronomical object located in the Besberra system in the Cegul sector of the Outer Rim Territories. It hosted a gladiatorial arena where the Houk gladiator Torog fought to the death. " .

