Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tolemses> <http://telicent.io/ontology/primaryName> "Tolemses" .
<https://starwars.com#planet_Dica> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Dica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tolemses> .
<https://starwars.com#sector_Tolemses> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Dica> <http://www.w3.org/2000/01/rdf-schema#comment> "Dica was a toxic wasteland of a planet where Qymaen jai Sheelal, better known as General Grievous, was believed to have murdered a Dark Jedi who carried Bane's Heart. " .
<https://starwars.com#planet_Dica> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P11> .
<https://starwars.com#planet_Dica> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#de2a81c8-6a3d-4323-b3fb-064c9024e55b> .
<https://starwars.com#de2a81c8-6a3d-4323-b3fb-064c9024e55b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dica"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dica> <http://telicent.io/ontology/primaryName> "Dica" .
<https://starwars.com#de2a81c8-6a3d-4323-b3fb-064c9024e55b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tolemses> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .

