Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tharin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_JunkfortStation> <http://telicent.io/ontology/primaryName> "Junkfort Station" .
<https://starwars.com#planet_JunkfortStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Junkfort Station was an Outer Rim Territories astronomical object. At some point, the smuggler Platt Okeefe mentioned Junkfort Station in an entry she made in the book known as the Smuggler's Guide, and an individual on the celestial body at one point claimed to have completed the Kessel Run smuggling route by traveling less than eleven parsecs. " .
<https://starwars.com#sector_Tharin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_JunkfortStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#43b4ff7e-f5a5-4df3-8aec-adeeca043f25> .
<https://starwars.com#planet_JunkfortStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_JunkfortStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#planet_JunkfortStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tharin> .
<https://starwars.com#43b4ff7e-f5a5-4df3-8aec-adeeca043f25> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Junkfort Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tharin> <http://telicent.io/ontology/primaryName> "Tharin" .
<https://starwars.com#43b4ff7e-f5a5-4df3-8aec-adeeca043f25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

