Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Carida> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2c0cb9ae-a619-4096-a36a-18a533a66b24> .
<https://starwars.com#planet_Carida> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Carida> <http://telicent.io/ontology/primaryName> "Carida" .
<https://starwars.com#planet_Carida> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Carida> <http://www.w3.org/2000/01/rdf-schema#comment> "Carida was a mountainous planet located in the Carida system within the Colonies region of the galaxy. During the Clone Wars, the Valor space station orbited the planet, while the era of the Galactic Empire saw Carida as home to an Imperial academy and a naval docking facility. " .
<https://starwars.com#2c0cb9ae-a619-4096-a36a-18a533a66b24> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2c0cb9ae-a619-4096-a36a-18a533a66b24> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carida"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Carida> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .

