Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Astal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#8984f433-a31a-4707-abb4-5c1244d619b8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bahalian"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bahalian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8984f433-a31a-4707-abb4-5c1244d619b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Bahalian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Astal> .
<https://starwars.com#sector_Astal> <http://telicent.io/ontology/primaryName> "Astal" .
<https://starwars.com#planet_Bahalian> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8984f433-a31a-4707-abb4-5c1244d619b8> .
<https://starwars.com#planet_Bahalian> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Astal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Bahalian> <http://telicent.io/ontology/primaryName> "Bahalian" .
<https://starwars.com#planet_Bahalian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P18> .

