Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Huloon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Huloon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#8ae27bab-939a-4237-a207-1647ee5cff01> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Huloon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Huloon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Huloon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8ae27bab-939a-4237-a207-1647ee5cff01> .
<https://starwars.com#planet_Huloon> <http://telicent.io/ontology/primaryName> "Huloon" .
<https://starwars.com#8ae27bab-939a-4237-a207-1647ee5cff01> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Huloon> <http://www.w3.org/2000/01/rdf-schema#comment> "Huloon was a planet located in the Huloon system within Bootana Hutta near the center of Hutt Space. A part of Hutt Space, it was formerly the home to a slave species also called Huloons before it was depopulated by the Hutts and turned into a nature preserve. After the massacre, pockets of Huloons resided in systems near their homeworld and yearned to return, but they would often suffer ridicule and torment at the hands of the Hutts. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

