Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Qhulosk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Qhulosk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T8> .
<https://starwars.com#02f0cb95-e31a-4b3a-8be0-0e04474eb4fe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#02f0cb95-e31a-4b3a-8be0-0e04474eb4fe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Qhulosk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Qhulosk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02f0cb95-e31a-4b3a-8be0-0e04474eb4fe> .
<https://starwars.com#planet_Qhulosk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Qhulosk> <http://telicent.io/ontology/primaryName> "Qhulosk" .

