Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vindalia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vindalia> <http://www.w3.org/2000/01/rdf-schema#comment> "Vindalia was a planet located within the Vindalia system of the Colonies and the homeworld of the Vindalian species. " .
<https://starwars.com#planet_Vindalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Vindalia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Vindalia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0df517d8-9041-45ab-ada0-beae12027068> .
<https://starwars.com#0df517d8-9041-45ab-ada0-beae12027068> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vindalia> <http://telicent.io/ontology/primaryName> "Vindalia" .
<https://starwars.com#0df517d8-9041-45ab-ada0-beae12027068> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vindalia"^^<http://www.w3.org/2001/XMLSchema#string> .

