Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Terrskiar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NewApsolon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Terrskiar> .
<https://starwars.com#sector_Terrskiar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_NewApsolon> <http://www.w3.org/2000/01/rdf-schema#comment> "New Apsolon was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#planet_NewApsolon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#a27edc50-44a4-43ae-a5ed-aab6d2d8c670> <http://ies.data.gov.uk/ontology/ies4#representationValue> "New Apsolon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NewApsolon> <http://telicent.io/ontology/primaryName> "New Apsolon" .
<https://starwars.com#sector_Terrskiar> <http://telicent.io/ontology/primaryName> "Terr'skiar" .
<https://starwars.com#a27edc50-44a4-43ae-a5ed-aab6d2d8c670> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NewApsolon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a27edc50-44a4-43ae-a5ed-aab6d2d8c670> .
<https://starwars.com#planet_NewApsolon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .

