Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Chitarghar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Chitarghar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Solibus> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#78c424cc-2042-4b48-8e3d-0bb0c2363515> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#78c424cc-2042-4b48-8e3d-0bb0c2363515> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Solibus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Solibus> <http://telicent.io/ontology/primaryName> "Solibus" .
<https://starwars.com#planet_Solibus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K15> .
<https://starwars.com#planet_Solibus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Chitarghar> <http://telicent.io/ontology/primaryName> "Chitarghar" .
<https://starwars.com#planet_Solibus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Chitarghar> .
<https://starwars.com#planet_Solibus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#78c424cc-2042-4b48-8e3d-0bb0c2363515> .

