Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_FesweMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P5> .
<https://starwars.com#planet_FesweMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#dc4fc323-5bff-428e-9453-3cafdee33345> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_FesweMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dc4fc323-5bff-428e-9453-3cafdee33345> .
<https://starwars.com#planet_FesweMinor> <http://telicent.io/ontology/primaryName> "Feswe Minor" .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_FesweMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_FesweMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#dc4fc323-5bff-428e-9453-3cafdee33345> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Feswe Minor"^^<http://www.w3.org/2001/XMLSchema#string> .

