Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Hertae> <http://telicent.io/ontology/primaryName> "Hertae" .
<https://starwars.com#sector_Hertae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_NexusOrtai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#bb79dcf4-0184-444a-ae01-4c31120df2bc> .
<https://starwars.com#planet_NexusOrtai> <http://www.w3.org/2000/01/rdf-schema#comment> "Nexus Ortai was an astronomical object located in the galaxy's Mid Rim. " .
<https://starwars.com#bb79dcf4-0184-444a-ae01-4c31120df2bc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NexusOrtai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hertae> .
<https://starwars.com#planet_NexusOrtai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#bb79dcf4-0184-444a-ae01-4c31120df2bc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nexus Ortai"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NexusOrtai> <http://telicent.io/ontology/primaryName> "Nexus Ortai" .
<https://starwars.com#sector_Hertae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_NexusOrtai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q14> .

