Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#153564fa-1b50-4023-ac0e-6a7ca1bb6b3b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Rhelg"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Rhelg> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#153564fa-1b50-4023-ac0e-6a7ca1bb6b3b> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Rhelg> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Rhelg> <http://telicent.io/ontology/primaryName> "Rhelg" .
<https://starwars.com#planet_Rhelg> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#153564fa-1b50-4023-ac0e-6a7ca1bb6b3b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Rhelg> <http://www.w3.org/2000/01/rdf-schema#comment> "Rhelg was a noteworthy world affiliated with the Sith. In the time of the Galactic Republic, Rhelg was quarantined along with other planets like Malachor, Ziost, and Jaguada, and its history and Sith affiliation was hidden. Some of the Sith worlds that were quarantined had their ancient Sith affiliation hidden so thoroughly that the modern inhabits of the planets were not aware of their history and encountered ancient battlegrounds and sacred temples completely unaware of their Sith history. " .
<https://starwars.com#planet_Rhelg> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .

