Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#6a59f7ea-c74f-4400-8786-072db4c4028b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Osadia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6a59f7ea-c74f-4400-8786-072db4c4028b> .
<https://starwars.com#planet_Osadia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#6a59f7ea-c74f-4400-8786-072db4c4028b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Osadia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Osadia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Osadia> <http://telicent.io/ontology/primaryName> "Osadia" .
<https://starwars.com#planet_Osadia> <http://www.w3.org/2000/01/rdf-schema#comment> "Osadia was a planet located within the Core Worlds. Its location was kept secret and removed off the star-charts so that the mysterious school that was located there could not be disturbed. " .

