Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sharlissia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Sharlissia> <http://www.w3.org/2000/01/rdf-schema#comment> "Sharlissia was an astronomical object located in the Outer Rim Territories and Trailing Sectors regions, in grid square N-18 of the Standard Galactic Grid. A hyperspace route linked it to the celestial body Kabal. " .
<https://starwars.com#943eec09-00a1-44cd-8f1d-98efd75cf3fa> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sharlissia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Bonnyuw-Luq> <http://telicent.io/ontology/primaryName> "Bon'nyuw-Luq" .
<https://starwars.com#sector_Bonnyuw-Luq> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Bonnyuw-Luq> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sharlissia> <http://telicent.io/ontology/primaryName> "Sharlissia" .
<https://starwars.com#planet_Sharlissia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N18> .
<https://starwars.com#planet_Sharlissia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bonnyuw-Luq> .
<https://starwars.com#planet_Sharlissia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#943eec09-00a1-44cd-8f1d-98efd75cf3fa> .
<https://starwars.com#943eec09-00a1-44cd-8f1d-98efd75cf3fa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

