Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4bf71615-0ab4-4e0d-b169-e74ce3920d91> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Millinar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Millinar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#4bf71615-0ab4-4e0d-b169-e74ce3920d91> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Millinar> <http://www.w3.org/2000/01/rdf-schema#comment> "Millinar was an elusive planet believed to be only a myth by the galaxy at large. The myth of Millinar was often compared to those of the Lost City of the Jedi and the Valley of the Jedi. The 'mythic' planet was actually located in the Interior Region of the Hapes Cluster, a region which itself had become almost legendary by the era of the Galactic Civil War. " .
<https://starwars.com#planet_Millinar> <http://telicent.io/ontology/primaryName> "Millinar" .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Millinar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Millinar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4bf71615-0ab4-4e0d-b169-e74ce3920d91> .
<https://starwars.com#planet_Millinar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .

