Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Calamari> <http://telicent.io/ontology/primaryName> "Calamari" .
<https://starwars.com#planet_Ruisto> <http://telicent.io/ontology/primaryName> "Ruisto" .
<https://starwars.com#2dd63eb0-ad53-4c18-b2ae-67a9c677e602> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ruisto> <http://www.w3.org/2000/01/rdf-schema#comment> "Ruisto was a planet located in the Calamari sector of the Outer Rim Territories. " .
<https://starwars.com#planet_Ruisto> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ruisto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calamari> .
<https://starwars.com#sector_Calamari> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ruisto> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U6> .
<https://starwars.com#2dd63eb0-ad53-4c18-b2ae-67a9c677e602> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ruisto"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calamari> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ruisto> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2dd63eb0-ad53-4c18-b2ae-67a9c677e602> .

