Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ession> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Ession> <http://www.w3.org/2000/01/rdf-schema#comment> "Ession was a planet in the Corporate Sector, located at the nexus of the Shaltin Tunnels and Lucaya Cross hyperlanes. It was settled around 4000 BBY. An industrial manufacturing center, it was the headquarters of Pakkerd Light Transport, formerly a division of Sienar Fleet Systems. " .
<https://starwars.com#planet_Ession> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#64db87cd-642e-44db-a233-da1c9816d113> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ession> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#64db87cd-642e-44db-a233-da1c9816d113> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ession> <http://telicent.io/ontology/primaryName> "Ession" .
<https://starwars.com#planet_Ession> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#64db87cd-642e-44db-a233-da1c9816d113> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ession"^^<http://www.w3.org/2001/XMLSchema#string> .

