Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Aridus> <http://www.w3.org/2000/01/rdf-schema#comment> "Aridus was a planet located in the galaxy's Expansion Region. During the Clone Wars, it was under Separatist control and Republic High Command sent at least one commando squad to Aridus in hopes of coordinating with local freedom fighters. " .
<https://starwars.com#planet_Aridus> <http://telicent.io/ontology/primaryName> "Aridus" .
<https://starwars.com#planet_Aridus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3d5970a9-a7a9-4461-ac81-23b398f697d3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Narvath> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Narvath> <http://telicent.io/ontology/primaryName> "Narvath" .
<https://starwars.com#planet_Aridus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#planet_Aridus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Narvath> .
<https://starwars.com#3d5970a9-a7a9-4461-ac81-23b398f697d3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aridus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aridus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3d5970a9-a7a9-4461-ac81-23b398f697d3> .
<https://starwars.com#sector_Narvath> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

