Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dohlban> <http://www.w3.org/2000/01/rdf-schema#comment> "Dohlban was a terrestrial planet located in the Dohlban system, a part of the Dohlbani sector in the Slice portion of the Mid Rim. The Kaaga Run hyperlane connected it to the Void Station in the Bothan sector and the Nar Kaaga system in Hutt Space. " .
<https://starwars.com#sector_Dohlbani> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Dohlban> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3e931e16-4f7f-4b20-bec5-28ab50dde3f5> .
<https://starwars.com#3e931e16-4f7f-4b20-bec5-28ab50dde3f5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dohlban"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_R13> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#dd60a22a-dabf-4474-803f-09d6fc9a45a1> .
<https://starwars.com#planet_Dohlban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R13> .
<https://starwars.com#grid_R13> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Dohlbani> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#3e931e16-4f7f-4b20-bec5-28ab50dde3f5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#dd60a22a-dabf-4474-803f-09d6fc9a45a1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R13"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_R13> <http://telicent.io/ontology/primaryName> "R13" .
<https://starwars.com#planet_Dohlban> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_R13> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Dohlban> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Dohlbani> .
<https://starwars.com#dd60a22a-dabf-4474-803f-09d6fc9a45a1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Dohlbani> <http://telicent.io/ontology/primaryName> "Dohlbani" .
<https://starwars.com#planet_Dohlban> <http://telicent.io/ontology/primaryName> "Dohlban" .

