Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Vulpter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#f2b6c6ee-2d9a-42f1-bead-fcfcc3e0b507> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vulpter"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#f2b6c6ee-2d9a-42f1-bead-fcfcc3e0b507> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Vulpter> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vulpter> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Vulpter> <http://telicent.io/ontology/primaryName> "Vulpter" .
<https://starwars.com#planet_Vulpter> <http://www.w3.org/2000/01/rdf-schema#comment> "Vulpter was a planet located in the galaxy's Deep Core that was the homeworld of the Vulptereen podracer Dud Bolt. The KX-series security droid K-2SO was constructed on Vulpter, as were many of the Galactic Empire's probe droids. " .
<https://starwars.com#planet_Vulpter> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f2b6c6ee-2d9a-42f1-bead-fcfcc3e0b507> .

