Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#0682afe2-d311-4322-aa73-0a777c53f364> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Carest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Carest> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0682afe2-d311-4322-aa73-0a777c53f364> .
<https://starwars.com#planet_Carest> <http://telicent.io/ontology/primaryName> "Carest" .
<https://starwars.com#planet_Carest> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Carest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#0682afe2-d311-4322-aa73-0a777c53f364> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carest"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Carest> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .

