Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Kattada> <http://www.w3.org/2000/01/rdf-schema#comment> "Kattada was an astronomical object located in the galaxy's Colonies region. It shared its name with Kattadan rosé, an intoxicating beverage. " .
<https://starwars.com#planet_Kattada> <http://telicent.io/ontology/primaryName> "Kattada" .
<https://starwars.com#1b472be0-5f2b-472b-9f16-09aeaa7b6c4c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Kattada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Kattada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Kattada> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1b472be0-5f2b-472b-9f16-09aeaa7b6c4c> .
<https://starwars.com#planet_Kattada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1b472be0-5f2b-472b-9f16-09aeaa7b6c4c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kattada"^^<http://www.w3.org/2001/XMLSchema#string> .

