Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_FreestandingSubsectors> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_FreestandingSubsectors> <http://telicent.io/ontology/primaryName> "Freestanding Subsectors" .
<https://starwars.com#planet_Poviduze> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J14> .
<https://starwars.com#planet_Poviduze> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Poviduze> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#12e4667e-9428-4d65-b1a6-2cdfd22400db> .
<https://starwars.com#planet_Poviduze> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_FreestandingSubsectors> .
<https://starwars.com#planet_Poviduze> <http://www.w3.org/2000/01/rdf-schema#comment> "The Poviduze system was a star system located in the Expansion Region. " .
<https://starwars.com#12e4667e-9428-4d65-b1a6-2cdfd22400db> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_FreestandingSubsectors> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#12e4667e-9428-4d65-b1a6-2cdfd22400db> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Poviduze"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Poviduze> <http://telicent.io/ontology/primaryName> "Poviduze" .

