Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dargulli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#ba69616b-4269-44ab-8352-9e91c9145ce7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Dargulli> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ba69616b-4269-44ab-8352-9e91c9145ce7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dargulli"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dargulli> <http://telicent.io/ontology/primaryName> "Dargulli" .
<https://starwars.com#planet_Dargulli> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ba69616b-4269-44ab-8352-9e91c9145ce7> .
<https://starwars.com#planet_Dargulli> <http://www.w3.org/2000/01/rdf-schema#comment> "Dargulli was an astronomical object located in the galaxy's Inner Rim. " .
<https://starwars.com#planet_Dargulli> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .

