Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#b12b1781-fb91-4815-9f12-a643507e0ba3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Hratth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Hratth> <http://telicent.io/ontology/primaryName> "H'ratth" .
<https://starwars.com#planet_Hratth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N10> .
<https://starwars.com#b12b1781-fb91-4815-9f12-a643507e0ba3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H'ratth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hratth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b12b1781-fb91-4815-9f12-a643507e0ba3> .
<https://starwars.com#planet_Hratth> <http://www.w3.org/2000/01/rdf-schema#comment> "H'ratth was a lush planet with a Jedi Academy where Jedi Master Chamma taught Andur Sunrider the Jedi ways in 4001 BBY. It was the homeworld of Vima Sunrider. The academy was known for its training of Jedi healers. " .
<https://starwars.com#planet_Hratth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

