Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Mytaranor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#f8bcb50e-89c8-46a6-825d-ccf5056270e3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kashyyyk"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kashyyyk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f8bcb50e-89c8-46a6-825d-ccf5056270e3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Mytaranor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Kashyyyk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P9> .
<https://starwars.com#planet_Kashyyyk> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mytaranor> .
<https://starwars.com#planet_Kashyyyk> <http://www.w3.org/2000/01/rdf-schema#comment> "Forest planet and home of the Wookiees. Also the site of one of the final battles of the Clone Wars." .
<https://starwars.com#sector_Mytaranor> <http://telicent.io/ontology/primaryName> "Mytaranor" .
<https://starwars.com#planet_Kashyyyk> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f8bcb50e-89c8-46a6-825d-ccf5056270e3> .
<https://starwars.com#planet_Kashyyyk> <http://telicent.io/ontology/primaryName> "Kashyyyk" .

