Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Varristad> <http://www.w3.org/2000/01/rdf-schema#comment> "Varristad was a small mining planet located in the Varristad system within the Abrion sector of the Outer Rim Territories. " .
<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#95350cad-5cd5-400a-9ca0-627b024bf35a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Varristad"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Varristad> <http://telicent.io/ontology/primaryName> "Varristad" .
<https://starwars.com#planet_Varristad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Varristad> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95350cad-5cd5-400a-9ca0-627b024bf35a> .
<https://starwars.com#95350cad-5cd5-400a-9ca0-627b024bf35a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#planet_Varristad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Varristad> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .

