Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d734091b-5c94-4f53-967c-7ee65277b5ae> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J10"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#0dd33c28-76a5-4fdb-bdae-03cbb41376d1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J10> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#0dd33c28-76a5-4fdb-bdae-03cbb41376d1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kokash"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Kokash> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J10> .
<https://starwars.com#grid_J10> <http://telicent.io/ontology/primaryName> "J10" .
<https://starwars.com#planet_Kokash> <http://telicent.io/ontology/primaryName> "Kokash" .
<https://starwars.com#grid_J10> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Kokash> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Kokash> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Kokash> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_J10> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#d734091b-5c94-4f53-967c-7ee65277b5ae> .
<https://starwars.com#planet_Kokash> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0dd33c28-76a5-4fdb-bdae-03cbb41376d1> .
<https://starwars.com#d734091b-5c94-4f53-967c-7ee65277b5ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .

