Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Farrfin> <http://www.w3.org/2000/01/rdf-schema#comment> "Farrfin was the capital of Farrfin sector and the Farghul homeworld. It joined the Galactic Republic in 3000 BBY. It was a haven for criminals. A shakedown by the Jedi left the Farghul distrustful of Jedi. " .
<https://starwars.com#planet_Farrfin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#26a0dd87-3502-460b-a86b-75f931dfa0de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Farrfin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Farrfin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#26a0dd87-3502-460b-a86b-75f931dfa0de> .
<https://starwars.com#planet_Farrfin> <http://telicent.io/ontology/primaryName> "Farrfin" .
<https://starwars.com#planet_Farrfin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Farrfin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#26a0dd87-3502-460b-a86b-75f931dfa0de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

