Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_J20> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#38e6326c-8abe-4c68-8f0b-123fd592bc1a> .
<https://starwars.com#grid_J20> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Anoth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#da0949c8-8cf6-4fe0-8ccf-93d40b7b0202> .
<https://starwars.com#38e6326c-8abe-4c68-8f0b-123fd592bc1a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Anoth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#da0949c8-8cf6-4fe0-8ccf-93d40b7b0202> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_J20> <http://telicent.io/ontology/primaryName> "J20" .
<https://starwars.com#planet_Anoth> <http://telicent.io/ontology/primaryName> "Anoth" .
<https://starwars.com#grid_J20> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Anoth> <http://www.w3.org/2000/01/rdf-schema#comment> "Anoth was an astronomical object located in the Wild Space region of the galaxy, positioned at the coordinates J-20 on the Standard Galactic Grid. " .
<https://starwars.com#planet_Anoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Anoth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J20> .
<https://starwars.com#38e6326c-8abe-4c68-8f0b-123fd592bc1a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J20"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#da0949c8-8cf6-4fe0-8ccf-93d40b7b0202> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Anoth"^^<http://www.w3.org/2001/XMLSchema#string> .

