Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_GhostNebula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Umbara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GhostNebula> .
<https://starwars.com#planet_Umbara> <http://www.w3.org/2000/01/rdf-schema#comment> "Planet with a thick, foggy atmosphere. Home to the Umbarans." .
<https://starwars.com#planet_Umbara> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P10> .
<https://starwars.com#9c0e2d60-f3e2-49ca-92c9-b0b7b5433c8c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#9c0e2d60-f3e2-49ca-92c9-b0b7b5433c8c> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Umbara"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_GhostNebula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Umbara> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Umbara> <http://telicent.io/ontology/primaryName> "Umbara" .
<https://starwars.com#sector_GhostNebula> <http://telicent.io/ontology/primaryName> "Ghost Nebula" .
<https://starwars.com#planet_Umbara> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#9c0e2d60-f3e2-49ca-92c9-b0b7b5433c8c> .

