Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_S15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#58b7fc54-f630-4db0-b05d-6043e2dbf149> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Hishyim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Abrion> .
<https://starwars.com#58b7fc54-f630-4db0-b05d-6043e2dbf149> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Abrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Hishyim> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Hishyim> <http://telicent.io/ontology/primaryName> "Hishyim" .
<https://starwars.com#planet_Hishyim> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S15> .
<https://starwars.com#planet_Hishyim> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#02222456-adab-4418-a011-d036eda3eef7> .
<https://starwars.com#grid_S15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#58b7fc54-f630-4db0-b05d-6043e2dbf149> .
<https://starwars.com#planet_Hishyim> <http://www.w3.org/2000/01/rdf-schema#comment> "Hishyim was a planet covered by a vast desert, located in the Abrion sector of the Outer Rim Territories. " .
<https://starwars.com#grid_S15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#02222456-adab-4418-a011-d036eda3eef7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hishyim"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Abrion> <http://telicent.io/ontology/primaryName> "Abrion" .
<https://starwars.com#grid_S15> <http://telicent.io/ontology/primaryName> "S15" .
<https://starwars.com#sector_Abrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#02222456-adab-4418-a011-d036eda3eef7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

