Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Carrion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#3b068bb9-47e2-452f-b5e7-f3a58c1aedc1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Delephr> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3b068bb9-47e2-452f-b5e7-f3a58c1aedc1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Delephr"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Delephr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Carrion> .
<https://starwars.com#planet_Delephr> <http://telicent.io/ontology/primaryName> "Delephr" .
<https://starwars.com#sector_Carrion> <http://telicent.io/ontology/primaryName> "Carrion" .
<https://starwars.com#planet_Delephr> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Delephr> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3b068bb9-47e2-452f-b5e7-f3a58c1aedc1> .
<https://starwars.com#planet_Delephr> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#sector_Carrion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

