Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Selab> <http://www.w3.org/2000/01/rdf-schema#comment> "Selab was a planet in the Hapes Cluster famed for its trees of wisdom. The crystal domes on the Star Home came from Selab. " .
<https://starwars.com#planet_Selab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Selab> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Selab> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#67b88b99-7676-4029-bd08-e798969f8300> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Selab> <http://telicent.io/ontology/primaryName> "Selab" .
<https://starwars.com#planet_Selab> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#67b88b99-7676-4029-bd08-e798969f8300> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#67b88b99-7676-4029-bd08-e798969f8300> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Selab"^^<http://www.w3.org/2001/XMLSchema#string> .

