Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_S18> <http://telicent.io/ontology/primaryName> "S18" .
<https://starwars.com#grid_S18> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#ff9de0a8-1b9c-4923-ae04-29dec9ee236d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S18"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lamaredd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lamaredd> <http://www.w3.org/2000/01/rdf-schema#comment> "Lamaredd was a location in the galaxy where the Quarren pirate Isquik Tors was active prior to his capture by the bounty hunter Boba Fett in 7972 C.R.C. Imperial Security Bureau agent Andressa Divo mentioned Lamaredd while writing to her father Tanivos Divo about Tors's capture. " .
<https://starwars.com#ff9de0a8-1b9c-4923-ae04-29dec9ee236d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Lamaredd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#grid_S18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#ae1c8858-b191-4a2b-b5fe-97cb19531995> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#grid_S18> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#ff9de0a8-1b9c-4923-ae04-29dec9ee236d> .
<https://starwars.com#ae1c8858-b191-4a2b-b5fe-97cb19531995> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lamaredd"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lamaredd> <http://telicent.io/ontology/primaryName> "Lamaredd" .
<https://starwars.com#planet_Lamaredd> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S18> .
<https://starwars.com#planet_Lamaredd> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ae1c8858-b191-4a2b-b5fe-97cb19531995> .

