Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Hertae> <http://telicent.io/ontology/primaryName> "Hertae" .
<https://starwars.com#sector_Hertae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Masterra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hertae> .
<https://starwars.com#planet_Masterra> <http://telicent.io/ontology/primaryName> "Masterra" .
<https://starwars.com#planet_Masterra> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#abbbbac9-ebaf-49ce-80e8-73c33de62418> .
<https://starwars.com#abbbbac9-ebaf-49ce-80e8-73c33de62418> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Masterra"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Masterra> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q14> .
<https://starwars.com#planet_Masterra> <http://www.w3.org/2000/01/rdf-schema#comment> "Masterra, originally known as Ord Masterra, was a planet in the Hertae sector of the Mid Rim. " .
<https://starwars.com#sector_Hertae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Masterra> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#abbbbac9-ebaf-49ce-80e8-73c33de62418> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

