Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Eamus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#083380e1-1f99-41c5-b94e-24f3708bb334> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eamus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Eamus> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#083380e1-1f99-41c5-b94e-24f3708bb334> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Eamus> <http://telicent.io/ontology/primaryName> "Eamus" .
<https://starwars.com#planet_Eamus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Eamus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Eamus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#083380e1-1f99-41c5-b94e-24f3708bb334> .

