Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ammuud> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#grid_S4> <http://telicent.io/ontology/primaryName> "S4" .
<https://starwars.com#093e935c-a787-47cf-84a6-a2d767ef1a03> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Ammuud> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Ammuud> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#256f882c-2635-4211-8728-0774c54b4238> .
<https://starwars.com#grid_S4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#093e935c-a787-47cf-84a6-a2d767ef1a03> .
<https://starwars.com#256f882c-2635-4211-8728-0774c54b4238> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Ammuud> <http://telicent.io/ontology/primaryName> "Ammuud" .
<https://starwars.com#093e935c-a787-47cf-84a6-a2d767ef1a03> <http://ies.data.gov.uk/ontology/ies4#representationValue> "S4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_S4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#256f882c-2635-4211-8728-0774c54b4238> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ammuud"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ammuud> <http://www.w3.org/2000/01/rdf-schema#comment> "Ammuud was a cold planet located in the semi-independent Corporate Sector of the galaxy's Outer Rim Territories. The planet saw decades of fighting between its seven resident family clans, who eventually united to govern Ammuud under the Code of Ammuud. " .
<https://starwars.com#planet_Ammuud> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_S4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .

