Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Chorax> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d9881dd0-c65e-464c-b9a3-2a30822356e2> .
<https://starwars.com#planet_Chorax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N11> .
<https://starwars.com#planet_Chorax> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Chorax> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Chorax> <http://telicent.io/ontology/primaryName> "Chorax" .
<https://starwars.com#d9881dd0-c65e-464c-b9a3-2a30822356e2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Chorax"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Chorax> <http://www.w3.org/2000/01/rdf-schema#comment> "Chorax was a planet in the Rachuk sector, which lay between Commenor and Talasea. It was the sole planet of the Chorax system, a haven for pirates and smugglers. " .
<https://starwars.com#d9881dd0-c65e-464c-b9a3-2a30822356e2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

