Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_MalrevIV> <http://www.w3.org/2000/01/rdf-schema#comment> " Malrev IV was a planet located in the Thrasybule sector of the Outer Rim Territories. Its history was strongly associated with the Sith. " .
<https://starwars.com#planet_MalrevIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Thrasybule> .
<https://starwars.com#ef107854-9ea0-451d-acfd-bdd86abdf702> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Malrev IV"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_MalrevIV> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_MalrevIV> <http://telicent.io/ontology/primaryName> "Malrev IV" .
<https://starwars.com#sector_Thrasybule> <http://telicent.io/ontology/primaryName> "Thrasybule" .
<https://starwars.com#ef107854-9ea0-451d-acfd-bdd86abdf702> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Thrasybule> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MalrevIV> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#sector_Thrasybule> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_MalrevIV> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ef107854-9ea0-451d-acfd-bdd86abdf702> .

