Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Jurzan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1012a0b2-d2cb-4688-8e72-a8329d56273e> .
<https://starwars.com#planet_Jurzan> <http://telicent.io/ontology/primaryName> "Jurzan" .
<https://starwars.com#1012a0b2-d2cb-4688-8e72-a8329d56273e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Jurzan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#1012a0b2-d2cb-4688-8e72-a8329d56273e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Jurzan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Jurzan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Jurzan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Jurzan> <http://www.w3.org/2000/01/rdf-schema#comment> "Jurzan was a planet in the Expansion Region, on the Harrin Trade Corridor. " .
<https://starwars.com#planet_Jurzan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M15> .
<https://starwars.com#sector_Jurzan> <http://telicent.io/ontology/primaryName> "Jurzan" .
<https://starwars.com#planet_Jurzan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Jurzan> .

