Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Moonus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R14> .
<https://starwars.com#sector_BothanSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Moonus> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Moonus> <http://telicent.io/ontology/primaryName> "Moonus" .
<https://starwars.com#sector_BothanSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Moonus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Moonus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_BothanSpace> .
<https://starwars.com#planet_Moonus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c3a4d2ee-fb10-462a-b6f5-e430f778a7bb> .
<https://starwars.com#c3a4d2ee-fb10-462a-b6f5-e430f778a7bb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Moonus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_BothanSpace> <http://telicent.io/ontology/primaryName> "Bothan Space" .
<https://starwars.com#c3a4d2ee-fb10-462a-b6f5-e430f778a7bb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

