Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Zarracina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Vendaxa> <http://www.w3.org/2000/01/rdf-schema#comment> "Vendaxa was a fertile planet located in the Expansion Region of the galaxy. It was the homeworld of the acklay, a non-sentient species of crustaceans that inhabited the planet's lush plains. " .
<https://starwars.com#fde54681-b682-4893-9dd2-1edff056fe1e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Vendaxa"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Vendaxa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O14> .
<https://starwars.com#fde54681-b682-4893-9dd2-1edff056fe1e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Zarracina> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Vendaxa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Vendaxa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#fde54681-b682-4893-9dd2-1edff056fe1e> .
<https://starwars.com#sector_Zarracina> <http://telicent.io/ontology/primaryName> "Zarracina" .
<https://starwars.com#planet_Vendaxa> <http://telicent.io/ontology/primaryName> "Vendaxa" .
<https://starwars.com#planet_Vendaxa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zarracina> .

