Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tarhassan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O11> .
<https://starwars.com#sector_Harron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Tarhassan> <http://www.w3.org/2000/01/rdf-schema#comment> "Tarhassan was a planet in the Expansion Region. It was controlled by the Confederacy of Independent Systems during the Clone Wars. " .
<https://starwars.com#planet_Tarhassan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Harron> .
<https://starwars.com#planet_Tarhassan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Tarhassan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e42ddbf8-9f6d-419f-841d-ebc1f2475fad> .
<https://starwars.com#sector_Harron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Harron> <http://telicent.io/ontology/primaryName> "Harron" .
<https://starwars.com#e42ddbf8-9f6d-419f-841d-ebc1f2475fad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tarhassan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#e42ddbf8-9f6d-419f-841d-ebc1f2475fad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tarhassan> <http://telicent.io/ontology/primaryName> "Tarhassan" .

