Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zisia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5d0bee16-b8b1-42ba-9a80-63d987f45643> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Zisia> <http://telicent.io/ontology/primaryName> "Zisia" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zisia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Zisia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#planet_Zisia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#5d0bee16-b8b1-42ba-9a80-63d987f45643> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zisia> <http://www.w3.org/2000/01/rdf-schema#comment> "Zisia was a rich planet that was located within the Zisia system in Hutt Space, a region of the galaxy controlled by the Hutt species. The planet lay on the hyperlane called The Dead Road, which connected it to the worlds of Elgit and Ulmatra. Zisia was the homeworld of the sentient Zisian species, members of which served as pliant slaves for millennia. " .
<https://starwars.com#5d0bee16-b8b1-42ba-9a80-63d987f45643> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zisia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

