Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Senex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aac9e9f7-9949-408c-9b0f-e24a8f6f01eb> .
<https://starwars.com#planet_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#aac9e9f7-9949-408c-9b0f-e24a8f6f01eb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#aac9e9f7-9949-408c-9b0f-e24a8f6f01eb> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Senex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Senex> <http://www.w3.org/2000/01/rdf-schema#comment> "Senex was a location in the galaxy's Mid Rim that was represented by Senator Terr Taneel in the Galactic Senate of the Galactic Republic during the end of the Clone Wars. Taneel was part of the Delegation of 2,000, a group of politicians who sought to counter Supreme Chancellor Palpatine's growing power. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

