Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Caluula> <http://telicent.io/ontology/primaryName> "Caluula" .
<https://starwars.com#86796233-0839-476b-b785-78338a37428a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Caluula"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_TionHegemony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Caluula> <http://www.w3.org/2000/01/rdf-schema#comment> "Caluula was an astronomical object in the Outer Rim Territories of the galaxy, within the Tion Cluster. It was positioned at the coordinates T-6 on the Standard Galactic Grid. " .
<https://starwars.com#sector_TionHegemony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Caluula> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Caluula> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#86796233-0839-476b-b785-78338a37428a> .
<https://starwars.com#planet_Caluula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_TionHegemony> .
<https://starwars.com#86796233-0839-476b-b785-78338a37428a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Caluula> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T6> .
<https://starwars.com#sector_TionHegemony> <http://telicent.io/ontology/primaryName> "Tion Hegemony" .

