Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4d9c4d5c-f665-454e-a3fd-345f3a52fe37> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mulatan"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mulatan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#4d9c4d5c-f665-454e-a3fd-345f3a52fe37> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mulatan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Mulatan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Mulatan> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4d9c4d5c-f665-454e-a3fd-345f3a52fe37> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Mulatan> <http://telicent.io/ontology/primaryName> "Mulatan" .
<https://starwars.com#planet_Mulatan> <http://www.w3.org/2000/01/rdf-schema#comment> "Mulatan was a planet located in the Bootana Hutta region of Hutt Space. It served as a guardian world dedicated to the defense of the Bootana Hutta and its throneworlds. " .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

