Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Bozhnee> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ossel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L18> .
<https://starwars.com#sector_Bozhnee> <http://telicent.io/ontology/primaryName> "Bozhnee" .
<https://starwars.com#sector_Bozhnee> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ossel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Ossel> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b74608e9-7de9-4ab5-a6d0-bca332b37d16> .
<https://starwars.com#b74608e9-7de9-4ab5-a6d0-bca332b37d16> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b74608e9-7de9-4ab5-a6d0-bca332b37d16> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ossel"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ossel> <http://telicent.io/ontology/primaryName> "Ossel" .
<https://starwars.com#planet_Ossel> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Ossel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Bozhnee> .

