Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Firrerre> <http://www.w3.org/2000/01/rdf-schema#comment> "Firrerre was a world located in the Outer Rim Territories. The New Republic consular office on Firrerre was considered to be the closest New Republic authority for spacers passing in and around the planet Jakku. " .
<https://starwars.com#sector_Zuma> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Zuma> <http://telicent.io/ontology/primaryName> "Zuma" .
<https://starwars.com#planet_Firrerre> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#ad1f42ef-957c-4e4b-96b5-de3e9aa357f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Firrerre> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#ad1f42ef-957c-4e4b-96b5-de3e9aa357f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Firrerre"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Firrerre> <http://telicent.io/ontology/primaryName> "Firrerre" .
<https://starwars.com#planet_Firrerre> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Zuma> .
<https://starwars.com#planet_Firrerre> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ad1f42ef-957c-4e4b-96b5-de3e9aa357f6> .
<https://starwars.com#sector_Zuma> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

