Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Arabanth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#planet_Arabanth> <http://www.w3.org/2000/01/rdf-schema#comment> "Arabanth was a planet in the Interior Region of the Hapes Cluster. " .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Arabanth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#69bc8025-c743-4328-a23a-b6741cafc79e> .
<https://starwars.com#69bc8025-c743-4328-a23a-b6741cafc79e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Arabanth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Arabanth> <http://telicent.io/ontology/primaryName> "Arabanth" .
<https://starwars.com#69bc8025-c743-4328-a23a-b6741cafc79e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Arabanth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Arabanth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .

