Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Belgaroth> <http://www.w3.org/2000/01/rdf-schema#comment> "Belgaroth was a planet that was located within the Core Worlds region of the galaxy, situated near the Rimma Trade Route. The planet was used by the Galactic Empire to test new weapons and combat maneuvers. It was also the homeworld of the droidbreaker, a species of hulking creatures that fed on plasteel and refined metals. " .
<https://starwars.com#planet_Belgaroth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K13> .
<https://starwars.com#planet_Belgaroth> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f46abcf9-d0df-40ed-b873-3acdc708307d> .
<https://starwars.com#planet_Belgaroth> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f46abcf9-d0df-40ed-b873-3acdc708307d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Belgaroth> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#f46abcf9-d0df-40ed-b873-3acdc708307d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belgaroth"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Belgaroth> <http://telicent.io/ontology/primaryName> "Belgaroth" .

