Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Adumar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J6> .
<https://starwars.com#grid_J6> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#beff5216-2a0c-402f-b819-e35b92ae6495> <http://ies.data.gov.uk/ontology/ies4#representationValue> "J6"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Adumar> <http://www.w3.org/2000/01/rdf-schema#comment> "Adumar was an astronomical object located in the Adumar system of the galaxy's Wild Space. " .
<https://starwars.com#planet_Adumar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Adumar> <http://telicent.io/ontology/primaryName> "Adumar" .
<https://starwars.com#grid_J6> <http://telicent.io/ontology/primaryName> "J6" .
<https://starwars.com#region_WildSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_J6> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#beff5216-2a0c-402f-b819-e35b92ae6495> .
<https://starwars.com#region_WildSpace> <http://telicent.io/ontology/primaryName> "Wild Space" .
<https://starwars.com#grid_J6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#22c53e24-cdfc-4f83-92d1-a739bcbe9ce0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Adumar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#22c53e24-cdfc-4f83-92d1-a739bcbe9ce0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Adumar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#region_WildSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#beff5216-2a0c-402f-b819-e35b92ae6495> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Adumar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#22c53e24-cdfc-4f83-92d1-a739bcbe9ce0> .

