Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#region_DeepCore> <http://telicent.io/ontology/primaryName> "Deep Core" .
<https://starwars.com#planet_Besero> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Besero> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L10> .
<https://starwars.com#planet_Besero> <http://www.w3.org/2000/01/rdf-schema#comment> "Besero was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#planet_Besero> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d54fd7db-d504-4947-b036-c3c0f5dc53d2> .
<https://starwars.com#d54fd7db-d504-4947-b036-c3c0f5dc53d2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#region_DeepCore> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#d54fd7db-d504-4947-b036-c3c0f5dc53d2> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Besero"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Besero> <http://telicent.io/ontology/primaryName> "Besero" .
<https://starwars.com#region_DeepCore> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxyRegion> .
<https://starwars.com#planet_Besero> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

