Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Polmanar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#8182e2d7-826e-4cdb-8057-7f581d706659> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Polmanar> <http://telicent.io/ontology/primaryName> "Polmanar" .
<https://starwars.com#sector_Anoat> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Anoat> <http://telicent.io/ontology/primaryName> "Anoat" .
<https://starwars.com#planet_Polmanar> <http://www.w3.org/2000/01/rdf-schema#comment> "Assumption ends here." .
<https://starwars.com#planet_Polmanar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K18> .
<https://starwars.com#planet_Polmanar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8182e2d7-826e-4cdb-8057-7f581d706659> .
<https://starwars.com#8182e2d7-826e-4cdb-8057-7f581d706659> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Polmanar"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Anoat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Polmanar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Anoat> .

