Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Yavin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P6> .
<https://starwars.com#planet_Yavin> <http://www.w3.org/2000/01/rdf-schema#comment> "Gas planet with several moons, including Yavin 4." .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Yavin> <http://telicent.io/ontology/primaryName> "Yavin" .
<https://starwars.com#621e44c5-9ae5-41ac-9b8d-56e0d02470de> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yavin"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Yavin> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#621e44c5-9ae5-41ac-9b8d-56e0d02470de> .
<https://starwars.com#planet_Yavin> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Yavin> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#621e44c5-9ae5-41ac-9b8d-56e0d02470de> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

