Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Centrality> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#5452fc88-75a0-45ef-b2c6-593582c36905> <http://ies.data.gov.uk/ontology/ies4#representationValue> "U8"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U8> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#b160240d-f3a3-4008-aeb4-0b6638975fe5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5452fc88-75a0-45ef-b2c6-593582c36905> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#b160240d-f3a3-4008-aeb4-0b6638975fe5> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Antipose"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_U8> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5452fc88-75a0-45ef-b2c6-593582c36905> .
<https://starwars.com#planet_Antipose> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_U8> <http://telicent.io/ontology/primaryName> "U8" .
<https://starwars.com#planet_Antipose> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b160240d-f3a3-4008-aeb4-0b6638975fe5> .
<https://starwars.com#sector_Centrality> <http://telicent.io/ontology/primaryName> "Centrality" .
<https://starwars.com#planet_Antipose> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Centrality> .
<https://starwars.com#planet_Antipose> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U8> .
<https://starwars.com#grid_U8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Antipose> <http://telicent.io/ontology/primaryName> "Antipose" .
<https://starwars.com#planet_Antipose> <http://www.w3.org/2000/01/rdf-schema#comment> "Convincing Chewbacca to start a public, impromptu fight with the arena system's top contender, Solo used the distraction offered by the gathering crowd of onlookers to sneak into Raskar's villa and scan the power gem. The smuggler determined that the artifact only had enough potency left for one proper use—a fact that Raskar had not disclosed to any of the contestants—and then persuaded Raskar to declare Chewbacca the ultimate winner of the competitions and therefore turn the gem over to him and Solo. The two smugglers then brought the power gem back to the Rebel Alliance base on the moon Yavin 4. " .
<https://starwars.com#sector_Centrality> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

