Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Forsen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Cassander> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Cassander> <http://telicent.io/ontology/primaryName> "Cassander" .
<https://starwars.com#planet_Forsen> <http://www.w3.org/2000/01/rdf-schema#comment> "Forsen was a lush agriworld in the Outer Rim. It was part of the Cassandran Worlds. " .
<https://starwars.com#6ad2fa94-dc1c-448d-9c48-9a73eed1e85f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Forsen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6ad2fa94-dc1c-448d-9c48-9a73eed1e85f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Forsen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6ad2fa94-dc1c-448d-9c48-9a73eed1e85f> .
<https://starwars.com#planet_Forsen> <http://telicent.io/ontology/primaryName> "Forsen" .
<https://starwars.com#sector_Cassander> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Forsen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Forsen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Cassander> .

