Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f70d1345-3efc-4029-965a-1c32e651d9ad> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kemal Station"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KemalStation> <http://telicent.io/ontology/primaryName> "Kemal Station" .
<https://starwars.com#f70d1345-3efc-4029-965a-1c32e651d9ad> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KemalStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R16> .
<https://starwars.com#sector_Arkanis> <http://telicent.io/ontology/primaryName> "Arkanis" .
<https://starwars.com#planet_KemalStation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KemalStation> <http://www.w3.org/2000/01/rdf-schema#comment> "Kemal Station was a damp, foggy, terrestrial moon orbiting the gas giant–type planet Kemal in the Kemal Station system, a part of the Arkanis sector in the Slice portion of the Outer Rim Territories. It was situated on the Triellus Trade Route hyperlane, which connected it to the Andooweel and New Ator systems. " .
<https://starwars.com#sector_Arkanis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KemalStation> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Arkanis> .
<https://starwars.com#sector_Arkanis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_KemalStation> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f70d1345-3efc-4029-965a-1c32e651d9ad> .

