Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KarvossII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_KarvossII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c5fbeb06-05a6-4be8-b216-0006b17c1176> .
<https://starwars.com#c5fbeb06-05a6-4be8-b216-0006b17c1176> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KarvossII> <http://www.w3.org/2000/01/rdf-schema#comment> "Karvoss II was a terrestrial planet in the Core Worlds' Parmorak sector. After the Great Sith War, a Human female from Karvoss II discovered her Force-sensitivity while practicing a form of martial arts. She eventually went on to create the Matukai sect of Force-users." .
<https://starwars.com#planet_KarvossII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#c5fbeb06-05a6-4be8-b216-0006b17c1176> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Karvoss II"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KarvossII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KarvossII> <http://telicent.io/ontology/primaryName> "Karvoss II" .

