Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#c0747de9-79ea-4667-81f6-5b22e7c53fbe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Oslumpex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#planet_Oslumpex> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c0747de9-79ea-4667-81f6-5b22e7c53fbe> .
<https://starwars.com#planet_Oslumpex> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Oslumpex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#c0747de9-79ea-4667-81f6-5b22e7c53fbe> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Oslumpex"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Oslumpex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Oslumpex> <http://telicent.io/ontology/primaryName> "Oslumpex" .

