Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Artesia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Artesia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f0558b40-815e-495b-ac46-26fcedb50edc> .
<https://starwars.com#grid_P11> <http://telicent.io/ontology/primaryName> "P11" .
<https://starwars.com#planet_Artesia> <http://www.w3.org/2000/01/rdf-schema#comment> "Artesia was a planet located within the Artesia system, a part of the Hangshan sector in the galactic regions known as the Slice and the Expansion Region. The Artesian space collage art form originated on the planet. " .
<https://starwars.com#f0558b40-815e-495b-ac46-26fcedb50edc> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Artesia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_P11> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#5bfd1b4d-7db4-41d4-9446-f1cd2612497e> .
<https://starwars.com#5bfd1b4d-7db4-41d4-9446-f1cd2612497e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#sector_Hangshan> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Artesia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P11> .
<https://starwars.com#grid_P11> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_Artesia> <http://telicent.io/ontology/primaryName> "Artesia" .
<https://starwars.com#sector_Hangshan> <http://telicent.io/ontology/primaryName> "Hangshan" .
<https://starwars.com#sector_Hangshan> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Artesia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Hangshan> .
<https://starwars.com#grid_P11> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#f0558b40-815e-495b-ac46-26fcedb50edc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#5bfd1b4d-7db4-41d4-9446-f1cd2612497e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "P11"^^<http://www.w3.org/2001/XMLSchema#string> .

