Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Belnar> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#3a358b2b-dc92-483e-951b-5401083d5749> .
<https://starwars.com#planet_Belnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Belnar> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#3a358b2b-dc92-483e-951b-5401083d5749> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Belnar> <http://www.w3.org/2000/01/rdf-schema#comment> "Belnar was an astronomical body located in the Colonies region at the coordinates M-9. Prior to 3 ABY, some insurrections occurred around Belnar, during of which Everi Chalis, an emissary to the Galactic Empire's ruling council, punished the crew of the starship Mandible over for accident, executing those responsible. Chalis later cited the Belnar Insurrections to the crew of an Imperial heavy freighter in 3 ABY, referencing the punishment of the Mandible's crew to threaten the freighter into changing course. " .
<https://starwars.com#planet_Belnar> <http://telicent.io/ontology/primaryName> "Belnar" .
<https://starwars.com#planet_Belnar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#3a358b2b-dc92-483e-951b-5401083d5749> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Belnar"^^<http://www.w3.org/2001/XMLSchema#string> .

