Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorDesilijic> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#29e0b1ad-8e5b-4b7b-8641-eda424e897df> .
<https://starwars.com#planet_KorDesilijic> <http://telicent.io/ontology/primaryName> "Kor Desilijic" .
<https://starwars.com#planet_KorDesilijic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#planet_KorDesilijic> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_KorDesilijic> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Desilijic was a planet located in the Bootana Hutta region of Hutt Space. It was the throneworld of the Desilijic kajidic. " .
<https://starwars.com#29e0b1ad-8e5b-4b7b-8641-eda424e897df> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#29e0b1ad-8e5b-4b7b-8641-eda424e897df> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Desilijic"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_KorDesilijic> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

