Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Senex> <http://telicent.io/ontology/primaryName> "Senex" .
<https://starwars.com#planet_Presteen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Presteen> <http://telicent.io/ontology/primaryName> "Presteen" .
<https://starwars.com#sector_Senex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#aaef0554-c81a-427f-bb05-620095f51845> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Presteen"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Presteen> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#aaef0554-c81a-427f-bb05-620095f51845> .
<https://starwars.com#planet_Presteen> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Senex> .
<https://starwars.com#planet_Presteen> <http://www.w3.org/2000/01/rdf-schema#comment> "Presteen was a trade world located in the Presteen system of the Senex sector, a part of the Senex-Juvex region in the Western Reaches portion of the Mid Rim. The Senex-Juvex Loop hyperlane linked it to the Caltinia and Veron systems. Presteen was under the control of the lesser nobles of House Araba, based on the nearby planet of Cyimarra. " .
<https://starwars.com#sector_Senex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Presteen> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#aaef0554-c81a-427f-bb05-620095f51845> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

