Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Zorbia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Moddell> .
<https://starwars.com#planet_Zorbia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#97adb3b7-8efc-42fe-b3b1-34ca7b0b246f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Zorbia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Moddell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#97adb3b7-8efc-42fe-b3b1-34ca7b0b246f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Zorbia> <http://www.w3.org/2000/01/rdf-schema#comment> "Zorbia was an astronomical object located in the Moddell sector of the Outer Rim Territories in grid square H-16 of the Standard Galactic Grid. It was situated on the Ovise Reach hyperspace route, which linked it to the Endor and Trindello systems. The Moddell sector's hyperspace anomalies sometimes transported starships to the Endor system from as far away as Zorbia. Zorbia was eventually depicted on a map of the Moddell sector included with the Rebel Alliance collection of non-electronic documents known as The Rebel Files. " .
<https://starwars.com#sector_Moddell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Zorbia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#97adb3b7-8efc-42fe-b3b1-34ca7b0b246f> .
<https://starwars.com#planet_Zorbia> <http://telicent.io/ontology/primaryName> "Zorbia" .
<https://starwars.com#planet_Zorbia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H16> .
<https://starwars.com#sector_Moddell> <http://telicent.io/ontology/primaryName> "Moddell" .

