Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Bassadro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_Bassadro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#95c80fcb-d0a1-4051-bd08-fc238d997442> .
<https://starwars.com#planet_Bassadro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Bassadro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Bassadro> <http://www.w3.org/2000/01/rdf-schema#comment> "Bassadro was a mining world with glassy crags on its volcanoes. It was devastated in a battle in which it was taken from the Confederacy of Independent Systems during the Clone Wars by Empatojayos Brand. " .
<https://starwars.com#95c80fcb-d0a1-4051-bd08-fc238d997442> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#95c80fcb-d0a1-4051-bd08-fc238d997442> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Bassadro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Bassadro> <http://telicent.io/ontology/primaryName> "Bassadro" .

