Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Dremulae> <http://www.w3.org/2000/01/rdf-schema#comment> "Dremulae was an astronomical object located in the galaxy's Deep Core. " .
<https://starwars.com#0739dbb9-e2ba-4771-a69b-b97b12597684> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Dremulae"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Dremulae> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#0739dbb9-e2ba-4771-a69b-b97b12597684> .
<https://starwars.com#planet_Dremulae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_DeepCore> .
<https://starwars.com#planet_Dremulae> <http://telicent.io/ontology/primaryName> "Dremulae" .
<https://starwars.com#planet_Dremulae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M10> .
<https://starwars.com#planet_Dremulae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#0739dbb9-e2ba-4771-a69b-b97b12597684> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

