Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#e1580239-8bff-4282-b9ef-bbf418eca8a0> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Duro"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Duro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Duro> <http://telicent.io/ontology/primaryName> "Duro" .
<https://starwars.com#e1580239-8bff-4282-b9ef-bbf418eca8a0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Duro> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Duro> <http://www.w3.org/2000/01/rdf-schema#comment> "Duro was a temperate planet located in the Core Worlds that was the homeworld of the Duros species. " .
<https://starwars.com#planet_Duro> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M11> .
<https://starwars.com#planet_Duro> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e1580239-8bff-4282-b9ef-bbf418eca8a0> .

