Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#74f6b5cd-2bd9-44e8-bdd5-19499011d571> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Castell> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#74f6b5cd-2bd9-44e8-bdd5-19499011d571> .
<https://starwars.com#planet_Castell> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#74f6b5cd-2bd9-44e8-bdd5-19499011d571> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Castell"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Castell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#planet_Castell> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M9> .
<https://starwars.com#planet_Castell> <http://telicent.io/ontology/primaryName> "Castell" .
<https://starwars.com#planet_Castell> <http://www.w3.org/2000/01/rdf-schema#comment> "Castell was a planet located in the Castell system of the Colonies, situated along the Perlemian Trade Route. The Commerce Guild had interests on Castell and their Presidente Shu Mai hailed from the planet. Castell sided with the Confederacy of Independent Systems during the Clone Wars during which it was defended by Diamond-class cruisers, Recusant-class Commerce Guild destroyers, as well as Commerce Guild Bombers and Commerce Guild corvettes. By the time of the Battle of Felucia during the Clone Wars final year, Castell had been captured by Republic forces. During the Galactic Civil War, it was a colony world of the Galactic Empire. It was ruled by its sector's Imperial Governor, Moff Ssaria. " .

