Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#56c9e9c5-f11c-4570-a8d1-ecb69dec7119> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Yag'Dhul"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_YagDhul> <http://www.w3.org/2000/01/rdf-schema#comment> "Yag'Dhul was a world located in the galaxy's Inner Rim that was the homeworld of the sentient Givin species. Its environment was so harsh that their organs were sealed away from the atmosphere and they could survive for a short while in vacuum. Yag'Dhul was located at the intersection of the Corellian Trade Spine and the Rimma Trade Route. During the Separatist Crisis, it joined the Confederacy of Independent Systems. Along with Sluis Van, Yag'Dhul made up part of a southern sphere of Separatist worlds, to which Count Dooku unsuccessfully attempted to add Eriadu. " .
<https://starwars.com#planet_YagDhul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L14> .
<https://starwars.com#planet_YagDhul> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#56c9e9c5-f11c-4570-a8d1-ecb69dec7119> .
<https://starwars.com#planet_YagDhul> <http://telicent.io/ontology/primaryName> "Yag'Dhul" .
<https://starwars.com#56c9e9c5-f11c-4570-a8d1-ecb69dec7119> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GivinDomain> <http://telicent.io/ontology/primaryName> "Givin Domain" .
<https://starwars.com#sector_GivinDomain> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_YagDhul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_GivinDomain> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_YagDhul> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GivinDomain> .

