Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Obroa-skai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Obroa-skai> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#670e096b-d538-48c3-a0a6-212a306a55f6> .
<https://starwars.com#planet_Obroa-skai> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N8> .
<https://starwars.com#planet_Obroa-skai> <http://www.w3.org/2000/01/rdf-schema#comment> "Obroa-skai was a planet located in the Obroa-skai system of the galaxy's Inner Rim. It was known mostly for its libraries and medcenters. At the end of the Clone Wars, one of those medcenters bought a fleet of Sephi flyers from Thustra for use during emergency evacuations. Galen Walton Erso served as a teacher at a college on the planet. " .
<https://starwars.com#planet_Obroa-skai> <http://telicent.io/ontology/primaryName> "Obroa-skai" .
<https://starwars.com#planet_Obroa-skai> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#670e096b-d538-48c3-a0a6-212a306a55f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#670e096b-d538-48c3-a0a6-212a306a55f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Obroa-skai"^^<http://www.w3.org/2001/XMLSchema#string> .

