Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_HosnianPrime> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1229cd24-044c-45e6-afc6-b717d3b19528> .
<https://starwars.com#1229cd24-044c-45e6-afc6-b717d3b19528> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Hosnian Prime"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_HosnianPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_HosnianPrime> <http://www.w3.org/2000/01/rdf-schema#comment> "Urban planet and capital of the New Republic. Destroyed by the First Order's Starkiller Base." .
<https://starwars.com#planet_HosnianPrime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#1229cd24-044c-45e6-afc6-b717d3b19528> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_HosnianPrime> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_M12> .
<https://starwars.com#planet_HosnianPrime> <http://telicent.io/ontology/primaryName> "Hosnian Prime" .

