Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#826472c9-3681-4a38-86b8-363e1b19c556> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_ParthovianCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_ParthovianCluster> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#826472c9-3681-4a38-86b8-363e1b19c556> .
<https://starwars.com#grid_T4> <http://telicent.io/ontology/primaryName> "T4" .
<https://starwars.com#826472c9-3681-4a38-86b8-363e1b19c556> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Parthovian Cluster"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_ParthovianCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#651f620d-999f-40bc-97ed-0afda0ee2f15> <http://ies.data.gov.uk/ontology/ies4#representationValue> "T4"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_T4> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#651f620d-999f-40bc-97ed-0afda0ee2f15> .
<https://starwars.com#grid_T4> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_ParthovianCluster> <http://www.w3.org/2000/01/rdf-schema#comment> "The Parthovian Cluster was in Wild Space. It was located at grid coordinated T-4. It contained the Faarlsun system. " .
<https://starwars.com#planet_ParthovianCluster> <http://telicent.io/ontology/primaryName> "Parthovian Cluster" .
<https://starwars.com#planet_ParthovianCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T4> .
<https://starwars.com#651f620d-999f-40bc-97ed-0afda0ee2f15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#grid_T4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .

