Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Periphery> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Periphery> <http://telicent.io/ontology/primaryName> "Periphery" .
<https://starwars.com#5bd3349c-e59a-4644-8429-cfafa106dfb8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Periphery> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lant> <http://telicent.io/ontology/primaryName> "Lant" .
<https://starwars.com#planet_Lant> <http://www.w3.org/2000/01/rdf-schema#comment> "Lant was the planet in the Lant system, a star system in the Periphery, a sector in the Outer Rim within Hutt Space. Lant was a trade world with extensive Hutt holdings. " .
<https://starwars.com#planet_Lant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Periphery> .
<https://starwars.com#planet_Lant> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5bd3349c-e59a-4644-8429-cfafa106dfb8> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lant"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lant> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5bd3349c-e59a-4644-8429-cfafa106dfb8> .
<https://starwars.com#planet_Lant> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S8> .

