Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tashtor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_TashtorSeneca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#dac69e63-7b92-4ebe-a8d6-bc628ddc8894> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tashtor Seneca"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Tashtor> <http://telicent.io/ontology/primaryName> "Tashtor" .
<https://starwars.com#planet_TashtorSeneca> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#dac69e63-7b92-4ebe-a8d6-bc628ddc8894> .
<https://starwars.com#planet_TashtorSeneca> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tashtor> .
<https://starwars.com#planet_TashtorSeneca> <http://www.w3.org/2000/01/rdf-schema#comment> "Tashtor Seneca was a location in the Tashtor Seneca system, a part of the Mid Rim's Tashtor sector. During the Galactic Civil War, the forces of the Galactic Empire destroyed the Croc of Gold, the freighter of the Rebel Alliance operative Devon Fuller, over Tashtor Seneca. " .
<https://starwars.com#dac69e63-7b92-4ebe-a8d6-bc628ddc8894> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Tashtor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_TashtorSeneca> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J16> .
<https://starwars.com#planet_TashtorSeneca> <http://telicent.io/ontology/primaryName> "Tashtor Seneca" .

