Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Saclas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#ea61ba35-9424-478e-aeca-41d9d0da0805> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Saclas> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .
<https://starwars.com#planet_Saclas> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ea61ba35-9424-478e-aeca-41d9d0da0805> .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Saclas> <http://telicent.io/ontology/primaryName> "Saclas" .
<https://starwars.com#ea61ba35-9424-478e-aeca-41d9d0da0805> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Saclas"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Saclas> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Saclas> <http://www.w3.org/2000/01/rdf-schema#comment> "Saclas was an Ocsin colony in the Corporate Sector. The planet was at the intersection of the Tertiary Solenbaran and the Solenbaran Merchant Route. " .

