Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#1dd0e765-99e0-47a6-9a91-635b1fee0f7e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Haverling"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#1dd0e765-99e0-47a6-9a91-635b1fee0f7e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Albarrio> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Haverling> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K5> .
<https://starwars.com#sector_Albarrio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Haverling> <http://www.w3.org/2000/01/rdf-schema#comment> "Haverling was a planet in the Albarrio sector of the Outer Rim Territories, near the world of Morishim. It joined the New Republic, aiding the government by providing new shipyards to support the New Republic Navy. " .
<https://starwars.com#planet_Haverling> <http://telicent.io/ontology/primaryName> "Haverling" .
<https://starwars.com#sector_Albarrio> <http://telicent.io/ontology/primaryName> "Albarrio" .
<https://starwars.com#planet_Haverling> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Haverling> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1dd0e765-99e0-47a6-9a91-635b1fee0f7e> .
<https://starwars.com#planet_Haverling> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Albarrio> .

