Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Genon> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Genon> <http://telicent.io/ontology/primaryName> "Genon" .
<https://starwars.com#planet_Genon> <http://www.w3.org/2000/01/rdf-schema#comment> "Genon was a planet not far from Imperial commercial centers but it was nearly devoid of settlement because of its most infamous inhabitant: Grappa the Hutt. Grappa used Genon as his base of operations, and his own reputation combined with his well-known connections to Black Sun kept the Empire and others at bay. " .
<https://starwars.com#planet_Genon> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#331cf20f-fcbc-4d52-9a5a-aa91b9b14c1f> .
<https://starwars.com#planet_Genon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N13> .
<https://starwars.com#planet_Genon> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#331cf20f-fcbc-4d52-9a5a-aa91b9b14c1f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Genon"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#331cf20f-fcbc-4d52-9a5a-aa91b9b14c1f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

