Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_NichtKa> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#5172515e-58ec-480f-8ee3-a816ea29b03e> .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_NichtKa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R5> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_NichtKa> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#5172515e-58ec-480f-8ee3-a816ea29b03e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Nicht Ka"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_NichtKa> <http://www.w3.org/2000/01/rdf-schema#comment> "Nicht Ka was a planet in the Sith Worlds, a region of space within the Stygian Caldera, which was located in the Esstran sector of the Outer Rim Territories. " .
<https://starwars.com#planet_NichtKa> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#5172515e-58ec-480f-8ee3-a816ea29b03e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_NichtKa> <http://telicent.io/ontology/primaryName> "Nicht Ka" .

