Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tennuutta> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Casfield> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Casfield> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tennuutta> .
<https://starwars.com#sector_Tennuutta> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Tennuutta> <http://telicent.io/ontology/primaryName> "Tennuutta" .
<https://starwars.com#271b0d37-6c8f-465a-ac30-acf9798d15ba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Casfield> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q7> .
<https://starwars.com#271b0d37-6c8f-465a-ac30-acf9798d15ba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Casfield"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Casfield> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#271b0d37-6c8f-465a-ac30-acf9798d15ba> .
<https://starwars.com#planet_Casfield> <http://telicent.io/ontology/primaryName> "Casfield" .
<https://starwars.com#planet_Casfield> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

