Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Sakiduba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Sakiduba> <http://telicent.io/ontology/primaryName> "Sakiduba" .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Sakiduba> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#1387608a-d31e-4e48-a082-f5fda37867c4> .
<https://starwars.com#1387608a-d31e-4e48-a082-f5fda37867c4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Sakiduba> <http://www.w3.org/2000/01/rdf-schema#comment> "Sakiduba, which could be translated as 'Third Saki,' was a planet located in the Bootana Hutta region of Hutt Space. " .
<https://starwars.com#planet_Sakiduba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#planet_Sakiduba> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S11> .
<https://starwars.com#1387608a-d31e-4e48-a082-f5fda37867c4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Sakiduba"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

