Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ziost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_SithWorlds> .
<https://starwars.com#planet_Ziost> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_SithWorlds> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ziost> <http://www.w3.org/2000/01/rdf-schema#comment> "Ziost was a world located in the galaxy's Outer Rim Territories in grid square R-4 on the Standard Galactic Grid. It was one of noteworthy worlds of the ancient Sith. " .
<https://starwars.com#62beb4c2-cead-47fd-b1ba-a62848c3f92b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ziost"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_SithWorlds> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_SithWorlds> <http://telicent.io/ontology/primaryName> "Sith Worlds" .
<https://starwars.com#planet_Ziost> <http://telicent.io/ontology/primaryName> "Ziost" .
<https://starwars.com#planet_Ziost> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R4> .
<https://starwars.com#planet_Ziost> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#62beb4c2-cead-47fd-b1ba-a62848c3f92b> .
<https://starwars.com#62beb4c2-cead-47fd-b1ba-a62848c3f92b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

