Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Galvoni> <http://telicent.io/ontology/primaryName> "Galvoni" .
<https://starwars.com#planet_Galvoni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#planet_Galvoni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K9> .
<https://starwars.com#planet_Galvoni> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#617fdf10-c829-462e-8e5e-1f9ea5ba0492> .
<https://starwars.com#planet_Galvoni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#617fdf10-c829-462e-8e5e-1f9ea5ba0492> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Galvoni> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#617fdf10-c829-462e-8e5e-1f9ea5ba0492> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Galvoni"^^<http://www.w3.org/2001/XMLSchema#string> .

