Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_LaakteenDepot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_LaakteenDepot> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#7d2695e1-92a0-4ec6-b99a-4c4ab9411ef4> .
<https://starwars.com#planet_LaakteenDepot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L13> .
<https://starwars.com#planet_LaakteenDepot> <http://telicent.io/ontology/primaryName> "Laakteen Depot" .
<https://starwars.com#planet_LaakteenDepot> <http://www.w3.org/2000/01/rdf-schema#comment> "Six months after the Battle of Yavin and the loss of the Empire's Death Star battlestation, the Super Star Destroyer Executor destroyed Laakteen Depot during the ship's maiden voyage as a deliberate show of Imperial military might. By annihilating the Rebel base with his newly completed warship, the Dark Lord Darth Vader intended to demonstrate to the galaxy the Empire's supremacy. " .
<https://starwars.com#planet_LaakteenDepot> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#7d2695e1-92a0-4ec6-b99a-4c4ab9411ef4> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Laakteen Depot"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#7d2695e1-92a0-4ec6-b99a-4c4ab9411ef4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

