Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#c385eb15-59af-4271-8597-ff71cae5ffe1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#c385eb15-59af-4271-8597-ff71cae5ffe1> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quermia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Quermia> <http://www.w3.org/2000/01/rdf-schema#comment> "Quermia was a garden planet located in the Outer Rim Territories. It was the namesake of the Quermian species, whose ancestors were settled on Quermia by Arkanian scientists. During the Clone Wars, Quermia was located in Separatist space, isolating it from the Galactic Republic. Although the extensive blockade of Quermia was lifted after the collapse of the Confederacy of Independent Systems, the planet fell under Imperial rule shortly thereafter. " .
<https://starwars.com#sector_Nilgaard> <http://telicent.io/ontology/primaryName> "Nilgaard" .
<https://starwars.com#planet_Quermia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Nilgaard> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Quermia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S5> .
<https://starwars.com#sector_Nilgaard> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Quermia> <http://telicent.io/ontology/primaryName> "Quermia" .
<https://starwars.com#planet_Quermia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#c385eb15-59af-4271-8597-ff71cae5ffe1> .
<https://starwars.com#planet_Quermia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Nilgaard> .

