Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Prishella> <http://www.w3.org/2000/01/rdf-schema#comment> "Prishella was a celestial body located in the regions known as the Outer Rim Territories and the Slice, in grid square T-10 of the Standard Galactic Grid. It was connected by the Pabol Sleheyron hyperspace route to the astronomical objects Formos and Little Kessel. " .
<https://starwars.com#planet_Prishella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kessel> .
<https://starwars.com#planet_Prishella> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T10> .
<https://starwars.com#planet_Prishella> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#31c5b1ca-8bc0-4e9b-901a-435b66a36e57> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Prishella"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kessel> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_Kessel> <http://telicent.io/ontology/primaryName> "Kessel" .
<https://starwars.com#sector_Kessel> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Prishella> <http://telicent.io/ontology/primaryName> "Prishella" .
<https://starwars.com#planet_Prishella> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#31c5b1ca-8bc0-4e9b-901a-435b66a36e57> .
<https://starwars.com#31c5b1ca-8bc0-4e9b-901a-435b66a36e57> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .

