Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Kallea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Kallea> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Terminus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_K20> .
<https://starwars.com#planet_Terminus> <http://telicent.io/ontology/primaryName> "Terminus" .
<https://starwars.com#planet_Terminus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#6fc89b1e-df0c-40a4-b306-4921faddb951> .
<https://starwars.com#planet_Terminus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Kallea> <http://telicent.io/ontology/primaryName> "Kallea" .
<https://starwars.com#6fc89b1e-df0c-40a4-b306-4921faddb951> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Terminus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#6fc89b1e-df0c-40a4-b306-4921faddb951> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Terminus> <http://www.w3.org/2000/01/rdf-schema#comment> "Terminus was an astronomical object located in the galaxy's Outer Rim Territories, and was the intersection of the Corellian Trade Spine and the Hydian Way. The corridor was known to be infested with pirates, including the Ohnaka Gang. Around 3 ABY, the Spirit of Jedha dropped out of hyperspace, and was trapped there. Droid Gotra began to transmit orders to all members of Gotra and the Cyban Front stationed in the Rim Territories, ordering them to strike high-value data caches on Terminus, Little Petrovi and Corbett Cluster. The transmission was promptly intercepted by the Guavian Death Gang, who then broadcast their own counteracting broadcast. " .
<https://starwars.com#planet_Terminus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kallea> .

