Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_OsssorckNebulae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#27819db1-718c-4e3c-963a-3fec5c1b6ea7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#27819db1-718c-4e3c-963a-3fec5c1b6ea7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Osssorck Nebulae"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_OsssorckNebulae> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#27819db1-718c-4e3c-963a-3fec5c1b6ea7> .
<https://starwars.com#planet_OsssorckNebulae> <http://telicent.io/ontology/primaryName> "Osssorck Nebulae" .
<https://starwars.com#planet_OsssorckNebulae> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J12> .
<https://starwars.com#planet_OsssorckNebulae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_OsssorckNebulae> <http://www.w3.org/2000/01/rdf-schema#comment> "The Nebulas of Osssorck, also known as the Osssorck Nebulae, were a series of nebulosities located in the Core Worlds. During the Galactic Civil War, an aging yet legendary gunfighter resided in the city of Buerhoz on the Outer Rim Territories' planet Clak'dor VII. When a group of individuals encountered the gunfighter at Buerhoz, he claimed to have witnessed the destruction of several cruisers of the Galactic Empire in the Nebulas of Osssorck. " .

