Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#8241ce05-ee5b-4350-9267-e61815e0559f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_ImmerianOutback> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Pamorjal> <http://www.w3.org/2000/01/rdf-schema#comment> "Pamorjal was a planet located in the Pamorjal system in the Expansion Region. " .
<https://starwars.com#sector_ImmerianOutback> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Pamorjal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_ImmerianOutback> .
<https://starwars.com#planet_Pamorjal> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .
<https://starwars.com#8241ce05-ee5b-4350-9267-e61815e0559f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Pamorjal"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Pamorjal> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_ImmerianOutback> <http://telicent.io/ontology/primaryName> "Immerian Outback" .
<https://starwars.com#planet_Pamorjal> <http://telicent.io/ontology/primaryName> "Pamorjal" .
<https://starwars.com#planet_Pamorjal> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#8241ce05-ee5b-4350-9267-e61815e0559f> .

