Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Mytus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_WildSpace> .
<https://starwars.com#planet_Mytus> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S3> .
<https://starwars.com#07447899-30b4-419c-890c-0e327c8e9a68> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Mytus"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Mytus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Mytus> <http://www.w3.org/2000/01/rdf-schema#comment> "Mytus was an astronomical object located in the regions known as the Outer Rim Territories and the New Territories. It was located within grid square S-3 on the Standard Galactic Grid. " .
<https://starwars.com#07447899-30b4-419c-890c-0e327c8e9a68> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Mytus> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#07447899-30b4-419c-890c-0e327c8e9a68> .
<https://starwars.com#planet_Mytus> <http://telicent.io/ontology/primaryName> "Mytus" .

