Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Varada> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#6367a800-0c15-4ae4-abac-c800dd7dbbdd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Skye> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_H19> <http://telicent.io/ontology/primaryName> "H19" .
<https://starwars.com#sector_Varada> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#grid_H19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#6367a800-0c15-4ae4-abac-c800dd7dbbdd> <http://ies.data.gov.uk/ontology/ies4#representationValue> "H19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ca8c2c9a-cdd5-4743-aed9-4baafb98bc64> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Skye"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#ca8c2c9a-cdd5-4743-aed9-4baafb98bc64> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Skye> <http://www.w3.org/2000/01/rdf-schema#comment> "Skye was an astronomical object located in the galaxy's Outer Rim Territories. " .
<https://starwars.com#planet_Skye> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_H19> .
<https://starwars.com#planet_Skye> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#ca8c2c9a-cdd5-4743-aed9-4baafb98bc64> .
<https://starwars.com#planet_Skye> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Varada> .
<https://starwars.com#grid_H19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#6367a800-0c15-4ae4-abac-c800dd7dbbdd> .
<https://starwars.com#sector_Varada> <http://telicent.io/ontology/primaryName> "Varada" .
<https://starwars.com#grid_H19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Skye> <http://telicent.io/ontology/primaryName> "Skye" .

