Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_KorNijiladii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S10> .
<https://starwars.com#643675e1-eec7-4911-8878-f4d4c1afd669> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_KorNijiladii> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_KorNijiladii> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#643675e1-eec7-4911-8878-f4d4c1afd669> .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_KorNijiladii> <http://www.w3.org/2000/01/rdf-schema#comment> "Kor Nijiladii was a planet located in the Bootana Hutta region of Hutt Space. It was a Hutt throneworld. " .
<https://starwars.com#planet_KorNijiladii> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_KorNijiladii> <http://telicent.io/ontology/primaryName> "Kor Nijiladii" .
<https://starwars.com#643675e1-eec7-4911-8878-f4d4c1afd669> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Kor Nijiladii"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

