Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f750d3bf-3bf8-4f98-8cef-bf26828ce03f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Prackla> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#sector_Prackla> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Cartao> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Cartao> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f750d3bf-3bf8-4f98-8cef-bf26828ce03f> .
<https://starwars.com#planet_Cartao> <http://telicent.io/ontology/primaryName> "Cartao" .
<https://starwars.com#planet_Cartao> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#sector_Prackla> <http://telicent.io/ontology/primaryName> "Prackla" .
<https://starwars.com#planet_Cartao> <http://www.w3.org/2000/01/rdf-schema#comment> "During the Galactic Civil War, the Rebel Alliance's 61st Mobile Infantry fought on Cartao. In 3 ABY, when the company was stranded on the manufacturing planet Sullust, the tentative Captain Hazram Namir asked Vifra, the head of engineering, whether she had been present for the fighting on Cartao. Vifra replied that she had only joined six months prior, and so Namir told her that he'd tell her about Cartao if she helped keep the Sixty-First alive. " .
<https://starwars.com#planet_Cartao> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Prackla> .
<https://starwars.com#f750d3bf-3bf8-4f98-8cef-bf26828ce03f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Cartao"^^<http://www.w3.org/2001/XMLSchema#string> .

