Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#65bacd6e-9731-4d09-a9cd-fa6a79fd0757> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Eadu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_U10> .
<https://starwars.com#planet_Eadu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#65bacd6e-9731-4d09-a9cd-fa6a79fd0757> .
<https://starwars.com#planet_Eadu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Eadu> <http://telicent.io/ontology/primaryName> "Eadu" .
<https://starwars.com#65bacd6e-9731-4d09-a9cd-fa6a79fd0757> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Eadu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Calaron> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Eadu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Calaron> .
<https://starwars.com#sector_Calaron> <http://telicent.io/ontology/primaryName> "Calaron" .
<https://starwars.com#planet_Eadu> <http://www.w3.org/2000/01/rdf-schema#comment> "Rocky, mountainous planet beset by constant severe storms. Home to an Imperial weapons research facility. Its appearance was partly inspired by the fictitious planet LV-426 from the Alien franchise." .
<https://starwars.com#sector_Calaron> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

