Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Valc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Perinn> .
<https://starwars.com#sector_Perinn> <http://telicent.io/ontology/primaryName> "Perinn" .
<https://starwars.com#e6c53f8c-941f-4535-90db-c1eba850b786> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Valc"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Valc> <http://www.w3.org/2000/01/rdf-schema#comment> "Valc was an astronomical object located in Wild Space. " .
<https://starwars.com#planet_Valc> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#e6c53f8c-941f-4535-90db-c1eba850b786> .
<https://starwars.com#planet_Valc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Valc> <http://telicent.io/ontology/primaryName> "Valc" .
<https://starwars.com#planet_Valc> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_J4> .
<https://starwars.com#e6c53f8c-941f-4535-90db-c1eba850b786> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Perinn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Perinn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

