Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#da41d4b6-0326-4fb3-9e6c-a2b66a5bfc1f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Aguarl"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_N15> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#bfe7d78e-13ad-4a27-a77a-5c61713b5be7> .
<https://starwars.com#planet_Aguarl> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#da41d4b6-0326-4fb3-9e6c-a2b66a5bfc1f> .
<https://starwars.com#planet_Aguarl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N15> .
<https://starwars.com#da41d4b6-0326-4fb3-9e6c-a2b66a5bfc1f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#bfe7d78e-13ad-4a27-a77a-5c61713b5be7> <http://ies.data.gov.uk/ontology/ies4#representationValue> "N15"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Aguarl> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Mbandamonte> .
<https://starwars.com#planet_Aguarl> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_N15> <http://telicent.io/ontology/primaryName> "N15" .
<https://starwars.com#grid_N15> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#sector_Mbandamonte> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Mbandamonte> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#bfe7d78e-13ad-4a27-a77a-5c61713b5be7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Aguarl> <http://telicent.io/ontology/primaryName> "Aguarl" .
<https://starwars.com#grid_N15> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#sector_Mbandamonte> <http://telicent.io/ontology/primaryName> "Mbandamonte" .
<https://starwars.com#planet_Aguarl> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

