Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_HuttSpace> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_HuttSpace> .
<https://starwars.com#planet_Xolu> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Xolu> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#a2438a98-d05d-48c7-bc91-73586d953d64> .
<https://starwars.com#planet_Xolu> <http://www.w3.org/2000/01/rdf-schema#comment> "Xolu was a planet that was located within the Xolu system in Hutt Space, a region of the galaxy controlled by the Hutt species. It was connected to the worlds of Hollastin and Far Pando by the hyperlane called the Pando Spur. " .
<https://starwars.com#sector_HuttSpace> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Xolu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S13> .
<https://starwars.com#a2438a98-d05d-48c7-bc91-73586d953d64> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Xolu> <http://telicent.io/ontology/primaryName> "Xolu" .
<https://starwars.com#planet_Xolu> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HuttSpace> .
<https://starwars.com#a2438a98-d05d-48c7-bc91-73586d953d64> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Xolu"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_HuttSpace> <http://telicent.io/ontology/primaryName> "Hutt Space" .

