Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Tarmidia> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#28533386-8317-45e3-ad4d-435446fab403> .
<https://starwars.com#sector_Kailion> <http://telicent.io/ontology/primaryName> "Kailion" .
<https://starwars.com#planet_Tarmidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O13> .
<https://starwars.com#28533386-8317-45e3-ad4d-435446fab403> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tarmidia> <http://telicent.io/ontology/primaryName> "Tarmidia" .
<https://starwars.com#planet_Tarmidia> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Kailion> .
<https://starwars.com#planet_Tarmidia> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#sector_Kailion> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#28533386-8317-45e3-ad4d-435446fab403> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tarmidia"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Kailion> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Tarmidia> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

