Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_PaqualisIII> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_PaqualisIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L8> .
<https://starwars.com#2e5dadaf-6af6-4632-92de-bc0346c2600f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_PaqualisIII> <http://www.w3.org/2000/01/rdf-schema#comment> "Paqualis III, also known as Paqualis, was a terrestrial astronomical object in the Inner Rim, situated along the Hydian Way and positioned at the coordinates L-8 on the Standard Galactic Grid. Following a skirmish with the bounty hunters 4-LOM and Zuckuss, the smuggler Han Solo offered to pilot the pair to an outpost on Paqualis III, near the Bounty Hunters' Guild. " .
<https://starwars.com#planet_PaqualisIII> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2e5dadaf-6af6-4632-92de-bc0346c2600f> .
<https://starwars.com#2e5dadaf-6af6-4632-92de-bc0346c2600f> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Paqualis III"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_PaqualisIII> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_PaqualisIII> <http://telicent.io/ontology/primaryName> "Paqualis III" .

