Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Ban-Satir> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#planet_Ban-Satir> <http://telicent.io/ontology/primaryName> "Ban-Satir" .
<https://starwars.com#sector_CorporateSector> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Ban-Satir> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2f777cf5-bf7b-4ae8-bbf6-220287ee76ba> .
<https://starwars.com#sector_CorporateSector> <http://telicent.io/ontology/primaryName> "Corporate Sector" .
<https://starwars.com#planet_Ban-Satir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_CorporateSector> .
<https://starwars.com#2f777cf5-bf7b-4ae8-bbf6-220287ee76ba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2f777cf5-bf7b-4ae8-bbf6-220287ee76ba> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Ban-Satir"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Ban-Satir> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_CorporateSector> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Ban-Satir> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_S4> .

