Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#4f04d468-36fc-4cd4-9f81-98027b06bf1d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Horuz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Horuz> <http://www.w3.org/2000/01/rdf-schema#comment> "Horuz was a planet located in the galaxy's Outer Rim Territories. Shortly before the Battle of Scarif, Imperial forces were deployed to Horuz. In the lead-up to the Battle of Jakku in 5 ABY, Horuz was reportedly to still be in the thrall of some Imperial remnant or criminal syndicates or gangs. " .
<https://starwars.com#planet_Horuz> <http://telicent.io/ontology/primaryName> "Horuz" .
<https://starwars.com#planet_Horuz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L5> .
<https://starwars.com#sector_Atrivis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#4f04d468-36fc-4cd4-9f81-98027b06bf1d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Horuz"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Horuz> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4f04d468-36fc-4cd4-9f81-98027b06bf1d> .
<https://starwars.com#planet_Horuz> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Atrivis> .
<https://starwars.com#sector_Atrivis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Atrivis> <http://telicent.io/ontology/primaryName> "Atrivis" .

