Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Thorgeld> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Core> .
<https://starwars.com#d1a0983e-08a0-45d8-8f08-f3df757d6a8d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thorgeld> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L9> .
<https://starwars.com#planet_Thorgeld> <http://telicent.io/ontology/primaryName> "Thorgeld" .
<https://starwars.com#planet_Thorgeld> <http://www.w3.org/2000/01/rdf-schema#comment> "Thorgeld I, also known as Thorgeld, was a Core Worlds planet. The mansion of Fabritech, Inc. head Kvarn Mandel and his family was located on the planet, in the underground city of Fabrin. During the Galactic Civil War, the crew of the light freighter Dorion Discus visited Thorgeld I. Shortly after the freighter left the planet, the Imperial Customs Frigate Assessor attempted to board the vessel for a customs inspection, but the Dorion Discus eventually escaped into hyperspace. " .
<https://starwars.com#planet_Thorgeld> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#d1a0983e-08a0-45d8-8f08-f3df757d6a8d> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thorgeld"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Thorgeld> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d1a0983e-08a0-45d8-8f08-f3df757d6a8d> .

