Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Antemeridias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#planet_Antemeridias> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2eca5580-cad6-419c-81fc-56520e891171> .
<https://starwars.com#sector_Antemeridian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Antemeridias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Antemeridian> .
<https://starwars.com#planet_Antemeridias> <http://telicent.io/ontology/primaryName> "Antemeridias" .
<https://starwars.com#2eca5580-cad6-419c-81fc-56520e891171> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#2eca5580-cad6-419c-81fc-56520e891171> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Antemeridias"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Antemeridias> <http://www.w3.org/2000/01/rdf-schema#comment> "Antemeridias was the capital of the Antemeridian sector. Located in the Outer Rim Territories, it was located along the Perlemian Trade Route. " .
<https://starwars.com#planet_Antemeridias> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Antemeridian> <http://telicent.io/ontology/primaryName> "Antemeridian" .
<https://starwars.com#sector_Antemeridian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .

