Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d576e259-4d32-48ba-b7f3-881f8962f749> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Florn"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d576e259-4d32-48ba-b7f3-881f8962f749> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Florn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_T5> .
<https://starwars.com#sector_Pakuuni> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Florn> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Pakuuni> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#planet_Florn> <http://telicent.io/ontology/primaryName> "Florn" .
<https://starwars.com#sector_Pakuuni> <http://telicent.io/ontology/primaryName> "Pakuuni" .
<https://starwars.com#planet_Florn> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d576e259-4d32-48ba-b7f3-881f8962f749> .
<https://starwars.com#planet_Florn> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Pakuuni> .
<https://starwars.com#planet_Florn> <http://www.w3.org/2000/01/rdf-schema#comment> "Florn was an astronomical object with a dangerous environment located in the galaxy's Outer Rim Territories that was the homeworld of the Lamproid species. " .

