Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Lantillian> <http://telicent.io/ontology/primaryName> "Lantillian" .
<https://starwars.com#169368e7-c7c2-4e93-b814-0e170b675c9e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_Lantillian> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Lantillies> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_P8> .
<https://starwars.com#169368e7-c7c2-4e93-b814-0e170b675c9e> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Lantillies"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Lantillies> <http://telicent.io/ontology/primaryName> "Lantillies" .
<https://starwars.com#planet_Lantillies> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Lantillian> .
<https://starwars.com#planet_Lantillies> <http://www.w3.org/2000/01/rdf-schema#comment> "Lantillies was a world located in the galaxy's Mid Rim, at the confluence of the Perlemian Trade Route and the Randon Run. By 14 BBY, it hosted an Imperial base. When the corvette Carrion Spike was stolen from Imperial Governor Wilhuff Tarkin by a rebel cell and used to attack TaggeCo mining facilities on Lucazec, Imperial forces stationed at Lantillies and Centares were moved in triage redeployments to try and protect other Imperial assets that might be attacked. Vice Admiral Dodd Rancit—who was secretly one of those behind the attacks—later outlined fears to Galactic Emperor Sheev Palpatine that Lantillies itself might be a potential target since it was no longer as protected due to the redeployments; however, the base was never attacked by the corvette as the rebel cell was destroyed by Tarkin. Lantillies was the homeworld of Resistance bombardier Nix Jerd. " .
<https://starwars.com#sector_Lantillian> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#planet_Lantillies> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Lantillies> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#169368e7-c7c2-4e93-b814-0e170b675c9e> .

