Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_WetyinsColony> <http://www.w3.org/2000/01/rdf-schema#comment> "Wetyin's Colony was the main settlement on the moon Yavin 4 that was established when settlers traveled from the planet Setor to become farmers. In the months after the Battle of Endor, when Shara Bey and Kes Dameron settled in a new home there after completing their service in the Alliance to Restore the Republic. Having their own home had been their dream after being separated from one another, as well as their son, Poe, for much of the Galactic Civil War. Upon moving into their new home, the couple planted one of two remaining fragments of a Great Tree that had once dwelled in the heart of the Jedi Temple, after Bey and Luke Skywalker recovered them from the Galactic Empire. " .
<https://starwars.com#06c0426b-5b3e-464d-9856-4d65298386ea> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Wetyin's Colony"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_WetyinsColony> <http://telicent.io/ontology/primaryName> "Wetyin's Colony" .
<https://starwars.com#planet_WetyinsColony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_GordianReach> .
<https://starwars.com#planet_WetyinsColony> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#06c0426b-5b3e-464d-9856-4d65298386ea> .
<https://starwars.com#planet_WetyinsColony> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_Q5> .
<https://starwars.com#planet_WetyinsColony> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#06c0426b-5b3e-464d-9856-4d65298386ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_GordianReach> <http://telicent.io/ontology/primaryName> "Gordian Reach" .
<https://starwars.com#sector_GordianReach> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#sector_GordianReach> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .

