Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#planet_Quellor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N12> .
<https://starwars.com#290e2c3b-380d-4ed2-9430-d8e54ae1059b> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Quellor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Quellor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_Colonies> .
<https://starwars.com#290e2c3b-380d-4ed2-9430-d8e54ae1059b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Quellor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#290e2c3b-380d-4ed2-9430-d8e54ae1059b> .
<https://starwars.com#planet_Quellor> <http://telicent.io/ontology/primaryName> "Quellor" .
<https://starwars.com#planet_Quellor> <http://www.w3.org/2000/01/rdf-schema#comment> "Quellor was a terrestrial astronomical object located in the Quellor sector of the galaxy's Colonies region. It was situated along the Quellor Run, running to the planet Commenor. Quellor was the homeworld of a TIE pilot of the Galactic Empire's 204th Imperial Fighter Wing, whose family waved an Imperial flag from their apartment. However, it was taken by the New Republic by 5 ABY. While speaking to the New Republic Starfighter Commander Wyl Lark, the 204th pilot cited the capture as the reason the Imperial could not go home. " .
<https://starwars.com#planet_Quellor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .

