Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#f130fa16-e35d-4424-a17e-08118ca34507> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Malador> <http://telicent.io/ontology/primaryName> "Malador" .
<https://starwars.com#planet_Malador> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#f130fa16-e35d-4424-a17e-08118ca34507> .
<https://starwars.com#sector_Juvex> <http://telicent.io/ontology/primaryName> "Juvex" .
<https://starwars.com#planet_Malador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Juvex> .
<https://starwars.com#sector_Juvex> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Malador> <http://www.w3.org/2000/01/rdf-schema#comment> "Malador was an overpopulated urban planet located in the Mid Rim's Juvex sector. Cappabellor beetles were native to Malador, and it served as the homeworld of the aristocratic House Kellermin. Over time, Malador's ecosystem was ruined by industrial pollution, and many House Kellermin nobles left the planet for the nearby world of Resti Kel, leaving slaves and client species to work in Malador's factories. " .
<https://starwars.com#planet_Malador> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_L17> .
<https://starwars.com#planet_Malador> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#f130fa16-e35d-4424-a17e-08118ca34507> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Malador"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Juvex> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .

