Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Tynna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Tynna> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#25dde9f2-79f3-4e92-b51e-f72cdf8e03f6> .
<https://starwars.com#25dde9f2-79f3-4e92-b51e-f72cdf8e03f6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Tynna> <http://telicent.io/ontology/primaryName> "Tynna" .
<https://starwars.com#sector_Tynna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#planet_Tynna> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#sector_Tynna> <http://telicent.io/ontology/primaryName> "Tynna" .
<https://starwars.com#planet_Tynna> <http://www.w3.org/2000/01/rdf-schema#comment> "Tynna was a planet located in the galaxy's Expansion Region. During the Clone Wars, Tynna was occupied by the Separatists. Republic High Command sent at least one commando squad to the planet to coordinate with local freedom fighters, an operation that was somewhat successful. By the closing actions of the Clone Wars, it was represented in the Galactic Senate by Senator Streamdrinker. During the early stages of the Galactic Empire's reign, Streamdrinker represented the planet in the Imperial Senate until they were arrested by Imperial Intelligence one day after the creation of the Empire. " .
<https://starwars.com#25dde9f2-79f3-4e92-b51e-f72cdf8e03f6> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Tynna"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Tynna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_N14> .
<https://starwars.com#planet_Tynna> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Tynna> .

