Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#d7d5b552-27d2-449b-bbb8-482bdd2623ca> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Carlania"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#d7d5b552-27d2-449b-bbb8-482bdd2623ca> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#sector_HapesCluster> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_Carlania> <http://telicent.io/ontology/primaryName> "Carlania" .
<https://starwars.com#planet_Carlania> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#d7d5b552-27d2-449b-bbb8-482bdd2623ca> .
<https://starwars.com#sector_HapesCluster> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_InnerRim> .
<https://starwars.com#planet_Carlania> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Carlania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_HapesCluster> .
<https://starwars.com#planet_Carlania> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O9> .
<https://starwars.com#sector_HapesCluster> <http://telicent.io/ontology/primaryName> "Hapes Cluster" .
<https://starwars.com#planet_Carlania> <http://www.w3.org/2000/01/rdf-schema#comment> "" .

