Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#sector_Farstey> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_ExpansionRegion> .
<https://starwars.com#2c3d7957-2ed7-4332-9347-6d688f7d037a> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Thisspias"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#2c3d7957-2ed7-4332-9347-6d688f7d037a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_Thisspias> <http://www.w3.org/2000/01/rdf-schema#comment> "Thisspias was a rocky, temperate planet located in the galaxy's Expansion Region. It was the homeworld of the Thisspiasian species, including the Jedi Master Oppo Rancisis. The planet had been a member of the Galactic Republic for a very long time, and was also the site of many important battles, particularly during the Great Manifest Period. " .
<https://starwars.com#sector_Farstey> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Farstey> <http://telicent.io/ontology/primaryName> "Farstey" .
<https://starwars.com#planet_Thisspias> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#2c3d7957-2ed7-4332-9347-6d688f7d037a> .
<https://starwars.com#planet_Thisspias> <http://telicent.io/ontology/primaryName> "Thisspias" .
<https://starwars.com#planet_Thisspias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O8> .
<https://starwars.com#planet_Thisspias> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#planet_Thisspias> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Farstey> .

