Security-Label: nationality=GBR
Content-Type: application/n-triples

<https://starwars.com#grid_O19> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_MeryxMinor> <http://telicent.io/ontology/primaryName> "Meryx Minor" .
<https://starwars.com#fb5cba56-c1f0-4549-91f8-79c20bed68a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#4104b4e6-40b5-49d0-aa23-776604815e37> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Meryx Minor"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#grid_O19> <http://telicent.io/ontology/primaryName> "O19" .
<https://starwars.com#sector_Sujimis> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_OuterRim> .
<https://starwars.com#grid_O19> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#fb5cba56-c1f0-4549-91f8-79c20bed68a3> .
<https://starwars.com#fb5cba56-c1f0-4549-91f8-79c20bed68a3> <http://ies.data.gov.uk/ontology/ies4#representationValue> "O19"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#sector_Sujimis> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#planet_MeryxMinor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_O19> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#planet_MeryxMinor> <http://www.w3.org/2000/01/rdf-schema#comment> "" .
<https://starwars.com#4104b4e6-40b5-49d0-aa23-776604815e37> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#planet_MeryxMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_O19> .
<https://starwars.com#planet_MeryxMinor> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Sujimis> .
<https://starwars.com#sector_Sujimis> <http://telicent.io/ontology/primaryName> "Sujimis" .
<https://starwars.com#planet_MeryxMinor> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#4104b4e6-40b5-49d0-aa23-776604815e37> .

