Security-Label: sensitivity=Ultra
Content-Type: application/n-triples

<https://starwars.com#grid_R7> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalacticGridLocation> .
<https://starwars.com#planet_Abhean> <http://ies.data.gov.uk/ontology/ies4#hasName> <https://starwars.com#b2a86513-717a-40bf-bade-a8311d9a1020> .
<https://starwars.com#sector_Maldrood> <http://telicent.io/ontology/primaryName> "Maldrood" .
<https://starwars.com#planet_Abhean> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#sector_Maldrood> .
<https://starwars.com#planet_Abhean> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#Planet> .
<https://starwars.com#grid_R7> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#AGalaxyFarFarAway> .
<https://starwars.com#grid_R7> <http://telicent.io/ontology/primaryName> "R7" .
<https://starwars.com#sector_Maldrood> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GalaxySector> .
<https://starwars.com#sector_Maldrood> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#region_MidRim> .
<https://starwars.com#grid_R7> <http://ies.data.gov.uk/ontology/ies4#isIdentifiedBy> <https://starwars.com#0a1b9fd7-6d52-4d44-b9c0-6c7a06e37651> .
<https://starwars.com#planet_Abhean> <http://ies.data.gov.uk/ontology/ies4#inLocation> <https://starwars.com#grid_R7> .
<https://starwars.com#0a1b9fd7-6d52-4d44-b9c0-6c7a06e37651> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#GeoIdentity> .
<https://starwars.com#planet_Abhean> <http://telicent.io/ontology/primaryName> "Abhean" .
<https://starwars.com#0a1b9fd7-6d52-4d44-b9c0-6c7a06e37651> <http://ies.data.gov.uk/ontology/ies4#representationValue> "R7"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#b2a86513-717a-40bf-bade-a8311d9a1020> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ies.data.gov.uk/ontology/ies4#PlaceName> .
<https://starwars.com#b2a86513-717a-40bf-bade-a8311d9a1020> <http://ies.data.gov.uk/ontology/ies4#representationValue> "Abhean"^^<http://www.w3.org/2001/XMLSchema#string> .
<https://starwars.com#planet_Abhean> <http://www.w3.org/2000/01/rdf-schema#comment> "Abhean was an astronomical object located in grid square R-7 of the Standard Galactic Grid as part of the regions known as the Mid Rim Territories and the Slice. The super-hyperroute known as the Perlemian Trade Route connected it to Roche and the Besh Gorgon system. " .
